### ISSUE TITLE
Can't change pagination pageSize dynamically

### ISSUE THREAD

**Issue by jabirfth** [vmware/clarity#1006]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I want to change the datagrid page size dynamically, so when I choose a new size the datagrid's pagination must be updated as well.

### Actual behavior

Nothing happens, the datagrid preserve the old value for pageSize

### Reproduction of behavior

* here is a link to a Plunker project that reproduces this issues :
https://plnkr.co/apYsKe

### Environment details

* **Angular version:** 4.0.X , 2.0.X

* **Clarity version:** 0.9.0

* **OS and version:** Windows 10

* **Browser:** Chrome 57.0.x

**Comment by adityarb88** [comment]
@jabirfth: Thanks for raising this issue. We will take a look and get back to you soon.

**Comment by adityarb88** [comment]
@jabirfth: I took a look at this and found that when you change the select value, the value is updated as a string and page size only accepts number. That is why the update is not happening. I created a plunkr which makes sure that the value is a number and that fixes the issue: https://plnkr.co/edit/ABpr5c?p=preview

Let us know if this resolves the issue and feel free to reopen the issue if it still persists.

**Comment by jabirfth** [comment]
@adityarb88: yes you're right, when forcing the conversion to number, it works exactly as expected
Thank you.

**Comment by kodemasta** [comment]
I notice in https://plnkr.co/edit/ABpr5c?p=preview that the vertical size of the grid grows to support larger page values but does not shrink to support smaller page values. Try selecting 'All' then '10' and you will see the grid is very large and you have to scroll all the way down to page.  Is this a bug ?
