### ISSUE TITLE
Craft Library is not for newest Library version

### ISSUE THREAD

**Issue by ehausen** [vmware/clarity#1007]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Expected Craft Library to import without notices

### Actual behavior
Craft Library gives a notice that the imported library is for old version

### Reproduction of behavior
Install newest Skecth
Install newest Craft plugins
Download latest Clarity Craft Library
Import Clarity Craft Library

### Environment details
CRAFT LIBRARY (0.9.0)

See support article from Invision: [How to update a library created with Craft Library 1.0.5 and earlier to work with version 1.0.28 and later](https://support.invisionapp.com/hc/en-us/articles/115002209843)

**Comment by reddolan** [comment]
@ehausen looking into this right now. Thanks for the heads up

**Comment by reddolan** [comment]
Icebox for now while we get resolution on a resizing bug within Craft

**Comment by reddolan** [comment]
Will be pushing an update out for this. There have been many small updates to the UI Template that belong in the Craft Library even though the resizing attributes have a bug.

**Comment by reddolan** [comment]
Updates from the 0.9.9 UI Template were merged into Craft Library. This update fixes the versioning and adds some updates from #1077 
[Clarity-0.9.9.library.zip](https://github.com/vmware/clarity/files/1085278/Clarity-0.9.9.library.zip)

There is still the Craft Library bug with resizing which will be addressed in a future release.

**Comment by reddolan** [comment]
@ehausen can you test the attached zip and see if you are still getting the error?

**Comment by reddolan** [comment]
@ehausen There still seems to be an issue with the versioning on the Library. InVision is currently looking into this

**Comment by reddolan** [comment]
Here is a clean Library that isn't throwing the error anymore. Please replace the zip file on the site with this one.
[Clarity-0.9.9.library.zip](https://github.com/vmware/clarity/files/1088788/Clarity-0.9.9.library.zip)

**Comment by mathisscott** [comment]
We need to add the new link to the website.

**Comment by reddolan** [comment]
I am not sure what you mean by "add the new link". We need to replace the zip with the one above.

**Comment by mathisscott** [comment]
That is what I mean. Thanks for clarifying, @reddolan
