### ISSUE TITLE
Datagrid with one row shows an extra empty row

### ISSUE THREAD

**Issue by rishabhgandotra** [vmware/clarity#1010]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Datagrids that have one row should display one row only. There are scenarios when users will have one row in a datagrid. For instance when the admins are building their datacenter, they may have only one host and one datastore per host. They might have only one management network. For these use cases, we should support showing one row in the datagrid without showing an extra row that is empty.

### Actual behavior

The actual behavior is that the datagrid shows two rows, one of which is empty.

### Reproduction of behavior

Here's the plunker- https://plnkr.co/edit/r53VP2?p=preview

### Environment details

* **Angular version:** Not relevant

* **Clarity version:** Not relevant

* **OS and version:** Not relevant

* **Browser:** all

**Comment by adityarb88** [comment]
Hi @rishabhgandotra: I believe we have a min height on the `.datagrid-body` to make sure that we have enough space for the spinner. If we don't add a min-height, every time the spinner will be shown, the datagrid height will increase to 72px.

**Comment by rishabhgandotra** [comment]
Hi @adityarb88,

IMO, the minimum height of the datagrid should be equal to the space required to display one row plus the header and the footer. Can we reduce the size of the spinner so that we avoid showing an extra empty row?

**Comment by adityarb88** [comment]
@rishabhgandotra: I have tagged our UX team on this ticket and they will take a look at this and get back to you.

**Comment by rishabhgandotra** [comment]
Thank you, @adityarb88 appreciate your prompt response.

**Comment by steven-zou** [comment]
The pagination is weird. If you set pagesize n and there is only 1 or m (lesser than n) rows, datagrid will still reserve n-m rows hight. A large scale empty space is there, especially 1 row case. In my opinion, the height of datagrid should be auto-scaling with the data rows.

**Comment by adityarb88** [comment]
@steven-zou: I don't believe thats true. Also, this looks like a different issue. Could you please open a separate issue with a plnkr which replicates that behavior?

**Comment by reddolan** [comment]
@adityarb88 would it be possible to detect there is only 1 row and change the class to use the smaller spinner?

**Comment by youdz** [comment]
Regarding @steven-zou's comment, there is a summary of this discussion in my comment on https://github.com/vmware/clarity/issues/1114#issuecomment-311417716

The behavior you're describing as weird is the expected behavior, we implemented it after several complaints when the datagrid _was_ indeed dynamically adapting to the rows.
