### ISSUE TITLE
Modal dialog content has a scrollbar even when there is plenty of room to resize the dialog

### ISSUE THREAD

**Issue by vpvelikov** [vmware/clarity#1013]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When I downsize my browser window any opened modal dialog and its content should take as much as possible from the available area without showing a scrollbar. Scrollbar should be displayed only when the dialog is reaching the window/viewport borders.

### Actual behavior
The scrollbar is added although there is a huge amount of area to accommodate a new line of content.
Modal content size is limited to max-height:55vh. This is extremely restrictive when downsizing the browser or when I don't use a dialog title or dialog buttons.
See the attached screenshot from the Clarity documentation (page headers and footers hiding the issue are removed). Note there are only a few pixels not fitting and the dialog content is even measured against the whole viewport (not the black frame):
![55vh-dialog-content-limitation](https://cloud.githubusercontent.com/assets/29205644/26793156/a71737de-4a25-11e7-9255-2221fbab3049.png)

See also the plunk linked below.

### Reproduction of behavior
Forked plunk against latest 0.9.x: https://plnkr.co/N2VuWV
The scrollbar is added although there is only 1 line of text not fitting. At the same time the grey area is unjustifiably big for a modal dialog.
The same is reproducible with older versions (0.8.14)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.9.x, 0.8.14

* **OS and version:** all

* **Browser:** [all]

**Comment by jaffoneh** [comment]
![screen shot 2017-06-05 at 9 55 09 am](https://cloud.githubusercontent.com/assets/690949/26794056/193f192c-49d5-11e7-9c69-853928cc90e7.png)

@vpvelikov that's not what I am seeing (if I am understanding the issue correctly) when I re-size the modal. Attached above is a screenshot of what it looks like with "lots of text" and a resized window size.

Seems like you might be embedding the modal inside of a page instead of letting it occupy the space above the whole page as an overlay?

**Comment by vpvelikov** [comment]
@jaffoneh not sure how your screenshot was taken but it manifests a bug in itself - there is no scrollbar when the window size is that small so the long text is cut and cannot be viewed.

My use case is focused on the scenario when my dialog frame is fully visible (not cut as above) but it has no header and no footer (just content area like in my screenshot). Then:
1. The dialog content area does not take advantage of this extra space
2. The dialog content area is hardcoded to 55% of the available viewport (despite the lack of header/footer).
Essentially this needlessly increases the overlay experience while my dialog is in a situation with insufficient available space to display my content. This is bad UX even if I have a header and footer - 55% is too restrictive if I want to display anything more than a "Are you sure? Yes/No" dialog.

**Comment by adityarb88** [comment]
@vpvelikov: The screenshot was taken in Chrome and the scrollbars appear on hover. Your case looks like a custom case where you don't have a header and a footer in the modal so I think you would have to override the `max-height` at your end. The `max-height` is in place to enable scrolling and to keep a check on overflowing content. If the `max-height` is not present there is a chance that part of the modal will be clipped by the browser. For eg something like this could happen without the max-height on the `.modal-body`:

![image](https://cloud.githubusercontent.com/assets/1426805/26795181/8bd3aca6-49d9-11e7-811b-e55fc5062541.png)

**Comment by adityarb88** [comment]
@vpvelikov: For the second case where you need to display more content, have you changing the size of the modal to `lg` or `xl`? https://vmware.github.io/clarity/documentation/modals

**Comment by vpvelikov** [comment]
@jaffoneh @adityarb88: Thanks for the fast reply.
I don't question `max-height`'s existence - it needs to be there to prevent this overflow. I question its value: 55vh is way too restrictive, so you are giving a lot higher importance on the dark overlay around the modal than on my content. Please check my Plunker above to see why I think there is no balance between overlay and content.

I myself can always limit it if want 55vh but modal dialog writers would always prefer their content shown and the flexibility to design their own UX instead of complying with such restrictive hardcoded boundaries.
In addition it is not always possible to override the default `max-height` value: if I am designing an extensible system where external plugins can be written I would not know what dialogs plugin writers would have. So essentially this limitation would be exported from Clarity to my system.

Here is a screenshot with lg modal and demonstration how modals with lots of content are sized and  based on the viewport (and have a needless scrollbar because of a few pixels), not based on the black demostrational area:
![55vh-dialog-content-limitation1](https://cloud.githubusercontent.com/assets/29205644/26796417/26484bfe-4a32-11e7-9fb4-d33c3169e29c.png)

**Comment by adityarb88** [comment]
@vpvelikov: Thanks for the feedback. Let me tag our UX team on this issue. They will take a look at this and respond as soon as possible.

**Comment by vpvelikov** [comment]
@adityarb88 Thanks for the help! :)

**Comment by jaffoneh** [comment]
@vpvelikov as @adityarb88 mentioned that is a valid point and a valid design suggestion. We'll take a look :) CC @reddolan

**Comment by yenmade** [comment]
Chatted with Aditya on this issue and this is definitely a valid design suggestion. We're going to change to 70vh and reduce the max-height responsively, 55vh for the small and x-small breakpoints. We'll further test and adjust when this issue is in development. Thanks for your feedback @vpvelikov!
