### ISSUE TITLE
Thick icons in electron/angular

### ISSUE THREAD

**Issue by Sparkoff** [vmware/clarity#1015]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I am using angular in an electron application with Clarity as front-end framework (here is the seed I use : https://github.com/maximegris/angular-electron). I expected icons to look like same as in web mode (as electron is chromium based).

### Actual behavior
When I use icons (in header brand or nav, or anywhere else in the app), they are too much thick in dev mode. This is note the case when the angular part is run in web-mode or when the final electron app is built.
I doesn't see differences in DOM or style properties between electron dev-mode/built-mode/angular web-mode.

### Reproduction of behavior
I use angular-electron version 1.4.2 with electron version 1.6.10.
I simply clone this project, add Clarity following instructions (https://vmware.github.io/clarity/get-started#seedProjectAngular starting at step 2, skipping MutationObserver polyfill as I will never be on IE10) and simply use some sample from Clarity documentation.

### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.9.7

* **OS and version:** MacOS Sierra

* **Browser:** Electron app (Chromium based)

**Comment by adityarb88** [comment]
@Sparkoff: Wanted to check if the issue you raised is the same as this one: https://github.com/vmware/clarity/issues/969

**Comment by Sparkoff** [comment]
It looks like to be same (I didn't saw this issue).
But I am on angular 4.1.3 and electron 1.6.10, which solved the issue and icons are still odds. Removing @webcomponents/custom-elements doesn't make any differences.

**Comment by Shijir** [comment]
Hi @Sparkoff I don't believe the problem is occuring because of Clarity Icons. I have successfully installed `clarity-icons` in Electron in the past (multiple times) as I mentioned here in this issue #969.  It might be due to other packages that's causing SVG graphic elements to render improperly. I would also make sure to clear all the caches involved in SVG rendering.

**Comment by mathisscott** [comment]
@Sparkoff 
We haven't heard back on this issue in a while. Were you able to resolve it? I'm closing for now due to inactivity.

**Comment by briosheje** [comment]
I'm having the same issue -again-.

Despite it was apparently solved, I'm experiencing the thick icons issue again with clarity and electron.

I'm not sure where the problem resides, I'm trying to remove stuff from my package.json and trying to run the application again, but nothing seems to be solving the problem at all.

My package.json is:

```
{
  "productName": "Hextra Video Converter",
  "name": "hextraconverter",
  "version": "0.0.1",
  "description": "Convertitore video Hextra SRL",
  "main": "",
  "scripts": {
    "rebuild-sass": "npm run rebuild node-sass",
    "watch": "npm run watch:dev",
    "watch:dev": "webpack --watch --progress --profile",
    "build": "npm run build:dev",
    "build:dev": "webpack --progress --profile --config webpack.config.js",
    "build:prod": "webpack --progress --profile --config webpack.config.prod.js",
    "package": "node package.js",
    "make-installer-windows": "node mk-win-installer.js",
    "clean-afterbuild": "node clean_sources.js",
    "package-all": "npm run build:prod && npm run package -- --all",
    "package-windows": "npm run build:prod && npm run package -- --platform=win32",
    "package-linux": "npm run build:prod && npm run package -- --platform=linux",
    "package-apple": "npm run build:prod && npm run package -- --platform=darwin",
    "installer-windows": "npm run package-windows && npm run make-installer-windows",
    "electron": "electron src/app",
    "webpack-test": "webpack --config webpack.test.js --progress --profile",
    "test": "karma start",
    "angular_doc_combodoc": "compodoc -p ./tsconfig.json -s"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "Hextra SRL",
  "license": "MIT",
  "homepage": "",
  "dependencies": {
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/platform-server": "4.1.3",
    "@angular/router": "4.1.3",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.1",
    "@webcomponents/custom-elements": "^1.0.0",
    "animate.css": "3.5.2",
    "clarity-angular": "0.10.0-alpha.5",
    "clarity-icons": "0.10.0-alpha.5",
    "clarity-ui": "0.10.0-alpha.5",
    "copy-webpack-plugin": "^4.0.1",
    "core-js": "^2.4.1",
    "electron": "1.6.10",
    "express": "4.15.3",
    "ffmpeg": "0.0.4",
    "ffprobe": "1.1.0",
    "fluent-ffmpeg": "2.1.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "mutationobserver-shim": "^0.3.2",
    "rxjs": "^5.2.0",
    "webpack-target-electron-renderer": "^0.4.0",
    "yargs": "^8.0.2",
    "fs-plus": "3.0.1",
    "zone.js": "0.8.5"
  },
  "devDependencies": {
    "@types/fluent-ffmpeg": "2.1.1",
    "@types/hammerjs": "^2.0.33",
    "@types/jasmine": "^2.2.34",
    "@types/moment-timezone": "^0.2.32",
    "@types/node": "^7.0.1",
    "@types/source-map": "^0.5.0",
    "@types/uglify-js": "^2.0.27",
    "@types/webpack": "^2.0.0",
    "compodoc":"0.0.41",
    "colors":"1.1.2",
    "angular2-template-loader": "^0.6.0",
    "awesome-typescript-loader": "^3.0.0-beta.18",
    "codelyzer": "^2.0.0-beta.2",
    "css-loader": "^0.28.0",
    "electron-installer-windows": "0.2.0",
    "electron-packager": "^8.1.0",
    "es6-promise-loader": "^1.0.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.0",
    "fs-plus": "3.0.1",
    "imports-loader": "^0.7.0",
    "istanbul-instrumenter-loader": "^2.0.0",
    "jasmine-core": "^2.4.1",
    "json-loader": "^0.5.4",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.0.0",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.0.0",
    "karma-phantomjs-launcher": "^1.0.0",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "2.0.2",
    "node-sass": "^4.0.0",
    "phantomjs-polyfill": "0.0.2",
    "phantomjs-prebuilt": "^2.1.7",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "remap-istanbul": "^0.9.0",
    "rimraf": "^2.5.2",
    "sass-loader": "^6.0.1",
    "source-map-loader": "^0.2.1",
    "style-loader": "^0.16.1",
    "svg-url-loader": "^2.0.0",
    "to-string-loader": "1.1.5",
    "ts-helpers": "^1.1.1",
    "tsconfig-lint": "^0.12.0",
    "tslint": "^5.0.0",
    "tslint-loader": "^3.2.0",
    "typescript": "~2.1.5",
    "url-loader": "^0.5.7",
    "webpack": "2.3.3",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-dev-server": "2.4.1",
    "yargs": "^8.0.2"
  },
  "engines": {
    "node": ">= 4.2.1 <= 6",
    "npm": ">= 3"
  }
}
```

Note: I did mention this issue some time ago here: https://github.com/vmware/clarity/issues/969

however the fix seems to not be working anymore, there must be something behind this issue at this point, since even by cloning the original project I get the thick icons (while in the original cloned one I don't).

**Comment by mathisscott** [comment]
@briosheje 
Do you have any way to inspect the CSS styles in your electron app? There may be some styling introduced by one of these packages that is affecting the icons.

Barring that, it may be worth upgrading electron to 1.7.2+ because there appears to be a chromium+electron issue that was resolved there...

**Comment by briosheje** [comment]
@mathisscott Sure, I can inspect anything needed, I will upload everything today's afternoon though, since I don't have my mac with me right now.

I will also try to update to Electron 1.7.2+ at this point, maybe it's just enough to solve the issue :).
