### ISSUE TITLE
Disable the row selection according to property of a record in Clarity datagrid.

### ISSUE THREAD

**Issue by rangagv** [vmware/clarity#1018]
Clarity datagrid having a multi selection, should have the ability to disable row selection according to some fields of the record. We have a use case where, all the objects are listed in the datagrid. User can select some records in the grids and perform some action on the selected item. There are some objects on which user does not have permission to perform the action. In this case, user should not have capability to select those particular rows. 

**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
If clarity datagrids have the capability to enable/disable the row selection according to a particular filed of object, user will have proper indication that he is able to perform some action on those objects.

### Actual behavior
Now there is no way, that programmatically we can disable the check box or radio box selection of the clarity datagrid row. Should have some thing like "clrDgSelected" for enable/disable the row.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:0.9

* **OS and version:Mac

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@rangagv Thanks for the feedback. I have tagged our UX team on this issue. They will take a look and respond as soon as possible.

**Comment by jaffoneh** [comment]
@rangagv quick question: when you say selection, are you using checkboxes for selection?

**Comment by rangagv** [comment]
@jaffoneh Yes, we are using the check box selections.

**Comment by juanmendes** [comment]
Just to clarify, what we are looking for is a `clrDgSelectable` attribute on rows. I believe this should work for both checkbox or regular selection.

**Comment by rangagv** [comment]
clrDgSelectable works for selection/unselection, but I requested to enable/disable of selection for rows.

**Comment by juanmendes** [comment]
@rangagv I think I see what you mean.

Let me try it: you are saying that `clrDgSelectable` sounds like a row cannot be selected (but could be deselected)? However,  what you want is the ability to set a property that means a row cannot change its selection state from the UI, whether it's selected or unselected, it will remain that way.

If that's what you are saying, I do agree, and the name I proposed is not very accurate. Maybe `clrChangeSelectionStateEnabled` is a better name, meaning the selection state cannot be changed through the UI.

**Comment by rangagv** [comment]
@juanmendes Yes, looking for something like clrChangeSelectionStateEnabled

**Comment by mfp22** [comment]
What is the status on this?

**Comment by kalpeshhpatel** [comment]
Hey guys, do we have any update on this?

Thanks

**Comment by mathisscott** [comment]
@mfp22 and @kalpeshhpatel 
This is not in our near-term pipeline. But it is marked as `help wanted` and might not be too challenging for an external contribution if either of you feel like taking it on.

**Comment by msoni11** [comment]
@juanmendes: **clrDgSelectable** attribute on row will work pretty well until we click on selectAll checkbox which iterate all items in selection provider and we couldn't get value of **clrDgSelectable**  under that provider. It could save our time if items(real data) contain disabled key with boolean value but this is not a good practice.

**Comment by jkuo-vmware** [comment]
@gnomeontherun 
I have an additional use case I'd like to document and share:
- As a user, I see a datagrid with rows of information, and I'd like to make a selection. However, the system only allows me to select N number of rows, after which, the remaining rows are shown as disabled and I can no longer select additional rows.

Example:
The system only allows a user to select 5 clusters in a datacenter at a time to perform upgrades. As a user, I want to see a list of all of my clusters, with additional columns providing information about my clusters to help me decide which to upgrade. I see there are 10 clusters in the list. As I go about selecting clusters, when I hit 5 selected clusters/rows, the remaining rows indicate that I can no longer select any more.

Implications:
- The Select All checkbox at the top of the datagrid either no longer applies or would need to modify its behavior to not select over the set number of rows.
- Either checkboxes or entire rows would need to show as disabled once N number of rows are selected.
- Accessibility considerations for how this type of information would be conveyed.

Potential Non-Essential Enhancements:
- Total number of checked items could be shown against max number of items allowable (bottom left corner of datagrid): "4 / 5 checked"

![image](https://user-images.githubusercontent.com/45468275/60469043-502c4880-9c10-11e9-9fd5-1959d61ff999.png)
