### ISSUE TITLE
[DOCS] Documentation for Vertical Navigation

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1019]
Create documentation for the vertical navigation component in new layout style.

**Comment by reddolan** [comment]
[InVision Inspect](https://vmware.invisionapp.com/d/main/#/console/10015910/236378612/inspect)
[Vertical-Navigation.sketch.zip](https://github.com/vmware/clarity/files/1056412/Vertical-Navigation.sketch.zip)
