### ISSUE TITLE
[ bug ]  Error  loading "clarity-angular" in app.module.js

### ISSUE THREAD

**Issue by sbacem** [vmware/clarity#102]
I have installed clarity in   [quickstart angular ](https://github.com/angular/quickstart)
But i have thise error  loading "clarity-angular" in app.module.js

index.html
```
<!DOCTYPE html>
<html>
  <head>
    <title>Angular QuickStart</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="./node_modules/clarity-icons/clarity-icons.min.css">
    <script src="./node_modules/mutationobserver-shim/dist/mutationobserver.min.js"></script>
    <script src="./node_modules/@webcomponents/custom-elements/custom-elements.min.js"></script>
    <script src="./node_modules/clarity-icons/clarity-icons.min.js"></script>    
    <link rel="stylesheet" href="./node_modules/clarity-ui/clarity-ui.min.css"> 
    

    <!-- Polyfill(s) for older browsers -->
    <script src="node_modules/core-js/client/shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>
  </head>

  <body>
    <my-app>Loading...</my-app>
  </body>
</html>

```
app.module.ts
```

import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ClarityModule } from 'clarity-angular';

import { AppComponent }  from './app.component';

@NgModule({
  imports:[ 
      BrowserModule,
      ClarityModule
    ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }


```
link of all code [https://ide.c9.io](https://ide.c9.io/sakli_bacem/proejct-clarity)

**Comment by sbacem** [comment]
I fixed it 
it should be added clarity-angular in systemjs.config.js

```
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
       ......
      'clarity-angular': 'npm:clarity-angular',
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
     .....
      rxjs: { main: 'Rx.js', defaultExtension: 'js' },
      'clarity-angular' : { main: './index.js', defaultExtension: 'js' }
    }
  });
})(this);
```
it must change also 
`rxjs: { defaultExtension: 'js' },`
to.
`rxjs: { main: 'Rx.js', defaultExtension: 'js' },`

I think is better to set in Install Clarity

**Comment by jaffoneh** [comment]
@jeeyun do we want to document this in the Wiki/FAQ to make sure the resource is available for others to take a look?

**Comment by jeeyun** [comment]
I have added the steps to our [README](https://github.com/vmware/clarity/blob/master/README.md). Do we see a value in still adding this info elsewhere (i.e. wiki)?

**Comment by jaffoneh** [comment]
@jeeyun adding it to README should be good enough. No need to add to the wiki as well.

**Comment by jaffoneh** [comment]
Closing this based on the previous comment.

**Comment by llawall** [comment]
This fix would be useful on this page too: https://vmware.github.io/clarity/get-started/ I'm not sure if this is what you are calling the wiki though? 

The clarity project 'wiki' link redirects back to the project page.

**Comment by jaffoneh** [comment]
@llawall it should be in the README right here: https://github.com/vmware/clarity/blob/master/README.md

**Comment by llawall** [comment]
Thanks @jaffoneh I saw it there. My point was that I followed the instructions on the link in my last comment which are very similar to the README but had the problem described here. I was wondering if you'd consider updating the get-started page too?

**Comment by jaffoneh** [comment]
@llawall based on @jeeyun's comment. README should've been updated based on the issue (to provide more info). However, we should take into account to update get started as well. Thanks for the feedback! / cc @jeeyun
