### ISSUE TITLE
Feature request:  method for indicating data is loading in a datagrid

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#1022]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Proposed behavior
Add a way to show that data is being loaded for a specific datagrid, to distinguish the "data pending" state from the "no data" state (covered by the placeholder).  

There's two possible ways this could be done: 

* A `<clr-dg-spinner>` directive which would show a spinner as well as optional text in the body of an empty datagrid, similar to the way that `<clr-dg-placeholder>` works now.  
* Making `<div class="progress top">` work in datagrids, the same way that it already works in cards.

I don't know which one is preferable design-wise.

**Comment by adityarb88** [comment]
@amellnik: We do have a spinner in the datagrid to indicate that the data is loading. https://vmware.github.io/clarity/documentation/datagrid/server-driven Is this what you are looking for?

**Comment by adityarb88** [comment]
You will have to search for the `[clrDgLoading]` directive on that page.

**Comment by amellnik** [comment]
Ah whoops, I missed that since I'm not using a server-driven datagrid.  It works in my case, although I would prefer that it sat in the same location as the placeholder and didn't overlay the entire grid (but I guess that's a separate issue).  Thanks!

![image](https://user-images.githubusercontent.com/7132414/26900953-dd5ae408-4b88-11e7-824f-0a62391f0b86.png)
