### ISSUE TITLE
[NG] Textarea Component

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1023]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Textarea component should have all the common functionalities of `Textarea` built into the angular component. It should also use the popover directive to position the tooltip so it's not clipped off.

### Actual behavior

Textarea component does not exist

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [All]

**Comment by gnomeontherun** [comment]
Going to close this as the forms epic has this new component included.
