### ISSUE TITLE
Data Grid Single Row Action not showing up on initial page load.

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#1025]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The three dots for the action menu should appear on initial page load when datagrid is displayed after data is returned from server

### Actual behavior

The page loads with the datagrid not displaying the overflow actions button. If I then click anywhere on the page, they show up.

### Reproduction of behavior

https://plnkr.co/edit/8VYkPejZOt7j97B14zC1?p=preview

**Comment by adityarb88** [comment]
I think this is a this issue was already filed here: https://github.com/vmware/clarity/issues/744
Could you please subscribe to that issue for more updates? Closing as duplicate.

**Comment by jacobbutton** [comment]
Yea, that looks like it. Sorry, I searched for previous reports of it but didn't see that one.
