### ISSUE TITLE
Icon downloads don't match development implementation

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1026]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
An icon that is downloaded from our site should match the way it gets implemented in code.

### Actual behavior
A downloaded SVG icon when implemented in Sketch doesn't have the whitespace around it that shows when an icon is implemented on a page in code. This is causing conflicts between design and development implementation of icons.

### Reproduction of behavior
![clarity-icon-issue](https://user-images.githubusercontent.com/1858226/26941287-963c85f2-4c43-11e7-8f43-1a2fe79b54fb.png)

- This shows the disparity in icon implementations
- the double caret icon is an example of the issue, but it is prevalent across all icons
- each icon on the left is the downloaded SVG icon
- the icon to its right is the implemented icon

### Environment details

* **Clarity version:** 0.9.7

**Comment by uxmariano** [comment]
+1 We've been dealing with this issue at NSX and would love to see it fixed!

**Comment by mathisscott** [comment]
We have discussed internally how to solve this and we believe the best solution is to add a transparent "frame" rectangle to the exported icons in the build. The frame should be 36 x 36.
