### ISSUE TITLE
how to refresh wizard 0.8  

### ISSUE THREAD

**Issue by MuruganDell** [vmware/clarity#1029]
Hi Clarity Design Team ,
         We are using clairty design  used for vsphere web client  ,wizard 0.8 version cann't able to refresh onclick based  ,how to achive this without page load  ,Let me know

**Comment by adityarb88** [comment]
@MuruganDell: Not exactly sure what the question is. Could you please provide a plnkr which demos what you are trying to do? Plnkr template for 0.8: https://plnkr.co/8TwwdL

**Comment by jaffoneh** [comment]
@MuruganDell can you please file a new issue with a plnkr as well as use the template supplied in filing an issue?

The issue above is difficult to understand and does not use our issue template that you can see by default when filing an issue on our GitHub repo. Closing for now based on the above.
