### ISSUE TITLE
Where is the documentation for angular components? 

### ISSUE THREAD

**Issue by sdemurjian** [vmware/clarity#103]
I don't see the documentation for angular components anywhere; am I missing something here?

I would also expect the full source code for each example to be available like most other component libraries.

BTW, a gitter would be nice for general usage questions.

**Comment by jaffoneh** [comment]
@sdemurjian depending on the component you're looking for, the Angular documentation is there in that component's page. For example: if you go to dropdowns you can see that part of the component is built on top of Angular (or that dropdown is an Angular 2 component)

<img width="905" alt="screen shot 2016-11-18 at 7 05 51 am" src="https://cloud.githubusercontent.com/assets/690949/20434659/b079e28c-ad5d-11e6-82ae-454464557208.png">

and then right there in the page you can get the HTML/CSS documentation *then* the Angular Component documentation (there is a heading called "Angular Component" in there).

https://vmware.github.io/clarity/documentation/dropdowns

I'd love to know more about your experience or why were you not able to find the documentation. Part of our goal is to improve our documentation as we go so we appreciate the feedback!

**Comment by sdemurjian** [comment]
Thanks for the quick reply. The issue I was having is that for example the header page does not have `[clr-nav-level]` or even the components like `<clr-header>` listed. I was only aware the components existed from looking through the source code.

https://vmware.github.io/clarity/documentation/header

**Comment by adityarb88** [comment]
@sdemurjian: The responsive navigation is documented on this page: https://vmware.github.io/clarity/documentation/navigation under the Responsive Navigation section since it involves using both `<clr-main-container>` and `<clr-header>` with `clr-nav-level`. I will get this feedback back to the team on finding the docs for responsive navigation to check how we can document this better so that its easier to find.

**Comment by sdemurjian** [comment]
@adityarb88 Oops, I definitely missed that section. Sorry about that!

**Comment by jaffoneh** [comment]
Pinging @gachappell to make sure we take this into account in our documentation. Closing this bug based on the previous comment!

**Comment by gdm85** [comment]
Those icons do not exist anymore in current documentation pages. Is there a new Angular documentation page?

**Comment by hippee-lee** [comment]
@gdm85 - this is a very old issue. The website and documentation has changes since then. 
If there is an issue with the current documentation or website please open a new issue.
