### ISSUE TITLE
Alerts : Update [(clrAlertClosed)] value when closing alert with closing action from [clrAlertClosable]

### ISSUE THREAD

**Issue by samdidos** [vmware/clarity#1030]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
When I close an alert which has two-way data binding [(clrAlertClosed)], I expect that the default closing action set by [clrAlertClosable]="true" could change the value set in [(clrAlertClosed)] to false.
### Actual behavior
The closing action makes the alert disappear, but don't change the binded value.

### Reproduction of behavior

See in this [Plunker](https://embed.plnkr.co/pLsTb6VuGXlAku6nekEd/)

### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.9.8

* **Browser:** all

**Comment by adityarb88** [comment]
@samdidos: It does work for me: https://plnkr.co/edit/jPBkSXBo23TXPPGhmPtM?p=preview I think you are binding to `!showAlertSuccess` which is causing the issue. Feel free to reopen the issue if you are still facing it.

**Comment by samdidos** [comment]
Ok I see, thanks a lot!
