### ISSUE TITLE
Advanced Features of Datagrid are not working on 0.9.8

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1033]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Datagrid features should work as demonstrated in the sample codes in the documentation.

### Actual behavior
I tried using the Datagrid component but some features are not working anymore like the selection and single row action. Selection/checkboxes are not showing up. Sames goes with the single row action.

I tried setting the [(clrDgSelected)] to the array object, the checkbox selection works but when I uncheck the checkbox, the record is deleted.

### Reproduction of behavior
Please use the plunker below for reproduction:
[https://plnkr.co/edit/P8SyXQ?p=preview](https://plnkr.co/edit/P8SyXQ?p=preview)

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by TechRazor** [comment]
@whizkidwwe1217 I made some changes to your plunker and I think I have it working how you want.

https://plnkr.co/edit/oNkIsEjiTZu2evkBJ8ZJ?p=preview

Single selection requires a different two-way binding then normal multi-selection
`<clr-datagrid [(clrDgSingleSelected)]="singleSelected">`

Selection requires a new variable for selected items, in your plunker you used the array of data instead. When you unselected an item, it removed it from the array itself.

The last example for Single Row Action needed the action overflow moved to the row component.

Please see the updated plunker and let me know if that answers your questions.

**Comment by whizkidwwe1217** [comment]
@TechRazor  Thanks for the quick response. I got it working using the updated plunker. I was only up to the multiple selection. The only thing I was missing is the **selected** array variable. Thanks for the help. I'll really appreciate it. :-)
