### ISSUE TITLE
clrWizardPageOnCommit is fired twice for the last page of wizards with clrWizardPreventDefaultNext = true

### ISSUE THREAD

**Issue by itaneva** [vmware/clarity#1034]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

clrWizardPageOnCommit should be fired only once for each page during navigation.

### Actual behavior

I have a clarity wizard, which requires complex validation on each page. I have implemented that by setting clrWizardPreventDefaultNext=true and performing the validation in the clrWizardPageOnCommit handler.

On the last page of the wizard, the handler is called twice, instead of just once. See the errorneous part of wizard-navigation.ts:

        if (isFinish || isDangerFinish) {
            // mark page as complete
            this.pageCollection.commitPage(currentPage);
            this._wizardFinished.next();
        }

        if (this.wizardHasAltNext) {
            this.pageCollection.commitPage(currentPage);

            if (isNext || isDangerNext) {
                this._movedToNextPage.next(true);
            }
            // jump out here, no matter what type we're looking at
            return;
        }

The last page falls in both of the cases, so the event is emitted twice.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.1.X

* **Clarity version:** 0.9.6

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Thanks for tracking down the issue in the logic, @itaneva . We will prioritize this issue when our schedule opens up. Based on your analysis, however, I think all we would need to tackle this issue is a test in the unit tests for the wizard and an extra check on the first conditional that ensures the extra `onCommit` is not fired.
