### ISSUE TITLE
Add monospace font to Clarity UI and the docs

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#1037]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Documentation should define a common typographical standard for items requiring a monospaced font.  For example, code editors or log viewers.

### Actual behavior
Typography section only references Metropolis font which is not monospaced

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/typography

**Comment by reddolan** [comment]
Recommendation for monospaced fonts for Clarity:
`14px Consolas, Monaco, Courier, monospace`

Will work on writing up copy for the site.

**Comment by reddolan** [comment]
(added to the bottom of Text Styles)
![image](https://user-images.githubusercontent.com/1858226/27646740-0f8f32fa-5bef-11e7-94f4-1d2c33cf8920.png)

(added below "The Metropolis Font")
### Monospaced Fonts
A monospaced font is used to display code or system-type messages like in a terminal or console. Clarity uses `14px Consolas` with fallbacks to `Monaco, Courier`, and then `monospace`.
![image](https://user-images.githubusercontent.com/1858226/27646819-4bda24e0-5bef-11e7-9651-be3904ca5e0d.png)
