### ISSUE TITLE
 Icons missing in the download set

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#1038]
**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
All icons shown on the iconography page should be included in the svg download. 

### Actual behavior
The icons that were added in GH #778 are missing from the svg download set.

**Comment by mathisscott** [comment]
@lil-kim 
These are now showing up as expected in the all-shapes download.
