### ISSUE TITLE
clr-tabs should support lazy initialization of tab content 

### ISSUE THREAD

**Issue by arnaudova** [vmware/clarity#1042]
```
[ ] bug
[X ] feature request
[ ] enhancement
```

### Expected behavior
While defining the tabs and tab contents (using the clr-tabs) we would like to define:
1. Tab content as a template to be eagerly loaded
2. Tab content as a template/template url/component to be lazy loaded as soon as the user opens the tab for the **first time**.

### Actual behavior
1. Is available
2. Is not available, but is essential for some of the use cases

**Comment by mathisscott** [comment]
This should be covered by the implementation of #898 

Leaving open for now, yet linked to that issue, so that we can verify it works after #898 is completed
