### ISSUE TITLE
On 'X' click, clrModalOpen attribute not toggling

### ISSUE THREAD

**Issue by CFourPO** [vmware/clarity#1047]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
#1020 - Similar issue here
When `X` is clicked on modal, attribute bound to `clrModalOpen` should change to `false`.

### Actual behavior

Value bound to `[clrModalOpen]` does not change and remains `true`. Can implement simple workaround by leveraging `OnChanges` and manually setting the `basic` value, clicking the `x` should probably toggle that value.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

[plunkr](https://plnkr.co/edit/BWBRPvnAJo42IDRfA2TV?p=preview)

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.0

* **OS and version:** 

* **Browser:** Chrome 60.0.3112.24

**Comment by adityarb88** [comment]
@CFourPO: Sorry but I am not able to understand the question correctly. If you don't use the `[()]` (banana in a box syntax), you would have to manually set the basic value like you mentioned in the issue above. So basically you need to update your function to this:

```
onChange(event) {
    console.log(event, this.basic);
    this.basic = event;
  }
```

The `[()]` syntax will automatically set the value for you but if you dont use that syntax you would have to update the value manually. Here is a plnkr which uses a setter to demonstrate that: https://plnkr.co/edit/89zEwHhT57pi09oeLcFL?p=preview

**Comment by adityarb88** [comment]
Closing this issue based on the above comment but please feel free to reopen the issue if you feel that its still not resolved. Thanks!
