### ISSUE TITLE
Doc enhancement: Show Flat Small buttons in Sizes section

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#1048]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
When reading docs about buttons, the Sizes section should reference a flat button as an example.

### Actual behavior
The only reference to a small version of flat button is in the flat buttons themselves, and it's easily overlooked.

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/buttons

**Comment by Shijir** [comment]
Fixed in https://github.com/vmware/clarity/commit/647a63906a788c51bc2a940420be45559023bc9a
