### ISSUE TITLE
Fixed width sidenav

### ISSUE THREAD

**Issue by mooreaa** [vmware/clarity#1049]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ x ] enhancement
```

### Expected behavior
Side nav menu should at least have option not to scale horizontally (fixed width). Right now, there is word warp occurring on nav elements with long text. Seems like it would be better design to allow fixed width menus. 

### Actual behavior
https://vmware.github.io/clarity/documentation

### Reproduction of behavior
https://vmware.github.io/clarity/documentation

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by lil-kim** [comment]
Hi @mooreaa,
Can you clarify?
We currently have fixed with for the side nav. The width can be changed through CSS. 
Are you asking for a resizable width side nav? ie: the user can drag it to make it wider?

**Comment by hippee-lee** [comment]
This issue hasn't been updated in a while. If you have more details that clarify the questions please re-open and add in the details that clarify the changes needed here.
