### ISSUE TITLE
the svg download of icons is missing some 

### ISSUE THREAD

**Issue by lweitzman** [vmware/clarity#1052]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

the svg download should provide access to all icons shown on the clarity documentation iconography page.

### Actual behavior

the svg download is missing the block and block-group icons

### Environment details
https://vmware.github.io/clarity/documentation/iconography

**Comment by mathisscott** [comment]
@lweitzman 
I see these now under "technology-shapes" in the download.
