### ISSUE TITLE
Expand button in datagrid should have type="button" specified

### ISSUE THREAD

**Issue by clementcur** [vmware/clarity#1061]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If I include a datagrid inside of a form, clicking an expand caret should not submit the form.

### Actual behavior
Clicking an expand caret submits the form. This is because the "type" property of the element defaults to "submit", as per the w3c spec. In order to prevent this behavior, all non-submitting form buttons should include type="button".

https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element

### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.9.7

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@clementcur: This fix was already released in 0.9.8: https://github.com/vmware/clarity/pull/1004
Please upgrade and let us know if that works.
