### ISSUE TITLE
Input Field and Label Color Inconsistency

### ISSUE THREAD

**Issue by nbewley** [vmware/clarity#1066]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Expected clarity website and Clarity template to use the same color values for input fields and labels.

### Actual behavior
The clarity design website uses #000000 for input fields and labels, whereas the Clarity sketch template ("clarity-template-0.9.0.sketch") uses #565656.

### Reproduction of behavior
Clarity Website:
<img width="1159" alt="website" src="https://user-images.githubusercontent.com/29443623/27159975-a346e2a6-5125-11e7-9610-fe2ff4acca50.png">

Clarity Template:
<img width="958" alt="template" src="https://user-images.githubusercontent.com/29443623/27159977-ab20e3aa-5125-11e7-82c6-b5e07f68548e.png">

**Comment by reddolan** [comment]
Changes made and merged into #1077
