### ISSUE TITLE
navService.goTo() isn't working propperly.

### ISSUE THREAD

**Issue by malkoto1** [vmware/clarity#1068]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When using the wizard's navService's goTo() method everything should work as documented

### Actual behavior
the navService.goTo() method has two problems:
1. When the page's ID is used as a first parameter of the method and not a WizardPage object, the method is silently failing wthout going to the specified page. It works well if a WizardPage object is provided.
2. If the secont parameter (lazyComplete) is set to true, the previous steps aren't being marked in the sideNav as completed.

### Reproduction of behavior
No plunkr, but a standard use scenario:
1. Click a button which calls a method with the following code in it:
            this.wizard.navService.goTo([thePageObject], true);
            this.wizard.open();

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.7

* **OS and version:** Mac OS

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Hi @malkoto1 

The line in your example should be throwing a JS error.

`this.wizard.navService.goTo(, true);`

My guess is that you are not passing the id with the expected prefix `clr-wizard-page-` but without a Plunkr I cannot be sure.

If that is not the case, try calling `this.wizard.open()` and then your goTo statement.

If goTo lazyComplete were not working, several tests on our build would be failing.

**Comment by malkoto1** [comment]
Hi, I have put up a quick plunkr: https://plnkr.co/edit/xYBrInvF0jZxCx7SgB6f?p=preview

You can play with it and test to access a current page by passing the page object and by passing a string.

**Comment by mathisscott** [comment]
@malkoto1 
Thanks for making that plunkr. Once I could see what you were trying to do it is an easy fix.

You have confused ids and refs in an Angular template. You can use either one. I prefer refs.

The following plunkr shows you how to use both. And they both work.

https://plnkr.co/edit/qpQwuV?p=preview
