### ISSUE TITLE
Minor: Increase space above first H3 on components pages ~ 24px on component pages

### ISSUE THREAD

**Issue by RobPatten** [vmware/clarity#107]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior

The H3 (i.e. "Using 'Blat") should be clearly discernible, especially after clicking  the Design Guidelines link.  
### Actual behavior

Heading is crowded and pushed to top.
It's difficult to see.

### Reproduction of behavior

https://vmware.github.io/clarity/documentation/datagrid#guidelines
### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
0.7.0
* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by jaffoneh** [comment]
@RobPatten could you provide more details, I am unable to figure out what is meant here in this bug (unless it already got fixed).

**Comment by jaffoneh** [comment]
@RobPatten seems like you edited my message :) This seems like a minor web change (not core to typography) so I am going to close this issue considering we're looking at changes to the spacing on the website and we can address it as we make those changes. Let me know if you'd like to discuss reopening this.
