### ISSUE TITLE
Buttons in dropdown  are flat instead of solid

### ISSUE THREAD

**Issue by likwifi** [vmware/clarity#1070]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Dropdown button styles should be same as other buttons

### Actual behavior

Buttons in dropdown  are flat instead of solid

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
0.9.8

* **OS and version:** 
Win10

![clarity-bug](https://user-images.githubusercontent.com/1791670/27179884-b401239c-51e1-11e7-8343-251c53496e83.png)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@likwifi 
A Plunkr would help us expedite this issue and help find a workaround for your use case.

Beyond that, I don't know if this is something the UX team recommends. <= @reddolan

**Comment by reddolan** [comment]
Not sure why you are seeing a Flat button versus a Normal here. Our [documentation](https://vmware.github.io/clarity/documentation/datagrid/hide-show) shows that it should be a Normal button. If you are seeing a Flat button, this sounds like a bug

![image](https://user-images.githubusercontent.com/1858226/27192440-012a1ed8-51c1-11e7-9c9f-c3689aa464c2.png)

**Comment by mathisscott** [comment]
@likwifi 
Could we get you to create a plunkr demonstrating your issue? It will help us triage it quicker.

The link for 0.9.x is here...

Thanks!

**Comment by likwifi** [comment]
@reddolan Thanks for doc link.
We've developed this component with clarity v0.8.6.
AFAR at that point column-switch component is not available.
That is why I've used dropdown class to wrap menu and that is why my button is transparent after clarity lib upgrade.
I'll switch to column-switch component.
Thanks.

**Comment by likwifi** [comment]
@mathisscott @reddolan I found this code that resets buttons styles in dropdown menu. In my opinion this selector should do that .dropdown-menu .dropdown-item

Are .dropdown-menu .btn and other selectors targeting buttons really needed?

.dropdown-menu .btn, .dropdown-menu .btn-danger, .dropdown-menu .btn-info, .dropdown-menu .btn-link, .dropdown-menu .btn-outline, .dropdown-menu .btn-outline-danger, .dropdown-menu .btn-outline-primary, .dropdown-menu .btn-outline-secondary, .dropdown-menu .btn-outline-success, .dropdown-menu .btn-outline-warning, .dropdown-menu .btn-primary, .dropdown-menu .btn-secondary, .dropdown-menu .btn-success, .dropdown-menu .btn-warning, .dropdown-menu .dropdown-item {
    font-size: 14px;
    letter-spacing: normal;
    font-weight: 400;
    background: transparent;
    border: 0;
    color: #565656;
    cursor: pointer;
    display: block;
    margin: 0;
    padding: 1px 24px 0;
    width: 100%;
    text-transform: none;
}

**Comment by adityarb88** [comment]
@likwifi: Yep, we have those styles for button groups. When buttons in a button groups are configured to be in a menu, they have different styles. But yours is a valid case too. We will take a look at this and figure out a better way to do this. Thanks for reporting this.

**Comment by coryrylan** [comment]
This functionality was deprecated and later removed in version 0.13 
https://github.com/vmware/clarity/pull/2756
