### ISSUE TITLE
Request:  List Component

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#1074]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
I'm looking for a component which can present a list of elements and meets the following requirements:
- Must be able to present a string as representation of the element.  (typically 'name')
  - Must handle truncation and/or wrapping when string is too long
- Must order elements vertically
  - Sort order of elements should be definable programmatically
- Elements must be selectable to drive changes to other displays

Desirables:
- optional inline editing of string
- optional fixed height for list which triggers internal scrolling
- optional button trailing list items for inline adding of new element

Example screen using a list:
![list example](https://user-images.githubusercontent.com/8105536/27206049-85792b0c-51e9-11e7-95c2-f8fa21ffa9b2.png)

### Actual behavior
component doesn't exist

**Comment by mathisscott** [comment]
Open question here about whether this would be a different component from #651

If so, we should probably find more distinct names. Note Clarity UI already supports HTML list elements -- which is a further point of imminent naming collision.

**Comment by reddolan** [comment]
This looks like #651 to me as well. 
@joshjohnson72 can you confirm that this *is or isn't* duplicating that request?

**Comment by reddolan** [comment]
@joshjohnson72 can you take a look at the request in #651 and see if your request is similar to it? We want to merge it if it is and if it's not, then understand how this request is different.

**Comment by gnomeontherun** [comment]
I agree, far as I can tell this is basically the same request and I'm going to close it in favor of the other issue. Please make any additional notes in #651 for further consideration.
