### ISSUE TITLE
The wizard in Clarity-Template-0.9.0.sketch should be updated

### ISSUE THREAD

**Issue by vmwareux-vivian** [vmware/clarity#1075]
**Select one ...**  (check one with "x")
```
[] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
The wizard in the sketch template (Clarity-Template-0.9.0.sketch) should be updated.

### Actual behavior
Compared to the Clarity website: 1) the font size of the title is smaller 2) the unavailable steps are grayed out (Clarity website doesn't gray out unavailable steps).

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by reddolan** [comment]
Changes made and merged into #1077
