### ISSUE TITLE
Expanding a row should not display hidden columns content

### ISSUE THREAD

**Issue by clementcur** [vmware/clarity#1076]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When expanding a row which has some hidden columns, the cells corresponding to those hidden columns shouldn't be displayed.

### Actual behavior
When expanding a row which has some hidden columns, the cells corresponding to those hidden columns are displayed, which breaks the structure of the table by having too many cells on the expanded row.

### Reproduction of behavior
see plunkr: https://plnkr.co/edit/sPPjVO3KjDCElLRZUEmI?p=preview

### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.9.9

**Comment by youdz** [comment]
We missed the interaction between these two features. Thanks for filing this.

**Comment by clementcur** [comment]
@youdz can this issue be prioritized? It's still a blocker on our side that prevents us from using the datagrid expandable feature.

**Comment by mathisscott** [comment]
@clementcur 
I have flagged this issue to be discussed in our weekly planning.

**Comment by clementcur** [comment]
Thx guys!
