### ISSUE TITLE
Update UI Template on the site

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1077]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
- have an updated version of the UI Template on the site for users to download
- include the new color palette
- update version number on [download button](https://vmware.github.io/clarity/get-started) to 0.10.0

### Actual behavior
current version is out of date and has bugs that need to be improved on it

### Linked Issues
#811, #1063, #1066, #1073, #1075 

### Environment details
* **Template version:** 0.9.0

**Comment by reddolan** [comment]
UI Template ready for upload
[Clarity-UI-Template-0.10.0.sketch.zip](https://github.com/vmware/clarity/files/1081989/Clarity-UI-Template-0.10.0.sketch.zip)

**Comment by jaffoneh** [comment]
@adityarb88 can we update this as part of 0.10.0 alpha if it is just a simple link change?

**Comment by reddolan** [comment]
Made a minor update to artwork for a 0.9.9 version number
[Clarity-UI-Template-0.9.9.sketch.zip](https://github.com/vmware/clarity/files/1085267/Clarity-UI-Template-0.9.9.sketch.zip)

**Comment by adityarb88** [comment]
published on the website
