### ISSUE TITLE
Convert Clarity UI values to rem

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1079]
Now that we are off of IE10, we can start using `rem` values for sizing.

Benefits...
• We can get rid of _all_ `$clr_baselineRem` related functions and variables from our SASS.
• By changing the font-size on our `html` element we can radically alter the layout of Clarity, even increasing the baseline of our vertical rhythm with one simple change.

Caveats (not adhering to these _will_ cause issues in browsers we support)
• Do not use `rem` sizing for `line-height` values in `:before` or `:after` pseudo-elements. Either rely on the parent element's line-height or figure something else out.
• Do not use `rem` for `1px` values, especially with borders.

To ensure that we keep vertical rhythm, yet also maintain our default font-size, coordinate the use `html` and `body` styles.

```
$clr_baseline: 24;

html {
    ...
    font-size: $clr_baseline * 1px; // <= our vertical baseline
    ...
}

body {
    line-height: 1rem;
    font-size: (14/$clr_baseline) * 1rem;
    ....
}
```

...users could override in their own CSS with...

```
html {
    font-size: 28px;
}
```

...which would increase everything from a 24px base to a 28px baseline.

This is a very big change that touches a great number of files. But it is mostly mechanical and for the most part involves simplifying what we are currently doing and removing code in many cases.

**Comment by dehru** [comment]
@mathisscott It's great to hear that this is planned!  Any idea how soon this can be implemented?  We are looking at using clarity and this was one of our main issues since we've moved away from px as our base unit a couple years ago.  I also see BS4 moved to REM.

**Comment by mathisscott** [comment]
@dehru
I'm working on this as we speak. I'm almost done with the first pass at the values. Then there will be lots of browser testing in my future!

It's still a ways off. But not too far away!

**Comment by mathisscott** [comment]
Additionally, I will be making it backwards compatible with our existing SASS so that it will not be a breaking change. That way you can get it in 0.10.x instead of having to wait until 0.11.

A lot of the old mixins and `$clr-baselineRem` variables will be deprecated for removal in 0.12 though. (Just a heads up)

**Comment by dehru** [comment]
Thank you!

**Comment by dehru** [comment]
Thank you @mathisscott
