### ISSUE TITLE
How to change default font-size

### ISSUE THREAD

**Issue by ronsc** [vmware/clarity#1081]
Hi Clarity Design Team ,
I have a question follow by this title.
I want to change font-size from 14px to 16px. What should I do.
Thx.

**Comment by mathisscott** [comment]
This is a little tricky in Clarity right now. But you would need to create a SASS file in your project that looks like this...

```
$clr-font-base-size: 16;
@import "[path_to_your_node_modules_directory]/clarity-ui/src/main.scss";
```

...then add that SASS file to your build to generate your app's CSS and use _that_ CSS instead of clarity-ui.min.css. This particular customization will be easier to do once #1079 is completed.

**Comment by ronsc** [comment]
Thx. for feedback. 
Currently So i do by this solution.

**Comment by paul-mcgrath** [comment]
Hi @mathisscott, how do you accomplish the same thing today?

I believe the steps have changed, and I've tried overwriting the $clr-font-size variable, but it doesn't seem to do the trick.

Any help would be super!

**Comment by mathisscott** [comment]
@paul-mcgrath 
The way it's wired up these days, it looks like `$clr-font-base-size` is what you would want to override. Note that this is just an integer. So if you want to change the font-size from 14px to 12px you would put in `12` not `12px`.

**Comment by paul-mcgrath** [comment]
Hi Scott, thanks for the reply.

I tried changing this as outlined in the theme section of the docs (sandwich the `theme.scss` between the two imports, and it didn't seem to have any effect.

Funnily enough, the `$clr-fontSkipBase64`,  `$clr-font`, and `$clr-altFont` overrides worked totally fine.

Is the font-base-size configuration different in some way?

**Comment by paul-mcgrath** [comment]
I also resorted to doing the following, based on [this issue][issue], and it seemed to have mostly the desired effect:

```
html {
  font-size: 28px;
}
```

I'm not sure this is the right way to accomplish it though, based on your previous message!

[issue]: https://github.com/vmware/clarity/issues/1079

**Comment by mathisscott** [comment]
@paul-mcgrath 
If you are using CSS and not SASS/SCSS, yes that is the preferred way to update the font sizing. We converted all our measurements to rems to support that. It's the easiest way to change the default size across the entire library.

**Comment by mathisscott** [comment]
@paul-mcgrath
