### ISSUE TITLE
Datagrid dynamic pagination

### ISSUE THREAD

**Issue by BugsyFTW** [vmware/clarity#1084]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

If i set the pagination of the datagrid to show 25 records on each page and then change the number of each page to 10 the datagrid should resize itself to the appropriated height.

### Actual behavior

When i lower the number of records per page the datagrid creates a blank space of the previous size.

### Reproduction of behavior
https://plnkr.co/edit/NmkRkIdmvZaVbNbcqjMv?p=info

### Environment details

* **Angular version:** 
4.0

* **Clarity version:** 
0.9.9

**Comment by hippee-lee** [comment]
Plunker from the referenced duplicate issue: https://plnkr.co/edit/VQIYST?p=preview

**Comment by adamstauffer** [comment]
still getting this issue in 0.10.27. if we have a datagrid with page size set to 25, but filter the datagrid to only show 10 items, the 15 row whitespace below isnt cleaned up. is this the same bug as what was originally posted or should i create a new issue?
