### ISSUE TITLE
Issue with disabled state of datagrid's single row selection action

### ISSUE THREAD

**Issue by ssanghavi** [vmware/clarity#1085]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
In datagrid single row selection actions, action-item buttons should have disabled look with 'disabled' attribute. These button should look/behave similar to other buttons.

### Actual behavior
It requires both disabled attribute and class to make it get disabled look and feel.

### Reproduction of behavior
Plnkr - https://plnkr.co/edit/GL2YzKPUIrvQusDNwvS3?p=preview

Above plunker shows 3 action-items
1. enabled
2. only disabled attribute - on hover it does not look disabled, although click does not trigger the action
3. both disabled attribute and class - this works as expected

### Environment details

* **Angular version:** 4.0.2

* **Clarity version: 0.9.X

* **OS and version: Not applicable

* **Browser: all

**Comment by hippee-lee** [comment]
Thanks for reporting this @ssanghavi. You are right, this is an oversight in the css for disabled `action-items` in `clr-dg-action-overflow` items. 
I'll be pushing a quick fix out shortly. Keep an eye on this issue to see it.
