### ISSUE TITLE
Use existing vertical space in a column

### ISSUE THREAD

**Issue by cyberbeast** [vmware/clarity#1091]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
The way "col-xs" class automatically occupies vertical space in a grid, is there any implementation that does it vertically? For, example I have a single-row ["col-xs-4"]-["col-xs-8"] layout. In both these columns I want to display a card that adjusts height such that it stretches all the way from its current location to the bottom of the screen. Setting a "col-xs" classed card only stretches the card horizontally. Can this stretching be done vertically as well?

**Comment by adityarb88** [comment]
@cyberbeast: Clarity grid doesn't support that. What you want to do is a custom layout that you will have to write at your end. In your case you might have to make sure that the `.row` occupies the entire height. Here is an example: https://jsfiddle.net/7ad2aLxe/

Thanks!
