### ISSUE TITLE
Please add 'enter' key support and ADA compliant focus support to the Wizard and the Modal.

### ISSUE THREAD

**Issue by bbronson** [vmware/clarity#1095]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
Please add 'enter' key support and ADA compliant focus support to the Wizard and the Modal.

1. When a modal or a wizard page is opened it should get focus.
2. When the user presses enter on the wizard page or modal which has that focus it should execute the Next button or the Finish if that is the only button there.

### Actual behavior
Pressing enter does nothing and an ADA user will be clueless if they are 'reading' this by listening to JAWS reader or another screen reader. The Modal and Wizard need to auto focus after they show up.

### Reproduction of behavior
https://plnkr.co/edit/XghzBL9I2NeK3lvyfvZz

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X/4.0.X

* **Clarity version:** 0.9.9

* **OS and version:** Mac OSX

* **Browser:** [all | Chrome latest ]

**Comment by bbronson** [comment]
Actually its a bug, since ADA is the law of the land, this is not just "Nice to have".

**Comment by jaffoneh** [comment]
The modal getting focus when it is opened makes sense, clicking enter actually executing something without the focus being on "next", or whatever the button is, does not.

Here is the behavior that should happen: the modal gets focus when opened, you can tab through the logical steps of going through the modal including what's inside the modal like an input field, once you get to "next" being in focus as you tab, you can click enter and that would execute it but simply clicking enter anywhere else within the modal while "next" is not in focus shouldn't actually go next.

Again, the modal having the focus does not and should not simply equal clicking enter executing something. The focus needs to be on the button itself to execute anything.

**Comment by mathisscott** [comment]
I agree the modal and wizard should be focused when they open. But wiring up the enter key to fire the next/finish button is a separate feature. And one that negatively impacts usability. 

What if a user focused a select box and hits enter to select a value? Suddenly the modal submits their form. 

The correct way to do this is to have the user focus the next button and then press enter. 

But beyond that, yes, modals and wizards should receive focus upon opening.

**Comment by jaffoneh** [comment]
To what @mathisscott said, that should we resolved as part of this pull request: https://github.com/vmware/clarity/pull/1056

**Comment by jaffoneh** [comment]
Based on the user experience recommendations we follow for accessibility, focus should be on the modal/wizard itself (which should be resolved as part of #1056) but it shouldn't automatically click on the "submit" or "next" button if that button does not have the focus.

More on focus management is available here as well: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role

Based on the above I am closing this issue.
