### ISSUE TITLE
Signpost takes more space than it visually looks like

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#1098]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Signpost displays as a small icon and it's height is expected to be about the same as visual.

### Actual behavior
Signpost actually takes more space than it looks like, especially its height. For example, it changes the height of row when used inside datagrid.
<img width="567" alt="screen shot 2017-06-22 at 5 22 13 pm" src="https://user-images.githubusercontent.com/8813134/27461570-6a864ec0-576f-11e7-97de-129144c200dd.png">

### Reproduction of behavior

* https://plnkr.co/edit/zYfOtd?p=preview

### Environment details

* **Angular version:** 4.1.0

* **Clarity version:** 0.9.9

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Issue is caused because the signpost trigger button has `height: 36px`
and
clr-icon has `line-height: 36`

We need to change these to preserve the vertical rhythm of the datagrid rows.

**Comment by yaooluu** [comment]
Issue 2: The signpost seems to have a blank tailing area below itself. This is reproducible in the same plunkr provided above. 

Refer to screenshot:
<img width="554" alt="screen shot 2017-06-22 at 7 09 01 pm" src="https://user-images.githubusercontent.com/8813134/27463752-79a541fe-577e-11e7-823b-67507d60828c.png">
