### ISSUE TITLE
Unable to hide tooltip-content with *ngIf

### ISSUE THREAD

**Issue by ssanghavi** [vmware/clarity#1101]
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
*ngIf should help hide tooltip content

### Actual behavior
Empty tooltip content is shown

### Reproduction of behavior
plnkr - https://plnkr.co/edit/c1T8uKj49Ex87L5MYI9m?p=preview

### Environment details

* **Angular version:** 4.1.2

* **Clarity version: 0.9.10

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@ssanghavi: I don't believe we will be able to support this. More info about this here: https://github.com/angular/angular/issues/6576

But you could something like this: https://plnkr.co/edit/Ibnb9OtChZ3bKFALaqTr?p=preview

I am closing this issue based on the above info but please free to re-open the issue if you have more questions/feedback.
