### ISSUE TITLE
Binding to dir input of clr-icon throws errors in edge and ie

### ISSUE THREAD

**Issue by MRamos62786** [vmware/clarity#1103]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Edge and IE should not throw errors when binding to dir input for clr-icon component.

### Actual behavior

https://plnkr.co/edit/qBjrzs

Run the plunker linked above in Chrome and note that it works as expected. Run it from edge or ie with developer tools open and note the errors thrown.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

See Above...

### Environment details

Latest Angular and Clarity Version. Browser causing issues is edge and ie...obviously...

**Comment by mathisscott** [comment]
@MRamos62786 
`dir` is an attribute on a custom element. So you have to bind to `[attr.dir]` not `[dir]`.

That's an Angular thing with binding to attributes.

https://plnkr.co/edit/ykL8fH?p=preview

**Comment by MRamos62786** [comment]
doh... thanks and apologies!
