### ISSUE TITLE
How can I change the image on the right side of the login page

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [vmware/clarity#1108]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
I want to create a  login page using clarity with a custom image at the right-hand side of the login page.

### Actual behavior
I followed the steps given here: [https://vmware.github.io/clarity/documentation/login](https://vmware.github.io/clarity/documentation/login) to create a login page.

### Environment details

* **Angular version:** 4.2.4

* **Clarity version:** 0.10.0-Alpha

* **OS and version:** Windows 10

* **Browser:** all

**Comment by chunghha** [comment]
@soumyakantiroychowdhury this question was asked before.
https://github.com/vmware/clarity/issues/929

As an example, the background-image in login-wapper can be replaced with your custom image like this css of your login component.

```
.login-wrapper {
  background-image: url(/assets/images/yourImage.png);
  background-repeat: no-repeat;
  background-size: 60%;
  background-position: right center;
}
.login-wrapper .login {
  min-height: 70vh;
}
```

**Comment by mathisscott** [comment]
@soumyakantiroychowdhury

@chunghha is correct. This is something that can be easily changed with the custom CSS.

Thanks, @chunghha!

**Comment by soumyakantiroychowdhury** [comment]
Thanks @chunghha - works perfect.

**Comment by ios3** [comment]
How do I completely remove image and center login component?

**Comment by mathisscott** [comment]
@ios3 
This is a great question for [StackOverflow](https://stackoverflow.com/questions/tagged/vmware-clarity).

CSS is again the answer that will help you in that. Just use CSS to make those changes. Shouldn't be more than a dozen lines or so.
