### ISSUE TITLE
An icon inside an anchor element disappears when hovered in Microsoft Edge browser

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1109]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The icon inside an anchor element should not disappear when hovered in Microsoft Edge browser

### Actual behavior

Using the angular directive of the icon inside in an anchor element disappears when hovered in Edge browser.

### Reproduction of behavior

Code snippet:

`<a href="javascript:void(0)"><clr-icon shape="edit"></clr-icon></a>`

### Environment details

* **Angular version:** 4.2.X

* **Clarity version:** 0.10.0-alpha.2 

* **OS and version:** Windows 10 Home Single License

* **Browser:** Microsoft Edge 38.14393.1066.0

**Comment by mathisscott** [comment]
This works for me...

https://plnkr.co/QDYOzZ

**Comment by whizkidwwe1217** [comment]
@mathisscott It happens when the href attribute of the anchor has a value of "javascript:void(0)". I fixed it by setting the href to "#" and called e.preventDefault() as a workaround to meet my requirements. Thanks.
