### ISSUE TITLE
The issue in example of server-driven

### ISSUE THREAD

**Issue by heguangjun** [vmware/clarity#1115]
Hello There,
I want write a page to get the content by REST API from server, and paging the content, the rest side already supported.
Then i found the below example:

https://vmware.github.io/clarity/documentation/datagrid/server-driven

But I can not totally get the idea, and the example code even can not find:
what is "**this.inventory**"

import {State} from "clarity-angular";

class MyComponent {
    users: User[];
    total: number;
    loading: boolean = true;

    refresh(state: State) {
        this.loading = true;
        // We convert the filters from an array to a map,
        // because that's what our backend-calling service is expecting
        let filters:{[prop:string]: any[]} = {};
        if (state.filters) {
            for (let filter of state.filters) {
                let {property, value} = <{property: string, value: string}>filter;
                filters[property] = [value];
            }
        }
        this.inventory.filter(filters)-----**--here what is mean, what is inventory**
            .sort(<{by: string, reverse: boolean}>state.sort)
            .fetch(state.page.from, state.page.size)
            .then((result: FetchResult) => {
                this.users = result.users;
                this.total = result.length;
                this.loading = false;
            });
    }
}

Could you give some suggestion.

Thanks very,
GuangJun

**Comment by chunghha** [comment]
@heguangjun you can find full demo code from here
(https://github.com/vmware/clarity/blob/master/src/app/datagrid/server-driven/server-driven.ts)
(https://github.com/vmware/clarity/blob/master/src/app/datagrid/inventory/inventory.ts)

**Comment by mathisscott** [comment]
Thanks, @chunghha !

@chunghha  is correct. `this.inventory` is specifically referencing the code that can be found here...

https://github.com/vmware/clarity/blob/new-website/src/app/documentation/demos/datagrid/inventory/inventory.ts

**Comment by heguangjun** [comment]
Great! Thanks for your reply. @chunghha<https://github.com/chunghha> @Scott.
☺
