### ISSUE TITLE
[ng] cannot access the ellipsis for action overflow with the keyboard

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#1116]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

User should be able to access the ellipsis via keyboard using the tab.

### Actual behavior

Right now, you can only access it by clicking.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/qKGn7OO07TUOS98rPr2B?p=preview

### Environment details

* **Angular version:** 2.2.X

* **Clarity version:** 0.9.10

* **OS and version:** all

* **Browser:** all

**Comment by mathisscott** [comment]
@jeeyun , @youdz , @adityarb88 
We need to prep this for contributions. I'm fine opening it up for contributions-welcome if we have a plan for fixing it.

**Comment by adityarb88** [comment]
@jeeyun: I believe the issue here is that the ellipsis-trigger is not inside of a button? If its added in a button, Clarity default outline styles will automatically be applied, no?

**Comment by adityarb88** [comment]
Right now the template is this:
```
<clr-icon #anchor shape="ellipsis-vertical" class="datagrid-action-toggle" (click)="toggle($event)"></clr-icon>
<ng-template [(clrPopoverOld)]="open" [clrPopoverOldAnchor]="anchor" [clrPopoverOldAnchorPoint]="anchorPoint"
             [clrPopoverOldPopoverPoint]="popoverPoint">
    <div #menu class="datagrid-action-overflow" (clrOutsideClick)="close($event)" [clrStrict]="true">
        <ng-content></ng-content>
    </div>
</ng-template>
```

and I believe we want it to be:

```
<button (click)="toggle($event)"  class="datagrid-action-toggle">
   <clr-icon #anchor shape="ellipsis-vertical"></clr-icon>
</button>
<ng-template [(clrPopoverOld)]="open" [clrPopoverOldAnchor]="anchor" [clrPopoverOldAnchorPoint]="anchorPoint"
             [clrPopoverOldPopoverPoint]="popoverPoint">
    <div #menu class="datagrid-action-overflow" (clrOutsideClick)="close($event)" [clrStrict]="true">
        <ng-content></ng-content>
    </div>
</ng-template>
```

@jeeyun, @youdz please confirm.

**Comment by mathisscott** [comment]
Assuming that is the way we want to go, would this be a breaking change?

**Comment by adityarb88** [comment]
I don't think so. This is internal to the datagrid.

**Comment by youdz** [comment]
Actually, let's fix this as we move the action overflow to the new popovers. I planned on doing this immediately after 0.10.0.
