### ISSUE TITLE
Research required and optional form field patterns

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1118]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
- Potentially improve the current "required" form field experience
- Research and document recommendations around required and optional field patterns

### Actual behavior
Current required field experience
![image](https://user-images.githubusercontent.com/1858226/27608778-4fac51de-5b4e-11e7-8b87-8701b7ca7a8d.png)

### Things to think about
- use "optional" versus "required" indicators. Any field not optional is assumed to be required
- how does this^ affect form validation?
  - validation done on blur, submit, or both
  - enable or disable submit button
  - error messages and experience of when they show/dismiss

**Comment by gnomeontherun** [comment]
This is completed with the new forms.
