### ISSUE TITLE
Add error validation documentation to the Wizards page

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1119]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Have design documentation on error-handling and validation on the [Wizards](https://vmware.github.io/clarity/documentation/wizards) page

### Actual behavior
There is no design documentation on error-handling

### Environment details

* **Clarity version:** 0.9.10

**Comment by mathisscott** [comment]
@reddolan 
Has this been done already?
