### ISSUE TITLE
Datepicker with multi calendar type like hijri 

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#1121]
```
[ ] bug
[x ] feature request
[x ] enhancement
```

### Expected behavior
Hi,
Thanks for your framework. I need to datepicker that support from hijri calendar or jalali. Do you have add this feature to your backlog.

Thanks

**Comment by mathisscott** [comment]
Can you tell us a little bit more about what is different about the hijiri and jalali calendar? We plan to offer some degree of Internationalization support with our first release of the date picker and  increase that support over time.

**Comment by essivision** [comment]
[https://en.wikipedia.org/wiki/Jalali_calendar](https://en.wikipedia.org/wiki/Jalali_calendar)
[https://en.wikipedia.org/wiki/Iranian_calendars](https://en.wikipedia.org/wiki/Iranian_calendars)
[Hijiri Calendar](https://en.wikipedia.org/wiki/Islamic_calendar)

**Comment by mathisscott** [comment]
Hi @essivision 
Jalali and Hijiri calendars are not part of the initial scope of work for the datepicker. Our intent, however, is to return to the datepicker after the initial scope of work is completed and extend our globalization support as well as add more features to the datepicker.

I will link this issue to the datepicker epic so it is not lost. I'm going to close this question as answered, however.

Thanks!

**Comment by mathisscott** [comment]
Let's keep this in mind for the larger scope of work for #474
