### ISSUE TITLE
Form labels: when input text is disabled, the label should also be disabled

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#1122]
**Select one ...**  (check one with "x")
```
[ X ] bug
[ ] feature request
[ ] enhancement
```

### Form labels should be disabled when input text is disabled
Clarity Forms documentation states: "When disabling a component, also disable all associated elements, such as the component label and explanatory text."

It should look like this:
![image](https://user-images.githubusercontent.com/23196444/27650795-eee7950a-5bea-11e7-9229-5e1ec7d09131.png)

**Comment by mathisscott** [comment]
@lil-kim 
What's the accessibility on that? The text looks awfully light to me.

**Comment by lil-kim** [comment]
I agree. It fails accessibility, but the problem is that if I darken it to be accessible, you can't tell that it's disabled. :-(
![image](https://user-images.githubusercontent.com/23196444/27653780-05c23ff0-5bf5-11e7-96ce-f5f994c4ffc0.png)

**Comment by jaffoneh** [comment]
@lil-kim what's the logic behind disabling the label itself (vs. just the input field). This becomes an important question considering the impact on accessibility.

**Comment by lil-kim** [comment]
@jaffoneh 
1) If we disable only the input, it could be confused with our help text.
2) It's documented in Clarity Forms page that the label should be disabled.

**Comment by mathisscott** [comment]
@lil-kim 
Broad generalization alert: form fields go to read-only for a couple of reasons...

1. The user is restricted from entering data into them for some reason.
2. The application is presenting data to the user that they cannot change.

We may need to revisit our design to allow for an accessible disabled look. While the super-light disabled may be okay for case #1, it poses a real problem for case #2 where users will still need to be able to understand the disabled value's data -- just not edit it.

**Comment by gnomeontherun** [comment]
To my knowledge, this is out dated an no longer part of the new forms considerations. Closing unless objections arise.
