### ISSUE TITLE
Need a design for an icon toggle button

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#1123]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Need a design for an icon toggle button with clear distinction of selected icon
...Specifically a toggle button that switches views from cards view to list view, but should work for different use cases as well.
Current implementation in some apps: two icons to switch views - a card icon and a list icon. The selected (current view) icon is black and the not-selected icon is grey. The distinction isn’t very clear, it needs a better design/solution.
![image](https://user-images.githubusercontent.com/23196444/27652594-363cbbbe-5bf1-11e7-8ca3-4ff6e666798b.png)

**Comment by mathisscott** [comment]
@lil-kim 
Is this for something other than the "Radio" option listed with button groups?

https://vmware.github.io/clarity/documentation/button-group

They seem to fill the same need to me.

**Comment by lil-kim** [comment]
Good point. The radio is one possible option, assuming that the text can be replaced with icons. I also wanted to explore a one-button toggle option and possibly using our existing tabs (replacing text w/ icons). This issue may result in a recommendation rather than a design.

**Comment by mathisscott** [comment]
The text in button groups can be replaced with icons. The issue resulting in a recommendation would be great. Or if you have an idea of radio-selected of flat button groups...

Or if you arrive at an interesting conclusion to the one-button toggle exploration.

**Comment by mathisscott** [comment]
For the time being, could we direct people to use the button groups while you explore more options?

In the event that there are teams out there that are having a hard time figuring out what Clarity recommends for this...

**Comment by jaffoneh** [comment]
@lil-kim @mathisscott note that this would apply to the actions on top of Datagrid as well. From the docs on button group, there is an example with just icons. We should standardize across all of those use cases on one way to do things (or simply use button groups and make changes, if needed, there as @mathisscott mentioned).

**Comment by gnomeontherun** [comment]
We have a grid icon already, so I believe we can close this as available.
