### ISSUE TITLE
Update UI Template and Library with new components

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1124]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Include new components that will be released soon
- [x] [Vertical Nav](https://github.com/vmware/clarity/issues/1001)
- [x] [Date Picker](https://github.com/vmware/clarity/issues/474)
- [x] [Vertical Tabs](https://github.com/vmware/clarity/issues/452)
- [x] [Search](https://github.com/vmware/clarity/issues/186)
- [x] [Select 2.0](https://github.com/vmware/clarity/issues/248)
- [x] create download of UI Template
- [x] create download of Library
- [ ] update [Design Resources](https://vmware.github.io/clarity/get-started#designResources) section with new version numbers and downloads
- [ ] update [Changelog](https://vmware.github.io/clarity/news) with new version number and download

### Actual behavior
none of the above components are in design resources (UI Template & Craft Library)

### Environment details

* **Clarity design resource version:** 0.9.9

**Comment by reddolan** [comment]
UI Template v 0.10.0
[Clarity-UI-Template-0.10.x.sketch.zip](https://github.com/vmware/clarity/files/1215865/Clarity-UI-Template-0.10.x.sketch.zip)

**Comment by reddolan** [comment]
Library v 0.10.0
[Clarity.library.zip](https://github.com/vmware/clarity/files/1216355/Clarity.library.zip)

**Comment by armpp** [comment]
@reddolan how to update ?, Plase help me
