### ISSUE TITLE
[NG] Popover positioning applies to the child element instead of the Host element

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1126]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

1. `position: absolute` styling should be applied to the Host element on which the `clrPopoverAnchor` directive is placed.
2. Positioning should work when `*clrIfOpen` directive is used with `clrPopoverAnchor`

### Actual behavior

Popover positioning applies to the child element instead of the host element

1. Popover positioning applies to the host element instead of the child element.
2. Popover positioning breaks when `*clrIfOpen` is used along with the `clrPopoverAnchor` directive.

Fix discussed with @youdz and @jeeyun: https://github.com/adityarb88/clarity/tree/topic/aditya/DatePicker

This doesn't work with dropdowns. Need to investigate that.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.10.0-alpha.2

* **OS and version:** 

* **Browser:** [all]

**Comment by youdz** [comment]
Closed by #1238.
