### ISSUE TITLE
Justify Tabs

### ISSUE THREAD

**Issue by MrToasty97** [vmware/clarity#1135]
Is it possible to justify the tabs to use the full width?

**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
It should be possible to use the tabs within the full width of the screen.

### Actual behavior
The tabs are only using the width they need, but do not fill the full width of the screen.

### Environment details

* **Angular version:** 4.2.4

* **Clarity version:** 0.9.10

* **OS and version:** Win 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by vijay-venkatraman-vmware** [comment]
@MrToasty97 Hi. Can you give us more information on your use case for Justify Tabs? Thanks.

**Comment by vijay-venkatraman-vmware** [comment]
We have merged your request into #1527 and will be closing this one. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you.
