### ISSUE TITLE
If datagrid has horizontal scroll bar, the paging info gets truncated

### ISSUE THREAD

**Issue by tovinayv** [vmware/clarity#1150]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior
Hi All, I'm facing this issue in IE. If datagrid has horizontal scroll bar, the paging info gets truncated.. Note: This is happening only in IE., In Chrome and firefox., it works fine.. Please refer attachment for screenshot..
![datagrid_truncation_ie11](https://user-images.githubusercontent.com/10471989/27868800-7fb81f70-61bb-11e7-9239-14b1db515641.png)

### Environment details

* **Angular version:** 2.0.X
4.0.1

* **Clarity version:** 
0.9.7

* **OS and version:** 
windows 10

* **Browser:** [ IE 11 ]

**Comment by jeeyun** [comment]
Happening in IE11 and Edge due to persistent scrollbar.

**Comment by youdz** [comment]
@hippee-lee: Can you check if your datagrid template work fixes this? If it does, please link the issues. 👍

**Comment by hippee-lee** [comment]
@youdz - correct this issue is on my list that will be fixed by #1586. The footer will no longer scroll with the headers/rows and the scrollbar will be moved up into the container that scrolls on the x-axis above the footer.
