### ISSUE TITLE
tabs functionality breaks when implementing scrolling on tab's content

### ISSUE THREAD

**Issue by cyberbeast** [vmware/clarity#1152]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Tab's content should be scrollable and the functionality for switching to the content of some other tab should not be affected by this behavior.

### Actual behavior
#1147 This is in reference to a previously closed issue, referenced in this sentence. However, The functionality break was diagnosed as an issue with plunkr. However, when the recommended workaround is replicated natively, the functionality actually does break (suggesting that its not plunkr that is causing the functionality break). Switching to other tab content is impossible.

**Comment by mathisscott** [comment]
@cyberbeast 
The [original plunkr that had been provided](https://plnkr.co/edit/FvCTLHHfQA9KNAlfVYAP?p=preview) was making calls through several outputs to expected event handlers on the host component that weren't there. Removing those and adding one small tweak to the CSS I posted fixed everything.

This plunkr works:

https://plnkr.co/edit/fHA6v9?p=preview

Please take some time to [read the Angular documentation on outputs and setting up events](https://angular.io/guide/template-syntax#event-binding---event-) in your templates.

Thanks!
