### ISSUE TITLE
how to display a system error message for a button click

### ISSUE THREAD

**Issue by colorplayer** [vmware/clarity#1153]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

Take the following screen flow for example. When a system error occurs, how should we display an error message?

<img width="160" alt="screen shot 2017-07-05 at 6 04 46 pm" src="https://user-images.githubusercontent.com/29934853/27891191-1f45d488-61ad-11e7-853d-e7dbd6e61bad.png">
<img width="211" alt="screen shot 2017-07-05 at 6 05 04 pm" src="https://user-images.githubusercontent.com/29934853/27891192-1f628ccc-61ad-11e7-84f9-2350ac8e9f09.png">

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
I believe you would want to use an alert for that.

https://vmware.github.io/clarity/documentation/alerts

I'm not sure users would understand the context of any sort of alert being shown inside of a button without some form of telling them what went wrong.
