### ISSUE TITLE
File Uploader Component

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#1154]
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
I need to file uploader. I think dropzone file uploader is very good to add to your library. Do you have any plan for this?

Thanks

**Comment by mathisscott** [comment]
Yes, we already have an issue open for file inputs. You can see it in issue #672

**Comment by essivision** [comment]
Mu means is component or directive like these links: 
[http://www.jqueryscript.net/demo/Lightweight-jQuery-Dual-List-Box-Plugin-listSwap/](http://www.jqueryscript.net/demo/Lightweight-jQuery-Dual-List-Box-Plugin-listSwap/)

[http://www.jqueryscript.net/demo/jQuery-Plugin-For-Multi-Selection-With-Two-Sides-lwMultiSelect/](http://www.jqueryscript.net/demo/jQuery-Plugin-For-Multi-Selection-With-Two-Sides-lwMultiSelect/)

[https://www.virtuosoft.eu/code/bootstrap-duallistbox/](https://www.virtuosoft.eu/code/bootstrap-duallistbox/)

**Comment by mathisscott** [comment]
@essivision 
The browsers we support allow drag and drop on native HTML file inputs. More than a style change, the file input component should be able to support basic drag and drop functionality.

What about the DropZone plugin meets your use case? Perhaps we could move forward if I understood your requirements better.

**Comment by essivision** [comment]
Dropzone has auto ajax file uploader and thumbnail preview. Also it has multi file uploader feature. You can define size and format other limitations for file uploader. It has progress bar for uploading that useful for large file size.
