### ISSUE TITLE
Dual-List Component

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#1155]
```
[ ] bug
[x ] feature request
[ ] enhancement
```
Do you have any plan to add Dual-List Component to your library?

**Comment by mathisscott** [comment]
Hi @essivision 
What do you mean by "Dual-List" component? Can you point us to any examples?

**Comment by essivision** [comment]
Mu means is component or directive like these links: 
[http://www.jqueryscript.net/demo/Lightweight-jQuery-Dual-List-Box-Plugin-listSwap/](http://www.jqueryscript.net/demo/Lightweight-jQuery-Dual-List-Box-Plugin-listSwap/)

[http://www.jqueryscript.net/demo/jQuery-Plugin-For-Multi-Selection-With-Two-Sides-lwMultiSelect/](http://www.jqueryscript.net/demo/jQuery-Plugin-For-Multi-Selection-With-Two-Sides-lwMultiSelect/)

[https://www.virtuosoft.eu/code/bootstrap-duallistbox/](https://www.virtuosoft.eu/code/bootstrap-duallistbox/)

**Comment by mathisscott** [comment]
@essivision 
This is the first request we've had for this kind of list swapper component. I'll ask the UX team about it so we can get their recommendation on it.

**Comment by reddolan** [comment]
@essivision can you explain what problem the user would be solving by using this? Is the goal to give the user a way to multiselect from a list of values?

**Comment by essivision** [comment]
Yes, we need to give multiple option from all options. For example I want to assign multiple user group to user from all exist user group. As matter of fact goal of this component is a way to give multiselect from a list of values.

**Comment by mathisscott** [comment]
I think this is a reasonable addition to the library. This will need to go through a design pass and then development.

This will need to be a post-1.0 effort, however.

**Comment by jeeyun** [comment]
We have a couple of components that support the use case of selecting multiple values from a list:

Combobox: https://github.com/vmware/clarity/issues/248 (in progress)
Datalist: https://github.com/vmware/clarity/issues/3813

Closing this for now.
