### ISSUE TITLE
Create "commerce" category for Clarity Icons

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1159]
Currently, we have a number of "commerce/finance" icons packed into the Essentials category. This bloats essentials with icons that many non-ecommerce webapps may not use. Note the non-trademarked icons in #501 would go in this category as well.

We'll need @lil-kim to answer two questions:

1. Do we need a separate category for commerce/finance/marketplace icons? Why not if the answer is "no"?
2. What should we call the new category?
3. Which icons do we need to relocate there? (Please update the confluence doc to reflect this migration. Whoever implements this change should use the confluence doc as a guide.)

Then we'll need @Shijir or whomever is assigned to implement this to perform the migration from Essentials to the new category.

This constitutes a breaking change so it should go into a minor release. If possible, I would prefer it go into 0.10. If not, it will have to go into 0.11 and should be completed before Clarity Icons is finalized.

**Comment by mathisscott** [comment]
I'm assigning this to the bullpen because the questions assigned to @lil-kim constitute a reasonably minor effort. When the questions are answered, please put back at the top of the backlog for a dev to work on in the next few weeks.

**Comment by lil-kim** [comment]
1, 2. Please create a new category, it should be called: Commerce
3. Refer to the Confluence icon list. You'll find the icons to be moved in the "Commerce" column.
https://confluence.eng.vmware.com/display/CLAR/Icon+Inventory+and+Classification
Thank you!
