### ISSUE TITLE
Create "travel" category for Clarity Icons

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1160]
Currently, we have a number of "travel/transportation" icons packed into the Social category. This bloats social with icons that are not applicable to that category.

We'll need @lil-kim to answer two questions:

1. Do we need a separate category for travel/transportation icons? Why not if the answer is "no"?
2. What should we call the category?
3. Which icons do we need to relocate there? (Please update the confluence doc to reflect this migration. Whoever implements this change should use the confluence doc as a guide.)

Then we'll need @Shijir or whomever is assigned to implement this to perform the migration from Social to the new category.

This constitutes a breaking change so it should go into a minor release. If possible, I would prefer it go into 0.10. If not, it will have to go into 0.11 and should be completed before Clarity Icons is finalized.

**Comment by lil-kim** [comment]
1, 2. Please create a new category, it should be called: Travel
3. Refer to the Confluence icon list. You'll find the icons to be moved in the "Travel" column.
https://confluence.eng.vmware.com/display/CLAR/Icon+Inventory+and+Classification
Thank you!
