### ISSUE TITLE
Create a "media" category for Clarity Icons

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1161]
Currently, we have a number of "media/entertainment" icons packed into the Essentials, Social, and Technology categories. This bloats essentials with icons that non-music or image-based webapps may not use.

We'll need @lil-kim to answer three questions:

1. Do we need a separate category for media/entertainment icons? Why not if the answer is "no"?
2. What should we call the new category?
3. Which icons do we need to relocate there? (Please update the confluence doc to reflect this migration. Whoever implements this change should use the confluence doc as a guide.)

Note also that this is complicated by similarly themed icons spread across different categories. Like play, stop, and fast-forward being in Essentials but volume-up/down being in technology. Or camera being in social but video-camera being in technology -- while film-strip is in Essentials.

Then we'll need @Shijir or whomever is assigned to implement this to perform the migration from the old categories to the new category.

This constitutes a breaking change so it should go into a minor release. If possible, I would prefer it go into 0.10. If not, it will have to go into 0.11 and should be completed before Clarity Icons is finalized.

**Comment by lil-kim** [comment]
1, 2. Please create a new category, it should be called: Media
3. Refer to the Confluence icon list. You'll find the icons to be moved in the "Media" column.
https://confluence.eng.vmware.com/display/CLAR/Icon+Inventory+and+Classification
Thank you!
