### ISSUE TITLE
Update instructions for using Clarity with angular-cli

### ISSUE THREAD

**Issue by kahurangitama** [vmware/clarity#1166]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
npm run start should run properly

### Actual behavior
node_modules/clarity-angular/layout/nav/clrResponsiveNavigationService.js:6
import { Injectable } from "@angular/core";
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/loyi/project/dist/ngfactory/src/app/app.server.module.ngfactory.ts:22:1)

### Reproduction of behavior
1. Install latest Angular CLI
2. Bootstrap a new application
3. Follow instructions to install Clarity over existing project

### Environment details

* **Angular version:** @angular/core@4.2.5

* **Clarity version:** 0.10.0-alpha.4

* **OS and version:** macOS Sierra 10.12.5

* **Browser:** all

**Comment by mathisscott** [comment]
@hippee-lee 
Would you mind taking a look at this and letting me know if it's an actual bug?

**Comment by hippee-lee** [comment]
Howdy @pavlosadovyi - I ran through our instructions for starting with the angular-cli tool. Here are the commands I ran:

1. `$ ng new testissue1166`
2. `$ cd testissue1166`
3. `$ npm install`
4. `$ ng serve` -> A cli bootstrapped app should work at this point
5. `$ ng g c test` -> Generate a test component to make sure things are wired correctly
6. `$ng install --save clarity-icons`
7. `$ npm install @webcomponents/custom-elements@1.0.0-alpha.3 --save`
8. Modified `.angular-cli.json` (see below)
9. `$ npm install clarity-ui --save`
10. Modified `.angular-cli.json` (see below)
11. `$npm install clarity-angular --save`
12. Modified `.angular-cli.json` (see below)

## relevent parts from my `.angular-cli.json`
```
"styles": [
        "../node_modules/clarity-icons/clarity-icons.min.css",
        "../node_modules/clarity-ui/clarity-ui.min.css",
        "styles.scss"
      ],
"scripts": [
    "../node_modules/@webcomponents/custom-elements/custom-elements.min.js",
    "../node_modules/clarity-icons/clarity-icons.min.js"
    ],
```

## Notes
- It looks like that section of our docs could use a refresh. If you can let me know where they are giving you trouble I can update them with a fresh perspective
- I did notice that the latest version of `@angular/cli` generated `.angular-cli.json` and our seed uses `angular-cli.json` -> I'm not sure why
- I did not install the mutation observer shim
[`Here is the repo I made`](https://github.com/hippee-lee/testissue1166), you should be able to clone it, install and serve
- If you still have trouble or can't find a solution for your error it would help if you could put your code on github so I can take a look at it.

**Comment by mathisscott** [comment]
I'm changing this over to an "update the docs" issue.

**Comment by hippee-lee** [comment]
Closing this b/c seed project has instructions for running an angular-cli app with Clarity. If this is still an issue feel free to re-open.
