### ISSUE TITLE
Using Forms in Grid does not stretch input controls to the maximum length of the grid column when validation tooltip is enabled to the input control

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1167]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The input text control's length should be extended to the length of the grid column.

### Actual behavior

When a validation tooltip is attached to the input control, it doesn't size properly according the length of the grid column.
![image](https://user-images.githubusercontent.com/1977391/27991603-03b15512-64af-11e7-9ddf-61b1b02626ea.png)

### Reproduction of behavior

Steps:
1. Create a form inside a grid (just like the sample in the "Forms in grid" section of the Forms (layout) documentation.
2. In a "form-group row" div, there should be two columns, one for the label and one for the input text.
3. Create two set of form-group row, the other has a validation tooltip and the other has none.
Issue: The one that has a validation tooltip does not resize properly. It does not stretch its length the length of the grid column. See screen shot above, the length of the **Code** field is shorter than the other fields without validation tooltips.

```
<form class="compact" [formGroup]="employeeForm" (ngSubmit)="onSubmit()" [hidden]="submitted">
    <section class="form-block">
        <div class="form-group row">
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <label for="txtCode">Code</label>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <label for="txtCode" aria-haspopup="true" role="tooltip" class="tooltip tooltip-validation tooltip-sm" 
                        [class.invalid]="employeeForm.get('code').invalid && (employeeForm.get('code').dirty || employeeForm.get('code').touched)">
                    <input class="form-control" type="text" id="txtCode" formControlName="code">
                    <span class="tooltip-content">Code is required.</span>
                </label>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <label for="txtFirstName">First Name</label>
            </div>
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <label for="txtFirstName">
                    <input class="form-control" type="text" id="txtFirstName" formControlName="firstName">
                </label>
            </div>
        </div>
    </section>
</form>
```

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by whizkidwwe1217** [comment]
Closing this for now. Just need to set the label width to 100% to stretch it all the way to the length of the column.

**Comment by adityarb88** [comment]
@whizkidwwe1217: `.form-control` class on the `.tooltip` should do the same.
