### ISSUE TITLE
Sidenav scroll bar

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#1168]
```
[ x] bug
[ ] feature request
[ x] enhancement
```

### Expected behavior
Sidenav component doesn't has scroll bar in pages that screen hight shorter than sidenav with full of menu. When I see your documention of component, I can't see lower menu.

**Comment by jaffoneh** [comment]
@essivision could you file the issue with the template provided so we know which version of Clarity/Angular/Browser/Device, etc? Without that info, it's hard to debug this or figure out what the issue you're facing is.

**Comment by adityarb88** [comment]
@essivision: Closing the issue based on what @jaffoneh mentioned above. Please reopen the issue with a plnkr for replicating it along with other details like Clarity version, browsers on which you are facing this issue etc. The link to the plnkr can be found in the issue template when you open a new issue.
