### ISSUE TITLE
Data-grid header label aligned to right on ipad

### ISSUE THREAD

**Issue by abelkbil** [vmware/clarity#1170]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Data-grid header expected to align right on ipad layout
http://prntscr.com/fu6ypi

### Actual behavior
Open https://vmware.github.io/clarity/documentation/datagrid/structure on ipad.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.1

* **Clarity version: 0.9.0

* **OS and version:Windows 10

* **Browser:** [ ipad : [Chrome, Safari] ]

**Comment by mathisscott** [comment]
What is the benefit of aligning the header text to the right of the cell on an iPad?

**Comment by abelkbil** [comment]
![GitHub Logo](https://image.prntscr.com/image/0-B0-ptgTOG74PPfwsTXmA.png)
https://prnt.sc/fu6ypi

Thanks for consideration. Dont you get this issue in your ipad ?. In mobile it works fine.

**Comment by abelkbil** [comment]
@mathisscott Is this correct in your ipad ?

**Comment by mathisscott** [comment]
@abelkbil 
Yes, I've checked it on two different iPads over the weekend. I'm not seeing the issue that you are.

What type of iPad are you using (Pro/Air/version)?

**Comment by abelkbil** [comment]
@mathisscott Ipad safari version was 8.4
