### ISSUE TITLE
The clrModalSize is not working when pop up modal dialog in a WIZARD step.

### ISSUE THREAD

**Issue by ghvm20142** [vmware/clarity#1171]
**Select one ...**  (check one with "x")
```
[*] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

We need to popup a modal dialog in a wizard step.
The height of the modal dialog should be a fixed height(min) when the dialog init.
It should be auto increase the height when the content increase and also should have a max-height
that should not over the wizard.

### Actual behavior

The height of the modal dialog is always same with the wizard no matter what's the clrModalSize.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

--latest version---
<clr-wizard>
.....
<clr-wizard-page>
<clr-modal [(clrModalOpen)]="certModalOpened"  [clrModalSize]="'lg'" [clrModalStaticBackdrop]="true">
  <h3 class="modal-title">xxxx</h3>
  <div class="modal-body">
    xxxxxxxxx
  </div>
  <div class="modal-footer">
      <button type="button" class="btn btn-outline" (click)="certModalOpened = false">
        cancel</button>
      <button type="button" class="btn btn-primary" (click)="onSubmit()">
        ok</button>
  </div>
</clr-modal>
</clr-wizard-page>

</clr-wizard >

### Environment details

* **Angular version:** 4.1.0

* **Clarity version:** 0.10.x

* **OS and version:** win7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ghvm20142** [comment]
<clr-wizard #wizard [(clrWizardClosable)]="vIOWizardClosable" [clrWizardSize]="'lg'" (clrWizardOnCancel)="onCancel()" [(clrWizardOpen)]="vIOWizardOpened">
<clr-wizard-page [clrWizardPagePreventDefaultNext]="true"
                    (clrWizardPageOnCommit)="on_commit()"
                    (clrWizardPageOnLoad)= "on_load()">
<clr-modal [(clrModalOpen)]="certModalOpened" [clrModalSize]="'lg'" [clrModalStaticBackdrop]="true">
<div class="modal-body">
   xxxxx
</div>
</clr-modal>
</clr-wizard-page>
</clr-wizard>

**Comment by mathisscott** [comment]
Stacking modals on top of wizards is a pattern that Clarity UX does not recommend.

From the website:

```
Stacking modals
Modals shouldn’t launch other modals. Stacking modals makes it hard to dismiss them and confuses the user on their levels of importance.
```

What is the reasoning behind opening a modal inside a wizard? Is there a better pattern that could be used?

**Comment by mathisscott** [comment]
@ghvm20142 
I haven't heard back on this. Was my comment sufficient to help you think through this workflow?

**Comment by ghvm20142** [comment]
Hi Mathi
During our VIO deployment wizard, we need user to provide VC(nsxv,nsxt,ldap) address. Then retrieve the server ssl certificate and  pop up it (VC,NSXV,NSXT,LDAP) in a modal dialog.
Then user can have chance to take a look at the ssl certificate,  and click ok to trust it or cancel if user find the ssl cert is not right.

lichao

**Comment by mathisscott** [comment]
@ghvm20142 
I see. Is layering a modal on top of a wizard better UX than dynamically adding a step to the wizard where users must review the ssl cert?

A modal on top of a wizard is not a pattern that Clarity recommends or supports. If you want to custom size the modal on top of the wizard, your best course of action may be styling it on your end with either custom CSS or inline styles.
