### ISSUE TITLE
Icon Size Differences

### ISSUE THREAD

**Issue by manndave** [vmware/clarity#1172]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Icons with the same height/width setting should appear the same size on screen
### Actual behavior
Two icons (info-circle and help in my case), both with CSS for height and width set to "24px" appear to be differently sized on screen, despite dev tools reporting them both as 24 x 24.  See images below to clarify:
Help Icon: 
![help icon](https://user-images.githubusercontent.com/6853483/28098237-1e4d349c-6683-11e7-8c2d-81383f074432.png)
Info Circle Icon:
![info circle icon](https://user-images.githubusercontent.com/6853483/28098236-1e4c859c-6683-11e7-825a-dd596fc9d262.png)
Two Icons:
![two icons](https://user-images.githubusercontent.com/6853483/28098238-1e4daf30-6683-11e7-87d8-262438af979f.png)
Info-circle clearly appears smaller

Markup:
![markup](https://user-images.githubusercontent.com/6853483/28098295-77ee4fea-6683-11e7-9f8a-e4c4af64e468.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.0

* **Clarity version:** 0.10.0-alpha.4

* **OS and version:**  Win 10

* **Browser:** Chromium (I think v56) via Electron

**Comment by lil-kim** [comment]
Hi @manndave 

Apologies for the confusion. We have two sets of those icons. The smaller set is only used in our alert banners. If you use the set with "standard" in the name you shouldn't have a problem with size differences. Let me know if this doesn't solve the problem. Thanks.
![image](https://user-images.githubusercontent.com/23196444/28098588-f95082c8-666b-11e7-881d-752f8f6725c5.png)

**Comment by manndave** [comment]
@lil-kim : Thanks for clarifying and the quick response.  I didn't notice the "standard" set.  It looks like this will solve my problem, but I'm not at my dev computer to check ATM.  Out of curiosity, is there a reason you made a separate set of icons instead of just shrinking them for the alert banner via CSS when needed?

**Comment by lil-kim** [comment]
@manndave 
We tried shrinking the "standard" sized icons to (16x16) for alert banners, but the lines became thin and didn't stand out well. For alert banners specifically, it was important for the icons to look a bit bolder at a small size. The lines in the smaller set are designed to be proportionally heavier than the standard set.

**Comment by manndave** [comment]
Worked great.  Thanks for the info and the reasoning behind it.  Learn a little bit more every day....  :-)
