### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by manndave** [vmware/clarity#1174]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
Would love to see a couple new icons:

- Magic Wand, Wizard Hat, or something similar that can indicate it launches a wizard (would go with the Wizard component)
- DNA Double Helix - OK, so this one is pretty specific, but it would help me out a lot :-)

**Comment by mathisscott** [comment]
Thanks for the suggestions, @manndave ! We'll circle back with our Icons team.

Out of curiosity, what would you use the DNA helix for?

**Comment by manndave** [comment]
Thanks, @mathisscott.  DNA is to represent a gene/chromosome browser in my application (naturally, what else would it be???  ;-)  ).
