### ISSUE TITLE
Datagrid built-in filter that allows user to select from a list of values in the column

### ISSUE THREAD

**Issue by BlakeDraper** [vmware/clarity#1175]
```
[ ] bug
[X ] feature request
[ ] enhancement
```

### Expected behavior
A built-in filter for allowing user to select from a list of values that are in the column. 

### Actual behavior
Currently needs to be a custom filter. Having a hard time implementing that, and I think a lot of people could really use a pick-list style filter. 

### Reproduction of behavior
N/A

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** All future

* **OS and version:** All

* **Browser:** [all ]

P.S. I see that you mention this in the docs, but I did not see an issue for it, so submitting as a bump.

**Comment by whizkidwwe1217** [comment]
I implemented it using custom filters inspired by the Wijmo flexgrid filters. It would be nice to have this similar feature built right in the clarity data grid filters :)
![image](https://user-images.githubusercontent.com/1977391/28236157-0e760dc0-6951-11e7-86af-f0063bae5e4b.png)
![image](https://user-images.githubusercontent.com/1977391/28236216-8e0f5158-6952-11e7-8e97-3457d5d7f85a.png)
![image](https://user-images.githubusercontent.com/1977391/28236222-b3a0bf92-6952-11e7-8b46-38ad530d0972.png)

**Comment by abelkbil** [comment]
@whizkidwwe1217 Do you get any issue on data gird while rendering in ipad. I get header names right aligned.

**Comment by reddolan** [comment]
This would be a helpful feature. It will need design time on it @mathisscott

**Comment by boldertech** [comment]
Here are some custom filters that we've been using that are really generic.
[custom-filters.zip](https://github.com/vmware/clarity/files/1357148/custom-filters.zip)

### Checkbox example
html template:
```html
<clr-dg-column [clrDgField]="'color'">
    Colors
    <clr-dg-filter [clrDgFilter]="colorFilter">
        <checkbox-list-filter #colorFilter
                    [filterParamName]="'color'"
                    [items]="colorOptions"
                    [(defaultFilterValues)]="defaultColors">
        </checkbox-list-filter>
    </clr-dg-filter>
</clr-dg-column>
```

component.ts:
```javascript
// if you want any colors enabled by default
defaultColors = [];
colorOptions = [
    {key: 'red', value: 'Red'},
    {key: 'orange', value: 'Orange'},
    {key: 'yellow', value: 'Yellow'},
    {key: 'green', value: 'Green'},
  ];
```

**Comment by gnomeontherun** [comment]
There is are workarounds available for this issue, and we recommend using it for Clarity Angular. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
