### ISSUE TITLE
clr-datagrid should provide option which makes its filter to get autoclose when focusout.

### ISSUE THREAD

**Issue by Harsh072** [vmware/clarity#1177]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

clr-datagrid should provide option which makes its filter to get autoclose when focusout.
### Actual behavior

clr-datagrid opens all filter, sometimes filter overlaps. No way out.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

Goto clarity documentation page. Open any datagrid with multiple filters and try clicking on all filters. All the filters will get opened at the same time. But opening of second filter should close first filter.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
latest.

* **OS and version:** 
All OS.
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by mathisscott** [comment]
@reddolan and @youdz

**Comment by youdz** [comment]
Yes, this was intentional. Once a filter is closed, you have no way of seeing what it currently filters on. And sometimes you need to look at current filters to add an extra one, so this was the "easiest" way of allowing to check several filters at once, without having to open them one by one and trying to remember them all.

**Comment by mathisscott** [comment]
Okay. I'm not going to mark this as a bug/enhancement then. I will leave it for UX to look at, however. Just to verify on their end.

**Comment by Harsh072** [comment]
@youdz makes perfectly sense. But what can we do for overlapping of multiple filters ?
Any suggestion ?
Should there be any flag by which we can make autoclosing as an option ?

**Comment by mathisscott** [comment]
If/when we add this meta-filter panel, this will eliminate the need to keep open filters open and we can move to a default of having only one filter panel open at a time.

#753

**Comment by gnomeontherun** [comment]
The core ask here is no longer a problem with #2923 which will only allow one to be open at a time in v2.2+.

Closing as no longer valid, and if we need changes here we'll have to assess against latest implementations.
