### ISSUE TITLE
[NG] Datagrid: Restrict to single row selection

### ISSUE THREAD

**Issue by sivaah** [vmware/clarity#118]
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behaviour
Is single row selection is supported in Datagrid? I'm trying to restrict to single row selection but the selection always allow multiple row selection.

### Reproduction of behaviour
https://vmware.github.io/clarity/documentation/datagrid

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.7.0

* **Browser:** [all]

**Comment by jaffoneh** [comment]
@sivaah could you provide more information around your use case? Are you trying to select a single row to perform an action, copy content, etc?

I am trying to make sure we include that in Issue #17 which is filed on single row selection in datagrid.

**Comment by sivaah** [comment]
@jaffoneh, Yeah.. Looks like duplicate of issue #17 

The feature request is to restrict user to select only one row from Datagrid so that some action can be performed on that row. currently selection allows selecting multiple row.

Please mark this as duplicate of issue #17
