### ISSUE TITLE
Pagination Not Working - angular 4.0.0 with clarity 0.10.0-alpha.4

### ISSUE THREAD

**Issue by rhgithub1** [vmware/clarity#1180]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
 Pagination must work based on the [clrDgPageSize]="X" 

### Actual behavior
Shows the full data set rather than pagination. plunker link below
https://embed.plnkr.co/1hTnVa/

### Reproduction of behavior
plunker link included. https://embed.plnkr.co/1hTnVa/

### Environment details

* **Angular version:** 4.0.0

* **Clarity version:** 0.10.0-alpha.4

* **OS and version:** Windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Howdy @rhgithub1 - It looks like your plunker has a model in it instead of a datagrid. 
Can you update it to reflect your issue and let us know when its ready to look at?

**Comment by rhgithub1** [comment]
please check now

**Comment by youdz** [comment]
You are using `*ngFor` instead of `*clrDgItems`. See the explanation in our documentation: https://vmware.github.io/clarity/documentation/datagrid/smart-iterator
