### ISSUE TITLE
Radio Button Group border is off in Chrome

### ISSUE THREAD

**Issue by syndesis** [vmware/clarity#1182]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Selected button in Button Group Radio should be completely filled when viewed in Chrome.

### Actual behavior
Button is not filled in Chrome.

Chrome screenshot:
![chrome](https://user-images.githubusercontent.com/611764/28227920-5f7c55ca-6899-11e7-9b01-ccbbc0af6c5a.png)

Firefox screenshot:
![firefox](https://user-images.githubusercontent.com/611764/28227927-6569422c-6899-11e7-88d8-00d2f5ec6c2b.png)

### Reproduction of behavior
View the Radio section of this page in Chrome.
https://vmware.github.io/clarity/documentation/button-group

### Environment details

* **Angular version:** 4

* **Clarity version:** 

* **OS and version:** Windows 7

* **Browser:** Chrome Version 59.0.3071.86 (Official Build) (32-bit)

**Comment by mathisscott** [comment]
@syndesis 
This looks fine to me in Chrome 59.0.3071.115 (64-bit). Do you think there's an issue between the 32 and 64-bit versions? Or has a more recent patch in Chrome fixed this?

<img width="348" alt="screen shot 2017-07-17 at 7 25 50 am" src="https://user-images.githubusercontent.com/2728359/28272873-9fe1bd7e-6ac1-11e7-9d5b-bc7f37d79f8d.png">

^ What I'm seeing...

**Comment by syndesis** [comment]
I updated to 59.0.3071.115 (Official Build) (32-bit) and I'm still seeing it.  A co-worker on the same OS but with the 64 bit version is not seeing the issue so that might be it.

**Comment by mathisscott** [comment]
@adityarb88 
Could you see if this is a Clarity issue we need to fix? You may need to run a VM that uses 32-bit Chrome.

**Comment by adityarb88** [comment]
@mathisscott: Sure. I will add this to my list

**Comment by jeeyun** [comment]
I see this behavior in Chrome, IE11 and Edge as I zoom in/out. Will need to investigate what the fix is.

**Comment by syndesis** [comment]
FYI, this might be related to #2105 .  I don't have a Windows machine to confirm anymore.

**Comment by gnomeontherun** [comment]
I can not see this issue today, closing as resolved.
