### ISSUE TITLE
DataGrid: Can't dismiss/close data grid Hide/Show Columns tool when a column filter is opened.

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1183]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Hide/Show Columns popup should be dismissed when clicking on the OK or X button.

### Actual behavior
When the filter popup is opened, hide/show columns can't be dismissed/closed.

### Reproduction of behavior
Steps:
1. Open a column filter (leave it opened).
2. Open Hide/Show columns.
3. Issue 1: On first click on Hide/Show columns, it doesn't show up. You have to click it again to open the popup.
4. Issue 2: You can't dismiss/close the Hide/Show columns popup when clicking on the X icon or the OK button even if you close the column filter.

![image](https://user-images.githubusercontent.com/1977391/28235946-ce05ae62-694b-11e7-9d9e-780f00b0a13a.png)

### Environment details

* **Angular version: 4.2.6

* **Clarity version: 0.10.0-alpha.4

* **OS and version: Windows 10 Home Single

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Thanks for finding this @whizkidwwe1217.

@youdz - along with fixing this it looks like I need to convert the column toggle to use `*clrIfOpen` and think they can be done at the same time. 

Along with the fix, does it make sense to use a hostlistner and close the toggle when a click action occurs outside of it?

**Comment by youdz** [comment]
@hippee-lee: We have a clean-up of popovers coming up soon, and it'll make switching to `*clrIfOpen` much easier. So let's wait for this before we fix the bug, it shouldn't be too long.

**Comment by digitlz** [comment]
Having the same issue as described by @whizkidwwe1217 . Are there any updates to this? I'm using Angular 5.2.1 and Clarity 0.11.5 .

**Comment by hippee-lee** [comment]
Hi @digitlz - I'm working on several other datagrid issues that need to be addressed for the pinned first column feature and hoped that it might also address this one. After a quick test for this issue I see that unfortunately it is still there. 

This issue is in the backlog and I'll dig into it when our priorities allow.

**Comment by dexfab** [comment]
Any updates on this bug?

**Comment by hippee-lee** [comment]
We need to check the popover refactor that is about to get merged into master and investigate/triage this again.

**Comment by gnomeontherun** [comment]
This is resolved as part of #2923 and fixed in 2.2+. Closing as resolved.
