### ISSUE TITLE
No show SVG of clr-icon in IE edge (IE 11)

### ISSUE THREAD

**Issue by cripolgon** [vmware/clarity#1187]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Should display the Logo svg

### Actual behavior
The block 'clr-icon' is loaded in html but the logo svg doesn't.

### Reproduction of behavior
For example: 
`<clr-icon shape="user" size="20"></clr-icon>
`
### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** ^0.10.0-alpha.4

* **OS and version:** 

* **Browser:** [ IE XX ]

**Comment by Shijir** [comment]
@cripolgon Could you provide more information about the problem you experiencing with Clarity Icons? Do you see any console errors? Also, are you loading the custom elements polyfill, `https://github.com/webcomponents/custom-elements`?

**Comment by cripolgon** [comment]
Hi, I'm sorry!
When the component charged, the svg doesn't do it. I don't have ant console errors.

![image](https://user-images.githubusercontent.com/15108191/28456814-e709d73c-6e03-11e7-80ce-650eba349df0.png)

And this is my polyfills.ts.

`/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.


/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';


/** ALL Firefox browsers require the following to support `@angular/animation`. **/
import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.
/**
 * Need to import at least one locale-data with intl.
 */
import 'intl/locale-data/jsonp/en';
import 'intl/locale-data/jsonp/es';
import 'intl/locale-data/jsonp/pt';
`

**Comment by mathisscott** [comment]
@cripolgon
What do you mean by "when the component charged"?

**Comment by mathisscott** [comment]
@cripolgon 
From what you posted it does not look like you are loading the custom elements polyfill.

That's probably the reason the icons are not showing up in IE 11.

**Comment by cripolgon** [comment]
@mathisscott Hi again! Sorry for not respond. Should you say me one polyfill for fix this issue? In resume, my svg in the <clr-icon> doesn't show in the website.

**Comment by mathisscott** [comment]
I just checked and the icons are loading on the Clarity website in IE11 and Edge.

Here's a screenshot of the documentation on the website re: the polyfill...

![screen shot 2017-09-22 at 8 21 35 am](https://user-images.githubusercontent.com/2728359/30746347-2dbe5a08-9f6f-11e7-9b37-99f22909f394.png)

There's also a link to a plunkr on the website that you can use to copy-paste code from.
