### ISSUE TITLE
Placement of button groups for data grids

### ISSUE THREAD

**Issue by tishun** [vmware/clarity#1188]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
- the action buttons in a button group in the header of a data grid are placed close to the grid
- the entire surface of the the action buttons in a button group in the header of a data grid is clickable

### Actual behavior
- the action buttons in a button group in the header of a data grid are placed with a large amount of free space from the datagrid itself; this is probably for the purpose of being able to host larger buttons, but especially for btn-link types of buttons it looks as the action buttons are not associated with the data grid itself

- around 30% of the surface (located in the lower part of the button) is not clickable, which is especially visible when having btn-link buttons - basically the user could place the mouse over the lower part of the button text and not be able to click it

### Reproduction of behavior
Visible in the Clarity showcase https://vmware.github.io/clarity/documentation/datagrid/batch-action
Screenshot : http://i67.tinypic.com/xnhz6d.jpg

### Environment details

* **Angular version:** any

* **Clarity version:** 0.9.5

* **OS and version:** any

* **Browser:** all

**Comment by tishun** [comment]
Awesome job, guys. What milestone release do we expect to contain this fix?

**Comment by adityarb88** [comment]
@tishun: This will go in both 0.9.15 & 0.10.0

**Comment by adityarb88** [comment]
@tishun: Actually we are just going to release this for 0.10.0 since the fix for this is a breaking change visually. I will add more details in the release notes. thanks!
