### ISSUE TITLE
New Wizard does not emit clrWizardOpenChange when changed through clrWizardOpen Input

### ISSUE THREAD

**Issue by KashMoneyMillionaire** [vmware/clarity#1189]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When changing value of clrWizardOpen input, the EventEmiter for _openChange should fire and any observers would see if the wizard is opened/closed

### Actual behavior
Changing the value does not fire the clrWizardOpenChange EventEmiter

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/hS6kIGVE7FKiwOkb2S3B?p=preview

### Environment details

* **Angular version:** 4.3.0

* **Clarity version:** 0.9.13

* **OS and version:** Windows 10

* **Browser:** Chrome

### Suggestion

Something similar to Option 2 here: https://stackoverflow.com/a/44686085/2510279

**Comment by mathisscott** [comment]
@youdz 
Is this something that we are looking to support?

**Comment by adityarb88** [comment]
@KashMoneyMillionaire: Change in `Input` should not reemit the same value as an `Ouput`. For more info please see this: https://github.com/vmware/clarity/issues/1184
