### ISSUE TITLE
Add aria-roles in components

### ISSUE THREAD

**Issue by LinBoLen** [vmware/clarity#1190]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

I have noticed that wijmo use this standard

>
> FlexGrid: https://www.w3.org/TR/wai-aria-1.1/#grid
> TreeView: https://www.w3.org/TR/wai-aria-1.1/#tree
> Gauge: https://www.w3.org/TR/wai-aria-1.1/#range
> ListBox: https://www.w3.org/TR/wai-aria-1.1/#listbox
> ComboBox: https://www.w3.org/TR/wai-aria-1.1/#combobox
> Menu: https://www.w3.org/TR/wai-aria-1.1/#menu
>

I want to pull request to support this feature, but time limit.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@LinBoLen 
Are you proposing to add aria roles to the Clarity project?

If so, I would like to give @youdz an opportunity to comment further before proceeding.

**Comment by LinBoLen** [comment]
yes, please.

**Comment by youdz** [comment]
I think this would be a very welcome contribution. My only recommendation is to aim for complete ARIA support on each component one by one. For instance, pick treeview, make sure it's 100% good on ARIA roles, and then move to a different one. That way, you can even post separate PRs, one per component, to work at your own pace.

Thanks for submitting this!

**Comment by mathisscott** [comment]
#2358 and #2359 cover most of what is left here. Closing this as it is being addressed by multiple issues.
