### ISSUE TITLE
ClarityIcons svg not loaded when added via webpack to aspnetcore-spa 

### ISSUE THREAD

**Issue by luis-cortina** [vmware/clarity#1198]
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
I expect clarity-ui, icons, and angular to load and run correctly in the new aspaspnetcore-spa project
- https://github.com/aspnet/JavaScriptServices/tree/dev/templates/AngularSpa

### Actual behavior
Everything works fine except the ClarityIcons are not shown on the browser(I can see the css rules but not the image itself) I suspect its related to how webpack loads the svg files since I can see the font-awesome fonts loaded in the browser dev tools but nothing else.

* **Clarity version:** 
0.9.14
* **OS and version:** 
Windows 8
* **Browser:** 
all

This is how I load the vendors

```
vendor: [
                '@angular/animations',
                '@angular/common',
                '@angular/compiler',
                '@angular/core',
                '@angular/forms',
                '@angular/http',
                '@angular/platform-browser',
                '@angular/platform-browser-dynamic',
                '@angular/router',
                'bootstrap',
                'bootstrap/dist/css/bootstrap.css',
                'es6-shim',
                'es6-promise',
                'event-source-polyfill',
                'jquery',
                'zone.js',

                'mutationobserver-shim/dist/mutationobserver.min.js',
                '@webcomponents/custom-elements/custom-elements.min.js',

                'clarity-ui/clarity-ui.min.css',
                'clarity-icons/clarity-icons.min.css',

                'clarity-icons',
                'clarity-angular',
                
                'font-awesome/css/font-awesome.css'
            ]

```

This is the browser network tab. No svg files loaded. Only fonts.

![image](https://user-images.githubusercontent.com/25346332/28535016-1ec3452e-7060-11e7-82fa-8c3a5a415dd0.png)

Any pointers on how to make this work?

Luis

**Comment by luis-cortina** [comment]
Related to #947, but not a dup since I'm not getting the same behaviour.

**Comment by luis-cortina** [comment]
Looking a little bit deeper I got a little bit more info:

- When inspecting the generated vendor.js and vendor.css files I can see all the code being added from the sources.
![image](https://user-images.githubusercontent.com/25346332/28586295-868232e4-7130-11e7-9b75-499f9aae4667.png)
The problem is that the clr-icon is empty, no svg code therefore no icon will show up?
Does this help?

![image](https://user-images.githubusercontent.com/25346332/28586337-a6102d28-7130-11e7-96e3-926e7207b1d7.png)



Luis

**Comment by mathisscott** [comment]
@luis-cortina 
 I'm not greatly familiar with aspnetcore-spa but I would advise checking in your console if `ClarityIcons` is defined, as well as getting a handle on whether this is a server-side rendering issue.

https://stackoverflow.com/questions/39719231/how-to-disable-server-side-rendering-on-an-asp-netcore-spa-application

**Comment by luis-cortina** [comment]
@mathisscott 

ClarityIcons is undefined, removing the server side rendering doesn't fix it.

**Comment by mathisscott** [comment]
@luis-cortina 
That's probably the problem. The `ClarityIcons` object is loaded on the global window object by default. I don't know why aspnetcore-spa isn't allowing that. But it is likely the source of the issue.

CC: @Shijir

**Comment by luis-cortina** [comment]
I got it to work now.  

In my `app.module.client.ts` I added ```import 'clarity-icons';```  and now it works.
I'm not sure what's going on, but that fixes the problem.

Closing now. Thanks for the pointers.
