### ISSUE TITLE
Add .btn-icon override class

### ISSUE THREAD

**Issue by jonathantrevor** [vmware/clarity#1201]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Small icon-only buttons, and those with short text (e.g. 10m, 1d, 8d for time selection), especially in toolbars / trays / button groups seem far to wide. 

The current base .btn class has a min-width of 72px which is too large, especially when combined with 12px l/r padding.

I'd recommend going to a smaller min-width, say 24px, or perhaps making just .btn.sm small buttons have the smaller relative size and/or padding.

### Actual behavior

Unsuitable for trays or toolbars which have a lot of buttons, or as single dropdown "buttons" or action "icon" buttons.

### Environment details

* **Angular version:**
n/a

* **Clarity version:** 
0.9 and 0.10

* **OS and version:** 
n/a

* **Browser:** all

**Comment by mathisscott** [comment]
When we have a button that only contains an icon, we should allow users to give it a `.btn-icon` class. This will adjust it so that the min-width is equal to the expected height. So that minimally, the sizing will be equilateral.

**Comment by mathisscott** [comment]
Also needs a docs update on buttons page...

**Comment by adityarb88** [comment]
@mathisscott, @reddolan: `This will adjust it so that the min-width is equal to the expected height. So that minimally, the sizing will be equilateral.` Are we also supporting small icon buttons? (24x24)

**Comment by mathisscott** [comment]
@adityarb88 
To avoid confusion, we should support small icon buttons. Our recommendation should be a minimum click target of 36x36 but users should be able to create small icon buttons nonetheless.
