### ISSUE TITLE
Selected rows in Datagrid get clear when de-select all rows 

### ISSUE THREAD

**Issue by lohiaad** [vmware/clarity#1204]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
should retain selected rows when de-selecting all rows from header in last page of datagrid

### Actual behavior
selected rows get cleared.

### Reproduction of behavior
Step to reproduce
1) select a row on any page.
2) go to last page and select all rows from header checkbox
3) deselect all rows from header checkbox

Can be reproduced on https://vmware.github.io/clarity/documentation/datagrid/full

plunker link
https://plnkr.co/edit/b9BvWKKWwV69o5iM5M7f?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.14

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@lohiaad 

The "select/deselect all" functionality in our datagrid works across pages. This is intentional so that users can have confidence in the interaction and so we do not have to warn users of a unexpected consequences of acting on a page-level vs. global level.

Thanks for the feedback. @youdz can explain more if needed.

**Comment by lohiaad** [comment]
@mathisscott 
i understood functionality but it is more confusing when select all works on page level and deselect on global level.

thanks

**Comment by mathisscott** [comment]
@lohiaad 
That is a good point about it working one way on select and another on deselect. I will ping @reddolan and @youdz so they can clarify the reasoning behind that.

**Comment by youdz** [comment]
Actually, I think this is a bug. Deselecting all on the current page should only deselect the current page, not the rest. We have no way of truly selecting "all" anyway, so the opposite behavior should be consistent.

**Comment by mathisscott** [comment]
CC: @reddolan and @yenmade

**Comment by reddolan** [comment]
@lohiaad @youdz are correct, this is a bug. Select All selects all rows on a page and should function the same way when deselecting.
