### ISSUE TITLE
spinner-inline is not displayed inline in Wizard

### ISSUE THREAD

**Issue by syndesis** [vmware/clarity#1205]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Element with class="spinner spinner-inline" should be displayed inline in a Wizard.

### Actual behavior
Spinner is absolutely positioned because of .clr-wizard .spinner style:

_wizard.clarity.scss
`.clr-wizard {
      .spinner {
        left: calc(50% + 115px);
        position: absolute;
        top: 40%;
    }`

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://plnkr.co/edit/8ibUgINcCecgNxyeKUR1?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.9.x

* **OS and version:** Windows 7

* **Browser:** all

**Comment by adityarb88** [comment]
@syndesis: Thanks for reporting this issue. We will take a look and get back to you.

**Comment by adityarb88** [comment]
@syndesis: I believe this is a bug. We provide the use of spinners to indicate page loading but we should do that with the help of a separate class and not target all spinners instead. We will add this to our list of issues to be fixed. Thanks again for reporting this!

cc: @mathisscott to confirm.
