### ISSUE TITLE
[feature request] Add date/time picker component

### ISSUE THREAD

**Issue by saravanareddy** [vmware/clarity#121]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

Would be great to see a calendar component added to the list. Thank you.

**Comment by jaffoneh** [comment]
@saravanareddy could you provide a bit more information? Are you looking for a date/time picker components? I want to make sure we're talking about the same component before providing more information.

**Comment by saravanareddy** [comment]
@jaffoneh: I should have called it date/time picker to be more precise. Please feel free to rename the issue as you see fit. Thank you.

**Comment by reddolan** [comment]
@saravanareddy this is part of our [1.0.0 Roadmap](https://github.com/vmware/clarity/projects/1)

**Comment by reddolan** [comment]
working on design specs now. Hope to have them posted soon for review. Will link it here when available.

**Comment by reddolan** [comment]
We have merged your request into Date & Time Picker #474. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you
