### ISSUE TITLE
Where is sass-planifolia included?

### ISSUE THREAD

**Issue by ysds** [vmware/clarity#1216]
According to ATTRIBUTION.md,

> Math functions from sass-planifolia (GNU License)

Clarity includes sass-planifolia. But I cant't find that source code. Where is sass-planifolia included? Also the current licence of sass-plantfolia is MIT not GNU. https://github.com/xi/sass-planifolia/blob/master/LICENSE

**Comment by mathisscott** [comment]
@ysds
We are using an early version of one of Tobias' math functions here...

https://github.com/vmware/clarity/blob/master/src/clarity-angular/utils/vendor/mathPow.clarity.scss
