### ISSUE TITLE
When horizontal scrolling is necessary, vertical scroll should be always visible and footer should not use the horizontal scroll

### ISSUE THREAD

**Issue by halachliyskid** [vmware/clarity#1217]
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
If a datagrid is too wide to fit in the screen a horizontal scroll bar should appear. This scroll bar should be above the footer/within the table, so that:
1. I can see the vertical scroll all the time (if there is one)
2. I can see the whole footer (it makes no sense to scroll the footer since it has almost no information)

### Actual behavior
Currently the horizontal scroll appears below the footer. Initially I cannot see if there is a vertical scroll, and to use it, I first must scroll to the right, then drag the vertical scroll, then drag the horizontal scroll back to the left, so I can see the first (and presumable most important) column. Also since I can't see neither the vertical scroll, nor the items count (which is on the right side of the footer), I don't even know if there are more items in the datagrid
The same issue would come up if there is paging - the controls for it are on the right side and therefore - hidden.

**Comment by mathisscott** [comment]
@reddolan ^

**Comment by mathisscott** [comment]
@reddolan 
Any update on this?

**Comment by mathisscott** [comment]
@reddolan

**Comment by mattmutt** [comment]
The scrollbars should be added the grid data body, not below or outside of the grid itself, as that would be counter intuitive.

Is there any sample of a Clarity datagrid that lays out correctly given these parameters? Correctly means in narrow / wide circumstances.
- percentage based column width definition
- flexible container ( a div or card component) that holds the Clarity datagrid

**Comment by gnomeontherun** [comment]
This requires some investigation as scroll bars display behave differently across browsers/platforms. This might also change the internal DOM structure to properly display scrollbars. There was some investigation into custom scrollbars as well, which is not a reliable solution.

**Comment by gssjr** [comment]
+1
