### ISSUE TITLE
Treeview, subtree not collapsing

### ISSUE THREAD

**Issue by marvinosswald** [vmware/clarity#1218]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
the sub tree should collapse like this:
<img width="435" alt="screen shot 2017-07-27 at 20 02 18" src="https://user-images.githubusercontent.com/1621844/28684945-8866c64c-7306-11e7-8fea-595e575b9127.png">

### Actual behavior
While the carret turns, the subtree itself doesn't hide:
<img width="451" alt="screen shot 2017-07-27 at 19 59 36" src="https://user-images.githubusercontent.com/1621844/28684989-acb1d582-7306-11e7-926c-c14a9f2dbd86.png">

### Reproduction of behavior
[Clarity Documentation - Tree View](https://vmware.github.io/clarity/documentation/tree-view)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.9.9

* **OS and version:** macOS 10.12.5

* **Browser:** [Safari 10.1.1]

**Comment by adityarb88** [comment]
@marvinosswald: Thanks for reporting this issue. Will take a look and get back to you.

**Comment by boemska-nik** [comment]
I've been meaning to report this. FWIW Issue also appears in IE11 as well as mobile + desktop Safari, and Yandex 14.12. 

Fine in Chrome, Firefox & Opera. I'm sure it was also affecting Stack View components, but that doesn't seem to be the case any more.

**Comment by mathisscott** [comment]
I've verified this on Safari, FWIW.
