### ISSUE TITLE
0.10.0-alpha.6 bug with tree view sub-nodes

### ISSUE THREAD

**Issue by mim-Armand** [vmware/clarity#1224]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Just wanted to let you guys know that In the `0.10.0-alpha.6` version, the **Tree-Node** component does not expand ( or even show the arrow icon to spand ) when there are more tree-node children, so trying the simple examples from the doc will not work either

### Actual behavior
Tree node does not show the children ( the style of children node-trees is -->` { height: 0 } ` )

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 
0.10.0-alpha.6
* **OS and version:** 
MAC-OS siara
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 61

**Comment by adityarb88** [comment]
@mim-Armand: I can't replicate this. Could you please use a plnkr to demo the issue?

**Comment by mim-Armand** [comment]
Hey @adityarb88, I tried to include a Plnkr but couldn't manage to find/include the alpha release in the libraries, and the problem exists only in the latest **pre-release** `0.10.0-alpha.6`, it's not an issue in the latest stable version ( I just wanted to let you know so it doesn't slip on into the next release )

**Comment by adityarb88** [comment]
@mim-Armand: I can't replicate the issue. Here is a plnkr demo-ing the tree view in alpha.6 https://plnkr.co/edit/mF60HhK9D7ZGiRh7AZfW?p=preview

Please use this to replicate your issue.

**Comment by mim-Armand** [comment]
Great, thanks ( I need to figure out how that's done! let me know if you may, how you add the alpha release to plnkr dependencies? 😄 )

[**so here it is, I used the basic example from the docs.**](https://plnkr.co/edit/1SI5QYlVoUn8uwF2zWCg?p=preview)

Please note I had to remove the `[clrTreeNodeExpanded]="true"` as plnkr wasn't happy about it for some reason `Can't bind to 'clrTreeNodeExpanded' since it isn't a known property of 'clr-tree-node'.` but that's probably unrelated to this issue

**Comment by adityarb88** [comment]
@mim-Armand: I think you are using the 0.9 docs for the 0.10.0 tree. Please note that 0.10.0 is still in alpha and we have a breaking change for tree view. To migrate to the new tree view, please refer to the release notes: https://vmware.github.io/clarity/news/0.10.0-alpha

Also, plnkr deps can be updated in config.js

Closing the issue based on this.
