### ISSUE TITLE
Main Container Height not 100%

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1227]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

When defining a `<div>` as the main container using the `.main-container` class, it is expected that the main container would be 100% height. But it is not so.

### Actual behavior

The main container does not extend full height of the window. 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3.2

* **Clarity version:**  0.9.15

* **OS and version:** Windows 10

* **Browser:** [all]

A workaround is to include the following css
```
.main-container {
    min-height: 100vh;
    height: initial;
}
```

**Comment by adityarb88** [comment]
@SayakMukhopadhyay: I don't believe this is true. The main container height is already set to 100vh Can you replicate this issue on a plnkr? https://plnkr.co/edit/uNwwZe?p=preview

**Comment by SayakMukhopadhyay** [comment]
First of all, thanks for a fully set up plnkr link 😄 . I am using a `<router-outlet>` to render my routes. And I believe this is what is causing the issue. Please check this plnkr https://plnkr.co/edit/az7D8V3Yk02gnk7p0Goh?p=preview

**Comment by adityarb88** [comment]
@SayakMukhopadhyay: I don't understand the issue in the plnkr. Could you please provide more details?

BTW, `.content-area` should be a direct child of the `.content-container`

**Comment by SayakMukhopadhyay** [comment]
Thanks for pointing out the at mistake. It has cleared up a lot of problems. But I still have the little issue with the height of the `.content-area`
![image](https://user-images.githubusercontent.com/13748882/28773784-90c356a2-7608-11e7-897b-0be5f549e414.png)
I can solve the problem by adding a `padding-bottom` or `margin-bottom` of 24 px to the `div` inside the `.content-area`. But I was wondering if there is a better way.
New plnkr link https://plnkr.co/edit/uqBY26QA7bynMlELcJTZ?p=preview

**Comment by adityarb88** [comment]
@SayakMukhopadhyay: This behavior depends on the browser. If you try it in chrome it works but firefox and IE it wont work. For more info please refer to this link: https://stackoverflow.com/a/20625114/3538394 You will have to handle this at your end. Closing the issue based on this. Please feel free to reopen if you have any feedback/questions.

**Comment by SayakMukhopadhyay** [comment]
Thanks. It clears my mind. 😄
