### ISSUE TITLE
Custom template for select component

### ISSUE THREAD

**Issue by uNki23** [vmware/clarity#123]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
select component should be able to display items with custom templates. you could have an image in front of the text or some detail information like:

___________________
**USERNAME**
_USERTYPE_
___________________
**USERNAME**
_USERTYPE_
___________________
**USERNAME**
_USERTYPE_
___________________

### Actual behavior
select component display native select (depends on browser/device) with no styling/templating options.

Thank you!

**Comment by youdz** [comment]
The problem with custom-build "select" elements with divs and spans is that they are not semantic, they are read completely wrong and almost impossible to use on screenreaders. And accessibility is one of our biggest priorities.

For this reason, we decided to stick to native `<select>` elements at the moment. We obviously styled the input part, but heavily customizing the dropdown is pretty much impossible across browsers.

Please note that the autocomplete/typeahead component will not have this issue, and will allow custom item templates.

**Comment by jaffoneh** [comment]
@uNki23 I am closing this issue based on @youdz's comment and the fact that autocomplete is coming soon (see issue #90). Please feel free to reopen this issue if you'd like to discuss further, offer additional solutions, or offer more thoughts on the topic!
