### ISSUE TITLE
Error on Data Grid when binding to an empty array

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1231]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I just want to make sure that this error doesn't sneak into the next build. This error didn't occur in version 0.10.0-alpha.5.
Datagrid should be able to bind to an empty array without errors.
### Actual behavior

Errors generated when array is empty:
![image](https://user-images.githubusercontent.com/1977391/28759201-cfbf5860-75cc-11e7-932e-f06d15158a2a.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

1. Create an array variable with initial items. (ex. array of employee objects, employees: Employee[])
2. The array object will be the data-source of the data grid. The grid loads the data without errors.
3. Create something that will clear the items of the array. For instance, a button, when click, it should clear the items in the array)
4. Issue: When the array is empty, an error is generated as shown above.

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:0.10.0-alpha.6 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@whizkidwwe1217: Please provide a plnkr which reproduces the error so that we can debug the issue. Here is a template for 0.10.0-alpha.6 https://plnkr.co/edit/rfkdmMaZofNlqnGCA5oU?p=preview

**Comment by exk0730** [comment]
Is this a possible duplicate of #1215? https://plnkr.co/yTJ8UnrpFdioU1iWJXLV?p=preview

**Comment by whizkidwwe1217** [comment]
@adityarb88 I can't reproduce it on plunkr [https://plnkr.co/edit/VQIYST?p=preview](https://plnkr.co/edit/VQIYST?p=preview). However, when I tried to stop ng serve and recompile the project, the error disappears. It might be a caching issue. After that, I'm having another error but I think it's a problem on my side. I'm closing this issue for now. Thanks :-)
