### ISSUE TITLE
accessibility + visibility with clr-dropdowns and tooltips

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#1232]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If clr-dropdown is given top-left alignment, it should not take up the default space it currently takes

### Actual behavior
https://plnkr.co/edit/jArAZjF483ejoqnkpi1J?p=preview demonstrates the bug wherein an overflow scrollbar is visible even though there seems to be no element which needs the scrollbar to appear.
as soon as all action 2 dropdowns in the last row are clicked twice, the dropdown menu is repositioned correctly and the unnecessary page scrollbar disappears.
Even if the user doesnt click any of the action buttons in the last row, the dropdowns should correctly occupy their places.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
[demo plunk](https://plnkr.co/edit/jArAZjF483ejoqnkpi1J?p=preview)
you may need to adjust the number of cards depending on your screen size.
have as many cards in the screen which can just be accomodated in the given space. you would still see a scrollbar.
then click on the action 2 buttons in the last row. the scroll bar would disappear.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@envyN: Thanks for raising this. We will take a look and get back to you.

**Comment by hippee-lee** [comment]
This may be a bug related to the new popover implementation on `Dropdown` as `clr-dropdown-menu` element is always in the DOM even though we _seem_ to be using the new Popover with `*clrIfOpen`.

**Comment by adityarb88** [comment]
@envyN: Which version of Clarity are you using?

**Comment by envyN** [comment]
@adityarb88 its 0.10.0-alpha.6 but seen in alpha4 as well. upgraded today to 6 and still see the issue

**Comment by adityarb88** [comment]
This issue occurs because of `visibility: hidden` on the dropdown menu. We didn't use `display: none` before for accessibility reasons but in our angular component (https://vmware.github.io/clarity/news/0.10.0-alpha.2), we remove the menu from the DOM. We need to figure out a strategy for accessibility for popovers when the appear/disappear. Keeping this issue open to track that.
