### ISSUE TITLE
Need an Adobe Experience Design UI Kit for mockup and prototyping

### ISSUE THREAD

**Issue by iwansyahp** [vmware/clarity#1233]
[ ] bug
[x ] feature request
[ ] enhancement
```

Hi, I am mockuping -> prototyping an angular app for user usability testing. I think it will be great if there is an Adobe Experience Design UI Kit for Windows' users for continuity design and development of Clarity/Angular based app.

Thanks

**Comment by whizkidwwe1217** [comment]
Yes, please support Adobe XD..I think there are more developers in Windows than in MacOS (This is just my opinion, no factual basis, please correct me if I'm wrong.)   :-)

**Comment by mathisscott** [comment]
Thanks for the suggestion, @iwansyahp and @whizkidwwe1217.

We will take this under consideration.

**Comment by reddolan** [comment]
At this time, we won't be supporting any design tools other than Sketch. This is mainly because we don't use Adobe XD internally. Also, a significant portion of the design community uses Sketch over XD.

That said, we will keep XD in mind and continue to listen to the Clarity community. If demand for XD grows, we will look at reconsidering in the future. 

In the meantime, if you are interested in building one and supporting it, we would be happy to promote it.

**Comment by iwansyahp** [comment]
Ok. Thank you for the response.

**Comment by frankspin89** [comment]
I'm thinking about porting the sketch file over to Adobe XD. 

Before I start, I'm wondering what your standpoint is regarding Adobe XD?

**Comment by mathisscott** [comment]
@reddolan covers that a couple of comments up. We don't use Adobe XD and there's no value for our company in applying resources to creating and maintaining an Adobe XD library. If the community wanted to do so, we could work out some way of providing links to community maintained projects on our website. But an Adobe XD library wouldn't be something we would maintain.

**Comment by whizkidwwe1217** [comment]
@frankspin89 Maybe you can check this out: [Lunacy]( https://icons8.com/lunacy). It's a new app called Lunacy that works for both Windows and Mac. They called it the Sketch for Windows. I tried it and it can indeed open a sketch file.
![image](https://user-images.githubusercontent.com/1977391/38905934-4c74df7e-42e6-11e8-8a89-4729279659a7.png)
