### ISSUE TITLE
Dual list/datagrid swapper component

### ISSUE THREAD

**Issue by s-rusev** [vmware/clarity#1234]
[ ] bug
[x ] feature request
[ ] enhancement

I've seen this request - https://github.com/vmware/clarity/issues/1155 and I'd like to ask for something similar - the only difference is that in our case we have 2 datagrids, rather than lists.

If we have the swapper component - how we can use it if there is too much data in the rows? 
Please check the provided screenshot - right now I'm using two multiselect datagrids, but probably it will be better to have a separate component with the ">>>" and "<<<" buttons available in between.

Thanks!

![multi-select-swapper](https://user-images.githubusercontent.com/5656738/28779714-ce585a54-760c-11e7-91b3-e42fdb692996.png)

**Comment by mathisscott** [comment]
@s-rusev 
This seems like a workflow that is very specific to what you are attempting to accomplish with your application. As such, it isn't a feature or pattern we feel Clarity should adopt for datagrids.

As for how you can implement this for your application, you can add buttons that switch records from one dataset to another like any other data-bound Angular component.
