### ISSUE TITLE
[ng] Stackview inside modal is rendered as expanded

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#1235]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Stackview rendered inside the modal should initially render as not expanded unless `clrSbExpanded` input is set to true.

### Actual behavior

After upgrading to Angular ^4.2.x, the stackview inside a modal is showing up as expanded. I know that the state isn't actually expanded, as the initial click will re-expand it, and the subsequent states after that operate as normal. Note that this only happens when we open the modal after it has been loaded. If the modal's `clrModalOpen` is already set to true on initial page load, this bug does not occur.

### Reproduction of behavior
Click on the edit button on the right-top corner of the stack view under "Stack View With Editing in a Modal":
https://vmware.github.io/clarity/documentation/stack-view

### Environment details

* **Angular version:** 2.2.X

* **Clarity version:**  0.9.16 

* **OS and version:**

* **Browser:** all

**Comment by mohitvaid** [comment]
+1

**Comment by gnomeontherun** [comment]
This is pretty stale, and believe is a duplicate. Having the modal defined outside of the stackview would likely address this or to use the Core modal. Closing as stale, unless we have a recent reproduction to address.
