### ISSUE TITLE
[CORE] Memory Issues when building the website in prod mode

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1239]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

No errors while running `ng build --prod`

### Actual behavior

When running `ng build --prod` we face the same issue described here: https://github.com/angular/angular-cli/issues/5618

Started noticing this just last week.

Temporary Solution:
`node --max-old-space-size=4076 node_modules/\@angular/cli/bin/ng build --prod`

### Reproduction of behavior

1. Clone https://github.com/vmware/clarity/tree/new-website
2. npm install
3. ng serve --prod

**Comment by notsonotso** [comment]
> Temporary Solution:

Doesn't work for sufficiently large number of components. Basically makes Angular a no-go for truly large projects.

**Comment by adityarb88** [comment]
[UPDATE] - We have a temporary solution where we don't have to use the `node --max-old-space-size` option. We are building the website with these options now `ng build --aot --sourcemaps=false --environment=prod`. More info here: https://github.com/angular/angular-cli/issues/5618

**Comment by mathisscott** [comment]
This has been determined to be an angular-cli issue.
