### ISSUE TITLE
[NG] Collapse Animation doesn't work when using clrIfExpanded Directive

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1240]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When an Element using `clrIfExpanded` is collapsed, it should first animate the collapse and then the children should be removed from the View

### Actual behavior

When an Element using `clrIfExpanded is collapsed, animation doesnt work because the child nodes are removed from the DOM immediately.

### Reproduction of behavior

Tree View:
https://plnkr.co/edit/NWGdymT6uBaSNnW3iJmw?p=preview

### Environment details

* **Angular version:** 4.2.X

* **Clarity version:** 0.10.0

* **OS and version:** All

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Jinnie** [comment]
After discussion with the team it was decided not to fix this, as we would have to introduce asynchronous update of the model, bound to an animation lifecycle event. The lost synchronicity and increased testing complexity are not justified with the minor visual animation gain.
