### ISSUE TITLE
[DOCS] Need usage doc for tabs overflow

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#1246]
Need to update the documentation for Tabs in preparation for 0.10.0 (#1236). I will update the code examples, but need usage guidelines, rationale, etc behind our solution for the overflow.

**Comment by reddolan** [comment]
Here is the copy:

### Tab Overflow
Tab overflow is used when the tab group is larger than its containing space, or used to preserve space. The overflow is configurable so you can assign tabs to the dropdown menu.

Tab overflow is shown below as an ellipsis button in the tab group and is the last position to the right. Clicking on the ellipses will show the overflow dropdown menu. 

We recommend that a overflow dropdown have at least two options in it. We also recommend that you test out scenarios with tab labels that may vary in length or when translated to another language to make sure there is enough room for them.

```example
- Dashboard
- Cloud
- Management
- ellipses
    - Settings
    - Alerts
```
