### ISSUE TITLE
Modal dialog is not shown on click of button

### ISSUE THREAD

**Issue by rsrgithub** [vmware/clarity#1247]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The modal dialog should open on click of "Button".

### Actual behavior
For some reason, the modal dialog is not opening. Please find attached the angular project showing the issue. Browser console does not show any error.

I am stuck and not able to proceed. Could you please help and guide me what is causing the issue and provide an appropriate solution.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3.3

* **Clarity Angular version:** 0.10.0-alpha.6 

* **OS and version:** Windows 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
[Clarity_ShowModal.zip](https://github.com/vmware/clarity/files/1196046/Clarity_ShowModal.zip)

**Comment by mathisscott** [comment]
@rsrgithub 
Thanks for zipping up your project. Could you please put the relevant bits inside [a plunkr](https://plnkr.co/uNwwZe)?

It will speed up our ability to diagnose what is happening and get you back on track. And while it might be little more than a copy-paste for you, it could take us much longer to try to familiarize ourselves with your code and try to figure out what you intend it to do. 

Thanks!

**Comment by rsrgithub** [comment]
@mathisscott 
Thanks for quick follow up on my issue.

The issue happens only in the attached project. I am sure there is some other javascript/CSS causing the issue but as there is no error visible on the console so I have no clue what is going wrong.

Issue does not happen on plunkr. My project is very very simple. It has main app module and one component module which has model component implemented.

I did try to put the code on plunkr but there it works.

So it's something weird/incorrect with my project setup. Some CSS/java script is causing the issue.

You can replicate it by downloading my project and do npm install and ng serve

On launch, click on "SHOW MODAL" button and nothing happens.

**Comment by mathisscott** [comment]
@rsrgithub 
I don't have time to dig deeper into it but it appears you aren't loading any of the Clarity CSS. None of the styles are available to your app, as far as I can tell.

**Comment by rsrgithub** [comment]
@mathisscott 

Thanks!

I am loading Clarity CSS at the component level. It is not global. Hooking up at the component level is causing the issue?

**Comment by mathisscott** [comment]
It doesn't look like it's _causing_ the issue so much as it isn't successful. Maybe you are missing part of the path? Or maybe the other CSS libraries you are including (Bootstrap or Material) are conflicting or overriding it?
