### ISSUE TITLE
Very slow loading in Internet Explorer 11

### ISSUE THREAD

**Issue by skarpovru** [vmware/clarity#1253]
```
[x] bug
```

### Expected behavior
Clarity application should be loaded without significant delays (as in Chrome/Firefox)

### Actual behavior
Loading of Clarity application in IE11 taking about 20 sec. 
Usually, IE11 is the only one allowed browser in a big companies. Was surprised to see what "enterprise-oriented" Clarity does not work with IE11:(
Investigation shows what issue is caused by the usage of html5 custom elements to render SVG icons, probably related to a known issue of IE with DOM fragments (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4561410/).

### Reproduction of behavior
Open https://vmware.github.io/clarity/documentation with Internet Explorer 11

### Environment details
* **Browser:** IE 11

**Comment by mathisscott** [comment]
@skarpovru 
Thanks for posting this. IE11 does appear to have taken a performance hit. But it doesn't seem to be related to document fragments or the icons. The initial load of the Clarity website appears to be slower than it previously was but no matter what page you start out on if you then go to the iconography docs it loads very quickly (and that page is literally nothing but hundreds of SVG icons rendered with custom elements).

I will make a note for us to triage this and figure out if this is an angular issue, website issue, or clarity issue. Thanks!

**Comment by ggmueller** [comment]
Taking a look into load times in one application today I'm seeing a lot of time being spent in DOMPurify.sanitize when adding the icons on page load.

Can't the sanitize be implemented as build step?

**Comment by mathisscott** [comment]
That's interesting, @ggmueller 

Sanitize is part of adding icons to the Clarity Icons library. It can't be a build step but we should definitely see if it is why IE11 is running slowly and try to figure out a way around that if so...

@Shijir ^

**Comment by ggmueller** [comment]
The times seen I have seen are not only in IE but also in Chrome for the Sanitze. 
It adds bit more then a second to the initial request for me.
