### ISSUE TITLE
[DataGrid] Selection 2 Way Binding does not update UI when ChangeDetection is set to OnPush

### ISSUE THREAD

**Issue by MJuma** [vmware/clarity#1258]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Adding items to [(clrDgSelected)] should automatically check those items in the DataGrid.

### Actual behavior

Adding items to [(clrDgSelected)] sets them as selected in the DataGrids state but does not update the UI. The user has to click within the UI to trigger Angulars ChangeDetection to update the UI.

### Reproduction of behavior

Plunker: https://plnkr.co/edit/KLZkUi4ME3k3E8hiQp69?p=preview
OnLoad the DataGrid has two rows and the first should be selected. You can see the row is highlighed which means the DataGrid is aware that row should be selected but the checkbox is not checked. If you click within the DataGrid then the checkbox gets checked.

This doesn't seem to be an issue with the DataGrid but with its implementation of the clr-checkbox component. Bellow the DataGrid are 3 check boxes, the first two use clr-checkbox and the last is a plain input of type checkbox. The first clr-checkbox gets its input through ngModel which is how the DataGrid uses clr-checkbox and this also suffers from the same bug. However, the second clr-checkbox gets its input using the [clrChecked] input and so because it relies only on its inputs it does work with OnPush ChangeDetection.

Check and uncheck the first row to see this behavior.

Can the DataGrid be updated to use the [clrChecked] input on the clr-checkbox instead of ngModel?

### Environment details

* **Angular version:** 4.X.X

* **Clarity version:** 0.9.x

* **OS and version:** all

* **Browser:** all

**Comment by MJuma** [comment]
Hi, any updates on this?

Thanks!

**Comment by mathisscott** [comment]
@youdz ^

**Comment by mathisscott** [comment]
@gnomeontherun 
Could you take a look into the root cause here?

**Comment by mathisscott** [comment]
@gnomeontherun 
Any ideas on what is the cause here?

**Comment by MJuma** [comment]
Root cause can be found on this line: [datagrid.html#L18](https://github.com/vmware/clarity/blob/e42a3788bc338a971c3dd5ad254e031e1d46469a/src/clarity-angular/data/datagrid/datagrid.html#L18)

`
<clr-checkbox [(ngModel)]="allSelected"></clr-checkbox>
`
needs to be changed to
`
<clr-checkbox [clrChecked]="allSelected"></clr-checkbox>
`

This will make it support ChangeDetection.OnPush

**Comment by gnomeontherun** [comment]
Just a little more context, this is due to ngModel having an internal async process for setting a new value (https://github.com/angular/angular/blob/4.4.6/packages/forms/src/directives/ng_model.ts#L30) to avoid expression changed errors (more common than this scenario I guess).
