### ISSUE TITLE
SideNav not on the left but after content-area when using router-outlet

### ISSUE THREAD

**Issue by Rebolon** [vmware/clarity#126]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
A sideNav should display on the left side of the page.

### Actual behavior
The sideNav is displayed at the bottom of the content-area when we have this DOM : 

`

    <body class="">
      <div class="main-container">
        <app-root >
        <header class="header header-4">...</header>
    
        <div class="content-container">
            <router-outlet></router-outlet>
            <app-item-layout>
                <div class="content-area">...</div>
                <div class="sidenav">...</div>
             ...
`

### Reproduction of behavior
Here is the project https://rebolon.github.io/clarity-issue-sidenav/item 
And the source code is here : https://github.com/Rebolon/clarity-issue-sidenav
Just clone and run `npm install`
then `./node_modules/angular-cli/bin/ng serve`

### Environment details

* **Angular version:** 
2.1.0

* **Clarity version:** 
0.7.1

* **OS and version:** 
Windows 7
and also reproduced on github pages

* **Browser:** 
[chrome 54 | IE 11 | FF 45 ]

**Comment by Rebolon** [comment]
Here is a temporary solution : 
in the root file styles.css, i added this : 

    app-item-layout {
        display: flex;
    }

Not sure it's the right way of doing this.

**Comment by youdz** [comment]
The `<content-container>` has `display: flex`, and as such it expects the various pieces of the layout to be its direct children. The solution is generally to include more or less in the template of your custom child components: one template containing the overall layout, `<router-outlet>` inside the `.content-area` element, and child components inside the various slots of the layout.

As an example, we are using `router-outlet` ourselves in our dev test app, and it works absolutely fine.

I will let @adityarb88 give additional information if needed.

**Comment by bertofer** [comment]
I have the same problem. In my case @youdz I have nested routes in the content container, and the sidenav itself only appears in a specific component of the root router-outlet. My structure right now is something like:

```jade
div.main-container
  header
  div.content-container
    router-outlet
    route-component
      sidenav
      div.content-area
        router-outlet
    another-route-component
      div.content-area
```

Thanks @Rebolon for the solution, worked for me!

**Comment by adityarb88** [comment]
Hi @bertofer, @Rebolon: You could also assign the `.content-container` class to your custom component (`route-compenent` in the above example). Could you please check if that works? Please let us know if it doesn't. 

BTW we recently created a Plnkr link which you can use to post issues. The link to the Plnkr template is here: https://plnkr.co/edit/VPxyl7?p=preview

**Comment by Rebolon** [comment]
it doesn't seem to work for me, i'll try to use plunkr to reproduce

**Comment by satsva** [comment]
I am new to Clarity and facing the same problem. I would like the sidenav change basing on the subnav...exactly like explained below. BTW, plnkr is not working. 

> 5. Subnav as primary navigation and sidenav as secondary navigation https://vmware.github.io/clarity/documentation/navigation

**Comment by adityarb88** [comment]
@satsva: https://plnkr.co/edit/8TwwdL?p=preview this plnkr link should work. Could you please replicate it here and we can take a look at it.

**Comment by satsva** [comment]
Thanks @adityarb88 plnkr now works. Please check the below for the issue:

https://plnkr.co/edit/qaGgbGlNZM5gxn60H2tZ?p=preview

Maybe I am doing something wrong. Please let me know. Thanks!

**Comment by adityarb88** [comment]
Hi @satsva: Really sorry for the late response. I totally missed the notification that you had posted a plunkr to demo your issue. You will have to update your layout a little bit to fix this issue. I have forked your plunkr to demo this: https://plnkr.co/edit/CTxO5taTtf1vwpQxruqW?p=preview. Let me know if that helps.

Basically what I did was this:
1. Updated the app component to just have the `router-outlet` along with the header and the sub nav
2. Added the `.content-container` class to the host of the components that you are routing to.
3. Moved the `.content-area` inside of those components.

Let me know if you have any issues. I am closing your issue based on this but feel free to reopen it if this issue still persists

**Comment by lokumdev** [comment]
@adityarb88: Any chance this behavior is broken in Clarity 0.9.0? I remember your plunkr working great but  now that I have tried the layout you recommend in an Angular (4) and Clarity 0.90 app, the content-area shows below the sidenav. Thanks

**Comment by axhcypod** [comment]
I would rather shoot myself in the face than work on plunkr.. thanks for trying tho.

**Comment by water42** [comment]
@adityarb88  is moving `.content-area` into components + adding the host binding the only solution / the recommended solution? it seems like an anti-pattern but I just ran into this issue myself and can't think of anything else.

**Comment by adityarb88** [comment]
@water42: This is done to make sure that the parent is `display: flex`. If for some reason this cannot happen, then you need to make sure that you have custom classes which make the layout work properly according to the way your `.content-area` and `.sidenav` are nested.

**Comment by water42** [comment]
Thanks for the explanation
