### ISSUE TITLE
Shrink/Minimize Icon (or an inverted Resize)

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1263]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```
May I request for an icon that inverts the 'resize' icon? Instead of pointing the arrows outward, point them inwards.
I want to use it as an icon for making cards compact.

![image](https://user-images.githubusercontent.com/1977391/29010350-445e50e6-7b5d-11e7-9aef-30d38e460d4a.png)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
Hi @whizkidwwe1217, that's a good idea and thank you for the suggestion.

**Comment by mathisscott** [comment]
@lil-kim 
Could we add this to our list of icons that we are planning to add?

Thanks!

**Comment by lil-kim** [comment]
Sure! Will do.
