### ISSUE TITLE
Problem when content-container is not a direct child of main-container

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1264]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
I am making an app with header navigation and sub nav. In my header nav, I have 2 routes other than the home route. My sub nav may or may not be present in those routes. So, I included the sub nav and the content-container in their individual components. This is causing UI issues, since putting them under another component is losing the direct parent-child relationship. Any way out of this?

### Actual behavior
https://plnkr.co/edit/a6ZZGc?p=preview

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3.1

* **Clarity version:** 0.9.15

* **OS and version:** Win 10

* **Browser:** [all]

**Comment by SayakMukhopadhyay** [comment]
I just now saw the `u-main-container` uitility class. I have added that class but the problem still persists. I have updated the plunker.

**Comment by adityarb88** [comment]
@SayakMukhopadhyay: You need to make sure that `.u-main-container` is a direct child of `.main-container`. Add the class to your host component: https://plnkr.co/edit/vwdwT9VjVkYZXovP7zQ3?p=preview

**Comment by SayakMukhopadhyay** [comment]
Thanks for the quick reply. I have implemented the above fix and it works for one module but does not for another. Then I noticed that the plunker does not exactly reflect the current status of the project. I have updated the plunker at https://plnkr.co/edit/JeWtNuf0o8dno5wB3BtF?p=preview
I would be glad if I could get some help in this regard.

**Comment by adityarb88** [comment]
@SayakMukhopadhyay: Your question now is not related to Clarity but is more about Angular Routing.  It looks like you are using a click handler on links `<a (click)="makeActive('Dashboard')" class="nav-link" [ngClass]="{'active': dashboard}" href="#">Dashboard</a>` which is not the recommended way of using links. You can read more about Angular Routing here: https://angular.io/guide/router

You are loading `other.component.html` in `some.component.html` whereas it looks like you want to load either one of them depending on the route. I recommend that you ask this question on StackOverflow.

**Comment by SayakMukhopadhyay** [comment]
Thanks! the nav link click handler is something I made up for the plunker, I am using the recommended way in my project to the same effect. And I will take your advice and ask this in SO. Thanks again!
