### ISSUE TITLE
Signpost does not maintain correct arrow positioning on content update

### ISSUE THREAD

**Issue by TekSiDoT** [vmware/clarity#1265]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Signposts resize according to their content and maintain the correct positioning for the arrow to remain pointing at the signpost trigger origin

### Actual behavior
When binding signpost to variable sized content, signpost are fixed to their top-left corner position while extending / shrinking the remaining window around this position.

### Reproduction of behavior
Plunkr on request, but the behavior seems obvious enough.

### Environment details

* **Angular version:** 4.2.6

* **Clarity version:** 0.10.0-alpha.4

* **OS and version:** Windows 10 / latest

* **Browser:** [ tested in Chrome / latest, probably in all browsers ]

**Comment by adityarb88** [comment]
@TekSiDoT: Thanks for filing the issue. Its always good to have the plnkr which replicates the issue. That way we know exactly what the issue is and make sure we test that case thoroughly before merging in the fix.

**Comment by TekSiDoT** [comment]
Alright, I'll add one.

**Comment by hippee-lee** [comment]
We need a demo that replicates the use case in order to understand where `Signpost` needs changes to support resizing and dynamic content. If you can provide a [demo app](https://stackblitz.com/edit/clarity-light-theme-v11) that replicates the issue described please re-open this issue.
