### ISSUE TITLE
Fit datagrid to browser screen?

### ISSUE THREAD

**Issue by keforbes** [vmware/clarity#1266]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Expected behavior
I expected when wrapping widgets in `main-container`, `content-container`, and `content-area` the items would be restricted to fit within the visible browser area.  Instead, these containers grow as large as their contents, creating scrollbars for the entire page (even the header scrolls off).  This surprised me because `main-container` has `height:100vh` and I want all widgets to be constrained by that.  I want my datagrid to fit in the visible space using scrollbars for itself rather than growing to show all items in the datagrid.  I know there must be a simple solution without hardcoding the height of the datagrid but I'm just not seeing it in the docs.

### Actual behavior
Containers grow until all items of the datagrid are visible, forcing the entire page to have scrollbars rather than just the datagrid.

### Reproduction of behavior
https://plnkr.co/NEnPag1otG8IJmfXPeqH

### Environment details

* **Angular version:** 4.3.1

* **Clarity version:** 0.9.15

* **OS and version:** Arch Linux

* **Browser:** all

**Comment by adityarb88** [comment]
@keforbes: I am not sure if I understand the issue correctly. The header does not scroll off the screen. It sticks at the top: https://plnkr.co/edit/SUtMXbcKS54Ta1QDsJRR?p=preview

Your plunkr does not have a header in it. Could you please update the plnkr to reflect the issue you are facing?

**Comment by keforbes** [comment]
Sorry, mentioning the header was just further re-iterating the behavior.  My problem is with the datagrid.  I want the datagrid to have scrollbars.  If I hardcode the datagrid's height I can force scrollbars, but I want the datagrid to grow to the size available by the browser window and use scrollbars for the overflow.

**Comment by keforbes** [comment]
Ha! And that was it, thanks for updating my plunkr.  I had tried `<div class="header">` and `<clr-header>` but apparently `<header class="header">` fixed my scrolling issue!

**Comment by keforbes** [comment]
So changing that header syntax did fix my issue with the header scrolling off, but how do I force the datagrid height to remain within the view port of the browser?  That plunkr still scrolls the page rather than putting scrollbars on the datagrid.

**Comment by adityarb88** [comment]
You could add a height on the datagrid using css or use datagrid pagination: https://vmware.github.io/clarity/documentation/datagrid/pagination

**Comment by adityarb88** [comment]
@keforbes: CSS option: https://plnkr.co/edit/9nMkNbyHUkh8Po3f4t04?p=preview

**Comment by keforbes** [comment]
Right, but that's hardcoding the height of the datagrid.  I want it to fit in the size of the browser.  For example, as I grow and shrink the size of the browser I want the datagrid footer to remain on screen.

**Comment by adityarb88** [comment]
You could still do that using CSS: https://plnkr.co/edit/0oAHs1JrzDu47TtKPdAl?p=preview

**Comment by keforbes** [comment]
Hmm, yes, that's exactly the behavior I'm looking for.  I'm not crazy about hardcoding the height of the header in the calculation but at least it should remain constant.  I thought there was some obvious way to constrain widgets within the `content-area` but it looks like there's no escaping pixel arithmetic.  Thanks for your help, I'll use this `height: calc(100vh - 108px);` trick.

**Comment by hughanderson4** [comment]
Plunker links are broken that show the table filling up a SPA layout.  can we update these to use Stackblitz?  I need to see how that is implemented before deciding on a UI framework, as fixed-table-header is a requirement for my project.

**Comment by hippee-lee** [comment]
Hi @hughanderson4 - we switched over to using Stackblitz a while ago. You can find a list of links for apps using different versions of Clarity here: https://vmware.github.io/clarity/documentation/v0.13/get-started

Its best not to comment on closed issues as it might not get noticed or answered right away.
