### ISSUE TITLE
New angular application not using Clarity framework

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#1267]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I created a new Angular application per the instructions at https://angular.io/guide/quickstart. I then immediately added the Clarity framework components as outlined on the Get Started web page and added references to my index.html file pointing them to where clarity is installed in my app (/node_modules), and added a reference to the ClairtyModule in the app.module.ts file per the setup instructions. I then executed my new app, having made no additional changes and I expect the new angular app to load the clarity stylesheets and js files .

### Actual behavior
I get 'Failed to load resource: the server responded with a status of 404 (Not Found)' for each css or js reference in the index.html file. Why is this happening? I followed these instructions in the past of other sample apps without issue but now any new apps are breaking. My reference to the location in the /node_modules folder should be correct.

See enclosed screens shots for detail. 

![browser](https://user-images.githubusercontent.com/27329476/29053451-04733d14-7ba5-11e7-9fea-3e866a2c3791.jpeg)
![index_html](https://user-images.githubusercontent.com/27329476/29053452-0473e99e-7ba5-11e7-86d8-5fad9fc5dc09.jpeg)
![package_json](https://user-images.githubusercontent.com/27329476/29053453-0479d0c0-7ba5-11e7-8f6e-8951d36a2358.jpeg)

### Reproduction of behavior
NA

### Environment details

* **Angular version:** 4.3

* **Clarity version:** 
.9.16
* **OS and version:** 
MacOS 10.12.6
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Why are you using relative paths when you are running a local server and have defined a base href?

Most likely you've built your app in a dist folder and the relative paths are no longer correct.

**Comment by coldhamix** [comment]
You should be including your scripts not in the index.html directly, but in the corresponding _styles_ and _scripts_ in **.angular-cli.json**.
