### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError in Header component

### ISSUE THREAD

**Issue by coldhamix** [vmware/clarity#1268]
**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No errors should be produced.

### Actual behavior
I am trying to encapsulate the sidebar into its own component. When I'm adding `[clr-nav-level]` property to it, an `ExpressionChangedAfterItHasBeenCheckedError` happens in `clr-header` component. If we reverse the order of `clr-header` and `my-sidebar` so that `clr-header` appears after `my-sidebar` everything works as expected.

### Reproduction of behavior
https://plnkr.co/edit/2gDsu1AX4pU1os8rKeKQ?p=preview

### Environment details

* **Angular version:** 4.3.2

* **Clarity version: latest** 

* **OS and version: all** 

* **Browser: all**

**Comment by adityarb88** [comment]
@coldhamix: Please use this as a workaround for now: https://plnkr.co/edit/KgJBKNzeg5Py7ffAqZZ7?p=preview but we will take a look and get back to you.

**Comment by coldhamix** [comment]
@adityarb88 Did not work for me as I my sidebar is nested one more level deeper, but still thanks for the workaround and waiting for the issue to get resolved

**Comment by mathisscott** [comment]
@adityarb88 ^

**Comment by coldhamix** [comment]
@mathisscott @adityarb88 Will this at least be fixed when the Header component is ready?

**Comment by coldhamix** [comment]
@mathisscott I'd like to contribute if possible

**Comment by mathisscott** [comment]
Sure, @coldhamix !

With these EHCAIWC errors, much of the work is actually tracking down the value that is causing the error. Angular's error messages are usually not helpful with that.

After you find the value, it's then a question of whether we need to move the changing of the value to later in the lifecycle or if we need to use either our custom way of handling these errors or by using something like setTimeout.

Once you've identified where the error is happening, you can post back here and we can point you in the right direction if you need us to.

**Comment by coldhamix** [comment]
@mathisscott I just found out where the issue happens. It's `clr-header` component in `layout/nav/header.ts` in method `initializeNavTriggers`.

```
navList.forEach(function (navLevel) {
    if (navLevel === ClrResponsiveNavCodes.NAV_LEVEL_1) {
        this.isNavLevel1OnPage = true;
    }
    else if (navLevel === ClrResponsiveNavCodes.NAV_LEVEL_2) {
        this.isNavLevel2OnPage = true;
    }
});
```

It is invoked in an observable which gets subscribed on `ngOnOnit`.

```
ngOnInit() {
    this._subscription = this.responsiveNavService.registeredNavs.subscribe({
        next: (navLevelList: number[]) => {
            this.initializeNavTriggers(navLevelList);
        }
    });
}
```

I tried to move it later in the lifecycle, to `ngAfterContentInit` (did not help) and `ngAfterViewInit` (no error message, but the callback is never called).

What really helps avoiding this error is wrapping ```this.isNavLevel1OnPage = true``` and ```this.isNavLevel2OnPage = true``` into setTimeout, though it looks a bit hacky to me.

**Comment by mathisscott** [comment]
Thank you for doing that investigation, @coldhamix!

@adityab88 and @youdz 
Is this something we should wrap in an Oompa Loompa?

**Comment by adityarb88** [comment]
@mathisscott: I am taking a look at this and will post an update here soon.

**Comment by adityarb88** [comment]
Update: Have submitted a PR for the fix. Waiting for reviews.

**Comment by coldhamix** [comment]
@mathisscott @adityarb88 did that land into 0.10.8?

**Comment by adityarb88** [comment]
@coldhamix This is going in 0.10.9 which is next week. Will be merged into master this week.
