### ISSUE TITLE
Signpost cannot be closed programmatically

### ISSUE THREAD

**Issue by spacegospod** [vmware/clarity#1269]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Opening a clr-signpost should update the flag passed to the clrIfOpen directive on that signpost

### Actual behavior
I have a signpost to which I have applied clrIfOpen. I expect the boolean flag I have passed to clrIfOpen to be updated when I open/close the signpost.
https://vmware.github.io/clarity/documentation/signposts
https://plnkr.co/edit/zSUYLU

### Reproduction of behavior
Refer to:
https://plnkr.co/edit/zSUYLU

### Environment details

* **Clarity version: 0.9.12**  

* **OS and version: Windows 10** 

* **Browser: all**

**Comment by spacegospod** [comment]
I forgot one thing:
I also tried the clrIfOpenChange output on clrIfOpen but it too is not triggered when the signpost is opened

**Comment by adityarb88** [comment]
@spacegospod: https://plnkr.co/edit/2J3ScJ0WC1gk9s1CVIXQ?p=preview Did you try this?
With structural directives you have to use the de-sugared syntax to use the Output Emitter:

```
<clr-signpost>
  <ng-template [(clrIfOpen)]="isOpen">
    <clr-signpost-content>
      <p>I am an awesome signpost</p>
      <span>{{isOpen}}</span>
    </clr-signpost-content>
  </ng-template>
</clr-signpost>
```

Closing based on this. Please feel free to reopen the issue if you have any questions/feedback.

**Comment by spacegospod** [comment]
Thank you for the swift reply! I will try it
