### ISSUE TITLE
Template parse errors: Can't bind to 'clrTooltipDirection' - with Clarity 0.10.0-rc.1

### ISSUE THREAD

**Issue by srikanthps** [vmware/clarity#1275]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Tooltip angular component when used from [documentation page](https://vmware.github.io/clarity/documentation/tooltips), should work without errors

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

Following the documentation of GitHub page, I installed clarity using commands such as:
npm install clarity-angular --save

packge.json has 

    "clarity-angular": "^0.10.0-rc.1",
    "clarity-icons": "^0.10.0-rc.1",
    "clarity-ui": "^0.10.0-rc.1",

Used below snippet to test out tooltip

    <clr-tooltip [clrTooltipDirection]="'top-right'" [clrTooltipSize]="'xs'">
        <clr-icon shape="info-circle" size="24"></clr-icon>
        <clr-tooltip-content>
            <span>Lorem</span>
        </clr-tooltip-content>
    </clr-tooltip>

Empty page is displayed - browser console shows below error:

```
Uncaught Error: Template parse errors:
Can't bind to 'clrTooltipDirection' since it isn't a known property of 'clr-tooltip'.
1. If 'clr-tooltip' is an Angular component and it has 'clrTooltipDirection' input, then verify that it is part of this module.
2. If 'clr-tooltip' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
</span>

```

If I switch to clarity 0.9.0 as found in[ clarity-seed project](https://github.com/vmware/clarity-seed/blob/master/package.json), then, things work fine.

Similar issue observed with few other components as well, for example, below code too errors out.

    <clr-tree-node [(clrTreeNodeExpanded)]="expanded">
        {{expanded ? "I am expanded" : "I am collapsed"}}
    
        <clr-tree-node>
            Child Tree Node
        </clr-tree-node>
    </clr-tree-node>

### Environment details

* **Angular version:** ^4.0.0.

* **Clarity version:**  ^0.10.0-rc.1

* **OS and version:**  Windows 7 Enterprise

* **Browser:** all

**Comment by Shijir** [comment]
@srikanthps you might have missed importing `ClarityModule`?

**Comment by srikanthps** [comment]
I have Clarity module imported.

  imports: [
    BrowserAnimationsModule,
    BrowserModule,
    ClarityModule.forRoot()
  ],

Also, I missed to mention that in same HTML, I have clarity data grid just working fine.
So, its not a setup issue.  My guess is something is broken in rc1 release.
If I switch back to older version of clarity 0.9.0, everything works without any issues.

**Comment by adityarb88** [comment]
@skathiresan: 0.10.0 has a breaking change for popovers (Tooltips, Signposts and Dropdowns). Please refer to the release notes for migrating to the new API: https://vmware.github.io/clarity/news/0.10.0-rc.1
