### ISSUE TITLE
Spacing issue when clr-signpost is used in a clr-dg-column

### ISSUE THREAD

**Issue by KevinABoucher** [vmware/clarity#1279]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
A consistent header height should be maintained even if a signpost help is placed in a grid header.

### Actual behavior
See extra spacing in grid header here:
https://plnkr.co/edit/btfNdRKbXh6kq9C3G3gL?p=preview

### Reproduction of behavior

https://plnkr.co/edit/btfNdRKbXh6kq9C3G3gL?p=preview

### Environment details

* **Angular version:** 
@angular/cli: 1.2.7
node: 8.2.1
os: win32 x64
@angular/cli: 1.2.7

* **Clarity version:** 

* **OS and version:** 

* **Browser:** 
Chrome

**Comment by harshabhat86** [comment]
Any idea if this is taken care of? I think this issue still exists.

**Comment by mathisscott** [comment]
@harshabhat86 
This has not been resolved yet. The team is working on other priorities at the moment. This has been marked as "Help Wanted" if anyone in the community was interested in picking it up.

**Comment by hippee-lee** [comment]
Updated StackBlitz for this issue: https://stackblitz.com/edit/datagrid-header-signpost-spacing-issue-1279
