### ISSUE TITLE
Create webhooks for PR approval requirements

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1281]
## Issue / Requirements

1. We would like to disable the merge button if a pull request has the `DO-NOT-MERGE` label on it.
2. We would like to disable a PR merge button if it does not have two approvals / :shipit:'s on it

## Proposal
This can be done by writing a custom webhook to use the [Github Developer API](https://developer.github.com/v3/) to check for the labels applied as well as the number of approvals and returns the correct status. 

**Note**: The service will have to be hosted internally, similar to how the `clabot` is set up. 

## Resources
- https://developer.github.com/v3/pulls/reviews/
- https://developer.github.com/v3/repos/statuses/
- https://developer.github.com/v3/pulls/
- https://stackoverflow.com/questions/35405647/automatically-check-that-pull-request-has-a-label-before-merging/35407250#35407250

**Comment by gnomeontherun** [comment]
@hippee-lee do we still need this? We have GitHub blocking PRs without two :shipit: and our labels should indicate pretty clearly not to merge without a hook?

**Comment by hippee-lee** [comment]
Nope, This was added before I realized we could change the required number of shippits.
