### ISSUE TITLE
UnMET Dependancy

### ISSUE THREAD

**Issue by callen5914** [vmware/clarity#1284]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

To install correct at the command line

### Actual behavior

I get this instead:

├── UNMET PEER DEPENDENCY @webcomponents/custom-elements@1.0.0
└─┬ clarity-icons@0.10.0 
  └── dompurify@0.9.0 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
Hi @callen5914, to be able to help you better and resolve this issue, we need information on the context.

**Comment by mathisscott** [comment]
@callen5914 
We haven't heard back on this. I'm assuming it's resolved on your end.
