### ISSUE TITLE
Icons in iOS are not displayed.

### ISSUE THREAD

**Issue by ildarnm** [vmware/clarity#1289]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When use clr-icon should showing icon.

### Actual behavior
In iOS didn't appears icons.

Simulator IPad Air  iOS 8.3
![untitled](https://user-images.githubusercontent.com/5478655/29226968-b3613e4a-7edc-11e7-967a-fdbaa0cb1b08.png)

Simulator IPhone 6S
![untitled2](https://user-images.githubusercontent.com/5478655/29226967-b3601740-7edc-11e7-8f92-bd96d63690e3.png)

### Reproduction of behavior
go to https://vmware.github.io/clarity/documentation/iconography on iOS

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [ iOS Chrome | iOS XX Safari ]

**Comment by Shijir** [comment]
hmm weird. I've just tested the iconography page on both Chrome and Safari browsers in iOS. Looks like you are running in the simulator. 

![img_0674 2](https://user-images.githubusercontent.com/3958008/29228294-11fcae70-7e8e-11e7-9414-8ef493037a17.PNG)
![img_0676](https://user-images.githubusercontent.com/3958008/29228293-11fa8866-7e8e-11e7-8027-ab98618bff9d.PNG)

**Comment by Shijir** [comment]
Also, in your first screenshot, the whole format of the page looks broken.

**Comment by Shijir** [comment]
The page on XCode iPhone SE -iOS 10.3 Simulator looks like this:
<img width="356" alt="screenshot 2017-08-11 12 13 18" src="https://user-images.githubusercontent.com/3958008/29228475-b666e9a8-7e8e-11e7-9acd-56c10866bcdf.png">

**Comment by ildarnm** [comment]
it is reproduced in iOS 9.3

**Comment by ildarnm** [comment]
@Shijir in console "attempted to assign to readonly property"

**Comment by adityarb88** [comment]
@ildarnm: Could you please update to the latest 0.9 or 0.10 versions and see if you can replicate the issue?

**Comment by Shijir** [comment]
@ildarnm sorry for the delay. I was finally able to reproduce the error. Looks like the error is caused because Safari's HTMLElement.prototype.constructor is `readonly`. We might need to tweak our custom element handling in Clarity Icons to resolve this issue. Thanks for catching and reporting this error.

**Comment by nbewley** [comment]
+1

Also noticed this issue Safari 9.1. See attached:

![safari9 1](https://user-images.githubusercontent.com/29443623/29330794-37cc31f6-81af-11e7-8982-1d91c4c8cdb8.png)
