### ISSUE TITLE
clr-dropdown doesnt close all dropdown menus when a nested menu item is clicked

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#1292]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If a dropdown has multiple levels and a user clicks on a menu item in any of the levels, the whole menu system should close.

### Actual behavior
Only the menu content of the clicked item and all after that are closed right now. does not close the whole dropdown

### Reproduction of behavior
Can be seen on the site itself Click on the angular dropdown button then link1 then bar then baz.
the menu system till foo and bar is not closed

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
0.10.0

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@envyN: Thanks for reporting this. I do believe that all the menus should close when an item is clicked but we will get a confirmation from our UX team on the correct behavior and then decide what needs to be done based on their input. cc: @mathisscott, @reddolan

**Comment by mathisscott** [comment]
@adityarb88 
The only instance where a dropdown menu should not close when an item is clicked is when an item is a form input. Think about clicking on a checkbox or radio button inside a dropdown.

Everytime a user clicks on a navigational element inside a dropdown menu, it should close all menus.

**Comment by reddolan** [comment]
@adityarb88 I second @mathisscott's comment. All menus should close when a selection is made.

**Comment by jeeyun** [comment]
Hmm this looks like a regression bug of some sort. It used to close all menus. I am able to reproduce on our doc site.

**Comment by reddolan** [comment]
I was able to reproduce as well
