### ISSUE TITLE
Tooltip Delay before showing

### ISSUE THREAD

**Issue by manndave** [vmware/clarity#1293]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
Add a parameter to the Tooltip that allows developers to specify a delay before the Tooltip is shown.  This can help the Tooltips from popping up and immediately disappearing when users just run their mouse across the screen.
Even just fixed options of, for example, Slow/Medium/Fast that delay for a fixed amount of time would be good.

Thanks!

**Comment by Rush** [comment]
Anybody have a solution for this?

**Comment by creadicted** [comment]
Would that not 'just' need a integration of a timer and a check if the focus was left while the timer called. 

``` typescript
@HostListener('focus')
  showTooltip(): void {
      this.show(this._showDelay)
  }
  
show(delay: number): void {
    // Leaving the hover should cancel the tooltip if there is a delay in showing.
    // don't know the architecture of clarity. Do you have general component change check helper method ? 
    this._showTimeoutId = setTimeout(() => {
      this.ifOpenService.open = true;
    }, delay);  
```

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
