### ISSUE TITLE
Datagrid: column widths change abruptly when expandable rows are used

### ISSUE THREAD

**Issue by soumyakantiroychowdhury** [vmware/clarity#1294]
[x ] bug
[ ] feature request
[ x] enhancement

Problem: When expandable rows are used, datagrid column widths change abruptly.

Initially when expandable rows are not used:

![image](https://user-images.githubusercontent.com/14230950/29246307-34d8487e-8013-11e7-82ae-1f563890e326.png)

### Actual behavior
When expandable row is enabled:

![image](https://user-images.githubusercontent.com/14230950/29246304-0a850ada-8013-11e7-8241-0b9bd82cd0d0.png)

### Reproduction of behavior
https://plnkr.co/edit/2H6vC0?p=preview

### Environment details

* **Angular version:** 4.2.X

* **Clarity version:** 0.10.0

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

### Additional Query
Can I set the column widths to fixed values when the datagrid is initialized? For example: 30% to the Name column, 20% to the Created On column etc.

**Comment by youdz** [comment]
There seems to be a bug where the column sizer tries to size the "caret" column, but then ignores it when assigning width. Really strange, I'm not sure when this was introduced.

Thanks for reporting this.

**Comment by ibuler** [comment]
Me too

**Comment by soumyakantiroychowdhury** [comment]
Thanks. Can you please answer this question:

"Can I set the column widths to fixed values when the datagrid is initialized? For example: 30% to the Name column, 20% to the Created On column etc."

Is there any option to do so? If there is, then the present issue can be circumvented for the time being.

**Comment by youdz** [comment]
You can do this in CSS, but I would recommend using pixel or `rem` values rather than percentage.
Just set the width of the `<clr-dg-column>` element either directly on it or through the CSS styles.

**Comment by marcelocarmona** [comment]
![error](https://user-images.githubusercontent.com/4614400/31033254-b9ffc0f8-a535-11e7-836b-a74fbfad8cfe.gif)

I found something similar, but with the columns name, its related when the column name is long and we have sorting and filtering.

https://plnkr.co/edit/9fM3inCXvPar2D33hOeX?p=preview
