### ISSUE TITLE
Datagrid-selection - select by clicking on row

### ISSUE THREAD

**Issue by ninodinatale** [vmware/clarity#1297]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Expected behavior

I can manually remove the checkboxes if I want to select a row by clicking on it, and not the checkboxes only.

### Actual behavior

By clicking on a row I am setting the selected item manually. This works fine. Now I wanted to remove the checkbox column. How can I accomplish this?

**Comment by youdz** [comment]
Duplicate of #476.
