### ISSUE TITLE
"vendor_... is not defined" when using with webpack

### ISSUE THREAD

**Issue by k-vekos** [vmware/clarity#1299]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Followed instructions in README.md for setup. Expect this to work.

### Actual behavior
Webpack executes successfully but when viewing site in Google Chrome these two error messages appear:

    vendor.js?v=WMbml6YqKoNIxvh2zbuqtXNEobqufybZaaMaLrCbVQ0:91154 Uncaught SyntaxError: Unexpected token &&
    ..\..\external "vendor_d9ee53424a5de1f76937":1 Uncaught ReferenceError: vendor_d9ee53424a5de1f76937 is not defined
        at Object.<anonymous> (..\..\external "vendor_d9ee53424a5de1f76937":1)
        at __webpack_require__ (bootstrap 0f15c52264409311598b:657)
        at fn (bootstrap 0f15c52264409311598b:85)
        at Object.defineProperty.value (eventsource.js from dll-reference vendor_d9ee53424a5de1f76937:1)
        at __webpack_require__ (bootstrap 0f15c52264409311598b:657)
        at fn (bootstrap 0f15c52264409311598b:85)
        at Object.<anonymous> (main.js?v=Q2SpoAUjDRAdYB2XsjYbrwz0GsmhM0WmoMGI2tUvcjU:264709)
        at __webpack_require__ (bootstrap 0f15c52264409311598b:657)
        at Object.setPrototypeOf.__proto__ (bootstrap 0f15c52264409311598b:706)
        at bootstrap 0f15c52264409311598b:706
    (anonymous) @ ..\..\external "vendor_d9ee53424a5de1f76937":1
    __webpack_require__ @ bootstrap 0f15c52264409311598b:657
    fn @ bootstrap 0f15c52264409311598b:85
    Object.defineProperty.value @ eventsource.js from dll-reference vendor_d9ee53424a5de1f76937:1
    __webpack_require__ @ bootstrap 0f15c52264409311598b:657
    fn @ bootstrap 0f15c52264409311598b:85
    (anonymous) @ main.js?v=Q2SpoAUjDRAdYB2XsjYbrwz0GsmhM0WmoMGI2tUvcjU:264709
    __webpack_require__ @ bootstrap 0f15c52264409311598b:657
    Object.setPrototypeOf.__proto__ @ bootstrap 0f15c52264409311598b:706
    (anonymous) @ bootstrap 0f15c52264409311598b:706

### Reproduction of behavior

I am using the [ASP.NET Core Angular Template](https://github.com/aspnet/JavaScriptServices/).

**package.json:**
```
 ...
"@webcomponents/custom-elements": "^1.0.0-alpha.3",
"clarity-angular": "^0.10.0",
"clarity-icons": "^0.10.0",
"clarity-ui": "^0.10.0",
...
```

**webpack.config.vendor.js:**
```
...
entry: {
	vendor: [
		...
		
		'clarity-icons/clarity-icons.min.css',
		'clarity-ui/clarity-ui.min.css',
		'@webcomponents/custom-elements/custom-elements.min.js',
		'clarity-icons/clarity-icons.min.js',
		'clarity-angular'
		
		...
	]
}
...
```
Very likely related to these other issues:
https://github.com/vmware/clarity/issues/947
https://github.com/vmware/clarity/issues/1166

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.10.0

* **Browser:** Chrome

**Comment by kapr1k0rn** [comment]
I am using Clarity with the ASP.NET Core Angular Template too, had some issues to make them work together but eventually I made it. 
my webpack.config.vendor.js is like this 
               
              ` '@webcomponents/custom-elements',
                'clarity-icons/clarity-icons.min.css',
                'clarity-icons',
                'clarity-ui/clarity-ui.min.css',`
and I don't have 'clarity-angular' in  webpack.config.vendor.js (can't remember why though)，also make sure you run `node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js` before you run the project.

**Comment by k-vekos** [comment]
@kapr1k0rn thanks! Using this configuration fixed the issue for me.

**Comment by dtruel** [comment]
I ran into this issue when copying and pasting from a boilerplate project to an existing one.  The problem was I forgot to copy _Layout.cshtml which included the vendor.js script.  Including the vendor.js script fixed it for me.
