### ISSUE TITLE
Problems with Header dropdown

### ISSUE THREAD

**Issue by gperdomor** [vmware/clarity#1300]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Right header dropdown should be aligned aligned properly, like this:
<img width="892" alt="screen shot 2017-08-14 at 5 22 36 pm" src="https://user-images.githubusercontent.com/371939/29290125-57c9058c-8115-11e7-8bd3-f2f6bd17e6c5.png">

### Actual behavior

<img width="979" alt="screen shot 2017-08-14 at 5 22 25 pm" src="https://user-images.githubusercontent.com/371939/29290174-7c7d1044-8115-11e7-934f-afaf98dbddb8.png">
<img width="911" alt="screen shot 2017-08-14 at 5 22 18 pm" src="https://user-images.githubusercontent.com/371939/29290177-7ecb50fe-8115-11e7-983f-c256bb9cfaf6.png">

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** https://vmware.github.io/clarity/ so I guess 0.10.0

* **OS and version:** macOS Sierra 10.12.6

* **Browser:** Tested on Chrome 60, Safari 11

**Comment by adityarb88** [comment]
@gperdomor: Thanks for raising this issue. This looks like an error in the documentation and not actually with the component. We will get this fixed as soon as possible.

**Comment by ninodinatale** [comment]
Just adding this in case you haven't noticed and someone else is struggling: In the docs for a clr-dropdown example in the header:
`           <clr-dropdown [clrMenuPosition]="'bottom-right'">
               // ...
            </clr-dropdown>
`

Seems that the property `clrMenuPosition` was removed. Instead, `<clr-dropdown-menu>` has now the property  `clrPosition`.
