### ISSUE TITLE
Customers would like to have a dropdown or select that can be filtered

### ISSUE THREAD

**Issue by bbronson** [vmware/clarity#1302]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
Dropdown can be filtered by keywords

### Actual behavior
The Clarity website prescribes using a normal html select box https://vmware.github.io/clarity/documentation/select-boxes. This cannot be filtered. It is true that you can type and get a certain element but our PM and customers want a dropdown like component that can be filtered.

For employees the high touch beta feature request is also visible here: https://bugzilla.eng.vmware.com/show_bug.cgi?id=1922025

### Reproduction of behavior
Its reproducible here https://vmware.github.io/clarity/documentation/select-boxes

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.10.0

* **OS and version:** Mac 10.11.6

* **Browser:** all

**Comment by adityarb88** [comment]
@bbronson: Thanks for the feedback! We already have a ticket filed for this: https://github.com/vmware/clarity/issues/248

Closing this as a duplicate. Please subscribe to #248 for more updates.
