### ISSUE TITLE
Content of the Stack View doesn't overflow correctly in Firefox

### ISSUE THREAD

**Issue by matonev** [vmware/clarity#1304]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The expectation is the text to overflow on new line.

### Actual behavior
The text doesn't overflow and a scroller appears, because the text goes outside of the content.
This is reproducible only in Firefox.
![image](https://user-images.githubusercontent.com/31008054/29307638-5a864d3e-81ab-11e7-8fcc-c1e9958db55d.png)

### Reproduction of behavior
https://plnkr.co/edit/qdO0U7LCAOZciWm8eSHX?p=preview

### Environment details

* **Clarity version:** 
v0.10.0-patch 

* **OS and version:** 
Windows 10

* **Browser:**
Firefox 54.0.1 (64-bit) - Currently Latest

**Comment by adityarb88** [comment]
@matonev: Thanks for raising this issue. I can replicate it on firefox. We will take a look and get back to you soon.
