### ISSUE TITLE
Update Browser & Device Support docs

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1308]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Clearer documentation on what browsers we support. 

### Questions to answer
- How do we define a version? Should this be release or something else?
- We show that we support mobile devices
  - Does this mean that we also support all of the listed browsers that are available on mobile devices?
  - Is this all mobile devices?

### Actual behavior
As of now, we say
> Clarity only supports the latest two versions of the listed browsers, with the exception of Internet Explorer.

We are getting questions/issues on support for Safari 9.1 and Mobile Safari. 

### Reproduction of behavior
![image](https://user-images.githubusercontent.com/1858226/29331067-1ceef516-81b0-11e7-87c3-61db467e1a31.png)

### Environment details

* **Clarity version:** 0.10.0

* **Browser:** all

**Comment by mathisscott** [comment]
We should try to get this into the 4.0 website work. I think it involves a different graphical treatment and not much else. #4005

**Comment by gnomeontherun** [comment]
We've revised our documentation with the new website for more depth and it is available now.
