### ISSUE TITLE
clarity-icons.min.js has runtime error in Safari 9 hence icons are not displayed

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#1310]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
clarity-icons.min.js runs properly and the icons are shown correctly in Safari 9

### Actual behavior
Error is shown in Safari's console:

```
TypeError: Attempted to assign to readonly property.
```

it was occurred in the following code:

```
}), exports.ClarityIconElement = ClarityIconElement, ClarityIconElement.observedAttributes = ["shape", "size"], ClarityIconElement.prototype = Object.create(HTMLElement.prototype), ClarityIconElement.prototype.constructor = ClarityIconElement;
```

And then no icons are shown on the page.

<img width="622" alt="screen shot 2017-08-16 at 5 00 45 pm" src="https://user-images.githubusercontent.com/6769465/29355753-d09a40e4-82a4-11e7-9129-8de8284af026.png">
<img width="1141" alt="screen shot 2017-08-16 at 5 01 15 pm" src="https://user-images.githubusercontent.com/6769465/29355761-d6ecb0bc-82a4-11e7-8c9a-f6767b72b201.png">

### Reproduction of behavior
I have already introduce custom-elements@1.0.0 and mutationobserver-shim@0.3.2.
If a working plunker is really needed I will try build one later (Currently I am within a corporation network and have difficulty access https://unpkg.com/reflect-metadata@0.1.3/Reflect.js, which is needed for that plunker)

### Environment details

* **Angular version:** 4.3.4

* **Clarity version:** 0.10.0

* **OS and version:** OS X EI Capitan 10.11.4

* **Browser:** [ Safari 9.1 ]

**Comment by adityarb88** [comment]
@shijir is the a duplicate for #1289

**Comment by adityarb88** [comment]
actually I just verified that it is. Closing this as duplicate. Please subscribe to #1289 for more updates.

**Comment by h657070128** [comment]
Thanks @adityarb88 . Glad to see it is already being handled.
