### ISSUE TITLE
Add new icon for group of documents or files

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#1311]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Could you please add the new icon in essential shapes for group of documents or files? It might look like icon for tags or users.

### Actual behavior
There are no icon for group of documents of files now.

### Environment details

* **Angular version:** 4.3.X

* **Clarity version:** 0.10.0-alpha.6

* **OS and version:** Windows 10

* **Browser:** all

**Comment by Shijir** [comment]
@lil-kim Is it possible to include the requested icons above in our additional upcoming icons?

**Comment by belyan** [comment]
Thank you!
