### ISSUE TITLE
[ng] alignment for dropdown's nested menu is wrong

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#1312]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The dropdown's nested menu should have an overlap of 4px and the nested item should align with one of the parent items.

### Actual behavior

Alignment is off on the Angular component. See screenshots for reference:

#### static
![screen shot 2017-08-16 at 10 01 25 am](https://user-images.githubusercontent.com/1827742/29376035-026ee356-826c-11e7-9191-d3de2044f7e9.png)

#### angular
![screen shot 2017-08-16 at 10 01 17 am](https://user-images.githubusercontent.com/1827742/29376029-fea6f952-826b-11e7-87a2-88c8224b828a.png)

### Reproduction of behavior
Compare static and angular versions on our website:
https://vmware.github.io/clarity/documentation/dropdowns#examples

### Environment details

* **Angular version:** 4.3.X

* **Clarity version:** 0.10.0-rc1 or above

* **OS and version:** all

* **Browser:** all

**Comment by youdz** [comment]
It's the set of selectors starting https://github.com/vmware/clarity/blob/master/src/clarity-angular/popover/dropdown/_dropdown.clarity.scss#L292 that we don't have anymore for the Angular version of the dropdown. My bad for missing this.

**Comment by jewway** [comment]
**1.the overlap of 4px**
I try the way below to fix it, but it need hard code  clrposition attribute. 

```sass
    //Directions
    .dropdown {
        // nested dropdown (submenu)
        .dropdown {
            .dropdown-menu {
                border-color: $clr-dropdown-child-border-color;
                position: absolute;
            }

            [clrposition="right-bottom"] {
                margin-bottom: $clr-dropdown-submenu-vertical-margin;
                margin-left: $clr-dropdown-submenu-overlap-margin;
            }

            [clrposition="left-bottom"] {
                margin-bottom: $clr-dropdown-submenu-vertical-margin;
                margin-right: $clr-dropdown-submenu-overlap-margin;
            }
        }
    }
```

Another solution : Add directions class on clr-dropdown component in runtime.
![image](https://user-images.githubusercontent.com/3501899/39507291-d9500584-4e0f-11e8-8d6d-e5d0332ff03a.png)

I am not sure have any better solution.

**2.the nested item should align with one of the parent items**
Have more clear example or picture to show align result ?

**Comment by gnomeontherun** [comment]
@mathisscott I'm pinging you as you start to think about dropdowns that this is a known issue in Angular. 

The workaround here would be to either use the CSS dropdowns or override some of the Angular dropdowns.

There is a workaround available for this issue, and we recommend using it for Clarity Angular. Given we are starting to work on this component with Clarity Core, we don't anticipate investing in this given how stale it is. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, this issue won’t be an issue. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
