### ISSUE TITLE
Vertical Nav: Error when collapsing vertical nav groups

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1324]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Should be able to collapse expand vertical nav and should also be able to collapse/expand nav groups without errors.
### Actual behavior

I'm getting this error when click on the collapse button of the vertical nav or when clicking the collapse button of one of the collapsible nav group .
![image](https://user-images.githubusercontent.com/1977391/29439410-edc2e08a-83ef-11e7-95b5-90a77c9d49de.png)
Here's my code (but it also doesn't work even using the samples in the docs or even removing the router links):
```
<clr-vertical-nav [clrVerticalNavCollapsible]="collapsible" [(clrVerticalNavCollapsed)]="collapsed">
    <ng-container *ngFor="let page of pages | async" >
        <clr-vertical-nav-group *ngIf="page.subPages.length > 0" routerLinkActive="active">
            <a clrVerticalNavLink routerLinkActive="active" routerLink="{{page.route}}" [routerLinkActiveOptions]="{exact:true}">
                <clr-icon clrVerticalNavIcon [attr.shape]="page.icon && page.icon !== '' ? page.icon : 'user'"></clr-icon>
                {{page.name}}
            </a>

            <clr-vertical-nav-group-children *clrIfExpanded="true">
                <a clrVerticalNavLink *ngFor="let subPage of page.subPages"
                    routerLink="{{subPage.route}}"
                    routerLinkActive="active">
                    {{subPage.name}}
                </a>
            </clr-vertical-nav-group-children>
        </clr-vertical-nav-group>

        <a *ngIf="page.subPages.length === 0" clrVerticalNavLink routerLink="{{page.route}}" routerLinkActive="active">
            <clr-icon clrVerticalNavIcon [attr.shape]="page.icon && page.icon !== '' ? page.icon : 'user'"></clr-icon>
            {{page.name}}
        </a>
    </ng-container>
</clr-vertical-nav>
```
After the errors show up, collapse button stops working and you cant uncollapse/expand the nav groups.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

I can't reproduce it in plunkr but I attached my project in this link: [https://1drv.ms/u/s!AtSLmRewLjqRk_trUBaHr-7TbCZrEA](https://1drv.ms/u/s!AtSLmRewLjqRk_trUBaHr-7TbCZrEA) I don't know if I'm missing something. Do you guys have any idea on this?
### Environment details

* **Angular version:** 4.2.6

* **Clarity version:** 0.10.1

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@whizkidwwe1217: Which version of Angular are you using?

**Comment by whizkidwwe1217** [comment]
@adityarb88  I'm using Angular 4.2.6
dependencies": {
    "@angular/animations": "4.2.6",
    "@angular/cli": "^1.3.0",
    "@angular/common": "4.2.6",
    "@angular/compiler": "4.2.6",
    "@angular/core": "4.2.6",
    "@angular/forms": "4.2.6",
    "@angular/http": "4.2.6",
    "@angular/platform-browser": "4.2.6",
    "@angular/platform-browser-dynamic": "4.2.6",
    "@angular/router": "4.2.6",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.4",
    "@ngrx/store": "^2.2.3",
    "@webcomponents/custom-elements": "^1.0.0-alpha.3",
    "clarity-angular": "^0.10.1",
    "clarity-icons": "^0.10.1",
    "clarity-ui": "^0.10.1",
    "core-js": "^2.4.1",
    "intl": "^1.2.5",
    "lodash": "4.17.4",
    "modernizr": "^3.5.0",
    "moment": "^2.18.1",
    "mutationobserver-shim": "^0.3.2",
    "prismjs": "^1.6.0",
    "rxjs": "^5.4.2",
    "wijmo": "third_party/wijmo/npm_images/wijmo-amd-min",
    "zone.js": "0.8.6"
  },

**Comment by adityarb88** [comment]
@whizkidwwe1217: Could you please upgrade to the latest angular (4.3 or above) and let us know if the issue still exists?

**Comment by whizkidwwe1217** [comment]
@adityarb88 Thanks. I upgraded to Angular 4.3.5 and the error is now gone.

**Comment by adityarb88** [comment]
Thats awesome. Closing the issue based on this.
