### ISSUE TITLE
Icons vol. 8

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1330]
Per issues attached, we are looking to include:

• a magic wand in Media <= this is used frequently in image editing and word processing apps
• a DNA helix in Technology
• shrink/minimize in Essentials
• an eCheck icon in Commerce
• any international currency icons we feel are lacking in Commerce
• an icon for a group of documents
• an icon for a group of files
• an icon for email/tweet/post attachments
• an icon for deploy in Technology (added by lilkim 8/30/17)

**Comment by lil-kim** [comment]
I moved #1453 of this epic to vol9 icons (#1518)
All other requested icons are attached:
[vol8_icons.zip](https://github.com/vmware/clarity/files/1338907/vol8_icons.zip)
Ready for implementation, @mathisscott
