### ISSUE TITLE
Icons to add to Clarity iconography

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#1331]
**Select one ...**  (check one with "x")
```
[ ] bug
[ x ] feature request
[ ] enhancement
```
### Please add the attached three cloud icons to Clarity Iconography 
[cloud icon set.zip](https://github.com/vmware/clarity/files/1235584/cloud.icon.set.zip)
Would be great if it's added in time for VMworld - @nbewley can provide more specific timeline.
Requested  for use in the Cloud Services Marketing website.

**Comment by mathisscott** [comment]
@Shijir 
These are for the Technology category.
