### ISSUE TITLE
Attachment (Paper Clip) Icon

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1334]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Should have an attachment icon (like a paper clip). Most of my screens/pages have an attachment feature that enables users to attach small files and documents.

### Actual behavior

Unfortunately, Clarity doesn't have any icons for attachments. I tried to use a link or an upload icon but I think a paper clip is more suited to attachments.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@lil-kim 
Could we consider adding this to the Social category?
