### ISSUE TITLE
can't bind to the shape property of clr-icon

### ISSUE THREAD

**Issue by krist-jin** [vmware/clarity#1335]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When using clr-icon like this:
`<clr-icon [shape]="someVariable"></clr-icon>`
I expect that it should be able to bind to the shape property of clr-icon and change the icon shape based on a variable. **If it's not supported in this way, is there any workaround to bind the shape to a variable so that the shape can change dynamically?**

### Actual behavior
Compiler complains:
> compiler.es5.js:1690 Uncaught Error: Template parse errors:
> Can't bind to 'shape' since it isn't a known property of 'clr-icon'.

### Reproduction of behavior
https://plnkr.co/edit/UoybOAn9R4SLhp5s5spM?p=preview
uncomment this line to reproduce:

### Environment details
see the plnkr

**Comment by mathisscott** [comment]
It's an attribute. So it has to be '[attr.shape]'. Not just '[shape]'
