### ISSUE TITLE
Datagrid row selection event?

### ISSUE THREAD

**Issue by s6joui** [vmware/clarity#1336]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Expected behavior

I need to do an ajax call when a row is selected but I can't find if there is an event that's triggered on selecting a row.
I know I can get the selected item with "[(clrDgSingleSelected)]" but I would like to run some code when that happens.

### Environment details

* **Angular version:** 4

* **Clarity version:** 0.10.0-alpha.6

**Comment by adityarb88** [comment]
@s6joui: You should be able to do that using the de-sugared syntax for 2 way binding.

```<clr-datagrid [clrDgSingleSelected]="selected (clrDgSingleSelectedChange)="selectedChanged($event)">```

Plnkr: https://plnkr.co/edit/WhwNnwkoOZ1o9LH8oM0A?p=preview

More info here: https://angular.io/guide/template-syntax

**Comment by s6joui** [comment]
It works great. Thank you!  Maybe you should consider adding it to the docs.

**Comment by alonbez** [comment]
Hi, I encountered an issue similar to you problem, I'm using [clrDgSelected]="selected" and (clrDgSelectedChange)="selectHandler($event)"
When I'm selecting an item everything works great, but when I'm un-selecting an item the $event object still contains the unselected item.
