### ISSUE TITLE
[Datagrid] Selection is not cleared in Selection (Single) when applying filter

### ISSUE THREAD

**Issue by sivaah** [vmware/clarity#1337]
**Select one ...**  (check one with "x")
```
[x] bug
[] feature request
[ ] enhancement
```

### Expected behavior
The selection has to be cleared when applying filter in Selection (Single) (clrDgSingleSelected). Similar to normal select with checkbox.

### Actual behavior
The selection is preserved even after applying filter.

### Reproduction of behavior
https://embed.plnkr.co/eoBUPb/

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by bdryanovski** [comment]
This is no longer valid
