### ISSUE TITLE
Update datagrid when data has changed

### ISSUE THREAD

**Issue by ninodinatale** [vmware/clarity#1340]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Question:

I just have a small question. Is it possible to update the datagrid when values have changed? I let users update and save records displayed in the datagrid. I get the new object and replace it with the old one in the array, but unfortunately, the datagrid does not update itself. So, is it possible to trigger an update or how can I handle this?

**Comment by ninodinatale** [comment]
You are right, I had an error in my code, thank you!

**Comment by ninodinatale** [comment]
@youdz reopening this again in order to clarify things. The datagrid only updates when I replace to whole object, but not when I manipulate it:

```
    // assuming that this is the object passed to the datagrid
    users: User[] = [];

    // this won't be detected as a change to the object
    this.users.push(user);

    // on the other hand, this will
    let userList: User[] = this.users;
    userList.push(user);
    this.users = userList;
```

Is this how it is supposed to work?

**Comment by youdz** [comment]
If this doesn't work, then yes it's a bug. But we've been modifying the array given to the datagrid without any issues so far. Can you try and reproduce it in a plunker? Thank you.

**Comment by mathisscott** [comment]
@ninodinatale 
Any update here?

**Comment by ninodinatale** [comment]
@youdz, @mathisscott 
Will create a plunker soon, had no time so far. Update is coming, I'm sorry.

**Comment by mathisscott** [comment]
@ninodinatale 
No worries! I was checking in to see if this was still an issue for you. Thanks for the update!

**Comment by ninodinatale** [comment]
I could not recreate it in a plunker, so it seems the problem lays somewhere else.
