### ISSUE TITLE
[Button Group] Allow dropdowns

### ISSUE THREAD

**Issue by marvinosswald** [vmware/clarity#1347]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

This shouldn't be hardcoded, I would propose this to be the default but overwritable. Like this:

- [clrMenuLabel]: String - This would replace the icon with a Label
- [clrMenuIcon]: String - This would just change the icon itself

### Actual behavior

https://github.com/vmware/clarity/blob/f0f79cd76d2480c5f0e78b45649e8139a1a8b75c/src/clarity-angular/button/button-group/button-group.html#L12
Hardcoded.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
The menu label ask is dependent on the functionality requested in #1326 

The ability to define a custom icon for the overflow is something we've discussed internally. Thanks for opening this issue, @marvinosswald !

**Comment by youdz** [comment]
I updated the title of this issue to have it describe the actual feature we want to implement to solve it. So far, only plain buttons are allowed in button groups. We want to allow dropdowns too. If a dropdown ends up in the overflow, it will simply be a nested dropdown (see https://vmware.github.io/clarity/documentation/dropdowns for examples of nested dropdowns).

At the moment, a button group looks like this:
```html
<clr-button-group>
    <clr-button>First</clr-button>
    <clr-button>Second</clr-button>
    <clr-button>Third</clr-button>
</clr-button-group>
```
We want to allow: 
```html
<clr-button-group>
    <clr-button>First</clr-button>
    <clr-dropdown>
        <button class="btn btn-outline-primary" clrDropdownTrigger>
            Second
        </button>
        <clr-dropdown-menu *clrIfOpen>
            ...
        </clr-dropdown-menu>
    </clr-dropdown>
    <clr-button>Third</clr-button>
</clr-button-group>
```

**Comment by reddolan** [comment]
We recommend keeping the ellipsis icon for a few of reasons
1. Consistency - as a product/solution has more overflow experiences, users become accustomed to recognizing the ellipsis as an overflow experience. Changing the icon will confuse users
2. Localization - retaining the icon keeps a product/solution from having to rewrite labels in several supported languages
3. Accessibility - changing the icon could have adverse effects on accessibility regarding different labels or missing important information

**Comment by andreiconstantinbytex** [comment]
I would to get assigned. Thanks!

**Comment by gnomeontherun** [comment]
Issue #5562 is a pretty similar duplicate.

The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
