### ISSUE TITLE
Wizard without modal

### ISSUE THREAD

**Issue by alberthoekstra** [vmware/clarity#1354]
Select one ... (check one with "x")

[ ] bug
[ ] feature request
[ ] enhancement
[x] question
Question:

So I have a virtical side menu which contain serveral items within serveral sections.
One of the menu items is 'Add new item'. This is a link to the 'New item component' and it should show a wizard to create a new item. A wizard in that page, not in a modal view.

Is that possible?

**Comment by mathisscott** [comment]
It's not a feature we advertise or intend to support so be warned. We do not recommend using static/inline wizards.

But here's some guidance...

https://github.com/vmware/clarity/blob/master/src/app/wizard/wizard-inline.demo.html

Note CSS classes on `clr-wizard`

**Comment by KashMoneyMillionaire** [comment]
Now here: [html](https://github.com/vmware/clarity/blob/master/src/dev/src/app/wizard/wizard-inline.demo.html) and here: [ts](https://github.com/vmware/clarity/blob/master/src/dev/src/app/wizard/wizard-inline.demo.ts)
