### ISSUE TITLE
Tooltip Positioning - Top and Bottom

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#1355]
This may have already been requested. If so, my apologies. I couldn't find it while searching.

Would it be possible to add a Top and Bottom option for Tooltip Positioning?

I'm picturing the tooltip positioned directly above or below the trigger with both the center of the trigger element and the center of the tooltip aligning with the little arrow thing in the center.

https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_tooltip_pos&stacked=h as an example

**Comment by mathisscott** [comment]
@jacobbutton 
We don't currently have a top/bottom-center option. I'll add this as a feature request for the tooltip component. Thanks for the suggestion.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
