### ISSUE TITLE
Vertical Nav to 3 level

### ISSUE THREAD

**Issue by ronsc** [vmware/clarity#1361]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Expected behavior
![3](https://user-images.githubusercontent.com/5668857/29652710-e5922ade-88d0-11e7-81e0-c6764dba156f.JPG)
I'm try Vertical Nav but I cannot make Vertical Nav to 3 level like angular.io web site (image capture above). 
My question can make 3 level with Vertical Nav ? 
if can, How to make. Thx.

**Comment by youdz** [comment]
I believe this was a deliberate choice from our UX team, but I will let @reddolan confirm and explain our reasons. If I'm mistaken, then this can become a feature request for vertical nav.

**Comment by reddolan** [comment]
@ronsc 
We had a similar request when we initially posted the design spec for Vertical Navigation. Here was the feedback I had provided: https://github.com/vmware/clarity/issues/1001#issuecomment-305590150
> your solution can incorporate 3 levels of navigation when using the header in combination with this vertical navigation.

> The idea of having three levels of navigation within this was something we discussed. We believe a 3rd level would significantly decrease the horizontal space available, even more so when icons are present. This would potentially force many links to display with an ellipses making it difficult for users to decipher links. Also with the addition of dividers and section headers we wanted to be conscious of the amount of visual noise potentially being added to the vertical nav. Lastly, in our research we saw most solutions had one or two levels of navigation. Those that have three levels, we wanted to get those teams to rethink and simplify their solution’s information architecture.

**Comment by reddolan** [comment]
Thank you for the request, but we will be closing this issue

**Comment by ronsc** [comment]
@youdz And @reddolan Thank you for reply.
