### ISSUE TITLE
[Modal] Modal service

### ISSUE THREAD

**Issue by gperdomor** [vmware/clarity#1364]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```
Right now, show or hide a modal is a little hardcoded, we need put the modal in our templates. I think we need something more dynamic. Something like this: https://material.angular.io/components/dialog/overview

**Comment by mathisscott** [comment]
@gperdomor 
What do you mean by "we need put the modal in our templates"?

Maybe I'm missing something because I don't see anything on that link that can't be done with the Clarity modal...

**Comment by gperdomor** [comment]
@mathisscott for example if you have a page when you can show multiple types of modals you need to do something like this

```
<clr-modal [(clrModalOpen)]="showModal1"> MODAL CONTENT </clr-modal>
<clr-modal [(clrModalOpen)]="showModal2"> OTHER MODAL CONTENT </clr-modal>
```

You can simplify putting the content in their own components, like:

```
<clr-modal [(clrModalOpen)]="showModal1"> <component1></component1> </clr-modal>
<clr-modal [(clrModalOpen)]="showModal2">  <component2></component2> </clr-modal>
```

Maybe that modals could be appears in many pages, like some kind of confirm action to delete some items in a CRUD view... You can put a global modal in the root component, but this is ugly because not all pages need that modal...

A proper solution can be some kind of modal service with can open and close modal in a dynamic way:

```javascript
// Imports

@Component({
// ...
})
export class ComponentExample {
    constructor(private modalService: ClarityModalService) {}

    showConfirmModal() {
        this.modalService.open(DialogExample)
    }
}
```

When DialogExample is other component, which can even open other component, without put them in the template html... Check the Material dialog example

**Comment by mathisscott** [comment]
@gperdomor 
I think I understand what you are asking. You want to be able to reuse modals across your application and you feel the best way to do that is encapsulate their content in a component.

Why wouldn't you just make the modal itself a component?

```
<urapp-component1-modal></urapp-component1-modal>
<urapp-component2-modal></urapp-component2-modal>
```

Then you can register them in a service within your application and handle the open and close in your app (as opposed to relying on a component framework to dictate your application's services)?

Other than "Material is doing it", I don't see the advantage of the approach you are suggesting. Moreover, you're going to run into some i18n issues with the way Material is doing their modals. You may not care now. But you probably will later.

**Comment by mathisscott** [comment]
@youdz ^

**Comment by chrizy** [comment]
Thanks @mathisscott for your answer, I am also stuck on this problem. How would you register/invoke `<urapp-component1-modal></urapp-component1-modal> `from a service?

**Comment by gnomeontherun** [comment]
@chrizy please see https://stackoverflow.com/questions/46664588/how-to-use-modal-dialog-with-vmware-clarity/46964407 for some details and an example.

**Comment by kdubious** [comment]
Not sure that this is 100% related, so let me know if I should move it.

I'm trying to make components that may or may not be opened in a modal dialog. Imagine a Company Detail page with an Employee table listing the employees of that company (Employee component). Clicking edit opens the Employee Detail component as a modal dialog. There's also an Employee List component, listing all Employees across all Companies. Clicking edit there routes to the same Employee Detail component (use above as a modal) this time used as the left side of a page.

The Employee Detail HTML starts with a Form. Inside the form is a div with the Bootstrap "modal-body" class (wrapping the inputs) and another div with the save & cancel buttons wrapped in "modal-footer". The Employee List HTML holds the <clr-modal>.

Final note, there's an *ngIf="model" on the form, showing it only when data is present.

My issue is that the modal does not seem to show the form, since it's outside of ["modal-title", "modal-body","modal-footer"] tags. Also, conceptually, it seems better if it followed the Material methodology, letting me create the Modal in the component TypeScript code, and pass it any other component that I wish to show.

**Comment by gnomeontherun** [comment]
@kdubious Could you create an example and start a new ticket or post to stackoverflow with `vmware-clarity` tag? This thread is specifically about the feature request, which might be related but your specific question is probably separate.

**Comment by maxtorchel** [comment]
mb this is the solution
https://angular.io/api/common/NgComponentOutlet
you can create service that share observable property with components, and in the modal component through *ngFor show your modals

example:
`
export class Modal {
  opened = false;
  constructor(public component: Type<any>, public data?: any) {}

  open() {
    this.opened = true;
  }

  close() {
    this.opened = false;
  }
}

@Injectable()
export class ModalService implements OnInit {

  private modal = new Subject<Modal>();

  constructor() { }
  ngOnInit(): void {
  }

  openModal(modal: Modal) {
    this.modal.next(modal);
  }

  getModal(): Observable<Modal> {
    return this.modal.asObservable();
  }
}

export class ModalComponent implements OnInit, OnDestroy {
  modals: Modal[] = [];
  subscription: Subscription;

  constructor(private modalService: ModalService) { }

  ngOnInit() {
    this.subscription = this.modalService.getModal().subscribe(modal => {
      modal.open();
      this.modals.push(modal);
    });
  }
  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  close(modal: Modal) {
    modal.close();
    this.modals.splice(this.modals.indexOf(modal), 1);
  }
}
`
modal component template:
`
<clr-modal *ngFor="let modal of modals" [(clrModalOpen)]="modal.opened" >
  <h3 class="modal-title">Title</h3>
  <div class="modal-body">
    <ng-container *ngComponentOutlet="modal.component"></ng-container>
  </div>
</clr-modal>
`

**Comment by LubosD** [comment]
For anyone ending up here, not knowing how to implement you own Modal service, this is a great start: https://medium.com/front-end-hacking/dynamically-add-components-to-the-dom-with-angular-71b0cb535286

**Comment by maxtorchel** [comment]
mb this is the solution
https://angular.io/api/common/NgComponentOutlet
you can create service that share observable property with components, and in the modal component through *ngFor show your modals

example:
```
export class Modal {
  opened = false;
  constructor(public component: Type<any>, public data?: any) {}

  open() {
    this.opened = true;
  }

  close() {
    this.opened = false;
  }
}

@Injectable()
export class ModalService implements OnInit {

  private modal = new Subject<Modal>();

  constructor() { }
  ngOnInit(): void {
  }

  openModal(modal: Modal) {
    this.modal.next(modal);
  }

  getModal(): Observable<Modal> {
    return this.modal.asObservable();
  }
}

export class ModalComponent implements OnInit, OnDestroy {
  modals: Modal[] = [];
  subscription: Subscription;

  constructor(private modalService: ModalService) { }

  ngOnInit() {
    this.subscription = this.modalService.getModal().subscribe(modal => {
      modal.open();
      this.modals.push(modal);
    });
  }
  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  close(modal: Modal) {
    modal.close();
    this.modals.splice(this.modals.indexOf(modal), 1);
  }
}
```
modal component template:
```
<clr-modal *ngFor="let modal of modals" [(clrModalOpen)]="modal.opened" >
  <h3 class="modal-title">Title</h3>
  <div class="modal-body">
    <ng-container *ngComponentOutlet="modal.component"></ng-container>
  </div>
</clr-modal>
```

**Comment by mcosta74** [comment]
One use case where a `ModalService` would be useful is if you need to open some modal (for instance a confirmation modal) in a @ngrx/effect.

For instance I'd like to manage the logged in state in *ngrx* and I'd like to add an action to log out and asking confirmation in a effect

**Comment by neaped** [comment]
just as a reference, here is a good approach:

https://stackblitz.com/edit/clarity-light-theme-v11-3clpz8?file=app%2Fmodal.component.ts

**Comment by mcosta74** [comment]
@neaped My use case require to open a modal from something that's not a component. For instance a service or a ngrx/effect.

**Comment by neaped** [comment]
@mcosta74 I haven't code for this use case yet, but I think the link that provided above, it gave a good way to approach for you use case. As mathisscott mentioned,  a single (or even multiple) modal can be write as a component, then register it as a service. Once you want to use it,  just call the modal service, then use the modal component to control the modal behaviors.  In addition,  LubosD also provide a good reference.

**Comment by 19Arne75** [comment]
Can you give more info about -> "i18n issues with the way Material is doing their modals. " ?
@mathisscott

**Comment by mathisscott** [comment]
@19Arne75 
That comment was from around 8 months ago. ngMaterial at that time had a11y issues with keyboard navigation in their modals. Those seem to have been cleared up. Thanks!

**Comment by 19Arne75** [comment]
@mcosta74 Something like this you looking for ?

https://stackblitz.com/edit/clarity-8jhcl5

**Comment by chrizy** [comment]
that looks promising. Thanks

**Comment by mcosta74** [comment]
HI,

this is my [proposal](https://stackblitz.com/edit/clarity-app-modal).
The main idea is to have a top level component (like the app alerts) controlled by a service.

The API shall be cleaned and documented but, if accepted I can work on a "formal" contribution proposal

**Comment by Icebird99** [comment]
@mcosta74 Thanks! That's exactly what I needed! 
I'm new at Angular and Clarity, and was having a hard time finding a solution for multiples alerts and modals, without the need to each time write the complete modal from scratch.
Your solution allow me to only call a simple function from the service, and it's a go!

**Comment by mcosta74** [comment]
@Icebird99 Glad to hear this is useful for you.
To be honest there's something to clean in this example but is more or less what I needed (only confirmation Dialog/MessageBox)

I see @gnomeontherun added some labels: "needs: ux input" and "!" (what's this?). 

Not sure the Clarity Team wants to introduce this kind of service in the core project. In case they accept the idea I can prepare something as proposal.

**Comment by hippee-lee** [comment]
@mcosta74 - `needs: ux input` is where a design work is done that looks at the use cases for understanding and documenting the UX of the change as well as providing any visual design related to the UI that are needed for the proposal. 

This design work produces a spec that can document the supported (and unsupported) use cases so we know what that the MVP is vs corner cases that may take longer or be more complicated to implement. From the spec we can proceed with development and also generate the documentation for guidelines and API related to the changes. 

Its part of the process detailed in the [contribution guidelines](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md).

**Comment by mcosta74** [comment]
@hippee-lee thanks for the explanation but I was asking about the label `!`.

If I understand correctly you're working on the design side, so at some point we'll have spec and then the feature implemented.

**Comment by hippee-lee** [comment]
Hey @mcosta74 - I'm not 100% sure what `!` is for and I keep forgetting to ask @gnomeontherun. I'm not working on design for this but its the first thing that needs to happen here is to produce the design/spec based on the identified use cases.

**Comment by CrazyBonze** [comment]
Hello, I was also looking for a way to dynamically load modals so i actually have Material design just for MatDialog, MatDialogRef and MAT_DIALOG_DATA in my application. Its a bit hacky but with how many modals my application has it works.

**Comment by mcosta74** [comment]
> Hello, I was also looking for a way to dynamically load modals so i actually have Material design just for MatDialog, MatDialogRef and MAT_DIALOG_DATA in my application. Its a bit hacky but with how many modals my application has it works.

to be honest I hate the Material solution for modals :D

**Comment by gnomeontherun** [comment]
I'm going to close this because we don't intend to support this behavior explicitly with a service and applications can easily set up their own service that fits their use cases and preferences.
