### ISSUE TITLE
Lazy loaded tree nodes should load children upon selection of a tree node

### ISSUE THREAD

**Issue by Darrenmeehan** [vmware/clarity#1368]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
In a lazy loading tree, selecting a node should load the children nodes, as selected.

### Actual behavior
Upon selecting a node, the node gets selected as expected, but no children get loaded.

### Environment details
* **Angular version:** 4.0.X
* **Clarity version:** 0.9.16
* **OS and version:** Windows 10 64Bit
* **Browser:** [all]

**Comment by Darrenmeehan** [comment]
This is something I'm willing to collaborate on to get implemented. I've started implementing this around Clarity, but would prefer to get it implemented in Clarity. I'm on-boarding with Angular some help would be required.

**Comment by youdz** [comment]
I believe we want to maintain the behavior of selection and expand/collapse separated. Maybe for your use case it makes sense, but we can't force that on everyone, especially considering the fact that what you're asking for would be recursive and only stop at the leaves of the tree.

It's pretty easy on the app side to expand a node dynamically whenever it becomes selected, simply by using the `clrSelectedChange` output and the `clrIfExpanded` input.

**Comment by Darrenmeehan** [comment]
Thanks very much for the prompt and clear reply.
