### ISSUE TITLE
Clarity Icons - Add aria-hidden="true" to Icon SVG

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1372]
Once we have the screen reader text for the title that is mentioned in #1326 we can add `aria-hidden="true"` to the SVG templates so that screen-readers will only see the supplemental text inside the `clr-icon`.

This was related to #1351 but broken off as a separate task.

**Comment by Shijir** [comment]
Closed by https://github.com/vmware/clarity/pull/1996
