### ISSUE TITLE
Wizard on mobile

### ISSUE THREAD

**Issue by alberthoekstra** [vmware/clarity#1379]
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
Question:
Currently I'm working on a registration form.
My system knows multiple types of users and every user type has differtent fields that need to be filled when registrating.

I'm thinking to use the wizard for this, but having a problem with mobile formfactors.
The wizard doenst quite scale nice to mobile sizes.
That's because on the left side the pages are shown and on the right side the content of the current page.

In another system I'm using they've got a very slick wizard.
Check this: http://tinyurl.com/yaqapfj6 

Is this achievable with the current wizard elements? 

How should I correctly implement a wizard thats even usable on mobile?

**Comment by mathisscott** [comment]
Hi @alberthoekstra 

The current wizard in Clarity is not usable on smaller form factors like a phone. This is a known limitation. At present, I don't know how we would make the wizard work on phones in its current state.

I'll rename your ticket to reflect a request for a responsive wizard. Thanks for submitting it!

**Comment by gnomeontherun** [comment]
Closing as not something we're going to tackle in the near term.
