### ISSUE TITLE
Current releases link on What's New page is not working

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1380]
1. Go to the What's New page
2. Click on an old release link in the left sidebar (like 0.9.10)
3. Click on the "Current Release (0.10.2)"
4. Note that the browser does not navigate to 0.10.2

I tried to reproduce locally but could not. I ran `generate-template.js` in both instances I tried.

I suspect that either `generate-template.js` was not properly run before deploying or that there is something wrong with that script.

This is something we should fix soon.

**Comment by adityarb88** [comment]
issue fixed.
