### ISSUE TITLE
<span> inside forms that uses grid layout have black text

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#1381]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Spans should have the same text color as other text element, i.e. lighter than black.

### Actual behavior
<span> elements shows as black text

### Reproduction of behavior
Look at "Forms in Grid" example: https://vmware.github.io/clarity/documentation/forms
"Sockets: 1" is black while the rest of the text is lighter.
But in the "Compact Forms" example, the same thing shows lighter text as that is not part of a grid layout.

I see this stylesheet defined (and variants of it):
`.form-group.row>[class*='col-']>span
{
    color: #000;
}`

**Comment by gnomeontherun** [comment]
This should be resolved by the new forms, linking to that milestone.

**Comment by gnomeontherun** [comment]
Resolved by latest forms.
