### ISSUE TITLE
How to solve icon blurriness when rescaling

### ISSUE THREAD

**Issue by gabrielecirulli** [vmware/clarity#1386]
Great work on the icons and thanks for sharing this project. I am interested in using them in my own project, but I'm struggling to work around the blurriness I experience when rescaling the icons. 

I am experiencing these problems specifically when using the icons as SVGs in Sketch, but also experienced them while testing the icons via your live examples.

The icons seem to be designed at 36px by 36px. As the size is too large for most applications, I tend to scale them down to around 50%, so 18px or 20px. When I scale them down, they become blurry because it seems they were not designed with such resolutions in mind.

The problem is less pronounced when viewing the icons on a retina screen, although in part still visible. I am designing for an audience that is unlikely to use high-dpi screens however, so the blurriness becomes a more critical factor.

Is there a workaround for this?

**Comment by mathisscott** [comment]
@gabrielecirulli 
I spent time over the weekend trying to replicate the blurriness but could not. Do you have any steps I could follow to see what people are referring to?

**Comment by mathisscott** [comment]
@gabrielecirulli 
I'm not seeing this blurriness in Sketch. Hopefully this was resolved by a recent update.
