### ISSUE TITLE
DataGrid - Programatically Show/Hide DataGrid Columns

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#1387]
Enhancement/Feature Request

I'd like to be able to programatically show or hide specific columns.

Imagine the use case where you have a datagrid displaying assigned tasks and external controls filtering the data.

If I'm filtering for incomplete tasks I'd like the datagrid to display a DueDate column.
If I'm filtering for completed tasks I'd like to hide the DueDate column and show a CompletedDate column.

If I'm not filtering for tasks assigned to a specific user I'd like to display an AssignedUser column.
If I am filtering for tasks assigned to a specific user I'd like to hide the AssignedUser column.

**Comment by alberthoekstra** [comment]
Maybe an eazy thought but you could use *ngIf I suppose?

**Comment by adityarb88** [comment]
@jacobbutton: We already support show/hide columns: https://vmware.github.io/clarity/documentation/datagrid/hide-show

Is this what you are looking for?

**Comment by jacobbutton** [comment]
@alberthoekstra - Yes, yes you can. Damn it! Now I feel like an idiot. Thank you for the suggestion.

@adityarb88 - The show/hide support demo'd there wasn't what I was looking for. That's user controlled rather than programitcally controlled. However, as already pointed out, I can just use *ngIf.

**Comment by hippee-lee** [comment]
@jacobbutton - don't forget / make sure you also `*ngIf` the corresponding `clr-dg-cell`

```
<clr-datagrid>
    <clr-dg-column *ngIf="showId">
        <ng-container *clrDgHideableColumn>
            User ID
        </ng-container>
    </clr-dg-column>
    <clr-dg-column>
        <!--Name-->
        <ng-container *clrDgHideableColumn>
            Name
        </ng-container>
    </clr-dg-column>
    <clr-dg-row *clrDgItems="let user of users" [clrDgItem]="user">
        <clr-dg-cell *ngIf="showId">
            {{user.id}}
        </clr-dg-cell>
        <clr-dg-cell>{{user.name}}</clr-dg-cell>
  </clr-dg-row>
<clr-datagrid>
```

**Comment by youdz** [comment]
Closing since `*ngIf` is indeed the correct solution. 😄
