### ISSUE TITLE
[DOCS,WEB] Improve Vertical Nav Documentation

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1388]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Improve the vertical nav documentation and demos to provide details about:
1. How nav groups are opened? Details about the caret icon trigger.
~~2. If and when a parent link should be used in a nav group.~~
3. Design recommendations on Summary pages for the nav group.
4. Click targets in the Vertical Nav.

We also want to replace static demos with actual routing demos to avoid confusion created from using dead links.

### Actual behavior

The above mentioned expected info is missing from the documentation.

**Comment by reddolan** [comment]
#3 above is actually covered in the Layout copy. Not sure we need another call out
