### ISSUE TITLE
Alert layout broken when using multiple alert items

### ISSUE THREAD

**Issue by oliverhanappi** [vmware/clarity#1389]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

According to the [docs](https://vmware.github.io/clarity/documentation/alerts), an alert can contain multiple alert items:

![docs](https://user-images.githubusercontent.com/401938/29862046-a9d6d55e-8d6b-11e7-8007-f01604961744.png)

### Actual behavior

The layout is however broken when using one of the samples given on the documentation page or the Angular component:

![error](https://user-images.githubusercontent.com/401938/29862123-e7baba0c-8d6b-11e7-8fc2-8a19c8a7f755.png)

### Reproduction of behavior

https://plnkr.co/xukmiT

Declare an alert with multiple alert items (sample taken from the docs):

````
<div class="alert alert-danger">
  <div class="alert-items">
    <div class="alert-item static">
      <div class="alert-icon-wrapper">
        <clr-icon class="alert-icon" shape="exclamation-circle"></clr-icon>
      </div>
      <span class="alert-text">...</span>
      <div class="alert-actions">
        <div class="alert-action dropdown bottom-right">
          <button class="dropdown-toggle">
            Actions
            <clr-icon shape="caret down"></clr-icon>
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="...">Shutdown</a>
            <a class="dropdown-item" href="...">Suspend</a>
            <a class="dropdown-item" href="...">Reboot</a>
          </div>
        </div>
      </div>
    </div>
    <div class="alert-item static">
      <div class="alert-icon-wrapper">
        <clr-icon class="alert-icon" shape="exclamation-circle"></clr-icon>
      </div>
      <span class="alert-text">...</span>
      <div class="alert-actions">
        <div class="alert-action dropdown bottom-right">
          <button class="dropdown-toggle">
            Actions
            <clr-icon shape="caret down"></clr-icon>
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="...">Shutdown</a>
            <a class="dropdown-item" href="...">Suspend</a>
            <a class="dropdown-item" href="...">Reboot</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
````

### Environment details

* **Clarity version:** 0.10

**Comment by oliverhanappi** [comment]
After a quick look, it seems that the following style is missing:

````
.alert-items {
  flex-direction: column;
}
````

**Comment by adityarb88** [comment]
@oliverhanappi: Thanks for reporting this. It does look like an issue. I am not sure if this is an issue with just the documentation though. I will have to investigate more. I will take a look and get back to you soon. Thanks!
