### ISSUE TITLE
clr-alert triggers 'Error: No provider for IfOpenService'

### ISSUE THREAD

**Issue by TekSiDoT** [vmware/clarity#1391]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
clr-alert displays the respective alert

### Actual behavior
clr-alert triggers 'Error: No provider for IfOpenService'

### Reproduction of behavior
Attempt to use one of the clr-alert example from the docs
[Plunkr](https://plnkr.co/Dq07oA7SZ7K5WNrIyekG)

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.9.x, 0.10.x

* **OS and version:** Win10 anniversary

* **Browser:** [Chrome  60]

**Comment by adityarb88** [comment]
@TekSiDoT: Thanks for reporting this. This is an issue with our documentation. `clr-dropdown-menu` should not be used instead of `alert-actions`. The example should instead be this: https://plnkr.co/edit/A83NYtmpirESKL0AjUY2?p=preview

Please use the example in the plnkr and we will get the documentation fixed soon.

**Comment by syndesis** [comment]
I updated from 0.9 to 0.10.3 and now I'm getting this error when trying to display alerts:
`Error: No provider for AlertIconAndTypesService!`

Is that message related to this bug or should I open a new issue?

**Comment by mathisscott** [comment]
That's a different thing.

Make sure you've run npm install before filing an issue though.

The last person who brought this up had updated their package.json to 0.10 but had not run npm install.



On Aug 31, 2017, at 6:33 PM, Frank Sheiness <notifications@github.com<mailto:notifications@github.com>> wrote:


I updated from 0.9 to 0.10.3 and now I'm getting this error when trying to display alerts:
Error: No provider for AlertIconAndTypesService!

Is that message related to this bug or should I open a new issue?

**Comment by adityarb88** [comment]
docs fixed.
