### ISSUE TITLE
Datagrid: Filters are not applied to dynamic data in a datagrid

### ISSUE THREAD

**Issue by r-bowen** [vmware/clarity#140]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Any applied filters should be reevaluated when data dynamically changes.

### Actual behavior
The filter on a column is only applied when it is first created so if data in that column dynamically changes the filtered results are no longer correct.

### Reproduction of behavior
This is the angular template I am using
```
<clr-datagrid>
	<clr-dg-column clrDgField="user">User"</clr-dg-column>
	<clr-dg-column clrDgField="host">"Host"</clr-dg-column>
	<clr-dg-column clrDgField="status">"Status"</clr-dg-column>

	<clr-dg-row *clrDgItems="let device of devices" className={{device.status}}>
		<clr-dg-cell>{{device.user}}</clr-dg-cell>
		<clr-dg-cell>{{device.host}}</clr-dg-cell>
		<clr-dg-cell>{{device.status}}</clr-dg-cell>
	</clr-dg-row>
</clr-datagrid>
```
### Environment details

* **Angular version:** 2.1.0

* **Clarity version:** 0.7.0

* **OS and version:** 

* **Browser:** [Chrome XX]

**Comment by youdz** [comment]
The problem with watching all the objects present in the datagrid to re-filter or re-sort every time one of their properties changes is that it's extremely heavy and will destroy performances. It is heavily recommended that you use immutable objects in the Datagrid rather than in-place modifications. Note that the array itself can be modified in place, this is far easier to support.

That said, maybe we can provide a way for you to manually trigger a filter and sort refresh on the Datagrid when your data changes. You will have to call it yourself, but at least you will have the option.

**Comment by r-bowen** [comment]
Angulars zoning algorithm is already taking care of the data changes and updating the HTML accordingly. can't you leverage that so you know when the change happens? This could also be optional and disabled by default. A function I can call would also solve the issue.

**Comment by youdz** [comment]
Angular updating the HTML is a completely different change detection, not the one you want here. For instance, if you have 10000 items and display 10 at a time, Angular is only monitoring changes on these 10 items. But to know if we have to re-filter/re-sort the whole datagrid, we'd need to monitor all 10k entries with deep comparison, not simple reference one.

And Zone is only a library to wrap all asynchronous changes happening within a certain context (HTTP requests, user actions, timeouts, ...) to track them all and be notified when one of them is done. It notifies Angular which then triggers change detection, but once again neither of them monitors all Javascript objects in memory.

As I mentioned in my previous comment, I think the only way we could provide this to you is a function that you manually call to trigger a filter and sort refresh. You seem to be suggesting this would be a solution for you, so we'll look into this as soon as we can.

**Comment by ganeshmali50** [comment]
Please provide example

**Comment by technbuzz** [comment]
What is the example of **Immutable object in Datagrid**?
