### ISSUE TITLE
clr-tooltip over progress-bar inside progress group

### ISSUE THREAD

**Issue by ninodinatale** [vmware/clarity#1401]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

I'd like to add a tooltip over one progress bar inside a progress group to display the percentage inside. 

### Actual behavior

Unfortunately, the progress bar won't show, if I hover over it where it should display, the tooltip shows though.

plunker: https://plnkr.co/edit/3PtHo7?p=preview

Am I doing something wrong or is this something that was not intended to do?

**Comment by adityarb88** [comment]
@ninodinatale: We don't recommend this pattern. Our UX team recommends that tooltips should only be shown on actionable icons (icons when clicked perform an action, for example direct you to a new page). We recommend that if you had to show the value, you show it next to the progress bar we do in the documentation.

![image](https://user-images.githubusercontent.com/1426805/29925655-f818d802-8e2e-11e7-9fd5-e319e2f5f290.png)

But if this is feature absolutely required by your app, you need to make sure that your tooltip is assigned a `width: 100%`. Right now the width is 0 and thats why its not showing the tooltip.
