### ISSUE TITLE
Datagrid resizable columns should be configurable

### ISSUE THREAD

**Issue by oliverhanappi** [vmware/clarity#1404]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Datagrid columns are always resizable in Clarity. It is sometimes desirable to prevent some or all columns from being resized. There should be a column level option and ideally a datagrid wide option to control if columns are resizable or not.

### Actual behavior

It is not possible to configure if columns are resizable or not.

**Comment by usmanajmal** [comment]
I will vote for this feature too. In some cases we don't like columns to be resized by user.

**Comment by Shijir** [comment]
@usmanajmal you could disable resizing by applying this simple CSS rule:

```css
.datagrid-column-separator {
  pointer-events: none;
}
```

**Comment by xzs** [comment]
> @usmanajmal you could disable resizing by applying this simple CSS rule:
> 
> ```css
> .datagrid-column-separator {
>   pointer-events: none;
> }
> ```

One possible setback with this work around is that all pointer-events including filtering will be disabled.

**Comment by Shijir** [comment]
@xzs  the workaround I suggested is still valid. It won't affect filtering or any other areas as we are specifically targeting `.datagrid-column-separator`: https://stackblitz.com/edit/clarity-light-disable-column-resizing

**Comment by mathisscott** [comment]
Given the simplicity of the workaround, I'm closing this because it is not going to be bumped up as a priority for the team. It is a good candidate for an external contribution, however. And if that is something someone would want to take on, I'm happy to revisit.
