### ISSUE TITLE
clr-vertical-nav is not a known element

### ISSUE THREAD

**Issue by ipchaube** [vmware/clarity#1406]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

clr-vertical-nav is not a known element. In node module unable to see vertical-nav module in clarity ui section. How I can install clarity nav with npm.

### Actual behavior

clr-vertical-nav is not a known element. In node module unable to see vertical-nav module in clarity ui section. How I can install clarity nav with npm.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X
2.0.x
* **Clarity version:** 
1.x
* **OS and version:** 
windows-7
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
Which version of Clarity are you using? Vertical Nav was introduced in 0.10.0. You need to make sure you are on 0.10.0 to use Vertical Nav.

**Comment by ipchaube** [comment]
@adityarb88 Thanks, How i can upgrade clarity to 0.10.0 through npm?

**Comment by adityarb88** [comment]
You need to upgrade the version in your `package.json`. Closing the issue based on this.

**Comment by ipchaube** [comment]
@adityarb88 Thanks this works for me.
