### ISSUE TITLE
Alerts not working in 0.10.x

### ISSUE THREAD

**Issue by syndesis** [vmware/clarity#1407]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Alerts should display in 0.10 like they did in 0.9

### Actual behavior
I updated from 0.9.16 to 0.10.3 and now I'm getting this error when trying to display alerts:
Error: No provider for AlertIconAndTypesService!

### Reproduction of behavior
I used the clarity seed app and just added code from the Alerts documentation to the home screen.  Any variation caused the issue.  Example:

```
<clr-alert [clrAlertType]="'alert-danger'" [clrAlertAppLevel]="true">
    <clr-alert-item>
        <span class="alert-text">
            This is an app level alert.
        </span>
    </clr-alert-item>
</clr-alert>
```

### Environment details

* **Angular version:** 4.3.0

* **Clarity version:** 0.10.3

* **OS and version:** Windows 7

* **Browser:** all

**Comment by hippee-lee** [comment]
Hi @syndesis 

I tried to recreate the issue with a clone of the clarity seed repo but was unable to trigger that error. 
What I did was clone the latest seed, add the alert and serve the project with this on the first page:

```<clr-alert [clrAlertType]="'alert-danger'" [clrAlertAppLevel]="true">
    <clr-alert-item>
        <span class="alert-text">
            This is an app level alert.
        </span>
    </clr-alert-item>
</clr-alert>
```

You can see my repo here: https://github.com/hippee-lee/issue-1407

Are you sure you have the latest clarity (v10) installed?  If you have upgraded, can you recreate the issue in either one of these plunks? [Clarity v10 plunk](https://plnkr.co/edit/uNwwZe?p=info) [Clarity v9 plunk ](https://plnkr.co/edit/8TwwdL?p=info). 

If you think its related to your seed project, can you use that to share a repo with the issue so I can take a look?

**Comment by syndesis** [comment]
Not sure what was happening yesterday but I cannot reproduce today.  Closing.

**Comment by robbiesmith79** [comment]
Hold on. I'm still getting this on 0.10.8 in the browser:
ERROR Error: Uncaught (in promise): Error: No provider for AlertIconAndTypesService!
Error: No provider for AlertIconAndTypesService!
    at injectionError (core.es5.js:1169)
    at noProviderError (core.es5.js:1207)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._throwOrNull (core.es5.js:2649)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKeyDefault (core.es5.js:2688)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKey (core.es5.js:2620)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_.get (core.es5.js:2489)
    at resolveNgModuleDep (core.es5.js:9481)
    at NgModuleRef_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleRef_.get (core.es5.js:10569)
    at resolveNgModuleDep (core.es5.js:9481)
    at NgModuleRef_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleRef_ ...

**Comment by adityarb88** [comment]
@robbiesmith79 We will not be able to debug the issue without a Plnkr to replicate the issue. Also, did you go through our release notes: https://vmware.github.io/clarity/news/0.10.0-alpha.2 for migrating from 0.9 to 0.10 wrt Alerts?
