### ISSUE TITLE
Datagrid loading spinner is not centered

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1409]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Datagrid loading spinner should be centered both with and without `clr-dg-action-bar` buttons.

### Actual behavior

The style for `.datagrid-spinner` does not take into account the space added for the action bar. 

### Reproduction of behavior
https://plnkr.co/edit/XAUNqV?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
Clarity latest

* **OS and version:** 
n/a

**Comment by hippee-lee** [comment]
We need to confirm that we need to account for the ActionBar by covering it with the overlay when the spinner is active. 

/cc @reddolan @youdz

**Comment by youdz** [comment]
I'll let UX answer that one. To give some context, the current spinner + overlay we have on the datagrid is a last-minute implementation for v1 of the datagrid, to which UX said "good enough". I don't believe it was ever put under heavy scrutiny.

**Comment by amellnik** [comment]
The last comment here is somewhat related: https://github.com/vmware/clarity/issues/1022

**Comment by mattrc** [comment]
+1

**Comment by lil-kim** [comment]
The spinner is currently vertically centered over the white overlay which covers not only the datagrid, but the action/tool bar above it. The overlay should cover just the datagrid - this should center the spinner correctly. Will look into this - may be resolved with issue #1586.
