### ISSUE TITLE
Add datepicker support

### ISSUE THREAD

**Issue by manuelarte** [vmware/clarity#141]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Date picker. Right now, I can put dates by adding <input type="date"...> but it would be nice to have a date picker component.
### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
Thanks, @manuelarte for the issue. This is definitely on our roadmap. I am only closing as a duplicate of #121
