### ISSUE TITLE
Document how to create dropdown for subnav menu

### ISSUE THREAD

**Issue by tarquinrex** [vmware/clarity#1411]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X ] enhancement
```

### Expected behavior

Create a drop down menu under subnav items

### Actual behavior

Can you please create sample code or documentation that shows how to create a dropdown menu under each subnav item. I know this is not your recommended layout guidelines according to your documentation but it is a very common layout pattern. The side navigation takes up a lot of space and can crerate a very busy looking screen. The subnav items do look great with the blue underline on hover so should keep that but just show drop down menu on click. The subnav item should also not show a border when clicked like the drop down button as it looks a bit ugly in a menu setting.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jeeyun** [comment]
Hi @tarquinrex thanks for filing this issue. I will defer to our UX team on whether to provide a sample code, and the reason for that is any code example we give out tends to be taken as our recommended way to implement things. And because this is a pattern that we don't recommend, I'm hesitant to provide it. I'm wondering if there's alternative design to meet your navigation use case. cc @lil-kim @reddolan @gracesnoh

**Comment by tarquinrex** [comment]
Hi @jeeyun, we can work around itr but there is a problem with an angular SPA website. If you look at the layout of the page the subnavigation menu and the side navigation menu are seperated by the body container so they cant be put into the same angular component. This means that it is not easy to communicate a submenu item click to load the child side menu items (crosss component communication). We can get it to work using an angular service but it would be much nicer to have all the logic in a single component instead of having 2 components and then shared state in an angular service.  Thanks.

**Comment by mathisscott** [comment]
@tarquinrex 
This is not a pattern we are going to support. It seems you want a kind of mega-menu navigation from the sub-nav.

I recommend using the header (and dropdowns from there) or perhaps a vertical nav with top-level and child navigation items.
