### ISSUE TITLE
Clarity corrupts other libraries

### ISSUE THREAD

**Issue by SaturnTeam** [vmware/clarity#1414]
**Select one ...**  (check one with "x")
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Clarity must not affects on bare html elements without any classes

### Actual behavior
Clarity changes font size and other styles on input element of Material inputs
How it looks:
![image](https://user-images.githubusercontent.com/10252514/30017286-ca210044-9182-11e7-9709-78a46099722e.png)
How it must look:
![image](https://user-images.githubusercontent.com/10252514/30017318-eec38d36-9182-11e7-9468-a36f032ab22d.png)
Code of template: (nothing about clarity)
```
        <md-form-field>
            <input mdInput placeholder="Логин" [(ngModel)]="model.login" required>
        </md-form-field>
        <md-form-field >
            <input mdInput  placeholder="Пароль" [(ngModel)]="model.password" type="password" required>
        </md-form-field>
        <md-form-field>
            <input mdInput placeholder="Сервер" [(ngModel)]="model.url" required>
        </md-form-field>
        <md-form-field>
            <input mdInput placeholder="Номер" [(ngModel)]="model.number" required>
        </md-form-field>
```

**Comment by youdz** [comment]
You trying to use two full blown design systems with drastically different patterns and recommendations, often incompatible. Trying to apply Clarity styles to a Material app is just going to lead to conflicts everywhere, and is not something we plan on supporting.

I will let @mathisscott confirm before closing, just in case I missed a recent development.
