### ISSUE TITLE
Customizing size of clarity wizard

### ISSUE THREAD

**Issue by indukr** [vmware/clarity#1415]
**Select one ...**  (check one with "x")
```
[ ] bug
[ X] feature request
[ ] enhancement
```

### Expected behavior
Should be able to resize the Clarity wizard. To be more specific, I want to modify width and height of wizard. As of now, I see wizard s are coming in predefined sizes large, medium and xl and I am not able to modify the size of wizard. If this is possible with the existing releases, pls help me with a sample.

### Actual behavior
Not able to modify the width and height of clarity wizard.

### Reproduction of behavior
N/A

### Environment details

* **Angular version:** 4.1.0

* **Clarity version:** 0.9.9

* **OS and version:** Windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Height and width of modals and wizards can be customized using CSS.

https://plnkr.co/edit/luklrJ?p=info
