### ISSUE TITLE
Tabbed Element View - Icon showcase

### ISSUE THREAD

**Issue by TekSiDoT** [vmware/clarity#1416]
```
[ ] bug
[x ] feature request
[ ] enhancement
```

I really like the new icon showcase. There is a very clean solution to showing details for each of the icons, any plans on implementing it for regular clarity?

![image](https://user-images.githubusercontent.com/10874046/30028157-449e9772-9184-11e7-81c2-912b5398aefd.png)

**Comment by mathisscott** [comment]
What would be the use case for including this in Clarity?

**Comment by TekSiDoT** [comment]
I'm afraid I have no better answer than ... your icon docs ;)

**Comment by mathisscott** [comment]
:-)

We aren't likely to add the icon detail elements to Clarity unless we have an understanding of how this type of component would be useful inside of an application. 

Closing this request for now...
