### ISSUE TITLE
Update file headers for the correct date

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1424]
Source code files need to be updated with the correct date range in the Copyright header.

As of filing this issue it should be

```/*
 * Copyright (c) 2016-2017 VMware, Inc. All Rights Reserved.
 * This software is released under MIT license.
 * The full license information can be found in LICENSE in the root directory of this project.
 */
```

**Comment by adityarb88** [comment]
@hippee-lee: can we close this? I believe we already updated the files with the right headers, no?

**Comment by hippee-lee** [comment]
Yep, thanks for the reminder.
