### ISSUE TITLE
[NG] Naming conventions

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#1425]
This is an epic, not a task. Our names for inputs & outputs, but also classes, components, directives and even file names, are kind of all over the place.

So we need to:

- [x] Figure out what the conventions we want are.
- [ ] Move progressively all components to the agreed naming convention.

When we can, we should avoid breaking changes and just deprecate the old name. This is not going to be worth the effort for all the changes, so we will accumulate some of them for a series of search & replace breaking changes in 0.11.

**Comment by mathisscott** [comment]
@youdz 
Is this done?

**Comment by youdz** [comment]
No, we still need to move existing inputs and outputs to the new conventions: `clr` prefix but no per-component prefix anymore, to reduce verbosity. The same goes for sub-component selectors.

The latest naming conventions can be found here: https://github.com/vmware/clarity/blob/master/CODING_GUIDELINES.md

We only did a partial renaming due to a lack of time, but somehow we forgot about the rest. I really want to add this back to 1.0 because of the risk of breaking change, let's discuss this offline when we have some time.

**Comment by jeeyun** [comment]
Naming conventions are outlined here and current code base is up to date to meet these:
https://github.com/vmware/clarity/blob/master/docs/CODING_GUIDELINES_ANGULAR.md#naming-conventions
https://github.com/vmware/clarity/blob/master/docs/CODING_GUIDELINES_CORE.md#naming-and-typescript-conventions

Closing.
