### ISSUE TITLE
Documentation needed on using SASS variables and mixins in Angular-cli project

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1426]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior

At least a wiki on how to use the `.scss` files in our project so that we can extend from internal variables and use the mixins provided.
### Actual behavior

Currently there is no documentation
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.0

* **OS and version:** W10

* **Browser:** [all]

**Comment by mathisscott** [comment]
Hi @SayakMukhopadhyay 
We already have an issue open to document how to use the SASS variables and mixins. It's #268 

I'm closing this issue as a duplicate for now. Please subscribe to #268 to be alerted to progress and changes.

Thanks!
