### ISSUE TITLE
[web] modal and wizard are broken on our website

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#1428]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I expect the buttons to open up modals/wizards would work.

### Actual behavior

Instead, it scrolls to a specific section of the pages.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

Try opening up a modal or a wizard on our website.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
Just figured out that bug actually exists in the `clrFocusTrap` directive/module.
