### ISSUE TITLE
does a popover instance hover event have potential layout problems since it alters the position?

### ISSUE THREAD

**Issue by mattmutt** [vmware/clarity#1431]
https://github.com/vmware/clarity/blob/054250b5cd88c2a8ba2b075c9c204e046a247e66/src/clarity-angular/popover/common/popover.ts#L66

by changing the position of say a Tooltip, which is by design guidelines set to have its `position` set to "relative", doesn't this potentially cause janky behavior when the mouse hovers over the trigger point which executes `anchor()`

Perhaps in the simplistic use case nobody will care to notice this positional change. But in more advanced cases where the CSS has already been meticulously laid out for a "relative" flow, going to `static` is disruptive on mouseover of the trigger point because of the inlined style change.

reference clarity CSS
```
.tooltip {
    display: inline-block;
    position: relative;
    text-align: left;
    overflow: visible;
}
```

**Comment by adityarb88** [comment]
@mattmutt: We need to make sure that the position is changed to `static` to make sure that the tooltip is not clipped off in containers with overflow hidden or auto.

cc: @jeeyun

**Comment by adityarb88** [comment]
Closing the issue based on this. Please feel free to reopen this issue if you have any additional questions/feedback.
