### ISSUE TITLE
Datagrid fails to load. "SelectionType is not exported."

### ISSUE THREAD

**Issue by karmasakshi** [vmware/clarity#1432]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Datagrid should load.

### Actual behavior
Datagrid fails to load. Error: `"export 'SelectionType' was not found in './providers/selection'`.

### Reproduction of behavior
Run `ng build --prod --build-optimizer`.

### Environment details

* **Angular version:** 4.4.0-RC.0

* **Angular CLI version:** 1.4.0-rc.2

* **Clarity version:** 0.10.3

* **OS and version:** macOS 10.13 Beta

* **Browser:** [Chrome 61]

**Comment by adityarb88** [comment]
@karmasakshi: Do you see the error without the `--build-optimizer` flag?

**Comment by karmasakshi** [comment]
No @adityarb88. Only when the CLI's optimizer is turned on. Issue persists on 1.4.0 which was released yesterday.
![screen shot 2017-09-08 at 11 09 59 pm](https://user-images.githubusercontent.com/4698762/30224143-428f1e74-94eb-11e7-9ec8-1a5d21577c6b.png)

**Comment by imcotton** [comment]
related:
- angular/angular-cli#2034
- webpack/webpack#2977

**Comment by karmasakshi** [comment]
This issue does not exist in the latest builds of Clarity (0.10.6) and Angular CLI (1.4.3). Closing.
