### ISSUE TITLE
[DOCS] Add UX recommendations for Icon Buttons

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1434]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Add UX recommendation for Icon Buttons

### Actual behavior

UX recommendation for Icon Buttons does not exist.

**Comment by reddolan** [comment]
Also update the Button Group Icons section to reflect the recent changes
