### ISSUE TITLE
Progress bar display issue on Safari for large numbers

### ISSUE THREAD

**Issue by nikhildhankani** [vmware/clarity#1437]
**Select one ...**  (check one with "x")
```
[*] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
For large max and value progress bar display correctly in Safari on Mac OS Sierra

### Actual behavior
For large max and value progress bar display complete incorrectly in Safari on Mac OS Sierra

### Reproduction of behavior
https://plnkr.co/edit/9wNotSurQtdxZRNi1DHV

![screen shot 2017-09-07 at 10 24 31 am](https://user-images.githubusercontent.com/11076783/30176290-c5eb129a-93b6-11e7-937d-30f3258df68b.png)
### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** latest

* **OS and version:** Mac OS Sierra

* **Browser:** [Safari Version 10.1.2 (12603.3.8)]

**Comment by adityarb88** [comment]
@nikhildhankani: Could you please try this: https://plnkr.co/edit/s48HJc5jdiVKHZcheafC?p=preview and let us know if that works?

**Comment by adityarb88** [comment]
Please feel free to reopen the issue if the solution provided above doesnt work.

**Comment by nikhildhankani** [comment]
Thank you Aditya, works like a charm! I would be interested to learn why this works and other fails. When I inspect I see that they are converted to exponential format and that the larger number is losing values.
