### ISSUE TITLE
Misaligned loader in datagrid

### ISSUE THREAD

**Issue by nikhildhankani** [vmware/clarity#1443]
**Select one ...**  (check one with "x")
```
[ * ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Loader in clarity datagrid should be center aligned 

### Actual behavior
Loader is misaligned

### Reproduction of behavior
Reproducible on clarity website. https://vmware.github.io/clarity/documentation/datagrid/full change some input and click apply.
![mis aligned loader](https://user-images.githubusercontent.com/11076783/30193142-65861cde-9400-11e7-932e-9182a54f8008.gif)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:latest

* **OS and version: Any

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Thanks for reporting this. 

This issue seems like a regression introduced in today's release. 
https://github.com/vmware/clarity/commit/37f2194735e753516151ce14b0f6b42bf52a6499

**Comment by nikhildhankani** [comment]
This happens in 0.10.2 as well

**Comment by youdz** [comment]
Duplicate of #1409.
