### ISSUE TITLE
Tab border

### ISSUE THREAD

**Issue by BugsyFTW** [vmware/clarity#1450]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

When you click on the Tab, the normal behavior happens. The selected button uses the correct stylesheet.

### Actual behavior

When you click on a Tab, it has a surrounding blue border from the button, I believe that in the tabs that border should not be visible as it doesn't fit the style. It would be an improvement if it could be removed.

### Reproduction of behavior
![blueborder](https://user-images.githubusercontent.com/3944235/30275896-de613f60-96fa-11e7-90d0-c21a0f472b9d.png)

### Environment details

* **Angular version:** 4.4.0-RC.0

* **Clarity version:** 0.10.4

**Comment by adityarb88** [comment]
@BugsyFTW: That is the outline style and is present for users to easily navigate using a keyboard. Its present on all buttons and links in Clarity. We recommend that you don't remove it for accessibility reasons. Closing the issue based on this.
