### ISSUE TITLE
Linking to a specific icon on the Clarity Icons website

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#1452]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ X ] enhancement
```

### Expected behavior
I'd like to be able to link to a specific icon on the icons website. For example, if I choose the icon "Home" and click on it to see its expanded state, I'd like to be able to have the URL represent that so I am able to link directly to it. This is useful both when linking to an icon between designers and developers as well as when filing issues on specific icons here. It is also useful when referencing icons in discussions.

### Actual behavior
Currently, this feature does not exist. You can reference the name of an icon for someone to find it but you would have to reference the "Clarity" name vs. what I am using the icon for creating possible confusion. For example, if I want to use the "X" icon named "Times" to represent "delete" which is a possibility, I would have to reference it with "times" for someone to find it even though it is not the correct use case.

### Reproduction of behavior
Clarity website.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.10.x

* **OS and version:** N/A

**Comment by Shijir** [comment]
this is a duplicate issue of https://github.com/vmware/clarity/issues/800
