### ISSUE TITLE
Need accessibility icon

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#1453]
**Select one ...**  (check one with "x")
```
[ ] bug
[ X ] feature request
[ ] enhancement
```

### Expected behavior
Need an accessibility icon so we're able to talk about software accessibility and accessibility as a concept. Many examples are available online.

### Actual behavior
No accessibility icon is currently available.

### Reproduction of behavior
Visit the clarity.design icons website.

### Environment details

N/A

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by reddolan** [comment]
There were two versions added in vol 9 I believe.
![image](https://user-images.githubusercontent.com/1858226/37932931-a6cc86f6-30fe-11e8-9f0f-f37e5f5b2c92.png)
