### ISSUE TITLE
Alerts not working in 0.10.4

### ISSUE THREAD

**Issue by zivanov123** [vmware/clarity#1454]
```
[ X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The examples in clarity site to be working.

### Actual behavior
I've taken example directly from the clarity site about alerts, which use only DOM elements without angular components.
The concrete example:

<div class="alert alert-info">
           <div class="alert-items">
              <div class="alert-item">
                 <div class="alert-icon-wrapper">
                    <clr-icon class="alert-icon" shape="info-circle"></clr-icon>
                 </div>
                 <span class="alert-text">...</span>
                 <div class="alert-actions">
                    <a href="..." class="alert-action">Acknowledge</a>
                    <a href="..." class="alert-action">Reset to green</a>
                 </div>
              </div>
           </div>
           <button type="button" class="close" aria-label="Close">
              <clr-icon aria-hidden="true" shape="close"></clr-icon>
           </button>
        </div>

This is resulting into:

Error: Uncaught (in promise): Error: No provider for AlertIconAndTypesService!
Error: No provider for AlertIconAndTypesService!
    at injectionError (reflective_errors.ts:73)

### Reproduction of behavior

Plunker: https://plnkr.co/edit/lOYm5CHP52BW0x0GveVB?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
https://plnkr.co/edit/CFowzx?p=preview

You are using a static alert inside of an Angular app. See this answer for this stackoverflow question for more information: https://stackoverflow.com/a/46024788/7376162

**Comment by zivanov123** [comment]
Thanks!
I understand the problem and the fix.

Seems that I've been looking at the three places in the doc where this is wrong and I spent a lot of time in research. Please check here:
https://vmware.github.io/clarity/documentation/alerts
Section: "Types"
See the code example - there is no 'static' class next to the .alert-item.

At least as result I've migrated all our alerts to the angular implementation.

**Comment by adityarb88** [comment]
@zivanov123: Thanks for notifying us of the issue. We will make sure we update our docs to use the `.static` class. If you use Clarity Angular too, then using the Angular Alerts component is the best option.

**Comment by zivanov123** [comment]
@adityarb88 No problem. Please also fix it here:

https://vmware.github.io/clarity/news/0.10.0-alpha.2

**Comment by mathisscott** [comment]
@adityarb88 
It is already in our docs.

![screen shot 2017-09-12 at 8 31 22 am](https://user-images.githubusercontent.com/2728359/30328388-d07cb998-9794-11e7-8d6c-b93711892802.png)

**Comment by mathisscott** [comment]
@zivanov123 
You only need to use the `.static` class when you are using non-Angular Clarity alerts inside of a Clarity Angular application.

1) This is not a standard way of doing things. The vast majority of the time you should use `clr-alert` instead of building an alert with just HTML inside a Clarity Angular app

2) Putting the `.static` class on straight DOM (not angular application) is unnecessary and would only serve to assist people who insist on not using `clr-alert` and don't read the existing documentation.

**Comment by zivanov123** [comment]
Yes, I saw that but I was not sure why it was written, since the examples were stating another thing :)

Thanks for fixing!
