### ISSUE TITLE
Tab in sub nav not compatible with routerLinkActive

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1455]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I was using 0.10.0 with the following piece of code which was working as intended
```
<nav class="subnav">
    <clr-tabs>
        <clr-tab>
            <button routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" class="btn btn-link nav-link nav-item">Home</button>
        </clr-tab>
        <clr-tab>
            <button routerLink="/page1" routerLinkActive="active" class="btn btn-link nav-link nav-item">Page 1</button>
        </clr-tab>
        <clr-tab>
            <button routerLink="/page2" routerLinkActive="active" class="btn btn-link nav-link nav-item">Page 2</button>
        </clr-tab>
    </clr-tabs>
</nav>
```
But after upgrading to 0.10.4, I get errors pointing that using the `clrTabLink` directive is mandatory and it is automatically setting the active tab based on click. But I would like to set the active tab based on the route.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.4

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by SayakMukhopadhyay** [comment]
I was able to replicate the situation in 2 plunkers.
0.10.0 - https://plnkr.co/edit/f8e40b?p=info
latest(0.10.5) - https://plnkr.co/edit/VDSJX9?p=info

Hope this helps.

**Comment by mathisscott** [comment]
@SayakMukhopadhyay 
We can't run these plunkrs. The error we see is:

<img width="799" alt="screen shot 2017-09-27 at 9 44 54 am" src="https://user-images.githubusercontent.com/2728359/30920025-96467e6e-a368-11e7-941e-86d8444d4818.png">

**Comment by SayakMukhopadhyay** [comment]
I have fixed the plunkers. The html files associated with the test component had vanished.

**Comment by shalaby** [comment]
any update on this?

**Comment by mathisscott** [comment]
@SayakMukhopadhyay + @shalaby 

Looking at the plunkr, tabs are not supposed to be used in the subnav like that. Subnav and tabs look similar (so I understand the confusion) but they are not the same.

Take a look at [the subnav documention in the header docs](https://vmware.github.io/clarity/documentation/header) for an example of how to do the subnav.
