### ISSUE TITLE
Datagrid demo's date pipes broken in IE10

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#146]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Datagrid should work in IE10.

### Actual behavior
Datagrid doesn't work in IE10.

### Reproduction of behavior
Go to the datagrid documentation page in IE10.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.7.2

* **OS and version:** 

* **Browser:** IE10

<img width="1552" alt="screen shot 2016-11-23 at 1 50 51 pm" src="https://cloud.githubusercontent.com/assets/2728359/20576646/5aad738e-b184-11e6-8d4a-095f3dc365fe.png">

<img width="1552" alt="screen shot 2016-11-23 at 1 51 24 pm" src="https://cloud.githubusercontent.com/assets/2728359/20576653/6344ef4a-b184-11e6-893a-c05da417565e.png">

<img width="1552" alt="screen shot 2016-11-23 at 1 51 15 pm" src="https://cloud.githubusercontent.com/assets/2728359/20576657/6b74005c-b184-11e6-9d57-0ccf1d77b7e3.png">

<img width="1552" alt="screen shot 2016-11-23 at 1 51 34 pm" src="https://cloud.githubusercontent.com/assets/2728359/20576670/710e2ee8-b184-11e6-80bc-db10bbb84e88.png">

**Comment by youdz** [comment]
The datagrid itself is not broken on IE, it's the DatePipe from Angular 2, that we use in the demo, that needs a polyfill to work on IE.

I'll rename the issue and label accordingly.
