### ISSUE TITLE
clr-icon shape property should be bindable

### ISSUE THREAD

**Issue by DexterYang1982** [vmware/clarity#1462]
**Select one ...**
```
[ ] bug
[x] feature request
[x] enhancement
```

### Expected behavior

<clr-icon [shape]=""> or <clr-icon   -shape="{{}}">

### Actual behavior

dynamic shape cannot be used

**Comment by Shijir** [comment]
Dynamic shapes can be used as follows:

```<clr-icon [attr.shape]="shapeNameData">```
