### ISSUE TITLE
[UX] Support max-width centered layout

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1464]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

**Actual Behavior**
Clarity layout occupies the entire screen space. 

**Feature Request**
Some of our users have requested for a layout which has a max-width and is centered on the screen. We need UX research to figure out if we want to support this behavior.

Following questions should be taken into consideration:
- If centered, how does the side nav and the header behave? Does the responsiveness behavior kick in?
- What happens when the screen size changes? How does the layout behave on different breakpoints?
- what width would it be?
- is this something that can be overridden easily?

### Environment details

* **Clarity version:** All

* **OS and version:** All

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
This is technically possible using the Core layout tokens, should someone be interested in that. I'm going to close this as possible https://clarity.design/storybook/core/?path=/story/foundation-layout-get-started--page.
