### ISSUE TITLE
Namespace CSS classes

### ISSUE THREAD

**Issue by yelhouti** [vmware/clarity#1466]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Be able to add clarity on top of other frameworks like ionic without css classes conflict (ex: .label)
### Actual behavior

clarity uses very generic classes name (by the way this not a problem only with clarity) we can prefix classes like we do html tags: .clr-label instead of .label.
It would mean that any one could start using clarity components without worrying about css conflicts with there current framework. A great selling point in my opinion
### Reproduction of behavior

I can add a plunker if you want to.

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.4

* **OS and version:** all

* **Browser:** [all]

**Comment by mathisscott** [comment]
Improving and standardizing our CSS naming conventions is something that we are interested in doing but it was removed from 1.0 work because it would constitute a major breaking change for all the products that use Clarity.

I'm also concerned that it would open up integration issues as people begin reporting Bootstrap conflicts or Semantic UI conflicts here.

I'm also curious why the onus falls on Clarity to resolve these conflicts?

**Comment by yelhouti** [comment]
well, others already reported issues with integration with bootstrap, since bootstrap has the same problem, I also checked semantic UI and they also have the same problem. jQuery UI on the other hand, had a solution for that by prefixing all it's classes with ui-, which in my opinion on of the mane reasons for it success.
As of why clarity should be the one solving this issues:

1. In my opinion all frameworks should do.
2. compared to bootstrap or semantic UI which provide theming and lower level components, and often added before clarity, clarity offer higher more complex component that are put on top of the existing framework and shouldn't break the existing themes.

This also will provide a big advantage over the competition as developers can be sure that adding clarity components wouldn't break existing code.

**Comment by mathisscott** [comment]
Thanks @yelhouti 

I'll bring this back to the Clarity team to reopen the dialogue around CSS naming conventions and how we want to handle those in the future.

It would be a huge breaking change for everyone using Clarity, though. So it is not something that we could do in the next few minor releases if we were to decide to.

We would have to develop a strategy to make the migration less painful for our users.

**Comment by yelhouti** [comment]
Thank you @mathisscott 
Indeed this would be a breaking change, and if needed I would be glad to work with the team on it.
For the migration strategy, I think we can, without too much effort, write a script to replace old classe names with the new ones, in both css (sass...), html, ts ... files inside a certain folder/file, also users in beta will provide feedback if we miss (or overdo) the refactoring.

**Comment by jayvdb** [comment]
Why not add namespaced css classes now, in addition to the existing ones, and then deprecate the un-prefixed ones in the next major release, and remove them at a later time, to be determined later.

**Comment by gnomeontherun** [comment]
That is actually the plan see #2162

**Comment by mathisscott** [comment]
Closing this in favor of #2162
