### ISSUE TITLE
datagrid checkboxes ?

### ISSUE THREAD

**Issue by 19Arne75** [vmware/clarity#1467]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

That checkboxes appear as in single selection.
Maybe its something simple im missing here ?
### Actual behavior

No checkboxes for selection in datagrid
### Reproduction of behavior

https://plnkr.co/edit/S4rWYFRCPq7Iyd77lIO7?p=preview

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@19Arne75: You need to make sure that `selected` is not null. Take a look at this plnkr: https://plnkr.co/edit/FYz32MZdcGiQRJ6M7mop?p=preview

Please feel free to reopen the issue if you have more questions.
