### ISSUE TITLE
Server-Driven Datagrid - Triple state sort.

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#1468]
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior

Remove sort from column by third click:
1. Sort
2. Reverse
3. No sort 

This feature required for https://github.com/vmware/clarity/issues/1067

### Actual behavior

Currently sort of column removed only by pressing another column's sort.

**Comment by mfp22** [comment]
Any idea when this will be implemented?

**Comment by mathisscott** [comment]
For the design, I recommend up arrow, down arrow, and then remove arrow as the three states (per existing datagrid sort design)

**Comment by brian15co** [comment]
Any idea when this will be implemented?

**Comment by gnomeontherun** [comment]
It's not currently in progress but please provide a use case or more details.

**Comment by brian15co** [comment]
Tons of use cases. Any application designed for dealing with large datasets

https://github.com/vmware/clarity/issues/1067#issuecomment-574262941

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
