### ISSUE TITLE
Update Signposts docs typos

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1471]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No typos on the [Signposts](https://vmware.github.io/clarity/documentation/signposts) docs page

Description
A vertical scrollbar (browser default) may be used if the content **exceeds** the maximum height of the dialog.

Interaction
Clicking the icon triggers the signpost. It remains visible until the user clicks the close icon or clicks anywhere outside of the **dialog** to dismiss it. To keep the interface uncluttered, only one signpost is displayed at a time. When a dialog is **visible**, clicking an icon to open another one automatically dismisses the previous dialog.

Recommendations
* Use sparingly as a device to add immediate, **relevant** information

### Actual behavior
Description
A vertical scrollbar (browser default) may be used if the content *exeeds* the maximum height of the dialog.

Interaction
Clicking the icon triggers the signpost. It remains visible until the user clicks the close icon or clicks anywhere outside of the *dialig* to dismiss it. To keep the interface uncluttered, only one signpost is displayed at a time. When a dialog is *visibl*, clicking an icon to open another one automatically dismisses the previous dialog.

Recommendations
* Use sparingly as a device to add immediate, *relevent* information

**Comment by hippee-lee** [comment]
Closed with PR #1484
