### ISSUE TITLE
When opening a DropdownMenu with code, it is not positioned correctly. 

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1474]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

When `*clrIfOpen` is set to true on a `<clr-dropdown-menu>`, the menu is not positioned correctly. 
`DropdownMenu` should wait to position itself until after the dropdown toggle has finished rendering. The positioning issue happens only when the user has set `*clrIfOpen="true"` initially (ie when the dropdown component is loaded). If you toggle the menu after the initial load, the menu again starts to position correctly.

### Expected behavior

On first render the DropDownMenu should be positioned correctly.
![image](https://user-images.githubusercontent.com/1426805/30501355-1efb600e-9a30-11e7-986a-9bfe9b454ffd.png)

### Actual behavior

Dropdown menu is not positioned correctly

![image](https://user-images.githubusercontent.com/1426805/30501328-0634c66e-9a30-11e7-8bed-0731cd1799c1.png)

### Reproduction of behavior
https://plnkr.co/edit/7YKBJGywhlLeK6nK7Hhp?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version: 0.10.x

* **OS and version:** All

* **Browser:** [all]

**Comment by mathisscott** [comment]
This seems to happen with a page/component that is rendered with a dropdown opened programmatically (not from user-action).

Open question about whether fixing this or not will cause regression -- due to having to move the rendering/opening to a different part of the lifecycle.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
