### ISSUE TITLE
Wizard doesn't call the current page callback for clrWizardPageOnCommit when navigating through the TOC.

### ISSUE THREAD

**Issue by bstoicov** [vmware/clarity#1477]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When in a wizard I navigate forward using the TOC of the wizard I expect at least the current page's clrWizardPageOnCommit callback to be called. This is needed in order not to track each possible change on the page that has to be validated/included in the RTC page.

### Actual behavior

Currently the wizard only goes through the clrWizardPageOnCommit callback when the navigation is done using the Next button. 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
How are you navigating forward using the TOC if the page isn't already marked as completed?

Are you navigating backwards and then forwards again using the TOC?

A [plunkr would help](https://plnkr.co/uNwwZe).

**Comment by bstoicov** [comment]
Yes, exactly. This happens when we navigate back to a previous page and then forth again using the TOC. And if we change something in this page for example it is not reflected on the RTC page.
That's pretty straightforward and that's shy I haven't put a plunkr example.

**Comment by mathisscott** [comment]
So you would need to add any business logic to make sure a change on Page 2 is reflected on Page 4. Whether that's a shared model or whatever, that's your choice.

Navigating forward with the left nav of the wizard does not submit the steps of the wizard. So it doesn't make sense for it to fire an onCommit. Think about if you went back to page 2, changed nothing, and clicked on page 4. Would you fire an onCommit for page 2? Why? And what about page 3? Would you fire an onCommit for that?

You should apply functionality to the `clrWizardCurrentPageChanged` on `clr-wizard`. You can then reset/update any pages you want when the left-nav is used to navigate wherever.

**Comment by bstoicov** [comment]
You say navigating with the left nav does not submit the steps of the wizard and that's why it doesn't fire onCommit. This seems strange to me as I expected that navigating forward with the left nav and with the Next button is absolutely the same thing. It turns out it's not and now I see that the navigation forward with left nav works only if I've navigated forward with the Next button before that. And that makes things even weirder for me simply because both these navigations move me forward. 

To answer your question I wouldn't care if anything is changed on the page or not. It doesn't matter. Just like it doesn't matter if I've change anything or not when I click Next (onCommit is always fired). And it is needed simply because the content/selection in the next page may depend on what's  on the page you're moving away from and the previous selection may now be invalid. And because of that in your example I would expect the same thing for page 3 as well. Otherwise every page needs to know if changes on it could possibly affect the next pages in order to force going through them.

**Comment by mathisscott** [comment]
```
Otherwise every page needs to know if changes on it could possibly affect the next pages in order to force going through them.
```
Sometimes that is a requirement.

At the end of the day, the Wizard is a modal that reveals a succession of forms. The left nav is a convenience to allow people to go backwards to forms they have already completed. So they don't have to click back -> back -> back and next -> next -> next.

In the case you've described, you're absolutely fine with the left nav “submitting” the wizard’s content. And you can customize the wizard to do that for your specific use case.

But having links outside of the content area of the wizard submit forms inside the content area is not a practice that we are going to make the default in the Wizard.
