### ISSUE TITLE
Input Group

### ISSUE THREAD

**Issue by srivathsah** [vmware/clarity#1478]
Thanks team for a wonderful library.

The only issue I'm currently having is setting up an input group like in bootstrap, I am trying to use this in login form, the input and the button are not falling in 1 row and I have tried as much as I can, is there anything equivalent of [bootstrap input group](https://getbootstrap.com/docs/4.0/components/input-group/) in clarity ?

An example use case is checking for username while signing up, what other alternative setup would you recommend for this use case if this is not there in clarity in-built

**Comment by gnomeontherun** [comment]
Hi @srivathsah, we don't currently have something an equivalent of input groups for Clarity. We are taking a look at the form components in Clarity and will be bringing a fresh UX to forms, so I'm tagging @reddolan to make sure he sees this request.

**Comment by dorthrithil** [comment]
@srivathsah For checking the username availability in a form you could use an async validator and then indicate errors via the standard input alerts.

**Comment by gerinjacob** [comment]
This will be really useful. We have requirement to show inputs grouped like,
<img width="378" alt="image" src="https://user-images.githubusercontent.com/7568688/73774351-d4980880-47a9-11ea-8d60-d4fe7a50d4c9.png">
Any plans to support this?

**Comment by hippee-lee** [comment]
This is in the backlog but has not been given a priority. 
We are open source so if you decide to contribute please take a look at our [contribution guidelines](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md). 
I'm happy to dig into it with you if you are interested.

**Comment by gnomeontherun** [comment]
This has been implemented in Core forms and will be the recommendation for using groups.

https://clarity.design/storybook/core/?path=/story/forms-preview-input-groups-getting-started--page
