### ISSUE TITLE
Clarity icons not coming up on prod build

### ISSUE THREAD

**Issue by evdigitech** [vmware/clarity#1482]
Clarity icons not coming up on prod build

[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Clarity icons should come up on production build. 

### Actual behavior
Clarity Icons not coming up on the production build. SVG tag is not getting appended inside clr-icon tag. Cannot read property require of undefined console error is coming.

Any help would be highly appreciated.

**Comment by mathisscott** [comment]
How are you pulling Clarity Icons in? And what build tool are you using?

CC: @Shijir

**Comment by evdigitech** [comment]
Currently i am adding Clarity icons using angular-cli.json file. Adding clarity icons css on style and js on script. For building production build i am using npm command. (npm run build:prod)

Is there any problem are you foreseeing?

**Comment by mathisscott** [comment]
If you are adding Clarity Icons via your angular-cli.json, I don't believe you need to add it via a script tag as well. I believe you should be doing what is listed under "Load Clarity Icons API and icon sets in Typescript" in the [Clarity Icons documentation](https://vmware.github.io/clarity/icons/clarity-icons).

**Comment by evdigitech** [comment]
thanks @mathisscott .. You are a saviour. My issue got resolved by importing the clarity icons in app.component.ts file.
