### ISSUE TITLE
[WEB] SEO for our documentation

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#1485]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Search engines should be able to crawl all pages of our website, not just the home page. It is especially important for our documentation pages.

### Actual behavior

Currently, only the home page is crawlable.

### Potential solutions

1. I believe the reason the home page works is that it's the only one that's part of the JS bundle that's loaded synchronously with the website. One solution would be to load synchronously (or have the Angular router load synchronously) the bundle corresponding to the current route, rather than always the home page. Not sure if this is possible.
2. Another option would be to move off of [github.io]() and host on AWS or somewhere else, at which point we could pre-render with Angular Universal or another similar utility.
3. Anything outside of these two solutions. Just always evaluate how much it brings to the table vs the amount of work it requires. For instance, pre-rendering with Angular Universal is probably more work to set up, but it also improves the website's speed for every user.

**Comment by youdz** [comment]
The current estimate is only for the investigation, we will increase it depending on the solution we pick to take implementation into account.

**Comment by gnomeontherun** [comment]
I've created a document with notes about our primary options (that I've come across).

Short summary: we can prerender our application so every url is a static html file. We still might want to consider changing how we host to have more control than Github Pages allows. I think its worth the effort, though its a bit unknown how easily the current site will prerender (had issues getting it to run on our site, but was able to run on another sample). 

https://docs.google.com/document/d/15XJunPXSrexqsCu6oGlH6QmfN203YqAHL9Yrq6sw-aE/edit?usp=sharing

**Comment by mathisscott** [comment]
Closing due to implementation being covered by #1526
