### ISSUE TITLE
Signpost height/position issues in datagrid and cut-off issue in modal

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#1487]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
* Signpost should not be taller in expanded area of datagrid.
* Signpost arrow position should not be that far to its icon.
* Signpost should not be chopped inside a modal.
* Signpost header should not be that low.

### Actual behavior
Described as above.
<img width="780" alt="screen shot 2017-09-19 at 12 26 55 pm" src="https://user-images.githubusercontent.com/8813134/30611659-d1c844aa-9d36-11e7-82db-8b02d561af10.png">
<img width="679" alt="screen shot 2017-09-19 at 12 26 40 pm" src="https://user-images.githubusercontent.com/8813134/30611664-d7fa2672-9d36-11e7-95f1-43dc9516e1d6.png">

### Reproduction of behavior
Please see code and comment in Plunker.

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://plnkr.co/edit/fxlV8B?p=preview

### Environment details

* **Angular version:** 4.3.0

* **Clarity version:** 0.10.2

* **OS and version:** MacOS El Captain

* **Browser:** Google Chrome | 60.0.3112.113 (Official Build) (64-bit)

**Comment by mathisscott** [comment]
The modal cutoff issue may be fixed with #932 ... Check back after that is done.

The other issue still needs to be looked at <= @hippee-lee

**Comment by mathisscott** [comment]
@hippee-lee 
Any word on this?
