### ISSUE TITLE
Spinner Button component (new)

### ISSUE THREAD

**Issue by gracesnoh** [vmware/clarity#1488]
### Description
![spinnerbtn](https://user-images.githubusercontent.com/8237984/30615409-bd346ee4-9d43-11e7-8c52-c2cb6808cd82.gif)
A spinner button component is a button component that generates a spinner inside of a button to indicate that a process is running. At the end of the process, a check icon is generated to indicate that the process is complete.

### Use cases under consideration
- page requests that require time to process
- buttons (all types & sizes)
- icon buttons
- forms: inline buttons

### Documentation
- Key features: add/remove spinners to all types of button components, apply screen reader text while process is running, and add/remove success state*
- We recommend using spinner buttons only for actions that require some time to process**
- We do not recommend using spinner buttons for links, navigating to different pages, or opening/closing a modal or wizard

*This feature may apply to situations where an action navigates to a new page but still requires time to process (i.e. logging in)

**For longer running processes, we recommend using a progress indicator or _circular progress indicator (not a currently existing component)_

#### States
![stateimg2](https://user-images.githubusercontent.com/8237984/30570399-f12d2294-9c95-11e7-9e44-b74f687bb2f6.png)

1. **Default state** acts just like a normal solid button would, darkening on hover.
2. **Loading state** transitions into a disabled state, hides the button label, and injects a rotating spinner.
3. **Success state** remains disabled, injects a check icon to indicate the success of an action, and returns back to default state.

##### Toggling Success State
- Success state can be toggled on/off according to the type of process that is taking place
- Ex) If a spinner button is applied to a “Log In” action, the success state should be toggled off because the process will result in navigating to a new page.

#### Usage
- For processes that require time to take place, such as creation or deletion actions
- For longer running processes, we recommend using a progress bar or a circular progress indicator (component in progress)

![do](https://user-images.githubusercontent.com/8237984/30570667-8a4147ca-9c97-11e7-85f9-8f7cdb49d6e1.png)
- Use spinner buttons for actions that update the content on the current page without navigating to a new one.

![dont](https://user-images.githubusercontent.com/8237984/30570679-a03234e0-9c97-11e7-9857-a04039e1da23.png)
- Use spinner buttons for actions that will navigate to a different page or open/close a modal or wizard.

#### Accessibility
- For accessibility, screen reader text is available for the Loading and Success button states
- Apply contextual text such as “Saving” and “Saved” to inform screen readers of what is happening

##### Solid
![solid](https://user-images.githubusercontent.com/8237984/30617452-f850ca5c-9d4a-11e7-9d3a-aa0e24cac5a1.png)
##### Outline
![outline](https://user-images.githubusercontent.com/8237984/30617537-54ae90d6-9d4b-11e7-93b9-ede28817e7aa.png)
##### Flat
![flat](https://user-images.githubusercontent.com/8237984/30617608-b55ef736-9d4b-11e7-84c9-8265d9028f84.png)
##### Icon
![icon](https://user-images.githubusercontent.com/8237984/30617719-3b04a43a-9d4c-11e7-9fca-d50d82f18440.png)
##### Small
x-small spinner: 13px by 13px, 1.5 border thickness

![small](https://user-images.githubusercontent.com/8237984/30618197-3f9d7e5c-9d4e-11e7-91d8-9ce152e98b05.png)

##### Block
![block-default](https://user-images.githubusercontent.com/8237984/30618202-457179c8-9d4e-11e7-8094-5879d651ab42.png)
![block-loading](https://user-images.githubusercontent.com/8237984/30618210-4bfbacc8-9d4e-11e7-95ac-6968f6b7b0f5.png)
![block-success](https://user-images.githubusercontent.com/8237984/30618213-4ed978e4-9d4e-11e7-8a50-3dfb87dd7cbd.png)

##### Inverse
inverse spinner: full circle (white border, 15% opacity), 1/3 circle (#007CBB border)

![inverse](https://user-images.githubusercontent.com/8237984/30618215-526eec50-9d4e-11e7-9450-4078299dd92b.png)
##### Button Group
![btn-grp](https://user-images.githubusercontent.com/8237984/30618225-5962d4fe-9d4e-11e7-946f-fa8ff08faccc.png)

#### onClick
Default state -> Loading state
![onclick](https://user-images.githubusercontent.com/8237984/30615653-679cda9c-9d44-11e7-8dc4-c1a48a52f880.gif)
1. Button changes to disabled state
2. Button label fades out (opacity: 0, animation-duration: 100ms)
3. Spinner fades in (opacity: 1, animation-duration: 100ms, animation-delay: 200ms)

#### onSuccess
Loading state -> Success state
![onsuccess](https://user-images.githubusercontent.com/8237984/30615702-92f40260-9d44-11e7-93ca-c795605e7f0d.gif)
1. Spinner fades out (opacity: 0, animation-duration: 100ms)
2. Check-line icon scales in (scale: 1, animation-duration: 300ms, animation-delay: 100ms, curve: Spring(damping:0.5))

#### return to default
Success state -> Default state
![reset](https://user-images.githubusercontent.com/8237984/30615760-c4b1eeb6-9d44-11e7-948a-7bf8c391b0cd.gif)
1. Check-line icon scales out (scale: 0, animation-duration: 300ms, curve: Spring(damping:0.5))
2. Button changes to default state
3. Button label fades in (opacity: 1, animation-duration: 100ms, animation-delay: 200ms)

Related/Original Issues: #1139 and #463

**Comment by joshjohnson72** [comment]
This looks good, but is there an onFailure state?  I didn't see any examples.

**Comment by gracesnoh** [comment]
@joshjohnson72 Good question, for now I think it would be best to display errors outside of the button (in the form of an alert or even an inline form validation). The spinner would stop before it gets to the success state, and return back to the default state:
![failstate](https://user-images.githubusercontent.com/8237984/30620264-2807ed1c-9d59-11e7-9d4d-b586cad4210a.gif)

**Comment by joshjohnson72** [comment]
I agree that when you hit an error you need space to explain the error, and the button doesn't afford that.  Only downside I see is that space has to be reserved for that possible error alert, or all the other elements will be shifted.

**Comment by gracesnoh** [comment]
@joshjohnson72 Thanks for bringing that up, what I meant to convey wasn't an empty space reserved for an alert but rather the point that an alert would show up if there was an error. Correct me if I'm wrong, but alerts take up the entire width of the screen and should only shift elements down vertically:
![table-failstate](https://user-images.githubusercontent.com/8237984/30656740-e361f64e-9de9-11e7-96d7-9b4b16e149fc.gif)

**Comment by joshjohnson72** [comment]
From the Clarity site on Alerts: "Alerts could appear within modals. It is recommended that no more than one alert appear within modal. Their function should not ve to validate, validation should be done inline and closer to the error itself."

**Comment by mathisscott** [comment]
A couple of additional notes here:

• This component will take the place of our current "Loading Button". If at all possible, we should repurpose that directive so we can introduce this functionality without a breaking change.
