### ISSUE TITLE
Spotlight (new component request)

### ISSUE THREAD

**Issue by arjunrao2709** [vmware/clarity#1489]
### Description
The spotlight component is used to provide a detailed in-context widget-level informational help. This is useful in cases for explaining the functionality of UI controls to users that have not been exposed to step-by-step onboarding procedures, or as an on-demand informational experience for users that don’t engage with the software regularly and need to be reminded of functionality.
 
### Use cases under consideration
- Engage/disengage spotlight state for a widget
- Show relevant spotlight help text
- Expose mechanism in spotlight to initiate actions
- Switch spotlight focus between widgets on a screen

![spotlight](https://user-images.githubusercontent.com/951949/30623576-005cd8cc-9dd6-11e7-8e9c-8c98526b5a5a.gif)

[Access Invision Link](https://vmware.invisionapp.com/share/WADKHMX7B)
 
### Future use cases
- Add mobile support
 
### Documentation
- Use when there is a need to show additional information about a card without using primary actions  (Note : Primary actions should be within the card)
- Have a toggle switch on the widget
- On toggle, the widget will enter a modal state such that other items on the page cannot be interacted with.
- The modal state can have multiple callouts for the widget
- Each callout may expose additional actions
- Clicking on “SEE ALL SPOTLIGHTS”, opens a dropdown that gives the user a selection of all available widgets that support spotlights on the page.
- Pressing ESC/clicking on close disengages the spotlight mode and returns to the pages default state.
 
### References
Chardin.js, intro.js, Twitter, Facebook Status Update

**Comment by mathisscott** [comment]
@jeeyun 
This is a candidate for Clarity Tools/Extras/In-Contacts 

Please move to your issue tracker when you get that set up.

**Comment by coryrylan** [comment]
Closing as stale. This may be a use case for future patterns work but likely not a component to be implemented in the near future. If this is still relevant please reopen with updated details.
