### ISSUE TITLE
Documentation 0.9

### ISSUE THREAD

**Issue by Dejahna** [vmware/clarity#1490]
Hello

I started to write an application with version 0.9 and I can no longer find the documentation for this version. I would say it would be complicated and expensive to migrate to 0.10. Is there a way to check the documentation for version 0.9?

Regards,

**Comment by mathisscott** [comment]
Currently, our documentation only accounts for the latest version of Clarity. We have an issue open to make older version docs available ( #1370 ).

Your best option at this time is to either clone our repo, set it to a previous version, and run the docs locally or to review the docs through the code here on github.

Please subscribe to issue #1370 for updates.

Closing this as a duplicate.

**Comment by hippee-lee** [comment]
@Dejahna - which version of Clarity 0.9x are you using?

**Comment by Dejahna** [comment]
0.9.13
