### ISSUE TITLE
Datagird single/multiple value selected on init.

### ISSUE THREAD

**Issue by quemica** [vmware/clarity#1493]
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Datagird single and multiple value selected on init.

### Actual behavior
I try to select one model on datagird start, but not one was selected, only if i dont have the `[(clrDgSingleSelected)]` works but then, i can not select any row, with `[(clrDgSelected)]` was the same problem.

**This works but i cant select:**
```
<clr-datagrid>
   ...
   <clr-dg-row *clrDgItems="let val of values" [clrDgItem]="val" [(clrDgSelected)]="val.selected">
      ...
   </clr-dg-row>
</clr-datagrid>
```

**This not work, but i can select, but the initial item (model) its not selected**

_**model** has the object i want to select._
```
<clr-datagrid [(clrDgSingleSelected)]="model">
   ...
   <clr-dg-row *clrDgItems="let val of values" [clrDgItem]="val" [(clrDgSelected)]="val.selected">
      ...
   </clr-dg-row>
</clr-datagrid>
```

### Environment details

**Angular version:** 4.4.3

**Clarity version:** 0.15.5

**Comment by adityarb88** [comment]
@quemica: The best place to ask questions where something is not working is on StackOverflow with the `vmware-clarity` tag. More info here: https://vmware.github.io/clarity/get-started#stackoverflow. Also it would help us out a lot if you can provide plnkrs which replicate the issue that you are facing.

For the issues that you mentioned above:
1. Multiple Selection: https://plnkr.co/edit/DWGaD4eN4IxqrRyiKeTR?p=preview
2. Single Selection: https://plnkr.co/edit/FZKt2Z0y75w6D2fJ6FgP?p=preview

Please refer to the above plnkrs. Is this what you are looking for?

Closing the issue based on this. Feel free to reopen this issue if you have any more questions.

**Comment by quemica** [comment]
Yes, that was i looking for, my error was on `ngOnInit()`.

**Thanks** 👍
