### ISSUE TITLE
<clr-tabs> display same row

### ISSUE THREAD

**Issue by superpck** [vmware/clarity#1494]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
Add another clr-tabs in clr-tab-content and display next row
<img width="635" alt="screen shot 2560-09-28 at 11 51 15" src="https://user-images.githubusercontent.com/977294/30950017-30db4690-a444-11e7-8f90-bfa9e5d10ef0.png">

### Actual behavior
Display same row
https://plnkr.co/edit/5beEC3p7GPJDTUDVfmcD?p=preview
<img width="647" alt="screen shot 2560-09-28 at 11 56 45" src="https://user-images.githubusercontent.com/977294/30950020-38353568-a444-11e7-9493-a9575864abd2.png">

### Environment details

* **Angular version:** 4.3.X

* **Clarity version:** 0.10.5 

* **OS and version:**  macOS 10.12.6

* **Browser:** all

**Comment by siteslave** [comment]
https://plnkr.co/edit/bSJNsxdWfkfG1wElLeMY?p=preview

![screen shot 2560-09-25 at 15 19 51](https://user-images.githubusercontent.com/526890/30798828-1e787572-a205-11e7-967a-46147f400554.png)

**Comment by reddolan** [comment]
@superpck this seems very confusing to the user. I am worried that they would think there is a bug seeing the 2nd level tabs and think they are the 1st level tabs wrapped to another line. There isn't enough visual differentiation to tell them apart. Is there a reason why you aren't using other navigation controls to build your content hierarchy?
