### ISSUE TITLE
header logo size changed in 0.10.x when using <span class="clr-icon clr-vmw-logo"></span>

### ISSUE THREAD

**Issue by adumesny** [vmware/clarity#1496]
![broken_app_icon](https://user-images.githubusercontent.com/3496166/30715560-ac659d3e-9ecb-11e7-8ba0-cb76e96481ca.png)
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```
### Expected behavior
header app icon to say the same (see image)

### Actual behavior
much smaller svg area

--- from slack channel ---
Aditya Bhandari [12:42 PM] 
i am hearing this for the first time but yes we should have a separate class to style the branding icon in case someone is not using the clr-icon approach

Shijir Tsogoo
[12:44 PM] 
I don’t think there was a breaking change introduced in clarity cons in 0.10.x. I think it was a style that’s removed from the header component in 0.10.x . We encountered the same issue on our website logo.

Aditya Bhandari [12:44 PM] 
yes. this is not a clarity icons issue. its a clarity ui issue

### Reproduction of behavior
switched from 0.9.6 to 0.10.4 and while doc has clearly stated borken API changes, it doesn't mention the app icon in the header being one of them.

the following header HTML using class="clr-icon clr-vmw-logo" as an example
```
 <header class="header-6">
    <div class="branding">
      <a [routerLink]="['/']" class="nav-link">
        <span class="clr-icon clr-vmw-logo"></span>
        <span class="title">Flying Dragon</span>
      </a>
    </div>
```
will now render the svg about half the size. using 0.10.4
```
<clr-icon shape="vm-bug"></clr-icon>
```
will fix the issue *but require it to be a clarity icon*.

in my app I have my own svg icon and was using CSS style to apply my custom image, instead of built in ones...

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details
switched from 0.9.6 to 0.10.4 and while doc has clearly stated borken API changes, it doesn't mention the app icon in the header being one of them.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
FWIW...

All we need to do is add `.clr-icon` back to this selector...

https://github.com/vmware/clarity/blob/8b8842042ea14a23c39318de8bd4d31f4beba219/src/clarity-angular/layout/nav/_header.clarity.scss#L78

**Comment by adityarb88** [comment]
@mathisscott: Yes!
