### ISSUE TITLE
Modal produces an error when pressing ESC key

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1498]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

An html with a modal component should not produce errors when pressing the ESC key.

### Actual behavior

When  the modal is hidden, when pressing the ESC key, it's generating an error:

![image](https://user-images.githubusercontent.com/1977391/30729953-e416ef88-9f95-11e7-8948-0d881acb8987.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.6 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Hi @whizkidwwe1217 
I know how much you ❤️ [plunkr](https://plnkr.co/edit/uNwwZe?p=preview). But could you replicate your issue in one this time?

I've tried reproducing this on both the website and plunkr and cannot.

**Comment by whizkidwwe1217** [comment]
Hi @mathisscott 
You can definitely replicate it with the default [plunkr](https://plnkr.co/edit/uNwwZe?p=preview). To replicate it, don't open up or show the modal. Just run the plunkr and hit the ESC key. :-)
![image](https://user-images.githubusercontent.com/1977391/30769436-d7208f18-a04a-11e7-8e41-bd504f34c5d3.png)

**Comment by mathisscott** [comment]
Ah. Got it. I was opening the modal first. 

I'll try replicating it again on Monday. Thanks!

**Comment by whizkidwwe1217** [comment]
@mathisscott  Thanks!

**Comment by hippee-lee** [comment]
@mathisscott this issue is related to https://github.com/vmware/clarity/pull/1472
In this case, it should be putting focus onto the body.

I'll look into it.
