### ISSUE TITLE
Login page decorative background doesn't expand to fit large screens

### ISSUE THREAD

**Issue by haykman** [vmware/clarity#1499]
# Clarity default login page have a issue with large screens.
Issue is reproducible on any browser.

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Login page decoration should fit white space.

### Actual behavior
The plaid decorative background on the install page gets cut off after a screen size grows to a large resolution. [See screenshot](https://i.imgur.com/fhs33L9.png) (From Clarity official documentation )

### Reproduction of behavior
Open https://vmware.github.io/clarity/documentation/login 
Zooming out page until issue will be visible

### Environment details

* **Clarity version:** Latest

* **Browser:** [all]

**Comment by mathisscott** [comment]
@haykman 
We couldn't reproduce this. Please check to make sure you don't have any custom CSS that is causing this issue.

**Comment by haykman** [comment]
Please see attached video
[2017-09-29_1156.zip](https://github.com/vmware/clarity/files/1343519/2017-09-29_1156.zip)

**Comment by haykman** [comment]
Please reopen this issue.

**Comment by adityarb88** [comment]
Reopening the issue. Will add this to our backlog. Thanks!

**Comment by hippee-lee** [comment]
![screen shot 2018-04-05 at 4 08 59 pm](https://user-images.githubusercontent.com/433692/38396252-b19d5048-38eb-11e8-9a1f-a0bb961c6678.png)

Zoom out with the browser zoom to re-create the issue. This is something we want to fix for high density screens. Included screenshot re-creates the issue.

**Comment by boemska-nik** [comment]
Can confirm issue occurs on hidpi screens & isn't related to browser zoom ![image](https://user-images.githubusercontent.com/11962123/45813721-4cf04d80-bccb-11e8-8b0e-53e10da7062d.png)

**Comment by mathisscott** [comment]
Hi @haykman and @boemska-nik 
Thanks for circling back around on this. We'll have someone take a look at it and try to suggest a workaround while we investigate a fix.
