### ISSUE TITLE
Provide an cursor-style pagination option to the Datagrid

### ISSUE THREAD

**Issue by euskadi31** [vmware/clarity#1502]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
The datagrid should provide a feature to allow paginate with [cursor-style](http://graphql.org/learn/pagination/#end-of-list-counts-and-connections) (in addition to pagination).

### Actual behavior
Currently, we only offer pagination.

### Environment details

* **Angular version:** 4.2.x

* **Clarity version:** 0.10.5

* **OS and version:** all

* **Browser:** all

**Comment by youdz** [comment]
I'm sorry, but none of us are familiar with GraphQL. Could you please detail what supporting cursor-style would mean in terms of API or even design?
Thanks.

**Comment by euskadi31** [comment]
Hi,

- Twitter API example: https://dev.twitter.com/rest/public/timelines
- Facebook API example: https://developers.facebook.com/docs/graph-api/using-graph-api/?locale=en_US#paging

Thanks

**Comment by youdz** [comment]
After looking at these, they rely on a specific sort (the chronological or unique ID order) and they do not seem to support filtering based on any kind of constraints (string search on a property of your objects, value range, ...).

So you'd have a Datagrid without sorting or filtering? It seems to me like this completely defeats the purpose of a Datagrid. I do understand the value of cursor-based pagination for streams of data that you leisurely browse, but the whole point of a Datagrid is to *efficiently* find a specific set of items.
