### ISSUE TITLE
Header-Actions not right aligned

### ISSUE THREAD

**Issue by asollber** [vmware/clarity#1504]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
In the header navigation the header-actions should be right aligned.

### Actual behavior
In my example the cog wheel is left aligned and different than the one shown in the documentation.
Documentation: https://vmware.github.io/clarity/documentation/header

### Reproduction of behavior
Plunker: https://plnkr.co/edit/9XIoWo9UTwwf4hHjXJml?p=preview

### Environment details

* **Angular version:** 4.4.2

* **Clarity version:** 0.10.5

* **OS and version:** macOS

* **Browser:** [ Chrome 60.0.3112.113 | Firefox 55.0.3 | Safari 11.0 ]

I love the wonderful design, keep up the great work!

Alain

**Comment by adityarb88** [comment]
@asollber: Please refer to this plnkr: https://plnkr.co/edit/0bkhOMnOTPjPZri278xS?p=preview. You are using the `.header-nav` incorrectly. `.branding`, `.search` and `.header-actions` are not to be nested inside of `.header-nav`. They all are sibling elements.

**Comment by asollberger** [comment]
Thanks a lot for pointing that out to me.
Best regards
Alain
