### ISSUE TITLE
DataGrid cells not aligned properly

### ISSUE THREAD

**Issue by koldaman** [vmware/clarity#1512]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Data in DataGrid should be aligned one below the other

### Actual behavior
When using clr-dg-pagination and you switch to other page, data in clr-datagrid moves to the right (more, if you have many colomns and the shift is more aparent in the latest columns). Header then does not align with the data in clr-dg-cell. Problem is observable in Google Chrome, IE behaves well. 

### Reproduction of behavior
It is observable even in your examples: (https://vmware.github.io/clarity/documentation/datagrid/pagination)

### Environment details

* **Angular version:** 4.3.0

* **Clarity version:** 0.10.1 (also tried latest 0.10.6)

* **OS and version:** 

* **Browser:** [ Chrome 60.0 ]

**Comment by adityarb88** [comment]
@koldaman: Sorry but I am not able to understand the issue correctly. Could you please provide more details (Plnkr or a Gif)? On our docs pagination page, I cant see what the issue is: https://vmware.github.io/clarity/documentation/datagrid/pagination

Here is the GIF of the datagrid in Chrome and I dont see any issues with the alignment:

![nimbus-record-video-2017-09-26-09-19-42](https://user-images.githubusercontent.com/1426805/30862554-721ef128-a29c-11e7-816c-702cd4bc939c.gif)

**Comment by koldaman** [comment]
Here is my behaviour:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22653353/30900459-64564136-a364-11e7-80d7-78ffb2409887.gif)

**Comment by mathisscott** [comment]
This appears to be happening only on Chrome 60 and only when scrollbars are visible.

**Comment by jayrungta** [comment]
Can confirm, this is happening to me too. Pagination messes up the datagrid cell widths. The headers and the normal cells have different widths. Is there any plan to address this issue?

**Comment by jayrungta** [comment]
Just to add, this looks especially bad if you add borders to cells:

Before:
![1](https://user-images.githubusercontent.com/16365416/31197020-ba99761c-a91d-11e7-9c1a-d666ecd6fbb7.PNG)

After:
![2](https://user-images.githubusercontent.com/16365416/31197030-c4e6848e-a91d-11e7-8474-29ad4bb6bdb8.PNG)

I can't show the data I'm working with, but you get the point. Also, this is not limited to pagination but every time the array containing the datagrid row values is updated.

**Comment by mathisscott** [comment]
@jayrungta 
Thanks for posting more information about your experience with this issue. We have not had time to triage this issue so it has not been moved into our backlog yet.

If someone in the community has time to check this out and give us an idea of why it is happening, It would greatly speed up the resolution of this issue.

As it stands, we will try to triage it when a resource becomes available.

**Comment by jayrungta** [comment]
@mathisscott My guess is that this has something to do with the scroll bar and how a padding is added to the header row whenever there is a scroll bar (even though this is happening for me even when there is no scroll bar). 

Hope you get to triage this soon, as this is a very glaring issue in my project.

**Comment by jayrungta** [comment]
@mathisscott  OK my guess was right, I used the Chrome Dev Tools to check for the padding on the Clarity Datagrid page:

Initially:
![11](https://user-images.githubusercontent.com/16365416/31197725-fa5bed0a-a91f-11e7-9689-929153960a17.PNG)

After changing the page:
![22](https://user-images.githubusercontent.com/16365416/31197729-fdda534a-a91f-11e7-8a18-07b381add83d.png)

A padding of 16px is being added to the header row even when there is no scroll bar. Seems like a bug for sure.

**Comment by adityarb88** [comment]
Was just looking into this issue and I found that whenever a page is changed, the scrollbar appears for a moment and then disappears again:

![image](https://user-images.githubusercontent.com/1426805/31198712-367af9e0-a923-11e7-9247-b36544f75e8e.png)

The scrollbar width is calculated when the scrollbar is visible and then added the to datagrid header.

**Comment by adityarb88** [comment]
The scrollbar is visible for a small amount of time because the items on the page contain more elements than the page size (The previous page's elements remain):

![image](https://user-images.githubusercontent.com/1426805/31199223-b2f637ea-a924-11e7-9eee-aa3b94598548.png)


In the image above instead of 10 items there are 20.

**Comment by jayrungta** [comment]
Wow that's a really good catch. Is this due to the Angular change detector, or something to do with Clarity?

**Comment by jayrungta** [comment]
@adityarb88 Hi Aditya, is there any timeline by which this issue is going to be addressed?

**Comment by jayrungta** [comment]
Thank you @adityarb88 !

**Comment by adityarb88** [comment]
@jayrungta: Just a heads up. This has not been released yet but the fix has been merged into master. It will be released soon.

**Comment by jayrungta** [comment]
@adityarb88 that's good enough for me. Thanks again.
