### ISSUE TITLE
New icons - Storage

### ISSUE THREAD

**Issue by asomaiah** [vmware/clarity#1515]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
There are new icons which are storage specific which are required in the Clarity icon library. These icons are to be used in several sales enablement tools for different products in VMware. 
I have attached samples of the requirements  in the Png. Please ignore the networking icon. The icons required are i. HDD ii. SSD iii. nVMe iV. Disk groups

![snip20170926_19](https://user-images.githubusercontent.com/12735691/30887447-5c1b0c84-a2d0-11e7-9586-ce0bcc0ec2c5.png)

There currently isnt an icon available for disk groups. What a disk group is is a collection of 2-8 hard drives. Can an icon be designed similar to the cluster icon or data cluster icon but with hard drives instead? 

### Environment details

* **Angular version:** Latest

* **Clarity version:** Latest

* **OS and version:** Windows, Mac - Latest

* **Browser:** all

**Comment by mathisscott** [comment]
Thanks, @asomaiah 

We'll look at adding these to volume 9 of icons.

**Comment by KashMoneyMillionaire** [comment]
https://github.com/vmware/clarity/issues/1518 for those looking for it

**Comment by asomaiah** [comment]
@mathisscott Thanks. Would it be possible to give me a rough time frame for when vol 9 of icons will be available?

**Comment by mathisscott** [comment]
I would think the next batch aren't landing until November at the earliest.
