### ISSUE TITLE
Give also the unminified version of CSS in the build

### ISSUE THREAD

**Issue by antitoine** [vmware/clarity#1516]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
For development, have the unminified version of the CSS will improve readability. For example, with the source map activated in Angular Cli, this will allow to directly go to the right CSS rule.

### Actual behavior
Now, only minified version of CSS is available (in Clarity UI and icons). At the end, I think the best behavior is the one described in #87.

### Reproduction of behavior
Install a new project with [Angular Cli](https://github.com/angular/angular-cli#installation), install [Clarity Icons/UI/Angular](https://vmware.github.io/clarity/get-started) and run `ng serve --sourcemap --extractCss`. Go to your browser console and see CSS rules.

### Environment details

* **Angular version:** 4.2.4

* **Clarity version:** 0.10.5

* **OS and version:** Ubuntu 16.04

* **Browser:** Firefox 57

**Comment by mathisscott** [comment]
@jeeyun 
Is this something that can be handled with #1509 ?

**Comment by jeeyun** [comment]
@mathisscott absolutely. we will be generating both minified and unminified versions of css. when the PR is merged, our npm packages will include both.

**Comment by mathisscott** [comment]
Cool. With this info, I'm closing this issue as a duplicate. Thanks!

**Comment by jeeyun** [comment]
@antitoine please feel free to subscribe to #1509 to keep track of the progress.
