### ISSUE TITLE
vol. 9 Icons

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1518]
Epic to hold icons we want to go into vol. 9

**Comment by KashMoneyMillionaire** [comment]
Is there a good place to suggest additions to the icons?

**Comment by mathisscott** [comment]
@KashMoneyMillionaire 
Yep

**Comment by reddolan** [comment]
*Beaker* icon for things like: labs, testing, etc.

**Comment by lil-kim** [comment]
All final icons for this epic:
[vol9_icons.zip](https://github.com/vmware/clarity/files/1507991/vol9_icons.zip)
Please add these icons to Clarity Iconography. Thanks!
