### ISSUE TITLE
Wizard : it misses an event for cancel action

### ISSUE THREAD

**Issue by Rebolon** [vmware/clarity#152]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
When we use the Wizard component, we expect to bind an event to the CANCEL button

### Actual behavior
We cannot bind event to the cancel button whereas we can with the FINISH button

### Evolution
WizardPage class could have an onCancel method that could be bindable to the clr-wizard-page with a clrWizardPageOnCancel

**Comment by Rebolon** [comment]
For those who wants to know why we may need this : 
 * on CANCEL/CLOSE we might want to do some action (route the user to another page, display alert box...) and for instance it hard to do that kind of features

**Comment by Rebolon** [comment]
I did this PR that implement the wished feature https://github.com/vmware/clarity/pull/179
but the functional tests failed (see comment of the PR)

**Comment by jaffoneh** [comment]
@Rebolon wanted to double-check and confirm you'd be okay with including your name on the [community page](https://vmware.github.io/clarity/news/) as a contributor once this change goes in. We would include it as: `Benjamin RICHARD`

**Comment by Rebolon** [comment]
@jaffoneh it's ok for me it would be a pleasure. Thanks
