### ISSUE TITLE
Vertical Nav Responsive

### ISSUE THREAD

**Issue by marvinosswald** [vmware/clarity#1520]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If i add `[clr-nav-level]="1"` to the `clr-vertical-nav` tag i expect it to add the burger button if its on a mobile device.

### Actual behavior
it doesn't, only if i add the following to my `clr-header`
```html
<div class="header-nav" [clr-nav-level]="2">
</div>
```
only does the trick in combination with the directive.

now everything works as expected but with the side effect of an unwanted second level menu and the overflow button. According to the underlaying code it shouldn't depend on that, only thing i can imagine right now is some search like _"is there a `clr-nav-level` directive inside my header"_.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.3.0

* **Clarity version:** 0.10.6

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@marvinosswald: Thanks for filing the issue. We always recommend adding a plnkr replicates the issue that you are facing when you file an issue. Without a plnkr its very difficult to know what the exact issue is.

As for the vertical nav responsive issue, I am not able to replicate it. Please refer to this plnkr: https://plnkr.co/edit/fOH4pJYSSonWSb0VYEh9?p=preview

Closing the issue based on this. Please feel free to reopen this with a plnkr if the above plnkr doesnt work. Thanks!
