### ISSUE TITLE
[Chrome] The ` (backtick character) overwrites next character when using Metropolis

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#1521]
<img width="134" alt="screen shot 2017-09-27 at 9 20 30 am" src="https://user-images.githubusercontent.com/11431579/30925396-93eab8ee-a366-11e7-89ac-01d8b956915e.png">

**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Use a backtick character in a string anywhere on a page. Expect to see the character show up in the string taking up space like any other character.

### Actual behavior

Backtick shows up on top of the next character
<img width="133" alt="screen shot 2017-09-27 at 9 20 41 am" src="https://user-images.githubusercontent.com/11431579/30925432-b06538b4-a366-11e7-93bb-5e21cea2016f.png">

The same exact HTML but with font-family:Arial override:
<img width="134" alt="screen shot 2017-09-27 at 9 20 30 am" src="https://user-images.githubusercontent.com/11431579/30925449-c1ce22be-a366-11e7-8747-787510dbcec0.png">

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/sqv3j5yfSoSJk778hFd4?p=info

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
0.10.x

* **OS and version:** 
MacOS

* **Browser:** 
Only happens on Chrome. Works correctly in Firefox and Safari.
I'm running Version 60.0.3112.113, but this was initially reported a while back.

**Comment by mathisscott** [comment]
@adityarb88 
Have we filed an issue with Metropolis on this yet?

**Comment by aleksashin** [comment]
Hi gents.

What is the ETA for this? VMC console clients are complaining...

Thanks!

**Comment by adityarb88** [comment]
@aleksashin: We are investigating this issue and will get back to you when we have more updates. We have also filed an issue with the font creator @chrismsimpson for more information regarding this. Issue on the Metropolis repo: https://github.com/chrismsimpson/Metropolis/issues/15

**Comment by mathisscott** [comment]
This will be solved when we complete #603

**Comment by adityarb88** [comment]
@mathisscott I don't this #603 will resolve this. The webfont conversion process somehow still does not fix the issue.

Also, I noticed that if you have multiple backtick characters in succession:

```<p>```````````` This line should show multiple backticks</p>```

then it renders like this:

![image](https://user-images.githubusercontent.com/1426805/31951335-c5371b18-b8ab-11e7-9ef0-ae283e452826.png)

I will wait for a reply from the font author before investigating this further.

More info here: https://github.com/chrismsimpson/Metropolis/issues/15

**Comment by mattmutt** [comment]
meanwhile, backtick characters are "back" in action : I've fixed it for just the basic font face, not every permutation of thick , thin, oblique...
https://github.com/vmware/clarity/pull/3353

**Comment by gnomeontherun** [comment]
This is resolved in Clarity City, and the resolution will be to update font.

https://github.com/vmware/clarity-city/commit/ac8e186c8d872b73a53734323ce13caa025b3e19
