### ISSUE TITLE
Custom Scrollbars

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1522]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Custom scrollbars for Clarity components which behave the same across all browsers and operating systems.

### Actual behavior

Our components use the default scrollbars provided by the browsers.

Issues with the default scrollbars:
1. They look different because each browser has its own implementation. No way to customize the scrollbar across all browsers.
2. Scrollbars behave differently on different operating systems based on user settings. For eg: In some cases, Mac scrollbars appear only when the user scrolls while on Windows they are visible all the time.
3. In some cases they take up space inside of the overflowing container and mess up the alignment.

### Reproduction of behavior

Few components which have more cases where the content overflows and the scrollbar appears:
1. Sidenav
2. Vertical Nav
3. Datagrid

Can be reproduced on our website: https://vmware.github.io/clarity/documentation

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** All

* **OS and version:** All

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
Came across this once upon a time https://grsmto.github.io/simplebar/
