### ISSUE TITLE
1 pixel off issue with Signposts inside of DataGrids

### ISSUE THREAD

**Issue by bbronson** [vmware/clarity#1528]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Signposts in datagrids should be vertically center aligned with text

### Actual behavior
Signposts are down by 1 pixel

### Reproduction of behavior
https://plnkr.co/edit/JUOO6yikPjVQPaLHsdTt?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** latest

* **OS and version:** Mac 10.11.6, 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] Chrome

**Comment by mathisscott** [comment]
This may actually be fixed in #1079. Will check back after that is merged in to verify.
