### ISSUE TITLE
Fix invalid SVG for cpu icon

### ISSUE THREAD

**Issue by jenil** [vmware/clarity#1529]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

The CPU icon has invalid XML. XML parser throws an error for attributes without value.

Remove the trailing `clr-i-alert` in [this line].(https://github.com/vmware/clarity/blob/master/src/clarity-icons/shapes/technology-shapes.ts#L663
)

**Comment by mathisscott** [comment]
Thanks for reporting this @jenil. I'll see that it is fixed with #1330 .
