### ISSUE TITLE
Move off Bootstrap - v2.0

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1531]
Clarity started out using Bootstrap (early version 4.0) underneath its custom styles. This was helpful in getting us further down the road in the beginning and it also helped with early adoption because so many VMware product UIs were built on top of it.

As Clarity has matured, we have found ourselves moving away from the basics that we had inherited from Bootstrap. The situation has reached the point where, in the Clarity code base, we only lean on the Bootstrap library for 3-4 files. Additionally, we find ourselves having to write our CSS selectors in such a way that they are “compatible” with Bootstrap — even though the code behind them is not Bootstrap.

Moving off of Bootstrap gives us the following advantages:

• A flatter set of CSS selectors that would make it easier for our users to customize Clarity
• A fully pre-fixed CSS library that would allow people to use other CSS libraries in addition to Clarity
• A predictable naming convention (which Bootstrap does not have) which would make it easier for people to learn and use Clarity, as well as contribute back to the project

This is not something that we want to do in version 1.0. It would be a major breaking change for everyone who uses Clarity. We want to release a stable 1.0 first and then start wrapping our heads around how we plan to deprecate and remove the Bootstrap library from Clarity. Note that this includes a migration strategy that may initially be just as simple as loading Bootstrap and Clarity together.

**Comment by gnomeontherun** [comment]
At this stage, we've moved away from it or encapsulated the little bit we have left. Closing this as largely done, and individual work depends on a lot of static, smaller components that base ought to reimagine anyways.
