### ISSUE TITLE
How to change the selected index of clr-tabs by code

### ISSUE THREAD

**Issue by alonbez** [vmware/clarity#1535]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
There is a way to changes the currnet selected tab od clr-tabs?
for exmaple:
**HTML**
<clr-tabs #tabs>

**CODE**
tabs.selectedIndex = 2;

### Actual behavior
Didn't found any option to do that.

Thanks!

**Comment by mathisscott** [comment]
@alonbez 
Assuming you are on 0.10.x... Use the `clrIfActive` directive. 

Look under the `Tabs with two-way binding` header [in the Tabs documentation](https://vmware.github.io/clarity/documentation/tabs) for an example.
