### ISSUE TITLE
Datagrid column cannot be shrunk

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#1537]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I have a wizard which has a datagrid in it. The datagrid column resizing works fine if the wizard is opened initially.

### Actual behavior
Initially the wizard is not opened initially, opening the wizard will cause datagrid column not able to shrink.

After debugging I found the following line NaN:
https://github.com/vmware/clarity/blob/55e90f4b474a25fa259d387829e8f7db66eb5b80/src/clarity-angular/data/datagrid/render/column-resizer.ts#L45

Which causes the following line NaN too:
https://github.com/vmware/clarity/blob/55e90f4b474a25fa259d387829e8f7db66eb5b80/src/clarity-angular/data/datagrid/render/column-resizer.ts#L95

I noticed that when wizard is not opened yet, the datagrid (Line 45) is already being initialized.

### Reproduction of behavior
https://plnkr.co/edit/lgSJrYiNBzKphdR9DBsH?p=preview

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.2

* **OS and version:** MacOS El Captain

* **Browser:** Chrome 61

**Comment by Shijir** [comment]
@yaooluu Thanks for filing this issue with our favorite Plunkr 😄 . As it looks like you are using Clarity v0.9, we will backport the fix to v0.9.x.

**Comment by mathisscott** [comment]
@Shijir 
When are we planning to backport this to 0.9?

**Comment by mathisscott** [comment]
@Shijir 
Any update on this?
