### ISSUE TITLE
Clarity Icons do not show up when a production build is made.

### ISSUE THREAD

**Issue by MrfksIv** [vmware/clarity#1538]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When a development build is made, with ng build -dev, all icons show up ok. This should be
also the case for the production build.

### Actual behavior
When `ng -prod` is used, the clarity icons fail to load. In the developer tools console the following error shows up:

scripts.24c7f1769bde070aab98.bundle.js:2 Uncaught TypeError: Cannot read property 'require' of undefined
at scripts.24c7f1769bde070aab98.bundle.js:2
at scripts.24c7f1769bde070aab98.bundle.js:2
at scripts.24c7f1769bde070aab98.bundle.js:18
at scripts.24c7f1769bde070aab98.bundle.js:2
at scripts.24c7f1769bde070aab98.bundle.js:18
(anonymous) @ scripts.24c7f1769bde070aab98.bundle.js:2
(anonymous) @ scripts.24c7f1769bde070aab98.bundle.js:2
(anonymous) @ scripts.24c7f1769bde070aab98.bundle.js:18
(anonymous) @ scripts.24c7f1769bde070aab98.bundle.js:2
(anonymous) @ scripts.24c7f1769bde070aab98.bundle.js:18

It should be noted that with a development build, everything is ok and all icons show up correctly.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X
`
@angular/cli: 1.4.4
node: 8.6.0
os: win32 x64
@angular/animations: 4.0.2
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/compiler-cli: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/platform-server: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.4.4
typescript: 2.2.0
`
* **Clarity version:** 
`
    "clarity-angular": "0.10.0-alpha.4",
    "clarity-icons": "0.10.0-alpha.4",
    "clarity-ui": "0.10.0-alpha.4",
`
* **OS and version:** 
Windows 7 Professional

* **Browser:** [all ]

**Comment by adityarb88** [comment]
@MrfksIv: I don't believe we have the sufficient information to replicate this issue. How are you loading the Icons? If you are using angular-cli, can you provide the respective config files to show how you load the icons?

You could also take a look at our website branch (we use angular-cli for our website and the icons work fine in prod mode) here: https://github.com/vmware/clarity/tree/new-website

cc: @Shijir

**Comment by MrfksIv** [comment]
I just switched to another clarity version and everything now works fine. The problem appeared right after I updated angular-cli to 1.4.4 for some reason. Anyway, I am closing this as it is no longer an issue.
