### ISSUE TITLE
After a tab is selected, selection rectangle remains visible

### ISSUE THREAD

**Issue by tishun** [vmware/clarity#1545]
**Select one ...**  (check one with "x")
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When the user selects a given tab the tab selection should change to the new tab.
The tab selection of the new tab should be the same as the tab selection from the first tab.

### Actual behavior
When a new tab is first selected a selection box appears around the tab surface.
When the focus is changed to another component the selection box disappears.

### Reproduction of behavior
Visible in Clarity showcase, see attached screenshot :
![Screenshot](https://ibb.co/b8zHRG)

### Environment details

* **Angular version:** 4.4.4

* **Clarity version:** 0.10.7

* **OS and version:** Windows 10 Enterprise, version 1607

* **Browser:** all

**Comment by mathisscott** [comment]
@tishun 
I cannot see the screenshot. When I try to view it, I get an error message that says `Non-Image content-type returned`.

Are you talking about the focus state?

**Comment by brinton-chand** [comment]
Just my two cents, but possibly a duplicate of #1450?

**Comment by tishun** [comment]
My bad, here is another try
![New Screenshot](http://i66.tinypic.com/1ftfdh.jpg)

**Comment by tishun** [comment]
@brinton-chand yep, same issue, thanks for catching this!

@adityarb88 I realize this is used for keyboard navigation, however it still looks far than perfect.

The [Materialize CSS tabs](http://materializecss.com/tabs.html) are probably the best example I can give. They handle mouse clicks without leaving any residual focus state and in the same time pressing tab shows the selector in a very visible way, so both cases are handled.

The [Material UI tabs](http://www.material-ui.com/#/components/tabs), for instance, allow both keyboard and mouse selection, and still preserve the same UX after the tab is clicked and before that.

[Bootstrap UI ](https://getbootstrap.com/docs/3.3/javascript/#tabs) also handles both states in a better way. There are more examples in the web too.

What do you think?

**Comment by adityarb88** [comment]
@tishun: Thanks for the feedback. I can take our UX team on this and see what they say.
cc: @reddolan

**Comment by mathisscott** [comment]
@reddolan 
Thoughts?

**Comment by adityarb88** [comment]
@reddolan: Please take a look and provide feedback whenever you a get a chance. Thanks!

**Comment by mathisscott** [comment]
The Materialize tabs approach is not accessible in high contrast modes. We can't use that approach. Closing for now...
