### ISSUE TITLE
Dropdowns in datagrid action bar are misaligned

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#1546]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

A dropdown in the datagrid action bar should line up with other buttons.

### Actual behavior

The dropdown is pushed down 1px.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates: https://embed.plnkr.co/WpEcxC/

### Environment details

* **Angular version:** 4.4

* **Clarity version:** 0.10.6

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@gnomeontherun 
If you don't plan to work on this, can you supply a screenshot or plunkr?

**Comment by gnomeontherun** [comment]
Bah the plunkr didn't save. Fixing.

**Comment by mathisscott** [comment]
Looks like we can solve this misalignment by applying `margin-top: -1px` to the `clr-dropdown` element.

**Comment by mathisscott** [comment]
We need to make sure that we specify the direct child of button-group here so we don't mess up nested dropdown menus!

**Comment by Shijir** [comment]
It looks to me that there are at least three separate issues. https://plnkr.co/edit/0nxDWpCkyCtlm2zqWBj5?p=preview
