### ISSUE TITLE
Master detail grids

### ISSUE THREAD

**Issue by pantonis** [vmware/clarity#1547]
**Select one ...**  (check one with "x")
```
[ ] bug
[X ] feature request
[ ] enhancement
```

### Expected behavior
Is there any example of master detail datagrid. For example I have a number of clients and their orders. Can I show that using a master detail datagrid where the client will be the parent row and when it expands it will show orders datagrid and will have sorting, filtering and pagination?

I have seen the example on clarity's website with the Expandable rows but it is very simple and I dont know if the functionality described above is supported with this control

**Comment by mathisscott** [comment]
@youdz and @reddolan

**Comment by jacobbutton** [comment]
Are you asking if this is possible or are you asking for there to be a demo of it in the documentation?

You can add custom components as the detail row of your master grid.  I haven't done it, but I'd image you can add a child data-grid for orders inside that custom component.

https://vmware.github.io/clarity/documentation/datagrid/expandable-rows

<clr-dg-row *ngFor="let user of users">
    <-- Cells declarations -->
    <clr-dg-cell>...</clr-dg-cell>

    **<my-detail *clrIfExpanded [user]="user" ngProjectAs="clr-dg-row-detail"></my-detail>**
</clr-dg-row>

**Comment by pantonis** [comment]
Hi,

Thanks for your reply. I am asking both. :) 
It would be good to have an example since master/detail is mostly used  for this purpose.
Also since I have a lot of clients( about 1000) with their orders do you think this will affect performance if the data update every second?

Thanks

**Comment by jacobbutton** [comment]
Details Row supports Lazy Loading on expansion so if you take that path it shouldn't impact your performance.  How to achieve this is detailed at the bottom of the Expandable Rows documentation at the above link.

**Comment by mathisscott** [comment]
@pantonis 
Is @jacobbutton's sufficient for your use case? It appears to answer your concerns. Please reopen this issue if not.

Thanks, @jacobbutton !
