### ISSUE TITLE
Generating A Tree Dynamically

### ISSUE THREAD

**Issue by windischb** [vmware/clarity#1548]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
I need to implement a dynamically generated Tree View with different levels of depth.

### Actual behavior
With the example, its only possible to create Trees with one level of depth.
Or do i have a failure on my side??

### Reproduction of behavior
https://plnkr.co/edit/WyWCyCvZ5HsjG7RsEjfF?p=preview

**Comment by adityarb88** [comment]
@windischb: Please take a look at this Plnkr https://plnkr.co/edit/YFYa0f?p=preview to see how to generate a tree with unknown depth. Closing the issue based on this. Please feel free to reopen the issue if you have any more questions.
