### ISSUE TITLE
Wizard: should be able to hide close ("x") button

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#155]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

There should be a way to hide the close ("x") button on top-right of a wizard. This is especially an issue when there's an alert showed on top.

### Actual behavior

There is no way to hide the close ("x") button on top-right of a wizard

### Reproduction of behavior

Any Clarity wizard can reproduce this.

### Environment details

* **Angular version:** 2.1.1

* **Clarity version:** 0.6.0

* **OS and version:** OS X El Captain 10.11.6

* **Browser:** [ Electron ]

![image](https://cloud.githubusercontent.com/assets/8813134/20681726/ae4928e8-b559-11e6-91d4-8546db0c2175.png)

**Comment by jaffoneh** [comment]
@yaooluu do you want to hide/show only when the error is there or are you looking for a way to not include the "X" at all?

On another note, could you provide more details as to why you're showing the error on top of the title in the Wizard. What is the use case where you need a page-wide error vs. inline errors to where the issues are with the possibility of having an error icon on the name of the page in the left-side TOC?

**Comment by yaooluu** [comment]
Hi @jaffoneh, the use case here is that the error banner shows errors that are returned from backend after use submitted the form by clicking "Next" on wizard page. This is a convention we've followed in a product series.

I'm looking for a way not to include the "X" at all. Like the option we have for Modal `clrModalClosable`.

**Comment by jaffoneh** [comment]
cc @youdz to provide an opinion here.

**Comment by youdz** [comment]
@jaffoneh, @yaooluu: No, `[clrModalClosable]` will not work right now because the wizard currently _wraps_ the modal and doesn't offer a delegate for it. 

Yes, this is a valid request that we should address. It's as simple as offering a delegate `[clrWizardClosable]` on the wizard component that just passes it to the modal through `[clrModalClosable]`.

**Comment by jaffoneh** [comment]
Thanks, @youdz. @adityarb88 could you take a look and see what we can do there?

**Comment by adityarb88** [comment]
@jaffoneh: Sure. I will add this to my list
