### ISSUE TITLE
Add clarity-icons/clarity-icons-api.js to build output

### ISSUE THREAD

**Issue by goodmorninggoaway** [vmware/clarity#1553]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Include clarity-icons/clarity-icons-api.js in build output

### Actual behavior
clarity-icons/clarity-icons-api.js removed from build output in 0.10.8

### Reproduction of behavior
Not possible

### Environment details
Node 8.5
npm 5.4.2

**Comment by mathisscott** [comment]
Hi @goodmorninggoaway 

Thanks for pointing this out. We'll have someone look at this ASAP.

**Comment by goodmorninggoaway** [comment]
I'm preparing a PR

**Comment by jeeyun** [comment]
Hi @goodmorninggoaway thanks again for submitting the PR. Since we had a bigger fix we needed to do on our icons package, the fix that would've been in your PR was merged in with #1556. Closing this issue.
