### ISSUE TITLE
[NG] Wizard refactor

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#156]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
The Wizard component's API should match our other components. At the very least, it should follow our own [coding guidelines](https://github.com/vmware/clarity/blob/master/CODING_GUIDELINES.md).

### Actual behavior
Currently, the Wizard component's API is drastically different from anything else we offer, which means users have to learn new patterns just for it. In addition, these different patterns are often not used in the main Clarity components for good reasons, typically because they hinder customizability. We end up with many feature requests because people have no workaround available, there only hope is that we get to these features as soon as possible.

Most importantly, the current Wizard contains hard-coded English text, which completely breaks any attempt at i18n.

A couple examples of issues to fix (this list is _not_ exhaustive):
- [Wizard template](https://github.com/vmware/clarity/blob/master/src/clarity/wizard/wizard.html#L36): a full footer of buttons with hard-coded text
- [Wizard page template](https://github.com/vmware/clarity/blob/master/src/clarity/wizard/wizard-page.html#L9): Interpolating the title instead of projecting it.
- [Wizard page title detection](https://github.com/vmware/clarity/blob/master/src/clarity/wizard/wizard-page.ts#L66): Using the native element **and** testing its content on ngInit, which cannot handle anything dynamic.

### Environment details

* **Angular version:** all

* **Clarity version:** 0.7.x

* **OS and version:** all

* **Browser:** all

**Comment by yaooluu** [comment]
@youdz Hi Eudes, I noticed that when you have: 

`<clr-wizard-step>This is a title</clr-wizard-step>`

Both wizard TOC and page will have this same title. However, if I have: 

`<clr-wizard-step>{{ titleVar }}</clr-wizard-step>`

TOC shows the title correctly, but wizard page shows no title at all. 

I looked into the code of wizard and was trying to figure out the relationship between interpolation, projection, 1-way binding and 2 way binding. Can you confirm that my above code is the second issue you mentioned?

**Comment by youdz** [comment]
@yaooluu: Yes, your example is one of the many that have to be handled with projection. Right now the code for the wizard is playing with native HTML elements on component initialization, which cannot handle anything dynamic.

To be precise, though, I'd say your specific case not working comes from one of the other many places where wizard does this, not the one I pointed out. I think it's because of [that line](https://github.com/vmware/clarity/blob/master/src/clarity/wizard/wizard-step.ts#L54). But same idea as the one I posted.

**Comment by yaooluu** [comment]
Hi @jaffoneh  and @mathisscott, 

Do we have any updates & timeline on this wizard refactoring? Especially for the issues that @youdz had pointed out.

Also, besides localization of wizard template, we have scenarios where text on wizard buttons could be very long (in other languages like Deutsch). I see that Clarity already uses ellipses for long text. But what we had also been doing is adding the "title" attribute to show the full text. 

Besides, is there a design guide for the maximum width of the button?

<img width="694" alt="screen shot 2016-12-16 at 11 41 18 am" src="https://cloud.githubusercontent.com/assets/8813134/21276086/b4bdb372-c384-11e6-9ee4-935547b23d54.png">

**Comment by mathisscott** [comment]
@yaolu, 

Unfortunately, the wizard refactor got bumped by a couple of other priorities. It's still pretty high up on the list. But won't likely get worked on for another week or two.

**Comment by jeeyun** [comment]
We should also enhance our API to allow programmatically select a step. A use case was raised where an application persisted the state of a wizard in progress, and wanting to reload it when the user comes back to finish going through the wizard at a later time.

**Comment by reddolan** [comment]
@yaooluu the max width on a button (non-block) is 360px. 

Ideally a button should describe the action a user will be doing within a word or two. For example Save, Submit, Comment, etc. 

In the case of languages with long text, I would recommend that the product team do there best to keep the button label within these parameters to keep the button label from truncating to an ellipses. 

Also, while the Title attribute can be helpful, it shouldn't be relied upon solely. In the cases of touch screens (no-hover) or keyboard-only users, the Title attribute is useless. Even the [w3.org](https://www.w3.org/TR/html/dom.html#the-title-attribute) discourages it's use in this fashion.

**Comment by mathisscott** [comment]
This is just the issue that keeps on issuing.

Here is a list of other things to look at with the Wizard per meeting today with @jaffoneh, @youdz, and @yenmade 

- [ ] Wizard title should account for long title names. Either beyond two lines or truncation. Currently it is up to two lines but no truncation and no padding to right
- [ ] Styling of Wizard title + Step is different from designs (see Invision)
- [ ] Do we support xLarge size like modal?
- [ ] We should consider making no "close X" the default 
- [ ] Loading - do we build loading (spinner) in Clarity (how is the next step loaded)?

===

And one more from the Wizard doc we got from VMW teams...

- [ ] Page lifecycle events that can be subscribed to
