### ISSUE TITLE
is it possible to scale custom clarity icons?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [vmware/clarity#1560]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

Hallo,

is it possible to scale custom clarity icons?

```js
import {ClarityIcons} from 'clarity-icons';
export class AppComponent {
    constructor() {

         ClarityIcons.add({'my-logo': '<svg>blablabla</svg>'}); 

  }
}
```

if I add custom big svg icon I can not use 
```html
<clr-icon shape="my-logo"></clr-icon>
```
in this case I see nothing...

But If I change size manually:
```html
<clr-icon shape="my-logo" size="500"></clr-icon>
```

it is OK :)

example:
size:500

![bildschirmfoto 2017-10-08 um 18 16 43](https://user-images.githubusercontent.com/2271337/31318570-fb8af9b8-ac54-11e7-8b6c-fff5f2e407a5.png)

size: 25
 
![bildschirmfoto 2017-10-08 um 18 16 59](https://user-images.githubusercontent.com/2271337/31318572-02ca3176-ac55-11e7-9fd3-db5a58b6c02d.png)

**Comment by youdz** [comment]
You want to use `viewBox` and `preserveAspectRatio` on your SVG to control exactly how it scales with respect to the container. 
For instance, Clarity icons SVGs all have `viewBox="0 0 36 36"` and  `preserveAspectRatio="xMidYMid meet"`, but obviously the SVG itself has been written accordingly, taking into account the 36x36 view box.

**Comment by mathisscott** [comment]
@youdz answer is the correct one. Let us know if you need further explanation, @WuglyakBolgoink
