### ISSUE TITLE
Missing main.scss in clarity-ui after upgrading to 0.10.8

### ISSUE THREAD

**Issue by marcojahn** [vmware/clarity#1563]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
existing ```main.scss``` file in folder ```/node_modules/clarity-ui/src/``` after updating to be able to build a custom version of clarity during angular-cli build.

### Actual behavior
We are importing the main.scss file in our styles.scss to be able to theme/style clarity for our own needs.
After upgrading to 0.10.8 the required file main.scss is missing.

As a temporary workaround we have copied the file from https://github.com/vmware/clarity/blob/master/src/clarity-angular/main.scss and changed all paths to node_modules what did it for our needs.

We would appreciate if you can add the file again during the new/modified build process.

### Reproduction of behavior
Upgraded from 0.10.5 to 0.10.8

### Details of our current usage (snip)
```
/* our variables */
@import "variables";

/*
 * File is provided by clarity itself
 * https://github.com/vmware/clarity/blob/master/src/clarity-angular/utils/_overwrites.clarity.scss
 */
@import "clarity.overwrites";


/*
 * To be able to use the templating bootstrap must be installed directly
 *
 * > yarn add bootstrap@4.0.0-alpha.5
 *
 * if updating clarity, please check their bootstrap dependency and update if needed.
 */
@import "~clarity-ui/src/main";
```

### Environment details

* **Angular version:** 4.x.x
4.4.3

* **Clarity version:**
0.10.8

* **OS and version:** 
macOS Sierra

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by adityarb88** [comment]
@jeeyun: Could you please take a look at this?
