### ISSUE TITLE
Documentation Bug.

### ISSUE THREAD

**Issue by jlkoszarek** [vmware/clarity#1565]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
VerticalNav documentation is incorrect in the code example for collapse nav. P URL: https://vmware.github.io/clarity/documentation/vertical-nav/collapsible-nav/normal

currently is:
<clr-vertical-nav [clrVerticalNavCollapsible]="collapsible" [(clrVerticalNavCollapsed)]="collapsed">
should be:
<clr-vertical-nav [clrVerticalNavCollapsible]=true [(clrVerticalNavCollapsed)]="collapsed">

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x
latest

* **Clarity version:**
latest

* **OS and version:** 
windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome Version 61.0.3163.100

**Comment by adityarb88** [comment]
@jlkoszarek: Thanks for reporting this issue. We will get this fixed soon.

**Comment by Aeseir** [comment]
Just a addition to this,  **[(clrVerticalNavCollapsed)]="collapsed"** doesn't seem to do anything as per example (with @jlkoszarek fix that is).
However  **[clrVerticalNavCollapsed]="collapsed"** loads the vertical nav in collapsed state which i believe was the intention of demo (could be wrong, most likely am).

**Comment by yehia2amer** [comment]
@Aeseir yes it should be [clrVerticalNavCollapsed]="true" too
