### ISSUE TITLE
Question: are you using ng-packagr for building your angular lib?

### ISSUE THREAD

**Issue by dherges** [vmware/clarity#1568]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question out of curiosity
```

### Expected behavior

```json
  "build:angular": "ng-packagr -p ng-package.json",
```

in [package.json](https://github.com/vmware/clarity/blob/master/package.json#L16) on master branch

Are you using ng-packagr for building your angular lib?

### Actual behavior

Are you crazy? 🎃  😂  

### Reproduction of behavior

Yeah yeah, see above 🍤 

### Environment details

* **Clarity version:** master

**Comment by hippee-lee** [comment]
Hi @dherges - Thanks for creating  such a useful tool. Yes, it is being used to build Clarity. 
Are you seeing any issues with how its been used in the project?

**Comment by dherges** [comment]
No not all. It's good news! :basketball_woman: 

I'll have a lightning talk at [angular connect](https://www.angularconnect.com/). Introduction slide is going to be "Let's componentize our brand in Angular!" and from there the motivation to build a component library - may I use clarity as an example for that? Also the clarity logo and/or website on a slide?

**Comment by mathisscott** [comment]
@dherges 
That would be great, thanks! Let us know if you need a logo or anything.
