### ISSUE TITLE
Update Clarity UI Template

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1569]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Have a comprehensive set components and override states

### Updates
- [x] change template to a Library (Sketch 47 update)
- [x] Basic card with a horizontal separator after the title
- [x] Checkbox: disabled unchecked
- [x] Checkbox: disabled checked
- [x] Disabled input field
- [x] Radio buttons: Disabled selected
- [x] Disabled select box
- [x] Radio buttons: Disabled not selected
- [x] Vertical table
- [x] Tab overflow
- [x] Toggle: Disabled On
- [x] Toggle: Disabled Off
- [x] Vertical Nav with Dividers
- [x] Vertical Nav with Headers
- [x] Vertical Nav with Header Link
- [x] Vertical Nav with Header Link (Icon)
- [x] Collapsible Vertical nav
- [x] Collapsed Vertical nav – with icons
- [x] Progress bars: Green
- [x] Progress bars: Red
- [x] Refactor: Buttons
- [x] Button with icon only
- [x] Button with text + icon
- [x] Button group with icon only
- [x] Button group with icon + text
- [x] Button group with overflow “…”
- [x] Compact table
- [x] datagrid with checkboxes for multiple selection
- [x] datagrid with radio buttons for single selection
- [x] datagrid with single row actions
- [x] placeholder for an empty datagrid
- [x] Refactor: Wizard step overrides
~~Refactor: Tree View overrides~~
~~Refactor: Stack View overrides~~
~~datagrid compact~~

### Environment details

* **UI Template version:** 0.10.0

**Comment by mathisscott** [comment]
@reddolan : Is this done?

**Comment by reddolan** [comment]
Sketch Library updates are complete and ready for the update in #1570 
[Clarity-UI-Library-0.10.11.sketch.zip](https://github.com/vmware/clarity/files/1419344/Clarity-UI-Library-0.10.11.sketch.zip)
