### ISSUE TITLE
Update Design Resources

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1570]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Have a new Library version of the Clarity UI Template as well a content that shows the Clarity Sketch Library is available to download.

Will also want to keep the previous version of the UI Template (0.10.0) available for users who have not moved to Sketch 47 yet.

### Actual behavior
Current 0.10.0 version is using Sketch 46 and doesn't have the Libraries ability

### Reproduction of behavior
![image](https://user-images.githubusercontent.com/1858226/31414471-e82a4a70-add2-11e7-9ad4-e549b7328cd0.png)

### Environment details

* **UI Template version:** 0.10.0

* **Clarity version:** 0.10.8

* **OS and version:** 

* **Browser:** [all]

**Comment by reddolan** [comment]
@hippee-lee we will want to add something to the release notes about deprecating the Craft Library and that we want folks to move over to Sketch Library

**Comment by hippee-lee** [comment]
@reddolan how about something like this ...

> We have moved the Clarity Design Resources to use the newly released Sketch Library (links to 
Sketch docs and Clarity files). The Craft Library is now deprecated and will be removed when Clarity v0.11.0 is released. 

My thought is to include it in next weeks release (or I can update yesterday's) and include the message inside an `alert-warning` as part of the `Other Changes` section. 

Sound good to you?

**Comment by mathisscott** [comment]
@reddolan 
Any update on this?

**Comment by reddolan** [comment]
Clarity UI Library - 0.10.11
[Uploading Clarity-UI-Library-0.10.11.sketch.zip…]()

Clarity Icons Library - 0.10.11
[Clarity-Icons-Library-0.10.11.sketch.zip](https://github.com/vmware/clarity/files/1420056/Clarity-Icons-Library-0.10.11.sketch.zip)

**Comment by reddolan** [comment]
![artboard](https://user-images.githubusercontent.com/1858226/32080656-cbd123fe-ba65-11e7-9942-0de8942cf158.png)
