### ISSUE TITLE
Firefox stalls/unresponsive while server driven clr-datagrid is loading

### ISSUE THREAD

**Issue by ajinkyac** [vmware/clarity#1572]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The browser should not stall or become unresponsive when clr-datagrid is being loaded for the first time.

### Actual behavior
For the server-driven grid, while loading of the data the grid makes the browser unresponsive or stalls clicking to other elements on the page.

### Reproduction of behavior
Use the clr-datagrid, plug it with a server data fetch method. Once the fetched data is made available to the grid and the loading indicator is spinning the browser stalls and it worst cases crash the browser. After some initial debugging on the browser level, we found that the element paint/repaint operation exceeds the browser buffer.

### Clarity Plunker Templates
https://embed.plnkr.co/6CQmxX/

### Environment details

* **Angular version:** 4.1.3

* **Clarity version:** 0.10.2

* **OS and version:** macOS Sierra

* **Browser:** Firefox 56.0 (64-bit)

**Comment by mathisscott** [comment]
@youdz 
When you get back, this is something we want to look at.
