### ISSUE TITLE
Vertical Nav Icons are not blue on active

### ISSUE THREAD

**Issue by lthoang101** [vmware/clarity#1579]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
In the demo for the Vertical Nav with icons, the icon for the active link has a blue fill color on active and on hover. (see https://vmware.github.io/clarity/documentation/vertical-nav/icon-links/normal)

### Actual behavior
However, on our page, it appears that the blue fill color is only enabled on hover and not on active/selected. 

I was expecting that the blue fill color would be enabled on both the active and hover. 

### Reproduction of behavior
This behavior is also seen in an existing plunker found in issue 1539 (https://github.com/vmware/clarity/issues/1539).

https://plnkr.co/edit/qBTft97DXV8G8bYYBWww?p=preview

### Environment details

* **Angular version:** 4.x.x
4.3.6

* **Clarity version:**
v0.10.5 and v0.10.8

* **OS and version:** 
Mac 10.11.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 61

**Comment by adityarb88** [comment]
@lthoang101: In the plnkr you have provided, I do not see the router links configured. Without that `routerLinkActive` will not work. Could you please provide an updated plnkr with the router links so we can reproduce the issue.

**Comment by adityarb88** [comment]
@lthoang101: Are you still facing this issue with the routes configured?

**Comment by adityarb88** [comment]
@lthoang101: We haven't heard back from you regarding this issue. We are closing the issue assuming that you managed to resolve it at your end. Please feel free to reopen the issue with the routes configured if you continue facing this and we will take a look. Thanks!
