### ISSUE TITLE
Datagrid Enhancement: Freeze/Pin First Column

### ISSUE THREAD

**Issue by vijay-venkatraman-vmware** [vmware/clarity#1586]
### Description

The most common use case is for freezing/pinning the first column in the datagrid. The first column is usually the primary identifier. With that frozen/pinned, you can horizontally scroll the datagrid without losing context.

### Documentation

You can freeze/pin the first column by clicking on the freeze/pin icon in the column header. Click again to toggle back to the initial unfrozen/unpinned state.

In the example below, the filter icon is shown on all columns, which might not always be the case. In the absence of the filter icon for a column, the icon for freeze/pin column will move to the right and take the position currently occupied by the filter icon.

![frozen_first_column_for_github](https://user-images.githubusercontent.com/31904821/31508388-b9fed74a-af32-11e7-9fac-e45dd852a35d.gif)

**Comment by vijay-venkatraman-vmware** [comment]
Original request - #619

**Comment by dexfab** [comment]
Any idea as to when this might be added. It would be great to be able to pin the first column when using a grid on mobile (https://www.nngroup.com/articles/mobile-tables/).

**Comment by hippee-lee** [comment]
The initial DOM structure was put in place during a large refactored last year. I’m working on smart popovers now so that popovers can avoid the clipping issues that stem from the current popover implementation. Once I have the SmartPopover utility in place I think the current plan is for me to switch back to pinned columns. 

There is no way I can give an exact date or a version. That said I would like to get it into v2 (assuming it isn’t a breaking change) or v3. Following the smart popovers and this issue for updates and progress is your best bet. 

Fwiw (my .02¢) - Clarity does not recommend use of datagrid on a small screen. It’s really difficult to create a good user experience (I’m thinking about every excruciatingly painful time I tried to use google spreadsheets on my phone).

**Comment by dexfab** [comment]
Thanks for the quick reply. I agree about not using datagrid on mobile, in general we try to avoid this but for some use cases we have found no alternatives and having the ability to pin the first column would alleviate this. Thanks again.

**Comment by mattmutt** [comment]
Is pinning rows, or at least having the facility in the API to correctly support placing rows under the main body of grid rows planned to be designed? The use case for showing one line summaries is needed in some financial views.

Attaching a demo link here to help visualize how that would work with a Clarity grid. Of course there are likely other edge cases and usability concerns, but the main motivation was to have a partitioned row somewhere in the footer region. 

Find the datagrid card here and try resizing, scrolling, paginating for example.
http://mattmutt.github.io/ngx-card-deck-seed/#/dashboard/dashboard-page/com_company_sample2/deck1

**Comment by gnomeontherun** [comment]
@mattmutt This seems to be outside of scope for this particular request, and would be best to setup a new ticket for it. At first glance, I don't see how this is pinning a row as it is just adding more content into the footer, could that help?

**Comment by mattmutt** [comment]
Developers should not be exposed to the complexities of the grid layout when trying to place data that aligns to the columns. I'm demonstrating a viable pattern for others who desire such a use case - a special row with aligned data inside the footer. Where does Clarity showcase this example?

**Comment by gnomeontherun** [comment]
@mattmutt We do not have an example or support for this, but it is still a separate request and do you mind making a different feature request with use cases?

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
