### ISSUE TITLE
Datagrid ExpressionChangedAfterItHasBeenCheckedError after re-assigning the selection

### ISSUE THREAD

**Issue by colossal-squid** [vmware/clarity#1589]
We're trying to implement a directive, that stores user selection in-between live data refreshes. Wrapping the assignment in 'preselect-comparator.ts' line 57 into a setTimeout works, but i'd like to avoid using setTimeout.

The plunkr is just a partial implementation for a singular selection (i've removed multi-select branches to make it shorter)
```
[x] bug
[ ] feature request
[ ] enhancement
```
https://plnkr.co/edit/WUNt57MsppVCqK18VtH1
Select a row in the grid (any row)
Click REFRESH DATA BUTTON
### Expected behavior
Data is reset, shuffled, selection is preserved by our custom preselect-comparator directive
### Actual behavior
ExpressionChangedAfterItHasBeenCheckedError is thrown

### Reproduction of behavior
https://plnkr.co/edit/WUNt57MsppVCqK18VtH1
### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** latest (as in plunkr)

* **OS and version:** latest osx

* **Browser:** all

**Comment by adityarb88** [comment]
@colossal-squid: It looks to me that you are updating the array twice. First setting it to empty and then shuffling and resetting it. If I remove the first assignment where you set it to empty, everything works fine and we get the same result. Please see: https://plnkr.co/edit/QyzLJiE5h2PjFRg974pg?p=preview

Does this help?

**Comment by colossal-squid** [comment]
Yes, this definitely "fixes" it in a plunkr, but even if i remove similar "reset" assignments before http service calls, I'd like to prevent such exceptions occurring in real life environment.

Can anyone explain me if this is a bug, or us using it wrong? And if second - what happens under the hood and why is this illegal?

**Comment by adityarb88** [comment]
I believe that you just have to make sure that the bindings are not updated after the view has been updated. If they are you need to manually run change detection again. If you can find this pattern in your use case right now (you could check this by logging into the different lifecycle hooks), then an `ExpressionChangedAfterItHasBeenCheckedError` error will be thrown. More info can be found here:

https://angular.io/guide/lifecycle-hooks
https://medium.com/@golbie/angular-2-change-detection-what-the-hell-is-has-changed-after-it-was-checked-82007cdfa38a
https://stackoverflow.com/questions/43375532/expressionchangedafterithasbeencheckederror-explained
https://stackoverflow.com/a/34957665/3538394

Let us know if this helps?

**Comment by colossal-squid** [comment]
There is another one with multiselect, I think I should create a separate ticket for this. Thanks
