### ISSUE TITLE
Dark theme specs for scrollbar?

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#1591]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```
We rely on the native browser's rendering of scrollbars for light (current) theme of Clarity. It would be nice to provide specs and css for the scrollbars in dark theme.

Some screenshots for visuals:

Dark theme with native scrollbars:
<img width="501" alt="screenshot 2017-09-28 17 21 04" src="https://user-images.githubusercontent.com/1827742/31567605-3fcaa438-b025-11e7-9b22-3257188c4a11.png">

Dark theme with custom color:
<img width="488" alt="screen shot 2017-10-02 at 4 10 17 pm" src="https://user-images.githubusercontent.com/1827742/31567615-48be8e56-b025-11e7-9273-9630578f1785.png">

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adumesny** [comment]
Yes it would be good to have a spec and some CSS styling to support those browsers that DO let you color/size the scrollbars as most people will need this, and rolling your own JS based scrollbars is problematic.

So far I have webkit based browsers and IE support. Will update as I go.

**Comment by hippee-lee** [comment]
FF does not support scrollbar styles with css. We do not have plans for a Scrollbar component in JavaScript - there are issues with using the scroll event to update _things_. 

https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

**Comment by gnomeontherun** [comment]
The technical implementation of custom scrollbars or implementing scrollbar styling is not possible with cross browser support.
