### ISSUE TITLE
Modal footer issue.

### ISSUE THREAD

**Issue by GnanendraPaladugu** [vmware/clarity#1594]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Modal footer buttons background is hiding when we reduce vertical height. 

### Actual behavior
Adjust the modal footer height automatically. 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Hi @GnanendraPaladugu 
Thanks for reaching out!

Could you provide a [plunkr demonstrating the issue](plnkr.co/uNwwZe)? It will help us to triage it and figure out what's happening.

Thanks!

**Comment by GnanendraPaladugu** [comment]
Hi,
We have found the solution above issue. we had given inside container height is 100% it is causing issue. Please close the issue.
Thanks.
