### ISSUE TITLE
Problem displaying the content in <clr-modal> with <ng-content>

### ISSUE THREAD

**Issue by ninodinatale** [vmware/clarity#1595]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Problem
I wanted to wrap my own component around <clr-modal>. My problem is, if I want to display the content of my component inside the <clr-modal> with transclution (so <ng-content>) the content won't show. I can't see anything in the DOM besides the modal itself and the header. May someone tell what I am doing wrong? I actually don't know if it's clarity specific or general Angular, so please, if it has nothing to do with the clarity framework, just close the issue and I can get help from somewhere else.

### Plunker
Please see the plunker, I hope you get the point. I made a modal which is working (without ng-content) and one with, which is not working: https://plnkr.co/edit/DNFl8RbLa8E7ayTFt0z8

### Environment details
* **Angular version:** 4.4.4

* **Clarity version:**
latest

**Comment by youdz** [comment]
This is an Angular behavior we can't do much about. Re-projecting projected content loses the selectors of the projected content, it puts it in a "black box".

You can fix this very easily by using `ngProjectAs=".modal-body"` (or whatever the selector of what you're trying to re-project is). I just did it on your plunker, and its works again: https://plnkr.co/edit/3jcgOUqgFSPYuuMbzeHG?p=preview
