### ISSUE TITLE
Vertical Nav collapse function should be at bottom, not top

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#1604]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
When implementing a vertical nav component for my applications navigation, the ability to navigate is the primary concern, so the navigational items should be presented primarily and other features of the nav control should be secondary

### Actual behavior
When implementing a vertical nav component, the ability to expand/collapse is shown at the top and displaces my navigational items from prominence.  

Look at Atlassian JIRA's use of a similar navigational component that places collapsing at the bottom of the tool so it doesn't detract from the primary navigation items.

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.5

**Comment by dsaojose** [comment]
I agree with this design decision.  The expanding and collapsing should be at the bottom, not the top.

**Comment by adityarb88** [comment]
@joshjohnson72: This looks like a duplicate for this: https://github.com/vmware/clarity/issues/1328

Please subscribe to #1328 for more updates. Thanks!
