### ISSUE TITLE
Creating DataGrid Columns Dynamically?

### ISSUE THREAD

**Issue by luis-cortina** [vmware/clarity#1610]
Hi:

Is it possible to create the data grid columns dinamically? Somthing like this maybe?

```
<clr-datagrid>
    <clr-dg-column *ngFor="let colName of columnNames">
          colName.name
     </clr-dg-column>

    <clr-dg-row *ngFor="let user of users">
        <clr-dg-cell>{{user.id}}</clr-dg-cell>
        <clr-dg-cell>{{user.name}}</clr-dg-cell>
        <clr-dg-cell>{{user.creation | date}}</clr-dg-cell>
        <clr-dg-cell>{{user.color}}</clr-dg-cell>
    </clr-dg-row>

    <clr-dg-footer>{{users.length}} users</clr-dg-footer>
</clr-datagrid>
```

**Comment by adityarb88** [comment]
@luis-cortina: This looks like a question for StackOverflow. I would recommend, asking a question there with the `vmware-clarity` tag. More info here: 

https://vmware.github.io/clarity/get-started#stackoverflow
https://stackoverflow.com/tags/vmware-clarity

Closing based on this. Thanks!
