### ISSUE TITLE
Wizard opens with all 4 clr-wizard-buttons

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#1615]
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
wizard button to behave in the examples

### Actual behavior
All 4 wizard buttons are displayed (cancel, back, next, finish)

### Reproduction of behavior
start new angular cli project (1.4.8)
add latest clarity and a basic wizard example.

https://github.com/aavelyn/clarity-wizard-btn/tree/master/testclarity

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/hP7pvbVFZPA8QLhLT0qi

### Environment details

* **Angular version:** 4.4.6

* **Clarity version:** 0.10.9

* **OS and version:** macOS Sierra

* **Browser:** Chrome

**Comment by hippee-lee** [comment]
Hi @aavelyn - I'm not seeing any wizard code in your plunker. Are you shire its the correct one?

**Comment by aavelyn** [comment]
just updated the plunker

**Comment by sascha-friederich** [comment]
i have the same behaviour, in 0.10.7 wizard works fine, error starts with version 0.10.8

**Comment by adityarb88** [comment]
@gnomeontherun: Could you please check if this issue is related to: https://github.com/vmware/clarity/commit/4610fd46e3dfcc9c4e4766b42da3a399c1216c31

**Comment by gnomeontherun** [comment]
It works fine if you use `<button (click)="wizard.open()" >Open</button>` with a template variable set on the wizard itself `<clr-wizard #wizard [(clrWizardOpen)]="open">`. This can give you a workaround for now until I land a fix. https://plnkr.co/edit/qirZbs23IAYJnAkLaScr?p=preview

I can confirm that the two-way binding of the `open` property is rendering all buttons, have a fix coming.
