### ISSUE TITLE
Getting linebreaks in tooltip-content

### ISSUE THREAD

**Issue by aaronfrost** [vmware/clarity#1616]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior

I would love to see a way to add a linebreak into my tooltip, so that I could have a slight ability to break things up. Like a list of things in a tooltip can make sense. If there is a way to do this currently, I couldn't see it in the docs. Would love to see that this already exists. 

### Actual behavior

In a tooltip, all we have is word wrapping. So we can't break things up into a list on different lines or so. 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
To see, go here
https://plnkr.co/edit/iM1QXO?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.8

* **OS and version:** OSX 10.12.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@aaronfrost: Tooltips are just for a line of text. See our docs:
![image](https://user-images.githubusercontent.com/1426805/31796495-c4a5740e-b4f7-11e7-9e5b-2d122f9f02d2.png)
https://vmware.github.io/clarity/documentation/tooltips

You should use Signposts if you want to accommodate content that spans across multiple lines:
https://vmware.github.io/clarity/documentation/signposts

Irrespective of what you use, Clarity uses a declarative API. So you should be able to use a list or multiple paragraphs to break content in the popover that you choose to use.

**Comment by adityarb88** [comment]
@aaronfrost: Plnkr for more info: https://plnkr.co/edit/Wi412HnCBkPsXgmZbBGQ?p=preview

**Comment by adityarb88** [comment]
@aaronfrost: Apologies. I missed the comment about the docs. Thanks for the feedback! I will raise a separate ticket to tag our UX team to see how our docs can be improved for tooltips and signposts.

**Comment by aaronfrost** [comment]
I figured it out. I can break on linebreaks by doing the following in my template:

```
<clr-tooltip-content>
    <ul>
        <li *ngFor="let piece of tooltip.split('\n')">{{piece}}</li>
    </ul>
</clr-tooltip-content>
```

Again, thanks for the response on this. Made me think a bit, and I got to what I wanted. Here is a plunker. https://plnkr.co/edit/QshPkH?p=preview
