### ISSUE TITLE
If clr-tooltip-content is nested inside of ng-container, there is an error

### ISSUE THREAD

**Issue by aaronfrost** [vmware/clarity#1618]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

when I wrap `ng-container` around `clr-tooltip-content` _(cause sometimes I optionally want to have the tooltip and othertimes not, so I use the `ng-container` to ngIf if I want to show it or not)_ it shouldn't throw an error. It should be fine, and not care if I wrapped it with a span or an ng-container. 

### Actual behavior

when I wrap `ng-container` around `clr-tooltip-content` _(cause sometimes I optionally want to have the tooltip and othertimes not, so I use the `ng-container` to ngIf if I want to show it or not)_ then the UI breaks when the tooltip is displayed. If I use any other wrapper besides ng-container, it works fine. It is just the ng-container that dies. This isn't a major bug, but cost me a bit of time trying to figure out. My current workaround is to use a div instead of ng-container. 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://plnkr.co/edit/oOKYBeZXoLB5ptWS3l6j?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.8

* **OS and version:** OSX 10.12.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
Thanks again @aaronfrost. Will take a look and get back to you.

**Comment by youdz** [comment]
Yes, we are just grabbing the parent host `ElementRef` and using it to position the tooltip, but adding an extra `ng-container` around the content means we get an undefined element. So we just need to get the `Tooltip` itself instead of the parent host, and use this to position.

Thanks for filing this. 👍
