### ISSUE TITLE
A modal window takes place when it is in a hidden state

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#1622]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
A modal window does not create extra padding when it is in a hidden state.

### Actual behavior
A modal window takes place when it is in a hidden state.

### Reproduction of behavior
https://embed.plnkr.co/UC5LA68PKfVMjoUwtqss/

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** latest

* **OS and version:** Windows 10

* **Browser:** Chrome 61.0.3163.100

**Comment by adityarb88** [comment]
@belyan: Not sure if I understand the question correctly.

![image](https://user-images.githubusercontent.com/1426805/31827455-cb9cfbf4-b585-11e7-98ba-ed710bb0d6f0.png)

Clarity buttons have margin around them. Are you talking about that? I don't believe modal takes any space because it is `position: fixed`

**Comment by belyan** [comment]
@adityarb88 I cleared margins for paragraphs in CSS. Cause is in the custom element `clr-modal`. It has the style `display: inline-block` by default, therefore it creates extra padding between paragraphs.

**Comment by adityarb88** [comment]
@belyan: I am still not sure what the issue is. Are you looking for this? If yes, you need to clear the margin for the button.

![image](https://user-images.githubusercontent.com/1426805/31830479-509aff4c-b58e-11e7-9db8-e51180bd3a07.png)


https://plnkr.co/edit/GxHX55zxg4TsUS7NTL5C?p=preview

**Comment by belyan** [comment]
@adityarb88 Could you please add the CSS rule `clr-modal { display: block; }`, and you will see difference.

**Comment by adityarb88** [comment]
@belyan: I understand your question now. I will take a look and get back to you.

**Comment by belyan** [comment]
@adityarb88 Thanks.

**Comment by mathisscott** [comment]
`clr-modal` needs a `display: none` on the host when it is not open. This should fix this extra space that is added.

**Comment by govi2010** [comment]
Hello Team , I am working on this right now Will send PR soon @mathisscott .

**Comment by adityarb88** [comment]
Thanks @govi2010

**Comment by govi2010** [comment]
hello @mathisscott , I have made changes which are require. now i am doing `npm build`, then `npm start`. I noticed that my changes are not being applied. Sorry to ask but I am new to this project. am i doing something wrong?

**Comment by govi2010** [comment]
@adityarb88  Sending PR.

**Comment by govi2010** [comment]
#1647 here is FIX @adityarb88  and @mathisscott . Let me know if you need any help
