### ISSUE TITLE
Tab overflow drop-down creates a horizontal scroll

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#1623]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Tab overflow drop-down does not create a horizontal scroll.

### Actual behavior
Tab overflow drop-down creates a horizontal scroll when it is in a hidden state and has not been initialized.

### Reproduction of behavior
https://embed.plnkr.co/3rEVkZRBDvtyYmjuUrf2/

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** Latest

* **OS and version:** Windows 10

* **Browser:** Chrome 61.0.3163.100

**Comment by adityarb88** [comment]
@belyan: Will take a look and get back to you.

**Comment by coldhamix** [comment]
It looks to me to be the same bug as #1630

**Comment by belyan** [comment]
@coldhamix I agree with you.

**Comment by adityarb88** [comment]
Closing this as a duplicate of #1474. Please subscribe to that issue for more updates.

**Comment by adityarb88** [comment]
duplicate of #1232. Please subscribe to #1232 for more updates.
