### ISSUE TITLE
In the Datagrid component, fire a clrDgColumnSizeChange event whenever a column width changes

### ISSUE THREAD

**Issue by clementcur** [vmware/clarity#1625]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
In the Datagrid component, whenever a column width changes by any mean (sibling columns getting resized, window getting resize, etc.), a `clrDgColumnSizeChange` event would be bubbled up. That applies to any column in the datagrid.

### Actual behavior
As of today, a `clrDgColumnResize` event is only bubbled up when a particular column has been resized using the dragging tool. Also, note that the last column is excluded and never fires that event.

### Reproduction of behavior
https://plnkr.co/edit/1Xv23N?p=preview

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.5

* **OS and version:** MacOS 10.12

* **Browser:** all

**Comment by clementcur** [comment]
In the meantime, I got unblocked by following @Shijir advice, which is to listen to the `clrDgColumnResize` event on each column, and using a template reference on a specific column, I can detect if its size changed.

I'll let you guys decide if this enhancement still makes sense since @youdz mentioned that in a near future, the Datagrid component might move to a flexbox style instead of hard widths.

**Comment by jeeyun** [comment]
@clementcur since you are unblocked and we aren't actively working on implementing it, will close this for now. If the need for it arises as you revisit it in the future, please feel free to re-open it.
