### ISSUE TITLE
Clarity-icon JS file npm distribrution is widely blocked due to adblocker regex

### ISSUE THREAD

**Issue by jonathantrevor** [vmware/clarity#1627]
Related to https://github.com/vmware/clarity/issues/850 which was closed without any changes.

While clarity-ui itself does not ship a .js file the clarity icon package does (several minified js files depending on what icons are needed). Anyone using these files as part of the distribution (or copying to their own CDNs) will be unable to see clarity-icons because the clarity name is blacklisted on a popular ad blocking regex. 

Perhaps renaming the js files inside of the clarity-icons package to something like clr-icon would be a solution. Otherwise anyone using the package may not catch the problem in testing (depends on what ad-blocker is installed, if any).

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Using a minified JS file shipped as an npm package should work in a majority of browsers with typical user installed extensions / addons

### Actual behavior

Clarity icons do not show up

### Reproduction of behavior

uBlock uses the easy list regex and stops clarity icons with the default name

### Environment details

* **Angular version:** n/a

* **Clarity version:** clarity-icons 0.10.x

* **OS and version:** 

* **Browser:** [all]

**Comment by mathisscott** [comment]
Hi @jonathantrevor 
#850 has been reopened and I've already been in contact with individuals on the ad blocker end of things. 

Long story short, they aren't going to do anything. But I've identified a path forward and we will be executing on that in the next week or two. 

I'm closing this as a duplicate. Please subscribe to #850 for future updates. 

Thanks for raising awareness that your team was hitting this issue again.
