### ISSUE TITLE
List of cards does not show all cards -- seemingly unrelated html changes bring them back

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#1628]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

See the plunkr. There should be 100 cards showing as you scroll down the page. Above the cards is an input box with a filter icon. Below the cards is the text "Bottom".

### Actual behavior

See the plunkr. Only some portion of the cards show up. Hover the mouse on any card, and the missing ones show up. Hover in the blank space where the cards should be, and once you're over a card, it and the ones below show up.

More weirdnesses:
- invisible cards are still taking up space (notice "Bottom" marker at bottom)
- remove the style="opacity:0.5" and the all the cards show
- add a standalone card at the top (above the filter input, leave opacity), and all the cards show

I only see this on Chrome. With FF and Safari, the icon doesn't even show up, and all the cards are visible.

### Reproduction of behavior
https://plnkr.co/edit/0z6b9dGCBhTjNQukMJli

When run, there should be 100 cards shown, but only first 39 are shown. The 39th one is partially cut off.

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**
latest
* **OS and version:** 
OSX

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Seen on Chrome. Not reproducible in FF or Safari, but icon is missing on both of those, so thigns are different.

**Comment by adityarb88** [comment]
Interesting. Haven't been able to figure out why this is happening. Will take a look again and get back to you.

**Comment by adityarb88** [comment]
@rongery: I can't seem to replicate this now. @hippee-lee can you replicate this now?

**Comment by adityarb88** [comment]
@rongery: Wanted to check back and see if you are still facing this issue?

**Comment by rongery** [comment]
@adityarb88 Yes, I still see this using the plunkr above. I'm using Chrome 61.0.3163.100. Attached screenshot shows clipped cards starting with part of number 40:

<img width="557" alt="screen shot 2017-11-08 at 9 21 33 am" src="https://user-images.githubusercontent.com/11431579/32563583-7eded644-c466-11e7-8523-6bd6712bf47a.png">

**Comment by adityarb88** [comment]
@rongery: The icons dont show up in FF and Safari because custom elements is not loaded in the Plnkr template. Try this one: https://plnkr.co/edit/4uwYofalimXunWegwn1W?p=preview

I use Chrome 62. May be this is an issue with Chrome? Could you try using the Plnkr that i supplied above and see if you can replicate the same issue?

**Comment by rongery** [comment]
I can still reproduce with your plunkr above with Chrome. I upgrade to 62.0.3202.89 and still see the same behavior. Seeing correct behavior, with icon, in FF using your plunkr. This is looking like an issue with Chrome, but I don't understand why you are not seeing it in your Chrome.

**Comment by adityarb88** [comment]
@rongery: I could reproduce it but only once. Same thing happened when @hippee-lee tried to reproduce this. Not sure whats wrong. Looks like an issue with Chrome?

**Comment by rongery** [comment]
Yes I suspect this is Chrome. I will leave it to you to close out the ticket.
