### ISSUE TITLE
🤦🏻‍♂️ Question: Documentation

### ISSUE THREAD

**Issue by WuglyakBolgoink** [vmware/clarity#1629]
Hallo guys,

I have a small question about updates in docu. :)

![image](https://user-images.githubusercontent.com/2271337/31853480-67062aa8-b689-11e7-9a69-892efa8cf627.png)

How can we see, what was changed? Are we have something like git repo?

**Comment by hippee-lee** [comment]
Hey there, @WuglyakBolgoink 

For the latest news you can go to https://vmware.github.io/clarity/news.
That said, I did the release this week and forgot to update the sidenav notes for v0.10.10.
I'll update it so that it reflects the latest changes that were released last week.

**Comment by WuglyakBolgoink** [comment]
Hallo @hippee-lee  thank you!
