### ISSUE TITLE
header display problem when there's a long navigation bar

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#1643]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Show the header properly.
If the navigation bar too long, it would be appreciated if a dropdown is added to the right of the header to show the overflowed navigation links.

### Actual behavior

When the long navigation bar causes the header to be wider than the window, there are problems in showing the header.
For chrome, there a right blank space, and the right blank space is as wide as the horizontal scroll bar.
For firefox, the header is truncated if it's overflowed beyond the window width.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/Bsqw4z8EBpGF2pIFGZHA?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** latest

* **OS and version:** mac osx

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 61
![image](https://user-images.githubusercontent.com/3956876/31977788-106f1240-b904-11e7-94c3-cfbfda992528.png)

Firefox 56
![image](https://user-images.githubusercontent.com/3956876/31977830-45d6c19e-b904-11e7-8247-5968f3e33f88.png)

**Comment by KingMario** [comment]
PS: for Firefox, if the following css is added, the behavior is the same as for Chrome.
```css
body {
  min-width: 1280px;
}
```

**Comment by adityarb88** [comment]
@KingMario: Thanks for filing this issue. Our design recommendations say this:

![image](https://user-images.githubusercontent.com/1426805/32001050-99ed55e2-b966-11e7-9146-0eb93164e51c.png)

You can find our design recommendations for navigation here:
https://vmware.github.io/clarity/documentation/navigation

If you have more than 4 links on the header, then its better to use the secondary navigation. More info here:
https://vmware.github.io/clarity/documentation/header

Your header in that case should look something like this:
![image](https://user-images.githubusercontent.com/1426805/32001095-b71f672c-b966-11e7-9581-c7a867ff4fa4.png)

Closing the issue based on this. Please feel free to reopen the issue if you have more questions.
