### ISSUE TITLE
The latest npm packages of clarity don't contain typescript files of the components  

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#1649]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The clarity npm packages to have "src" folder with the component typescript files which to be consumed from webpack builds.
### Actual behavior
The clarity npm packages after version 0.10.7 don't have “src” folder with typescript files of the components.
The result is that the build of our project which uses webpack and uses clarity is failing.
![claity-angular packages](https://user-images.githubusercontent.com/439779/32090577-be8e9c60-baf8-11e7-9dc3-3820ac4f928d.png)

### Reproduction of behavior
Download the newest clarity package.

### Environment details

* **Angular version:** 4.x.x

* **Clarity version: 0.6.9**

* **OS and version:Windows 10** 

* **Browser:** all

**Comment by youdz** [comment]
We are just following Angular's recommendation when it comes to publishing libraries. 
For instance, if you look at Angular itself, they are not publishing the typescript files either, just the `.d.ts` and a single (or almost single) JS file in ES5. We are doing exactly the same. 

If your project is using webpack and can build with Angular, then it can build with Clarity. You shouldn't compile from our sources, you risk running into problems if your Typescript version isn't the same as ours.
