### ISSUE TITLE
Update docs re: datagrid selection (header checkbox only selects rows on current page)

### ISSUE THREAD

**Issue by pakopa** [vmware/clarity#1650]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[ X ] question
```

### Expected behavior
Header checkbox selects all rows in the datagrid record set

### Actual behavior
Header checkbox selects only the rows on the current page.

Is this the intended behavior? Maybe there could be an option to perform the selection of all rows.

### Reproduction of behavior
Check the header checkbox in the header of a datagrid with several pages and switch pages. Other pages rows are not selected.
### Environment details

* **Angular version:** 4.4.3

* **Clarity version:** 10.7

* **OS and version:** Windows 10

* **Browser:** Chrome 61

**Comment by adityarb88** [comment]
cc: @reddolan

**Comment by mathisscott** [comment]
This is the expected behavior. Do we have documentation we need to update on this @reddolan ?

**Comment by mathisscott** [comment]
@reddolan 
Docs?

**Comment by reddolan** [comment]
@mathisscott yeah, we should update the docs to reflect this. I don't think we have anything written up yet

**Comment by gnomeontherun** [comment]
Adding to the website and closing as resolved.
