### ISSUE TITLE
Sorting / order icon

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#1651]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
An icon that can be used on buttons that provide sorting functionality for lists, tables, etc. This could look for example like the icon used by Youtube:

<img width="93" alt="screen shot 2017-10-27 at 15 41 16" src="https://user-images.githubusercontent.com/3655915/32106968-83aeb56e-bb2d-11e7-8362-eff2c8fed57d.png">

### Actual behavior
There is no sorting icon.

### Environment details

* **Clarity version:**
0.10.11

**Comment by adityarb88** [comment]
@lil-kim, @mathisscott

**Comment by mathisscott** [comment]
I added this to the Vol. 9 Icon epic -- #1518 . @lil-kim , could you review this request and make a determination on its inclusion when you circle back around to icons? Thanks.

**Comment by lil-kim** [comment]
Completed as part of Epic #1518
