### ISSUE TITLE
Update Vertical Nav examples to have correct background color

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1653]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Vertical Navigation examples should have a #fafafa background color on the content area

### Actual behavior
background color is #ffffff right now

### Reproduction of behavior
![image](https://user-images.githubusercontent.com/1858226/32123363-beab17b2-bb18-11e7-880c-7a86d5623df4.png)

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
fixed
