### ISSUE TITLE
Documentation for clrSignpostPosition needs to be updated

### ISSUE THREAD

**Issue by aaronfrost** [vmware/clarity#1654]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

In the documentation for signposts, it says two things that need to be updated. First, it needs to show that `clrSignpostPosition` has changed to `clrPosition`, and second, it needs to show that the `clrPostion` goes on the `clr-signpost-content` component, NOT ON the `clr-signpost` component. Currently, the documentation shows that you should put `clrSignpostPosition` on the `clr-signpost` component, which causes Angular to throw errors. I had to dive into the code to find the right way to use this. 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://vmware.github.io/clarity/documentation/signposts

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@hippee-lee could you please take a look at this?

**Comment by hippee-lee** [comment]
Thanks for reporting this @aaronfrost.
I updated our docs and it will get published this week.
