### ISSUE TITLE
Login component not taking up entire page

### ISSUE THREAD

**Issue by KeirDavis1** [vmware/clarity#1656]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The login component to take up the entire screen with no scroll or padding.

### Actual behavior
Shows padding and a scrollbar. This is meant to be a single page login screen and doesn't look right with the padding and scrollbar.

### Reproduction of behavior
![image](https://user-images.githubusercontent.com/1273689/32175664-7c254144-bd7d-11e7-98e7-f7b0d13ae2a6.png)
![image](https://user-images.githubusercontent.com/1273689/32175682-863a958a-bd7d-11e7-9f83-313b85a5bd9d.png)

- Ran `ng g component login`
- Added login component to app.routing.ts
- Copied code from https://vmware.github.io/clarity/documentation/login into the login.component.html
- `ng serve`
- Go to `localhost:4200`

### Environment details

* **Angular version:** 4.4.6

* **Clarity version:** 0.10.10

* **OS and version:** Windows 10 Pro 

* **Browser:** Chrome 61.0.3163.100

**Comment by adityarb88** [comment]
@KeirDavis1: Our UX team recommends that you should use the login as a separate page without the header. It looks like you are placing the login inside of the `.content-area` which has a padding on it. Please let me know if this helps.

**Comment by KeirDavis1** [comment]
Yes, it's a component which is loaded in via the app.routing. How do I specify that the application load this without the `.content-area`?

**Comment by KeirDavis1** [comment]
Or should I really say, what is the recommended way of completing this?

I'm aware that the app.component.html contains the following snippet, however if I am to remove this, it will lose padding on all the other pages.
```
...
  <div class="content-container">
    <div class="content-area">
      <router-outlet></router-outlet>
    </div>
  </div>
...
```

**Comment by adityarb88** [comment]
@keirdavis1: You could use router outlet name to render the login component outside of the layout that clarity provides and render everything else inside of the layout.

More info here: 
https://angular.io/api/router/RouterOutlet
https://stackoverflow.com/questions/38038001/multiple-named-router-outlet-angular-2

If you have more questions, I would recommend asking on StackOverflow with the `vmware-clarity`.
https://stackoverflow.com/questions/tagged/vmware-clarity

In addition to us monitoring it, other users who have solved this use case also monitor it so you would get a quick response. Also, please attach a plnkr which replicates your issue.

Closing the issue based on this.

**Comment by jmls** [comment]
@KeirDavis1  did you ever solve this ? I have exactly the same issue, would appreciate the workaround of you have one
