### ISSUE TITLE
Tooltip support for svg

### ISSUE THREAD

**Issue by madhurpgarg** [vmware/clarity#1660]
**Select one ...**  (check one with "x")
```
[ ] bug
[ X ] feature request
[ ] enhancement
```

### Expected behavior
I would like to use the tooltip component in svg as well 

### Actual behavior
Not possible to use current tooltip component in svg

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@madhurpgarg 
What do you mean by "use the tooltip component in svg"?

**Comment by madhurpgarg** [comment]
I can use tooltip component as mentioned in documentation for ex,

<a href="..." role="tooltip" aria-haspopup="true" class="tooltip tooltip-md">
    <clr-icon shape="info-circle" size="24"></clr-icon>
    <span class="tooltip-content">Lorem</span></a>

​Which is fine when I am using this tooltip in regular html tags, but I
would like to use this tooltip ​with the same styling in D3 charts (which
are generated using SVGs). This tooltip component is not possible to be
used in SVGs because I can not embed regular HTML tags in SVG tags.

In my case the tooltip trigger is an SVG element(eg. <path> element ) and
the tooltip content can be regular HTML elements. Since in above component,
the tooltip trigger is tightly coupled with tooltip content, I am not able
to use this same component in SVG.

If, somehow, we can separate tooltip content with the trigger then I will
be able to use this component in D3 chart SVGs as well where I'll just keep
the tooltip component in HTML and add the trigger in the SVG.

Anyways, I have achieved what I want, but I had to write the HTML and CSS
manually which I don't think is the best way to do, if I have a component
ready to use.

Or, may be I am not using this component in best way so if you can guide me
to use it properly.

Regards,
Madhur Garg
----

**Comment by mathisscott** [comment]
@madhurpgarg 
Writing the HTML/CSS manually is the way to go. It may not seem that way. But if we were to "separate" the tooltip content as its own component, you'd have the same issue.
