### ISSUE TITLE
Weird behaviour using clr-dropdown inside a component with OnPush detection strategy

### ISSUE THREAD

**Issue by zeratulmdq** [vmware/clarity#1662]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```
### Actual behavior
We are migrating from 0.9.14 to latest and I’ve found a weird behaviour when using `clr-dropdown` on a component with `ChangeDetectionStrategy.OnPush`. If you don’t add the `clrIfOpen` directive to `clr-dropdown-menu` component, once you click on the trigger button, the menu opens correctly but if you click outside of the menu it moves to the top left corner of the parent container (instead of disappearing)
I know you’ll say “just use the directive, is the recommended approach” but it breaks the Output funcionality as you can see [here](https://github.com/vmware/clarity/issues/1642)

### Reproduction of behavior
[Plnkr](https://plnkr.co/edit/TQVZzn?p=preview)

### Environment details

* **Angular version:** 4.4.4

* **Clarity version**: 0.10.9

* **OS and version**: Sierra 10.12.6

* **Browser:** [Chrome | Firefox | Safari ]

**Comment by mathisscott** [comment]
@jeeyun 
Is this the same as #1710?

**Comment by mathisscott** [comment]
@jeeyun : Did we look at this in Palo Alto?

**Comment by jeeyun** [comment]
Hi @zeratulmdq, seems like this issue fell through the cracks and am just now taking a look. I am able to reproduce this issue with latest version of Clarity. We'll investigate this further and provide an update soon.

**Comment by mathisscott** [comment]
@jeeyun 
Any updates here? Is this still an issue?
