### ISSUE TITLE
Sketch UI Library: Label of text symbols to include application

### ISSUE THREAD

**Issue by ali5ter** [vmware/clarity#1668]
**Select one ...**
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
When adding/replacing a symbol from Clarity-UI-Library-0.10.11, it would be useful if the label for the text symbol described how the text should be used - like the former Craft library did for text styles (see image)
![screen shot 2017-11-03 at 11 13 24 am](https://user-images.githubusercontent.com/265869/32381133-599c8fde-c088-11e7-8c1d-520d0bd1c435.png)

### Actual behavior
When adding/replacing a symbol from Clarity-UI-Library-0.10.11, the list of text symbols doesn't suggest the application of the text (see image), so we have to refer back to the docs to see, for example, that a P3 should be used for form labels.
![screen shot 2017-11-03 at 11 13 06 am](https://user-images.githubusercontent.com/265869/32381248-9a858140-c088-11e7-94e6-8eee744ad05e.png)

### Reproduction of behavior
1. Download Clarity-UI-Library-0.10.11 from Clarity site
2. Open Sketch preferences and add this library
3. Add 

### Environment details

* **Angular version:** not applicable

* **Clarity version:** 0.10.11

* **OS and version:** macOS Sierra 10.12.6

* **Browser:** not applicable

**Comment by adityarb88** [comment]
@reddolan: Could you please take a look at this issue?

**Comment by mathisscott** [comment]
@reddolan 
Is this something we are planning to do?

**Comment by reddolan** [comment]
@mathisscott yes. I already have the changes made, I just need to get them posted to the site with this upcoming release. Still need to make the updates to Dark theme though. I will spin up a new issue for those updates and link them to this request
