### ISSUE TITLE
Need to add an indeterminate checkbox state. Design spec attached.

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#167]
![indeterminate checkbox](https://cloud.githubusercontent.com/assets/23196444/20736400/0c2026ae-b65b-11e6-9445-a43ae945fd51.png)

**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Needed in a tree view to denote a group/folder that has some items checked, but not all.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
i think we landed on this being good to go.
