### ISSUE TITLE
modify the CSS to allow for tooltips to be placed in the datagrid and table headers

### ISSUE THREAD

**Issue by shepsels** [vmware/clarity#1674]
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
When hovering over datagrid column title, it should show a tooltip with the full column name for long names.

### Actual behavior
There's no tooltip currently.
### Reproduction of behavior
any grid. for example:
https://embed.plnkr.co/plunk/KJhNDD

* **Browser:** [all ]

**Comment by adityarb88** [comment]
@shepsels: Clarity uses a declarative API. So if you wanted to do this you could do this right now. Please see this plnkr: https://plnkr.co/edit/WtlaxXPJgsSxGNiIC2Gd?p=preview Note that this is not recommended or supported by default. You would have to make sure that the column alignment is fine by adjusting the CSS at your end.

I will also tag our UX team to check with them, what they recommend you should do when you have long column names in the datagrid.

**Comment by mathisscott** [comment]
I think we should modify the CSS on our end to allow for tooltips to be placed in the datagrid and table headers without blowing out the height of the header cell. Other than that, I don't think we should change our UX recommendations or make any other concessions on this issue.

Given that the CSS is easy to implement on the product side, I will mark this as `has-workaround` and prioritize accordingly.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
