### ISSUE TITLE
Error when opening modal: No provider for InjectionToken DocumentToken!

### ISSUE THREAD

**Issue by chanm003** [vmware/clarity#1676]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Modal should open.

### Actual behavior
Console shows following error:
Error: No provider for InjectionToken DocumentToken!

Is this a service that needs to be registered somewhere?

### Reproduction of behavior
Copied the markup from:
https://github.com/vmware/clarity/blob/master/src/app/modal/modal-angular-show.demo.html

So view template looks like this:
```
<p>
    Try it live:
    <button class="btn btn-primary" (click)="basic = true">Show modal</button>
</p>
<clr-modal [(clrModalOpen)]="basic">
    <h3 class="modal-title">I have a nice title</h3>
    <div class="modal-body">
        <p>But not much to say...</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline" (click)="basic = false">Cancel</button>
        <button type="button" class="btn btn-primary" (click)="basic = false">Ok</button>
    </div>
</clr-modal>
```
And Component defines a boolean variable:
```
 basic: boolean = false;
```

Clicking on the 'Show Modal' button triggers an error.

### Environment details

* **Angular version:** 4.2.4

* **Clarity version: 0.10.11

**Comment by chanm003** [comment]
My app.module.ts looks like this:
```
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    ClarityModule.forRoot(),
    AppRoutingModule,
    CoreModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
I also use a shared module.  SharedModule gets imported into all my feature modules:
```
@NgModule({
  imports: [
    CommonModule, FormsModule, ClarityModule
  ],
  exports: [
    CommonModule, FormsModule, ClarityModule
  ],
  declarations: [],
})
export class SharedModule {}
```

**Comment by adityarb88** [comment]
@chanm003: I can't replicate this issue. Please see this: https://plnkr.co/edit/wKjfh33HbIQTR7aU6quh?p=preview 

Could you please replicate this on a Plnkr?

**Comment by chanm003** [comment]
@adityarb88 Thanks for the quick response.

The issue went away.  I upgraded from Angular 4.2.4 to 5.0.0 and went to Clarity 0.10.12

I am not sure if I had to do both.  Or just needed to do one of the above.
