### ISSUE TITLE
Add Clarity Icons to the Sketch Template

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#168]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Clarity Icons should be available in the Sketch template to make it easier for designers and users of the Sketch template to include it in their designs.

### Actual behavior
They're not there currently.

**Comment by reddolan** [comment]
Will have this ready for 0.7.3. I know we normally prefer to do whole number releases on the Sketch file, but this was something that I could get out fairly quickly and some folks have been asking for it.

**Comment by reddolan** [comment]
- Icons added to their own page
- Icons swapped out on components (except for Filter on Datagrid)
- sent file to Lilia for review
[Clarity-UI-Template-0.7.3.sketch.zip](https://github.com/vmware/clarity/files/626341/Clarity-UI-Template-0.7.3.sketch.zip)

**Comment by mathisscott** [comment]
Once Lilia approves, I can work with @adityarb88 to get this posted to the website.

**Comment by reddolan** [comment]
@mathisscott, Lilia's updates were made to the template. This can go live when you guys are ready to do so. 

[Clarity-UI-Template-0.7.3.sketch.zip](https://github.com/vmware/clarity/files/628430/Clarity-UI-Template-0.7.3.sketch.zip)

**Comment by adityarb88** [comment]
Added to the website
