### ISSUE TITLE
button loading spinner not showing in button group

### ISSUE THREAD

**Issue by marvinosswald** [vmware/clarity#1681]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

A loading spinner should show on a button even if its in a button group

### Actual behavior

loading spinner doesn't show

### Reproduction of behavior

https://plnkr.co/edit/k0vC2vtiV4wvPP4RrRZv?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.12

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@marvinosswald That plnkr contains a Modal. Could you please update to replicate the issue you are facing?

**Comment by marvinosswald** [comment]
@adityarb88 my bad, updated the plnkr same url though

**Comment by adityarb88** [comment]
@marvinosswald: Thanks for reporting this. This definitely is a bug and we will add this to our backlog.

**Comment by govi2010** [comment]
@adityarb88  I think this is because of `selector: "button[clrLoading]"` in loading-button.ts. ...

**Comment by adityarb88** [comment]
@govi2010: Yes right now the loading indicators works only for static buttons but we wont be able to extend the selector to `button[clrLoading], clr-button[clrLoading]` because `clr-button` already is a separate component. Angular will throw an error when two different templates are defined. I will think of a solution and discuss with the team on how we can resolve this.

**Comment by govi2010** [comment]
@adityarb88  I fixed this issue by

**Comment by govi2010** [comment]
<img width="600" alt="screen shot 2017-11-10 at 9 11 26 pm" src="https://user-images.githubusercontent.com/8776031/32665896-c1f1c7f6-c65b-11e7-87be-d6f6bd30be69.png">

**Comment by govi2010** [comment]
@adityarb88  any update on my code review. Let me know it you want to fix this any other way
