### ISSUE TITLE
[NG] Angular v5 migration

### ISSUE THREAD

**Issue by dherges** [vmware/clarity#1683]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Please support Angular v5! 

When you feel ready to and decide to migrate to v5, can you keep me posted whether you encounter issues with binaries produced by [ng-packagr](https://github.com/dherges/ng-packagr)?

We've started migration using [ng-packagr@1.5.1](https://github.com/dherges/ng-packagr/blob/master/CHANGELOG.md#151-2017-11-10) (note the bugfix!) and though it uses the 4.4.x tsc-wrapped, I have not encountered any issues for first ~50 components... :parasol_on_ground: 

### Actual behavior

Angular four!

### Reproduction of behavior
n/a

### Environment details

* **Clarity version:** v0.10.13

**Comment by mathisscott** [comment]
Hi @dherges 
Thanks for checking in with us!

We have a PR out for the NG5 upgrade -> #1659 

The plan is for that to go out in our 0.11 release. We will have alpha and beta releases before that so please subscribe to #1659 and you'll see when the changes are merged in.
