### ISSUE TITLE
How to implement [clrLoading] 

### ISSUE THREAD

**Issue by bnlambert** [vmware/clarity#1684]
Hi

I am using Clarity with angular 4.x. I am unable to implement [clrLoading]. I keep having this error

'ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'clrLoading' since it isn't a known property of 'button'. ("'

**Comment by adityarb88** [comment]
@bnlambert: Thanks for filing the issue. Could you please re-submit the issue following our issue template which you can access when you open a new issue? We require the version of Clarity you are using and also a Plnkr which replicates the issue. Without this information, it wont be possible for us to debug the issue. Thanks!

Closing the issue based on this.

**Comment by purushottamjha** [comment]
I am getting the same error.

**Comment by Jinnie** [comment]
Here are the stackblitz templates that can be used to reproduce the issue for different Clarity versions:
https://stackblitz.com/@clr-team
