### ISSUE TITLE
how to programmatically control the open/close of dropdown

### ISSUE THREAD

**Issue by krist-jin** [vmware/clarity#1686]
Hi,

I'm trying to figure out a way to programmatically control the open and close for clarity dropdown.

Here is what I have tried:
1. using property binding to **clrIfOpen**
I prefer this way but it's not working properly. Say I bind a variable **openDropDown** to **clrIfOpen**. When the dropdown is closed, dropdown.ifOpenService.open is set to false but **openDropDown** is still true. If I set **openDropDown** to true again then it will not change the value of dropdown.ifOpenService.open and dropdown will not open.

2. setting dropdown.ifOpenService.open
This way seems working but please refer to https://embed.plnkr.co/lNLRDaKFC0txNXf210Of/
If I click on the button and set a break point to line#64 in ip-open.service.ts, you will find that the dropdown is actually opened and then closed immediately.

So my question is what's the correct way to programmatically control the open/close of dropdown?

**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Properly open and close dropdown programmatically

### Actual behavior
?

### Reproduction of behavior
https://embed.plnkr.co/lNLRDaKFC0txNXf210Of/

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all]

**Comment by adityarb88** [comment]
@krist-jin: Programmatically opening and closing the dropdown using `*clrIfOpen` should work. Please take a look at this Plnkr: https://plnkr.co/edit/e1Fcz1XmNK4zfAxKk8A2?p=preview

In your case whats happening is that when you click the toggle dropdown button outside, it closes the dropdown menu itself because the dropdown is closed when you click outside of the menu.

Let me know if this helps.

**Comment by krist-jin** [comment]
Thanks @adityarb88
What if I change to `this.openDropDown = true;`
Then it will pop up for this first time, then if I click outside of the menu it will disappear and never show again automatically.
What should I do in order to show the menu again through `this.openDropDown = true;` after I click outside? Thanks!
please refer to: https://plnkr.co/edit/any84rmAlVaQcf4Z6qRN?p=preview

**Comment by adityarb88** [comment]
@krist-jin: Then you should use the de-sugared syntax for the clrIfOpen structural directive. More info here: https://plnkr.co/edit/tiC8eWf4u3kTJaYWGR8M?p=preview I hope this answers your question. Closing the issue based on this. Please feel free to ask more questions on StackOverflow with the `vmware-clarity` tag. We monitor StackOverflow daily and your question might be beneficial to other members of the community too. More details here: https://stackoverflow.com/tags/vmware-clarity
