### ISSUE TITLE
clr-tab-content not maintaining state across tab clicks

### ISSUE THREAD

**Issue by chanm003** [vmware/clarity#1688]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
```
<clr-tabs>
    <clr-tab>
        <button clrTabLink>Pending</button>
        <clr-tab-content *clrIfActive="true">
            <some-child-component></some-child-component>
        </clr-tab-content>
    </clr-tab>
    <clr-tab>
            <button clrTabLink>Approved</button>
            <clr-tab-content *clrIfActive>
                [Placeholder]
            </clr-tab-content>
    </clr-tab>
</clr-tabs>
```

1.  Page loads
2. User interacts with child component in first tab
    -  types 'Hello World' into a `<input type="text">`
3. User clicks on tab two
4. User clicks on tab one, and child component should remember its state
    - i.e. the text 'Hello World' should remain in the `<input type="text">`

### Actual behavior
Same steps as above, but after step 4, the text box is blank again.   Lifecycle hooks on child component indicate that ngOnDestroy is fired as soon as tab two is clicked.

### Reproduction of behavior
https://embed.plnkr.co/YA3TGT/

### Environment details

* **Angular version:** 5.0.0

* **Clarity version:** 0.10.12

**Comment by adityarb88** [comment]
@chanm003: This is how tabs are designed to work. Only the active tabs remains in the view. This is done to improve performance of the page. Imagine that an app had 6-7 tabs and all tab content was stored in memory. That would impact the performance of the application.

If you wanted to save the state of the application you could do it in multiple ways. One way is to use Inputs and Outputs. You could even use a service if you wanted to do this. Here is a quick and dirty prototype of the Input/Output approach:
https://plnkr.co/edit/g2K8WkULpzKvJWbCAcRK?p=preview

Let me know if that helps. Closing the issue based on this. Please feel free to reopen the issue if you have more questions.
