### ISSUE TITLE
How to prevent converting px into rem

### ISSUE THREAD

**Issue by falcon-eu** [vmware/clarity#1690]
Hi all,

My root html font size was set to percent. I upgraded clarity lib in my project based on Angular. As an effect my template is extremaly different than before becaouse all properties based on pixels are automatically converted into rem. How to prevent that? Thank you for help in advance.

**Comment by mathisscott** [comment]
Hi @falcon-eu 
If you could [provide a plunkr](https://plnkr.co/edit/uNwwZe) with the general idea of what you are trying to do by setting the `html` font-size to a percent, we could probably help you figure something out.

**Comment by falcon-eu** [comment]
Okay my problem was that my project includes styles from file cliarity-ui.css located in node_modules and lots of styles were inherited from there. I have just copy old css file and now everything is okay.
