### ISSUE TITLE
Problem with clarity-ui package wrt css 

### ISSUE THREAD

**Issue by brihaspati** [vmware/clarity#1692]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Angular is supposed to be able to identify locally installed clarity styles css files 
### Actual behavior

There is some sort of problem with clarity css packages, due to which it's not being recognized by Angular, however if I use the CDN version of same in Index.html, it works just fine
### Reproduction of behavior
Local Setup:
1. Angular-cli(version 1.5.0) with Angular 5. 
2. NPM as package manager, chrome as browser

Steps: 
1.Created new angular project using angular-cli--> `ng new example-project`
2.Installed Clarity-Ui--> `npm install clarity-ui --save`
3.Added `"../node_modules/clarity-ui/clarity-ui.min.css"` in the angular-cli.json styles section as described in getting started section of clarity, but this stylesheet was not recognized by Angular
4. Also, I tried to link the same in index.html--> `<link rel="stylesheet" href="../node_modules/clarity-ui/clarity-ui.min.css" />`, again it didn't work
5.Finally if I use the hosted version, it works--> `<link rel="stylesheet" href="https://unpkg.com/clarity-ui/clarity-ui.min.css" />`

Note: I had tried the same with Angular 4.x few days back it wasn't working either.

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.0.0

* **Clarity version:Latest**

* **OS and version:Mac Os, Sierra** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
Our website is built with angular-cli and it works for us. For more info please refer to this: https://github.com/vmware/clarity/blob/new-website/angular-cli.json

Would you be able to share a sample repo which reproduces the issue?

**Comment by brihaspati** [comment]
@adityarb88, Apologies. I had faced this two times for sure, otherwise i wouldn't have raised an issue here.And I am pretty sure that I had followed the same procedure each time as I am comfortable in using angular-cli. But with a new project setup, its working fine now. I don't know whats the issue here, for now, please close the bug. Hope it won't appear again in future.

**Comment by adityarb88** [comment]
@brihaspati: No worries. Let us know if you face any issues. Thanks!
