### ISSUE TITLE
Badges in Labels alignment issue

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#1700]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Labels with badges should look aligned properly.

### Actual behavior

Badges are slightly high.

![screen shot 2017-11-17 at 1 40 22 pm](https://user-images.githubusercontent.com/79500/32966055-340b9528-cb9e-11e7-9f45-d833ea2164d4.png)

### Reproduction of behavior

Can be seen on docs. https://vmware.github.io/clarity/documentation/labels#labels-with-badges

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.14

* **OS and version:** OSX 10.12

* **Browser:** Chrome 62, Safari 11 (Firefox Quantum looks ok), Win unknown

**Comment by bangelakos** [comment]
This doesn't seem to occur on a build of the latest locally.

![image](https://user-images.githubusercontent.com/1455881/33088094-3c2f9db4-ceb2-11e7-89ae-bf222e20d3f8.png)

**Comment by mathisscott** [comment]
@hippee-lee 
Can you take a look and see if this is an issue still? No rush. Later this week or next week is fine.

**Comment by hippee-lee** [comment]
There is an issue. The website is 1px off for the placement of the badge in the label. 
Have not found the root cause yet though as the style on both the label and the badge for both the published website (incorrect) and clarity@latest used here: https://stackblitz.com/edit/label-investigation (correct)

**Comment by mathisscott** [comment]
@hippee-lee 
Could this be a problem with just the website? Maybe there is a custom style on the website that is causing a conflict?

**Comment by hippee-lee** [comment]
Yeah, that's what I suspect. I'm running it locally now to see if I can quick fix it. 
Just wanted to make notes so I didn't forget :-)
