### ISSUE TITLE
Textbox [type="date"] year format validation allows 6 character YYYY

### ISSUE THREAD

**Issue by boemska-nik** [vmware/clarity#1701]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The Textbox date-formatted selector for dates validates to 4-digit YYYY value

### Actual behavior

There's a couple of digits too many on the YYYY, it's more like YYYYYY. 

Here's what I did in Chrome 62 on Windows on the example in the Input Fields docs:

![image](https://user-images.githubusercontent.com/11962123/32985870-699c3b06-ccbc-11e7-9021-46a1a1d292b1.png)

### Reproduction of behavior

See screenshot above

* **Browser:** Chrome 62

**Comment by coldhamix** [comment]
It has nothing to do with Clarity, it's just how date picker works in Chrome. You can still do something like:

```
<input type="date" max="9999-12-31" />
```

**Comment by adityarb88** [comment]
@boemska-nik: @coldhamix is right. We have just styled the native date input. You have to handle the validation at your end for the native date input. Closing based on this. Thanks!
