### ISSUE TITLE
Allow removal of modal & wizard overlay in iframes

### ISSUE THREAD

**Issue by vpvelikov** [vmware/clarity#1704]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Consider the following use case: I am developing a UI extension to existing Web application which normally does not allow me to access/modify its DOM (e.g. my piece of UI is embedded inside an iframe).

I would like to be able to use Clarity modal and wizard components with no dark overlay to prevent bad user experience.

### Actual behavior
If I use a Clarity modal or wizard component within an iframe the overlay is populated only inside the iframe. My UI code has no access to the parent window so I cannot apply the modal overlay behavior to the app globally (like I could if I owned the application). This leaves bad user experience and prevents me from using the components at all.

### Reproduction of behavior
See this screenshot from the Clarity documentation with comments:
![image](https://user-images.githubusercontent.com/29205644/33077204-da3ddb22-ced7-11e7-99e5-90a889dc70ac.png)

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.14

* **OS and version:** all

* **Browser:** all

**Comment by adityarb88** [comment]
@vpvelikov: But you could modify the CSS to remove the backdrop and change the height of the modal dialog, no? Something like this: https://plnkr.co/edit/OzfeYFIdvYjhj0eR3OuE?p=preview

**Comment by vpvelikov** [comment]
This makes the dark overlay disappear but in the provided example I get significant useless whitespace instead and my actual wizard does not scale up to cover the whole iframe.
Generally, overlay and whitespace offset don't make sense inside an iframe. So I think the Clarity component should allow me to configure it to take up the full area in this case like this:
![image](https://user-images.githubusercontent.com/29205644/33078178-8b45fb0a-ceda-11e7-8c62-d6e7ee80d092.png)

It would be great if the Clarity wizard can accommodate this scenario, should be pretty straightforward.
Does that make sense?

**Comment by adityarb88** [comment]
@vpvelikov: But you could also change the size of the modal dialog using CSS. Clarity also provides 4 sizes for the modal. May be use the `xl` size?  

Removing the backdrop and then changing the size of the dialog box is not recommended by our UX team. I don't believe we will be able to do this on our end. The modal component is supposed to pop-out and the dialog should not take the entire space on the user's screen. The backdrop on the modal helps to let the user know that the dialog is open on top of the current user workflow and needs to be acted upon to continue with the workflow. Removing the backdrop and then modifying the modal dialog size to occupy the whole screen, means that the user might lose context of where they are in the application.

We do not recommend you do this but if this is needed then I would recommend overriding the CSS on your end to make these changes.

Closing the issue based on this. Please feel free to reopen the issue if you have more questions.

**Comment by adityarb88** [comment]
@vpvelikov: Thanks for your feedback. I will let our UX team take a look at this and respond back.
cc: @mathisscott @reddolan

**Comment by vpvelikov** [comment]
@adityarb88 Cool, thanks a lot for having a look at it.

**Comment by adityarb88** [comment]
@vpvelikov: You could also use the inline wizard. Please refer to this link: https://github.com/vmware/clarity/blob/master/src/app/wizard/wizard-inline.demo.html

**Comment by vpvelikov** [comment]
@adityarb88 That's great! Seems exactly what I am looking for. I will try it out and report if there are any problems. Thanks a lot for the positive reply.

Just one more question: Are **clrWizardPreventModalAnimation**, **clr-wizard--inline** and **clr-wizard--no-shadow** supported by Clarity? Where can I read the full list of options?
I hope all demos I see in the wizard folder are official ones that can be used even if they are not part of the Clarity components docs. :)

**Comment by vpvelikov** [comment]
Tested it and it works quite well within the iframe.
There is one glitch: the wizard scales horizontally to consume all available width of the iframe but it **does not scale vertically to consume all available height**. It turns out _clr-wizard--inline_ defines "position: static" style which causes the issue. If it is changed to "position: fixed" llike it is for normal wizards all is fine.
As I don't want to hack the component by overriding styles:
Is there any reason why this static position is done? Is there another Clarity-defined class or style I can use to make sure I have fixed position?
Thanks.

**Comment by vpvelikov** [comment]
The mentioned issue is because when static position is used there needs to be **max-height: 100%** for both the navigation and the content area. Instead, this was applied only to the content area. The following screenshot explains the problem with the Inline wizard:
![image](https://user-images.githubusercontent.com/29205644/33129776-c9eac754-cf99-11e7-88a3-50d0124d6e90.png)
Could you please look into fixing this?
Should be trivial to add 100% max-height for the navigation area.

**Comment by adityarb88** [comment]
@vpvelikov: Thanks for doing this investigation. Inline wizards was created by just modifying the CSS for the pop-out wizard. Not a lot of users use Inline Wizards and we do not plan to support it. We haven't found a lot of issues with inline wizards (this might be one of the first ones reported) but we rely on external contributions from users who use this feature to fix bugs. Please feel free to submit a PR with the same details that you provided above to fix the issue. If you are unable to submit a PR, would you mind filing a separate issue for it so that we can add a `help-wanted` label on it. Thanks!

**Comment by vpvelikov** [comment]
Cool, I will do that.
But I hope you are not planning to drop **clrWizardPreventModalAnimation**, **clr-wizard--inline** and **clr-wizard--no-shadow**, right? :)

**Comment by mdmarkova** [comment]
@adityarb88: I filed a new issue: https://github.com/vmware/clarity/issues/1711
