### ISSUE TITLE
Clarity doesn't work with IE11

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#1705]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Expect my SPA to load and function in IE 11. My application works fine in Firefox Quantum and Chrome 62.

### Actual behavior
Page fails to load and throws an error in polyfills.bundle.js on line 396 (see enclosed screenshot). 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** .10.14

* **OS and version:** 
Windows 7 SP1
* **Browser:** [all | Chrome XX | Firefox XX | IE 11 | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

![image](https://user-images.githubusercontent.com/27329476/33086654-13c79314-ce9d-11e7-9d8a-af28c0a7d2e0.png)

**Comment by gnomeontherun** [comment]
What polyfills do you have enabled? The `app/polyfills.ts` file has some imports to include for IE11 and have comments to tell you which ones.

**Comment by beaker1977** [comment]
Thanks for the info. I didn't even know about the polyfills.ts file. After uncommenting the IE import statements my SPA now loads, albeit with some funky CSS behaviour I'll have to deal with. You can mark this closed.

**Comment by gnomeontherun** [comment]
Great, you can also reference Angular docs https://angular.io/guide/browser-support#polyfills
