### ISSUE TITLE
Loading text is displayed inside Datagrid spinner

### ISSUE THREAD

**Issue by karmasakshi** [vmware/clarity#1709]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Spinner without "Loading..." when Datagrid `clrDgLoading` is `true`.

### Actual behavior
"Loading..." text spins with the spinner.

### Reproduction of behavior
Check https://github.com/vmware/clarity/blob/master/src/clarity-angular/data/datagrid/datagrid.html, line 59.

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.10.14

* **OS and version:** macOS 10.13.1

* **Browser:** Checked on Chrome 61 only

**Comment by karmasakshi** [comment]
It's surprising it doesn't show in the demo: https://vmware.github.io/clarity/documentation/datagrid/server-driven.

**Comment by adityarb88** [comment]
@karmasakshi: Could you please post a plnkr which replicates the issue that you are facing? This will help us debug the issue. Thanks! Plnkr template: https://embed.plnkr.co/AuJuo5/
