### ISSUE TITLE
Active and open classes do no get removed when dropdown is used inside a header

### ISSUE THREAD

**Issue by dexfab** [vmware/clarity#1710]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When user clicks outside the dropdown content area:
- open class should be removed from clr-dropdown item
- active class should be removed from div with dropdown-toggle class

### Actual behavior
When user clicks outside the dropdown content area:
- open class remains on clr-dropdown item
- active class remains on div with dropdown-toggle class
(both classes are removed if clicking on the toggle itself)

Dropdown behaves properly when used outside of header.

### Reproduction of behavior
`<clr-header>`
`  <div class="header-actions">`
`    <clr-dropdown>`
`    <button type="button" class="btn btn-outline-primary" clrDropdownTrigger>`
`        Dropdown`
`        <clr-icon shape="caret down"></clr-icon>`
`    </button>`
`    <clr-dropdown-menu clrPosition="top-left" *clrIfOpen>`
`        <label class="dropdown-header">Dropdown header</label>`
`        <button type="button" clrDropdownItem>Action 1</button>`
`        <button type="button" disabled clrDropdownItem>Disabled Action</button>`
`        <div class="dropdown-divider"></div>`
`        <clr-dropdown>`
`            <button type="button" clrDropdownTrigger>Link 1</button>`
`            <clr-dropdown-menu>`
`                <button type="button" clrDropdownItem>Foo</button>`
`                <clr-dropdown>`
`                    <button type="button" clrDropdownTrigger>Bar</button>`
`                    <clr-dropdown-menu clrPosition="left-top">`
`                        <button type="button" clrDropdownItem>Baz</button>`
`                    </clr-dropdown-menu>`
`                </clr-dropdown>`
`            </clr-dropdown-menu>`
`        </clr-dropdown>`
`        <button type="button" clrDropdownItem>Link 2</button>`
`    </clr-dropdown-menu>`
`</clr-dropdown>`
`  </div>`

`</clr-header>`

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.10.13

* **OS and version:** Windows 10

* **Browser:** all

**Comment by adityarb88** [comment]
@dexfab Could you please replicate the issue on a plnkr? I can't seem to replicate it. It works fine for me. Please see this: https://plnkr.co/edit/HZz0wUvG4q2I7XvmkvSg?p=preview

**Comment by dexfab** [comment]
@adityarb88 thanks for the quick update. I've tried the plunker and couldn't reproduce it either. So I went back to our app and what seems to be causing the issue is that we are wrapping the header inside its own component. If I take the header out into the main app component, I get the expected behavior.
Code is like:
`<clr-main-container>`
`<app-navbar>`
`<clr-header>`
`...`
`</clr-header>`
`</app-navbar>`
`</clr-main-container>`

I'll try to reproduce this Plunker but I wonder is the extra div added by the component causing the bug.

**Comment by dexfab** [comment]
@adityarb88 I'm managed to reproduce it in plunker:
https://plnkr.co/edit/4DwQByxHVV869Fz5Bq8h

It seems that using a different change detection policy is causing the issue.

**Comment by mathisscott** [comment]
@adityarb88 ^

**Comment by jeeyun** [comment]
@dexfab thanks for the plunker link. Makes it much easier for us to narrow down the issue. 👍 As you probably know, when you use `onPush`Angular will only run change detection under certain conditions (for example, when a components input value changes) so in your case, it's not re-rendering the navbar component because you aren't triggering a condition in the app that would cause it to rerender. You could probably move down the usage of the `onPush` detection strategy to a sub-component of your app that needs it, rather than in the component that contains the navigation.
