### ISSUE TITLE
Modal Dialog box not displayed

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#1712]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Modal dialog box should open when button is clicked

### Actual behavior
Modal does not open and the following error is shown in the web console:

ERROR Error: Found the synthetic listener @fadeDown.done. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

### Environment details

* **Angular version:** 5.0.3

* **Clarity version:** 0.10.15

* **OS and version:** Windows 10

* **Browser:** [Chrome XX | Firefox XX]

**Comment by KANekT** [comment]
Clarity not support Angular 5 ?

**Comment by KANekT** [comment]
I updated to 4/4/6

**Comment by appsilva** [comment]
I'm using Clarity Design System's Modal and I only had this problem when adding storybook to my angular application, but the solution is similar.. just add the **_BrowserAnimationsModule_** to the **_moduleMetadata_** imports and it should work.

```
export const withDefault = () => ({
    component: ModalComponent,
    props: { ... },
    moduleMetadata: {
        imports: [ ..., BrowserAnimationsModule ],
    },
});
```
