### ISSUE TITLE
Conditional clr-dg-row-detail

### ISSUE THREAD

**Issue by zivanov123** [vmware/clarity#1713]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ X ] enhancement
```

### Expected behavior
Currently there is no way to have a datagrid with expandable rows and some of them to not have the expand caret.
This is needed in the case where [clrDgReplace] is true and expanding actually won't be displaying anything more than currently displayed.

### Actual behavior
The caret in case of datagrid with clr-dg-row-detail cannot be hidden.

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.6

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
I don't understand the request, it's entirely possible to have some rows expandable, and some not: https://plnkr.co/edit/8RhYgQrPmFdE5jHWsdm4?p=preview

Is that what you need?

**Comment by zivanov123** [comment]
Yes, that is exactly what I needed.
I've missed the ngProjectAs part with ng-container.

Thanks!
