### ISSUE TITLE
Multi app level alerts pager control's background sets to white

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#1714]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Background color of the multi-alert pager should be of the same color hue of the currently displayed alert.
### Actual behavior

The background color of the pager is white and the text is not visible.
![image](https://user-images.githubusercontent.com/1977391/33226560-db7dbc2c-d1cb-11e7-98f5-bd48616f7e2c.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

Here's the plunker to replicate the issue: https://plnkr.co/edit/Vjn1uE

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**0.10.15

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
For some reason we're missing a `:host { display: block }` on the alerts container.

In the meantime, you can simply fix it on your side by adding this in your CSS:
```css
.alerts {
  display: block;
}```

See this modified version of your plunker with the added CSS: https://plnkr.co/edit/eMjDP3?p=preview
