### ISSUE TITLE
Bad resizing

### ISSUE THREAD

**Issue by bystronerik** [vmware/clarity#1715]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

Bad resizing, more on screen
[https://imgur.com/a/7pPTY](https://imgur.com/a/7pPTY)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.0.0

* **Clarity version:** 0.10.15

* **OS and version:** Windows 10

* **Browser:** Chrome 57.0.2987.133

**Comment by gnomeontherun** [comment]
No longer an issue or resolved in the upcoming website work. Closing as resolved.
