### ISSUE TITLE
Stack View

### ISSUE THREAD

**Issue by 19Arne75** [vmware/clarity#1716]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Stack view children with overflow enchantment similar to datagrid `<clr-dg-action-overflow>` to allow adding/removing/children easily when using editModal as shown in Clarity example with value editing.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Can we get more information on the feature or bug you're describing? Maybe a [plunkr](https://plnkr.co/edit/uNwwZe) setting up what you are expecting to happen and then a description of what isn't?
