### ISSUE TITLE
Request for split pane similar to ng2-split-pane in clarity

### ISSUE THREAD

**Issue by indukr** [vmware/clarity#1717]
**Select one ...**  (check one with "x")
```
[ ] bug
[X ] feature request
[ ] enhancement
```

### Expected behavior
My basic requirement is to split a screen in wizard step. I don't need the splitted screen to be resizable also. Currently I am using ng2-split-pane to acheive the same. Can you let me know if you have similar functionality in clarity to achieve the same? If yes, please share your knowledge on this

### Actual behavior
N/A

### Environment details

* **Angular version:** 4.3.0

* **Clarity version:** 0.10.8

* **OS and version:** windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jacobbutton** [comment]
If you don't need the "panes" to be resizable, could you not just use the Grid component to create two columns?

https://vmware.github.io/clarity/documentation/grid

**Comment by indukr** [comment]
hi @jacobbutton ,
Thanks for suggesting grid option but grid's behavior is horizontal and I am looking for a vertical split of the screen that may look like: 
![image](https://user-images.githubusercontent.com/26592033/33305574-c71341b0-d434-11e7-81dd-39d58332c6f0.png)

Is there a way to do this using grid or any other options in clarity?

Thanks
Rajendra

**Comment by mathisscott** [comment]
@indukr 
You could do it regular CSS and HTML. You could use flexbox if you wanted. Or an HTML table. Or CSS grid – depending on your browser support. Easiest path is probably CSS grid.

https://developer.mozilla.org/en-US/docs/Web/CSS/grid

**Comment by indukr** [comment]
Hi @mathisscott ,
Thanks for your suggestion. I tried it and I am able to get the UI as required. But found a better option in the form of "angular-split" which is a wrapper over 'split.js' and is more flexible and easy. Just updating you as this might be useful when you come up with a clarity component for split pane ;)

Thanks
Rajendra
