### ISSUE TITLE
Indeterminate (Looping) Progress Bars do not get color styling

### ISSUE THREAD

**Issue by a-student** [vmware/clarity#1718]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Consider this code:
```
<div class="progress loop danger"><progress></progress></div>
```
Progress bar is expected to be red (`danger` styled).

### Actual behavior

Progress bar is blue as by default.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/efcWXsvKTAUHekK6P8g2?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** Latest

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@a-student 
I cannot get your plunkr to work but I have verified that this is an issue on the website.
