### ISSUE TITLE
Make title element inside SVG optional

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#1723]
Could you please make the title element of SVG optional, because in Firfox, the title will be shown as a tooltip when hover the icon (which is not always wanted).
<img width="286" alt="image" src="https://user-images.githubusercontent.com/3956876/33306405-716bd9de-d44d-11e7-9f10-bc5ef2ff166f.png">

**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Remove the title element inside the SVG to not show the tooltip in Firefox if an optional attribute is set.

### Actual behavior

The title is always there inside the SVG element, thus, there's always a tooltip for an clarity icon when hover.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** not specified

* **Clarity version:** not specified

* **OS and version:** not specified

* **Browser:** [all]

PS:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/3956876/33306617-416b3e36-d44e-11e7-9610-63c3709a9dd5.png">
Is it because of the tooltip component?

**Comment by Shijir** [comment]
@KingMario which version of Clarity Icons are you using? We have made a change to Clarity Icons in the version of 0.10.12 that addresses this issue. So if you upgrade to Clarity Icons v0.10.12 or later versions, that tooltip shouldn't appear in any browser.

**Comment by KingMario** [comment]
@Shijir The version is 0.10.4. I just tried the version of 0.10.12 and the problem is gone. Thanks for your help.
