### ISSUE TITLE
ng-packagr question

### ISSUE THREAD

**Issue by rmeshksar** [vmware/clarity#1729]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] Just a question
```

Hi,
I am learning about ng-packagr and found your project to be using it.
I would appreciate your clarification on my question.

Noticed that in this file:
https://github.com/vmware/clarity/blob/master/src/clarity-angular/index.ts

All the modules have been exported first. Wondering if there is a module per component why the module for each component is not exported on its own index.ts file along with components, directives, ... .

Thanks.

**Comment by youdz** [comment]
Good catch, there is no reason, it's just an artifact of the old architecture.
It's an easy change, just a bit long and manual. 😛 

Thanks for raising this!

**Comment by rmeshksar** [comment]
Thanks for prompt reply, I noticed exact same structure in another library as well and thought maybe there is a reason for that.
https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/index.ts

**Comment by georgiee** [comment]
While you are already talking about this.

I think the content of the files index.ts and public_api.ts are semantically upside down. The public_api.ts is there by convention to define what's being exported, the index.ts is only defined for convenience when pointing locally to this folder. You reverse that meaning by putting everything in the index.ts already.

In the end this all really doesn't matter as the code is exported anyway but it's a very little semantic difference and easily fixable.

**Comment by youdz** [comment]
Yes, the `index.ts` and `public_api.ts` are reversed. I mentioned this to the team a couple weeks back, we haven't adressed it yet though because of the low priority. Thanks for pointing it out. 😉
