### ISSUE TITLE
Does Clarity UI Support Targets in the Progress bars..

### ISSUE THREAD

**Issue by sunpasup** [vmware/clarity#1731]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@sunpasup 
What do you mean by "targets"?

**Comment by juanmendes** [comment]
I think the suggestion was to have steps at specified percentage points

Something like 

![image](https://user-images.githubusercontent.com/549331/36546102-7b79a498-17b8-11e8-8850-b0faa2a6f8b0.png)

**Comment by mathisscott** [comment]
@juanmendes 
We call this a "timeline". We have open issues for a vertical and horizontal version (#353 and #1633 ).

Please subscribe to those issues for updates. Thanks!
