### ISSUE TITLE
Make UX recommendation for datagrid export

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1735]
We need a design recommendation for how people should implement datagrid export. We will discuss whether this lives on the Clarity site under the datagrid documentation or elsewhere.

Teams want to implement export functionality in their datagrids but are looking to us for visual/workflow consistency.

**Comment by reddolan** [comment]
We should just recommend that people use the action buttons above the datagrid. Create one that has a EXPORT label or and export icon.
