### ISSUE TITLE
Resized icons not displaying properly in vertical-nav component

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#1737]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Resizing icons to 24 from the default 16 on a vertical-nav link should display a larger icon and icon should be displayed when vertical nav collapses.

### Actual behavior
I have a vertical nav component with icons in the links. I have resized the icons to size 24 from the standard 16 and am using the 'clrVerticalNavIcon' property on the nav link so the icon is displayed when the vertical nav is collapsed. However the icon still shows as size 16 instead of 24. Further, it only resizes to 24 and displays when collapsed when I remove the 'clrVerticalNavIcon' property from the link.

### Reproduction of behavior
I couldn't figure out how to fork the clarity plunker template. I've included screen shots of the behavior and the code I'm using for my vertical nav.

<clr-main-container>
    <div class="content-container">
      <div class="content-area">
      </div>
    </div>
     <clr-vertical-nav  [clrVerticalNavCollapsible]="true" [(clrVerticalNavCollapsed)]="collapse">    
            <a clrVerticalNavLink ><clr-icon shape="search" clrVerticalNavIcon></clr-icon>Search</a>
            <a clrVerticalNavLink ><clr-icon shape="search" size="24" clrVerticalNavIcon></clr-icon>Search2</a>
            <a clrVerticalNavLink ><clr-icon shape="search" size="24"></clr-icon>Search3</a>
     </clr-vertical-nav>
</clr-main-container>
[Clarity issue.pptx](https://github.com/vmware/clarity/files/1522396/Clarity.issue.pptx)

### Environment details

* **Angular version:** 4.1.x

* **Clarity version:**
.10.15
* **OS and version:** 
Windows 7
* **Browser:** [al | Chrome 62| Firefox quantum| IE 11 |

**Comment by beaker1977** [comment]
Here you go. https://plnkr.co/edit/0JcaOa4UrPUO1m5TYcNb?p=preview

**Comment by reddolan** [comment]
@beaker1977 the icon sizes were intentionally made that size so that they did not overwhelm the text to the right of them. We do have plans to bump the size of all 16px icons to 18px to work better with our vertical rhythm, but that is a little ways out. We don't have plans to increase the size past 18px though

**Comment by beaker1977** [comment]
18 is better than 16 but still kind of small to my eyes, but beggars can't be choosers. Thanks for the info.

**Comment by reddolan** [comment]
Closing. 

Will be generating new issues for
- global icon resizing to respect the 6px ratio
- ability to override the size of icons in an easier fashion
