### ISSUE TITLE
Lack of font customization

### ISSUE THREAD

**Issue by icepeng** [vmware/clarity#1738]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
There should be a method or document provided to use a font other than Metropolis as a basis.

### Actual behavior
Theme entry in the document states that Font customization is possible, but it is very difficult to actually change the font-family. Creating the theme.scss and overriding $clr-font does work, but it took a long time to figure this out. Is it better to provide some methods, especially for using non-latin language countries?

**Comment by mathisscott** [comment]
@icepeng 

I don't think adding a method or mixin would help for this. Documentation specific to changing the default font might be helpful, however.

**Comment by paul-mcgrath** [comment]
Yes, this would be incredibly helpful 👍
