### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by KashMoneyMillionaire** [vmware/clarity#1739]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
A set of templates to use for emails, including inline css, similar to https://foundation.zurb.com/emails/email-templates.html

**Comment by mathisscott** [comment]
Thanks for the suggestion, @KashMoneyMillionaire 

Email templates are not in our plans. I'll leave this open on the project for future consideration.
