### ISSUE TITLE
Responsive Table

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#1746]
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
I wanna to table that responsive in mobile and tablet view. If you have this feature, please send us this manual.

Thanks

**Comment by mathisscott** [comment]
@essivision 
Can you give me more details on your use case? If you [submitting a simple plunkr](https://plnkr.co/edit/uNwwZe) detailing your issue, we might be able to help.

**Comment by essivision** [comment]
There are some example of responsive table:

[https://css-tricks.com/examples/ResponsiveTables/responsive.php](https://css-tricks.com/examples/ResponsiveTables/responsive.php)

[https://datatables.net/extensions/responsive/examples/column-control/auto.html](https://datatables.net/extensions/responsive/examples/column-control/auto.html)

**Comment by mathisscott** [comment]
@essivision 
You can't do this with CSS? We even have responsive utility classes from Bootstrap alpha.5.

This doesn't seem like a Clarity issue.
