### ISSUE TITLE
Add vol 9 icons to Icon Library

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1748]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
vol 9 icons included in the Icon Library
#1518 - vol 9 icons are here

### Actual behavior
no vol 9 icons are in there now

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.16

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
This will be fixed by #1744. Probably will go in v0.10.17.

**Comment by reddolan** [comment]
@hippee-lee here is the updated Icon Library for the site
[Clarity-Icons-Library-0.10.17.sketch.zip](https://github.com/vmware/clarity/files/1540882/Clarity-Icons-Library-0.10.17.sketch.zip)

Download button on [https://vmware.github.io/clarity/get-started#designResources](https://vmware.github.io/clarity/get-started#designResources) needs to have version number updated to 0.10.17

I also noticed that [https://vmware.github.io/clarity/news](https://vmware.github.io/clarity/news) has the 0.10.0 version of the "Sketch Template" mentioned. This should be "Sketch Library" and be pointing to the 0.10.11 download instead. Not sure if I should make this a separate issue or not.
