### ISSUE TITLE
Portlet layout

### ISSUE THREAD

**Issue by msoni11** [vmware/clarity#1750]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Portlet view is missing from Clarity project. The example can be seen in Summary view in html5 client.

### Actual behavior
This is new feature request and can be seen in Summary view in html5 client. Here is the screenshot:
![screen shot 2017-12-06 at 12 20 25 pm](https://user-images.githubusercontent.com/1658096/33648441-e43974d4-da7f-11e7-820b-974da8fa7a2d.png)

**Comment by mathisscott** [comment]
@msoni11 
What would be the difference between this and [just using a grid](https://vmware.github.io/clarity/documentation/grid)? Is it just that you want cards to be able to collapse?

**Comment by msoni11** [comment]
@mathisscott It is actually card layout with collapse/expand.

**Comment by msoni11** [comment]
This is not a grid but kind of [stack view](https://vmware.github.io/clarity/documentation/stack-view)

**Comment by mathisscott** [comment]
@msoni11 
Drag-and-drop using cards is on our long-term roadmap. But the type of portlet view for which you are asking is not. There are teams in VMware working on a solution similar to what you are asking for here. Ping me on the Clarity Slack or email me and I will give you more info on that.

**Comment by SayakMukhopadhyay** [comment]
😮 The collapsible card thing is very interesting and can be a good alternative to the Accordion/expansion panel/whatever according to my previous enhancement request https://github.com/vmware/clarity/issues/1767
