### ISSUE TITLE
Refactor internal use of old popovers

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#1757]
Need to clean up uses of the old popover implementation and replace with updated version.

* [ ] Button Group Overflow
* [x] Datagrid Filters
* [x] Dropdowns
* [ ] Signposts
* [ ] Tooltips

**Comment by mathisscott** [comment]
@gnomeontherun 
What's up with this ticket?

**Comment by gnomeontherun** [comment]
This is a tracking ticket to remove the old popover implementation, which is used internally in the components listed above.

**Comment by adityarb88** [comment]
@gnomeontherun: The above components use the new popovers. Datagrid filters and button groups I believe use the old one

**Comment by gnomeontherun** [comment]
Then we can fix the description :)

**Comment by adityarb88** [comment]
done

**Comment by Wallabeng** [comment]
Is there any ETA for signposts to work with the smart popovers? As we currently need to fix it with z-index on the parent to overlay other content.

**Comment by poifir** [comment]
Any progress on any of the affected components? Can we expect something in the next release?

Cut off signposts are really an annoying issue ... would be great if we could get an ETA at least for them.

Thanks!

**Comment by twittwer** [comment]
Is there some progress regarding signposts? - Seems like the number of issues closed in favour of this is growing.

Used in datagrid it causes some really strange behaviour. In the last rows the table gets a scrollbar when opening the signpost and the user has to scroll to see the signpost content.

Thx

**Comment by gnomeontherun** [comment]
This ticket was generated before our strategy with Core was defined, where we had intended to bring the smart popovers into all of the Angular components. The problem is that the smart popovers need further refinement to work with signposts and tooltips, and our efforts with Clarity Core will address this problem more holistically. 

To that end, I'm going to close this issue as something we aren't going to complete because of concerns about duplicating efforts to do this in Clarity Angular and Clarity Core, as well as the concern about breaking changes that appear to be required to make it happen.

For those watching this issue, the solution for the cutoff type issues will be to use the Clarity Core implementations when they are available, or to use manual positioning settings to keep the popovers in view without clipping.

**Comment by twittwer** [comment]
@gnomeontherun Is there an issue to keep track and get notified when the cutoff type bugs (e.g. signposts) are solved with Clarity Core?

**Comment by mathisscott** [comment]
@twittwer 
They will be fixed when signposts are introduced in Clarity Core. There are dependencies we are working on now to get to signposts but right now signposts are blocked until the dependencies are completed.
