### ISSUE TITLE
Only Core Clarity Icons Available (Other Sets Not Working)

### ISSUE THREAD

**Issue by sathomas** [vmware/clarity#1758]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

- Include `clarity-icons.min.css` CSS file.
- Include `custom-elements.min.js` JavaScript file.
- Include `clarity-icons.min.js` JavaScript file.

> [...] `clarity-icons.min.js` loads not only the Clarity Icons Api, but also all icons sets.

### Actual behavior
Icons in sets other than "Core" are not available, and the `error-standard` icon is displayed instead.

### Reproduction of behavior
See [pen](https://codepen.io/sathomas/pen/EbBzGM).

### Environment details

* **Angular version:** N.A.

* **Clarity version:** clarity-icons@0.10.17

* **OS and version:** macOS 10.13.2

* **Browser:** Chrome 62, Firefox 57, Safari 11.0.2

**Comment by Shijir** [comment]
@sathomas that's very odd. In Plunkr, all shapes are loading just fine. https://plnkr.co/edit/HpjUYCMngZntYZwMKkfD?p=preview

I will investigate further...

**Comment by Shijir** [comment]
It's only reproducible in codepen for some reason. Also, in codepen, I can retrieve the shape, `pencil`, from the Api. https://codepen.io/anon/pen/aVezXq?editors=1111

**Comment by Shijir** [comment]
@sathomas okay figured out what's going on after trying it out in other online editors such as jsfiddle, jsbin, and plunkr. The reason that all shapes were not loading was that codepen loads 3rd party libraries at the end of `body` tag, not in the head. It should be easily fixable.

**Comment by mathisscott** [comment]
@Shijir 
Any update on this?

**Comment by Shijir** [comment]
@mathisscott I am still working on it. The issue turned out to require a more substantial work. I am about to push an update to the [PR](https://github.com/vmware/clarity/pull/1777) that addresses this issue.
