### ISSUE TITLE
Empty space between navigation groups.

### ISSUE THREAD

**Issue by mdmarkova** [vmware/clarity#1760]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X ] enhancement
```
### Expected behavior

I would like to remove the empty space which appears between the navigation groups.
### Actual behavior

Define 2 or more navigation groups. A lot of space appears between the groups.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://plnkr.co/edit/KjsI70oaBIJbeCmBI9do

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@mdmarkova: Our UX team recommends that you do not do that. The space is present so that the user can easily distinguish between two different nav groups. If you have to reduce the space, then you would have to add a custom style on your end which overrides the `margin-top` on 
`.sidenav .nav-group` to what you want it to be. Something like this: https://plnkr.co/edit/CCtDrSxzw2uZK0va29lm?p=preview

Let us know if that helps. Closing the issue based on this. Please feel free to reopen the issue if you have any more questions or feedback.

**Comment by mdmarkova** [comment]
Thanks a lot for the fast response. For now that helps.

**Comment by ickobombata** [comment]
Hello, can you please reconsider this issue.
I am attaching screenshots of how this looks from the UI perspective.

![_thumb_124152](https://user-images.githubusercontent.com/7595872/36527650-3349dc30-17bb-11e8-9638-8debe28550a4.png)
![_thumb_124153](https://user-images.githubusercontent.com/7595872/36527651-33675ad0-17bb-11e8-823e-8f624ef13db2.png)

**Comment by mathisscott** [comment]
Hi @ickobombata 
It looks like your product is using the sidenav component in an odd place.

https://vmware.github.io/clarity/documentation/v0.11/sidenav

The sidenav isn't intended to be replicated multiple times throughout the content area.

Your use case looks better suited to the tree view (https://vmware.github.io/clarity/documentation/v0.11/tree-view) or what we are calling "vertical tabs" (#452).

**Comment by ickobombata** [comment]
Hi @mathisscott 
We can try that out the result will be better and without empty space.

But I think that not all labels can be clickable in a tree view.
We need the top (roots of a tree view) to be also clickable that is why we choose the side nav.
And we are not replicating it multiple times, we only have one side nav with 2 sections inside.
Which we copied from the https://vmware.github.io/clarity/documentation/v0.11/sidenav .
We think that the empty space is huge, and we are looking for alternatives without css modifications.

Thanks,
Marti
