### ISSUE TITLE
Changing the sort order of a data grid by clicking on the data grid header

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#1761]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
I have a clarity data grid sorted by a column. I would like to have ability to change sort order when click anywhere on the column header, or at least when I click on the sort arrow. The enabling click on the header/arrow may be useful and more intuitive for the users.

### Actual behavior
 I have to click on the column's name to change the sort order.

### Environment details

* **Angular version: 4.x.x

* **Clarity version: 0.10.6

* **OS and version: Windows 

* **Browser: all

**Comment by youdz** [comment]
We can't make the whole column header trigger the sort, because it contains other clickable targets (like the filter toggle). But having the arrow itself toggle the sort is the intended behavior, this is an oversight on our part. Thanks for filing this.
