### ISSUE TITLE
Unselect All in the hide/show columns popup of the data grid component.

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#1762]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
I would like to have "Unselect All" in the hide/show columns popup of the data grid component.

### Actual behavior
There is only "Select All" in the hide/show columns popup of the data grid component.

### Reproduction of behavior
![image](https://user-images.githubusercontent.com/439779/33835364-e9f2d6c8-de8e-11e7-98cf-8d257c2e987f.png)

__
### Environment details

* **Angular version: 4.x.x

* **Clarity version:0.10.6

* **OS and version: Windows 

* **Browser: all

**Comment by adityarb88** [comment]
@dkanev: Sorry but I am not sure if I understand the use case for this. If you unselect all, then you only show one column (default) in the datagrid? 

It seems like you want to unselect all and then select the columns that you want to see (please correct me if I am wrong) but I believe that use case is rare and in this case it should be okay to use the checkbox to uncheck the columns one by one to display the ones you want, no?

cc: @reddolan for feedback.

**Comment by hippee-lee** [comment]
@dkanev - @adityarb88 is correct, there has to be at least one column showing as the default but we have no way to know which column is the default column.

**Comment by dkanev** [comment]
@adityarb88:  Yes, I want to unselect all and then select the columns that I want. My grid has a lot of columns and in some case unselect one by one columns can be tedious

**Comment by hippee-lee** [comment]
@dkanev in that case I would suggest starting out with only a few columns visible which you can do that like this

```
<clr-dg-column>
    <ng-container *clrDgHideableColumn="{hidden: false}">ID</ng-container>
</clr-dg-column>
<clr-dg-column>
    <ng-container *clrDgHideableColumn="{hidden: true}">First Name</ng-container>
</clr-dg-column>
<clr-dg-column>
    <ng-container *clrDgHideableColumn="{hidden: true}">Last Name</ng-container>
</clr-dg-column>
<clr-dg-column>
    <ng-container *clrDgHideableColumn="{hidden: true}">Report Name</ng-container>
</clr-dg-column>
<clr-dg-column>
    <ng-container *clrDgHideableColumn="{hidden: true}">Description</ng-container>
</clr-dg-column>
<clr-dg-column>
    <ng-container *clrDgHideableColumn="{hidden: true}">Tool Name</ng-container>
</clr-dg-column>
<clr-dg-column>
    <ng-container *clrDgHideableColumn="{hidden: false}">Technical Name</ng-container>
</clr-dg-column>
```
