### ISSUE TITLE
nav box-shadow should be black in dark theme

### ISSUE THREAD

**Issue by elesueur** [vmware/clarity#1763]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
When the dark theme is applied, the horizontal nav tabs should have a black border along the bottom:

![screen shot 2017-12-11 at 12 16 36 pm](https://user-images.githubusercontent.com/8139865/33844062-2885fe5a-de6d-11e7-8e55-35abbfd7aba8.png)

### Actual behavior
box-shadow with #ccc gives a border color that looks white:

![screen shot 2017-12-11 at 12 15 53 pm](https://user-images.githubusercontent.com/8139865/33844026-0e41ec52-de6d-11e7-954e-4f99e5bf6446.png)

### Reproduction of behavior

use the nav tabs component

### Environment details

* **Angular version:** 4.3.x

* **Clarity version:** 0.10.16

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by lil-kim** [comment]
Hi Scott,
Please hold off on this change until I do a design review. I want to make sure whatever color is chosen works across all screens.

**Comment by lil-kim** [comment]
@mathisscott 
Design review completed and approved. For the not-active tab, please change the bottom 1 px color to: #485764

It should look like this:
![image](https://user-images.githubusercontent.com/23196444/34063221-82f86108-e1a5-11e7-91a8-0d80a2dc4ca6.png)
