### ISSUE TITLE
Extend Stack View to allow any content within it

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1767]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[X] enhancement
```

### Expected behavior
Currently the Stack View component shows only key-value pair in parent as well as child as mentioned in the documents. I was wondering if it was feasible to extend it or maybe have a new component which allows any content withing a child. This emulates Expansion Panel of Angular Material https://material.angular.io/components/expansion/overview . 

### Actual behavior
Actual behavior of stack view is as mentioned in the documents https://vmware.github.io/clarity/documentation/stack-view . Attempt to put other custom components as a sub content has given unintended results.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.17

* **OS and version:** Win 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
We've had that request a couple times. Sometimes it's called "collapsible panels", sometimes "accordion", ...

Anyway, we have an issue open for it here: https://github.com/vmware/clarity/issues/250
I don't believe we have a design for it yet, and it's not a priority at the moment. But this could be a good candidate for external contributions, both for design and implementation.

**Comment by SayakMukhopadhyay** [comment]
Thanks for the issue link! Like you its difficult to search if the term in not fixed. I will subscribe to that issue.
