### ISSUE TITLE
How add Wrapper for nav in clr-tabs

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#1768]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Actual behavior
I need wrapper for `<ul class="nav" role="tablist">`

how replace template for clr-tabs?

example `<div class="container"><ul class="nav" role="tablist"></div>
            
            <ng-container *ngFor="let link of tabLinkDirectives">`

![img-2017-12-12-15-04-24](https://user-images.githubusercontent.com/580273/33883699-d6a2a048-df4d-11e7-9f1e-039b3da2693a.png)

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.*

* **OS and version:** 

* **Browser:** [all]

**Comment by mathisscott** [comment]
Hi @KANekT 
I'm not sure I understand the request. Could you [try creating a plunkr for it](https://plnkr.co/edit/uNwwZe)?

Maybe if we could see what you were trying to do we would be able to better advise you.

**Comment by mathisscott** [comment]
Hi @KANekT 
Your plunkr isn't working. If you could get it working, we may be able to take a look.

Thanks.
