### ISSUE TITLE
Note version for Bootstrap dependency on website

### ISSUE THREAD

**Issue by dgrahn** [vmware/clarity#1769]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I should be able to import

```
@import "../node_modules/clarity-ui/src/utils/dependencies.clarity";
```

### Actual behavior
After adding that line to the beginning of `styles.scss`, I get the following error.

```
      File to import not found or unreadable: node_modules/bootstrap/scss/normalize.
Parent style sheet: [project-path]/node_modules/clarity-ui/src/utils/_dependencies.clarity.scss
      in [project-path]\node_modules\clarity-ui\src\utils\_dependencies.clarity.scss (line 11, column 1)
```

I have included `bootstrap 4.0.0-alpha.5` in my `package.json`, that is the current version which is listed in the clarity code.

### Reproduction of behavior
I'm not sure how to use Plunker to reproduce this since it's a compilation error.

### Environment details

* **Angular version:** 5.0.1

* **Clarity version:** 0.10.17

* **OS and version:** Windows 10

* **Browser:** n/a

**Comment by hippee-lee** [comment]
Hi @dgrahn can you share your project on github (or a stripped down version of it with the issue so I can take a look at it?

**Comment by dgrahn** [comment]
https://github.com/dgrahn/clarity-seed

This should do it.

**Comment by dgrahn** [comment]
This should do it.

https://github.com/dgrahn/clarity-seed

**Comment by hippee-lee** [comment]
It looks like you are trying to create a custom theme, right?

Looking at the seed code in the repo the first issue I see is that the dependencies file is imported into the `app.componment.scss` file. That's incorrect. 

Did you follow the steps outlined [here](https://vmware.github.io/clarity/documentation/themes) for Custom Themes that start from either the light or the dark theme?

**Comment by dgrahn** [comment]
I did follow that. Sorry about the `app.component.scss`. That's not what actually happens in my app. But I do get the same error. I just forked the seed, and modified the `package.json` and the first sass file I found to demonstrate the exception.

**Comment by hippee-lee** [comment]
Ok. I'm happy to help but It's difficult without a way to reproduce the error. 

When I made the variable changes and added the dark theme I tested them on the `clarity-seed` and used that to write the steps for Custom Themes.

**Comment by dgrahn** [comment]
Try doing `npm install` and then `npm start` on the app. That should reproduce.

**Comment by dgrahn** [comment]
Also, is there a `_theme.light.clarity.scss`?

**Comment by hippee-lee** [comment]
Dev note to self, I need to re-run through the instructions for Custom Themes to determine if there is an issue with the steps outlined for adding a custom theme to the `clarity-seed`.

**Comment by dgrahn** [comment]
Do note that I changed the `package.json`. I think there's something wrong with that which is downloading the wrong bootstrap version. But I don't know what! When it downloads the bootstrap, it doesn't contain normalize.

**Comment by hippee-lee** [comment]
I ran through the instructions [here](https://vmware.github.io/clarity/documentation/themes) with the Clarity seed app and didn't run into any issues setting it up for theming. 

I'm trying to better understand your issue since I am unable to recreate it.  Are you 

1. trying to create a custom Clarity theme?
2. trying to use Clarity variables in your application component SCSS files?
3. Somethign else? 

Any help you can give that makes it easy for me to recreate your issue will help me help you.

**Comment by dgrahn** [comment]
Trying to create a custom theme. Did you use my `package.json`? When I do that bootstrap is missing `_normalize.scss`.

I started looking into this on the [bootstrap repository](https://github.com/twbs/bootstrap). It appears that they have removed `_normalize.scss` from distribution. The last version tag I can find that has `_normalize.scss` is v4.0.0-alpha.6, making the first version without it v4.0.0-beta.

My `package.json` adds `^v4.0.0-alpha.5`. 

We can go ahead and close this, but I'd suggest adding a note on the website that theming depends on that version of bootstrap for those who didn't start with the seed.

Thanks hippee!

**Comment by hippee-lee** [comment]
Thanks for following up @dgrahn. 
It sounds like you got it working. 
Feel free to revisit this issue if you have more issues.
