### ISSUE TITLE
[WEB] Card header title is not listed on Typography dox page

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#177]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[X] enhancement
```

Card header titles are H4s. They should be listed in the Headers table on the dox page under H4s.

* **Clarity version:** 0.7.3

**Comment by jaffoneh** [comment]
@mathisscott could you provide a little more info here? Do you mean listing them in the "Used for" section in the header styles table on https://vmware.github.io/clarity/documentation/typography? Not sure what this issue is trying to report or is it required. Thanks.

**Comment by mathisscott** [comment]
Yep. We need to list that card header titles are H4s in the Header table on the typography page of the website. Like the note says: "Headers table on the dox page". Sorry that the wording was not clear.

**Comment by jaffoneh** [comment]
@mathisscott cool, thanks for clarifying.

**Comment by jaffoneh** [comment]
@adityarb88 as a quick change to the website, adding it to 0.7.4.

**Comment by adityarb88** [comment]
Merged to master.
