### ISSUE TITLE
Nav headers are not hidden when vertical nav is collapsed

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1774]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
https://plnkr.co/edit/tuZ3jzLe5oAyP7exBgMO?p=preview

### Actual behavior
https://plnkr.co/edit/si6V24QOFvDn2ivznmGL?p=preview

### Reproduction of behavior
See above...

**Comment by adityarb88** [comment]
@mathisscott, @rameshyala: I don't believe this is a bug. Vertical Navigation wasn't designed or implemented to support this use case. More details about the cases we support: https://github.com/vmware/clarity/issues/1001. This nav should actually look like this: https://plnkr.co/edit/FCds44XjRRowQId3wXps?p=preview

@reddolan Please correct me if I am wrong or if I am missing something.

But if we do want to support this, we could add this as an enhancement.

**Comment by mathisscott** [comment]
Per UX, we aren't supporting the sidenav headers in vertical nav. See @adityarb88's comment above for more details.
