### ISSUE TITLE
Allow Usage of Toggle switch in Datagrid Without Increasing Row Height

### ISSUE THREAD

**Issue by dgrahn** [vmware/clarity#1775]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Toggle switches should be able to be placed in a datagrid without increasing the height of the row.

### Actual behavior
Adding a toggle switch to a datagrid cell causes the row to grow in height.

### Reproduction of behavior
https://embed.plnkr.co/ZkJXbS/

**Comment by Jinnie** [comment]
With this bug we assume that the user wants rows with 1 line of text and he wants the toggle not to change the line height.
But if we do this fix, we may easily break other cases. One that comes to my mind is this - the user wants a larger control, with several toggles, in one cell. Here is what happens:
https://stackblitz.com/edit/clarity-toggle-in-a-datagrid?file=src%2Fapp%2Fapp.component.html
I think that it is use case specific and it's perfectly okay that the style of the toggle is defined by the user. We should not introduce style exceptions in any of our components, based on assumptions how they may be used.

**Comment by gnomeontherun** [comment]
This actually need to be reviewed with new toggle switches, which are a little bit different and might actually fit (haven't tested this). However, we do sometimes support things like this, because the height of a row is meant to be consistent.
