### ISSUE TITLE
Allow labels after toggles?

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#1778]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Proposed enhancement 
Currently Clarity [toggles](https://vmware.github.io/clarity/documentation/toggle-switches) have a label before the toggle (or no labels).  However, there's some cases where a label on the right side might make sense -- for example a left aligned control outside of a form group.  This screenshot shows how this looks with the label on the left.  

![image](https://user-images.githubusercontent.com/7132414/33964066-090d4c18-e00c-11e7-8e81-d9dc682d390e.png)

Would labels on the right be consistent with the style guidelines, and if so, could it be enabled?  

This currently has a hacky workaround -- leaving a blank label and following the toggle with a span causes the text to be misaligned, but setting the label to `&nbsp;` aligns the span text correctly (at the cost of a small space in front of the toggle) as shown in the screen shot below.  

![image](https://user-images.githubusercontent.com/7132414/33964345-f8cc4178-e00c-11e7-822e-31dc12f01817.png)

### Reproduction of behavior
(Labels can be seen in documentation)

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.9.x

* **OS and version:** all

* **Browser:** all

**Comment by mathisscott** [comment]
I think this is a reasonable request. We should allow for a CSS class on the `.toggle-switch` element that places the `label` to the right of the toggle switch.

**Comment by dgrahn** [comment]
I've been looking for an easy project to get started contributing. This looks like it might be a good one. I'll work on this and touch base when I have something.
