### ISSUE TITLE
Card Subheader

### ISSUE THREAD

**Issue by dgrahn** [vmware/clarity#1782]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Card should have a subheader.

### Actual behavior
Card does not have a subheader.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-card-subheader-enhancement

### Environment details

* **Clarity version:** 0.10.17

**Comment by gnomeontherun** [comment]
I think this is a meaningful idea, though we need to clear the specific design with UX. There is a workaround to style it yourself.

**Comment by hippee-lee** [comment]
I updated this issue with a stackblitz that used the original plunkr example.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
