### ISSUE TITLE
Web site fails to load under IE 11

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#1784]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
[Presentation1.pptx](https://github.com/vmware/clarity/files/1561273/Presentation1.pptx)

```

### Expected behavior
Web page successfully loads in IE 11.

### Actual behavior
Web page displays 'Loading...' message and halts (See enclosed screenshot).  Under Developer Tools --> Console the message 'webpackJsonp is undefined' is displayed. 

Additional info: 
-  I have already uncommented the requisite lines in the polyfills.ts file to support IE 11. 
-  The web app was compiled using the 'ng build --prod --aot ' command. 
- The web app is residing on a Windows Server 2016, IIS 10 site with Windows authentication enabled. 
- The web app runs fine on IE locally but fails when hitting the webserver site
- The web app runs fine under Chrome (v63) and Firefox Quantum

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**
.10.17
* **OS and version:** 
Windows 7
* **Browser:**  IE 11.0.9600.18837

**Comment by mathisscott** [comment]
@gnomeontherun @hippee-lee 
I've verified that this is an issue on the [kitchen sink app](http://clarity-ks.surge.sh/). Can one of you take a look? It appears to me like there might be an issue in some date/time code inside Angular. I don't know what the issue with the iterable in the polyfill is. It may be an Icons issue. Or something else in Angular...

Screenshots attached...

![screen shot 2017-12-18 at 8 45 54 am](https://user-images.githubusercontent.com/2728359/34111813-63ba4e00-e3d0-11e7-84f0-0a2757a79ae8.png)
![screen shot 2017-12-18 at 8 46 05 am](https://user-images.githubusercontent.com/2728359/34111814-63d92f96-e3d0-11e7-8da8-5ab62c1f2501.png)
![screen shot 2017-12-18 at 8 46 51 am](https://user-images.githubusercontent.com/2728359/34111815-63fb2a10-e3d0-11e7-9a0b-4b3b9c3c1fc0.png)
![screen shot 2017-12-18 at 8 47 02 am](https://user-images.githubusercontent.com/2728359/34111817-64157226-e3d0-11e7-8b1b-553b8ef57086.png)

**Comment by Shijir** [comment]
@mathisscott Those issues might be mitigated if we enable ES6/ES7 polyfills in `polyfills.ts` file in our kitchen sink app.

**Comment by mathisscott** [comment]
@hippee-lee : Could you verify if what @Shijir is saying is the case sometime this week?

**Comment by hippee-lee** [comment]
Confirmed, the ks-app wasn't using the es6 polyfills required for IE11.
