### ISSUE TITLE
feature request: clarity icon for Bluetooth

### ISSUE THREAD

**Issue by HansS** [vmware/clarity#1786]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Thanks for the request, @HansS !

We'll add it to the icons volume 10 epic.

**Comment by lil-kim** [comment]
Completed as part of Epic #1787
