### ISSUE TITLE
Icons vol. 10

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#1787]

**Comment by reddolan** [comment]
a couple more to add to the vol.
- filter icon: like iOS and Google now use (similar to the new Sort icon)
  - also with possible active state
- drag icon: from the new Drag'n Drop work

**Comment by reddolan** [comment]
A couple more requests. CSP uses these as switchers for light/dark theme
- sun
- moon

**Comment by jacobbutton** [comment]
Any chance we could get a briefcase icon?

**Comment by lil-kim** [comment]
I've attached the final svg files for Data visualization icons #1867 here:
[dataviz chart icons.zip](https://github.com/vmware/clarity/files/1704918/dataviz.chart.icons.zip)
@Shijir chart_pie_solid has an error in the svg code.

**Comment by martijnmelchers** [comment]
@lil-kim I like the 2nd one!

**Comment by lil-kim** [comment]
@Shijir 
Icons are ready tp be published. Here are the two zip files containing all icons for Volume 10:

[dataviz chart icons.zip](https://github.com/vmware/clarity/files/1704918/dataviz.chart.icons.zip)
[vol 10 svg.zip](https://github.com/vmware/clarity/files/1725253/vol.10.svg.zip)

(The dataviz chart icons are the same I attached on Feb 8. These were an external contribution and should be tested. )
