### ISSUE TITLE
[data-grid] switch between (singleSelected / batch / no column) after grid initialization

### ISSUE THREAD

**Issue by spetri** [vmware/clarity#1790]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Should be able to switch between checkboxes / radio buttons / empty column by updating some @Input.

### Actual behavior
It'd be great to be able to switch between states (singleSelect, batchAction, no column) after the datagrid has been initialized. As of now, every time there is an Input, it sets a selection type every time (same as when setting the `clrDgSelected`).

### Environment details

* **Angular version:** 5.1.1

* **Clarity version:** 0.10.18

* **OS and version:** Mac OSX Latest

* **Browser:** [all]

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
