### ISSUE TITLE
Dark Theme: loading state backdrop color doesn't match dark colors palette

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1795]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

![screen shot 2017-12-20 at 10 16 07 am](https://user-images.githubusercontent.com/433692/34216873-783a8a0e-e55e-11e7-912b-92726a08fa56.png)

### Suggested behavior
The suggestion color is to use `rgba(24,24,24,0.5); ` @lil-kim does this meet our accesability standard? 
![screen shot 2017-12-20 at 10 17 43 am](https://user-images.githubusercontent.com/433692/34216937-b2f9c83a-e55e-11e7-89ac-c0d904e17e75.png)

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** @latest

* **OS and version:** All

* **Browser:** [all]

**Comment by lil-kim** [comment]
Hi @hippee-lee ,
For consistency, can we use the same backdrop we have when the wizard pops up?
It's rgba 0, 0, 0, 0.85.
re: accessibility, it's only really required for text (at least, to my knowledge). This is a large graphic so it shouldn't be an issue.

**Comment by elesueur** [comment]
@lil-kim  it's pretty dark...
![screen shot 2017-12-20 at 12 23 02 pm](https://user-images.githubusercontent.com/8139865/34219880-a0440daa-e580-11e7-9287-4caaea14c374.png)

**Comment by lil-kim** [comment]
@elesueur Can you try 0, 0, 0 at 50%?

**Comment by elesueur** [comment]
@lil-kim 0.5 looks OK...

![screen shot 2017-12-20 at 12 31 14 pm](https://user-images.githubusercontent.com/8139865/34220191-b8ed4f8c-e581-11e7-940b-cbb07eb843db.png)

regarding accessibility, I think @hippee-lee is more talking about the ability to read the text underneath the backdrop, i.e. column headers... personally, I don't think it's that important, the whole point of the backdrop is to obscure the text a little bit.

**Comment by lil-kim** [comment]
LGTM. I agree the text doesn't have to - actually can't - be accessible for this to look like a background overlay.

**Comment by hippee-lee** [comment]
Sounds like we are going with `0, 0, 0 at 50%` for the datagrid loading color. 
Thank you both.
