### ISSUE TITLE
cirModalClosable ill-behaved on iPad

### ISSUE THREAD

**Issue by RobPatten** [vmware/clarity#180]
**Select one ...**  (check one with "x")
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When viewing in Chrome or Safari on an iPad, the dialog for the cirModalClosable example should display centered within the viewport. It should also not allow scrolling of the content behind the modal.
### Actual behavior

There is a noticeable lag (on iOS, but not Windows) after touching the SHOW MODAL button. Button changes color on touch, but the modal is not displayed within view. If you scroll up (which is odd, because the modal should retain focus), the modal and backdrop are drawn. User is still able to scroll behind the modal. 
After dismissal, some of the backdrop sometimes stays behind.
cirModalClosable behaves well on Android (Nexus 6, 5.1.1) and Windows mobile. 
cirModalClosable is better behaved in Chrome  an iPhone 7 plus (10.0.2), but not so much in landscape.

### Reproduction of behavior

Within Chrome or Safari on an iPad, navigate to https://vmware.github.io/clarity/documentation/modals
Scroll to cirModalClosable example.
Push Show Modal.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
0.7.3

* **OS and version:** 
10.1.1 (iPad); 10.0.2 (iPhone 7+); Android 5.1.1
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@adityarb88 can we replicate this and figure out if it is a website issue vs. an issue with modals themselves? If you have any questions when it comes to replicating this please reach out to @RobPatten

**Comment by adityarb88** [comment]
@RobPatten: Do you still see this issue? We fixed an issue 3 days back with the website and Modals and I suspect that was causing this too. Could you please check again and let me know? I am not able to replicate it on my side.

**Comment by RobPatten** [comment]
@adityarb88 Yes, still seeing on 0.7.3 this morning. Tried it on a third browser (SavySoda) as well.
Git doesn't support .mov for upload, so am Slacking this to you.

**Comment by adityarb88** [comment]
This is blocked. I tried to debug this yesterday but couldn't find a solution. I believe [this](http://stackoverflow.com/a/25014586/3538394) is the only known solution but it doesn't work in our case. Just noting this down here so that its not assigned to any milestone yet. Will continue looking for a solution.

**Comment by mathisscott** [comment]
Need to investigate if this is still an issue. Currently we see it with all modals on a phone.

**Comment by gnomeontherun** [comment]
There appears to be two issues with this currently. First, there is actually a bug in webkit that we suffer from here.

https://github.com/twbs/bootstrap/issues/22311
https://bugs.webkit.org/show_bug.cgi?id=153852

From preliminary research, it should be workable with Chrome (mostly) but might need some changes https://bugs.chromium.org/p/chromium/issues/detail?id=175502.

Second issue is that at least on our docs that the modal overlay is not overlaying the whole page, just the content area.

**Comment by gnomeontherun** [comment]
This bug seems to be alright in latest testing. I'm going to close this as out of date.
