### ISSUE TITLE
Data Grid Height for Single Row

### ISSUE THREAD

**Issue by dgrahn** [vmware/clarity#1800]
```
[x] clarification
```

I've marked this as a clarification because I don't think it's a bug. Perhaps the documentation should be updated to explain this?

### Expected behavior
When there is only one row in a data grid, the data grid should collapse to fit the single row.

### Actual behavior
When there is only one row in a data grid, the data grid has room for two rows.

### Reproduction of behavior
https://embed.plnkr.co/B2VqTr/

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.10.17

**Comment by hippee-lee** [comment]
Hi @dgrahn. There has been some discussion about this in the past, [here](https://github.com/vmware/clarity/issues/1010#issuecomment-305877745) and [here](https://github.com/vmware/clarity/issues/1114#issuecomment-311417716) are two places with some of those details.

I'm closing this issue based on the previous issues.
