### ISSUE TITLE
Need powerful Expandable datatable.

### ISSUE THREAD

**Issue by nsksaisaravana** [vmware/clarity#1802]
Expandable datatable is a basic one, please check the Angular JS UI-GRID, the grid is very powerful. I am missing such a powerful grid in Angular. 
http://ui-grid.info/

**Comment by SayakMukhopadhyay** [comment]
I think the [Datagrid](https://vmware.github.io/clarity/documentation/datagrid/structure) component has a lot of useful features that you are looking for. I don't know if it is exhaustive or not but I use it in production and it is an absolute beast, and a joy to work with.

**Comment by nsksaisaravana** [comment]
You are absolutely correct for a datagrid but for an expandable grid, the features are not up to UI-GRID. Please browse the URL and check for the expandable grid.

http://ui-grid.info/docs/#!/tutorial/216_expandable_grid

**Comment by SayakMukhopadhyay** [comment]
The demo tutorial is not working for me ☹️ . I might be misunderstanding your requirement but Datagrid has an [expandable row](https://vmware.github.io/clarity/documentation/datagrid/expandable-rows) feature. Is it not what you are looking for?

**Comment by mathisscott** [comment]
@nsksaisaravana 
Based on my investigation of the provided link, it appears you want nested datagrids?

[This plunkr](https://plnkr.co/edit/6ndoSe?p=preview) shows how that can be done.
