### ISSUE TITLE
Datagrid throws ExpressionChangedAfterItHasBeenCheckedError 

### ISSUE THREAD

**Issue by JelenaRasic** [vmware/clarity#1806]
[x ] bug
[ ] feature request
[ ] enhancement

clr-tooltip in clr-dg-cell thors the ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'top-right'.
Tooltip wraps a clr-icon which has click event (it opens clr-modal)

### Expected behavior
Open modal, do whatever needs to be done in it, close modal

### Actual behavior
When modal closes the error appears and the tooltip content appears on the top left corner of the screen until I click anywhere on the screen.

### Reproduction of behavior
I cannot reproduce it on Plunker

### Environment details

* **Angular version:** 4.4.6

* **Clarity version:** 0.10.18

* **OS and version:* Linux mint 18.2

* **Browser:** Chrome Version 63.0.3239.108 (Official Build) (64-bit)

**Comment by mathisscott** [comment]
Without [a plunkr](https://plnkr.co/edit/uNwwZe), I don't know how effectively we can triage this issue. If it cannot be reproduced in a plunkr, it is likely an application issue.

**Comment by JelenaRasic** [comment]
Here is a link on Plunker, https://plnkr.co/edit/bpx0l3YB87f25QSkfRYy?p=preview

It doesn't throw the error but in my project, I get the error when I close the modal

**Comment by mathisscott** [comment]
Hmm. That's odd. You might want to compare the code in your application against the working code in the plunkr. This looks like an application issue.
