### ISSUE TITLE
Add Option for Datagrid Row to Expand when Row is Clicked

### ISSUE THREAD

**Issue by dgrahn** [vmware/clarity#1807]
**Select one ...**  (check one with "x")
```
[x] enhancement
```

### Expected behavior
Currently the only way to expand a datagrid row is to click the caret. It would be nice to have the option for the row to expand when any part of the row is clicked.

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.10.18

* **OS and version:** all

* **Browser:** all

**Comment by mathisscott** [comment]
The problem with making a click on a data grid row also expand the row is that you could therefore not place any other clickable elements inside the row. This means a data grid that was wired up like this could not have buttons, drop downs, hyperlinks, tooltips, or any other clickable element inside of it.

Additionally, you couldn't place such content inside the expanded content.

Links within buttons and buttons within buttons are against web standards. This is why we don't do this. I don't think that is going to change.

**Comment by dgrahn** [comment]
I'm not sure why it would prevent placing links or buttons inside of the details, but that would be the tradeoff. I feel like this would be valuable when you want the default action of the row to be opening the details.
