### ISSUE TITLE
Add version info for Icons

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#1808]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
We should track the version that icons are added to the overall sets so we can display details about when they were added. It will also help if someone is trying to figure out if an icon is available for them (if they are on an old release for example). We can add a filter to display icons available in a particular release.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by reddolan** [comment]
Was this something you were thinking would be added to the dox on the site?

**Comment by reddolan** [comment]
Similar to how FontAwesome is doing it?
![image](https://user-images.githubusercontent.com/1858226/37932422-54c1da6a-30fd-11e8-9ff8-1748f0647fed.png)

**Comment by gnomeontherun** [comment]
Yes, some kind of indicator so people can know that they might have to upgrade to get a particular icon (and we'd probably want to have a filter by version as well).

**Comment by colinreedmiller** [comment]
Using this issue as an opportunity to address https://github.com/vmware/clarity/issues/2139

**Comment by colinreedmiller** [comment]
Prototype:

https://www.figma.com/proto/EX5MGPr9BNa48gS1ZCRDEm/Add-version-info-for-Icons-1808?node-id=9%3A392&viewport=-1074%2C-985%2C2&scaling=min-zoom
