### ISSUE TITLE
[UI] Buttons by default should not have margins

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#181]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Buttons should be assigned margins for specific context (for eg: in forms or modals footers). In general you should be able to use buttons inline without any margins.

### Actual behavior

All Buttons have margin around them irrespective of the context.

![image](https://cloud.githubusercontent.com/assets/1426805/20853720/c9c38c7a-b8a2-11e6-8ac6-b3e4ea1ab258.png)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** all

* **OS and version:** all

* **Browser:** [all]

**Comment by EileenLB** [comment]
I'm interested in knowing if you make this change.
Currently I'm allowing for the default margins in the vertical spacing for my Page layouts.

![verticalspacing-with-btn-margins](https://cloud.githubusercontent.com/assets/14795506/20854479/4b27f6ba-b8a9-11e6-9688-95bd35fdbf61.png)

**Comment by adityarb88** [comment]
Hi @EileenLB. Yes I am planning on making this change because having default margins for buttons cause alignment issues when you want to use them inline with other components.

On a different note - in your screenshot above I noticed the comment that `Clarity Headers have no default margins`. That is incorrect because Clarity Headers do have a default top margin but in the example mentioned above, I am assuming that since the header appears first in the `.content-area`, its margin is being overridden to 0 to account for the top-padding on the `.content-area`

**Comment by jaffoneh** [comment]
@adityarb88 how does this change affect products already using Clarity? Is this a 0.8.0 change?

**Comment by adityarb88** [comment]
Yes. I think this should be a 0.8.0 change. Even though the change is simple, it might end up causing alignment issues in case users have used buttons in components other than forms, modals etc

**Comment by jaffoneh** [comment]
@adityarb88 we might need to think of ways to make sure this doesn't effect currently implementations of Clarity in dozens of products. Let's talk about ways to make sure even when this lands in 0.8.0, it doesn't effect current products.

**Comment by adityarb88** [comment]
This issue is on hold. @mathisscott and I discussed about this and we want to gather more info before we decide on whether to implement this change or not.

**Comment by colinreedmiller** [comment]
WCAG 2.1 has us considering cases where we might force 44px touch targets for any actionable element. Themeable button margins would seem a solution that addresses the bug above while also allowing for AAA compliance. Though technically a AAA requirement, this is a strong recommendation for AA.

https://www.w3.org/WAI/WCAG21/quickref/#target-size

@sheribyrne
@mathisscott

**Comment by coryrylan** [comment]
I have followed this technique with good success, maybe something to consider. This helps create vertical rhythm pretty easily and consistently  https://csswizardry.com/2012/06/single-direction-margin-declarations/

**Comment by coryrylan** [comment]
Should block until these two issues are resolved to prevent future visual breaking changes.

Design Space Tokens spec WIP: https://github.com/vmware/clarity/issues/3303
Clarity Core implementation: https://github.com/vmware/clarity/issues/4061

**Comment by mathisscott** [comment]
The direction we go in #3303 and #4061 will ultimately address this issue. I'm going to close it as a duplicate for that reason.
