### ISSUE TITLE
Feature Request: Replay Icons

### ISSUE THREAD

**Issue by martijnmelchers** [vmware/clarity#1811]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

That there are replay icons in the Media section. Preferably two: repeat all and repeat one (so the repeat-all one with a one). This could be a great addition since that's the only one missing from the media section

**Comment by Shijir** [comment]
@martijnmelchers thanks for the suggestions. @lil-kim can we address this in our Vol. 10 icons?

**Comment by lil-kim** [comment]
Completed as part of Epic #1787
