### ISSUE TITLE
Tooltip validation doesn't work with textarea

### ISSUE THREAD

**Issue by colinskow** [vmware/clarity#1812]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Tooltip validation should work on textarea elements just as it does on other inputs

### Actual behavior
Textarea elements render incorrectly when wrapped by a label tag

### Reproduction of behavior
https://plnkr.co/edit/x7NRmzBdpEiuNqI89R6c?p=preview

### Environment details

* **Angular version:** 4.x.x & 5.x.x

* **Clarity version:** 0.10.19

**Comment by Shijir** [comment]
Our tooltip validation doesn't support textarea elements right now. We are currently researching to improve our form validations generally. You can track the progress in https://github.com/vmware/clarity/issues/1118. @reddolan please weigh in your thoughts on this issue.

**Comment by colinskow** [comment]
Supporting select elements would also be great!

**Comment by adityarb88** [comment]
@colinskow: We already have the designs ready for this but the implementation hasn't been done yet. Please subscribe to the below issues for more updates.

Text area - https://github.com/vmware/clarity/issues/45
Select Boxes - https://github.com/vmware/clarity/issues/46

Closing this issue as a duplicate.
