### ISSUE TITLE
Opening wizard without using modal

### ISSUE THREAD

**Issue by inms-adarsh** [vmware/clarity#1813]
Hi,

I want to create wizard in the same window(I don't require to open it in Modal). How it can be possible in Clarity?

**Comment by hippee-lee** [comment]
Hi @inms-adarsh take a look at the inline wizard here: https://github.com/vmware/clarity/blob/master/src/app/wizard/wizard-inline.demo.html

Will that help you?

**Comment by adityarb88** [comment]
@inms-adarsh: @hippee-lee is right. Please take a look at the inline wizards demo that @hippee-lee linked above for more information. I would also recommend reading this thread before using inline wizards: https://github.com/vmware/clarity/issues/1704#issuecomment-346386242

Closing this issue based on the above info. Please feel free to reopen the issue if you have more questions/feedback.
