### ISSUE TITLE
[WEB] Add demo and docs for right labeled toggle switch

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1815]
```
[ ] bug
[ ] feature request
[x] enhancement
```

Right labeled toggle switch was added here: #1805 

### Website needs the following
- [ ] Right labeled toggle demo w/ code
- [ ] Added documentation on the feature

### Clarity UI needs the following:
- [ ] CSS Regression Tests for Right labeled toggle

**Comment by gnomeontherun** [comment]
We've redone toggles and this no longer applies I believe.
