### ISSUE TITLE
Typography Positioning

### ISSUE THREAD

**Issue by spetri** [vmware/clarity#1816]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
For most (if not all) of the headers and typography styles, there is (significant) margin and positioning included. The problem is that, I want to be able to position the text without needing to write `margin: 0;` on all our headers / text as a default. I would expect each typography to have just text styling (such as `font-size`, `color`, `font-weight`, etc.) and not positioning.

### Actual behavior

Example of `h6`:
```
h6 {
	font-family: Metropolis,Avenir Next,Helvetica Neue,Arial,sans-serif; // Expected
    font-size: .58333rem; // Expected
    letter-spacing: normal; // Expected
    line-height: 1rem; // Expected
    margin-top: 1rem; // Not Expected
    margin-bottom: 0; // Not Expected
}
```

### Environment details

* **Angular version:** Latest

* **Clarity version:** Latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@spetri: Margins are added to most of the headers and paragraphs so that our users don't have to worry about vertical rhythm (Clarity default is 24px). Our UX recommends that you have these margins to maintain vertical rhythm. We don't recommend that you override them but if you want to then the best way to do that would be to create a utility class which removes the margins on your end.

Please let me know if you have any other questions/feedback. Closing the issue based on this.

**Comment by spetri** [comment]
@adityarb88 I understand about vertical rhythm with Clarity default set at `24px`, but when it comes to text elements and other components, it really should be up to the user to decide what multiple of `24px` they would like to use for positioning and not need to override it every time.

With that said, our team will look into creating a utility class for the time being, thanks!

**Comment by adityarb88** [comment]
@spetri: Thanks for the feedback. Just to understand your point completely, Even if you were to decide what multiples of 24px you want to use for the headers or paragraphs, you would still have to create those utility classes for your app right? Browsers assign a default margin to the headers anyway. Our UX has overridden those browser defaults to follow the vertical rhythm. These values were tested in multiple components across Clarity. For users who do not want to deal with margins on their end, this approach becomes very easy to use as they dont have to do anything at their end but its still customizable for users who want to change these margins.

Am i missing something here?
