### ISSUE TITLE
Improve Code Highlights Documentation

### ISSUE THREAD

**Issue by aaronfrost** [vmware/clarity#1817]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior

When reading the documentation, it is so vague, I have no idea how to do what I need to do. I want to use the code-highlights to format and highlight some JSON. I have no idea how to do what I need to do. I guessed that I needed to npm install prismjs. The syntax highlighting is not working well here, though, and I am sure it's because I don't have something setup correctly. It is pretty vague, though. I don't really have any pointers to go off of.

**Comment by aaronfrost** [comment]
I have this same issue. I have JSON displaying... but there is not code highlighting happening. All the text is simply black. I have no idea how to get it to highlight color coding for the syntax. 

I would love some additional description of how to do this from an Angular app. If it's simple, and I am guessing it is, then we should add it to avoid confusion going forward.

**Comment by gnomeontherun** [comment]
We need to improve the documentation _and_ the implementation. However, this is an example of how to use it. Its kind of a wrapper type component that we don't really describe, and was originally built for our documentation without fully baking it. It really needs a good refactor to clean it up and make it more functional standalone. The main issue is that Prism often runs before Angular compiles the component, and thus you have to call the CodeHighlight.redraw() method to get Prism to run again to highlight the syntax. Let me know what questions you have and we can work on getting the docs updated.

https://stackblitz.com/edit/clarity-code-highlight

**Comment by mathisscott** [comment]
Per #98 , the code highlight component is targeted for removal from Clarity in 0.12.
