### ISSUE TITLE
[Docs] Documentation website references uncommitted files when run locally

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#1820]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Users wanting to contribute to the documentation should be able to check out `new-website` and run it locally with `ng serve`.

### Actual behavior
```
ERROR in /home/alex/Others/clarity/src/app/news/news-routing.module.ts (5,37): 
Cannot find module '../../releases/final-template/auto-generated-routes'.
```

### Reproduction of behavior
With a recent global angular-cli, clone to a new directory, checkout `new-website`, run `ng serve`.  

Should there be another setup step to generate this module prior to serving locally?  If so, it could be documented [here](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md#contributing-to-documentation).

**Comment by adityarb88** [comment]
@amellnik: We auto generate the release notes for our documentation. Before running `ng serve` you need to run the node script: https://github.com/vmware/clarity/blob/new-website/generate-template.js using `node generate-template.js`

This script generates the release notes.

You are right, we should document this. I will keep this issue open to get this resolved.
