### ISSUE TITLE
Reordering Datagrid rows (design spec)

### ISSUE THREAD

**Issue by gracesnoh** [vmware/clarity#1826]
### Description
Datagrid rows can be reordered by dragging anywhere inside of the row. This is not a default behavior for all datagrids.

![dox-basic](https://user-images.githubusercontent.com/8237984/34446765-b41589a8-ec92-11e7-8217-059369d4a3f0.gif)

### Usage
To change the order of datagrid items where the order determines an outcome. For example, ordering Wi-Fi networks that prioritizes networks starting from the top to the bottom.

Reordering datagrid rows cannot be enabled when filtering or sorting is applied to the datagrid. 

### Behavior
Datagrid rows have drag handles on the left edge and are represented by six-dot icons inside a 18x24 container. Handles serve as visual affordances for drag & drop. 
![dox-handle](https://user-images.githubusercontent.com/8237984/34446343-0b40ca16-ec8f-11e7-9239-9b5ffa59c664.png)
While handles act as visual indicators that drag and drop is an available action, the row is draggable from anywhere inside its container. All clickable elements inside of a datagrid row remain clickable but are also draggable.
![dox-clickable](https://user-images.githubusercontent.com/8237984/34446382-43f93f46-ec8f-11e7-9c28-5413c938197f.png)
When a datagrid item is dragged, a new “copy” containing only the first column cell will drag with the cursor. The original datagrid item is greyed out, indicating its previous position.
![dox-border](https://user-images.githubusercontent.com/8237984/34446391-5d3da53c-ec8f-11e7-82a4-effb39f0a420.png)
Only the first column cell is shown because dragging the entire datagrid row will be difficult for users to control, especially when horizontal scrolling is enabled in the datagrid.

When the midpoint of the dragged row “copy” enters the bottom or top half of another row, a drop target will be triggered in between the two rows. Drop targets do not appear in places that would result in dropping the row in its original position.
![dox-midpoint](https://user-images.githubusercontent.com/8237984/34446404-84ef17f0-ec8f-11e7-8da1-97ed95d68eaa.png)
When a row is dropped, the surrounding rows will shift away to make room for a new empty row, covering up the greyed out previous state of the dragged row. Then the dragged “copy” will move towards the empty row and fade out to opacity: 0. As soon as it fades, the new empty row will reveal the row’s contents, fading back to opacity: 1.

![dox-dropped-behavior](https://user-images.githubusercontent.com/8237984/34446790-e4df0aa0-ec92-11e7-89ac-7482fe9a39cd.gif)

> For datagrids with pagination, rows cannot be dragged to a different page. Rows can only be reordered among rows on the same page.

### Scrolling
When the datagrid is scrollable, dragging a row over the edge of the window will automatically scroll the datagrid to reveal more rows. The farther away from the datagrid the object is dragged, the faster it will scroll. Using a scroll wheel will also scroll the view and maintain the drag action.

![dox-scrolling](https://user-images.githubusercontent.com/8237984/34446811-24cba61e-ec93-11e7-89d9-d6f4547c535e.gif)

### Invalid drop
When a row is dragged outside of range (i.e. outside of the datagrid), the cursor will become disabled. If a row is dropped out of range or anywhere without a drop target, the dragged row will return to the row’s original position and fade to opacity: 0. 

The original row that was greyed out will change back to opacity: 1 once the dragged row returns to its original position.

![dox-invalid](https://user-images.githubusercontent.com/8237984/34446859-8da41afe-ec93-11e7-837e-cacef68fe08b.gif)

#### Single row action

![dox-single-row](https://user-images.githubusercontent.com/8237984/34446423-abebadd2-ec8f-11e7-966e-b85a92dfa44d.png)

#### Single row selection and action

![dox-single-selection](https://user-images.githubusercontent.com/8237984/34446453-f0ac8e5a-ec8f-11e7-83f5-7688cd1cec49.png)

#### Basic datagrid

![dox-basic-dg](https://user-images.githubusercontent.com/8237984/34446690-21fd5816-ec92-11e7-9fcb-9b8814cb1b1f.png)

#### Compact datagrid

![dox-compact](https://user-images.githubusercontent.com/8237984/34446951-604744e0-ec94-11e7-9d1a-a30e80257490.png)

### Keyboard accessibility
Users can drag and drop datagrid rows using keyboard controls. Tabbing to the row object and pressing space bar will activate drag and drop mode. 

Then users can use the arrow keys to move the drop target up and down. Pressing space bar again will confirm the action and drop the row in its new place.

![dox-a11y](https://user-images.githubusercontent.com/8237984/34446734-64b60090-ec92-11e7-99ca-162792eb5d89.png)

Related Issues: #620

**Comment by adestis-ds** [comment]
Would be really great to know when this can/will be implemented. Any ideas for a milestone?

**Comment by mathisscott** [comment]
@adestis-ds 
It's in progress now. So sooner instead of later. What is the timeline you're looking for? I can give you an idea of whether or not it's possible in that timeframe. But I can't give you an exact date when it will be done due to shifting priorities, normal dev cycles, etc.

**Comment by adestis-ds** [comment]
First half year 2018 would be great. However it would also be great to have it included in a roadmap to see what is your estimated timeframe. Would be good for product (feature) planning on our side. Also it would be great to have a list of (planned) components where users can easily vote. I found these design suggestions only by chance...

**Comment by mathisscott** [comment]
@adestis-ds 
We are experimenting with a roadmap internally with VMware. If you are with VMware, ping me on the VMware or Clarity Slack channel and I can share that with you. We want to run the experiment for at least a quarter though to see if it stays accurate.

**Comment by Shijir** [comment]
@pumano I am actively working on this feature. The ETA is around mid-July.

**Comment by pumano** [comment]
@Shijir sounds really good! Thanks for answer.

**Comment by ninodinatale** [comment]
@mathisscott Can we have an update on the progress and on a ETA on this feature?

Thank you!

**Comment by mathisscott** [comment]
@ninodinatale 
Given the complexity of the datagrid, I don't think we would be able to deliver this feature by the end of December if we started on it today. That said, it is not in our list of near-term priorities and we have a lot of priorities to get through before we can consider this enhancement.

If you have people on your team who could work on it, a contribution might be the best way to go and I would be happy to get you in touch with the team to go over the contribution process. But this feature would probably be blocked by #1826. So that would need to be completed before work could be started on this.

**Comment by mathisscott** [comment]
Hi @ninodinatale 
My bad. I had this issue confused with #1771 

We are actually not working on this feature right now. It is blocked by #1771 

We haven't scheduled this to be worked on yet. I don't think it will be available before the end of December.

**Comment by ninodinatale** [comment]
Hey @mathisscott 
Thank you for the information.

**Comment by d-m-s** [comment]
@mathisscott just seen you've updated https://github.com/vmware/clarity/wiki/Work-in-progress 
is there a chance this feature could make it sometime soon after #1771 has finished?
would be really a great addition to #1771 and the datagrid in general.

**Comment by kjetilhp** [comment]
any news on the ETA of this? still spring 2019 as a goal?

**Comment by gnomeontherun** [comment]
There is no active work on this feature so we have no goal or timeline to report.

**Comment by namitabandal** [comment]
@mathisscott Any updates on the ETA of this feature?

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
