### ISSUE TITLE
Probable errors in the website for 0.11.0-beta.1 release page

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1828]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

NPM Packages should mention and link to @clr/\<module\>. Currently they link to clarity-\<module\>.

Probably @ng/\<module\> should be @clr/\<module\>.
### Actual behavior

![image](https://user-images.githubusercontent.com/13748882/34454497-cf623e12-ed92-11e7-9b60-5ebfb0847750.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**
0.11.0-beta.1
* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@SayakMukhopadhyay: Thanks for reporting this. We will get this fixed soon.

**Comment by hippee-lee** [comment]
Fixed with #1840
