### ISSUE TITLE
Feature request: Color(picker) icons

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#1829]
```
[ ] bug
[x] feature request
[ ] enhancement
```

An icon for color choosing would be really useful. There are two common types I know: a pipette and a drop.

**Comment by mathisscott** [comment]
Adding to volume 10 of icons...

**Comment by lil-kim** [comment]
Icon published. See Vol 10 icons:
https://github.com/vmware/clarity/issues/1787
