### ISSUE TITLE
Getting ReferenceError: Prism is not defined

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#1832]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Should not get any error

### Actual behavior
Getting ReferenceError: Prism is not defined
![image](https://user-images.githubusercontent.com/12848838/34467491-a2e01dea-ef19-11e7-9d32-34b213b73f27.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

Plunker link: https://plnkr.co/edit/GajhfjWtm1GcA1HAUGsM?p=preview

### Environment details

* **Angular version:** 4.4.6

* **Clarity version:** 0.10.20

* **OS and version:** any

* **Browser:** [all]

**Comment by adityarb88** [comment]
@shravansofts: You need to include prismjs in your application. Please refer to this plnkr: https://plnkr.co/edit/Y0rMiGiyqcNmredO7N6i?p=preview (Read index.html). You need to include prism.js, the css theme for code highlight and the language script that you want to highlight. More info on our docs: https://vmware.github.io/clarity/documentation/code-highlight

Closing the issue based on the above info. Please feel free to reopen the issue if you have more questions.
