### ISSUE TITLE
How to trigger modal with jquery

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#1833]
```
[ ] bug
[ x] feature request
[ x] enhancement
```

### Expected behavior
Already I use clarity-ui as CSS framework in my project. My project is not SPA and it's static (not angular). I use jquery for some action. Now, how to use and run modal with jquery or javascript?

* **Clarity version:** 0.10.9

* **OS and version:**  Windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@essivision 
[Here is an example of using jQuery to toggle the modal](http://plnkr.co/edit/Ox0r8a?p=preview)
