### ISSUE TITLE
Progress bar custom color

### ISSUE THREAD

**Issue by GitJacek** [vmware/clarity#1834]
**Select one ...**  (check one with "x")
```
[ ] bug
[X ] feature request
[X ] enhancement
```

### Expected behavior
Hi, im looking for way to set progress bar custom color. Currently im able to pick only blue green( with success class) and Red (danger). I Tried to use custom CSS styles but no effect (i Tried with ! important color and background-color styles).

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.20

* **OS and version:** 
Windows 7 and 10
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@GitJacek: Could you please reopen the ticket with the details provided in the template?

We do not see any information provided:
![image](https://user-images.githubusercontent.com/1426805/34484581-86c15244-ef93-11e7-8706-f7b451790fb1.png)

Are you looking to change the progress bar color? Were you able to do this via CSS on your end? Are you requesting for this feature to be provided by us or are you not able to customize the progress bar on your end?

Without this information we will not be able to evaluate the ticket.

Closing this issue based on the above info. Please reopen a new issue with the information provided in the issue template.

**Comment by GitJacek** [comment]
Hi, i'm sorry my mobile messed around. I already edited issue before You closed it, but probably after You clicked on its.

**Comment by adityarb88** [comment]
@GitJacek: No worries. Reopened the issue. We will take a look at this and respond back in a few. Thanks!

**Comment by adityarb88** [comment]
@GitJacek: Please refer to this plnkr: https://plnkr.co/edit/w8xwwd24vy325FDUw0hX?p=preview
(app.component.css)

Progress element requires you to use browser prefixes to update the color. Hope this helps.

**Comment by GitJacek** [comment]
@adityarb88 thank you. The thing is that this way i can set only one color right? My goal is to set progress bar color depending on value.

**Comment by adityarb88** [comment]
@GitJacek: You could use the CSS attribute selector to check for different values and add different colors on that.

For ex:

```
.progress > progress[value="50"]::-webkit-progress-value  {
      background-color: yellow;
}
```

**Comment by GitJacek** [comment]
Im almost three, i want to switch color depending on Intervals. For example 0-40 Black 40-50 pink etc. But i guess it can be done from typescript somehow. Thank you for your help @adityarb88

**Comment by adityarb88** [comment]
@GitJacek: I would recommend asking this on StackOverflow with the `vmware-clarity`, `angular` and `css` tag. https://stackoverflow.com/tags/vmware-clarity Our community is very responsive. I would also recommend to add a plnkr to the question to demo what you currently have. That way users answering the question can build on your plnkr.
