### ISSUE TITLE
clrModalOpenChange fires twice when a modal closes. 

### ISSUE THREAD

**Issue by aaronfrost** [vmware/clarity#1835]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When a modal closes, the `clrModalOpenChange` should only fire once. 

### Actual behavior

When a modal closes, the `clrModalOpenChange` should only fires twice. 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.1.1

* **Clarity version:** 0.10.10

* **OS and version:** MacOSX 10.13.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by aaronfrost** [comment]
Sorry, I don't think that was a real issue.

**Comment by hippee-lee** [comment]
Thanks for the follow-up.

**Comment by imolorhe** [comment]
I am having the same issue. @aaronfrost how did you resolve it?

**Comment by imolorhe** [comment]
This started happening in my app after I upgraded to angular 5

**Comment by VickyYoung** [comment]
I have the same issue. Is this bug fixed? On what build?

**Comment by mathisscott** [comment]
@VickyYoung 
We haven't been able to reproduce this issue. Could you [create a stackblitz reproduction in 0.12](https://stackblitz.com/edit/clarity-light-theme-v012) or [0.11](https://stackblitz.com/edit/clarity-light-theme-v11)?

**Comment by lohiaad** [comment]
@mathisscott Stackblitz link https://stackblitz.com/edit/clarity-light-theme-v11-oqn2sx

**Comment by hippee-lee** [comment]
@lohiaad - this is a duplicate of #3149. Please subscribe to that issue for updates to progress on it. 

Fwiw - the issue stems from the way a modal close() and the fadeDone() methods are handled for that component. In the case where users close modals with the built in close button the closeChange observable is fired from both the close method and the fadeDone() method.
