### ISSUE TITLE
btn-sm button with loading indicator doesn't look good

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#1836]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

A <button> with a class of .btn-sm and clrLoading="true" should lay out nicely.

### Actual behavior

See the plunker. The loading spinner seems too big and is not vertically centered.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/bw4dwl8tfXr8QUzMy5zV

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**
Latest (and earlier)

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by adityarb88** [comment]
@rongery: Thanks for raising this issue. I will mark this as a bug. Updated plnkr: https://plnkr.co/edit/I6wy9TUw75k1R5EcLp9S?p=preview because I think the default clarity plnkr was pasted above by mistake.

**Comment by rongery** [comment]
Sorry about the bad paste job (I did create one and fork it but apparently
didn't get the right link), and thank you for correcting it. Other than the
text in the buttons, our plnkrs are pretty much identical.
