### ISSUE TITLE
Conditional pagination issue

### ISSUE THREAD

**Issue by grreeenn** [vmware/clarity#1838]
**Select one ...**  (check one with "x")
```
[x ] bug 
[ ] feature request
[ ] enhancement
```
Not sure if it's a bug or an expected behavior..
I'm building a datagrid wrapper component, which serves many pages and gets the structure and data dynamically. As a part of a structure the component gets a boolean with a pagination switch - so the component may enable the pagination only in tables that should have it. So I've put the pagination-related code into ng-container with *ngIf, but...

### Expected behavior
Is to show the pagination just when the *ngIf condition is met.

### Actual behavior
The pages switch does not show up. Pagination variables, firstItem and lastItem shows up correctly, though.

### Reproduction of behavior
Put the pagination-related code into ng-container or any other element (even without a condition)
https://plnkr.co/edit/vXGb7eBFQlwL22LPSYBy?p=preview

### Workarounds tried
I've tried to put the condition on the clr-dg-pagination element itself - fails as firstItem and lastItem are undefined;
I've tried to put the condition on the clr-dg-footer itself - works fine until there're no hideable columns, when there are some - does the job but throws ExpressionChangedAfterItHasBeenCheckedError;
I've tried to put the whole footer into ng-container - it just fails silently

I have a feeling that I miss some rather simple workaround, but I still can't find it... Thank you for your help!

### Environment details

* **Angular version:** 5.1.2

* **Clarity version:** 0.10.19

* **OS and version:** Win 10

* **Browser:** Chrome  63.0.3239.84, FF 57.0.2

**Comment by adityarb88** [comment]
@grreeenn: Not sure if I understand your question correctly. Are you looking for something like this? https://plnkr.co/edit/FzDlMGaRIN1GszssoKlF?p=preview

**Comment by adityarb88** [comment]
@grreeenn: Please take a look at this plnkr: https://plnkr.co/edit/JLlJVp0YzRf48j7Hpcko?p=preview

This should work fine. I will check with @youdz if this is the solution that we were aiming for. If not, I will post a better one later on after further investigation.

**Comment by adityarb88** [comment]
@grreeenn: We have fixed this bug in 0.11.1 & 0.10.23. Please refer to this file for more details: https://github.com/vmware/clarity/commit/df1ed6a99c72e292ede76f02f7edcfdeef3256e5#diff-c2816faca8eee9d8ca2c37224086529a

**Comment by grreeenn** [comment]
@adityarb88 thank you very much! I'll fix the pseudo-workaround I did meanwhile as soon as we update our packages :)
