### ISSUE TITLE
Update UI Libraries

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1849]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
- [x] updated UI Libraries (light)
- [x] updated UI Libraries (dark)
- [x] updated Icon Library
- [x] update copy on the Get Started page
- [ ] update version numbers on download buttons
- [ ] remove the Craft Library alert
![image](https://user-images.githubusercontent.com/1858226/34787775-5071e66c-f5ed-11e7-9944-96f00f77dcce.png)

### Updates
- [x] Wizard: resizing issue
- [x] Text Symbols (#1668): update symbol names to describe usage
- [x] Dropdowns: correct line height to 30px
- [x] Header nav: refactor to make adding links and icons easier
- [x] Cards: add no content versions: with & without divider
- [x] Signpost: added an inactive state icon
- [x] Modal & Wizard: separate out the buttons for easier customization
- [x] Tree View: refactor with improved overrides
- [x] Icon color-switch (Core)

**Comment by reddolan** [comment]
Updates made to light theme and merged into Gitlab. Working on dark theme now

**Comment by reddolan** [comment]
0.11.0 Sketch Files
[UI Library](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-0.11.0.sketch)
[UI Library - dark](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-UI-Library-dark-0.11.0.sketch)
[Icon Library](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Clarity-Icons-Library-0.11.0.sketch)

**Comment by reddolan** [comment]
Buttons update to
UI LIBRARY (0.11.0)
DARK UI LIBRARY (0.11.0)
ICON LIBRARY (0.11.0)
UI LIBRARY (0.10.11) [flat button]

![image](https://user-images.githubusercontent.com/1858226/34809550-7e90de10-f64a-11e7-80fd-cc650b3e4e5d.png)

**Comment by reddolan** [comment]
@hippee-lee this issue should be good to go for tomorrow

**Comment by hippee-lee** [comment]
Closing this. I added the new files to the website and they will be published when its updated.

**Comment by reddolan** [comment]
@hippee-lee there is also something being removed from that page. See the description, it is the Info Alert on that page about Craft Library
