### ISSUE TITLE
Update home page "Sketch" section

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#1852]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
- home page Sketch section should point to the Design Resources section
- copy should reflect the use of Libraries
- *copy to come*

### Actual behavior
- the link is dead and doesn't link anywhere or to anything
- the copy talks about templates

### Reproduction of behavior
![image](https://user-images.githubusercontent.com/1858226/34750241-eb363722-f55a-11e7-80ca-936053e532ff.png)

### Environment details
* **Clarity version:** 0.10.21

**Comment by reddolan** [comment]
[Sketch logo]
### Sketch Libraries
Jumpstart your project by using one of our [Sketch Libraries](https://vmware.github.io/clarity/documentation/v0.11/get-started#designResources) that have ready to use components.

**Comment by hippee-lee** [comment]
Closing this, it will be published with todays website updates.
