### ISSUE TITLE
Input width / Input Validation width

### ISSUE THREAD

**Issue by spetri** [vmware/clarity#1855]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Expect the width of the input to be the same, both on an empty input element and an empty input element w/ validation.

### Actual behavior
The input width of the validated element is longer than one without validation.

### Reproduction of behavior
https://plnkr.co/edit/JIwRcgL6uQgyI7UrsOyb?p=preview

### Environment details
- clarity-angular: 0.10.13
- angular: 4.3.0

* **Browser:** all

<img width="379" alt="screen shot 2018-01-10 at 1 46 27 pm" src="https://user-images.githubusercontent.com/1146420/34797276-c153af04-f60c-11e7-8793-3772a4174a60.png">

**Comment by adityarb88** [comment]
@spetri: Thanks for reporting this issue. We will take a look at this with the forms refactor issue.
Please subscribe to #932 for more updates.

In the meanwhile, you could adjust the size on the inputs or use forms in grids as a workaround for this issue. Plnkr: https://plnkr.co/edit/WKpwOrrOQYJqHnNxfi6S?p=preview

**Comment by mathisscott** [comment]
@gnomeontherun 
Does the new work on forms fix this issue?

**Comment by gnomeontherun** [comment]
This should be resolved because we reserve a 'space' for the icon regardless if it is used or not. Closing as fixed.
