### ISSUE TITLE
Search component (new)

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#186]
### Description
- a field or icon that can be interacted with to return a specific result or results
- search from header so that it is in a consistent place site-wide

### Use cases under consideration
- autocomplete
- placeholder text
- recent searches
- hot keys
- advanced search
- responsive design

### Future use cases under consideration
- operators, modifiers, wildcards
- saved searches
- formatted autosuggestions (different designs based on context)
- search from grid

#### Header Options
Search will be available to all Header design patterns

![headers](https://cloud.githubusercontent.com/assets/1858226/21439231/6486ae86-c852-11e6-8c95-28baae2b7e91.png)

Search Interaction
- Clicking on the Search icon or field will activate the Search interaction
- icon area will turn white (box around icon)
- icon will turn Active blue 
- white search box will expand to fill the Header space up to 1000px (see Responsive)
- expansion will start from the search icon/field origination point
- expansion will cover all icons and links
- expansion will stop to the left of the product name area
- search field will retain the placeholder text if there was, or display Search if it was just an icon

Starting point
![start](https://cloud.githubusercontent.com/assets/1858226/21439674/ff5cded8-c854-11e6-8850-950d2c13b4b4.png)

Beginning of interaction
![state 2](https://cloud.githubusercontent.com/assets/1858226/21439679/05828416-c855-11e6-8bab-21b378c01588.png)

Search field fully open
![state 3](https://cloud.githubusercontent.com/assets/1858226/21439687/0ec8b69e-c855-11e6-863f-14c7dfe412f9.png)

#### Recent Searches
- display recently searched  items when available
- shows immediately after expansion animation is finished
- display pages and/or search queries
- pages are displayed blue like a link
- icons associated with different object types (optional)
- Search experience can be closed by: clicking “cancel”, clicking outside of the search field or dropdown, and also by hitting the Esc key

![recent searches](https://cloud.githubusercontent.com/assets/1858226/21439705/1d264774-c855-11e6-8bc2-9568f68a0607.png)

#### Suggestions Interaction 
- Recent Searches stays visible while typing, up to 2 characters
- once the 3 character is typed, display the Searching dropdown
- if the suggestions come back quickly (~1 sec or less), immediately show the Suggestions dropdown and bypass showing the Searching dropdown
- show up to 5 of the most recent search queries

While typing
![suggestions - typing](https://cloud.githubusercontent.com/assets/1858226/21439716/289a95c4-c855-11e6-99ab-c55625e5a28a.png)

Searching dropdown
![suggestions - searching](https://cloud.githubusercontent.com/assets/1858226/21439717/2b86fafc-c855-11e6-9ee8-b452d5d08c97.png)

#### Suggestions
- Results that match the search query will be displayed in the Suggestions dropdown
- the default display is a dropdown list design
- Clarity recommends that results are displayed alphabetically
- icons associated with different object types (optional)
- users can navigate the list with arrow keys
- selected result will have a grey background to highlight the selection
- hitting the Enter key or clicking the result will navigate the user
- search query is bolded within results
- additional meta data can be associated with the search result
- Search for “[query]” will be displayed as first result and will be selected
- show up to 5 search results

![suggestions](https://cloud.githubusercontent.com/assets/1858226/21439720/304edb36-c855-11e6-8636-a4d285eb8893.png)

#### No Results
- displayed when the user’s search query has no matching results
- No Results dropdown will replace Recent Searches, Loading, or Suggestions dropdowns when no results are available and depending on where the users is in the workflow
- display the search query in the No Results dropdown and bolded

![no results](https://cloud.githubusercontent.com/assets/1858226/21439729/3cb7614a-c855-11e6-96b8-d681f6cc4b53.png)

#### Responsive
- will follow all above interactions
- Search experience will be responsive to different screen sizes
- responds to our normal break points: 768px and 544px
- the responsive versions will cover the entire Header area

Screen widths 768px to 545px
![responsive - 768](https://cloud.githubusercontent.com/assets/1858226/21439760/56398148-c855-11e6-9626-a63f9dbb3c8a.png)

Screen widths 544px or less
![responsive - 544](https://cloud.githubusercontent.com/assets/1858226/21439762/59ec4316-c855-11e6-863e-c03adcc86c01.png)

- Search will have a max width of 1000px
- larger screens will push the Search to the left or right side
- Search will overlay any Header elements and will have a fade based on the Search alignment

left fade for right-aligned Search
![search-aligned-right](https://cloud.githubusercontent.com/assets/1858226/21439792/7b43cc96-c855-11e6-8e9c-11bc190baa3a.png)

right fade for left-aligned Search
![search-aligned-left](https://cloud.githubusercontent.com/assets/1858226/21439794/7e8d9b84-c855-11e6-9281-bc1663a0af85.png)

#### Sizes
- standard size is 1000px (max)
- small size is 500px, when the width of Search results are narrow
- small will display right or left aligned depending on its origination

small Search (right-aligned)
![small-search](https://cloud.githubusercontent.com/assets/1858226/21440117/0ed47a2c-c857-11e6-976d-5981a101fc83.png)

**Documentation is subject to change**

**Comment by pchoi** [comment]
Is there a plan to introduce the following capabilities?

1. `pagination`
2. `throttle/debounce`

**Comment by joshjohnson72** [comment]
Feature request:  It's been noted that showing search only as an icon may not be discoverable enough, so it would be useful to support a persistent open search associated with the right-aligned items in the header.  I'm picturing something similar to the "small Search (right-aligned)" but without the "cancel" and displayed inline with the other right-aligned icons.
![embedded-right-search](https://cloud.githubusercontent.com/assets/8105536/23929741/65bdf236-08e5-11e7-8ee1-44d62153f641.png)

**Comment by bkcohaesus** [comment]
Hi, do you have any estimate when this feature might be available? 1month, 3 months, 6months? Our team is building an app on Clarity and really need search for our MVP. We don't want to do any thing custom if this is coming, but the ticked has not updated in a while.

**Comment by mathisscott** [comment]
Hi @bkcohaesus
search is not currently being implemented but it's on our short list in the coming months. Could you share a bit more about your use cases and priorities so we can see if we can re-prioritize it to help you out?

**Comment by jakehockey10** [comment]
I was just wondering how the datasource for the autocomplete is currently planned to work like.  Will there be various ways to set a repository or endpoint?  Thanks

**Comment by mathisscott** [comment]
@youdz can correct me on this if I am wrong but my understanding is that the datasource will be passed through your hostcomponent. most likely the autocomplete suggestions will be managed on your end through a declarative syntax similar to how datagrid rows are created.

**Comment by youdz** [comment]
Yes, this is exactly it. We will never make HTTP calls for you, for various testability and maintainability reasons.

So you'll just make the call on your side, and display the results declaratively (for instance with an 
`*ngFor`) inside of our component.

**Comment by whizkidwwe1217** [comment]
Hi, I was just wondering if this component could also be used as an input control for forms. Will this be like an auto-complete combo box that can be used not just in the header component but in the form as well?

**Comment by mathisscott** [comment]
@whizkidwwe1217 
Not really. I think the component you're wanting to follow is #248

**Comment by adityarb88** [comment]
Implementation/Fix to this should also include resolving the issues mentioned in #451 & #447

**Comment by Jinnie** [comment]
Hi all,
We have an use-case where our auto-suggesting search box should be combined with tags.
We are currently using the ng2-tag-input component (demo: http://www.buompris.co/ng2-tag-input/), but we'd prefer to switch to a clarity component once we have one.
Is there any viable chance to have tags added to the current specs?

**Comment by jaffoneh** [comment]
CC @reddolan to learn more about the above request and see if it makes sense to include in the search component or the select 2.0 component.

**Comment by reddolan** [comment]
@Jinnie #248 (Select 2.0) has a feature spec'd for tag/label usage. It is labeled as "Multiselect". Is this what you are talking about?

**Comment by Jinnie** [comment]
Absolutely. Thanks, @reddolan, I'll bookmark #248 and watch for the progress there.

**Comment by Jinnie** [comment]
Btw, will it only work with predefined values, or it will be possible to add free text entries?
In our use-case it will be a complex search field, that we want to use to filter content both on tags (predefined) and partial entity name. For example typing "delete" should filter on all actions with the word "delete" in their name, like "delete virtual machine", "delete snaphsot", etc.

**Comment by mathisscott** [comment]
Hi @Jinnie 
The select 2.0 component will be the view layer for your business logic. What it filters, how it filters, or if it even _is_ a filter is the piece that Application developers would add.

Much like how the datagrid does not store your application’s state and is not opinionated about where the data is coming from.

So visually, yes, the select 2.0 component will give you the visual tools to represent all of that. But your business logic will be driving it.

I hope that makes sense.

**Comment by Jinnie** [comment]
Thanks for the answer, @mathisscott
I added info about filtering, etc, just to clarify my use-case. 
My actual question is whether the select 2.0 will turn only predefined answers from the dropdown to selected entities, with border and X icon for deletion, or I will have the power to implement it in such a way, that I am able to add random text, which may not be part of the, let's call them, "options 2.0" - the predefined answers of the select component.

**Comment by mathisscott** [comment]
Hi @Jinnie 
I don't see Clarity supplying that text. So anything you determine is an item will be an item. Your app will be what is sending the Clarity component these labels. I'm sure that if you have additional text you want to add or not show that you will be able to do it in the host component before it reaches the Clarity Select.

**Comment by psingl** [comment]
I am not able to use this feature properly. Can someone tell me about me on how to use this component? I am not finding much details in the official docs.

**Comment by gnomeontherun** [comment]
@psingl This is not yet implemented, but you could use the design pattern outlined here for building something.

**Comment by psingl** [comment]
Hey there! Has someone implemented the above search design? If yes, could you please provide with the source code?

**Comment by hippee-lee** [comment]
Hi @psingl - There is no source code for this feature. As pointed out above, this issue is the search design spec but it hasn't been implemented. If you are looking to implement your own solution you could use the design spec outlined in this issue.

**Comment by dhanunjaya** [comment]
Hey there! did anyone implemented the above search design?

**Comment by gnomeontherun** [comment]
There has been no change in implementation status for Clarity.

**Comment by vinaykhegde** [comment]
Hi guys good job,I have started using Clarity, and I wanted to know any workaround or updates on this implementation?

**Comment by mathisscott** [comment]
HI @vinaykhegde 
No, there has been no change in status. You can see [what the Clarity team is working on and planning to work on here](https://github.com/vmware/clarity/wiki/Work-in-progress).

Thanks!

**Comment by gnomeontherun** [comment]
The basics of a search component are available in Clarity Core already, but this issue covers a number of specific use cases that aren't supported out of the box. These feature requests have been captured into our list and we’re going to take them into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
