### ISSUE TITLE
Feature Request: Copy Clipboard Icon for Clarity

### ISSUE THREAD

**Issue by Rayfall** [vmware/clarity#1860]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@lil-kim @mathisscott could you please take a look and provide feedback?

**Comment by mathisscott** [comment]
@Rayfall 
We have a copy icon. And we have a clipboard icon (which can be used instead if you don't like the copy icon).

What's the difference between what we have and a "copy clipboard" icon?

**Comment by Rayfall** [comment]
The "Copy" Icon is like a copy-paste and the "Clipboard" Icon doesn't seem to work with my company.

I was looking for more of a "Copy to Clipboard" Icon. The icon they previously used had an arrow pointing to the clipboard to indicate the copied to clipboard. I wanted to reach out to see if I could request the icon. Something more along the lines of this:

![copy_to_clipboard](https://user-images.githubusercontent.com/35342691/34890669-d3a7694e-f7a0-11e7-8ebe-bc926c10c328.png)

**Comment by mathisscott** [comment]
Oh, I see. We'll add that to our next iteration of icons. Thanks for clarifying!

**Comment by Rayfall** [comment]
Thank you!

**Comment by lil-kim** [comment]
Completed as part of epic #1787
