### ISSUE TITLE
Prod build of Angular app fails after upgrading to Clarity 0.11.0

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#1862]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Executing the command 'ng build --prod --aot --base-href=/bic/' should compile my angular app for a production build. My application compiles and works with the 'ng serve' command.

### Actual behavior
Compilation fails with the below errors messages. Further I've enclosed my package and angular-cli json files for reference.
[.angular-cli.txt](https://github.com/vmware/clarity/files/1626812/default.angular-cli.txt)
[package.txt](https://github.com/vmware/clarity/files/1626813/package.txt)

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\blank\Documents\Angular\cr\crmt\src'
resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\blank\Documents\Angular\cr\crmt\src'
  using description file: C:\Users\blank\Documents\Angular\cr\crmt\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\Users\blank\Documents\Angular\cr\crmt\package.json (relative path: ./src)
    using description file: C:\Users\blank\Documents\Angular\cr\crmt\package.json (relative path: ./src/$$_gendir/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\blank\Documents\Angular\cr\crmt\src\$$_gendir\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\blank\Documents\Angular\cr\crmt\src\$$_gendir\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\Users\blank\Documents\Angular\cr\crmt\src\$$_gendir\app\app.module.ngfactory.js doesn't exist
      as directory
        C:\Users\blank\Documents\Angular\cr\crmt\src\$$_gendir\app\app.module.ngfactory doesn't exist
[C:\Users\blank\Documents\Angular\cr\crmt\src\$$_gendir\app\app.module.ngfactory]
[C:\Users\blank\Documents\Angular\cr\crmt\src\$$_gendir\app\app.module.ngfactory.ts]
[C:\Users\blank\Documents\Angular\cr\crmt\src\$$_gendir\app\app.module.ngfactory.js]
[C:\Users\blank\Documents\Angular\cr\crmt\src\$$_gendir\app\app.module.ngfactory]
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
ERROR in Error: Metadata version mismatch for module C:/Users/blank/Documents/Angular/cr/crmt/node_modules/@clr/angular/clr-angular.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@angular\compiler\bundles\compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@angular\compiler\bundles\compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@angular\compiler\bundles\compiler.umd.js:25385:14)
    at C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@angular\compiler\bundles\compiler.umd.js:24241:30
    at Array.forEach (native)
    at extractProgramSymbols (C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@angular\compiler\bundles\compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@angular\compiler\bundles\compiler.umd.js:23796:47)
    at CodeGenerator.codegen (C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (C:\Users\blank\Documents\Angular\cr\crmt\node_modules\@ngtools\webpack\src\plugin.js:430:58)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.11.0

* **OS and version:**  Win 7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
Closing the issue based on this. Please feel free to reopen the issue if you have more questions/feedback.

**Comment by hippee-lee** [comment]
@beaker1977 - along with what @adityarb88 mentioned (upgrading to Angular5) I noticed that you do have `@clr` packages installed but they are in your `devDependencies`.

![screen shot 2018-01-12 at 9 28 31 am](https://user-images.githubusercontent.com/433692/34887450-6b241f36-f77b-11e7-95ce-701f2df3459a.png)

**Comment by adityarb88** [comment]
@beaker1977 @hippee-lee: In the file that I am seeing (`package.txt`), I see `clarity-*` being used:

![image](https://user-images.githubusercontent.com/1426805/34907120-9f3b5006-f847-11e7-89e6-b41421437b36.png)

**Comment by hippee-lee** [comment]
Right, those are in the _dependencies_. `package.txt` also has the scoped clarity packages (`@clr/*`) installed as _devDependencies_

**Comment by beaker1977** [comment]
Thanks for everyone's help. I overlooked the Angular 5 dependency requirement. After a little bit of trial and error I got everything working properly.
