### ISSUE TITLE
Installing clarity as a dev dependency?

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1863]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I have been using clarity as a simple dependency in my project (i.e. using `--save` option). But the upgrade guide to Clarity 0.11.x at https://vmware.github.io/clarity/news/0.11.0-beta.1 mentions using it as a dev dependency. Then again in the getting started section at https://vmware.github.io/clarity/documentation/v0.11/get-started `--save` option is used. I am confused. Which one is recommended?

### Actual behavior

Difference in documents regarding Clarity installation

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.11.x

* **OS and version:** Win10

* **Browser:** [all]

**Comment by hippee-lee** [comment]
I pushed a fix to our website branches. It should go out with this weeks release.

**Comment by adityarb88** [comment]
Published
