### ISSUE TITLE
Add sass variable that will bypass the base64 fonts in a generated theme

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#1866]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
How change Default Font from Metropolis?

### Reproduction of behavior
`// Pre variable and theme dependencies
@import "../../node_modules/@clr/ui/src/utils/dependencies.clarity";

// Theme (Variable overrides)
$styledInputs: inputs("text", "password", "number", "email", "url", "tel", "date", "time", "datetime-local", "search");
@import "fonts";
$clr-font: 'Exo 2', 'Helvetica Neue', Arial, sans-serif !default; //Default font stack for Clarity

// Clarity component code (consumes the variables and theme overrides)
@import "../../node_modules/@clr/ui/src/utils/components.clarity";
`

But is not change font-family in output css

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.11.x

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
You shouldn't use the `!default` SASS flag like that.

`!default` only sets the variable in question if it _doesn't already have a value_.

Try the following...

```
// Pre variable and theme dependencies
@import "../../node_modules//src/utils/dependencies.clarity";

// Theme (Variable overrides)
$styledInputs: inputs("text", "password", "number", "email", "url", "tel", "date", "time", "datetime-local", "search");
$clr-font: 'Exo 2', 'Helvetica Neue', Arial, sans-serif;
@import "fonts";
```

...and see if that works.

**Comment by KANekT** [comment]
No it not working for me
Example in out css:
`    .sidenav .nav-group label {
      color: #313131;
      font-size: 0.58333rem;
      font-weight: 500;
      line-height: 1rem;
      font-family: Metropolis, "Avenir Next", "Helvetica Neue", Arial, sans-serif;
      letter-spacing: normal; }
`
i need 
`    .sidenav .nav-group label {
      color: #313131;
      font-size: 0.58333rem;
      font-weight: 500;
      line-height: 1rem;
      font-family: 'Exo 2', 'Helvetica Neue', Arial, sans-serif;
      letter-spacing: normal; }
`

**Comment by mathisscott** [comment]
Did you do what I posted above? It's different from what you posted in the issue.

**Comment by KANekT** [comment]
`h1 {
        @include clr-getTypeProperties(h1);
    }

    h2 {
        @include clr-getTypeProperties(h2);
    }

    h3 {
        @include clr-getTypeProperties(h3);
    }

    h4 {
        @include clr-getTypeProperties(h4);
    }

    h5 {
        @include clr-getTypeProperties(h5);
    }

    h6 {
        @include clr-getTypeProperties(h6);
}`

Not ReWrite font

**Comment by mathisscott** [comment]
I'm sorry @KANekT 

I don't understand what you are wanting to do.

If all you want to do is change the font of the H1 tag, you can do that with regular CSS.

But above you try to change the font of the entire app. Then show an example of trying to change the font in the sidenav...

Then your final reply contradicts your first example.

Please clarify. This does not appear to be a Clarity issue.

**Comment by KANekT** [comment]
I need change the font of the entire app.

but `$clr-font: 'Exo 2', 'Helvetica Neue', Arial, sans-serif;`

not change font Metropolis to Exo 2 for 
h*
.login-wrapper **
.modal-header **
header **
.sidenav **

Yes, I can change font in my CSS, but I think that this is a bad practice ...

**Comment by KANekT** [comment]
```
//Generates responsive typography based on the element style map in variables.clarity.scss
@mixin clr-getTypeProperties($element, $whichTypeProperties: (), $breakpoint-property: min-width, $breakpoints-map: $clr-breakpoints) {
```
This mixin now use $clr-font ?

**Comment by mathisscott** [comment]
@KANekT 
Not for all elements. Clarity has the ability for "header" styles to use a different font from "body" styles.

Try setting both the `$clr-font` and `$clr-altFont` variables to "Exo 2" to see if that solves the issue.

**Comment by KANekT** [comment]
@mathisscott Yes, $clr-font and $clr-altFont It Great!!! and worked!

And how i delete @import "../typography/fonts.clarity"; from components.clarity ?

only write myself file for this ?

**Comment by mathisscott** [comment]
@KANekT 
So you're trying to remove the base-64 fonts? Makes sense.

Only way to do this is by overriding the existing Clarity SASS build. You'll need to create a custom `main.scss` that pulls in Clarity's `utils/dependencies` file and your own `components` SASS file.

Your component SASS file should be a copy-paste of our own `utils/components` file with the line pulling in the fonts.scss commented out.

It's a similar process to what you'd have to do to make a deep custom version of Bootstrap...

**Comment by KANekT** [comment]
It is very unfortunate that there is no flag - which would turn off the fonts

**Comment by mathisscott** [comment]
I think this is a reasonable request and should not be hard to do. It's also a huge issue for those who are customizing Clarity for their apps and don't want the weight of the base64 font sitting unused in their CSS. I totally understand that.

I'll move it to the backlog.

**Comment by KANekT** [comment]
@mathisscott thx!
