### ISSUE TITLE
Feature request: Gallery icon

### ISSUE THREAD

**Issue by artemisclyde** [vmware/clarity#1869]
```
[ ] bug
[x] feature request
[ ] enhancement
```
Seperate icons for image galleries and video galleries would be great. So far I can only use image and video icons, but none that suggests a gallery. I thought of [something like this](https://fontawesome.com/icons/images?style=regular).

**Comment by mathisscott** [comment]
@lil-kim 
Does this request seem like a good candidate for vol. 10?

**Comment by lil-kim** [comment]
Completed as part of epic https://github.com/vmware/clarity/issues/1787
