### ISSUE TITLE
clarity icons aren't placed/sized correctly in buttons

### ISSUE THREAD

**Issue by bjabes** [vmware/clarity#187]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
putting an icon (other than a caret) inside a button, it should aligned and sized correctly. Looking at the plunkr here, it's a bit off.

### Actual behavior
https://plnkr.co/edit/HJQShA3x1wBZvAAlEltZ?p=preview

### Environment details

* **Angular version:** 2.0.X
2

* **Clarity version:** 
0.7

* **OS and version:** 
Mac

* **Browser:** 
all

**Comment by jaffoneh** [comment]
@Shijir could you take a quick look and see what can we do here to improve this? Also CCing @adityarb88

**Comment by adityarb88** [comment]
Removing the `bug` label because this is an enhancement. Clarity buttons don't account for icons currently. @shijir: we will need to ask @lil-kim / design team on what should be the exact icon sizes and the corresponding spacing in regular and small buttons and then implement this enhancement.

**Comment by Shijir** [comment]
Fixed in PR [#241](https://github.com/vmware/clarity/pull/241)
