### ISSUE TITLE
[DOCS] Lots of 404 errors in documentation website

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#1873]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Links to components should properly redirect to component in from last version of docs.

### Actual behavior

A lot of 404 pages due to non proper redirect from component link to versioned component link (for example: from https://vmware.github.io/clarity/documentation/header to https://vmware.github.io/clarity/documentation/v0.11/header

### Reproduction of behavior

Navigate to clarity docs website: 
Choose "header" component from sidebar
Find any link to another component and try to click on it.

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 
Mac OS latest
* **Browser:** [all | Chrome XX | Firefox XX | Safari XX | Mobile Chrome XX ]

**Comment by adityarb88** [comment]
@pumano: Thanks for raising this issue. We will get this fixed soon.

**Comment by adityarb88** [comment]
More details about this issue: https://github.com/vmware/clarity/issues/1874#issuecomment-358799435

**Comment by hippee-lee** [comment]
Closed with: https://github.com/vmware/clarity/commit/a0f7f77c88cc954a1f3ad3fd76e81ccb94b56a17 (v11 docs) and https://github.com/vmware/clarity/commit/d898b15fd8866c3eb35e755eebd9ead7a7c968e6 (v10 docs)
