### ISSUE TITLE
Clarity Forms Redesign Implementation Plan

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#1878]
This outlines the expected plan for refactoring and enhancing forms in Clarity. The specifics may change over time based on the actual versioning of Clarity, and any release dates or versions are subject to change.

## Initial changes for v0.12

First step is to release only what is new and non-breaking, and deprecate current checkbox.

* [x] Deprecate existing `ClrCheckbox`
* [x] Create `HostWrapper`
* [x] Reorganize SCSS
* [x] Update styles based on UX

##### `ClrInput`
  * [x] Default Styling
  * [x] Error Support
  * [x] Disabled & Read Only
  * [x] Horizontal & Compact Layouts
  * [x] Documentation

##### `ClrPassword`
  * [x] Default Styling
  * [x] Error Support
  * [x] Disabled & Read Only
  * [x] Horizontal & Compact Layouts
  * [x] Documentation

## After v0.12

This version is about adding more components, which don't currently have.

##### `ClrRadio`
  * [x] Default Styling
  * [x] Error Support
  * [x] Disabled & Read Only
  * [x] Horizontal & Compact Layouts
  * [x] Documentation

##### `ClrCheckbox` (new version)
  * [x] Default Styling
  * [x] Error Support
  * [x] Disabled & Read Only
  * [x] Horizontal & Compact Layouts
  * [x] Documentation

##### `ClrSelect`
  * [x] Default Styling
  * [x] Error Support
  * [x] Disabled & Read Only
  * [x] Horizontal & Compact Layouts
  * [x] Documentation

##### `ClrTextarea`
  * [x] Default Styling
  * [x] Error Support
  * [x] Disabled & Read Only
  * [x] Horizontal & Compact Layouts
  * [x] Documentation

##### `ClrInputPassword`
  * [x] Show/hide

## Uncommitted 

* Additional input types [`number`, `date`, `email`, `range`, `search`, `tel`, `time`, `url`] if they need any custom support
* Select2 which may be provided from external contribution

**Comment by MithilaTople** [comment]
Hi, @jeremydejiacomo and I were looking at some of the mockups for error handling in the new form update. The error icon is placed next to the field (except for radio buttons and checkboxes) and the error message appears below the field. We were wondering if the icon could be placed next to the error message, since the current placement seems a bit detached from the message and could be confused with a tooltip.

**Comment by mathisscott** [comment]
@reddolan + @gnomeontherun ^

**Comment by reddolan** [comment]
That text location is used by other text types: helper, red error (normal), black error (masked inputs). Adding the icon for just the error state would create jiggle between the different states. We also wanted to tie the visual cue of the icon to the input field in all places possible, helping to enforce that the input has an error.

**Comment by RobArbor** [comment]
In the current implementation i'm missing the required class for labels. 
as user it is very convenient to know which fields are required.

![image](https://user-images.githubusercontent.com/18066581/45945199-ffd2eb00-bfec-11e8-98d0-a5cb0099135d.png)

**Comment by gnomeontherun** [comment]
This is an omission in our documentation, but there is no design for adding required labels because the default behavior is that all fields are required, and denote the optional fields in the label. This is a change with the way our old forms do things, and the change was based on research done by UX on best practices.

**Comment by d-m-s** [comment]
Regarding the required inputs:
We're having lots of data input in different applications and usecases ... in most of them there is a greater amount of optional fields and some required ones.

Anyhow, adding an additional "(optional)" to each of the labels poses the following problems:
- labels will get very long 
(with internationalization usually even longer, if ellipsis is used the important part that the label is optional, is not visible!)
- for the user it is harder to scan which fields are mandatory.
- denoting required fields with an red asterisk "*" is something learned by lots of users!

Do you really think it's a best practice to switch marking required fields and mark optional ones instead?

**Comment by Kangcor** [comment]
> Regarding the required inputs:
> We're having lots of data input in different applications and usecases ... in most of them there is a greater amount of optional fields and some required ones.
> 
> Anyhow, adding an additional "(optional)" to each of the labels poses the following problems:
> 
> * labels will get very long
>   (with internationalization usually even longer, if ellipsis is used the important part that the label is optional, is not visible!)
> * for the user it is harder to scan which fields are mandatory.
> * denoting required fields with an red asterisk "*" is something learned by lots of users!
> 
> Do you really think it's a best practice to switch marking required fields and mark optional ones instead?

Maybe can we use `clr-control-helper` to mark optional fields?

**Comment by gnomeontherun** [comment]
There is nothing that prevents you from putting an * in the label, we just don't provide a default styling for it anymore. I believe the main argument is forms should be succinct and optional fields get in the way of completion of forms. If things are optional, it's possibly best to move those fields to a different flow or put them together.

I think we need to provide better guidance here, so I'm going to ping @reddolan about this.

**Comment by reddolan** [comment]
@Kangcor @gnomeontherun is correct. This was an intentional decision based on the extensive research that we did prior to the Forms refactor. There is much evidence that points to the fact that users consistently miss the "*" required indicator as it is typically small and inconsistently used. There is also evidence showing that users can fill out forms faster knowing that all the fields are required, and optional ones are marked. There are also accessibility concerns around the "*" as a star doesn't indicate anything to most screen readers. Having "optional" in a label is always read by a screen reader. We have plans to update our Forms documentation to support these points.

**Comment by gnomeontherun** [comment]
The final pieces of this have been implemented, closing as resolved for 1.0.
