### ISSUE TITLE
Tooltips inside Wizards has wrong overlapping

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#1880]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Tooltips should be displayed over wizard title (tooltip text should overlap any wizard layout content)

### Actual behavior

Tooltip (if placed at the start of wizard page) can't show full content due to overlapping by wizard title

see screenshot:
<img width="1170" alt="overlap" src="https://user-images.githubusercontent.com/17675259/35198173-1088bdb0-fefc-11e7-91d6-e8b86fe5f743.png">

### Reproduction of behavior

1) Get example code of wizard from clarity doc webside
2) Place Tooltip (XL size) to any wizard page (top of page)
3) Check hover text overlapping

### Environment details

* **Angular version:** 5.2.1
* **Clarity version:** v 0.11.1
* **OS and version:** Mac OS latest
* **Browser:** Chrome 63

**Comment by youdz** [comment]
This is a known issue with "static" tooltips, because they're in a positioned container they get clipped and there's nothing we can do about it at the moment. The solution is simply to use the Angular version of our tooltips, it should work fine: https://vmware.github.io/clarity/documentation/v0.11/tooltips#angular-component

I'm keeping this issue open for now so you can check if that solves your problem. 👍

**Comment by pumano** [comment]
according to docs:

> Placement
Choose a tooltip position that ensures the entire tooltip is visible on the screen and that the tooltip does not cover an important UI element. By default, the positioning for tooltips is to the top-right of the icon, pointing to its center.

I just found workaround and use other positioning `tooltip-bottom-right` for solving that issue. I also test Angular component for tooltip it has same problem. Thanks for response too.

**Comment by adityarb88** [comment]
@pumano: I was looking into this issue but found that this works without any issues when you use the Angular component like @youdz suggested above. Please take a look at this StackBlitz: https://stackblitz.com/edit/clarity-light-theme-v11-o9kwbx?file=app/app.component.html

Let us know if this works for you. Closing the issue based on the above info. Please feel free to reopen the issue if you have any additional questions.
