### ISSUE TITLE
have an option to embed wizard not inside a modal

### ISSUE THREAD

**Issue by Thatkookooguy** [vmware/clarity#1884]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
There should be an option to use the wizard component outside of a modal.

### Actual behavior

The wizard component forces the user to have the wizard inside a modal. I think that's a weird behavior since you can simply put the wizard in a modal.

### Environment details

* **Angular version:** 4.3.6

* **Clarity version:** 0.10.5

* **OS and version:** OS X Sierra 10.12.6

* **Browser:** all

**Comment by adityarb88** [comment]
@Thatkookooguy: Thanks for filing the issue. You can use an inline wizard to do this. Please refer to this issue for more information: https://github.com/vmware/clarity/issues/1704

**Comment by Thatkookooguy** [comment]
@adityarb88 that fixes the styling, but keeps the underlined modal there. Why should that modal exist if my wizard don't use it? it's true it gives somewhat the right result visually, but it adds a complexity that is unnecessary in the number of DOM elements (and javascript code that run & kept alive).

I think the solution you suggested can be used as a very temporary solution for some users.
I wouldn't consider this as an `inline wizard` feature. it's more of a hack :-)

what if the user uses clarity in parallel with another styling library?
Let's say I wrote an Angular 5 app with clarity and a specific modal library that gives me extra functionality.

It sounds to me like the wizard shouldn't be coupled to an unrelated component. The user should be able to use a wizard inside or outside a modal (or inside another library's component, or even in a pop-up). don't you think?

**Comment by adityarb88** [comment]
Thanks for your feedback. Our UX team recommends that the wizard open in a modal and thats the primary use case that we support. I will let @reddolan answer why. 

But we still provide an option for inline wizards. Please take a look at this comment: https://github.com/vmware/clarity/issues/1704#issuecomment-346111362 (I should have linked the specific comment earlier. The file that you should look at is this: https://github.com/vmware/clarity/blob/master/src/app/wizard/wizard-inline.demo.html. I am not sure if you got a chance to look at that.). Let us know if that helps.

**Comment by Thatkookooguy** [comment]
> But we still provide an option for inline wizards. Please take a look at this comment: #1704 (comment) (I should have linked the specific comment earlier. The file that you should look at is this: https://github.com/vmware/clarity/blob/master/src/app/wizard/wizard-inline.demo.html. I am not sure if you got a chance to look at that.). Let us know if that helps.

@adityarb88 that's what my previous comment talked about. That example keeps the modal, just hides it with styling. So the negative effects of this still apply.

> Our UX team recommends that the wizard open in a modal and that's the primary use case that we support

why though? what functionality will you lose if the wizard won't be inside a clarity modal component? especially if you already create an "inline-wizard" example?
Besides, you could still use a wizard inside a modal by just using it that way (like in this crude example: `<clarity-modal><clarity-wizard></clarity-wizard></clarity-modal>`).

**Comment by mathisscott** [comment]
Hi @Thatkookooguy 
Per our UX team, the wizard is intended to be an interrupt workflow. Meaning that it is not intended to be an inline component. It opens all sorts of corner cases where users would or could leave the wizard to navigate elsewhere in the application and puts an onus on maintaining that state for them for an indefinite period of time.

We offer an inline hack because many teams at VMware still use it inline. But it is not a recommended use case.

**Comment by Thatkookooguy** [comment]
>  It opens all sorts of corner cases where users would or could leave the wizard to navigate elsewhere in the application and puts an onus on maintaining that state for them for an indefinite period of time.

@mathisscott I'm not sure why those corner cases are any different from starting to fill a form and trying to navigate elsewhere in the application in the middle of it.
When using clarity forms, that scenario is left alone to be handled by the application itself. Why shouldn't this be the case with a wizard? it's not as if I click the reload button in the browser and the clarity wizard throws a warning at me.

But I understand the discussion is finished already since you closed the issue :-)
I'll leave you guys alone
