### ISSUE TITLE
[DOCS] Vertical Nav API docs

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1889]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

API/Summary table is present in the Vertical Nav Documentation.

### Actual behavior

API/Summary table is missing in the Vertical Nav Documentation.

Please refer to the Tree View Docs for more details:
https://vmware.github.io/clarity/documentation/v0.11/tree-view
![image](https://user-images.githubusercontent.com/1426805/35444404-78dd4dbc-027c-11e8-9286-25f797b35af1.png)

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/v0.11/vertical-nav/basic-structure/charmander

**Comment by pumano** [comment]
Also will be helpful to add to example how to add dividers: `<div class="nav-divider"></div>` because I got it from source code

**Comment by rokobasilisk** [comment]
The links to Code and Examples in the Vertical Nav Documentation are also broken. Not sure if it is worth creating a new issue for this.

**Comment by gnomeontherun** [comment]
No longer an issue or resolved in the upcoming website work. Closing as resolved.
