### ISSUE TITLE
npm v0.11.2 fail: /interfaces/icon-interfaces not exist

### ISSUE THREAD

**Issue by panpan0000** [vmware/clarity#1891]
**Select one ...**  (check one with "x")
```
[* ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

in ```node_modules/\@clr/icons/clr-icons-api.d.ts```
`import { IconAlias, IconShapeSources } from "./interfaces/icon-interfaces";`
but the file `interfaces/icon-interfaces.ts` is not packaged in the v0.11.2
please rebuild v0.11.3 to fix it

### Actual behavior
`

ERROR in node_modules/@clr/icons/clr-icons-api.d.ts(9,17): error TS2304: Cannot find name 'IconShapeSources'.
node_modules/@clr/icons/clr-icons-api.d.ts(12,21): error TS2304: Cannot find name 'IconAlias'.

`

### Reproduction of behavior

npm package: v0.11.0 was still good.
npm package: v0.11.2 failed.

### Environment details

* **Angular version:** 5.x
* ** npm run e2e

**Comment by Shijir** [comment]
Hi @panpan0000, please install` v0.11.2-patch` version which solves that exact problem. https://vmware.github.io/clarity/news
