### ISSUE TITLE
Release Dates in 2017 instead of 2018

### ISSUE THREAD

**Issue by rlove** [vmware/clarity#1900]
**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

 Release dates to report the correct year.

### Actual behavior

https://vmware.github.io/clarity/news/0.11.2-patch
Show release date Jan 26, 2017 I believe it should be 2018 

This appears to be broken since 0.10.23

I am new to looking at clarity I when I saw this I thought the project was dead. However, once I saw the commit history I realized it was a mistake.

**Comment by Shijir** [comment]
@rlove you are right. Thanks for notifying us on this. We'll fix it asap.

**Comment by Shijir** [comment]
Fixed here in: https://github.com/vmware/clarity/commit/00da9bd515787b684a6afaa8f26cc2f3a73f0f7c
