### ISSUE TITLE
Cannot move <clr-alerts> to the first alert with clrCurrentAlertIndex

### ISSUE THREAD

**Issue by svvac** [vmware/clarity#1907]
This is a bug report.

### Expected behavior
Using `<clr-alerts>`, setting the `clrCurrentAlertIndex` input property to `0` should reset the scroller to the first alert.

### Actual behavior
Setting `0` is ignored, because the property has a `if (index)` guarding it and `0` is falsy.

https://github.com/vmware/clarity/blob/v0.11.2/src/clr-angular/emphasis/alert/alerts.ts#L32

I guess it should read something like `typeof index === 'number'` instead.

I hit this while dynamically generating alerts and removing them. Since the component does't seem to react to the removal of its alerts, you need to update the current index manually in order for an alert to be displayed (if you're on the last and remove one, then you got an empty block because the component is reading out of the list bounds). When you remove the penultimate alert (the one before the last one), you cannot reset the index to zero (it's falsy), and thus your single alert doesn't get displayed. Setting the index directly on the `multiAlertService.index` works though.

On a side note, the `MultiAlertService.manage()` call should probably setup listeners to the `QueryList` in order to clamp the index inside the array bounds anyways.

**Comment by mathisscott** [comment]
@svvac 
Thanks for reporting this. We've added it to our backlog.

**Comment by bdunkz** [comment]
@svvac - when you mention the component does not react to the removal of an alert, how are they being removed?  Clicking close on the alert should cause the index to be updated.  Resetting the index to 0 does seem like it could be an issue though.

**Comment by svvac** [comment]
I populate my `<clr-alerts>` with a `ngFor` that collects alerts from various parts of the app. The problem appears when such an alert gets removed and the list iterated by `ngFor` shrinks.

**Comment by UttamA** [comment]
I see this issue is already fixed with #2120.

**Comment by Jinnie** [comment]
I confirm that this has been fixed with #2120. I created a stackblitz reproduction and it works fine. It is also properly covered with tests, so I am closing it.
