### ISSUE TITLE
Tooltips for vertical nav

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#1910]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
Have tooltips on navigation groups and items.

### Actual behavior
There are no tooltips. WHen text doesn't fit (especially with certain languages) user cannot see the complete text.

### Reproduction of behavior
Use long text

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.2.2

* **Clarity version:** 11.2

* **OS and version:** Win 10

* **Browser:** all

**Comment by adityarb88** [comment]
@rbirkgit: Our UX team recommends that you keep the title short and concise. More info here:

![image](https://user-images.githubusercontent.com/1426805/35745448-50304ac8-0811-11e8-8210-1476c8718f73.png)
https://vmware.github.io/clarity/documentation/v0.11/vertical-nav/basic-structure/charmander

The implementation shows an ellipsis when the labels are too long.

@reddolan from our UX team can provide more feedback regarding the tooltips suggestion but as of now its not officially supported in the implementation.

**Comment by reddolan** [comment]
I recommend using the `title` attribute

**Comment by reddolan** [comment]
We didn't have a way of easily transitioning between a multiline open state and a single-line collapsed state which is why long labels are truncated with ellipsis and the recommendation for concise labels. We understand that long labels may happen and using a `title` attribute would enable a user to see the full label if need be.
