### ISSUE TITLE
Caret position does not increase when typing `

### ISSUE THREAD

**Issue by sjcetx** [vmware/clarity#1911]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Caret position to increase when typing ` character

### Actual behavior
When typing \` the caret position does not increase, subsequent presses of  \` will draw over the original one.  
Can be tested on your own example site
https://vmware.github.io/clarity/documentation/v0.11/input-fields

I have tested it in chrome and firefox

**Comment by adityarb88** [comment]
@sjcetx: This looks like a duplicate of #1521. Please subscribe to that issue for more updates. Thanks!

Closing this as duplicate.
