### ISSUE TITLE
Is posible to use a stack view as collapsable container for display childs components on expand ?

### ISSUE THREAD

**Issue by jromerob** [vmware/clarity#1912]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X ] enhancement
```

### Expected behavior
Use a stack view as collapsable container for display childs components on expand. Thua child component must occupy the 100% width

### Actual behavior
Can use as collapsable container but stack-label is always present

### Environment details

* **Angular version:** 
5

* **Clarity version:**
0.11.0

* **OS and version:** 

* **Browser:** 
all

**Comment by mathisscott** [comment]
Like an accordion?

This question was addressed in https://github.com/vmware/clarity/issues/250
