### ISSUE TITLE
Datagrid pagination causing horizontal scrollbar

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#1919]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Displaying 2 or more pages of results should display links to the subsequent pages but no horizontal scrollbar in the datagrid.

### Actual behavior
A horizontal scrollbar appears if more two or pages of results are displayed.  See enclosed screenshots for example.
[Pagination.pptx](https://github.com/vmware/clarity/files/1690273/Pagination.pptx)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:**  0.11.3

* **OS and version:**  Win 7 
 
* **Browser:**  IE 11|

**Comment by hippee-lee** [comment]
Hi @beaker1977 - I looked at the `pptx` slides but is difficult to see whats going on. Can you replicate the issue in a demo app? Here is a StackBlitz with a simple datagrid to get you started.

https://stackblitz.com/edit/issue-1919

**Comment by beaker1977** [comment]
I forked the demo app and included the model and layout for my datagrid. Stackblizt doesn't quite replicate the issue, ie there is no horizontal scrollbar  but the pagination shows up as dots at least in Chrome (Stackblitz doesn't work in IE 11 it appears). Hopefully you can replicate on your end.

https://stackblitz.com/edit/issue-1919-zznkrk?file=main.ts

**Comment by hippee-lee** [comment]
I see now, Its happening because the last column is hidden. 
See here: https://stackblitz.com/edit/issue-1919-v11

This issue has already been reported. Please subscribe to #1248 for updates.
