### ISSUE TITLE
Changes to error/danger/warning state of icons

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#192]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

so for error colors on icons. here’s what we decided to do:

1) make `.icon-color-danger` same color as `.icon-color-warning`
2) add `.icon-color-error` that is the same color as ^those^
3) update website to include `.icon-color-error` and remove mentions of `.icon-color-danger`

we’re not getting rid of `.icon-color-danger` (yet). just not advertising it.

@Shijir : when you get #1 and #2 done, i’m tasked with updating the website with #3

**Comment by Shijir** [comment]
Completed in [[196](https://github.com/vmware/clarity/pull/196)]
