### ISSUE TITLE
Icon give console erros in datagrid  

### ISSUE THREAD

**Issue by rameshyala** [vmware/clarity#1951]
Hi , i am creating a datagrid with icons something like below image, i got a console errors with this code , when i remove the icons code( <clr-icon shape="rupee"></clr-icon>)  it works fine,so what issue with icons hear. i am using clarity ui V0.11.2

### The datagrid code is 
     <clr-datagrid>
         <clr-dg-column>{{gradeLabel}}</clr-dg-column>
         <clr-dg-column>{{minPayLabel}} (<clr-icon shape="rupee"></clr-icon>)</clr-dg-column>
         <clr-dg-column>{{maxPayLabel}} (<clr-icon shape="rupee"></clr-icon> )</clr-dg-column>
        <clr-dg-column>{{midPayLabel}} (<clr-icon shape="rupee"></clr-icon> )</clr-dg-column>

        <clr-dg-row *clrDgItems="let jg of jobGrades">
            <clr-dg-cell>{{jg.Code}}</clr-dg-cell>
           <clr-dg-cell>{{jg.MinPay | numberFormatter}}</clr-dg-cell>
           <clr-dg-cell>{{jg.MaxPay | numberFormatter}}</clr-dg-cell>
          <clr-dg-cell>{{jg.MidPay | numberFormatter}}</clr-dg-cell>
          </clr-dg-action-overflow>
      </clr-dg-row>
  </clr-datagrid>

Hear is the [plunk](https://plnkr.co/edit/hcEa7H62jG1iJ1yU4IK9?p=preview), in this check the console errors. Thank you.
  

### The console error was 
![error](https://user-images.githubusercontent.com/18004992/35803129-adadf93c-0a98-11e8-94c0-197a513b9216.png)

**Comment by Shijir** [comment]
Thanks, @rameshyala! This issue is related to https://github.com/vmware/clarity/issues/1904. I am closing this one so please follow the issue there now. I will be working on the fix ASAP.
