### ISSUE TITLE
Signpost support for hovering

### ISSUE THREAD

**Issue by hspier** [vmware/clarity#1952]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
The signpost component should have an option to be able to display it on hovering on top of clicking. It should also support a delay before being shown like the tooltip (enhancement request: https://github.com/vmware/clarity/issues/1293).

### Actual behavior
According to the documentation, we must not use a tooltip on components and are instead suggested to use the signpost component to convey information. Also, the tooltip is not supporting rich content where the signpost is. For this reason, none of these components can be used for displaying rich contextual information on hovering a certain component.

**Comment by hippee-lee** [comment]
@hspier - in our usage guidelines we mention: 

`When the information presented needs to stay in view at length (Unlike tooltips, signposts stay in view until the user interacts with another element)
`
That behavior is inconsistent with hide/show on hover.  This is why hover isn't implemented on signposts. 

@lil-kim Am I missing anything? And, is this something we want to consider adding?

**Comment by mathisscott** [comment]
@hippee-lee : You're correct. We don't recommend hover in general across our components due to inconsistent behaviors on touch devices. Additionally, hover on signposts is doubly not recommended due to the content that is expected to be inside of a signpost. Hover on a signpost with scrolling behavior is nightmare fuel.

**Comment by hspier** [comment]
I guess that, after playing a little more with the tooltip, what would be missing is the ability to style the border of the tooltip differently from the background. It works when using a colored background but not if the background is white. I'll create another feature request.
