### ISSUE TITLE
Improper CSS targeting Clarity Icons in Dropdown

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#1957]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Clarity Icons in Dropdown should look pleasurable.

### Actual behavior

Clarity Icons are not targetted properly in dropdowns. As a result, all icons placed inside a dropdown component overlapped on top of each other. Please see the issue here: 

<img width="172" alt="screenshot 2018-02-05 23 21 26" src="https://user-images.githubusercontent.com/3958008/35846422-721cc898-0acb-11e8-8b28-98aa80f732f2.png">

https://stackblitz.com/edit/clarity-light-theme-v11-zfx7vw?file=app/app.component.html

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
Resolved by #2012
