### ISSUE TITLE
Clarity Filters removing checkbox selection

### ISSUE THREAD

**Issue by jaypillai** [vmware/clarity#1963]
**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
https://vmware.github.io/clarity/documentation/v0.11/datagrid/full

User has to select multiple items in table. He goes for [clrDgItem]  and [(clrDgSelected)] . The table has filters implemented. The user selects first two rows, he does column filter after that. All the selections made earlier must be retained

### Actual behavior
In this case all the selections are removed.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

Issue can be reproduced in demo example of clarity 
https://vmware.github.io/clarity/documentation/v0.11/datagrid/full

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
We actually actively reset the selection when filters change because the state of what is selected can quickly become confusing. If you select 3 items, and then filter it so only two are visible, should the third item also be selected or not? If the user then hits a 'delete' button, should it delete only the visible items or all selected ones? More importantly, how do they unselect an item that isn't visible? Therefore UX determined it was best to clear the filters to avoid this ambiguity. 

I'm going to close this, but feel free to share more about your expectations here, but I don't expect us to make a change to the default behavior here.

**Comment by jaypillai** [comment]
But this contradicts the reason why we should have filters in the very first place. In this scenario where we have multi selection with pagination, the user selects a row from page 1 and then wants to selects some other data from page 11, he uses filters to get that row, after selecting the row, the initial selection is removed. This is defineltely a bug. Not sure whu this is made the default behaviour. 

Adding or editing anything in filter texts removes all selections. this definetely should not be the expected behaviour.

**Comment by gnomeontherun** [comment]
That might be true in your case, but it makes assumptions that the user will understand that non-displayed items are still active. Our reasoning is that it is detrimental to UX  if you select something and then are able to hide it. If you are deleting a set of records, and the filter shows only 3 items but 5 more are selected but hidden, what does the Delete button do? 

Also reference this https://github.com/vmware/clarity/issues/484#issuecomment-285419495

Now, we don't prevent you from persisting the selected items on your own in some manner and acting upon it, but the UX concerns about a user knowing what items are actually selected in a datagrid are too high to make this a default behavior.

**Comment by maijaz01** [comment]
@gnomeontherun you mean if I have 3 rows that I have selected and after that, if I apply the filter on top of that so maybe according to filter it match only 2 rows, and only 2 rows will be visible and the 3rd one will be selected but not displayed user may not aware that the 3rd value is there in that grid.
So what I say is there any possibility that, we must display value which is selected and merge the result of a filter that would solve all the problem

Please let me know your opinion

**Comment by gnomeontherun** [comment]
@maijaz01 I'm not sure I understand your perspective, but we do have an open issue to change this default #2342.

**Comment by maijaz01** [comment]
I mean suppose I have selected 3 rows from checkbox, then I do a filter with a name so the filter gives me some result, so my suggestion is can we merge both the filter.
1 checkbox + filter result

**Comment by gnomeontherun** [comment]
Please use #2342 for any further discussion about selection persistance with filtering. That is our expected solution.

**Comment by maijaz01** [comment]
Thanks @gnomeontherun for pointing out at r8 place
