### ISSUE TITLE
[CORE} Fix tslint

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#1970]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

tslint is not running as expected.

### Actual behavior
tslint will run as expected and report errors

Placeholder for the incoming pull request that fixes this.

**Comment by adityarb88** [comment]
Along with tslint we also need to fix clang:format. After I run clang:format, the tests take a lot longer to run.
