### ISSUE TITLE
Disabled buttons are hard to read with the Clarity dark theme.

### ISSUE THREAD

**Issue by KevinABoucher** [vmware/clarity#1973]
**Select one ...**  (check one with "x")
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
We expect disabled buttons to be legible with the dark theme enabled.

### Actual behavior
Disabled button is hard to read with dark theme.

### Reproduction of behavior
https://clarity-dark-theme-v10-bqwdxu.stackblitz.io

### Environment details

* **Angular version:** v5.1.3

* **Clarity version:** 10.1.1

* **OS and version:** Mac Latest

* **Browser:** Chrome Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by reddolan** [comment]
Primary looks good, but the Small one looks like it might be a bug. Looking into it further

**Comment by reddolan** [comment]
It's a bug for sure, @hippee-lee and @lil-kim confirmed it is

**Comment by hippee-lee** [comment]
@KevinABoucher - can you share the stackblitz url so I can see the source? I'm not having any luck replicating the `I should be able to read this better` button in the Clarity button demos.
