### ISSUE TITLE
[UX] Theme switcher in the clr-header

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [vmware/clarity#1976]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
[x] question
```
I am planning a theme switcher for my webapp to switch between the light and dark themes (only 2 themes for now). I am planning to put the switcher somewhere on the header. Is there any UX guideline regarding this?
I have a few ideas but I am not sure if they are user friendly
* Put a toggle button. Its a single click action but might look incredibly odd in the header.
* Put an icon, sun and moon. But the problem is I am always confused on other sites using this if clicking on the sun is supposed to turn on the light mode or the sun represents that the light mode is active. Also Clarity Icons lack a sun and a (crescent) moon.
* A dropdown. The Dropdown can list the names of the themes (might look cumbersome) or can show a colour patch. This is the only option which supports more than 2 themes.
### Expected behavior

Great UX while theme switching.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.2.x

* **Clarity version:**0.11.x

* **OS and version:** Win10

* **Browser:** [all]

**Comment by adityarb88** [comment]
@reddolan @lil-kim could you please take a look at this?

**Comment by gnomeontherun** [comment]
Here is an example I built previously that might give you something to work with. https://stackoverflow.com/a/47640096/3969946

**Comment by SayakMukhopadhyay** [comment]
@gnomeontherun I am the same guy in the comments 😄 . Your solution is like option 3, but I was wondering if there is a more UX friendly way of doing this. I ask this because I know the standards VMWare has for UX are top notch and some advise regarding theme switching UX would be greatly appreciated.

**Comment by SayakMukhopadhyay** [comment]
I see as per #1787 Sun and moon is added to the icon set, mainly for theme switching as per https://github.com/vmware/clarity/issues/1787#issuecomment-357360292 . Does that mean that Light/Dark theme switching is recommended to be done by Method 2 (see original issue). If so, what should the icon represent? The current theme or the theme that can be switched to?

**Comment by hippee-lee** [comment]
@SayakMukhopadhyay - In Jeremey's example [here](https://stackblitz.com/edit/clarity-theme-switcher?file=app%2Fapp.component.ts) he uses a drop down in the header. I've also seen a theme switcher implemented with a slider button. Either way the technique in Jeremy's example will be the same for both. If your app seems like a better fit for one or the other UI widgets for switching I'd use that.

**Comment by SayakMukhopadhyay** [comment]
So, there is no particular UX approach favoured by the team at VMware. Ok, thanks! I will close the issue then.

**Comment by mathisscott** [comment]
Hi @SayakMukhopadhyay

The Clarity UX team hasn’t made a recommendation on a theme switcher in the header. It is something that is on our radar however.

**Comment by SayakMukhopadhyay** [comment]
Thanks for the response @mathisscott . I will keep watching the repo for updates!

**Comment by mathisscott** [comment]
This is something that would be decided based on a product's use case as some products may have more than two themes. Other products may have too many items in their header to accommodate a theme switcher and may need to place that functionality in a panel or deeper in their application's settings.

So this is not something we would make a recommendation on. If it makes sense to have theme switching in your header, using a toggle for an app with two and only two themes makes sense. Using a dropdown for apps with more than two themes makes sense.

Thanks!
