### ISSUE TITLE
[NG] Datepicker - MVP

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1983]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

**Datepicker Component MVP Features:**
1. Locale Support
2. Support to render the Calendar based on first day of the week
3. Navigation support for previous and next months
4. Navigation support for previous and next decade
5. Keyboard Navigation
6. clrDate Input/Output for Javascript Date objects.

MVP will use the HostWrapping Module.

**API:**
1. Host Wrapped:
```<input type="date" clrDate>```

2. Wrapper provided by user:
```
<clr-date-container>
   <input type="date" clrDate>
</clr-date-container>
```

**Comment by sdurnov** [comment]
I would also suggest period selection

**Comment by adityarb88** [comment]
@sdurnov: Thats in our plan but its not in scope for the MVP. For more details please read this issue: https://github.com/vmware/clarity/issues/474

**Comment by sdurnov** [comment]
Just for info: do you accept pull requests with implementation of feature requests like this one?

**Comment by mathisscott** [comment]
@sdurnov
The v1 datepicker is already in flight. I believe there is already a PR for it in review. 

After that is merged in, however, you could pick up the range picker feature if you want but I recommend chatting with one of our developers before you start so they can give you a heads up on our best practices and work out the API before you get started.
