### ISSUE TITLE
[UX] Datepicker Min/Max Dates

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1984]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

Add support for the following features to the Clarity Datepicker Component:
1. Min Dates
2. Max Dates

How it works on Chrome:
https://jsfiddle.net/rqjboweo/

**Comment by adityarb88** [comment]
cc: @reddolan

**Comment by gnomeontherun** [comment]
This is not in our list of priorities right now, follow this ticket to see when it becomes prioritized.

**Comment by kalpeshhpatel** [comment]
Hey @gnomeontherun , do we have any update on this ask?

**Comment by gnomeontherun** [comment]
No updates, it hasn't been prioritized based on the other work in flight.

**Comment by juanmendes** [comment]
I have been thinking about picking this up. I'm assuming we mean restricting clicking dates and navigating to invalid dates in the popup, not the actual text input. How do you guys go about creating a spec for a feature?

**Comment by hippee-lee** [comment]
FYI - here is the design spec in the original design  issue for the component (under Date Range Picker): https://github.com/vmware/clarity/issues/474

For Min/Max API I would start with the relevant parts from [DEVELOPMENT_CONTRIBUTIONS](https://github.com/vmware/clarity/blob/master/DEVELOPMENT_CONTRIBUTION.md)

Start w/ some examples of how the an input with the current `clrDate` component would/might look by adding in a description of the affect or changes to the current API and answering the relevant questions from the Implementation Plan` section.

**Comment by gnomeontherun** [comment]
Also it would be good to review a few other datepicker components and see how they handle some details. I'm wondering things like if you can't select a date greater than today, can you go to a month/year beyond the current day? How do we denote a disabled item? Are there any accessibility issues when we disable a day/month/year? The design spec is old enough that we should also question some of the details if we see concerns.

**Comment by AlexMarcuBytex** [comment]
Im currently working on this so you can assign me.

**Comment by juanmendes** [comment]
@gnomeontherun Are you going to spec the work in the style of  https://github.com/vmware/clarity/issues/474 ?

**Comment by gnomeontherun** [comment]
@juanmendes That is the main inspiration but this specific feature doesn't have a design for this specific feature. We have to review it with design, but the functionality is pretty limited in scope and shouldn't impact anything else.

**Comment by Vaishak** [comment]
is Time Picker also included in this or is there a separate thread where I can follow it's progress?
