### ISSUE TITLE
[NG] Date Range Picker

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#1985]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

Create a Date Range Component based on the details specified in #474.

**Comment by KANekT** [comment]
How long will this feature be developed?

**Comment by mathisscott** [comment]
@KANekT 
At present, this feature is the very next one on our list for the date picker family.

We are wrapping up the date picker MVP work right now and we will have a few cycles where we focus on stabilizing that code (if we need to).

We have other new components that require our attention but I'm confident we will be revisiting this one after them. As far as how long it would take to build the date range picker? There are too many variables there for me to give any estimate with high confidence.

**Comment by spetri** [comment]
@mathisscott it's been a few months, has there been any updates to this ticket?

**Comment by gnomeontherun** [comment]
The work on selecting a range hasn't been prioritized, but since the base date picker is available you could approximate it by using two date pickers as a workaround for now.

**Comment by RNACode** [comment]
+1

**Comment by BigBadaboom** [comment]
dup of #474?

**Comment by mathisscott** [comment]
At present, we have a few competing designs that have emerged for this feature. We need UX to reconcile the different designs so we know which UX is the way forward. Assuming that can be addressed in the short term, we are considering this feature for the 5.0 release.

**Comment by erabl-identos** [comment]
Will this feature also support a direct way to select a specified time range (year, month, week) without having to pick two individual dates?

A usecase for this would be to show all activities/sales from last February, where the user simply selects the desired month.

Currently there is no workaround to achive this feature, as it is not possible to [filter out](https://github.com/vmware/clarity/pull/4390) all dates except the first and last one of a time range. Allowing to select two arbitrary dates first and validating them afterwards is not very user-friendly, as the user does not know which selections will be accepted beforehand and is only confronted with an error message after he/she made the wrong choice.

The user experience could be improved by guiding the user towards the correct selection by only showing valid time ranges in the first place.

If the time range is year the existing clarity datepicker can be reused, and upon clicking on a year the datepicker closes and sets the timerange to the first/last of the year.
<img src="https://user-images.githubusercontent.com/17832299/95009160-1f5f6e00-0620-11eb-8ea7-9672cd0145c7.png" width="200px"/>

For the time range month a similar approach could be used, but one would need a way to move to the next/previous year.
<img src="https://user-images.githubusercontent.com/17832299/95009272-fbe8f300-0620-11eb-9fd9-4dcfcf9c82e2.png" width="200px"/>

The selection of a calender week would probably require to show the week number next to each row in the "day-selection view" with the individual days disabled and clickable week indexes.
<img src="https://user-images.githubusercontent.com/17832299/95009447-78c89c80-0622-11eb-9486-46153d067ce5.png" width="200px"/>


The NPM package [angular-bootstrap-datetimepicker](https://www.npmjs.com/package/angular-bootstrap-datetimepicker) showcases an approach where the developer sets a `maxView` and `minView`, where `minView` determines the level on which the datepicker closes and emits the selected time range. Have a look at this [demo Stackblitz](https://stackblitz.com/edit/github-gzez6k?file=src/app/home/home.component.ts).

**Comment by mathisscott** [comment]
@erabl-identos 
That feature is not currently under consideration but we do need another design pass here before implementation. So thank you for the suggestion/contribution.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
