### ISSUE TITLE
Datagrid columns width not calculated correctly

### ISSUE THREAD

**Issue by Dead96** [vmware/clarity#1986]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When I use Datagrid Component with Pagination and Single Row Action, the columns width must be calculated depending on the properties (Actual behavior of Datagrid without Pagination)

### Actual behavior
When I use Datagrid Component with Pagination and Single Row Action, the columns width is not calculated correctly. I think it depends on using *ngFor instead of *clrDgItems, but it is necessary for the correct working of Pagination.

### Reproduction of behavior
https://plnkr.co/edit/aDhXHhsKovR4IUSwnDYU?p=preview

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.x

* **OS and version:** [Win10]

* **Browser:** [all]

**Comment by youdz** [comment]
That's definitely a bug, it reminds me of #1294 (which was fixed a while back, so maybe we missed something).

I took the liberty of simplifying your plunker (the whole refresh part didn't do anything), and adding an example to show that `*clrDgItems` works fine, it's a combination of `*ngFor` and row actions: https://plnkr.co/edit/3KqpMQaN3DIozksTF9rv?p=preview

**Comment by xucito** [comment]
This also occurs if the last column is `[hidden]`

**Comment by youdz** [comment]
Fixed by #2670.
