### ISSUE TITLE
Is it possible to add signposts to each of the options of Select component?

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#1987]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
![image](https://user-images.githubusercontent.com/12848838/36154997-2b366644-10f9-11e8-8b3f-0bb8999a06eb.png)

### Actual behavior
I'm trying to wrap the option in signposts. But it is not working as expected. select is ignoring the option itself. I believe this behavior will be same for tooltip component as well.
https://stackblitz.com/edit/clarity-light-theme-v11-81ivew

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-81ivew

### Environment details

* **Angular version:** 5.2.1

* **Clarity version:** 0.11.x

**Comment by adityarb88** [comment]
@shravansofts: The only permitted content in a `select` is `option` or `optgroup`. More info here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select. 

![image](https://user-images.githubusercontent.com/1426805/36155527-95aafaf0-10a2-11e8-9733-3f76a212f00c.png)


Native select elements do not support anything other than that. Closing the issue based on the above info. Please let us know if you have any more questions.
