### ISSUE TITLE
Clarity website: "Updated" tag on components isn't helpful

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#1988]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```
### Steps to reproduce

- Navigate to the Clarity website
- View the Documentation section
- Note a component item with "Updated" tag visible
- Click the component

### Expected behavior

Component should show what's been updated somewhere

### Actual behavior

Component doesn't show anything about what's been updated, so the user has to hunt and guess

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/v0.11/datagrid/structure

### Proposed solution
In addition to "Examples & Code" and "Design Guidelines", components with the 'Updated' tag should have a "What's New" tab that just lists the recent changes to that given component.  This assumes the release note changes are useful and meaningful, but it's at least better than hunting and guessing.

**Comment by gnomeontherun** [comment]
We've essentially stopped doing this. I'm going to close this.
