### ISSUE TITLE
Upgrade Metropolis (our font) to Release 8

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#199]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

There is a new release of Metropolis. We should upgrade to the latest (release 8) of Metropolis: https://github.com/chrismsimpson/Metropolis/releases/tag/r8

**Comment by adityarb88** [comment]
Removing the milestone until we can fix the issue mentioned over here: #197
