### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#1995]
We need to update and test against Angular 6.

* [ ] Ensure schematics support new CLI config format
* [ ] Update RXJS
* [ ] Bump minimum versions in packages

**Comment by exequiel09** [comment]
Tried and encountered some broken rxjs imports due to relatively new rxjs version used in Angular v6. Can't properly test since some dependencies are not yet forward-compatible with the new version of Angular.

**Comment by amemifra** [comment]
News about the topic?

**Comment by hippee-lee** [comment]
@amemifra - take a look at issues #2239 and #2242 they have details about using `rxjs-compat` to address this topic.
