### ISSUE TITLE
Multi Select component

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#2001]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Would be great to use it. Currently, in my project, I need this component.
https://www.primefaces.org/primeng/#/multiselect

### Actual behavior

Currently It's possible to create custom own component, but will be good to have it out-of-the-box.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@pumano: We already have an issue open for this. Please subscribe to https://github.com/vmware/clarity/issues/248 for more updates.

Closing this as duplicate.
