### ISSUE TITLE
No clrFilterValueChange events?

### ISSUE THREAD

**Issue by avellanas** [vmware/clarity#2004]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Changing the value of a default string filter raises a clrFilterValueChange event.

### Actual behavior
No event is raised.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v10-yh9hrb

This logs to the console if the clrFilterValueChange event is raised on any of the three columns. Use any of the filters with any string, nothing is logged. 

For comparison, it also logs on clrDgSortedChange events, which can be seen by sorting any of the columns.

### Environment details

* **Angular version:** 4.3.4

* **Clarity version:** 0.10.23, 0.10.24

* **OS and version:** Windows 10 Enterprise

* **Browser:** [Chrome  64.0.3282.167 | Firefox 47.0.2 | IE 11]

**Comment by aaronfrost** [comment]
Same here. I am trying to save the filters to localstorage... but I can't capture them.
