### ISSUE TITLE
Update docs for datagrid multiselect

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#2006]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
https://vmware.github.io/clarity/documentation/v0.11/datagrid/selection

### Actual behavior
Datagrid multiselect not working due to some module error.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-7x1m99?file=app%2Fapp.component.html

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Hi @shravansofts - I don't seem to be able to replicate a module error with the stackblitz you provided. It runs and I don't see any errors. Can you provide more help so the issue can be replicated? 

Perhaps I am I missing something from the issue report? 

Here is a quick video with the stackblitz you provided. 
![issue-2006](https://user-images.githubusercontent.com/433692/36492727-ac2867ea-16e2-11e8-97cb-3d7aa683d0b0.gif)

**Comment by youdz** [comment]
To add a little bit, I see 2 problems in your stackblitz:

1. You're binding `[(clrDgSelected)]="selected"`, but your property on the component is called `selectedRows`.
2. You are not initializing you `selectedRows` property, which is something we need. It should be: `selectedRows: any[] = [];`

Here is a working Stackblitz: https://stackblitz.com/edit/clarity-light-theme-v11-bn7kva?file=app%2Fapp.component.ts

**Comment by shravansofts** [comment]
@youdz Thanks for the clarification. Documentation is not specifying this initializing aspect.
To avoid this kind of queries we need a plunker link for each component demo. I have raised a separate issue for the same [here](https://github.com/vmware/clarity/issues/2008).

I observed a typo in the documentation of selection as shown below. Please correct it.
![image](https://user-images.githubusercontent.com/12848838/36518605-303fada2-17ad-11e8-8d7c-d26a2c00173a.png)
