### ISSUE TITLE
Update Bootstrap 4 dependency to final release

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2011]
Currently it's Alpha 5, please upgrade to final release.

**Comment by adityarb88** [comment]
@sdurnov: Please refer to these issues for more info: https://github.com/vmware/clarity/issues/1899, https://github.com/vmware/clarity/issues/1964

We are planning on moving off of Bootstrap. More details here: https://github.com/vmware/clarity/issues/1531

Closing the issue based on the above info but please feel free to reopen the issue if you have more questions or any feedback. Thanks!

**Comment by sdurnov** [comment]
Honestly - this is terrible idea to get rid of Bootstrap. Bootstrap is the only mature and popular full-stack scss library, and many teams will use its set of tools no matter which JS framework and UI library they use. Bootstrap is one of primary reasons why our team had chosen Clarity.
Guys, no need to reinvent a bicycle here. Obviously, you won't have resources to make something more functional than Bootstrap 4 utilities, would you?! Don't lock us to something less functional. Clarity has many controls, but it won't cover 100% of use cases. Teams will still need Bootstrap, and if you drop it for something else, we'll have to maintain both your style system variables plus Bootstrap variables, which will make projects harder to maintain.

I hope you'll hear me.

Clarity is one of very few really good UI libraries on the market (even outside of Angular world - I was looking at popular React UI libs and all of them aren't good enough for enterprise projects). It's faster and more visually accurate, than most of UI libs on the market. Don't make it too specific in terms of CSS. I don't even know what to choose if not Clarity. Angular Material is still too buggy and not functional enough. Kendo UI is also too slow and ugly. I don't even want to say anything about PrimeNG and ag-grid.
All bootstrap wrappers are also crap, as they use Bootstrap controls (which were terrible since v.1) and doesn't provide data grid and treeview controls.

**Comment by mathisscott** [comment]
This is great feedback, @sdurnov. 

The Bootstrap dependency removal is not currently in our near-term plans. We will take your points into consideration before we make any commitment to that.

Thanks!

**Comment by ronnyek** [comment]
seems to  me like its a reasonable end goal to incorporate whats valuable and not depend on bootstrap. That being said, does it make sense to depend on an alpha of bootstrap until then?

**Comment by sdurnov** [comment]
@ronnyek if you already decided and won't change your mind, then, I guess, the sooner you wipe out Bootstrap, the better it would be for devs. I think nobody would like to invest in development and then spend resources again to respond to breaking changes.

**Comment by ronnyek** [comment]
Wait, what? I'm not specifically partial to bootstrap necessarily, but there is a hard depdendence on the alpha because of moving of scss files in bootstrap. All I am saying is clarity talks about moving away from bootstrap as a potentially longer term goal... so is clarity going to continue forward depending on alpha.5 until bootstrap is gone?

**Comment by adityarb88** [comment]
@ronnyek: Yes, for the near future we are going to depend on alpha.5. We use Bootstrap 4 mostly for the grid. Moving to the final BS4 release means a breaking change in the grid. If I remember correctly, the only changes in alpha.6 were name changes. We don't want our users to unnecessary go through a breaking change for class name changes. The major reason for moving to the final release would be in case the grid in alpha.5 is missing some important features that the final release has. I haven't looked at the final grid and am not sure if we are missing any important features but we haven't received any requests/issues for the current grid that we support.

**Comment by ronnyek** [comment]
I think that's fair, thanks for explanation on that one.

**Comment by sdurnov** [comment]
@adityarb88 the problem here is that many teams (I think) will use Bootstrap, because it covers 100% needs related to layout and typography. We can live with separate set of scss variables for Clarity, but what's important - is to be able to have both Clarity and final Bootstrap without conflicts, at least. After thinking on that topic, I can agree that some teams would use something different for layout, so I guess removing Bootstrap dependency is probably a good idea.
Then I just need to make sure that final Bootstrap and Clarity will live together without major broblems.

**Comment by mathisscott** [comment]
@sdurnov 
That is one of the motivations behind removing our Bootstrap dependency. Right now, we pretty much stomp on anyone who is trying to use both Bootstrap and Clarity. If we properly sandboxed our styles and such, then it would be less of an issue for teams to use parts of Bootstrap alongside our components (even though we don't advise that or want to invest lots of resources addresses conflicts that Bootstrap would introduce).

**Comment by ronnyek** [comment]
Seems like if we're trying to avoid fallout of bootstrap reliance, seems like the earlier you ditch bootstrap the better... can we get a ballpark (real general time frame) estimate? Like in a couple years, or a couple months?

**Comment by mathisscott** [comment]
@ronnyek
Well, not a couple of months. Removing the Bootstrap dependency isn’t on our near term roadmap. I can’t give an exact date. Because our priorities are always in flux. 

But it isn’t two years out either. 

No earlier than September of this year. Likely no later than October 2019.
