### ISSUE TITLE
[question] how to set clrDgField for an array of strings for dgItem

### ISSUE THREAD

**Issue by jeado** [vmware/clarity#2013]
I have `listNames` which is array of strings and I`d like to sort it so I need to put  [clrDgField] on <clr-dg-column>.

but what value can I use ?

```
<clr-datagrid>
    <clr-dg-column [clrDgField]="?????">listName</clr-dg-column>
    <clr-dg-row *clrDgItems="let listName of listNames" [clrDgItem]="listName">
      <clr-dg-cell>{{ listName }}</clr-dg-cell>
    </clr-dg-row>
  </clr-datagrid>
```

**Comment by gnanasekhar504** [comment]
use the object keys like [clrDgField]="'listName'"

**Comment by kalpeshhpatel** [comment]
Hey there, do we have any update for this?

Thanks

**Comment by jeado** [comment]
@gnanasekhar504 but there is no key. listName is a string not a object

**Comment by mathisscott** [comment]
@youdz ^

**Comment by youdz** [comment]
If your list of models is just a list of string, then I have no idea why you're using a datagrid. I will just have a single column, the use case makes no sense to me.

If you really want to do this, you can always use `[clrDgSortBy]` and `<clr-dg-string-filter>` as documented [here](https://vmware.github.io/clarity/documentation/v0.11/datagrid/custom-sorting) and [there](https://vmware.github.io/clarity/documentation/v0.11/datagrid/string-filtering), but we can't change `clrDgField` to adapt to a use case that we can't understand.
