### ISSUE TITLE
Custom Datagrid Filters: Error in example code on website

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2017]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

`MyFilter` should implement `ClrDatagridFilter`.

### Actual behavior

`MyFilter` implements `Filter`.

### Reproduction of behavior
Visit website: [Link](https://vmware.github.io/clarity/documentation/v0.11/datagrid/custom-filtering)

Here you see the following example code:

```
import {ClrDatagridFilterInterface, ClrDatagridFilter} from "@clr/angular";

@Component({
    selector: "my-filter",
    /* ... */
})
class MyFilter implements Filter<User> {
    constructor(private filterContainer: ClrDatagridFilter) {
        filterContainer.setFilter(this);
    }
    changes = new Subject<any>();
    isActive(): boolean { /* ... */ }
    accepts(user: User) { /* ... */ }
}
```

**Comment by adityarb88** [comment]
@dorthrithil: Actually I think it should implement `ClrDatagridFilterInterface<User>`. Will wait for @youdz to confirm.

**Comment by youdz** [comment]
@adityarb88 is right on that one, you want to implements the interface.
