### ISSUE TITLE
[Datagrid] clDgRowSelection attribute naming

### ISSUE THREAD

**Issue by jewway** [vmware/clarity#2019]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Why only clDgRowSelection attribute prefix naming is different from other attribute ?

Expected **clrDgRowSelection**.

![image](https://user-images.githubusercontent.com/3501899/36714165-02aefb4a-1bcc-11e8-9854-17a75e6900e3.png)

[datagrid.ts line:127](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid.ts#L127l)

### Environment details

* **Angular version:** 5.2.6

* **Clarity version:** 0.11.6

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@jewway: `clrDgRowSelection` enables the row selection mode where you can click anywhere on the row to select it. 

![test](https://user-images.githubusercontent.com/1426805/36790860-2a7e6384-1c64-11e8-9421-b8b3dadc4620.gif)

More info here: https://vmware.github.io/clarity/documentation/v0.11/datagrid/selection

Closing the issue based on the above info. Please feel free to reopen the issue if you have any more questions or feedback. Thanks!

**Comment by jewway** [comment]
I may not express clearly , I refer to the property name is misspelled in , missing word "r".

**Comment by adityarb88** [comment]
@jewway: Apologies. I missed that. Yes ideally it should be prefixed with `clr`. I will check with @youdz if there is a reason for this or if this was just a typo. If it was a typo may be we can create a duplicate Input and deprecate this one.

**Comment by youdz** [comment]
Yes, typo, thanks for raising this. I'm guessing that means we're missing a unit test for it too? Either that or the unit test also has a typo...
