### ISSUE TITLE
Tooltip with long text is not shown properly

### ISSUE THREAD

**Issue by swapnilsvaidya1412** [vmware/clarity#2020]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

If tooltip is having long text, then tooltip height/width should gets adjusted automatically to accomodate all the text
### Actual behavior

If tooltip component is having long text, then tooltip text is not shown properly.
 Text overflows the tooltip element and if it is used in card then scroll bar appears on the card.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://stackblitz.com/edit/clarity-dark-theme-v10-efelwd?file=app%2Fapp.component.html

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnanasekhar504** [comment]
Use tooltip-lg and break the long words.

**Comment by adityarb88** [comment]
@swapnilsvaidya1412: 
For now you could add this style at your end to get this fixed immediately. We will add it at our end too:

```
.tooltip-content {
  word-break: break-word;
}
```
Info: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break
Demo: https://stackblitz.com/edit/clarity-dark-theme-v10-fndbkb?file=app/app.component.css

BTW our UX recommendation is that you use tooltip for a line of text only. Adding a lot of content in a tooltip is not recommended.

**Comment by adityarb88** [comment]
@swapnilsvaidya1412: I missed the discussion that our team did earlier regarding this. We will not be adding styles which break a word to wrap into multiple lines as this might cause unexpected behavior. For more info please read this: https://github.com/vmware/clarity/issues/1146#issuecomment-313105291

We recommend that you increase the size of the tooltip to let the content fit correctly or use the style we mentioned above in your CSS.

Closing this issue based on the above info. Please feel free to get in touch with us if you have more questions/feedback.

**Comment by swAucxis** [comment]
Instead of defining a fixed width. We would prefer an auto width solution. And the xs, sm, md, lg determines the max width.
