### ISSUE TITLE
Size and scrollbar issues with Datagrid embedded in Card

### ISSUE THREAD

**Issue by aditorium** [vmware/clarity#2032]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

We have created cards which can be resized and moved around by the user. In some of these cards, we want to embed a Datagrid which is supposed to "fill" the available space (e.g. a card-block). In many cases, the Datagrid columns / rows will not fit into the available space, so I would expect to see scrollbars as follows:

- a horizontal scrollbar which moves the `datagrid-column`s but NOT `datagrid-foot` (I would like that the "Show Columns" button and other information stay visible)

- a vertical scrollbar which moves the rows in `datagrid-body` (but NOT `datagrid-head`)

### Actual behavior

The Datagrid grows outside the card. The [trick with "height: 100%"](https://stackoverflow.com/questions/46375081/clarity-is-there-a-recommended-way-to-make-clr-datagrid-take-up-all-available-v) doesn't seem to work in my scenario.

If I "force" the Datagrid to a specific size via CSS, I get a horizontal scrollbar which seems to move the whole Datagrid including `datagrid-foot`. Only when I scroll to the extreme right, I will see the vertical scrollbar (which BTW does not react to mouse clicks in Edge, at least in my stackblitz example).

Perhaps I am doing something wrong (due to lack of experience), but would appreciate it if someone would look into the issue.

### Reproduction of behavior

* [Stackblitz Example](https://stackblitz.com/edit/clarity-light-theme-v11-h5xgjg?file=app%2Fapp.component.html)

### Environment details

* **Angular version:** 5.2.1

* **Clarity version:** 0.11.1

* **OS and version:** 

* **Browser:** all

**Comment by hippee-lee** [comment]
Hi @aditorium - This issue has been reported before. Please subscribe to #1217 for updates.

Additionally, I am currently implementing a pinned column feature for the Datagrid component that I believe will address issue 1217. Please keep an eye out for that. 

Closing this based on the above. If you feel this issue is different please let me know.

**Comment by aditorium** [comment]
Thanks @hippee-lee. Yes, issue #1217 describes pretty much the same problem, sorry I didn't see it before submitting a new one.

However, I still haven't found a way to make the Datagrid "fill" the available space inside of a card-block. Any ideas would be appreciated.

**Comment by hippee-lee** [comment]
@aditorium
For your question about filling available space, can you create a [stackblitz](https://stackblitz.com/edit/clarity-light-theme-v11) with what you are trying to do? And, would you mind asking a question on StackOverflow and tagging it with `vmware-clarity` so it can be answer it there?

**Comment by aditorium** [comment]
@hippee-lee 
FYI, I have posted the question on [StackOverflow](https://stackoverflow.com/questions/49218439/datagrid-how-to-fill-available-space-inside-card-block)
 (including a link to the StackBlitz example)
