### ISSUE TITLE
Angular cli build error:  Error: Internal error: unknown identifier undefined at Object.importExpr$$1

### ISSUE THREAD

**Issue by tarquinrex** [vmware/clarity#2033]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```
### Expected behavior
Should build with --aot and --prod flags

### Actual behavior
When doing an ng build --aot --prod it fails with error "Error: Internal error: unknown identifier undefined at Object.importExpr$$". This is resolved when I rollback to version 0.11.6.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x
@angular/cdk: 5.2.3
@angular/cli: 1.7.2
@angular/language-service: 4.4.6
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack: 3.11.0

* **Clarity version:**
> 0.11.6 

* **OS and version:** 
Windows 10 x64

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Comment by dorthrithil** [comment]
I had the same issue yesterday after doing an npm update. Clarity was updated to `0.11.7` by that. It took me some time to figure out that the Clarity team actually released a patch for this issue, so if you update to `0.11.7-patch.1` this error should be resolved.

**Comment by hippee-lee** [comment]
@tarquinrex, yes @dorthrithil is correct we had to issue a patch for in improper import that breaks during aot compilation. 

Here is the release note: https://vmware.github.io/clarity/news/0.11.7-patch.1

running ```npm update``` should get you the latest versions of Clarity. 
Please re-open and let me know if you still have compilation issues.

**Comment by sirajc** [comment]
Changing import to following, fixes the error
```
import { LoadingListener } from "../../utils/loading/loading-listener";
import { ClrLoadingState } from "../../utils/loading/loading";
```

Should I create a new issue, to track the fix
cc: @youdz

**Comment by hippee-lee** [comment]
Thanks for reporting this @sirajc. The issue you are seeing is similar to this issue. I'll create a new issue to track this one and we will get a fix for it out this week.

**Comment by Ram-SR** [comment]
Anyone looking for help and if your issue is not about services as injectable, the other case will be your components. Remove default export from your parent components/parent abstract classes. That fixed my issue
