### ISSUE TITLE
Can Wizard add something above header?

### ISSUE THREAD

**Issue by wghglory** [vmware/clarity#2034]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

I want to show a message above the wizard header. I put my markup before `<ng-template clrPageTitle>Something</ng-template>`. I expect the markup is placed before or into modal-header div.

### Actual behavior

but I noticed that the markup is in a div with modal-content.

### Environment details

* **Angular version:** 4.4.4

* **Clarity version:** v.10.8

* **OS and version:** Mac 10.13.1

* **Browser:** [Chrome]

**Comment by wghglory** [comment]
I made a stupid question I guess. Just realized that I can put my markup inside `<ng-template clrPageTitle>`

**Comment by adityarb88** [comment]
@wghglory: You will have to do this with custom CSS at your end. I have created a stackblitz which demos that: https://stackblitz.com/edit/clarity-light-theme-v11-efpgxj?file=app/app.component.css

Closing the issue based on the above info. Please feel free to reopen the issue if you have more questions.

**Comment by adityarb88** [comment]
The wizard page title itself is at the top and since the content is projected at the top, you can project the header using the page title. You will just have to make sure that the CSS is adjusted to your needs. The extra header above the title won't be supported in Wizards by default.

**Comment by wghglory** [comment]
@adityarb88 Thanks so much! This is very helpful.
