### ISSUE TITLE
[UX] Design for Invalid Dates in the Datepicker

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#2045]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Actual behavior

When the user enters an invalid date in the datepicker, the calendar opens with today's date because the entered date is invalid. But there is no indication to the user that the entered date is invalid. We need UX input on what to do in this case.

![image](https://user-images.githubusercontent.com/1426805/37099397-296efdb6-21ee-11e8-9c16-619416d46327.png)

### Expected behavior

Design for invalid user inputs in the datepicker.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
cc: @reddolan

**Comment by reddolan** [comment]
It would be good to figure out decent solution to this

**Comment by gnomeontherun** [comment]
This is resolved assuming that the Angular input has proper form validations set on the component. I'm going to close this as fixed.
