### ISSUE TITLE
Checkbox tree error

### ISSUE THREAD

**Issue by nithinkarthik6** [vmware/clarity#2050]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Check box tree should appear without any error
### Actual behavior

Tree view is appearing properly but when i use [(clrSelected)] input on the root node it shows a error Can't bind to 'clrSelected' since it isn't a known property of 'clr-tree-node'.
1. If 'clr-tree-node' is an Angular component and it has 'clrSelected' input, then verify that it is part of this module.
2. If 'clr-tree-node' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
### Reproduction of behavior

When using checkbox tree view the error occurs in browser console

### Environment details

* **Angular version:** 4.4.6

* **Clarity version:**

* **OS and version:** windows server 2008 R2 enterprise - 64bit

* **Browser:** all

**Comment by adityarb88** [comment]
@nithinkarthik6: Which version of Clarity are you using? Also, can you provide a stackblitz which replicates your issue?

**Comment by nithinkarthik6** [comment]
Updating to latest version of clarity helped me but TabLink component is removed in version 0.11.0v what is the alternative to create tabs inside a tab?

Thanks in advance

**Comment by adityarb88** [comment]
@nithinkarthik6: You need to provide us with more info (StackBlitz which replicates the issue or a code snippet) for us to be able to help you. Without the code we don't know what exactly you are trying to do.

**Comment by nithinkarthik6** [comment]
Upgrading to latest version of clarity-designed helped me solve the issues. Thank you :)
