### ISSUE TITLE
How to let row col layout be resizable

### ISSUE THREAD

**Issue by gudelian941** [vmware/clarity#2051]
Hi , 
  I use row and column to be the layout of my page,  there is only one row and this row has two column,
I want to know how to let the column be resizable, now their width can't be modified by dragging

**Comment by adityarb88** [comment]
@gudelian941: We recommend that you file the issue following the issue template. Your issue description has no code snippets and no information about the version of Clarity you are using. Without that its not possible for us to triage the issue.

It looks like you are using the CSS grid. The CSS grid columns do not support drag and drop.

Closing the issue based on the above info. Please feel free to reopen the issue with the issue template if you have any questions. Thanks!
