### ISSUE TITLE
Improvements and Changes for Clarity Icons

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#2052]
- [ ] Once we move icons to `core-set` from another, we should just remove them from their old sets. We don't need to wait until the next breaking change to do the removal.

- [ ] As every shape and sets are exportable modules now, we could do export everything from `clr-icons/index.ts` as such:

 ```ts
export * from "./shapes/core-shapes";
export * from "./shapes/commerce-shapes";
export * from "./shapes/essential-shapes";
export * from "./shapes/media-shapes";
export * from "./shapes/social-shapes";
export * from "./shapes/travel-shapes";
```

This will allow users to import everything from `@clr/icons`. So it will look like:
```ts
import {ClrShapeCar, ClrShapeApplication, EssentialShapes } from "@clr/icons"
```
The method above should be *the recommended way* because if we move shapes from one set to another, users can still import them from the same path, `"@clr/icons"`. And we should include this method in our documentation.

 Currently, users need to know which icons belong to which set before importing them. 

```ts
import { EssentialShapes } from "@clr/icons/shapes/essential-shapes"
import { ClrShapeCar } from "@clr/icons/shapes/travel-shapes"
```

**Comment by gnomeontherun** [comment]
Deprecate these by the start of 0.12.0 and remove in 0.13
