### ISSUE TITLE
clrVerticalNavCollapsed 

### ISSUE THREAD

**Issue by mickeyevers77** [vmware/clarity#2053]
How do you start with a collapsed view instead of showing full navbar inside a clrVerticalNavCollapsed?

**Comment by adityarb88** [comment]
@mickeyevers77: Could you please file the issue again using the issue template? The issue template is provided to you when you open a new issue. Please make sure to attach a stackblitz or a screenshot which describes the issue. Without these details its difficult for us to triage the issue.

Thanks!
