### ISSUE TITLE
clrVerticalNavCollapsed

### ISSUE THREAD

**Issue by mickeyevers77** [vmware/clarity#2054]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I want to use the vertical nav with images. When I open the page I want to start the vertical nav as collapsed. I use (clrVerticalNavCollapsed)]="collapsed"

### Actual behavior
What happens is that when I open the page the vertical nav starts unfolded

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** all

**Comment by adityarb88** [comment]
@mickeyevers77: Is this what you are looking for? https://stackblitz.com/edit/clarity-light-theme-v11-lvluiy?file=app/app.component.html

**Comment by mickeyevers77** [comment]
thanks! @adityarb88
