### ISSUE TITLE
Support other date delimiters in new date control

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#2055]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
Would be nice to support other date delimiters than "/". Sweden for example use "-" and Germany ".'

### Actual behavior
Right now only "/" is supported.

### Environment details

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web

**Comment by adityarb88** [comment]
@rbirkgit: Thanks for filing the issue!

I see that the date format which is retrieved from Angular for locale `sv` is `y-MM-dd` (https://github.com/angular/angular/blob/master/packages/common/locales/sv.ts#L40)
and for `de` is `dd.MM.yy`
(https://github.com/angular/angular/blob/master/packages/common/locales/de.ts).

I want to verify if we can use the delimiter in this format to display dates in the date picker input. I think we can but I just need to verify it once.

I would also have to consult with out UX team and our internationalization team to check what they think about this. I will add more updates to this tickets when I have more info.

**Comment by KANekT** [comment]
in russian date format dd.MM.y

[ru.ts](https://github.com/angular/angular/blob/master/packages/common/locales/ru.ts)

**Comment by rameshyala** [comment]
Hi, @adityarb88 i am set Locale to my app like { provide: LOCALE_ID, useValue: 'en-IN' } in app module, but it still showing the MMDDYYYY format only, actually it need to change into DDMMYYY format right?.How i get this format.

and i have a one more doubt, now if i change the actual date in datePicker i will get any onChnage event  now (change detection)?

Thank you.
