### ISSUE TITLE
Support date picker with label wrapper for validations

### ISSUE THREAD

**Issue by mmarcelomartins** [vmware/clarity#2058]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[*] enhancement
```

### Expected behavior
Would be nice to support the label wrapper for validations purposes.

### Actual behavior
I put a label wrapper and some actions in date picker popover (choose year and choose month) make popover disapear.

### Environment details

* **Angular version:** 5.2.8

* **Clarity version:** 0.11.8

* **OS and version:** Windows 10

* **Browser:** Chrome  64.0.3282.186

In firefox Quantum 58.0.2 and Edge 42.17074.1002.0 works as expected.

**Comment by adityarb88** [comment]
@mmarcelomartins: I did not understand the popover disappearing part. How did you add a label wrapper and actions in the popover? Could you please provide a StackBlitz or a code snippet so that we can replicate the issue?

For the validation part, we already have tagged this for our UX team to take a look at. Please subscribe and take a look at this issue for more information: https://github.com/vmware/clarity/issues/2045

**Comment by mmarcelomartins** [comment]
@adityarb88 :  Follow the code snippet https://stackblitz.com/edit/angular-plvqqn, In my project i add custom css for the validation messages appear (for now), so in the code snippet you don't see any validation messages.
The popover disapear when i click for select the year or the month. In Microsoft Edge and in the Firefox Quantum works as expected, only fails in Google Chrome.

**Comment by adityarb88** [comment]
@mmarcelomartins: I see what you mean. Let me take a look at this and get back to you. Thanks for the StackBlitz!

**Comment by adityarb88** [comment]
@mmarcelomartins: I took a look at this and this will be resolved with the new forms refactor: https://github.com/vmware/clarity/issues/932 This will introduce a new design for validation. @gnomeontherun is current working on the new forms.

**Comment by gnomeontherun** [comment]
Yes, this will be part of the new forms layout and we won't probably be able to support this in the current 0.11 branch. I suggest for now that you apply your own validation messaging or wait for the new forms.

**Comment by gnomeontherun** [comment]
The new forms support validation helpers here so I believe this is resolved. You'll have to be on 0.13.6+ for the date picker to support this.
