### ISSUE TITLE
Programmatically control DatePicker popup

### ISSUE THREAD

**Issue by Magister** [vmware/clarity#2061]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Need possibility to trigger datepicker programmatically, for example to make it pop-up when user clicks on date field, or presses a hotkey.
Also, it would be great to make auto-created calendar button skip keyboard navigation.

The main purpose is to speed up form processing, consider following example: user navigates to field, selects date with popup, then wants to change it one more time (to correct mistake), selects it again and goes to next form field.
#### The desired behavior is:
1. `<Tab>` to date input, popup auto-opens
1. select date with arrows & press Enter
1. user wants to change selected date (correct mistake), press hotkey (`F4` for example)
1. select date with arrows & press Enter
1. `<Tab>` to go to next field

#### Versus what we have now:
1. `<Tab>` to date input
1. `<Tab>` to go to popup trigger button
1. `<Space>` to trigger popup
1. select date with arrows & press Enter
1. user wants to change selected date (correct mistake), but focus is gone somewhere, need to press `<Shift> + <Tab>` to return it to a calendar button
1. `<Space>` to trigger popup
1. select date with arrows & press Enter
1. `<Tab>` to go to next field

### Actual behavior
I have not found any API to trigger datepicker popup. After date selection, there is no visible focused element - looks like focus goes to some invisible element.
Also, there is no way to skip calendar button while navigating form with keyboard using `<Tab>` and `<Shift> + <Tab>`.

### Environment details

* **Angular version:** 5.0.1

* **Clarity version:** 0.11.8

* **OS and version:** Debian 9

* **Browser:** all

**Comment by adityarb88** [comment]
@Magister: I am going to tag our UX team to take a look at this ticket. They will get back to you soon. Thanks!

cc: @reddolan

**Comment by adityarb88** [comment]
We definitely do not want to open the date picker popover while the input is focused because if a user is typing the input, we do not want the popover to open unnecessarily. This decision was made by our UX team while designing the date picker and they can provide more info on this. But I do think that it would be nice to have a keyboard shortcut to open the date picker popover. Let's check what our UX team thinks about this.

**Comment by Magister** [comment]
> We definitely do not want to open the date picker popover while the input is focused because if a user is typing the input, we do not want the popover to open unnecessarily.

I understand, that's why I'm asking about API so I can do that myself, if my users need such behavior.

**Comment by reddolan** [comment]
Having the additional hot key could be useful. We need to look at this in a more holistic manner, across all popovers. 

It's also worth mentioning that adding the hot key isn't actually saving key strokes, as it would still take two key strokes `alt + down-arrow`. Currently it is `tab` to the icon and `enter` to open.

**Comment by Magister** [comment]
@reddolan single-key hotkey, such as `<F4>` will save a keystroke. And even if use `<Alt> + <Down-Arrow>` as you mentioned, it will save time - as it's faster to press `<Alt> + <smthn>` than a two-key sequence - because there will be some minimal delay between them.

And one more time, I want to emphasize that this issue is about **API**, not some pre-defined things.

**Comment by adityarb88** [comment]
@Magister: We discussed this with our UX team. The Date Picker is already accessible by keyboard `Tab` to the Date Picker trigger and `Enter` to open it. 

Our research also indicated that we want to avoid opening the Date Picker popover when the input field is focused. We want to avoid adding methods/features that go against our UX recommendations.  I am going to close this issue but please feel free to let us know if you have more questions/feedback.

Thanks!

**Comment by Magister** [comment]
@adityarb88 Well, it's a pity that you don't give developers a choice. Having an API for components gives more flexibility, and you avoid it - that's not only about this ticket, that's about all the project.

I'm now moving away from Clarity to Angular Material - because they give a lot more flexibility and customization options, from being able to open datepicker popup programmatically, override date parsing/formatting, to a better designed datatable architecture, and many many other things.

Good luck!
