### ISSUE TITLE
Cannot close DatePicker popup with keyboard

### ISSUE THREAD

**Issue by Magister** [vmware/clarity#2062]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Pressing `<Esc>` key should close popup and do not select any date.

### Actual behavior
`<Esc>` key do not close popup, the only way to do that with keyboard is to select some date.

### Environment details

* **Angular version:** 5.0.1

* **Clarity version:** 0.11.8

* **OS and version:** Debian 9

* **Browser:** Firefox 58.0.1

**Comment by adityarb88** [comment]
@Magister: Thanks for raising this issue. I have added this enhancement to our backlog.
