### ISSUE TITLE
Not able to create Tabs within Tabs 

### ISSUE THREAD

**Issue by nithinkarthik6** [vmware/clarity#2063]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Tabs within tabs
### Actual behavior

Not able to create tabs within tabs . 
Can you give me an alternative for TabLink as it is not found when i update to 'clr/angular' from clarity-angular
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.4.6

* **Clarity version:**0.11.8

* **OS and version:**  windows enterprise 2008 R2

* **Browser:** all

**Comment by adityarb88** [comment]
@nithinkarthik6: Could you please add a Stackblitz or a code snippet which replicates the issue that you are facing? Without that its very difficult for us to be able to help you.

Please take a look at this Stackblitz for an example of tabs in tabs: https://stackblitz.com/edit/clarity-light-theme-v11-tpgpbb?file=app/app.component.html It works as expected.

**Comment by nithinkarthik6** [comment]
Thanks for sharing the link of example of tabs. It worked fine.
Thanks for the help
