### ISSUE TITLE
Trying to change $clr-breakpoints but does not apply

### ISSUE THREAD

**Issue by marcojahn** [vmware/clarity#2066]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Defining a SASS map for $clr-breakpoints should take affect.
```
$clr-breakpoints: (
  small : 544px,
  medium: 768px,
  large : 992px,
  xlarge: 1600px
);
```

### Actual behavior
Changing the breakpoint with the map above does not have any effect. col-xl-* breakpoint still is at 1200px

### current integration ###
```
$clr-breakpoints: (
  small : 544px,
  medium: 768px,
  large : 992px,
  xlarge: 1600px
);
@import "../node_modules/@clr/ui/src/utils/dependencies.clarity"; // Includes light theme

// Your Application Theme File
@import "./theme.scss";

// Clarity Component SCSS
@import "../node_modules/@clr/ui/src/utils/components.clarity";
```
another idea was to do it sometime later
```
@import "../node_modules/@clr/ui/src/utils/dependencies.clarity"; // Includes light theme

$clr-breakpoints: (
  small : 544px,
  medium: 768px,
  large : 992px,
  xlarge: 1600px
);
// also tried to import maps.clarity again
// @import "../node_modules/@clr/ui/src/utils/maps.clarity";

// Your Application Theme File
@import "./theme.scss";

// Clarity Component SCSS
@import "../node_modules/@clr/ui/src/utils/components.clarity";
```

### Environment details

* **Angular version:** 5.2.8

* **Clarity version:** 0.11.8

* **OS and version:** MacOS latest

* **Browser:** [all]

**Comment by adityarb88** [comment]
cc: @hippee-lee Could you please take a look at this?

**Comment by hippee-lee** [comment]
Thanks for reporting this. It looks like I put `@import "maps.clarity";` in the file that aggregates components so its after both the dependencies and the theme file / overrides if one is doing that. 

I'll need to move it up and make sure that everything still works.

**Comment by dscoblen** [comment]
Very cool, thank you!
