### ISSUE TITLE
[ng] Datagrid column headers wrap 

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#207]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior

The data grid should either not wrap column headers or should wrap them intelligently. When a column header is wrapped, the filter icons across all headers should be positioned relative to the extra line height from the wrapped header text.

### Actual behavior
Data grid column headers wrap haphazardly and the filter icons are position as if the column headers are just a single line.

### Reproduction of behavior

https://embed.plnkr.co/6PaGJK/

<img width="1398" alt="screen shot 2016-12-08 at 10 58 02 am" src="https://cloud.githubusercontent.com/assets/2728359/21014451/b69a6eae-bd23-11e6-80c1-a9de2de45037.png">

### Environment details

* **Angular version:** 2.2.0

* **Clarity version:** 0.7.3

* **OS and version:** 

* **Browser:** [all]

**Comment by youdz** [comment]
Regarding this: 
>Data grid column headers wrap haphazardly and the filter icons are position as if the column headers are just a single line.
Datagrid uses `table-layout: auto` to let the browser natively handle column width based on their content. So in the image you posted, the data in he rows that are cut out must correspond more or less to the width of the columns we see (for instance, there must be a pretty long `API` cell with no spaces at all somewhere).

If you _know_ you want a specific column to take a specific length, whether it's in pixels, percentage or millimeters, then you can easily add a class to that column and set its width through CSS.

Maybe we'll be looking into making smarter column widths than the browser, but the real bug to fix here is the wrapping styles that are messed up.

**Comment by mathisscott** [comment]
What about the placement of the filter icons?

**Comment by youdz** [comment]
Placing of filter icons, column separator not scaling, header text pushed to the next line... This is what I mean by wrapping styles messed up. So yes, that's what I'll fix right now, until we investigate smarter columns with UX later.
