### ISSUE TITLE
[SASS] Clarity main.scss can't found bootstrap normalize.scss file

### ISSUE THREAD

**Issue by jewway** [vmware/clarity#2071]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```
### Actual behavior
Bootstrap v4.0.0-alpha.5 can't find normalize.scss file , maybe the change dependencies.clarity.scss to refer bootstrap-sass repository ([bootstrap-sass/assets/stylesheets/bootstrap/_normalize.scss](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_normalize.scss)) .

### Environment details

* **Angular version:** 5.2.8

* **Clarity version:** 0.11.8

**Comment by jewway** [comment]
Sorry, i solved by reference the theme of patterns page.

![image](https://user-images.githubusercontent.com/3501899/37386043-a119cdca-2791-11e8-96c1-7594a733bd97.png)

**Comment by BennieMeng** [comment]
什么意思啊大哥，没get到你的点 @jewway 。你怎么解决了这个路径找不到问题，我也想引入一下node_modules/@clr/ui/src/main.scss，这个文件，但是一直在报错，File to import not found or unreadable: ~bootstrap/scss/normalize.

**Comment by jewway** [comment]
Hi @BennieMeng , if you want to customize theme, only import **dependencies.clarity** and **components.clarity** files,  please refer [this document](https://vmware.github.io/clarity/documentation/v0.12/themes).

**Comment by BennieMeng** [comment]
@jewway  thank you , i get it . i am sorry for my mistake of learning document. if i want to set mutiple themes, do you have good idea. if so , i will feel great gratitude.

**Comment by jewway** [comment]
You can refer to [switch theme example](https://stackblitz.com/edit/clarity-theme-switcher?file=app%2Fapp.component.ts) @gnomeontherun provided.
