### ISSUE TITLE
Datepicker locale support and separator for locale "DE"

### ISSUE THREAD

**Issue by marcojahn** [vmware/clarity#2072]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The application locale setting causes the clrDate picker to respects the correct separator for locale "DE" to be the correct format ("dd.mm.yyyy" instead of "dd/mm/yyyy")

I think one of the following solutions could be done
1. clrDate uses the correct separator for each locale
2. date format can be configured (using attribute like data-dateformat="dd.mm.yyyy")
3. separator can be configured (using attribute like data-separator=".")

### Actual behavior
The separator is still "/" instead of "."

### Environment details

* **Angular version:** 5.2.8

* **Clarity version:** 0.11.8

* **OS and version:** macOS latest

* **Browser:** [all]

**Comment by adityarb88** [comment]
@marcojahn: We already have an issue filed for this. Please subscribe to https://github.com/vmware/clarity/issues/2072 for more info. Thanks!

**Comment by marcojahn** [comment]
which one is the duplicate ?
https://github.com/vmware/clarity/issues/2056 ?

**Comment by adityarb88** [comment]
@marcojahn: #2055
