### ISSUE TITLE
Tooltips not visible in a tree

### ISSUE THREAD

**Issue by plamens** [vmware/clarity#2077]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Tooltips over icons in a tree view are visible.

### Actual behavior
Tooltips over icons in a tree view are not visible.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v10-pqvbeh

The tooltip seems to be hidden, because of the **overflow-y: hidden;** on the clr-tree-node:
https://github.com/vmware/clarity/blob/64ea9412339951bb7a89feb11df5ca272bd791a4/src/clr-angular/utils/animations/collapse/collapse.ts#L11-L13

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.22

* **OS and version:** Windows 10

* **Browser:** [all]

**Comment by adityarb88** [comment]
@plamens: You need to use the Angular tooltip component to make sure that the tooltip is not clipped. Please refer to this Stackblitz for more info: https://stackblitz.com/edit/clarity-light-theme-v10-payxyx?file=app/app.component.html

**Comment by adityarb88** [comment]
Closing the issue based on the above. Please feel free to reopen the issue if you have more questions.
