### ISSUE TITLE
Clarity Documentation Website: On Datagrid page, link to Tables is broken

### ISSUE THREAD

**Issue by hilldaniel** [vmware/clarity#2079]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Link to Tables page in last paragraph on the data grids page should function

### Actual behavior
404 error

* **Browser:** [Chrome & Safari]

**Comment by adityarb88** [comment]
@hilldaniel: Thanks for reporting this. We will get this fixed soon.

Link: https://vmware.github.io/clarity/documentation/v0.11/datagrid/structure

![image](https://user-images.githubusercontent.com/1426805/37523534-9f0cdcbc-28fd-11e8-9857-7c9b00c8ff70.png)

**Comment by adityarb88** [comment]
Website will be updated soon with the fix.
