### ISSUE TITLE
Server-driven datagrid selection not preserved when all rows are selected via header checkbox

### ISSUE THREAD

**Issue by mviger** [vmware/clarity#2083]
**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Header checkbox select should select currently displayed rows and track the selection of those rows.

### Actual behavior
Header checkbox select selects all rows currently displayed, but does not track them.  

### Reproduction of behavior
**Stackblitz:** https://stackblitz.com/edit/clarity-serverdatagrid-header-trackby

Check header checkbox, all rows should be selected.  Navigate to next page in grid, return to previous page. Items that were previously selected will no longer appear selected.

### Environment details

* **Angular version:** 5.2.0

* **Clarity version:** 0.11.4

* **OS and version:** Windows Server 2016

* **Browser:** all  

### Additional Comment
`toggleAll()` in selection.ts does a push of all non-selected items into current[], but does not update the selection[] in a similar manner to `setSelected`.  I believe updating selection[] would resolve the issue.

**Comment by youdz** [comment]
My guess is you are not using the `trackBy` option with your objects fetched from the server, but there is no way of knowing for sure with what you posted. Please post a StackBlitz reproducing your issue so we can investigate.

**Comment by mviger** [comment]
The easiest way to reproduce this is to run `npm start` navigate to `http://localhost:4200/datagrid/selection` and use the check box in the header bar to select all entries on page 1.  Go to page 2 of the datagrid and then return back to page 1.  The bottom left will read that there are 10 items selected, but none of the items in the grid will have their boxes checked.

I am using trackBy, otherwise no items would ever return selected after changing pages. This only occurs when using the check box in the header bar.  Manually checking a few items and using paging works great.

I can create a Stackblitz at some point, but it might take me a day or 2 before I can get back to it.
