### ISSUE TITLE
Upgrade Clarity to Angular 2.3.0

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#209]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Angular 2.3.0 was just announced, we should upgrade Clarity to it.

https://github.com/angular/angular/blob/master/CHANGELOG.md#230-2016-12-07

**Comment by jeeyun** [comment]
Our unit tests run on phantomJS and we are running into this issue: https://github.com/angular/angular/issues/13301.

It's been fixed and merged to master, so maybe we can upgrade to a later version when Angular releases a patch.

**Comment by jaffoneh** [comment]
We're on Angular 2.4.1.
