### ISSUE TITLE
UK/AU Datepicker format

### ISSUE THREAD

**Issue by kuba-010** [vmware/clarity#2091]
**Select one ...**  (check one with "x")
```
[*] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I'm trying to get the datepicker to display in dd/mm/yyyy format. I've followed the instructions and run the cli app as GB and AU (i.e. ng serve --locale en-gb) 

The datepicker should use the format of dd/mm/yyyy

### Actual behavior
The datepicker comes up in mm/dd/yyyy format

### Environment details
* **Angular version:** 5.2.4
* **Clarity version:** 0.11.9

**Comment by adityarb88** [comment]
@kuba-010: `ng serve --aot --locale en-GB` should work. You need the `aot` flag to load the locale data. For JIT compiler (which is without the aot flag), you need to follow the instructions in the docs:

![image](https://user-images.githubusercontent.com/1426805/37632691-d7418c2a-2bc5-11e8-9e94-fd38b70c5fb9.png)
 
More details here: https://angular.io/guide/i18n

Let us know if that helps. Closing this issue based on the above info. Please feel free to reopen if you have more questions. Thanks!

**Comment by kuba-010** [comment]
Oops overlooked the --aot and JIT differences, my bad! Thanks for that!

**Comment by delockdown** [comment]
Hi @adityarb88 ,
Is it possible to get 'YYYY-MM-DD' formate because after this it gets the format of 'DD-MM-YYYY'.

**Comment by adityarb88** [comment]
@delockdown: You could bind to `clrDateChange`. That emits a Javascript `Date` object.  Would that help? You could also refer to this issue for more information: https://github.com/vmware/clarity/issues/2056

**Comment by delockdown** [comment]
Hi @adityarb88, Can you create a example of doing that change that for me. It would be very helpful to me.

**Comment by adityarb88** [comment]
@delockdown: We already have an example of that in our docs:
https://vmware.github.io/clarity/documentation/v0.11/datepicker

![image](https://user-images.githubusercontent.com/1426805/39248313-b6f1f7be-4869-11e8-8571-5fda8fe6044e.png)

Let us know if that helps.

**Comment by rameshyala** [comment]
Hi @adityarb88 , i am set locale to my app in app.module file like ' providers: [{ provide: LOCALE_ID, useValue: 'en-IN' }]', but this ' en-IN' locale need to show format as DDMMYYYY but actually it showing MMDDYYYY format. check once [Stackblitz](https://stackblitz.com/edit/clarity-light-theme-v11-nknd98?file=app%2Fapp.module.ts).

One more doubt is now date picker have change detection option , i mean change the actual date emit any event ?.   

Thank you.

**Comment by Zyzle** [comment]
@adityarb88 This doesn't actually appear to be working in the current version (0.12.5), setting LOCALE_ID in the way shown doesn't affect the date format at all in the case of `en-GB` and in fact causes errors in the app when you attempt to set it to any non `en` locale
