### ISSUE TITLE
Can't bind initial datepicker value using reactive forms

### ISSUE THREAD

**Issue by jansivans** [vmware/clarity#2093]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Initial date value should be bound to datepicker when using reactive forms.

### Actual behavior
Initial date value can not be bound to datepicker when using reactive forms.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-icqw1x?file=app%2Fapp.component.ts

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:** 0.11.9

* **OS and version:** Windows 10

* **Browser:** all

**Comment by adityarb88** [comment]
@jansivans: Thanks for reporting this issue. I can confirm that this is a bug. The `NgControl.valueChanges` subscription does not fire for the initial value and thats why we don't write it back to the input or update the current selected day. I will spend some time today to investigate this and post more updates here.

**Comment by adityarb88** [comment]
@youdz, @gnomeontherun: So I see 2 different behaviors when the initial value is not null:
1. Reactive Forms: `NgControl.valueChanges` does not fire but `NgControl.value` is not null and contains the initial value. I can use this value to update the input and the selected day in the Calendar.
2. Template Drive Forms: `NgControl.valueChanges` fires but `NgControl.value` is null.

Obviously, we have the second case covered but the first one is missing. I will add it today and test if that solves the issue.
