### ISSUE TITLE
Typo on Datepicker component page

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#2095]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
"Template Driven Form Demo"

### Actual behavior
"Temp**al**te Driven Form Demo"

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/v0.11/datepicker

**Comment by adityarb88** [comment]
@joshjohnson72: Thanks for reporting this issue. Will get this fixed soon.

**Comment by adityarb88** [comment]
Website will be updated soon with the fix.
