### ISSUE TITLE
Date Picker unexpected view

### ISSUE THREAD

**Issue by andrei-vaganov** [vmware/clarity#2096]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

![clarity datepicker2](https://user-images.githubusercontent.com/25936646/37686693-320eb354-2ca1-11e8-8c01-3aaf767b7842.jpg)

### Actual behavior

![clarity datepicker](https://user-images.githubusercontent.com/25936646/37686705-3e64e768-2ca1-11e8-8894-1e753f88499c.jpg)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://stackblitz.com/edit/clarity-light-theme-v11-yvchzp

OR

1. https://vmware.github.io/clarity/documentation/v0.11/get-started  
2. Starting With a Clarity Seed Project (Recommended)
3. Add `<input type="date" clrDate>` on template
4. npm start

### Environment details

* **Angular version:** 5.0.5

* **Clarity version:** 0.11.9

* **OS and version:** Win10, Node.js 9.8.0

* **Browser:** Chrome 65.0.3325.162, Opera 51.0.2830.55
--

**Comment by adityarb88** [comment]
@andrei-vaganov: Could you please check again the version of Clarity that you are using?

![image](https://user-images.githubusercontent.com/1426805/37686945-01b91b62-2c70-11e8-839b-4923ed5189ba.png)

I see that you are using 0.11.1. Datepicker was released in 0.11.8

**Comment by adityarb88** [comment]
Please see: https://stackblitz.com/edit/clarity-light-theme-v11-rrcias?file=app/app.component.html

![image](https://user-images.githubusercontent.com/1426805/37686997-3f9296e8-2c70-11e8-8423-e4632d1123ec.png)

**Comment by andrei-vaganov** [comment]
![clarity datepicker3](https://user-images.githubusercontent.com/25936646/37687183-3621aa08-2ca3-11e8-83ee-c2a4ce0d75f5.jpg)

**Comment by andrei-vaganov** [comment]
![clarity datepicker4](https://user-images.githubusercontent.com/25936646/37687215-5ae8fe0e-2ca3-11e8-888f-0224e7b786ab.jpg)

**Comment by adityarb88** [comment]
@andrei-vaganov: Looks like you are using 0.11.0. You need to upgrade to the latest version of Clarity. Please update your package.json to use 0.11.9

**Comment by andrei-vaganov** [comment]
ohhh, I've updated my package.json and it works fine now!
```
    "@clr/angular": "^0.11.0",
    "@clr/icons": "^0.11.0",
    "@clr/ui": "^0.11.0",
```
to 
```
    "@clr/angular": "^0.11.9",
    "@clr/icons": "^0.11.9",
    "@clr/ui": "^0.11.9",

```

I was sure it was done automatically by package manager and also was confused by: 
![clarity datepicker4](https://user-images.githubusercontent.com/25936646/37687541-a1c1eca4-2ca4-11e8-80bc-8f56fe63f58c.jpg)

Many thanks!

**Comment by adityarb88** [comment]
no worries. closing the issue.
