### ISSUE TITLE
Sketch Library - Vertical nav doesn't stretch vertically

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#2098]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Resizing the vertical nav component should only stretch the background

### Actual behavior
Resizing the vertical nav component stretches the individual nav items

### Environment details

* **Clarity version:**
0.11.x Sketch File

**Comment by adityarb88** [comment]
@reddolan could you please take a look at this?

**Comment by joshjohnson72** [comment]
I'd post a quick video, but it's not supported by github.

**Comment by hippee-lee** [comment]
@joshjohnson72 - they do support animated gifs if you can export the video as that and keep it under 10MB it will upload.

**Comment by reddolan** [comment]
Fixed in 0.11.x will be part of next UI Library release
