### ISSUE TITLE
Icon Request: 4-way arrow to indicate "move position"

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#2099]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Would like to have an icon added to indicate the ability to move an element's position.  This is typically an icon made of 4 outward facing arrows.  (Similar to the Router icon, but all arrows pointing out)

![4-way arrows icon](https://user-images.githubusercontent.com/8105536/37688846-34e4f56c-2c5f-11e8-928b-c24bbfd51718.png)

**Comment by adityarb88** [comment]
@mathisscott, @lil-kim: Could you please take a look at this?

**Comment by lil-kim** [comment]
Yep, we'll add this to Icons-volume 11. Thanks.
