### ISSUE TITLE
Remove OK/Apply button from column hide/show panel in datagrid

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#2100]
**Select one ...**  (check one with "x")
```
[x] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
What is the role of **clr-dg-column-toggle-button clrType="ok"** for datagrid column toggle feature?
As a user, I would expect that the column toggling state will be applied/persisted only if I click on that button. If a user make changes to column visibility but doesn't click ok then it should reset back to the old state until you click on OK button. However, we could show changes made on checkbox click as a preview mode but should not persist.

### Actual behavior
The current behavior doesn't require to click on **clr-dg-column-toggle-button clrType="ok"** button.
I feel like this directive/component itself is redundant. 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

you could check the behavior from official doc itself

### Environment details

* **Angular version:** 5.x.x/4.x.x

* **Clarity version:**0.11.x

* **Browser:** all

**Comment by mathisscott** [comment]
Per review, we feel the best course of action here is to remove the OK button. It is not consistent with design choices in other components. The suggestion is to simplify the hide/show column experience so it looks more like this...

<img width="403" alt="screen shot 2018-05-04 at 3 00 31 pm" src="https://user-images.githubusercontent.com/2728359/39649975-165a65f8-4fac-11e8-8a20-02640ffbdc6f.png">

**Comment by gnomeontherun** [comment]
Will need another issue to clean up the OK button logic for projected buttons.

**Comment by ph55** [comment]
What about saving columns state ?
Currently I do use click event to persist hidden columns in database.

```html
<clr-dg-column-toggle-button clrType="ok" (click)="saveColumns()">
    Save
</clr-dg-column-toggle-button>
```

If it removed, event should be exposed on column check/uncheck.
