### ISSUE TITLE
Add alias to the `help` icon on the website

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#2103]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Can we get an icon for unknown status inside a circle as well?
It looks odd when we represent status with all the others(as shown below)
Similar to 
![image](https://user-images.githubusercontent.com/12848838/37748722-ede4a9ee-2daa-11e8-8416-6c9472359d5f.png)

### Actual behavior
current Icon:
![image](https://user-images.githubusercontent.com/12848838/37748704-dade83ba-2daa-11e8-9925-be0cee59ceef.png)

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**0.11.x

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@lil-kim: Could you please take a look at this?

**Comment by shravansofts** [comment]
@lil-kim Agreed. This works for us.
As suggested please add a tag for this icon.
You could close this issue.

**Comment by adityarb88** [comment]
@shijir: I will keep this open as an enhancement to the website. Could you please tackle this?
