### ISSUE TITLE
Clarity alert is not visible, when we get new alert after all the alerts are closed

### ISSUE THREAD

**Issue by LokeshN** [vmware/clarity#2104]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Clarity alert should be visible, when we get new alert after all the alerts are closed

### Actual behavior
Clarity alert is not visible, when we get new alert after all the alerts are closed
Steps to reproduce the issue:
1. I initially get two alerts and it shows up in clr-alerts components 
2. I immediately close those two alerts
3. Now the third alert comes up and it is not visible, even though it is present in the DOM
I added the third alert using setTimeout(..) to be visible after 5 seconds. To simulate the issue in plunkr, we need to close the first two alerts immediately before the third alert comes up.

Plunkr url: https://plnkr.co/edit/Mp96L9JLwFp8ql5gEd57?p=preview

### Reproduction of behavior
Plunkr: https://plnkr.co/edit/Mp96L9JLwFp8ql5gEd57?p=preview

### Environment details
This issue is also happening with angular version 5.x and with clarity version 0.11.3

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@LokeshN: Thanks for reporting this issue. I edited the plnkr so that the issue replication is easier:

https://plnkr.co/edit/oRGx7WWJlZZ4f2BoqBTp?p=preview

1. Dismiss both the alerts on screen.
2. Click Add alert.
3. Inspect DOM. Alert is present but not shown.

**Comment by Shijir** [comment]
I see this issue has been resolved by https://github.com/vmware/clarity/pull/2037, which was introduced in v0.11.8. 

https://stackblitz.com/edit/clarity-light-theme-v11-g1gqv9?file=app/app.component.html
