### ISSUE TITLE
Small radio button group has incorrect background in Edge

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#2105]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Small radio button group has **correct** background height in Edge.

### Actual behavior
Small radio button group has **incorrect** background height in Edge.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-cgd4a6

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 11.x

* **OS and version:** Windows 10 x64

* **Browser:** Microsoft Edge 40.15063.674.0

**Comment by adityarb88** [comment]
@belyan: Thanks for reporting this issue. We will take a look and get back to you.

Screenshot from Edge:
![image](https://user-images.githubusercontent.com/1426805/37831862-3bf36a30-2e7d-11e8-84ca-572149dc6eff.png)

**Comment by adityarb88** [comment]
Additional Notes:
The label in the radio is not being positioned correctly in Edge:
![image](https://user-images.githubusercontent.com/1426805/37831953-8e430c50-2e7d-11e8-9ce5-85f6c4d6886d.png)

**Comment by borcherspm** [comment]
This is also happening in IE.

**Comment by borcherspm** [comment]
removing ```display: inline-table``` did not fix it for me.  

I had to hardcode the line-height to 23px to fix it...

```
label {
  line-height: 23px !important;
}
```
