### ISSUE TITLE
Caret icon in dropdown button does not represent the current state

### ISSUE THREAD

**Issue by karmasakshi** [vmware/clarity#2107]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
The caret icon should point upwards when the dropdown is open.

### Actual behavior
The caret icon is always pointing downwards regardless of the dropdown state.

### Reproduction of behavior
N/A

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:** 0.11.10

* **OS and version:** macOS 10.13.3

* **Browser:** [Chrome 63]

**Comment by mathisscott** [comment]
@karmasakshi 
There is a problem with this feature request when we consider that dropdown menus can show up on top, to the right, to the left, or on the bottom of the dropdown trigger. If there is a use case for your application that requires this behavior, it can easily be achieved with a few lines of CSS to augment the default styles. But it is not a feature we plan to implement in Clarity.

Thanks!
