### ISSUE TITLE
Issue with Popovers while hosted in sharepoint page

### ISSUE THREAD

**Issue by headswe** [vmware/clarity#2108]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Clicking outside should close the popover

### Actual behavior
The dropdown menu dosen't close and places itself in the top left corner
![2018-03-26_16-37-07](https://user-images.githubusercontent.com/425212/37913275-c9c02292-3114-11e8-9721-814f252ffe4a.gif)

### Reproduction of behavior
Not really possible

### Environment details

* **Angular version:** 5.0.0

* **Clarity version:** 0.11.10

* **OS and version:** Windows 10

* **Browser:** All

**Comment by adityarb88** [comment]
@headswe: Could you please replicate this issue on a StackBlitz? There is no way for us to debug this issue without that. Thanks!

https://stackblitz.com/edit/clarity-light-theme-v11

**Comment by headswe** [comment]
I'd love too, expect it unlikely that will happen like I said in the original report.
Since it only happens in the SharePoint environment.

**Comment by headswe** [comment]
A small note is that when i attempt to click away the popover or using ESC to dismiss it the issue occurs afterwards it will be stuck at (0,0) until the same popover is opened again.

The popover release code seems to run perfectly but the element is not removed from the DOM, 
Oddly enough the popover element is deleted from view when clicking on the button used to summon it.

**Comment by headswe** [comment]
I've been looking futher into this and it seems this class is not set.

`    "isOffScreen": [{ type: HostBinding, args: ["class.is-off-screen",] },],
`

**Comment by headswe** [comment]
Seems like the change detection is breaking.

IfOpenService.open will be set to false and the popover will be released but angular change detection will not fire. and the bindings wont update resulting in is-off-screen not being set and the popover being stuck until another event fires and the normal flow resumes.
