### ISSUE TITLE
Broken link on the Clarity website - error 404

### ISSUE THREAD

**Issue by georgievay** [vmware/clarity#2109]
The link to the latest Sketch template is broken and returns a 404 error page. **[LINK](https://vmware.github.io/clarity/assets/images/sketchTemplates/Clarity-Template-0.11.6.sketch)**

**Comment by adityarb88** [comment]
@georgievay: I don't see a broken link. Please check this: https://vmware.github.io/clarity/documentation/v0.11/get-started#designResources
Are you downloading from this page? 

Please provide more information to replicate the issue.

**Comment by adityarb88** [comment]
@georgievay: I found the broken link. Its from the release page: https://vmware.github.io/clarity/news. We will get that fixed soon. Thanks!

**Comment by georgievay** [comment]
Yes, this is the page that i meant.

**Comment by hippee-lee** [comment]
Fixed in this commit: https://github.com/vmware/clarity/commit/144648e6b9d767da33c8bf6ac66f2d48bc09d059
