### ISSUE TITLE
Update icon documentation for 'dashboard' to 'dashboard-gauge'

### ISSUE THREAD

**Issue by RainTomassi** [vmware/clarity#211]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Per documentation: https://vmware.github.io/clarity/documentation/iconography
`<clr-icon shape="dashboard"></clr-icon>`
Should display the dashboard icon.

### Actual behavior
Using 'dashboard' displays an exclamation-circle.  Doc just needs to be updated to reflect the correct string of 'dashboard-gauge'
`<clr-icon shape="dashboard-gauge"></clr-icon>`

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@Shijir : What's the status on this?

**Comment by jaffoneh** [comment]
This is being fixed by #236. @Shijir can confirm.

**Comment by Shijir** [comment]
Fixed in [PR#236](https://github.com/vmware/clarity/pull/236)
