### ISSUE TITLE
Can not unselect grid element

### ISSUE THREAD

**Issue by vitkt** [vmware/clarity#2111]
```
[x] bug
[ ] feature request
[ ] enhancement
```
I have list of elements. Each element contains id and inner list. 
` public myData:any=[{"id":1,"subData":[{"id":1},{"id":2},{"id":3}]},
                          {"id":2,"subData":[{"id":4},{"id":5},{"id":6}]}];
`
Also I have two clr-datagrids. First datagrid is for main list, second one is for inner list of selected element. But I don`t want to have selected element in second grid by default.
### Expected behavior

When I set 'clrDgSingleSelected' property of sublist datagrid to null, sublist datagrid should not be selected without my click.
### Actual behavior
Sublist is selected after forced unselect when I select element in first datagrid.

### Reproduction of behavior

* https://stackblitz.com/edit/clarity-unselect-example
- Select first element in first grid
- Select any element in second grid
- Unselect element in second grid by button
- Select second element in first grid
- Select first element in first grid again
- Element in second grid is selected

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.11.6

* **OS and version:** Windows 10

* **Browser:** tested on Chrome and Firefox

**Comment by stefnoten** [comment]
We encounter the same issue for a single grid, when refetching data (e.g. refresh, sort, filter, ...):

1. Select a row
2. Unselect the row programmatically
3. Refetch data (via a refresh, sort, filter, ...)

Result: the row is selected again.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
