### ISSUE TITLE
clr-tabs needs API to set and track tab changes if you don't want auto delete *clrIfActive behavior

### ISSUE THREAD

**Issue by adumesny** [vmware/clarity#2112]
```
[ ] bug
[ ] feature request
[ X] enhancement
```

### Expected behavior
ClrTabs class has no easy way to set/get the active tab, or get notified when tab selection changes, unlike all tab controls I've ever used.

### Actual behavior
the doc at https://vmware.github.io/clarity/documentation/v0.11/tabs is very sparse for the angular control, and I was looking at events/API and saw nothing. The use of *clrIfActive and <ng-template [(clrIfActive)]="condition"> for 2 way binding to set and get the active tab assumea that you wan to create content on the fly (usually a good thing) and destroy when you click another tab (not always what you want).

Reasons why auto create/delete isn't always the best (or what can be implemented in the constrain you have) : 

1) content of a tab may take a while to generate - user clicking back and forth shouldn't have a big lag (first time might be minimized by pre-fetching in the background, but the UI itself might still take a while to generate)

2) content you're showing isn't coming from you (ex: IFrame) - you have no control, and deleting it would loose any context/changes if user just clicks around

3) you do not have a complete Model/View separation and the Angular component rendering the HTML template also has logic on when to apply changes when container parent OK/Cancel is pressed. Separating it out can be a lot of extra work.

4) *clrIfActive is optional - yet there is no documented way how to specify the active tab in the html template or code, or get the active tab. So what do you do if you don't force [(clrIfActive)] ?

### Reproduction of behavior
My Scenario is I have a widget editor (modal dialog created dynamically) that has 3-4 tabs, with each tab a list of sub-editors angular component (typically one per property). Upon dialog create all sub-editors are created (there is some interdependencies) and when the dialog OK is called it asks each to write() itself out (else cancel which does nothing) and destroy itself and all content. Field editors have the UI and logic on how to edit a single field - separating into model/view would create dozens more classes from what I already have (very modular, low level components). Creating speed/dom complexity is NOT an issue.

You can run a live version by going to 
http://flyingdragon.eng.vmware.com/flyingdragon/latest/demo/load;doc=%2Ffd%2Fwidget%2Fcom.vmware.fd.page_test_bindings
and clicking the edit pencil button over any widget on the page

![image](https://user-images.githubusercontent.com/3496166/37984820-2d3bff52-31ac-11e8-8a7b-ed3113cc5102.png)

![image](https://user-images.githubusercontent.com/3496166/37984925-650940ca-31ac-11e8-9c97-5a027a1c8337.png)

code sample:
https://stackblitz.com/edit/clarity-light-theme-v11-rmihi6

### Environment details

* **Angular version:** 5.2.4

* **Clarity version:** 0.11.4

* **OS and version:** Windows 10

* **Browser:** [Chrome 65 ]

**Comment by adumesny** [comment]
Kevin Boucher [6:43 PM]
We have this type of tab caching in multiple places, some for components I don’t own and don’t want re-created each time the tab is changed and some for the reason Alain mentions.

Ron Birk [7:33 PM]
I had multiple cases where we turn off the clrIfActive (i.e. don't use it) as it's important the content doesn't get removed/re-created when clicking on the different tabs. This is an important feature of the tab control.

Alain Dumesny [12:16 AM]
@eudes the get method is just `this.tabLinkDirectives.toArray().findIndex(x => x.active)` or `find()` if you want the tab rather than index... set is trivial once you know the code, though took a while to figure out what it was doing from the outside

Ron Birk [8:03 AM]
I agree on this part. Using *clrIfActive to set/get active tab quickly makes the code very messy with all kind of workarounds. We tried it once and got very ugly. A simple get/set method for active tab would be so very nice to have.

Eudes Petonnet-Vincent [8:52 AM]
This is going to be a long answer, and it's on Slack so there is always the risk of it being misinterpreted. Please know that I'm only trying to do what's best for Clarity and explain my reasoning here, and that none of what I'm writing should be taken as aggressive or personal.
First, I would like to point out that the fact that 3 people want a feature should not decide what goes in an open-source project. Not only is 3 people extremely small compared to our user base, it would also be far too subjective. So the conversation focus on the validity of the use case, the maintainability for Clarity, ...
Regarding the validity of the use case, all I have based on that whole conversation is a single high-level example with a pretty abstract description, in which you explain that your model is tightly coupled to the lifecycle of your view. This is the opposite of MVC, MVVM or MV* whatever they call it these days. My entire point from the beginning is that this shouldn't be the case, and if it weren't then `*clrIfActive` wouldn't be a problem. If you were able to write a small StackBlitz example of how the tabs are used in your application, I would be happy to look at it to either validate your use case or suggest an alternate structure that would provide better maintainability. I obviously wouldn't force my opinion on you, but it would help structure the conversation more than throwing abstract concepts around like we are doing.
I also understand that in your case, the tabs are small and fast, so destroying/hiding doesn't matter. But we believe hiding will always be worse unless in extreme edge cases, which is why we do not want to "push" bad practices by acknowledging them in our API. It's the same conversation as whether to use `*ngIf` or `[hidden]`. Even Angular recommends using the first one unless you are absolutely sure you _need_ the other.
Regarding your API, what would the setter receive? A tab id? A Tab component? An index? No one uses tabs the same way, the ids are private, the components are always painful to query, ... Using indices is out of the question because we support dynamic tabs so indices can change at any time while the active tab actually stays the same.
Finally, you would be introducing a second source of truth for the current tab. Sure, maybe the "API" is just a simple two-way binding, but 2 sources of truth leads to bugs, "Exception has changed after it was checked" errors, and complex maintenance. We are not saying no out of laziness or refusal to change, we are saying no because we've been burned by these double-sources-of-truth situation several times, and the only way out months later was to stop supporting one of them. That's the burden of writing a library of components, what seems to be a one-line change never is because of all the use cases we support.

Ron Birk [9:09 AM]
My point is that we had iframes with 3rd party expensive rendered data in a tab for example. Destroying that and recreate every time a user happens to click on another tab and back is not good. The user would also expect to come back to the same state.

Eudes Petonnet-Vincent [9:11 AM]
But wouldn't having several iframes loaded and all when they're not even used be even worse for the application's performance?

Ron Birk [9:11 AM]
Second for active tab, every tab control I have ever used always had a name/id or index. I don't know why that is bad. Our code got so big and messy and all we wanted was a simple API.

Ron Birk [9:17 AM]
What we ended up doing was using the navigation control as it looks like the tabs, but worked better for us. Anyway, I just added info to Alain that he is not alone in his thinking. That's all.

**Comment by adumesny** [comment]
Here is code sample I'm using in case it help next person not using *clrIfActive but still set/track the active tab - not ideal as I have to delay setting things or angular complain of value bring changed in ngAfterViewInit()

```
@ViewChild(ClrTabs) private readonly tabs: ClrTabs;

// called when Dialog OK is pressed. Assign the new values before dialog closes
public onOK() {
    ...
    // save active tab
    this.widget.tabIndex = this.tabs.tabLinkDirectives.toArray().findIndex(x => x.active);
}

// the the default tab to what we need
public ngAfterViewInit() {
    const tabIndex = this.widget.tabIndex;
    if (tabIndex !== 0 && tabIndex < this.tabs.tabLinkDirectives.length) {
        window.setTimeout(() => { this.tabs.tabLinkDirectives.toArray()[tabIndex].activate(); }, 0); // delay so Angular doesn't complain
    }
}
```

**Comment by adumesny** [comment]
added code sample (basic tab without *clrIfActive set)

**Comment by mathisscott** [comment]
After lengthy discussions and consideration, we have determined that this falls outside of the use case for tabs. In the case presented, it would be better to align a tab-looking implementation to routes or some other implementation that doesn't involve expensive DOM elements sitting in the background.

@adumesny 's workaround remains here for those who feel compelled to follow.

**Comment by adumesny** [comment]
you guys are wrong... this is a pretty common workflow. Yes there is a workaround, but it's kinda ugly and not easy to find.

**Comment by Rush** [comment]
A use case I just encountered is opening a modal that has tabs inside of it. I want to be able to programmatically affect which tab is initially open.

**Comment by adumesny** [comment]
@Rush I do that using the following code (remember which tab is active on next open/create)
`
@ViewChild(ClrTabs) private readonly tabs: ClrTabs;

  /** if we have tabs, remember which one is active and make that default next time... */
  public ngAfterViewInit() {
    let want = this.editorTab;
    // if first tab is hidden, make sure we don't default to it or tabs will be broken...
    if (!this.haveGrid && want === 0) { want = 1; }

    if (want !== 0 && want < this.tabs.tabLinkDirectives.length) {
      window.setTimeout(() => { this.tabs.tabLinkDirectives.toArray()[want].activate(); }, 0); // delay so Angular doesn't complain
    }
  }

  /** internal - called when Dialog OK is pressed. Assign the new values before dialog closes
   */
  public onOK() {
....
    // save active tab
    this.widget.editorTab = this.tabs.tabLinkDirectives.toArray().findIndex(x => x.active);
  }
`

**Comment by madhurpgarg** [comment]
> Here is code sample I'm using in case it help next person not using *clrIfActive but still set/track the active tab - not ideal as I have to delay setting things or angular complain of value change in ngAfterViewInit()
> 
> ```
> @ViewChild(ClrTabs) private readonly tabs: ClrTabs;
> 
> // called when Dialog OK is pressed. Assign the new values before dialog closes
> public onOK() {
>     ...
>     // save active tab
>     this.tabIndex = this.tabs.tabLinkDirectives.toArray().findIndex(x => x.active);
> }
> 
> // set the default tab to what we need
> public ngAfterViewInit() {
>     const tabIndex = this.tabIndex;
>     // if first tab is hidden, make sure we don't default to it or tabs will be broken...
>     if (this.firstHidden && tabIndex === 0) { tabIndex = 1; }
>     if (tabIndex !== 0 && tabIndex < this.tabs.tabLinkDirectives.length) {
>         window.setTimeout(() => { this.tabs.tabLinkDirectives.toArray()[tabIndex].activate(); }, 0); // delay so Angular doesn't complain
>     }
> }
> ```

Thanks Alain, it saved my day. I had been search the similar thing but couldn't get through it until I reached this post.

**Comment by webia1** [comment]
First of all, thank you very much for the great job done. We are in the middle of our product development and suddenly clarity tabs do not work after Angular 9 migration. That is for us, unfortunately, a very frustrating moment. If I have really understood, there will be no effort to change that for Angular 9.  How can we get tabs working, without some hacks?

**Comment by hippee-lee** [comment]
Hi @webia1 - this issue has already been closed. Please open a seperate issue with a minimal reproduction for what you are seeing. We keep starter apps here: https://stackblitz.com/@clr-team
