### ISSUE TITLE
clrCurrentAlertIndex of Alerts component does not accept zero

### ISSUE THREAD

**Issue by gerinjacob** [vmware/clarity#2119]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
`clrCurrentAlertIndex` input attribute of `clr-alerts` should accept zero

### Actual behavior
In the punker provided, https://current-alert-index-zero.stackblitz.io
There are 2 buttons, `Go To First Alert` and `Go To Second Alert`.
I am able to go to second alert, but not to first alert.

**Root Cause:**
Inside ClrAlerts component there is an `if` check for index, which evaluates zero to false. Hence it is not getting set.
```javascript
public set _inputCurrentIndex(index: number) {
  if (index) {
    this.multiAlertService.current = index;
  }
}
```
**Possible Solution:**
Check for zero as well,
```javascript
public set _inputCurrentIndex(index: number) {
  if (index || index === 0) {
    this.multiAlertService.current = index;
  }
}
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://current-alert-index-zero.stackblitz.io
https://stackblitz.com/edit/current-alert-index-zero

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** v11

* **OS and version:** Any

* **Browser:** all

**Comment by svvac** [comment]
duplicate of #1907
