### ISSUE TITLE
Will modal support adding custom class or style to adjust modal styles like width?

### ISSUE THREAD

**Issue by wghglory** [vmware/clarity#2121]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

I use `<clr-modal>` lg and md to control the modal size, however I need a size between lg and md. Can I pass some classes to clr-modal for customization?

**Comment by Shijir** [comment]
Hi @wghglory, could you please ask this question on StackOverflow with the `vmware-clarity`, `angular`, `html` and `css` tags? We regularly check questions on StackOverflow and will try to provide a solution to your issue there. By doing so, other developers who might have the same inquiry could see the solution.

So closing the issue based on this. Thanks!
