### ISSUE TITLE
Adding Drawer component in Clarity

### ISSUE THREAD

**Issue by UttamA** [vmware/clarity#2123]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Drawer is required to quickly view item details and perform action on the same page instead of going to detail page and then perform action. Other example is the navigation drawer is quite prominent in mobile devices.
As a part of our application we developed a drawer and want to contribute to clarity.

### Actual behavior
Presently we dont have drawer component in clarity and this will be good value add to clarity. 

### Environment details

* **Angular version:** 5.0.0

* **Clarity version:** 0.11.8

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by SayakMukhopadhyay** [comment]
Is the drawer component different from [sidenav](https://vmware.github.io/clarity/documentation/v0.11/sidenav) or [vertical nav](https://vmware.github.io/clarity/documentation/v0.11/vertical-nav/basic-structure/charmander) ?

**Comment by whizkidwwe1217** [comment]
@SayakMukhopadhyay  I think he's referring to a component similar to Microsoft' Office Fabric UI's **Panel** component. [Office Fabric UI Panel](https://developer.microsoft.com/en-us/fabric#/components/panel)
![image](https://user-images.githubusercontent.com/1977391/38193482-dbe75054-36a4-11e8-820a-f732308a45d1.png)

**Comment by UttamA** [comment]
Yes this is same as panel.

**Comment by UttamA** [comment]
![panel](https://user-images.githubusercontent.com/4607437/38193610-7f48b432-3690-11e8-88e8-730c58d62bb7.png)

**Comment by UttamA** [comment]
The component we build for our product

**Comment by whizkidwwe1217** [comment]
We also need that kind of component. I hope clarity team will consider building it.

**Comment by SayakMukhopadhyay** [comment]
This might not be exactly what you want but for showing more data and other stuff for datagrid rows one can use [this](https://vmware.github.io/clarity/documentation/v0.11/datagrid/expandable-rows)

**Comment by UttamA** [comment]
@SayakMukhopadhyay Expandable rows for datagrid use case are different from panel. This drawer/panel can be attached to any list view.

**Comment by adityarb88** [comment]
@reddolan: Could you please take a look at this?

**Comment by bmgdev** [comment]
We use slide panels religiously, this would be a tremendous boon to add.

**Comment by colinreedmiller** [comment]
It will be helpful for people requesting this component to share some specifics on suggested interaction and content requirements.
How does the user access this?
Minimize / maximize?
What functionality is available within the panel?
In the datagrid example, will Master-Detail #3338 satisfy the use case?

**Comment by ccabezudo** [comment]
I will love to see this item too. Will use material design implementation while this gets implemented on clarity.

https://material.io/components/navigation-drawer/#usage

**Comment by hugohomesquita** [comment]
I will love to see this item too. Will use primeng implementation while this gets implemented on clarity. 😁

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
