### ISSUE TITLE
[Datagrid] Selection is cleared when applying a filter in multi-select grid

### ISSUE THREAD

**Issue by ivvatov** [vmware/clarity#2124]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
When a selection has been made and a filter is applied afterwards, the selection should be preserved. Or there should be an option to achieve the desired behavior when needed.

### Actual behavior
When a selection has been made and a filter is applied afterwards, the selection is not preserved. There is no way for the client to instruct the clr-datagrid to persist the selection after filter edits.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-cymqjw?file=app%2Fapp.component.ts

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all]

**Comment by adityarb88** [comment]
@ivvatov: Please refer to this comment: https://github.com/vmware/clarity/issues/484#issuecomment-285419495. This is the expected behavior. Please post your question and feedback on #484 for more details.

Closing as duplicate.

**Comment by reddolan** [comment]
For those following this issue, we have opened a [new issue](https://github.com/vmware/clarity/issues/2342) with the intent of solving this scenario. Please subscribe to the new issue for updates
