### ISSUE TITLE
New icons request

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#2129]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Request for various Text settings icons that would be useful for apps.

Set of text edit buttons (example):
![image](https://user-images.githubusercontent.com/23196444/38219852-7bf452cc-368c-11e8-88d6-ea2153951d10.png)

1. Text (add text/font style)
2. Text size
3. Header 1
4. Header 2
5. Header 3
6. Page
7. Check list
8. Bulleted List
9. Numbered list
10. Quotes
11. Bold (text)
12. Text Size
13. Underline
14. Italic
15. Align left
16. Align center
17. Align right
18. Align justify
19. Paint / color (A paint roller)
20. vertical content alignment (top, bottom, center)
21. horiz content alignment (left, right, center)
22. Coin bag - solid (To accompany line version done in vol 10)

**Comment by mathisscott** [comment]
Can we make sure that we group these icons into their own set? I can see them being useful for a subset of users but I don't see them being broadly applicable.

**Comment by dorthrithil** [comment]
Will there also be icons for vertical content alignment (top, bottom, center)?

**Comment by lil-kim** [comment]
@dorthrithil 
Sure. Added it to the list.

**Comment by mathisscott** [comment]
These were added with volume 11.
