### ISSUE TITLE
Datepicker override the styles

### ISSUE THREAD

**Issue by rameshyala** [vmware/clarity#2131]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@rameshyala: Please provide more information in the issue description. What is the issue that you are facing? Also, please provide a StackBlitz which replicates the issue.

Closing because the issue description does not have any information.
