### ISSUE TITLE
vsphere web client html clarity support pie chart ?

### ISSUE THREAD

**Issue by MuruganDell** [vmware/clarity#2132]
Hi all ,

    Please let me know  anyone which version of clarity  support  vsphere web client html5  pie chart 
,also attached the snapshot example on flex based  vsphere  web client   

<img width="288" alt="pie-chart" src="https://user-images.githubusercontent.com/29304103/38254003-b838411e-3775-11e8-9b6a-30ac1e305520.PNG">

**Comment by mathisscott** [comment]
@MuruganDell : Clarity currently does not have charts included in its library. People using Clarity have successfully used both High Charts and various flavors of d3 to generate charts for them.
