### ISSUE TITLE
[NG] Datagrid spec files compile even though they import the wrong interfaces

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#2136]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

If a spec file imports an interface that doesn't exist, tests should fail at compilation time.

### Actual behavior

They currently compile without even emitting a warning, and since interfaces disappear after compilation anyway, the tests run and pass.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/providers/filters.spec.ts contains the following import:
```typescript
import {Filter} from "../interfaces/filter";
```
But `Filter` doesn't exist anymore. Any IDE will show an error on this line, yet these tests are currently running and pass fine.

### Environment details

* **Clarity version:** 0.11.x

**Comment by gnomeontherun** [comment]
I came across this when doing the Angular 6 upgrade. 

https://github.com/vmware/clarity/commit/dc5e2bdf8fd580560b02b0f4bbfd64492c26eea8#diff-a9f1481d435a614d8710d59fe4abb11e
