### ISSUE TITLE
Icon request: File types

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2137]
```
[ ] bug
[x] feature request
[ ] enhancement
```

- An icon for PDFs would be very useful.

**Comment by mathisscott** [comment]
@lil-kim : what are our thoughts on icons for document types?

**Comment by lil-kim** [comment]
I agree. An icon for PDF and some other file formats would be useful. Will add this to Vol. 11

**Comment by mathisscott** [comment]
Cool. Thanks, @lil-kim . Would it make sense to put these icons in the same set as the word processor icons, technology set, or should they live in their own set?

**Comment by lil-kim** [comment]
There are so many file types I think they should live in their own set

**Comment by youdz** [comment]
As discussed in person, I suggest we look into having dynamic generation of file icons accepting any type as the shape: `<clr-icon shape="file-xxx"></clr-icon>` would generate an icon for the "XXX" file type.

This would allow us to avoid maintenance and constant requests for new file types, and reduce bundle weight by a gigantic amount if it collapses 100 icons down to a single SVG.

**Comment by lil-kim** [comment]
Examples of file formats:

PDF, JPG, EPS, AI, PSD, PNG, GIF, TIF, SKETCH
DOC, TXT, PPT, XLS, ZIP, EXE, MD, EPUB, MOBI, TTF, OTF, WOFF
MOV, AVI, MP3, MP4, WAV, PCM, M4A, MPEG, AVI
HTML, CSS, PHP, JS, XML, SVG, JSON, TS, DMG

**Comment by lil-kim** [comment]
Hi @Shijir , @youdz 
I'm attaching an svg file to test dynamic generation of file type icons. Let me know if you need anything else. 
[file type X.svg.zip](https://github.com/vmware/clarity/files/1905355/file.type.X.svg.zip)

![image](https://user-images.githubusercontent.com/23196444/38710056-20c7a770-3e73-11e8-84ea-f931ba89a7dd.png)

**Comment by lil-kim** [comment]
Needs dev research. Removing from Vol. 12

**Comment by gnomeontherun** [comment]
@lil-kim Did we ever get back to creating these icons or what is the status?

**Comment by lil-kim** [comment]
Nope. This one fell through the cracks. IDK if any tests were done to see if the different types could be generated dynamically. Maybe @Shijir knows?

**Comment by gnomeontherun** [comment]
Just posting an interesting way this could be done today with minimal effort and Core, but not something we have built in to Core icons.

The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
