### ISSUE TITLE
Clarity Iconography> Show a marker to indicate new icons

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#2139]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Clarity Iconography - When new icons are released, show an icon/marker next to each new icon.
 The marker should remain only until the next batch of new icons is released. One idea of how this could look:

![image](https://user-images.githubusercontent.com/23196444/38335410-09766edc-3813-11e8-9faf-199d87f966fc.png)
Lil-Kim to provide marker and mockups.

**Comment by youdz** [comment]
My two cents even if you didn't ask for it 😛, the gray marker doesn't really stand out, it almost looks to me like it clutters the screen because it's the same color as everything else. Maybe making it green or some other color (purple, I know...) could help?

**Comment by colinreedmiller** [comment]
Adding this to https://github.com/vmware/clarity/issues/1808

**Comment by yuxin-ux** [comment]
Just to clarify, how would a designer or developer use the "new" label to achieve a goal? I am trying to understand the scenario of how this is used besides "good to know"

**Comment by mathisscott** [comment]
This was just intended for documentation on the website. Because the icons today aren't really versioned. It can be hard to tell what's been added. 

If we move the icons into the versioned docs, the use case for this feature on the website becomes redundant.
