### ISSUE TITLE
Remove as many base64 icons as possible

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2155]
We want to reduce or remove the icons from being in the CSS directly if possible, for accessibility and customizability.

* [ ] Identify which icons can be removed
* [ ] Replace them with clr-icon implementations
* [ ] If breaking change, need to deprecate and then add issue to remove in future.

**Comment by adityarb88** [comment]
Looks like this is a duplicate of https://github.com/vmware/clarity/issues/2241

**Comment by gnomeontherun** [comment]
Decided we're going to timebox this issue and accomplish what we can, probably to 2 weeks.

**Comment by coryrylan** [comment]
This will improve render performance as well as removing duplication of the svgs. Non clr icon based images can be moved into assets by the clr add schematic.

- [ ] https://github.com/vmware/clarity/blob/ad0773ef6e142a762745b19dfcb53f3ad4afecc7/src/clr-angular/image/_icons.clarity.scss

- [ ] https://github.com/vmware/clarity/blob/e143b8590b8682caaecb86f5bc17ad691700f63d/src/clr-angular/layout/_variables.login.scss

**Comment by gnomeontherun** [comment]
Closing as the task is being handled naturally through Core.
