### ISSUE TITLE
Replace clang with prettier

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2156]
Setup prettier and only have it format changed lines.

**Comment by sdurnov** [comment]
AFAIK, you may have issues with Prettier's property 'semi' in TS. If property is set to "true", it will add semicolons in places where it may be banned as unneeded by tslint rule. If you set it to "false", it will remove some needed semicolons.
I'd suggest to use jsbeautify for html format, prettier only for CSS/SCSS and tsfmt(typescript-formatter) for TS.
