### ISSUE TITLE
Icon default size changes

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2158]
Currently icons are 16x16, proposal is to make them 12 or 18 for 6px baseline.

**Comment by colinreedmiller** [comment]
6px baseline is being compared to 8px for HawaiiFresh. Baseline may be changing. Default icon sizes will adjust (or not accordingly) If we stay with 6px we can re-examine this.

**Comment by mathisscott** [comment]
This doesn't seem like something we are tackling in the long term. Plz open a new ticket if we can take on a big visual change like this in the future.
