### ISSUE TITLE
Remove old forms and add shim layer

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2159]
To assist with migration, we plan to create a shim layer for old forms even when they are removed from the core build for projects to opt-into keeping old forms.

* [x] Remove old forms from main build
* [x] Documentation

**Comment by gnomeontherun** [comment]
@hippee-lee we still need to update the build for the sass to export a separate file for old forms.

**Comment by mathisscott** [comment]
@gnomeontherun 
What's our plan for this?

**Comment by gnomeontherun** [comment]
This is merged, we just need to do documentation now which is why this is still open.

**Comment by gnomeontherun** [comment]
Documentation has been updated.
