### ISSUE TITLE
Implement `clr-` prefix for css classes

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2162]
We want to implement all public styles with the `clr-` prefix. There should be a shim layer to support both styles.

* [ ] Implement new selectors
* [ ] Support old selectors via shim
* [ ] Look at using ng update to change

Investigate options to either ship both selectors in the same package, or as separate files for each use case.

**Comment by mathisscott** [comment]
As part of this work we also want to change old BEM variables to the new kebab case. So something like `$clr-element--thing` becomes `$clr-element-thing`

**Comment by kylebradshaw** [comment]
We've come up against this issue in our attempts to leverage Clarity in our established angular project. Some of the Clarity component styles have collisions with our current codebase. 
Ex. `.btn`,  `.btn-group`, .dropdown`, `.radio`, `.checkbox` etc
The Clarity css `clr-ui.css` is not namespaced/prefixed consistently.

I asked the question here: https://stackoverflow.com/questions/59274087/best-way-to-prefix-all-clarity-style-rules-for-inclusion-into-established-projec

Looks like in `@clr/ui@latest` the `.clr*` prefix is leveraged in some spots but not others. I see that this was changed to *Someday* - what is a good stop-gap to use? Is there a recommended postcss plugin that we might be able to leverage?

**Comment by mathisscott** [comment]
Hi @kylebradshaw 
After we got the 👍 to work on a foundational library of web-components, prefixing the global CSS became lower in priority. The future for us is Shadow DOM encapsulation to prevent styles clashing as you describe.

One additional problem with munging libraries together, though, is that even once (or if) we prefix all the classes, there will still be collisions as libraries like Bootstrap don't prefix their own styles.

The best path forward is to overwrite what you need to with CSS in your own project.

**Comment by kylebradshaw** [comment]
Thanks for your reply. I started to investigate some `postcss` solutions that might enable me to re-write some of the compiled css after the fact and landed on this lib https://www.npmjs.com/package/postcss-prefixer which seems to give me what I'm looking for, I just need to test it as a viable solution in our own project and will let you know how that works out.

**Comment by gnomeontherun** [comment]
Just FYI, a prefixer is helpful only if you can update all of the HTML at the same time.

**Comment by mathisscott** [comment]
Given the direction `@clr/ui` and `@clr/core` are moving, this is a non-issue.
