### ISSUE TITLE
DataGrid bottom border disappears when no footer is specified

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#217]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The DataGrid should have a bottom border when footer is removed.

### Actual behavior

The bottom border for the grid is not visible when footer is removed.
![image](https://cloud.githubusercontent.com/assets/1977391/21073359/fe52c332-bf16-11e6-8062-75d1678d0dcf.png)

```
<clr-datagrid>
    <clr-dg-column [clrDgField]="'name'">Name</clr-dg-column>
    <clr-dg-column [clrDgField]="'password'">Password</clr-dg-column>
    <clr-dg-column [clrDgField]="'active'">Active</clr-dg-column>

    <clr-dg-row *clrDgItems="let user of users">
        <clr-dg-cell>{{user.name}}</clr-dg-cell>
        <clr-dg-cell>{{user.password}}</clr-dg-cell>
        <clr-dg-cell>{{user.active}}</clr-dg-cell>
    </clr-dg-row>

    <!--<clr-dg-footer>{{users.length}} users</clr-dg-footer>-->
</clr-datagrid>
```
### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by yenmade** [comment]
@whizkidwwe1217 Some elements that could appear in the footer are pagination, and in the case of no pagination, the total item count. This can be useful so the user knows at a glance the # of items displayed and even 0 items in empty states. The footer also helps to visually contain information. Like in the case of scrolling within the datagrid, having a footer helps as a guide to where the scrollable area is. I'm interested in understanding a bit more around your use case for not having a footer in the datagrid. Can you help shed some light on this?

**Comment by yenmade** [comment]
In addition to the above, we have a future feature to allow show/hide column functionality accessed through an icon in the footer. While there are strong reasons to include a footer in a datagrid, we aim to have things work and look right independent of how it's used. 

The ideal design is to add the stroke with the 3 px corner radius to be consistent with the Clarity datagrid.

![3px_radius](https://cloud.githubusercontent.com/assets/22527471/22047074/9ea2120e-dcd9-11e6-836b-26fefd850d19.png)

This will require further investigation into the effort required to implement. If it is determined that the effort is large and may introduce bugs, the suggestion is to extend the stroke with no corner radius to the last row.

![no_radius](https://cloud.githubusercontent.com/assets/22527471/22047146/05a902e6-dcda-11e6-9c5c-ca2ffae8aeb6.png)

**Comment by yenmade** [comment]
We strongly recommend including a footer in a datagrid for the reasons stated above. Since no use cases for not having a footer has come to light, I'm going to close this issue.
