### ISSUE TITLE
Carousel Component

### ISSUE THREAD

**Issue by CastilloMike** [vmware/clarity#2174]
**Select one ...**  (check one with "x")
```
[ ] bug
[ x] feature request
[ ] enhancement
```

### Expected behavior

A carousel like the one that has Bootstrap

### Actual behavior

Clarity does not have a Carousel Component
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**
latest
* **OS and version:** 
any
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@reddolan: Could you please take a look at this?

**Comment by reddolan** [comment]
We won't be creating a carousel component. This is because it is known to have many usability and accessibility issues. 
https://www.nngroup.com/articles/auto-forwarding/

**Comment by reddolan** [comment]
I misunderstood the request. When carousels are used as a homepage hero component and have auto-forwarding, these are the implementations that are problematic. There are some useful implementations of a carousel though.

**Comment by reddolan** [comment]
Notes on best practices for design & implementation
- [https://www.nngroup.com/articles/designing-effective-carousels/](https://www.nngroup.com/articles/designing-effective-carousels/)
- [https://uxplanet.org/designing-a-user-friendly-homepage-carousel-f664c9f2b50e](https://uxplanet.org/designing-a-user-friendly-homepage-carousel-f664c9f2b50e)
- [https://www.nngroup.com/articles/auto-forwarding/](https://www.nngroup.com/articles/auto-forwarding/)
- [https://baymard.com/blog/homepage-carousel](https://baymard.com/blog/homepage-carousel)

**Comment by gitfan13** [comment]
I'm currently working on my second second Angular + Clarity project, and I will soon need a carousel element on many pages. I'd love to use a "native" carousel in Clarity, otherwise I'd have to build one myself, but it definitely won't be as nice as what you guys can build.  ;-)

**Comment by sadew145** [comment]
bootstrap.min.css will override clarity classes. Is there a fix so I can  use bootstrap 4 carousel?

**Comment by arwinters** [comment]
> @reddolan bootstrap.min.css will override clarity classes. Is there a fix so I can use bootstrap 4 carousel?

I saw the same behavior in my Clarity Angular Apps. It would be great to use a native Clarity carousel.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
