### ISSUE TITLE
Non-Bordered Table has light header border color in dark theme

### ISSUE THREAD

**Issue by thojo** [vmware/clarity#2176]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The bottom border color of table header cells for `.table-noborder` should be a darker color when using the dark theme, e.g. like border color of the basic table in dark theme.

### Actual behavior

For non-bordered tables in dark theme the header cell's bottom color is the light theme color.

### Reproduction of behavior

See light vs. dark theme:
* [Light Theme v11](https://stackblitz.com/edit/clarity-light-theme-v11-mp1fzh)
* [Dark Theme v11](https://stackblitz.com/edit/clarity-dark-theme-v11-cgfokt)

### Environment details

* **Angular version:** 5.2.9
* **Clarity version:** 0.11.12
* **OS and version:**
* **Browser:** all

**Comment by adityarb88** [comment]
@hippee-lee @lil-kim: Could you please take a look at this?

**Comment by hippee-lee** [comment]
Thanks for reporting this issue @thojo.
We will get a fix for it pushed out with this weeks release.
