### ISSUE TITLE
clr-datagrid doesn't resize correctly last data grid column when it displays long data  and columns have specified width

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#2177]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The horizontal scroll bar not to appear when resize columns.

### Actual behavior
The horizontal  scroll bar appears.
If the grid has row actions the horizontal  scroll bar doesn't appear. I would like the same behavior
when there is no row actions.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-s1mu2h

### Environment details

* **Angular version:** 5.2.1

* **Clarity version: 0.11.1

* **OS and version: Windows 10

* **Browser:** Chrome

**Comment by youdz** [comment]
This looks like a bug to me, some variation of the automatic column width computing + extra columns (checkboxes, actions, expand caret, ...) that we supposedly fixed a while back.

At the very least both version of the datagrid in this stackblitz should have the same behavior. In the second one, it looks like the width computed for the last column doesn't use the proper column's data.

**Comment by youdz** [comment]
Fixed by #2670.
