### ISSUE TITLE
Inconsistent single action behavior if filter is opened in datagrid

### ISSUE THREAD

**Issue by jansivans** [vmware/clarity#2186]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior
If a datagrid has single row action and filter opened, action behaves inconsistently.

### Reproduction of behavior

1. Go to https://stackblitz.com/edit/clarity-light-theme-v11-91w4f7
2. Click "three dots" one by one. Result can be seen in screenshot:
![](https://i.imgur.com/hvb5ZXy.png)
Everything works so far - each action window opens one by one.
3. Open filter window for "Name" column.
4. Try clicking "three dots" - this can be done now only with double-click and everything becomes ugly if trying to click other "three dots" buttons:
![](https://i.imgur.com/9kqOuNr.png)

### Environment details

* **Angular version:** 5.2.1 (also tested with 5.2.9)

* **Clarity version:** 0.11.13

* **OS and version:** Windows 10

* **Browser:** all

**Comment by adityarb88** [comment]
@jansivans: Thanks for reporting this. This does look a bug. We will take a look and get back to you.

**Comment by adityarb88** [comment]
cc: @youdz

**Comment by phuongtailtranminh** [comment]
Any improvement for this? I've met the same error

**Comment by hippee-lee** [comment]
It looks like this is still an issue in the latest version: https://stackblitz.com/edit/clarity-light-theme-v11-5zwq1b

I'm currently working on improving Clarity Popovers in general: #2923 and will check this behavior with the solution I've got in my PR #3374

**Comment by phuongtailtranminh** [comment]
> It looks like this is still an issue in the latest version: https://stackblitz.com/edit/clarity-light-theme-v11-5zwq1b
> 
> I'm currently working on improving Clarity Popovers in general: #2923 and will check this behavior with the solution I've got in my PR #3374

Yes. It's still an issue in the latest version (1.1.3)

May I know when the next version will be shipped?

**Comment by hippee-lee** [comment]
As mentioned above I have PR (#3374) - with the pieces. I still need to write the unit tests for the services and directives. 
At the same time I'm getting our sources ready for Clarity v2.0.0 (here is the [milestone](https://github.com/vmware/clarity/milestone/58)) this got delayed by a few days. Angular release an unexpected `rc` with some breaking changes and the vull version of Angular dropped yesterday. I'm actively working on verifying the next version of Clarity and it should ship in the next few days, next week at the latest. Once thats out I can re-focus my attention on the unit tests for Smart Popovers and getting it through the review process. 

Follow along the linked issues and milestone for the latest info.
