### ISSUE TITLE
Icon Request - Peso Currency Symbol

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#2191]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```
Can I request for a Peso currency symbol?
![image](https://user-images.githubusercontent.com/1977391/38779314-250a36b2-40f9-11e8-9e06-07fc6ff0e928.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@lil-kim: Could you please take a look at this request?

**Comment by pumano** [comment]
Also will be good to have russian rouble sign: ₽

**Comment by mathisscott** [comment]
Hi @pumano 
Could you open a separate github issue for the Ruble? We will try to get it into our Vol. 12 icon release in a couple of months.

Thanks!

**Comment by pumano** [comment]
Yes, sure #2221
