### ISSUE TITLE
looks like the community page is not being updated

### ISSUE THREAD

**Issue by Thatkookooguy** [vmware/clarity#2192]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Once a user contributed to this repo, their username should be added to the "Contributors" list.
(if not immediately, then at a reasonable interval). If not by name, at least by username

### Actual behavior
The Contributors list on `GitHub` for clarity is not synchronized with the one on the `clarity site`.

### Reproduction of behavior
just compare these:
1. https://vmware.github.io/clarity/community
2. https://github.com/vmware/clarity/graphs/contributors

### Environment details

Here's a table of the Github's Contributors list for this repo, stacked against if they got a shoutout in the clarity contributors section:

github name | github username | got a shoutout
------------ | ------------- | -------------
**Victor Mejia** | [victormejia](https://github.com/victormejia) | **true**
**Cotton Hou** | [imcotton](https://github.com/imcotton) | **true**
**Alex Mellnik** | [amellnik](https://github.com/amellnik) | **true**
**Gerin Jacob** | [gerinjacob](https://github.com/gerinjacob) | **true**
**Govinda Alwani** | [govi2010](https://github.com/govi2010) | **true**
**Clement Cureau** | [clementcur](https://github.com/clementcur) | **true**
**Ivan Donchev** | [Jinnie](https://github.com/Jinnie) | **true**
**Robert Pamfile** | [Robertmw](https://github.com/Robertmw) | **true**
**chunghha** | [chunghha](https://github.com/chunghha) | false
**bdunkz** | [bdunkz](https://github.com/bdunkz) | false
**bdunkz** | [bdunkz](https://github.com/bdunkz) | false
**matonev** | [matonev](https://github.com/matonev) | false
**David Herges** | [dherges](https://github.com/dherges) | false
**PatrickJS** | [gdi2290](https://github.com/gdi2290) | false
**gachappell** | [gachappell](https://github.com/gachappell) | false
**Alyssa Brunswick** | [alyssabrunswick](https://github.com/alyssabrunswick) | false
**Marc Viger** | [mviger](https://github.com/mviger) | false
**Neil Kalman** | [Thatkookooguy](https://github.com/Thatkookooguy) | false
**dgrahn** | [dgrahn](https://github.com/dgrahn) | false
**Willian Oliveira** | [williangd](https://github.com/williangd) | false
**Bojan Đurđević** | [bojan88](https://github.com/bojan88) | false
**Denis** | [uncledent](https://github.com/uncledent) | false (unless it's Denis Beklarov)
**Kaelig Deloumeau-Prigent** | [kaelig](https://github.com/kaelig) | false
**Sebastian Döll** | [katallaxie](https://github.com/katallaxie) | false
**Travis Finch** | [travisfinch](https://github.com/travisfinch) | false

(All older contributors don't show on github (before Aug 2016))
TOTAL: 25
GOT CREDIT: 8
DID NOT GET CREDIT: 17

* **Clarity version:** current

* **Browser:** all

**Comment by adityarb88** [comment]
@Thatkookooguy: Thanks for reporting this! Although some of the names have already been mentioned on the Community page (For eg: `bdunkz` is `Brian Duncan`), I do agree that some are missing too. We actually want to automate this process. Right now we manually add names to the contributors list on the Community Page.

We will add this to our list our enhancements for the website. Thanks!

**Comment by gnomeontherun** [comment]
This is something I have planned for a website refresh, until then it will likely be manual.
