### ISSUE TITLE
18 px spacing option for modal and wizard windows

### ISSUE THREAD

**Issue by jeremydejiacomo** [vmware/clarity#2194]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Description
Enhancement to modal and wizard window spacing structure to allow for an 18 px base option to the 24 px standard spacing.

### Documentation
Ability to set the spacing default for modal and wizard windows to be 18 px. This allows for smaller header, footer, and wizard nav panel areas and to be used in conjunction with the header and footer structure changes in this item: https://github.com/vmware/clarity/issues/2188

Wizard Specs
![screen shot 2018-04-16 at 10 12 42 am](https://user-images.githubusercontent.com/7140246/38827629-8680b2bc-4181-11e8-9438-a4630d1548bd.png)

Modal Specs
![screen shot 2018-04-16 at 10 17 28 am](https://user-images.githubusercontent.com/7140246/38827638-8cf05cce-4181-11e8-8279-0262a58da502.png)

**Comment by gnomeontherun** [comment]
@mathisscott can we consider this closed via Core? It would be possible to more easily configure the spacing.

**Comment by mathisscott** [comment]
@gnomeontherun : The core modal does not presently allow for easy customization of the outer padding. I could add that as a non-breaking change. But it would land after v5.

**Comment by gnomeontherun** [comment]
This is related to #2188 and closing with the same resolution details.
