### ISSUE TITLE
Signpost at wrong position if google chart is inside

### ISSUE THREAD

**Issue by Capsicum42** [vmware/clarity#2198]
[x] bug
[ ] feature request
[ ] enhancement
`

### Expected behavior
The signpost should start with the arrow at the info symbol.
I included a google chart in the signpost

### Actual behavior
For all position "top" the arrow is below the info symbol

https://stackblitz.com/edit/signpost-google-chart?embed=1&file=app/app.component.html
Wrong: (This is the result from clicking on the first info box)
![image](https://user-images.githubusercontent.com/16342525/38978262-24bed6d4-43b7-11e8-9763-862c465879fd.png)

Correct:
![image](https://user-images.githubusercontent.com/16342525/38978318-586e8542-43b7-11e8-8c34-b861dcac079d.png)

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:**
0.11.13

* **OS and version:** 
Ubuntu 16.04.3
* **Browser:**  Chrome 65
 Firefox 59

**Comment by gnomeontherun** [comment]
This appears to be an issue with the lifecycle of your charts. Your chart is rendered _after_ the signpost position and size is calculated (so it renders a signpost based on a non-existant chart), and when the chart renders it causes the signpost to expand but the arrow positions are no longer calculated right. Your charts are also outside of normal change detection.

If you know the size of the chart to render, then you can set explicit width/height on the my-chart component content so the signpost can calculate its position and size appropriately. Alternatively, you could render the charts _before_ the my-chart OnInit lifecycle hook. Closing based on the solution being part of the implementation.
