### ISSUE TITLE
Modal as different component

### ISSUE THREAD

**Issue by nithinkarthik6** [vmware/clarity#2199]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Modal as a different component should be included

### Actual behavior

Modals are working fine if i put them in main.component.html but i want to create a seperate modal component.html and .ts and include it in main page. How do i do it ? 
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 5.2.8

* **Clarity version:** v0.11

* **OS and version:** windows

* **Browser:** all

**Comment by realcnbs** [comment]
Something like this?
https://stackblitz.com/edit/clarity-light-theme-v11-3clpz8

**Comment by hippee-lee** [comment]
Hi @nithinkarthik6 - this isn't an issue with Clarity itself. Would you mind asking on StackOverflow and tag your question with `vmware-clarity`? If you post a Stackblitz for what you have tried so far when we answer it there it will help the community.
