### ISSUE TITLE
Tooltip within Wizard + Stack View not visible

### ISSUE THREAD

**Issue by sascha-friederich** [vmware/clarity#2200]
### Since clarity version 0.11.7 tooltip is not displayed anymore.

**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When I open a wizard that uses a Stack view the tooltip should be visible!

![tooltip_clarity_11_6](https://user-images.githubusercontent.com/25248228/38986552-06246a48-43cd-11e8-93a2-2b1c87050beb.png)

### Actual behavior
When I open a wizard that uses a Stack view the tooltip is not displayed anymore!

![tooltip_clarity_11_7](https://user-images.githubusercontent.com/25248228/38986527-ef740b78-43cc-11e8-8edd-2af8cdd53b55.png)

### Environment details

* **Angular version:** 5.2.10

* **Clarity version:** 0.11.7 until 0.11.13

* **OS and version:** Windows 7

* **Browser:**   Chrome 65, Firefox 52.3 ESR

**Comment by pumano** [comment]
I report similar issue too: https://github.com/vmware/clarity/issues/1880
Hope Clarity Team fix it.

**Comment by adityarb88** [comment]
@sascha-friederich: Please refer to this comment: https://github.com/vmware/clarity/issues/1880#issuecomment-359541423

Are you using the Angular tooltip component or the static one? You need to use the Angular tooltip component to avoid clipping.

**Comment by sascha-friederich** [comment]
thanx for the hint - using the angular component instead of the static one everything is fine.
