### ISSUE TITLE
Wizard step error state

### ISSUE THREAD

**Issue by jeremydejiacomo** [vmware/clarity#2203]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Description
Enhancement to the wizard component to add an error state to the wizard step states.
Wizard step states:
- Inactive
- Active
- Complete
- Error (new state addition)

### Documentation
Wizard step state that displays when an error has occurred once the wizard is saved/submitted/published. This addresses two primary scenarios: 
1. Once wizard steps are complete, on save/submit/publish the information is sent to a server/service to be validated and incorrect input(s) need to be reported back to the corresponding step(s).
2. When selections in a later step in the wizard invalidate an entry in earlier steps.

The error state utilizes a color change in the progress indicator, an alert icon, and subtle border between other steps to draw attention to the error status. See below for specs:

Error reported:
![error_state_specs](https://user-images.githubusercontent.com/7140246/39010109-a00c4776-43db-11e8-82d9-7ddfa11efbe1.png)

Error state active:
![error_state_behavior](https://user-images.githubusercontent.com/7140246/39010118-a5f8323a-43db-11e8-9378-ffa2dedcc7b5.png)

**Comment by ybian02** [comment]
### Description
Enhancement to the wizard component to add an error state to the wizard step states.
Wizard step states:

- Inactive

- Active

- Complete

- Error(new state addition)

### Error Reported
When an error occurs, replace the step number with the error icon to ensure consistency with the stepper design. Change the progress indicator to red and add a one-px gap above and below the red bar for accessibility.

![error-reported](https://user-images.githubusercontent.com/14363961/43278401-e01bf254-90bf-11e8-9988-472572de13d5.png)

### Error State Active
Indicate clearly why the error occurs on the error step. 

![error-state-active](https://user-images.githubusercontent.com/14363961/43278408-eba5205a-90bf-11e8-8309-f620fdb07268.png)

### Error Resolved
The progress indicator changed back to green once all errors are resolved.

![error-resolved](https://user-images.githubusercontent.com/14363961/43278421-f212b02e-90bf-11e8-95b5-eb00c8c1f421.png)

**Comment by Only1MrAnderson** [comment]
Hey, 
Any insight into how we could accomplish this while it is still being developed? I see @coryrylan updated the docs but not sure how we can change the page number since it is not exposed in the template...

**Comment by mathisscott** [comment]
@Only1MrAnderson 
The current page of the wizard can be set by using `wizard.goTo()` or by setting the `currentPage` property in the navService.

**Comment by Only1MrAnderson** [comment]
@mathisscott thanks for the reply.  I understand that, but how does one modify the UI as it defaults to the number of the page? I am referring to this image here. There is nothing in the documentation about overriding that.

![43278408-eba5205a-90bf-11e8-8309-f620fdb07268](https://user-images.githubusercontent.com/8826208/55822971-5d7cdf80-5ac6-11e9-8a67-69749ea1c936.png)

**Comment by hippee-lee** [comment]
The image with the red icon next to _Very beautiful images_ is the mockup / design that needs to be implemented. I know it looks like the real thing but I believe it is an image from Sketch. 

Does using form validation help the wizard user address errors and issues before moving on to the next step? Even though this hasn't yet been implemented yet? 
It does sound like this feature is important the app. Would you be interested in contributing here?

**Comment by Only1MrAnderson** [comment]
@hippee-lee I agree it is very beautiful. I would be interested in contributing. Let me give contributing.md a quick read 👍

**Comment by antonevane** [comment]
Is there a timeline for implementation.

**Comment by hippee-lee** [comment]
This feature is still in the backlog queue.

**Comment by jeff-bacon** [comment]
Are there any plans to remove this from the official documentation since it's not implemented yet?  A little text giving a warning to readers would even suffice.  Unfortunately I spent time refactoring some of my code base to implement this feature but when the time came, found out that it was not even a feature in Clarity although it has a fairly large section under the wizard documentation.

**Comment by florin-borceanu** [comment]
I'm working on this issue, can you assign me please?
