### ISSUE TITLE
Date input doesn't show errors properly 

### ISSUE THREAD

**Issue by delockdown** [vmware/clarity#2206]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Need to be show the error as it is in other input fields

### Actual behavior
![screen shot 2018-04-23 at 1 36 32 pm](https://user-images.githubusercontent.com/1327120/39114079-61795896-46fb-11e8-8485-9ee4289aa8b4.png)

when error value is entered it will show the icon but doesn't show any thing. For correct value, icon will disappear. Everything works fine except the showing of error message. 
Am I doing it wrong or is there any UI issue with date validation?  

### Reproduction of behavior
```HTML 
<div class="form-group">
     <label for="date">Date</label>
     <label [class.invalid]="form.get('date').invalid
         && form.get('date').dirty"
         role="tooltip"
        class="tooltip tooltip-validation tooltip-sm">
        <input id="dateControl" type="date" clrDate formControlName="date"/>
         <span class="tooltip-content" *ngIf="form.get('date').hasError('date')">
              Enter valid date
        </span>
         </label>
</div>
```

### Environment details

* **Angular version:** 5.2.0

* **Clarity version:** 0.11.11

* **OS and version:** Mac OS High Sierra

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@delockdown: Thanks! This is a known issue. I am going to close this as duplicate. Please refer to this issue for more info: https://github.com/vmware/clarity/issues/2058#issuecomment-372349255

We are currently working on a new version of forms which will resolve this. Please let us know if you have any other questions.
