### ISSUE TITLE
Proposal: move UX development from Sketch to Figma

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2207]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Sketch is great tool, but it works only for Mac users.
There's a cross-platform tool with apps for Mac and Windows, which also works in browser - [Figma](https://figma.com). This is a very Sketch-like with support of components and components library, which supports master components, instances and their auto-update.
You can import sketch files to Figma, but native Figma experience is more powerful.
Figma is free for small teams.

Figma also provides API, which may be used for creating Figma-to-HTML or even Figma-to-Angular converters.

**Comment by reddolan** [comment]
Figma is a quickly growing platform, and this sounds like a great idea! It also sounds like you are skilled in Figma. While we don’t have the resources to maintain something like this as a part of Clarity, if you wanted to create the resources we would be happy to let folks know about your efforts.

**Comment by sdurnov** [comment]
Ok then, I have a question. If I'll create Clarity components for Figma, may I sell it?

**Comment by mathisscott** [comment]
@sdurnov 
Per our license, you are free to sell a Figma library.

https://github.com/vmware/clarity/blob/master/LICENSE

**Comment by 11mb** [comment]
@sdurnov, do you already sell this?

**Comment by sdurnov** [comment]
@11mb, gonna finish library in a week or so

**Comment by sdurnov** [comment]
@reddolan @mathisscott just posted a public version of Clarity UI kit for Figma.
[Medium post](https://medium.com/@sergey_81667/clarity-design-system-for-figma-9778e11cf30f)

I would appreciate if you check it out and promote it smh.
