### ISSUE TITLE
Adjusting vertical spacing in Tree View

### ISSUE THREAD

**Issue by DonaldAlan** [vmware/clarity#2209]
Is there a way to adjust the vertical spacing between lines/entries in Tree View? I want it more compressed.

**Comment by adityarb88** [comment]
@DonaldAlan: You could do this on your end. You would just have to override the styles. Something like this: https://stackblitz.com/edit/clarity-light-theme-v11-jyfrr8?file=app/app.component.css

For more info please refer to this link: https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

Let us know if this helps. Closing the issue based on this.
