### ISSUE TITLE
Clarity UX center

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2212]
```
[ ] bug
[x] feature request
[ ] enhancement
```
I feel like design guidelines are nice, but not enough.

I'm sure that there's a lot of screens are being created internally by VMware itself, and there should be even more created by teams who use Clarity.

I think it would be great help for all who start using Clarity to have more examples of layouts created using Clarity.

How about creating a page with gallery or blog, where people can share their real life examples or concepts, both VMware devs and external devs, to share skills or get some critics?

**Comment by sdurnov** [comment]
@mathisscott btw, what about, at least, creating a room in [Spectrum chat](https://spectrum.chat) and promoting it on the main page?

**Comment by IASamoylov** [comment]
It's a good idea, I think that in the documentation has not enough examples for content:

I want to see more guidelines for:
- Titles
- Sub titles
- Links/Actions under title

Now we only have
- Main content [Application Layout - Common Layout Patterns](https://v1.clarity.design/app-layout#guidelines)

and maybe add examples with styles for these elements, how it made for [headers](https://v1.clarity.design/header)

I found some practices used on the site

![image](https://user-images.githubusercontent.com/19590161/57619943-fc966a80-758f-11e9-9105-05cf502bba94.png)
![image](https://user-images.githubusercontent.com/19590161/57620768-70397700-7592-11e9-9e6b-e94ff16cba79.png)


and base paddings for content

![image](https://user-images.githubusercontent.com/19590161/57620048-526b1280-7590-11e9-8eec-9e6a5bca0c4d.png)

**Comment by IASamoylov** [comment]
Any best practices in UI/UX will be good for teams of developers that don't have a designer.

**Comment by bdryanovski** [comment]
I think that this discussion here will be best suited for Github Discussions and closing the issues 

@gnomeontherun

**Comment by gnomeontherun** [comment]
We are working toward improvements and I will close this as resolved by those efforts at least to some degree, since the asks here are not very specific. Additional requests should go to Discussions.
