### ISSUE TITLE
[NG] Tabs overflow toggle is missing type="button"

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#2214]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Any button in the template of a Clarity component should have `type="button"`, in case the component is used inside of a form.

### Actual behavior

The tab overflow toggle doesn't have `type="button"`, so when the tabs are used in a form opening the toggle submits the form every time. Reported here: https://stackoverflow.com/questions/50027543/clarity-tab-overflow-button-submits-form

### Reproduction of behavior
I should do one, but we know it breaks. Please don't take this issue as an example of "I don't need to reproduce the behavior".

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.11.x

* **Browser:** all

**Comment by adityarb88** [comment]
assigned it to myself. will fix it soon. thanks!
