### ISSUE TITLE
Add documentation about the FocusTrap and FocusTrapTracker directives

### ISSUE THREAD

**Issue by tkoleary** [vmware/clarity#2218]
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
I expected that the online documentation would tell me something about how to make modals more accessible.

### Actual behavior
 Finding none I assumed that I'd need to build a component myself. After struggling for a while with this I accidentally discovered that there is a simple directive clrFocusTrap that accomplishes what I wanted to do.

Adding some reference to clrFocusTrap here: https://vmware.github.io/clarity/documentation/v0.11/modals would be nice. As well as some documentation on FocusTrapTracker which I'm still not quite sure how to use but looks promising.

**Comment by Shijir** [comment]
Hi @tkoleary, we haven't documented about `FocusTrap` directive because it's one of our several components/directives that are created with an intention to be used internally only.

**Comment by tkoleary** [comment]
What?! What does "internally only" mean? The directives are in the repo and the repo is open-source, per the license.

"The MIT license (the "License") set forth below **_applies to all parts of the Clarity project_** except for the fonts" (my emphasis)

You are certainly not obligated to write documentation for everything in the project but if the goal of making it open-source is to get others outside VMWare to use and extend it, having complete documentation would be a good idea.
