### ISSUE TITLE
Ruble sign icon

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#2221]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior

Please add russian ruble sign icon: ₽
For details: https://en.wikipedia.org/wiki/Ruble_sign

**Comment by sdurnov** [comment]
Yes, please. Also, we need some failback font for Cyrillic, which is compatible with Metropolis.
