### ISSUE TITLE
[datagrid] Chrome issue on header on sorting

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#2229]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When a user click on datagrid header to sort the header shall look like
<img width="917" alt="datagrid-header-safari" src="https://user-images.githubusercontent.com/3706809/39536570-4a0de81e-4e37-11e8-8353-571bfd908002.png">

### Actual behavior
In Chrome the header looks like
<img width="901" alt="datagrid-header-chrome" src="https://user-images.githubusercontent.com/3706809/39536602-5d445b3e-4e37-11e8-80cf-2dc1c7a022d0.png">

### Reproduction of behavior
All the screenshots are taken from the official documentation website
Go (https://vmware.github.io/clarity/documentation/v0.11/datagrid/server-driven) and click on some  section to sort

### Environment details

* **Angular version:** 5.2.x

* **Clarity version:** latest

* **OS and version:** macOS 10.12.6

* **Browser:** [Chrome XX ]

**Comment by Shijir** [comment]
Well, that's a default focus outline by Chrome, which is an accessibility feature. So we avoid removing that outline as it would make it very challenging if not impossible for keyboard users to tell where they are on the page.

**Comment by mcosta74** [comment]
ok thanks
