### ISSUE TITLE
Line height is 23px on anchors in dropdowns

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#223]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Line height should be 24px on [dropdown list items](https://vmware.github.io/clarity/documentation/dropdowns)

### Actual behavior
Line height is 23px in the generated CSS

### Reproduction of behavior
![image](https://cloud.githubusercontent.com/assets/1858226/21114095/8e4a7f56-c071-11e6-8509-6ad05599106e.png)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.7.4

* **OS and version:** OSX 10.12.1

* **Browser:** [Chrome 54.0.2840.98]

**Comment by jaffoneh** [comment]
@adityarb88 could you confirm and have a chat with @reddolan to get this fixed?

**Comment by adityarb88** [comment]
@reddolan: I see the height as 24px on the website and on my demo app. Is there any particular example that this is failing on? We did set the `line-height` to 23px because the text didn't appear vertically centered otherwise on Edge. @mathisscott could you please confirm this?

**Comment by reddolan** [comment]
In the screenshot above, you can see that the CSS is showing 23px for line-height. This is directly from the website: [https://vmware.github.io/clarity/documentation/dropdowns](https://vmware.github.io/clarity/documentation/dropdowns)

It is coming from clarity-ui-min for .dropdown .dropdown-menu .dropdown-item

**Comment by adityarb88** [comment]
@reddolan. I know the line-height is set to 23px but that was done to vertically align the text on certain browsers. Along with the 23px line-height, we have also added a padding-top of 1px to make sure that the height remains 24px. I am not able to replicate the issue on my end :(

**Comment by jaffoneh** [comment]
@reddolan @adityarb88 I am unable to replicate the issue on my end either. I see it at 24px. 
<img width="320" alt="screen shot 2016-12-12 at 12 49 14 pm" src="https://cloud.githubusercontent.com/assets/690949/21116513/bd414be8-c06a-11e6-894f-ed0b29dc11d4.png">

**Comment by jaffoneh** [comment]
Even though line-height is at 23px, we're still following our vertical rhythm and the overall is still at 24px. I am closing based on this and the comment before it.
