### ISSUE TITLE
Corner drag-handle icon

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2233]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
A drag handle icon for corners.

### Actual behavior
Currently there's a drag-handle icon which is great for horizontal and vertical dragging. For dragging in two directions simultaneously, e.g. when grabbing the corner of an element, this icon does not convey the right meaning to the user.

**Comment by adityarb88** [comment]
@lil-kim: Could you please take a look at this?

**Comment by lil-kim** [comment]
Hi @dorthrithil 
We have a "resize" icon on the Clarity Iconography page:
https://vmware.github.io/clarity/icons/icon-sets#commerce-shapes
![image](https://user-images.githubusercontent.com/23196444/39718028-e199db60-51e9-11e8-82e0-85fe584c65f4.png)
This would need to be flipped, of course, if you're dragging a window from the bottom right corner. Is this icon what you had in mind?

**Comment by dorthrithil** [comment]
This would be OK if I wouldn't have to combine it with the standard drag handle icons. The usecase where I could need such an icon is an editor where one of the features is to resize boxes:

![usecase](https://user-images.githubusercontent.com/3655915/39864525-28fb09ea-544a-11e8-83eb-f61ac7fde0d7.jpg)

**Comment by lil-kim** [comment]
Ah, I see. Thanks @dorthrithil for clarifying your use case. I will design it to be consistent with the standard drag handles.
