### ISSUE TITLE
clr-datagrid loading spinner placement bug

### ISSUE THREAD

**Issue by petarbk** [vmware/clarity#2234]
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
If the clr-datagrid is in a loading state and we have horizontal scroller, datagrid's spinner overlay and the spinner itself should be placed correctly.

### Actual behavior
Spinner's overlay and the spinner are not placed correctly if we scroll horizontally. Also the overlay's height exceeds content's height (this is caused by margin-top rule that is applied on clr-datagrid's inner` <div class='datagrid'>`).

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-spinner-bug

### Environment details
Clarity version: 0.11

Browser: all

**Comment by petarbk** [comment]
I fix this by using the following CSS rules: 
```
.datagrid-spinner {
      position: sticky;
      left: 0;
      top: 0;
}
```

This doesn't fix the excessive height, though. One solution is to simply remove the problematic margin-top rule. Or apply a margin-top rule with the same value to .datagrid-spinner. For me the best solution is just removing the margin. This also fixes another issue - if you have content above the grid, it won't align properly because you have this extra space.

**Comment by hippee-lee** [comment]
Hey @petarbk , I'm closing this because there is already an issue for centering the loading spinner properly here: https://github.com/vmware/clarity/issues/1409

Please subscribe to that issue for updates and the latest changes to the feature branch that will fix these issues.

**Comment by hippee-lee** [comment]
Correct, Both issues (horizontal and vertical positioning of hte loading spinner) will be addressed with the changes I'm making for pinned first column. 
The loading spinner will overlay the entire datagrid and prevent user interaction with the datagrid until loading is complete.
