### ISSUE TITLE
Intelligent popover positioning using @angular/cdk overlay module

### ISSUE THREAD

**Issue by sosharma1403** [vmware/clarity#2240]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
Popover components should change their position in order to be visible on the screen all the time.

### Actual behavior
Dropdown menu gets clipped off when placed to extreme right or left of the screen.
![clarity-dropdown](https://user-images.githubusercontent.com/30067725/39687445-1a68eefc-51ec-11e8-86a5-325a96f64b28.png)

### Related issue
#1262 

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** Latest

* **OS and version:**  windows 7

* **Browser:** all

**Comment by gnomeontherun** [comment]
Hello, to provide us with a meaningful feature request, please fill out details and explain what your needs are. Don't focus on the implementation (like using @angular/cdk, because we don't), but rather focus on the problem or feature.

**Comment by vinayakpatil** [comment]
@gnomeontherun I know we should NOT focus on the implementation part but would like to suggest http://tether.io for above requirement.

cc: @youdz @adityarb88

**Comment by sosharma1403** [comment]
@gnomeontherun Information provided

**Comment by gnomeontherun** [comment]
This is resolved by the #2923 implementation, closing as fixed.
