### ISSUE TITLE
VMware clarity not supporting for latest version of rxjs in Angular 6.

### ISSUE THREAD

**Issue by jaanreddy** [vmware/clarity#2244]
Getting below error
================

ERROR in ./node_modules/@clr/angular/esm5/clr-angular.js
Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in 'D:\jaan\harman\Angular6_VMware-clr-App\ng6-vmware-clr-app\node_modules\@clr\angular\esm5'
ERROR in ./node_modules/@clr/angular/esm5/clr-angular.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'D:\jaan\harman\Angular6_VMware-clr-App\ng6-vmware-clr-app\node_modules\@clr\angular\esm5'
ERROR in ./node_modules/@clr/angular/esm5/clr-angular.js
Module not found: Error: Can't resolve 'rxjs/operator/first' in 'D:\jaan\harman\Angular6_VMware-clr-App\ng6-vmware-clr-app\node_modules\@clr\angular\esm5'
ERROR in ./node_modules/@clr/angular/esm5/clr-angular.js
Module not found: Error: Can't resolve 'rxjs/operators/map' in 'D:\jaan\harman\Angular6_VMware-clr-App\ng6-vmware-clr-app\node_modules\@clr\angular\esm5'

**Comment by dorthrithil** [comment]
I would guess this will be fixed in https://github.com/vmware/clarity/pull/2238

**Comment by pumano** [comment]
`rxjs-compat` solve problem. I have fully working clarity with angular 6

**Comment by tarundhillon** [comment]
@pumano can you please expand how you are using rxjs-compat to overcome clarity compatibility issues  ? Thanks

**Comment by pumano** [comment]
@tarundhillon when you upgrade to angular 6 you need to install `rxjs-compat` npm module for project. 
Check https://update.angular.io/ for more details.
It's specially for having backward compatibility with 5 rxjs libs. I'm sucessfully upgraded to angular 6 and clarity works perfectly.

**Comment by tarundhillon** [comment]
brilliant !! thanks

**Comment by adityarb88** [comment]
Thanks @pumano. Closing based on the above info provided by @pumano.

**Comment by adityarb88** [comment]
Also please refer to https://github.com/vmware/clarity/issues/2242

**Comment by jaanreddy** [comment]
Thank you, It's working :)
