### ISSUE TITLE
Wizard full width footer area for action buttons

### ISSUE THREAD

**Issue by jeremydejiacomo** [vmware/clarity#2246]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Description
Enhancement to the wizard component for the footer area to extend the full width of the modal window. This allows for:
- clear separation of content area and buttons
- increased space for multiple buttons 
- increased space for longer string length of button labels

### Documentation
Wizard footer area that spans the width of the modal with the left navigation panel height ending at the footer area divider. These visual design changes impact the standard 24px wizard spacing as well as the 18px alternate wizard spacing previously submitted (see issue: https://github.com/vmware/clarity/issues/2194 ) 
View comps below for specs:

Full width footer with wizard using 24px spacing
<img width="811" alt="fullwidth_footer_24px" src="https://user-images.githubusercontent.com/7140246/39716226-c1c22d9c-51fd-11e8-8999-df5b04841e31.png">

Full width footer with wizard using 18px spacing
<img width="810" alt="fullwidth_footer_18px" src="https://user-images.githubusercontent.com/7140246/39716302-fd79bb0c-51fd-11e8-8ff6-4c17d37913b8.png">

**Comment by adityarb88** [comment]
Thanks @jeremydejiacomo!

**Comment by mathisscott** [comment]
@gnomeontherun @colinreedmiller @hippee-lee : Are these Wizard enhancements something we are considering in the near future? If so, is this something we want to drive from @clr/core and push out from that vector into @clr/angular? Or is this something we would consider implementing in the angular components first? I also want to acknowledge that UX/Design is a blocker here so our answers to those questions will be impacted by that timeline.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
