### ISSUE TITLE
Wizard left step navigation panel collapse/expand interaction

### ISSUE THREAD

**Issue by jeremydejiacomo** [vmware/clarity#2247]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Description
Enhancement to the wizard component to allow users to collapse and re-expand the left step navigation panel. This gives users the ability to increase the content area.

### Documentation
Wizard left step navigation panel collapsible functionality to emphasize information in the content area. The collapse/expand interaction behavior is based on the Vertical Nav component collapse/expand behavior with differences in placement and icon versus horizontal rule relationship. The steps should display step number and maintain step state when left navigation panel is collapsed. See comps below for specs:

Visual specs:
<img width="962" alt="collapse-expand_visual_specs" src="https://user-images.githubusercontent.com/7140246/39717501-75061adc-5201-11e8-9e22-1704774b682f.png">

Spacing (expanded)
<img width="895" alt="expanded_spacing" src="https://user-images.githubusercontent.com/7140246/39717528-8a17a40e-5201-11e8-919f-d19dab44f63e.png">

Spacing (collapsed)
<img width="980" alt="collapsed_spacing" src="https://user-images.githubusercontent.com/7140246/39717538-94f65cb2-5201-11e8-9b4c-d378ad61e43f.png">

Step navigation scroll behavior (expanded)
<img width="889" alt="leftnav_scroll_behavior_expanded" src="https://user-images.githubusercontent.com/7140246/39717556-ac5ddd8a-5201-11e8-8c01-07dac93374fe.png">

Step navigation scroll behavior (collapsed)
<img width="887" alt="leftnav_scroll_behavior_collapsed" src="https://user-images.githubusercontent.com/7140246/39717566-b598fb50-5201-11e8-8862-4e98f845f2e5.png">

End-state reference: expanded
<img width="820" alt="expanded_leftnav_comp" src="https://user-images.githubusercontent.com/7140246/39717600-cd4f4b96-5201-11e8-828f-f0d2b605c423.png">

End-state reference: collapsed
<img width="827" alt="collapsed_leftnav_comp" src="https://user-images.githubusercontent.com/7140246/39717622-d83b69cc-5201-11e8-94d8-50cdd8388eb4.png">

**Comment by mathisscott** [comment]
@gnomeontherun @colinreedmiller @hippee-lee : Are these Wizard enhancements something we are considering in the near future? If so, is this something we want to drive from `@clr/core` and push out from that vector into `@clr/angular`? Or is this something we would consider implementing in the angular components first? I also want to acknowledge that UX/Design is a blocker here so our answers to those questions will be impacted by that timeline.

**Comment by colinreedmiller** [comment]
I'll attend the next planning session and we can look at this in the context of the rest of the backlog. Though these enhancements appear to be reasonable requests, I need a sense of triage and priority. I'll look through these in detail in the meantime.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
