### ISSUE TITLE
Closing sidenav on navigation

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#2250]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[V] question
```
Currently when navigating from sidenav on small screens - it remain open until you close it manually.
Is there anyway to close sidenav automatically on navigation ?
![image](https://user-images.githubusercontent.com/1386622/39810203-d9789d0a-538c-11e8-8417-4444171a8eb5.png)

https://vmware.github.io/clarity/documentation/v0.10/navigation

### Environment details
* **Angular version:** 5.2.3
* **Clarity version:**
0.10.19

**Comment by adityarb88** [comment]
@ph55: Could you provide a replication of this behavior? It depends on the way you have implemented it. If you take a look at our website, we close the menu when a nav link is clicked. The way we recommend you implement Responsive Navigation is documented here: https://vmware.github.io/clarity/documentation/v0.11/app-layout.

You could also take a look at the nav in our dev app for more info: https://github.com/vmware/clarity/blob/master/src/app/app.component.html

**Comment by ph55** [comment]
Ok, so `nav-link` class was missing in `a` element. Thanks.
