### ISSUE TITLE
Tree View nodes in Modal do not expand for first time

### ISSUE THREAD

**Issue by compmaster** [vmware/clarity#2251]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Tree View nodes inside Modal should be expanded after user clicks the expand arrow.

### Actual behavior
If modal is opened more that once: Tree View nodes do not expand for the first time.

### Reproduction of behavior
1. Open a Modal that contains hierarchical TreeView nodes
2. Close the Modal.
3. Reopen the Modal.
4. Try to expand nodes.

#### Demo
https://clarity-light-theme-v11-hruykr.stackblitz.io

### Environment details

* **Angular version:** 5.2.9

* **Clarity version:** 0.11.10

* **OS and version:** Microsoft Windows 7 SP1 (compilation 7601)

* **Browser:** Opera 52.0.2871.64, Firefox 59.0.2

### Further examination

This issue is probably related to Angular animations and the wildcard that incorrectly measures height of node's content and sets it to 0. This issue occurs if Modal is opened more that once and not destroyed.

**Comment by adityarb88** [comment]
@compmaster: Thanks for reporting this. We will take a look and get back to you.

Simplified demo: https://stackblitz.com/edit/clarity-light-theme-v11-apbfw3?file=app/app.component.html

**Comment by adityarb88** [comment]
@compmaster: There is a work around for this until we investigate the issue. Please refer to this StackBlitz: https://stackblitz.com/edit/clarity-light-theme-v11-yq4hqz?file=app/app.component.html

You can add an `*ngIf` on the `.modal-body`:

`<div class="modal-body" *ngIf="opened">`

**Comment by gnomeontherun** [comment]
This is related to an unsupported version of Clarity, and Tree View was rewritten in v2 to address bugs like this one. Closing as out dated and shouldn't be a problem in v2+.
