### ISSUE TITLE
[BUG] DataGrid clrDgSelected mutates array of selected items

### ISSUE THREAD

**Issue by colinskow** [vmware/clarity#2253]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The clrDgSelected binding on DataGrid should not mutate the array of selected items, but create a new array. It should not change anything if the binding is one way. This is required for OnPush change detection and Redux / ngrx workflows.

### Actual behavior

A clrDgSelected binding mutates the array by pushing new items. This breaks Redux, ngrx, and OnPush change detection. It should instead clone the array. 

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v11-miey3g

Select items and open console to see error.

### Environment details

* **Angular version:** 5.2.1

* **Clarity version:** 0.11.1

* **Browser:** [ all ]

**Comment by gnomeontherun** [comment]
Thanks, we'll need to investigate this a bit further

**Comment by bdryanovski** [comment]
This is fixed into `v2.4.10` and `v0.11` is out of support so I'm closing this.
