### ISSUE TITLE
Reconsider max-width on .branding container in clr-header

### ISSUE THREAD

**Issue by elesueur** [vmware/clarity#2255]
```
[ ] bug
[ ] feature request
[*] enhancement
```

### Expected behavior
At smaller screen sizes / breakpoints, the app title should not be truncated if there is available space to the right

![screen shot 2018-05-09 at 6 30 24 pm](https://user-images.githubusercontent.com/8139865/39843006-0f366ef2-53b7-11e8-8164-a024fda51d8b.png)

### Actual behavior
The application title text is truncated even if there is space to the right.

![screen shot 2018-05-09 at 6 29 55 pm](https://user-images.githubusercontent.com/8139865/39842992-00c3696a-53b7-11e8-9bf7-63bb3737823c.png)

### Reproduction of behavior
Create an app with a reasonable length title and shrink the window down to smaller widths.

### Environment details

* **Angular version:** 5.2.0

* **Clarity version:** 0.11.5

* **OS and version:** Chrome 66

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by elesueur** [comment]
My proposal would be to consider simply removing the max-width on the .branding container.

**Comment by mathisscott** [comment]
@reddolan + @adityarb88 
Thoughts?

**Comment by reddolan** [comment]
Sounds good to me

**Comment by youdz** [comment]
Clarity does not have a `max-width` on the branding container or the title in the header. Could you check where the max-width comes in your case? Thanks!

**Comment by mathisscott** [comment]
Your thoughts, @adityarb88

**Comment by adityarb88** [comment]
@elesueur @reddolan: When we implemented the header, we specifically added the max-width on the branding area. This was to safeguard against the text overlapping with `.settings` container on the right if the user has the section. If you do not have a `.settings` container (like in the above example), I would instead recommend that this override be added on the application side. 
Removing the `max-width` increases the chance of text overlapping in the header on smaller screens and might even be a breaking change.

Our recommendation was also that the Branding be as short as possible especially on smaller screens because of the lack of space.

**Comment by reddolan** [comment]
The above example looks like it should have adequate space for the text `AWS` and the right icon area. That right icon area should be only taking up about 60px width, leaving some additional space for the text in the middle.

**Comment by adityarb88** [comment]
@reddolan but thats just the above example. In general the header can also contain the `.settings` area. We chose to add the max-width to handle that use case. Unfortunately, we can't add that style conditionally as the branding is placed before the `.settings` area.

**Comment by mathisscott** [comment]
Investigating using flexbox to dynamically adjust the width. We'll see if that winds up being the solution we need.

**Comment by unff** [comment]
Just to chime in on this, I'm seeing this behavior as soon as I get under 768px.  See the attached screenshot.  I can't fathom a reason for the truncation in this case, and I can't get around it in CSS as the style causing it is baked into the page with Angular.  This behavior annoys me in ways I didn't think possible.
![sshot0062](https://user-images.githubusercontent.com/7915543/43340929-f26875a8-91ab-11e8-88b2-8b6d88114b11.png)

Code:
`<header class="header header-6">
      <div class="branding">
          <a href="#" class="nav-link">
              <img src="../assets/images/logo.svg" class="headerLogo" />
              <span class="title">Foxen Labs</span>
          </a>
      </div>
      <div class="header-actions">
          <clr-dropdown>
              <button class="nav-text" clrDropdownTrigger>
                  info@foxenlabs.com
                  <clr-icon shape="caret down"></clr-icon>
              </button>
              <clr-dropdown-menu *clrIfOpen clrPosition="bottom-right">
                  <a href="#" clrDropdownItem>Preferences</a>
                  
              </clr-dropdown-menu>
          </clr-dropdown>
      </div>
  </header>`

**Comment by colinreedmiller** [comment]
This looks like an application design issue rather than a Clarity one. I agree with the reasoning for the branding container having a width maximum property and overriding it on the application side as needed when a settings container is not used.
