### ISSUE TITLE
Date Picker don't mark form as dirty

### ISSUE THREAD

**Issue by williangd** [vmware/clarity#2263]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When you select a date in the date picker, the form is marked as dirty.

### Actual behavior
When you select a date in the date picker, the form is not marked as dirty.

### Reproduction of behavior
Click the date picker icon to open the component and select a date.
The form is marked as dirty only when typing the date with the keyboard
https://stackblitz.com/edit/clarity-light-theme-v11-6quune

### Environment details

* **Angular version:** 5.2.1

* **Clarity version:** 0.11.16

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@williangd: Thanks for reporting this issue. We will take a look and get back to you.

**Comment by gnomeontherun** [comment]
Yup, that should do it. Same with `markAsTouched()`
