### ISSUE TITLE
Table rows are incorrect height

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2264]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Table rows are 34 pixels 

### Actual behavior
Expect them to be 36 px for vertical rhythm.

### Reproduction of behavior

https://vmware.github.io/clarity/documentation/v0.11/tables

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by coryrylan** [comment]
Closed by https://github.com/vmware/clarity/pull/2975
