### ISSUE TITLE
Add custom icon by URL

### ISSUE THREAD

**Issue by essivision** [vmware/clarity#2267]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Do you have any solution to add custom icon to clarity by URL. I want to add some custom icon but I don't want to copy svg code to js file. What should I do?

### Environment details

* **Clarity version:** 0.11.17

* **OS and version:** Windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
When you add custom icons to the Clarity Icons API running in your app, it can be any html snippet that you want. From a font-awesome span or i tag to an image tag pointing to a remote source.
