### ISSUE TITLE
Resize cursor is visible over dropdown menu when it appears over column separator

### ISSUE THREAD

**Issue by ivvatov** [vmware/clarity#2269]
[X] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Datagrid column separator is *not movable* when under a drop-down menu.

### Actual behavior
When a dropdown menu is opened above a column separator, one can still resize the column beneath the dropdown menu.

![clr-dg-resize-cursor](https://user-images.githubusercontent.com/27762496/40001256-8433f9c6-5796-11e8-9815-44b6b1fba08e.PNG)

A resize cursor will appear when one moves the cursor over the spot marked on the screenshot.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v11-mcdzbj?file=app%2Fapp.component.html

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [all]

**Comment by adityarb88** [comment]
@ivvatov: Thanks for reporting this. I will add this to the backlog.

**Comment by adityarb88** [comment]
This is happening because the z-index of the column separator handle is 1000 too.

![image](https://user-images.githubusercontent.com/1426805/40001977-5bdb33f6-575d-11e8-819f-8d052a5a1542.png)
