### ISSUE TITLE
[icons] Break up existing icons

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#228]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior

Our existing icons only live in one object. We need to break them up into their respective sets...

Set #1: Core or, maybe, Essentials

Set #2: Social

Set #3: As yet unnamed but more VMware focused icons

When the sets are finalized, we will attach an image here.

Requirements:

1) Each set should be in their own `.ts` file and should be importable (like SVG_ICON_TEMPLATES is now)

**Comment by adityarb88** [comment]
Closed because @Shijir already merged in his changes to master.
