### ISSUE TITLE
Doc Issue - "Try to Open at Step 3" and "Try to Open at Step 5" should open wizard and jump to step 3 and 5 after clicked.

### ISSUE THREAD

**Issue by nghiado** [vmware/clarity#2292]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Document Website https://vmware.github.io/clarity/documentation/v0.11/wizards
Programmatically Navigating the Wizard
"Try to Open at Step 3" and "Try to Open at Step 5" should open wizard and jump to step 3 and 5 after clicked.
 
### Actual behavior
"Try to Open at Step 3" and "Try to Open at Step 5" just open wizard at step1 for both actions.

### Environment details

* **Angular version:** 5.x.x
![screen shot 2018-05-17 at 9 37 27 am](https://user-images.githubusercontent.com/1259031/40184693-837660e2-59b6-11e8-9dc3-6c24bbdb0142.png)

* **Clarity version:** v0.11

* **OS and version:** MacOS

* **Browser:** Chrome

**Comment by mathisscott** [comment]
@nghiado 
I hear what you are saying but it is not a bug.

If you have a use case where you have a 3 step wizard and only need to edit data in the last step then you simply have steps one and two marked "completed". This is also discussed in the documentation.

Thanks!
