### ISSUE TITLE
Select row in DataGrid from code

### ISSUE THREAD

**Issue by borcherspm** [vmware/clarity#2293]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I'm trying to have code select a row in a DataGrid based on an action outside of the DataGrid.

### Actual behavior
The DataGrid in the pagination bar shows that a count of rows was selected, but it nevers reflects in the DataGrid selection column.

### Reproduction of behavior
* [Example Plunker](https://stackblitz.com/edit/clarity-light-theme-v11-vatsfi?file=app%2Fapp.component.html)
  * In plunker click button "Select User".  Code tries to select user.  No row is selected.

### Environment details

* **Angular version:** 5.2.10

* **Clarity version:** 0.11.15

* **OS and version:** Windows

* **Browser:** [all | Chrome 66 | Firefox 59 | Edge 41 | IE 11 ]

**Comment by youdz** [comment]
A quick look tells me you are not using `trackBy`, so Angular checks reference equality when comparing users. See https://angular.io/api/common/NgForOf for how to use the `trackBy` option for `*ngFor`.

**Comment by borcherspm** [comment]
Thanks for the quick reply.  It's my bad, I forgot to add the trackBy.  

Even with that it still doesn't work.

**Comment by tarangkhandelwal** [comment]
Try using the reference of same object that data grid is working on.
Updated plunker: [Link](https://stackblitz.com/edit/clarity-light-theme-v11-uk35vf)

**Comment by borcherspm** [comment]
Thank you!  That helped a lot.  Once I started filtering to the same objects that are in the grid, the selection works.
