### ISSUE TITLE
datagrid with signpost sorts instead of displays signpost (and not working in firefox)

### ISSUE THREAD

**Issue by spetri** [vmware/clarity#2294]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When there is a signpost in the datagrid-header + sort, the user should be able to click the signpost without sorting.

### Actual behavior
When the user clicks the signpost, it sorts the datagrid. Also, in Firefox, the user cannot even click the signpost (because in the DOM, it's a signpost `<button>` as a child in a sort`<button>`.

### Reproduction of behavior
https://stackblitz.com/edit/datagrid-sort-with-signpost?file=src/index.html

In Chrome, signpost displays but clicking on it also sorts the list. In Firefox, signpost displays, but clicking it does nothing.

**Comment by mathisscott** [comment]
Need to allow for non-content title items in the column header that will not invoke a click event on the column name/title.

**Comment by mathisscott** [comment]
Per @youdz, this would be a breaking change to the datagrid...

**Comment by gnomeontherun** [comment]
We won't consider this behavior because it nests click targets and breaks accessibility expectations. We appreciate the request and suggest consideration of other patterns to support adding more contextual information to your application.

**Comment by Jinnie** [comment]
I find this similar to something I recently worked on - the popover in a model pattern.
In general - we in Clarity can't know who hosts our components (signpost in this case), so we can't afford to prevent event distribution through the DOM. But the user using our components can and should.
You can (accept this as pseudo-code please) add a `(click)=$event.stopPropagation()` to the clr-signpost tag and it should not lead to sorting anymore.
