### ISSUE TITLE
There would be double X in filter box after user enters some words in IE 11

### ISSUE THREAD

**Issue by lieaqnes** [vmware/clarity#2299]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
There are only one  X in filter input after user enters some words in IE 11

### Actual behavior
There would be double X in filter box after user enters some words in IE 11
<img width="712" alt="screen shot 2018-05-21 at 10 41 36 am" src="https://user-images.githubusercontent.com/8463373/40288032-f5f30e7e-5ce3-11e8-9268-a58e93a5a9ac.png">

### Reproduction of behavior
1. open IE  11
2. enter the link https://vmware.github.io/clarity/documentation/v0.11/datagrid/string-filtering.
3. click Pokemon column and enter some words.
### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:** 

* **Browser:** [IE 11]

**Comment by pumano** [comment]
I got the same thoughts about it. 
It's not a bug, but an enhancement. 

It's will be cool to have possibility to remove filter data with one click to 'x' icon.

**Comment by hippee-lee** [comment]
Hi @lieaqnes - the second `X` is a clear button for the input put there by IE11 and MS Edge. Its a non standard [pseudo-element](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-clear) that is only shown on focused, non empty inputs. 

You can remove the `pseudo-element` by targeting the input(s) in the apps css.
