### ISSUE TITLE
Date Picker not outputting dates in Reactive & Template Driven Forms

### ISSUE THREAD

**Issue by rameshyala** [vmware/clarity#2300]
[X] Question

Hi , i am set locale to my app in app.module file like ' providers: [{ provide: LOCALE_ID, useValue: 'en-IN' }]', but this ' en-IN' locale need to show format as DDMMYYYY but actually it showing MMDDYYYY format. check once [Stackblitz](https://stackblitz.com/edit/clarity-light-theme-v11-nknd98?file=app%2Fapp.module.ts).

One more doubt is now date picker have change detection option , if i change actual date is emit any event now, i am check clarity git hub code i am found for template-driven-forms have '(clrDateChange)=" "'  option, but in that for reactive forms does not see anything , how i will do that ?. 

Thank you.

**Comment by brinton-chand** [comment]
https://angular.io/guide/i18n#i18n-pipes

> By default, Angular only contains locale data for en-US. If you set the value of LOCALE_ID to another locale, you must import locale data for that new locale.

Check the link for instructions in how to import. Hope this helps.

**Comment by rameshyala** [comment]
Thank you @brinton-chand the locale issue is works fine, now this date picker is having a change detection option for reactive forms ?.

**Comment by adityarb88** [comment]
@rameshyala: What exactly do you mean by change detection problems? Can you replicate this on a StackBlitz? In the StackBlitz that you posted above, I do not see Reactive Forms.

Our docs has an example of using Date Picker in reactive forms. May be that will help?
https://vmware.github.io/clarity/documentation/v0.11/datepicker
![image](https://user-images.githubusercontent.com/1426805/40426476-2c1fc54c-5e69-11e8-9861-69a68374ce01.png)

**Comment by rameshyala** [comment]
Hi, @adityarb88 i am just asking, if change the date (assume the date picker have default today date), when i am modify that date in that time i will get any event now? 
Thank you

**Comment by adityarb88** [comment]
@rameshyala: What I was saying is that your StackBlitz doesnt have reactive forms. Can you replicate your issue exactly. If you look at the link above, we have provided a demo for Reactive Forms. And when the user modifies the date, an event is emitted. If you can replicate the issue you are facing in a StackBlitz we can take a look and let you know what the issue is.

**Comment by adityarb88** [comment]
@rameshyala: I created a StackBlitz which demos this: https://stackblitz.com/edit/clarity-light-theme-v11-u1lzvu?file=app/app.component.html

Hope this helps.

**Comment by rameshyala** [comment]
Thank you @adityarb88 looks good, my doubt solved with your stackbliz.

**Comment by adityarb88** [comment]
@rameshyala: Let me take a look and get back to you. Thanks!
