### ISSUE TITLE
Popups for clarity  

### ISSUE THREAD

**Issue by rameshyala** [vmware/clarity#2306]
[ X] feature request

Hi Clarity team,
Do you have any future plans for develop popup in this clarity framework? if not can you suggest me how i will do app change menu some like below image with your components or using third party framework.

Thank you.

![icld](https://user-images.githubusercontent.com/18004992/40354199-eb1b99ce-5dd0-11e8-8e22-2314c877524e.png)

**Comment by dorthrithil** [comment]
Did you try signposts? 

https://vmware.github.io/clarity/documentation/v0.11/signposts

**Comment by gnomeontherun** [comment]
Signposts are the correct implementation for a popover, which provides you with a blank space to implement your own internal content. If you have questions about how to use it, please try to use StackOverflow for follow up questions. Closing based on this answer.

**Comment by rameshyala** [comment]
Hi, @gnomeontherun for that above screenshot implemention signpost is fine but the signpost have cross icon on the top right, right now there is no option for hide that icon, Can you provide that option to remove/ hide to that cross icon.

Thanks

**Comment by gnomeontherun** [comment]
There has to be a way to close the popover, so you shouldn't remove them.

**Comment by gnomeontherun** [comment]
@rameshyala This is really a question for StackOverflow.com (use the `vmware-clarity` tag) as we use GitHub issues for bugs and features. Also commenting on a old closed issue doesn't always get attention.

This seems like a dropdown behavior, not a signpost. I'd investigate using a dropdown instead, or consider a custom implementation. Trying to force a component to do something so different from its intended purpose is likely to break over time as we add features or refactor the component.
