### ISSUE TITLE
<input pattern="<REGEX>")...> ignores pattern

### ISSUE THREAD

**Issue by DonaldAlan** [vmware/clarity#2311]
**I'm submitting a ...**  (check one with "x")

- [x] bug report - search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request - use StackOverflow (add the `ngx-charts` tag) or the gitter chat for support questions

**Current behavior**

If I add a pattern attribute to an HTML5 input component, I expect a red border to appear if the value I enter doesn't match the regex of the pattern. But no red border appears.

**Please tell us about your environment:**

Windows 10, Angular 6, CLI 6.0.1, Firefox Quantum (60.0.1), 

* **ngx-charts version:** x.x.x

```
    "@clr/angular": "^0.11.16",
    "@clr/icons": "^0.11.16",
    "@clr/ui": "^0.11.16",
```

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by gnomeontherun** [comment]
Hi @DonaldAlan I think you used a different GitHub issue template here, you aren't describing what version of Clarity you have or a sample of what you're doing. Could you provide details about what you are doing that is failing?

**Comment by DonaldAlan** [comment]
Sorry, fixed.  clr version 0.11.16.  Here's the code:
```
 <form>
    <section class="form-block">
      <label>Input Fields</label>
      <div class="form-group">
        <label for="formFields_1">Textbox [type="text"]</label>
        <input type="text" id="formFields_1" placeholder="Email 1" pattern="\w+@\w+\.\w+" size="35" [value]="'JohnDoe@abc.com'">
        <input type="text" id="formFields_2" placeholder="Email 2" size="45">
        <input type="text" id="formFields_3" placeholder="Email" size="25">
        <input type="text" id="formFields_4" placeholder="Email 2">
        <input type="text" id="formFields_5" placeholder="Email">
        <input type="text" id="formFields_6" placeholder="Email 2">
      </div>
    </section>
  </form>
```
The pattern input field doesn't work:  put an invalid email syntax and it doesn't show red.

**Comment by hippee-lee** [comment]
It looks like inputs are missing style for the `:invalid` pseudo class.
Thanks for reporting this.

**Comment by gnomeontherun** [comment]
Our current form controls don't automatically validate, unfortunately. The validation is handled largely on your end by adding the `invalid` class, see https://vmware.github.io/clarity/documentation/v0.11/input-fields.

This will change with the forms refactoring currently underway, by providing Angular components that wire up to the control states and automatically handling the validation classes for you.

**Comment by gnomeontherun** [comment]
I have tested this with new forms and having a pattern validator works out of the box. Closing this as resolved.
