### ISSUE TITLE
Cannot initialize row selection in Datagrid

### ISSUE THREAD

**Issue by gssjr** [vmware/clarity#2315]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Can set the selected rows by adding to the list bound to clrDgSelected

### Actual behavior

The array seems to be reset

### Reproduction of behavior
[https://stackblitz.com/edit/clarity-light-theme-v11-hxgqpz](https://stackblitz.com/edit/clarity-light-theme-v11-hxgqpz)

In ngOnInit, the inputdata is pushed to the selected rows array but is immediately cleared out.

### Environment details

* **Angular version:** 5.2.10

* **Clarity version:** 0.11.9

* **OS and version:** Windows 10

* **Browser:** Chrome 66.0.3359.181

**Comment by zerocewl** [comment]
Thank you @jeeyun 
Maybe add your example to the documentation?

**Comment by gssjr** [comment]
It seems to work as expected if using `*ngFor` instead of `*clrDgItems`
