### ISSUE TITLE
The default style of the "power" icon is not correct

### ISSUE THREAD

**Issue by austinfu1** [vmware/clarity#2320]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

It  should  show the default style on page
https://vmware.github.io/clarity/icons/icon-sets#core-shapes

### Actual behavior

It displays the same style with the power icon with class="is-solid" which is not correct.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.x.x
5.0.0
* **Clarity version:**
0.11.15
* **OS and version:** 
windows 10
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 66.0.3359.181

**Comment by adityarb88** [comment]
@austinfu1: Could you replicate the issue you are facing on a StackBlitz?

We couldn't replicate it: https://stackblitz.com/edit/clarity-light-theme-v11-t7gsvz?file=app/app.component.html and like you mentioned in the issue description, it works on the website.

Are you sure you are loading the Media Shapes category? More details about loading different sets is in the Get Started section of the Icons documentation: https://vmware.github.io/clarity/icons/clarity-icons

**Comment by austinfu1** [comment]
@adityarb88 : My bad, i  put 2 icons on my page, but for the 1st icon, </clr-icon> is missing，i fixed this, and the power icon shows as expected. So this issue can be closed, thank you.
