### ISSUE TITLE
Time Range Picker

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#2322]
```
[ ] bug
[x] feature request
[ ] enhancement
```

Create a Time Range Component based on the details specified in #474.

**Comment by adityarb88** [comment]
@reddolan: Could you please take a look at this request?

**Comment by daverickdunn** [comment]
Just wanna add that without this, I imagine the date picker is redundant in the majority of use cases, certainly in terms of having to add more packages. 

In other words, if I'm gonna add a standalone package for picking a date + time, I'm not going to use the date picker from Clarity and the time picker from package X - I'm just going to use package X.

@reddolan Is the design in https://github.com/vmware/clarity/issues/474 not sufficient, or are you referring to some other design aspect?

P.S. I really like the Date Picker though. Cheers! ;D

**Comment by reddolan** [comment]
@daverickdunn there is a Date Range feature on #474. The request here is for a design/experience around a time range, which we didn't cover in #474. Teams could just set up to side by side time-form controls to adapt this idea. However, there may be a more valuable experience to having one unified control to manage this.

**Comment by reddolan** [comment]
@daverickdunn agreed. That is why we have it in the design spec on #474. It just happens to have higher priority items in front of it

**Comment by purushottamjha** [comment]
Without time picker, date range picker is pretty much useless for me.  It will be very helpful if we have this feature.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
