### ISSUE TITLE
Barcode icons request

### ISSUE THREAD

**Issue by Ergnos** [vmware/clarity#2326]
**Select one ...**  (check one with "x")
```
[ ] bug
[  ] feature request
[ x ] enhancement
```

We are developing an application in where barcode scans have to be performed, therefore barcode and qr code icons would be a great addition.

**Comment by adityarb88** [comment]
@lil-kim: Could you please take a look at this request?

**Comment by lil-kim** [comment]
Completed as a part of Epic #2222
