### ISSUE TITLE
bootstrap dep in 0.12-rc1

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#2330]
```
[x] bug
[ ] feature request
[ ] enhancement
```
I use 
```
// Pre variable and theme dependencies
@import "../../node_modules/@clr/ui/src/utils/dependencies.clarity";
```
for create theme

and i have error in angular cli 6:
```
File to import not found or unreadable: ../../../node_modules/bootstrap/scss/media.
      in D:\OhMyBoss\client\node_modules\@clr\ui\src\utils\_components.clarity.scss (line 10, column 1)
```
```
File to import not found or unreadable: ../../../node_modules/bootstrap/scss/media.
      in D:\OhMyBoss\client\node_modules\@clr\ui\src\utils\_components.clarity.scss (line 10, column 1)
```

for fix it:
from
```
// Bootstrap 4 Dependencies - Begin Part 1
@import "../../../node_modules/bootstrap/scss/variables";
@import "../../../node_modules/bootstrap/scss/mixins";
@import "../../../node_modules/bootstrap/scss/normalize";
//Bootstrap 4 Dependencies - End Part 1
```
to
```
// Bootstrap 4 Dependencies - Begin Part 1
@import "../../../../bootstrap/scss/variables";
@import "../../../../bootstrap/scss/mixins";
@import "../../../../bootstrap/scss/normalize";
//Bootstrap 4 Dependencies - End Part 1
```

from
```
// Bootstrap 4 Dependencies - Begin Part 2
// NOTE: These are here b/c they need to be overwritable for the $grid-breakpoints map in a theme.
@import "../../../node_modules/bootstrap/scss/media";
@import "../../../node_modules/bootstrap/scss/utilities";
@import '../../../node_modules/bootstrap/scss/images';
@import "../../../node_modules/bootstrap/scss/list-group";
@import "../../../node_modules/bootstrap/scss/close";
@import "../../../node_modules/bootstrap/scss/grid";
@import "../../../node_modules/bootstrap/scss/responsive-embed";
```
to
```
// Bootstrap 4 Dependencies - Begin Part 2
// NOTE: These are here b/c they need to be overwritable for the $grid-breakpoints map in a theme.
@import "../../../../bootstrap/scss/media";
@import "../../../../bootstrap/scss/utilities";
@import '../../../../bootstrap/scss/images';
@import "../../../../bootstrap/scss/list-group";
@import "../../../../bootstrap/scss/close";
@import "../../../../bootstrap/scss/grid";
@import "../../../../bootstrap/scss/responsive-embed";
```

summary replace 
`/node_modules/` to `/../`
### Environment details

* **Angular version:** 6

* **Clarity version:** 0.12.0-rc.1

**Comment by hippee-lee** [comment]
Hi @KANekT - do you have bootstrap installed in the projects dependencies? I suspect that its not installed. 
If I am wrong and you do have bootstrap installed, in order to see whats going one I need something that recreates the issue. Can you push a project that recreates it to github and link to it here so I can take a look at it?

**Comment by KANekT** [comment]
Yes i install bootstrap

`  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.2.0",
    "@angular/cli": "^6.0.7",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@clr/angular": "0.12.0-rc.1",
    "@clr/icons": "0.12.0-rc.1",
    "@clr/ui": "0.12.0-rc.1",
    "@ngrx/effects": "^6.0.0",
    "@ngrx/router-store": "^6.0.0",
    "@ngrx/store": "^6.0.0",
    "@ngrx/store-devtools": "^6.0.0",
    "@webcomponents/custom-elements": "^1.1.1",
    "bootstrap": "4.0.0-alpha.5",
    "core-js": "^2.5.7",
    "d3": "^4.12.2",
    "lodash": "^4.17.10",
    "ng2-file-upload": "^1.3.0",
    "rxjs": "^6.2.0",
    "zone.js": "^0.8.26"
  },
`

**Comment by gnomeontherun** [comment]
I changed the import paths when we updated scripts for building our packages recently, but perhaps there is a workaround to avoid this relative path issue. It would be different for each project, and I wish Sass had better support here.

@hippee-lee Let's try the `~` again and double check. I forget what it was doing, but it wasn't building the styles the same in both the CLI and node-sass scripts.

**Comment by hippee-lee** [comment]
👍🏽 I'll take a look at this as soon as I can.

**Comment by KANekT** [comment]
@hippee-lee Awaiting More Info - You wait for some information from me or the @gnomeontherun  explained what needs to be done? :-)

**Comment by gnomeontherun** [comment]
We're still reviewing what we need to handle here, but its probably on our end to update documentation or code.

**Comment by gnomeontherun** [comment]
I have a fix out to go into the next release, and plan to also update the custom theme docs with a slight change for how to do it.
