### ISSUE TITLE
DatePicker position customizable

### ISSUE THREAD

**Issue by Kevin2iBi** [vmware/clarity#2331]
**Select one ...** (check one with "x")

```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior

I want it to be possible to put the position where the component is intended to appear.
Ex: Bottom-Left, Top-Left

### Actual behavior

Currently the component always appears at the bottom

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:**

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
I think that's a reasonable request to solve popover positioning issues until we have (one day™) smart positioning.

**Comment by whizkidwwe1217** [comment]
Will this get into the next release? I have a side panel that contains a form with a date picker in it and it's getting clipped. There's no way to position the picker.
![image](https://user-images.githubusercontent.com/1977391/45930062-1184a600-bf8d-11e8-82cb-1cb9d84db985.png)

**Comment by youdz** [comment]
Given our other priorities, we are not working on it at the moment so it will not be part of the next release. Most of use are tied up with large features or more urgent fixes so I do not see us implementing this in the short term.

The work required is actually fairly small, and it's something we could easily accept external contributions for. If you are interested in contributing, you can check out our `[clrPosition]` input for Dropdowns (https://github.com/vmware/clarity/blob/master/src/clr-angular/popover/dropdown/dropdown-menu.ts#L47)  and offer something similar for Datepicker.

**Comment by whizkidwwe1217** [comment]
@youdz No worries. I'll check that out thanks. 🙂

**Comment by whizkidwwe1217** [comment]
@gnomeontherun Will this be available in the final release of v3? As you can see in the GIF below, the calendar does not even show up because of clipping issues.
![datepicker3](https://user-images.githubusercontent.com/1977391/71428120-c1e5da80-26f9-11ea-902f-4be124cc616e.gif)

**Comment by hippee-lee** [comment]
@whizkidwwe1217 - can you post the link to your stackblitz reproduction so I can take a look into it again?
There is some ongoing work with popovers and it may be related to your request / issue but I need to see your issue to be sure.

**Comment by whizkidwwe1217** [comment]
@hippee-lee Here's the link to the StackBlitz: https://stackblitz.com/edit/angular-9rc7-27m8mu
I tried putting a `clrPosition='top-right'` directive to the `clr-date-container` but it's not working. Please make sure to test it with your browser with a limited window height. Thanks and happy holidays!

**Comment by whizkidwwe1217** [comment]
Sometimes I get enough space below and the picker will show up. But when I try to scroll down, the picker gets dismissed immediately.
![image](https://user-images.githubusercontent.com/1977391/71637717-1b638180-2c85-11ea-9981-a91ef1e14b8d.png)

**Comment by hippee-lee** [comment]
@whizkidwwe1217 - for anything under 768 width the datapicker assumes a mobile device and should use the native datepicker for the device. Or am I misunderstanding the reporduction steps and it should be a very wide but short viewport?

**Comment by whizkidwwe1217** [comment]
@gnomeontherun I was referring to the height. As you can see in the GIFs, all the form controls fit perfectly in the viewport. However, the height of the panel is not enough to accommodate the height of the date picker so it triggers the vertical scrollbar. But when you try to scroll down, I can't select a date because the picker is automatically dismissed. 
![datepicker1](https://user-images.githubusercontent.com/1977391/71705103-cf494600-2e18-11ea-9c08-6733259d38b5.gif)

Another issue is when I decrease the height of the panel, just enough to make the date picker positioned visibly at the bottom, the picker does not show up.
![datepicker2](https://user-images.githubusercontent.com/1977391/71705357-4a5f2c00-2e1a-11ea-8d70-e71edda5ba5a.gif)

I'm experiencing these issues similar to the comment in https://github.com/vmware/clarity/pull/3731#issuecomment-535459796, that's why I was asking if there would be a fix or a way to position the picker in a different direction in the final version of v3.

**Comment by hippee-lee** [comment]
There is v3 work being done to bring the smart popover util that can detect viewport clipping and reposition the popover content (in this case the day/month/year views). 

I looked at the stackblitz and it looks like the layout of the drawer is hiding preventing the datapicker views for displaying. Just playing around in dev tools, working the varies element styles for: overflow, z-indexes and some other things ,  I was able to get it to show but there are still scrolling issues. 

This does work out of the box in the standard app layout. I will take a second look at the app and see if I can come up with a recommendation for it. Until then I suggest that you re-visit the layout inside the drawer component to identify which element is causing the issue in that layout.

**Comment by whizkidwwe1217** [comment]
Thanks @hippee-lee for your feedback. I think for complicated layouts, especially when there are nested DIVs involved, it would be much better if Clarity's smart popover supports appending it to the HTML body. It's similar to Bootstrap's popover.
![image](https://user-images.githubusercontent.com/1977391/71767969-ea1cd700-2f4c-11ea-8a0c-aa2bdc03c717.png)
