### ISSUE TITLE
Tree not update state

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#2339]
**Select one ...** (check one with "x")

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
i init app
![screenshot_01](https://user-images.githubusercontent.com/580273/41027402-9df8d14c-697f-11e8-82e6-519f11f8ba52.png)
folded tree
![screenshot_02](https://user-images.githubusercontent.com/580273/41027403-9e2f7d00-697f-11e8-85cc-3d51892fb5ab.png)
check main element
![screenshot_03](https://user-images.githubusercontent.com/580273/41027404-9e5a69f2-697f-11e8-839a-687225d31a1c.png)
I expect all child element is checked
![screenshot_05](https://user-images.githubusercontent.com/580273/41027406-9eae88ac-697f-11e8-9b4b-e7fc4cf63e77.png)

### Actual behavior
but state not changed
![screenshot_04](https://user-images.githubusercontent.com/580273/41027405-9e86af44-697f-11e8-95c0-8f52fe6d8c88.png)
### Reproduction of behavior
* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://stackblitz.com/edit/clarity-light-theme-v11-gr1kwc

### Environment details

* **Angular version:** 5 or 6

* **Clarity version:** 0.11 or 0.12

**Comment by KANekT** [comment]
Oh, this error is duplicate of #1400 ?

**Comment by adityarb88** [comment]
Looks like it is. Closing this as a duplicate.
