### ISSUE TITLE
Datagrid: preserve selection when filtering

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#2342]
**Select one ...** (check one with "x")

```
`[ ]` bug
`[ ]` feature request
`[x]` enhancement
```

### Expected behavior

I need to be able to incrementally build a selection of items in a datagrid through the following process:
1. filter the items of a datagrid down to a manageable number,
2. select one of these items, 
3. undo my filter,
4. repeat from step 1 for a new item.

### Actual behavior

Currently adding, removing or changing any filter simply erases the current selection, which makes the desired process impossible.

### Proposed solution

The overall selection we keep in memory should remain constant but private, while the  "public" selection should follow the current filters at all times. **Any actions performed through the action bar will apply only to the public selection** (this is **critical** to prevent destructive actions from happening on unwanted items). To ensure this, we simply have to make sure the private selection remains truly **private**, our consumers will never need it.

Here is a step-by-step use case example showing what the private and public selections become based on user action, and how many selected items the selection counter in the footer of the data grid displays:

1. My dataset is the list of states of the United States.
2. I select Alabama and California.
  Private selection: `["Alabama", "California"]`
  Public selection: `["Alabama", "California"]`
  Selection counter: 2
3. I apply the filter "Jer".
  Private selection: `["Alabama", "California"]`
  Public selection: `[]`
  Selection counter: 0
4. I select New Jersey.
  Private selection: `["Alabama", "California", "New Jersey"]`
  Public selection: `["New Jersey"]`
  Selection counter: 1
5. I delete my "Jer" filter.
  Private selection: `["Alabama", "California", "New Jersey"]`
  Public selection: `["Alabama", "California", "New Jersey"]`
  Selection counter: 3
6. I apply the filter "New".
  Private selection: `["Alabama", "California", "New Jersey"]`
  Public selection: `["New Jersey"]`
  Selection counter: 1
7. I select New York.
  Private selection: `["Alabama", "California", "New Jersey", "New York"]`
  Public selection: `["New Jersey", "New York"]`
  Selection counter: 2
8. I realize my terrible mistake and unselect New Jersey.
  Private selection: `["Alabama", "California", "New York"]`
  Public selection: `["New York"]`
  Selection counter: 1
9. I select New Hampshire.
  Private selection: `["Alabama", "California", "New York", "New Hampshire"]`
  Public selection: `["New York", "New Hampshire"]`
  Selection counter: 2
10. I delete me "New" filter.
  Private selection: `["Alabama", "California", "New York", "New Hampshire"]`
  Public selection: `["Alabama", "California", "New York", "New Hampshire"]`
  Selection counter: 4

This will even work if I apply multiple filters and remove them in a different order while selecting/unselecting items at the same time.

**Comment by mathisscott** [comment]
@mrnic3 
This was released in 0.12.2.

**Comment by eastp** [comment]
Is there a workaround for this in the interim?

**Comment by zhangyuting** [comment]
Hi there,

Is this feature released? Can I know the version? Thanks.

Yuting

**Comment by youdz** [comment]
This is still in the backlog, we haven't started working on it and it's not currently part of our priorities so I cannot give you an ETA on it. 

We will update this thread when we pick it up, sorry that's the best I can give you.

**Comment by aldialimucaj** [comment]
An option to preserve the selection after filter application would make us all happy. Please consider it.

**Comment by boeckMt** [comment]
Is there any update for this?
I think an easy way would be to let the filter decide if it want to preserve the selection e.g.

` // https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/providers/selection.ts#L25

this._filters.change.subscribe((evt) => {
        const preserveSelection = evt.map(item => item.preserveSelection)
        if (!this._selectable || preserveSelection.includes(true)) {
          return;
        }
        this.clearSelection();
})`

**Comment by ashishh62** [comment]
Hi Team,
Is there any update o this?
Is the issue fixed?
If yes, how can we do it?

**Comment by gnomeontherun** [comment]
Closed by #3887
