### ISSUE TITLE
Improve URL path of documentation on our site

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#2346]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
https://vmware.github.io/clarity/documentation/buttons (for current versions)
https://vmware.github.io/clarity/documentation/v0.10/buttons (for past versions)

Current documentation urls without version numbers. This way bookmarks will always point to the current version of documentation. Unless someone bookmarks a versioned documentation page

### Actual behavior
https://vmware.github.io/clarity/documentation/v0.11/buttons

### Reproduction of behavior
![image](https://user-images.githubusercontent.com/1858226/41117996-701b3c14-6a43-11e8-92f6-c01d8f025578.png)

### Environment details

* **Clarity version:** 0.11

**Comment by youdz** [comment]
I will let @gnomeontherun put an estimate on this, I have no idea how long this would take with the current website.

**Comment by gnomeontherun** [comment]
This will be resolved with upcoming docs work, closing as no longer needed.
