### ISSUE TITLE
Button lost its warning color

### ISSUE THREAD

**Issue by imcotton** [vmware/clarity#2349]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

`btn-warning` should has different color than `btn-danger`

```html
<button class="btn btn-warning">Warning</button>
<button class="btn btn-danger">Danger</button>
```

### Actual behavior

`btn-warning` has the exact color as `btn-danger`

### Reproduction of behavior

- [Documentation](https://vmware.github.io/clarity/documentation/v0.11/buttons)
- StackBlitz: [Light Theme v11](https://stackblitz.com/edit/js-7jlpfg?embed=1&file=index.html&hideExplorer=1&hideNavigation=1)

### Environment details

* **Clarity version:** 0.11

* **Browser:** [all]

**Comment by SayakMukhopadhyay** [comment]
IIRC, the warning button doesn't have a different colour like orange due to accessibility issues. The clarity team will be able to (wait for it) _clarify_

**Comment by hippee-lee** [comment]
Warning button color and danger button should be the same.
