### ISSUE TITLE
clr-datagrid getting vertical scrollbar for paginated grid

### ISSUE THREAD

**Issue by dragon503** [vmware/clarity#2351]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[ ] enhancement
```

### Reproduction of behavior

clr-datagrid getting vertical scrollbar for paginated grid. I see the same happening in documentation page as well for datagrid pagination examples. 

https://vmware.github.io/clarity/documentation/v0.11/datagrid/full.

And the clr-dg-clumn not accurately aligned with clr-dg-cell. you can see as below
![image](https://user-images.githubusercontent.com/10250828/41268228-ad4b3750-6e31-11e8-93ec-24380546db53.png)

if i remove the calculated height by clarity,   it will be ok. The height calculated not correct.
we use parseInt and missed 1px of the height.

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

### Environment details

* **Angular version:5.2.11

* **Clarity version:0.11.20

* **OS and version:windows7

* **Browser:Chrome  63.0.3239.132 (Official Build) (64-bit)

**Comment by hippee-lee** [comment]
Thanks for reporting this issue. The DOM structure for Datagrid is currently being updated to support pinned columns (#1586) I'm trying to address as many of these UI issues as I can for that feature since we have to make the DOM changes to support pinned columns.

**Comment by youdz** [comment]
This seems to not have been fixed as part of #2670, I'm putting it back into our backlog.

**Comment by coryrylan** [comment]
After a quick investigation it looks like this was fixed at some point in v1.x

v1 - https://clarity.design/documentation/datagrid/full
v0.13 - https://vmware.github.io/clarity/documentation/v0.13/datagrid/full

**Comment by hippee-lee** [comment]
I am closing this. As @coryrylan mentioned it is fixed in the latest version.

**Comment by strapsi** [comment]
this problem has reappeared in version 3
https://v2.clarity.design/datagrid/full <-- no scrollbar in version 2
https://v3.clarity.design/datagrid/full <-- scrollbar is there again since version 3

**Comment by Jinnie** [comment]
@strapsi I am unable to reproduce it. What browser and OS are you using?

**Comment by strapsi** [comment]
i'm using opera 70 on Linux Mint 19.3 Cinnamon
i can only reproduce it with opera. when i open the documentation with firefox everything is okay

**Comment by Jinnie** [comment]
Sorry, Opera is not in our supported list, which can be found here:
https://clarity.design/documentation/get-started
In the "Device and browser support" section.

(We are happy to know that this is the only visible issue the datagrid has in Opera, though :))
