### ISSUE TITLE
clrDate does not override browser-native date picker

### ISSUE THREAD

**Issue by wmpedersen** [vmware/clarity#2360]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The date picker directive clrDate should show the Clarity date picker across supported browsers.

### Actual behavior

According to v0.11 docs and component status the date picker component should be available. When I include an input with type date and the directive clrDate the native browser picker is shown, and the component does not render the Clarity version.

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v11-5a1t3m
  
  
  
  

### Environment details

* **Angular version:** 5.0.0

* **Clarity version:** 0.11

* **OS and version:** Windows 10 Pro version 1709

* **Browser:** Chrome 66.0.3359.181 | Firefox 60.0.1 | IE 11.431.16299.0 | Edge 41.16299.402.0

**Comment by youdz** [comment]
The date picker was introduced in [0.11.8](https://vmware.github.io/clarity/news/0.11.8), and your StackBlitz is using 0.11.1. If I update it to the latest 0.11, it works fine: https://stackblitz.com/edit/clarity-light-theme-v11-datepicker
