### ISSUE TITLE
Pagination for Datagrids 

### ISSUE THREAD

**Issue by mollyyee** [vmware/clarity#2361]
```
[ ] bug
[ ] feature request
[x] enhancement
```

## Description

Pagination in datagrids has been enhanced to include:

- Pagination by input field
- Total number of items/datagrid
- Ability to select number of rows per page

![static](https://user-images.githubusercontent.com/16811152/41371017-00b13d96-6efe-11e8-8e97-47dae2434348.png)

## Documentation
[Documentation on Invision
](https://vmware.invisionapp.com/share/279YRSQRD#/301364900_Documentation)
Datagrids can hold more content than can reasonably be displayed on one page. To account for this, we have designed our pagination component to help users quickly navigate through a large dataset.

To activate pagination on your datagrid, you simply need to add a clr-dg-pagination component in your datagrid's footer. This component exposes many of properties, most of them bindable, to help you interact with it:

[Insert table from current website]

You may also choose to add or remove elements of the pagination component, such as the number of rows shown per page, the total number of items per datagrid, or the first/last page buttons.

By default, the component will responsively drop elements in smaller datagrids starting with the ability to select number of items per page, then the total number of users, then the buttons navigating to the first and last page of the dataset.

## States (not included in documentation)

**First Page** or **Last Page**

To account for accessibility against the darker #fafafa background, disabled icons on the first and last page will be #737373 at 54% opacity. 
![first](https://user-images.githubusercontent.com/16811152/41376449-1cd24064-6f0e-11e8-8224-0dbc3a2dcac7.png)
![last](https://user-images.githubusercontent.com/16811152/41376452-1e3205fc-6f0e-11e8-89ef-142a79ad95c1.png)

**Spacing for 2-digits vs. 3-digits pages**

For a large number of pages in the triple digits, the input field will grow to accommodate for the extra space, shifting over all the elements to the left of the input field by 6px. Spacing between elements remain at 6px. 
![small](https://user-images.githubusercontent.com/16811152/41376526-52ace3d8-6f0e-11e8-86cb-108ddf786890.png)
![big](https://user-images.githubusercontent.com/16811152/41376528-54d4d1c0-6f0e-11e8-9a23-8f9100fdaadb.png)

## Breakpoints (not included in documentation)

By default, the pagination component will maintain 144px of spacing between itself and the left edge of the datagrid footer. If there is less than 144px available, then the element closest to the left edge of the footer will drop off, like so: 

![image 1](https://user-images.githubusercontent.com/16811152/42116214-2c65b034-7bab-11e8-80d3-d1a6ed3b8e75.png)

![image 2](https://user-images.githubusercontent.com/16811152/42116215-2c7d2fc0-7bab-11e8-944a-d9c2784ead51.png)

In small footers, such as those in the master detail view, the pagination component continue to shrink and drop the first/last pagination buttons, like so: 

![master detail 2](https://user-images.githubusercontent.com/16811152/42116325-9229e5f2-7bab-11e8-8aaa-98506d5b7c96.png)

Related/original issues: #1384

**Comment by d-m-s** [comment]
i really like the improved pagination shown in the screens! just one thing - have you tested it on tablet? touch-target might be problematic ...

**Comment by mathisscott** [comment]
Hi @d-m-s 
Generally our touch targets include space _around_ the icons. So the touch targets of the design shown would be much larger than just the glyph.

**Comment by gondomar** [comment]
I've updated clarity to v0.12.4 and I'm not seeing this working.  
Currently have:
<clr-datagrid>
...
   <clr-dg-footer>
      <clr-dg-pagination></clr-dg-pagination>
   <clr-dg-footer>
<clr-datagrid>

Am I missing something?

**Comment by mathisscott** [comment]
Hi @gondomar 
We've finished the _design_ and UX of pagination but have not implemented it yet.

It will be a while before this shows up in the datagrid. If you have an immediate need for it, I'd love to hear the use case. It will help us in our prioritization after 1.0.

**Comment by gnomeontherun** [comment]
Please see https://vmware.github.io/clarity/documentation/v0.12/datagrid/pagination for current pagination details.

**Comment by gondomar** [comment]
A few use cases: 

- User filters for relevant information and needs to compare several rows of data.  Switching to another page of data makes it difficult to compare previous rows of data.  Changing viewable record count makes it possible to see more side by side.
- User's screen sizes are different and may allow for a larger set of data to be displayed between devices.  Makes see similar data on the same page a possibility.

There are other use cases, but I hope this gives you a feel.  This, among a few other things are reasons that our sponsors are forcing us to look into other datagrid options.  It would be nice to have this functioning sooner than later.

**Comment by mathisscott** [comment]
Hi @gondomar 
Thanks for the details. Pagination is in our queue. It's a priority for us because it is blocking a couple of other key issues/components we are looking to implement. It is not something we are currently working on but I can say with confidence that it is under consideration for our next batch of work later this year.

**Comment by robbiesmith79** [comment]
The one request we had is if the component was built in such a way that each of the child elements of the greater pagination element are optional. Meaning, if you only wanted to show just the arrows and total number of rows and not the full spectrum of options, that'd be great. Don't get me wrong, additional ways to navigate your data with an input box select a page number and rows per page is a very welcome addition!
