### ISSUE TITLE
Replacement for `label` element used without interactive element in Login component

### ISSUE THREAD

**Issue by peterblazejewicz** [vmware/clarity#2367]
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

The `label` element has very specific semantics and UX role within the form element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
I think it should be used as intended preventing spread of non-advised practises within community
Anyway, it just spills errors in IDE (if someone is using html linter) or in validator

here is a correct use of `label` in Clarity source:
https://github.com/vmware/clarity/blob/master/src/ks-app/src/app/containers/login/login.component.html#L24

I would probably use the `header` element, but in Clarity its role has been deeply bound to navigation header role only within platform. So I'd probably resort to `section` or just use `div`

Thanks!

### Actual behavior

the  `label` element is used just as any other element with dubious role of hosting a heading.

### Reproduction of behavior

https://github.com/vmware/clarity/blob/master/src/ks-app/src/app/containers/login/login.component.html#L10-L14

### Environment details

* **Angular version:** 4.x.x
n/a
* **Clarity version:**
n/a
* **OS and version:**
n/a
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
n/a

**Comment by gnomeontherun** [comment]
The CSS styles for this section are designed by class names, so you could change it from a label to div or other container element. So in reality, this is just a documentation issue that we could fixup I believe.

**Comment by gnomeontherun** [comment]
Updated documentation website as well.
