### ISSUE TITLE
Form in new grid (0.12)

### ISSUE THREAD

**Issue by antitoine** [vmware/clarity#2368]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

It is impossible to use the new grid (clr 0.12) in the forms, the specific rules are only applied for the old grid (clr 0.11).

### Actual behavior

There's an extra space.

![image](https://user-images.githubusercontent.com/10686594/41510391-0dce522a-7264-11e8-9546-3c9c4f909d34.png)

The HTML: 

```
          <div class="form-group clr-row">
            <div class="clr-col-lg-4 clr-col-md-5 clr-col-12">
              <label for="idFilterForm">Référence</label>
            </div>
            <div class="clr-col-lg-8 clr-col-md-7 clr-col-12">
              <label for="idFilterForm"
                     aria-haspopup="true"
                     role="tooltip"
                     class="tooltip tooltip-validation tooltip-sm"
                     [class.invalid]="filterForm.get('id').value && filterForm.get('id').invalid && (filterForm.get('id').dirty || filterForm.get('id').touched)">
                <input id="idFilterForm" type="text" formControlName="id" size="36" placeholder="48756a5b87d219c58db56c16de99f18637c85e528b388bd04a28a69a0ffdc32b">
                <span class="tooltip-content">La référence est invalide.</span>
              </label>
            </div>
          </div>
```

The missing CSS rule:

```
.form .form-group.clr-row,
form .form-group.clr-row {
  padding-left: 0;
}
```

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v012-pyi85k

### Environment details

* **Angular version:** 6.0.5

* **Clarity version:** 0.12.0

* **OS and version:** Ubuntu 16.04

* **Browser:** all

**Comment by adityarb88** [comment]
@antitoine: If I am not wrong, I think the documentation for the redesigned forms hasn't been updated yet. The old forms can only be used with the old grid. I will confirm this with @gnomeontherun and get back to you on the website update status.

@gnomeontherun could you please confirm?

**Comment by gnomeontherun** [comment]
This is not intended to be a supported configuration, the new forms and new grid will work together, while the old forms and old grid will work together. There are some breaking changes that we cannot fully support other configurations, and the beginnings of the new forms documentation is open on PR #2365. However, we're still putting together all of the Angular controls so for the time being I recommend staying with old flavors until we have the forms completed.

**Comment by gnomeontherun** [comment]
The first round of forms documentation will be out this week, but old grid and old forms will continue to work together with new grid and new forms working together.

Closing as this is as expected for now, and additional documentation will help clarify some of this. See #2365
