### ISSUE TITLE
Incorrect behavior of nested components inside <clr-dg-row>

### ISSUE THREAD

**Issue by daslashi** [vmware/clarity#2373]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

I think it would be great to use custom components inside `<clr-dg-row>`:

```
<clr-dg-row *clrDgItems="let user of users">
    <user [user]="user"></user>
</clr-dg-row>
```

### Actual behavior

Now in this scenario all the nested `<clr-dg-cell>` are placed in the first column of datagrid.

### Reproduction of behavior

https://stackblitz.com/edit/clarity-datagrid-nested-row

### Environment details

* **Angular version:** 5.x.x

* **Clarity version:** 0.11.x

**Comment by gnomeontherun** [comment]
This can be done without any changes. You just put the clr-dg-row inside of your component and then use `*clrDgItems` on your component.

```
<clr-datagrid>
	<clr-dg-column [clrDgField]="'id'">User ID</clr-dg-column>
	<clr-dg-column [clrDgField]="'name'">Name</clr-dg-column>
        <user [user]="user" *clrDgItems="let user of users"></user>
</clr-datagrid>
```

Then the UserComponent template is

```
<clr-dg-row>
        <clr-dg-cell>{{user.id}}</clr-dg-cell>
        <clr-dg-cell>{{user.name}}</clr-dg-cell>
</clr-dg-row>
```

https://stackblitz.com/edit/clarity-datagrid-nested-row-7xxlq8?file=app/app.component.html

I'm going to close this and if you have other questions about this we try to use StackOverflow with the `vmware-clarity` tag to track questions and support.

**Comment by daslashi** [comment]
Thanks for quick help.
