### ISSUE TITLE
Collapse/Expand Component

### ISSUE THREAD

**Issue by cat-mandres** [vmware/clarity#2374]
```
[ ] bug
[ X ] feature request
[ ] enhancement
```

### Expected behavior

There should be a clarity component which can easily collapse & expand any content anywhere on a page.

**Comment by gnomeontherun** [comment]
This seems like a duplicate of #250, is that fair? If it is similar or close enough you could expand on any additional use cases on that ticket for us. Otherwise I'm closing this as a duplicate, feel free to reopen if there is something distinctly different and provide more detail.

**Comment by cat-mandres** [comment]
Not quite, we were more thinking about something like this:

https://getbootstrap.com/docs/4.0/components/collapse/

Where you can hide/show entire sections anywhere on the page - not only in the accordion style.
