### ISSUE TITLE
Spinner button remains active after state change when [disabled] is true

### ISSUE THREAD

**Issue by RobArbor** [vmware/clarity#2375]
**Select one ...** (check one with "x")

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Spinner button should remain disabled when `[disabled]` is `true`.

### Actual behavior

After state change spinner button becomes active.

### Reproduction of behavior
https://stackblitz.com/edit/clarity-light-theme-v012-2ohocu

Steps to reproduce:
1. type some text
2. click save

### Environment details

* **Angular version:** 6.0.0

* **Clarity version:** 0.12.0

* **OS and version:** Windows 10

* **Browser:** Chrome 67 | Firefox 60

**Comment by adityarb88** [comment]
@RobArbor: We will take a look and get back to you. Thanks!
