### ISSUE TITLE
Error in upgrade to 0.12 version

### ISSUE THREAD

**Issue by btd1337** [vmware/clarity#2380]
**Select one ...** (check one with "x")

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Compile the project correctly.

### Actual behavior

After you upgrade from version 0.11 to version 0.12 this error occurs:
```
ERROR in node_modules/@clr/angular/popover/common/popover-host-anchor.token.d.ts(2,58): error TS2315: Type 'ElementRef' is not generic.
webpack: Failed to compile.
```

### Reproduction of behavior

* Install the new Clarity version:

```
npm install @clr/ui@0.12.1 @clr/icons@0.12.1 @clr/angular@0.12.1 --save
```
* Try run project:
```
npm start
```

### Environment details

* **Angular version:** 5.2.11

* **Clarity version:** 0.12.1

* **OS and version:** Arch Linux

* **Browser:** [all]

**Comment by adityarb88** [comment]
@btd1337: Are you still on Angular 5? 0.12 requires that you upgrade to Angular 6. If you are still on Angular 5, please upgrade and let us know if you face this issue.

**Comment by hippee-lee** [comment]
Following up on @adityarb88's comment if you are already on Angular 6, I did a fresh install with the @angular/cli and manually added Clarity without any issues. 

https://github.com/hippee-lee/clarity-12-test

If you continue to have this issue please post a repository that reproduces the error so I can take a look.

**Comment by gnomeontherun** [comment]
Angular 6 introduced an optional generic for ElementRef, so Angular 6 is required for 0.12 as outlined in release https://vmware.github.io/clarity/news/0.12.0.

https://github.com/angular/angular/blob/master/CHANGELOG.md#small-features

**Comment by btd1337** [comment]
Somewhere informs you that the installation of version 0.12 is only for Angular 6?

**Comment by Shijir** [comment]
@btd1337 It's in the changelog for v0.12: https://vmware.github.io/clarity/news/0.12.0

>The 0.12 release is only certified to work with Angular 6 and above.

**Comment by gnomeontherun** [comment]
Also, NPM will warn you when trying to install packages that have outdated dependencies. Closing as this should not be an issue if you have Angular 6.
