### ISSUE TITLE
Inlines spinner - multiple images spinning

### ISSUE THREAD

**Issue by GaryHyland** [vmware/clarity#2382]
**Select one ...** (check one with "x")

```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Std inline spinner wanted

### Actual behavior

Attached shows the issue
![clarity spinner issue](https://user-images.githubusercontent.com/39715655/41757119-a09d7b24-7612-11e8-9238-36e7ca033826.png)

### Reproduction of behavior

`<form>
	<h3>blah</h3>

	<section class="form-block">
		<label>Geolocation data</label>
		<div class="clr-row">
			<div class="clr-col-sm-12 clr-col-md-6">
				<div class="form-group">
					<span class="spinner spinner-inline">checking...</span><span>checking...</span>
				</div>
			</div>
		</div>
	</section>
</form>`

Dunno why the code section not showing properly above - you get the idea though, fairly simple.
there seems to be 12 copies of the spinner icon all rotating like a fan blade. Related to clr-col-12 or 6??

### Environment details

* **Angular version:** 6.0.5

* **Clarity version: 0.12

* **OS and version: Win 10 x64

* **Browser:** [Edge]

**Comment by adityarb88** [comment]
@GaryHyland: It looks like you are using the forms in grid markup incorrectly. Our docs provide more info on how to use forms in grids. 
![image](https://user-images.githubusercontent.com/1426805/41781095-9c622450-7604-11e8-895a-0fdfcfb19e6a.png)

Also, please note that 0.12 adds a new grid and a redesigned forms component. The new grid should only be used with the new forms (new forms docs are still not up. We are working on that right now). Until you can use the new forms, please use the old forms with the old grid.

Please take a look at this: https://stackblitz.com/edit/clarity-light-theme-v11-dgeknz?file=app/app.component.html

I had to add a `margin: 0` on the spinner to make it align correctly.

Let us know if this helps. Closing the issue based on the above info. Please feel free to reopen if you have more questions.
