### ISSUE TITLE
Question: Is't possibile to use the UI Components with VueJS?

### ISSUE THREAD

**Issue by biapar** [vmware/clarity#2383]
Is't possibile to use the UI Components with VueJS?

**Comment by adityarb88** [comment]
We just add styles to native HTML elements in Clarity UI. You should have no issues using Clarity UI with VueJS.

Closing the issue based on the above info. Please feel free to reopen the issue if you have more questions.

**Comment by biapar** [comment]
Have you some example?

**Comment by biapar** [comment]
Updates?

**Comment by mathisscott** [comment]
Hi @biapar 
Keep an eye on https://clarity.design/storybook/core/

It's still in progress but I think that is what you are looking for.
