### ISSUE TITLE
Min and max dates for datepicker component

### ISSUE THREAD

**Issue by franckstifler** [vmware/clarity#2385]
```
[ ] bug
[x] feature request
[x] enhancement
```

### Expected behavior

Date picker does not provide an api to disable dates from a min or a max value.

### Environment details

* **Angular version:** 6.x.x

* **Clarity version:** 0.12*

* **OS and version:** Windows*

* **Browser:** [all]

**Comment by adityarb88** [comment]
@franckstifler: This is a duplicate of https://github.com/vmware/clarity/issues/1984. Its already in our queue. Please subscribe to https://github.com/vmware/clarity/issues/1984 for more updates.
