### ISSUE TITLE
Getting Started Unclear for UI-only (Non-Angular)

### ISSUE THREAD

**Issue by tedyoung** [vmware/clarity#2389]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior

As a non-Angular developer, I want to use the UI (i.e., the HTML/CSS). I expected the "Getting Started" page to have a section, with step-by-step instructions, for making use of just the UI portion.

### Actual behavior

The "Getting Started" page doesn't provide straightforward instructions for the above use case. It starts out describing the three cases (UX, UI, Angular), followed by links for the UX templates, but then jumps right to "Installing with the Angular CLI".

The next option is the seed project, which seemed promising until it stated that it's "integrated with @clr/ui and @clr/angular, so you don’t need to install Clarity separately.", which is not what I want (I don't want Angular).

The last part are step-by-step instructions for adding it manually to an Angular project.

---

I think this page could use an overhaul, especially since it's a new user's first exposure to the project. I'm happy to propose a bit of a re-org for this page, as well as incorporating the UI-only use case (if someone can point me to the specifics, or a sample project using it).

**Comment by mathisscott** [comment]
Hi @tedyoung 
What do you have in mind for a re-org? I'm happy to discuss.

As for using just the UI portion, I believe you can just import `@clr/ui` into your project and use the CSS.

More information here: https://www.npmjs.com/package/@clr/ui

**Comment by hippee-lee** [comment]
@tedyoung - Two questions:
1. did you have any follow-up ideas for the documentation re-org mentioned above? 
2. Were you able to integrate the `@clr/ui` into your project?

**Comment by gnomeontherun** [comment]
Closed via #2507
