### ISSUE TITLE
ReferenceError: customElements is not defined

### ISSUE THREAD

**Issue by rajinder-yadav** [vmware/clarity#2392]
```
[X] bug
```

### Expected behavior

New Angular 6 app built using the CLI, seeing a reference error in debug console.

```
ReferenceError: customElements is not defined clr-icons.min.js:17:345
```

![clarity-error](https://user-images.githubusercontent.com/439226/41815298-6d43fa00-7734-11e8-8552-9675674718c3.png)

### Actual behavior

Don't expect to see any error.

### Reproduction of behavior

Create new app using cli and follow step to install Clarity design.

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

### Environment details

* **Angular version:** 6.0.2

* **Clarity version: 0.12.1

* **OS and version: `Linux karma 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* **Browser: Firefox Quantun 60.0.2 (64-bit)

**Comment by dfaivre** [comment]
I had the same issue, it was because I was loading the `clr-icons.min.js` before the polyfill.  FYI, I got it from the `clarity-seed` project, which also seems to have it backwards.  https://github.com/vmware/clarity-seed/blob/master/.angular-cli.json

**Comment by gnomeontherun** [comment]
The seed has it correct https://github.com/vmware/clarity-seed/blob/master/.angular-cli.json#L29.

Also, if you are starting a new project you can run `ng add @clr/angular` and it should set it up correctly for you.

**Comment by dfaivre** [comment]
@gnomeontherun -- That's actually the line I had to manually edit, and put the `"../node_modules/web-animations-js/web-animations.min.js"` script above it (switch lines 29 and 30).  My scripts section:

```
"scripts": [
              "node_modules/@webcomponents/custom-elements/custom-elements.min.js",
              "node_modules/@clr/icons/clr-icons.min.js"
            ]
```

**Comment by dfaivre** [comment]
Oh, yep, I misread web-animations for webcomponents.  Sorry about that.
