### ISSUE TITLE
Missing error icon tooltip message

### ISSUE THREAD

**Issue by dszegvari** [vmware/clarity#2394]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When a field is not valid, it should be marked invalid by the exclamation mark icon. When clicking on the icon, the validation error message should be displayed in a tooltip.

### Actual behavior

When a textarea, a datepicker or a combobox is invalid, the exclamation mark icon appears, but it doesn't open any tooltip for the error message.

### Reproduction of behavior

Link to the reproduction: 
https://stackblitz.com/edit/clarity-light-theme-v11-wzrs2u?file=app%2Fapp.component.html

From Clarity Version: [Light Theme v11](https://stackblitz.com/edit/clarity-light-theme-v11)

### Environment details

* **Angular version:** 6.0.3

* **Clarity version:** 0.12.0

* **OS and version:** Windows 10

* **Browser:** Likely all (tested with Chrome 67, Firefox 60, IE 11, MS Edge 41

**Comment by gnomeontherun** [comment]
Hello, this is a limitation of our old forms, which is being addressed by the new forms work in progress. Unfortunately, the complete lineup of Angular components are not yet ready, so the datepicker, select, and textarea examples are currently not supported for tooltip validation. We're moving away from tooltips entirely. You can see the first round of documentation in #2365 which should go up this week.

Closing as this is a limitation of the old forms we don't plan to resolve, but instead are providing the new forms.
