### ISSUE TITLE
How to binding focus event for clr-dg-row ?

### ISSUE THREAD

**Issue by emilyliuguiling** [vmware/clarity#2397]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[ ] enhancement
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Hi @emilyliuguiling - I'm not seeing an issue report or a stackblitz that replicates / demonstrates it. It seems like you submitted without filling in the details? Here is a link to a Clarity starter stackbliz: https://stackblitz.com/edit/clarity-dark-theme-v11

**Comment by hippee-lee** [comment]
@emilyliuguiling - any updates on a reproduction stackblitz?
