### ISSUE TITLE
Mark unsupported versions of documentation

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2403]
Update the website to clarify the support for a particular version, such as 0.10 is now EOL.

**Comment by gnomeontherun** [comment]
Done https://vmware.github.io/clarity/documentation/v0.10/color

**Comment by reddolan** [comment]
Did we build a custom App-level Alert for this? The font sizing is different between the implementation and the docs

![image](https://user-images.githubusercontent.com/1858226/42539252-6983d764-844f-11e8-9eff-26ebf302a340.png)

**Comment by reddolan** [comment]
Docs show the font-size at 13, whereas the implementation is at font-size 11

**Comment by gnomeontherun** [comment]
Nothing special, I just used the 'alert-small' variation.

**Comment by reddolan** [comment]
Hmm, didn't know that we could do that. Thx
