### ISSUE TITLE
Typo on Documentation: getting started

### ISSUE THREAD

**Issue by mikec83** [vmware/clarity#2405]
On the getting started documentation, there is a typo in the sample code:

Step 4: Add Clarity to Angular application
Import the ClarityModule into your Angular application's module. Some features also depend upon the BrowserAnimationsModule, so you should add it as well. Your application's main module might look like this:
```
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { BrowserAminationsModule } from "@angular/platform-browser/animations";
import { ClarityModule } from "@clr/angular";
import { AppComponent } from "./app.component";

@NgModule({
    imports: [
        BrowserModule,
        BrwoserAnimationsModule,
        ClarityModule,
        ...
     ],
     declarations: [ AppComponent ],
     bootstrap: [ AppComponent ]
})
export class AppModule { }
```

The typo is **_Brwoser_**AnimationsModule

**Comment by hippee-lee** [comment]
@mathisscott - I'll publish this separate from the v0.12.2 website push.

**Comment by hippee-lee** [comment]
Fixed with this commit: https://github.com/vmware/clarity/commit/260a5fd347506ac9845060b829a76b0821bd0c69
