### ISSUE TITLE
"ng add" works only if default project exist

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#2406]
```
[] bug
[ ] feature request
[V] enhancement
```

### Expected behavior

`ng add @clr/angular@next` should support applications and not only work with default one.

Please allow to specify project:
`ng add @clr/angular@next --project=another-app`

### Actual behavior

Currently it only works if `src/app` exist
If trying to add to different project - error thrown:
![image](https://user-images.githubusercontent.com/1386622/42061577-5c326794-7b33-11e8-91ce-d19d3420e99d.png)

### Environment details
* **Angular version:** 6.0.1

**Comment by hippee-lee** [comment]
Thanks for the feedback. There are plans to expand the capabilities for the Clarity schematic and this feedback helps us to know whats important to you as a user.
