### ISSUE TITLE
Form submit action is not working

### ISSUE THREAD

**Issue by rameshyala** [vmware/clarity#2407]
[ X] bug

Hi,  i am using normal form it have a POST action with form data, i am update clarity with latest v0.12.1, after that this form submit action is not working, even  i did't see any call info in network tab (developer tools). It is works fine with the previous versions . 

check the [stackblitz,](https://stackblitz.com/edit/clarity-light-theme-v11-yp5xeg?file=app/app.component.htmll) in that the login.php is not calling with latest. 
Thanks.

**Comment by gnomeontherun** [comment]
Your stackblitz is using 0.11.21, but why are you trying to do a normal form instead of an Angular form? 

https://stackblitz.com/edit/clarity-light-theme-v11-dg6nfk?file=app/app.component.html

**Comment by gnomeontherun** [comment]
Closing as this is not really a bug, but an incorrect form.

**Comment by rameshyala** [comment]
Hi, @gnomeontherun in my case  i am not using any angular framework hear(in this page), i need call the  servicel with POST (it's not need not be a  XHR call,my service expect non XHR call) , It works fine with older versions of clarity with latest update it is breaking. It's work for angular forms ,just try once with normal forms with clarity UI call the form post action.
