### ISSUE TITLE
customElements is undefined in IE11

### ISSUE THREAD

**Issue by GolubevS** [vmware/clarity#2410]
[X] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

First example in https://vmware.github.io/clarity/documentation/v0.12/input-fields
IE11 error: customElements is undefined

### Reproduction of behavior

First example in https://vmware.github.io/clarity/documentation/v0.12/input-fields

### Environment details

* **Angular version:** 6.x.x

* **Clarity version:** 0.12

* **Browser:** IE11

### Workaround

In "angular.json" file change script order from default

"scripts": [
      "node_modules/@clr/icons/clr-icons.min.js",
      "node_modules/@webcomponents/custom-elements/custom-elements.min.js"
]

to

"scripts": [
      "node_modules/@webcomponents/custom-elements/custom-elements.min.js",
      "node_modules/@clr/icons/clr-icons.min.js"
]

(default script order is generated by the command "ng add @clr/angular@next")

**Comment by GolubevS** [comment]
Change in default script order described above leads to many of clarity components goes into a non-working state (i.e. this workaround not working).

**Comment by gnomeontherun** [comment]
I'm not clear about how the https://vmware.github.io/clarity/documentation/v0.12/input-fields page is an example, I see it loading fine in IE11. I am fixing the bug with `ng add @clr/angular` so it orders them correctly.

https://live.browserstack.com/issue-tracker/58d2510c4afd9a6bcd37dd2492cc6dd29fd9afd4/win10_ie_11.0.jpg

**Comment by GolubevS** [comment]
After changing script order to 

"scripts": [
      "node_modules/@webcomponents/custom-elements/custom-elements.min.js",
      "node_modules/@clr/icons/clr-icons.min.js"
]

datagrid and modals stop working in ie11 (and i guess many others components), so i think this workaround is not a good decision.

As to "IE11 error: customElements is undefined", i can't reproduce it on https://vmware.github.io/clarity/documentation/v0.12/input-fields page (i just copy code of the first example to my project) and on plunker https://stackblitz.com/edit/clarity-light-theme-v11-znjrkx. I can reproduce this error only in my project.

I think there are some differencies in environments config of these pages and my project. I'm using clarity 0.12 and

Angular CLI: 6.0.8
Node: 10.1.0
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

Content of files "app.component.ts" / "app.component.html" can be found at https://stackblitz.com/edit/clarity-light-theme-v11-znjrkx

Result:

![err](https://user-images.githubusercontent.com/39259721/42181658-3ecf3042-7e44-11e8-92fd-989ad29965d4.png)

**Comment by gnomeontherun** [comment]
This appears to be an issue related to the build and setting up the polyfill. I'm not sure what you're doing in your build, nor do I see this issue in the stackblitz you provided in IE11. Are you including the polyfill twice (in polyfills.ts and in angular.json)? Otherwise, if you have a custom webpack build there are some possibilities that your build could mangle it in a way that it breaks the polyfill see https://github.com/webcomponents/custom-elements/issues/90#issuecomment-304421398

**Comment by GolubevS** [comment]
I finally found the cause of the IE11 error (thanks for polfills mention) - in polyfills.ts uncomment line:

import 'core-js/es6/reflect';

and yes, it's needed to change script order in angular.json with polyfill in first:

"scripts": [
    "node_modules/@webcomponents/custom-elements/custom-elements.min.js",
    "node_modules/@clr/icons/clr-icons.min.js"
]

My polyfill.ts file looks like this now:

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';

And now there aren't any errors in IE11:)

I think information about all necessary polyfills should be included in your "Get started" page:

https://vmware.github.io/clarity/documentation/v0.12/get-started

otherwise this information will have to be obtained empirically :)

**Comment by gnomeontherun** [comment]
I refer you to Angular's details about IE11 https://angular.io/guide/browser-support

**Comment by GolubevS** [comment]
Thanks!
