### ISSUE TITLE
Usage of *clrDgHideableColumn with Server-driven Datagrid

### ISSUE THREAD

**Issue by m-tomczyk** [vmware/clarity#2418]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Expected behavior

In my application there is use-case where data grid may contain many columns. Some of them should not be visible by default but only on user request. It is possible to accomplish it by using `*clrDgHideableColumn` directive but all columns must be provided with data even if not visible. 
For performance reason this is not possible. For a change that shows column i need to request server for this additional data. 
Is there 'clarity' way of doing that? Some hook/output i can listen to column visibility changes and retrieve-provide data when needed? If not, is it planned?
This can be implemented bypassing clarity directive but I don't want to 'go against the current'. 

### Actual behavior

No clear way to accomplish server-driven column visibility

### Reproduction of behavior

Does not apply

### Environment details

* **Angular version:** 6.0.3

* **Clarity version:** 0.12.1

* **OS and version:** any

* **Browser:** all

**Comment by youdz** [comment]
You are right, we are not exposing an output for hideable columns, and we should.

We're a bit backed up up right now so I don't think we can tackle this feature request in the short term, but I believe using your own `*ngIf` on the columns and the corresponding cells like you suggested is a reasonable workaround that won't break in the future (only uses stable features like "dynamic" columns). Once we have the output implemented, you will be able to move to it when you have time for it, since the workaround will be stable.

**Comment by m-tomczyk** [comment]
Thank you for information. `*ngIf` with custom column showing logic is what was my first choice and the one I'll go for as for now.
Still I went for some source snooping and found alternative. I'll leave it here, maybe it will be useful for somebody else.

### Alternative workaround that will *not* work
First thing that I was looking into is `ClrDatagridHideableColumn` directive itself and right there I found promising public field `column` of type `DatagridHideableColumnModel` that contained public getter `hiddenChangeState` - looked exactly like what I needed. I set up `@ViewChildren` catching all `ClrDatagridHideableColumn` and tried to extract what i needed. Sadly this property look dead. It is not set inside this directive. Could not find any other class that would set it, nor was it set at runtime. 

### Alternative workaround that did work
After bit more snooping i found that clarity uses `HideableColumnService` that had even more promising public observable that you can hook to: `columnListChange`. This service seams to be provided in `ClrDatagrid` component but is not injected in it. But it happens to be injected in `ClrDatagridFooter` and as public property even. So going with some rxjs operators (internally datagrid uses own column IDs that i needed to convert to own) I was able to get stream that I needed. 

***I'm pretty sure that even if I managed to avoid accessing private properties, the public ones are not considered public API. So this workaround may become broken at any time.***

Example template:
```html
<clr-datagrid>
  <clr-dg-column [clrDgField]="'first'">
    <ng-container *clrDgHideableColumn="{hidden: false}">
      First
    </ng-container>
  </clr-dg-column>
  <clr-dg-column [clrDgField]="'second'">
    <ng-container *clrDgHideableColumn="{hidden: false}">
      Second
    </ng-container>
  </clr-dg-column>

  <clr-dg-row *clrDgItems="let item of data">
    <clr-dg-cell>{{item.first}}</clr-dg-cell>
    <clr-dg-cell>{{item.second}}</clr-dg-cell>
  </clr-dg-row>

  <clr-dg-footer>
    <clr-dg-pagination #pagination [clrDgPageSize]="10">
      {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
      of {{pagination.totalItems}} rows
    </clr-dg-pagination>
  </clr-dg-footer>
</clr-datagrid>
```
And corresponding component:
```typescript
export class AppComponent implements AfterViewInit {

  @ViewChild(ClrDatagridFooter)
  footer: ClrDatagridFooter;

  @ViewChildren(ClrDatagridColumn)
  columns: QueryList<ClrDatagridColumn>;

  data = [
    {
      first: '1',
      second: '1'
    },
    {
      first: '2',
      second: '2'
    }
  ];

  ngAfterViewInit() {
    this.footer.hideableColumnService.columnListChange
      .pipe(
        flatMap(items => of(...items)),
        flatMap(item => item.hiddenChangeState.pipe(
          map(status => ({status, field: this.columns.find(col => col.columnId === item.id).field}))
        ))
      )
      .subscribe(change => console.log(change));
  }
}
```

### Proper implementation suggestion
If I may suggest one - For my usecases most convenient implementation would be by extending `ClrDatagridStateInterface` keeping it as single source of datagrid status. It could be extended with property similar to:
```typescript
columns? : {
  name: string,
  visible: boolean
}[]
```

**Comment by m-tomczyk** [comment]
Related/duplicated issues for this change: https://github.com/vmware/clarity/issues/1856 https://github.com/vmware/clarity/issues/2117 and https://github.com/vmware/clarity/issues/2204#issuecomment-383210477

**Comment by Wallabeng** [comment]
As we need this output for one of our custom components, I implemented the output functionality in a fork.
Please let me know if this fits your needs and can be merged in your master or at least gets a topic branch for a pull request and review afterwards.
Here's the commit for it:
https://github.com/Wallabeng/clarity/commit/030a64c5d83c295e61f33243b316416476df4984

**Comment by Wallabeng** [comment]
@youdz thanks for the hints. I will fix this, can I open the pull request against the master (which you disallow in coding guidelines) or do you create a topic branch for this?

**Comment by Wallabeng** [comment]
Regarding unit tests: As it's a different style to include this directive, I also copied the existing tests to the new test set.

**Comment by technbuzz** [comment]
Looks like this functionality `[(clrDgHidden)]`  is added in **1.0.0-beta.1** as can be seen here https://vmware.github.io/clarity/news/1.0.0-beta.1

Do any one knows how to use it?

**Comment by youdz** [comment]
@technbuzz: that's because you have to use `<ng-template>`, not `<ng-container>`, like this:
```html
<ng-template clrDgHideableColumn [(clrDgHidden)]="hidden">
```
That's because Angular doesn't support two-way binding with the shortcut `*`-syntax.

Please ask your question on StackOverflow next time, we want to keep GitHub to bug reports and feature requests, not "how to" questions.

PS: Closing this issue since the feature was merged.
