### ISSUE TITLE
@clr/ui@0.12.2 requires a peer of bootstrap@4.0.0-alpha.5 but none is installed

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#2419]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[V] enhancement
```

### Expected behavior

No warning should be thrown

### Actual behavior

NPM warning thrown:
```bash
npm WARN @clr/ui@0.12.2 requires a peer of bootstrap@4.0.0-alpha.5 but none is installed. You must install peer dependencies yourself.
```

### Reproduction of behavior

`ng new ng-clr`
`ng add @clr/angular`
![image](https://user-images.githubusercontent.com/1386622/42213084-91793870-7ec0-11e8-9290-650f10cf29fb.png)

### Environment details
```bash
Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by gnomeontherun** [comment]
This is expected behavior, and described for anyone who wants to use a custom theme https://vmware.github.io/clarity/documentation/v0.12/themes#examples.

This will go away when we stop having any dependency on Bootstrap, and so follow a different ticket #1531 for updates. I'm going to close this as its a duplicate.
