### ISSUE TITLE
Header actions with caret down display issues when using text

### ISSUE THREAD

**Issue by rmaspoch** [vmware/clarity#242]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The caret down icon should be aligned next to the adjacent text without overlapping.

### Actual behavior
The caret gets displayed on top of the text. In Edge the caret does not show at all.

![clarity](https://cloud.githubusercontent.com/assets/7172365/21185541/154e4f46-c1df-11e6-8aa7-848fe9ce99f1.png)

### Reproduction of behavior
In order to reproduce the issue I copied the header actions with a user email address from the header types demo.
Here's a plunker illustrating the issue:
https://plnkr.co/edit/JUSOfEUA0FTSTXJynIGf

It seems some styles are overwritten causing the width & height of the caret to grow to 22px instead of the intended 10px.

### Environment details
Angular 2.2.3
Clarity 0.7.4
Windows 10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Chrome 54.0.2840.99
Microsoft Edge 38.14393

**Comment by adityarb88** [comment]
Hi @rmaspoch. Thanks for reporting this. I will take a look at why this works in the demo but not on the actual header.
