### ISSUE TITLE
Override responsive shrink of sidenav menu to trigger at larger screen size

### ISSUE THREAD

**Issue by GaryHyland** [vmware/clarity#2423]
**Select one ...** (check one with "x")

```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Setting/config to allow responsive hide of left nav menu at specific screen size.
Have some tablets that am running my app on that are 1024 x768 and would really benefit from having the left nav menu shrink to hamburger (as it does currently if go below 576 wide).
Would think this a useful settings for people to have access to. ie shrink left nav and show hamburger menu at px or grid size eg. lg for me.

Needed for apps where want to ensure have enough space on screen to capture in-field details and also ensure text/fields are sized large enough for use by people using finger on the touchscreen.

Also, appreciate any interim means to best do this using SCCS / CSS file changes or overrides.

### Actual behavior

Left nav menu only slides out of way once go down to 576.
Generally people will use a certain page and only need to use menu occasionally, so menu takes up a lot of space when not often used. Can afford this space on large desktop screens but not really at 1024 size on a small screen tablet.

### Environment details

* **Angular version:** 6.0.5
* **Clarity version:** 0.12.1

* **OS and version:** Win 10

* **Browser:** Edge

**Comment by adityarb88** [comment]
@GaryHyland: I was wondering if you got a chance to take a look at the Vertical Nav (https://vmware.github.io/clarity/documentation/v0.12/vertical-nav/basic-structure/charmander). It provides an option to collapse on larger screens and then similar to the sidenav, you can assign it a responsive level for breakpoints `sm` and below. Please let us know if that helps.

**Comment by hippee-lee** [comment]
Hey @GaryHyland - will the vertical nav suggested above help you with this issue?

**Comment by GaryHyland** [comment]
Thanks. I am still reviewing the best option for me.
Good to know about the vertical nav and that it can be responsive also.
Happy to close. I will look to feedback if I do anything that may be worth sharing.

**Comment by GaryHyland** [comment]
Have got responsive nav triggering at 1024 by copying the CSS block 
@media screen and (max-width: 768px) {
from @clr/ui/clr-ui.css into my app css file and changing the 768 to 1024.
Works to trigger the nav as I want for present. Might be good if could set this responsive trigger point in some clr setting to avoid having to duplicate or change clr css code.
