### ISSUE TITLE
[Improvement] Position of the action pop-up in the single row action data-grid

### ISSUE THREAD

**Issue by ChitMeng-VMware** [vmware/clarity#2428]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

When the overflow button is clicked within the row of the data-grid, the action pop-up should show along alongside with data row selected.

### Actual behavior

When the overflow button is clicked within the row of the data-grid, the action pop-up covers the first item of the row (or more)
![screenshot of single row action data-grid](https://user-images.githubusercontent.com/22942872/42339752-bea0dd5c-8042-11e8-8a08-94e1566fe519.png)

### Reproduction of behavior

Jira ticket raised for this issue
https://jira.eng.vmware.com/browse/SKYNSXT-119 

### Environment details

* **Angular version:** 4.x.x

* **Clarity version: 0.12.2

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jeeyun** [comment]
Deferring to @reddolan for UX input on whether we need to change our design on this.

**Comment by GaryHyland** [comment]
Yeah - I reckon an option to position at end of the row would also be good. For example.. I have a grid that has input fields and buttons in it on the right hand side and I also then position an action button on the right by using clr-dropdown-menu.

**Comment by colinreedmiller** [comment]
Without knowing more about all the potential permutations and corner cases it would seem that we might find ourselves considering many positioning needs such as are available in signposts and tooltips: 

https://clarity.design/documentation/signposts
https://clarity.design/documentation/tooltips

e.g.
    positions: string[] = [ "top-left", "top-middle", "top-right",
                            "right-top", "right-middle", "right-bottom",
                            "bottom-left", "bottom-middle", "bottom-right",
                            "left-top", "left-middle", "left-bottom" ];
    position: string = "right-middle";

@ChitMeng-VMware What do you think is required to achieve a complete and sufficiently flexible solution? The case shown would be remedied by most options except "right-middle" which would result in the problem we see, while another case might require another position to surface the action pop-up in a useful position. Thoughts?

**Comment by gnomeontherun** [comment]
This request has merit but we are not currently planning to address it due to it likely requiring a design change and possible visual breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved or configurable by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
