### ISSUE TITLE
Clarity alert should be visible, when a new alert is pushed to an empty list of alerts

### ISSUE THREAD

**Issue by walter-mair** [vmware/clarity#2430]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

A Clarity alert should be visible, when a new alert is pushed to an empty list of alerts
This happens in production mode only. It works as expected in development mode.

### Actual behavior

Clarity alert is not visible, the first time an alert is pushed. 
On the next push of an alert, both alerts show up.
After deleting all alerts, this behavior can be reproduced!

Stackblitz url: https://stackblitz.com/edit/clarity-light-theme-v11-6npkw

### Reproduction of behavior

It works fine in Stackblitz, since this uses development mode.
The Stackblitz environment does not allow to enable production mode by inserting the statement

'enableProdMode();' into main.ts right after the last import statement, because of

Error in 5.2.1/bundles/core.umd.js (5296:15)
Cannot enable prod mode after platform setup.
Evaluating main.ts
Booting application
 
However, outside Stackblitz the production mode can be set this way and the malfunction can be reproduced

Looking at the Elements in Inspect Browser, you can see the difference:  
In production mode a  'class="alert alert-info alert-hidden"' is generated, which cause the alert not to be displayed.
'alert-hidden' is NOT generated in development mode.

### Environment details

* **Angular version:** 5
with
* **Clarity version:** 0.11

as well as 

* **Angular version:** 6
with
* **Clarity version:** 0.12.0

* **OS and version:** Ubuntu 18.04 LTS

* **Browser:** tested with
Chrome  Version 67.0.3396.99 (Official Build) (64-bit)
Mozilla Firefox for Ubuntu 60.0.2 (64-bit)

**Comment by adityarb88** [comment]
@walter-mair: I am unable to access the stackblitz that you posted. I see this: 
![image](https://user-images.githubusercontent.com/1426805/42379990-67f6c86e-80fa-11e8-84ab-0da8d08949bd.png)

Please fix the StackBlitz and update the issue and we will be happy to take a look. Thanks!

**Comment by walter-mair** [comment]
@adityarb88 
sorry,  
here the correct URL:
https://stackblitz.com/edit/clarity-light-theme-v11-6npkwj

**Comment by gnomeontherun** [comment]
There is some kind of lifecycle issue here, probably around the internals of detecting changes in the alert.
