### ISSUE TITLE
Angular + DatePicker - can't change font color for the input value

### ISSUE THREAD

**Issue by ChrisKaun** [vmware/clarity#2439]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I'm using clarity in a angular project and currently I am struggling with the date picker.
When using the date picker without injecting the LOCALE in a simple `<input type='date' clrDate>` I can change the font-color by simply adding a css-rule `color: red` to it.

### Actual behavior

When I inject the current LOCALE ('de-DE')  to my my angular component, the date will be parsed to the correct format (dd.mm.yyyy)  but I can't change the font color of that input.

### Reproduction of behavior

https://clarity-light-theme-v11-fm8fyv.stackblitz.io/

### Environment details

* **Angular version:** 5.2.10

* **Clarity version:**
v0.11.1

* **Browser:** [all]

**Comment by gnomeontherun** [comment]
There appears to be some issue with the stackblitz, adding:

```
<style type="text/css">
input[type="text"] {
  color: red;
}
</style>```

to the bottom of `index.html` changes the color to red.

**Comment by mathisscott** [comment]
@ChrisKaun 
Your style declarations were all messed up.

See [this working example on stackblitz based on your code](https://stackblitz.com/edit/clarity-light-theme-v11-dvdmqk?file=app/hello.component.ts)
