### ISSUE TITLE
Nav titles in wizard which are really long and truncated should have a tooltip

### ISSUE THREAD

**Issue by nikhildhankani** [vmware/clarity#2444]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Nav titles in wizard which are really long and truncated should have a tooltip

### Actual behavior

There is no tooltip for nav titles in wizard which get truncated

### Reproduction of behavior

https://stackblitz.com/edit/clarity-wizard-navtitle-tooltip?file=app/app.component.html

**Comment by mathisscott** [comment]
We should use an HTML `title` attribute for these cases if possible. I reviewed some other applications and that appears to be the appropriate solution. The stepnav titles are all buttons. So we would need to project the stepnav text into the button and capture the text for the title attribute on the button as well.

**Comment by nikhildhankani** [comment]
@mathisscott any updates on this?

**Comment by mathisscott** [comment]
Hi @nikhildhankani 
This is in our backlog but isn't on our priority list. It is not likely that we would be able to get to it anytime soon.

We are open for contributions, however, if you would feel comfortable helping out...

**Comment by srikanthps** [comment]
Would it be alright if we use `title` always irrespective of whether truncation of text is happening or not?  It seems like its not trivial to figure out when a text has been truncated by CSS unless one uses hacks like this: https://stackoverflow.com/a/7739113/794242

**Comment by gnomeontherun** [comment]
The implementation of this should be pretty simple to project the text into a `title` attribute on the button, but this is internal to the wizard and needs to be supported natively by Clarity. Happy to have a contribution if it is a priority on your end!

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
