### ISSUE TITLE
Accordion Component (new)

### ISSUE THREAD

**Issue by mollyyee** [vmware/clarity#2452]
```
[ ] bug
[x] feature request
[ ] enhancement
```

## Description
An accordion is a set of vertically stacked panels that expand to reveal content related to its panel.

![static](https://user-images.githubusercontent.com/16811152/42589557-38e422ce-84f6-11e8-9f9a-941d3a7ceb7e.png)

## States

**Hover/Focus**
Each panel will serve as a click target for expanding content. 
![hover active](https://user-images.githubusercontent.com/16811152/42589797-037e511c-84f7-11e8-8b1c-29eae035b1e0.png)

**Active**
Content within the accordion should be aligned with the titles in the panels. 
![expanded](https://user-images.githubusercontent.com/16811152/42589804-078a8a64-84f7-11e8-8ff8-9fe275c9a30d.png)

**Multiple Panels Active**
As of now, users can open multiple panels at once. In another setting, we will build the ability to only have one panel open at a time, where opening a second panel (with one panel already expanded) will automatically close the first panel.  
![multi expand](https://user-images.githubusercontent.com/16811152/42589805-07a35170-84f7-11e8-9b23-a906a585ab41.png)

**Text Wrapping Behavior**
Though we recommend keeping accordion titles concise enough to fit in one line, text may need to wrap in smaller accordions.
![error states](https://user-images.githubusercontent.com/16811152/42590219-0ec2d326-84f8-11e8-8ec4-202c288cc2f6.png)

**Icon Placement**
If there needs to be a specific call out in a certain panel, we've designed for icons to be in-line with the text, shifting over titles. 
![icon](https://user-images.githubusercontent.com/16811152/42590371-7a34d712-84f8-11e8-8822-dca7df5888ba.png)

## Dark Theme States

**Static**
![dt- better](https://user-images.githubusercontent.com/16811152/42590741-800369a0-84f9-11e8-9415-32d4cb9e1e69.png)

**Hover/Focus**
![dt-ohver](https://user-images.githubusercontent.com/16811152/42590685-64582a10-84f9-11e8-9c16-e24eac46c678.png)

**Active**
![accordion - without lines](https://user-images.githubusercontent.com/16811152/42590689-670948e8-84f9-11e8-8557-300ca4ded218.png)

Related/Original Issues: #250

**Comment by 19Arne75** [comment]
Is there anywhere i can read more about how clarity is going to implement accordition ?

Made a quick accordition in stackblitz https://stackblitz.com/edit/clarity-accordition-xz2yx9
 
Not sure if i should go ahead with my own or wait for the official..

**Comment by 19Arne75** [comment]
@mathisscott Let me know if i can contribute with something to claritys accordition component.

**Comment by hippee-lee** [comment]
Hi @19Arne75 - contributions are always welcome. We have a general contributions page [here](https://github.com/vmware/clarity/wiki/Contributing) and [here](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md). 


It seems like you are interested in starting with the development for this component. Have you read through the development contributions guidelines  [here](https://github.com/vmware/clarity/blob/master/DEVELOPMENT_CONTRIBUTION.md)?

**Comment by 19Arne75** [comment]
@hippee-lee, yes, I do recognize the setup of git though it has been some time since I used it.
Should i go ahead with the git fork/clone ?

**Comment by mcosta74** [comment]
Please, be sure to call the component (and all sub-components) `Accordion` instead of `Accortion`

**Comment by gnomeontherun** [comment]
First, before you write any code, please submit a new issue with a development plan, as described in the developer contribution guidelines. We have strict standards that we hold all of our code to (ours included), and this will save you and us a lot of time down the road. Also, accessibility is not an option, so please outline things like aria attributes and how it should work on screen readers. If we settle on the dev plan, then we'll work with you on a branch for the feature itself.

https://github.com/vmware/clarity/blob/master/DEVELOPMENT_CONTRIBUTION.md

I'm going to lock conversation on this thread since this is the design details and a new issue should be for the development proposal.

**Comment by coryrylan** [comment]
Make current accordion headers match height of the stackview for consistency. Stepper should keep the same design. Accordion design will be addressed with the new alignment of stepper, accordion, and stackview.
