### ISSUE TITLE
Need Colspan(Summary Row) support in the Datagrid.

### ISSUE THREAD

**Issue by CarreraPHP** [vmware/clarity#2463]
**Select one ...** (check one with "x")

```
[ ] bug
[x] feature request
[x] enhancement
```

### Expected behavior

Need Colspan support in the Datagrid. 

- If i can submit a PR Request for the same, need some guides as to how i can implement it, 
- What all should i take into account. 
- For instance, I believe, to implement colspan support on grid, i need to also handle column resizing as well. 
- If for any reason, colspan was not implement, I would like to know it as well.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.12.3

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by gnomeontherun** [comment]
This is a major feature request, since we don't use tables under the hood. I think for this request to carry weight, we need more details about _why_ its a useful feature and use cases.

**Comment by hippee-lee** [comment]
Hey @CarreraPHP - did you have any additional details about your use case for colspan in datagrid?

**Comment by CarreraPHP** [comment]
@gnomeontherun & @hippee-lee , In Banking and Financial Domain, DataGrid is used mainly to show Numeric values in multiple columns and at times, we may have to show Computed Values like SUM, AVG of all the values in a single column. 

We can implement Computation by using Angular Pipe, but adding weightage to the Value is more important and for the we need Colspan. Rows consisting of Colspan receive more attention than the normal rows, so with the label for the computed value in the column with colspan will add the necessary attention to the value.

If the Colspan is implemented as a special type(summary) row will also suffix the need. However, then the row should be visible in all the page and multiple rows should be supported.

**Comment by stn1986** [comment]
I'm not completely sure I'm understanding you correctly, but you can leave column cells empty which will basically have the same result as colspan.

Also, if you need a totals row on each page like this:

<img width="1027" alt="screenshot 2019-02-04 at 10 23 57" src="https://user-images.githubusercontent.com/5657697/52199828-7919fe80-2867-11e9-8568-77a949cfe375.png">

I've done it like this:
```
<clr-datagrid>
  // Your regular cells
  <clr-dg-row *clrDgItems="let something of manySomethings">
    // etc
  </clr-dg-row>

  // Summary row
  <clr-dg-row>
    // Same as above but with summed (or whatever) data and some columns empty
  </clr-dg-row>
</clr-datagrid>
```

Works with resizing and you can add as many as you want.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
