### ISSUE TITLE
Layout issue progress bar card IE 11

### ISSUE THREAD

**Issue by RobArbor** [vmware/clarity#2466]
**Select one ...** (check one with "x")

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Progress bar should be displayed correctly in a card

### Actual behavior

Progress bar isn't displayed correctly

### Reproduction of behavior

Note can only be reproduced with Internet Explorer.

https://stackblitz.com/edit/clarity-light-theme-v012-3ux5ga

### Environment details

* **Angular version:** 6.0.4

* **Clarity version:** 0.12.4

* **OS and version:** Windows 10

* **Browser:** IE 11.165.17134.0

**Comment by adityarb88** [comment]
@RobArbor: Can you post an image as to what you are seeing on IE11? I couldn't get the StackBlitz to open on IE11 but our website documentation (Progress Bars in Cards)

https://vmware.github.io/clarity/documentation/v0.12/cards

**Comment by RobArbor** [comment]
![ie11_issue](https://user-images.githubusercontent.com/18066581/42764612-5a254b60-8916-11e8-9e1c-266a4b8ff048.png)

**Comment by adityarb88** [comment]
@RobArbor: Please try this link: https://stackblitz.com/edit/clarity-light-theme-v012-qupq1v?file=src/app/app.component.html on IE11

You need to use `attr.value` and `attr.max` for it to work on IE. I believe this should solve your issue.

Please let us know if it doesn't

**Comment by RobArbor** [comment]
Thanks for the help.

Swapping the attributes fixed my issue 
`<progress [max]="100" [value]="70"></progress>`
strange behaviour of IE... 😕

looks related 
https://github.com/angular/angular/issues/24001
