### ISSUE TITLE
New Forms Documentation and Usage

### ISSUE THREAD

**Issue by GaryHyland** [vmware/clarity#2468]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior

Probably mostly documentation but wanted somewhere to capture some points as I start tackling clrForm in clr 0.12.4
- clrForm will issue indexOf errors in console for any label outside of clr-input-container. I (incorrectly really) have used label elements for some headings -which I will amend. A note possibly on strictly using label only within clr-input-container might be appropriate if it will cause errors though.
- required class on label no longer seems to work - surely we still want a good visual marker for mandatory fields.
- LOVE the helper and error texts - looks and works great but will prob have to hold off new forms until more controls are supported for now - ie toggle.
- Documentation - the Forms shows CSS first but Input shows Angular, which I think is preferable - should be consistent either way.
- Would like to see some more real world type form examples in Forms documentation (I know it is not complete yet). Want to see clear guidance of recommended form visual / structure components - form - section - fieldset/legend - clr-input-container - label - input. Also the tie-in / alignment with Bootstrap classes - form-block - form-group - form-control. Want to understand and align with Clarity intended presentation methods where possible.
- For my desktop web focussed forms I will likely still use horizontal for forms used regularly with lots of fields, so keen to understand the preferred form block sturctures, or do I jkust refer to Bootstrap?
- Not sold on the bold field labels. What drove the decision on this? Can look OK for sparse simple vertical forms but think it puts focus too much on the labels not he data fields.

Waiting eagerly to use the forms to full effect.

### Environment details

* **Angular version:** 6.0.3

* **Clarity version:** 0.12.4

* **OS and version:** Win10

* **Browser:** Edge

**Comment by 19Arne75** [comment]
Why is vertical default layout option ? I always got the impression from clarity that desktop environment should be the default mode.

**Comment by gnomeontherun** [comment]
There are a few notes here that we'll be resolving when we add the UX documentation for forms, which should be very soon. There are a few gaps due to pending development, and some things that we can improve. I'll be internalizing this list over the coming weeks and appreciate the input to help make it better!

**Comment by CarreraPHP** [comment]
Will input-container angular component support Textarea? need clarity on layout attribute. Hoping to find these info in the documentation.

**Comment by gnomeontherun** [comment]
Textarea is documented already (it has `clr-textarea-container`). See https://vmware.github.io/clarity/documentation/v0.12/textarea

**Comment by mathisscott** [comment]
This effort should be covered with #932

**Comment by gnomeontherun** [comment]
There are a few notes there I do want to address.

1) Forms are flipping from denoting fields that are required, assuming that they all required unless marked optional. This is based on UX research.
2) There are no more bootstrap features in the new forms, we are intentionally breaking away from Bootstrap as we do not wish to be dependent upon it or its changes.
3) It is possible to have rows with lots of fields, documentation is coming.
