### ISSUE TITLE
Document conditional expandable rows (wiki or Website)

### ISSUE THREAD

**Issue by superche** [vmware/clarity#2475]
**Select one ...** (check one with "x")

```
[ ] bug
[x] feature request
[x] enhancement
```

### Expected behavior

I would like to request supporting conditionally disable for extendable datagrid row.

The content in row detail might be invalid for some cases.
It's better to hide the arrow and row detail for those rows.

For Example:
The arrow and row detail is hidden for the 3rd row.
![screen shot 2018-07-19 at 5 09 26 pm](https://user-images.githubusercontent.com/35420957/42933128-95d4c430-8b76-11e8-8d78-712930faa2d8.png)

### Actual behavior

It's not supported. An empty detail row appent.
![screen shot 2018-07-19 at 5 13 49 pm](https://user-images.githubusercontent.com/35420957/42933363-2be2af8c-8b77-11e8-8913-d747539cfa18.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  
[clarity-v11-datagrid-issue](https://stackblitz.com/edit/clarity-v11-datagrid-issue)

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.10.15

* **OS and version:**

* **Browser:** all

**Comment by superche** [comment]
@youdz Thanks 👍

**Comment by gnomeontherun** [comment]
Closed via #2507
