### ISSUE TITLE
Clarity DataGrid dynamically Selected UI not working

### ISSUE THREAD

**Issue by gondomar** [vmware/clarity#2477]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

With 2 way binding, I expect to set the "selected" variable and see the update in the datagrid

### Actual behavior

In the Stackblitz example, the "Selected" string changes when you manually select an item and it also changes when you programmatically change the value (button), but the UI doesn't update to reflect that change.  I'm not sure if this is similar to issue #1258, but it sounds similar.

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v11-vvrxtx

### Environment details

* **Angular version:** 5.2.1

* **Clarity version:** 0.11.21

* **OS and version:** Windows 10

* **Browser:** [all ]

**Comment by youdz** [comment]
Yeah, that's a bug on our side. When the list of items is updated, we make sure the selection array has the latest references.

But when the selection array itself is set to a new value by the app, the items list and the array get out of sync and the rows can't identify that they're selected anymore. We just need to run the same "sync the selected and items array" code when the selection itself is changed by the app, not just the items.

**Comment by gondomar** [comment]
Is there a workaround for this? Or a way I can refresh something to get them back in sync?

**Comment by youdz** [comment]
The current workaround would be to make sure you use the same reference for both the `allGroups` array and the `selected` array. What that means is that instead of writing:
```typescript
this.selected =  [{ GroupId: 1, GroupName: "Test2" }];
```
you can write:
```typescript
this.selected =  [this.allGroups[1]];
```
and it will work fine. The first version creates a brand new object, whereas the second simply reuses the object you already created.

I hope this helps. 🙂

**Comment by dennitsa** [comment]
I have pretty much the same issue with clrDgSingleSelected. Any attempt to preselect an item in the datagrid fails as clrDgSingleSelected updates my variable with "undefined". 
This is reproducible in v0.11.25( See https://stackblitz.com/edit/clarity-light-theme-v11-rakdgv)
As well as in the latest v0.12.5 (See https://stackblitz.com/edit/clarity-light-theme-v11-nbupfw)

My workaround for the time being is to use v0.11.21, where this is not happening, but this definitely needs a fix.

**Comment by youdz** [comment]
@dennitsa: I don't think this is the same issue, since the workaround doesn't work the same way. It might be related to instantiation order in Angular, I remember we fixed a similar issue a long time ago, I wonder why it might have come back.

**Comment by dennitsa** [comment]
@youdz should I log a new issue then?

**Comment by youdz** [comment]
Please do, yes. I remember we had a very similar issue a while back which we solved with debouncing. The debouncing became useless around 0.10.x, but it seems like latest refactors might have brought the issue back. Your bug clearly needs proper investigation, so creating a separate issue for it means we can consider it in our planning sessions. 👍

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
