### ISSUE TITLE
Progress colors for warning and danger mixed up

### ISSUE THREAD

**Issue by jensenmensen** [vmware/clarity#2478]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

If I declare separate colors for progress bar warning and danger in a theme, actually use these colors.

### Actual behavior

Colors for warning and danger are mixed up. Wrong code is in lines 99-100 in _progress-bar.clarity.scss.

### Environment details

* **Angular version:** 6.x.x

* **Clarity version:** 0.12.4

* **OS and version:** Windows 7

* **Browser:** Chrome 67

**Comment by mathisscott** [comment]
Hi @jensenmensen 
If you are looking to customize the colors for progress bars in a Clarity-based app, I would recommend just overriding the existing ones with CSS.

I wouldn't recommend rebuilding the Clarity SASS into CSS unless you're doing something dramatically different in theming. I haven't drilled down into why that wouldn't work though. Could you provide more details on how and what you're doing?

**Comment by jensenmensen** [comment]
Hi @mathisscott  
I'm just creating a theme for our app and have overriden $clr-progress-danger-color and $clr-progress-warning-color. But because of the mixup in _progress-bar.clarity.scss they get assigned to the wrong css classes.

**Comment by mathisscott** [comment]
Oh I see. I also see that we are defining those variables without a `!default` designation. So it's really anyone's guess if an override happens predictably.

I move this into our backlog and try to get a fix for it for the next release.
