### ISSUE TITLE
no clr-icon svg generated on ie11

### ISSUE THREAD

**Issue by jromerob** [vmware/clarity#2481]
**Select one ...** (check one with "x")

```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The clr-icon tag must generate svg element with the icon image

### Actual behavior

No svg element is generated in any <clr-icon> component of the project. In other browsers works right.
No console errors.
components versions: 
 "@angular/animations": "~5.0.0",
        "@angular/common": "~5.0.0",
        "@angular/compiler": "~5.0.0",
        "@angular/core": "~5.0.0",
        "@angular/forms": "~5.0.0",
        "@angular/http": "~5.0.0",
        "@angular/platform-browser": "~5.0.0",
        "@angular/platform-browser-dynamic": "~5.0.0",
        "@angular/router": "~5.0.0",
        "@clr/angular": "^0.11.0",
        "@clr/icons": "^0.11.0",
        "@clr/ui": "^0.11.0",
        "@webcomponents/custom-elements": "1.0.0",

Typescrypt source:
![image](https://user-images.githubusercontent.com/11867464/43067892-191d8684-8e69-11e8-9724-e6e8859c8086.png)

Html generated
![image](https://user-images.githubusercontent.com/11867464/43068176-fa48bf70-8e69-11e8-919d-8eaf9cbd923b.png)

### Environment details

* **Angular version: 5.0.0

* **Clarity version:0.11

* **Browser:** IE 11

**Comment by mathisscott** [comment]
Hi @jromerob 
Are you loading the custom elements shim in your HTML page?

```
<!--CLARITY ICONS DEPENDENCY: CUSTOM ELEMENTS POLYFILL-->
<script src="path/to/node_modules/@webcomponents/custom-elements/custom-elements.min.js"></script>
```

**Comment by jromerob** [comment]
Yes, is included in angular-cli.json:

`  
"scripts": [
            "../node_modules/core-js/client/shim.min.js",
            "../node_modules/mutationobserver-shim/dist/mutationobserver.min.js",
            "../node_modules/@webcomponents/custom-elements/custom-elements.min.js",
            "../node_modules/@clr/icons/clr-icons.min.js",
            "../node_modules/web-animations-js/web-animations.min.js",
`

**Comment by mathisscott** [comment]
Hi @jromerob 
Could you validate that the custom-elements polyfill is loading? It may also be an async issue where the angular-cli scripts aren't being loaded in the expected order. Or an issue where the compiled scripts are throwing an error in IE.

A stackblitz reproducing the issue would be helpful as well.

**Comment by jromerob** [comment]
Hi @mathisscott finaly i found an error in a previous script that stop the javascript execution only in IE this causes that custom-elements and others librarys didn't load.

Thanks for the help an sorry for the late response
