### ISSUE TITLE
Change theme color palette

### ISSUE THREAD

**Issue by tuliosciotta** [vmware/clarity#2484]
Hi everyone.
I would like to know how to change the color palette of the theme.. It is currently blue but I would like to switch to purple. I tried to find some default variable in scss files but I did not find it.

Can anyone help me with this issue?
Tks!

**Comment by hippee-lee** [comment]
It sounds like you want a custom theme. Custom themes give you the ability to control colors and a complete color palette if you choose to. 
There is more info re: cstom themes here: https://vmware.github.io/clarity/documentation/v0.12/themes#examples

I'm closing this based on the documentation for custom themes but please re-open if that does not answer your question.
