### ISSUE TITLE
File to import not found or unreadable: ~bootstrap/scss/normalize.

### ISSUE THREAD

**Issue by BennieMeng** [vmware/clarity#2486]
![image](https://user-images.githubusercontent.com/37033797/43132952-deea2e7e-8f6f-11e8-9bbe-a507121e3163.png)
when i import main.scss, i find this issue

**Comment by Shijir** [comment]
If you are accessing our sass files and building on your own, you need to install `bootstrap@4.0.0-alpha.5`. This issue is also related to https://github.com/vmware/clarity/issues/2419

**Comment by BennieMeng** [comment]
yes, thank you , i solve it by install bootstrap@4.0.0-alpha.5.

**Comment by juanmendes** [comment]
I'm also running into this problem when upgrading, I already have `bootstrap@4.0.0-alpha.5` installed but I'm not using the angular cli so I am not sure where to set the `"stylePreprocessorOptions": { "includePaths": ["node_modules"] } ` option. It doesn't seem to be an option for the MiniCssExtract plugin we're using with webpack

```ERROR in ./src/styles/themes/theme-default.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'bootstrap/scss/variables';
^
      File to import not found or unreadable: bootstrap/scss/variables.
      in /Users/jmendes/git/vcd_ui/content/core/node_modules/@clr/ui/src/utils/_dependencies.clarity.scss (line 11, column 1)
    at runLoaders (/Users/jmendes/git/vcd_ui/content/core/node_modules/webpack/lib/NormalModule.js:286:20)
```
