### ISSUE TITLE
[Question] Navigation. Always hide sidenav. Always show hamburger icon.

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#2487]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[ ] enhancement
[V] question
```
### Details
Is there any option to make sidenav always collapsed regardless screen size?
I'm talking about this example:
https://vmware.github.io/clarity/documentation/v0.12/navigation
```html
<clr-main-container>
  <clr-header>

    <div class="header-nav" [clr-nav-level]="1">

    </div>

  </clr-header>
  <div class="content-container">
    <main class="content-area">

    </main>
  </div>
</clr-main-container>
```

### Environment details
* **Angular version:** 6.0.1
* **Clarity version:** 0.12

**Comment by adityarb88** [comment]
@ph55 Please take a look a Vertical Nav https://vmware.github.io/clarity/documentation/v0.12/vertical-nav/basic-structure/charmander

It has a collapsible feature on larger screens.

**Comment by ph55** [comment]
I see that it only collapsible to small icons - not fully hidden.
![image](https://user-images.githubusercontent.com/1386622/43143048-8a4b4478-8f62-11e8-8473-a2e01a182284.png)

Is this what you meant ?

**Comment by mathisscott** [comment]
@ph55 
Yes, that's what @adityarb88 is talking about. Why would you want it to be fully hidden? How would users open it back up if it's hidden?

**Comment by ph55** [comment]
@mathisscott by pressing hamburger icon.
Basically I want the following mobile behavior on large screen by default:

![navlevel1](https://user-images.githubusercontent.com/1386622/43145512-343099b6-8f68-11e8-8377-b7b983c7f39f.gif)

**Comment by mathisscott** [comment]
@ph55 
Then what you want is to customize/extend the responsive nav to all screen widths (not just phone sizes). I _think_ that is possible using CSS. If you'll get a stackblitz started, I may be able to help you reach a solution for your app.

**Comment by GaryHyland** [comment]
This is "probably" what I will look to do with my app, depending on the device choice and further complex page design/development. I will likely set it to hide at 1024 and below as really need the space for any half complex type of form on tablets, etc, esp when keeping fields spaced for decent use with touch,etc.

Can afford to have menu always showing above 1024 ie. std PC browser on desktop screen.
Best of both worlds, easy access to menu options by touch hamburger then menuitem. Though the vertical nav also may be a good fit depending on your menu structure ie if aligns well with just certain key options that you can logically designate icons for then great.

When I get time I was going to dig into css and look to override. Can publish back what I found was need to override the responsive break - I only use responsive nav 1 so don't need to do any right hand menu stuff.

**Comment by GaryHyland** [comment]
link to my issue #2423 asking about same

**Comment by GaryHyland** [comment]
Refer to my issue above where I have added a comment with CSS changes I made to do this.

**Comment by ph55** [comment]
> that is possible using CSS
Thanks @mathisscott, I'll try to figure it out how to override css.
