### ISSUE TITLE
Getting started - Installing with the Angular CLI (Recommended) not working

### ISSUE THREAD

**Issue by carlosvzla** [vmware/clarity#2488]
[ ] bug
[ ] feature request
[x] enhancement

### Expected behavior

Executing `ng add @clr/angular@next` should add clarity to the project

### Actual behavior
`Installing packages for tooling via npm.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @clr/angular@next 

npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist`

### Environment details

* **Angular version:** 6.0.3

* **Clarity version: 0.12.5

* **OS and version:** Windows 10

* **Browser:** [all ]

**Comment by hippee-lee** [comment]
Thanks for reporting this. Its an issue with the docs. The correct command is 
```
ng add @clr/angular
```

**Comment by carlosvzla** [comment]
Yes, i was able to install it without @next. Forgot to mention it was a doc issue. Regards.

**Comment by hippee-lee** [comment]
I pushed a fix for this here: https://github.com/vmware/clarity/commit/17b8fcff827d317ae12867cd7c677841e00f7e80
