### ISSUE TITLE
[Edge] Wizard Navigation shorter than Wizard

### ISSUE THREAD

**Issue by Gesh4o** [vmware/clarity#2493]
Hello guys,

**I am submitting a ...** (check one with "x")

```
[*] bug
[ ] feature request
[ ] enhancement
```

I have a problem when working with wizard pages in **Edge (W10)** - the **navigation side** of the wizard is **shorter** than the **wizard** itself which results into the following:
<img width="1680" alt="screen shot 2018-07-25 at 3 09 07 pm" src="https://user-images.githubusercontent.com/13942085/43200679-f735d9ec-901e-11e8-94b2-dc3a228a3a54.png">

### Steps to reproduce

1. Download the example - https://stackblitz.com/edit/clarity-light-theme-v11-z4ibyz
2. Run it **locally** (since with stackblitz on Edge you may not)
3. **Minimize** the browser **height** until the above error occurs 

### Root cause/fix (friendly suggestion)
There is this selector which controls the height: 
```css
.clr-wizard.wizard-xl .clr-wizard-stepnav-wrapper, .clr-wizard.wizard-xl .modal-content {
    max-height: 75vh
}
```

If I disable the above rule it will look like this:

<img width="1680" alt="screen shot 2018-07-25 at 3 37 06 pm" src="https://user-images.githubusercontent.com/13942085/43201265-ab36f510-9020-11e8-9a0b-70e1531f4e1c.png">

**NOTE**: As it is said this is just a **suggestion** - I assume there must be reason for this selector to exist but I believe that this is a good starting point.

**NOTE**: Keep in mind that the page that is shown in the example overflows but in the domain I work I can reproduce it on almost every wizard and with no matter of page size.

### Environment details

* **Angular version:**
4.x.x 

* **Clarity version:**
0.11.*
* **OS and version:**
Windows 10

* **Browser:** [ Edge  ]

**Comment by mathisscott** [comment]
@Gesh4o 
Thanks for catching this. That CSS is there to prevent the wizard for expanding beyond all sense and reason on large screens. We should guard against this styling on smaller screens.
