### ISSUE TITLE
clrWizard.reset() failing to reset to first page when clrWizardPreventNavigation is used.

### ISSUE THREAD

**Issue by rokobasilisk** [vmware/clarity#2497]
```
[ X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

clrWizard that uses clrWizardPreventNavigation for disabling navigation on loading, should still reset the wizard to page 1 when clrWizard.reset() is run.

### Actual behavior

Currently when clrWizardPreventNavigation is set in the wizard component, the clrWizard.reset() function doesn't reset the wizard to page 1. This is irrespective if the clrWizardPreventNavigation is set to false/true on time of reset().

### Environment details

* **Angular version:** 
5.2.11

* **Clarity version:**
0.11.10

* **OS and version:**
Windows 10

* **Browser:**
Test in Chrome.

My current workaround is to reset onFinish, and on wizard open.

**Comment by mathisscott** [comment]
Hi @rokobasilisk 
Thanks for filing this issue! [Could you create a basic stackblitz that can reproduce the issue](https://stackblitz.com/edit/clarity-light-theme-v11)? That will help us a great deal.
