### ISSUE TITLE
Labeling an ARIA dialog

### ISSUE THREAD

**Issue by mibryamov** [vmware/clarity#2499]
**Select one ...** (check one with "x")

```
[ ] bug
[x] feature request
[x] enhancement
```

### Expected behavior
One very important thing for accessiblity of the dialogs is having a proper label on the dialog that
have role=dialog set. Even though it is not required for a dialog itself to be able to receive focus,
it still needs to be labeled. If a dialog already has a visible title bar, the text inside that bar
can be used to label the dialog itself. The best way to achieve this is by using the aria-labelledby
attribute to the role="dialog" element.
For more details: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role

A label can be specified also by using aria-label:
https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal

Please, back-port the change in Clarity ver. 0.11.x if possible.

### Actual behavior
Currently there is no aria-labelledby or aria-label attribute, and when the dialog is focused, the screen readers read just "dialog", instead of "Edit settings dialog" for example.

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:** 0.11.x

* **OS and version:** all

* **Browser:** all

**Comment by mathisscott** [comment]
Just a note. This one may be trickier than it sounds because it will require the modal to be aware of textual content inside of a content child.

It's not hard. But a little trickier than a one line change.

**Comment by mathisscott** [comment]
Double reported in #2746
