### ISSUE TITLE
More travel vehicle icons

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2502]
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior

It would be nice to have a larger set of travel vehicle icons available to complete the set of existing ones (car, plane, truck). Currently I can think of the following:

- Caravan (trailer)
- Caravan (motor home)
- Trailer
- Boat (like a small rowing boat)
- Ship (like a container vessel and / or a ferry)

* **Clarity version:** 0.12.6

**Comment by mathisscott** [comment]
@lil-kim 
Would this be something we would consider for volume 13?

**Comment by dorthrithil** [comment]
Sure!

Caravan (trailer): https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeKMQHM1L02JCvDfgDuW3NKMk9Hg9O8xIT1UH7nVAEErK_Tr8h

Caravan (motor home): https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHPyJwVCudvJLimm3O1RyDnNWv8UAfikYo_cU_HoSKgt-cmFK0

Trailer: https://cdn2.iconfinder.com/data/icons/vehicles-5/100/721787-_Trailer-512.png
