### ISSUE TITLE
Stepper (New Component) 

### ISSUE THREAD

**Issue by mollyyee** [vmware/clarity#2503]
### Description

A stepper structures multi-step processes into 2 or more expanding panels that break up complex workflows. 

### States

**First Step**

By default, open up the first step so that users can start input data to finish the task. The step title will include a number with the step name, starting with 1. “NEXT” button should always be enabled as users tend to not click on a disabled button. If we require users input before moving forward, we can show an error message right above the “NEXT” button. Hide the caret on the left for the future step since users are not supposed to edit those steps yet.

![first step](https://user-images.githubusercontent.com/16811152/43412315-b7429e80-93e1-11e8-857e-e9b9cb419297.png)

**Middle Step**

When one or more steps are completed, use a green indicator at the beginning of the step title section. Mark the next step as the active step and open the input section.

![group 7](https://user-images.githubusercontent.com/16811152/43412405-f70959e6-93e1-11e8-9b5c-2e07870a6f10.png)

**Last Step**

When the users enter the last step of the stepper workflow, use the primary action button with a clear action label to indicate that is the last step of the workflow. 

![group 9](https://user-images.githubusercontent.com/16811152/43412428-0aba0f58-93e2-11e8-8f64-24248ab2a065.png)

**Error State**

When a server side error comes back, show the red indicator in the step with the appropriate error message.

![error](https://user-images.githubusercontent.com/16811152/43412451-2407ae20-93e2-11e8-87db-31688498aa9e.png)

**Text Wrapping State**

When the step name, description, or summary is too long to fit in one line, the text should wrap and the step title section should grow larger to accomodate the additional text. Within one stepper, the width of the step name should be the same so the content will align. Keep a minimum of 36px padding between the step name and the description/summary.

![text wrapping](https://user-images.githubusercontent.com/16811152/43412482-3c270820-93e2-11e8-9de2-9b7b21cb0f50.png)

**Dark Theme- First Step**
![dt -1](https://user-images.githubusercontent.com/16811152/43412552-75a3ed0c-93e2-11e8-9c11-5fc5e0836273.png)

**Dark Theme- Middle Step**
![dt 2](https://user-images.githubusercontent.com/16811152/43412556-784bc2b4-93e2-11e8-8b6b-2b8e318f8ed0.png)

**Dark Theme- Final Step**
![dt - 3](https://user-images.githubusercontent.com/16811152/43412562-7a91e49a-93e2-11e8-8e10-3408ccd7509f.png)

**Dark Theme- Error State**
![dt- error](https://user-images.githubusercontent.com/16811152/43412571-812eb8a0-93e2-11e8-9a95-bdd14f6c7d95.png)

[Light Theme Spec in inVision
](https://vmware.invisionapp.com/share/6ALKZEM2HE9#/309492459_Stepper_Design_Specification)

[Dark Theme Spec in inVision
](https://vmware.invisionapp.com/d/main#/console/12350241/309492483/preview)
### Documentation

in [inVision](https://vmware.invisionapp.com/share/6ALKZEM2HE9#/311590473_Documentation)

**Design Guidelines**

Each panel representing each step will contain a title and a description that describes the entire workflow at a glance. After completing each step, collapsed panels then replace step descriptions with summaries describing what the user has accomplished. 

Here is when you might want to use a stepper over normal forms or wizards: 
•  Complex and long work processes that may not fit in one viewport
•  When the user would need to see the forms in-line with the rest of the page content
•  If users need more detail than step titles to understand the process.
•  If summaries of previous steps are helpful in informing next steps. 

Steppers are composed of two sections- the stepper header and input section. 

**Stepper Header Section**
The step title section has three states: completed, active, to-do. When a step is in its active state, its title section will be highlighted and its input section will be visible for users to interact. As users complete steps, the steps are marked with a green bar to the left, and a summary of users’ input will replace the description. 

**Input Section** 
The input section has two elements: the form and the buttons. The form is used to collect input from users to finish the step. The buttons section will allow the users to proceed to the next step or finish the workflow. To go back to a previous step, users need to click on the step title of one of the previous steps. That step will become the active step with its input section visible for editing.

**Do** use clear copy in the final CTA to best represent the action that users are taking in completing the stepper. 

![group 3](https://user-images.githubusercontent.com/16811152/43412826-3e8479f8-93e3-11e8-96a4-d1cd8aabdbcb.png)

**Don't** use ambiguous a non-action oriented description that does not specify what users are accomplishing. 

![group 4](https://user-images.githubusercontent.com/16811152/43412833-41368dbc-93e3-11e8-88ec-c79f502976df.png)

**Final CTA**

For the button label in the final CTA, we recommend that the copy also describe an immediate outcome of completing a stepper. If the workflow will require more time to process after the stepper is complete, then FINISH or other non-specific terminology may work better. 

Though we recommend action-oriented button labels, there are use cases where labels like DONE work well. If the user is viewing read-only information, we recommend using labels like DONE.

**Comment by pumano** [comment]
It will be nice to have add support for mobile screens out of the box, because wizards not support mobile screens properly.

**Comment by sdurnov** [comment]
Is it possible to make it "lighter"? Because right now it looks too heavy because of too much borders imo.

**Comment by sdurnov** [comment]
Also, is it gonna be only vertical?

**Comment by Vaishak** [comment]
is there going to be a horizontal implementation of this?

**Comment by gnomeontherun** [comment]
@Vaishak see #3902 but in short we don't have plans to make a horizontal version.
