### ISSUE TITLE
Volume 13 icons

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#2504]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[x] enhancement
```

**Comment by d-m-s** [comment]
a "paste" or "copy-from-clipboard" icon would be a welcome addition to clarity's icons.

please find in the following a suggestion, derived from the "copy-to-clipboard"
![copy-from-clipboard](https://user-images.githubusercontent.com/311619/43842685-2ab931b2-9b26-11e8-9bdd-74f5ed8a810f.png)

[copy-from-clipboard.zip](https://github.com/vmware/clarity/files/2270562/copy-from-clipboard.zip)
(zip file contains the svg)

**Comment by RobArbor** [comment]
Not sure where to put icon requests: 
- "microphone" / "microphone-mute" icon for in the media section.

**Comment by lil-kim** [comment]
Hi @d-m-s 
![image](https://user-images.githubusercontent.com/23196444/44104005-931d8322-9fa2-11e8-9c60-b7862a4407cb.png)
Coincidentally, there is a "paste" icon in vol. 12 icons - soon to be published. Would this icon work for your needs?

**Comment by lil-kim** [comment]
@RobArbor 
Good suggestion. Consider it added.

**Comment by TrifonovSergey** [comment]
Add a "filter off" icon, please.

**Comment by lil-kim** [comment]
**Comprehensive icon list for vol 13**
(...so far. More may be added)
1. Caravan (trailer) #2502
2. Caravan (motor home) #2502
3. Trailer #2502
4. Boat (like a small rowing boat) #2502
5. Ship (like a container vessel and / or a ferry) #2502
6. Gauge chart icon #2568
7. Radar chart Icon #2568
8. microphone
9. microphone-mute"
10. filter off

**Comment by whizkidwwe1217** [comment]
@lil-kim May I request for a language or translation icon? The talk-bubble icon is too generic and it's kinda used  for chat & messaging. I'm also not sure if the world icon is also appropriate. I think it's more appropriate if there are asian-english glyphs (which pretty much common) or something that doesn't have a bubble.
![image](https://user-images.githubusercontent.com/1977391/44609235-6c5d9d00-a829-11e8-88a3-a46c61fa25df.png)
![image](https://user-images.githubusercontent.com/1977391/44609385-032a5980-a82a-11e8-8e06-6bc9af18cd23.png)
![image](https://user-images.githubusercontent.com/1977391/44609521-906dae00-a82a-11e8-8c1a-717fd9cc3f91.png)

**Comment by lil-kim** [comment]
@whizkidwwe1217 
Seems legit. Added it to the list.

**Comment by artemisclyde** [comment]
An icon for zip files (the usual file icon plus the zip on it) would be great

**Comment by amellnik** [comment]
A few suggestions:

* A tree
* A recycling symbol 
* A bicycle (in travel)

**Comment by Stela-Stamenkova** [comment]
Hello everyone, 
I am attaching the ready icons.
[Export-R1.zip](https://github.com/vmware/clarity/files/2438216/Export-R1.zip)

**Comment by lil-kim** [comment]
@amellnik Sorry, we received your last three requests (snowflake, ice cube, a fish) after our list for vol 13 was already in progress. It will be included in the following release of icons (vol. 14). The ice cube request - whether you mean a frozen block of water or the former rapper/actor :-) - is problematic. I don't think it will be distinguishable from the block icon already in the Clarity library. Would this icon work for your use case?
![image](https://user-images.githubusercontent.com/23196444/46370724-ff210100-c64b-11e8-8fcd-41a3b8fa8040.png)

**Comment by gnomeontherun** [comment]
These have been merged and released
