### ISSUE TITLE
Documentation on Grid section needs to be corrected

### ISSUE THREAD

**Issue by vinaykhegde** [vmware/clarity#2506]
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
Documentation on Grid has a small change, like in Horizontal Alignment in Rows, **Space Around** has an example with clr-justify-content-between and **Space Between** has an example with clr-justify-content-around.

### Environment details

* **Angular version:** 6

* **Clarity version:** 0.12

* **OS and version:** windows 10

https://vmware.github.io/clarity/documentation/v0.12/grid

![space-around](https://user-images.githubusercontent.com/34911874/43454138-ba00b230-94d9-11e8-9fe5-adf25d8741d1.jpg)
![space-between](https://user-images.githubusercontent.com/34911874/43454143-bf91b6f4-94d9-11e8-94c4-0a3399b635bc.jpg)

**Comment by gnomeontherun** [comment]
Closed via #2507
