### ISSUE TITLE
Vertical nav doesn't expand properly on Chrome 67+ (on mac)

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#2509]
**Select one ...** (check one with "x")

```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Expanding last group should show all sub-items

### Actual behavior

Only the first 1.5 items are shown when expanding the last menu group

### Reproduction of behavior

https://stackblitz.com/edit/menu-bug

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
  
  
  
  

### Environment details

* **Angular version:** 4.x.x

Angular 6.0

* **Clarity version:**

Clarity 0.12.6

* **OS and version:**

Mac High Sierra 10.16.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 67+

**Comment by hippee-lee** [comment]
note, if the `clr-vertical-nav-group` and its children is the last item of the navigation, this issue occurs. but if there is something after it the nav group expands as expected. See here and add, remove the last `clrVerticalNavLink` to replicate.

**Comment by mathisscott** [comment]
@rbirkgit 
Could you try this on latest Chrome to see if it's still an issue? I can't replicate it on Chrome 68...

**Comment by rbirkgit** [comment]
Kara is reporting the issue is still there on her Chrome 68 on Mac.

**Comment by hippee-lee** [comment]
@rbirkgit  - I did a bit of investigation last week when discussing with Shijir. 
I forked your stackblitz to document those findings.

**Comment by Shijir** [comment]
Seems like the following snippet would solve the issue. 
```
clr-vertical-nav-group {
   will-change: transform;
}
```

Also, tried this one too. It works as well:
```
clr-vertical-nav-group {
    transform: translateZ(0);
}
```

**Comment by gnomeontherun** [comment]
Thanks to @nmarkapuram-vmw we've identified that this is no longer an issue on latest Chrome. Seems like there might have been an issue in Chrome that was resolved. Closing as no longer an issue.
