### ISSUE TITLE
Modal cropped when inside StackView [Chrome]

### ISSUE THREAD

**Issue by kars7e** [vmware/clarity#251]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Using StackView, each clr-stack-content element has a subelement in form of a button which opens modal. This modal should display properly centered, with backdrop covering entire page.

### Actual behavior
It behaves correctly in Firefox, however in Chrome/Safari modal window and backdrop seem to be cropped to the size of StackView. see plnkr below.
https://plnkr.co/edit/vIP7rV68k5m2niitWcOy?p=preview

### Reproduction of behavior
https://plnkr.co/edit/vIP7rV68k5m2niitWcOy?p=preview

### Environment details

* **Angular version:** 2.2.4

* **Clarity version:** 0.7.4

* **OS and version:** macOS 10.12

* **Browser:** 
[ Chrome 54 | Safari 10.1 ] - Broken
[ Firefox 50 ] - Working fine

**Comment by adityarb88** [comment]
Hi @kars7e. Thanks for reporting this. We already have a `-webkit-transform: translateZ(0)` on our `.main-container`. I believe I added that while implementing responsive navigation as there was an issue with `position: fixed` at that time too. 

I am not sure what is causing this again now inside of stack view. This is an issue with webkit browsers and I tried a couple of things that some users mentioned on Stackoverflow:
http://stackoverflow.com/questions/15152470/chrome-rendering-issue-fixed-position-anchor-with-ul-in-body
http://stackoverflow.com/questions/17068361/chrome-positionfixed-inside-positionabsolute-breaking-with-iframe-video

but that doesn't seem to work. I will try to search for other alternatives and see if this can be fixed. Thanks!

**Comment by Wallabeng** [comment]
Maybe something like that is needed.
https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/modal/modal-stack.ts

**Comment by rdvojmoc** [comment]
Is there any solution for this bug that we can use until it's fixed?

**Comment by gnomeontherun** [comment]
I don't see the behavior on v4 website listed above, and I think if you put the modal outside of the stack view element it would be better. It is also possible to use the Core modal instead which might address the issue. Since the demos are beyond our supported versions, I'm going to close this issue as stale and if there is an updated reproduction of the issue we'd welcome a fresh demo with a recent version of Clarity on a new issue..
