### ISSUE TITLE
Sample / Reference Layouts

### ISSUE THREAD

**Issue by ronnyek** [vmware/clarity#2512]
**Select one ...** (check one with "x")

```
[ ] bug
[x] feature request
[ ] enhancement
```

General navigation and showcase of the tools themselves seem to be more than represented in documentation etc.... but find myself struggling sometimes trying to build the equivalent of a records detail page. e.g. Looking at an order, or looking at a virtual machines details. 

From UI guidelines, are all of those sort of interactions destined to become a master detail view, with details being on the right, and never a dedicated page for the details? Is navigation via breadcrumbs recommended or do  you have some other recommended methods. 

I generally really like how clean and performant clarity is today, and want to stick with that... but feel like other than a couple diagrams or icons or whatever at: https://vmware.github.io/clarity/documentation/v0.12/app-layout

It seems like there are some guidelines, but generally starting from scratch 

It'd just be nice to have some super generic templates to look at and gain inspiration from.

**Comment by mathisscott** [comment]
Hi @ronnyek 
We've been wanting to add examples of Clarity in use to the documentation for a while now. It has never bubbled up in priority, however. Eventually, we will have that on the site.

As for what patterns to use for applications related to virtual machines, etc., that should be something your team's UX designer should recommend. Clarity is a design system that is realized in a library of UI components. As such, telling people exactly how their apps should be built in all cases is outside of our charter.

Thanks for reaching out. I was unable to find our existing issue to add sample app designs to the documentation. I will leave this issue open until I do.

**Comment by mathisscott** [comment]
Found it: #2212

**Comment by ronnyek** [comment]
Apparently I didn't search well enough. Apologies and Thanks!
