### ISSUE TITLE
Blur effect in popups borders

### ISSUE THREAD

**Issue by d-go** [vmware/clarity#2517]
Sometimes there is a blur effect in borders for popups due to decimal values in `translateX` and `translateY`

https://github.com/vmware/clarity/blob/28187afbbf375e823dd1932cca4d6e6841e66075/src/clr-angular/popover/common/popover.ts#L240

A simple `Math.round()` fixes the issue:
```
this.element.style.transform = `translateX(${Math.round(leftDiff)}px) translateY(${Math.round(topDiff)}px)`;}
```

With decimal values:
![image](https://user-images.githubusercontent.com/19176705/43672441-8ef1f666-9773-11e8-9f88-43b114205ac6.png)

Without decimal values:
![image](https://user-images.githubusercontent.com/19176705/43672450-c49d8d84-9773-11e8-89cf-97fbbd80f43e.png)

**Comment by d-go** [comment]
For sure, count on me for that 



-------- Original message --------From: Jeremy Wilken <notifications@github.com> Date: 8/8/18  10:22  (GMT-06:00) To: vmware/clarity <clarity@noreply.github.com> Cc: Diego Hernández Reyes <diego09hernandez@gmail.com>, Author <author@noreply.github.com> Subject: Re: [vmware/clarity] Blur effect in popups borders (#2517) 
Thanks for the report, would you be willing to submit a PR for this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vmware/clarity","title":"vmware/clarity","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/vmware/clarity"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gnomeontherun in #2517: Thanks for the report, would you be willing to submit a PR for this?"}],"action":{"name":"View Issue","url":"https://github.com/vmware/clarity/issues/2517#issuecomment-411445099"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/vmware/clarity/issues/2517#issuecomment-411445099",
"url": "https://github.com/vmware/clarity/issues/2517#issuecomment-411445099",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [vmware/clarity] Blur effect in popups borders (#2517)",
"sections": [
{
"text": "",
"activityTitle": "**Jeremy Wilken**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@gnomeontherun",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"vmware/clarity\",\n\"issueId\": 2517,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"vmware/clarity\",\n\"issueId\": 2517\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/vmware/clarity/issues/2517#issuecomment-411445099"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 364599627\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by d-go** [comment]
Do I have write permissions? I can't push/publish my branch neither cloning by HTTPS nor SSH

**Comment by mathisscott** [comment]
@d-go 
You'll want to fork the Clarity repo. Then create a branch in your fork to work on. Then push that branch to your forked Github repo and do a PR to master from there.

If you're not familiar with this, here are [a couple of good docs](https://help.github.com/articles/fork-a-repo/) [on how it all works](https://help.github.com/articles/fork-a-repo/).

**Comment by d-go** [comment]
Got it, no problem
-------- Original message --------From: Scott Mathis <notifications@github.com> Date: 8/9/18  09:51  (GMT-06:00) To: vmware/clarity <clarity@noreply.github.com> Cc: Diego Hernández Reyes <diego09hernandez@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [vmware/clarity] Blur effect in popups borders (#2517) 
@d-go

You'll want to fork the Clarity repo. Then create a branch in your fork to work on. Then push that branch to your forked Github repo and do a PR to master from there.
If you're not familiar with this, here are a couple of good docs on how it all works.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/vmware/clarity","title":"vmware/clarity","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/vmware/clarity"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mathisscott in #2517: @d-go \r\nYou'll want to fork the Clarity repo. Then create a branch in your fork to work on. Then push that branch to your forked Github repo and do a PR to master from there.\r\n\r\nIf you're not familiar with this, here are [a couple of good docs](https://help.github.com/articles/fork-a-repo/) [on how it all works](https://help.github.com/articles/fork-a-repo/)."}],"action":{"name":"View Issue","url":"https://github.com/vmware/clarity/issues/2517#issuecomment-411785184"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/vmware/clarity/issues/2517#issuecomment-411785184",
"url": "https://github.com/vmware/clarity/issues/2517#issuecomment-411785184",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [vmware/clarity] Blur effect in popups borders (#2517)",
"sections": [
{
"text": "",
"activityTitle": "**Scott Mathis**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@mathisscott",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"vmware/clarity\",\n\"issueId\": 2517,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"vmware/clarity\",\n\"issueId\": 2517\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/vmware/clarity/issues/2517#issuecomment-411785184"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 364599627\n}"
}
],
"themeColor": "26292E"
}
]
