### ISSUE TITLE
Development proposal Accordion component

### ISSUE THREAD

**Issue by 19Arne75** [vmware/clarity#2522]
## Summary

Implementation of accordion component to expand/collapse projected content.

Proposed accessibility as ARIA outlined in:
https://www.w3.org/TR/wai-aria-practices/#accordion
https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

Information below is only prototype sketch and not following clarity coding/naming guidance yet 100%.

## Examples

Clarity design: Accordion Component (new) #2452
Prototype: https://stackblitz.com/edit/accordion-v012-p5wm52

## API

Inputs
[Callout] - callout choices with 4 default types
```
type        icon shape          class

info        info-standard       is-info
warning     warning-standard    is-warning
error       error-standard      is-error
success     success-standad     is-success
```

[Icon] - Override default icon with any valid clr-icon shape

Example 1:
```
<accordion-container [(openChange)]>
<accordion-header [Callout]="'warning'">
{{accordion.header}}</accordion-header>
<accordion-content>{{accordion.content}}</accordion-content>
</accordion-container>
```

Example 2: Callout error with custom icon
```
<accordion-container [(openChange)]>
<accordion-header
 [Callout]="'info'"
 [Icon]="'help-info'">{{accordion.header}}</accordion-header>
<accordion-content>{{accordion.content}}</accordion-content>
</accordion-container>
```

Output [(openChange)] - if practical possible, two-way binding of current state open/close

## Implementation Plan

New components, service, module
```
accordion/
- accordion-container.ts
- accordion-header.ts
- accordion-content.ts
- accordion.scss
- accordion.module.ts
- /providers
  - container.service.ts
```

Communication between components goes through container.service ( provider is accordion-container )
- accordion-header (click) -> toggle accordion.service.open

Using clr-grid for layout.

Own module for future enchantments.

## Conclusion

Expecting about 3 month development before initial release.

Need guidance about clarity sccs for proper styling, screen readers, git skills not up to date either.
If i'm allowed to contribute I appreciate all info that a newbie can need, thanks.

**Comment by gnomeontherun** [comment]
Thanks for the initial proposal. There are a lot of details to be ironed out here. The demos you provided don't include the nuances for all of the design that we need to implement. 

Without going into great detail, I suggest that you spend some time trying to reverse engineer some of our other components. Look at how we've built things like button groups, dropdowns, and so forth. This might help you catch some of the bigger items, and better match our typical patterns.

We are currently at capacity for what we can handle on our end, so until this comes up in priority we can't spend a lot of time trying to work with you on this at the moment. However, I encourage you to spend more time learning Angular and our patterns and update this ticket with more details to help us out.
