### ISSUE TITLE
Datagrid. Hide all columns button.

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#2528]
```
[X] enhancement
```

https://vmware.github.io/clarity/documentation/v0.12/datagrid/hide-show

Please add button to hide all columns.

Usually the UX of selecting columns are one of these:
* Hide not needed columns.
* Hide all - select few column you need.

Very useful in case of large tables with many columns.
![image](https://user-images.githubusercontent.com/1386622/43889711-931e4614-9bcd-11e8-88c6-03f3973f47b9.png)

As a suggestion, 'SELECT ALL'/'HIDE ALL' could just replace each one on click.

**Comment by youdz** [comment]
I understand the use case and I agree this is a valid request.

We're going to hit an issue however, because the columns update in real time as you select/unselect them, and the datagrid currently has a technical constraint that prevents it from having 0 columns (which is a non-existing use case). So "Hide all" would create a problem for that.

Either we have to make it so that the datagrid gracefully displays nothing but retains its space when it has 0 columns, or we need to change the real-time behavior to a delayed one. Either way, this is surprisingly more work than I thought it would be when I first read it.

**Comment by youdz** [comment]
A couple more thoughts on this, I posted too quickly. 😊 

If you have that many columns, I believe the better UX is to initialize the datagrid by showing only a few critical ones, and letting the user add the ones they need from there. In your example, I don't know your userbase but something like ID/Franchise/First name/Last name seems like a good initial state. Maybe Status is more universally needed than Franchise? Anyway, the typical columns everyone uses should be determined by your specific app.

But it doesn't change the fact a mass-hide would still be needed: even if you were to go for the behavior I just described, a user could click "Select All" by mistake. It would feel **terrible** not to be able to undo that efficiently and having to go and manually uncheck everything.

I'll let @reddolan or @mathisscott confirm this is a valid request from a UX perspective, and they can mark the issue as "Accepted" at that point.

**Comment by mathisscott** [comment]
I agree with @youdz on this one.

Wouldn't it be a better experience to do research, identify the 3-4 most relevant columns, display those, and then allow users to add additional columns as needed?

Even if we had a "Select and Hide All" columns feature, it's still putting the onus on end users to go in, hide all the columns, and then select the few they want to see when there are probably overlaps in what they want to see in these datagrids.

Wouldn't it be better UX to save them those steps?

**Comment by ph55** [comment]
I agree that displaying most relevant columns would be good solution for one use case.
But this doesn't cover one @youdz mentioned:

> But it doesn't change the fact a mass-hide would still be needed: even if you were to go for the behavior I just described, a user could click "Select All" by mistake. It would feel terrible not to be able to undo that efficiently and having to go and manually uncheck everything.

**Comment by youdz** [comment]
I just talked to @mathisscott , there was a slight misunderstanding. We do want to make the "Select all" button become "Unselect all" if all the columns are already selected.
Options to handle the constraint of always keeping at least one column visible are:
- Delay the change until "Ok" is clicked, and disable the "Ok" button until at least one column is selected. _But real-time behavior is really nice for users customizing their datagrid._
- Make "Unselect all" always keep the first column checked, and keep the current behavior of preventing full uncheck. That was Scott's suggestion and I like it. 👍 

### I insist that this should not be considered a "good enough" solution to datagrids with many columns, you should definitely initialize the datagrid by showing only a few critical columns, and let the user add the ones they need.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
