### ISSUE TITLE
[Proposal]Update of hover and cursor styles for header nav buttons if disabled

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#2533]
## Summary

Describe the change or feature in detail. Try to answer the following questions.

* What is the change?
Modify the header-nav-appearance mixin to change the opacity if only the button is enabled on hover.

* What is a use case for this change?
Sometimes, a header nav button could be disabled.

* Why should it go in Clarity?
 The hover appearance and cursor style of a disabled nav button may make the user confused.

* Does this change impact existing behaviors? If so how?
No.

* If this change introduces a new behavior, is this behavior accessible?
N/A

## Examples

N/A

## API

N/A

## Implementation Plan

* What parts of the code are affected?
The header-nav-appearance mixin in src/clr-angular/layout/nav/_header.clarity.scss

* Will you introduce new services, components or directives?
No.

* Can you describe the basic flow of information between classes?
N/A

* Does this introduce asynchronous behaviors?
N/A

* Will you need to refactor existing Clarity code?
N/A

* Will reasonable performance require optimizations?
N/A

* Will it need to access native elements (and be incompatible with server-side rendering)?
N/A

## Conclusion

It's only several lines of CSS modification and can be committed in no time.

PS:
_what about hover styles in src/clr-angular/button/_buttons.clarity.scss and other parts? Those look like complicated._

**Comment by mathisscott** [comment]
@KingMario 
What is the use case for disabling a nav header button?

**Comment by KingMario** [comment]
@mathisscott 
Anything I need to provide?

**Comment by mathisscott** [comment]
Hi @KingMario 
No, I get it. Thanks for clarifying.
