### ISSUE TITLE
Increase the contrast of cards

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#254]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Cards should appear well even on different screens. This is a ticket to explore different designs and to see if this is actually a problem for our users.

### Actual behavior
Right now, they might look "washed" out on screens with different colors ratios.

### Reproduction of behavior
Look at cards on our typical background (#fafafa) on a TV screen/projector for example.

**Comment by yenmade** [comment]
In tackling this issue, we’ve done extensive explorations around ways in which we can improve the contrast of cards against different screens. Some scenarios we looked at are cards on landing pages, situations where many cards appear alongside each other (dashboards), and when cards appear alongside other components such as a datagrid. **We are not optimizing for displays such as projectors and televisions**, although those have been considered.

The design below takes into account the visual integrity of Clarity as a whole and aims to minimize the chances for breaking changes. During implementation, we will continue to test on different screens and refine this solution if necessary.

![card-contrast](https://cloud.githubusercontent.com/assets/22527471/22162225/9baa61f2-df02-11e6-8017-383452b023a1.png)

**Comment by jeeyun** [comment]
@yenmade here's a plnkr link with the proposed spec: https://embed.plnkr.co/09JRbTneFqB1Wbb7rvYa/

Let me know if this looks good or if you think we should make additional adjustments.
