### ISSUE TITLE
Keyboard Interaction for a dropdown menu component 

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#2543]
**Select one ...** (check one with "x")

```
[ ] bug
[X] feature request
[X] enhancement
```

### Expected behavior

Keyboard Interaction for the dropdown menu with arrow keys
https://www.w3.org/TR/wai-aria-practices/#menubutton
https://www.w3.org/TR/wai-aria-practices/#menu

I would like to request the dropdown menu to support arrow key navigation between the dropdown menu items. Currently it supports TAB.

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:0.11.x

* **OS and version:ALL

* **Browser:** all

**Comment by gnomeontherun** [comment]
Closed by #3283
