### ISSUE TITLE
Dark theme card list-group not styled.

### ISSUE THREAD

**Issue by RobArbor** [vmware/clarity#2544]
**Select one ...** (check one with "x")

```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The card list group should match the dark theme. 

### Actual behavior

![theme-issue](https://user-images.githubusercontent.com/18066581/44080341-0869e5f4-9fac-11e8-9cd0-0a7713d6c880.png)

### Reproduction of behavior

https://stackblitz.com/edit/clarity-dark-theme-v012-sy9yhu

### Environment details

* **Angular version:** 6.0.4

* **Clarity version:** 0.12.8

* **OS and version:** Windows 10 

* **Browser:** [all]

**Comment by lil-kim** [comment]
Here are the color specs for styling to dark theme:
background: #22343C
Border: #0F171C

Should look like this:
![image](https://user-images.githubusercontent.com/23196444/44679067-c6f42600-a9ee-11e8-9754-f127808e58e8.png)
(Approved by Red and Scott)

**Comment by gnomeontherun** [comment]
Fixed by #2620
