### ISSUE TITLE
angular reactive forms - Validators on checkbox only work once

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#2548]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Binding e.g. Validators.required to a checkbox should update validity state accordingly

### Actual behavior

The control state updates only once. E.g. if the checkbox was required and unchecked, the state is invalid. Checking it puts the state to valid. ]
BUT
any further actions wont affect the control state. 

Here is a stackblitz repo which reproduces the behaviour

https://stackblitz.com/edit/clarity-base-qgt9kt

### Environment details

* **Angular version:** 6.x.x

* **Clarity version:** 0.12.8

**Comment by gnomeontherun** [comment]
This is actually Angular behavior and not Clarity. Being 'required' means it has a value set, which happens the first time you click it. See this https://stackblitz.com/edit/clarity-base-4tfj4h?file=app/app.component.html example where there is no Clarity styling for the checkbox. Also see https://stackoverflow.com/questions/35462316/requiring-a-checkbox-to-be-checked and you probably want to check that the `checkbox.value === true` instead.

Closing as not an issue.

**Comment by aavelyn** [comment]
@gnomeontherun so basically it means that since false is also a value, the state doesn't change.
Thanks for the clarification!
