### ISSUE TITLE
Datagrid / Table sticky headers when scrolling

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#2549]
**Select one ...** (check one with "x")

```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Possibility to turn on/off sticky header (by default is off) It's very good for long tables / datagrids

### Actual behavior
Not possible? 

### Environment details

* **Angular version:** 6.x.x

* **Clarity version:** 0.12.8

* **OS and version:** Windows 10 / MacOS High Sierra

* **Browser:** all

**Comment by mathisscott** [comment]
@pumano 
If you set the height of the datagrid, I think you will see the behavior you're expecting.

**Comment by pumano** [comment]
@mathisscott its works perfectly, would be good if you can add that solution to tables / datagrid documentation. Thanks!

**Comment by Akay7** [comment]
@mathisscott 
Is it a chance to have horizontal and vertical scrollbars and sticky headers at the same time?

**Comment by mathisscott** [comment]
@Akay7 
I believe that will be implemented with the work @hippee-lee is doing on #1586
