### ISSUE TITLE
Datagrid - Unable to close hide/show after a filler is opened on a column

### ISSUE THREAD

**Issue by amithvns** [vmware/clarity#2550]
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior
Unable to close a column hide/show popout after opening filler popout on any column in the Datagrid

### Reproduction of behavior

https://clarity-light-theme-v012-nehi4r.stackblitz.io

### Environment details

* **Angular version:** 6.x.x

* **Clarity version:** 0.12

* **OS and version:** 

* **Browser:** Chrome 61

**Comment by gnomeontherun** [comment]
It seems to happen only if you start by opening a filter box, leave it open and open the column toggler box (which seems to take two clicks), then its not possible to close the column toggler.

**Comment by amithvns** [comment]
Hi @gnomeontherun, Can this issue be added to your scope for the next upcoming releases?

**Comment by gnomeontherun** [comment]
We have it in our backlog to address when time allows, but we also have plans to refactor the whole popover experience to fix this and a number of other issues as well.

**Comment by amithvns** [comment]
@gnomeontherun, Thanks for the update.

**Comment by gnomeontherun** [comment]
This is fixed with the #2923 implementation, closing as fixed.
