### ISSUE TITLE
Alert Service

### ISSUE THREAD

**Issue by koolkav1** [vmware/clarity#2553]
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Alert Service

I would love to have a Clarity level alert service so I can programmatically create new alerts as object classes. Similar to Material's Snackbar https://material.angular.io/components/snack-bar/overview
https://stackoverflow.com/questions/48693463/dynamic-clarity-app-level-alerts has not solved the problem.
Thanks,
Kav

**Comment by mathisscott** [comment]
Hi @koolkav1 
I think we already have an issue open for this. Could you take a look at #365 ?

I'm closing this as a duplicate for now.
