### ISSUE TITLE
Tooltip is not displayed fully if its on the field inside a dialog near the dialog header.

### ISSUE THREAD

**Issue by snagar78** [vmware/clarity#256]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Tooltip should be shown over the top.

### Actual behavior
https://plnkr.co/edit/fJzlogPxqhDhR97zAiaP?p=preview
Click open dialog button and focus on the first field and tooltip is not displayed properly.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@snagar78 thanks for submitting an issue here. This seems to be the same issue being discussed in issue #37, right?

**Comment by snagar78** [comment]
@jaffoneh Yes this looks similar and looking at the discussion i think i would just change tooltip orientation to bottom :)

**Comment by jaffoneh** [comment]
@snagar78 thanks. I'll close this one as duplicate since the other issue is mentioned here. Feel free to add to that discussion there with opinions and/or feedback!
