### ISSUE TITLE
How to hide radio button column from datagrid for single row selection

### ISSUE THREAD

**Issue by VaibhavTekade** [vmware/clarity#2560]
**Select one ...** (check one with "x")

```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Component clr-datagrid
- Configurable grid to hide first radio button column 

- First column should be configurable, don't want radio button in grid for single row selection feature
### Actual behavior
- Trying Clarity datagrid and want to use single row selection feature. 
- Once I set [(clrDgSingleSelected)]="xxx" [clDgRowSelection]="true" a radio button is added in grid first column .

### Reproduction of behavior

https://stackblitz.com/edit/clarity-light-theme-v11-egtphq?file=app%2Fapp.component.html

### Environment details

* **Angular version:** 4.x.x

* **Clarity version:**

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
The radio buttons being displayed for any datagrid with select capabilities is a design choice.

For accessibility reasons, we can't simply rely on background color to indicate that a row is selected or not. It also is important to make sure the datagrid **appears** selectable to the user from the beginning: without the radio buttons, the only way to see that a datagrid is selectable is by hovering over rows and identifying that the cursor becomes a pointer. And even at that point, the user wouldn't know if they could select only one or multiple rows.

So our hard recommendation is to always keep the checkboxes or radio buttons of a selectable datagrid visible.
