### ISSUE TITLE
Datagrid Expandable Row - expanding last row does not display content in clear manner

### ISSUE THREAD

**Issue by srikanthps** [vmware/clarity#2562]
## Describe the bug

When using expandable rows for datagrid, when last row of data grid is expanded, the expanded content
appears below the row - and is not obvious immediately to user -  only feedback to user is appearance of 
scroll bar - but it is very easy to miss.

It is causing usability issue. 

## How to reproduce

Stackblitz: https://clarity-expandable-row-issue-abcdefg.stackblitz.io

1.  Go to stack blitz app -  https://clarity-expandable-row-issue-abcdefg.stackblitz.io
2.  Click on > icon in the last row for 'User 9'
3.  Observe that expanded row details is not displayed in visible area of screen.

## Expected behavior
The last row displays expanded data clearly.
This happens in example show in  https://vmware.github.io/clarity/documentation/v0.12/datagrid/expandable-rows.

## Versions
**App**

* Angular: 6
* Node: 8.9
* Clarity: 0.12.9

**Device:**

* Type: PC Windows
* OS: Windows
* Browser : Chrome

## Additional notes

It seems clarity is adding a height value to `<clr-datagrid>` element
https://github.com/vmware/clarity/blob/28187afbbf375e823dd1932cca4d6e6841e66075/src/clr-angular/data/datagrid/render/main-renderer.ts#L111

If in browser developer tools, I remove the height attribute, the expandable row works as expected.  It uses the available space in screen.

**Comment by youdz** [comment]
The height set on the datagrid is here to keep a consistent height across pages, to avoid the rest of the app's content jumping up and down every time you move from one datagrid page to another.

I do agree that there is a slight discoverability/feedback issue when expanding the last row though. I'll tag this issue for one of our designers because I can't really formulate a plan until we have an idea of what we want to do from a UX perspective.

**Comment by colinreedmiller** [comment]
Given the parameters of this issue the apparent solution is for the contents of the table (on click) to move north so the entire expanded bottom row is visible. This requires the top row(s) to become invisible when they are repositioned behind the (sticky) table header. This solution is technically challenging and has many corner cases. This requires detecting the content and calculating the expanded rows height dynamically, and the UX of the entire table content moving is undesirable. This complex state calculation dwarfs the value of the feature. 

See: https://github.com/vmware/clarity/issues/2005 Master Detail View
