### ISSUE TITLE
Grid's loading spinner is showing "Loading..." text when grid is placed inside stack view

### ISSUE THREAD

**Issue by ttsvetko** [vmware/clarity#2565]
## Describe the bug

Grid's loading spinner shows the "Loading..." label when grid is placed inside a Stack View component.

## How to reproduce
https://stackblitz.com/edit/clarity-dark-theme-v012-uqy1rp?file=src%2Fapp%2Fapp.component.html 

1.  Go to the link above
2.  Expand the stack view in order to see the grid.
3.  Press `Loading` button above the stack view
4.  See the spinner - `Loading...` labels is visible

## Expected behavior

`Loading...` label should not be visible

## Versions
* Angular: 6
* Clarity: 0.12

**Device:**
* Browser all

**Comment by gnomeontherun** [comment]
Looks like the spinner needs a greater `text-indent` to push it off fully in this case.
