### ISSUE TITLE
Persisten size of column or access to width of datagrid columns.

### ISSUE THREAD

**Issue by Akay7** [vmware/clarity#2581]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Columns after resize save their size to persistent storage(Or can grant access to their size in code)
### Actual behavior
Columns after reloading the page, have default size.
### Reproduction of behavior
1. Resize columns in the datagrid
2. Then reload the page, 
3. Columns have the same size as before resizing columns.

I think this related to saving the state of hidden columns(#2117)

**Comment by Shijir** [comment]
A UI framework/library shouldn't be responsible for saving data or state into a storage. 
Once you resize a datagrid column width, the new width data is emitted through `(clrDgColumnResize)`. You could save that and set the column to that width when the application restarts.

**Comment by Akay7** [comment]
@Shijir thank you very much. I would like to know is it exist an emitter for hide/show event of hideable columns?

**Comment by hippee-lee** [comment]
Yes, `(clrDgColumnResize)` is an existing event emitter (https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/render/column-resizer.ts#L40). It emits the width after drag events are done.
