### ISSUE TITLE
Add testing for schematics migration

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2586]
## Summary

Create a test that will run the migration scripts to ensure they continue to work on known migrations.

* [ ] Create a new repo that contains an example of all of the things that need to be migrated
* [ ] Run the migration scripts, one at a time
* [ ] Between each script, compute and compare an md5 hash to validate it ran as expected
* [ ] Add into Travis CI 

## Use case

Ensures that our migration scripts continue to function as expected.

## Examples

/shrug

## Workarounds

Manual testing

**Comment by mathisscott** [comment]
@gnomeontherun 
Do we want to move this into the backlog?

**Comment by gnomeontherun** [comment]
@sis0k0 has added some testing here, we can close this.
