### ISSUE TITLE
Notification dropdown

### ISSUE THREAD

**Issue by vinaykhegde** [vmware/clarity#2601]
## Summary

Hi  team clarity, great job from you guys, I have started using clarity UI for my website.

Can we have dropdown for notification icon on header?

## Use case

user can see the notification easily by clicking on bell icon and view it in dropdown
## Examples

an image something like this 
![notify](https://user-images.githubusercontent.com/34911874/44771961-318d9900-ab8a-11e8-82e9-3a5f173ad9bc.PNG)

## Workarounds

_Is there a workaround for this feature at the moment?

**Comment by pumano** [comment]
Workaround to use dropdown list or create custom notification list

**Comment by vinaykhegde** [comment]
Hi @pumano  Thanks for the update, can you please elaborate on how can I use dropdownlist(Angular component) to make that happen?

**Comment by vinaykhegde** [comment]
Hi @pumano Thankyou for the suggestion which you gave, I tried a work around on dropdown and added list-group and got a notification dropdown somewhat ready.
![notifydropdown](https://user-images.githubusercontent.com/34911874/44866077-d0f17f80-aca1-11e8-8370-6f65ba43a91d.PNG)

**Comment by pumano** [comment]
@vinaykhegde looks good!

**Comment by pumano** [comment]
@vinaykhegde looks good!
