### ISSUE TITLE
Document Color Variables

### ISSUE THREAD

**Issue by CITguy** [vmware/clarity#2603]
## Summary
Color palette documentation is missing SCSS variable names.

## Use case
Developers that need to consume official clarity colors need the ability to consume pre-defined SCSS color variables in order to keep implementations in sync with official clarity colors.

## Examples
n/a

## Workarounds
As a developer, I've got two options:

1. Define my own set of color variables
    * This is time consuming and can get out of sync when clarity updates.
2. Dig through clarity source code in hopes of finding a defined variable.
    * Many documented colors don't have SCSS variables defined at all, so I'll still need to maintain a self-defined list of colors.

**Comment by mathisscott** [comment]
@CITguy 
Have you seen [our documentation on theming](https://vmware.github.io/clarity/documentation/v0.12/themes)? Is that more like what you are looking for?

**Comment by CITguy** [comment]
The "Custom Themes" section of the Themes documentation mentions the following for a custom light theme:

> In order to customize the Clarity light theme you will need to build with the Clarity SCSS and overwrite the SCSS variables that set the look-n-feel for each component you need to customize.

However, I cannot find any documentation on the SCSS color variables that I need to overwrite. The SCSS variables are hidden deep in the source code.

**Comment by CITguy** [comment]
FYI: I'm not a consumer of Clarity. I was doing color research for another design system and I noticed this issue in your documentation.

**Comment by mathisscott** [comment]
I see. Thanks for getting back to me on that. We'll take a look at how we can improve that.

**Comment by KANekT** [comment]
This issue is "Document theming customization" in wiki link go to https://github.com/vmware/clarity/issues/1586
![изображение](https://user-images.githubusercontent.com/580273/58687746-2f5fa180-838b-11e9-9fca-9fd1caace489.png)

**Comment by gnomeontherun** [comment]
Core documentation will help address this.

**Comment by gnomeontherun** [comment]
This is available today in Core https://clarity.design/storybook/core/ and will be incorporated into the main website in coming months. Closing as resolved by Core.
