### ISSUE TITLE
Datagrid Column Headers overlap when text is too long

### ISSUE THREAD

**Issue by ttsvetko** [vmware/clarity#2605]
## Describe the bug

Column headers overlap when column is resized and column header's text is too long.

## How to reproduce

Go to: https://stackblitz.com/edit/clarity-dark-theme-v012-tsdheb
Resize any of the columns except the last one.

## Expected behavior

Text to be truncated and show ellipsis OR to be able to resize the columns so that column header can fit in and not less than that width.

## Versions

**App**

* Angular: 6
* Node: 8.10
* Clarity: 0.12.5

**Device:**

* Type: MacBook
* OS: MacOS
* Browser: all
* Version: latest

**Comment by hippee-lee** [comment]
Hi @ttsvetko there is an issue for this already: https://github.com/vmware/clarity/issues/1725 The workaround at the bottom of the comments might be useful to you. Please subscribe to that issue for more updates. 

Closing based on that. If that issue I linked to is different from your issue feel free to re-open this one.
