### ISSUE TITLE
List Groups inside of dropdown menus don't wrap text

### ISSUE THREAD

**Issue by vinaykhegde** [vmware/clarity#2606]
## Describe the bug

When you put a list-group list-group-flush inside of a dropdown menu, you lose the wordwrap, cause the menu forces white-space: no-wrap on it's children. We have to override it manually. And I am not sure whether I can use list group in dropdown or not, Its an workaround that I am doing to create a notification dropdown.

## How to reproduce

https://clarity-light-theme-v012-pwy9cv.stackblitz.io

## Expected behavior

Putting a list-group inside of a dropdown menu item should not lose the default wrapping of text that normally wraps in lists.

## Actual behavior
When you put a list-group inside of a dropdown menu, we lose the wordwrap, cause the menu forces white-space: no-wrap on it's children. we have to override it manually.

## Versions

**App**

* Angular: [6]
* Node: [8.10.0]
* Clarity: [e.g. 0.12]

**Comment by mathisscott** [comment]
@vinaykhegde 
What is the use case for putting a list group in a dropdown?

**Comment by vinaykhegde** [comment]
Its an workaround that I am trying out to create a notification dropdown.
![notifydropdown](https://user-images.githubusercontent.com/34911874/44892109-97039600-ad00-11e8-86eb-d518f727adc5.PNG)

**Comment by mathisscott** [comment]
@vinaykhegde 
Are the items in the dropdown clickable?

**Comment by vinaykhegde** [comment]
@mathisscott 
can be both, If notification  to be seen in detail then clickable can be done or else the item will be left as it is in the view. As off now I have not made it clickable.

**Comment by mathisscott** [comment]
@vinaykhegde 
It doesn't make sense to mix clickable and non-clickable elements that both look the same and exist at the same level in the DOM. That means basic functionality in your application has now been designated as discoverable.

It's like removing all the underlines from links on a webpage and making them the same color as regular text.

If I have the time, I will try to put together a stackblitz soon demonstrating how this type of dropdown can be done. I just had a half dozen presentations dropped on me, though, so I don't know how soon I can do this. Maybe later this week.

**Comment by vinaykhegde** [comment]
@mathisscott 
Thank you for your demo, will be waiting to see one.

**Comment by mathisscott** [comment]
@vinaykhegde 
[Here is that workaround](https://stackblitz.com/edit/clarity-light-theme-v012-brf9nd?file=src%2Findex.html). It isn't that much CSS to handle on the application side for now.

Before we consider adding this officially to the dropdown menus in Clarity, we will need our UX people to go over it and examine the use cases and accessibility issues it raises. That will take us some time.

Until then, the workaround is there.

**Comment by colinreedmiller** [comment]
Since there is a workaround and the component in question (a notification drawer) is in progress #2350 as part of toasts and snackbars #365 I will be closing this unless another list group wrapping use case is submitted.
