### ISSUE TITLE
Add utility class that forces word breaks on table cells for when users want to put tables in small things

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#2607]
## Describe the bug

Table cells are constrained to a minimum width. The table does not auto-fit. Instead, it creates a scrollbar and it seems like the cells with longer text has already reach the minimum width.
I need the table to fit inside a small card or div in a dashboard page.

![image](https://user-images.githubusercontent.com/1977391/44866179-18ced180-acb7-11e8-86c0-d0a0d1c49b02.png)

## How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v11-x5hujx

1. Resize the window to make it smaller.

## Expected behavior

The whole table should fit to the parent container and cells should automatically wrap texts. It should resize cells automatically to fit in the parent container like the stackview component:
![image](https://user-images.githubusercontent.com/1977391/44866660-6f88db00-acb8-11e8-8111-e363a1e69216.png)

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
@whizkidwwe1217 
Hi, thanks for filing this issue. We can't make this the default for tables because there would be just as many people wanting us to un-make it the default.

[The good news is that it's a fairly simple CSS fix. It can be used as a workaround in the meantime.](https://stackblitz.com/edit/clarity-light-theme-v11-nbkzxy?file=index.html)

This could be helpful as an option to add or remove from tables where needed. And would be welcome as a contribution. I don't know if anyone on our team would be able to pick it up in the near future.

**Comment by mathisscott** [comment]
We will also need to add this to the table demos, gemini tests, and dox.

**Comment by whizkidwwe1217** [comment]
@mathisscott The CSS workaround is good enough for me, thanks! Appreciate it. It's just annoying when the table overlaps the card in the dashboard.
![image](https://user-images.githubusercontent.com/1977391/44872343-d3ff6680-acc7-11e8-8015-daa170a001e9.png)

**Comment by youdz** [comment]
I would like to point out that in your example, you are comparing how the stack view wraps compared to the table. Your stack view example has actual text, with spaces between words. Your table has very long strings without any spaces. **If you were to use words and spaces in your table, it would wrap correctly.**

I've just discussed this with Scott, and I'm actually going to close this issue. The CSS you have to write in your app to wrap long strings like that (which is unusual) is literally just one line. If we were to add a utility class for it, you'd still have to write one line for that, but it would add maintenance, documentation and bloat the API for us. I can only see downsides to utility classes that add just one line of CSS, they offer almost no value. And the best part is that by using CSS directly, you'll know how to do it when you work with any framework in the future, whereas learning our utility class would not help you grow in any way. 😉

**Comment by whizkidwwe1217** [comment]
@youdz Thanks for the advice. I'm actually more of a back-end guy and just started learning front-end dev. And yeah, this can be closed and I'm happy with the quick fix. Cheers! (btw, the texts in my sample are actually long texts and can't be broken down into words since they are asp.net core EF migration keys. But I can always truncate it with an ellipsis as an alternative to wrapping).
