### ISSUE TITLE
Datetime-local is not taking seconds

### ISSUE THREAD

**Issue by vinaykhegde** [vmware/clarity#2615]
Hi Team,
I am not sure whether its right or wrong but when I try input type datetime-local its not taking milliseconds, shows error this field required. Thanks.
![datetime-loca](https://user-images.githubusercontent.com/34911874/44984782-b79b4c80-af9b-11e8-9346-30cd5205b588.PNG)

**Comment by mathisscott** [comment]
Hi @vinaykhegde 
Could [create a stackblitz recreating the issue](https://stackblitz.com/edit/clarity-light-theme-v012)?

It will help us to investigate what might be causing it and whether there is a workaround for it.

**Comment by vinaykhegde** [comment]
Hi Team,
Here is the stackblitz.
https://clarity-light-theme-v012.stackblitz.io

**Comment by gnomeontherun** [comment]
The `datetime-local` requires setting AM or PM, which validates the field in your example. So I'm not sure what you're experiencing?

![image](https://user-images.githubusercontent.com/79500/45107553-905d9000-b0ff-11e8-907a-f52a4d73fdf3.png)

**Comment by gnomeontherun** [comment]
Also I just realized that `datetime-local` does not support seconds itself. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

I'm going to close as I suspect this is an implementation issue.
