### ISSUE TITLE
Error tooltips for invalid inputs are not visible in stack blocks

### ISSUE THREAD

**Issue by civanova** [vmware/clarity#2617]
## Describe the bug

Error tooltips for invalid inputs are not visible in stack blocks

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v11-qwuhmz

1.  Go to the invalid input in the stackblock
2.  Focus the input
3.  See that the error tooltip is not visible

## Expected behavior

The tooltip to be visible

## Versions

**App**

* Angular: 4
* Node: 8.10.0
* Clarity: 0.11.21

**Device:**
* Browser all

**Comment by gnomeontherun** [comment]
I recommend updating to the new form components, as it will be supported long term where old forms are deprecated.

**Comment by gnomeontherun** [comment]
Try to use new forms like you see below, which you might need to add some CSS to reduce the padding on the label above the row.

```
<clr-stack-block>
  <clr-stack-label>Valid input</clr-stack-label>
  <clr-stack-content>
    <clr-input-container>
      <label>Space</label>
      <input clrInput name="field1" [(ngModel)]="field1" required />
      <clr-control-error>This field is required</clr-control-error>
    </clr-input-container>
  </clr-stack-content>
</clr-stack-block>```

However, we're not making any other changes to the old forms at this time, since they are deprecated.
