### ISSUE TITLE
Check subscriptions before calling them

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#2618]
## Describe the bug

Most of our components use RxJS subscriptions so once they are destroyed the subscription should be cleared as well. However, there are needs where users need to destroy components before their subscription takes place. As a result, it's common for users to run into an error where undefined subscription property is called. This is especially common when a component has a single or individually assigned subscription in Angular's lifecycle hooks such as ngAfterContentInit, ngAfterViewInit, etc.

Currently, we have several components that try to unsubscribe their subscriptions in `ngOnDestroy` without checking whether the subscriptions actually have taken place or not.

## Expected behavior

We need to check whether those subscriptions are defined or not before trying to unsubscribe them.

## Versions

**App**

* Angular: 6.0^
* Clarity: 0.12^

**Comment by youdz** [comment]
A component calling `ngOnDestroy()` before `ngOnInit()`, `ngAfterContentInit()` or `ngAfterViewInit()` is a symptom of a real lifecycle issue in the app itself, and we should keep failing early so it can be caught and fixed before it becomes a larger problem.

See https://github.com/vmware/clarity/pull/151 and https://github.com/vmware/clarity/pull/1185 on examples of when we refused similar requests. As usual, I'll be happy to discuss this more if you can get a running example on StackBlitz that shows it *can* happen in a valid use case.
