### ISSUE TITLE
UI & Icon Library Updates

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#2626]
## Summary
- [x] update components in the UI and Icon libraries to reflect the action blue color change in #2585. color change to: 0079B8
- [x] update the color in the "Clarity-colors.zip" file
- [x] rename Dropdown Buttons to distinguish them from the basic buttons (this is only in the small sized ones, the normal sized ones have the preferred naming)
- [x] find and remove the duplicate "Small Primary-outline button"

## Reproduce issues
rename Dropdown Buttons
![image](https://user-images.githubusercontent.com/1858226/45187680-66cb6400-b1e6-11e8-9688-697621f44366.png)

duplicate "Small Primary-outline button"
![image](https://user-images.githubusercontent.com/1858226/45187658-51563a00-b1e6-11e8-8f7d-c0fbcff2fbe8.png)

**Comment by bmireles** [comment]
@reddolan Do we need to update the color in the sketch palette as well?

**Comment by bmireles** [comment]
For outline buttons do we want the border, text and icons to all be 0079B8?
They are currently 0077B7. Not sure if that is intentional.

**Comment by reddolan** [comment]
Yeah, we want to hunt down all instances of the previous color and change them to the new action blue.

**Comment by reddolan** [comment]
All of these changes are complete
