### ISSUE TITLE
UI Library Update - Datagrid Refactor

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#2627]
## Summary
- change the way that the Datagrid components are built
- currently it's done by rows
- update to be done with columns

reference the Pagination design spec in #2361

**Comment by bret-bailey** [comment]
Currently, the nbRow value is incremented twice for each row ... see the code snippet below.

During the refactoring, can you makes sure the this.radioId matches the row index?

This becomes problematic when writing tests with Selenium and the id is checked ...

---

src\clr-angular\data\datagrid\datagrid-row.ts

```
  /**
   * Model of the row, to use for selection
   */
  @Input('clrDgItem') item: T;

  constructor(
    public selection: Selection<T>,
    public rowActionService: RowActionService,
    public globalExpandable: ExpandableRowsCount,
    public expand: Expand,
    public hideableColumnService: HideableColumnService
  ) {
    this.id = 'clr-dg-row' + nbRow++;
    this.radioId = 'clr-dg-row-rd' + nbRow++;
  }
```

**Comment by gnomeontherun** [comment]
@bret-bailey that is unrelated to this ticket, can you please open a new issue?

**Comment by bret-bailey** [comment]
will do, np - just thought it was something small that could be cleaned up during a refactor, which is why I simply added the comment here.

**Comment by reddolan** [comment]
changes complete and moved to the site
