### ISSUE TITLE
Server-Driven datagrid: rows selection missing

### ISSUE THREAD

**Issue by power721** [vmware/clarity#2628]
## Describe the bug

When use Server-Driven datagrid, after I refresh data, the selected count in left footer is kept but the rows are not selected.

## How to reproduce

1.  load data from server
2.  select rows
3.  reload data from server which return same data

## Expected behavior

Rows selection should kept after refresh data.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Comment by power721** [comment]
The Selection use indexOf to find checked items.
Should leverage the trackBy function.

**Comment by hippee-lee** [comment]
This may be related to issue #2265. Can you take a look there and see if it is similar to your use case? There is already a working StackBlitz on the linked issue that reproduces the issue behavior.

**Comment by power721** [comment]
Yes, it's same issue.

**Comment by hippee-lee** [comment]
Ok, I'm going to close this as a duplicate. Please subscribe to that issue for updates.
