### ISSUE TITLE
Horizontal navigation through the wizard

### ISSUE THREAD

**Issue by guntisravani** [vmware/clarity#2633]
* What is the change?
Currently, the wizard navigation is vertical.

* Why should it go in Clarity?
Users require horizontal navigation option as well.
* Does this change impact existing behaviors? If so how?
N/A
* If this change introduces a new behavior, is this behavior accessible?
N/A

Please let me know if you require any information further

**Comment by mathisscott** [comment]
@guntisravani 
What is the use case driving this request?

**Comment by mathisscott** [comment]
Barring new information on the use case, I'm closing this as a duplicate of #1633 which is a component that seems more applicable to the use case as I understand it.
