### ISSUE TITLE
Datagrid: Standard filter breaks after two custom filters

### ISSUE THREAD

**Issue by Wallabeng** [vmware/clarity#2636]
## Describe the bug
We have a datagrid with 2 custom filters and 2 standard filters and regardless of column order, we observe the same behaviour all the time : The standard filter after the second custom filter doesn't work, as it always sends undefined values via output "clrDgRefresh".
In provided stackblitz the filtering of column "salutation" breaks.
But if you exchange  "telephonenumber" and "type", the filter (and only it) of column "telephonenumber" breaks

## How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v012-cluznb?file=src%2Fapp%2Fapp.component.ts

Filter column "salutation" -> doesn't work as the filter key/value sent via output "clrDgRefresh" is undefined

## Expected behavior
Filtering should work.

## Versions

**App**

* Angular: 6
* Clarity: 0.12.0

**Device:**

* macOS High Sierra 10.13.6
  * Firefox Quantum 60.2.0esr (64-Bit)
  * Chrome 68.0.3440.106 (64-Bit)

Couldn't test on other devices, but I guess it's a general issue.

**Comment by Wallabeng** [comment]
@mathisscott 
Sorry, I fixed it!

**Comment by mathisscott** [comment]
Cool. Thanks, @Wallabeng 

So what are we looking for here? It's hard for me to understand what is breaking because I see an empty array as a dataset and a setTimeout in there. Is all that necessary to reproduce the issue?

**Comment by Wallabeng** [comment]
Ok, I removed all the clutter code (as I also only got it from a colleague).
He used an ngIf to close the filter after selecting an option, but this was the wrong way.
I use clrDgFilterOpen now and everything works fine.

Sorry for any inconveniences!
