### ISSUE TITLE
Datagrid: column-toggle design issue in case of many columns and few rows

### ISSUE THREAD

**Issue by dszegvari** [vmware/clarity#2638]
## Describe the bug

In case of many columns and few rows, a portion of the column toggle panel is out of the viewport.

## How to reproduce

1.  Go to https://stackblitz.com/edit/clr-datagrid-column-toggle-design-issue
2.  Click on the column toggle icon
3.  See that a portion of the column toggle panel is out of the viewport. The user cannot access the first coupe of columns' checkbox.

## Expected behavior

I expect to see every columns' checkbox.

## Versions

**App**

- Angular: 6
- Node: 10.8.0
- Clarity: 0.11.28

**Device:**

- Type: Dell
- OS: Windows 10
- Browser: Tested with Chrome, Firefox

**Comment by mathisscott** [comment]
Hi @dszegvari 
This is something that we could stand to make easier. But it will probably become a non-issue before we can get to it.

[Here is a stackblitz demonstrating the workaround](https://stackblitz.com/edit/clr-datagrid-column-toggle-design-issue-qwl7xg?file=src/app/app.component.ts).

It will be hard to prioritize this as #2240 is something we will need to complete to finish #1586 

If you are looking for the enum that has the anchor points in the stackblitz, [you can find it here](https://github.com/vmware/clarity/blob/master/src/clr-angular/popover/common/popover.ts).

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
