### ISSUE TITLE
Correctly export Stack View components

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#264]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

[src/clarity/stack-view/index.ts](https://github.com/vmware/clarity/blob/master/src/clarity/stack-view/index.ts) should export the components themselves in addition to the array. See other components for examples.

### Actual behavior

Right now, it only exports the array, so any interaction through Typescript requires to import from `src/` instead of the main index.

### Environment details

* **Angular version:** 2.2.3

* **Clarity version:** 0.7.5

* **OS and version:** all

* **Browser:** all

**Comment by jeeyun** [comment]
Hi @youdz I believe this was handled in https://github.com/vmware/clarity/pull/288. Please let me know if that's not the case. If it is, feel free to close this.
