### ISSUE TITLE
Clarity 0.13 Hide/Show feature OK button does not work

### ISSUE THREAD

**Issue by speti43** [vmware/clarity#2640]
## Describe the bug

Clarity 0.13 Hide/Show feature -> OK button is broken.

## How to reproduce

Go to clarity demo page:
https://vmware.github.io/clarity/documentation/v0.13/datagrid/hide-show

1, Column toggle button
2, Column selection modal appears
3, Ok button (Check)
4, Modal stays open

## Expected behavior

Modal closes.

## Versions

Clarity official demo page

* Angular: [6]
* Node: [8.10.0]
* Clarity: [0.13]

**Device:**

* Type: Dell latitude E5550
* OS: Windows 10
* Browser [Google chrome]
* Version [68.0.3440.106 (Official Build) (64-bit)]

**Comment by m-tomczyk** [comment]
It's probably working as intended. See: https://github.com/vmware/clarity/issues/2100 and https://github.com/vmware/clarity/pull/2546

**Comment by gnomeontherun** [comment]
We removed this feature from 0.13, but missed it in our documentation, so no need to worry about it anymore!
