### ISSUE TITLE
Datagrid Pagination Output Page Change Event Name

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#2659]
## Expected behavior

Output event (clrDgPage) not working

I see code:

https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid-pagination.ts#L132

And worked for me  (clrDgPageChange)

Error in doc?

[(clrDgPage)] | currentPage | Index of the currently displayed page, starting from 1.

https://vmware.github.io/clarity/documentation/v0.12/datagrid/pagination

## Versions

**App**

* Angular: 6
* Clarity: 0.12

**Comment by youdz** [comment]
See [the Angular docs on two-way binding](https://angular.io/guide/template-syntax#two-way-binding---), `[(xxx)]="myVar"` two-way binding is just syntactic sugar for: 
```
[xxx]="myVar" (xxxChange)="myVar = $event"
```

The documentation is correct since it shows the two-way binding syntax.
