### ISSUE TITLE
clrSelect empty label tags are generated

### ISSUE THREAD

**Issue by speti43** [vmware/clarity#2660]
## Describe the bug

clrSelect directive generates empty label tags.

## How to reproduce

https://stackblitz.com/edit/clr-form-select-without-label

![image](https://user-images.githubusercontent.com/5813332/45619755-c6ddc800-ba7a-11e8-8e5b-38cfb113cbbd.png)

1.  Go to stackblitz
2.  Inspect html above select

## Expected behavior

Labels for select should only be generated when the user declares:
`<clr-select-container>
  <label>I've got some options</label>
  <select clrSelect name="options" [(ngModel)]="options" required>
    <option value="one">One</option>
    <option value="two">Two</option>
    <option value="three">Three</option>
  </select>
  <clr-control-helper>Helper text</clr-control-helper>
  <clr-control-error>This field is required!</clr-control-error>
</clr-select-container>`

## Versions

App

Angular CLI: 6.1.3
Node: 8.11.2
Clarity: 0.13
Device:

Type: Dell latitude E5550
OS: Windows 10 64bit
Browser: Chrome - Version: 69.0.3497.92 (Official Build) (64-bit)

**Comment by youdz** [comment]
You're using `[ngModel]` to force the `<select>` to have an empty value on initialization (none of the options is pre-selected). This makes Angular create an empty option for the select that will disappear as soon as the user selects one of the valid options.

This has nothing to do with the Clarity select, you can see it happens with a plain HTML select too: https://stackblitz.com/edit/select-bind-invalid-option?file=src%2Fapp%2Fapp.component.html
As you can see, the one binding an invalid initial value starts with a temporary empty option. That's just Angular.

I also added to this plunker [the solution seemingly recommended by Angular](https://angular.io/api/forms/SelectControlValueAccessor), which is to add a disabled option with an empty value.

**Comment by speti43** [comment]
@youdz  You are missing the point, I'm not complaining about the empty `<option>` tag.
Please read the bug again carefully, and please reopen the bug.

**Comment by gnomeontherun** [comment]
I'm not sure I understand the exact issue here, we need the labels in some cases (like you have it set to horizontal layout, but vertical layout don't add extra labels). Your last screenshot shows lots of controls in a line, which wouldn't be a horizontal layout anyways so I'm not sure if this example is representative of your fully issue, but here are some notes.

Do you want validation and/or helper text? 
1. If so, you'll need the `clr-select-container`. Use vertical layout in the clrForm so it doesn't add a label. (It adds the label for horizontal and compact layouts only, for alignment purposes, and there is no way to disable it at the moment.)
2. If not, then just leave off the `clr-select-container` and no label will be added no matter what layout is used.

**Comment by speti43** [comment]
@gnomeontherun If you take a look at my stackblitz, you will see I didn't add clr-select-container, even so an empty label is generated. 
So just keep this simple, what I would like:
`<select clrSelect ....>` should generate
``` 
<someContainers>...
   <select .... classes="proper css classes">
</someContainers>
```
What I actulley get:
`<select clrSelect ....>` generates 
```
<label>Empty label which I dont need</label>
<select clrSelect ....> should generate  
<someContainers>...
   <select .... classes="proper css classes">
</someContainers>
```

**Comment by gnomeontherun** [comment]
Your stackblitz is using horizontal layout, so it will add the label. Because of the narrow size of a stackblitz window (usually), it actually triggers the vertical layout but the label exists. So as I said with option 1, use `clrLayout="vertical"` instead otherwise it will add the label.

**Comment by speti43** [comment]
Problem solved, thank you for the guide! 👍
