### ISSUE TITLE
Allow more form components in card footers

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#2661]
## Summary

Currently there are easy ways to add buttons or dropdown menus to card footers.  There doesn't appear to be any general way to add other types of controls like select boxes or toggle switches.  

## Use case

Cards provide a natural way to isolate charts, plots, or other views into data.  The footer of cards is a natural place to add a small number of controls 

## Examples

Material's cards allow [something similar](https://material.io/design/components/cards.html?image=https%3A%2F%2Fstorage.googleapis.com%2Fspec-host-backup%2Fmio-design%252Fassets%252F0B6xUSjjSulxcYXYwTkFwYmVTM0k%252Fcards-uicontrols-2.png#actions) -- a reusable divider that creates something similar to a footer that can be populated with controls.  

## Workarounds

In previous Clarity releases I've managed to get toggle switches working in card footers, but it was always hacky.  An alternative is just not using a footer and putting a few controls in a row at the bottom of a card, but this doesn't look very nice.

**Comment by gnomeontherun** [comment]
I don't think we're opposed to this, its probably just that we haven't done the tweaks necessary to make the controls fit just right in those places. I don't believe you're asking for any new features, just some styling is that correct?

That shouldn't be a big deal on the implementation side. Its just checking that things layout, and I'm only really thinking about dropdowns, toggles, and selects.

@reddolan Do you have any input here about if there is a reason UX wouldn't want these interactive elements (assuming it isn't a link card)?

**Comment by mathisscott** [comment]
This is a reasonable request. I'll move it to the backlog and open it up for external contributions given that it is predominantly a CSS issue.

**Comment by amellnik** [comment]
If anyone is interested in looking into this I'm adding the very hacky classes below:

```css
.inline-form {
  padding: 0;
}

.inline-container {
  margin-top: 0rem;
  margin-right: 0.5rem;
  display: inline-block !important;
}

.inline-card-footer {
  padding: .5rem .75rem;
}
```

to get dropdowns in footers that look like this:

![screen shot 2019-02-27 at 1 38 26 pm](https://user-images.githubusercontent.com/7132414/53524716-06322b00-3a95-11e9-938e-8403410d1e3f.png)

on Clarity 1.0.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
