### ISSUE TITLE
Add a v013 stackblitz template

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2664]
## Summary

Please add a Clarity Version 0.13 Stackblitz template. Currently there are only 0.10, 0.11 and 0.12 templates available for the @clr-team stackblitz user.

## Use case

Stackblitz tempaltes are useful for bug reports.

## Workarounds

Currently you have to create an own stackblitz.

**Comment by youdz** [comment]
We should absolutely create one, I'm surprised we forgot as part of the 0.13 release.

In the meantime, StackBlitz has an awesome but little-known feature that will let you easily start a Clarity 0.13 StackBlitz. This button will update all dependencies to their latest version:
<img width="322" alt="stablitz-update-dependencies" src="https://user-images.githubusercontent.com/4647197/45754784-987efa80-bbea-11e8-9c6b-d8d6a360a74b.png">

**Comment by gnomeontherun** [comment]
See https://stackblitz.com/@clr/team to see the new ones, we'll update docs as well.

**Comment by Shijir** [comment]
Please check now. It should be updated.
