### ISSUE TITLE
Creating wizard pages dynamically.

### ISSUE THREAD

**Issue by prashant-pokharna** [vmware/clarity#2666]
There is a required while using Clarity framework.
Once the first page of Wizard page is completed, We get to know how many more wizard pages are required on run time. 
I couldn't find a solution for this in clarity documentation. Is there a way to do that or is it something new requirement.
Thanks in advance.

**Comment by SayWhat69** [comment]
Use *ngFor to create as many pages as you need

**Comment by prashant-pokharna** [comment]
Hi,
Thanks for your response.
This works when you know pages before creating the wizard itself. 
I created the wizard and after page 1 i know how many more pages are required.
Do we have any way to solve this problem.

Prashant.

**Comment by SayWhat69** [comment]
You can just add or remove elements to/from the 'pages' Array

**Comment by mathisscott** [comment]
This can also be done using `*ngIf` on the pages. The example above shows how to do that. So the `*ngFor` isn't completely necessary there if you needed to go granular with it.

**Comment by SayWhat69** [comment]
Simply look in the documentation...

https://vmware.github.io/clarity/documentation/v0.13/wizards
