### ISSUE TITLE
Click on "Learn more" in v0.13 input documentation leads to 404 page

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2671]
## Describe the bug

There's a dead link in your version 0.13 input documentation website.

## How to reproduce

![screen shot 2018-09-21 at 12 56 02](https://user-images.githubusercontent.com/3655915/45877505-60b8b400-bd9e-11e8-9fea-4f54195bf67e.png)

![screen shot 2018-09-21 at 12 58 24](https://user-images.githubusercontent.com/3655915/45877513-63b3a480-bd9e-11e8-97b2-6743dae14358.png)

## Expected behavior

There's no 404 error.

**Comment by GeekAb** [comment]
I think URL should be https://vmware.github.io/clarity/documentation/v0.13/forms, not https://vmware.github.io/clarity/documentation/v0.13/**input**/forms

**Comment by hippee-lee** [comment]
Hi there, thanks for reporting this. I made a change that fixes the links. The changes should be published soon.
