### ISSUE TITLE
Documentation for Datagrid Single Select is incorrect for v0.13.0

### ISSUE THREAD

**Issue by jeremygreenberger** [vmware/clarity#2674]
## How to reproduce

_Check out https://vmware.github.io/clarity/documentation/v0.13/datagrid/selection-single_

1.  Go to 'Selection (Single)' section.
2.  See that the example uses 'clDgRowSelection'

## Expected behavior

_The example should be using 'clrDgRowSelection'_ 

## Versions

**App**
* Clarity: [e.g. 0.13.0]

**Comment by hippee-lee** [comment]
Hi @jeremygreenberger - thank you for reporting this. I appreciate your feedback and helping us make the docs better. 

I made the change and the website should be re-published soon.
