### ISSUE TITLE
Document theming of Clarity SCSS on website

### ISSUE THREAD

**Issue by chunghha** [vmware/clarity#268]
[ ] bug
[ ] feature request
[X] enhancement

Do you have a plan on your road-map for these items?
1. Custom Theme Support
2. Clarity NG components can be integrated to users' application independently without Clarity UX and/or UI. (maybe using Component Inheritance in Angular 2.3 +)

Reason to ask is that I have several Angular1/Bootstrap3 Web applications and started a couple of Angular2 projects with Angular2/Bootstrap4 (w/ ng-bootstrap) then I am following progress of this Clarity project mainly for me to use several components already this project provides.

On technical side, changing current bootstrap3 themes I have to something else for bootstrap4 theme is not an issue for my NG1 applications. But, I may have really hard time to go thru design approval process if Look&Feel for NG2 applications is totally different than current NG1 applications. This concern I have now applies to Clarity's L&F exactly - no one in my team recognized Clarity is based on Bootstrap 4 when I demo'ed my NG2/Clarity app even though they liked App Layout, Navigation and all good components of Clarity. 

So I like to ask about the 2 items if you'd already have something on your plan. Thanks!

**ps: I am sorry if this is not a good place to ask this kind of questions.
(edited: Clarify --> Clarity)

**Comment by anodynos** [comment]
Any progress on this? We have a project that could use Clarity instead of Bootstrap and a developer that loves it, but we have to be able to customize the look & feel...

**Comment by jaffoneh** [comment]
@chunghha and @anodynos: our priority is to focus on building a complete design system that includes the design patterns, look and feel, as well as the components. Providing custom theme support isn't currently a high priority of ours considering that goes in the other direction from our priority of building up Clarity as a complete end to end design system. That has been said, you can use Clarity components today and customize them, it is just that this is not yet documented.

**Comment by gnomeontherun** [comment]
This has been completed and is at https://vmware.github.io/clarity/documentation/v0.11/themes
