### ISSUE TITLE
Hand-grab and hand-open icons are missing 

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#2682]
## Describe the bug

The SVG asset files for `hand-grab` and `hand-open`  shapes were provided in Volume 12, but they haven't been implemented.

https://github.com/vmware/clarity/issues/2222

## How to reproduce

Search for the above-mentioned icons in https://vmware.github.io/clarity/icons/icon-sets.

## Expected behavior

`hand-grab` and `hand-open`  shapes should be present.

**Comment by reddolan** [comment]
`tree-view` is also missing from the download on Technology

**Comment by reddolan** [comment]
NM, it's in `Essentials`
