### ISSUE TITLE
Datagrid: Various popovers get cut off depending on datagrid size and placement

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#2683]
## Describe the bug

This is a list of datagrid issues related to the lack of smart popovers in the datagrid:

1. Filters: When the datagrid is to short, the filter popover overflows with the rest of the header/table content underneath the footer. This can be worked around by setting a min height on the datagrid.
2. Hideable Column Toggle: Depending on the height of the datagrid, the list of hideable columns can be shown above the fold 
3. signposts / tooltips in rows can be `clipped` depending on the location and need to be manually set by the consumer to ensure onscreen and visible placement. 

## Expected behavior
After development of https://github.com/vmware/clarity/issues/1262#issuecomment-320699953 the issues with these popovers in datagrid should not occur.

**Comment by amellnik** [comment]
One other issue that may already be solved: opening a filter on the first column can fall off the screen if the column is narrow.

**Comment by hippee-lee** [comment]
Hey Alex, I don't think the issue you describe is already fixed. But, it should be fixed once I develop the fix for this issue.

**Comment by sdurnov** [comment]
@hippee-lee do you have it planned for release anytime soon?

**Comment by hippee-lee** [comment]
Hi @sdurnov - I have one more item that needs to be done for the upcoming v1.0 release and then I will start on the smart popover enhancement that will address these issues. 

I hope to start on it by end of this week or early next week.

**Comment by hippee-lee** [comment]
Hey @JoshuaNitschke - thats one of the things the smart popover fix needs to address. For now, your best bet is to set a min height on the datagrid so that the filter popover doesn't overflow.

**Comment by sdurnov** [comment]
@hippee-lee but that won't help with 1st columns filter popup. Btw, this issue is for 2.0 now? Meaning it is planned to be released in half a year? This is bad news :(

**Comment by BramMeerten** [comment]
> 1. Filters: When the datagrid is to short, the filter popover overflows with the rest of the header/table content underneath the footer. This can be worked around by setting a min height on the datagrid.


I don't agree this should be part of an enhancement ticket. I think it should be a bug because it worked in the previous version. You can test this in the Custom Filtering documentation page of v.0.13:
https://vmware.github.io/clarity/documentation/v0.13/datagrid/custom-filtering
![image](https://user-images.githubusercontent.com/1921407/50888841-d355aa00-13f6-11e9-8e58-c6424489d978.png)

The workaround of setting a min-height is not a feasible option for us, because we have filters that contain a datepicker. This means that we'd need a min-height of about 400px.

But another workaround is to set the overflow of the datagrid to ```visible```:
```
.datagrid {
   overflow: visible;
}
```

**Comment by hippee-lee** [comment]
If any of the columns have been widened then the `.datagrid` element will be wider than its container (`.datagrid-host`). Setting `overflow: visible` will show the columns outside of the host container.

**Comment by jkjha** [comment]
> > 1. Filters: When the datagrid is to short, the filter popover overflows with the rest of the header/table content underneath the footer. This can be worked around by setting a min height on the datagrid.
> 
> I don't agree this should be part of an enhancement ticket. I think it should be a bug because it worked in the previous version. You can test this in the Custom Filtering documentation page of v.0.13:
> https://vmware.github.io/clarity/documentation/v0.13/datagrid/custom-filtering
> ![image](https://user-images.githubusercontent.com/1921407/50888841-d355aa00-13f6-11e9-8e58-c6424489d978.png)
> 
> The workaround of setting a min-height is not a feasible option for us, because we have filters that contain a datepicker. This means that we'd need a min-height of about 400px.
> 
> But another workaround is to set the overflow of the datagrid to `visible`:
> 
> ```
> .datagrid {
>    overflow: visible;
> }
> ```

This breaks lot of other things in grid. Like no scrolling.

**Comment by hachadwick** [comment]
this was nearly three months ago. has there been any updates on this?

**Comment by hippee-lee** [comment]
@hachadwick please follow #3374 for the updates

**Comment by windsonic** [comment]
We're having same problem and here's our fix in Clarity v1.1.0:
`
// Fixed the horizontal scrolling problem of datagrid
clr-datagrid {
  overflow: auto;   
}`

`
// To make sure the filter can be fully displayed
.datagrid {
  overflow: visible;
}

.datagrid-table {
  position: static;  
}
`

Also we added a directive to calculate min width of datagrid:
`
@Directive({
  selector: 'clr-datagrid',
})
export class ClrDgMinWidth implements AfertViewInit {
  constructor (
    @Self() private readonly clrDatagrid: ClrDatagrid,
    private readonly elRef: ElementRef<HTMLElement>,
    private readonly renderer: Renderer2,
  ) { }

  ngAfterViewInit () {
    const columns = this.clrDatagrid.columns.toArray();
    const minWidth = columns.length * 100;
    [ '.datagrid', '.datagrid-footer' ].map( selector => 
      this.elRef.nativeElement.querySelector(selector),
    )
    .filter(el => !!el)
    .forEach(el => this.renderer.setStyle(el, 'min-widht', `${minWidth}px`);
  }
}
`

**Comment by Jinnie** [comment]
@windsonic is it working as you expect it to do? I see you are setting 'min-wid**ht**' on the last line

**Comment by windsonic** [comment]
> @windsonic is it working as you expect it to do? I see you are setting 'min-wid**ht**' on the last line

Hi Jinnie, I updated my comments. Please take a look.
