### ISSUE TITLE
[Security issue] Clarity depends on bootstrap 4.0.0-alpha which has xss issue

### ISSUE THREAD

**Issue by zhoumeina** [vmware/clarity#2686]
Harbor team depends on Clarity 0.12. Now this version is using bootstrap 4.0.0 alpha which is reported xss security risks. 
Can clarity make a patch to 0.12 version, modify the dependency to bootstrap 4.1.3? otherwise , harbor team can not release new version. 
Waiting for feedback

**Comment by gnomeontherun** [comment]
We are aware of the XSS report, but Clarity does not use the JavaScript from Bootstrap which has the vulnerability. Updating Bootstrap is a breaking change for us, because Bootstrap changed a lot of files and features between 4.0.0-alpha.5 and 4.0.0.

**Comment by zhoumeina** [comment]
@gnomeontherun , do you have any plan of this? It looks not so reasonable to use a alpha version in a product release.

**Comment by KANekT** [comment]
@zhoumeina view issue https://github.com/vmware/clarity/issues/1531

**Comment by mathisscott** [comment]
@gnomeontherun 
Could you give an update here on what our plan is? Thanks.

**Comment by gnomeontherun** [comment]
As I noted in https://github.com/goharbor/harbor/pull/5967, most projects don't actually need Bootstrap unless the build custom themes. So your immediate issue can be resolved by removing it from your project if tooling is throwing notices about having a dependency upon Bootstrap 4.0.0-alpha.5. 

Our rationale for not updating before is that we don't use the JavaScript (which has the issue), and we don't ship with Bootstrap (its optional for only custom theme implementations). However, automated testing tools don't know the difference or understand the way dependencies are actually used to know that we don't actually consume the offending code, and we realize this may be an issue for some 

As I mentioned, updating Bootstrap causes a number of breaking changes and we're not able to do this right now based on the amount of work involved to smooth over all the changes and also manage the release. That is why we targeted it for 2.0, and that will not change.

However, I have a plan that allows us to remove the Bootstrap dependency in 1.0 (by copying over just the Sass files we consume) without a breaking change to almost all users. It _could_ be a breaking change for some users who are doing their own themes and have not followed our guide, so to be certain we will wait until the 1.0 version with this change.

**Comment by gnomeontherun** [comment]
We cannot put this change into 0.12, it will only go into 1.0 and above. If you don't need bootstrap to build a custom theme, this warning can be ignored. NPM doesn't have a way to mark optional peer dependencies.

Since this was merged, we'll close this ticket.
