### ISSUE TITLE
Icons choice for read-only version of checkbox treeview (advice needed, usability)

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2689]
I'm creating pretty standard admin app, where I have a Role edit page.
On this page, except for editing role name and description, I have a summary of permissions this role has in different app modules/sections.

This information is read-only, and I'm struggling to figure out how to show it.

In page where those permissions are editable, I just use checkbox treeview, like in your examples - it has top-level permissions and subpermissions, If part of subpermissions for top-level permission is enabled, I show indeterminate checkbox for top-level item.

![image](https://vmware.github.io/clarity/assets/images/documentation/tree-view/example_tree_checkbox_interacting.svg)

Showing same checkboxes with turned off interaction or in disabled state would confuse users.
Read-only state is something different, after all.

So I'm wondering, which icons could I use to clearly indicate that this is a read-only tree view, and to keep same metaphor of checked/unchecked/indeterminate checkbox.

This is what I came up with recently, but I don't really like the result. It looks less readable than regular checkbox treeview

![image](https://user-images.githubusercontent.com/32732457/46145302-72033400-c268-11e8-992a-7378fdacd5ae.png)

**Comment by colinreedmiller** [comment]
Is tree view the best choice for this use case?
What other ways can this information be presented?
What is the value in using the same view as the case where they are editable?
Is there any relationship between this user and the one who edits these permissions? i.e. If the read-only permissions were presented differently would the user who sets permissions view permissions in both ways - is this a meaningful concern?

Are icons necessary?
Can a Basic Tree display the list of permissions labelled clearly enough that the type styling of each item can indicate its status?
i.e. black (normal) text for enabled and grey (disabled) text for unavailable? Perhaps minimal iconography will help (e.g. bullet) - small back circle with enabled - hollow grey circle for disabled?

Clarity can’t solve this - the UX of the right choice for the user is a product design concern not part of Clarity - please refer to the suggestions above.
