### ISSUE TITLE
Inconsistent height behavior of DataGrid

### ISSUE THREAD

**Issue by hughanderson4** [vmware/clarity#2691]
## Describe the bug

DataGrid sometimes gets taller if I change the page size.  Sometimes not.

If you increase the page size, the vertical height grows, unless you have previously decreased the page size.

If you ever decrease the page size, the vertical height becomes locked and then does not grow with subsequent page size changes.

## How to reproduce

1.  Bind a dropdown to the page size of DataGrid who has many records
2.  Change page size from default of 25 to 10
3.  Notice the vertical height of table decreased
4.  Change the page size from 10 to 25
5.  Notice the vertical height of the table stayed the same, but scrollbar shows there are more records
6.  Refresh the page
7.  Now change page size from default 25 to 50
8.  Notice that the vertical height of the table increased
9.  Now change from 50 to 10
10.  Notice that the vertical height of the table decreased
11. Change back to 50
12.  Notice the vertical height of the table stayed the same, but scrollbar shows there are more records

## Expected behavior

Resizing behavior of Datagrid should be consistent.  In step 12 when I change back to 50, Datagrid should return to the same height it was in step 8.  In step 5 when I changed to 25, Datagrid should return to same height it was in step 1.

Or, height of Datagrid should never change.

Or, allow binding for height of Datagrid, so user can control.

## Versions

**App**

* Angular: 6.1
* Node: 8.10
* Clarity: 0.13.2

**Device:**

* Type: PC
* OS: Windows 10
* Browser: Chrome

**Comment by hippee-lee** [comment]
Hi @hughanderson4 - can you paste a link to the [StackBlitz](https://stackblitz.com/edit/clarity-light-theme-v013) that you are using with these steps so I can take a closer look at whats going on? Thanks.

**Comment by hughanderson4** [comment]
I noticed it in our large enterprise app, it's a bit of work for me to strip that down to a trivial demo.  Will try to carve out some time this evening to stage it.

**Comment by hughanderson4** [comment]
Hey, it's a case of user error :\

When I added a binding for `[clrDgPageSize]` to my `<clr-dg-pagination>` now this behavior is gone.

Sorry for the ruckus!
