### ISSUE TITLE
Sketch Library Updates

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#2694]
## Summary
* update Sketch asset downloads from [Get Started](https://vmware.github.io/clarity/documentation/v0.13/get-started) and [What's New](https://vmware.github.io/clarity/news)
* update version numbers 

## Updates from
* #2625 
* #2626 
* #2627 

## Links to files (when complete)

**Comment by reddolan** [comment]
Will comment with GitLab links when files are ready

**Comment by hippee-lee** [comment]
Files were updated with the website release for v0.13.5.
