### ISSUE TITLE
Incorrect column label color in data grid Show Columns popover when on Dark theme

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#2696]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

![image](https://user-images.githubusercontent.com/1977391/46254015-5cd21380-c4bb-11e8-9651-d55c361c4179.png)

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._
https://stackblitz.com/edit/clarity-dark-theme-v013-5p45lh

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
This looks like a regression bug related to the checkbox control that was recently updated. 
Please subscribe to this issue, I'll update here when I know more about the fix for it.

**Comment by GeekAb** [comment]
The issue is with class "clr-control-label" added to <label> which was not there earlier. Not sure if other style changes of "clr-control-label" are required if so we can just remove color property from class.

**Comment by hippee-lee** [comment]
Thanks @GeekAb - I'll be pushing a pull request to address the root cause of the issue soon.
