### ISSUE TITLE
New forms dark theme styling

### ISSUE THREAD

**Issue by emmalivingstone** [vmware/clarity#2702]
## Describe the bug

The new forms don't have styling for use with the dark theme.

## How to reproduce

[Stackblitz](https://stackblitz.com/edit/clarity-dark-theme-v013-bsdwfv)

## Additional notes

I thought since the new forms are a work in progress the dark theme styling might not be done yet, just wondering if it's on the radar? Thanks.

**Comment by hippee-lee** [comment]
Hi @emmalivingstone - thanks for reporting this. I'm linking this issue as it relates to this one: #2696.

Please subscribe to this issue. I'll be pushing a PR that will address this soon.
