### ISSUE TITLE
Set min and max dates with clrDate

### ISSUE THREAD

**Issue by sagarp2901** [vmware/clarity#2707]
## Summary
Unable to set min and max to disable dates when using clrDate on the date input.

## Use case
Date: <input type="date" clrDate [(ngModel)]="startDate" />
min and max to disable dates in this case has no effect and all the dates are enabled.

**Comment by gnomeontherun** [comment]
This is a duplicate of https://github.com/vmware/clarity/issues/1984, please subscribe to that issue.

**Comment by sagarp2901** [comment]
> This is a duplicate of #1984, please subscribe to that issue.

I have been through #1984 and the solution provided there does not works when <input> contains clrDate.

**Comment by gnomeontherun** [comment]
That is because we have to build it yet, thats just a prototype of the idea which needs updating for the current implementation.

**Comment by sagarp2901** [comment]
Okay. Any estimates on when it will be available?
