### ISSUE TITLE
Icons volume 14 

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#2709]
1. Snowflake
2. Fish
3. Fuel - example [https://cdn2.iconfinder.com/data/icons/maki/100/fuel-512.png](url)
4. Basic circuit elements (resistor, capacitor, inductor) - see Oct 22 comment for reference
5. Squid - see Oct 22 comment for reference
6. Volume (as in capacity-not sound level) [https://icons8.com/icon/1415/volume](url)
7. (Already done) "Skip to first/last page" for pagination icon set (completed. published to Clarity icon library)
8. Bell curve (Normal distribution chart) see Oct 25 comment...
9. Crosshairs, see #2987 for example and details
10. [form kinds](https://www.google.com.tw/search?biw=1366&bih=657&tbm=isch&sa=1&ei=dWfSW-SlCYqK8wWl6I74BA&q=html+input+field+icon&oq=html+input+field+icon&gs_l=img.3...38801.49237.0.49630.27.23.0.4.4.0.101.1043.22j1.23.0....0...1c.1.64.img..0.23.902...0j35i39k1j0i19k1j0i8i30i19k1j0i30k1j0i10k1j0i30i19k1j0i24k1.0.iRlQVW6jaIw) (like text input、number input、select、horizontal slider fields)、
11. table kinds (like general table、[tree grid](https://www.google.com.tw/search?tbm=isch&q=treegrid+icon&spell=1&sa=X&ved=0ahUKEwjsnc759aLeAhVIx7wKHQHqA1YQBQg7KAA&biw=1366&bih=657&dpr=1)、[pivot table](https://www.google.com.tw/search?tbm=isch&q=pivot+icon&chips=q:pivot+icon,online_chips:pivot+grid&sa=X&ved=0ahUKEwjkhp_W9aLeAhWBw7wKHdgDAkoQ4lYIJygB&biw=1366&bih=657&dpr=1)) icons
12. Target (for timeline component)

**Comment by dorthrithil** [comment]
A fuel icon would be great: https://cdn2.iconfinder.com/data/icons/maki/100/fuel-512.png

**Comment by amellnik** [comment]
* Basic circuit elements (resistor, capacitor, inductor) 
* A squid (might not be practical)

**Comment by dorthrithil** [comment]
A vulume (capacity, amount) icon would be useful: https://icons8.com/icon/1415/volume

**Comment by jeeyun** [comment]
HI @lil-kim could we add an icon for "skip to first/last page" in the new pagination design? Not sure what would be the appropriate name for this. Screenshot for reference:

<img width="789" alt="screen shot 2018-10-15 at 9 49 54 am" src="https://user-images.githubusercontent.com/1827742/46965645-45b92700-d060-11e8-85fb-0f8a4c828362.png">

**Comment by amellnik** [comment]
@lil-kim - The capacitor, resistor and inductor circuit elements here are pretty typical: https://en.wikipedia.org/wiki/Electronic_symbol#/media/File:Circuit_elements.svg

There's also a circuit element symbol for a SQUID, which in retrospect would make way more sense than using an icon of a squid (the animal) in my use case.  It looks the screenshot below (from [this image](https://en.wikipedia.org/wiki/SQUID#/media/File:SQUID_IV.jpg)) without the red text (and maybe rotated 90 degrees to be consistent) with the others.  

![image](https://user-images.githubusercontent.com/7132414/47335906-4f372600-d642-11e8-98b9-b15f19d6fa9f.png)

**Comment by lil-kim** [comment]
@amellnik 
Added your SQUID request to the comprehensive list in the first comment.

**Comment by archerchiu** [comment]
Could you consider the Bell curve ([Normal distribution chart](https://en.wikipedia.org/wiki/Normal_distribution))、[form kinds](https://www.google.com.tw/search?biw=1366&bih=657&tbm=isch&sa=1&ei=dWfSW-SlCYqK8wWl6I74BA&q=html+input+field+icon&oq=html+input+field+icon&gs_l=img.3...38801.49237.0.49630.27.23.0.4.4.0.101.1043.22j1.23.0....0...1c.1.64.img..0.23.902...0j35i39k1j0i19k1j0i8i30i19k1j0i30k1j0i10k1j0i30i19k1j0i24k1.0.iRlQVW6jaIw) (like text input、number input、select、horizontal slider fields)、table kinds (like general table、[tree grid](https://www.google.com.tw/search?tbm=isch&q=treegrid+icon&spell=1&sa=X&ved=0ahUKEwjsnc759aLeAhVIx7wKHQHqA1YQBQg7KAA&biw=1366&bih=657&dpr=1)、[pivot table](https://www.google.com.tw/search?tbm=isch&q=pivot+icon&chips=q:pivot+icon,online_chips:pivot+grid&sa=X&ved=0ahUKEwjkhp_W9aLeAhWBw7wKHdgDAkoQ4lYIJygB&biw=1366&bih=657&dpr=1)) icons?
Sincerely

**Comment by archerchiu** [comment]
Hi, @colinreedmiller 
We are going to establish dashboard design tool. Many kinds of widgets to be dragged for designer, such as form, table, and chart aspects. Namely, designer is easy to know what kind of widget through icons. 
Thanks.

**Comment by lil-kim** [comment]
Updated and compiled list of icons for vol 14 - see first comment.

**Comment by yaooluu** [comment]
@lil-kim Please also add a "target" icon mentioned as "current step" at: https://github.com/vmware/clarity/issues/1633

**Comment by lil-kim** [comment]
@Stela,
I missed adding some icons from the comment on 10/25 from Archerchiu. (now added to consolidated list at the top of this page) Not all may be possible to translate into icons, but please do what you can. Thanks!

**Comment by stela** [comment]
> @stela,
> I missed adding some icons from the comment on 10/25 from Archerchiu. (now added to consolidated list at the top of this page) Not all may be possible to translate into icons, but please do what you can. Thanks!

@lil-kim @Stela-Stamenkova Wrong "stela" I'm afraid!

**Comment by lil-kim** [comment]
@stela Thanks so much for letting me know! :-)

**Comment by Stela-Stamenkova** [comment]
Hello everyone!
I am attaching the icons, let me know how they work!
Best,
Stela
[Vol.14_expanded.zip](https://github.com/vmware/clarity/files/2808947/Vol.14_expanded.zip)

**Comment by Ergnos** [comment]
@Stela-Stamenkova , 
the filenames of the Capacitor, Inductor and Resistor are currently mixed up. 

Line_Capacitor -> Line_Inductor
Line_Inductor-> Line_Resistor
Line_Resistor -> Line_Capcitor

Regards.

**Comment by amellnik** [comment]
@Ergnos is correct.  I also think that the resistor and inductor symbols might need an additional zigzag/loop to be recognizable.  (See [this](https://commons.wikimedia.org/wiki/File:Resistor_symbol_America.svg) for example).

**Comment by Shijir** [comment]
@Ergnos Thanks for your feedback. I have addressed the issue in the PR.

@amellnik thanks for your feedback. I agree with your concern so I will talk to @Stela-Stamenkova and @lil-kim 

I am working on the PR right now. You can track it here: https://github.com/vmware/clarity/pull/3099

**Comment by lil-kim** [comment]
@Shijir, I modified the inductor and resistor icons based on feedback from @Ergnos 
 and @amellnik :
[inductor-resistor.zip](https://github.com/vmware/clarity/files/2847548/inductor-resistor.zip)

**Comment by amellnik** [comment]
@lil-kim Looks good!
