### ISSUE TITLE
vertical-nav width is not connected with responsive-nav panel width 

### ISSUE THREAD

**Issue by boeckMt** [vmware/clarity#2713]
## Describe the bug

if $clr-vertical-nav-width is bigger than $clr-sliding-panel-width or $clr-sliding-panel-width-sm, the clr-vertical-nav is not completely hidden for clr-nav-level-1 or clr-nav-level-2.

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v11-y1gaeo

1. Set [clr-nav-level]="1" on clr-vertical-nav.

2.  Go to styles.scss and set $clr-vertical-nav-width: 16rem;
or if css: go to src\app\app.component.css and set 
.clr-vertical-nav {
  width: 16rem;
}

3.  Resize the Window so nav get's collapsed.

## Expected behavior

the nav should be completely hidden

## Versions

**App**

* Angular: [6.1.9]
* Node: [8.9.1]
* Clarity: [0.13.4]

**Device:**

* Type: [Pc]
* OS: [Win]
* Browser [chrome]
* Version [69]

**Comment by boeckMt** [comment]
i think this can fix it.
in _responsive-nav.clarity.scss
```
+@mixin nav-transformX($width) {
+  @if $clr-vertical-nav-width > abs($width){
+    @if($width < 0){
+      transform: translateX(-1 * $clr-vertical-nav-width);
+    }@else{
+     transform: translateX($clr-vertical-nav-width);
+    }
+  }@else{
+    transform: translateX($width);
+  }
+}
...

@media screen and (max-width: map-get($grid-breakpoints, md)) {
    .main-container {
      .header-hamburger-trigger,
      ...
      .header-nav.clr-nav-level-2,
      .subnav.clr-nav-level-2,
      .sub-nav.clr-nav-level-2,
      .sidenav.clr-nav-level-2,
      .clr-vertical-nav.clr-nav-level-2 {
        @include sliding-nav-positioning(0, 0, 0, auto);
-       transform: translateX($clr-sliding-panel-width);
+      @include nav-transformX($clr-sliding-panel-width);
        ...
      }
...
@media screen and (max-width: map-get($grid-breakpoints, sm)) {
    .main-container {
     ...
      .header-nav.clr-nav-level-1,
      .subnav.clr-nav-level-1,
      .sub-nav.clr-nav-level-1,
      .sidenav.clr-nav-level-1,
      .clr-vertical-nav.clr-nav-level-1 {
-        transform: translateX(-1 * $clr-sliding-panel-width-sm);
+       @include nav-transformX(-1 * $clr-sliding-panel-width-sm);
      }

      .header-nav.clr-nav-level-2,
      .subnav.clr-nav-level-2,
      .sub-nav.clr-nav-level-2,
      .sidenav.clr-nav-level-2,
      .clr-vertical-nav.clr-nav-level-2 {
-        transform: translateX($clr-sliding-panel-width-sm);
+       @include nav-transformX($clr-sliding-panel-width-sm);
      }
    }
...
```

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
