### ISSUE TITLE
Tooltip doesn't look good in Mac Safari

### ISSUE THREAD

**Issue by nghiado** [vmware/clarity#2715]
![screen shot 2018-10-09 at 6 41 53 pm](https://user-images.githubusercontent.com/1259031/46705001-28fd9900-cbf3-11e8-9566-f47d3b778702.png)

**Comment by gnomeontherun** [comment]
Looks like the `.tooltip>.tooltip-content:before` bottom rule is rendered slightly lower in Safari than others, reducing from `-.375rem` to `-.3rem` moves it up better, need to check across browsers.
