### ISSUE TITLE
In clr-wizard <ng-template clrPageButtons> button disable not working

### ISSUE THREAD

**Issue by pareshgami** [vmware/clarity#2716]
## Describe the bug
I have to use custom NEXT button in each clr-wizard-page so I am using `<ng-template clrPageButtons></ng-template>` and I am using `[clrWizardPageNextDisabled]` for making button disable in each step.

In first step button disable is working before some days. Now that is not working.
```
<clr-wizard>
    <clr-wizard-page [clrWizardPageNextDisabled]="!stepFirstNextButtonEnable">
        <ng-template clrPageTitle>Platforms</ng-template>
        <ng-container>
            ....
        </ng-container>
        <ng-template clrPageButtons>
            <clr-wizard-button class="custom-btn-primary" [type]="'custom-next-step-first'">NEXT</clr-wizard-button>
        </ng-template>
    </clr-wizard-page>

    <clr-wizard-page [clrWizardPageNextDisabled]="!stepSecondNextButtonEnable">
        <ng-template clrPageTitle>Platforms</ng-template>
        <ng-container>
            ....
        </ng-container>
        <ng-template clrPageButtons>
            <clr-wizard-button class="custom-btn-primary" [type]="'custom-next-step-second'">NEXT</clr-wizard-button>
        </ng-template>
    </clr-wizard-page>
</clr-wizard>
```

## How to produce bug

Use `<ng-template clrPageButtons>` inside  `<clr-wizard-page/>` tag like below code
```
<ng-template clrPageButtons>
            <clr-wizard-button class="custom-btn-primary" [type]="'custom-next-step-first'">NEXT</clr-wizard-button>
</ng-template>
```

**Comment by mathisscott** [comment]
Hi @pareshgami 
[Could you provide us with a stackblitz demonstrating the issue](https://stackblitz.com/edit/clarity-light-theme-v013)?

**Comment by pareshgami** [comment]
Please check below link for an issue.

https://stackblitz.com/edit/angular-clr-wizard

**Comment by pareshgami** [comment]
The issue figured it out.

`<clr-wizard-button type="custom-next">NEXT</clr-wizard-button>`

We need to use `type = "custom-next"`
