### ISSUE TITLE
Improve guidelines on unit tests

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#2719]
## Summary

**What is the change?**

Improve/complete our unit testing guidelines.

**Why should it go in Clarity?**

Currently, our unit test guideliness are incomplete. We need to have more complete and clear unit testing guidelines, which will help both internal and external contributors to write more consistent and quality unit tests.

**Does this change impact existing behaviors? If so how?**

In the short term, I don't expect this change to impact our existing tests. However, it will impact the way developers would write their unit tests as soon as the new unit testing guidelines and rules get effective.

**Comment by mathisscott** [comment]
@Shijir + @youdz 
Can you two chat about this?

**Comment by gnomeontherun** [comment]
Closing due to being stale, we can always put content together as needed.
