### ISSUE TITLE
Tooltip symbol issue in latest Sketch.app

### ISSUE THREAD

**Issue by samsonw** [vmware/clarity#2720]
## Describe the bug

Tooltip symbol doesn't look good in latest verions of Sketch.app (52.2).

## How to reproduce

1.  Import `Clarity-Template-0.12.7.sketch` as library in sketch. 
2.  Insert a `Alert / Tooltip` symbol into the document

![image](https://user-images.githubusercontent.com/44293/46779552-ed75e280-cd4a-11e8-8fce-22eba94f3347.png)

**Comment by gnomeontherun** [comment]
@reddolan

**Comment by AbhiAgarwal192** [comment]
@samsonw Checking this one.

**Comment by mathisscott** [comment]
@reddolan 
Do you know what might be happening here?

**Comment by reddolan** [comment]
Another designer just pinged me about this too. I am not sure what happened, older versions didn't have it broken. Might have been an update in Sketch that botched it. Fixing and adding to our next release

**Comment by gnomeontherun** [comment]
Released on website now.
