### ISSUE TITLE
[core] improve reusability of animation code in Clarity

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#273]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

It would be nice to re-use functions that generate animation metadata (we have collapse, fade, fade-slide, and slide) so that the animations are centralized and standardized.

### Actual behavior

As part of AoT refactor, the animation metadata has been hard-coded into the components (Modal and StackBlock). Let's revisit this to evaluate if we can import functions into the component decorator as we used to before the AoT. There might be a way to make ngc happy. Need to investigate.

### Reproduction of behavior

N/A

### Environment details

* **Angular version:** 2.2.X

* **Clarity version:** 0.8.X

* **OS and version:** All

* **Browser:** All

**Comment by adityarb88** [comment]
@jeeyun: May be this helps: https://github.com/btroncone/ngrx-store-localstorage/issues/13

**Comment by gnomeontherun** [comment]
Closing as stale.
