### ISSUE TITLE
Website: Wrong example code for textarea in helper and error messages section

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2732]
## Describe the bug

The example code is for inputs.

<img width="882" alt="screen shot 2018-10-13 at 08 41 40" src="https://user-images.githubusercontent.com/3655915/46902334-035ae300-cec4-11e8-8885-9d6b091a0414.png">

## How to reproduce

1.  Go to https://vmware.github.io/clarity/documentation/v0.13/textarea
2.  Scroll down to "Helper and error messages"
3.  See wrong code example

## Expected behavior

Code example for textareas.

**Comment by gnomeontherun** [comment]
Fixed in website branch, deploying now. Thanks for the report!
