### ISSUE TITLE
Vertical Nav Group expand/collapse isn't triggering events.

### ISSUE THREAD

**Issue by JustinBerger** [vmware/clarity#2733]
## Describe the bug

It doesn't appear 

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v013-ekaege

1.  If menu is not open (small screen) click the hamburger menu icon.
2.  Click on 'People' menu group to expand
3.  Click on 'People' menu group to collapse
4.  Expand event never fires, which causes it to not log the event.

## Expected behavior

Expanding/Collapsing vertical nav groups should fire expandedChange events.

## Versions

**App**

* Angular: 6
* Clarity: 0.13.2

**Device:**

* Type: Desktop
* OS: Windows
* Browser: Firefox
* Version: 62

* Browser: Chrome
* Version: 69

## Additional notes

I am trying to add some custom functionality based on when the section is expanded or collapsed.

This is what I'm working on: http://www.animebanzai.org/scheduleApp/events
Code lives here: https://github.com/AnimeBanzai/ScheduleAppWeb

**Comment by youdz** [comment]
The good news for you is that this is a documentation issue, not a bug. 😄 

The vertical nav follows our old and way too verbose conventions, so the two-way binding is `[(clrVerticalNavGroupExpanded)]` 😳, not `[(expanded)]`.

This means if you just want to listen to the output, you have to use `(clrVerticalNavGroupExpandedChange)`. I updated your StackBlitz just changing that output, and it works fine now: https://stackblitz.com/edit/vertical-nav-group-expand-listener?file=src/app/person-nav/person-nav.component.html
