### ISSUE TITLE
Already clicked "Select All" button remains enabled

### ISSUE THREAD

**Issue by zlevai** [vmware/clarity#2734]
## Describe the bug

"ALLE AUSWÄHLEN!!" button remains enabled once that was clicked. So button does not reflect that all the check-boxes are checked in.
Note: If I check in all items manually checkbox by checkbox then ALLE AUSWÄHLEN! button becomes to disabled (works by expected).

## How to reproduce

1.  Go to https://vmware.github.io/clarity/documentation/v0.13/datagrid/hide-show
2.  Click on column option button/toggle below the grid -> Column option panel opens
- Click on ALLE AUSWÄHLEN! button -> All check-boxes becomes to checked in
Actual result: "Select All!" is enabled

## Expected behavior
Expected result: "Select All!" is disabled

## Versions

Angular CLI: 6.1.9
Node: 8.11.2
Clarity: 0.13.4

Device:
Type: Dell latitude E5550
OS: Windows 10 64bit
Browser: Google Chrome, Version 69.0.3497.100 (Official Build) (64-bit)

## Additional notes

If I check in all items manually checkbox by checkbox then ALLE AUSWÄHLEN! button becomes to disabled (works by expected).

**Comment by AbhiAgarwal192** [comment]
@zlevai Do you mean after you click on "Select ALL" button, the name for the button should change to something like "Unselect All"?

**Comment by zlevai** [comment]
@AbhiAgarwal192  Not. I would expect to work the same way when you check in all the checkbox manually one by one. Then "Select ALL" button changes to disabled, so that is greyed and not clickable.

**Comment by cbhumireddy** [comment]
@zlevai @AbhiAgarwal192 : I have already raised PR first day itself. Waiting for one more approval to merge. See [PR](https://github.com/vmware/clarity/pull/2737) for more details.
