### ISSUE TITLE
Not able to provide clr-icon via data binding

### ISSUE THREAD

**Issue by sevenOneHero** [vmware/clarity#2740]
## Description
So when you want to have an clr-icon dynamic, meaning to say , it should come from a variable declared within a Typescript / JS file , that fails.

## How to reproduce - > Put following line in angular clr project

`                <clr-icon [shape]="icon" class="is-solid"></clr-icon>
`

## Expected behavior

Its pretty standard stuff in angular, that the input to directive can be bound to a variable, so it should work . 

## Versions

**App**

* Angular: 6+
* Clarity: 0.13

**Comment by enoquemoises** [comment]
I do it like this:

`<clr-icon [attr.shape]="icon"></clr-icon>`

**Comment by youdz** [comment]
Clarity icons are custom elements, they're not Angular. So the answer @enoquemoises gave is the correct one, you have to bind to the shape attribute just like you do with any standard HTML element.

See https://stackoverflow.com/questions/46914238/how-can-i-dynamically-change-the-shape-of-a-clr-icon-custom-element and https://stackoverflow.com/questions/46928487/how-to-set-shape-attribute-of-clr-icon for similar answers on StackOverflow.
