### ISSUE TITLE
z-index to filter popup's on columns when hover or click to popup's in datagrid

### ISSUE THREAD

**Issue by Chandu3245** [vmware/clarity#2741]
## Describe the bug

Click open all filter popup's of datagrid (dont close any), hover/click on any popup to close/edit, it still below it's successor popup. 

## How to reproduce

 Click open all filter popup's of datagrid, hover/click on any popup to close/edit the popup still below it's successor popup. 

## Expected behavior

After opening required filter popup's, dont close any and going back to a particular filter popup, the popup should bubble up to top to let user see complete popup along with close button. may be z-index would suffice on selected filter popup.

## Versions

**App**

* Angular: [ 4.3.0]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.10.0]

**Device:** Windows

* Type: [e.g. MacBook]
* OS: [10]
* Browser [e.g. chrome, ]
* Version [e.g. 67]

## Additional notes

please let me know if there is any workaround.

**Comment by mathisscott** [comment]
I believe this will be solved once we take on #1632
