### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by jrautenberg** [vmware/clarity#2745]
## Summary

_Can we have a scheduler to allow for any number (or combo) of days in a week to be selected and then for the day combo selected set a specific time frame ._

* There is no scheduler in Calrity right now (surprisingly)
* WThis is an important function for our users across several Horizon products ?
* Existing experiences consist of multi select drop down menus that make it difficult for the user to see the schedule as a whole. The user is also forced to "name" the schedule. For example "Mon. - Wed." ?
* If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?
Lightning design system has something similar. I
m not sure we need the calendar month view though.
https://www.lightningdesignsystem.com/components/datetime-picker/

## Workarounds

_the work around is what we have now. We are looking for a more elegant solution_

**Comment by gnomeontherun** [comment]
This sounds very specific for a small set of applications, mostly those which have to schedule maintenance windows or something similar. Please provide more complete and detailed use cases for us, otherwise we won't be able to understand what you really are asking for.

**Comment by jrautenberg** [comment]
This is a control that users would set in order to optimize how and when Virtual Machines would be spun up and on which pod/ per cloud deployment. This control helps users run their business more efficiently. Attached is a screen shot of what we have now. We are trying to stay within the current Clarity system. However, it is strange to summarize the number of days selected and ask the user to name the schedule. From the users perspective, it seems more natural to show the days selected and the time frame. 

![screen shot 2018-10-17 at 1 11 15 pm](https://user-images.githubusercontent.com/44240984/47113808-d5043d00-d20e-11e8-8185-a5274fd74ac1.png)

**Comment by gnomeontherun** [comment]
Thanks for the details, but this is very application specific and not something that Clarity is likely to build or support. If we look at this screenshot, we help with the inputs and form controls but the complex combination is specific to your application, which none of them appear to follow Clarity right now.

Also the lightning demo is only a date/time picker, which we have a date picker already. The time picker has a tickets #2322 and #474, which might be useful to follow for additional features you might like.

I understand this is a complex user experience, but its very specific to a small set of applications. I'm going to close this as outside of the scope of Clarity.
