### ISSUE TITLE
clrDgRowSelection breaks column width on Datagrids

### ISSUE THREAD

**Issue by daverickdunn** [vmware/clarity#2747]
Using `[clrDgRowSelection]` on a "Single Selection" Datagrid (and perhaps others), causes the first column to aggressively consume row width.

[StackBlitz Reproduction](https://stackblitz.com/edit/clarity-dark-theme-v013-sjynx1?file=src%2Fapp%2Fapp.component.html)

Columns are responsive and equal width.

Clarity v13.

**Comment by youdz** [comment]
This was fixed by #2670, and will be part of today's release.
