### ISSUE TITLE
Tooltip should have position "auto" to make the content stay inside the viewport.

### ISSUE THREAD

**Issue by nghiado** [vmware/clarity#2762]
## Summary

* What is the change?
Add clrPosition="auto" or make sure the tooltip will be always visible inside the viewport
* Why should it go in Clarity?
We often have problem with tooltip position and have to set them case by case based on our UX to make sure content is always visible inside the viewport
<img width="450" alt="screen shot 2018-10-19 at 2 05 17 pm" src="https://user-images.githubusercontent.com/1259031/47238934-63142b00-d3a9-11e8-891a-d931df8c7314.png">

* Does this change impact existing behaviors? If so how?
Should not, just make it better for developer.
* If this change introduces a new behavior, is this behavior accessible?

**Comment by nghiado** [comment]
Same request for Signposts

**Comment by nghiado** [comment]
Hope we can have something like Bootstrap placement=auto
https://getbootstrap.com/docs/4.1/components/tooltips/#options

**Comment by hippee-lee** [comment]
This is a known issue. Please subscribe to these issues for updates: #1262 and #2683.

Closing as a duplicate.
