### ISSUE TITLE
wrong modal appearance in sidenav

### ISSUE THREAD

**Issue by AK2083** [vmware/clarity#2764]
## Describe the bug

I use the sidenav with a nav list. In the nav list is a button which trigger the modal. 
On small screens (tested in chrome developer tols) the modal appears only on the sidenav and not centered on the screen.

## How to reproduce

[Stackblitz](https://stackblitz.com/edit/clarity-6vfknq)

1.) On small screens: press button on the top left side to open the sidenav
2.) Press Toggle-Button
3.) Modal appears in sidenav

## Expected behavior

I would expect the modal appears on whole screen (centered)

## Versions

**App**

* Angular: [6.1.10]
* Node: [10.11.00]
* Clarity: [00.13.06]

**Device:**

* Type: [Surface Pro]
* OS: [Win 10]
* Browser [Chrome]
* Version [70.0.3538.67]

**Comment by gnomeontherun** [comment]
You should move the modal out of the sidenav into the main body and it works fine. There is some CSS that we need to make the nav work that causes this, so the solution is to just move the modal outside of the nav.
