### ISSUE TITLE
Date picker display issues when used inside table (chrome, firefox)

### ISSUE THREAD

**Issue by gzink** [vmware/clarity#2765]
## Describe the bug

When using the date picker inside of a table, some colums inside the date picker are not shown.

## How to reproduce

```html
<table class="table">
   <tbody>
       <tr>
         <td>
            <input type="date" clrDate>
         </td>
       </tr>
   </tbody>
</table>
```

https://stackblitz.com/edit/clarity-light-theme-v013-6thcd1?file=src/app/app.component.html

## Expected behavior

All columns of the month are shown.

## Versions

**App**

* Clarity: 0.13 (0.11 also does not work)

**Device:**

* OS: Ubuntu 18.04
* Browser Firefox 62, Chrome

**Comment by gzink** [comment]
The columns are missing in the day view

![calendar](https://user-images.githubusercontent.com/7340266/47308482-0c6d5200-d632-11e8-99c6-259160c2e280.png)

**Comment by gnomeontherun** [comment]
Yeah, some table cell styles are bleeding into the date picker. This is a bug that we need to address, but the workaround is to avoid using it in a table until then.

**Comment by GeekAb** [comment]
The issue is with padding added to table cells. 

`.table td, .table th {
    line-height: .583333rem; 
    padding: .458333rem .5rem;
    text-align: center;
}`

The workaround is to remove this padding in case of calendar-cell.
Something like below will solve it and will not interfere with anything else.

`table.calendar-table td.calendar-cell {
    padding: 0;
}`
