### ISSUE TITLE
Angular 7 Support

### ISSUE THREAD

**Issue by daverickdunn** [vmware/clarity#2767]
## Describe the bug
Running:
`ng update @clr/angular`

Results in the follwoing error:
`Package "@clr/angular" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0", would install "7.0.0")`

## How to reproduce
Have existing project on Angular 6.x.x and Clarity 0.13.x

Follow the recommended upgrade procedure as described here: [Step 6: Update Clarity](https://vmware.github.io/clarity/documentation/v0.13/get-started)

First upgrade Angular:
`ng update @angular/core`

Then try upgrade Clarity:
`ng update @clr/angular`

## Expected behavior
Clarity supports Angular 7.x.x

## Versions
Angular: 7.0.0
Node: 9.11.1
Clarity: 0.13.1-patch.1

**Device:**
OS: Windows 10 x64

**Comment by gnomeontherun** [comment]
This is part of the 1.0 milestone and will be coming out soon. This is already covered by #2729 and #2154. Watch for the 1.0 beta and RC releases to update to Angular 7.

**Comment by daverickdunn** [comment]
Alright, thanks.
