### ISSUE TITLE
Deep hierarchy use case needs documenting for Sidenav component

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2768]
## Summary

_Documentation says: Use Sidenav for a navigation schema with a deep hierarchy._

But on a Clarity website and in the documentation there are only examples with 2 levels - collapsible nav element with a link inside.

It's not really clear how to have a collapsible link or how to have a collapsible nav element inside another one as if you just put it inside - it looks pretty terrible, because of its top margin.

So I'm not really sure if there is some undocumented method to achieve this, or I just need to use collapsible nav element inside another one and to remove its top margin and add some negative left margin with CSS? With updated margins it may look like this:

![image](https://user-images.githubusercontent.com/32732457/47303046-a8478f80-d62b-11e8-8225-bd9b23abfd3d.png)

And it's fine, but is there any default way?

* Add examples for deep hierarchy inside Sidenav

## Use case
When Sidenav is used for navigation with deep hierarchy

## Workarounds
The only workaround now it to change margins of nested collapsible nav element with something like this:
```
.nav-group .nav-group{
  margin-top: 0;
  margin-left: -31px;
}
```

**Comment by hippee-lee** [comment]
Hi @sdurnov, 

We do say in our navigation docs that ```If your app has more than two levels of navigation, you’ll need to build a custom solution. At three levels, the navigation becomes increasingly nested and too complex for Clarity to provide a single responsive solution.```

In the use case you are describing you might try combining different Navigation components. Here are two ideas:

1. Use the SideNav or Vertical Nav with Tabs 
2. Use a SubNav component with Vertical Nav or Sidenav component

I'm going to close this as deep navigation hierarchy's in SideNav or Vertical Nav are not use cases Clarity supports.
