### ISSUE TITLE
CSS Build Optimizations

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#2769]
As part of the CSS changes for 2.0 it would be nice to include the following build modifications:

1. Differentiate between _public_ and _private_ css classes and only prefix the _public_ classes
2. Add a check/tool that can compare the css classes output for a build against a previous or _golden_ file of the last version
    - http://www.alanhart.co.uk/tools/compare-css.php
3. If possible Generate the CSS golden file from source as a base for developer documentation .

**Comment by mathisscott** [comment]
@hippee-lee 
The reason we prefix our classnames in CSS is to avoid collision with other CSS frameworks. I'm not sure that bringing over the private vs. public delineation from our TypeScript code would help in this regard (as suddenly we would have non-prefixed classnames again that could overwrite classnames from other CSS frameworks).

What are your thoughts on item 1?

**Comment by mathisscott** [comment]
But it isn't really possible for us to encapsulate our CSS inside our Angular components until after the custom elements riddle is solved. Moving all or part of our CSS into the component library would negatively impact people using the Clarity CSS in non-Angular projects.

**Comment by gnomeontherun** [comment]
I believe this won't be an issue any more once we are further along with Core. Going to close this.
