### ISSUE TITLE
Need for 'ReadOnly' style on Input Fields

### ISSUE THREAD

**Issue by kevinmcbride** [vmware/clarity#277]
**Select one ...**  (check one with "x")
```
[ ] bug
[ x ] feature request
[ ] enhancement
```

### Expected behavior

I was looking for a ‘read only’ style for an input field.  Seems like this should look different from the ‘disabled’ style.  Here is the look we want - id does not grey out the text — the value of the text is kinda important, not something we want to diminish.

The use case is a field in the form that tells the user what type of rule they are creating in their firewall.  In another context, the user can choose whether it is Allow or Deny, but in this context we only allow Allow type rules.  So in one sense, the field is disabled, but I have seen other design patterns that have a Read Only state where the text is fully visible/opaque.  Disabled state seems to suggest the field does not apply, but what we want to communicate is that this is the value and it is read only.

Here is the desired look:
![image](https://cloud.githubusercontent.com/assets/7705856/21399801/fc940dd2-c761-11e6-9034-bf691d30d54c.png)

### Actual behavior

Currently, only a disabled state is supported.  Here is what that looks like:
![image](https://cloud.githubusercontent.com/assets/7705856/21399781/e1964496-c761-11e6-965a-6cbc62f1a74c.png)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all]

**Comment by yenmade** [comment]
Adding this to the UX backlog to explore visual treatments for a 'read only' style.

**Comment by jaffoneh** [comment]
Spec for this landed in #656. Closing this one and will continue to follow up on implementation in #656.
