### ISSUE TITLE
Color palette doc-missing hex numbers and minor improvements

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#2784]
## Color palette documentation - minor bugs and improvements

3 issues to address:
1) In the dark theme palette, 2 colors need to be added to the 'Background and Borders' set:
- #485764
- #6D7884
See attached image for details

2) In Light theme > Buttons and app-level alerts
The color #CCCCCC is labeled with white text. It should be black text
The green #318700 is labeled with a white "A" on the left side. It should show both a white and a black "A" to denote that both text colors are accessible on it. See attached image for details

3) Problem: People have commented that they didn't see the tabs under Functional Colors for Light theme and Dark theme. It may become more visible if more space were added above and below the tab. See image for recommended spacing.
--------------------------
IMAGES for issues above:
**Issue 1:**
![image](https://user-images.githubusercontent.com/23196444/47534689-2fd01100-d86d-11e8-907e-6949d3ca3a7e.png)

**Issue 2:**
![image](https://user-images.githubusercontent.com/23196444/47535023-6eb29680-d86e-11e8-91ea-e153baf1f8f9.png)

**Issue 3:**
![image](https://user-images.githubusercontent.com/23196444/47535038-7f630c80-d86e-11e8-9a51-93fc68dc0825.png)

**Comment by Jinnie** [comment]
I have a question about issue 3. The 48px margin, that needs to be reduced to 36 px is coming from a global style for all <h6> elements on the site. Changing it will have effect on many places. For example, the vertical spacing between cards lower on the same list, will also be reduced.
My suggestion is to stay safe and only add the margin preceding the tab labels and leave the ones below them as they currently are. Any attempt to fix the local instance only will lead to complications, or hacky solutions.
Please, advise.

**Comment by Jinnie** [comment]
Btw, the current margin (below labels) is not 0, it is 12px. So we'll have the same margin1 + margin2 total value. I can safely change this one to 24px, as requested, but we may get too large whitespace there on the light theme (+12px compared to now).

**Comment by Jinnie** [comment]
#318700 will be globally substituted to #2F8400, as requested in #2535, and it will remain accessible only against white.

**Comment by lil-kim** [comment]
Hi @Jinnie 
Thanks for explaining the problem with issue #3. Let's go with your suggestion.

**Comment by lil-kim** [comment]
@Jinnie 
The white space in the light theme example above looks good to me. Now there's enough space around the tabs that it doesn't get lost in the page. Thanks!
