### ISSUE TITLE
Is’t possible to use components without Angular?

### ISSUE THREAD

**Issue by biapar** [vmware/clarity#2785]
Is’t possible to use components without Angular? Like Datagrid, signpost, etc..
Thanks.

**Comment by gnomeontherun** [comment]
Yes, read the https://vmware.github.io/clarity/documentation/v0.13/get-started section about HTML/CSS only version. Only some components work without Angular, which you can see which ones require Angular by viewing our documentation https://vmware.github.io/clarity/documentation/v0.13 and the NG column denotes which need Angular.

**Comment by biapar** [comment]
So, for example, I cannot use the datagrid without Angular and the other components with Dot in the ng column 🤔.
