### ISSUE TITLE
[Header] Nav-link with icon + text - how?

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2788]
## Summary

There's no example of how to create icon + text item in header-actions.
There's only a single icon, or just text, or text with drop-down, but no icon + text.
So, it's not clear how to implement it best way.
* What is the change?
Add another class like **nav-icon-text**, which will provide correct layout and opacity for such item. Right now, clr-icon has _position:absolute_ if using **nav-link** class, or it misses opacity if not using **nav-link**.
* Why should it go in Clarity?
Because there are use cases for this, so it will reduce the amount of useless CSS and will help users follow UI guidelines without guessing margins/paddings for self-made replacements.
* Does this change impact existing behaviors? If so how?
No
* If this change introduces a new behavior, is this behavior accessible?
Should be

## Use case

_Provide some specific details about how this change would improve your application and use case._

Displaying username, for instance.

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_
![image](https://user-images.githubusercontent.com/32732457/47647397-eb53b680-db87-11e8-906c-94ae3b4c50fe.png)

## Workarounds
_Is there a workaround for this feature at the moment, even if it is less than ideal?_

Either not using nav-link or nav-icon class, and stying your item completely as you need, or using the nav-link class, but overriding icon position and content spacing.

**Comment by colinreedmiller** [comment]
@sdurnov As I read the issue, the file below gives appropriate guidance for building a class such as nav-icon-text as you suggest. Can you comment as far as this fulfilling the request?

![#2788-header-icon.png](https://images.zenhubusercontent.com/5bc78fe0ba9b001064ad7062/c33d105b-64a1-4bca-99ca-1978d28fb495)

**Comment by sdurnov** [comment]
@colinreedmiller This is exactly what I expected to see

**Comment by colinreedmiller** [comment]
@sdurnov - Thanks for the quick reply. I'll take this up with Clarity engineering based on this design.

**Comment by coryrylan** [comment]
@colinreedmiller is this good to go for dev implementation? I can get started on this but wasnt 100% sure since you are still assigned.

**Comment by colinreedmiller** [comment]
@coryrylan - good to go. The spec is simple because it seems all that is required. Let me know if you need anything additional.

**Comment by coryrylan** [comment]
@colinreedmiller After some investigation it looks like the icon with text in top level nav is documented as not recommended. Is this something we should update in the documentation?

https://clarity.design/documentation/header 

![Screen Shot 2019-03-14 at 2 12 33 PM](https://user-images.githubusercontent.com/2021067/54384850-3ec03000-4663-11e9-9c5f-4814f09151f2.png)

**Comment by colinreedmiller** [comment]
Documentation needs update to address this exception.
