### ISSUE TITLE
Using Side Nav and Content Area in RouterOutlet renders really bad!

### ISSUE THREAD

**Issue by callen5914** [vmware/clarity#2791]
## How to reproduce

_Dude are you seriously going to make import my ENTIRE project to stackblitz that app blows any way!_

```
<clr-main-container>
  <app-header></app-header>
  <router-outlet></router-outlet>
</clr-main-container>
```

```
<div class="content-container">  
  <nav class="side-nav">
    <section class="sidenav-content">
      <a href="..." class="nav-link active">
        Nav Element 1
      </a>
      <a href="..." class="nav-link">
        Nav Element 2
      </a>
      <section class="nav-group collapsible">
        <input id="tabexample1" type="checkbox">
        <label for="tabexample1">Collapsible Nav Element</label>
        <ul class="nav-list">
          <li><a class="nav-link">Link 1</a></li>
          <li><a class="nav-link">Link 2</a></li>
        </ul>
      </section>
      <section class="nav-group">
        <input id="tabexample2" type="checkbox">
        <label for="tabexample2">Default Nav Element</label>
        <ul class="nav-list">
          <li><a class="nav-link">Link 1</a></li>
          <li><a class="nav-link">Link 2</a></li>
          <li><a class="nav-link active">Link 3</a></li>
          <li><a class="nav-link">Link 4</a></li>
          <li><a class="nav-link">Link 5</a></li>
          <li><a class="nav-link">Link 6</a></li>
        </ul>
      </section>
    </section>
  </nav>
  <div class="content-area">
      <h1>Broke!!!!!!!!!!!!!!!!</h1>
    </div>
</div>
```

## Expected behavior

_That the side nav wouldn't break when loading throught router outlet!._

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

Mac on the latest of everything!
Angular 6+
Clr latest !

## Additional notes

_Add any other notes about the problem here._

**Comment by whizkidwwe1217** [comment]
@callen5914 You can structure your navigation elements like this:

app.component.html
```html
<clr-main-container>
    <clr-header></clr-header>
    <router-outlet></router-outlet>  <!-- This is the router outlet of the primary navigation -->
</clr-main-container>
```
home.component.html 
```html
<div class="content-container">
    <main class="content-area">
        <!-- You can put an optional element here -->
        <router-outlet></router-outlet> <!-- This holds child routes of Home primary navigation item -->
    </main>

    <nav class="sidenav">
        <section class="side-navcontent">
            <!-- Put your sidenav items here -->
        </section>
    </nav>
</div>
```
dashboard.component.html
`<!-- Other primary navigation items -->`

Check this sample project I put up in stackblitz: [https://stackblitz.com/edit/clarity-light-theme-v013-s4spkv](https://stackblitz.com/edit/clarity-light-theme-v013-s4spkv)

**Comment by callen5914** [comment]
@whizkidwwe1217 I think something has gone bad in my codebase as I did just you recommended and the side nav is still broke. I am going to try to start a whole new project and see if it duplicates.

**Comment by gnomeontherun** [comment]
The source of your problem is that the CSS classes and DOM structure for the layouts are sensitive and if you have extra elements (like `<router-outlet>`) that break the expected hierarchy then it won't display correctly. You can break the layout in many ways by not having the right DOM structure, so you need to handle that properly.
