### ISSUE TITLE
[WEBSITE] Error building locally

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#2793]
## Describe the bug

Following the instruction reported [here](https://github.com/vmware/clarity/wiki/Building-the-Website)

I'm getting the 404 page

## How to reproduce

Follow the instruction reported [here](https://github.com/vmware/clarity/wiki/Building-the-Website)

Open the browser at `http://localhost:4200` and click on "Documentation" in the header

<img width="1270" alt="screenshot 2018-10-30 at 08 53 30" src="https://user-images.githubusercontent.com/3706809/47703963-41753800-dc22-11e8-8288-61f71d0ca4b6.png">

## Expected behaviour

The website renders properly

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

I contributed to the website last week and everything was working

**Comment by gnomeontherun** [comment]
This is not an error actually, just not well documented. Since we're in a beta/rc phase, the `latest` directory now points to 1.0, but 1.0 is not the default version. You have to modify the URL manually to change the `v0.13` to `v1.0` for it to work.

**Comment by mcosta74** [comment]
thanks

**Comment by srikanthps** [comment]
Does not work for me.
I downloaded the master branch's source - and I dont get same view as we see on production website.

![image](https://user-images.githubusercontent.com/102016/58752435-51ad0880-84cc-11e9-9fd8-7ca0b65eb697.png)

**Comment by hippee-lee** [comment]
I'm certifying the latest Angular packages (8.0.0) I missed a couple of the @`@ViewChild` changes in the website. Please take a look at PR https://github.com/vmware/clarity/pull/3405 and lmk there is you see anything else.
