### ISSUE TITLE
Create Issue Template for Icon requests

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#2796]
Github issue template for new icon requests - requester must specify the following:
1. Specify what the requested glyph signifies.
2. Specify the use case and product(s) where this icon will be used.

**Comment by gnomeontherun** [comment]
@colinreedmiller Do you have specific language you would like? We just need a bit of markdown describing what you want to ask in order to make the template. See https://raw.githubusercontent.com/vmware/clarity/master/.github/ISSUE_TEMPLATE/feature-request.md for an example

**Comment by colinreedmiller** [comment]
name: Icon request
about: Proposal for a new icon
---

## Summary

* What is the icon?
* What does the requested icon signify?
• What is the use case for this icon?
• In which product(s) will this icon be used?

## Use case

_Provide some specific details about how this icon would improve your application and use case._

## Examples

_Are there any examples of similar icons with similar uses?_

## Workarounds

_Is there a workaround for this at the moment, even if it is less than ideal?_
