### ISSUE TITLE
Is there an equivalent for stepper?

### ISSUE THREAD

**Issue by buinauskas** [vmware/clarity#2802]
Good day!

Material and PrimeNG support a stepper component that let display progress through a sequence of logical and numbered steps.

Is there a equivalent in Clarity, or if not equivalent, but rather a recommended way to tackle this problem?

Wizard seemed nice, however in my case different users will be performing these actions, which feels strange.

**Comment by gnomeontherun** [comment]
You can see the full list of components on our documentation, which depending on your exact use case might provide what you need. As far as a traditional accordion/stepper, we have a design spec but have not yet implemented it. Follow this ticket for progress on the accordion and when it might be available. https://github.com/vmware/clarity/issues/2452
