### ISSUE TITLE
Inline DatePicker?

### ISSUE THREAD

**Issue by alfredma1117** [vmware/clarity#2806]
Hi, is it possible to display the datepicker (the calendar?) inline?
I really like the look of the datepicker but I haven't figured out a way to display it inline...

Thanks!
Alfred

**Comment by gnomeontherun** [comment]
Currently this is not a feature or part of the design spec. It is always assumed to be a popover experience tied to an input. You can see the larger vision for the date picker here #474 and comment if you have additional use cases there to keep track of it.
