### ISSUE TITLE
Login page design enhancements

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2807]
## Summary

The login screen has some design concerns, and needs some attention to detail.

* The vertical rhythm is does not flow well
* There are some small details, padding/margins/spacing that need perfection
* It doesn't use form labels properly

## Use case

Apps that need logins with excellent login screens.

## Examples

google.com

## Workarounds

Just manual CSS overrides.

**Comment by mathisscott** [comment]
This will also require reaching out to VMware product teams to gauge impact on products currently using Clarity.

**Comment by gkhadK** [comment]
@gnomeontherun I understand this bug is for login page improvements. But just wanted to check if we are tracking the placeholder label issues all together here or in a separate bug? Along with login page, other Impacted components are - Datalist input fields, forms. text areas, inputs etc. Please advise.

**Comment by gnomeontherun** [comment]
There are some examples on the website today that don't have labels, but those are documentation issues and not problems with Clarity itself. We have other issues for missing labels in documentation that probably cover all of the cases.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
