### ISSUE TITLE
The custom filter component does not emit any action events of changing

### ISSUE THREAD

**Issue by alpha1988** [vmware/clarity#2814]
## Describing the bug
After crossing between modules templates the component that inside 'clr-dg-filter'  
 that have own list of checkbox filters does not emit any 'click', 'change' events of this checkboxes.

## Reproduction of behavior
1) Create couple modules that imoprting into the RoutingModule with lazyLoading
2) To navigate betwing them use RouterLinks
2) On page 'A' we create DataGrid with custom filter that just have list of the <clr-checkbox> according example from documentation. It's works fine.
3) Open page 'A' and use filtering.
4) Then open page 'B'
5) Return to the 'A' page. Open filter.
6) It's rendered but when you will click on it's checkboxes or use @HostLIstener on this custom-filter component. You will see that it is not emit any events. Like something is braking the event emitting.

**App**

* Angular: [6.1.9]
* Clarity: [0.13.4]

**Comment by gnomeontherun** [comment]
Please provide a demonstration of your issue using a StackBlitz (https://github.com/vmware/clarity#feedback) because its hard to know what you're doing with a custom filter otherwise.
