### ISSUE TITLE
ng add @clr/angular is not working on my mac.

### ISSUE THREAD

**Issue by callen5914** [vmware/clarity#2815]
So when I run the command
```
ng add @clr/angular 
```
It usually works just fine. But last night I spun up a brand new Angular project and again today and just for testing added the code needed for the "Header" element but it isn't rendering any of the styles. Is it possible something is corrupt on my computer? Because I looked in the issues and no one else is reporting this.
```

"private": true,
  "dependencies": {
    "@angular/animations": "^7.0.2",
    "@angular/common": "^7.0.2",
    "@angular/compiler": "^7.0.2",
    "@angular/core": "^7.0.2",
    "@angular/fire": "^5.1.0",
    "@angular/forms": "^7.0.2",
    "@angular/http": "^7.0.2",
    "@angular/platform-browser": "^7.0.2",
    "@angular/platform-browser-dynamic": "^7.0.2",
    "@angular/router": "^7.0.2",
    "@clr/angular": "^0.13.8",
    "core-js": "^2.5.4",
    "firebase": "^5.5.7",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.26",
    "@clr/ui": "^0.13.8",
    "@clr/icons": "^0.13.8",
    "@webcomponents/custom-elements": "^1.0.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.5",
    "@angular/compiler-cli": "^7.0.2",
    "@angular/language-service": "^7.0.2",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
```

![screen shot 2018-11-06 at 4 02 22 pm](https://user-images.githubusercontent.com/4636053/48093462-639c2680-e1dd-11e8-8333-4d135c927f44.png)
![screen shot 2018-11-06 at 4 02 51 pm](https://user-images.githubusercontent.com/4636053/48093473-6eef5200-e1dd-11e8-9a49-d6c829c7452c.png)

**Comment by hippee-lee** [comment]
Something looks modified in your `package.json`

I just ran 
```
$ ng new test-schematics
$ cd test-schematics
$ ng add @clr/angular
```

and got this (which works)
```
{
  "name": "test-schematics",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@clr/angular": "^0.13.8",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26",
    "@clr/ui": "^0.13.8",
    "@clr/icons": "^0.13.8",
    "@webcomponents/custom-elements": "^1.0.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^6.0.3",
    "@angular-devkit/build-angular": "~0.6.8",
    "typescript": "~2.7.2",
    "@angular/cli": "~6.0.8",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  }
}
```

**Comment by hippee-lee** [comment]
@callen5914 - also, please don't double post especially on closed issues (#2699).
First, when you post on closed issues it usually will not get attention right away. Second, double posting by asking the same question on a different issue and creating a new issue creates noise that takes away from triaging and addressing new and open issues.

**Comment by hippee-lee** [comment]
If you are still having problems, please post a public facing repository on github so that I can take a look.

**Comment by gnomeontherun** [comment]
Did it add the Clarity stylesheets in your `angular.json` file? Are there any errors in your browser or console? Do you have the right DOM structure?

**Comment by callen5914** [comment]
@gnomeontherun Let me check...

**Comment by callen5914** [comment]
I think that worked... Now for me to check the other replies.
```
 "styles": [
              "node_modules/@clr/icons/clr-icons.min.css",
              "node_modules/@clr/ui/clr-ui.min.css",
              "src/styles.css"
            ],
```

**Comment by callen5914** [comment]
My public facing repo as requested by @hippee-lee

**Comment by callen5914** [comment]
```
Your global Angular CLI version (7.0.4) is greater than your local
version (6.2.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
```

Maybe this has something to do with it?

**Comment by callen5914** [comment]
Okay guys, 
I don't know what happened but here's some thing I did tonight. 
1. download NodeJS 10.13.0
2. Re-ran the CLI install command globally 
3. made another ng test app 
4. added clr adn then pasted sample header code

Low and behold it seems to be behaving correctly. I really wish I knew what I was doing wrong. but there's break in there somewhere. I wonder if it was angular 7.0.4

If no one else has anything to add to my blunders please mark as closed and I apologize for the mistake.

**Comment by hippee-lee** [comment]
Hi @callen5914 - it sounds like there is something mis-configured with your project. In your comment above I'm not seeing a link to a github repo. If you can push your project to github and paste a link to the repo I'll be happy to take a look and see if I can help you get things sorted out.

**Comment by hippee-lee** [comment]
@callen5914 - That might be it. It sounds like you had already created a project with Angular 7 and then added Clarity. Our schematic for installing doesn't detect  that you have a dependency for Angular seven and the Clarity version supporting Angular 7 is still in release candidate status (https://vmware.github.io/clarity/news/1.0.0-beta.1)

If you have time can you try starting fresh and installing Clarity like this?
```
$ ng new test-project
$ cd test-project
$ ng add @clr/angular@next
```

`@clr/angular@next` tells schematics to install the version on npm tagged with `next` - which supports Angular 7. 

Then you should be able to copy/paste in the code examples. I'm really sorry you got caught inbetween the release of Angular(7) and the next version of Clarity ([1.0.0-beta.1](https://vmware.github.io/clarity/news/1.0.0-beta.1)) that will support it.

**Comment by callen5914** [comment]
@hippee-lee Thanks a bunch for the information

```
ng add @clr/angular@next
```
Seems like a pretty critical step. It's now mid-night here so I will try in the morning after I take the kids to school. You have been a big help!

Cheers

**Comment by gnomeontherun** [comment]
Going to mark this as resolved for now, since we also have another ticket to make this easier next time there is a major version change. See #2817 for that. Until then just use @next to get the latest pre-release.
