### ISSUE TITLE
Custom Sort Events

### ISSUE THREAD

**Issue by technbuzz** [vmware/clarity#2823]
## Use case

Pre-Sorted Columns can be achieved from server but I what if I the table is sorted on any other column order. Is there any way to emit events with [clrDgSortBy]?

## Examples

For instance if I want to store the sorting state in ngrx and update the store on each column filtering

**Comment by Jinnie** [comment]
Hi @technbuzz 
You should subscribe to (clrDgRefresh), it emits a common event for every operation that might lead to server-side data update, including - sorting, filtering, paging.
You can see details and the format of the event here:
https://vmware.github.io/clarity/documentation/v0.13/datagrid/server-driven
