### ISSUE TITLE
Scrolling bug - Non-Single-Structure

### ISSUE THREAD

**Issue by MrCrunsh** [vmware/clarity#2824]
## Describe the bug

The bug occurs as soon as the html file is distributed to individual files. The scroll behavior is not the same.

## How to reproduce

Version 1 (All in One Component)
App: https://clarity-light-theme-v013-jdmh2w.stackblitz.io
Editor: https://stackblitz.com/edit/clarity-light-theme-v013-jdmh2w

Version 2 (Single Components)
App: https://clarity-light-theme-v013-vg44bj.stackblitz.io
Editor: https://stackblitz.com/edit/clarity-light-theme-v013-vg44bj

1.  Go to Version 1 - App and scroll down
2.  Go to Version 2 - App and scroll down
3.  Same Content, different scrolls

## Expected behavior

The bug occurs as soon as the html file is distributed to individual files. The scroll behavior is not the same

## Versions

**App**
Angular CLI: 7.0.4
Node: 8.11.4
OS: linux x64
Angular: 7.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

**Device:**

* Type: Personal Computer
* OS: Linux Ubuntu
* Browser chrome
* Version ???

## Additional notes

None

**Comment by Jinnie** [comment]
The content projection of the content-container inside the clr-main-container is done via class name.
So, when you put your app-content directive inside, it gets projected at some default location, which is not where it is intended to be.
If you add the "content-container" class to the app-content component, the projection will be done correctly, and the scrolling will work as expected: 
  <app-content class="content-container"></app-content>

Alerts and headers are getting positioned correctly in this case, but it may not be the issue with other components where you may try to nest custom components inside clarity ones, as you do here.
You may need to help angular like so, in case inner components are resolved by tag-name:
<clr-main-container>
  <app-alerts ngProjectAs="clr-alerts"></app-alerts>
...
Again - it is not the case here, but it may be in other places, if you intend to wrap clarity stuff in your own components.
