### ISSUE TITLE
Add possibility for buttons and signposts in clrForms (v1.0)

### ISSUE THREAD

**Issue by martijnmelchers** [vmware/clarity#2826]
## Summary

_Summary the request and address the questions as appropriate._

* What is the change?
Add a `clr-button-container` and/or `clrButton` and the `clrSignPost`
* Why should it go in Clarity?

At the moment when you add a button to a form it looks really bad, the button is just at the bottom and don't really fit into the form (and it's stuck to the form most of the times).

It would be really awesome if you could have buttons like `clrReset` or `clrSubmit` which reset and sumbit the form and which fit more into the form than current buttons do.

Also add the possibility to add a button to the right of a input this could be useful if you want to "copy" the content of an input or make a "search" form.

The signpost could be a really nice addition to the current description because you might want to add a more detailed explanation to what something does.

* Does this change impact existing behaviors? If so how?

Not that know of.

* If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

It would improve the clrForms module and it would be really useful for some cases where you need a button next to a input and the buttons at the bottom of the form would just be a normal thing almost everyone uses.

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_
![2f0f1aba9db77b878925b228e 1](https://user-images.githubusercontent.com/6060006/48274147-fb4e7e80-e442-11e8-9bee-cfc799c9d030.png)

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_
Not with the angular version, that I know of.

**Comment by gnomeontherun** [comment]
Thanks for the input, would you mind giving an example of the bad layout currently as you are trying to use buttons? I think its a good suggestion, but I need to make sure I understand your attempts.

We do recommend avoiding hiding any content about your form from the users in tooltips or signposts, which is what the helper text is meant to support. Could you detail why you need a signpost?

As far an input and button together, we actually have this support as a CSS flavor, but not as an Angular component. I think we'll need to at least work out some examples of how to implement these things, so point noted.

**Comment by gnomeontherun** [comment]
Code is most helpful, if you can make a StackBlitz that is best so I can see _exactly_ what you're doing.
