### ISSUE TITLE
[WEB] Wizard samples overflow boxes in Chrome Canary

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#2828]
## Describe the bug

In the [Wizard docs on Chrome Canary](https://vmware.github.io/clarity/documentation/v0.13/wizards), the inline example wizards are spilling outside their containers.

<img width="1899" alt="screen shot 2018-11-09 at 4 02 28 pm" src="https://user-images.githubusercontent.com/2728359/48295836-92243680-e455-11e8-8afc-5544e11956ac.png">

## How to reproduce

Open the above link in Chrome Canary. Scroll down until you see it.

## Expected behavior

Example wizards should be in their boxes like they were before.

## Versions

**App**

* Clarity: [e.g. 0.13.9]

**Device:**

* Type: MacBook
* OS: MacOS
* Browser chrome canary
* Version  72.0.3606.0

## Additional notes

The issue appears to be from a new way that Canary is applying the `vh` units on this page. If we override the `75vh` of the modal wizard xl size with a height of 100%, it works fine. See screenshot below.

<img width="790" alt="screen shot 2018-11-09 at 7 28 46 pm" src="https://user-images.githubusercontent.com/2728359/48295965-d9f78d80-e456-11e8-86d9-4bfbb54da3cb.png">

The more interesting parts are:

1. This is only something we would use or do on the website. So it only needs to be fixed on the website. Please use a CSS selector and override on the website only.

2. We don't know how this override would affect the other browsers (Regular Chrome, Safari, Firefox, Edge and IE11). Please test on those just to be safe.

3. We should also go ahead and redeploy the website after this. Since it should be an override from the website CSS, we may not need to rebuild the dox to fix it. Just have to be clever with the CSS selectors. If not, please rebuild the docs for all versions.

**Comment by Jinnie** [comment]
This is related to the fix of this issue: #2493 [Edge] Wizard Navigation shorter than Wizard
Having set the height to 75vh and max-height to none may work okay in full-screen mode, but does not work when the wizard has a smaller container, as on the web-site. In other browsers it looks better, although it's not impossible to get a view like this one:
<img width="668" alt="screen shot 2018-11-15 at 14 00 31" src="https://user-images.githubusercontent.com/1798828/48551964-b06bb580-e8df-11e8-9daf-6cbf516a698e.png">

**Comment by Jinnie** [comment]
v0.10 and v0.11 are okay. 
So, the changes will only need to be ported to .12, .13, 1.0.
