### ISSUE TITLE
[1.0.0 bug] datagrid-action-overflow popup is hidden behind footer

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#2829]
## Describe the bug
See the screenshot from official website: https://vmware.github.io/clarity/documentation/v1.0/datagrid/single-action
The datagrid-action-overflow popup is hidden behind footer and you have to scroll down to see the content on the popup. I believe it is not very user-friendly. The popup should always be placed above the grid table, just like the behavior in 0.13 and backwards.

![screen shot 2018-11-12 at 4 09 13 pm](https://user-images.githubusercontent.com/6769465/48334604-31d00780-e696-11e8-8690-ac12cd3fdbe0.png)

This is not happening on 0.13 and backwards.

## How to reproduce

Visit https://vmware.github.io/clarity/documentation/v1.0/datagrid/single-action and click the ellipsis of last row

## Versions

**App**

* Angular: 7
* Clarity: 1.0.0

**Device:**

* Type: MacBook
* Browser: chrome
* Version: 70.0

**Comment by hippee-lee** [comment]
I'm closing because this is a known issue. Please subscribe to https://github.com/vmware/clarity/issues/2683 and https://github.com/vmware/clarity/issues/1262 for updates. Let me know if you believe this is different from those and I'm happy to re-open it.
