### ISSUE TITLE
[1.0.0 bug] Enlarging the browser width leaves some blank area inside the datagrid

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#2830]
## Describe the bug
See the screenshot from official website: https://vmware.github.io/clarity/documentation/v1.0/datagrid/single-action
After enlarging the browser width, the datagrid does not get enlarged proportionally. There will leave some blank area on the right part of the datagrid.

![screen shot 2018-11-12 at 4 26 12 pm](https://user-images.githubusercontent.com/6769465/48335118-c38c4480-e697-11e8-8e76-257f84bd0282.png)

This is not happening on 0.13 and backwards.

## How to reproduce

With a relatively small window size (e.g. 990px) and visit https://vmware.github.io/clarity/documentation/v1.0/datagrid/single-action. Then enlarge the window to be 1200px width. Observe the datagrid.

## Versions

**App**

* Angular: 7
* Clarity: 1.0.0

**Device:**

* Type: MacBook
* Browser: chrome
* Version: 70.0

**Comment by m-tomczyk** [comment]
There is also other side of this bug, if window gets shrunken datagrid always stays same size as initial calculation. It breaks content (adding x overflows) if site uses expanding side panels or similar type of widget

**Comment by gnomeontherun** [comment]
The solution in #2865 to manually trigger a datagrid resize is the recommendation for any situation where the container changes in size. Depending on your use case, you'll want to implement a method that will resize based on the conditions of your application.

**Comment by h657070128** [comment]
Hi @gnomeontherun , thanks for your comments. However, do I have to add an event handler for window resizing on EVERY page which contains datagrids?

**Comment by Jinnie** [comment]
Hi, @h657070128 
You can make a small helper component, which you can use as wrapper to any datagrids you use and avoid adding the same code everywhere.
See this example:
https://stackblitz.com/edit/clarity-resize-notifier-example?file=src%2Fapp%2Fdatagrid.notifier.ts

**Comment by h657070128** [comment]
@Jinnie Thanks Ivan! It helps a lot.

**Comment by jacobbutton** [comment]
@mathisscott - Would you mind explaining the "Invalid" tag to me? Does that mean this won't be fixed? Is clarity no longer going to refresh the datagrid size on browser resizes?

**Comment by jacobbutton** [comment]
Thanks for the clarification.

**Comment by jacobbutton** [comment]
Is there a benefit to calling the resize() method of the datagrid instead of just overwriting the .datagrid-table css with...

`    .datagrid-table{
        width:100% !important;
    }`

**Comment by mathisscott** [comment]
resize() will go through and resize your columns as best it can. setting the width in CSS won't do that.
