### ISSUE TITLE
[CSS] Add more grid breakpoints after Extra Large

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2832]
## Summary

Screens can be pretty large nowadays. Old Bootstrap grid system with the largest breakpoint stopping at >= 1200px is not enough. I'd suggest adding more breakpoints after XL up to 4k and maybe even few more to cover future resolutions.

* **What is the change?** Add more breakpoints for larger screens
* **Why should it go in Clarity?** To let people fine-tune layouts >= 1200px by using grid classes and not going into writing media queries.
* Does this change impact existing behaviors? No.
* If this change introduces a new behavior, is this behavior accessible? Yes.

## Use case

It will allow me to set form controls and other components widths using the grid, without having too wide components on large screens, or without writing media queries in CSS and breaking consistency.

## Workarounds

I guess extra breakpoints can be added if you compile Clarity scss in your project, but doing so only to get breakpoints is an overkill IMO.

**Comment by mathisscott** [comment]
@colinreedmiller

**Comment by joshjohnson72** [comment]
+1  Would at minimum like to see an XXL breakpoint @ ~1600px, just so large displays (i.e. TV monitors) can utilize space better than the averaged laptop resolution.

**Comment by ietabhi** [comment]
This item should be little more priority as most of application now using 1600px+ resolution and we can see so much white space for app.

same value for grid column don't work for app 1200px and 1900px

**Comment by gnomeontherun** [comment]
Applications can define extra options in their own CSS (without compiling Clarity), so nobody is blocked by Clarity. 

There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
