### ISSUE TITLE
[NG]: The datagrid is rendered too small when used in wizard

### ISSUE THREAD

**Issue by gjungb** [vmware/clarity#2833]
## Describe the bug

When using the datagrid inside of a wizard, the datagrid / columns get rendered too small.

![anmerkung 2018-11-12 161941](https://user-images.githubusercontent.com/3391068/48356563-d7837680-e696-11e8-8ac5-9e770b89bc4f.jpg)

## How to reproduce

https://stackblitz.com/edit/angular-kr1usn

1.  Go to 'https://angular-kr1usn.stackblitz.io'
1.  Click on 'WIZARD'
1.  See error

## Expected behavior

The datagrid should be rendered in full width.

## Versions

**App**

* Angular: [7.0.3]
* Clarity: [1.0.0-beta.2]

**Device:**

* Type: [Microsoft Surface Pro]
* OS: [Windows 10]
* Browser [chrome, edge, firefox]
* Version [latest]

## Additional notes

The `width` of the `datagrid-table` is calculated as `0px`:
 ```<div class="datagrid-table" role="grid" style="width: 0px;">```

**Comment by gjungb** [comment]
Looks like this is caused by the row width calculation https://github.com/vmware/clarity/blob/b3e75d153382214c86aa409632e4e8211ddd0296/src/clr-angular/data/datagrid/providers/table-size.service.ts#L63

**Comment by Jinnie** [comment]
The datagrid gets initialized before its parent, the wizard, is fully initialized.
You can add an ngIf on the datagrid, so you have more control when it gets created and after some exercises around the "open" field, you can get to a workaround similar to this one:
https://stackblitz.com/edit/angular-meuvu7
Directly binding to the "open" won't work, while the indirect binding through setTimeout (without timeout value) yields the thread, allowing the wizard initializiation to finish before datagrid gets created.
I can't promise it will work efficiently before it goes through some unit tests, so we are sure we're not messing the angular lifecycle in an unacceptable manner at some point.
But it's some starting point you can experiment with.

**Comment by gjungb** [comment]
@Jinnie Thx for your quick reply. I'm going to apply your proposed workaround to my real world app and keep this issue updated.

**Comment by Jinnie** [comment]
Closing this as there is a workaround. I also checked with the team - this is a known issue, where we're waiting for a fix from Angular to handle it in Clarity, so no need to keep this issue open for tracking.

@gjungb please update with your results, or feel free to reopen if needed.

**Comment by gjungb** [comment]
If the datagrid is needed on a later wizard page, there's an easy solution that makes use of `(clrWizardPageOnLoad)` and `*ngIf` like so: https://angular-gchrux.stackblitz.io

@Jinnie no need to reopen this, thx.

**Comment by luis-cortina** [comment]
> If the datagrid is needed on a later wizard page, there's an easy solution that makes use of `(clrWizardPageOnLoad)` and `*ngIf` like so: https://angular-gchrux.stackblitz.io
> 
> @Jinnie no need to reopen this, thx.

Can you share the code for this solution?

**Comment by jvalkeal** [comment]
@luis-cortina You'll see that in https://stackblitz.com/edit/angular-gchrux

**Comment by jvalkeal** [comment]
Just a comment to others, that `clrWizardPageOnLoad` trick only works if datagrid is not on a first wizard page.
