### ISSUE TITLE
DatePicker able to set value when control is disabled

### ISSUE THREAD

**Issue by terryvdgriend** [vmware/clarity#2836]
## Describe the bug

When using the clrDate date picker on a disabled input field, i can edit the value of that input field with the date picker icon. I would not expect this.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v013-4e48bb?file=src%2Fapp%2Fapp.component.ts

1. Select one of the date picker icon's.
2. Select a date.
3. The value in the input field is updated.

## Expected behavior

When the input field of the datepicker is disabled, I would expect that I can't edit the value of the input field using the datepicker. However this is now possible.

## Versions

**App**

* Angular: 7.0.3
* Clarity: 1.0.0-beta.2

**Device:**

* Type: Windows
* OS: 10
* Browser: All

**Comment by jaypillai** [comment]
Hmm a quick fix would be disable click on the datepicker icon when disabled.

Add [ngClass] for disabled state and the css for the corresponding class should be something like below:-

.disabled-datepicker {
  pointer-events: none;
  opacity: 0.5;
}

**Comment by gnomeontherun** [comment]
We need to verify that we're passing the disabled state up to the button as well.

**Comment by gnomeontherun** [comment]
This is actually functional with the new forms, it is not supported with the old forms layout and won't be patched by us since they are deprecated. So you need to use `clr-date-container` around your input for this to work properly, otherwise the wiring doesn't happen.

```
        <clr-date-container>
          <input type="date" clrDate name="test" [(ngModel)]='model' [disabled]="disabled"/>
        </clr-date-container>
        <clr-date-container>
          <input type="date" clrDate [formControl]='dateControl'/>
        </clr-date-container>
```

**Comment by terryvdgriend** [comment]
If this is the case, then the DatePicker sections on the documentation website needs an update. It still uses the old forms layout as an example.

**Comment by gnomeontherun** [comment]
Indeed, working on it for 1.0.
