### ISSUE TITLE
Datagrid : text size

### ISSUE THREAD

**Issue by Furieux** [vmware/clarity#2837]
Hi !

I used the Datagrid component but got the text really small. Not at all like the example on the clarity site.

![image](https://user-images.githubusercontent.com/8227662/48421810-85f1ef00-e75d-11e8-8c47-a83c13aa8c35.png)

Any idea where it comes from and how to solve this ?

I simply reused the code from clariy website in my component :

```
<clr-datagrid>
    <clr-dg-column [clrDgField]="'Cali'">Kali</clr-dg-column>
    <clr-dg-column [clrDgField]="'Totems'">Totem</clr-dg-column>
    <clr-dg-column [clrDgField]="'Prenom'">Prénom</clr-dg-column>
    <clr-dg-column [clrDgField]="'Nom'">Nom</clr-dg-column>


    <clr-dg-row *clrDgItems="let kali of listekalis">
        <clr-dg-cell>{{kali.Cali}}</clr-dg-cell>
        <clr-dg-cell>{{kali.Totems}}</clr-dg-cell>
        <clr-dg-cell>{{kali.Prenom}}</clr-dg-cell>
        <clr-dg-cell>{{kali.Nom}}</clr-dg-cell>

        <clr-dg-row-detail *clrIfExpanded>
          <span>  {{ kali.Date_cali + ' ' }} </span>
          <span>  {{ kali.Lieu_cali + ' ' }} </span>
          <span>  {{ kali.Cali_explication }} </span>
        </clr-dg-row-detail>
    </clr-dg-row>

    <clr-dg-footer>{{ listekalis.length }} kalifiés</clr-dg-footer>
</clr-datagrid>
```
Thanks

**Comment by Jinnie** [comment]
Please, try to reproduce in Stackblitz:
https://stackblitz.com/edit/clarity-light-theme-v013

Have you, by any chance, explicitly set font-size value on your **html** element? Clarity is using rem units for sizing, which are relative to the DOM-tree root element size, so if you set some custom size there, you'd get the result you're describing.

**Comment by sdurnov** [comment]
Your Datagrid details column icon looks too big. Looks like you have some 3rd-party CSS applied globally. Open your page in the browser, open browser dev tools. Select elements which have wrong styling/size and check where their properties are coming from.

**Comment by Furieux** [comment]
I use indeed a third party for styling : bootstrap. I've just deleted it and it is now showing right !
But the rest of the app isn't right anymore.

Is there a way to use bootstrap in combination with clarity ?

**Comment by sdurnov** [comment]
Depends on what are you using Bootstrap for. If you just need to customize your colors/font/sizing - I guess you can achieve it with Clarity SCSS. You can also copy some Bootstrap utils and use it together with Clarity.

**Comment by sdurnov** [comment]
Or you can import Bootstrap SCSS right in-place, just in the components where you need it.

**Comment by Furieux** [comment]
After having the bootstrap declaration moved before clarity and re-served the app, it is not so messy anymore. It's good now.

Thanks for your help :)
