### ISSUE TITLE
Add badge/alerts icons to Clarity library

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#2840]
@joshjohnson72 requested badge and alert versions of the 'block' and 'blocks-group' icons.
Publish to Clarity icon library by 11/30 if possible. 
![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/511c709a-c138-4749-a522-1d23975a6f88)

@Stela-Stamenkova has provided the 8 icon variants to publish:
[https://app.zenhub.com/files/69590701/53f8e3e0-baf9-4136-8471-dd6e72c4e707/download](https://app.zenhub.com/files/69590701/53f8e3e0-baf9-4136-8471-dd6e72c4e707/download)

These should be added to the 'Technology' category. Thanks!

**Comment by Shijir** [comment]
Closed by #2885
