### ISSUE TITLE
remove default header template of wizard

### ISSUE THREAD

**Issue by Syadav777** [vmware/clarity#2842]
![error](https://user-images.githubusercontent.com/45034693/48481863-f6b80a80-e834-11e8-994c-b4728c50e6f7.JPG)
we  are trying to set wizard in the modal and we want to add title into modal iteself rather than giving title into wizard.
If we are removing <ng-template clrPageTitle></ng-template> from wizard, its throwing error. If we don't removing this tag 
from wizard its occupying some space in wizard side nav header.
Is there any solution to remove ng-template from wizard?

**Comment by jaypillai** [comment]
Don't remove title from wizard.

instead if you want to hide the left navigation pane , do it via css/scss  :--

::ng-deep .clr-wizard {


    .modal-content-wrapper {

        .clr-wizard-stepnav-wrapper {
            display:none;
        }
    }
}

**Comment by mathisscott** [comment]
I agree with @jaypillai . The best way to do what you want is through CSS.
