### ISSUE TITLE
[datagrid] expose a "state" method on custom filters to simplify clDgRefresh

### ISSUE THREAD

**Issue by awdyson** [vmware/clarity#2846]
## Summary

* What is the change?
  - `ClrDatagridFilterInterface` gets an optional `state` (or whatever) method with a `{ property: string; value: any }` return type
  - `StateProvider` checks for the existence of this method before/instead-of returning the whole custom filter class
* Why should it go in Clarity?
It'd make dealing with the refresh output easier.
* Does this change impact existing behaviors? If so how?
Not that I see on quick inspection.
* If this change introduces a new behavior, is this behavior accessible?

## Use case

Here's my custom filter -- the template is basically `<checkbox *ngFor="options">`:
```
export class ClrDgCheckFilterComponent implements ClrDatagridFilterInterface<object> {
  @Input() options: Option[] = [];
  @Input() property = '';

  changes = new EventEmitter<true>();
  selected = new Set();

  // My request is that StateProvider knows to call this method if it exists
  get state() {
    if (!this.dirty) return null;
    return { propery: this.property, value: Array.from(this.selected) };
  }

  private get dirty() {
    return !!this.selected.size && this.selected.size !== this.options.length;
  }

  constructor(private dgFilter: ClrDatagridFilter) {
    this.dgFilter.setFilter(this);
  }

  accepts(entry: object) {
    if (!this.dirty) return true;

    const selected = this.selected.has(deepGet(entry, this.property));
    return selected;
  }

  isActive() {
    return this.dirty;
  }

  onChange({ val }: Option) {
    this.selected.has(val) ? this.selected.delete(val) : this.selected.add(val);
    this.changes.emit(true);
  }
}
```

Here's the current output from a built-in filter and this filter:
![image](https://user-images.githubusercontent.com/5612248/48573991-d5056480-e8c2-11e8-9611-d90d0c019d51.png)
Ideally, I'd like to be able to have the output from my filter look just like the built-in. @amellnik if https://github.com/vmware/clarity/issues/2513 requires a more complex representation, I'd love to be able to keep in step with that as well.

## Workarounds

Yep, handle the transformation in a service you provide to the component. Also open to suggestions 😄

**Comment by amellnik** [comment]
By property you mean the property of the row object associated with that column, right?  If I'm understanding this correctly, this partially solves https://github.com/vmware/clarity/issues/2513.

**Comment by awdyson** [comment]
I don't think so, but there's a chance that enhancement might solve my issue as well. The stackblitz isn't loading at the moment, and it's a little hard for me to grok exactly what your solution would entail. The main problem you're looking to solve seems really worthwhile by the way.

I'll update my original post with a concrete example.

**Comment by Jinnie** [comment]
Done!
