### ISSUE TITLE
Not able to achieve recursive clr-stack-view

### ISSUE THREAD

**Issue by noopur-dabhi** [vmware/clarity#2848]
I'm trying to achieve recursive stack view, but somehow stack-view is not considering dynamically generated stack-blocks as children, and hence view is not rendered properly.

```
<clr-stack-view>
  <ng-container *ngTemplateOutlet="stackBlockTemplate; context: {data: data}"></ng-container>
</clr-stack-view>
<ng-template #stackBlockTemplate let-data="data">
  <clr-stack-block *ngFor="let account of data">
    <clr-stack-content>{{account.name}}</clr-stack-content>
    <ng-container *ngIf="account.childAccounts">
      <ng-container *ngTemplateOutlet="stackBlockTemplate; context: {data: account.childAccounts}"></ng-container>
    </ng-container>
  </clr-stack-block>
</ng-template>
```

<img width="287" alt="screen shot 2018-11-15 at 5 53 24 pm" src="https://user-images.githubusercontent.com/17811679/48552782-aeb1ea00-e8ff-11e8-9892-57036c89274e.png">

As you can see, I don't get the collapsible icon, because somehow stack-view is not considering dynamically generated stack-block as child

**Comment by gnomeontherun** [comment]
You've posted on StackOverflow as well, so I'm going to close this in favor of https://stackoverflow.com/questions/53319624/not-able-to-achieve-recursive-stack-view-in-vmware-clarity-with-angular. Please post a reproduction of your issue with StackBlitz.

**Comment by noopur-dabhi** [comment]
Here is StackBlitz link : [https://stackblitz.com/edit/clarity-light-theme-v11-9bb9lg](https://stackblitz.com/edit/clarity-light-theme-v11-9bb9lg)

**Comment by epicStudio** [comment]
Hello,

this issue sounds similar to what I am dealing with at the moment: https://stackoverflow.com/questions/56563439/clarity-stack-view-does-not-work-with-angular-ngtemplateoutlet

Have you figured out a solution yet?
