### ISSUE TITLE
[Suggestion/request] Don't pull in the whole RX.js library

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#285]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Only import the features from Rx.js that Clarity actually needs/uses. This will help minimize the number of requests that are made right off the bat when an app is loaded and each time it's refreshed. Instead of pulling in all of Rx.js, create an rxjs-operators.ts file that imports the operators that the components need. I think this is the suggested route given by the [Angular team](https://angular.io/docs/ts/latest/guide/server-communication.html#!#rxjs).

### Actual behavior
From what I can tell it looks like the entire Rx.js library is being pulled in (referenced as Rx.js) by Clarity components. That creates a ton of requests and makes for a slow initial page load or any time the app is refreshed (which is a lot while in development). I'm seeing this while working on an app built from the clarity-seed repo (System.js version). As an example, in the Clarity components, `Observable` is being imported by doing `import { Observable } from "rxjs";` rather than `import { Observable } from "rxjs/Observable";`.

**Comment by youdz** [comment]
This is actually a touchy subject, where everything is still up in the air.
Some people put the task on the developer, like the Angular team does. Some put it on the bundlers, which should be able to treeshake the dead weight even if you import from the index. And some put it on the library itself to provide a stable internal structure, like RxJS does.

Angular's recommendation right now relies on both the developer and the many files of RxJS being part of their public API, but if you look at the [AoT documentation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#tree-shaking), they rely on rollup and its plugins to trim RxJS. I don't believe any of the decisions is final, and I'd be surprised if the way to import RxJS didn't change several times in the next year or couple years.

That said, the link you referenced seems to be the "safest" way to trim RxJS without involvement from the developer, so maybe we should go with that.

### One thing bothers me in the behavior you describe, though
You say your app sends several requests to fetch RxJS. This should *never* happen, no matter what the solution we agree on is. You should always either rely on the minified bundles provided by the RxJS package itself, or bundle on your own with webpack, rollup or whatever your preference is. 
*If this multi-request behavior is the default one for our SystemJS seed, please raise an issue over there.* I remember this being an issue in the Angular quickstart itself, where they would send 30 requests just to get RxJS files. I don't know if it's still the case, but either way seeing multiple requests for the same library, either in development or production mode, should be a big red flag.

**Comment by jbgarr** [comment]
Hello @youdz thanks for your reply.

So just to add some additional info here, I am running the SystemJS seed (and will raise an issue there as well) and with that seed project (just the basic version of it out of the box) it makes 454 requests when the app is fired up or reloaded. Out of those 454 requests, 343 of them are related to RxJS. I have been able to work around this by modifying my gulpfile and running the development version of my app (so it runs minified and bundled versions and makes far fewer requests), but even that isn't the best solution since it requires the app to be built every time I make a change. So I have to choose between waiting for the app to build each time OR pulling in hundreds of files for the RxJS library each time I make a change. Sadly, waiting for the build is far faster at this point.

One thing to note, the requests for RxJS are not trying to pull in the SAME file, but since RxJS is made up of hundreds of modules, when you pull in the whole library (by referencing Rx.js as the main entry point) it makes requests for each module separately resulting in the huge number of requests mentioned above.
