### ISSUE TITLE
Modal close default

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#2852]
## Describe the bug

_Default behavior for user closing a modal is specified as requiring explicit click - clicking outside to close is configurable but should not be the default._

## Expected behavior

_Click outside the modal should not cause it to close as default._

Documentation reads: "Clarity Modals are not dismissed when clicking on the background overlay. This prevents losing information or data. An option to override this is available."

[https://vmware.github.io/clarity/documentation/v0.11/modals](https://vmware.github.io/clarity/documentation/v0.11/modals)

**Comment by Shijir** [comment]
Closed by #2885

**Comment by Shijir** [comment]
Sorry closed wrong issue 😛

**Comment by Jinnie** [comment]
Now we can close it officially :)
