### ISSUE TITLE
[1.0] Datagrid footer content goes out of the bounds on small screens

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#2855]
## Describe the bug

Pager content doesn't wrap, goes out of bounds instead. 

## How to reproduce

Open [datagrid pagination example](https://vmware.github.io/clarity/documentation/v1.0/datagrid/pagination)
Set page size too small, iPhone X, for instance. See that at least page size drop-down is out of bounds.

## Expected behavior

Content should wrap in a clean way, or be transitioned into another visual form.

## Versions

**App**

* Clarity: [e.g. 1.0.0 beta 2]

**Device:**

* Type: [PC]
* OS: [Win 10]
* Browser [Chrome, iPhone X emulation mode]
* Version [70.0.3538.102]

**Comment by sdurnov** [comment]
@mathisscott as you put needs design label, I want also to mention one thing. From what I see in real life, Datagrid footer had 1 critical design flaw - in many cases, when page size is large enough, user has to scroll to change page size or page number. Of course, users complain about that and ask to implement same functionality in a toolbar. Please consider extending current action bar functionality to support page size and page number changing, as well as normal support for form controls here, as well as nicely wrapping its content when overflow happens.

**Comment by mathisscott** [comment]
@sdurnov 
That's a lot of scope added in! If you wouldn't mind filing separate github issues for those requests, that would be helpful. Scope creep would turn this item from a reasonable fix for something broken to a months-long mega-change that wouldn't see the light of day until the end of next year. 😊

**Comment by sdurnov** [comment]
@mathisscott Sure

**Comment by lil-kim** [comment]
Visual design spec is ready, see: #3097
