### ISSUE TITLE
Generic clr-input-container

### ISSUE THREAD

**Issue by RobArbor** [vmware/clarity#2864]
## Summary
It would be nice to have a more generic `clr-input-container`.
So i can use third party controls within the clarity forms. 

* What is the change?
A generic form container element, to use with custom elements / controls.

* Why should it go in Clarity?
Make it easy to use custom elements / controls that fit in the clarity form layout.
Would make clarity better compatible with third party controls.

## Examples
```
<form clrForm>
  <clr-generic-container>
    <label>My label</label>
    <my-awesome-control class="clr-control"></my-awesome-control>
  </clr-generic-container>
</form>
```

## Workarounds
Currently i've created a very simple version in my project but it lacks the multiple layouts implementation and only works with a horizontal layout.

**Comment by gnomeontherun** [comment]
This is an interesting request, and not something that is as simple as making a generic container. Each control also has to implement a set number of things to work properly with the container, and while I like the idea of opening this up so its more generic, its more complex than just a generic container.

I'll keep this as a feature request for the future, but for now you might consider reviewing how the input is implemented and seeing if you can duplicate the conditions in your own controls.

**Comment by gnomeontherun** [comment]
I'm going to close this request in favor of #2886 which has more detail about the same request.
