### ISSUE TITLE
When user customize the click action of clr-dg-column-toggle-button , an error accours 

### ISSUE THREAD

**Issue by Jennychen66** [vmware/clarity#2868]
## Describe the bug

I'm using clarity version 0.13 and showing a list of datagrid columns with hide/show propertites , I want to custemize the 'OK' button at the bottom of the clr-dg-column-toggle panel but an error occurred. 

![image](https://user-images.githubusercontent.com/39254430/48817714-b3085800-ed82-11e8-86b2-6a502d6c2a4c.png)
## How to reproduce
`        <clr-dg-column-toggle>
          <clr-dg-column-toggle-button (click)="load($event,item)">Load</clr-dg-column-toggle-button>
        </clr-dg-column-toggle>`

`  public load(event, project) {
    var latestFormColumns = JSON.parse(localStorage.getItem("columns"));
    console.log(latestFormColumns);
    for (var i = 0; i < latestFormColumns.length; i++) {
      var colToChange: ClrDatagridColumn;
      colToChange = this.columns.find(col => col.columnId === latestFormColumns[i].key);
      if (colToChange && colToChange.hideable) {
        this.columns.find(col => col.columnId === latestFormColumns[i].key).hideable.hidden = latestFormColumns[i].value;
      }
    }
  };`
_

## Expected behavior

The error should not occured

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.13]

**Device:**

* Browser [e.g. chrome]
* Version [e.g. 22]

**Comment by youdz** [comment]
It was part of the 0.13 breaking changes, we removed the "OK" button and kept only the "Select All" one: https://vmware.github.io/clarity/news/0.13.0-beta.2
>### Removal of the OK button in datagrid column selector.
>This is a visual breaking change, where we removed the OK button from the datagrid column toggle popover. If you have been using the clr-dg-column-toggle-button button to localize the button text, you can safely remove the OK button as well. This component will now only be used for the Select All text localization. The clrType binding has also been deprecated since it will now not be needed.

We considered it to be only a visual breaking change, but didn't realize some people might be attaching click event handlers to it. Anyway, it was been removed because changes in columns happen live so it was simply redundant with the "x" close button.
