### ISSUE TITLE
Filter titles for [clrDgField] string filters

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2869]
## Summary

Add an option for specifying a title for the string filter popup that comes per default when using `[clrDgField]` in a datagrid.

## Use case

We received feedback from our customers (who may not be that technically experienced), that it is unintuitive what the filters are actually doing. They are missing a small description like "Filter by name" so they know what the input field is actually for.

## Examples

This could look something like this:

![screen shot 2018-11-21 at 15 59 12](https://user-images.githubusercontent.com/3655915/48849373-85cda100-eda6-11e8-8665-a780dbb7952d.png)

## Workarounds

Implement custom Filters.

**Comment by youdz** [comment]
Given the high number of tasks on our plate, if we get time to work on Datagrid filters we would rather spend it on #1632 than this, since they both solve the issue but #1632 solves many more at the same time.

Closing this as duplicate, please subscribe to the linked issue for updates, thank you.
