### ISSUE TITLE
Separating layout css rules from the theme css rules in different files

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#2877]
## Summary
I would like to request separating layout css rules from the theme css rules in different files
* What is the change?
I would like to request Clarity UI to provide a way tor the user to consume the theme specific CSS rules separate from the layout, typography rules. I.e. to have clasrity-ui.min.bundle.css and clarity-ui-theme-light.min.css  or clarity-ui-theme-dark.min.css

* Why should it go in Clarity?
It will enable dynamic theme switching without causing screen blinking and resizing of elements.

* Does this change impact existing behaviors? If so how?
The users will have to load 2 css files , or if you provide pre-build bundles as you provide now there will be no changes
* If this change introduces a new behavior, is this behavior accessible?
It will improve the UI behavior when themes are dynamically switched
## Use case

I have a Angular application and I want to change the Clarity UI theme. I can change the href-attributes but the UI starts to resize, blink, and looking not so well. 

## Examples
https://getbootstrap.com/docs/3.3/getting-started/
## Workarounds
None, the theme can be switched but the UI is still jumping and bouncing

**Comment by gnomeontherun** [comment]
We've talked about this and have it somewhat captured in our CSS Epic, but I'd like to treat this as a standalone ticket for discussing the organization necessary for better theming.

**Comment by mathisscott** [comment]
Once the theming improvements are in, this is not an issue. #3131
