### ISSUE TITLE
Finish Design Contribution Guidelines

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#2893]
Presently, our design contribution guidelines are in a perpetual "TODO" state.

https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md#contributing-to-design

What do we need to do to finish them?

**Comment by reddolan** [comment]
This is where I remember things being left off. I had [documented the process](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Resources/blob/master/Clarity%20Contribution%20Process%20-%20Design.png). Scott and Jehad were going to review it, then recommend changes. I don't know if it made it any further than that.

**Comment by colinreedmiller** [comment]
Discover
Answer the following questions:
• What problem is being solved?
• How will a user interact with it?
• Are there features that will be enabled based on use cases?
Conduct market and VMware-product research to see what solutions may already exist. 
Compare how other solutions may or may not solve the problem.
Document references with names, links and screenshots.

Align & Define
Share documentation from “Discover” with Clairty team to understand the problem and its potential solutions.
Discuss why it makes sense for the solution to be incorporated into Clarity.
Clarity will give feedback on whether more information is needed, or if Clarity has decided for or against the solution.

Ideate
Product Design & Engineering team members meet to collaborate on potential solutions. 
Discuss implementation constraints, and raise issues that might affect the solution’s design.
Considerations
• internationalization
• long/short values
• error/zero/empty states
• accessibility recommendation
• responsive
• touch
• edge cases
• motion

Iterate
Share solution progress with Clarity team to make sure it aligns.
Clarity will give feedback on whether more information or design is needed. May need to return to the “Ideate” phase.

Lock
Solution design can be handed off to Clarity when all needed information is provided, or if the team is finished working on the solution.
Designs accepted by Clarity are not guaranteed immediate development.

**Comment by mathisscott** [comment]
@Jinnie 
We need to replace the text here (https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md#contributing-to-design) under the `TODO` with the text Colin posted above. Ideate, Iterate, etc. are headers. He kept the bullet points in. If you have any questions, feel free to ping myself or @colinreedmiller 

This only needs to be a change on master. Github picks it up off master automagically.

**Comment by colinreedmiller** [comment]
Updated and replaced Sketch and .png files in [https://gitlab.eng.vmware.com/DesignRepo/Clarity/Resources/tree/master](url)
