### ISSUE TITLE
Generic / broad selectors on native/naked html tags are very annoying.

### ISSUE THREAD

**Issue by Bartmax** [vmware/clarity#2895]
## Describe the bug

Some selectors, like for example `header` are targeting all `<header/>` elements.
No native html element should have any styling (besides resets).
It makes it **very hard to use** with and without other components as it make the use of semantic html a pit for failure.
In this particular example, `header` is *not* an element for page header only purposes.

## How to reproduce

https://clarity-light-theme-v1-0-1xnqan.stackblitz.io

add this html anywhere:
```
  <article>
    <header>
      this shouldn't have any background color or sizing
      <h2>this shouldn't be placed centered and on a fixed height container</h2>
    </header>
  </article>
```

## Expected behavior

No custom css are applied to native/naked html elements. (except for reset)
css styles should be targeted instead of:
```
header, .header { ... }
```
as:
```
header.header { ... }
```
## Versions

**App**

* Clarity: [0.13]

## Additional notes

This does not only happens with header nor background. There are many styles applied to different elements.

Ideally I would love to know if you are ok with these remarks, because if not I rather move to another library so i appreciate if you can at least tell me if you are interested on changing this current behavior or not.
Thanks.

**Comment by youdz** [comment]
I agree that styling `<header>` directly is opiniated. But saying that no native element should have any styling is too extreme, and completely impractical for any UI library. You won't find any design system and full-blown library out there that doesn't style native headers like `<h1>` or semantic elements like `<strong>`, `<small>` or `<code>`.

I will keep this open because I agree that styling `<header>` specifically is an issue, it has many more uses than just a navbar.

**Comment by Bartmax** [comment]
bootstrap is a good example. 
Maybe I wasn’t clear, sorry, what I meant is to have sane defaults (resets) like bootstrap. 

Not specific to any component,just a good default/reset. 

If you want styling for a particular “component” like tables then you can always do ‘table.table’. 

And that’s not extreme at all. Many UI libraries made this mistake at least once in its life and they tend to revert that.

**Comment by gnomeontherun** [comment]
While this is a known challenge with Clarity Angular/UI today, this will not be an issue with Clarity Core. To avoid major problems with existing usage of Clarity Angular/UI, this is something we have to reject and recommend adopting the Core components instead to avoid the generic selector problems. More details will be provided on the website and in upcoming releases, or just start with using Core today https://clarity.design/storybook/core/.
