### ISSUE TITLE
Disabled button background colour in overflow menu

### ISSUE THREAD

**Issue by emmalivingstone** [vmware/clarity#2898]
## Describe the bug

I'm not sure if this is intended or if it's a bug, but when you have a disabled button within a button group overflow menu the background is a different colour to the overflow menu then if you hover it changes to the same colour as the overflow menu.

## How to reproduce

https://stackblitz.com/edit/clarity-overflow-button-bg-bug

1.  Open the button overflow menu.
2.  The disabled download button background is grey - different to other buttons.
3.  Hover the download button.
4.  Its background becomes the same colour as the overflow menu background.

## Expected behavior

The disabled button's background should always have the same background colour as the overflow menu, with just the text being grayed out to show it is disabled. 

## Versions

**App**

* Angular: 6.0.0
* Node: 8.11.4
* Clarity: 0.13.2

**Device:**

* Type: Desktop
* OS: Windows
* Browser Chrome
* Version 70

**Comment by Jinnie** [comment]
@emmalivingstone thanks for the report and Stackblitz reproduction.
It's a bit hard to notice, but the colors are actually different. The disabled background is #ccc, while the hover is #eee.
This is definitely not very accessible and we will probably address it as part of a more major palette consolidation task, which we are planning as part of #2677

**Comment by youdz** [comment]
As @Jinnie said, it's a small piece of #2677, but we're going to keep this issue open because this actually _looks_ broken, so we might want to address it sooner rather than later.
