### ISSUE TITLE
Need to provide an option to close all other open stackblocks when a new stackblock is opened in StackView

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#29]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
```

### Expected behavior
Need to provide a way for users to close all other stack blocks when a new stack block gets opened so the stack view acts as an accordion. This will *not* be the default option, it will be an additional feature that a user can turn on.

### Actual behavior
Right now the default and only behavior is to allow as many stack blocks to be open within a stack view.

### Reproduction of behavior
N/A

### Environment details

* **Angular version:** 2.0.X
2.1.0

* **Clarity version:** 
0.6.1

* **Browser:**
all

**Comment by jaffoneh** [comment]
@yenmade this needs some UX input. The point of a stackview is progressive disclosure but my concern is that this makes a stackview an accordion and might encourage that pattern as a recommended pattern by Clarity. It seems to me that if you want to close other stackblocks as you open new ones then maybe a stackview is not what you're looking for because you could many of other options (tabs for example). That said, I'd like to make sure we do further research on this before we make a call to not go forward with it as an option.

**Comment by yenmade** [comment]
Agreed, I'll add this to the UX backlog to further research before making a call.

**Comment by mathisscott** [comment]
1. Do not make this the default
2. Do make it a configurable option on StackView

Needs API work to define contributions. Needs plunkr to mark for workaround.

**Comment by youdz** [comment]
Here is how to do it on the app side for now, until the feature is implemented: https://plnkr.co/edit/UdrYdIhCpVI9PAUhWc7n?p=preview

**Comment by gnomeontherun** [comment]
This issue is stale with little activity in the past months, and it is also possible for applications to handle this on their end. Closing this as we try to clean up the backlog, and a new issue can be created for it if it becomes a need.
