### ISSUE TITLE
Best way for a custom Themes

### ISSUE THREAD

**Issue by Vad1mo** [vmware/clarity#290]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
I would like to find Information in form of a tutorial on how to create a custom theme.

### Actual behavior
There is no such information or any kind of reference how to accomplish this. 

### Note
Are you planning to release such information or is it not planned?

**Comment by mathisscott** [comment]
Yes we were planning to add Documentation to the website to outline these steps. I checked github, however, and found we don't yet have an issue open for it. 

Thanks for opening one.

**Comment by jaffoneh** [comment]
Marking this as a duplicate of #268
