### ISSUE TITLE
Clarity Icons> Add tags to commonly used icons to make them easier to find  by search.

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#2910]
Adding these tags to the icons below should give users better search results. The new tags are inside (  )s.

COG -  ( gear )

SUCCESS-STANDARD - ( check, status, OK, normal)

CHECK - ( status, OK, normal, enable )

CHECK-CIRCLE - ( status, OK, normal, success )

ANGLE -  ( collapse, expand, chevron )

TIMES - ( x, delete )

SYNC - ( update )

PLUS-CIRCLE - ( add )

**Comment by jeeyun** [comment]
The aliases cannot be shared across different icons. Maybe we use variations of the aliases (e.g. `ok-standard`, `ok`, `ok-circle`)?

**Comment by Shijir** [comment]
Closed by https://github.com/vmware/clarity/pull/2941
