### ISSUE TITLE
[1.0 and 0.13 bug] clr-dgRefresh is called when datagrid is destroyed in server driven datagrid

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#2911]
## Describe the bug and How to reproduce

Go to https://vmware.github.io/clarity/documentation/v1.0/datagrid/server-driven and open console. Then navigate to another page, say click "Placeholder" under "Server Driven". See the error in console:
![screen shot 2018-12-05 at 4 01 11 pm](https://user-images.githubusercontent.com/6769465/49498744-07ddbf80-f8a7-11e8-83b4-aaff16d9d2e5.png)

I believe this is kind of duplicated with #1099 : clr-dgRefresh is not supposed to be called when datagrid is destroyed. However, I wonder why the issue happens on new 1.0.0 release and new 0.13 release while 1.0.0-beta.1 does not have this issue. 
Previously I was using 1.0.0-beta.1 and today I upgraded to 1.0.0.
FYI that on the documentation website, the issue can only be reproduced on version 1.0 and 0.13.

## Expected behavior

clr-dgRefresh is not called when datagrid is destroyed. In this case, destruction is due to route change.

## Versions

**App**

* Angular: 7
* Clarity: 1.0 and 0.13

**Device:**

* Type: MacBook
* Browser chrome
* Version 70

**Comment by Jinnie** [comment]
Hi @h657070128 
This is a known issue, which depends on an Angular bug.
Please follow this issue #1099
Closing as duplicate

**Comment by h657070128** [comment]
Hi @Jinnie , but why does 1.0.0-beta.1 not have this issue?

**Comment by Jinnie** [comment]
I see the same with the 0.13 site.
Actually, we can easily provide a website-only fix for this error. I'm reopening for a quick fix. It won't hurt even if the underlying issue is properly resolved.

**Comment by Jinnie** [comment]
Should be ok now. Will get auto deployed to the website after a little time.

**Comment by h657070128** [comment]
Thanks @Jinnie for the quick fix. The solution is easy but I just wonder what changes were made between 1.0.0 and 1.0.0-beta.1 that leads to the calling of clr-dgRefresh when datagrid is destroyed. On 1.0.0-beta.1 clr-dgRefresh is not called as expected.

**Comment by Jinnie** [comment]
I can't say at the moment why it's been working at beta.1. I can verify that we have this issue in 0.13
Some datagrid refactories were taking place, maybe it's been "fixed" for a moment, in some intermediate state, but the mentioned angular bug (see inside #1099) leads to a series of workarounds and regressions of different sub-components and functionalities and until it is finally fixed, it's too costly to be trying to workaround every single side-effect.
