### ISSUE TITLE
Data grid header overlaps other data grid components.

### ISSUE THREAD

**Issue by spitfjre** [vmware/clarity#2915]
## Describe the bug

The data-grid header z-index (it is 500) is too high and overlaps other data-grid components.

![screenshot](https://i.imgur.com/LXS1eMX.png)

## Versions

**App**

* Angular: 7.1.0
* Node: 11.3.0
* Clarity: 1.0.0

**Comment by Jinnie** [comment]
Thanks for the feedback.
Actually, the column-switch popup is missed in our z-index accounting. The datagrid header z-index is fine, as we are aligning other absolute positioned items against this 500 value.
I'll commit a fix soon.

**Comment by Jinnie** [comment]
Fixed
