### ISSUE TITLE
UI Tooltip positioning of right and left

### ISSUE THREAD

**Issue by Vad1mo** [vmware/clarity#292]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Positioning of the tooltips should be as indicated  

### Actual behavior

I would expect that the **right** the tooltip would be inline with the row not 50% below the row.
So it is actually diagonal right. 

![bildschirmfoto 2016-12-27 um 19 29 19](https://cloud.githubusercontent.com/assets/1492007/21505810/120e243c-cc6b-11e6-90a2-1cc6638fd89e.png)

![bildschirmfoto 2016-12-27 um 19 29 34](https://cloud.githubusercontent.com/assets/1492007/21505808/0bdfc2d2-cc6b-11e6-9ba0-e5602c3df379.png)

On can leave the current right style but rename it and introduce a new style which is named right then and which is inline with the row.

**Comment by jaffoneh** [comment]
@Vad1mo could you provide a bit more information? In the "right" tooltip, it is positioned to the middle of the icon to make sure it is pointing at it. Do you mean it should be pointed at the top of the icon instead (in this example)?

**Comment by Vad1mo** [comment]
here is an image what I image right should mean.
![bildschirmfoto 2016-12-27 um 19 29 19](https://cloud.githubusercontent.com/assets/1492007/21517573/7f1604bc-cce0-11e6-907b-6121b19ac75e.png)

The dotted gray line represents the row boundaries.

**Comment by yenmade** [comment]
@Vad1mo Can you elaborate more on what your need is to have the tooltip appear directly to the right and left of an icon (vs slightly lower but the arrow pointed at the correct position)?

**Comment by Vad1mo** [comment]
Yes exactly. 
**right** class, should be **100% right** and not **right and 50% below center**

So at the end there would be two more classes.

```
.top-right
.upper-right (new) 
.right (new)
.lower-right (current right)
.bottom-right
```

**Comment by yenmade** [comment]
@Vad1mo Thanks for listing the classes, makes it clear what you're looking for. What I'd like to better understand from a design perspective is why the positioning of the current tooltip doesn't meet your needs. Even though the text sits slightly below, the positioning of the arrow draws relation to the icon. Are there specific use cases you have for a 100% right and 100% left tooltip? This information will help us take into account different use cases for future designs. Thanks!

**Comment by Vad1mo** [comment]
Difficult to tell it actually looked better, when it was completely right.  
We had only horizontal and vertical positions. 

To be honest I got used too how it is right now. 

If you want you can close this proposal.

**Comment by yenmade** [comment]
@Vad1mo One of the reasons our tooltips aren't 100% left/right  is to avoid completely covering adjacent items (like in the case of a form). I'm going to close this issue for now, but thanks again for your input!
