### ISSUE TITLE
Question: How to save the state of the datagrid headers, sorting orders?

### ISSUE THREAD

**Issue by omurbekjk** [vmware/clarity#2925]
## Use case
Datagrid has hide/show feature. It works fine. But after hiding some columns and refreshing the page, previous state resets. Also same applies for column filtering. What is the recommended approach to save the state of datagrid configuration?

**Comment by mathisscott** [comment]
Hi @omurbekjk 
We have an open issue to create an easier way to communicate state to the datagrid #2846 .

Is that what you are looking for?

On a side note, I don't know if preserving state would be helpful to you if you are removing columns from the datagrid that are the source of the sorting or filtering. I don't know if that is a use case that would be supported even if #2846 were implemented.
