### ISSUE TITLE
[WEB] Datagrid initial width not evaluated

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#2926]
## Describe the bug

Going to the datagrid page, the grid is not fully initialized.
<img width="1149" alt="screen shot 2018-12-10 at 1 30 49 pm" src="https://user-images.githubusercontent.com/1798828/49730181-4517c800-fc80-11e8-8136-ee76366f372b.png">

I am still not sure if this is website problem, or datagrid problem, after the initialization is now semi-manual via the `resize()` method.

## How to reproduce

1.  Go to https://vmware.github.io/clarity/documentation/v1.0
2.  Click on the "Datagrid" nav option
3.  Verify that the datagrid is as displayed in the screenshot from the description. NOTE: if you go directly to the page, or change through the local datagrid links, the datagrid is fine. You need to navigate to the "Datagrid" from another page.

## Expected behavior

Columns should be sized accordingly to the datagrid width

## Versions

**App**

* Angular: 7
* Node: 10.1
* Clarity: 1.0

**Device:**

* Type: Mac
* OS: OSX
* Browser chrome
* Version 70.0.3538.102

**Comment by dpcamp** [comment]
I'm experiencing the same issue within my app after upgrading to 1.0
