### ISSUE TITLE
Typo – Docs for Icon variants

### ISSUE THREAD

**Issue by EileenLB** [vmware/clarity#293]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Doc explanation should be easy to understand

### Actual behavior
Doc explanation is oddly-phrased.  
The problem appears to be due to a 'typo' in the content

### Reproduction of behavior
See screen capture for examples
<img width="645" alt="odd-phrasing-2016-12-27 at 10 51 30 am" src="https://cloud.githubusercontent.com/assets/14795506/21506400/cecc8bbe-cc24-11e6-9bdc-66454239093d.png">

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.8

* **OS and version:**  OS is not relevant to this issue.

* **Browser:**  All

**Comment by mathisscott** [comment]
Fixed these typos with commit: https://github.com/vmware/clarity/commit/92282c78ab29f32782497f29dbbb8d34a3fe14bd.
