### ISSUE TITLE
TreeView incorrect selected state in childs

### ISSUE THREAD

**Issue by indus** [vmware/clarity#2931]
## Describe the bug

Child-TreeNodes don't get the correct selected state via the ```clrSelected``` binding when they get updated implicitly by toggeling the ancestor TreeNode.

## How to reproduce

- Make a TreeNode with two childs.
- Leave it collapsed.
- Make the RootNode selected.
- Expand the root node and make one of its childs unselected.

Result/Bug: The remaining Child node won't be selected and is in an undefined state (The checkbox is ok but the ```clrSelected``` binding never has updated a selected property to true, because at the time of implicit selection it was not there as the parent was collapsed).

## Expected behavior

When a ChildNode of a tree is selected implictly by selecting the parent node this has to trigger its ```clrSelected``` binding (At the latest when the parent node gets expanded; because then there is a chance that the implict state from the parent Node is no longer true for the child node)

## Versions

**App**

* Angular: 7.1.0
* Node: 0.13.10
* Clarity: 0.13.10

## Additional notes

_Add any other notes about the problem here._

**Comment by youdz** [comment]
Our tree has been completely rewritten in 1.0, specifically to address these kinds of bugs that came from mixed behavior between lazy-loaded nodes and eager-loaded ones.

You can check on our [latest tree documentation for 1.0](https://vmware.github.io/clarity/documentation/v1.0/tree-view#examples), the behavior you described works fine now. Note: if you want the tree to be "smart" and update all bindings across the tree when a parent is selected, make sure you do not use the lazy-loading feature.
