### ISSUE TITLE
Calendar/Schedule control

### ISSUE THREAD

**Issue by pjtmatos** [vmware/clarity#294]
[ ] bug
[ X] feature request
[ ] enhancement

### Expected behavior
Add a calendar/schedule control (like google calendar, outlook calendar, etc).

**Comment by jaffoneh** [comment]
@pjtmatos do you mean a date/time picker? Does #121 cover your request/use cases and if not, what is different?

**Comment by pjtmatos** [comment]
No, I mean an actual calendar/schedule.

Something similar to: http://angular-ui.github.io/ui-calendar/

The datepicker could be use in conjunction with to, for instance, select the month or day.

**Comment by jaffoneh** [comment]
A full calendar control is probably not going to be of Clarity as a component anytime soon. It seems like a much more involved "project" vs. a component. Although it might make sense to build a "Clarity Calendar" as an open source project on top of Clarity, building within Clarity itself seems a lot more involved than a component within a design system especially with the fact that we're currently working on implementing date/time picker. Thanks for filing the issue and please feel free to share your feedback.
