### ISSUE TITLE
New Checkbox disabled style missing

### ISSUE THREAD

**Issue by RobArbor** [vmware/clarity#2943]
## Describe the bug

The 'disable' style is missing from checkboxes. Though it is disabled but will be confusing for the user.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-s1x9kt

1.  Disable a checkbox.
2.  Note disabled style is not applied.

## Expected behavior

![image](https://user-images.githubusercontent.com/18066581/50011949-a3fd7a00-ffbd-11e8-8825-aafc48ecd96a.png)

## Versions

**App**

* Angular: 7
* Node: [e.g. 8.10.0]
* Clarity: 1.0.1

**Device:**

* Type: PC
* OS: Windows
* Browser All

**Comment by gnomeontherun** [comment]
We don't have this documented at the moment, but it does work with one small tweak. You must put the checkboxes inside of a `<clr-checkbox-container>` for it to work correctly. Also, the stackblitz is using 1.0.0-beta.2, which this feature landed in rc.1 so it need to be updated. See https://stackblitz.com/edit/clarity-light-theme-v1-0-sgd1yt?file=src%2Fapp%2Fapp.component.html

I'll update the docs to resolve this fully shortly.

**Comment by sgrtho** [comment]
That one was killing me as well. If you do update the docs, please also add some infos about the intermediate state which now also requires the container to work.
