### ISSUE TITLE
Toggler component with new forms

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#2953]
## Summary

We have existing toggle buttons, but want to support them in new forms properly.

* Extend the checkbox functionality to support toggler (its largely a class to add)

## Use case

Toggles often need to be in a form like a checkbox, so use cases are largely the same.

## Examples

Nope.

## Workarounds

You can use it without this, but it doesn't get the niceties and layouts.

**Comment by hippee-lee** [comment]
Reopened in order to connect the docs PR to this issue.
