### ISSUE TITLE
Vertical Nav doesn't shows clr-icons when child has one

### ISSUE THREAD

**Issue by cesargomezh** [vmware/clarity#2963]
## Describe the bug

I started today to use Clarity framework and it's nice. But look like I found a bug with vertical nav when one o more childs have a clr-icon inside <a> tag. When I collapse the vertical nav, the clr icons are blank, althought parent has one.

## How to reproduce

https://clarity-light-theme-v1-0-lpxyhn.stackblitz.io/

With code shown below. Just press bottom collapse button.

## Expected behavior

At moment to collapse vertical nav, it should show icons like this example: https://vmware.github.io/clarity/documentation/v1.0/vertical-nav/collapsible-nav/normal

## Versions

1.0

* Angular: 7.1.4
* Node: 11.2.0
* Clarity: 1.0.2

**Device:**

* Type: Teclast
* OS: Windows 10 1809
* Browser Firefox Developer Edition
* Version 65.0b5

## Additional notes

_Add any other notes about the problem here._

**Comment by jeeyun** [comment]
Hi there,
Thanks for reaching out. I took a look at your code and you are missing `clrVerticalNavIcon` directive in your icons. I would also suggest not using the nav divider in each line, as our design guideline recommends using it for grouping clusters of nav items. 

Please take a look at this updated stackblitz that fixes your issues:
https://stackblitz.com/edit/clarity-light-theme-v1-0-dng5wi

Closing, as the component is working as expected.
