### ISSUE TITLE
replacement container bootsrap

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#2969]
which classes should i use instead:
.container and container-fluid
for remove bootsrap

**Comment by KANekT** [comment]
but this does not solve my case: center placement

in bootstap this is .container

**Comment by hippee-lee** [comment]
Hey @KANekT, 

I'm not sure what you mean (in the context of a Clarity application) when you say 

> but this does not solve my case: center placement.

Please create a [Stackblitz](https://stackblitz.com/@clr-team) that demonstrates the issue and post a question on Stackoverflow. This does two things for us, 
1. it lets us talk in code on a q/a site geared towards that type of conversation
2. demonstrates what you are trying for addressing your issue

This helps us understand how you are using Clarity and makes it possible to provide help.
Thanks.

**Comment by gnomeontherun** [comment]
Closing this as inactive without a reproduction.
