### ISSUE TITLE
.datagrid-column-separator element is outside the .clr-dg-column element (host)

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#2972]
## Describe the bug

When using columns that can be hidden if the last column is hidden the `.datagrid-columnseparator` element from the previous column is outside the `clr-dg-column` host. This causes a horizontal scroll bar to appear when the last column is hidden. 

## How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v1-0-3-hide-show-scrollbar-issue

1. Go to stackblitz
2. make sure all datagrid columns are fully displayed in browser (e.g no horizontal scrollbar to begin with)
3. Hide last column. 

## Expected behavior

When the last column is hidden (as described above) there should not be a scrollbar. 

## Versions

**App**

* Angular: 7.1.4
* Node: n/a
* Clarity: 1.0.3-patch

**Device:**: all

**Comment by Shijir** [comment]
I think this is actually an old issue, first reported here: https://github.com/vmware/clarity/issues/1248.

**Comment by hippee-lee** [comment]
I'm pretty sure I fixed it with the render refactor.

**Comment by hippee-lee** [comment]
It looks like this wasn't fixed during the render refactor changes that went in. I'll close it in favor of the original issue. #1248
