### ISSUE TITLE
datagrid hide and show after header column  drag  clarity version 1.0

### ISSUE THREAD

**Issue by muruganG** [vmware/clarity#2976]
## Describe the bug

In the datagrid header  columns resize dragging after  hide and show uncheck  columns   only check resized column then its only taking how much resize  width  only taking remaining space will be black screen 

## How to reproduce
This issue u can able to reproduce in the clarity 1.0 document  datagrid  hide and show  option  

1.  Go to Clarity documentation 1.0 and try to open the datagrid  ,In the datagrid page one feature called hide and show 
2.  Click on  hide and show ,once opened the page try to resize  one header column and the  footer hide and show other columns uncheck except resized column
3.  See error

![image](https://user-images.githubusercontent.com/10629787/50570565-569f4c00-0db6-11e9-8b54-15e35fe297d8.png)

## Expected behavior
It show take datagrid complete with.

**Comment by hippee-lee** [comment]
Sorry, I changed the name. Here is the updated link: https://stackblitz.com/edit/clarity-v1-0-theme-switcher-static
