### ISSUE TITLE
Visual discrepancy of "close X" button in alerts, modals, and wizards

### ISSUE THREAD

**Issue by yenmade** [vmware/clarity#298]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```
The following tasks will be needed:

- [x] Determine the desired visual style for the close X icon
- [ ] Update ~~Sketch/Invision files or~~ code accordingly

### Expected behavior
The "close X" icon in modals and wizards should match the website documentation for respective components.

### Actual behavior
The "close X" icon in the Sketch template as well as Invision files are visually different from what's implemented and on the website. 

### Reproduction of behavior
Download Sketch template, go to https://vmware.github.io/clarity/documentation/modals or https://vmware.github.io/clarity/documentation/wizards

**Comment by reddolan** [comment]
This also affects [Alerts](https://vmware.github.io/clarity/documentation/alerts) and Signpost (in dev). 

I recommend we use the InVision specs. The Wizard and Modal would have a 16x16 Dismiss icon, using the new icon. The Alerts and Signpost would use the new Dismiss icon at 10x10. The examples that exist on the site look like they are using the previous Dismiss icon. 

This recommendation would then mean those components would need to be updated.

The UI Template matches the InVision specs, so no changes would need to be made there. 

cc: @lil-kim

**Comment by reddolan** [comment]
The decision was to update the component code to use the Dismiss icon.

**Comment by mathisscott** [comment]
This tangentially affects the wizard refactor (#156). So I've picked it up because I have questionable judgment.

**Comment by mathisscott** [comment]
I'm moving this to 0.8.3. I initially thought that the close "X" was just in a couple of places. But it's not. It's in four components (possibly more) and many, many demos on the demo-app and website. So the scope of work is about two or three times what I thought it was to begin with.

Given that today has started filling up with meetings, there's no way I'll have this done today.
