### ISSUE TITLE
Unable to display UI element in new Form

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#2983]
## Describe the bug

I currently have an application that displays a Select element who's values are populated from entries in a backend database table. I'm trying to add either a button or '+' icon next to the Select element that would open a modal dialog box where the user can define a new entry in the Select list if necessary (and hence eventually be saved to the database). However I can't get a button or '+' icon to display next to the Select element. 

I can display it if I place the the tag within the Label component but this is ugly. I am open to suggestions to alternate UX solutions if you can think of one that would provide this capability.

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v1-0-saaqif
2.  Load the page
3.  See the visible button displayed next to the label. The button should display immediately to the right of the Select element is invisible. See app.component.html file for page code.

## Expected behavior

A UX element displays offering the user an option to add another element to a Select element.

## Versions

**App**

* Angular: 7.1.1
* Node: [e.g. 8.10.0]
* Clarity: 1.0.3 patch

**Device:**

* Type:Win 7
* OS: Win 7
* Browser Firefox IE11, Chrome 70, Firefox 63
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This is related to #2970 and the fix I am working on should address this as well.

**Comment by beaker1977** [comment]
If this is related to 2970 then you can close and I'll keep my fingers crossed your fix kills two birds with one stone.
