### ISSUE TITLE
ClrDatepickerModule Unexpected value imported

### ISSUE THREAD

**Issue by jbrown7488** [vmware/clarity#2985]
## Describe the bug
When trying to build AoT I'm getting the following
ERROR in : Unexpected value 'undefined' imported by the module 'ClrDatepickerModule in node_modules/@clr/angular/clr-angular.d.ts'

## Versions

**App**

* Angular: 7.1.4
* Node: 8.10.0
* Clarity: 1.0.3

**Device:**

* Type: Surface
* OS: Windows 10
* Browser: Chrome
* Version: 71.0.3578.98

**Comment by dorthrithil** [comment]
I'm quite sure this was fixed in 1.0.3-patch

**Comment by jbrown7488** [comment]
I'll try updating to it. Thanks

**Comment by jbrown7488** [comment]
That was it. Sorry should of tried that. Thanks.
