### ISSUE TITLE
Crosshairs icon

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#2987]
## Summary

* What is the icon?

A crosshairs symbol like you know it from e.g. guns.

* What does the requested icon signify?

It signifies a target.

* In which product(s) will this icon be used?

This kind of icon is commonly used to set a map to "your location".

## Use case

In my application I have a map which can either be set to a location by geocoding some query or using the browsers geolocation API. For the latter I need an appropriate icon for the button.

## Examples

From Google Maps:

![screen shot 2019-01-03 at 20 58 02](https://user-images.githubusercontent.com/3655915/50659007-73e13f80-0f9b-11e9-96b5-4da81b83e3a2.png)

## Alternatives

Maybe `target`, `compass` or `map-marker`. But I think crosshairs are better as most people are used to that icon because of Google Maps popularity.

**Comment by lil-kim** [comment]
Icon completed and published to Clarity icon library as part of epic #3099
