### ISSUE TITLE
Visual discrepancy - Header text in Sketch Template and Build

### ISSUE THREAD

**Issue by EileenLB** [vmware/clarity#299]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```
The following tasks will be needed:
1.  Determine the desired visual style for the Header text 
2. Update Sketch/Invision files –or– code accordingly

### Expected behavior
The appearance & specifications for the text in the Screen Header should be consistent between the Sketch Template and the build.

### Actual behavior
The color, font-weight, and font-size in the Sketch Template are different from what is implemented in the Clarity build.

### Reproduction of behavior
_**In the Build**:_      – use a devtool to "inspect" the element.
_**In the Sketch file**:_  –    select the text string to see its specs
_See also the attached images and bulletted lists below._

#### Example 1 – `.nav-text` in its Normal state ...includes inherited values from `.nav-link`

**font-weight**
1. sketch: &nbsp;400 &nbsp;(Metropolis Regular)
2. build: &nbsp;500

**color**
1. sketch: &nbsp;#fff 
2. build: &nbsp;#fafafa 

**opacity**
1. sketch: &nbsp;100%
2. build: &nbsp;65%
<![nav-text-sketch](https://cloud.githubusercontent.com/assets/14795506/21556373/c5e3a33c-cdd4-11e6-9921-4417ade15504.png)><img width="217" alt="nav-text-build" src="https://cloud.githubusercontent.com/assets/14795506/21556374/c5e3e4fa-cdd4-11e6-8627-79b3323b9eb8.png">

<hr>

#### Example 2 – `.title` in its Normal state 

**font-size**
1. sketch: &nbsp;17px
2. build: &nbsp;16px 
![title-sketch](https://cloud.githubusercontent.com/assets/14795506/21556399/ec999888-cdd4-11e6-8151-467721212dc3.png)<img width="217" alt="nav-text-build" src="https://cloud.githubusercontent.com/assets/14795506/21556408/fe58ec04-cdd4-11e6-86b8-9a27f4c592c9.png">

<hr>

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.8.0

* **OS and version:**  All

* **Browser:** all

**Comment by yenmade** [comment]
I believe this is a known issue and @reddolan will be updating in the next version of the Sketch UI template. The header font styles should match the latest file in Invision. @reddolan Can you confirm?

**Comment by reddolan** [comment]
All of these updates will be in the next release of the UI Template

**Comment by reddolan** [comment]
update coming in #325 for 0.8.2 next week
