### ISSUE TITLE
Rating component

### ISSUE THREAD

**Issue by designalex** [vmware/clarity#2990]
## Summary

We are in need of a rating component. For our use case, it's for collecting 7-scale NPS and PSAT scores. 

It's new - I don't currently see a rating component that could fit this use case in Clarity.
Why - we did notice that other design systems have such a component and wonder if we should have one for Clarity. 

## Use case

The use case is to provide a rating mechanism for products that are collecting feedback.
It could also be considered as horizontal radio button group.  

## Examples

https://ant.design/components/rate/
http://hellosnl.blogspot.com/2018/01/lightning-star-rating-component.html
![Screen-Shot-2016-06-16-at-5-24-31-PM.png](https://images.zenhubusercontent.com/5c2e8ba7a336ec068063787d/26ccef6c-98c0-4398-a8ac-ee8003238466)
![nps-example1.png](https://images.zenhubusercontent.com/5c2e8ba7a336ec068063787d/4e4f04d4-b115-444c-b290-8fb4e242f5fb)
![Screen Shot 2019-01-03 at 2.45.56 PM.png](https://images.zenhubusercontent.com/5c2e8ba7a336ec068063787d/b12cb109-7491-497a-b0b2-8947956f3f12)

**Comment by mathisscott** [comment]
@colinreedmiller and @gnomeontherun 
Any first impressions about inclusion of a component like this in the library? Do we have any alternative options available? I'm happy to move it into our backlog if not.

**Comment by colinreedmiller** [comment]
I have been speaking with Alex about this - it seems that much in the way we use **button** to create **button-bar** we could re-purpose **radio button** to create a horizontal **radio button bar**. The functionality is that of a radio button group with X options arranged horizontally. The visual design Alex did for his application is similar spec for the timeline: [https://app.zenhub.com/workspaces/clarity-5829bbc3b399ebbf183145bf/issues/vmware/clarity/1633]

I am not sure how valuable this is, perhaps arranging radio buttons as they exist in a horizontal fashion is sufficient. Any relationship with the timeline component begs the question of those steps (timeline) being actionable as navigation.

Very standard style: 
![image](https://user-images.githubusercontent.com/44213553/50716997-4e0a7800-1039-11e9-98c1-d654dbd787da.png)

**Comment by mathisscott** [comment]
Giving it a similar look to the timeline might be confusing. What if you have horizontal radios _and_ a timeline on the same page... yet they function differently?

At a high level, this looks like an HTML/CSS component to me. There isn't much for Angular to do here. So we would really just want to know what the visuals look like. Anyone want to take a swing at that? @designalex ???

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
