### ISSUE TITLE
form-deprecated's form-group indirect descendants span and input style issue

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#2991]
## Describe the bug

In deprecated form, under `.form-group` element, the `span` & `input` elements of the 3rd party input component will have unexpected margin-top & margin-bottom

## How to reproduce

```
<div class="form-group">
  <label for="clr-form-appIds">App Ids
  </label>
  <label for="clr-form-appIds"
    [style.position]="'relative'">
    <ng-select class="multi-tag"
      [labelForId]="'clr-form-appIds'"
      [items]="[]"
      bindLabel="name"
      [addTag]="true"
      [multiple]="true"
      [hideSelected]="true"
      ngDefaultControl
      formControlName="appIds">
    </ng-select>
  </label>
</div>
```

ng-select uses span for multi-tag display and input for entering new item. The ng-select's tag and input box will have unexpected margin-top & margin-bottom.

## Expected behavior

As commented in [this line](https://github.com/vmware/clarity/blob/399ea3b8174b4d2efb5e949e7ea2e70d36f86bdb/src/clr-angular/forms-deprecated/_forms.clarity.scss#L145) the styles should only affect direct descendants of `.form-group` element.

## Versions

**App**

* Angular: 6
* Node: 10
* Clarity: 0.12

## Additional notes

add `& >` to each selector may fix it, but what about the grid as commented in [the next line](https://github.com/vmware/clarity/blob/399ea3b8174b4d2efb5e949e7ea2e70d36f86bdb/src/clr-angular/forms-deprecated/_forms.clarity.scss#L146)?

**Comment by gnomeontherun** [comment]
I don't think we can make this change without a breaking change, which is something I don't think we will do for deprecated forms at this stage. I'll double check with the team on this.

It sounds like you can override the margins on your side to compensate for now, which is the recommendation for now.

**Comment by gnomeontherun** [comment]
I'm going to close this as we cannot make this change and its also uncertain that we'd solve the problem on our end with third party components styles changing in ways we can't always anticipate either. The workaround is to make some styling changes as necessary in the app level.
