### ISSUE TITLE
Add possibility to track errors in datepicker

### ISSUE THREAD

**Issue by dsteegen** [vmware/clarity#2992]
## Summary

Currently the date picker does not have support to check if an invalid date is entered in the component. Adding the validation ourselves is not so easy as we need to know what the format of the date is. This is determined via the configured Locale of the Angular app in an internal Clarity service.

* What is the change?
Create a component that implements the Angular `ControlValueAccessor` interface. This allows users bind the value to a `FormControl`. The `FormControl` should be marked as invalid if the an invalid value was entered for the date.

* Why should it go in Clarity?
This seems to be a common use case that probably many people can benefit from. 

* Does this change impact existing behaviors? If so how?
This should normally not break existing features.

* If this change introduces a new behavior, is this behavior accessible?
Yes. 

## Use case
Add a date picker on a form group. The save button of the form should not be enabled if the date picker contains an invalid date (e.g wrong format or a date in the past, or ...). 

## Workarounds

Checking on the interval value of the date picker. If this is null and the HTML input has a text value, the value can be considered as invalid.

**Comment by gnomeontherun** [comment]
This should be completed with the forms refactorings done so as long as you mark a field as invalid with Angular, there is error support.
