### ISSUE TITLE
Datepicker two-way binding broken when re-selecting an old date

### ISSUE THREAD

**Issue by BramMeerten** [vmware/clarity#2993]
### Describe the bug
When using two-way binding with the date picker and when I:
1. Select a date
2. Set a date programatically
3. Select the first date again

The last selected date is not emitted.

### How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v1-0-uyhtqy?file=src/app/app.component.ts

1. Select a date (for example 2018-01-02)
2. Click the 'Update to 2019/01/31' button.
3. Select te same date as in the first step again.

### Expected behavior
The last selected value should be emitted.

I suspect this bug happens because the ```previousOutput``` field is not updated when programatically setting the date, this way ```previousOutput``` has an even older value and when selecting that value again, nothing is emitted:
```
private emitDateOutput(dayModel: DayModel): void {
    if (dayModel && !dayModel.isEqual(this.previousOutput)) {
      this._dateUpdated.emit(dayModel.toDate());
      this.previousOutput = dayModel;
    } else if (!dayModel && this.previousOutput) {
      this._dateUpdated.emit(null);
      this.previousOutput = null;
    }
  }
```
[Link to source](https://github.com/vmware/clarity/blob/399ea3b8174b4d2efb5e949e7ea2e70d36f86bdb/src/clr-angular/forms/datepicker/date-input.ts#L238).

### Versions
Angular version 7.0.0
Clarity version 1.0.3-patch
Google Chrome 71.0.3578.98 (Official Build) (64-bit) (cohort: Stable)

**Comment by gnomeontherun** [comment]
Thanks for the report, this does look like a bug and we'll work it into our backlog soon.
