### ISSUE TITLE
bootstrap classes not found in @clr/ui

### ISSUE THREAD

**Issue by winster** [vmware/clarity#2994]
## I use angular 7
I included clarity using "ng add @clr/angular"
this automatically added following lines in angular.json
"node_modules/@clr/icons/clr-icons.min.css",
"node_modules/@clr/ui/clr-ui.min.css",

Now in one of the component.html, I used following html snippet

> <something>
    <div class="row"><div class="col">
      1 of 2
    </div>
    <div class="col">
      2 of 2
    </div></div>
  </something >

Columns didn't render in a single row. When I checked styles, I could not find any styles related to .row or .col. These classes I could not find in "clr-ui.min.css". What went wrong here?

**Comment by gnomeontherun** [comment]
We don't support the Bootstrap grid in v1.0 without using the deprecated file. Instead I recommend that you use our grid classes, documentation can be found on our site at https://vmware.github.io/clarity/documentation/v1.0/grid.

Its very similar to Bootstraps except the class names are prefixed with `clr-`.
