### ISSUE TITLE
table paging

### ISSUE THREAD

**Issue by yanyixing** [vmware/clarity#300]
**Select one ...**  (check one with "")
```
[ ] bug
[x] feature request
[ ] enhancement
```
Is the table paging component  on the roadmap ?
This is a common component in other UI frameworks

**Comment by jaffoneh** [comment]
@yanyixing what do you mean by table paging? Are you referring to datagrid/datatable? It's available here: https://vmware.github.io/clarity/documentation/datagrid

**Comment by yanyixing** [comment]
function just like bootstrap datatable's paging
https://datatables.net/manual/styling/bootstrap

**Comment by yanyixing** [comment]
I have found this component, thanks

**Comment by jaffoneh** [comment]
No problem. Feel free to provide feedback or open issue on the datagrid component itself as you use it. Closing this issue based on the last comment.
