### ISSUE TITLE
tooltip ：The prompt text is covered by the outer layer.

### ISSUE THREAD

**Issue by jwangyangls** [vmware/clarity#3000]
## Describe the bug

_When we need prompt text, the page is smaller, and the prompt text appears below the input, then it is covered and blocked by the outer layer._

## How to reproduce

![image](https://user-images.githubusercontent.com/29826789/50807995-88289200-1337-11e9-8761-02cff0c04b15.png)
Tips are long，but it shows part of it.

## Expected behavior
I hope all the tips will be displayed.
![image](https://user-images.githubusercontent.com/29826789/50808264-a6db5880-1338-11e9-9e07-88f52007d4ec.png)

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 1.0.3]

**Device:**
* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version []

**Comment by youdz** [comment]
This is a known issue, we are currently rewriting our popovers to fix it: #2923.

We have moved away from validation tooltips in forms, however, so your specific problem would be solved if you moved to new forms with inline error messages.
