### ISSUE TITLE
[Docs] selection-single page small improvements

### ISSUE THREAD

**Issue by danail-vasilev** [vmware/clarity#3002]
## Small documentation improvements:

https://vmware.github.io/clarity/documentation/v1.0/datagrid/selection-single

1) The link to "Cards" at the end of the page is not valid
2) In the same page but previous versions there is a typo with clrDgRowSelection property(i.e., clDgRowSelection)

**Comment by gnomeontherun** [comment]
fixed in https://github.com/vmware/clarity/commit/0d0b46a4e3e1bbb2f56554e92d4fc8e856abe655
