### ISSUE TITLE
Wizard first title misaligned

### ISSUE THREAD

**Issue by EricsG95** [vmware/clarity#3006]
## Describe the bug

This can be seen from the first title in wizard navigation page page as I was using. The title of the first one is not aligned with the rest of the titles of the bottom one. I am not sure it is by design or not, or it is a bug. What is the reasoning behind this?

## How to reproduce
I have attached the screen shots from official page documentation, and it already looks in that way without the need to modify anything out of the box.

![wizard header misalign](https://user-images.githubusercontent.com/10571842/50879162-e4adaf00-1414-11e9-816b-b4023891bddb.JPG)

1.  Go to https://vmware.github.io/clarity/documentation/v1.0/wizards
2. Open the wizard, you should be able to see it already

## Expected behavior

The first title should be in alignment with the rest of the titles below.

## Versions

**App**

* Angular: 7.1.3
* Node: 8.11.3
* Clarity: 1.0.3-patch

**Device:**

* Type: Lenovo Thinkpad P50
* OS: Windows 10, 1707, build 16299.846
* Browser Chrome
* Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by Jinnie** [comment]
Numbers and text are not separately aligned. Text follows the number with a specified padding. As 1 is narrower than 2, 3... the first line title is not aligned. Here's what will happen with > 10 items:

<img width="235" alt="screen shot 2019-01-09 at 1 10 14 pm" src="https://user-images.githubusercontent.com/1798828/50896070-a0201480-1410-11e9-8e3e-597b51598f49.png">

Now sure how/if we should address this. Maybe some UX comment would be beneficial.

**Comment by gnomeontherun** [comment]
This wasn't considered high priority from UX given the refresh work going on internally at the moment, however the workaround if you are bothered by this is to add styles like this.

```css
.clr-wizard .clr-wizard-stepnav-link::before {
  display: inline-block;
  width: 1rem; // pick your own width here
}
```

**Comment by EricsG95** [comment]
I see, I understand. Thank you so much for your response as well as the quick fix. Appreciate it much @gnomeontherun!

**Comment by mathisscott** [comment]
This won't be fixed until we get tabular numbers on our font.
