### ISSUE TITLE
Wizard height issue in Mozilla firefox 

### ISSUE THREAD

**Issue by rameshyala** [vmware/clarity#3007]
Hi, In wizard page have more then six controls (exceeds the normal height), in Mozilla browser scroll is not coming , It is working fine in Chrome browser. Check the [Stackblitz]( https://stackblitz.com/edit/clarity-7fjkeh?file=app%2Fapp.component.html)  in Mozilla firefox browser.

Thank you.

![image](https://user-images.githubusercontent.com/18004992/50893834-d61cc300-1427-11e9-9a15-5813d1a04309.png)

**Comment by Jinnie** [comment]
Confirmed this. Firefox interprets height: 100% on the .modal-content-wrapper differently than Chrome. Adding a max-height: 100% for safety seems to be fixing it.
Running some tests, updating some more tests and we'll have a fix soon, I guess.
