### ISSUE TITLE
Reactive Form Date Picker with value as date object

### ISSUE THREAD

**Issue by mohammedzamakhan** [vmware/clarity#3008]
## Describe the bug

I am using Reactive Forms, and if I use date picker, I only get dates as string, but I need it to set Date Object instead

## How to reproduce

Go to https://clarity.design/documentation/datepicker#examples, and check the reactive forms demo

1.  Go to https://clarity.design/documentation/datepicker#examples
2.  Click on Select the date from the date picker
3.  Check the value below
4.  No ability to get the date as a Date object unlike template driven forms

## Expected behavior

A way to get the value as Date Object

## Versions

**App**

* Angular: 7.2.0
* Node: 9.1.0
* Clarity: Latest

**Comment by gnomeontherun** [comment]
You should still be able to get the date object out by using `(clrDateChange)="dateObject"`, so you should be able to unblock yourself there. 

Also, you could use the `valueChanges` observable on the form control to listen for changes in your controller and convert the string to a date. See https://angular.io/api/forms/AbstractControl#valueChanges. 

I honestly don't remember why we have this limitation at the moment, but that should at least unblock you.

**Comment by xantin** [comment]
How to use (clrDateChange)="dateObject"? E.g.  if I use it this way
`<input id="dateControl" type="date" formControlName="expiration" clrDate (clrDateChange)="dateObject" />` the **dateObject** is lways null.

Is there any documentation about **clrDateChange**, please?

**Comment by Jinnie** [comment]
Hi, @xantin 
There is no explicit documentation of this case, but it is specified as 2-way binding in our docs:
<input type="date" [(clrDate)]="date">
Which you can decompose like this, for your need:
<input type="date" clrDate (clrDateChange)="dateChanged($event)">
...
dateChanged(date: Date) {
 // do something with date
}

**Comment by Jinnie** [comment]
Note:
If we consider starting work on this enhancement, we must also address the use of Date object with template-driven forms. Leaving this issue open to track the request. Closing duplicates in favor of this issue.

**Comment by gnomeontherun** [comment]
Long term, we're going to want to standardize all values as date strings. This will put us in alignment with how HTML input[type=date] elements work, but I don't see a reason to make this change until we've built a web component version of this. We'll keep this in the backlog, and bring it up when we revisit the date picker for.

**Comment by gnomeontherun** [comment]
This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
