### ISSUE TITLE
Ability to disable particular dates in the date picker

### ISSUE THREAD

**Issue by mohammedzamakhan** [vmware/clarity#3009]
## Summary

Date picker should have the ability to disable particular dates. Probably adding a Input that takes a function that disables particular dates of the month, or even it can disable the months or years in the date picker selection.

* What is the change?
* Why should it go in Clarity?
* Does this change impact existing behaviors? If so how?
* If this change introduces a new behavior, is this behavior accessible?

## Use case

There can be so many use cases for this.

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

Don't know of any as of now

**Comment by yogeshnagrath** [comment]
Hi all,

We are also facing one issue of similar type.

In our case, we want to block all the dates except the ones which are in particular range of dates.

For eg: Lets take january 2021, we want to enable only 5th-10th jan, 15th-20th jan and 25th-30th jan or 1st-1st jan(same start date and end date).

We need this for our project(Horizon Cloud) to schedule timely upgrades.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
