### ISSUE TITLE
Hideable column appears in expandable column row

### ISSUE THREAD

**Issue by Akay7** [vmware/clarity#3010]
## Hideable column appears in expandable column row

_In a grid with hideable columns and expandable rows_

## How to reproduce

Grid with hideable columns, and expandable row(replace every column).

1.  Hide a few columns
2.  Expand any row
3.  Appears information of hidden columns

## Expected behaviour

_Hidden columns must be hidden from expanded rows_

## Versions

**App**

* Angular: 7.0.0
* Node: v8.11.4
* Clarity: 1.0.3-patch

**Device:**

* OS: Windows 7, openSUSE Leap 15.0
* Browser chrome, firefox
* Version 71.0.3578.98, 60.4.0esr (64-бит)

**Comment by hippee-lee** [comment]
It helps us investigate if you can submit a `Blitz` that replicates your issue. We keep starters here: https://stackblitz.com/@clr-team

It looks like this only occurs with expandable rows that get replaced, can you confirm? 

I think I was able to recreate the issue based on the description but in the future a reproduction is appreciated :-). Please check https://stackblitz.com/edit/3010-replaced-row-hidden-column-issue and confirm this is the same as you are experiencing. 

If it is the same one, I believe its just missing some css that targets that cells in the replaced rows but want to confirm before I push a fix for it.

**Comment by Akay7** [comment]
@hippee-lee Thank you for showing correct `Blitz` for reproducing this bug. In my case bug appears only when grid with hideable columns and showing details of replaceable row.
