### ISSUE TITLE
clrDate input is not emptied on model reset

### ISSUE THREAD

**Issue by lg-mehdi-mhiri** [vmware/clarity#3012]
## Describe the bug

When the model of `clrDate` is set to `null`, the input is not reset to an empty string.

## How to reproduce

[Stackblitz](https://clarity-light-theme-v1-0-7bgwod.stackblitz.io/)

1.  Select a date using the picker, or click the `Today` button
2.  Click on the `Clear` button to set the date to `null`
3. The model is emptied, but the input still has the previous value

## Expected behavior

The text in the input should be emptied.

## Versions

**App**

* Angular: 7.1.3
* Node: 11.4.0
* Clarity: 1.0.3

**Device:**

* Type: PC
* OS: Windows 10
* Browser: Firefox
* Version: 65

## Additional notes

Related to #2474, but not a duplicate (that issue only concerned reactive forms)

**Comment by mathisscott** [comment]
@coryrylan 
Could you check to see if this is still an issue in 1.0.4?

**Comment by Jinnie** [comment]
A workaround would be to manually reset the ngModel of the input (as we're using angular form as a basis of our component).
Here's a stackblitz:
https://stackblitz.com/edit/clarity-form-reset?file=src%2Fapp%2Fapp.component.html
