### ISSUE TITLE
Alert: Disabled Property for Links, Actions Isn't Used?

### ISSUE THREAD

**Issue by ahand** [vmware/clarity#3015]
## Describe the bug

There is a property in the Alerts section of the Dark Theme file called $clr-alert-app-disabled-color. However, when I set its value, I don't see anywhere in the Alerts controls where that value is picked up in the Kitchen Sink app.  It's class is "dropdown-toggle". 

If the Actions link item is enabled, it should pick up the color as specified in this property: $clr-alert-action-color. (Which it's not.) 

If the Actions link is disabled, then I would expect it to pick up the disabled color property: $clr-alert-app-disabled-color.

## How to reproduce

I made changes to the properties shown in the file:  
clarity-master/src/clr-angular/utils/_theme.dark.clarity.scss

Examples of values: 
//This disabled property doesn't affect the 'Actions' links in the red Alert in the screenshot
$clr-alert-app-disabled-color: #640480; 

$clr-theme-alert-font-color: #000000;

$clr-alert-danger-bg-color: #FFF7F7;
$clr-alert-danger-font-color: #000000;
$clr-alert-danger-border-color: #D20000;  
$clr-alert-danger-icon-color: #D20000;  

$clr-alert-action-color: #000000;
$clr-alert-action-active-color: #000000;

1. In the Alerts section of the Dark Theme file, change the color for the property, $clr-alert-app-disabled-color, to something outrageous, like Purple. 
2.  Run the Clarity Kitchen Sink app.
3.  View the Static Alerts section of the demo. 
4.  In the first couple of Error alerts, you'll see an Actions link with a dropdown arrow. The Actions links are gray and look disabled. However, the text color is unchanged and is not the outrageous color set in Step 1, such as Purple. 

## Expected behavior

If the Actions link item is enabled, it should pick up the color as specified in this property: $clr-alert-action-color. 

If the Actions link is disabled, then I would expect it to pick up the disabled color property: $clr-alert-app-disabled-color. Or maybe I've overlooked a relevant property? 

## Versions

Kitchen Sink app as downloaded from Git on Monday, Jan. 7, 2019.

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: Appears to be v1.0.3

**Device:**

* MacOS, Chrome

![alert - disabled text issue](https://user-images.githubusercontent.com/11655671/51003292-fb263a00-14ea-11e9-8bc7-127e0ec08e03.png)

**Comment by gnomeontherun** [comment]
This value is not used anywhere based on a search of the project, so I'm guessing it was a mistake that got through. I'll mark this for removal.

**Comment by mathisscott** [comment]
@gnomeontherun is correct. `$clr-alert-app-disabled-color` is not being used. It will be removed.
