### ISSUE TITLE
External links not work in clr-header

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#3018]
## Describe the bug

external links with HREF attribute don't work in clr-header component

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-n46px4

## Expected behavior

Click on an external link should navigate to the address assigned to the HREF attribute.

**Comment by gnomeontherun** [comment]
You've got a click handler on the header itself, which is taking over the default href and linking behaviors. I removed that and it works fine. 

Closing as you probably don't want to have a click event binding on the whole header.

**Comment by KingMario** [comment]
Thanks
