### ISSUE TITLE
[component] stepper architecture

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#3019]
## Feature Proposal UX
- See issue https://github.com/vmware/clarity/issues/2503

## Static HTML/CSS
  - static html/css example https://stackblitz.com/edit/clarity-light-theme-v1-0-ddavun

## Test Cases
- [ ] It should prevent user from moving to next step if form is invalid or async failure
- [ ] It should allow user to go to previously completed step
- [ ] It should set step state to active on previously completed step when navigated back to previous step
- [ ] It should collapse all future steps if user opens previously completed step
- [ ] It should notify when all steps have completed
- [ ] It should notify when an individual step has completed (or maybe a state change, error/complete?)
- [ ] It should render error state when set programmatically
- [ ] It should render complete state when user goes to next step without error
- [ ] It should render the first step as active and open initially with all other steps closed
- [ ] It should allow programmer to force stepper to next step if next step is disabled for async processing
- [ ] It should show appropriate active/complete/error/inactive icons in respective states
- [ ] It should allow programmer to explicitly set a step as complete without user intervention (ex pre populated steps/edits)
- [ ] It should allow programmer to explicitly reset the stepper state
- [ ] It should set appropriate number for step and consider dynamic steps being added or removed
- [ ] It should be able to use full keyboard to navigate between steps
- [ ] It should set state properly for screen reader functionality

**Comment by sdurnov** [comment]
Ehh, I was hoping to see something visually lighter. Anyway, nice to see that @coryrylan has so much energy. Looks like Clarity development speed is increasing.

**Comment by Jinnie** [comment]
The prototype looks nice.
I have a general question though. Cory, it's not about the way you are implementing it, but more about the spec we have.
Are we sure that in the "Error state" handling we want to replace the step number with exclamation mark circle? It looks pretty cool, I admit, but I am not sure it is very accessible. We're losing information that may be helpful for the accessible navigation this way.
Any thoughts, team?

**Comment by Jinnie** [comment]
@mathisscott I agree numbers are not crucial. Thanks for the detailed answer.
I checked it with a screen reader and it just skipped the error icon. Primarily that's what caught my attention and made me start the conversation. But for testing against a prototype, this is quite okay. I'm sure we'll be handling it in the final version.

**Comment by youdz** [comment]
The icon should have a localized title that reads something like “Error” on a screen reader. Well have that in the Angular version, I guess this static example doesn’t have it.

**Comment by gnomeontherun** [comment]
Just a few comments.

1. What about error in inactive state? That could happen if you had an async validation process perhaps.
1. The UX plan shows an alert below the button, I think we need a demo of that and a recognition of how that might look with the API (do you project it to a specific place)?
1. The DOM for buttons looks fine, just want to point out that we'll want to have a similar implementation for buttons to the wizard. 
1. Curious about the left alignment for the button and content inside of the stepper panel, it looks like its not quite aligned equally with the stepper numbers in the panel titles.
1. The padding between the content and the button in the step panel seems too small.
