### ISSUE TITLE
Cards: Title & Block Color Properties in Theme - No effect?

### ISSUE THREAD

**Issue by ahand** [vmware/clarity#3021]
## Describe the bug

There are two properties in the Cards section of the Dark Theme file and I set their values as follows:
- $clr-card-block-color:  #DE0063;   //A dark pink
- $clr-card-title-color: #00CF92;  //A bright green

After compiling and running the Dark Theme in the Kitchen Sink demo, I looked at all of the pages in the Cards section. However, I couldn't see any traces of the pink or green in the cards. The other colors I changed were white for the background and light gray for the border color. 

$clr-card-bg-color: #fff;
$clr-card-border-color: #CBD2D6;

I made changes to the properties shown in the file:
clarity-master/src/clr-angular/utils/_theme.dark.clarity.scss

1.  Change the values in the dark theme file as noted above. 
2. Run the Clarity Kitchen Sink app.
3. View the Cards section of the demo.
4. Look for any trace of the pink or purple in the cards demo'd on all of the Cards pages. 

## Expected behavior

There aren't any notes in the theme file detailing what to expect. I was thinking the two properties would change either some text color in those sections or the background color. Being able to set both heading text and section background colors independently would be cool. 

## Versions

Kitchen Sink app as downloaded from Git on Monday, Jan. 7, 2019.

Angular: [e.g. 6]
Node: [e.g. 8.10.0]
Clarity: Appears to be v1.0.3

![image](https://user-images.githubusercontent.com/11655671/51052383-50198d00-158b-11e9-9d1d-5f2b5d5f0da4.png)

**Comment by gnomeontherun** [comment]
Both of these are unused and have no impact on rendering. Will mark them for removal.

**Comment by mathisscott** [comment]
I have verified that` $clr-card-block-color` is not being used and will remove it.

I've verified that `$clr-card-title-color` works after the changes in #2942 

Same with bg and border-color.
