### ISSUE TITLE
Dropdown Menu: 3 Text Item Color Properties - No Effect?

### ISSUE THREAD

**Issue by ahand** [vmware/clarity#3024]
## Describe the bug

In the Dark Theme file, there are several text related properties that I set to desired values, but which had no results. So then I set them to outrageous values to see where they would surface. These properties are important, but don't seem to be having any effect. It appears that these properties are being set elsewhere. 

In the Dropdown section of the Dark Theme file: 
- $clr-dropdown-text-color: #640480; //A dark purple. 
- $clr-dropdown-item-text-color: #00CF92; //A bright green
- $clr-dropdown-font-color:  #DE0063; //A dark pink. How does this differ from the above? 

None of the above properties changed any text colors within the dropdown panels. 

Note: The header property is working. 
- $clr-dropdown-header-color: #000000; //This one is OK. 

## How to reproduce

I made changes to the properties shown in the file:
clarity-master/src/clr-angular/utils/_theme.dark.clarity.scss

1.  Change the values in the dark theme file as noted above.
2.  Run the Clarity Kitchen Sink app.
3.  View the Dropdown section of the demo.
4.  Note how none of the dropdown panels are affected by the properties above. 

## Expected behavior

When I change the properties listed above, I expect to see an effect.  

## Versions

**App**

Kitchen Sink app as downloaded from Github on Friday, Jan. 11, 2019.

Clarity:  v1.0.4

![image](https://user-images.githubusercontent.com/11655671/51062805-1f4a4f80-15ad-11e9-8e90-e65958cb840a.png)

**Comment by ahand** [comment]
With further investigation, this is what I've found. 

I set this property to Orange. 
$clr-dropdown-item-text-color: #FF9600; //  orange 

I saw the dropdown panel appear with orange text in multiple controls in the Kitchen Sink demo, as expected, including: 
- Cards > Dropdowns in Cards
- Combobox Basic & Optional Menu
- Dropdown main page, unselected text. Note that the Disabled Link text color appears to be calculated, rather than using a specific property.

Didn't find evidence of the other 2 properties being used, though. 
- $clr-dropdown-font-color
- $clr-dropdown-text-color


![image](https://user-images.githubusercontent.com/11655671/51153000-4611bb80-1823-11e9-8aea-ea7aa0a81faa.png)

**Comment by gnomeontherun** [comment]
The `$clr-dropdown-text-color` is used by the dropdown inside of alerts. The `$clr-dropdown-font-color` is not used anywhere and I'll mark for removal.

**Comment by mathisscott** [comment]
`$clr-dropdown-font-color` is not used. Maybe it was legacy and never got removed?

`$clr-dropdown-text-color` and `$clr-dropdown-item-text-color` were both giving me a little trouble but I've cleaned them up and will have a PR for that soon.
