### ISSUE TITLE
Calendar Control: Theme Issues

### ISSUE THREAD

**Issue by ahand** [vmware/clarity#3028]
## Describe the bug

Using the Dark Theme to set values, there are multiple properties that don't seem to be used or to have the intended effect.

## ISSUE 1
It's not clear what this property's intended usage is, but the current implementation seems incorrect. My guess is that this property's color is intended to be the background color for the newly selected date, and shown on mouse down.
$clr-calendar-active-cell-background-color: #DE0063; //Pink. This is the problematic property.
$clr-calendar-active-focus-cell-background-color: #E4F1FB; //light blue

1. Today's date is Jan. 11, 2018.
2. Using the calendar control, select a different date, such as Jan 18, 2018. 
3. Click off so that the control disappears and you see 1/18/2019 in the input field. 
4. Click on the calendar icon to display the control again.
5. Mouse down on a different date, such as Jan 14. While the mouse is down, you'll notice that the background of 1/14 is light blue, the focus sell bg color. You also note that the originally selected date's background color is now the pink property for the active cell bg color. This is the only time the pink property is expressed. 
6. You'll notice the same issue when changing the month or year. On mouse down for a new month or year, the original's cell is pink. 

## ISSUE 2 
I set these 2 properties individually to outrageous colors. However, I couldn't see any evidence of their usage in the UI. What are these two properties for? 
$clr-datepicker-trigger-color: #DE0063;  //Pink
$clr-datepicker-trigger-hover-color: #B500A0; //Purple 

## ISSUE 3
The popup panel to display the date doesn't seem to be aware of the edge of the browser. As a result, the date panel can appear mostly out of scrolling bounds. See the screenshot where the date input field is at the bottom of the Kitchen Sink app's Layouts page, and the date panel appears below it. Instead, I expected the date panel to dynamically determines that it needs to display up instead. I noticed this issue with other popup panels as well, in both Chrome and Safari on the Mac. 

I made changes to the properties shown in the file:
clarity-master/src/clr-angular/utils/_theme.dark.clarity.scss

## Versions

**App**

Kitchen Sink app as downloaded from Github on Friday, Jan. 11, 2019.

Clarity: v1.0.4

![image](https://user-images.githubusercontent.com/11655671/51066800-8245e180-15c1-11e9-878f-943b43d84dc2.png)

<img width="896" alt="image" src="https://user-images.githubusercontent.com/11655671/51066808-896cef80-15c1-11e9-8a99-71094cb1d964.png">

**Comment by gnomeontherun** [comment]
1) `$clr-calendar-active-cell-background-color` only sets the background color of the selected cell. Then `$clr-calendar-active-focus-cell-background-color` is the background color when the cell is selected, and focused. To see this, you need to use keyboard navigation. See: select a date, reopen picker, use arrow keys to navigate away from and back to the selected date. The color changes should match these two variables and only apply if the date is already selected.

2) These properties only apply to the old forms implementation of the date picker, the new forms (v1.0+) don't need these and you can ignore them. What you'll need to set is `$clr-forms-focused-color` which will set this color for now, or write a CSS rule to target `.clr-input-group .clr-input-group-icon-action` with a new color.

3) We know about this issue, and our work on a new popover implementation will solve this problem (in several places where we have popover content going off page or not dynamically positioned).

Based on the above, I believe this can be closed.
