### ISSUE TITLE
Built-in base64 woff Metropolis font renders different to everything else?

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3031]
## Describe the bug

Clarity uses base64-compiled woff version of Metropolis R8 font, if I'm correct.
I compared it to otf/ttf and woff versions (installed locally or fetched from Metropolis R8 github) and found that base64 version is identical to TTF and has serious differences with OTF version and non-embedded WOFF (1) version. At the same time, OTF renders very similar to standalone WOFF, but still, OTF is somewhat less blurry, small symbols are little bit taller, round elements of symbols are more precise than ones of WOFF.

At the same time, base64 and TTF versions, compared to OTF/standalone WOFF, are less bold (OTF is MUCH bolder), there is a noticable difference in some capital letters rendering (for instance, B and E), digits are much taller.

## How to reproduce

Use this Blitz: https://stackblitz.com/edit/clarity-light-theme-v1-0-testing-nmvgrd

0.  Remove locally installed Metropolis font, so it wouldn't affect results. Install browser extention that will disable CORS.
1.  Go to styles.scss.
2.  turn off $clr-fontSkipBase64 variable and comment all font-face directives.
3.  PrntScreen or capture any app page content.
4.  turn on $clr-fontSkipBase64 variable and use commented font-face directive groups to check ttf/otf/woff font files one by one.

## Expected behavior

I'm not a font guy, so I'd assume that all options should render the same result, at least within the same combination of hardware, OS and browser

**Comment by sdurnov** [comment]
Quick comparison chart
![image](https://user-images.githubusercontent.com/32732457/51086938-be15ae00-175d-11e9-903b-9609fb3016a8.png)

**Comment by gnomeontherun** [comment]
This is outside of our hands with the old version of Metropolis, but as we move to using Clarity City, this should be resolved. I'm going to close this as out of scope and solved by Clarity City.
