### ISSUE TITLE
UI/UX Object Level functionality - contextual edit - pin line as graphic element 

### ISSUE THREAD

**Issue by jrautenberg** [vmware/clarity#3032]
I have a couple questions about current Clarity design patterns and implementation. I have an in progress layout and am wondering if the questions highlighted on the page regarding object level actions, inline actions, the usage of ancillary graphic elements is going beyond the what would be considered clarity? Are these ideas "not clarity" or "ok". Thanks.
![capacitydetails_summary_azure clarity patterns](https://user-images.githubusercontent.com/44240984/51130414-cdd6d600-17e1-11e9-8a2a-ebbd31d74956.png)

**Comment by gnomeontherun** [comment]
This really isn't a typical issue for GitHub, if you have implementation questions in the future we ask that you use StackOverflow. We watch that as well.

We've documented the Clarity values in our website, but know there are so many things that an application will do that are beyond Clarity. Its hard for us to say what is "considered Clarity" or not, and not really our intention to do this. Rather, you should take our components, UX, and functionality as your foundation and apply the enhancements you need for your own application. Test it with your users to find out if you're doing the right thing or if you need to design it somewhat differently. 

Closing but suggest you talk with your designers about the UX and do any research if our guidelines don't provide guidance.
