### ISSUE TITLE
Alert Functionality

### ISSUE THREAD

**Issue by jrautenberg** [vmware/clarity#3033]
Is there a "Clarity" way of exposing notifications
![success_notification](https://user-images.githubusercontent.com/44240984/51131112-96692900-17e3-11e9-8b81-4025ea00249d.png)
? 
As I look through the design documentation it looks like there might be a 24 px top and bottom margin (particularly in the provided page header example). Is that correct?
Is the intention to have the content of the page shift down to allow for the notification banner?
Currently we are not taking into consideration shifting content and it looks like ...(see attachment). Is this ok by Clarity design patterns?
Can you please help me understand Clarity intentions for how the alert gets exposed to the user in regards to how it effects the page content? 

Thanks.

**Comment by youdz** [comment]
I think what you're looking for is #365, but we don't have a notification component yet. It has severe accessibility constraints that have to be handled both at the design and implementation level, so we do not even have a design ready for it yet. It is not part of our short-term priorities either, but we will take your request into consideration when we plan our next tasks.
