### ISSUE TITLE
Signposts: 2 Unused Theme Properties?

### ISSUE THREAD

**Issue by ahand** [vmware/clarity#3035]
## Describe the bug

In the Dark Theme file, there are 2 properties that appear to be unused. Their names make them sound useful, but I set them to outlandish colors to see what would happen, and nothing appears to have changed. 

$clr-signpost-content-bg-color: #640480; //Purple  //#22343c;
$clr-signpost-content-border-color: #D20000;  //Error Red //$clr-black;

I did a search in the Clarity codebase to see if either property was referenced in other files. Both appear to have no other references, which makes me think that they are unused. 

## How to reproduce

I made changes to the properties shown in the file:
clarity-master/src/clr-angular/utils/_theme.dark.clarity.scss

1. Change the values in the dark theme file as noted above.
2. Run the Clarity Kitchen Sink app.
3. View the signposts section of the demo.
4. Observe that there are no visible effects in the signposts features shown. 

## Expected behavior

If the 2 properties are unused, let's remove them from the Dark Theme file. If they *should* be used elsewhere in the code but aren't, then let's implement those features. 

## Versions

**App**

Kitchen Sink app as downloaded from Github on Friday, Jan. 11, 2019.

Clarity: v1.0.4
![image](https://user-images.githubusercontent.com/11655671/51136906-7725c800-17f2-11e9-9ba3-64792e56c188.png)

**Comment by gnomeontherun** [comment]
Both appear to be unused and should be removed.
