### ISSUE TITLE
[Clarity Website] Header link for Clarity Icons is broken

### ISSUE THREAD

**Issue by Gesh4o** [vmware/clarity#3042]
## 
How to reproduce:
1. Go to: https://vmware.github.io/clarity/documentation/v0.13/datagrid/selection
2. Click "Icons" tab in the header 
3. It routes you to: **https://vmware.github.io/clarity/icons/clarity-icons** (get 404)

## Expected behavior

You should be probably routed to: https://clarity.design/icons.

## Versions

**App**
Official website

**Device:**
https://github.com/vmware/clarity/blob/master/CONTRIBUTING.mdAny

**Comment by Jinnie** [comment]
The redirect seems to work fine, but the https://clarity.design/icons/clarity-icons resource returns 404.
This is the Icons/Getting Started link. The same issue can be observed on https://clarity.design/icons after clicking on "Get started".

**Comment by gnomeontherun** [comment]
This is related to prerendering and could setup a few redirect rules just in case.
