### ISSUE TITLE
Icon download shows sources code instead of direct download

### ISSUE THREAD

**Issue by ChitMeng-VMware** [vmware/clarity#3044]
## Describe the bug

When downloading icons from the Clarity website, it shows SVG source code instead of allowing users to get the SVG file into their local machine.

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to 'https://clarity.design/icons'
2.  Click on any icon on the page
3.  Click on 'SVG ICON' button
4.  See SVG code 

## Expected behavior

SVG file gets downloaded onto the client machine.

## Versions

**App**

* Angular: n/a
* Node: n/a
* Clarity: n/a

**Device:**

* Type: MacBook
* OS: macOS Mojave Version10.14.2
* Browser : Chrome
* Version 71.0.3578.98

**Comment by gnomeontherun** [comment]
Now that we are using GitHub to host the assets, its not sending the right headers to download the file. Need to find a workaround.

**Comment by gnomeontherun** [comment]
That said, the workaround now is to just do File -> Save for the page in your browser. Its an extra step but gets it done.

**Comment by gnomeontherun** [comment]
We can use netlify functions to download the file properly. Should be pretty straightforward, just need to build and test it. https://www.netlify.com/docs/functions/ https://github.com/netlify/functions
