### ISSUE TITLE
datagrid bug

### ISSUE THREAD

**Issue by jwangyangls** [vmware/clarity#3045]
## Describe the bug

When I stretch the browser border, the table border cannot stretch along with it.

## How to reproduce

![image](https://user-images.githubusercontent.com/29826789/51222150-6fdbf700-1977-11e9-99ea-09460b1df385.png)

1.  Go to 'datagrid'
2.Stretching screen.  

## Expected behavior

It is hoped that the border length of the table will automatically extend with the screen, but only the border at the head and tail of the table can be achieved, but not in the middle.

## Versions

**App**

* Angular: [e.g. 7]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 1.0

**Comment by youdz** [comment]
Already fixed in 1.0.2 by #2938.

**Comment by jwangyangls** [comment]
I find that this problem has not been modified yet.

**Comment by Jinnie** [comment]
@jwangyangls Please, provide a stackblitz that reproduces this in new datagrid versions. I just re-tested it with 1.0.5 and it looks fixed to me.
