### ISSUE TITLE
In Datagrid *clrDgItems is not working

### ISSUE THREAD

**Issue by integratedinfosys** [vmware/clarity#305]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The grid should appear with data

### Actual behavior

Grid doesn't show data with *clrDgItems, where as *ngFor works well

### Reproduction of behavior

I am attaching a zip file of the project. Node modules are deleted
### Environment details

* **Angular version:** 2.0.X
2.4.1
* **Clarity version:** 
0.8.0
* **OS and version:** 
Windows 7 64bit
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome and Firebase
[clarity-datagrid.zip](https://github.com/vmware/clarity/files/682544/clarity-datagrid.zip)

**Comment by chunghha** [comment]
Per your angular version and problem described, I assume you're getting the issue of #282

**Comment by integratedinfosys** [comment]
Thanks @chunghha, the problem got solved after I downgraded Angular to 2.4.0.
Clarity Design System is a wonderful. If you maintain a working Kitchen Sink App, will be of greatly appreciated.
