### ISSUE TITLE
The clarity spinner clrDgLoading does not prevent users from clicking edit/delete actions on a row.

### ISSUE THREAD

**Issue by eoincro** [vmware/clarity#3051]
## Describe the bug
The clarity spinner clrDgLoading does not prevent users from clicking edit/delete actions on a row. It occurs as the datagrid is loading the user can still interact with the datagrid as the spinner is running which should be disabled,
## How to reproduce

`
<h2 class="page-title">Solutions</h2>

<app-solutions-list
  [solutions]="(solutionsAdmin$ | async)?.solutions"
  [isLoadingSolutions]="(solutionsAdmin$ | async)?.isLoadingSolutions"></app-solutions-list>

<app-create-solution-modal *ngIf="(solutionsAdmin$ | async)?.showCreateModal"
                           [isCreatingSolution]="(solutionsAdmin$ | async)?.isCreatingSolution"
                           [isUploading]="(solutionsAdmin$ | async)?.isUploading"
                           [tags]="(solutionsAdmin$ | async)?.tags"
                           [authorizations]="(solutionsAdmin$ | async)?.authorizations"
                           [uploadedScreenshots]="(solutionsAdmin$ | async)?.uploadedScreenshots"
                           [uploadedFiles]="(solutionsAdmin$ | async)?.uploadedFiles"
                           [showAlert]="(solutionsAdmin$ | async)?.modalAlert"
                           [solutions]="(solutionsAdmin$ | async)?.solutions">
</app-create-solution-modal>

<app-delete-solution-modal [show]="(solutionsAdmin$ | async)?.showDeleteModal"
                           [isDeletingSolution]="(solutionsAdmin$ | async)?.isDeletingSolution"
                           [solutionToBeDeleted]="(solutionsAdmin$ | async)?.solutionToBeDeleted">
</app-delete-solution-modal>

<app-edit-solution-modal *ngIf="(solutionsAdmin$ | async)?.showUpdateModal"
                         [isUpdatingSolution]="(solutionsAdmin$ | async)?.isUpdatingSolution"
                         [isUploading]="(solutionsAdmin$ | async)?.isUploading"
                         [uploadedScreenshots]="(solutionsAdmin$ | async)?.uploadedScreenshots"
                         [uploadedFiles]="(solutionsAdmin$ | async)?.uploadedFiles"
                         [tags]="(solutionsAdmin$ | async)?.tags"
                         [authorizations]="(solutionsAdmin$ | async)?.authorizations"
                         [solutions]="(solutionsAdmin$ | async)?.solutions"
                         [showAlert]="(solutionsAdmin$ | async)?.modalAlert"
                         [solutionToBeUpdated]="(solutionsAdmin$ | async)?.solutionToBeUpdated">
</app-edit-solution-modal>`

steps outlined in attached gif.

## Expected behavior

The user should not be capable of interacting with the datagrid while it is loading.
## Versions

**App**

* Angular: ^7.0.5
* Node: 8.0.47
* Clarity: 1.0.4

**Device:**

* Type: dell xps
* OS: linux
* Browser chrome
* Version 22

## Additional notes

_Add any other notes about the problem here._
![editwhileloading](https://user-images.githubusercontent.com/13860204/51316770-910f1700-1a4d-11e9-91f5-061912b35717.gif)

**Comment by mathisscott** [comment]
No stackblitz. We can't say whether this is a Clarity or product issue.
