### ISSUE TITLE
Datagrid vertical height issues in non-Chrome browsers

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3055]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

**Issue:**
1. Datagrid with 100% vertical height won't fit perfectly in non-Chrome browsers.

A `datagrid` component and another element are wrapped in a `div` container with `flex` layout and the `direction` set to `column`. The design is kind of a grid that stretches vertically but with a toolbar on top of it. The problem is that it works perfectly fine in Chrome but not in other browsers. The height of the datagrid extends off-screen and toggles the scrollbars of the parent element.

**Chrome browser**
![image](https://user-images.githubusercontent.com/1977391/51426914-fb7dae00-1c2b-11e9-8992-27cc924676ef.png)

**Edge, Mozilla and other non-Chrome browsers**
![image](https://user-images.githubusercontent.com/1977391/51426923-1819e600-1c2c-11e9-95b4-10abaf2463d6.png)

## How to reproduce
Check this stackblitz: https://stackblitz.com/edit/clarity-light-theme-v013-s4spkv

html:
```html
<div class="container">
   <div class="toolbar"></button>
    <clr-datagrid></clr-datagrid>   
</div>
```
```css
.container {
   display: flex;
   flex-direction: column;
   height: 100%;
}
clr-datagrid {
   height: 100%;
}
```
## Expected behavior

_A clear and concise description of what you expected to happen._

Datagrid should fit 100% vertically in non-Chrome browsers.

## Versions

**App**

* Angular: [e.g. 6] 7.*
* Node: [e.g. 8.10.0] 11.6.*
* Clarity: [e.g. 0.12.5] 1.0.4

**Device:**

* Type: [e.g. MacBook] Dell XPS 13
* OS: [e.g. iOS] Windows 10 Enterprise
* Browser [e.g. chrome, safari] Latest browsers (Edge, Mozilla, Chrome, IE, Opera)
* Version [e.g. 22] Latest

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
This is not a Clarity datagrid issue, but a common (though unpleasant) difference between the implementations of flexbox specs in Chrome and Firefox. 
Please, see this for more details:
https://moduscreate.com/blog/how-to-fix-overflow-issues-in-css-flex-layouts/
Here is your example with the suggested change applied:
https://stackblitz.com/edit/clarity-ff-flex-issue?file=src/app/home/home.component.css
It's been applied on 2 levels - on the datagrid itself and in the host, both of which are using vertical flexbox layout.
