### ISSUE TITLE
Button group is missing margin top and bottom

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#3057]
## Describe the bug

A button that is not in a button group has `.25rem` margin top and bottom. Buttons in a button group do not have any margin top or bottom. This leads to misaligned  buttons if you combine single buttons and button groups.

![screen shot 2019-01-20 at 16 40 21](https://user-images.githubusercontent.com/3655915/51441456-1f93ca80-1cd2-11e9-937f-984379ec1fef.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-nhura1

## Expected behavior

Buttons are vertically aligned no matter if they are in a button group or not.

## Versions

**App**

* Angular: 7.2.1
* Node: 10.1.0
* Clarity: 1.0.4

**Device:**

* Browser: Chrome
* Version: 71.0.3578.98

**Comment by coryrylan** [comment]
Related suggestion to remove margins (breaking change) from buttons to allow easier default inline use. https://github.com/vmware/clarity/issues/181 Looking at other UI libs this seems to be pretty common pattern.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. As we build Clarity Core implementations, we won't be adding margins by default so this will be easy to address. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
