### ISSUE TITLE
DataGrid not computing proper widths for clr-dg-cell when width is applied through css in percentage

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#3058]
DataGrid not computing proper widths for clr-dg-cell when width is applied through css.

## How to reproduce

https://stackblitz.com/edit/column-width-issues-1-0

1.  Go to shared stackblitz
2.  Click on Add action button.
3.  New record is added.
4.  Observe the width of the cells for the new row.
5. Width applied is very less and content is shrinked.
Width of header items is computed properly

## Expected behavior

Width of row cells should be computed applied based on user provided values.

## Versions

**App**

* Angular: 7.2
* Clarity: 1.0.4

**Device:**

* Type: MacBook
* Browser chrome
* Version Latest

## Additional notes

Header-renderer.ts : detectStrictWidth results in the width for cells which is not accurate when userwidth is in percentage.

This works with 0.13.x :
https://stackblitz.com/edit/clarity-light-theme-v013-column-widths

**Comment by mathisscott** [comment]
@tarangkhandelwal 
What use case does setting percentage width address over Clarity's built-in dynamic width sizing or the recommended use of defined widths?

**Comment by tarangkhandelwal** [comment]
@mathisscott : 
One of the use cases is that when it is required to have some columns fill percentage of the viewport. 
This column can have long text and gets wrapped in multiple line.  

Rest columns can be of dynamic width or a fixed width in pixels.
https://stackblitz.com/edit/clarity-light-theme-v013-column-widths-percentages

**Comment by gnomeontherun** [comment]
I see your demo but it also does not fully work once you start to resize columns. The Name column is broken in this regard, which is why we don't explicitly support % widths.

**Comment by mathisscott** [comment]
The recommended workaround is to use `flex-grow` settings on your columns.
