### ISSUE TITLE
Datagrid height calculated incorrectly when used in ClrTabContent

### ISSUE THREAD

**Issue by zhanivanov** [vmware/clarity#3059]
## Describe the bug

I'm using a datagrid which gets its data async. It is placed in a ClrTab and the tabs are not lazy loaded. When the datagrid is in a not active tab it gets it height set to 0 when the data comes from the backend. The issue is only reproducible when using *clrDgItems smart iterator and datagrid pagination. If I am on the datagrid's tab on the time of loading the data its height is calculated correctly.

## How to reproduce

Stackblitz: https://stackblitz.com/edit/angular-ktx32f

1.  Wait for the timeout
2.  Go to the second tab
3.  See the datagrid has height 0

## Expected behavior

I expect to have the datagrid calculated correctly when i go to the second tab.

## Versions

**App**

* Angular: [6]
* Clarity: [0.13.4]

**Comment by youdz** [comment]
Datagrid in tabs that are not using `*clrIfActive` is a use case we do not want to support. The performance cost of creating/destroying the datagrid is less than the performance cost of having the datagrid loaded and running in memory as a detached node. And as you point out in your issue, using `*clrIfActive` solves the problem. 

I'm closing this issue, but if you have a use case for **not** using `*clrIfActive` that we haven't heard of, feel free to comment on this closed issue and I will reopen it if the use case is one we want to support.
