### ISSUE TITLE
Dropdown in Datagrid cell is not displaying properly

### ISSUE THREAD

**Issue by markedwardsims** [vmware/clarity#3069]
## Describe the bug

This defect is when using a Dropdown component inside a Datagrid cell. After opening the Dropdown, rather than the Dropdown being on top of the grid, it creates space inside the `.datagrid` element as well as a scroll. 

## How to reproduce

I have created this Stackblitz reproduction:

https://stackblitz.com/edit/clarity-custom-theme-v1-0-hmlpoe

1.  Click the vertical dot icon in the row that has the name `Bash`
2.  Observe that the dropdown is hidden inside the datagrid rather than on top

## Expected behavior

The expected behavior is that the Dropdown will flow outside the datagrid

## Versions

**App**

* Angular: 7.0.4
* Clarity: 1.0.4

**Device:**

* Type: MacBookPro
* OS: iOS 10.14
* Browser: Chrome
* Version: Latest (71.0.3578.98)

## Additional notes

This was working properly in my project with version 0.13 of Clarity. It became an issue after upgrading to v1.0.

**Comment by hippee-lee** [comment]
There are several issues that relate to this one: #1262 & #2683. Please subscribe to #2923 to monitor the  (in progress) development of our SmartPopover that will solve issues like this in the library.
