### ISSUE TITLE
[Website] App-Level Alert docu 

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#3074]
## Describe the bug
Small fix on App-Level Alert docu: 
Text mentions "There are **three** different sub-types of app-level alerts info, warning, and error."
In the example above **four** types are shown.

## How to reproduce
1.  Go to https://clarity.design/documentation/alerts

## Expected behavior
Either correct text or example to have a matching documentation

## Additional notes
I would suggest to drop support for app-level alert 'success'.
The 'success' type is better designed with notifications #365 that automatically hide.

## Versions
**App**
Clarity Docs: V1.0

**Comment by Niladri24dutta** [comment]
@mathisscott I can work on this. Should I update the description to exclude the 'success' type or we need to update the code to remove the example for 'success' ?
