### ISSUE TITLE
Pivot Grid

### ISSUE THREAD

**Issue by markofranjic** [vmware/clarity#3075]
## Summary

Pivot grid which will show data in grid by specific key

## Use case

I have relations  one to many on my database. Department has many work positions.
I want avoid table like this
Department  WorkPositionName       Position Salary
IT                   System Enginner           1000
IT                   System Administrator    500
IT                   System Arhitect             2500

I want avoid duplicate Department in this case IT.

https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/SimpleArray/Angular/Light/

**Comment by gnomeontherun** [comment]
I can't get that demo to load, it times out, can you expand your use case and summary further with additional examples and more about why you need this?

**Comment by sdurnov** [comment]
@markofranjic you can achieve 1st column behavior with [expandable rows](https://clarity.design/documentation/datagrid/expandable-rows). Sadly, no stacked columns yet, but as far as I understand, you need this just for rows, right?

**Comment by mathisscott** [comment]
We recommend against this pattern due to the lack of control over the whitespace and how it affects cell traversal, screen readers, and the usability of the pane as rows/columns are expanded and nested.
