### ISSUE TITLE
any plans to support typeahead feature?

### ISSUE THREAD

**Issue by omurbekjk** [vmware/clarity#3078]
## Summary
ng-bootstrap has typeahead feature, it will be nice to have it too in clarity

## Use case

It is used to autocomplete search, autosuggest values and more...
## Examples

https://ng-bootstrap.github.io/#/components/typeahead/examples

**Comment by youdz** [comment]
Our combobox/select component is the one we plan to recommend for typeahead use cases.
Please note that the API would be extremely different from the ng-bootstrap one, but we'll write examples of how you would use it both with local or remote item lists.
