### ISSUE TITLE
[Website] [Documentation] "Learn more" link is broken for "Radio Buttons" section

### ISSUE THREAD

**Issue by Gesh4o** [vmware/clarity#3079]
## Describe the bug

"**Learn more**" link is broken (https://vmware.github.io/clarity/documentation/v0.13/radio/forms):

<img width="910" alt="screen shot 2019-01-28 at 9 48 57 am" src="https://user-images.githubusercontent.com/13942085/51821580-570e0280-22e2-11e9-98b6-a0925161d342.png">

## How to reproduce

1.  Go to 'https://vmware.github.io/clarity/documentation/v0.13/radio'
2. Navigate to 'Angular Radio Component'
3.  Click on 'Learn more'

## Expected behavior

To show information about ClrFormsNextModule.

## Versions

**App**
v13 of the docs

**Device:**
Any

**Comment by gnomeontherun** [comment]
This has been pushed and resolved for 0.13.
