### ISSUE TITLE
Password validates immediately instead of on delay

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3081]
## Describe the bug

The password should not immediately start to alert about errors until focus is lost

## How to reproduce

https://clarity.design/documentation/password

1.  Go to demo with validation
2.  Start typing
3.  See error immediately

## Expected behavior

The error state should not be activated until focus is lost.

## Versions

**App**

* Angular: 7
* Node: 8.10.3
* Clarity: 1.0.4

**Comment by kelvix** [comment]
Not an issue but I also can't seem to refresh the page without being presented a "Page Not Found" modal being presented to me. Clicking on the "How to reproduce" lands me on the same "Page Not Found". All other components respond with a HTTP 301 leading me to the right place.

**Comment by Jinnie** [comment]
@kelvix This is a problem on the website. This issue is for something else.
You can follow this PR to track the 404 problem: #3107

**Comment by gnomeontherun** [comment]
This is actually happening on inputs as well if you add a different validator like minlength and required.
