### ISSUE TITLE
Password validation icon is misaligned

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#3083]
## Describe the bug

The `.clr-validate-icon` on password containers is aligned differently in contrast to the icon on input containers because of `clr-input-group`s margin right.

![screen shot 2019-01-29 at 08 49 02](https://user-images.githubusercontent.com/3655915/51892691-fdb9d800-23a2-11e9-8fec-8b293030f6fd.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-rlejzm

## Expected behavior

`.clr-validate-icon`s are aligned the same way on all kinds of inputs.
## Versions

**App**

* Angular: 7
* Node: 10.1.0
* Clarity: 1.0.4

**Device:**

* Browser Chrome

**Comment by coryrylan** [comment]
related issue https://github.com/vmware/clarity/issues/3084
