### ISSUE TITLE
[clrDgField] string filter not filtering table rows.

### ISSUE THREAD

**Issue by ryan-jan** [vmware/clarity#3085]
## Describe the bug

When using `<clr-dg-column [clrDgField]="'Name'">Name</clr-dg-column>` in a datagrid column my table displays the filter option in the column header, however, when you type a search string in the filter box the matched value is found and sent to the bottom of the table. All other values in the table are still visible but the matched value has been put at the bottom of the table. When I then clear the filter the table seems to duplicate all rows.

## How to reproduce

Set `<clr-dg-column [clrDgField]="'Name'">Name</clr-dg-column>` as a column header.

StackBlitz App - [https://angular-schapa.stackblitz.io](https://angular-schapa.stackblitz.io)
StackBlitz Editor/Code - [https://stackblitz.com/edit/angular-schapa](https://stackblitz.com/edit/angular-schapa)

## Expected behavior

I would expect that any values in the Name column which match the search term are shown and values that do not match the search term are hidden from the table.

## Versions

**App**

* Angular: 7.1.0
* Node: v10.14.0
* Clarity: 1.0.4

**Device:**

* OS: Windows
* Browser: Chrome
* Version: 71.0.3578.98

**Comment by gnomeontherun** [comment]
Please provide a working demonstration in a StackBlitz for us to review, thanks!

https://stackblitz.com/@clr-team

**Comment by ryan-jan** [comment]
I have now updated the original post with links to a StackBlitz which is demonstrating the issues I am facing. Thanks.

**Comment by Jinnie** [comment]
Hi @ryan-jan 
No idea how you created your stackblitz, but I ported your code 1:1 to the latest 1.0 stackblitz, made sure to update it to 1.0.5, and it seems to be working.
https://stackblitz.com/edit/clarity-filter-issue-ryan-jan?file=src%2Fapp%2Fapp.component.ts
There was no good reason for your code not to work, so I had to do it to see if it's in the code, or in the infrastructure.
Are you getting this issue in your built from source project too, or only on Stackblitz?

**Comment by ryan-jan** [comment]
I just realized that I hadn't imported the import `BrowserAnimationsModule` rookie mistake! Sure enough with that imported the filtering is behaving as expected. Thanks for your help and apologies for not spotting this in the first place.
