### ISSUE TITLE
GitHub releases are outdated (v1.0.2)

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#3091]
## Describe the bug

The latest release listed in GitHub is v1.0.2. 

## How to reproduce

Check this link: https://github.com/vmware/clarity/releases

## Expected behavior

The latest release should be 1.0.5.

## Additional notes

I'm using GitHubs "Watch releases" feature and I was wondering why I didn't get notified about the 1.0.5 release.

**Comment by hippee-lee** [comment]
Thanks for bringing this into attention. 
I published the missing releases.
