### ISSUE TITLE
Request for resizable layout (side nav, main container, etc..) based on angular-split

### ISSUE THREAD

**Issue by vashh08** [vmware/clarity#3093]
The new feature should be able to resize the Sidenav and Content Area (being responsive), with a drag functionality. Can also add feature to hide Sidenav. It won't impact existing features.

In my case I am building a mailing/messaging app where the interface is splitted into 3 columns.
Sidenav, Content Area to display list of messages and Content Area to preview messages. These are align horizontally, and user must be able to drag and resize any of the 3 columns.

There is an example on https://bertrandg.github.io/angular-split/#/examples/simple-split which I am trying to integrate without success. 

Thanks.

**Comment by mathisscott** [comment]
This is not a pattern that Clarity is supporting. We did a good deal of research on it and found that the pattern had accessibility, usability, and performance issues overall. It's not something we are going to do.

If you want it for your application despite all that, then integrating with something like angular-split is work on the product side.
