### ISSUE TITLE
Implement a responsive footer for Datagrid - specs included

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#3097]
## Make the datagrid footer responsive for smaller screens

The content currently breaks when the screen size is reduced.
* Make the content wrap
This ticket addresses issue #2833

![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/5d191cde-84b7-4252-93f7-544a144c8c07)

The footer should wrap when the screen size is smaller, like this:
![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/bdca7b93-4636-4158-a246-8ed3dcf876e9)

* Alignment
Maintain left alignment for show/hide and selected row icons. Maintain right alignment for pagination items

* Changes:

1) Remove vertical dividers - they look awkward when wrapped

2) Change right side padding to equal left side
![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/8fd1137b-0496-4336-9f9a-df2c0f7824d0)
* Spec:
![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/14183867-b10d-4079-aa9a-1cc2581493a1)

**Comment by Jinnie** [comment]
Hi, Lilia, all,

Although it's not listed on the website, there is a div.datagrid-footer-description between show/hide and the pagination section.
<img width="710" alt="screen shot 2019-02-13 at 5 11 58 pm" src="https://user-images.githubusercontent.com/1798828/52721681-da9e4380-2fb2-11e9-96e7-f49c8f21d85f.png">
It actually looks a bit broken now, as it's not aligned to the "Users per page" text. But the component accepts and projects anything not recognized that it finds between `<clr-dg-footer>...</clr-dg-footer>`, so I think, we should either add this to the design, or drop the description from future versions of the footer.

**Comment by lil-kim** [comment]
Hi @Jinnie , Thanks for catching that. I would like to remove that from future versions, but want to make sure that there isn't some reason for it that I'm not aware of.

**Comment by amellnik** [comment]
If possible, it would be nice to allow users to easily add their own action icons on the left side of the footer along with the rows and column icons.  For example, I often want to add a download icon button to the datagrid itself.

**Comment by Jinnie** [comment]
@lil-kim I got why is it there - the footer description is important when we want to show data in the footer when we don't have pagination. Like this:


<img width="309" alt="screen shot 2019-02-15 at 1 40 47 pm" src="https://user-images.githubusercontent.com/1798828/52854533-57522e80-3127-11e9-8797-835e5fa123e3.png">

We should not remove it.

**Comment by Jinnie** [comment]
@lil-kim And another question on the spec. .pagination-list used to have 1.5rem - 2px height.
Not sure why it was like this, but unless we remove it the heights change to:
large - 36px
middle - 70px
small - 106px
<img width="286" alt="screen shot 2019-02-15 at 3 00 33 pm" src="https://user-images.githubusercontent.com/1798828/52858396-a782be00-3132-11e9-9dae-7e2b0ac5a147.png">

**Comment by lil-kim** [comment]
Hi @Jinnie 
Each row of the datagrid should be 36 px ht, but it looks like the grid rows are 37 and the header and footer are different too - maybe complicated by the 2 px line, which is there by design. But it could be changed to a 1px line, if that makes it easier to fix. The goal is for the whole datagrid height to be a multiple of 6px, so that it aligns with our vertical rhythm. So the footer should be 36, 72, 108
![image](https://user-images.githubusercontent.com/23196444/52879992-9a0b0b00-3115-11e9-985c-cb6e0c99f2cc.png)

**Comment by Jinnie** [comment]
As we don't have specs for the compact version, I'm posting the result from applying the styles "as is"
Please, confirm or request changes.

<img width="726" alt="screen shot 2019-02-25 at 1 01 08 pm" src="https://user-images.githubusercontent.com/1798828/53333162-c71da180-38fd-11e9-9f51-624abb8044d8.png">

I'm a bit worried about the overlapping on the 2nd screenshot. It's not a showstopper, I think, but it seems we have a minor visible issue there.

**Comment by lil-kim** [comment]
For compact view, It would be best if we could make an exception for the footer and keep its rows at the standard 36px. Would that be possible?

**Comment by Jinnie** [comment]
Possible, yes, but looks a bit imbalanced with a compact header, IMO:

<img width="720" alt="screen shot 2019-02-25 at 8 20 19 pm" src="https://user-images.githubusercontent.com/1798828/53359172-d838d380-393a-11e9-8b63-016074f6b757.png">

**Comment by hippee-lee** [comment]
@Jinnie - the `.compact-datagrid` has some overrides for icons and other elements that didn't play nice with the default styles. The button could be targeted there and positioned properly with an override.

**Comment by lil-kim** [comment]
@Jinnie How about a compromise...30 px on the height? Also, it would be good to see a few more rows in the datagrid example to see a more typical view.

**Comment by Jinnie** [comment]
@lil-kim , here are some samples.
1.5rem, more rows:
<img width="719" alt="screen shot 2019-02-26 at 7 58 48 am" src="https://user-images.githubusercontent.com/1798828/53391458-17990b80-399f-11e9-979f-0176159b289f.png">

1.1rem - lowest non-overlapping setting:
<img width="718" alt="screen shot 2019-02-26 at 8 08 28 am" src="https://user-images.githubusercontent.com/1798828/53391436-07812c00-399f-11e9-9b55-07e77a68676a.png">

1.25rem (30px)
<img width="718" alt="screen shot 2019-02-26 at 8 12 41 am" src="https://user-images.githubusercontent.com/1798828/53391406-f0dad500-399e-11e9-97b2-6bec5c700c7d.png">

@hippee-lee Just ignore the misplaced buttons for the screenshots, please. I'll adjust them after we have a decision on the height.

**Comment by gnomeontherun** [comment]
We are deprecating the compact layout, so we shouldn't be doing special designs for it.

**Comment by Jinnie** [comment]
OK, so I'm doing a PR with the initial version, which is cheap to produce and "good-enough".

**Comment by gnomeontherun** [comment]
This was completed, and in v2+
