### ISSUE TITLE
Offer responsive utilities for datagrid

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#3098]
## Summary

Currently you can either show or hide a column via the column toggle feature. A more responsive way would be to set a grid breakpoint at which the column changes it's state between visible and hidden, e.g. like this:

```html
<clr-dg-column>
    <ng-container *clrDgHideableColumn="{breakpoint: 'md'}">
        User ID
    </ng-container>
</clr-dg-column>
```

This would hide the column on screens smaller then 768px. It also should dynamically toggle the hidden state when the screen size changes. 

## Use case

Generally you may want to avoid horizontal scroll bars in datagrids so you may want to use the column toggle feature to show and hide columns. With a responsive version as proposed here, it would be possible to always show as much information as fits on the screen while dropping the least important columns first when the screen size gets smaller.

## Workarounds

You can bind some variable or function to `clrDgHideableColumn` and compute the hidden state yourself.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
