### ISSUE TITLE
Reactive form Date Picker. "Disabled" status does not apply to the pick button

### ISSUE THREAD

**Issue by gonzobard777** [vmware/clarity#3101]
## Describe the bug

The pick button is _active_ if the control is in the **disabled** state. Date can be changed.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-wd6hos?file=src%2Fapp%2Fapp.component.html

1.  Change the "disabled" state of the date field by clicking on the button 'Is date disabled?'
2.  Set the date field to **disabled** state
3.  Push the pick button
4.  Change the date

## Expected behavior

The pick button is inactive if the control is in the "disabled" state. Date cannot be changed.

## Versions

**App**

* Angular: 7.2
* Clarity: 1.0.4

**Device:**

* Type: All
* OS: All
* Browser All

**Comment by gnomeontherun** [comment]
This is resolved with using the new form layouts, which you want to consume in the following way.

```html
<form [formGroup]="formGroup" clrForm>
  <clr-date-container>
    <input
      placeholder="decision date"
      [formControlName]="'decision_date'"
      clrDate
    />
  </clr-date-container>
</form>```

We have a ticket to update our docs with a bit more about the date container for scenarios like this, but it is required if you plan to disable the input.

The old form layouts, which are deprecated, are not receiving attention at this stage so I'm going to mark this as fixed when using the correct form containers.
