### ISSUE TITLE
Datagrid width not accounting for Action or Detail columns.

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#3108]
## Describe the bug

Datagrid dynamic width calculation results in width larger than 100% of parent and creates a scroll bar when Details or Action(Menu) columns are displayed and there is a cell who's content is long enough to push cell width and wrap to new line.

It seems like the dynamic width calculation is not accounting for the width of the Detail or Action columns because final width seems to be 100% + the width of those columns.

I'd imagine this is also impacted by the Selection Column, but have not tested for that case.

## How to reproduce

https://stackblitz.com/edit/clarity-issue-3108

You can see width behavior by looking at the grid in the provided stackblitz.

Toggle Menu(Action) and Detail columns using the buttons to see how width of grid is impacted by whether or not they're displayed.

## Expected behavior

Datagrid width calculation should account for action columns and there shouldn't be a scroll bar when those columns are displayed.

## Versions

**App**

* Angular: 7
* Clarity: 1.0.5

**Comment by gnomeontherun** [comment]
This is related to having a column with a long string, which if you reduce to just one word lays out properly. Will need further investigation.

**Comment by jacobbutton** [comment]
Yes. This only happens if there is a column with a long enough string.

I should also add, that even with the Action and Detail columns hidden, there is sometimes still a scroll bar but that scroll bar only scrolls a pixel or two.

**Comment by hippee-lee** [comment]
This issue is related to the routine that autosizes the datagrid content  inside column headers and column cells. The content is used to autosize with browser calculations for the table but the cells with row actions (and select inputs and expandable rows) are not.

Its not just a simple css fix and will need a bit more time to fix properly.

**Comment by wokis** [comment]
Any news on this? The issue is still present in v4.0.1.

**Comment by mathisscott** [comment]
@wokis 
We've moved this issue into our backlog. It's not an easy fix so we will have to schedule the work in with our other priorities.

**Comment by rogerfar** [comment]
Just wanted to give this a subtle kick, as it's been over a year, any update on this?
