### ISSUE TITLE
Cleanup datagrid selection preservation is buggy 

### ISSUE THREAD

**Issue by usmanajmal** [vmware/clarity#3109]
Clarity version:   "@clr/angular": "0.11.34"

**Problem:** 
Clarity remembers a previous selection after a new selection and jumps back to the previous selection eventually. 

**Explanation:**
I have a datagrid which has a button in first cell of each row. Clicking on the button calls my selectItem function which looks like following:

  ```
selectItem(entity: EntityType, event?) {
    if (event) {
      event.preventDefault();
    }

    if (entity) {
      this.selectedItems = [entity];
      .
      .
    }
  }
```

That selectedItems is used by clr-datagrid as:
```
<clr-datagrid [clrDgLoading]="loading"
                [(clrDgSelected)]="selectedItems"
                (clrDgRefresh)="refresh($event)">
.
.
.</clr-datagrid>
```

If I have following items in my data grid and first one is the first ever selection, selecting button of any other item from the table cell will select it for a second but then the selection will automagically jump to the first selected item again. 

![clr-datagrid-selection-issue](https://user-images.githubusercontent.com/1510307/52757984-73d15800-2fbb-11e9-84ac-f7b387d2eb6e.gif)

I tracked this back to Clarity code in https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/providers/selection.ts where for some reason initial selection is preserved i.e. `leftOver` variable contains the initial first ever selection and its used as following:

(Btw, following TODO comments is a bit concerning and this may be the core issue)

```
// TODO: Discussed this with Eudes and this is fine for now.
 // But we need to figure out a different pattern for the
 // child triggering the parent change detection problem.
 // Using setTimeout for now to fix this.
 setTimeout(() => {
   if (selectionUpdated) {
      this.current = leftOver;
   }
 }, 0);
```

After this.current is update with the suspected wrong item in leftOver, this.selection.change's subscriber (given below) gets triggered which has the wrong item emitted on line `_this.selectedChanged.emit(s)` where s has the wrong value. This makes the UI jump back to the first ever selection as shown in GIF. 

```
ClrDatagrid.prototype.ngAfterViewInit = function () {
        var _this = this;
        this.refresh.emit(this.stateProvider.state);
        this._subscriptions.push(this.stateProvider.change.subscribe(function (state$$1) { return _this.refresh.emit(state$$1); }));
        this._subscriptions.push(this.selection.change.subscribe(function (s) {
            if (_this.selection.selectionType === SelectionType.Single) {
                _this.singleSelectedChanged.emit(s);
            }
            else if (_this.selection.selectionType === SelectionType.Multi) {
                _this.selectedChanged.emit(s);
            }
        }));
    };
```

Change-set where this change is made has heading: "[ng] Datagrid bug fix for when selection is cleared by applying filter". Seems like this code is supposed to be run only for filtering business but its getting executed even for the case I mentioned where no filtering is performed. 

Filing this bug in order to raise this issue as I couldn't understand why older selection is preserved. 

Cc: @jeeyun @youdz Saw your comments / names in code related to this area so Ccing you here. :)

**Comment by youdz** [comment]
I'm sorry but we cannot investigate a bug based on a GIF and incomplete pieces of code. Could you please post a clean reproduction using one of our [StackBlitz templates](https://stackblitz.com/edit/clarity-light-theme-v1-0)?

Because right now looking at the GIF, there is no way such a large delay is due to a `setTimeout()` with no time offset. `setTimeout(..., 0)` doesn't even let the browser render before completing most of the time.

**Comment by usmanajmal** [comment]
Please don't get distracted by 'the long delay in GIF'. The jump back happens instantaneously in UI. Its just that the GIF-maker I used, has slowed down the video/animation. 

What I like to know is following:

- Why is this piece of code preserving last selected value and eventually emit a selected-change event?
- Why does this piece of code even executed as my datagrid is not using any filtering? As mentioned, the change-set which introduced this change was for clearing selection when filter is applied. 

I will appreciate if I can get some insight about that and I will try to provide a stackblitz.

**Comment by youdz** [comment]
I insist, please give us a reproduction on StackBlitz if you want us to investigate. We cannot allocate time to write reproductions ourselves, so if you are not willing to do it this issue will just sit there until we have a lot of free time, if ever.

We also cannot spend time explaining on here the entire architecture of the datagrid, which is where some of your questions are leading.

**Comment by usmanajmal** [comment]
I will try to reproduce using StackBlitz.

Entire architecture of datagrid was never asked. Only questioned the change-set _"[ng] Datagrid bug fix for when selection is cleared by applying filter"_. Commit ID: 83159285a9246096bc34b7c33f96747eaae3c3cb. 

Anyway thanks for the help.

**Comment by mathisscott** [comment]
@usmanajmal 
It appears you are trying to force checkboxes to behave like radio buttons?

Why not use [the datagrid's single selection feature](https://clarity.design/documentation/datagrid/selection-single)?

**Comment by usmanajmal** [comment]
@mathisscott that a very good point you mentioned and it may be the source of this issue. 

I cannot use single selection feature of datagrid because I want users to be able to multi-select e.g. consider the case where they like to delete multiple items in one go. They will multi-select more than one item using checkboxes and then hit delete button, only once. 

Having said that, I also have to have a feature where on clicking name of the item (which in my case is a button in datagrid cell), I have to show some details of that item on right hand side of the datagrid in a different component. And when someone clicks on name of the item, I have to remove all other row selections of the table and mark only selected item's row as selected. If, however, user wants to use multi-select, they can still do so via the checkboxes of each row. 

onclick of that button looks something like following i.e. this.selectedItems is set to an array which has only one value: `entity`. That's the item user clicked on.

```
selectItem(entity: EntityType, event?) {
  if (event) {
    event.preventDefault();
  }

  if (entity) {
    this.selectedItems = [entity];
    .
    .
  }
}
```
Seems like doing so kind of make the datagrid component tell that i am using multi-select due to which the suspected selection from past is preserved and eventually jump back to it happens as mentioned in this bug's description.

**Comment by gnomeontherun** [comment]
Without a demo it's not possible for us to triage exactly what is happening. The UX of what you are proposing is not very clear to me how a user would know the difference nor is it clear why this is a use case. Mixing single/multi select would be an antipattern because the user cannot be certain about the outcome of a given action.

Either way, we are working on a Detail Pane feature (#2005) that would solve showing the details of the item.

**Comment by usmanajmal** [comment]
UX is same as what is mentioned in #2005 under "Multi-select" detail view. Only difference is that your feature shows details on clicking a 'details icon'. Ours work on clicking name of the item. UX/UI of name in our case is made evident in a way that it looks clickable, so its not an anti pattern for us. 

I will try to create a demo.

**Comment by gnomeontherun** [comment]
I understand the name looks clickable due to being a link, but it does not imply that it triggers a selection change like a checkbox or radio. This is the UX problem.

Are you trying to change selection so that you can use the data from the selected array to show a detail pane? If so, why do you need to change the selection?

**Comment by usmanajmal** [comment]
Yeah makes sense. I may let our UX team know that the clickable-name doesn't tell user that some details will appear on clicking it. Details icon in your mockups is a better option. 

As for your selection question, I see what you mean. Our UX team have been following a pattern where clicking a name mean two things:
a. User is selecting this row and
b. Show details related to this row
