### ISSUE TITLE
Use Paging Test Case Errors

### ISSUE THREAD

**Issue by jwangyangls** [vmware/clarity#3110]
## Describe the bug
Only in the case of unit testing,not in practice.When I use unit tests, test DataGrid pages. Each page displays up to 15 data. I have 18 data, 15 of which should be displayed on the first page and 3 on the second page. But the actual situation is that when I click on the next page button, the second page shows 18 data, and scroll bars appear. There are no three data I expected. When UL and Li are used to simulate data display outside components, the results are correct.

## How to reproduce
![image](https://user-images.githubusercontent.com/29826789/52767417-6670a800-3065-11e9-821c-b3aa6c6100de.png)
![image](https://user-images.githubusercontent.com/29826789/52767427-6c668900-3065-11e9-9ab6-ff8723051b62.png)

## Expected behavior
I have 18 data, 15 of which should be displayed on the first page and 3 on the second page.
## Versions

**App**

* Angular: [e.g. 7]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 1.0.0]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by jwangyangls** [comment]
I suspect that there are bugs in the component's test code

**Comment by jwangyangls** [comment]
ClrDgRefresh This method can no longer be called in the test.

**Comment by youdz** [comment]
This is Angular's animation module making DOM element removal asynchronous. Since it's in Angular itself we can't fix it, but you can just use `fakeAsync()` and `tick()` to force removal in your unit test.
