### ISSUE TITLE
button  overlap problem of Pagination

### ISSUE THREAD

**Issue by liyang010813** [vmware/clarity#3114]
The page page tab button overlaps when it is first loaded
![image](https://user-images.githubusercontent.com/31497640/52838176-b4041800-312c-11e9-87bd-06e8d173792e.png)

**Comment by liyang010813** [comment]
Problems arising after deployment

**Comment by Jinnie** [comment]
@liyang010813 please provide a Stackblitz representation of this issue.
https://stackblitz.com/edit/clarity-light-theme-v1-0 <- last Clarity version
https://stackblitz.com/@clr-team <- all versions

**Comment by liyang010813** [comment]
Clarity version is 1.0.5 and arising is add --prod. deployment environment is win8 server.
There is no problem running locally. This problem occurs when you package and deploy to the server, and the When used with clr-col, the style will also fail on the first load. What else need to be described? This is the first time I have asked a question on github.It may not be very easy to describe the problem. If there is any other need, please specify. Thank you

**Comment by liyang010813** [comment]
Clarity version is 1.0.5 and arising is add --prod. deployment environment is win8 server.
There is no problem with the local operation. This problem will occur after the package is deployed to the server, and the use of clr-justy-content-between in Grid with clr-col will also cause the style to fail when it is first loaded. What else should be described? This is the first time I have asked a question on github.This may not be a very good way to describe the problem.

**Comment by liyang010813** [comment]
Clarity version is 1.0.5 and arising is add --prod. deployment environment is win8 server.
There is no problem with the local operation. This problem will occur after the package is deployed to the server, and the use of clr-justy-content-between in Grid with clr-col will also cause the style to fail when it is first loaded. What else should be described? This is the first time I have asked a question on github.This may not be a good way to describe the problem.

**Comment by hippee-lee** [comment]
@liyang010813 - is it possible for you to zip up the build artifact that is being deployed onto your server and attach or link to it here? Or, recreate the issue in a simple demo app that can be pushed up to github so we can see the issue?

It is very difficult to diagnose and investigate for you without a reliable way to reproduce the issue you are experiencing.

**Comment by liyang010813** [comment]
@hippee-lee Okay, I 'll reconstruct the application recurrence later.

**Comment by liyang010813** [comment]
Strangely, I have no problem deploying the project with Nginx. Is it the way it was deployed? The deployment method of the previous problem is: After the program is packaged, the program is configured to read index.html and then pack the gang. After the package, the packaged file and the packaged file are placed under a folder to directly start the pop program. Think you !

**Comment by liyang010813** [comment]
Strangely, I have no problem deploying the project with Nginx. Is it the way it was deployed? The deployment method of the previous problem is: After the program is packaged, golang is configured to read index.html and then bundle up with golang. After packaging, put the packaged file and golang packaged file under a folder and start the golang program directly. Please give me a hint.

**Comment by liyang010813** [comment]
Strangely, I have no problem deploying the project with Nginx. Is it the way it was deployed? The deployment method of the previous problem is: After the program is packaged, there is an index. HTML configured in the golang, and then after packing the golang, you can directly start the golang program by putting the packaged file and the glang packaged file under a folder.Think you!

**Comment by liyang010813** [comment]
Strangely, I have no problem deploying the project with Nginx. Is it the way it was deployed? The deployment method of the previous problem is: After the program is packaged, there is an index. HTML configured in the golang, and then after packing the golang, you can directly start the golang program by putting the packaged file and the glang packaged file under a folder.Think you! 
![image](https://user-images.githubusercontent.com/31497640/52924926-d040c880-3369-11e9-8724-bce3e97d2db9.png)

**Comment by liyang010813** [comment]
Problem solved.
