### ISSUE TITLE
Missing fillColor on empty datagrid placeholder

### ISSUE THREAD

**Issue by antomor** [vmware/clarity#3116]
## Summary

I would like to specify the `fillColor` property on the EmptyDatagridPlaceholder image since that the same property can be specifed on other images as well ( see [_icons.clarity.scss](https://github.com/vmware/clarity/blob/master/src/clr-angular/image/_icons.clarity.scss#L107) )

## Workarounds

It is possible to completely change the placeholder image with a custom one.

**Comment by gnomeontherun** [comment]
Can you please provide more detail about why this change is desired?

**Comment by antomor** [comment]
Sure, I am creating a custom theme.
While I can change the colour of all other datagrid icons, I can’t do it on the placeholder icon. Do you know some other way that doesn’t imply the replacement of the icon?

Thank you in advance,

--
Antonio

**Comment by hippee-lee** [comment]
In its original implementation the placeholder icon was not meant to be overridable / configurable by consumers. I do think its something that would be good to add but this isn't a priority for the team at this time. 

The placeholder image is a data uri with an svg image in it. You could override it with your own svg if you wanted to create a custom svg for your theme. 

Take a look here: https://stackblitz.com/edit/clarity-datagrid-basic-hvv46k?file=src/styles.css for an example.
