### ISSUE TITLE
Allow to change icon and placing for the expandable row detail 

### ISSUE THREAD

**Issue by ramsbaron** [vmware/clarity#3118]
## Summary
Currently the expandable row feature provides a right facing arrow and and a down arrow as icons for closed and expanded row. It would be great to allow developers to customize the icon and change its placing to far right.

* What is the change?
- [ ] allow customizing the icon image
- [ ] allow placement of the icon to the far right

* Why should it go in Clarity?
* Does this change impact existing behaviors? If so how?
No change to existing behavior is intended.
* If this change introduces a new behavior, is this behavior accessible?
No change to behavior is intended but the placement to the right may result in a change in order of the access to the operation.

## Use case
We are implementing both selection and expansion in the data display. Both of these are on the left side and may result in confusion and/or fat-fingering. Placing the expansion caret to the right of the data set would avoid this and foster a better ux.

## Examples
In many places the plus and minus signs are used for indicating that the data is expandable.
Further in data tables usually the actionable features (except) selection) are on the right side.

## Workarounds
One work around I can think of is to code the expansion of the row on a different button placed to the right of the data.

**Comment by colinreedmiller** [comment]
Clarity can't allow this:
1. (Positioning) Horizontal scrolling may hide the icon thus becoming a discoverability issue.
2. (Positioning) Hierarchy / page scanning - F pattern location is important. Placing the icon elsewhere renders it less apparent.
3. (Substitution) Consistency - the convention used elsewhere needs to be maintained. Allowing different icons that have the same indication is a UX issue in that it may confuse the user.
