### ISSUE TITLE
Update the documentation about Datagrid Custom Filtering

### ISSUE THREAD

**Issue by kaleksandrov** [vmware/clarity#3128]
## Describe the bug

Currently the documentation about Datagrid Custom Filtering is far away from enough. There are some code snippets and an interface declaration. However nowhere is explained what the interface methods serve for. The develop has no other option than looking into Clarity's codebase in order to understand those methods. The examples are also very thin. The Filter implementation given is not complete and the methods from the interface are not implemented.

## How to reproduce

Just vistit https://clarity.design/documentation/datagrid/custom-filtering and start reading

## Expected behavior

The documentation to be more explanatory so one can implement a custom filter without the need to browser clarity's codebase

## Versions

Clarity: 1.0

**Comment by Kangcor** [comment]
I also would be very happy to see some implementations of more custom filters

**Comment by alexkoretzki** [comment]
i would love that you will make a full example how to use it because  i am also try to use it and cant understand from the docs how it works
