### ISSUE TITLE
Hide window for clr-dg-column-toggle

### ISSUE THREAD

**Issue by askeet** [vmware/clarity#3129]
## Describe the bug

Toggle UI for columns doesn't work  

## How to reproduce

https://stackblitz.com/edit/clarity-datagrid-b293nu

1.  Go to datagrid with enabled filters and  toggle for columns  
2.  Click on any filter and open the window with selecting of data
3.  Scroll down to icon with opening hidable columns   
4.  Click the icon two times to open window with columns. 
5.  Try to close all windows with filters 

## Expected behavior

clr-dg-column-toggle has to be closed

**Comment by gnomeontherun** [comment]
This is a known bug #2550, closing in favor of the other bug. Thanks!
