### ISSUE TITLE
Textarea resize, show "cursor: nw-resize;" on hover

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#3130]
## Description
Improve Textarea resize, show "cursor: nw-resize;" on hover

## How to reproduce
1.  Go to https://clarity.design/documentation/textarea
2.  Hover over resize handle

Result: cursor remains default.

## Expected behavior
Show "cursor: nw-resize;" on hover 
![textarea](https://user-images.githubusercontent.com/311619/53188446-a6a3cd80-3605-11e9-920f-61fbf2779ec7.png)

When implementing super correct, show cursor according to textarea's "resize" attribute
resize: vertical / horiztonal / both
- vertial -> "cursor: ew-resize;"
- horiztonal -> "cursor: ns-resize;"
- both -> "cursor: nw-resize;"

## Versions
* Clarity: 1.0
* Device: Desktop, Notebook
* OS: Windows 10
* Browser: Chrome

**Comment by gnomeontherun** [comment]
This is browser behavior, not Clarity. We don't control this behavior and there is no way to adjust that in CSS without rebuilding the functionality.

**Comment by d-m-s** [comment]
alright, browser & effort beats ux in this case then ...  thx for the quick reply though

**Comment by hippee-lee** [comment]
@d-m-s - agreed that it would be a good UX for resizable text areas. The challenge here is that not all browsers even display the re-size corners so any cross browser solution would have to enable the resize behavior for browsers that don't support it in a consistent way with the browsers that already have it. 

When you say `browser & effort beats ux` it makes it seem like Clarity isn't concerned about UX. But we absolutely are. However we have to weight the effort to add this feature against the teams workload with already prioritized features and outstanding issues. 

Is this something you feel strong enough about to lead the contribution effort for it?

Here are roughly the things that would it would need.
1. researching the cross browser compatibility issues and how to disable existing behavior
2. accessibility
3. implementation - prolly an addition to `clrTextarea` and or additional directives to enable the behavior
4. testing (visual regression and unit tests)

If it is of interest to you please take a look at our [contribution](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md) and [coding](https://github.com/vmware/clarity/blob/master/CODING_GUIDELINES.md) guidelines and let me know if you would like my help moving forward.
