### ISSUE TITLE
Unable to add title attribute to clr-button.

### ISSUE THREAD

**Issue by collins1830207** [vmware/clarity#3132]
## Describe the bug

I need to add title attribute to clr-button, so I use ```<clr-button class="btn" title="title">Add</clr-button>```, it doesn't work.
And I tried to use custom attribute directive to complete it, but it still failed.

## How to reproduce
Reproduce this issue [here](https://stackblitz.com/edit/custom-title-directive?embed=1&file=src/app/app.component.html)

## Expected behavior
1. it would be nice if I could add title by using ```<clr-button class="btn" title="title">Add</clr-button>```.
2. custom directive works on ```<clr-button></clr-button>```

## Versions

**App**

* Angular: [6.0.0]
* Node: [8.12.0]
* Clarity: [0.12.0]

**Device:**

* Type: [MacBook]
* OS: [iOS]
* Browser [chrome]

**Comment by collins1830207** [comment]
I change ```this._renderer.setElementAttribute(this._elRef.nativeElement, 'title', this.content);``` to ```this._renderer.setElementAttribute(this._elRef.nativeElement.ownerDocument.activeElement, 
        'title', this.content);```, now I can add title for clr-button, but still think that user should be able to use title directly instead of adding a custom directive.

**Comment by collins1830207** [comment]
Another similar problem is that I can't set the id on the clr-button, you can reproduce it on the same [link](https://stackblitz.com/edit/custom-title-directive), when we run test automation, we usually use id to identify elements, but I can't see the id attribute on the rendered DOM.

**Comment by coryrylan** [comment]
The id attribute has been fixed. Due to accessibility concerns we currently wont be supporting title on `clr-button`. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#Accessibility_concerns

https://www.w3.org/TR/html/dom.html#the-title-attribute
