### ISSUE TITLE
ButtonGroup display problem in new forms

### ISSUE THREAD

**Issue by GaryHyland** [vmware/clarity#3134]
## Describe the bug

Below example shows code and screenshots for buttongroup in normal form and with clrForm
`			<form clrForm>
				<div class="btn-group">
					<div class="radio btn">
						<input type="radio" name="btn-group-radios1" id="btn-radio-11">
						<label for="btn-radio-11">Radio 1</label>
					</div>
					<div class="radio btn">
						<input type="radio" name="btn-group-radios1" id="btn-radio-12">
						<label for="btn-radio-12">Radio 2</label>
					</div>
					<div class="radio btn">
						<input type="radio" name="btn-group-radios1" id="btn-radio-13">
						<label for="btn-radio-13">Radio 3</label>
					</div>
					<div class="radio btn">
						<input type="radio" name="btn-group-radios1" id="btn-radio-14">
						<label for="btn-radio-14">Radio 4</label>
					</div>
				</div>
			</form>
			<form>
				<div class="btn-group">
					<div class="radio btn">
						<input type="radio" name="btn-group-radios2" id="btn-radio-21">
						<label for="btn-radio-21">Radio 1</label>
					</div>
					<div class="radio btn">
						<input type="radio" name="btn-group-radios2" id="btn-radio-22">
						<label for="btn-radio-22">Radio 2</label>
					</div>
					<div class="radio btn">
						<input type="radio" name="btn-group-radios2" id="btn-radio-23">
						<label for="btn-radio-23">Radio 3</label>
					</div>
					<div class="radio btn">
						<input type="radio" name="btn-group-radios2" id="btn-radio-24">
						<label for="btn-radio-24">Radio 4</label>
					</div>
				</div>
			</form>
`
![claritybuttongroup issue](https://user-images.githubusercontent.com/39715655/53218478-3b0a4080-3697-11e9-9538-910128f51837.PNG)

Surge example seems to just use old form I gather so has not issue
Note that the underlying code generated is
`<label for="btn-radio-13" class="clr-col-12 clr-col-md-2" ng-reflect-for-attr="btn-radio-13">Radio 3</label>`
I can verify that if I resize screen below md size then the problem goes away.

## How to reproduce

Refer code above

## Expected behavior

Need instructions for using radio button group using new forms.

## Versions

**App**

* Angular: [7]
* Node: [10.15]
* Clarity: [1.1.0]

**Device:**

* Type: [Surface Book]
* OS: [Windows 10]
* Browser [chrome]
* Version [72.0.3626.109]

**Comment by GaryHyland** [comment]
Update - managed to fix this issue for the new forms (clrForm) by adding 
class="clr-col-sm-12 clr-col-md-12"
to each label.
I suspect there is or will be a better Angular component clr-button-group type method for dogin this now or in future but I cant see anything in the docs.

**Comment by gnomeontherun** [comment]
You are correct about your solution, where we use the grid by default to layout form controls. Putting buttons inline without using the grid will align slightly off. The generic container #2864 approach will help solve these issues when its implemented.
