### ISSUE TITLE
Virtual scrolling support in Clarity datagrid module. 

### ISSUE THREAD

**Issue by pavandixit93** [vmware/clarity#3138]
## Summary

Hi Team, Currently i am using clarity design system. it consist of many great features and also it is very easy to use and it is user friendly.

In my project i am using clarity datagrid feature to handle large amount of data, it is working perfectly. Now i have to add virtual scrolling feature with datagrid. I dont see any documentation on _datagrid with virtual scrolling_. Can you please let me know about,

1) Are you going to implement datagrid with virtual scrolling feature?  and 
2) Is this part of clarity design system's next road-map?
3) Are there any challenges to add this feature?
## Use case

NA

## Examples

NA

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by Jinnie** [comment]
Virtual scrolling on the datagrid is an easy technical task, which is *very* hard to be done in an accessible way. Accessibility is a major requirement for all Clarity components.
Although there are some researches done on it and prototypes, it is still not officially on the Clarity list of Work In Progress tasks: https://github.com/vmware/clarity/wiki/Work-in-progress

Please, check this issue for more details:
https://github.com/vmware/clarity/issues/41

**Comment by pavandixit93** [comment]
@Jinnie Thanks for the update. I will check the link.
