### ISSUE TITLE
Datepicker locale mobile format error

### ISSUE THREAD

**Issue by mathisloge** [vmware/clarity#3139]
## Describe the bug

On mobile devices, the datepicker formats the input Date with the current locale

## How to reproduce

[Stackblitz example](https://clarity-light-theme-v1-0-pgsjqc.stackblitz.io/).

1.  Go to the example
2.  View Page on Desktop-Size-Screen. it should show the current date
3.  Reload the page with a mobile screen setting and look in the dev console of chrome. 
4.  See error

## Expected behavior

The Date should parsed inside the input field with format 'yyyy-mm-dd' no matter which language is set

## Versions

**App**

* Angular: 7.2.5
* Node: v11.10.0
* Clarity: 1.1.0

**Device:**

* Type: Mobile Screen Size
* OS: Windows
* Browser: chrome

**Comment by youdz** [comment]
Just a note, on mobile devices we completely deactivate our datepicker. We believe the native datepicker experience on all mobile devices is going to be better than the shrunk web one we could provide. In particular on phones, picking a date on a small calendar is really difficult, and users are accustomed to whatever the native experience of their phone is (typically spinning wheels on both iOS and Android, for instance).

I'm pretty sure we should still emit `[(clrDate)]` correctly though, so this does look like a bug to me.
