### ISSUE TITLE
Please add these icons to Clarity 

### ISSUE THREAD

**Issue by Stela-Stamenkova** [vmware/clarity#3143]
Hello,
Can you please add these two icons to the Clarity library?
Thank you!
Stela

![host-group_line.svg](https://images.zenhubusercontent.com/5b8fea72fb5dec0b0d9ca3df/e5ac5f4d-bb46-41bd-90d8-cd0739e61727)

![host-group_solid.svg](https://images.zenhubusercontent.com/5b8fea72fb5dec0b0d9ca3df/52ff8143-00e4-4062-b4dd-38ebb5a70ce0)
[hostgroup-icons.zip](https://github.com/vmware/clarity/files/2932552/hostgroup-icons.zip)

**Comment by kirkian** [comment]
Hi Stela & Jeremy, just to mention, the naming for this icon is **host groups**  :)
Thanks

**Comment by lil-kim** [comment]
Hi @Shijir 
Please replace the current "circle" and "dot-circle" icons in the library with these:
[timeline_icons_update.zip](https://github.com/vmware/clarity/files/2932456/timeline_icons_update.zip)
This zip also includes a spinner icon. Please let me know if it needs any changes. Thanks!

**Comment by coryrylan** [comment]
Done in PR #3192
