### ISSUE TITLE
Datagrid Filter Box visibility issue under certain conditions

### ISSUE THREAD

**Issue by orditeck** [vmware/clarity#3145]
## Describe the bug

The filter's box becomes almost unusable when filtering without pagination (or with pagination but with all the results on page 1, so basically it happens when the table doesn't have a fixed height which a pagination > 1 page adds) and below 2 results (because with 2 results there is enough heigh to view the filter's box).

![datagrid](https://user-images.githubusercontent.com/2186535/53497284-d9b8e780-3a71-11e9-8dac-bc78403bd277.gif)

## How to reproduce

1.  Go to https://clarity.design/documentation/datagrid/string-filtering
2.  Click on the filter icon next to the Pokemon column
3.  Enter "Kabuto"
4.  See error

## Expected behavior

Filter box should be visible

## Versions

**App**

* Angular: 7.2.5
* Node: 9.11.2
* Clarity: 1.1.0

**Device:**

* Type: MacBook
* OS: MacOS 10.14
* Browser: Chrome
* Version: 72.0.3626.109

**Comment by Kangcor** [comment]
I think this issue is already open [link](https://github.com/vmware/clarity/issues/2683)

**Comment by orditeck** [comment]
Ah. My bad. Closing this in favor of #2683 then
