### ISSUE TITLE
ClrModal angular component dispatching double events when closed

### ISSUE THREAD

**Issue by jvitorino** [vmware/clarity#3149]
## Describe the bug

I recently upgraded from an earlier version of Clarity and Angular 4 to the latest version of Clarity and Angular 7 and our event listener is being fired twice when the modal is closed.  I looked at the source code and found this todo:
```
  close(): void {
    if (this.stopClose) {
      this.altClose.emit(false);
      return;
    }
    if (!this.closable || !this._open) {
      return;
    }
    this._open = false;
    // todo: remove this after animation bug is fixed https://github.com/angular/angular/issues/15798
    // this was handled by the fadeDone event below, but that AnimationEvent is not firing in Angular 4.0.
    this._openChanged.emit(false);
    // SPECME
    this.focusTrap.setPreviousFocus(); // Handles moving focus back to the element that had it before.
  }

  fadeDone(e: AnimationEvent) {
    if (e.toState === 'void') {
      this._openChanged.emit(false);
    }
  }
```
it seems like the "todo" was never done?

## How to reproduce

Create a component that binds to the clrModalOpenChange event emitter on the ClrModal component.  Open the modal and then close it and notice that your event listener is fired twice.

## Expected behavior

Expect that only a single event is emitted when the modal is closed

## Versions

**App**

* Angular: 7
* Node: 10.15
* Clarity: 1.1

**Device:**

* Type: PC
* OS: Windows 10
* Browser: Chrome
* Version 72

**Comment by hippee-lee** [comment]
Thanks for reporting this. I thought we had an open issue for this but searching issues didn't return anything related. 

I am adding a minimal reproduction so it can be seen in action. 
https://stackblitz.com/edit/clarity-issue-3149-double-open-chaneg-events
