### ISSUE TITLE
Close button icons do not have an accessible name

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3154]
## Description
When using VoiceOver/Safari/iOS 12.1.4 and swiping to the "X"  icon in the .top right corner of  the "we are hiring"  container, the user hears this control announced as the word "button".  Screen reader users will not know what this button does without providing an accessible name.

In the HTML for this button below, we can see that there is no text or attribute for this button to have an accessible name.

`<button _ngcontent-c0="" class="close" type="button"><clr-icon _ngcontent-c0="" shape="close"><svg version="1.1" viewBox="0 0 36 36" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" focusable="false" aria-hidden="true" role="img"><path class="clr-i-outline clr-i-outline-path-1" d="M19.41,18l8.29-8.29a1,1,0,0,0-1.41-1.41L18,16.59,9.71,8.29A1,1,0,0,0,8.29,9.71L16.59,18,8.29,26.29a1,1,0,1,0,1.41,1.41L18,19.41l8.29,8.29a1,1,0,0,0,1.41-1.41Z"></path></svg></clr-icon></button>`

## Location
Mobile iOS home page

## Priority
High

## Recommended fix
I recommend using aria-label to add an accessible name for this button as seen below.

`<button aria-label="close we are hiring" class="header-hamburger-trigger" type="button"><span></span></button>`

## LOE
fast

**Comment by youdz** [comment]
This one is strange, our code for alerts clearly shows we add the "Close" text to the icon. Not sure why it's not working anymore. This could be a problem for every single one of our icons, if it stopped working.
