### ISSUE TITLE
Swipe trap iOS 12.1.4/VoiceOver

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3156]
## Description  
Can't swipe right past  "Icons" in Hamburger menu using iOS 12.1.4/VoiceOver. VoiceOver users are trapped when the try to swipe past the work "Icons" link. They can explore by tough to move past it but it would take some guessing and the user could be lost afterwards.

## Location     
Hamburger menu

## Priority     
High
## Recommended fix      
Unknown fix

## LOE  
High

**Comment by gnomeontherun** [comment]
This is for the old website, and should not be an issue in the new website. Closing as resolved through new site.
