### ISSUE TITLE
Conversational UI component

### ISSUE THREAD

**Issue by niftyhawk** [vmware/clarity#3157]
## Conversational UI to create a chat experience with a chatbot

_Angular component needed to create a Conversational UI._

* New component needed to create a Chat UI.
* Just like any other User Interface component, it makes sense to keep it in Clarity
* No, it doesn't impact change in any other component.
* If this change introduces a new behavior, the behavior should be accessible, by clicking an external link or image.

## Use case

Most sites integrate 24X7 support, by allowing the users to communicate with a chat bot. I would like to see an angular component in Clarity that shows a chat ui.

## Examples

https://www.telerik.com/kendo-angular-ui/components/conversationalui/

## Workarounds

None

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
