### ISSUE TITLE
After you open the Hamburger Menu the focus should move to the first menu item

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3163]
## Description  
After you open the Hamburger Menu the focus should move to the first menu item
## Location     
clr-header

## Priority   
Medium  

## Recommended fix      
Script to move focus to the  first menu item after the Hamburger Menu is opened.

## LOE  
fast

**Comment by gnomeontherun** [comment]
This is related to the old website, closing this as no longer valid.
