### ISSUE TITLE
Focus does not move correctly after routing to the Changelog view when using VoiceOver/Safari/iOS 12.1.4

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3165]
## Description  
Focus does not move correctly after routing to the Changelog view when using VoiceOver/Safari/iOS 12.1.4.After activating the 'What's new?' control from the Hamburger Menu, VoiceOver announces  the words "bug fix" which may confuse the user.

## Location     
Mobile iOS hamburger menu 

## Priority     
Medium 

## Recommended fix  
 I recommend moving focus to the heading of the view, i.e., "1.1.0 Changelog" so the user hears a heading that explains the contents of this view.

## LOE  
 fast

**Comment by gnomeontherun** [comment]
This is related to the old website, closing as no longer valid.
