### ISSUE TITLE
Download links don't indicate their purpose or that they lead to external domain

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3168]
## Description  
Site wide, there are inks that don't indicate their purpose and/or the fact that they lead to external domain. For example see the link below that downloads a file from an external domain. 

`<div class="description"><p class="title">Sketch template</p><p><a sketchtemplatelink="" target="_blank" href="https://github.com/vmware/clarity-assets/raw/master/sketch/light/clarity-library-light-1.0.0.sketch">Light Theme</a><br><!----><a sketchtemplatelink="" type="dark" target="_blank" href="https://github.com/vmware/clarity-assets/raw/master/sketch/dark/clarity-library-dark-1.0.0.sketch" class="ng-star-inserted">Dark Theme</a></p></div>`

## Location     
https://clarity.design/news

## Priority     
High

## Recommended fix      
Add link text that explains the purpose these links. If a link points to another domain, explain that as well in the link text.  

## LOE  
Fast

``

**Comment by gnomeontherun** [comment]
@chlane These links are for downloading assets, which just happen to be on a different domain (GitHub). Would it just suffice to change to something like "Download Sketch File" instead for example?

**Comment by chlane** [comment]
Hi Jeremy,

No this one is mainly about informing the user they are navigating to another domain.

Chris

**Comment by gnomeontherun** [comment]
They are not actually navigating, they are downloading a file. They won't leave the page, does that still require a change?

**Comment by chlane** [comment]
The problem is  that neither standard HTML <input> tags  or simuilated input elements <div role=”textbox”> …</div> can have child elements that are interactive. So the pills have to be structurally separate from the input field.

This can be seen at

https://www.w3.org/TR/wai-aria-practices/examples/grid/LayoutGrids.html

Look at "Example 2: Pill List For a List of Message Recipients"


I’ve also pasted the code below. You can see that the pills are structurally separate from the input field.

<div class="recipient-list">
          <span id="send_to_label">Send To:</span>
          <div role="grid" class="pill-list" aria-labelledby="send_to_label" data-wrap-cols="true">
            <div role="row" class="pill-item" data-id="1">
              <span role="gridcell"><a id="r1" class="pill-name" tabindex="0" href="#">Recipient Name 1</a></span>
              <span role="gridcell"><span id="rb1" class="pill-remove" tabindex="-1" role="button" aria-label="Remove" aria-labelledby="rb1 r1"> X </span></span>
            </div>
            <div role="row" class="pill-item" data-id="2">
              <span role="gridcell"><a id="r2" class="pill-name" tabindex="-1" href="#">Recipient Name 2</a></span>
              <span role="gridcell"><span id="rb2" class="pill-remove" tabindex="-1" role="button" aria-label="Remove" aria-labelledby="rb2 r2"> X </span></span>
            </div>
          </div>

          <div id="recipient-form">
            <input id="add-recipient-input" type="text" aria-label="Add Recipient" placeholder="New Recipient Name">
            <button id="add-recipient-button">Add</button>
            <div class="accessible_elem">
              Last change to recipient list:
              <span aria-live="polite" aria-relevant="text" id="form-action-text"></span>
            </div>
          </div>
        </div>


My concern with visually overlaying the pills over the input field is that the focus order might appear to be strange to sighted keyboard only users. This could be a possible tradeoff though.

Chris

**Comment by chlane** [comment]
Oh right sorry, the text should let the user know they are downloading something from another domain.

**Comment by AlexMarcuBytex** [comment]
Hello! Would be an idea to add a link or download icon in the label to express the purpose of the text link?

**Comment by gnomeontherun** [comment]
The request is more about that you are downloading something from another domain, which I think could be just `Download _FILE_ from GitHub`.

**Comment by chlane** [comment]
The idea is just to communicate the link purpose textually. Since it downloads a file from GitHub "Download _FILE_ from GitHub" will work. If you want to add an icon,  the icon will be redundant since it will be adjacent to the text "download". But if we want it for aesthetic reasons it  can be added and hidden from screen reader user using aria-hidden="true".

**Comment by AlexMarcuBytex** [comment]
Well, i guess the label can be changed to be more specific or im thinking of using title attribute for links which can be set through sketchLink directive. I see that you use that only for this specific case. What do you think?

**Comment by chlane** [comment]
Is it possible for us to use the link text "Download _FILE_ from GitHub" so the accessible names comes from the visible text?

**Comment by AlexMarcuBytex** [comment]
Ok. Assign me and i ll change the label that way.

**Comment by Jinnie** [comment]
It's yours, Alex!

**Comment by AlexMarcuBytex** [comment]
Should we use italic style for the name of the file like in your example to be more suggestive?

**Comment by AlexMarcuBytex** [comment]
I ll change the scope name but im waiting for clarifications.
