### ISSUE TITLE
Datagrid Hide/Show Columns option add X-axis scroll when last column hided with checkboxes menu

### ISSUE THREAD

**Issue by DPanarin** [vmware/clarity#3169]
## Describe the bug
When using "Hide/Show Columns option" in datagrid component if the last column was unchecked from checkboxes columns menu and then removed from the datagrid this causes a scrollbar on x-axis to be added. Probably a problem is with the table header items dividers (draggable vertical lines). It seems that css properties that used to remove the last element don't work correctly. They remove last elenemt (cell) but not last divider.

## How to reproduce

Such behavior can be reproduced on the official clarity documentation website <a href="https://clarity.design/documentation/datagrid/hide-show">Link to clarity dock where the bug can be reprodused</a>

1. Go to clarity official docks website. Chose datagrid component. Select Hide/Show demo from demos list.
2. Scroll to example datagrid table.
3. Click to Hide/Show button on the bottom left corner.
4. Unselect last checkbox to hide the last column in the table.
5. See the horizontal scrollbar.

## Expected behavior

Unselection of the last element of the menu and removing the last column of the table should not add a horizontal scrollbar to datatgrid

## Versions

**App**

* Angular: [7.2.6]
* Node: [11.4.0]
* Clarity: [1.0]

**Device:**

* Type: [PC]
* OS: [Ubuntu 18.04]
* Browser: [chrome]
* Version [71.0.3578.98 (64-bit)]

**Comment by kbuffington** [comment]
This is still an issue in v2. Definitely seems to be related to not removing the last column header divider.
