### ISSUE TITLE
Iconography: Red colors for error and warning class are not distinguishable

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#317]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The warning color should be a yellow or lighter orange color; should be clearly distinguishable from the Error red color. One possible caveat: would changing "warning" to orange affect classes in any other components? ie: danger/warning buttons?

### Actual behavior
Currently Warning and Error classes both use reds that are very similar.

### Reproduction of behavior

![image](https://cloud.githubusercontent.com/assets/23196444/21664109/6366a690-d299-11e6-9678-116989577457.png)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
What color should it be?

**Comment by lil-kim** [comment]
As decided in today's vizD review meeting, the warning color for icons should be: **#FAC400**.
Note: this change **should not** be applied to any other components with a warning class, ie: alerts and buttons.
