### ISSUE TITLE
Datagrid sorting does not work

### ISSUE THREAD

**Issue by codestitch** [vmware/clarity#3170]
## Describe the bug

Followed the documentation in creating a data grid. I added `[clrDgField]` property for sorting as mentioned in the documentation but is not working as the expected.

## How to reproduce

Create new component and add this:

**datagrid.component.html**
```
<h1>Data Grid</h1>
<clr-datagrid>
   <clr-dg-column>Position</clr-dg-column>
   <clr-dg-column [clrDgField]="'name'">Name</clr-dg-column>
   <clr-dg-column [clrDgField]="'weight'">Weight</clr-dg-column>
   <clr-dg-column [clrDgField]="'symbol'">Symbol</clr-dg-column>
   <clr-dg-column [clrDgField]="'color'">Color</clr-dg-column>
   
   <clr-dg-row *clrDgItems="let element of elements">
      <clr-dg-cell>{{element.position}}</clr-dg-cell>
      <clr-dg-cell>{{element.name}}</clr-dg-cell>
      <clr-dg-cell>{{element.weight}}</clr-dg-cell>
      <clr-dg-cell>{{element.symbol}}</clr-dg-cell>
      <clr-dg-cell>
          <div class="color-square" [style.background-color]="element.color"></div>
      </clr-dg-cell>
   </clr-dg-row>

   <clr-dg-footer>{{elements.length}} element</clr-dg-footer>
</clr-datagrid>
```

**datagrid.component.ts**
```
...imports...
@Component({ ... })
export class DatagridComponent {
   elements: PeriodicElement[] = ELEMENT_DATA;
   constructor() { }
}

const ELEMENT_DATA: PeriodicElement[] = [
   { position: 1, name: 'Hydrogen', weight: 1.0079, symbol: 'H', color: 'red' },
   { position: 2, name: 'Helium', weight: 4.0026, symbol: 'He', color: 'green' },
   { position: 3, name: 'Lithium', weight: 6.941, symbol: 'Li', color: 'blue' },
   { position: 4, name: 'Beryllium', weight: 9.0122, symbol: 'Be', color: 'yellow' },
   { position: 5, name: 'Boron', weight: 10.811, symbol: 'B', color: 'cyan' },
   { position: 6, name: 'Carbon', weight: 12.0107, symbol: 'C', color: 'pink' },
   { position: 7, name: 'Nitrogen', weight: 14.0067, symbol: 'N', color: 'orange' },
   { position: 8, name: 'Oxygen', weight: 15.9994, symbol: 'O', color: 'violet' },
   { position: 9, name: 'Fluorine', weight: 18.9984, symbol: 'F', color: 'brown' },
   { position: 10, name: 'Neon', weight: 20.1797, symbol: 'Ne', color: 'black' },
];

export interface PeriodicElement {
   name: string;
   position: number;
   weight: number;
   symbol: string;
   color: string
}
```

1.  Create new page component to display datagrid.
2.  apply code and check

![capture](https://user-images.githubusercontent.com/5573444/53813432-8ce37e00-3f55-11e9-8ece-b6222238cf0e.PNG)

3. searched for oxygen but it did not filter, it only move the  row to the last.

## Expected behavior

Should only display rows that you filter

## Versions

**App**

* Angular: 7
* Node: 8.12.0
* Clarity/angular: 1.1.0
* Clarity/icons: 1.1.0
* Clarity/ui: 1.1.0

**Device:**

* Type: Windows Laptop
* OS: Windows10
* Browser : Chrome
* Version : 72.0.3626.121 

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Per our bug report template, providing a stackblitz demo is requested so we can more easily triage your issue. You can find starters here: https://stackblitz.com/@clr-team.

**Comment by Jinnie** [comment]
Your code seems to be working pretty fine:
https://stackblitz.com/edit/issue-3170-repro?file=src/app/app.component.html

Please, do make stackblitz demos like the above for your future issues. This helps us a lot.
