### ISSUE TITLE
The vertical ellipses button on the design page announces as "button" when read by a screen reader

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3172]
## Description  
The vertical ellipses button on the design page announces as "button" when read by a screen reader. This issue was reproduced using VoiceOver/Safari/iOS 12.1.4.  The word "button" alone does not describe the purpose of this control. This will confuse screen reader users.  

see the relevant HTML below.

`<button class="header-overflow-trigger" type="button"><span></span></button>`

This issue is related to https://github.com/vmware/clarity/issues/3155

This issue also occurs with the vertical ellipses button used to select changelogs at https://clarity.design/news. 

## Location     
https://clarity.design/icons Any page where the vertical ellipses button is used.

## Priority     
High

## Recommended fix      
Add text that describes the purpose of this button  by either using visible text, accessible offscreen text or aria-label.

/* .CSS class for accessible offscreen text /
.offscreenText {position: absolute;clip: rect(1px 1px 1px 1px); / IE6, IE7 */clip: rect(1px, 1px, 1px, 1px);clip-path: inset(50%);padding: 0;border: 0;height: 1px; width: 1px; overflow: hidden;white-space: nowrap;}

## LOE  
Low

**Comment by coryrylan** [comment]
fixed in https://github.com/vmware/clarity/pull/3206
