### ISSUE TITLE
The images under Color Blind Accessibility need better alt text

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3177]
## Description  
 All of the images under Color Blind Accessibility need better alt text. Each of these images conveys more information than provided by their respective alternative text. See the images below.

`<img _ngcontent-c3="" alt="Normal vision" src="assets/images/documentation/color/normal_vision_donut.png">`

`<img _ngcontent-c3="" alt="Colorblind simulation" src="assets/images/documentation/color/colorblind_simulation_donut.png">`

`<img _ngcontent-c3="" alt="difficult color pairs for colorblindness" src="assets/images/documentation/color/difficult_color_pairs_for_colorblindness.png">`

`<img _ngcontent-c3="" alt="Do" src="assets/images/documentation/color/red_green_do.png">`

`<img _ngcontent-c3="" alt="Don't" src="assets/images/documentation/color/red_green_dont.png">`

`<img _ngcontent-c3="" alt="Do" src="assets/images/documentation/color/light_dark_do.png">`

`<img _ngcontent-c3="" alt="Don't" src="assets/images/documentation/color/light_light_dont.png">`

## Location     
https://clarity.design/documentation/color

## Priority     
High

## Recommended fix      
Write alternative text that conveys the meaning of the image. See the example below.

`<img _ngcontent-c3="" alt="Purple #7F41A7 and Blue #2765A are not distinguishable from one another by people who are color blind. Red and Green and Teal and Blue are also not distinguishable from one another by people who are color blind
" src="assets/images/documentation/color/difficult_color_pairs_for_colorblindness.png">`

## LOE  
Low

Purple #7F41A7
Blue #2765A6

**Comment by gnomeontherun** [comment]
No longer an issue or resolved in the upcoming website work. Closing as resolved.
