### ISSUE TITLE
Some of the icons download has error - no content in the file

### ISSUE THREAD

**Issue by ChitMeng-VMware** [vmware/clarity#3180]
## Describe the bug

Some of the icons download has issues opening. I only tested with "dollar" and "dollar-bill". But "Unknown" and "Home" are behaving correctly.

When the file is open in the Chrome browser, it shows "error on line 1 at column 1: Document is empty".

## How to reproduce

Go to https://clarity.design/icons; search wit"

1.  Go to '.https://clarity.design/icons.'
2.  Search for  'dollar'
3.  Downloads the icons
4.  Open the icons in the web browser

## Expected behavior

Users should be able to see the icons.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: MacBook
* OS: macOS Mojave
* Browser: Chrome
* Version:  72.0.3626.121 (Official Build) (64-bit)

## Additional notes

Thank you. :-)

**Comment by mathisscott** [comment]
@Shijir 
I looked into this and it appears that the Commerce shapes are not available to download and are also not in the ZIP file of all archives. Could you get this corrected for the release this week?

**Comment by gnomeontherun** [comment]
For some reason, I missed this set in the `clarity-assets` repo, just need to update the latest build into `icons/commerce`
