### ISSUE TITLE
(IN PROGRESS) <label> elements should use the "for" attribute 

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3182]
## Description

```
<clr-checkbox-wrapper>
  <input type="checkbox" clrCheckbox value="option1" name="options" />
  <label>Option 1</label>
</clr-checkbox-wrapper>

```
## Location
https://clarity.design/documentation/checkboxes

## Priority
High 

## LOE
Medium

**Comment by coryrylan** [comment]
Clarity inputs that use the proper wrapper component will have the for attribute automatically added for them. If you inspect the DOM in the dev tools you will see an auto generated `id` and `for`.

<img width="786" alt="screen shot 2019-03-06 at 12 56 01 pm" src="https://user-images.githubusercontent.com/2021067/53905951-5b2eed80-400f-11e9-8806-724992ad2815.png">
