### ISSUE TITLE
(IN PROGRESS) Stop using text-transform: uppercase; on buttons

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#3185]
```
.btn {
    cursor: pointer;
    display: inline-block;
    -webkit-appearance: none!important;
    border-radius: .125rem;
    border: 1px solid #0079b8;
    min-width: 3rem;
    max-width: 15rem;
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
    text-align: center;
    text-decoration: none;
    text-transform: uppercase;
    vertical-align: middle;
    line-height: 1.5rem;
    letter-spacing: .12em;
    font-size: .5rem;
    font-weight: 500;
    height: 1.5rem;
    padding: 0 .5rem;
    background-color: transparent;
    color: #0079b8;
    margin: .25rem .5rem .25rem 0;
}
```

## LOE

39 | Button text - we need to get   away from All Caps, any way we can move to mixed case in future versions? | Buttons | medium | I really like this article on   when to use upper vs mixed or lower case.    https://uxplanet.org/why-letter-casing-is-important-to-consider-during-design-decisions-50402acd0a4e | High |   |  
-- | -- | -- | -- | -- | -- | -- | --

**Comment by mathisscott** [comment]
If we were to fix this, it would be as a part of a larger visual change. Not saying that isn't on the horizon. Just that we wouldn't tackle it in the current visual treatment. ;-)

**Comment by chlane** [comment]
Hi Scott,

I actually closed this after reading the article Sheri included and want to discuss it with her first.

Chris
