### ISSUE TITLE
[NG] Make the checkbox component public

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#319]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
The `<clr-checkbox>` component should be documented with proper demos, so that our users can test this "shortcut" and give us feedback on its usefulness. The point being to release this type of component for all inputs, so that our users won't have to constantly check the correct markup and classes needed by our static form controls.

### Actual behavior
Currently, the [component exists](https://github.com/vmware/clarity/blob/master/src/clarity-angular/checkboxes/checkbox.ts) and [is extensively tested](https://github.com/vmware/clarity/blob/master/src/clarity-angular/checkboxes/checkbox.spec.ts), but is just not documented. It is used internally by some of our other components.
It is also missing a few of the usual checkbox attributes, like `disabled` or `required` (although that last one probably works with `ngModel` on the `<clr-checkbox>` element itself. These should be added as part of the publication of the component if time allows, or be requested as a separate issue if not.

**Comment by hippee-lee** [comment]
Reopening this issue, it should not have been closed.
