### ISSUE TITLE
DataPicker - Reactive Form

### ISSUE THREAD

**Issue by markofranjic** [vmware/clarity#3194]
## Describe the bug

Cannot get formated date to DataPicker.
I got date from Web API in this format '2019-03-07T00:00:00' and that date need to be formated and set to data picker, but DataPicker doesn't format date and set date.

## How to reproduce
https://stackblitz.com/edit/angular-clarity-ui-ux-jxggys?file=src/app/app.component.ts

## Expected behavior

When form is empty and I populate all required fields and save that to database over web api, that works as excepted.

When I want edit form, I got data from web api and all data has been set to input fields but data picker is empty.

**Comment by Jinnie** [comment]
@markofranjic I'm sorry, but this has nothing to do with Clarity. You have to make sure your server exports the correct time zone, or use UTC only, or manually account in your app for the time zone difference. See the ISO Dates (Date-Time) section here:
https://www.w3schools.com/js/js_date_formats.asp
Pay attention to the highlighted notes.

**Comment by Jinnie** [comment]
@markofranjic My mistake, your case is valid. We already have a report on it though, please follow this issue: #3008

**Comment by Jinnie** [comment]
@markofranjic can you provide more information about this case:
```
startDate: [new Date('2019-03-07T00:00:00').toLocaleDateString()] // Doesnt work
```
It seems to be working when I am testing with it.

**Comment by markofranjic** [comment]
Yes, you are correct that works.

Is there any chance to resolve this issue like other UI components. like Angular Material?

**Comment by Jinnie** [comment]
We're evaluating the different options. But for now, the website remains the single source of truth:
```
We recommend that you either access the date as a string or as a javascript date object
from the date picker. Using both at the same time might cause unexpected behavior.
```
Thanks for your feedback, it does help!
