### ISSUE TITLE
Problem with datagrid-action-overflow and signpost inside datagrid

### ISSUE THREAD

**Issue by williangd** [vmware/clarity#3197]
## Describe the bug

datagrid-action-overflow and signpost within datagrid are creating scroll

## How to reproduce

The problem also occurs in the documentation.
The problem dont occurs in version 0.13.

Version 1.1:
![datagrid-1-1](https://user-images.githubusercontent.com/16259047/54029226-740ddf00-4186-11e9-9a8f-face4eacf5be.png)
![datagrid-signpost](https://user-images.githubusercontent.com/16259047/54029630-d4515080-4187-11e9-8aa3-e16c800eb080.png)

Version 0.13:
![datagrid-0-13](https://user-images.githubusercontent.com/16259047/54029240-81c36480-4186-11e9-8e48-d79b3e97889c.png)
![datagrid-signpost-0-13](https://user-images.githubusercontent.com/16259047/54029637-dc10f500-4187-11e9-8cff-2fcda2811d56.png)

## Expected behavior

Same behavior of version 0.13.

## Versions

**App**

* Angular: 7.2.8
* Node: 10.15.3
* Clarity: 1.1.1

**Comment by Jinnie** [comment]
Thanks for reporting. This will be fixed with the new smart popovers.
There is already an issue tracking this #2683 
Please, check it for details and updates.
