### ISSUE TITLE
Timeline component (Static)

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#3199]
## Summary

I'm proposing a timeline component implementation based on existing design spec from https://github.com/vmware/clarity/issues/1633. This change introduces a static version of the timeline using HTML/CSS. Accessibility will require some further evaluation as I'm not sure about the expectations on this topic.

## Use case

The use case of a timeline component is to have visualized way of presenting a serious of pre-defined steps and show the current progress/status.

## Examples
See demo at: 
https://clarity-timeline-demo-v3.stackblitz.io (Latest)

~~https://clarity-timeline-demo-v2.stackblitz.io~~ (Center justified horizontal, depricated)

~~https://clarity-light-theme-v1-0-xeza1u.stackblitz.io~~ (Embedded SVG icons, depricated)

Screenshots of demo:
<img width="963" alt="timeline_horizontal_v3" src="https://user-images.githubusercontent.com/8813134/58459781-09af6f80-80e1-11e9-91f5-264609db60ef.png">

<img width="325" alt="timeline_vertical_v3" src="https://user-images.githubusercontent.com/8813134/58459821-1b911280-80e1-11e9-9376-70b56c9280f3.png">

## API

The following HTML sample code demonstrates how the timeline component can be consumed from user side. Highlights are:
* The `.clr-timeline` contains a number of `.clr-timeline-step` blocks.
* Each `.clr-timeline-step` contains `.clr-timeline-step-header` (Optional), `clr-icon` and `.clr-timeline-step-body`.
* Each `.clr-timeline-step-body` contains `clr-timeline-step-title` and `clr-timeline-step-description`.
* `.clr-timeline-horizontal` or `.clr-timeline-vertical` class is added to `.clr-timeline` to specify timeline type (direction).
* ~~Different classes `.not-started`, `.is-current`, `.in-progress`, `.is-completed` and `.is-error` can be added to each `.clr-timeline-step` to indicate the step status.~~ (Replaced by specifying different clr-icon shapes).
* `aria-label` is added to each `clr-icon` to show their meaning for screen reader.
* `aria-current="true"` is added to current step icon.

```html
<h4>Horizontal timeline</h4>

<ul class="clr-timeline clr-timeline-horizontal">
  <li class="clr-timeline-step">
    <div class="clr-timeline-step-header">11:59 am</div>
    <clr-icon shape="circle" aria-label="Not started"></clr-icon>
    <div class="clr-timeline-step-body">
      <span class="clr-timeline-step-title">Add KMS</span>
      <span class="clr-timeline-step-description">Root CA certificate requested.</span>
    </div>
  </li>
  <li class="clr-timeline-step">
    <div class="clr-timeline-step-header">11:59 am</div>
    <clr-icon shape="dot-circle" aria-current="true" aria-label="Current"></clr-icon>
    <div class="clr-timeline-step-body">
      <span class="clr-timeline-step-title">Add KMS</span>
      <span class="clr-timeline-step-description">
        Root CA certificate requested. Upload it to the KMS to complete the connection.
        <button class="btn btn-sm">Action</button>
      </span>
    </div>
  </li>
  <li class="clr-timeline-step">
    <div class="clr-timeline-step-header">11:59 am</div>
    <clr-icon shape="spinner" aria-label="In progress"></clr-icon>
    <div class="clr-timeline-step-body">
      <span class="clr-timeline-step-title">Make vCenter trust KMS</span>
      <span class="clr-timeline-step-description">
        Root CA certificate requested. Upload it to the KMS to complete the connection. Third sentence is very long
        and very long.
      </span>
    </div>
  </li>
  <li class="clr-timeline-step">
    <div class="clr-timeline-step-header">11:59 am</div>
    <clr-icon shape="success-standard" aria-label="Completed"></clr-icon>
    <div class="clr-timeline-step-body">
      <span class="clr-timeline-step-title">Make KMS trust vCenter</span>
      <span class="clr-timeline-step-description">Upload it to the KMS to complete the connection. Third
        sentence.
        <button class="btn btn-sm btn-link">Action</button>
      </span>
    </div>
  </li>
  <li class="clr-timeline-step">
    <div class="clr-timeline-step-header">11:59 am</div>
    <clr-icon shape="error-standard" aria-label="Error"></clr-icon>
    <div class="clr-timeline-step-body">
      <span class="clr-timeline-step-title">Connected</span>
      <span class="clr-timeline-step-description">No. It's not connected.</span>
    </div>
  </li>
</ul>
```

## Implementation plan

_Describe how you plan to implement the feature, answering questions among the following or anything else you deem relevant._

* What parts of the code are affected?
  - clr-angular/timeline/[_timeline.clarity.scss,  _variables.timeline.scss] (created for the component)
  - dev/src/app/timeline (for dev app demo)
* Will you introduce new services, components or directives?
  - See above. Only new static styles for now.
* Can you describe the basic flow of information between classes? - N/A.
* Does this introduce asynchronous behaviors? - No.
* Will you need to refactor existing Clarity code? - No.
* Will reasonable performance require optimizations? - No.
* Will it need to access native elements (and be incompatible with server-side rendering)? - No.

## Conclusion
The current implementation follows the design spec and are mostly done from feature perspective.  Some of the remaining items are:
~~- Some code cleanup.~~
- Discuss a few minor topics regarding the UX design spec.
~~- Test out browser compatibility.~~ (Tested in Chrome, Firefox, Safari, Edge and IE11)
- Accessibility support. (Will have further discussion if required)
- Dark theme support. (Missing UX design).
- Testing (What testing are required here?)
- Documentation (When will this be required?)

Timelines (Yes, timelines of the timeline component):
- Static timeline UI style: preferably in a few weeks to a month.
- Angular component: TBD.

**Comment by typhoon1978** [comment]
Need this!!! Great work!

**Comment by gnomeontherun** [comment]
Hey @yaooluu thanks for this great demo and it looks pretty good at first glance. I have a few comments for you and design based on this.

1. All classes should be prefixed with `clr-timeline`, right now you have a few that aren't like `horizontal`. Good job on the rest.
2. I don't agree with making the button's 100% width inside of the steps, though that is what the spec appears to do. This is strange when there is a lot of space, so I need to ask @colinreedmiller about that.
3. We don't want to embed the icons into the CSS, so the icon generators should be replaced with elements with `clr-icon` shapes. Given the new spinner icon, you'll have to manually add that to icons for this demo. In the Angular component version, consumers won't have to define the icons but in the static version they will.
4. I didn't do a full cross reference, but the colors should all stem from existing color variables (lines 4-7, 49-52 in variables.scss), so if there are any differences you'll need to update them in your implementation.
5. There is some polish to work out on the step headers, if the content is not 100% consistent (like if you change the `11:59 am` value to something longer) it can push content down in horizontal or to the right in vertical.
![image](https://user-images.githubusercontent.com/79500/54159776-d92e3280-441b-11e9-8a84-554192d15565.png)
6. Have you tested in IE11 and all other browsers? I haven't checked but wanted to know what you've done here.
7. Some of the CSS rules you've written are unnecessarily nested, we want to aim for max 3 levels deep in actual implementation, not that you need to fix that for this demo.
8. Another design question is around navigation, none of the headers are links (again based on design) but I wonder if there won't be a need to click on a title to navigate? Again @colinreedmiller?

Overall, the challenges are likely to be in ensuring consistent display with more dynamic content. I didn't try too many changes to push the boundaries, but the DOM looks good to me (it needs the icons too).

**Comment by gnomeontherun** [comment]
Also pinging @chlane about a11y for this, do you have any feedback?

**Comment by clane** [comment]
So far the main issue I see is that the icons representing the various states a step can have do not have textual equivalents for screen reader users to hear.

For example, the green checkmark icon is intended to visually indicate that the step is in the "is-completed" state but there is no text or aria-label that these icons can get their accessible name from. Screen reader users will not know what these icons mean. 

The step states that these icons represent are as follows. 

not-started
is-current
in-progress
is-completed

The is-current step should be indicated with aria-current="true" and should be the only element with the aria-current attribute. Toggling between "true" and "false" values will not work. 

I'm not sure what the difference between the is-current and in-progress state is but it seems like in-progress means something is loading due to the spinner. When there is a spinner I recommend using a live region that tells the user what is happening at reasonable intervals.

**Comment by colinreedmiller** [comment]
@yaooluu - I am concerned with the center justification of the type on the horizontal design. While I understand the visual reasons, it is less parsable than the left justified vertical. Have you done any design exploration with different layout approaches for the content in the horizontal? If you have I'd like to see them and discuss the pros and cons, and if you have not I think we need to do so and examine the results.

**Comment by colinreedmiller** [comment]
re: Button full width I agree - I think this will be easier to solve when we address the label / message (center) justification issue above. It is my hope that a fully left justified horizontal design with a variable width left aligned button will work and be a good F-pattern design.

re: Clicking on the step icons to navigate - most users will do this and expect it to be a navigational affordance. I imagine enabling this would be useful but there may be a case where it is undesirable to allow the user to navigate the timeline in this way. If the timeline itself does not enable navigation between steps is it representing status only for a multi-step process? The example suggests that some interaction occurs (buttons on steps) while other steps are status only (message).

**Comment by gnomeontherun** [comment]
@yaooluu Do you have any questions or need more details to look into the feedback of this issue?

**Comment by yaooluu** [comment]
Hi @gnomeontherun, sorry I got delayed by others tasks. I had went through the feedback and will start addressing them, I'm planning to have an updated version out in a few days. I will reach out if I have more questions of concerns. Thanks!

**Comment by yaooluu** [comment]
Hi @gnomeontherun , I've done the following regarding your comments:

> 1. All classes should be prefixed with `clr-timeline`, right now you have a few that aren't like `horizontal`. Good job on the rest.

Done.

> 2. I don't agree with making the button's 100% width inside of the steps, though that is what the spec appears to do. This is strange when there is a lot of space, so I need to ask @colinreedmiller about that.

Will need more discussion based on @colinreedmiller 's feedback.

> 3. We don't want to embed the icons into the CSS, so the icon generators should be replaced with elements with `clr-icon` shapes. Given the new spinner icon, you'll have to manually add that to icons for this demo. In the Angular component version, consumers won't have to define the icons but in the static version they will.

Done. I added the spinner as a custom icon for now.

> 4. I didn't do a full cross reference, but the colors should all stem from existing color variables (lines 4-7, 49-52 in variables.scss), so if there are any differences you'll need to update them in your implementation.

Done. Except one color `#9b9b9b`, which is mentioned in the spec but not defined in Clarity. What should I do with it?

> 5. There is some polish to work out on the step headers, if the content is not 100% consistent (like if you change the `11:59 am` value to something longer) it can push content down in horizontal or to the right in vertical.

I realized this issue before I start the implementation. After spending hours researching, I could not find a way to `have headers be aware of each other and expand together if any one of them has more content` using pure HTML and CSS. In one of our internal projects, I had implemented a timeline Angular component based on another UX's design and was facing same issue, I used a different approach with JavaScript to dynamically adjust the sizes.

I had discussed this issue with @mathisscott before, we decided to go with the approach where we force header to be on one line (for horizontal) and use same header width (for vertical), you can see this in demo link above. Let me know if you have other better alternatives.

> 6. Have you tested in IE11 and all other browsers? I haven't checked but wanted to know what you've done here.

I tested the demo link on latest Chrome, Firefox, Safari, Edge and IE11. All works fine except IE11 with horizontal timeline. The step body text are not wrapping and overlapped there. I'm still debugging the root cause.

> 7. Some of the CSS rules you've written are unnecessarily nested, we want to aim for max 3 levels deep in actual implementation, not that you need to fix that for this demo.

Thanks for this great suggestion. I was simply mimicking the structure of the classes in DOM. I had reorganized the structure and to make it much cleaner. 

> 8. Another design question is around navigation, none of the headers are links (again based on design) but I wonder if there won't be a need to click on a title to navigate? Again @colinreedmiller?

Could you let me know who will be the design owner for timeline that I could work with? I see in previous https://github.com/vmware/clarity/issues/1633 that a few other designers were involved as well.

**Comment by yaooluu** [comment]
> So far the main issue I see is that the icons representing the various states a step can have do not have textual equivalents for screen reader users to hear.
> 
> For example, the green checkmark icon is intended to visually indicate that the step is in the "is-completed" state but there is no text or aria-label that these icons can get their accessible name from. Screen reader users will not know what these icons mean.
> 
> The step states that these icons represent are as follows.
> 
> not-started
> is-current
> in-progress
> is-completed
> 
> The is-current step should be indicated with aria-current="true" and should be the only element with the aria-current attribute. Toggling between "true" and "false" values will not work.
> 
> I'm not sure what the difference between the is-current and in-progress state is but it seems like in-progress means something is loading due to the spinner. When there is a spinner I recommend using a live region that tells the user what is happening at reasonable intervals.

Hi @clane , due to the removal of embedded SVG, the above step states are removed as well. I've updated the example HTML above to reflect the accessibility requirement you mentioned:
- `aria-label` is added to each `clr-icon` to show their meaning for screen reader.
- `aria-current="true"` is added to current step icon.

The above two items will be required for consumer to add when using static styles, and will be taken care by Angular version of the component later. Will this meet the accessibility criteria?

**Comment by yaooluu** [comment]
> @yaooluu - I am concerned with the center justification of the type on the horizontal design. While I understand the visual reasons, it is less parsable than the left justified vertical. Have you done any design exploration with different layout approaches for the content in the horizontal? If you have I'd like to see them and discuss the pros and cons, and if you have not I think we need to do so and examine the results.

Hi @colinreedmiller , actually I had been following the original specs and didn't do any design exploration until you mentioned it. But looking at the design again I do feel a little bit of what you mean by "less parsable". I just quickly applied some hacks in my code to get a left justified horizontal timeline, with the button not taking full width. It looks like below:

<img width="748" alt="Screen Shot 2019-03-25 at 9 33 49 PM" src="https://user-images.githubusercontent.com/8813134/54971952-5c847380-4f46-11e9-9755-1df4db7f5421.png">

For comparison purpose, the current implementation is:
<img width="794" alt="Screen Shot 2019-03-25 at 9 39 00 PM" src="https://user-images.githubusercontent.com/8813134/54971975-7b830580-4f46-11e9-9cff-4ac5a22bec04.png">

Let me know what you think :)

**Comment by chlane** [comment]
Hi Yao,

It’s ok for aria-label to be populated by the consumer but aria-current would normally be set by the component.

**Comment by colinreedmiller** [comment]
@yaooluu Left alignment and variable width buttons are an improvement - thanks.

I have done a little work on the spacing and line height in the description. This is not a complete spec but it ought to help get us where we need to go. The container is for margin reference and needn't be part of the component - included to validate the spacing choices. Please let me know if you have questions working out the permutations of the component based on this direction.

<img width="1130" alt="timeline-left" src="https://user-images.githubusercontent.com/44213553/55117396-eef05880-50a7-11e9-8cc9-9348ca54edaf.png">

**Comment by mathisscott** [comment]
@mcmac123 
Please update with comments from today's meeting.

**Comment by clane** [comment]
@yaooluu - aria-current should be managed by the component as it is not static. aria-label on the other hand is static and can be supplied by the consumer.

**Comment by yaooluu** [comment]
Hi @clane , I understand your concern here. If you mean an `Angular` component, then yes both `aria-current` and `aria-label` can be managed by the component and consumer doesn't need to worry about them.

What I presented above is pure HTML/CSS version of the the timeline. Everything is static there (they're just HTML structure with styles) and consumer has full control of how they want to use it (i.e. manually specify which step is the current one, by assigning "dot-circle" to any clr-icon element). Therefore, there is no way for us to dynamically add an an attribute (`aria-current="true"`) to HTML element (icon whose shape is dot-circle) using just CSS. And JavaScript is designed for such behavior, but as I mentioned this is the static version of timeline with just markups and styles.

**Comment by yaooluu** [comment]
Hi team, I would like to proceed further on this topic. It will be great if you can let me know what more needs to be done here to get the final UX spec so that I can publish a request to get this merged.

**Comment by mathisscott** [comment]
@colinreedmiller ^

**Comment by colinreedmiller** [comment]
Hi @yaooluu I am just finishing up a revised design spec to address sizing, spacing and alignment issues. Most expedient might be a quick realtime chat via Slack or Zoom to review the changes since it is fairly complex doc.

**Comment by yaooluu** [comment]
Had a discussion with @colinreedmiller and cleared some major questions. Will proceed with the changes and then have UX review and sign off the updated version.

**Comment by colinreedmiller** [comment]
Complete spec:
[https://app.zenhub.com/files/69590701/cea7d702-1e9a-4cfd-999f-8f0b8cb70848/download](https://app.zenhub.com/files/69590701/cea7d702-1e9a-4cfd-999f-8f0b8cb70848/download)

**Comment by cloud9amit** [comment]
where can i find source code of it. Like class="clr-timeline clr-timeline-horizontal" where is this defined?

**Comment by mathisscott** [comment]
Hi @cloud9amit 
This component is still in development and is not available yet. Please subscribe to this issue to be notified when its status changes. Thanks!

**Comment by yaooluu** [comment]
I've update the timeline styles to match the latest UX specs. @colinreedmiller Could you please review the updated demo link above?

**Comment by colinreedmiller** [comment]
https://clarity-timeline-demo-v3.stackblitz.io/

Demo conforms to design specification.
note: No dark theme design exists for this component yet.

**Comment by yaooluu** [comment]
Hi @mathisscott , with the UX approval above, what should be the next steps for me to follow?

**Comment by mathisscott** [comment]
If it has a stamp of approval from @colinreedmiller, then I think you're ready to submit a PR for review. We may have some suggestions about SASS variables or CSS during the review. But I think you're at a point where we can work through those in a PR.

**Comment by mathisscott** [comment]
And thanks, @yaooluu. You've been incredibly professional and diligent through this process. We don't usually have a situation where the UX needs to change in the middle of implementation. Thank you for your patience.

**Comment by colinreedmiller** [comment]
Implementation looks great. Stamp of approval given.

also: Everything Scott said x100 - @yaooluu - I really appreciate your perseverance in making adjustments to the design in flight.

**Comment by gnomeontherun** [comment]
Hi @yaooluu, just wanted to check on the status on your end, thanks!

**Comment by yaooluu** [comment]
Hi @gnomeontherun I'm working on creating a pull request. Can I get a topic branch created for this issue?

**Comment by gnomeontherun** [comment]
I think we're in a place you can just make the PR against master since you've got the whole implementation right? No need for a topic branch unless you are expecting to submit a lot of smaller RPs.

**Comment by yaooluu** [comment]
@gnomeontherun Sounds good to me. I was just looking at DEVELOPMENT_CONTRIBUTION.md and there it mentioned:
> When we post on the issue to approve your proposal, the person on the team who'll be your primary contact will post a link to a topic branch against which you will submit your pull requests. 

I'll create a pull request against master then.

**Comment by gnomeontherun** [comment]
Yeah, that is true if necessary but since you've already done a lot of the prototyping and detailing, I don't think we need to this time. We should update that to be more clear, but looking forward to reviewing!
