### ISSUE TITLE
Documentation SEO duplicate content

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#3201]
Older versions of the clarity documentation are available for reference. Older versions of the documentation should contain an additional meta tag to notify search engine crawlers not to index the content.

Because the documentation is so similar between versions, it puts the site at high risk of duplicate content which will push the documentation down in search engine results. This should also help users not accidentally refer to older documentation but the latest.

Meta tag to be added to all older non latests docs pages
`<meta name="robots" content="noindex nofollow" />`

**Comment by NorthRiver** [comment]
As a new user of Clarity, i have to admit that i DID end up quite a lot of times on the v0.11 of the documentation instead of the 1.0.

**Comment by gnomeontherun** [comment]
I've pushed changes to the github pages docs (which are old versions) with the meta tag to not index them.

**Comment by gnomeontherun** [comment]
This will take some time for SEO to sort out, but marking as resolved.
