### ISSUE TITLE
Datepicker initial value not displayed in TD forms

### ISSUE THREAD

**Issue by bsalama** [vmware/clarity#3203]
## Describe the bug

An initial date set using [clrDate] input binding is not displayed in the datepicker component if ngModel is added to the `<input>` element.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-yz6jmk

1. Go to https://stackblitz.com/edit/clarity-light-theme-v1-0-yz6jmk
2. The datepicker field is blank

## Expected behavior

The datepicker should show the date bound to [clrDate]

## Versions

**App**

* Angular: 7.2.0
* Clarity: 1.0.4

**Device:**

* Type: PC
* OS: Windows 10
* Browser: FF/Chrome

**Comment by Jinnie** [comment]
Hi @bsalama 
Why do you want to add `ngModel`?
It implies template driven datepicker. It works with a string-based date representation bound to the ngModel attribute. On our site we don't recommend the simultaneous use of both direct clrDate binding and the other, string-based scenarios:
```
We recommend that you either access the date as a string or as a javascript date object from the date picker. Using both at the same time might cause unexpected behavior.
```
Could you explain your use case in more detail please?

**Comment by bsalama** [comment]
I would like to add `ngModel` mainly for validation purposes. Using ngModel purely however is tricky since the string representation emitted by the datepicker is locale-dependent. Unless there is way to use Clarity's internal date service to parse/generate this date string.

**Comment by Jinnie** [comment]
Clarity is using the locale date representation, so `Date.toLocaleDateString()` will generate the proper string value you can use.
Nevertheless, we realize that the ability to use date object directly is more natural and though it's not on the roadmap, we are evaluating other options for the future releases, so we are thankful for your feedback.
We're keeping this issue one open for tracking the need for date-object based datepicker:
https://github.com/vmware/clarity/issues/3008
Although it's directed at reactive forms, the solution would be common. So I'm closing this as duplicate.
