### ISSUE TITLE
selected nav-group is not active when sidenav has multiple nav-groups 

### ISSUE THREAD

**Issue by abbyhtml** [vmware/clarity#3204]
Hi,

As per clarity documentation of .sidenav-content:
This is a wrapper intended to contain one or more .nav-group groups.

However with multiple .nav-groups , the selected nav-groups style does not change on click i.e. backgroung-color/color like than of an active nav-link.

**Comment by hippee-lee** [comment]
Hi @abbyhtml, - we need a minimal stackblitz that recreates the issue you are describing to help us investigate.

**Comment by hippee-lee** [comment]
The stackblitz doesn't seem to reflect the image uploaded. The navigation doesn't seem to be working for me.

**Comment by Jinnie** [comment]
If I get it right, @abbyhtml wants to click on the nav-group labels (element1 and element2) and wants them to behave as active elements (be selectable, hoverable). 
This is possible with 1st level nav-items, which looks similarly, but not sure it is expected to be done with the nav-group labels.

**Comment by abbyhtml** [comment]
Hi Jinnie,

Yes that is exactly was I was looking at. I could make the labels clickable but not behave as active elements (be selectable, hoverable) without tinkering the styles.

After your message I re-looked at the documentation and feel that maybe a "Tree View" is more suitable for my application layout. I will have to replace sidenav with a tree view inside content-container. Hope it will work along with routing to change views in content-area.

![image](https://user-images.githubusercontent.com/40457657/54334772-001f7b00-464d-11e9-9b02-f2981bc3d467.png)

**Comment by Jinnie** [comment]
@abbyhtml Glad you found a solution. You can check the "Routing using a tree" page in our documentation:
https://clarity.design/documentation/tree-view#routing-tree
