### ISSUE TITLE
ClrToggleWrapper component not found?

### ISSUE THREAD

**Issue by krist-jin** [vmware/clarity#3218]
## Describe the bug

Not able to use the ClrToggleWrapper component mentioned in https://clarity.design/documentation/toggle-switches and looks like there is no ClrToggleWrapper in the codebase at all if I search for ClrToggleWrapper in the repo.
Or maybe my understanding of the doc is wrong, and this ClrToggleWrapper is a dummy component and we need to create it ourselves?

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v1-0-6auuc4

Error is given: `'clr-toggle-wrapper' is not a known element`

## Expected behavior

```
<clr-toggle-wrapper>
  <input type="checkbox" clrToggle value="option1" name="options" />
  <label>Option 1</label>
</clr-toggle-wrapper>
```
Should show a toggle switch as demonstrated in the doc

## Versions

**App**

* Angular: 7
* Clarity: 1.0.4

**Device:**

* Type: MacBook
* OS: macOS 10.14.3
* Browser chrome
* Version 72

**Comment by dorthrithil** [comment]
`clr-toggle-wrapper` was introduced in Clarity 1.1.0 (see https://clarity.design/news/1.1.0)
If you update the dependencies of the stackblitz everything works: https://stackblitz.com/edit/clarity-dark-theme-v1-0-bifbaf
