### ISSUE TITLE
Open-source internal VMware Clarity components

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3222]
Hi! I often see screenshots of various VMware products on Twitter, and I see that they have some beautiful internal Clarity components, which are not present in this official package. Would be nice to have it opensourced, maybe, at least, as a separate add-ons package.

**Comment by hippee-lee** [comment]
Hi @sdurnov - Everything in Clarity is published to `npm`. There is no internal vs external Clarity package that gets published. What I think you may be seeing are the internal components developed on top of Clarity that are shared among different teams and product apps. 

I'm closing this as its not an issue and there is no internal Clarity code that only gets distributed to internal VMware teams. 

Can you expand on which components you are see that you are interested in?
