### ISSUE TITLE
Native Datepicker displays yesterday's date when selecting today's date in specific Timezones

### ISSUE THREAD

**Issue by hammc** [vmware/clarity#3224]
## Describe the bug

When using Clarity Datepicker on a small screen the native Datepicker displays yesterday's date when selecting the current date in specific timezones (for example GMT+0100 (Central European Standard Time) when binding to a Date Object.

## How to reproduce

1.  Set your timezone to GMT+1/UTC+1
2.  Go to [Clarity Datepicker Documentation](https://clarity.design/documentation/datepicker) -> Accessing the Date -> As a Javascript Date Object (on a mobile device or Chrome with Device Mode)
3.  Select a Date
5.  Error: the Date before the correct date gets displayed

## Expected behavior

The selected date should be displayed

## Versions

**App**

* Angular: 7.2.2
* Node: 8.11.3
* Clarity: 1.1.1

**Device:**

* Type: PC
* OS: Windows 10
* Browser: Chrome with Device Mode in Chrome DevTools
* Version: 72.0.3626.121

**Device:**

* Type: Pixel 2
* OS: Android Version 9 (Pie)
* Browser: Chrome
* Version: 72.0.3626.121

![DatePicker](https://user-images.githubusercontent.com/13888804/54673613-e40f5400-4afa-11e9-97e9-7a1ae046465c.gif)

**Comment by gnomeontherun** [comment]
The datepicker here is obviously the 'native' implementation and not our own UI. That part is good, but I do see this issue being set.

Somewhere we must not be handling timezones correctly, but I believe that is probably in the display more than the setting of the date (which should be built as a date object at midnight for the day, and that follows the +N GMTs would display it as the next day). This is curious we haven't seen it before, but the timezone offset doesn't appear to get applied.

**Comment by oliverhanappi** [comment]
Any news on this?

**Comment by hippee-lee** [comment]
Hi @oliverhanappi - this issue has been identified as a bug that needs more investigation. It is currently in the backlog queue.

**Comment by martinbrom** [comment]
While dealing with issue #3961 I also found a solution to this issue. Therefore, I would like to fix this issue as well. Please create the topic branch for me if you agree. Proposal follows:

## Summary

When on mobile devices, value of the input is set via calling the valueAsDate prototype. This function expects a UTC date as a parameter. When we select a date in the input, the date is automatically containing a time zone. The selected date also has a time of 00:00 by default. When the valueAsDate function converts the time-zoned date to UTC, it does so by subtracting the time zone offset from the date time. When the system time zone is greater than GMT+0, the offset gets subtracted from 00:00 (the time of the selected date), which in turn changes the date to the previous day.

* What is the change?

Before changing the value of input type="date" on mobile devices, we convert the date from time-zoned to UTC.

* Does this change impact existing behaviors? If so how?

Mobile datepicker now works correctly for mobile devices in time zones greater than GMT+0.

## Implementation Plan

Convert time-zoned date to UTC by subtracting the time zone offset.

* What parts of the code are affected?

clr-angular\forms\datepicker\date-input.ts : updateInput()

* Will you introduce new services, components or directives?

No

* Will you need to refactor existing Clarity code?

Yes

## Conclusion

Fix is a one-liner that I have already implemented by mistake while solving a different issue -> No time at all.

**Comment by martinbrom** [comment]
This is closed by #3993.
