### ISSUE TITLE
Doc site shows versions in bad order on Firefox

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#3233]
## Describe the bug

What's new left side panel with versions shows bad order with v0.10 as latest version. Seems to only happen on Firefox (I am on Windows and may matter)

## How to reproduce

Firefox 65 or 66 on Windows

## Expected behavior
v2 should be latest. Works on other browsers

## Versions

**App**

Clarity doc site

**Device:**

Firefox 65/66

## Additional notes

Works fine with IE11, Edge and Chrome

**Comment by coryrylan** [comment]
Looking at this it seems to happen in safari as well.

**Comment by rbirkgit** [comment]
The order got updated, but it's not right. I would expect 0.13 to come under 1.0 and not at the bottom.

**Comment by coryrylan** [comment]
I should of caught this. Reopening to fix.
