### ISSUE TITLE
Icon request for a FC HBA

### ISSUE THREAD

**Issue by abbyhtml** [vmware/clarity#3237]
FC HBA stands for Fibre Channel Host Bus Adapter. A FC HBA connects a ESXi host server with a storage array or a Fibre channel switch. It is refereed as "storage adapters" under configure-> storage section of vSphere.

vSphere client shows the FC HBA found on a ESXi host as below:
![image](https://user-images.githubusercontent.com/40457657/54900629-01c52a80-4efa-11e9-9bb6-f9ae45a2e1eb.png)

We are developing a vSphere plugin than can discover and manage FC HBA found on a ESXi host. We would like to have a icon to represent it from clarity.

In the icons technology section we find icons for network switch and storage but none for storage adapters. The only icon resembling is that of memory which ideally should not be used but visually looks most similar. 

FC HBA looks like this:
![image](https://user-images.githubusercontent.com/40457657/54901099-7c427a00-4efb-11e9-808f-86841b428535.png)

**Comment by lil-kim** [comment]
Hi @abbyhtml 
Icon requests for VMware products should be requested via a JIRA ticket.
https://confluence.eng.vmware.com/display/DESIGN/How+to+request+icons+and+graphic+assets
If the icons are good candidates for the Clarity open source icon library, I will add them.
Thanks. Closing this issue.

**Comment by abbyhtml** [comment]
The link provided does not work. Can you point me on how to open a JIRA ticket?

**Comment by hippee-lee** [comment]
@abbyhtml - The link works for me. Are you accessing confluence via VPN or an internal network?

**Comment by abbyhtml** [comment]
Hi lee,

I am not a VMware employee. I work for a VMware partner company. I do not have access to JIRA or this website https://confluence.eng.vmware.com/.

**Comment by hippee-lee** [comment]
Sorry @abbyhtml - I mis-understood. 
@lilia, is there enough info in the description for us to consider this? It seems like the _Fibre Channel Host Bus Adapter_ is the general thing being described here and since its not specific to VMware it might go into the Technology set.

**Comment by lil-kim** [comment]
Apologies for the misunderstanding, @abbyhtml. I will add this to our next release of Clarity icons.
issue #3309
