### ISSUE TITLE
[CORE] Clean up the demos in src/app

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#324]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Our main project should have a `sandbox/` folder in `src/` next to `app/` and `clarity-angular/`.
It should contain fewer examples, mostly all-encompassing ones, rather than splitting everything per feature as we used to do when the demos where exported to the website. A component's example should now be one (maybe a couple in some cases) full-blown example showcasing all the features, that serves both as starting point for people wanting to work on a component, as an easy way to reproduce a bug, and as reference for CSS regression testing.

In particular, these examples in the sandbox are now targeted at Clarity contributors, not at consumers looking for documentation. Take some liberties, allow yourself to document by commenting parts of the code, ...

### Actual behavior

The current demos in `src/app/` are still the ones we used on the website before, and as such are split down to atomic features. For instance, the [current buttons demo](https://github.com/vmware/clarity/tree/master/src/app/buttons) is now completely overkill.

**Comment by youdz** [comment]
@jeeyun: I'll let you confirm if this seems reasonable to you, and maybe provide some details or warnings about build changes that would need to be implemented. Feel free to unassign yourself after this and remove the `Review Needed` label, we'll decide at that point who's going to work on this.

**Comment by jeeyun** [comment]
This sounds reasonable. I think this should be done in stages until we finalize our strategy for CSS regression testing. My proposal:

1. Create `sandbox/` folder with one demo component per component. The demo component still contains variations of a given component to cover CSS regression, but no documentation texts. Think one kitchen sink page per component.
2. Port over the CSS regression tests to now test off the `sandbox` application.
3. Remove the `app/` folder from the project.

**Comment by mathisscott** [comment]
@jeeyun / @adityarb88 : Is this still something we want to do?

Please close if not.
