### ISSUE TITLE
Part of Hide/Show feature in data grid gets cut off

### ISSUE THREAD

**Issue by krishnakarthik9** [vmware/clarity#3244]
## Describe the bug
I followed this documentation: https://clarity.design/documentation/datagrid/hide-show to create a data grid with option to hide/show columns.

When there is only single row then part of Hide/Show list gets cut off as shown in the screenshot. 
![clarity](https://user-images.githubusercontent.com/12638352/54973655-cccadd80-4fb6-11e9-926e-f109fcbb57b3.png)

## How to reproduce

Create a data grid with just one row and click on Hide/Show toggle option.

stackblitz urls:
APP: https://clarity-light-theme-v1-0-eewwkl.stackblitz.io/
Editor: https://stackblitz.com/edit/clarity-light-theme-v1-0-eewwkl

## Expected behavior

Hide/Show list should not get cut off.

## Versions

**App**

* Angular: 6
* Node: 10.15.3
* Clarity: 1.0

**Device:**

* Type: Dell
* OS: Ubuntu 18.04 VM on windows 10
* Browser firefox
* Version 66.0

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
There is an open issue to address popovers in the datagrid. It is in active development. Please subscribe [here](https://github.com/vmware/clarity/issues/2923) to follow progress.
