### ISSUE TITLE
Circle icon does not support is-solid class

### ISSUE THREAD

**Issue by drourke2** [vmware/clarity#3246]
## Describe the bug

The circle icon no longer works with 'is-solid' class.

## How to reproduce

<clr-icon shape="circle" class="is-solid is-info" size="8"></clr-icon>

1.  Add clr-icon to any project and view in browser.

## Expected behavior

The circle icon should have solid center filled with color.

## Versions

**App**

* Angular: 7.2.9
* Node: 10.14.2
* Clarity: 1.1.2

**Device:**

* Type: MacBook Pro
* OS: macOS (10.14.3)
* Browser Chrome
* Version 73.0.3683.86

## Additional notes

The circle icon supported 'is-solid' class in version 1.1.1.

**Comment by drourke2** [comment]
Is this fixed?  I just pulled down the latest version 1.1.3 of @clr/icons and the circle still does not support solid.

**Comment by hippee-lee** [comment]
It is in v2 but has not been backported to the v1 branch.
https://stackblitz.com/edit/issue-3246-filled-circle-icon

**Comment by drourke2** [comment]
Since it was working in v1.1.1, I would have thought it would have been patched in v1 before v2.  I see now that it's scheduled for v1.1.4.  Thanks!

**Comment by DwieDave** [comment]
Updating only @clr/icons to the @next version did fix the error for me despite the warnings.

**Comment by asual** [comment]
Since upgrading to 2.0.1 we started seeing the following error in Chrome and it seems related to this fix:

> Error: <path> attribute d: Unexpected end of attribute. Expected number, "…,0,0,1,18,34ZM18".

**Comment by Jinnie** [comment]
@asual Confirm. The "M18" at the end is not needed. Will spawn an issue for this and create a quick fix. Thanks!
