### ISSUE TITLE
Removal of 2.0 deprecations

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3248]
We need to remove the following:

* [x] Deprecated grid file, and any lingering uses of old grid
* [x] Audit component templates for old grid classes and make sure we have scss parity (matt)
* [x] Deprecated old form module (Cory)
* [x] Old form styles (Cory)
* [x] Remove examples of `clr-checkbox` in button groups (Cory)
* [x] Remove deprecated bootstrap sass (Cory)
* [x] Remove old datepicker layout option (Matt)
* [x] Unnecessary gemini tests (Matt)

**Comment by coryrylan** [comment]
Have majority of the deprecated forms module and styles removed. Everything builds but I need to go back and check all three projects and gemini for any possible issues.

**Comment by coryrylan** [comment]
Is the older `.toggle-switch` part of the old forms deprecation? I see that the new component was added a couple of months ago.
