### ISSUE TITLE
Update the UI Template and post to the site

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#325]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
An updated version of the UI template including fixes from other issues
Include new icons and variants

### Actual behavior
Minor errors in colors, sizes

**Comment by reddolan** [comment]
Template updated 
[Clarity-UI-Template-0.8.2.sketch.zip](https://github.com/vmware/clarity/files/702645/Clarity-UI-Template-0.8.2.sketch.zip)

**Comment by jaffoneh** [comment]
Assigning to @hippee-lee to add to the website as part of the release next week.

**Comment by hippee-lee** [comment]
Closing this. 
See this commit for changes: https://github.com/vmware/clarity/commit/be79ee0c8c3766e5d4605385080b9517e4014206https://github.com/vmware/clarity/commit/be79ee0c8c3766e5d4605385080b9517e4014206
