### ISSUE TITLE
[Responsive] Clarity header's hamburger icon is not created if clr-header is initialized after ResponsiveNavigationService

### ISSUE THREAD

**Issue by jooskim** [vmware/clarity#3254]
## Describe the bug

The hamburger icon should appear when the viewport width drops down to a certain point regardless of whether Clarity header has initialized prior to `ResponsiveNavigationService` or not.

## How to reproduce

https://clarity-rvfyyw.stackblitz.io

1.  Go to the link above
2.  Resize your browser horizontally to the point the sub navigation bar will disappear
3.  See the hamburger button does not show up and the default home icon is still present

## Expected behavior

As you resize the window horizontally the banner icon will disappear and the hamburger icon should show up. See the correct behavior found in the link below:

https://clarity-ykwjnz.stackblitz.io

## Versions

**App**

* Angular: 7.2.0
* Node: 8.12
* Clarity: 1.0.5

**Device:**

* Type: MacBook Pro
* OS:  macOS 10.14
* Browser Chrome
* Version 73

## Additional notes
Instead of using `Subject` as found in `ResponsiveNavigationService` (https://github.com/vmware/clarity/blob/4def207215354cb55330ec22526994f27b41603f/src/clr-angular/layout/nav/providers/responsive-navigation.service.ts#L16), using `ReplaySubject` will ensure `clr-header` will be able to listen to the events that had already fired before Clarity header was initialized.

Credit: Etienne Le Sueur

**Comment by gnomeontherun** [comment]
I can see the issue, and that might be workable solution. Either way, we need to dig a little deeper and make sure we get a unit test to verify and fix this.
