### ISSUE TITLE
Expandable rows in a datagrid component renders slow when expanding and produces console errors when expanded/collapsed rapidly

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3255]
## Describe the bug
Expanding/collapsing an expandable row in the datagrid is very slow even though there are only 50-100 records. I also tried to stress test the expand/collapse by doing it rapidly multiple times and it produces console errors. The data grid still works, though.

![image](https://user-images.githubusercontent.com/1977391/55121083-c2821e00-5133-11e9-8684-b0185ce7fd38.png)

**Comment by hippee-lee** [comment]
**Please provide an isolated (https://stackblitz.com/@clr-team) reproduction.**

Based on what you have described I tried to recreate it but did not observe what you have.
Here are the steps I took

1. Go to https://clarity.design/documentation/datagrid/expandable-rows
2. Expand several rows (seems normal to me -> no console errors)
3. Click as fast as I could on one row (seems normal to me -> no console errors)

**There are several reasons a stackblitz is important** 
1. It gives an isolated example of the issue that can be looked at and used to triage and identify where slowness or console errors are coming from
2. The website demos are part of a much larger and more complicated application so its hard to be sure where the issue you are experiencing originates
3. The recreation steps provided in this case are very hard to repeat _in the same way_. Having the isolated stackblitz helps narrow down what specifically triggers the console errors (this is especially important when clicking fast on my computer doesn't give me the console errors).

**Comment by whizkidwwe1217** [comment]
@hippee-lee Here's the StackBlitz: https://stackblitz.com/edit/clarity-light-theme-v1-0-mrno4n
The console errors don't show up in a consistent timing but it always produces console errors like 3-10 seconds of clicking fast and expanding/collapsing rows is undeniably slow.
![image](https://user-images.githubusercontent.com/1977391/55173684-1b46ca80-51b7-11e9-8ff0-b2fcde5756f3.png)

My Chrome version is:
Google Chrome is up to date
Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by whizkidwwe1217** [comment]
I think the error happens somewhere in this code?
![image](https://user-images.githubusercontent.com/1977391/55174533-98bf0a80-51b8-11e9-9e29-74a54938def2.png)

**Comment by hippee-lee** [comment]
I do observe the expanded content bleeding on top of the row below it. That seems to be what you are describing as _ undeniably slow._. In this case, would there still be an issue for you if the content was 'hidden' underneath the row below it?  

For the console error issue, I am not able to generate console errors with fast clicking. I updated to latest chrome: Version 73.0.3683.86 (Official Build) (64-bit)
![fast-click-expand-row](https://user-images.githubusercontent.com/433692/55175081-df225400-513b-11e9-936b-1f3ff7926e1f.gif)
Do you have any more info that will help generate console errors?

**Comment by whizkidwwe1217** [comment]
@hippee-lee I was able to reproduce it even on a different machine but I don't know how to reproduce it with exact steps. I think it's all about timing. I'm thinking that the reason console errors are generated is due to either the **oldHeight** or the **newHeight** variable becomes undefined or null at some point.
![Untitled Project](https://user-images.githubusercontent.com/1977391/55207738-6a701800-5216-11e9-90aa-4f7c5e8c9c03.gif)

![image](https://user-images.githubusercontent.com/1977391/55207102-e026b480-5213-11e9-8b91-16164f20bd11.png)
As you can see in the warning logs, it complains about the height with a value of undefinedpx.
![image](https://user-images.githubusercontent.com/1977391/55207267-6511ce00-5214-11e9-800a-e2c7a7cd5dbd.png)
Although these errors are not really blocking anything nor breaking the grid functionality, it just that it's showing up in stress testing. I can just explain it to the QAs. It's okay to close this issue.

Regarding the slow collapse/expand, it really is very slow on my end. I think it's because I'm loading 200 records into the datagrid. As a workaround, I limit the records to 50 and used paging to reduce the memory footprint.

**Comment by hippee-lee** [comment]
Thanks for the followup. This information helps. We will get this into the backlog and prioritize it accordingly.

**Comment by mattmutt** [comment]
Similar or coincidental? patch proposed: https://github.com/vmware/clarity/pull/3229

**Comment by Jinnie** [comment]
Copying my comment from the above issue:

> Note: the animation hack class will probably soon be gone. I am currently working on refactoring of this approach. I will link this issue once I have a PR. Please be patient.
