### ISSUE TITLE
404 on datagrid docs page

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#3262]
## Describe the bug

When right clicking open new tab or hard land on the datagrid default documentation page you will get a 404.

## How to reproduce

For example in the documentation nav the link to the data grid in the nav is the following url:
https://clarity.design/documentation/datagrid

When clicked it redirects client side to:
https://clarity.design/documentation/datagrid/structure

If right clicked to open it does not redirect client side and causes a 404.

## Expected behavior

The url https://clarity.design/documentation/datagrid should probably be the default
url for the datagrid instead of a redirect to `/structure`.

## Versions
Latest documentation on https://clarity.design

**Comment by gnomeontherun** [comment]
Fixed this on the master branch.
