### ISSUE TITLE
How to tree shake Clarity Modules?

### ISSUE THREAD

**Issue by mohammedzamakhan** [vmware/clarity#3264]
## Summary
Currently, when I only use one module from the package, and analyze my bundle, I see that the whole clarity module is being included in my bundle. 

There should be a way to only include the modules that we require in the project
_Summary the request and address the questions as appropriate._

* What is the change?
* Why should it go in Clarity?
* Does this change impact existing behaviors? If so how?
* If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by coryrylan** [comment]
For your application can you list the following version information:
- Angular
- Angular CLI
- Clarity

Also to determine you bundle size / composition which tool are you using? There are a couple I know of such as [webpack bundle analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) and [source-map-explorer](https://github.com/danvk/source-map-explorer). If possible can you include a screenshot of your bundle graph if you are using one of these tools?

**Comment by coryrylan** [comment]
Some initial investigation it does look like there is some issue here. I'll post more details once I get some time to dig into this more.

**Comment by mohammedzamakhan** [comment]
Any updates @coryrylan?

**Comment by gnomeontherun** [comment]
Not yet, but the workaround is to import the specific modules you need.

**Comment by mohammedzamakhan** [comment]
@gnomeontherun I tried that and it didn't work! are you sure that solves the issue?!

**Comment by gnomeontherun** [comment]
This used to work that way, and the build would only include directly referenced items. It would help to provide a small reproduction in case we're looking at something differently than you are.

**Comment by mohammedzamakhan** [comment]
**Case 1: Using Clarity Module**

```
import { ClarityModule } from '@clr/angular';
@NgModule({
    ...
    imports: [
        ...
        ClarityModule
    ],
    ...
})
export class AppModule { }
```
results in 

<img width="605" alt="single module" src="https://user-images.githubusercontent.com/2327532/56627700-96f83380-660c-11e9-9bd8-428ccfd2c0bd.png">

**Case 2: Importing Individual Modules**
```
import {
  ClrDatagridModule,
  ClrWizardModule,
  ClrInputModule,
  ClrModalModule,
  ClrAlertModule,
  ClrIconModule,
  ClrTextareaModule,
} from '@clr/angular';

@NgModule({
    ...
    imports: [
        ...
        ClrDatagridModule,
        ClrWizardModule,
        ClrInputModule,
        ClrModalModule,
        ClrAlertModule,
        ClrIconModule,
        ClrTextareaModule,
    ],
    ...
})
export class AppModule { }
```

results in 

<img width="609" alt="individual modules" src="https://user-images.githubusercontent.com/2327532/56633527-29580180-6624-11e9-8725-d48d2b07af09.png">

**Comment by hippee-lee** [comment]
I looked into this and here is what I found. 

I created a new standalone project with angular cli (using the latest angular beta). It is here: https://github.com/hippee-lee/issue3264

I also used the [Angular Console](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console) tool integrated into VSCode for inspecting the package sizes and stats were generated via
```ng build issue3264-bundle-analysis --configuration=production --sourceMap=true --statsJson```

Here are some results for various use cases:

| Use Case  | Total Bundle Size  | clr-angular size |
| ------------- | ------------- | ------------- |
| No Clarity Module(s)  |326.2 kB  | n/a | 
| ClarityModule (nothing used in app)  | 413.4 kB  | 48.5 kB | 
| ClarityModule (simple datagrid) | 533.5kB | 100.7 kB |
| ClrDatagridModule (nothing used in app) | 411.7 kB | 47.7 kB |
| ClrDatagridModule (simple datagrid) | 531.7 kB | 99.9 kB |

I do see the following templates left in the bundle when its just `ClarityModule` or ClrDatagridModule` w/o anything being used in the app:

- clrdatecontainer.html
- clrpasswordcontainer.html
- clrdaypicker.html
- clryearpicker.html
- clrselectcontainer.html
- clrtextareacontainer.html
- clrinputcontainer.html
- clrcalendar.html
- clrdatepickerviewmanager.html
- clrmonthpicker.html
- clrday.html
- clrcheckboxwrapper.html
- clrradiowrapper.html

There are also a couple of aot compiled symbols after the radio wrapper that are really small.

**Comment by mohammedzamakhan** [comment]
I used source map explorer for my analysis

**Comment by coryrylan** [comment]
Using @hippee-lee project example it does look like tree shaking is working with the latest version of Angular. I made a modification to https://github.com/hippee-lee/issue3264 by importing only the Modal module.

```typescript
import { BrowserModule } from "@angular/platform-browser";
import { NgModule } from "@angular/core";

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";
import { ClrModalModule } from "@clr/angular";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    ClrModalModule,
    BrowserAnimationsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

I then use a modal successfully in my app template.

```html
<clr-modal [clrModalOpen]="true">
  <div class="modal-body">
    <p>But not much to say...</p>
  </div>
</clr-modal>
```

![Screen Shot 2019-04-24 at 3 48 19 PM](https://user-images.githubusercontent.com/2021067/56692805-9d3bed80-66a8-11e9-9185-4377d9e95a28.png)

The bundle report using this command
`npx source-map-explorer dist/issue3264-bundle-analysis/main-es2015.*.js` produces the following:

![Screen Shot 2019-04-24 at 3 47 54 PM](https://user-images.githubusercontent.com/2021067/56692826-a4fb9200-66a8-11e9-9ceb-1cc243ac9e78.png)

The application only pulls in the modal component module at 6kb. When it comes to the datagrid it uses other clarity components so you will see the forms module get pulled into the bundle.

Angular treeshakes to the module level. It cannot treeshake efficiently down to the individual components as the treeshaker cannot assume that a component registered to a module doesnt cause side effects. It assumes if it is imported into the file then it should be included into the bundle.

The only way to get treeshaking working with individual components today is to give each component its own `NgModule` and import each component module (See Angular Material for this strategy). In upcoming versions of Angular once Ivy is complete `NgModule` will be optional allowing better tree shaking options.
