### ISSUE TITLE
Inline spinner icon should be offered in a smallest size

### ISSUE THREAD

**Issue by mattmutt** [vmware/clarity#3265]
## Summary

Currently the semantic ranges for a spinner are large, medium and small. However UX rules dictate that the iconography sizing matches the normative size of other Clarity icons. Currently that standard appears to be 16px. For some reason the spinner abides by multiples of 18, roughly +12.5% difference across. That means any forms having inlined spinners will have an oddly larger spinner in relation to other static icons.

Question is, should the sizing multiple of a spinner align to Clarity icons? If so how to achieve that, without tampering CSS classes?

* Propose some way to influence a smaller semantic for the spinner. Following the Bootstrap convention, that would be `.spinner-xs`

* Consistency for alignment within forms where other static Clarity icons are positioned

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

Attached is a form workflow illustrating the alignment. See the dotted red box in comparison to another Clarity icon - sized with at a standard 16 x 16.

![smallest-spinner-icon-too-large](https://user-images.githubusercontent.com/8688570/55364130-56394e80-5494-11e9-9f01-c16a69110374.png)

## Workarounds
Yes, hardcode width,height in our application's CSS for this use case.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
