### ISSUE TITLE
Remove inline font from CSS

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#3269]
We can help improve the initial render of Clarity based apps by 1 or more seconds by removing the current font set from the inline CSS and use a seperate font file. Ideally this should be done when we update to the new custom font. Things to note:

- Should take advantage of new font file formats like woff2 [more details](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization)
- CSS font family should use appropriate font display such as `swap` or `fallback` [more details](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#using_font-display) 
- We should update the Angular schematic to automatically move the font files into the application assets

**Comment by mathisscott** [comment]
@coryrylan 
This needs to wait until after our path on Metropolis is clear. It would be unnecessary re-work otherwise. That said, it definitely needs to be done.

Do you think this can be accomplished without breaking changes?

**Comment by coryrylan** [comment]
I think this would be a breaking change because we would require them to update the `angular.json` to copy the new font files over when they deploy the application. That can be automated with a schematic for new projects. You could make one for upgrading but technically a breaking change since they are having make a minor configuration change in an existing project.

**Comment by mathisscott** [comment]
So 3.0 milestone it is.

**Comment by gnomeontherun** [comment]
Handled this by loading files from clarity city font package.
