### ISSUE TITLE
Remove inline SVG from CSS

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#3270]
Tracking case for eventually removing inline SVG from CSS. By removing inline SVG from CSS we can use clr-icons. This will improve render performance as well as removing duplication of the svgs. Non clr icon based images can be moved into assets by the clr add schematic.

- [ ] https://github.com/vmware/clarity/blob/ad0773ef6e142a762745b19dfcb53f3ad4afecc7/src/clr-angular/image/_icons.clarity.scss

- [ ] https://github.com/vmware/clarity/blob/e143b8590b8682caaecb86f5bc17ad691700f63d/src/clr-angular/layout/_variables.login.scss

**Comment by mathisscott** [comment]
Is this a duplicate of #2155 ?

I'm fine with going one or the other. But they do seem redundant.

**Comment by coryrylan** [comment]
Closing as duplicate
