### ISSUE TITLE
 ClrForm.markAsTouched() does not work in angular 7

### ISSUE THREAD

**Issue by julgon2012** [vmware/clarity#3272]
## Describe the bug

I can not make an input show the error (it turns red) by executing the sentence  ClrForm.markAsTouched() or another similar

## How to reproduce

login.component.html

    

    <div class="clr-row">
      <div class="clr-col-12 clr-col-md-6 clr-col-xl-4 mx-auto">
        <div class="card">
          <div class="card-header">
            <clr-icon shape="user" size="24"></clr-icon>
            <h5 class="pl-1 font-weight-bold d-inline">Móvil - Login</h5>
          </div>
          <div class="card-block">
            <div class="card-text">
              <form clrLayout="vertical" clrForm [formGroup]="form" (ngSubmit)="onSubmit(form.value)">
                
                <clr-select-container>
                  <label>Tipo de documento</label>
                  <select clrSelect formControlName="tipDocum">
                    <option value="DU">DOCUMENTO NACIONAL</option>
                    <option value="CT">CUIL / CUIT</option>
                    <option value="PA">PASAPORTE</option>6
                  </select>
                </clr-select-container>
                
                <clr-input-container>
                  <label for="numDocum">Nro de documento</label>
                  <input clrInput type="number" formControlName="numDocum" 
                            placeholder="Número de documento" />
                  <clr-control-error *clrIfError="'required'">
                        Debe ingresar su número de documento</clr-control-error>
              <clr-control-error *clrIfError="'min'">Ingrese un mínimo de 5 dígitos</clr-control-error>
              <clr-control-error *clrIfError="'max'">Ingrese un máximo de 13 dígitos</clr-control-error>
            </clr-input-container>

            
            <clr-input-container>
              <label for="password">Clave de acceso</label>
              <input clrInput type="password" formControlName="password" placeholder="Clave de acceso" />
              <clr-control-error *clrIfError="'required'">Debe ingresar su clave de acceso</clr-control-error>
            </clr-input-container>
            
            <button [disabled]="submitted && form.invalid || loading" class="btn btn-danger mt-2">Validar</button>
            <div *ngIf="loading">
              <img              src="miimagen.jpg" />
            </div>
            <div class="text-center mt-2" *ngIf="!loading">
              <span>
                <a routerLink="/forgot-pass">¿Olvidó su clave?</a>
                <span class="pl-2 pr-2">|</span>
                <a routerLink="/sing-in">Regístrese</a>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row mt-1">
  <div class="col col-sm-6 offset-sm-3 col-lg-4 offset-lg-4">
  </div>
</div>

login.component.ts

    import { Component, OnInit } from '@angular/core';
    import { FormBuilder, FormGroup, Validators } from '@angular/forms';
    import { Router } from '@angular/router';
    import { ValidateUserService } from '../../services/user/auth/validate-user.service';
    import { ClrForm } from '@clr/angular';

    @Component({
       templateUrl: './login.component.html',
       styleUrls: []
    })
    export class LoginComponent implements OnInit {
       form: FormGroup;
       submitted = false;
       loading = false;

   constructor(
      private fb: FormBuilder,
      private usrAuth: ValidateUserService,
      private router: Router
       ) { }
       ngOnInit() {
          // borro el token anterior
          window.sessionStorage.removeItem('MovilUserToken');

          this.form = this.fb.group({
             tipDocum: ['DU', [Validators.required]],
             numDocum: [
                '',
                [
                   Validators.required,
                   Validators.min(10000),
                   Validators.max(9999999999999)
                ]
             ],
             password: ['', [Validators.required]]
          });
       }
       get f() {
          return this.form.controls;
       }

       onSubmit(formValue: any) {
          this.submitted = true;

          if (this.form.invalid) {
             this.form.controls.numDocum.markAsTouched();
             return;
          }
          this.loading = true;
          const json = `{user:'${formValue.tipDocum}${formValue.numDocum}',
                       pass:'${formValue.password}'}`;

          this.usrAuth.getData(json).subscribe(
             entries => {
                this.evaluateResponse(entries);
             },
             error => {
                alert('error');
             }
          );
       }
       evaluateResponse(resp: string) {
          const jsonRes = JSON.parse(resp);
          if (jsonRes.Status !== 0) {
             alert(jsonRes.Error);
             this.loading = false;
             return false;
          }

          window.sessionStorage.setItem(
             'MovilUserToken',
             jsonRes.Datos.UserToken
          );
          this.router.navigate(['home']);
       }
    }

in the Chrome debug you see that the ng-untouched directive changes to ng-touched, but the component does not add the clr-error class to the div that wraps the input object.

the example given in the documentation produces an error.

    export class ReactiveFormsDemo {
        @ViewChild(ClrForm) clrForm;
        exampleForm = new FormGroup({
            sample: new FormControl('', Validators.required),
        });
        submit() {
            if (this.exampleForm.invalid) {
                this.clrForm.markAsTouched();  // this produces the error
            } else {
                // Do submit logic
            }
        }
    }

## Versions

**App**

* Angular: [7]
* Node: [10.15.3]
* Clarity: [1.0]

**Device:**
PC with Windows 7

* Type: [PC]
* OS: [Windows 7]
* Browser [chrome ]
* Version [73.0.3683.86 (Build oficial) (64 bits)]

**Comment by Kangcor** [comment]
I recommend removing any info from your company, like the <h5> card-header

**Comment by gnomeontherun** [comment]
This was recently merged and is for Clarity v2, so congratulations on finding it! This is unreleased, and I shouldn't have published it to the website yet. The current API is `ClrForm.markAsDirty()` which will be deprecated and replaced with `ClrForm.markAsTouched()` in 2.0.

I'm working on a few details to make this fully correct, but v1 documentation will live here https://v1.clarity.design/.
