### ISSUE TITLE
Datepicker removing typed text

### ISSUE THREAD

**Issue by Luke20013** [vmware/clarity#3275]
When using the datepicker, I want to be able to **select a date, and then type something extra** into the text box
When running locally this works perfectly, but on the deployed instance, the **typed text is removed** when the date format is in the box.
The same problem can be experienced in the [datepicker documentation](https://clarity.design/documentation/datepicker)
I have tried with both the input type as "date" and "text"

**Comment by Luke20013** [comment]
Actually it is happening locally now too

**Comment by hippee-lee** [comment]
The datepicker only projects labels and the `clrDate` directive into the component templates. Whats happening is that there is `ng-content` slot for angular to put the text into. 
The scope of its behavior is limited to picking dates. 

Closing as something that the datepicker was not designed to support.

**Comment by Luke20013** [comment]
@hippee-lee This did work in the 1.0.4
So it must be happening when the input gets set to null in the 1.0.5 changes
