### ISSUE TITLE
"No provider for LayoutService" when using `clrLayout="vertical"`

### ISSUE THREAD

**Issue by MichaelLangbein** [vmware/clarity#3278]
Hello!
This is my first bug-report - hope everything is in order. Thanks in advance for your help!

## Describe the bug

When using `clr-tabs` with `clrLayout="vertical"`, an error is thrown: 

> ERROR Error: StaticInjectorError(AppModule)[ClrLayout -> LayoutService]: 
  StaticInjectorError(Platform: core)[ClrLayout -> LayoutService]: 
    NullInjectorError: No provider for LayoutService!

## How to reproduce

[Stackblitz](https://stackblitz.com/edit/clarity-light-theme-v1-0-8hbgqg)
[Github](https://github.com/MichaelLangbein/vertivalTabBugReport)

1.  `ng new verticalTabsDemo`
2.  `cd verticalTabsDemo` 
3.  `ng add @clr/angular`
4.  in `app.component.html`, add this code (copied directly from [the documentation](https://clarity.design/documentation/tabs)): 
  ```
<div class="main-container">
  <div class="content-container">
      <div class="content-area">
        <clr-tabs  clrLayout="vertical">
         <clr-tab>
             <button clrTabLink id="link1">Tab1</button>
             <clr-tab-content id="content1" *clrIfActive>
             ...
             </clr-tab-content>
         </clr-tab>
         <clr-tab>
             <button clrTabLink>Tab2</button>
             <clr-tab-content *clrIfActive="true">
             ...
             </clr-tab-content>
         </clr-tab>
        </clr-tabs>
      </div>
  </div>
</div>
```
5.  See error: 
```
ERROR Error: StaticInjectorError(AppModule)[ClrLayout -> LayoutService]: 
  StaticInjectorError(Platform: core)[ClrLayout -> LayoutService]: 
    NullInjectorError: No provider for LayoutService!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:8896)
    at resolveToken (core.js:9141)
    at tryResolveToken (core.js:9085)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:8982)
    at resolveToken (core.js:9141)
    at tryResolveToken (core.js:9085)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:8982)
    at resolveNgModuleDep (core.js:21218)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:21907)
    at resolveDep (core.js:22278)
```

## Expected behavior

The tabs should show up.

## Versions

**App**

* Angular: [~7.2.0]
* Node: [v8.10.0]
* Clarity: [1.1.2]

**Device:**

* Type: [Desktop]
* OS: [Ubuntu 18]
* Browser [chrome]
* Version [Version 73.0.3683.103 (Official Build) (64-bit)]

**Comment by hippee-lee** [comment]
I think the bug is because we do not export `TabsLayout` enum and its used here: https://github.com/vmware/clarity/blob/master/src/clr-angular/layout/tabs/tabs.ts#L74

@Jinnie - can you confirm? If it is, I'd rather not expose the TabsLayout enum unless that is the best way to handle this.

**Comment by Jinnie** [comment]
This error comes from the ClrLayout directive of the forms trying to be applied.
That's because the Vertical Tabs are a v2 feature. Our docs have been updated too early it seems!?

**Comment by kefengwei** [comment]
Hello, i have try. The v2 have the same problem.

**Comment by Jinnie** [comment]
It's not in the beta, I guess.
After the Vertical Tabs commit, the clrLayout directive has a more specific selector and won't be applied on the tabs. Please, don't use the Vertical Tabs yet. Sorry for the inconvenience.
