### ISSUE TITLE
Asynchronously loaded column definitions not displayed, if data grid is empty

### ISSUE THREAD

**Issue by tobixdev** [vmware/clarity#3281]
## Describe the bug

In our project we have an Angular component which renderes a data grid based on asynchronously loaded meta information (e.g. columns for the data grid). This works fine, if there are rows to display. 

If the data grid is empty and the column definitions have been loaded from the service, the additional columns will not be displayed.

## How to reproduce

This [Stackblitz](https://stackblitz.com/edit/clarity-data-grid-asynchronous-columns?file=src%2Fapp%2Fapp.component.html) reproduces the error using a JavaScript timeout.

As shown in the example above the empty table does not display the additionally loaded columns. Columns which are not loaded asynchronously will be shown (see "Fixed Column" in example).

## Expected behavior

The columns should also be visible in the empty table. The behavior should be consistent and not depend on the loaded rows.

## Versions

**App**

* Angular: 7.2.5
* Node: I don't know on which node version the StackBlitz runs, but in our project we use 10.15.3
* Clarity: 1.1.2

**Device:**

* Type: Desktop PC
* OS: Windows 10
* Browser: Tested on Chrome, Firefox, Edge
* Version: Chrome (73.0.3683.103), Firefox(57.0), Edge (41.16299.1004.0)

## Additional notes

The columns will be displayed, if `*clrDgItems` is used instead of `*ngFor` for column iteration. But I don't think this is the intended way, as it is reserved for row iteration (I think). Furthermore the "data grid empty image" will not be displayed, which may be a separate issue, if both ways should offer consistent behavior in that regard.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
