### ISSUE TITLE
Recursive lazy-loaded TreeView is broken in Clarity 1.1.2

### ISSUE THREAD

**Issue by RoyJacobs** [vmware/clarity#3284]
## Describe the bug

When opening an expandable node in a recursive lazy-loaded TreeView an error is thrown and logged in the console:

```Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: true'. Current value: 'ngIf: false'.```

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v1-0-vppqhq
2.  Click on node `b` to expand it
3.  See error in console

## Expected behavior

No error in the console.

## Versions

* Clarity: 1.1.2

## Additional notes

This issue does not occur in Clarity 1.1.1. I assume this is related to either https://github.com/vmware/clarity/pull/3211 or https://github.com/vmware/clarity/pull/3227 (looking at the changelog of 1.1.2)

**Comment by Shijir** [comment]
Yes, I see an error in your stackblitz. But that error is totally different than what you are describing above. It's asking you to define your `getChildren` parameter function.

**Comment by RoyJacobs** [comment]
Argh, sorry. I must have saved to the wrong StackBlitz. Will reopen when I get the repro up and running again.

**Comment by RoyJacobs** [comment]
@Shijir I've updated the Stackblitz. Can you reopen the issue? I've narrowed the issue down to returning promises from the `getChildren` call.

**Comment by RoyJacobs** [comment]
I'll just create a new issue.
