### ISSUE TITLE
Add an option to disable hardcoded height on datagrid

### ISSUE THREAD

**Issue by SethTompkins** [vmware/clarity#3288]
The method `computeDatagridHeight` attempts to calculate and hardcode a height onto the main datagrid element in order to solve an IE11 flexbox bug.

https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/render/main-renderer.ts#L140-L145

This specific use case may be useful in some instances, but if you are utilizing flexbox properly all the way down the DOM tree then this height hack is not needed. In those cases it is preferred to not have this bit of extra styling as this height value could potentially get out of sync with the current state of the DOM as the only place the calculation occurs is in the `ngAfterViewChecked` lifecycle hook.

It would be excellent if we could get an input property to the datagrid that allowed us to simply switch off this behavior as needed.

**Comment by hippee-lee** [comment]
Can you provide more context about your use case for adding this feature? 

We do not always add height to the datagrid. I believe it is only added when there is pagination. Early on we got feedback from users that the _jumping_ that the bottom of the datagrid did when the last page of items did not have the full number of items in it for display. 

Take a look here, I've got two datagrid, the basic one w/o pagination doesn't get its height set. 
I'm not opposed to adding an @Input for this but I do want to understand the use-case it will support.

**Comment by jvitorino** [comment]
I've also run into this.  We have controlled the size of the grid ourselves and we're using flexbox and would like the grid to shrink when other content on the page expands.  With the height being set explicitly, this breaks our layout when we enable pagination.

**Comment by hippee-lee** [comment]
Can you create an example stackblitz so I can see what you are doing?

**Comment by jvitorino** [comment]
https://angular-ezsdxc.stackblitz.io/ shows the issue where the grid doesn't shrink when the collapsible div at the top of the window is expanded.  when the pagination component is removed, the grid shrinks since the explicit height style isn't added.

**Comment by Jinnie** [comment]
The `DatagridMainRenderer` seems to be setting the height explicitly and only once, on `AfterViewInit`.
Currently a workaround could be to explicitly set the datagrid height to 100% of it's container:
```
clr-datagrid {
  height: 100% !important;
}
```
But we need to check if we can come up with a better solution.

**Comment by jvitorino** [comment]
thank you, I thought that I had tried that but I must not have since it's working as a workaround.

**Comment by dkanev** [comment]
Could you provide other solution then the workaround which use !important?
Using ! important is bad practice and should be avoided.

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#:~:text=Using%20!,greater%20specificity%20will%20be%20applied.

**Comment by mathisscott** [comment]
@dkanev 
Instead of using `!important` just up the specificity of the CSS selector.

**Comment by dkanev** [comment]
@mathisscott  According to the specification the !important is the way to override  inline style.

https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity  :
A) Overriding inline styles
Your global CSS file that sets visual aspects of your site globally may be overwritten by inline styles defined directly on individual elements. Both inline styles and !important are considered very bad practice, but sometimes you need the latter to override the former.
In this case, you could set certain styles in your global CSS file as !important, thus overriding inline styles set directly on elements.


The more specific CSS selectors doesn't help in this case, I tested it and it doesn't work or I am missing something.
Could you give me example how this can be done.

Thanks.

**Comment by mathisscott** [comment]
@dkanev 
Ah, yes. You are right. I forgot that the datagrid has to set the height on the element using the style attribute.

So it seems that, while not a general best practice, using `!important` in your custom CSS here is at least the recommended course of action?

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support, and we have recently dropped IE11 support as of the end of 2020 for any version of Clarity. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but there is a workaround that can help address this case.
