### ISSUE TITLE
Additional common Text Edit icons

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3296]
## Summary

_To help us better understand the purpose and role of icons, please provide us  
as much detail as possible. You may request an icon without specifying a specific
shape, but please detail the purpose and use cases._

* What are the icons?
1. Strikethrough
![image](https://user-images.githubusercontent.com/1977391/56088932-e62bbf00-5ebc-11e9-98f9-34ccff93855c.png)
2. Subscript
![image](https://user-images.githubusercontent.com/1977391/56088929-d14f2b80-5ebc-11e9-9a03-a860ec5774ed.png)
3. Superscript
![image](https://user-images.githubusercontent.com/1977391/56088930-de6c1a80-5ebc-11e9-8e29-eb63710fb3be.png)
4. Foreground color
![image](https://user-images.githubusercontent.com/1977391/56088924-b54b8a00-5ebc-11e9-9495-335ba6b5d0c7.png)
5. Highlight color
![image](https://user-images.githubusercontent.com/1977391/56088926-c4cad300-5ebc-11e9-841e-0d389915bd4d.png)
6. Indent (Increase Indention)
![image](https://user-images.githubusercontent.com/1977391/56088906-8208fb00-5ebc-11e9-9430-87a78f281fef.png)
7. Outdent (Decrease Indention)
![image](https://user-images.githubusercontent.com/1977391/56088918-92b97100-5ebc-11e9-9a92-163f624eec5d.png)

* What does the requested icons signify?
The name of the icons are self-explanatory.
* In which product(s) will this icon be used?
Rich Text editor component
## Use case

I'm building a rich text editor component in Angular using Clarity but it's lacking some common icons for basic editing

## Examples

_Are there any examples of similar icons with similar uses? Can you find any demos?_
See images in each item in the list above.
## Alternatives

_Is there an alternative for this at the moment, even if it is less than ideal?_

I can make my own svg icons but I think Strikethrough, Superscript, Subscript, Indent and Outdent are commons shapes that must be included in the Text Edit category of Clarity icons.

**Comment by mathisscott** [comment]
Closing as completed with designs in #3309. #3309 now covers the implementation/adding of these icons to the library.
