### ISSUE TITLE
DataGrid:  (clrDgRefresh) event triggered when the grid is being destroyed.

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#3297]
## Describe the bug

Data grid is triggering clrDgRefresh when the Grid/pagination is destroyed.
This seems to happen after https://github.com/vmware/clarity/pull/2841/files .
ngDestroy of ClrDatagridPagination resets page size which results into state change and thus calling clr-dgRefresh on grid.

For our case, we have a wrapper grid component that listens to this event and makes provides the data via API calls/some data source. Having refresh triggered while being destroyed is not expected as it leads to extra API calls and mismatch of data in case a same grid component is reused between views.

## How to reproduce

https://stackblitz.com/edit/grid-refresh-on-destroy

Steps to reproduce the behaviour:

1.  Go to "Tab1" that has data grid.
2.  Click on "Tab2" that has just static text.
3.  Check console. 
4.  Console will have logged refresh event triggered by the grid while moving to Tab2.

## Expected behaviour

Data grid should not cause refresh on being destroyed.

## Versions

**App**

* Angular: 7
* Node: 8.9+
* Clarity: 1.0.4

**Device:**

* Browser Chrome, FF
* Version Latest

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
We already have this issue open: #1099
Closing as duplicate.
