### ISSUE TITLE
where is the source code?

### ISSUE THREAD

**Issue by yanyixing** [vmware/clarity#330]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```
Where can I found the source code about your official website’s document https://vmware.github.io/clarity/documentation

**Comment by jaffoneh** [comment]
@yanyixing could you explain your question a bit more? Are  you looking for the Clarity source code or the source code for the documentation website itself? cc @mathisscott and @adityarb88

**Comment by yanyixing** [comment]
I need the source code for the  documentation website itself, thanks

**Comment by youdz** [comment]
The source code of our website is on `website` branch: https://github.com/vmware/clarity/tree/website
It is however not meant to be public or taken as an example, and is mostly undocumented. 
Could you tell us why you want to look at it, so we can maybe give you some advice?

**Comment by yanyixing** [comment]
@youdz thanks. I just want to consult the website's style

**Comment by jaffoneh** [comment]
Closing this one based on the last comment.
