### ISSUE TITLE
Recursive lazy-loaded TreeView is broken when using promises

### ISSUE THREAD

**Issue by RoyJacobs** [vmware/clarity#3300]
## Describe the bug

When opening an expandable node in a recursive lazy-loaded TreeView an error is thrown and logged in the console:

```Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: true'. Current value: 'ngIf: false'.```

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v1-0-vppqhq
2.  Click on node `b` to expand it
3.  See error in console

## Expected behavior

No error in the console.

## Versions

* Clarity: 1.1.2

## Additional notes

If I return an `Observable` from `getTreeChildren` instead of a `Promise`, it works correctly in 1.1.2 (simply remove the `.toPromise()` in `getTreeChildren`. In 1.1.1 both `Observable` and `Promise` responses work correctly.

This issue does not occur in Clarity 1.1.1. I assume this is related to either https://github.com/vmware/clarity/pull/3211 or https://github.com/vmware/clarity/pull/3227 (looking at the changelog of 1.1.2)

**Comment by RoyJacobs** [comment]
I can workaround it by not setting `[clrLazy]` to `true`, but this is a bit unfortunate since it now requires my whole tree to be loaded. For now it's okay, though.

**Comment by Jinnie** [comment]
It's because the flag for the `loading` spinner is set synchronously and then updated asynchronously in the model, which is outside of the Angular lifecycle handling. Typical EHCBIWC error.
I reproduced this with both a subscription and a promise on my environment.
The rxjs/of operator is actually running with a synchronous scheduler by default, that's why it "seems to" pass. If you use a real observable, or change the scheduler to an async one (like this:
```
  getTreeChildren = (item: Item) => {
    return of([
      { text: 'a', isExpandable: false },
      { text: 'b', isExpandable: true }
    ], asyncScheduler)
  }
```
), you will get the error with it, too.

**Comment by KANekT** [comment]
in 3.0.0-next.7 i have this error

use   root$ = new BehaviorSubject<[]>([]);

`    <clr-tree [clrLazy]="true">
      <clr-tree-node
        *clrRecursiveFor="
          let file of root$ | async;
          let i = index;
          getChildren: getChildren
        "
        [clrExpandable]="file.isNode"
        [(clrSelected)]="file.selected"
      >
        {{ file.title }}
      </clr-tree-node>
    </clr-tree>
`

`  getChildren = (node: TreeNodeModel) => {
    if (node.isNode) {
      return this.tree.filter((f) => f.parentId === node.id);
    } else {
      return null;
    }
  }`
