### ISSUE TITLE
redundant icon in icons documentation

### ISSUE THREAD

**Issue by fahrulalwan** [vmware/clarity#3306]
## Describe the bug

![Screenshot_14](https://user-images.githubusercontent.com/45678350/56352931-7722d300-61fa-11e9-950e-05683d65f6ec.png)
this is maybe not a bug, but for better documentation.
i dont know the differences between them, maybe it is better to remove one.

thanks :)

**Comment by Shijir** [comment]
Not redundancies, those are necessary icons aliases for some users.
