### ISSUE TITLE
Icons Vol15 

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#3309]
Epic for Icons Volume 15

Icons to be added for next icon release:
@Stela-Stamenkova , please refer to issue #3296 for examples and details for #1-7. These icons should be consistent in style, size & weight with the text-editing icon set currently in the Clarity library.
1. Strikethrough 
2. Subscript
3. Superscript
4. Foreground color
5. Highlight color
6. Indent (Increase Indention)
7. Outdent (Decrease Indention)
8. Storage adapter (FC HBA) Reference #3237
9. Label for BETA (similar to the "new" label icon in Clarity) - request from @reddolan

**Comment by Stela-Stamenkova** [comment]
Hello everyone!
[Icons_Vol15.zip](https://github.com/vmware/clarity/files/3185553/Icons_Vol15.zip)

I am attaching the icons, let me know how they work.
Best,
Stela

**Comment by reddolan** [comment]
Do we anticipate these making it into the 2.0 release?

**Comment by mathisscott** [comment]
@reddolan 
2.0 is in release candidacy. I think it's more likely these make it into 2.1. @gnomeontherun could add more info on that.

**Comment by reddolan** [comment]
@mathisscott thank you. I will plan to get these icons ready for the 2.0 resource work that aligns with #3258

**Comment by Stela-Stamenkova** [comment]
Hello,
I am adding them again per comment by Lilia.
Let me know how they work now.
[icons_Vol-15.zip](https://github.com/vmware/clarity/files/3198205/icons_Vol-15.zip)

**Comment by lil-kim** [comment]
Looks good, @Stela-Stamenkova. Thank you!

**Comment by reddolan** [comment]
Do we happen to know which categories each will reside in?

**Comment by reddolan** [comment]
I am assuming 
- Text Editing: Strikethrough, Subscript, Superscript, Foreground color, Highlight color, Indent, Outdent
- Technology: Storage adapter
- Essential: Beta

**Comment by lil-kim** [comment]
@reddolan Agreed!

**Comment by reddolan** [comment]
I see `beta-line`, but am not seeing `beta-solid`. Was this intentional? `new` has line and solid

**Comment by lil-kim** [comment]
Good catch @reddolan. @Stela-Stamenkova would you please add a solid version of "Beta"? Thank you!

**Comment by reddolan** [comment]
I am also seeing something weird with the `beta` one where the `TA` are not showing in the SVG when importing it into Sketch or Figma. Is there something different with the `TA`?

![image](https://user-images.githubusercontent.com/1858226/58045314-f441b080-7af6-11e9-837e-6c471bb887a8.png)

**Comment by reddolan** [comment]
Also, the names of Indent and Outdent are reversed

![image](https://user-images.githubusercontent.com/1858226/58049998-ff9ad900-7b02-11e9-8e37-937d7b34b669.png)

**Comment by Stela-Stamenkova** [comment]
Hello again!
Red, I am sorry, here they are again, with solid version and bug fixed.
[Vol15.zip](https://github.com/vmware/clarity/files/3201852/Vol15.zip)

**Comment by mathisscott** [comment]
Hi @Stela-Stamenkova 
The solid beta icon is a filled polygon with white text. That's not going to to work. What we need is a solid polygon with the text cut out. In Illustrator terms this would be a "subtract" merging of these paths, I believe. When you get that taken care of could you post the new solid beta icon here?

Thanks!

**Comment by mathisscott** [comment]
Once I get an updated beta-solid icon, I can move this into review.

**Comment by lil-kim** [comment]
@mathisscott,
Here's the corrected beta icon:
[beta_solid.svg.zip](https://github.com/vmware/clarity/files/3340771/beta_solid.svg.zip)

**Comment by abbyhtml** [comment]
Regarding the new icon added here "Storage adapter (FC HBA) Reference #3237".
Even after updating the icons to version 2.0.2 , I do not see the svg file for storage-adapter in the technology-shapes.zip. Is this not available yet?
The clarity website icons section is displaying the icon though.

![image](https://user-images.githubusercontent.com/40457657/61437001-aa8c0f80-a959-11e9-84d9-2503782b31db.png)

**Comment by mathisscott** [comment]
@abbyhtml 
The vol. 15 icons were merged into master last week. The website auto-updated and published the icons documentation. So while they are on the website, the icons have not been released yet. They will be available in 2.0.3. I would expect that release to happen next week.
