### ISSUE TITLE
Unable to override style of a `clr-control-container` in a component

### ISSUE THREAD

**Issue by sylvaingirardbe** [vmware/clarity#3313]
## Describe the bug

I'm unable to override the style of a `clr-control-container` in a component because it's not scoped to the component.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-zj2zkm

As you can see in the repro, I'd like the text input in the dropdown to be 100% width of the dropdown, which doesn't work at the moment without overriding global styles.

## Expected behavior

That the container is scoped correctly so that I can override styles in a component.

## Versions

**App**

* Angular: 7.2.0
* Node: 8.11.3
* Clarity: 1.0.5

**Device:**

* Type: HP ProBook
* OS: Windows 10
* Browser Chrome
* Version 73

**Comment by gnomeontherun** [comment]
I'm not clear what you mean about being 'scoped correctly', but you can always pierce into an Angular component using `::ng-deep`. Below is the CSS you would use in your component to override the input container internals. See https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

```
::ng-deep clr-input-container .clr-control-container {
  display: block;
  width: 100%;
} 
::ng-deep clr-input-container input {
  width: 100%;
}
```

**Comment by gnomeontherun** [comment]
Closing as answered.

**Comment by sambhav2612** [comment]
@genehynson this didn't work with `clr-select-container`. why's that?
