### ISSUE TITLE
Clarity documentation version dropdown doesn't show all versions

### ISSUE THREAD

**Issue by artemisclyde** [vmware/clarity#3320]
## Describe the bug
When going to https://clarity.design/documentation, Version V2 is automatically selected in the dropdown to the left. Version v2 is not shown anymore after selecting another documentation version though.

## How to reproduce
* Go to https://clarity.design/documentation.
* Select version v1 in the left dropdown.
* Click the dropdown again. v2 is not shown anymore.

![Clarity Design System   Documentation](https://user-images.githubusercontent.com/16636453/56724550-87333900-674b-11e9-86d3-fdf080100616.png)
![Clarity Design System   Documentation   T2abs](https://user-images.githubusercontent.com/16636453/56724553-88fcfc80-674b-11e9-9a9c-a9b64d0f8194.png)

**Comment by hippee-lee** [comment]
I know why this happens. I'll push out a fix for this soon.

**Comment by hippee-lee** [comment]
This will be fixed after the build deploys on Netlify.
