### ISSUE TITLE
Datagrid search filter is getting hidden, if there is only one search result

### ISSUE THREAD

**Issue by bhanupradeep7** [vmware/clarity#3328]
This is a regression issue
Clarity= 1.0
Angular 7
if search returns only a single row, then the row stays at the top and view is scrolled down making the row invisible. therefore its hiding the search bar as well.

Refer the attached screenshot 
This can be reproduced in https://v1.clarity.design/datagrid/string-filtering
![Screen Shot 2019-04-30 at 12 00 24 PM](https://user-images.githubusercontent.com/18656855/56946327-70278900-6b47-11e9-8b1b-86b5064ec133.png)

**Comment by gnomeontherun** [comment]
This is a duplicate #3011 and #2683. Please help us out by searching existing issues before posting, and I'm going to go ahead and close. Follow #2683 for progress on the popover fixes coming.
