### ISSUE TITLE
Create Signpost component

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#333]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
Have the ability to display help information in the context of input fields as well as anywhere within an application.

An example is attached below although more cases might need to be covered.

<img width="743" alt="screen shot 2017-01-09 at 9 46 36 am" src="https://cloud.githubusercontent.com/assets/690949/21776718/a96cc9de-d650-11e6-8d74-f0278b2debfa.png">

**Comment by reddolan** [comment]
@jaffoneh with the design spec being complete, what "UX input" is needed on this issue?

**Comment by jaffoneh** [comment]
@reddolan as far as I know, design spec was not complete. The effort started but hasn't been completed with different use cases looked at and addressed. Might need a final pass + posting it here as a design spec.

**Comment by reddolan** [comment]
@jaffoneh awesome. I will pass the info on.

**Comment by lil-kim** [comment]
This issue has been updated. Please see Signpost Help Component (New) #486
