### ISSUE TITLE
While using basic select no css

### ISSUE THREAD

**Issue by thatscot** [vmware/clarity#3330]
## Describe the bug

When using basic select html provided by clarity, I get a basic select box with no styling. 

## How to reproduce

```
  <div class="card">
    <div class="card-header">
      Generate Report
    </div>

    <div class="card-block">

      <div class="flexBox" id="highSchoolFlexBox"clrInline>

        <h3> Stage </h3>

        <select clrSelect name="options" [(ngModel)]="options">
          <option value="one">One</option>
          <option value="two">Two</option>
          <option value="three">Three</option>
        </select>

      </div>
    </div>
  </div>
```

## Expected behavior

I expect it should be styled as seen in clarity documentation. 

## Versions

**App**

* Angular: 6
* Node: 8

**Device:**

* Type: Laptop
* OS: Ubuntu
* Browser Chrome, Firefox

**Comment by thatscot** [comment]
Clarity version - 0.12.3-patch.2

**Comment by gnomeontherun** [comment]
Per the 0.12 documentation, the new Angular select component is not in 0.12. See this for the correct examples for 0.12. https://vmware.github.io/clarity/documentation/v0.12/select-boxes
