### ISSUE TITLE
clarity datagrid and cdkVirtualFor

### ISSUE THREAD

**Issue by tomsiaudvytis** [vmware/clarity#3332]
## Summary
Clarity has nothing for big data sets without pagination and Angular from v7 introduced virtual scroll. 
https://material.angular.io/cdk/scrolling/overview
Which gives very smooth and lag-less scrolling even in very big data sets

## Use case
Simple application I am working, has only ~3k rows but without pagination it's very laggy..
It would be amazing if clarity data grid could use *cdkVirtualFor to iterate over elements
## Examples
https://stackblitz.com/angular/garkdaqyvvv?file=app%2Fcdk-virtual-scroll-overview-example.html
this is how virtual scrolling works

## Workarounds
Not investigated

**Comment by gnomeontherun** [comment]
Clarity has support for large data sets using server-driven grids and pagination.

We have #41 open for this feature, so I'm marking this as a duplicate and closing it. You may wish to post on StackOverflow with a demo of your situation and what is laggy about it, perhaps there is a reason.

As a note, virtual scrolling has not been implemented in a way that is also properly accessible for assistive technologies, and this limits our ability to focus on this until we have an approach that works. We've done a lot of investigation on this to date without a solution.
