### ISSUE TITLE
Vertical nav expand/collapse gets stuck on slow machines

### ISSUE THREAD

**Issue by cgherman** [vmware/clarity#3334]
## Describe the bug

On slower devices, the collapsible navigation menu can get stuck in a loop.  This occurs when the user clicks the menu a few times in a row, causing the menu to constantly expand and collapse, requiring the page to be reloaded.

## How to reproduce

1.  Open Chrome Browser
2.  Go to https://clarity.design/documentation/vertical-nav/collapsible-nav/normal
3.  Click on 'Code & Examples'
4.  Click on 'Collapsible Navigation'
5.  Press F12 to launch the developer console, and select the “Performance” tab
6.  For CPU throttling, select: "6x slowdown" to ensure that the issue is visible on any machine
7.  In the Project Pokemon example, quickly expand and collapse the menu a handful of times (I have been able to replicate with a double-click)
8.  Disable CPU throttling to better see the issue
9. See error – the events for expand and collapse compete with each other, and the menu gets stuck in a manic loop

## Expected behavior

The nav menu should only allow only one expand or collapse action to be in play at any given time, even on slower processors.

## Versions

**App**

* Angular: 7
* Node: 8.10
* Clarity: Occurring in online samples (our version is 0.11)

**Device:**

* Type: Xeon W-2135 6 cores@ 3.70 GHz w/32GB RAM
* OS: Windows 10
* Browser: Chrome
* Version: 74.0.3729.131 (Official Build) (64-bit)

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Thanks for the report, animations can cause lifecycle issues when changes occur too fast and this case appears to be problematic. We'll have to investigate further what we can do, but the loop does stop if you speed the CPU back up and click once to resolve the final state quickly.

**Comment by gnomeontherun** [comment]
This is a stale issue now and we are working on a new navigation component for Clarity Core. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
