### ISSUE TITLE
Improve clr-icons TypeScript  typings

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#3337]
Due to the way out Icons are constructed there are constraints on how they can be typed properly with TypeScript. We are planning on refactoring the icons in the near future to address the tree shaking issue (https://github.com/vmware/clarity/issues/2599). When the refactor is worked on we should make sure the icons properly provide the TypeScript typings for better ide integration.

Use PR https://github.com/vmware/clarity/pull/3294 for reference when it comes to the implementation as it provides detail of the constraints of the current API as well as the changes necessary to get the proper typing support.

**Comment by mathisscott** [comment]
Fixed with #3967
