### ISSUE TITLE
Toggle switches – Documentation bug

### ISSUE THREAD

**Issue by polyconvex** [vmware/clarity#3342]
## Describe the bug

A super weird bug causes the description of Toggle switches to render out extra letter to the "on" -word.

"With toggle switches, users can select the ______one______ or off state of an option."

## How to reproduce

Go to: 
https://clarity.design/documentation/toggle-switches
It is right there o.o 

1.  Go to 'https://clarity.design/documentation/toggle-switches'
2.  Read the description of the page
3.  See error

## Expected behavior

Expected "on" instead of "one"

## Versions

**App**

Latest

**Device:**

On every device

## Additional notes

Defcon 1

**Comment by hippee-lee** [comment]
Thanks for reporting this. A  fix for it should be published soon.
