### ISSUE TITLE
Create Masked Input Component

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#335]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
Have the ability to enter data in a certain format within an input field. For example: specifying the way a phone number needs to be entered by a user and have that enforced by the masked input field itself.

**Comment by reddolan** [comment]
We have merged this request into #1259 and will be closing this one. Please direct questions and/or comments to the new issue.
