### ISSUE TITLE
Tab order on the website needs update

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#3351]
## Describe the bug
Tabbing order on the Clarity website goes like this:
- skip link
- top nav
- content
- side nav
When we didn't have the skip-link this made some sense, but now we'd better land on side nav before the content.
This was already fixed on the ks-app.

## How to reproduce

1.  Go to https://clarity.design/documentation
2. Click Tab (x9)
3. Verify that focus goes to content and skips the side nav.

## Expected behavior

After the top nav the focus should move to the side nav.

**Comment by srikanthps** [comment]
This issue seems to have been addressed by https://github.com/vmware/clarity/commit/a7736834ca648d8c5496e7ca60b018690ec5fdf3#diff-cfa7908cec9876db90f4c7b08f6769ec.

By moving the nav bar above the router-outlet, the tab order seems to be working fine now.

Should this issue be closed?

**Comment by mathisscott** [comment]
If that's the case, then yep!

Thanks for the heads up, @srikanthps !
