### ISSUE TITLE
icon colors do not match clr-ui dark mode colors

### ISSUE THREAD

**Issue by ashtynlynne** [vmware/clarity#3352]
## Describe the bug

Clarity icon colors do not match clarity UI colors for dark mode

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v1-0-ccmxax

1. Icon colors in dark mode should match the clarity UI colors in dark mode - the check mark in the example above should be #60B515 instead of #2F8400

## Expected behavior

Icon colors in dark mode should match the clarity UI colors in dark mode

## Versions

**App**

* Clarity: 1.0

**Device:**

* Type: MacBook
* Browser: Chrome

## Additional notes

None

**Comment by AlexMarcuBytex** [comment]
I investigated it and i see that you cant overwrite the style for these icons ( in this case, the `.is-success` class) from the dark theme style file. Im thinking of adding a class `.dark` in the icons style which should apply the correct color in the dark theme.

**Comment by mathisscott** [comment]
A better approach might be to add a block of CSS at the bottom of the dark theme that ties the colors into the expected dark theme variables. It's trivial to override these colors in CSS.

**Comment by AlexMarcuBytex** [comment]
@mathisscott i tried that and it doesnt work. the clr icon style is separated from clr angular style. dark theme file overrides just variables from clr angular components. so, what would be the right approach here if there s no dependency between them?

**Comment by mathisscott** [comment]
@AlexMarcuBytex 
CSS works regardless of whether it's in the dark-theme.scss file or the icons.css file.

You may need to up the specificity of what you are potentially adding to the dark theme (to override the icons CSS if it is loaded later).

But it's literally....

```

**Comment by gnomeontherun** [comment]
@mathisscott why was this closed? The PR appears to be open?

**Comment by mathisscott** [comment]
we closed it in the leads meeting. the PR is for a backport, iirc. i'll move it back. thanks!

**Comment by gnomeontherun** [comment]
This was backported, closing as resolved.
