### ISSUE TITLE
website: audit the API tables for all Clarity Components

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#3354]
## Summary

_Summary the request and address the questions as appropriate._

* What is the change?
Update the API tables Or add if missing) for each of the component documentation pages

* Why should it go in Clarity?
Some tables may be out of date and other components are missing tables al together. 

* Does this change impact existing behaviors? If so how?
Does not affect existing behaviors. 

* If this change introduces a new behavior, is this behavior accessible?
Does not introduce new behaviors. 

## Use case
As a Clarity consumer I want to quickly and easily see the `Angular` API for a component and know what `@Input`'s and `@Output`s it has made public for consumers to tie into. 

## Examples

n/a
## Workarounds

n/a

**Comment by gnomeontherun** [comment]
Proud to say we have done this for upcoming website, closing as resolved!
