### ISSUE TITLE
The arrow icon in the dropdown component is a little bit off in v1

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3355]
## Describe the bug

The arrow icon is not centered relative to the text of the dropdown button/item:
![image](https://user-images.githubusercontent.com/1977391/57673880-231bda80-7650-11e9-84eb-4557fe920b1c.png)

## How to reproduce
It's noticeable in the website of version 1
![image](https://user-images.githubusercontent.com/1977391/57673930-52324c00-7650-11e9-9deb-8aa603f976ae.png)

Looks good in version 2 though
![image](https://user-images.githubusercontent.com/1977391/57673954-60806800-7650-11e9-9b1d-dc663be2b58f.png)

## Versions

**App**

* Angular: 7.2.*
* Node: 10.*
* Clarity: 1.* (latest)

**Device:**

* OS: Windows 10 Enterprise
* Browser Edge Chromium
* Version latest

## Additional notes

_Add any other notes about the problem here._

**Comment by bdryanovski** [comment]
It seems that is some kind of regression after this commit 9cd61b266460613af175271d7a8a95f6e20bf313 

This change: 
```scss
// from
$clr-dropdown-caret-xOffset: 0.333rem;

// to
$clr-dropdown-caret-margin-top: 0.375rem;
```
It seems that `0.3rem` looks good ?!

**Comment by gnomeontherun** [comment]
@bdryanovski you can patch this for v1, it doesn't appear to affect v2+.

**Comment by bdryanovski** [comment]
Sure will do

**Comment by gnomeontherun** [comment]
This was fixed in v1, closing.
