### ISSUE TITLE
Select boxes does not support clarity tooltip on individual options

### ISSUE THREAD

**Issue by ahanaac** [vmware/clarity#3356]
## Describe the bug-The select boxes which are present in clarity version 0.11 and not present from 0.13 and in the select boxes the clarity tooltip cannot be applied to the select box.

Details-The select box is the component which is present in clarity version 0.11 and the multi select boxes are also present but from 0.13 version the multi select boxes are not present and the select boxes does not support the clarity tooltip on the individual options in the select boxes.

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

Issue1;

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v11-bprcpn
2.  Click on any individual option and hover on it and the tool tip is not visible although the clarity tool tip is added.

Issue2:
1.The multi select box option is not present from the 0.13 version it is last in the 0.12 clarity version.

## Expected behavior

_The expected behavior where the select boxes should support clarity tooltip where as the other fields and combination of boxes supports the tool tip incorporation and expectation is that the multi select box should be supported in the latest version from 0.13 as it is not present in those versions.
It should not have any error in console.
## Versions

**App**

* Angular: 5[e.g. 6]
* Node: 6.10.3[e.g. 8.10.0]
* Clarity:0.11 [e.g. 0.12.5]

**Device:**

* Type: Laptop
* OS: Windows 10
* Browser Chrome
* Version ----

## Additional notes

N/A

**Comment by hippee-lee** [comment]
It looks like the only permitted content for an `option` is:
```
Text, possibly with escaped characters (like &eacute;).
```
See more on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option)

**Comment by ahanaac** [comment]
the tool tip which is present in the clarity is not able to added in the individual options
what can be the solution?

**Comment by ahanaac** [comment]
The issue was related with tool tip on the options and thus the solution put forwarded is the applying option which is hard coded

**Comment by gnomeontherun** [comment]
I don't believe this is a scenario we had ever intended to support, even if it did work in prior versions. I'm not sure what your use case is exactly, but this is also a challenge to support in an accessible manner for screen readers. Have you considered the `title` attribute instead?

The forms you are using are also deprecated, so as you update to 1.0+ you'll want to review the updated form controls.

**Comment by ahanaac** [comment]
The use case is mostly about the tool tip which we can apply on the drop down and the select boxes but we are not able to apply the clairity tool tip on the select boxes options.
The tool tip is mostly is the work around because on selection of the individual options when we use horizontal scroll on a fixed maximum width the string of that option gets truncated on selection so we are trying to show the options displaying a tool tip.

**Comment by ahanaac** [comment]
Yes title attribute i have considered and apllied tool tip as the clarity clr trigger tool tip is applicable.

**Comment by hippee-lee** [comment]
I'm really sorry but I am have a hard time understanding this use case. 
Is there any way you can create a vanilla non-clarity prototype that demonstrates what you want to accomplish? 

Working code will help me see the UI you would like and understand the code you are using to create it.  ( stackblitz, codepen etc - anything that runs in a browser will help me understand )
