### ISSUE TITLE
A header is not a heading

### ISSUE THREAD

**Issue by dharcourt** [vmware/clarity#3358]
## Describe the bug

The Drop-down menu API (class names) and documentation (at https://clarity.design/documentation/dropdowns) use "header" when what is meant is "heading".

## How to reproduce

1.  Go to 'https://clarity.design/documentation/dropdowns'.
2.  Find all occurrences of "header".
3.  Read the definitions of "header" at https://www.merriam-webster.com/dictionary/header, https://dictionary.cambridge.org/us/dictionary/english/header, https://techterms.com/definition/header, https://www.dictionary.com/browse/header.
4.  Note how each of those definitions refers to the header being at the top of a page (or sometimes at the beginning of a file), and how drop-down menus aren't and don't have pages or files.
6. Read the definition of "heading" at https://www.merriam-webster.com/dictionary/heading, https://dictionary.cambridge.org/us/dictionary/english/heading, and https://www.dictionary.com/browse/heading.
7. Note how the definition of "heading" matches exactly what Clarity's drop-down menu calls a "header".

## Expected behavior

"Heading" is used for text that appears before something to describe, summarize, or give a title to that something. "Header" is used for text that appears at the top of every page (similarly to how footers appear at the bottom of every page).

## Versions

* Clarity: v2

## Additional notes

- Bootstrap has the same heading/header confusion. Perhaps this is where this mistake came from. You can do better than bootstrap.
- Obviously not a show-stopper, but also not without impact: Some developers will mistakenly type `class="dropdown-heading"` when they would need to type `class="dropdown-header"`. You wouldn't call this class "dropdown-fruggle" or "dropdown-headling", so don't call it "dropdown-header" when you mean "dropdown-heading" (even if you think you mean "dropdown-header :-).
- You can change "dropdown-header" to "dropdown-heading" in a backward-compatible way by leaving "dropdown-header" as an undocumented class that provides the same functionality as a new documented "dropdown-heading" class.

**Comment by hippee-lee** [comment]
Whether grammatically correct or not it seems to have been established as a pseudo naming convention for more than just Clarity and bootstrap components, e.g - Lightning uses it in the Menu's component [here]( https://www.lightningdesignsystem.com/components/menus/#With-Subheaders). 

Thank you for bringing this to our attention but it's not something Clarity can change at this time.
