### ISSUE TITLE
Server-Driven Full Pagination 

### ISSUE THREAD

**Issue by nbartley** [vmware/clarity#3361]
## Summary

Add example Full Pagination Server-Driven example using non mock service.

* What is the change?

The current Server Driven Full pagination demo relies on the internal mock service, and sets many paging variables locally. For instance, it keeps a static size count for the array, whereas the array size should rescale based on filters, and therefore be set by the api end point.

* Why should it go in Clarity?

It isn't currently clear how to pass pagination information (record set total records, current page, implementing the task w/ a subscribe model instead of declared promises, etc) for a more novice programmer, or someone not completely clear with how clarity data-grid works. 

* Does this change impact existing behaviors? If so how?
This does not change existing behavior, it is merely a demonstration page.

## Use case

Providing users unfamiliar with clarity datagrid a clear example of how to consume a restapi which provides total records/current page/and data in a complex json return (Not everyone has the luxury of building their own endpoints either sadly...).

## Workarounds

**Comment by hippee-lee** [comment]
It is really difficult to create something like this that works for _everyone_. The examples in server driven datagrid show one way to handle the mocked server response. **Every API and every application will be different.**

This code in the documentation could be an application service that makes http requests and _then_ updates the list of items for the datagrid as well as the pagination properties. Noting the **then**, this example could easily be using HttpClient to hit an end point and mapping the results to the relevent properties.  
```
        this.inventory.filter(filters)
            .sort(<{by: string, reverse: boolean}>state.sort)
            .fetch(state.page.from, state.page.size)
            .then((result: FetchResult) => {
                this.users = result.users;
                this.total = result.length;
                this.loading = false;
            });
```
I'm not sure how to create a generic demo or even if that is different from whats already in the documentation. I'm closing this for now as it seems more like a how to question specific to one API. Those types of questions can be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/vmware-clarity) where it can be demonstrated with a simple example what has been tried and what the backend/API looks like. Without seeing htat its hard to help.
