### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError in [clrDgLoading]

### ISSUE THREAD

**Issue by farlock85** [vmware/clarity#3364]
## Describe the bug

When using the clrDgLoading on the datagrid it gives the error:
```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'loading: undefined'. Current value: 'loading: true'.
```

## How to reproduce

Implement the example from the Datagrid -> Server Driven example as stated in the docs.
https://stackblitz.com/edit/clarity-light-theme-v013-kdp43p?file=src%2Fapp%2Fapp.component.html

## Versions

**App**

* Angular: 6
* Clarity: 0.13.2

**Comment by Jinnie** [comment]
Hi @farlock85
The initial `refresh` event is emitted in datagrid's AfterViewInit. So if you set your `loading` variable there (when you first set it to true before loading data) you will get this error as you are still in the same angular cycle.
You have several options:
- Set the `loading` variable to true immediately when you declare it. As you use the `refresh` event for initially loading your data it won't be wrong to start in `loading` state. There is no "not-loading" state that should be visualized before the 1st loading spinner.
- If you are also setting other variables which have bindings you will be getting more ECAIHBC errors. In this case it may be better to explicitly trigger a change detection by calling `ChangeDetectorRef#detectChanges()` in your component's `ngAfterViewInit`.
