### ISSUE TITLE
Certify against Angular v8 stable

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3379]
When Angular 8 is released, we need to update and certify against before we can do 2.0.

* [x] Bump versions in our package
* [x] Bump versions in our NPM package file
* [x] Run all testing suites

**Comment by spitfjre** [comment]
Angular 8.0.0-rc.5 introduced a [breaking change](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes).

[Migration strategy](https://pr30644-4698539.ngbuilds.io/guide/static-query-migration) is already provided.
