### ISSUE TITLE
Export commonly used enums for use in component code (e.g. Layouts)

### ISSUE THREAD

**Issue by garkenbout-quintor** [vmware/clarity#3380]
## Summary

* What is the change?
Export commonly used Enums like the Layouts from '@clr/angular/forms/common/providers/layout.service'

* Why should it go in Clarity?
Allows for use of the enum values in code. Current use case was me trying to use 'Layouts.HORIZONTAL' in a form tag with 'clrForm [clrLayout]=".."' instead of using a hardcoded (and typo-sensitive) string 'horizontal'.

* Does this change impact existing behaviors? If so how?
Exposes enum values to developers. Should not impact behaviours. Maybe might need to allow for the html tags to have property setters to include the enums.

* If this change introduces a new behavior, is this behavior accessible?
Shouldn't introduce 'new behaviour'.

## Use case

See 'Why should it go in Clarity'

## Examples

See 'Why should it go in Clarity'

## Workarounds

Current workaround is making a hardcopy of the declared enum or using hardcoded strings

**Comment by hippee-lee** [comment]
This is something we should expose. It will have to be renames with the `Clr` prefix as part of this change.

**Comment by gnomeontherun** [comment]
At some point we did export the layouts option. If there are other requests with good reason, we could consider them if as contributions if they are meaningful to make public and not internal use only. Closing as resolved.
