### ISSUE TITLE
Datagrid: Add Support for Indeterminate Checkboxes

### ISSUE THREAD

**Issue by ghillert** [vmware/clarity#3386]
## Summary

For the Checkbox Tree, Clarity supports "Indeterminate Checkboxes". You should support "indeterminate checkboxes" also for the datagrid.

## Use case

This would standardize behavior between the datagrid and the checkbox tree.

## Examples

Checkbox tree:

![image](https://user-images.githubusercontent.com/685363/58211575-f13eef80-7cb1-11e9-820d-458c60c4b01d.png)

The datagrid does not show the indeterminate checkbox in the header column:

![image](https://user-images.githubusercontent.com/685363/58211631-1e8b9d80-7cb2-11e9-9e59-f9797090a17c.png)

**Comment by Shijir** [comment]
> This would standardize behavior between the datagrid and the checkbox tree.

Tree and Datagrid with selections have different functionalities and goals. Our Datagrid component doesn't support nested items or rows. So it's expected that they would behave differently. As such, I don't see anything common between them to be standardized.

**Comment by ghillert** [comment]
@Shijir That is not what I meant. I think from a UX experience, when I select 2 rows in the data-grid, the checkbox in the header should show the `indeterminate` state instead of the `unselected` state. That way the user has a visual indication whether all, some or no checkboxes are selected, just by looking at the header checkbox.

**Comment by gnomeontherun** [comment]
Ahh I see what you mean, it wasn't clear based on your issue but we can take another look at this feature request.

**Comment by ghillert** [comment]
@gnomeontherun Awesome - thanks for considering this!

**Comment by gnomeontherun** [comment]
The basic agreement is it would help over-communicate the fact something is selected which coordinates with the bottom checkbox indications.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
