### ISSUE TITLE
Option to remove clr-tooltip from tabindex

### ISSUE THREAD

**Issue by williangd** [vmware/clarity#3392]
## Summary

On some forms with many fields I need to change the tabindex of the tooltips to -1. Even putting tabindex = "- 1", it is not removed from tabindex.

Is there any way to remove tooltips from tabindex?

**Comment by gnomeontherun** [comment]
Could you provide a bit more detail about what you want, with a little demo? I'm not sure what exactly you want to put tabindex -1 onto.

**Comment by williangd** [comment]
I want to remove the tooltip from tab flow.

Here is the example: https://stackblitz.com/edit/clarity-light-theme-v013-qcnhae

**Comment by hippee-lee** [comment]
How would keyboard only users access the tooltip content in this use case?

**Comment by williangd** [comment]
Good question. 
Some users have asked to remove the 'tooltips' from the tab flow on some larger forms, not on all forms.

**Comment by hippee-lee** [comment]
Ok. This breaks a11y and prevents keyboard users from accessing tooltips. IMO - I do not think is a good idea, do you?

**Comment by gnomeontherun** [comment]
Our new form pattern provides a better chance to display the content without tooltips, have you considered that? I believe the ask is one that we cannot directly facilitate for accessibility reasons.

**Comment by gnomeontherun** [comment]
I'm going to close this as something we won't do since it would break accessibility for the tooltips.
