### ISSUE TITLE
Text getting selected through out the wizard when double clicking on the wizard page

### ISSUE THREAD

**Issue by avinashvaka** [vmware/clarity#3393]
## Describe the bug

On performing double click on the wizard page or the free space after content the entire text content in the following wizard pages is getting selected.

## How to reproduce

Added a  screen recording which helps to reproduce the issue
https://screencast-o-matic.com/watch/cqhuXyTbMF
https://screencast-o-matic.com/watch/cqhuXCTbMM

(https://clarity-light-theme-v11-prxdvg.stackblitz.io).
https://stackblitz.com/edit/clarity-light-theme-v11-prxdvg

1.  Launch a wizard.
2.  Double Click on empty space after content on wizard-page and select wizard next button to navigate next page.
3.  we can observe that the entire content in the all the upcoming next pages in the wizard are selected.

### **Possible solution**
As the issue is producing due to double click we are proposing a solution by disabling the double clicks on entire application UI that can be override in component level if required in future. But we have some queries to consider this as a potential solution,

* Is it recommended to disable the double clicks on entire UI? Will it effect any of the internal functionalities of other components and any possibility of causing regressions in the application?

* Is it possible to override the individual clarity component click event behavior in future when required?

* Also, We wanted to know any of the existing clarity components is bounded with double click events? 

## Expected behavior

On performing double click the text must be selected either in the selected page or particular content but the selection should not be carried to consecutive pages. This effects the usability and consistency of the application.

## Versions

**App**

* Angular: [5]
* Node: [v 6.10.3]
* Clarity: [0.11]

**Device:**

* Type: [Dell Latitude 7480]
* OS: [windows]
* Browser [chrome]
* Version [74.0.3729.169]

**Comment by gnomeontherun** [comment]
I can reproduce this issue, but it is generally a minor issue. We do not advise blocking click behaviors as this might break other things and cause issues for how people use their devices.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
