### ISSUE TITLE
Inconsistent validation error style for select element

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#3398]
## Describe the bug

When select element is invalid it has no red border.

## How to reproduce

You can reproduce in official docs: https://v1.clarity.design/forms
![image](https://user-images.githubusercontent.com/1386622/58628799-5b274c80-82e3-11e9-98bc-a8b1a702f401.png)

## Expected behavior

Validation style should be consistent for all elements. Invalid select should have same red border as invalid input:

![image](https://user-images.githubusercontent.com/1386622/58629005-e9033780-82e3-11e9-83f1-dff303732f38.png)

**Comment by gnomeontherun** [comment]
Thanks, placing this in the backlog. Should be an easy fix.

**Comment by iamkdev** [comment]
I made the below change into `clarity\src\clr-angular\forms\styles\_containers.clarity.scss#113`. It seems worked as expected.

<pre>
    .clr-control-container {
      display: flex;

      &.clr-error {
        .clr-select-wrapper select {
          border-bottom-color: $clr-forms-invalid-color;
          @include input-border-bottom-animation($clr-forms-invalid-color);
        }
      }
    }
</pre>
