### ISSUE TITLE
No provider for ClrResponsiveNavigationService!

### ISSUE THREAD

**Issue by virusakos** [vmware/clarity#341]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

No error thrown

### Actual behavior

Error "No provider for ClrResponsiveNavigationService!"

### Reproduction of behavior

Not reproducable in plunker

### Environment details

* **Angular version:** "@angular/compiler-cli": "^2.3.1"

* **Clarity version:** "clarity-angular": "^0.8.1"

* **OS and version:** macOS Sierra 10.12.2

* **Browser:** Tested only in Chrome 55.0.2883.95 (64-bit) | IE 11.576.14393.0 | Safari 10.0.2

I am reporting something that I do not know if it is a bug or my environment is wrong.
I am in the process of evaluating clarity to see if I am going to use it in my project.
I used "Using an Angular Seed Project" to install clarity.
I only added an empty `<clr-main-container>` tag (no content) in `app.component.html` and I am getting the error "No provider for ClrResponsiveNavigationService!"

**Comment by Shijir** [comment]
Hi @virusakos, you might need to call `forRoot` on ClarityModule in `app.module.ts`. So instead of including just `ClarityModule`, it should be `ClarityModule.forRoot()` in the `imports` field.

**Comment by virusakos** [comment]
Hi @Shijir, thank you!
The documentation in "Step 2c: Install Clarity Angular" has `ClarityModule.forChild()` in the imports field.
I copy pasted the code and didn't pay attention. My bad.
I changed it to `ClarityModule.forRoot()` and the error is now gone.

**Comment by jaffoneh** [comment]
Closing based on the last comment.
