### ISSUE TITLE
Modal close button needs an accessible name

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3413]
The modal close button is simply just an X SVG, and we need to add the appropriate Close title to it like we have in other places using commonStrings.

**Comment by bdryanovski** [comment]
I don't see what could be the problem? Or is it already solved?

```html
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" *ngIf="closable" (click)="close()">
            <clr-icon shape="close" [attr.title]="commonStrings.close"></clr-icon>
        </button>
    ...
</div>
```

<img width="380" alt="Screen Shot 2019-06-10 at 2 39 40 PM" src="https://user-images.githubusercontent.com/204564/59193223-a36d2700-8b8d-11e9-8b8f-c450b61bbece.png">

Do we need to have some other text or add `aria-label` - it seems that right now the reader is saying 'button Close'

**Comment by mathisscott** [comment]
@chlane ☝️

**Comment by mathisscott** [comment]
Per @chlane 
Use `[attr.aria-label]="commonStrings.close"`
