### ISSUE TITLE
Button has outline on focus. It doesn't go until focus something else.

### ISSUE THREAD

**Issue by iamkdev** [vmware/clarity#3429]
## Button has outline on focus. It doesn't go until focus something else.

_When clicked a button or tabs(which has buttons). It leaves the #a4c6fd colored outline. Below as sample screenshot._

![clarity-btn-focus](https://user-images.githubusercontent.com/1850968/59131239-74896200-898f-11e9-84bd-97e842600ab0.PNG)

## How to reproduce

1.  Go to 'https://clarity.design/documentation/tabs'
2.  Click on 'Tab' from the below examples.
3.  It leaves outline of #a4c6fd color.

## Expected behavior

_Outline doesn't look good and it should be removed from the button focus._

## Versions

**App**

* Angular: [e.g. 8]
* Node: [e.g. 11.4.0]
* Clarity: [e.g. 2.0.0] _//its exist on all previous versions as well_

**Device:**

* Type: [Dell Inspiron]
* OS: [Windows 10]
* Browser [chrome]
* Version [74.0.3729.169]

## Additional notes

_I can raise the PR if the change is acceptable._

**Comment by iamkdev** [comment]
Solution:

> clarity\src\clr-angular\utils\_reboot.clarity.scss#314

`  button:focus {
    outline: none;
  }`

**Comment by gnomeontherun** [comment]
This is as expected and desired, because focus is important for keyboard users to know where the focus is so as they navigate they know where they are on the page. 

We won't remove this outline nor change the default behaviors, and don't recommend you remove this either for your users.

**Comment by mvorisek7** [comment]
BlueprintJS does something interesting with this. They only enable the outlines if they are using tab to navigate, otherwise if mouse use is detected, they disable the outlines. You can read more about it here:
https://blueprintjs.com/docs/#core/accessibility

It might be worth looking into to see how feasible it would be to implement in Clarity
