### ISSUE TITLE
clr-vertical-nav collapses, but div class="content-area" do not resize

### ISSUE THREAD

**Issue by SorinPricopie** [vmware/clarity#3430]
## Describe the bug

clr-vertical-nav collapses, but div class="content-area" do not resize

![image](https://user-images.githubusercontent.com/51517987/59152086-25eacf00-8a46-11e9-8769-5c003a2da782.png)

## Expected behavior

div class="content-area" to resize (or nav class=sidenav to collapse together with clr-vertical-nav).
![image](https://user-images.githubusercontent.com/51517987/59151935-ea4f0580-8a43-11e9-959e-07ca817b683c.png)

![image](https://user-images.githubusercontent.com/51517987/59151940-f6d35e00-8a43-11e9-8f8b-90d510694ff3.png)

Am I doing something wrong?

## Versions

**App**

* Angular: 7.3.9
* Node: 6.4.1
* Clarity: latest, installed today

**Device:**

* Type: Desktop
* OS: win7
* Browser: chrome

**Comment by iamkdev** [comment]
clr-nav-level will only works on breakpoint below 786px. Check the docs.

**Comment by SorinPricopie** [comment]
> clr-nav-level will only works on breakpoint below 786px. Check the docs.

Thank you for your answer iamkdev, I was hoping that I can place a collapsible "clr-vertical-nav" inside a "sidenav backnav" and this way, when clicking "<<" inside "clr-vertical-nav", both "clr-vertical-nav" and "sidenav backnav" will collapse to the left (icons in "clr-vertical-nav" remaining visible and "content-area" resizing).

**Comment by iamkdev** [comment]
You can do that using a simple ngIf and toggle it

**Comment by SorinPricopie** [comment]
> You can do that using a simple ngIf and toggle it

Thank you again @iamkdev, i will try and see how it works :)
BTW, congrats to you and  the rest of the team, clarity is really beautifull  and usefull. I am still  struggling to   understand how to  change  some  things (for exemple colors for text, backgrounds, borders), i hope you will help me when i.m stuck again :)

**Comment by gnomeontherun** [comment]
Thanks @SorinPricopie for the compliments, you can also review the theming documentation if you really need to change variables in a custom theme. Generally we've set those carefully so I recommend being caution and intentional about any changes you make.

For questions like this, we recommend that you use StackOverflow. We don't handle questions here, but focus on issues and bug reports. We actively monitor StackOverflow as well. Cheers and best of luck on your journey!
