### ISSUE TITLE
Improve dropdown a11y

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#3437]
## Summary
Following the guidelines found [here](https://www.w3.org/TR/wai-aria-practices/#menu), I'm proposing the following to improve a11y for dropdown component:

- Add `aria-disabled='true'` to disabled dropdown item
- Update our documentation and example codes to add `role='separator'` to dropdown dividers (note that this is done on the application side since `<clr-dropdown-menu>` uses content projection).
- ~Add visual style for focused state on disabled dropdown item (?)~

**Comment by jeeyun** [comment]
@chlane: can you review my proposed changes and leave a comment here if there are issues or things I've missed?

@colinreedmiller: could you provide design guidance for focused state on a disabled dropdown item?

**Comment by chlane** [comment]
aria-disabled  and role="separator" look correct for what you are doing, the visual focus indication still needs to meet contrast requirements despite the fact that the item being focused is disabled. Only, the disabled control itself is exempt from the contrast requirement(1.4.11 Non-text Contrast).

**Comment by chlane** [comment]
aria-disabled and role='separator' fit makes sense with what I saw in the screenshot
