### ISSUE TITLE
Optional description for radio buttons

### ISSUE THREAD

**Issue by bsduncan** [vmware/clarity#344]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
When creating a radio button group I want to allow for an optional multi-line description for each of the radio labels.  One possible implementation would put the description below the label.  This provides more information than can be conveyed by a label alone.

### Actual behavior
Enhancement request

### Reproduction of behavior
Enhancement request

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
Hi @bsduncan: If I understand your question correctly, you should be able to do this by just adding a `div` after the `label` in the `.radio` button. I created a plunk to demo it: https://plnkr.co/edit/3uBN8gRUoeVQcaAnfbLA?p=preview

![image](https://cloud.githubusercontent.com/assets/1426805/21814248/8c05c266-d70d-11e6-97c0-db3bbb3e94fb.png)


I am closing this issue for now but please feel free to reopen it or get in touch with us with more details in case I missed something.
