### ISSUE TITLE
Question Regarding multiple datagrids with pagination on one Page

### ISSUE THREAD

**Issue by tkhan29** [vmware/clarity#3445]
Hello,
I ran into an issue on clarity v0.13 when I had 2 datagrids with pagination shown at the same time.
If the number of records in both tables had met the pagination limit (in this case 10).  The first datagrid would behave normally but the second data grid would disappear from the page. I worked around this by showing only one datagrid at a time using *ngIf.  My question is will this still be an issue in Clarity V2?

**Comment by mathisscott** [comment]
@tkhan29 
I don't think we've seen this issue before. Can you [create a stackblitz for it](https://stackblitz.com/@clr-team) recreating the issue?

**Comment by tkhan29** [comment]
Below is the stackblitz link.  I noticed while setting it up that this issue occurs specifically with tables in clr-tab-content.  Please let me know what you find.  Thanks.
-Taneem

https://stackblitz.com/edit/clarity-light-theme-v013-39pvns

**Comment by tkhan29** [comment]
Notice the first datagrid appears but the other 2 do not.

**Comment by tkhan29** [comment]
Any update?

**Comment by mathisscott** [comment]
Hi @tkhan29 
You're missing `*clrIfActive` directives on your `clr-tab-content` tags. [Here is a working example](https://stackblitz.com/edit/clarity-light-theme-v013-4embfs).

[More examples in our documentation here](https://vmware.github.io/clarity/documentation/v0.13/tabs)
