### ISSUE TITLE
Accordion whole header should be clickable

### ISSUE THREAD

**Issue by dexfab** [vmware/clarity#3454]
As seen on https://clarity.design/documentation/accordion#examples, only one third of the header is actually clickable to expand a section of the accordion. This causes issues with Fitts's law and  Gestalt principle. Really the whole element should be clickable to give the user a bigger target area.

**Comment by diogojesus95** [comment]
Looking for this implementation aswell, we are using stack view at the moment, but it's buggy with clarity 2.0 and angular 8 https://github.com/vmware/clarity/issues/3350.

So I tried to switch to accordions but we need the whole area to be clickable.

**Comment by hippee-lee** [comment]
@coryrylan - was the max-width intentional here: https://github.com/vmware/clarity/blob/master/src/clr-angular/accordion/_accordion.clarity.scss#L66 ?

**Comment by coryrylan** [comment]
The clickable area was restricted as part of the design spec for the stepper component so the right hand side could have additional click targets. I think I know of a way to make the button fill content dynamically. I'll take a look at this one.

**Comment by diogojesus95** [comment]
> @coryrylan - was the max-width intentional here: https://github.com/vmware/clarity/blob/master/src/clr-angular/accordion/_accordion.clarity.scss#L66 ?

In the meantime can't we make this change in our side?  I tried changing the max-width to min-width but it's not being applied. Do I need to do any extra step? Sorry still new to angular

**Comment by coryrylan** [comment]
This was fixed and released in the latest Clarity version 2.0.1
