### ISSUE TITLE
Add Kubernetes related icons (already made) to Clarity iconography

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#3456]
Please add these 5 icons to the Clarity icon library under the Technology category:

[K8-icons.zip](https://github.com/vmware/clarity/files/3291916/K8-icons.zip)

This can be added to epic #3309 Icons vol 15 if that is more efficient.

**Comment by lil-kim** [comment]
CC-ing @ali5ter

**Comment by mathisscott** [comment]
Added in #3309
