### ISSUE TITLE
 missing css classes

### ISSUE THREAD

**Issue by julgon2012** [vmware/clarity#3457]
## Describe the bug

I have detected that css classes that were in the previous version are missing and have not been replaced, for example the hidden - * - down.
While there are still the hidden - * - up, which were renamed as clr-hidden - * - up, the aforementioned are not.
On the other hand, if they rename classes or remove classes like the case of the mx-auto, they should notify it in the changes of the version.

## Versions

**App**

* Angular: [8.0.2]
* Node: [12.x.x]
* Clarity: [2.0.0]

**Device:**
PC

* Type: 
* OS: [Windows]
* Browser [chrome, safari]
* Version

**Comment by Kangcor** [comment]
Also the margin and padding shorthand classes have disappeared: pb-1, px-1, p-0, m-0, etc.

**Comment by gnomeontherun** [comment]
We will fix the hidden up/down css classes, those were not intentionally lost.

We weren't advertising the margin/padding classes or intending to support, those much have leaked from Bootstrap. If you need those, we recommend adding them from Bootstrap yourself. If we supported such utilities they would likely be quite different.
