### ISSUE TITLE
overflow trigger icon is not right aligned when no header-actions div exists

### ISSUE THREAD

**Issue by elesueur** [vmware/clarity#347]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When in sub 768px mode, the responsive navigation level 2 trigger button should be right aligned.

### Actual behavior
The overflow trigger icon hugs the app title

### Reproduction of behavior
Repro is trivial, just remove the header-actions div from the DOM

### Environment details

* **Angular version:** 2.0.X
2.4.1

* **Clarity version:** 
0.8.1

* **OS and version:**
macOS 10.12

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Only tested in Chrome

**Comment by adityarb88** [comment]
Thanks for reporting this @elesueur. I will investigate and try to get this fixed soon.
