### ISSUE TITLE
Bugs in Clarity Datagrid

### ISSUE THREAD

**Issue by prachitag** [vmware/clarity#3474]
## Describe the bug

- When there are few rows in the data grid, half of the filter box is not visible.
- When the column width is reduced to minimum, the filter box is hidden for first column
- Alignment of Column Headers gets messed up during column resizing

## How to reproduce

Supporting screenshots:

![image-2019-06-12-18-27-40-470](https://user-images.githubusercontent.com/44446723/59637244-2c460e80-910a-11e9-8410-79818d1adb7c.png)
![image-2019-06-12-14-38-30-232](https://user-images.githubusercontent.com/44446723/59636640-d755c880-9108-11e9-8c97-1069bdaba2c9.png)
![image-2019-06-12-14-30-13-956](https://user-images.githubusercontent.com/44446723/59636702-0a985780-9109-11e9-952f-8a9d569eb278.png)

**Comment by Jinnie** [comment]
The first two issues will be handled by the Smart Popovers utility:
https://github.com/vmware/clarity/pull/3374

For the last, please provide a Stackblitz reproduction with one of the following templates:
https://stackblitz.com/@clr-team

**Comment by gnomeontherun** [comment]
I believe this is fully resolved by smart popovers and closing as such.
