### ISSUE TITLE
Accordion component not present in Clarity Figma library

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#3476]
https://github.com/vmware/clarity/issues/250
https://github.com/vmware/clarity/issues/2452

**Comment by reddolan** [comment]
did you all land on which design it should be? The design on the site is much different than the one in Molly's spec.

**Comment by mathisscott** [comment]
@colinreedmiller ☝️

**Comment by colinreedmiller** [comment]
The purpose of this issue is to surface its absence and provide context for the ensuing conversation. If there is a need in the near term for accordion in the libraries, we will select (and possibly update) the design that most closely aligns with Clarity in its current form. 

Regardless of the decision regarding the timing of adding the accordion to the libraries, we need to consider this over the longer term: The steeper, stack, and accordion share a code base which the ideal solution should leverage, reflected through a unifying design.

The best course of action may be to address the absence of the accordion over the short term with one of the existing designs, and include a unifying approach to a more substantial visual update in the near future.

@coryrylan

**Comment by mathisscott** [comment]
@reddolan 
How is this going?

**Comment by reddolan** [comment]
It's at the top of my backlog. Hoping to get to it today
