### ISSUE TITLE
Button Group Not Handling Button Components Correctly

### ISSUE THREAD

**Issue by jeffjarzombeck** [vmware/clarity#3482]
### Example

https://stackblitz.com/edit/clarity-light-theme-v2-ys798n

### Describe the bug

The Button Group allows a collection of Buttons to be formatted together. This works as expected when the Button Group's direct children are Buttons. However, when a Button Group has children which are Angular Components which are nothing more than Buttons themselves, the Clarity styling no longer works.

### Versions

- Angular: 8.0.0
- Clarity: 2.0.0
- Chrome: 74.0.3729.169

**Comment by Jinnie** [comment]
You are putting your own component inside the .button-group container. 
In the same time, the button style in the group is determined by this CSS selector: `.btn-group .btn`
So far, so good, but the `.btn` part of your setup is not in the same scope as the `.btn-group`. It's in the shadow DOM of your own component.
I don't know what exactly do you want to achieve, but you have several possible scenarios:
1. Make your own component _be the button_ (opposed to _contain the button_) and have the class `btn` on it's host element.
2. Use a normal button, as in your 1st example.
    - If you need any additional behavior, you can add it as a Directive, not a a Component.

**Comment by jeffjarzombeck** [comment]
Thanks for your response, Jinnie. I believe your first suggestion means I should look into creating a custom element which resolves to a <button>, correct?

The thinking behind this setup is the buttons inside this button group are buttons to show modals. Each  modal is different and sometimes complex. Sometimes there are 6 buttons inside the button group. Encapsulating that logic into a component makes sense to me but it seems like I need to take this one step further. Thanks for your help!

**Comment by Jinnie** [comment]
Probably what I first suggested was not good in terms of semantics and accessibility. When you want a button, you'd better use a button, not mimic one.
What's your use case for wrapping a button in your own component?

**Comment by jeffjarzombeck** [comment]
The use case is we have n buttons and when pressing each, a modal is opened. This modal is sometimes a form, sometimes just a confirm/cancel. Each is different. Because some have forms, the original thought was to create a component for each where the template was a button and a modal. When clicking that button, the modal would be opened. This allowed all of the logic of the form to be self-contained.

I've figured out a solution now which is to have the button group contain a collection of buttons. When clicking on a button, a component (which is now wrapping the modal element only) is dynamically created.
