### ISSUE TITLE
Datagird numeric filters don't work & have undefined placeholders

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#3483]
## Describe the bug

Datagrid numeric filters don't have the right placeholders:

From the stackblitz linked below:
![Screen Shot 2019-06-19 at 1 02 17 PM](https://user-images.githubusercontent.com/7132414/59796502-8376eb00-9292-11e9-8ceb-533e55090411.png)

Seen in the wild: 
![Screen Shot 2019-06-19 at 12 51 54 PM](https://user-images.githubusercontent.com/7132414/59796506-85d94500-9292-11e9-9279-99d3c465c48e.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-nm7acf

1.  Open the filter on the `wins` column

## Expected behavior

Inputting values on the numeric filters should result in the filters being applied.

The placeholders should say `Min value` and `Max value`.  

## Versions

**App**

* Angular: 8
* Node:  12
* Clarity: 2.0.1

**Device:**

* Type: Mac
* OS: MacOS
* Browser Chrome
* Version 74

## Additional notes

At first I thought this was just my project since the placeholders do show up correctly in the docs: https://clarity.design/documentation/datagrid/binding-properties

![Screen Shot 2019-06-19 at 12 52 53 PM](https://user-images.githubusercontent.com/7132414/59796596-b8833d80-9292-11e9-98e1-221611881c60.png)

However, this also shows up in a fresh stackblitz so maybe something else is going on.  This was probably introduced by me with https://github.com/vmware/clarity/pull/3397 but I'm not sure how.  

Edit:  I realized that the filters don't even work.  I think something changed during the angular 8 migration / clarity 2.0 release that I missed which broke these.  In particular, the filters work fine on the documentation website so it looks like there's either some sort of dependency difference or something changed since the website was deployed.  

Edit2: The filters work fine on master when running `npm start` or `npm website:start`, but building the packages and using them in a sample project (like the stackblitz above) causes them not to work, so it's something in the build/release step.

**Comment by bdryanovski** [comment]
Affected versions are `2.0.0`, `2.0.1`, `2.0.2`, `2.1.0`.

It seems that `commonStrings` is an empty object. If my memory serves me well, this was a known issue that is resolved with the change of how we provide the translation and the new service.

https://github.com/vmware/clarity/pull/3660
https://clarity.design/documentation/internationalization

This is resolve in all version after and including `2.1.1`

**Comment by gnomeontherun** [comment]
The placeholder text is working, but the filter is not. @bdryanovski are you still looking into this?
