### ISSUE TITLE
Compatibility issue with Angular 7.2.0 and Clarity 2.0.1

### ISSUE THREAD

**Issue by josefsuatengco** [vmware/clarity#3484]
## Describe the bug

App is breaking in Angular 7.2.0 because of 'ɵɵdefineInjectable' in clr-angular.js.  It seems its only available in Angular 8.  As of right now we can't update our app to Angular 8.  Is there a way to handle backwards compatibility in the latest Clarity version as we also need to use Clarity 2 to use accordion?

## How to reproduce

1.  Have Angular 7.2.0 and Clarity 2.0.1 installed.
2.  Import ClarityModule in app.module.ts of your angular app.
3.  You will see this warning during build
![image](https://user-images.githubusercontent.com/48904042/59841968-0ded4680-9388-11e9-9093-c95d6dc54cf4.png)

4.  During runtime, that app will break and this will be the error.
![image](https://user-images.githubusercontent.com/48904042/59842018-29f0e800-9388-11e9-93a6-a3e613f89a36.png)

## Versions

**App**

* Angular: 7.2.0
* Node: v10.15.3
* Clarity: 2.0.1
**Device:**

* Type: Thinkpad T470p
* OS: Windows 10
* Browser: Chrome
* Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by hippee-lee** [comment]
Clarity is following the Angular release schedule ([read more](https://medium.com/claritydesignsystem/updating-the-clarity-release-and-support-strategy-c1e37f7d5a0)). 

What this means is that you should expect breaking changes between major version upgrades that will not be supported in previous versions. There will be 12 more months of bug fixes for Clarity v1.x.x.

**Comment by WaBriones** [comment]
Hi @hippee-lee why was this closed? We're starting out a new project and using everything in the latest versions that are stable, Angular 8 was released just a few months back and you can't expect everyone to start using the latest Clarity with the latest Angular right of the bat, without even specifying a workaround.

**Comment by gnomeontherun** [comment]
We have a defined support policy where certain versions of Clarity support certain versions of Angular because of these types of problems that occur. Also Angular has some breaking changes in v8 that we had to incorporate so that means we cannot support Angular v7 in Clarity 2.0. The workaround is to install the latest Clarity 1.x release until you plan to update to Angular 8. 

See our change log for Clarity 2 and our support strategy here. https://medium.com/claritydesignsystem/updating-the-clarity-release-and-support-strategy-c1e37f7d5a0

**Comment by AliWieckowicz** [comment]
Thanks for stating this clearly and directly.  I strongly suggest adding clear information on angular clarity version compatibility (citing specific versions numbers) to the documentation site.  It would be a big time savings for some of us novices.

**Comment by hippee-lee** [comment]
Documentation is specific to the last release for each major version. 
Above the component side navigation is a dropdown that allows selection of the version of interest if it is not the latest.
