### ISSUE TITLE
Date Picker display breaks with user defined CSS

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3500]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

https://stackblitz.com/github/clane/clarityTest2/tree/master/clarity-test-app

- Open one of the date picker examples and note its vertical position on the screen
- Run the following JavaScript in the console to set the CSS styles to increase text-spacing

(function() {
 //launch it on your page and look to make sure that the text is able to resize in their containers
 var style = document.createElement('style');
 style.type = 'text/css';
 //style.appendChild(document.createTextNode());
 document.head.appendChild(style);
 style.sheet.insertRule('*{line-height:1.5 !important; letter-spacing: 0.12em !important; word-spacing: 0.16em !important;}', style.sheet.cssRules.length);
 style.sheet.insertRule('p{margin-bottom: 2em !important;}', style.sheet.cssRules.length);
})();

- Observe that the vertical position of the date picker has changed. 

## Expected behavior

Prevent the DatePicker from moving as a result of the user setting the following CSS properties.

Line height (line spacing) to at least 1.5 times the font size;
Spacing following paragraphs to at least 2 times the font size;
Letter spacing (tracking) to at least 0.12 times the font size;
Word spacing to at least 0.16 times the font size.

**Comment by gnomeontherun** [comment]
This seems to occur only if you apply the changes when the date picker is open and then apply the styling changes. 

@chlane will retest this and evaluate if there is something we should do or not.

**Comment by chlane** [comment]
While the issue is could be severe when it occurs, it is more logical for the user to apply the text spacing styles before opening the date picker. If they do that this issue will not occur. Now that the behavior is noted, I think this issue can be closed with no further action.
