### ISSUE TITLE
Tabs should support keyboard navigation

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3502]
## Describe the bug

Tabs do not support keyboard arrow key navigation.

## How to reproduce

- Go to https://v1.clarity.design/tabs
- Attempt to use the arrow keys to navigate the tabs in any example

## Expected behavior

Keys should work.

Implement the Tabs as described at https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
This again is totally in the area of effect of #3609 
I'm reassigning it to me as it will be closed by the above PR, together with the other 4 or 5 tabs related focus issues.

**Comment by coryrylan** [comment]
Fixed and closed via https://github.com/vmware/clarity/pull/3700
