### ISSUE TITLE
Tab overflow button needs an accessible name

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3508]
## Describe the bug

Tabs overflow button just says 'button' when using a screen reader, and does not indicate what it does.

## How to reproduce

- Using a screen reader go https://v1.clarity.design/tabs
- Read the overflow dropdown toggle button
- You will only hear the word "button"

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
Will probably fix it as side effect of another issue. Assigning to myself.

**Comment by gnomeontherun** [comment]
@Jinnie Did we tackle this one yet as part of the overflow work?

**Comment by Jinnie** [comment]
Yes. For a blind user this button does not exist now, we're automatically forwarding to the next meaningful button.
Thanks!
