### ISSUE TITLE
Inline data-grid editor

### ISSUE THREAD

**Issue by caveman43** [vmware/clarity#351]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior

Data grids should be able to perform basic actions on row/column values such as add a row, inline-edit a row, delete a row, import/export data.

Also, on top of that if data schema is complex, then data-grid should be comprehensive enough to tackle that while editing inline. Consider data-grids of extjs, in which grid-cells could contain textbox, textarea, dropdowns, calendar etc and also customized input fields.

I have attached a snapshot of extjs data-grid.
![screen shot 2017-01-10 at 4 07 52 pm](https://cloud.githubusercontent.com/assets/11432364/21830290/92b458be-d750-11e6-9b23-754817129180.png)

### Actual behavior

Functionality not available yet.

### Reproduction of behavior

NA

### Environment details
NA
* **Angular version:** 2.0.X

* **Clarity version:** 
all

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by whizkidwwe1217** [comment]
You may want to take a look at Wijmo grid. It's better than ExtJS grid. 
[Wijmo Grid link here...](http://demos.wijmo.com/5/angular2/explorer/explorer/#/grid/intro)

**Comment by vkpavan26** [comment]
Hi Team,

Is there any work planned on this item.We were also looking for similar functionality.

Attaching UseCases of references.

![ipprefixes](https://cloud.githubusercontent.com/assets/25317393/26397313/8728e7b0-4093-11e7-9dc1-7b2a4e4e5a97.png)
![ippool](https://cloud.githubusercontent.com/assets/25317393/26397314/87299692-4093-11e7-8068-c141bd5deb0f.png)

**Comment by mathisscott** [comment]
Inline editing of cells is not currently on our list of prioritized enhancements for the datagrid. The auto-completing select box is on our radar, however. The team's priorities for the near future are pretty booked right now. If you could give us more information on your circumstances for both inline editing in the datagrid and the autocompleter, we can take it back to the team and discuss.

**Comment by stannynuytkens** [comment]
Need!

**Comment by zsf3** [comment]
Wanted!

**Comment by yehia2amer** [comment]
This Feature is Very much needed.

Maybe something like that : [ngx-inline-editor](https://github.com/qontu/ngx-inline-editor)

**Comment by chrisenn** [comment]
We need this!

**Comment by sdurnov** [comment]
This is not a question of life and death, but lack of this feature contributed a lot to going with Kendo for enterprise app. This is really sad, as Kendo controls are much slower, harder to set up and UI is far behind..

**Comment by typhoon1978** [comment]
Absolutely needed!

**Comment by chitayta** [comment]
Hello, 
I think many people need it for their cases, including me! :D

**Comment by Orichlol** [comment]
Needed!

**Comment by gnomeontherun** [comment]
I know this is a common request, but it is still much easier for apps to do this than for Clarity to do this. The main reason is that you know the shape of your datagrid and the necessary form structures to support inline editing, so having a toggle with ngIf on it is something the application can handle.

So far, there hasn't been much talk about the use cases. We do not want to get into the realm of Datagrid becoming a spreadsheet, plus we have to consider how this works for accessibility. Please provide more details about use cases before we jump to conclusions that this would be the right solution to those use cases.

**Comment by gnomeontherun** [comment]
Due to the complexity of this feature and the priorities of the team, we're moving to close this request as it is typically easier for applications to do this than for it to be built into Clarity. We may consider it again in the future, but at this stage we're closing to help clean up our backlog.
