### ISSUE TITLE
how to configure the default sorting of datagrid

### ISSUE THREAD

**Issue by yanyixing** [vmware/clarity#352]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
```

In the document https://vmware.github.io/clarity/documentation/datagrid, I can't found how to configure the default sorting of datagrid.
Can datagrid setting the default sorting column?

**Comment by youdz** [comment]
Currently, this is a feature we're missing. We've had several requests for it, it's currently tracked in #355. Feel free to comment over there if you want to provide additional requests or information.
