### ISSUE TITLE
Stepper focus management

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3528]
## Describe the bug

There are a few places where focus is not properly managed in the stepper.

* [ ] When using the next button in each step, the focus should move to the next step title

* [x] When there are errors, the next button retains focus instead of the form fields itself (Will be resolved from https://github.com/vmware/clarity/issues/3556)

## How to reproduce

https://clarity.design/documentation/stepper

- View the stepper and navigate using next/back buttons
- Focus is lost or remains on the button and not new content

## Expected behavior

The focus should move to newly selected panel.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by coryrylan** [comment]
> When there are errors, the next button retains focus instead of the form fields itself (this is really a forms problem but might require work here)

@chlane What is the expected behavior here?

**Comment by chlane** [comment]
The expected behavior is that screen reader users know about the errors somehow.  My recommendation for do this is in https://github.com/vmware/clarity/issues/3556 which is specific to forms.

**Comment by coryrylan** [comment]
Closed in https://github.com/vmware/clarity/pull/3649
