### ISSUE TITLE
No documentation for clr-main-container and clr-header

### ISSUE THREAD

**Issue by amitmerin** [vmware/clarity#3538]
Related to #103

Both `clr-main-container` and `clr-header` are not documented.
They appear on the responsive navigation example, but no word on them anywhere else.
I would expect to see on the header documentation a "angular component" section within the documentation for `clr-header`.
It is frustrating because only the `clr-*` components actually support responsive layout - a fact that I could also not find in the documentation.

**Comment by gnomeontherun** [comment]
These are actually documented in https://clarity.design/documentation/navigation. We can do more to ensure that this documentation shows up, because I agree its a bit buried and probably should always be used.
