### ISSUE TITLE
Improve generated ids

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#3541]
## Describe the bug

The ids generated by the id-generator.service are in format `clr-id-<number>`. These ids though, are not guaranteed to be the same on different runs and we should designate some way that they are currently internal.

## Expected behavior

A suggested format of `_clr_random_id_<number>` should be enough to convey that the id is random and internal.

**Comment by gnomeontherun** [comment]
We've not prioritized or had further discussion on this. We could still consider a PR if necessary but I'm going to close this request as not a priority.
