### ISSUE TITLE
Droppable area not getting detected when scrolling

### ISSUE THREAD

**Issue by prathamesh7pute** [vmware/clarity#3542]
## Describe the bug

When drag and drop directives are used and if drop area is outside the current view and if it becomes available in the view after scrolling then droppable directive fails to detect droppable area even if draggable ghost image is on top of it.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v1-0-card-container?file=src%2Fapp%2Fapp.component.html

1.  Select any card to drag
2.  Notice if you drop selected card on the other card which is in the current view (no scrolling happened yet, to see the remaining cards) it is properly detecting the droppable area as soon as the draggable ghost image is on top of it.
3.  Now try to select the first card and drop it on last card (so that autoscroll will get triggered) - you can notice here it is failing to detect droppable area although draggable ghost image is over the droppable area

## Expected behavior

Droppable directive should update droppable area as soon as ghost image is on top of it irrespective of the view is scroll or not.

## Versions

**App**

* Angular: [7+]
* Node: [8.10.0+]
* Clarity: [0.13+]

**Device:**

* Type: [MacBook]
* OS: [MacOS Mojave]
* Browser [chrome, safari]
* Version [latest]

## Additional notes

Issue is due to the caching of clientRect in method isInDropArea in the droppable directive. As it is using  cached calculated clientRect attributes on the first Drag Move, it is failing to detect proper drop area when clientRect changes on the scroll.

**Comment by gnomeontherun** [comment]
The drag and drop utilities are internal and we are not planning to make them public. They are meant for any unique purposes we develop internally, and recommend that you consider using other supported drag and drop utilities or build your own for best results. Closing as stale and not supported.
