### ISSUE TITLE
Styling issue nested accordions

### ISSUE THREAD

**Issue by ElectiveRob** [vmware/clarity#3543]
## Describe the bug

Styling issue nested accordions

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-srh29y

## Expected behavior

child accordions should not have the selected style by 'default'

## Versions

**App**

* Angular: 8
* Node: 10.15.3
* Clarity: 2.0.1

**Device:**

* Type: Desktop PC
* OS: Windows 10
* Browser chrome
* Version 75

**Comment by ElectiveRob** [comment]
Workaround:
```
.clr-accordion-panel-open .clr-accordion-header {
  background: inherit;
}
.clr-accordion-panel-open > .clr-accordion-header {
  background: #d9e4ea;
}
.clr-accordion-panel-open .clr-accordion-angle {
  visibility: visible;
  -webkit-transform: inherit;
  transform: inherit;
}
.clr-accordion-panel-open > .clr-accordion-header > .clr-accordion-header-button > .clr-accordion-status > .clr-accordion-angle {
  visibility: visible;
  -webkit-transform: rotate(90deg);
  transform: rotate(90deg);
}
```

**Comment by gnomeontherun** [comment]
I think we first have to ask the question if nested accordions is a recommendation.

**Comment by julgon2012** [comment]
I do not know if they will be recommendable, but the user will request and develop the pleasure.

**Comment by gnomeontherun** [comment]
To help us understand this request, what is the use case that you wish to have nested accordions?

**Comment by julgon2012** [comment]
For example, when we create a vertical menu, with multiple levels of options...

menu1
   |--> menu1.1
                     |--->menu1.1.1
   |--->menu1.2

**Comment by hippee-lee** [comment]
I wouldn't recommend the Accordion as a navigational element. 
We offer several components that are intended to be used for building [navigation](https://clarity.design/documentation/navigation). Included in the navigational components is the [Vertical Nav](https://clarity.design/documentation/vertical-nav/basic-structure/charmander) component.

**Comment by ElectiveRob** [comment]
We're using it for auto generated nested forms:

![image](https://user-images.githubusercontent.com/9783941/62444697-881e3280-b75e-11e9-8c89-af112b721a07.png)

**Comment by julgon2012** [comment]
hippee-lee

Clarity navigation solutions are not suitable for multiple menu levels.
That is why we try to use accordion.

Anyway, I appreciate you answering me.
Best regards.

**Comment by mathisscott** [comment]
This is not a pattern we are looking to support. If you need to nest accordions and remove the spacing for child accordions, then you could do so in your application's CSS using either a negative margin or translateX
