### ISSUE TITLE
Clarity v2 breaks clrDgHideableColumn two way binding

### ISSUE THREAD

**Issue by ldusoswa** [vmware/clarity#3545]
## Describe the bug

This used to allow me to manipulate defaultGrid externally to the grid and the grid would react by hiding/showing the appropriate columns.

`<ng-container *clrDgHideableColumn="{hidden: !defaultGrid}">
        Name
  </ng-container>`

until I upgraded to clr-angular 2.0.1, then the functionality disappeared, almost like it was no longer a two way binding.

## How to reproduce

Clarity 1.1.0 - working preview: https://stackblitz.com/edit/angular-ellsha
Clarity 2.0.1 - same code, just the clarity dependency updated, functionality no longer works: https://stackblitz.com/edit/angular-6kjenx

## Expected behavior

As per <v2, when you click the button, the column should become hidden

## Versions

**App**

* Angular: 8.0.2
* Node: 12.1.0
* Clarity: 2.0.1

**Device:**

* Type: Dell Laptop
* OS: Win10 x64
* Browser: chrome
* Version: 75.0.3770.100

## Additional notes

I have tried to use ng-template instead of ng-container, along the lines of 
`<ng-template [clrDgHideableColumn]="{hidden: !defaultGrid}"></ng-template>`

But had no joy. I also tried:
`<ng-template clrDgHideableColumn [clrDgHidden]="!defaultGrid">`

It seems like there was an explicit removal of functionality. I'd like a way to be able to manipulate those columns without having to rely solely on the standard clarity clr-dg-column-toggle.

**Comment by Shijir** [comment]
I confirm this is a bug. The effort to fix this bug is low. I think we could ship the fix in `v2.0.3`.
