### ISSUE TITLE
Add 2-way binding to the clr-dg-column Component for Filters and Sorting

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#355]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior

1. Add the ability to detect if a column is currently sorted -or- specify an initial sort state for the clr-dg-column Component.
2. Add the ability to detect when a column is currently filtered -or- specify an initial filter state for the clr-dg-column Component.

### Actual behavior
Users can set an initial State for clr-dg-columns for both Sorting and Filtering because the State of Sorting and FIltering is exposed and accesible. In addition when using Sorting or Filtering on the clr-dg-column Component this binding is two way and persists / is accessible in the datagrid's properties. 

### Reproduction of behavior
n/a

### Environment details

* **Angular version:** n/a

* **Clarity version:** n/a

* **OS and version:** n/a

* **Browser:** n/a

**Comment by ssanghavi** [comment]
We have similar requirement where user navigates to details page and comes back to grid. I need a way to indicate what column the grid is sorted/filtered on.

**Comment by clementcur** [comment]
Could we get an ETA on this issue? some of our work depend on it.
Thx!

**Comment by jaffoneh** [comment]
@clementcur it's actually on top of our priorities. Haven't been assigned yet but someone should be looking at it next week and when they do, we'll be able to provide an estimate. Let us know if there is a timeline you need if this is blocking you and we're happy to chat.

**Comment by clementcur** [comment]
Great, sounds good. That's fine, we can wait for a couple of weeks.

**Comment by clementcur** [comment]
@jaffoneh do you have a new milestone in mind?

**Comment by jaffoneh** [comment]
@clementcur should be there in 0.8.8 next week (PR should be out shortly).

**Comment by duzenko** [comment]
I'm looking for a way to set the default sort column but all issues are closed as duplicates of this one.
So how do I set the default sort column, really?

**Comment by hippee-lee** [comment]
@duzenko - there is an example for **Pre-Sorted Columns** in the docs: https://clarity.design/documentation/datagrid/custom-sorting

Basically the app needs to bind to the `clrDgSortOrder` with the desired `ClrDatagridSortOrder`:
``` html
<clr-dg-column [clrDgField]="'name'" [clrDgSortOrder]="descSort">Name</clr-dg-column>
```

``` typescript
import {ClrDatagridSortOrder} from '@clr/angular';
...
@Component({ /* ... */ })
class MyComponent {
    this.descSort = ClrDatagridSortOrder.DESC;
}
```
