### ISSUE TITLE
Stack View button has illogical sequence for screen readers

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3567]
## Describe the bug

The interstitial content in the stack view presents an illogical reading sequence for screen reader users. When screen reader users hear a button announce an expanded or collapsed state they will think that the button controls the readability of upcoming content. 

Discovering content related to the stack-block-label button immediately after hearing that it is in a collapsed state may be confusing. While this is a low severity issue when there is a small amount of interstitial content, the severity will increase in relation to the amount of interstitial content.

## How to reproduce

https://stackblitz.com/github/clane/clarityTest2/tree/master/clarity-test-app

- Using a screen reader go to Stackview example
- Read one of the collapsed stack-block-label buttons
- Observe that you read the value of the stack's key value pair immediately after reading the collapsed button. 

## Expected behavior

The Stack view's implementation should combine the stack-block-label and the interstitial content in the first stack-block-content element into a single control, specifically a button. The stack's key value pair can be used to provide an accessible name and description for this button. This can be done with aria-label or aria-labelledby and aria-describedby.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by chlane** [comment]
When we last met in Palo Alto we decided to concatenate the key and and value and use the resulting string as the accessible name. Then we would advice consumers to use short values to prevent abnormally long button names with documentation.

**Comment by Jinnie** [comment]
I apparently linked this from the wrong PR.
Setting the pipeline accordingly.

**Comment by clane** [comment]
Additionally,  a low vision user using zoom or magnification functionality may not be able to visually perceive the toggling effect of the stack view button because of the interstitial content filling the viewport.

**Comment by mathisscott** [comment]
@Jinnie 
Is this effort complete?

**Comment by gnomeontherun** [comment]
Need to verify if this was fixed fully

**Comment by chlane** [comment]
Fix verified on https://clarity.design/documentation/stack-view
