### ISSUE TITLE
Vertical nav focus management

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3577]
## Describe the bug

Vertical nav links do not navigate screen reader users to new content when the link is clicked and the page isn't a full page reload (Angular routing).

## How to reproduce

https://clarity.design/documentation/vertical-nav

- Using a screen reader, go to https://clarity.design/documentation/vertical-nav
- Activate of the links in the Basic Structure example
- Note that you do not hear any new content

## Expected behavior

We should create an example that moves focus to the new content when routing. Focus should move into the content.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

This might be a requirement for apps since we can't always know what the right choice is in this case.

**Comment by Shijir** [comment]
closed by #3725
