### ISSUE TITLE
Form components doesn't play nice with grid classes

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3580]
## Describe the bug

Grid classes doesn't apply correctly to input/select/textarea elements inside. There were discussion earlier, but you, guys, stated that this is by design.

But let's consider this scenario:

Container, where form is placed, has fixed/limited width. In this case, selects may go out of bounds, as they have automatic width, based on longest option. Very common when used in Clarity modal component, for instance.

[StackBlitz example](https://stackblitz.com/edit/clarity-forms-issue-1)

![image](https://user-images.githubusercontent.com/32732457/60606187-9249bb80-9dc3-11e9-96e4-6f87f2f98aa9.png)

If I want to limit input/select width, so it won't go out of bounds, OR if I want to make all fields in form column of the same width, I have to set form component inner elements properties in css.

And, as form element internals are being auto-generated, I can't set css properties for part of form component inner elements right in my view component file. 
Instead, I have to put it into a global css, which may not be acceptable in many cases.

As a workaround, we can set max-width/width to 100% on everything where it works from component css, and it might look like it's fine:

[StackBlitz example](https://stackblitz.com/edit/clarity-forms-issue-2)

![image 2](https://user-images.githubusercontent.com/32732457/60607331-b6a69780-9dc5-11e9-90af-3dd631e4e2c5.png)

But when you trigger validation, it will break layout again.

![image 3](https://user-images.githubusercontent.com/32732457/60607340-bad2b500-9dc5-11e9-9e45-401f80e430c7.png)

So to fix that, now I must go and check size of validation icon and its margins, put this magic number into my css and reduce input/select size using this value.
Or I can go easier and limit field width to, for instance, 90%, so validation icon will fit in too.

But those are unreliable and ugly workarounds.

## Expected behavior

We shouldn't care about all those wrappers/inputs inside. Input must take 100% of its wrapper width if we set grid column class. If we don't - it must be automatic (for selects, based on longest option), but with max-width = 100%, so it won't go out of container's bounds.

We don't have to write any extra css to get form fields working as most people would expect.
Currently, all my colleagues are frustrated when they have to work with Clarity forms, as the behavior is not what they expect. They have to waste time to figure out how to get it working properly.

## Versions

**App**

* Angular: [8]
* Node: [12]
* Clarity: [2.0.1]

**Comment by gnomeontherun** [comment]
Hi @sdurnov thanks for the detailed scenarios and demos. Our intention with the form controls was to remove the need for a lot of the markup, but anyone who wants to make changes is less empowered as a result due to the default behaviors. I want to see us address the right amount of customization so its available for everyone and not custom styles if we can avoid it.

The case where you don't want the input to extend beyond its container is a valid issue, and what we need to do in this case is calculate the width with the margin in mind. This is easily done with `max-width: calc(100% - 1rem);`, which holds the icon validation spacing. Clarity should address this.

The request to force form controls to take 100% of their containers is not going to be our default, because the size of an input can be meaningful and useful. There is a request for this to be optional #3480. 

You say the behaviors are not what they expect, could you elaborate on what your expectations are overall?

**Comment by gnomeontherun** [comment]
Also, the case of being able to set the label / control grid classes for an entire form is found in #2897.

**Comment by sdurnov** [comment]
> You say the behaviors are not what they expect, could you elaborate on what your expectations are overall?

My understanding of default behavior:

- Without grid classes everything should work as it is working now, but without overflowing a container

- With grid classes there should be 2 options - autosize (but don't overflow) and fill all columns. Autosize may be kept as a default, so there won't be breaking changes in API. Fill all columns behavior may be implemented using optional input parameter.

As for the error icon - I think 2 options should present regardless of using grid classes or not:

1. When icon becomes visible, input element should be narrowed down to fit input+icon in existing container

2. Input stays the same, icon is displayed with possible overflow

I think option 1 should go by default, as it is safe for any situation, option 2 may be turned on using optional input parameter.

And yes, global form setting is something that may be very time saving feature!

**Comment by gnomeontherun** [comment]
Consider using the Clarity Core version of the component for your application which should not have this concern. In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by implementations in Clarity Core.
