### ISSUE TITLE
Master detail highlight / select / multiselect visual design

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#3581]
There are some aspects of selected-row-highlight and view-details that are not ideal when using master detail. A design cycle to address this yielded good results but exposed a larger concern about how such changes would impact other components. Master detail does need some small changes but doing them at this time would introduces unintended consequences re: consistency.

Using this issue to hold the work that has been done on this until it can be addressed more holistically.

**Comment by colinreedmiller** [comment]
Design exploration looking at one solution: 
[https://www.figma.com/file/J2wJ4mEwqTN0KNwp2WrWDb08/Master-detail-2005?node-id=0%3A1](url)

**Comment by sdurnov** [comment]
> Design exploration looking at one solution:
> [https://www.figma.com/file/J2wJ4mEwqTN0KNwp2WrWDb08/Master-detail-2005?node-id=0%3A1](url)

Url is dead

**Comment by colinreedmiller** [comment]
The implications and consequences of making this change are too monumental at present. The analysis stands but addressing it will need to be part of a more holistic approach.
