### ISSUE TITLE
no documentation for css classes clr-hidden-[size]-down / up

### ISSUE THREAD

**Issue by ymanvieu** [vmware/clarity#3586]
hello,

i just discover by browsing the issues page that clarity design has css classes for hiding/displaying  html elements bases on screen size as bootstrap does.

i didn't find any documentation about it and it would be really nice to have it.

can you take a look at it ?

thanks

**Comment by ymanvieu** [comment]
any update ?

**Comment by gnomeontherun** [comment]
No longer an issue or resolved in the upcoming website work. Closing as resolved.
