### ISSUE TITLE
Put placeholder above input field when you start typing in it.

### ISSUE THREAD

**Issue by Igor9669** [vmware/clarity#359]
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
When you don't use labels for inputs it would be nice to have an option that when user starts typing in the input then it's placeholder moves up. Like in material design. 


### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@Igor9669 that's a pretty good suggestion. We'll have to look at what that means in the context of the way forms are currently organized as well as when it relates to things like accessibility and the relationship of forms to other components to make good recommendations of when to use such a pattern if implemented. Adding @yenmade to make sure we take a look.

**Comment by reddolan** [comment]
@Igor9669 we are looking at this in conjunction with many other form element designs and experiences.

**Comment by reddolan** [comment]
We won't be pursuing this due to usability and accessibility issues
