### ISSUE TITLE
Deprecate inline wizard

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3591]
Now the Stepper exists, the need for an inline wizard (which is undocumented and psuedo-supported) is no longer needed or recommended.

**Comment by AlexMarcuBytex** [comment]
What implies this issue? Should we fully delete it from the code? If you can tell me some steps, i ll solve this.

**Comment by AlexMarcuBytex** [comment]
Can you assign me on this? Im working on this following the steps presented in the PR review. Thanks!
