### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3595]
## Describe the bug
I upgraded to Clarity version 2.0.2 and having some issues in compiling the project.
![image](https://user-images.githubusercontent.com/1977391/60750732-98b47f00-9fdf-11e9-8c4c-1aa153f6b38d.png)

## Expected behavior
Should be able to compile without errors

## Versions

**App**

* Angular: 8.0.0
* Node: 10+
* Clarity: 2.0.2

**Device:**

* Type: Dell XPS 13
* OS: Windows 10 Enterprise Edition
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by whizkidwwe1217** [comment]
It seems like when I do an `npm install --save @clr/icons@latest @clr/angular@latest @clr/ui@latest` downgrades the Clarity reference to 1.1.5.

![image](https://user-images.githubusercontent.com/1977391/60750824-ad454700-9fe0-11e9-8f07-a604cf43b07b.png)

The workaround is to install the packages with the specific version. I'm not sure if I installed the packages incorrectly or there might be an issue in Clarity's npm registry. I'll just let this ticket open and let you take a look on it. Thanks.

**Comment by gnomeontherun** [comment]
The `latest` tag got applied to the wrong version with our last release, I've put it back on 2.0.2. This should be resolved.
