### ISSUE TITLE
Show selected value in dropdown header.

### ISSUE THREAD

**Issue by ripley** [vmware/clarity#3597]
## Summary

_There should be one option for dropdown component to show selected value in header._

* What is the change?
_Dropdown component has an option to show selected value in header._

* Why should it go in Clarity?
_It's  confusing not showing selected values when multiple dropdowns are used to provide filter option._

* Does this change impact existing behaviors? If so how?
_This is an optional feature, behavior can be kept same as before._

* If this change introduces a new behavior, is this behavior accessible?
_Yes._

## Use case
Use dropdown to provide filter options, each time a value is selected a new criteria is added.

## Examples

_Please see link below from airbnb, each time a value is selected for a dropdown it's shown in the header.._
[Airbnb filters](https://www.airbnb.com/s/homes?refinement_paths%5B%5D=%2Fhomes&click_referer=t%3ASEE_ALL%7Csid%3Af627f961-26ac-47f0-84df-e860523e08f9%7Cst%3ALANDING_PAGE_MARQUEE&title_type=NONE&search_type=filter_change&checkin=2019-07-09&checkout=2019-07-11&adults=1&work_trip=true&ib=true&price_min=75&room_types%5B%5D=Entire%20home%2Fapt&s_tag=hNZw42TC)

## Workarounds

_It's possible to implement this feature (or switch to Selected component, by adding an apply button) by overriding Dropdown's behavior, but I think it'll be more user friendly and elegant to provide this natively_

**Comment by gnomeontherun** [comment]
Can you tell me if the upcoming work on #248 will address your request? Dropdowns are not really a replacement for a select box.

**Comment by ripley** [comment]
@gnomeontherun Thank you for the response.

The usage guideline for dropdown and select in clarity document says:

- Dropdown menus present a list of options that take an immediate action or navigate the user outside of the current context.
- Select boxes present a list of options that the user can choose from and apply to an input field.

The behavior here for Dropdown is required, we need to put multiple Dropdowns (5 ~ 6) as filters and the page will refresh automatically each time any of them is changed, user may lose track if a dropdown always show its header text instead of selected value.

https://github.com/vmware/clarity/issues/248 looks like an awesome enhancement to select, it's not quite the same as this issue tho.

**Comment by ripley** [comment]
Turned out this can be worked around easily, closing the issue.
