### ISSUE TITLE
[Improvement] CSS layout util classes are too long

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3598]
## Summary

I see that you added few bootstrap-like css utility classes for flex, for visibility, etc.
This is great, but I think you can make it better.

Currently I see long classes names for individual flex property, like `.clr-justify-content#{$infix}-between`. Try combining few of them and you'll get unreadable code.

* What is the change?

Add short versions of classes names.
For instance, instead of `.clr-justify-content#{$infix}-between` we can have `.clr-jcb-#{$infix}`.

I'm pretty sure, that most people who use flex classes are pretty familiar with them and such short name will work just fine.

Second - I don't see such class for `display: flex`. I guess it would be helpful to add `.clr-flex` class or/and add this css value to all other flex utilty classes.

* Why should it go in Clarity?
For developers convenience

* Does this change impact existing behaviors? If so how?
No

* If this change introduces a new behavior, is this behavior accessible?
N/a

## Workarounds

Writing an using such classes on my own.

**Comment by mathisscott** [comment]
@sdurnov 
Thanks for submitting this issue!

As a guideline, Clarity has avoided use of acronyms and abbreviations in variable names, properties, components, etc. It would be problematic for us to deliver a library that developers needed a glossary to use.

So this is not a direction we are likely to pursue. In the future (3.0), you may find it easier to implement your own shorter CSS classnames using Clarity. But outside of making it easier, I don't think we would introduce classnames that use acronyms or abbreviations.
