### ISSUE TITLE
input allows invalid engineering notation

### ISSUE THREAD

**Issue by rdfeist** [vmware/clarity#3601]
## Describe the bug
Using clrInput type="number" allows for invalid format entry using the 'e' character.  For instance: "1.23e5e", "ee", etc.  It evaluates to a null or empty value, but ideally it would not allow the input.

## How to reproduce
<clr-input-container [formGroup]="controlFormGroup" style="display: inline; margin-right: 10px;">
   <input *ngIf="controlFormGroup.get('dataType').value === 'Real'"
    clrInput type="number" class="no-spinners"
    [id]="name"
    [readonly]="!editing"
    formControlName="value"
  />
</clr-input-container>

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This is correct, because e is used in some numeric values for exponents. This is as expected and there isn't anything here for Clarity to do. You can opt to add your own validator or workaround to block it if you wish.

https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in
