### ISSUE TITLE
Tooltip on signpost trigger is shown on hovering the signpost content too.

### ISSUE THREAD

**Issue by aswami-vmware** [vmware/clarity#3607]
Steps to reproduce:

Added a signpost around an icon. Icon is the signpost trigger. Added some content in the signpost. 
Also added a tooltip around the icon such that hovering the icon should show up the tooltip and clicking the icon should open up the signpost.

observed behaviour: on clicking the icon, signpost opens up but the tooltip is also shown. Moreover, tooltip is also shown on hovering the signpost content.

**Comment by gnomeontherun** [comment]
With bug reports, please use our bug template in the future and have a demonstration so we can be sure to see what you're seeing.

As far as having a signpost and tooltip on the same element, this behavior sounds exactly as expected from the technical implementation. However, it doesn't really make sense to combine both onto the same element, you should use one or the other. Tooltips are meant to show on hover, and the signpost icon (and signpost content) would be considered part of the tooltip trigger. Ultimately, this is not recommended or supported for usability reasons, as you have two triggers on the same elements and this is also a violation for accessibility reasons.

Closing as not an issue.
