### ISSUE TITLE
Add filter property to clr-tree-node

### ISSUE THREAD

**Issue by ArturGudiev** [vmware/clarity#3608]
## Summary

Add possibility to filter tree nodes in clarity recursive tree. In simple case I would use *ngIf  in wrapped ng-container directive to filter some tree nodes but in this case it's impossible because nothing is shown.

* What is the change?
Add property to clr-tree-node to filter nodes. 

* Why should it go in Clarity?
Now it is impossible to filter tree nodes in recursive trees in templates. 

* Does this change impact existing behaviors? If so how?
No, it doesn't. 

* If this change introduces a new behavior, is this behavior accessible?
Yes. 

## Use case
I have a tree. I would like to filter it by condition in template without extra fields and methods in component. 

## Examples
see https://stackoverflow.com/questions/56971793/use-ngif-to-filter-tree-nodes-in-clarity-recursive-tree

## Workarounds

Create another field in template (e.g. displayedNodes) and filter existing nodes there.

**Comment by Jinnie** [comment]
Related (though no fully equivalent) to https://github.com/vmware/clarity/issues/3603

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
