### ISSUE TITLE
DataGrid layout is akward

### ISSUE THREAD

**Issue by zivanov123** [vmware/clarity#361]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
DataGrid cannot be easily used and layed out as its height depends on the number of rows which were specified.
Much better would be if it scales the content in order to fit in its parent.
The number of rows can be used, however if there is not enough space to display them - a scroller to be added.

### Actual behavior
Currently the content does not scale to fill the parent.
See this plunker for example with parent which fills the page, but the grid stays in the middle..
The same can be achieved with hardcoded height to 300px of the parent (this way the grid will overflow below the parent bottom line)

https://plnkr.co/edit/DxMl8v?p=preview

### Reproduction of behavior
https://plnkr.co/edit/DxMl8v?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by rreymer** [comment]
I experience similar issue. I suggest to have a scrollbar that appears inside the datagrid body when there are a lot of rows in the datagrid. This can be exposed as an option to the datagrid itself - if datagrid content should be scrollable or not.

**Comment by mmayors** [comment]
I'm experiencing similar issues with the datagrid. I'd like to place the datagrid in a dropdown and allow the user to select a row. If the total rows exceed the height of the datagrid's parent then I'd like scrollbars to appear to scroll within the grid. If anyone has any workarounds let me know.

**Comment by youdz** [comment]
This was fixed as part of #511. Datagrids do not expand to fill the parent by default, but you can now style the `<clr-datagrid>` element yourself with whichever height you want, and the body will scroll if the height you choose cannot accommodate all the rows. In your case, to fill the parent, you just want `height: 100%`.
