### ISSUE TITLE
Conditionally displaying the expandable row hides few columns

### ISSUE THREAD

**Issue by sivaah** [vmware/clarity#3617]
## Describe the bug

Conditionally displaying the expanded rows, hides the rows which are not expandable.
## How to reproduce

[https://stackblitz.com/edit/clarity-light-theme-v2-nkmvxn](https://stackblitz.com/edit/clarity-light-theme-v2-nkmvxn)

<img width="495" alt="Screen Shot 2019-07-12 at 1 05 42 PM" src="https://user-images.githubusercontent.com/6573919/61110858-df095280-a4a5-11e9-9597-e671cb29d0f5.png">

Here first two rows are hidden.

1.  Go to  https://stackblitz.com/edit/clarity-light-theme-v2-nkmvxn
2.  The first two rows were not visible

## Expected behavior

The rows which are not expandable should be visible.

## Versions

**App**

* Angular: [8.1.1]
* Node: [10.10.0]
* Clarity: [2.0.2]

**Device:**

* Type: [MacBook]
* OS: [iOS]
* Browser [chrome]
* Version [75.0.3770.100]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
It looks like you want to open specific rows when the datagrid is populated with users. 

There is no need to use an `ng-container` with `ngProjectAs`. Clarity provides the `ClrIfOpen` structural directive that will handle the conditional state for the application. 

I modified your example and used desugared syntax to set the row detail open state based on the user data provided. https://stackblitz.com/edit/clarity-light-theme-v2-hqcuku

Here is the relevent line:
```
<clr-dg-row-detail [clrIfExpanded]="user.expand" (clrIfExpandedChange)="handleChange($event)">
```

Please let me know if I mis-understood your use case.

**Comment by sivaah** [comment]
@hippee-lee you understood wrongly, may be my example confused you. I want to make only few rows expandable which has additional info to display.

The below feature is broken after upgrade to V2, I can't provide my live project details and screenshots here.
<img width="897" alt="Screen Shot 2019-07-13 at 6 43 54 AM" src="https://user-images.githubusercontent.com/6573919/61165101-a7e48100-a539-11e9-8523-d49ce69a1fd4.png">

I have updated my example code to give you more clarity on the issue.
https://stackblitz.com/edit/clarity-light-theme-v2-nkmvxn

Here i want only row 3 should have expand icon and can be expanded.

**Comment by hippee-lee** [comment]
Thanks for clarifying. It looks like we need to take a closer look at this.

**Comment by hippee-lee** [comment]
My suspicion is that after the changes to ViewEngine from Angular v7 -> v8 this isn't working any more: https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid-row-detail.ts#L60

Also related: https://github.com/angular/angular/issues/30059#issuecomment-486001438

**Comment by Jinnie** [comment]
Found the cause, it's a complicated initialization race, which leads to a view being attached too early and to the wrong template outlet, which gets discarded in a later moment.
There's an easy fix.
