### ISSUE TITLE
Dark theme text colors

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#3618]
Some text colors in the dark theme are low contrast - they pass a11y but need a little attention. Mostly concerned with values in label / value pairs and the text area in forms.

#ADBBC4   |   201,16,72
on #17242B 

other text is:
#E9ECEF   |   210,16,93

**Comment by colinreedmiller** [comment]
Examination of VMC on AWS shows the text color in question is <body> dark theme thus changing it will result in the change occurring everywhere. Additional uses of a light grey are in gauge components which are not in Clarity. Original appearance of this issue was surfaced in form elements: text area.

**Comment by gnomeontherun** [comment]
We revamped the color system, and I believe this should have been addressed as part of that work. Closing as resolved.
