### ISSUE TITLE
clrDgLoading with ClrLoadingState

### ISSUE THREAD

**Issue by mathisloge** [vmware/clarity#3620]
## Describe the bug

Datagrid is not working with ClrLoadingState

## How to reproduce
[https://stackblitz.com/edit/clarity-light-theme-v2-sajlym](https://stackblitz.com/edit/clarity-light-theme-v2-sajlym) 

1.  Follow the provided link
2.  After two seconds the loading var is set to success
3.  The Loading Indicator of the Datagrid is still visible

## Expected behavior

After setting ClrLoadingState to Success, im expecting the loading indicator to fade out.
Same as the "Demo Button" showing up in the demo.

## Versions

**App**
* Clarity: 2.0.2

**Comment by coryrylan** [comment]
A temporary workaround is to set the `loading` state to a boolean true/false instead of using `ClrLoadingState`.

**Comment by mathisloge** [comment]
Yes. Currently im using a timeout after 800ms to set it to default, since i would like the indicator on a button using the same loading var.

**Comment by gnomeontherun** [comment]
We've discussed this and we don't intend to support this case. Please just use a boolean.
