### ISSUE TITLE
Stack view action button 'btn-link' class problem

### ISSUE THREAD

**Issue by amrsalama** [vmware/clarity#3621]
## Describe the bug

The action button of Stack View has problem with `btn-link` class.

![Screenshot](https://user-images.githubusercontent.com/15939360/61183846-7dccb500-a646-11e9-93d8-6b3f7b55a2f4.png)

![Screenshot](https://user-images.githubusercontent.com/15939360/61183847-80c7a580-a646-11e9-84e7-ef7710628e50.png)

## How to reproduce

It is already on the docs example https://clarity.design/documentation/stack-view

**Comment by mathisscott** [comment]
@amrsalama 
I cannot reproduce this. If you want an outlined button that doesn't stick out to the right, just remove the `btn-link` class. The `btn-link` class should not have an outline, so I'm not sure what has been customized in your implementation that broke that.

If you feel this is still an issue, please submit a stackblitz.
