### ISSUE TITLE
Can't download Namespace icon

### ISSUE THREAD

**Issue by Stela-Stamenkova** [vmware/clarity#3624]
I tried to download the Namespace icon from Clarity website and received the following message: 
This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.

* MacBook
* OS: High Sierra
* Browser: Chrome & Safari

**Comment by mathisscott** [comment]
@Shijir 
What do we need to do to get those downloads working? Is there a script that needs to be run?

**Comment by gnomeontherun** [comment]
We need to add the icons into the https://github.com/vmware/clarity-assets repository for them to be downloadable, we might have missed this step. We need to get a good document drawn up for adding icons.

**Comment by mathisscott** [comment]
I did miss this step. I forgot about the assets repo having the icons in it. Do I just push them up there then?

**Comment by gnomeontherun** [comment]
Yes, that can solve it because the website redirects to GitHub to download, if its not there you get 404.

**Comment by mathisscott** [comment]
Got it. I'm loaded down with meetings today. But I will try to push those up when I get time.

**Comment by mathisscott** [comment]
Fixed by https://github.com/vmware/clarity-assets/commit/865169f6ceeaa06152b653bb9d22d2b316bc7ba9
