### ISSUE TITLE
pod icon missing

### ISSUE THREAD

**Issue by andyjmorgan** [vmware/clarity#3627]
## Describe the bug

the pod icon appears available on the clarity website but instead displays an error.

<clr-icon shape="pod"></clr-icon>

interestingly if you try to download the svg it's empty.

## How to reproduce

https://clarity-light-theme-v2-jurf1b.stackblitz.io

modify an icon shape to "pod"

## Expected behavior

the pod icon should appear

## Versions

"@angular/core": "^8.1.1",
"@clr/angular": "^2.0.2",
"@clr/icons": "^2.0.2",
"@clr/ui": "^2.0.2",

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This icon isn't released yet, but it accidentally showed up in our website. Wait for the next release to get it. Sorry for the confusion, we didn't mean for that to get published yet.
