### ISSUE TITLE
Design Resources Update

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#3628]
Updates
- Edit copy to remove `(beta)`
- Swap the order of Figma and Sketch libraries
- Add Color Library
- Update versions of resources to 2.2.0
- Add Google Analytics tracking on each download button

[Link to proposed changes](https://www.figma.com/file/M7V0wZcfGAuxBJah6JRxDS7m/3628-Design-Resources-update?node-id=0%3A1)

Figma Resources
- [UI Library - Light](https://www.figma.com/file/v2mkhzKQdhECXOx8BElgdA/Clarity-UI-Library-light-2.2.0)
- [UI Library - Dark](https://www.figma.com/file/wRYSrWSffZXcdQuiolwkym/Clarity-UI-Library-dark-2.2.0)
- [Icon Library](https://www.figma.com/file/40gaW7S2yP7B0ME6QNDEsR/Clarity-Icons-2.2.0)
- [Color Library](https://www.figma.com/file/mxn3xoLg2mkjMqf5GGYUzw/Clarity-Colors-2.2.0)

Sketch Resources
- [UI Library - Light](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Versions/Clarity-UI-Library-2.2.0.sketch)
- [UI Library - Dark](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Versions/Clarity-UI-Library-dark-2.2.0.sketch)
- [Icon Library](https://gitlab.eng.vmware.com/DesignRepo/Clarity/Libraries/blob/master/Versions/Clarity-Icons-Library-2.2.0.sketch)

**Comment by raphaelschaad** [comment]
Why "Swap the order of Figma and Sketch libraries"? :)

**Comment by mathisscott** [comment]
As a company, we are adopting Figma as our preferred design tool. This means the Figma library will be our primary library in the future.

**Comment by raphaelschaad** [comment]
Got it, interesting to see the shift happening.
