### ISSUE TITLE
option color error of select component in the dark theme

### ISSUE THREAD

**Issue by kefengwei** [vmware/clarity#3633]
![image](https://user-images.githubusercontent.com/4326865/61438035-1cbc1e80-a971-11e9-9a38-80c5429657be.png)
The stackblitz link:[https://stackblitz.com/edit/clarity-dark-theme-v2-ezaea7](url)

**Comment by mathisscott** [comment]
@kefengwei 
The dropdowns in HTML select elements are notoriously tricky to style across browsers. We don't add styles to the vanilla select elements. If you need them to look a certain way, you should look into another widget that replicates the functionality or keep an eye on [the combobox issue we are currently working on](https://github.com/vmware/clarity/issues/248).
