### ISSUE TITLE
With Clarity v1.1.5, disabled attribute doesn't work with buttons under dropdown

### ISSUE THREAD

**Issue by jkjha** [vmware/clarity#3634]
## Describe the bug

With Clarity v1.1.5, disabled attribute doesn't work with dropdown. This seems to be regression of https://github.com/vmware/clarity/pull/3417

```
<clr-dropdown>
        <div clrDropdownTrigger >
          <span>Click Me</span>
        </div>
        <clr-dropdown-menu *clrIfOpen>
          <button type="button" clrDropdownItem
        [disabled]="true" clrTooltipTrigger>Transfer </button>
        </clr-dropdown-menu>
      </clr-dropdown>
```

This used to work with all version <1.1.5 . 

## How to reproduce

Please check this stackblitz: https://stackblitz.com/edit/clarity-custom-theme-v1-0-6kylnz?file=src%2Fapp%2Fapp.component.html

1. Go to https://clarity-custom-theme-v1-0-6kylnz.stackblitz.io
2. Click on Click Me link which is a dropdown.

## Expected behavior

Transfer button should be disabled.

## Versions

**App**

* Angular: 7.2
* Clarity: 1.1.5

## Additional notes

This may be similar : https://github.com/vmware/clarity/issues/3610

**Comment by Jinnie** [comment]
I confirm this is an issue - it looks like we promoted [disabled] to @Input on the clrDropdownItem so we can sync it with aria-disabled. 
Unless we intentionally do not want to use disabled (I have some memories that disabled menu items should be focusable), this is broken.
