### ISSUE TITLE
option for clr-wizard to know which button is clicked on clr-wizard-step

### ISSUE THREAD

**Issue by chunghha** [vmware/clarity#364]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
I like to have an option for clr-wizard to know which button is clicked on clr-wizard-step so I can use it to differentiate logic on my clrWizardPageOnCommit function.

### Actual behavior
I can't find a way to distinguish which button is clicked on clr-wizard-step. Please see the demo in the plnkr below. If there is one already then please document how to use it with an example.

### Reproduction of behavior
https://plnkr.co/edit/hkaDZ8OWQlq0ZQ7O7kNA?p=preview
Go to Account Page in the Subnav. If you finish 3rd step, you can go to the Home page. But, how to know if CANCEL button clicked on the 3rd step as I want to go to the About page.

### Environment details

* **Angular version:** 2.4.3

* **Clarity version:** 0.8.2

* **OS and version:** Windows 7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by chunghha** [comment]
Probably what I would like to have is clrWizardPage**OnCancel** option which is not there yet.

**Comment by jeeyun** [comment]
Hi @chunghha, this is our bad. We actually merged in a PR last month that added this option (https://github.com/vmware/clarity/pull/183). The option is called just what you suggested: `clrWizardOnCancel`. So if your clarity-angular version is 0.7.4 or later, it should have it so give it a try.

Our documentation is outdated and we need to update it. I'll tag this issue appropriately so that either I or @mathisscott can update our documentation.

**Comment by chunghha** [comment]
@jeeyun thanks for letting me know the option.

updated plnkr:
https://plnkr.co/edit/pEcTShQmRykVaIhbmmcn?p=preview

onCancel() works fine on all three steps. But, onCommit() does not with the cancel option. Event emitted twice, one from onCommit() and another from onCancel(). Latter event shouldn't be emitted. Please try the plnkr in this comment, you will see alert twice when you click FINISH button on the 3rd step.

**Comment by jeeyun** [comment]
Yes you are right. Thanks for updating the plnkr. It seems that we are treating close/cancel as synonymous in some of our code when we should distinguish between them. I'll float it up to the team and see when we can address this.

**Comment by mathisscott** [comment]
We are aiming to introduce this enhancement with the work we are doing to improve the wizard component overall.

Part of: #156

**Comment by mathisscott** [comment]
Closing because it's now referenced in #156. Intended to go in with that change.
