### ISSUE TITLE
In clr-wizard, missing next event

### ISSUE THREAD

**Issue by Patafix31000** [vmware/clarity#3641]
In clr-wizard, next() function seems to be missing in v2 when clicking on Next button.
It results in: `ERROR TypeError: _this.wizard.next is not a function`

Seems the same problem as commit [54060e](https://github.com/vmware/clarity/commit/54060e55bc6ee2c54fc488c8c721459e957f5359)

## How to reproduce

Open a wizard modal, validate form and click on next button.

## Versions

* Angular: [8.1.2]
* Clarity: [v2.0.2]

**Comment by hippee-lee** [comment]
Hi there, 
When filing a bug report please include a stackblitz link that allows us to investigate.
