### ISSUE TITLE
Wizard title and body shows blue outline on chrome

### ISSUE THREAD

**Issue by sivaah** [vmware/clarity#3643]
## Describe the bug

Wizard title and body elements has attribute tabindex="0" which cause title and body accessible and shows blue color outline on chrome and dotted outline on firefox.

The issue is not seen in [v0.13](https://vmware.github.io/clarity/documentation/v0.13/wizards)

The wizard suppose to have accessibility only on Step Titles, Close Button and bottom actions, since these are clickable and can do some actions on selection but title and body doesn't do any action on selection.

## How to reproduce

<img width="906" alt="Screen Shot 2019-07-24 at 1 19 59 PM" src="https://user-images.githubusercontent.com/6573919/61775722-16b5ba00-ae17-11e9-8b87-5b5a1054d1df.png">
<img width="890" alt="Screen Shot 2019-07-24 at 1 20 34 PM" src="https://user-images.githubusercontent.com/6573919/61775734-1ae1d780-ae17-11e9-83ba-071e35d8e3b1.png">

1.  Go to https://clarity.design/documentation/wizards
2.  Open any wizard example and click on title or body

## Expected behavior

The wizard header and body should not be clickable or accessible using keyboard
1. Go to https://vmware.github.io/clarity/documentation/v0.13/wizards
2. Open any wizard example and click on title or body

## Versions

**App**

* Angular: [7, 8]
* Node: [8.10.0]
* Clarity: [2.x, 1.x]

**Device:**

* Type: [MacBook]
* OS: [iOS]
* Browser [e.g. chrome, Firefox]
* Version [75.0.3770.142]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
This functionality was added to allow keyboard only users the ability to scroll with arrow keys.

**Comment by sivaah** [comment]
> This functionality was added to allow keyboard only users the ability to scroll with arrow keys.

@hippee-lee 
I can agree on the reason for wizard body but i'm not clear on why keyboard only user has to scroll on wizard modal title. 

`<span class="modal-title-text" tabindex="0"><!---->Page 1</span>`

I tried giving a paragraph on the wizard title to verify whether any scrollbars introduced to scroll on title but i don't see scroll behaviour on the modal title with large text.

<img width="593" alt="Screen Shot 2019-07-24 at 10 33 45 PM" src="https://user-images.githubusercontent.com/6573919/61813368-2b1fa400-ae63-11e9-962c-2f0bc0915c46.png">


I feel this bug is still valid for wizard title.
