### ISSUE TITLE
date picker in mobile view

### ISSUE THREAD

**Issue by ponna93** [vmware/clarity#3648]
## Describe the bug
Date picker in mobile view is not working we are using clarity version 1
_A clear and concise description of what the bug is, and the conditions when it occurs._
 when user selects the date, that selected date is not shown in UI but  that is (calendar info is taken )picked when u schedule pickup u can see that selected date is proper.
## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  open vm clarity date picker on mobile
2.  selected any date
3.  u will not see the selected date in ui
4.  but u will be able to see the selected date

## Expected behavior
selected date should be visible in mobile 
## Versions
1
**App**

* Angular: 7
* Node: 10.15.0
* Clarity: 1

**Device:**
mobile browser

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
From the documentation [here](https://clarity.design/documentation/datepicker): 

> We automatically disable the Clarity Date Picker on small mobile phones. This is done because unlike desktop browsers, most mobile browsers have a built-in date picker. These built-in date pickers are optimized to work on mobile devices and provide an experience which the user is already familiar with.
> Clarity Date Picker is shown at screen width 768px and above.
