### ISSUE TITLE
Dynamically changing page size in datagrid may throw an error

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#3650]
## Describe the bug

Having
```
<clr-dg-pagination #pagination [clrDgPageSize]="pageSize">
```
if the bound variable `pageSize` is changed to a size bigger than before, an exception is observed:
```
preview-d2335ca5bdb955611c1cb.js:1 ERROR TypeError: Cannot read property 'get' of undefined
    at ClrDatagridRow.get [as _view] (datagrid-row.ts:229)
    at eval (datagrid.ts:216)
    at Array.forEach (<anonymous>)
    at QueryList.forEach (query_list.ts:100)
    at eval (datagrid.ts:215)
    at SafeSubscriber.schedulerFn [as _next] (event_emitter.ts:116)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:265)
    at SafeSubscriber.next (Subscriber.ts:207)
    at Subscriber._next (Subscriber.ts:139)
    at Subscriber.next (Subscriber.ts:99)
```
## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to https://stackblitz.com/edit/datagrid-page-size-issue?file=src/app/app.component.html
2.  Click on '2'
3.  Then click on '8'
4.  See the error in the developer console

## Expected behavior

No error on page size change.

## Versions

**App**

* Clarity: 2.1.0

## Additional notes

- What causes the issue is the get method in the wrappedInjector of the view getter here:
```
  datagrid-row.ts:
  ----------------
  public get _view() {
    return this.wrappedInjector.get(WrappedRow, this.vcr).rowView;
  }
```
- If the value in Page#size is changed directly, the page size is updated without error.
- Also a chocolate error is thrown, which is intentionally suppressed in the demo, but I'm not really sure it's expected.

**Comment by mathisscott** [comment]
@Jinnie 
Could you triage this and then add an estimate and move it to the backlog if you feel it's valid?

**Comment by bdryanovski** [comment]
Is this still valid? It's from Clarity v2 - I try reproducing it at v4 but without luck?

@Jinnie

**Comment by Jinnie** [comment]
Updated stackblitz (v12):
https://stackblitz.com/edit/clarity-dark-theme-clr12-cds5-syppty?file=src%2Fapp%2Fapp.component.ts
Check:
![Screen Shot 2021-11-10 at 15 33 13](https://user-images.githubusercontent.com/1798828/141122553-d58311ea-35ac-46b6-a90c-9bf940809c68.jpg)
Conclusion: Yes, it's still valid.
