### ISSUE TITLE
Spinner components colors

### ISSUE THREAD

**Issue by Yoozii** [vmware/clarity#3653]
Select one ... (check one with "x")

[ ] bug
[ ] feature request
[X] enhancement

Expected behavior
To be able to change the color of the spinner to any custom background of spinning block.

Current behaviour
Spinner only spins in blue in both regular and dark theme 

https://clarity.design/documentation/spinners

**Comment by gnomeontherun** [comment]
Thanks for the suggestion, we'll consider it! Do you have use cases or more details to share about it and why it would be meaningful?

**Comment by Yoozii** [comment]
I am working on a project for my company following specific branding guide lines with specific color codes. I customised the whole theme based on our brand by changing the "clarity-custom-theme.scss". I couldn't change the spinner color or the highlight on click color which are blue.

In my portal I use alot of graphs therefore alot of spinners to when the graphs are loading and it all loads in blue. I really love using clarity and I would love to see it more flexible with themes and color pallets specially for the artistic and following branding guide lines like me. 

I resolved this previously on clarity V1 by adding `$clr-spinner-color: #7DA830 !important;` to the scss file but this doesn't work now that I updated to clarity V2. 

<img width="197" alt="Screen Shot 2019-07-31 at 12 04 09" src="https://user-images.githubusercontent.com/41358494/62194735-808c1180-b38b-11e9-8422-471b068ae5af.png">

**Comment by AlexMarcuBytex** [comment]
Is this issue still valid? If yes, do you have any ideas to implement a variable coloured spinner? I tried to pass a css variable with a custom color from html, but as the browser cant read variables like `--color: #FFFFFF`, its impossible to draw the svg. I think that there should be a group of custom colors available ( let s say 4 or 5 ), each with its class.

**Comment by mathisscott** [comment]
@AlexMarcuBytex 
This issue is still valid. It would require a dive into an API change for the spinner. It's not a high priority for us at the moment, as features go, because we have work-in-progress on a circular progress bar as well as CSS custom variables that make the future of this feature less certain.

**Comment by AlexMarcuBytex** [comment]
Cool then! Thanks for the answer!

**Comment by gnomeontherun** [comment]
Consider using the Clarity Core version of the component for your application which should not have this concern. In an effort to clean up our backlog and focus our attention, I’m going to close this as resolved by the implementation of progress circles in Clarity Core.
