### ISSUE TITLE
Datagrid with pagination in a modal not showing lines unless toggling it

### ISSUE THREAD

**Issue by audiozoa** [vmware/clarity#3656]
## Describe the bug

When trying to use a datagrid with pagination in a modal the data does not appear as line items unless using an *ngIf

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-dvgs5q

1.  Click Open Modal (data show as missing)
2.  Click Toggle Table (disables table)
3.  Click Toggle Table again (shows table with data)

## Expected behavior

Show the line items of a datagrid on modal open

## Versions

**App**

* Angular: 8.0.1
* Node: 10.13.0
* Clarity: 2.0.1

**Device:**

* Type: Dell
* OS: Windows 10
* Browser: Chrome, Firefox

**Comment by audiozoa** [comment]
Another way around it currently is to set the [openModal] to perpetually be true and add an *ngIf on the component tag

**Comment by gnomeontherun** [comment]
This is a known issue and has a few other older issues here. Your workaround is correct, and it is due to lifecycle of how components are instantiated. 

Follow https://github.com/vmware/clarity/issues/895 for updates on this, until then apply the workaround.
