### ISSUE TITLE
Fix #3606 Update line-height for clr-control-label causing extra spacing for wrapped lables

### ISSUE THREAD

**Issue by davidrourke** [vmware/clarity#3658]
## Describe the bug

The fix for line-height for clr-control-label (#3606) is causing extra line spacing for wrapped labels.

In version 1.1.5 wrapped labels look like this:

![image](https://user-images.githubusercontent.com/25104184/62250087-03c45c00-b3ba-11e9-930d-b1f30a5e8b32.png)

In version 1.2.0 wrapped labels look like this:

![image](https://user-images.githubusercontent.com/25104184/62250169-39694500-b3ba-11e9-8f6b-e7db847887ae.png)

## How to reproduce

I've provided a stackblitz example:

https://clarity-light-theme-v1-0-fnr3rl.stackblitz.io

## Expected behavior

Wrapped label should should not have the extra spacing.

## Versions

**App**

* Angular: 7.2.0
* Node: 10.x
* Clarity: 1.2.0

**Device:**

* Type: MacBook Pro
* OS: 10.14.5 
* Browser Chrome
* Version 75.0.3770.142

**Comment by gnomeontherun** [comment]
Thanks for pointing this out, the backport to v1 was incorrect and we need to fix this.

**Comment by gnomeontherun** [comment]
Closed by #3674
