### ISSUE TITLE
Including clarity-icons in an Angular2 app compiled with webpack.

### ISSUE THREAD

**Issue by juanargote** [vmware/clarity#366]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I am trying to follow [Angular2's webpack configuration guidelines](https://angular.io/docs/ts/latest/guide/webpack.html). Based on those, I expect that importing clarity-icons.min.js in a vendor.ts file that I include as an entry in my webpack configuration file should also allow me to use clarity-icons throughout my web app (see below).

./webpack.config
```
module.exports = {
  entry: {
    'polyfills': './src/polyfills.ts',
    'vendor': './src/vendor.ts',
    'app': './src/bootstrap.ts'
  },
  ...
}
```

./src/vendor.ts
```
...
import "../node_modules/mutationobserver-shim/dist/mutationobserver.min.js";
import "../node_modules/@webcomponents/custom-elements/custom-elements.min.js";
import "../node_modules/clarity-icons/clarity-icons.min.js";
...
```

### Actual behavior

However, this approach results in the following error traces:

> ERROR in [at-loader] node_modules/clarity-icons/src/index.ts:12:13 
>    Property 'ClarityIcons' does not exist on type 'Window'.

> ERROR in [at-loader] node_modules/clarity-icons/src/index.ts:15:12 
>    Property 'ClarityIcons' does not exist on type 'Window'.

> ERROR in [at-loader] node_modules/clarity-icons/src/index.ts:18:5 
>    Cannot find name 'customElements'.

And instead I am forced to include the `clarity-icons.min.js` file as a script in my `index.html` file. Is there anything I am missing to be able to include clarity-icons as a dependency to be compiled by webpack?

### Environment details

* **Angular version:** 2.0.X
2.4.1
* **Clarity version:** 
0.8.2
* **OS and version:** 
macOS Sierra 10.12.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by Shijir** [comment]
Hi @juanargote, could you try removing `../node_modules/` to load your modules? I believe webpack already resolves these paths for you. So your `vendor.ts` would look like this:

```
import "mutationobserver-shim/dist/mutationobserver.min.js";
import "@webcomponents/custom-elements/custom-elements.min.js";
import "clarity-icons";
```

Also, it's ideal to have `custom-elements.min.js` and `mutationobserver.min.js"` in your `polyfills.ts` as they are polyfill modules.

**Comment by juanargote** [comment]
Hi @Shijir, you are totally right. After removing the `../node_modules/` prefix from my paths the import worked just fine. I had previously opened [a question on Stackoverflow](http://stackoverflow.com/questions/41292255/how-to-enable-clarity-icons-in-an-angular2-app-through-a-webpack-entry) about this issue. Feel free to answer there if you want. Otherwise I can answer it myself and point to this thread. Thanks for the quick reply!

**Comment by juanargote** [comment]
Hi again @Shijir, I just noticed that even though the webpack compilation now works fine, some icons that are enclosed in buttons are now 36px large by default, their orientation is not modified by adding `[up, down, right, left]` to the shape or an explicit `dir` attribute, and they do not respond to changes in their `size` attribute. See the image and its corresponding code snippet below:

![image](https://cloud.githubusercontent.com/assets/2653782/21990533/2a4b0be2-dbdd-11e6-8f56-7242566aeedb.png)

```
<button class="btn btn-sm btn-link" (click)="doSomething()"><clr-icon shape="step-forward" dir="down" size="16"></clr-icon></button>
<span class="label">{{time}}</span>
<button class="btn btn-sm btn-link" (click)="doSomethingElse()"><clr-icon shape="step-forward" size="16"></clr-icon></button>
```
It seems like even though the bundle is compiled, some of the underlying clarity js may not be correctly loaded.

**Comment by Shijir** [comment]
Hi @juanargote, can I see how you are loading `clarity-icons.min.css`?

**Comment by juanargote** [comment]
Sure, I am loading it at the bottom of my `vendor.ts` file. It currently looks like this:

```
import "reflect-metadata";

// Angular
import "@angular/platform-browser";
import "@angular/platform-browser-dynamic";
import "@angular/core";
import "@angular/common";
import "@angular/http";
import "@angular/router";

// RxJS
import "rxjs";

// Other vendors' js, ts, css, sass, ...
import "leaflet";
import "zone.js/dist/zone";
import "zone.js/dist/long-stack-trace-zone";
import "clarity-icons";
import "leaflet/dist/leaflet.css";
import "clarity-ui/clarity-ui.min.css";
```

**Comment by Shijir** [comment]
@juanargote you might want to place those `sass` or `css` above `js` libraries as they are dependent on style files. I would try the following:

```
import "leaflet/dist/leaflet.css";
import "clarity-ui/clarity-ui.min.css";

import "leaflet";
import "clarity-icons";
```

**Comment by juanargote** [comment]
@Shijir that did not seem to work but I also realized that I was simply missing the `clarity-icons.min.css` file. For reference, this is the final look of the `vendor.ts` file:

```
import "reflect-metadata";

// Angular
import "@angular/platform-browser";
import "@angular/platform-browser-dynamic";
import "@angular/core";
import "@angular/common";
import "@angular/http";
import "@angular/router";

// RxJS
import "rxjs";

// Other vendors' js, ts, css, sass, ...
import "zone.js/dist/zone";
import "zone.js/dist/long-stack-trace-zone";

import "leaflet/dist/leaflet.css";
import "clarity-ui/clarity-ui.min.css";
import "clarity-icons/clarity-icons.min.css";

import "leaflet";
import "clarity-icons";
```

Thank you very much for your help.
