### ISSUE TITLE
Unable to concat clarity-ui.min.css with other css files using gulp-concat-css

### ISSUE THREAD

**Issue by nghiado** [vmware/clarity#367]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Should be able to concat clarity-ui.min.css with other css files to create a single css using gulp-contact-css
### Actual behavior
When I run gulp-concat-css, it throws error when concating clarity-ui.min.css with the error property missing ':'.
I think it has something todo with the encoded svg icons in /clarity-angular/images/_icon_clarity.scss.

### Reproduction of behavior

[clarity-css-concat-issue.zip](https://github.com/vmware/clarity/files/705441/clarity-css-concat-issue.zip)
Unzip the sample project
````
npm install
gulp
````

### Environment details
* **OS and version:** 
Mac OS Sierra 10.12.2
node -v v6.9.2

**Comment by Shijir** [comment]
Hi @nghiado, I was able to reproduce the same error thanks to your provided gulp task code. Using `gulp-concat-css` plugin was logging that error. However, I was able to successfully concatenate the css files using `gulp-concat` plugin. Also, one of my teammates suggested that the error was with the `gulp-concat-css` plugin itself originally. 

Related to https://github.com/mariocasciaro/gulp-concat-css/issues/26

**Comment by nghiado** [comment]
@Shijir Thanks for your suggestion. I had to  switch to gulp-concat to work around this issue.
Just a thought while debugging this issue and looking at https://github.com/vmware/clarity/blob/master/src/clarity-angular/images/_icons.clarity.scss
I think it's not a scalable solution when we have to put all encoded svg manually like that.
Can we checkin original svg files and use some gulp plugins to convert them to css. It also allows us to optimize the output and remove unused svg elements.

**Comment by Shijir** [comment]
@nghiado Your suggestion sounds very reasonable to me. We will definitely take that into our consideration as we make changes to _icons.clarity.scss.
