### ISSUE TITLE
Dropdown item can not be focused

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#3673]
## Describe the bug

It seems not possible to focus a dropdown item via `element.focus()`.

## How to reproduce

https://stackblitz.com/edit/clarity-dropdown-search

1.  Visit stackblitz
2.  Click dropdown to open
3.  Press key to search for item (e.g. m)
4.  See error: Item that starts with entered key should be focused (e.g. More)

## Expected behavior

It should be possible to focus a dropdown item programmatically.

## Versions

**App**

* Angular: 8
* Clarity: 2.1.0

**Device:**

* Browser Chrome

**Comment by gnomeontherun** [comment]
This is likely related to changes for accessibility in Dropdown, where we have to manage focus internally. We'll have to investigate but I suspect its a lifecycle challenge and perhaps the manual focus management conflicts with forcing focus.

**Comment by jeeyun** [comment]
Hi @twittwer,
We've made some changes recently to comply with the ARIA spec for menu, which means a prescribed focus management for the whole dropdown: https://www.w3.org/TR/wai-aria-practices/#menubutton

Unfortunately this means what you are trying to do is not supported. Sounds like the use case is better suited for combobox which is in active development but unfortunately not yet available. Meanwhile, if you really want to preserve the functionality you have, you can consider using our static (HTML/css) dropdown markup and add in the functionality that you have implemented.

Closing as we won't be taking further action on this issue at this time.
