### ISSUE TITLE
Accordion Component's clrIfExpanded two-way binding is not working

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#3675]
## Describe the bug

Tried to set the clrIfExpanded directive to true initially so that the panel will be expanded by default but it doesn't work.

## How to reproduce
Here's a sample in StackBlitz:
https://stackblitz.com/edit/clarity-light-theme-v2-yrfkcg

## Expected behavior
It should expand/collapse based on the two-way binding value.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by coryrylan** [comment]
`clrIfExpanded` is for making sure content is lazily rendered. To toggle when the panel should open you will need to use `clrAccordionPanelOpen` on the panel element. 

```html
      <button class="btn" (click)="expanded = true">Expand First Panel</button>
      <clr-accordion>
        <clr-accordion-panel [(clrAccordionPanelOpen)]="expanded">
          <clr-accordion-title>Item 1</clr-accordion-title>
          <clr-accordion-content>Content 1</clr-accordion-content>
        </clr-accordion-panel>
      </clr-accordion>
```
