### ISSUE TITLE
Feature request: horizontal scrolling across columns

### ISSUE THREAD

**Issue by colinskow** [vmware/clarity#3679]
My app has more columns than can comfortably fit in the width of the typical browser window. When Clarity's datagrid overflows horizontally, however, it forces a horizontal scrollbar across the entire page.

I would like just the header and rows to scroll. The footer should remain static. And if the columns comfortably fit within the page width, no horizontal scrollbar should be present.

I've already tried several ways to add the scrolling manually using the CSS overflow-x property on grid elements, but no matter what it seems to expand the entire page.

An example of perfect grid scrolling behavior is here:
https://www.ag-grid.com/example.php#/

**Comment by hippee-lee** [comment]
@colinskow - please use the issue template when filing issues. 
In this case an example (we provide starter stackblitzes for multiple versions) would help here. As far as I know in both v1 and v2 the footer stays static and only the header/rows will scroll when columns expand beyond the datagrid container. 

Please create an example stackblitz that demonstrated what you describe.

**Comment by colinskow** [comment]
Okay, I can confirm this is working correctly in StackBlitz on both V1 and V2. Which means I must be doing something to screw it up on my end.
https://stackblitz.com/edit/clarity-light-theme-v2-ffeqaf

**Comment by hippee-lee** [comment]
If you can isolate your issue in a stackblitz feel free to post the link here. I'm happy to have a look at the code.
