### ISSUE TITLE
Dropdown in header actions does not work with inline wizard

### ISSUE THREAD

**Issue by royling** [vmware/clarity#3680]
## Describe the bug

The dropdown in header actions cannot work when an inline wizard is added in content.

## How to reproduce

https://stackblitz.com/edit/clr-dropdown-with-clr-wizard

Clicking the action button in header, the dropdown menu flashes and cannot be clicked.

## Expected behavior

The dropdown expands and the action in the dropdown can be clicked.

## Versions

**App**

* Angular: [e.g. 6] 8.2.0
* Node: [e.g. 8.10.0] -
* Clarity: [e.g. 0.12.5] 2.1.0

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

the dropdown works if wizard is removed.

and this works well with clarity v1, see https://stackblitz.com/edit/clr-dropdown-with-wizard-v1

**Comment by mathisscott** [comment]
The best diagnosis I have is that the focus trap on the wizard is preventing the dropdown from opening. This wasn't an issue in earlier versions where we did not have a focus trap.

That said, the inline wizard has always been an undocumented, easter-egg feature that was there to help teams out while we worked on the stepper. It is not something that we endorse or planned to support long term.

The stepper was released in 2.0 and officially deprecated the unofficial inline wizard.

The recommendation is to move away from the inline wizard and use the stepper.

**Comment by royling** [comment]
good to know that stepper can be an alternative.

And, is there any workaround if inline wizard must be used? how can I easily disable the focus trap?

**Comment by mathisscott** [comment]
I don't know if there is a way to disable the focus trap. Maybe @Shijir or @hippee-lee know a way to do that?

Note that inline wizard is deprecated and will be removed at some point in the future.

Because it's not an officially supported feature in the wizard, it may not go through a normal deprecation cycle either.

**Comment by royling** [comment]
@Shijir or @hippee-lee would you mind to have a look at this?

And, @mathisscott Thanks for the deprecation note.
But, the stepper may not be a good fit for our design: a complex workflow, with many steps and serval large forms.
IMHO, the stepper's accordion-like design is perfect when **each panel is simple** for only **few steps**. Or, when it goes to the last step, the collapsed steps would occupy a large space on the top, unlike wizard's left-right layout.

**Comment by royling** [comment]
@mathisscott just updated `@clr/angular` to the latest (v2.1.1) in https://stackblitz.com/edit/clr-dropdown-with-clr-wizard, the issue is gone. I guess it's fixed.

Thanks!
