### ISSUE TITLE
clr-icon is overriding user defined role property value

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#3683]
## Describe the bug

`clr-icon` is assigning ‘role:none’ in the conntectCallback which is called when the custom element is appended in the DOM

## Expected behavior

We should check if the user has provided any role value through property first.

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
@Shijir 
Does this one have a workaround?

**Comment by Shijir** [comment]
Yes. I am shipping the fix soon.

**Comment by Shijir** [comment]
The workaround is to set the role **attribute** when the icon is in the DOM. 

I am shipping the fix soon.

**Comment by Shijir** [comment]
closed by https://github.com/vmware/clarity/pull/3690
