### ISSUE TITLE
DataGrid overflows page if not directly inside first `.content-area`

### ISSUE THREAD

**Issue by colinskow** [vmware/clarity#3684]
## Describe the bug

The DataGrid works perfectly when precisely inside the recommended `.main-container > .content-container > .content-area` structure. However I have it nested several components deep inside the `.content-area` container. This causes it to overflow the page horizontally or vertically.

I haven't been able to figure out CSS properties for the containers the DataGrid is nested inside to prevent it from overflowing.

This may be my own stupidity with CSS/Flexbox, but even so a workable solution should be added to the documentation as I'm sure this is a common problem.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-dgscroll01

The issue is visible right away. Take away the wrapping `.content-container` divs and the grid scrolls exactly as expected.

## Expected behavior

DataGrid should fill available space without causing scroll. If this is not a bug in DataGrid itself, then a workable solution to nest the grid should be documented.

## Versions

**App**

* Angular: [8.2.0]
* Node: [10.16.2]
* Clarity: [2.1.0]

**Device:**

* OS: Linux
* Browser Chrome
* Version 76

**Comment by Jinnie** [comment]
Why do you keep the `class="content-container"` on your inner test divs? If you use unclassed divs all works as you expext. Any div with `flex` layout will break your default layout. If you **do** need your containers to be `flexbox`, then you may need to manually manage widths to 100% of container for the datagrid and the containers themselves.
