### ISSUE TITLE
New Icons for various storage LUN types

### ISSUE THREAD

**Issue by abbyhtml** [vmware/clarity#3686]
## Summary
ESXi server can be connected to external storage Arrays via networks such as Fibre Channel. There are several types of LUNs (Logical Unit Number) a storage array exposes e.g. tape drive. The current clarity icon set in technology section can be expanded to represent different LUN types. 

* What is the icon?
We would like to have an icon for three LUN types. With the support for class "is-solid, has-alert and has-badge".

1. Tape Drive
A tape drive is a data storage device that reads and writes data on a magnetic tape.

![image](https://user-images.githubusercontent.com/40457657/62768817-56d29900-bab5-11e9-878d-31e247d758b0.png)

2. Media Changer
Mechanical transport device that can transport media between slots and drives.

3. Control Lun
Control Lun is a ALU (Array logical Lun) and is a type of Lun in storage arrays.

* What does the requested icon signify?
These icons signify the lun type attached to the ESXi server. 

* In which product(s) will this icon be used?
These icons will be used in a vSphere plugin used to manage the storage adapters (FC HBA) and discovered storage connected to the ESXi server.

## Alternatives
As of now clarity icons storage and container-volume are the closest in the technlogy section. However they do not help identify the type of storage.

Please note this request is not from vmware but a partner company.

**Comment by abbyhtml** [comment]
Hi do we have any updates on this?

**Comment by hippee-lee** [comment]
Hi @abbyhtml - this is still in the backlog.

**Comment by lil-kim** [comment]
Hi @abbyhtml , 
I want to make sure the icons you requested are accurately represented before I finalize them. Pls let me know if these are suitable:
![image](https://user-images.githubusercontent.com/23196444/64986139-40211e00-d87b-11e9-9f91-9ceb53227538.png)

**Comment by abbyhtml** [comment]
Thanks Lilia,

The icons look great. Thank you for taking this up.

Please finalize them and make it available in the next clarity release.

Regards,
Abhishek

**Comment by lil-kim** [comment]
Attaching ready-to-ship icons:
[GH3686-icons.zip](https://github.com/vmware/clarity/files/3637583/GH3686-icons.zip)
