### ISSUE TITLE
2.1.1 Changelog missing info

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#3689]
THe breaking change is not specified in the latest 2.1.1 release notes.

**Comment by mathisscott** [comment]
@jeeyun + @gnomeontherun ☝️

**Comment by KANekT** [comment]
![image](https://user-images.githubusercontent.com/580273/62818106-ebd3a180-bb4a-11e9-8234-2ba99a1ce4da.png)

latest version in 2.1.1

**Comment by gnomeontherun** [comment]
I'm not sure what you mean, the changelog has 2.1.1 https://github.com/vmware/clarity/blob/master/CHANGELOG.md. Are you talking about in the git tag?

**Comment by coryrylan** [comment]
Maybe a glitch on Github? Seems to be there now.

![Screen Shot 2019-08-14 at 9 32 30 AM](https://user-images.githubusercontent.com/2021067/63029623-7fbcaa80-be76-11e9-9f4d-7b02007f9638.png)

**Comment by gnomeontherun** [comment]
Closing as it is found in changelog.
