### ISSUE TITLE
How do I hide an entire clr-stepper-panel based on a toggle switch from another clr-stepper-panel? 

### ISSUE THREAD

**Issue by joshio1** [vmware/clarity#3693]
## 

I am unable to hide a stepper panel after I toggle a checkbox in another stepper panel. I tried with both [hidden] as well as *ngIf, I do not get the expected results.
1. When I use [hidden], I get an error while loading the page saying:

`core.js:4799 ERROR TypeError: Cannot read property 'id' of undefined
    at StepperModel.openFirstPanel (clr-angular.js:17866)
`

2. When I use *ngIf and toggle the checkbox in another stepper panel, the stepper panel changes focus and expands the first stepper panel again. I would like the new stepper panel to be added or removed silently.

This is the condition I have put in my *ngIf or [hidden]:
`form.get('checkboxName').value`

## How to reproduce

1.  Create a stepper with more than one stepper panels. One of the stepper panels must contain a checkbox inside it.
2.  Add a *ngIf or hidden in other stepper panel such that it is shown only when the checkbox is selected.
3.  Check the checkbox

## Versions

**App**

* Angular: [e.g. 8]
* Clarity: [e.g. 2.1.0]

**Device:**

* Type: Mac
* OS: [e.g. iOS]
* Browser [chrome]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Can you please help us by creating a demo using StackBlitz? We request this of all reports so we can triage your issue. We have some starters at https://stackblitz.com/@clr-team

**Comment by gnomeontherun** [comment]
This has become stale waiting for a response, so we're going to close it. Please provide a reproduction and details in future issues to help us prioritize.
