### ISSUE TITLE
Defining Clarity tag, label, and annotation key:value pairs

### ISSUE THREAD

**Issue by levyo** [vmware/clarity#3698]
We have instances in several VMware products where we need to display tag, label, and annotation key:value pairs. In some tools all 3 can potentially be displayed on the same screen, and users have no way to distinguish between the components. We therefore need to introduce a design proposal to visually differentiate between the components and allow them to be contextually displayed and understood by our users.

* What is the change?
Currently Clarity only has a style for labels. (Pill) However, we need to expand the style relies on color differentiation which may not be accessible to some users. The new design proposal will introduce key visual elements to help users identify the key:value pair component without the reliance on color.

* Why should it go in Clarity?
The newly defined and styled components should go in Clarity since they are often used by designers and developers across many of our products.
 
* Does this change impact existing behaviors? If so how?
The introduction of the new components will replace and enhance existing label, tag, and annotation patterns to allow all 3 to exist in a single product. The new design proposal will help to enhance usability and affordance by visually differentiating between the 3.
 
* If this change introduces a new behavior, is this behavior accessible?
The new design proposal will meet full accessibility requirements.

Process
A small group has already started working on this effort. We opened a JIRA ticket, and a working Figma file.

Figma
https://www.figma.com/file/5xoUtRE5fER2odixddV1ko/Tags-Definition-Copy?node-id=0%3A1

**Comment by mathisscott** [comment]
@levyo 
[Semantic UI](https://semantic-ui.com/elements/label.html) has a take on this that you may find helpful in your design explorations.

**Comment by gnomeontherun** [comment]
Thanks for the report, I'm looking at the initial design but I think we need more specifics around the use cases and goals. The design looks like it may be in an exploration stage, but we can also take a look at this with you to ensure we have a path forward on process and expectations.

**Comment by levyo** [comment]
Yes. It's more or less been stuck in an exploratory stage. A few of us kicked off the effort, which sprung off a need to differentiate between labels and tags in VMC products. (Dimension and VMC on AWS) In Dimension we had usecases for tag creation and organization as a way for users to organize and filter out their SDDC edge locations. In VMC on AWS, we use labels to indicate upcoming scheduled maintenance and SDDC types. There is a usecase to use both tags and labels in the same product. In WCP we have a usecase where both tags and labels are used for different reasons, AS WELL AS key:value annotation pairs. All 3 are displayed in a pill, so needless to say there's confusion. If you already opened the Figma file you might have noticed how we're initially playing with ways to visually . differentiate between the components, without the reliance . on . color. More to come later.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
