### ISSUE TITLE
Improve icon accessibility and performance

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#3699]
## Summary

Currently, when users add the title attribute to `clr-icon`, we create an offscreen `span` element containing the title attribute value and appends that into `document`. Instead of doing that, we could make use of `aria-label` on `clr-icon` element directly. That will make it possible for screen-readers to register the icon element title value. The title attribute on `clr-icon` has inconsistent support across different browsers. 

* What is the change?

Complement `clr-icon`'s `title` attribute with default `aria-label` which has good support across all browsers. 

* Why should it go in Clarity?

This change will free us from the need to create an offscreen element containing title value on each and every icon that has the title attribute specified on. 

* Does this change impact existing behaviors? If so how?

With this change, we have to change the default role attribute setting too. With this change, we should set the `role="none"` on the SVG template tag and let the user define their desired role attribute values such as `img`, `button`, etc., on `clr-icon`. 

* If this change introduces a new behavior, is this behavior accessible?

Yes.

## Use case

When users define the title attribute on `clr-icon` like this:

```
<clr-icon shape="house" title="home page"></clr-icon>
```
this will turn into the following when it's rendered in DOM:
```
<clr-icon shape="house" title="home page" aria-label="home page"></clr-icon>
```

## Workarounds

This change will just introduce better performance, consistent behavior and reduce code complexity.

**Comment by mathisscott** [comment]
Fixed with #3967
