### ISSUE TITLE
Tooltips, Dropdown Menus & Sign Posts get clipped off in Modals

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#37]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
```

### Current behavior

Currently `.modal-body` in `.modal` has a `max-height: 55vh` and `overflow-y: auto`. Using the `max-height` and `overflow: auto` allows us to handle overflowing content inside of the `.modal-body`. But because of the way `overflow: auto` works, the current behavior clips off tooltips, dropdown menus, sign posts, or any other component that has `position: absolute`  in modal-body if the component spans outside of the `.modal-body`. The only way to avoid the component from being clipped off right now is to change the direction using the direction classes provided.

###### Tooltip gets clipped off
![Tooltip gets clipped off](https://cloud.githubusercontent.com/assets/1426805/20275094/0393a6d4-aa4c-11e6-95aa-2219a325b036.png)

###### Modal scrolling on content overflow
![Modal scrolling on content overflow](https://cloud.githubusercontent.com/assets/1426805/20275118/2748ab7e-aa4c-11e6-8993-13e1f8c959c3.png)

### Expected behavior

Tooltips, Dropdown Menus, and Sign Posts should not get clipped off in Modals

### Proposed Fix
The only alternative solution, that we know of, is to remove the `max-height` and the `overflow-y: auto` from the `.modal-body`. Instead use `overflow: visible` and and allow the content in the modal to decide its height. If the modal height is greater than the view height, the `.content-area` scrolls to show the remaining modal. This solution satisfies all the conditions that we want to meet but changes that way the modal works. 

One example of this is the modal implementation that Twitter uses.

###### Tooltip in Modal
![Tooltip in Modal](https://cloud.githubusercontent.com/assets/1426805/20275187/669451f2-aa4c-11e6-9240-86919c3ac2fc.png)

###### Popover/Sign Post in a Modal
![Popover/Sign Post in a Modal](https://cloud.githubusercontent.com/assets/1426805/20275202/7e57a672-aa4c-11e6-9856-a63a4589ffc8.png)

###### Content overflow + Scrolling
![Content overflow + Scrolling](https://cloud.githubusercontent.com/assets/1426805/20275264/c46b97c2-aa4c-11e6-9877-75ac2f00fda5.png)

### Other alternative that we considered
Use an attribute to store the content for the component and adding it on the `body` or `.main-container` when the tooltip is activated. 

This solution doesn't work because:

1. Storing content in attributes doesn't work because we can't use HTML markup in attributes and some of the components like Sign Posts should be able show links, images etc inside of them.
2. Bad from accessibility point of view because screen readers might read the tooltip content in incorrect order because its added in the `body` or `.main-container`
3. DOM manipulation every time the content is shown because it has to be added to the body or .main-container when active and removed when inactive.

### Implications of implementing the proposed alternative solution:

1. Changes the way Modal works. Breaking change for applications which use modals which has overflowing content inside of it.
2. Affects the design and implementation of Wizards since the wizard design assumes that the dialog has a max-height and the implementation depends on Modals.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.2.0 and above

* **Browser:** all

Open to suggestions/alternative solutions that might help solve this issue and still allow for Modals to have a max-height and the ability to support overflowing content.

**Note:** Sign Posts are under implementation

**Comment by reddolan** [comment]
Discussion started

**Comment by MRHarrison** [comment]
I think you just have to bite the bullet and have the option to append to body or assigned class.  There sometimes isn't a perfect solution.  This functionality is in every UI library I have used.  You should add the append to body solution until you find the perfect solution you are looking for.  I'm having the same issue with the sidebar.  This is a huge blocker for me and now I have to make my own custom tooltip component.

Also we should be able to add a tooltip to most dom elements without issue, and not specifically an anchor tag with an icon in it.  A little too opinionated for me.

**Comment by adityarb88** [comment]
Hi @MRHarrison. Thanks for your feedback. This is actually one of our top priorities to fix but we want to make sure that the fix that we decide to implement solves the meets the following things:

1. Does not clip off tooltips, sign posts etc inside the modal
2. Is not bad for accessibility
3. If possible, does not manipulate DOM

If we do attach the tooltip to the body, it is bad for accessibility and is probably going to modify the DOM. Its bad for accessibility because the tooltip will be attached to the body and screen readers will not read them along with the field that it is attached too.

The proposed fix removing `overflow: hidden` will solve all the issues that we are facing. In fact we looked at how other UI libraries implement this and most of them are moving towards implementing modals this way.

The proposed fix is a big breaking change for everyone because it changes the way modal works. We are evaluating the impact that this change will have and we plan to fix this issue ASAP.

For your other question on tooltips being attached to other elements along with icons, I would let our UX team (@yenmade and @reddolan) respond to that. Feel free to open a separate issue for this if you need this functionality and our UX team will get back to you. Thanks again!

**Comment by MRHarrison** [comment]
Perhaps I don't understand the screen readers issue well enough, but the append to body only happens when you do a hover.  The information is still inline with its content, the tooltip is only appended and removed with hover events. 

Turning off the `overflow: hidden` for the modal, sidebar, and whatever else that will require, will create a huge headache for you and whoever wants to build a custom element that needs an `overflow: hidden` or `overflow-y: scroll`.

**Comment by adityarb88** [comment]
@MRHarrison I would need more details or an example to look at that. Are you suggesting adding the content as an attribute to the markup? If yes then we wont be able to support links, images or anything other than plain text in components which extend tooltips like Sign Posts. If not, could you please give us an example?
But even then it would make the tooltips an angular component, no? Tooltips right now are pure CSS which would make this change a breaking change. 

The issue here is not the tooltips but the modal because it restricts all components which need to appear on hover or click and have `position: absolute`.

cc: @youdz

**Comment by MRHarrison** [comment]
Can't see tooltip in sidebar.
<img width="256" alt="overflow-hidden-hides-tooltip" src="https://cloud.githubusercontent.com/assets/486209/21738215/a6eddbf6-d436-11e6-8ecd-128e900d0a2c.png">

I kinda think the issue here is the tooltips.  Yes, the tooltips should be an angular component.  Not sure why it must be pure CSS?

**Comment by snagar78** [comment]
![image](https://cloud.githubusercontent.com/assets/7144356/21757230/801125d2-d5e0-11e6-9833-525ae72bc8b2.png)

One more case where tooltip is getting cut.
I am using card column layout (.card-columns-2) and tooltip is displayed on a "badge" and is not displayed fully.

**Comment by MRHarrison** [comment]
Whats the verdict on this?

**Comment by reddolan** [comment]
@MRHarrison @snagar78 Thank you for your patience. We are currently reviewing all of the details on this. We are discussing the best way to solve these situations. We will post a comment once we have more

**Comment by adityarb88** [comment]
Hi @MRHarrison. Thanks for your feedback again. The discussion last week with you was very useful. We are thinking of taking a look at Tether (http://tether.io/) or other similar libraries to help us solve the issues that we discussed last week. Once we finalize on details around this, we plan on implementing this change and releasing them as part of v0.9.0 (Please note that there is no firm date on when v0.9.0 will be released yet).

**Comment by MRHarrison** [comment]
That should work, thanks for the quick reply!

**Comment by jeeyun** [comment]
Addressed by #649. A separate Clarity input component should be created for the input validation piece.

**Comment by ivvatov** [comment]
Using the `clr-tooltip` component from https://github.com/vmware/clarity/pull/649 in a `clr-modal` (more specifically, in the "div.modal-body"), does not work as is - the tooltip content is hidden.

**Comment by jbgarr** [comment]
I have a form in a modal and the validation tooltips are being cut off. I see @jeeyun has mentioned this as needing to be a separate piece, but I wanted to check and see if there has been any progress made on that?

**Comment by jeeyun** [comment]
Hi @ivvatov can you take a look at this sample plunkr and see how your specific component might be different? I am able to use a `clr-tooltip` inside the div without issue: https://embed.plnkr.co/SlrDoznQ2DQbspcG4EsF/ 

If you could replicate the issue with a plunkr I'd be happy to take a look.

**Comment by jeeyun** [comment]
Hi @jbgarr thank you for asking. I just created an issue for it so you can track it for progress: #835.

Meanwhile, I'd suggest using a different direction for the tooltip as a workaround until the angular component is ready.

**Comment by ivvatov** [comment]
Hi @jeeyun it seems that having a `relative` or an `absolute` position on the tooltip or a parent element causes issues. 
You can take a look at this plunkr: https://plnkr.co/edit/F7PARAhiG2z302yR0RHB

**Comment by ivvatov** [comment]
Here are the clarity guidelines for input validation (https://vmware.github.io/clarity/documentation/input-fields). Currently, we cannot change (1) the clr-tooltip pop-up behavior (i.e. tooltip is visible on hover only) and (2) we cannot color the tooltip in red. Please advise.

**Comment by mathisscott** [comment]
@ivvatov : In the plunkr you shared, using `position: relative` on the `clr-tooltip` wrapper is definitely not advised. It appears you need an enhancement where the tooltip aligns with its right edge flush to the arrow. @jeeyun, do we have an issue open for an enhancement for that?

Regarding the clarity guidelines for input validation, what is your use case? Our guidelines are highly recommended and clearly define what we support. You are free to go outside of those if you must and teams do it all the time. But you take on ownership of issues introduced in your app by doing so.

**Comment by ivvatov** [comment]
@mathisscott , regarding the clr-tooltip positioning in clr-modals: We cannot use clr-tooltip in a div with position `relative` and we cannot set position `relative` to a clr-tooltip when used in a modal. I think there is a room for improvement here.

Regarding second comment, I am attaching a screenshot from your guideline for validation. We would like to follow the guidelines in our team, but the clr-tooltip component (not the static markup/css version) simply does not look like the old one. Plus, it only shows on hover and we haven't found a way to change this behavior (i.e. show it from code).
![clarity-validation-recommendation](https://cloud.githubusercontent.com/assets/27762496/25854865/33831a82-34da-11e7-8eb5-ecef0d0d9bf9.PNG)
