### ISSUE TITLE
clr-stack-block 

### ISSUE THREAD

**Issue by paavels** [vmware/clarity#370]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[x] enhancement
```

It would be very good if StackView's would be able to handle tree view like structure. Currently when there is some kind of tag (ie your custom recursive directive) inside clr-stack-block, design for StackView breaks.

### Environment details

* **Angular version:** 2

* **Clarity version:** 0.8.0

**Comment by jaffoneh** [comment]
@paavels do you mean you would want to nest stackblocks beyond the immediate parent-child relationship? Wouldn't a tree be better for that structure?

Could you describe a bit more about the use case you're trying to achieve here?

**Comment by paavels** [comment]
Yes, I do want to nest stackblocks in tree structure. As far as I tested - Stackview allows to display more than 1 level. However connecting that to Angular is difficult. What I tried is creating recursive component. When you are using tag based component, your design breaks, because Angular is creating tag for that component. The outcome is something like

 ```
<clr-stack-block>
        <clr-stack-label>Test</clr-stack-label>
        <clr-stack-content>Test</clr-stack-content>
        <custom-component>
        <clr-stack-block>
            <clr-stack-label>000</clr-stack-label>
            <clr-stack-content>111</clr-stack-content>
            <custom-component>
	             <clr-stack-block>
                             <clr-stack-label>000</clr-stack-label>
                             <clr-stack-content>111</clr-stack-content>
                    </clr-stack-block>
                    <clr-stack-block>
                             <clr-stack-label>222</clr-stack-label>
                            <clr-stack-content>333</clr-stack-content>
                   </clr-stack-block>
            </custom-component>
        </clr-stack-block>
        <clr-stack-block>
            <clr-stack-label>222</clr-stack-label>
            <clr-stack-content>333</clr-stack-content>
        </clr-stack-block>
        </custom-component>
    </clr-stack-block>
```

If there would be a CSS class in Clarity that could be assigned to <custom-component> to instruct it not to break UI, it could be a solution.

When you are trying attribute based component, you have component clash with clr-stack-block definition.

**Comment by jaffoneh** [comment]
@paavels we've been discussing this internally (in addition to other examples like hierarchy in datagrids) and we're reaching the conclusion that based on the use cases we're seeing and after adding the master > detail view within datagrids and after publishing trees, having hierarchy in stack views is not recommended and it is not a design pattern we'd like to support moving forward. If you have any additional use cases, please do share them and we'll be happy to take a look and possibly re-open if needed.
