### ISSUE TITLE
datagrid with open filter and single-action issue

### ISSUE THREAD

**Issue by balandinve** [vmware/clarity#3703]
## Describe the bug

If to open filter and then click by single-action twice - showed menu. If click to another row single action dots - his open too and cannot do anymore.

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/edit/clarity-light-theme-v2-wbobay). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Open filter
2.  Click by single-action menu of first row.
3.  Click by single-action menu of first row - menu is showed.
4.  Click by single-action menu of second row.
5. Click by single-action menu of second row - menu is showed.
6. single-action menu of both row is not hidebale

* Angular: 8.0.0
* Node: 10.14.1
* Clarity: 2.0.0

* Type: Desktop
* OS: Windows
* Browser chrome
* Version 76

**Comment by gnomeontherun** [comment]
@hippee-lee Do you expect this to be resolved by popover fixe? I suspect so.

**Comment by hippee-lee** [comment]
Yes. Am working on the rebase from master now. I hope to have a PR ready today or Monday.

**Comment by gnomeontherun** [comment]
This is resolved by by #2923 and is fixed in 2.2.
