### ISSUE TITLE
Sidenav in website documentation page doesn't collapse

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#3704]
## Describe the bug

1. Go to https://clarity.design/documentation
2. See the sidenav on the left
3. Click on the Patterns or Components sidenav header
4. Note that the arrow changes orientation but the section does not collapse

## How to reproduce

See above.

## Expected behavior

Since the sidenav examples (https://clarity.design/documentation/sidenav) do work, it's hard to say whether this is broken in Clarity or just a website issue.

If it is just a website issue, we have the option to just remove the "collapsible" class from the sidenav. If it is a problem with the HTML/CSS version of our sidenav, it should be fixed.

## Versions

**App**

* Clarity: 2.1.1

**Device:**

* Type: MacBook
* OS: OSX
* Browser: Chrome
* Version 75.0

**Comment by florin-borceanu** [comment]
I investigated this issue and I found a fix for it.
Can I start working on it?
If so, can you assign the issue to me?
Thanks!

**Comment by mathisscott** [comment]
Sounds good, @florin-borceanu. Thanks!
