### ISSUE TITLE
Datepicker does not honor readonly/disabled options

### ISSUE THREAD

**Issue by kbuffington** [vmware/clarity#3708]
## Describe the bug

When I add `readonly` or `disabled` to a clrDate input, the text input itself honors those settings, but the calendar button is still clickable and selecting a date in it will change the value of the input.

## How to reproduce

Click on the calendar of a disabled or readonly clrDate input.

https://stackblitz.com/edit/clarity-light-theme-v2-ikxvod

## Expected behavior

Calendar should not be clickable, or should not allow the user to select another date.

## Versions

**App**

* Angular: 7/8
* Clarity: 1.1.3 - 2.0

**Device:**

* Type: MBP
* OS: Mojave
* Browser Chrome 76

**Comment by florin-borceanu** [comment]
I investigated this issue and I found out that if you add the "clr-date-container" tags before and after the input tag, the disable behavior works just fine. 
Although, the read-only behavior needs more investigations and some logic to be written.
Can I start to update the documentation accordingly?
If so, can you assign the issue to me?
Thanks!

**Comment by mathisscott** [comment]
Sounds great. Thanks again, @florin-borceanu !

**Comment by gnomeontherun** [comment]
The `readonly` functionality would require you to create a new input on the date-input to capture that setting and inform the parent controls that we're in a readonly mode. I don't believe we have special styles, we would just treat it like it was disabled by applying the correct disabled class and disabling the dropdown button.

**Comment by gnomeontherun** [comment]
Closed via https://github.com/vmware/clarity/pull/4174
