### ISSUE TITLE
commit message guidelines are no longer valid

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#3709]
## Describe the bug

The PR #3681 introduced the `conventional-changelog` package to automatically generate the CHANGELOG.md file.

To make it working properly the commit message should follow the angular guidelines.

Would be nice to update the `DEVELOPMENT_CONTRIBUTION.md`

**Comment by gnomeontherun** [comment]
This will be resolved by the open PR https://github.com/vmware/clarity/pull/3705
