### ISSUE TITLE
Datagrid Selection not working

### ISSUE THREAD

**Issue by integratedinfosys** [vmware/clarity#371]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

Datagrid Selection not working
### Reproduction of behavior

Including zip file of the project without npm modules.
### Environment details

* **Angular version:** 2.0.X
2.4.0
* **Clarity version:** 
0.8.0
[data-grid.zip](https://github.com/vmware/clarity/files/706708/data-grid.zip)

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@integratedinfosys is this basically a duplicate of #17? Also, could you include a plnkr instead of the zipped file so Clarity team members are able to help? Thanks.

**Comment by integratedinfosys** [comment]
No its not a duplicate. Select in Datagrid is not working at all. I might be missing something in the code. It is a short code, please look into this.
Somehow, I couldn't manage to run the code in plnkr, may be some issue with Angular Version, as I have to use Angular 2.4.0 to have Datagrid working.

**Comment by jaffoneh** [comment]
@integratedinfosys the latest 0.8.x plnkr should work. When we talk about select, are you taking about multi-select (what's available in the documentation today)?.

Running local applications from different issues outside of the plnkr is pretty time consuming for the team so we prefer plnkers if possible. If you're seeing a specific bug or issue, reporting that and the stacktrace should help as well. Thanks again for reporting an issue and once more information is available, we're happy to help.

**Comment by integratedinfosys** [comment]
https://plnkr.co/edit/V6touMW8PC3NTIDT0muX?p=preview

**Comment by jaffoneh** [comment]
@integratedinfosys All I see in the plnkr is a datagrid with 5 rows. Could you provide more details so we're able to figure out if there is an issue here or if we can help you. Are you looking for single row selection in a datagrid? What have you attempted, what are you looking to do, and what is not working? Please be more detailed with this issue.

**Comment by integratedinfosys** [comment]
I am not looking for single row selection. I might be missing something. I am not getting check boxes for the row selection at all.

**Comment by chunghha** [comment]
@integratedinfosys I think you missed two things.

1. selected: string[] = []; in your home component TS.
2. [(clrDgSelected)]="item.selected" in your home component html.

Please see this updated plnkr.
https://plnkr.co/edit/IHfrjo9B5JUWP8uSyFIG?p=preview

**Comment by integratedinfosys** [comment]
Thank you. selected: string[] = [] solves the problem.
Looks like [(clrDgSelected)]="item.selected" is not needed. Please see 
https://plnkr.co/edit/IHfrjo9B5JUWP8uSyFIG?p=preview
Can you please clarify this.

**Comment by integratedinfosys** [comment]
I think having complete code in the documentation may be a good idea.

**Comment by chunghha** [comment]
@integratedinfosys you don't need to have **clrDgSelected** on row unless you want to select items from your code.

**Comment by integratedinfosys** [comment]
Thank you!!
