### ISSUE TITLE
External datagrid filter/ search option should be available on top of table rather than header column with full example

### ISSUE THREAD

**Issue by vitthalmahale** [vmware/clarity#3711]
## Summary

_Summary the request and address the questions as appropriate._

* What is the change?
* Why should it go in Clarity?
* Does this change impact existing behaviors? If so how?
* If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by gnomeontherun** [comment]
We have a design spec for this functionality but it has not been implemented. You can look at the spec and build something for yourself if you need as a workaround until we implement it.

Follow #1632 for updates.

Also, we require information about your use case and what exactly you are requesting so we can better understand your request for future tickets.

**Comment by vitthalmahale** [comment]
I want a Datagrid example like which will search matching inputs all over table row with an external search option without header input field. with full example implemented as like plunker or something similar

**Comment by gnomeontherun** [comment]
That is not something built into the datagrid now, so you're in charge of handling the searching/filtering at that stage like a server-driven datagrid would do.
