### ISSUE TITLE
chart element

### ISSUE THREAD

**Issue by yanyixing** [vmware/clarity#372]
https://www.starwindsoftware.com/blog/vmware-clarity-why-should-you-care
In this blog, I found the chart element. Does clarity contains those elements? where can I found ?

**Comment by jaffoneh** [comment]
@yanyixing currently, Clarity doesn't ship its own charting library. Although we're considering options there, we don't currently ship Clarity-specific shirts. That said, you can use your charting library of choice (and there are many open source ones) alongside Clarity with no issues.

**Comment by TekSiDoT** [comment]
Just leaving this here to reinforce that clarity would very much profit by integrating its chart elements.

**Comment by mathisscott** [comment]
Thanks for the feedback, @TekSiDoT

**Comment by icepeng** [comment]
Chart elements would fit great with Clarity. +1 to @TekSiDoT

**Comment by fvandillen** [comment]
We are considering Clarity to be the UI framework for the next major version of our app. It would be the instant winner when it starts shipping with a charting library.

**Comment by mathisscott** [comment]
@fvandillen 
Thanks for that. Charts are in our long-term plans for sure. What types of charts best fit your application's needs? We are looking to define an MVP deliverable for a chart library.

**Comment by fvandillen** [comment]
@mathisscott Thanks for your response and good to hear charts are on the long-term plans. Our application is centered around smart utility meter data. As such, we are using D3 right now to draw (multi)line and vertical bar charts, in addition to scatterplots.

**Comment by icepeng** [comment]
Currently, I am using `ngx-echarts` https://github.com/xieziyu/ngx-echarts https://github.com/ecomfe/echarts for alternative.

If clarity supports chart element that fit well with card, it would be awesome.

**Comment by SayakMukhopadhyay** [comment]
ECharts looks powerful. I have found HighCharts to be great for my use case. I am using https://github.com/cebor/angular-highcharts for angular bindings.
