### ISSUE TITLE
[NG] Create a radio button component

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#373]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
We need to write a radio button Angular component for users who want a quick and simple solution. It would be the same idea as [our existing checkbox component](https://github.com/vmware/clarity/blob/master/src/clarity-angular/checkboxes/checkbox.ts).
It should project the label, integrate properly with `ngModel`, generate proper ids to avoid conflicts, and allow the user to use radios without labels.

### Actual behavior

At the moment, users have to jump through a lop of hoops to use simple radio buttons: the label is required, which means a matching id on the input and label is also needed. Quite painful when dealing with very dynamic inputs or unusual DOM.

### Reproduction of behavior
Plunker of a working example with the current static radio buttons: https://plnkr.co/edit/tE7qEU8Sy05sSQrZg3tE?p=preview
Note that the id has to be specified in the model, which we don't want.

### Environment details

* **Angular version:** 2.4.X

* **Clarity version:** 0.8.x

* **Browser:** all

**Comment by nishantshreshth** [comment]
Very much needed. A relevant piece of code from my application:

```html
    <div class="radio-inline">
      <input type="radio" name="{{ product.id + '-installation-type' }}" id="{{ product.id + '-new-install' }}" checked>
      <label for="{{ product.id + '-new-install' }}">New Install</label>
    </div>
    <div class="radio-inline">
      <input type="radio" name="{{ product.id + '-installation-type' }}" id="{{ product.id + '-import' }}">
      <label for="{{ product.id + '-import' }}">Import</label>
    </div>
```

**Comment by Jeff-Zoch** [comment]
Definitely needed. Currently writing a form-builder and would love to have radio buttons native in Angular 2, as the code is much simpler and cohesive to other components created thus far. Using ids and not having ngModel behave as seamlessly makes it hard to justify using
