### ISSUE TITLE
[WEB] Custom filters example incorrect and ambiguous

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#3737]
## Describe the bug

An example on the custom filters website page incorrectly adds clrDgItem property to a clr-dg-cell, while it should be using clr-dg-column instead.

## How to reproduce

1.  Go to https://clarity.design/documentation/datagrid/custom-filtering
2.  Scroll down to the example which description starts with `By default, filtering searches the original model value for matches`
3.  Verify that the example contains (at 2 places):
> <clr-dg-cell [clrDgField]="...

## Expected behavior

> <clr-dg-column [clrDgField]="

## Additional notes

The whole example is a bit ambiguous as it is not clearly stated that it illustrates problematic behavior with **default** filtering.
We have a case where it was understood like example of how it needs to be done.
I suggest that we find a way to explicitly and visibly identify that this is not a positive, but a negative example.

**Comment by amellnik** [comment]
I can take a swing at this -- I was going to make a PR to propose other changes to the DataGrid docs (like how the usage notes appear at the bottom of every section).

**Comment by gnomeontherun** [comment]
Awesome, I'll assign you!

**Comment by Jinnie** [comment]
Verified this has been fixed in both websites
