### ISSUE TITLE
The tooltip text is not visible in Dark theme

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#3740]
## Describe the bug

The tooltip text is not visible in Dark theme. Needs to have dark visible text.

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v2-ysdyky

## Expected behavior

Visible tooltip text

## Versions

**App**

* Angular: 8.0.0^
* Clarity: 2.1.2

**Comment by mathisscott** [comment]
This is a regression caused by a deprecation that was incorrectly applied.

**Comment by mathisscott** [comment]
I should have a fix for PR shortly.
