### ISSUE TITLE
Datagrid in compact mode with clrDgRowSelection

### ISSUE THREAD

**Issue by tJeyhun** [vmware/clarity#3742]
Compact mode is broken for datagrid with 

   [clrDgRowSelection]="true"

**Comment by hippee-lee** [comment]
Hi @tJeyhun - in the issue template we ask for some information about the issue and a stackblitz reproduction. You can see what the content/markdown for bug reports was here: https://github.com/vmware/clarity/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

Please fill that our and add a stackblitz that recreates the issue as described so we can investigate/triage.

**Comment by tJeyhun** [comment]
Sorry, my mistake,
Problem was conflicting bootstrap css file that I added earlier.
Will use stackblitz more often :)
