### ISSUE TITLE
Datagrid current page not rendered correctly in IE 11

### ISSUE THREAD

**Issue by davidrourke** [vmware/clarity#3747]
## Describe the bug

In version 1.2.x the current page in the pagination footer is rendered correctly:

![Datagrid paging v1 2 x](https://user-images.githubusercontent.com/25104184/63715075-07a89a00-c811-11e9-91cd-705be6eb8fa1.PNG)

However, in version 2.x the current page in the pagination footer is not rendered correctly:

![Datagrid paging v2 0](https://user-images.githubusercontent.com/25104184/63715344-93222b00-c811-11e9-9360-8e6f18907b34.PNG)

## Expected behavior

The current page number should render correctly.

## Versions

**App**

* Angular: 8.2.3
* Node: 12.9
* Clarity: 2.1.2

**Device:**

* Type: Dell Latitude
* OS: Windows 7 Pro
* Browser IE 11 
* Version 11.0.9600.19403

## Additional notes

_Add any other notes about the problem here._

**Comment by AlexMarcuBytex** [comment]
@hippee-lee that's true. actually, the pagination number has a line-height of 1rem. With 0.75. fits perfectly.
