### ISSUE TITLE
Improve left-menu to include user settings (if there) when responsive

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#375]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Identify common right links that exist in an application's top right side of the header (e.g. Settings, User, Notification), set design standards, and account for responsive behavior. 

### Actual behavior
We don't currently do anything with that from a technical standpoint and we don't have design standards around it.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.x

* **OS and version:** all

* **Browser:** all

**Comment by yenmade** [comment]
Putting this in the UX backlog

**Comment by reddolan** [comment]
@jaffoneh the title says left-menu. Do you mean the upper-right menu? The title confused me thinking this was the "left nav"

**Comment by jaffoneh** [comment]
@reddolan I do mean the left menu. Think about this scenario: we currently have user settings in the top right section of the header, what happens when we go responsive? Where does the user menu goes? The expectation is that it goes into the responsive left navigation that comes out of the "burger" menu.

**Comment by reddolan** [comment]
@jaffoneh I would expect the user/settings nav to be in the upper right corner on a small screen, similar to where it lives on larger screens. We do this on the doc site, one nav for main navigation and a second nav for secondary navigation

![navigation-small](https://cloud.githubusercontent.com/assets/1858226/25874836/454ae95e-34c9-11e7-8647-ff4af8e30576.png)

**Comment by jaffoneh** [comment]
@reddolan the right-side navigation only appears if the page has sub-pages. For example, on the community page that does not exist. We cannot depend on the existence or lack of the right hand menu on responsive for displaying essential functionality that should always exist like user settings.

**Comment by mathisscott** [comment]
Bring over existing research and converge with existing responsive nav to work out a better story around responsiveness in a Clarity application.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
