### ISSUE TITLE
Cannot select text in modal

### ISSUE THREAD

**Issue by rogerfar** [vmware/clarity#3754]
In any modal you cannot select any of the text.

## How to reproduce

1.  Go to Go to https://clarity.design/documentation/modals
2.  Click on any of the demo buttons
3.  Try to select any of the text in the body
4.  You can't.

Setting `clrModalStaticBackdrop` to false doesn't change the behaviour.

This commit is most likely the cause: https://github.com/vmware/clarity/commit/33684ef

**Comment by gnomeontherun** [comment]
Something does seem strange here, not sure if that is the source but we need to investigate this.

**Comment by farlock85** [comment]
I downgraded to 2.2.0 for now and it works again.

**Comment by bdryanovski** [comment]
It seems that
```js
  event.target.blur();
```  
is preventing me to select the text. 

BTW, double-clicking the text let me select it and some times the first click let me select some part of the text.

**Comment by AlexMarcuBytex** [comment]
You ll only be able to select that text by changing the focus through keyboard ( tab key ). Should we find any solution or this is the correct behaviour?

**Comment by farlock85** [comment]
Doesn't seem like a great usecase to have it only work on tab. How I found out was that a customer wasn't able to copy the text from an error message modal and thought we put in some sort of 1990's copy protection.

**Comment by williangd** [comment]
Same problem here. The problem does not happen in version 2.1.0.

**Comment by AlexMarcuBytex** [comment]
@coryrylan can you help us? i see that this was implemented on #3657 pr.

**Comment by coryrylan** [comment]
I'll take a look at this, it is a regression from a different a11y bug fix.

**Comment by Shijir** [comment]
closed by #3821

**Comment by rahultokase** [comment]
Hi 
we can fix this issue by capturing the mouse down event on the target element or modal element and stop the event propagation to the down.
```
element.addEventListener("mousedown", function (event) {
  event.stopPropagation();
}, true);
```
Thanks
Rahul Tokase

**Comment by rogerfar** [comment]
@rahultokase This issue has been fixed already a while back
