### ISSUE TITLE
Esc closes modal when clrModalStaticBackdrop set to true

### ISSUE THREAD

**Issue by igalbk** [vmware/clarity#376]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When using modal window with clrModalStaticBackdrop set to "true", the modal won't close on "Esc" button  press

### Actual behavior
Pressing "Esc" closes the modal

### Reproduction of behavior
The problem exist on modal example with clrModalStaticBackdrop on https://vmware.github.io/clarity/documentation/modals

### Environment details

* **Angular version:** 2.0

* **Clarity version:** 0.76

* **OS and version:** all

* **Browser:** all

**Comment by mathisscott** [comment]
I think pressing the esc key should close the modal in this instance. The use case for not doing so is to prevent errant clicks from closing a modal.

It's less likely for users to errantly press the esc key.

**Comment by jaffoneh** [comment]
@igalbk what you might want is `clrModalClosable ` instead since it allows you to control how a modal gets closed and won't close on clicking outside or using the ESC key.
