### ISSUE TITLE
clr-datagrid loading backgroud is very dark

### ISSUE THREAD

**Issue by nicolasbreuni** [vmware/clarity#3761]
## Describe the bug

_After the update to 2.1.2, the datagrid loading spinner background is much darker than before, as you can see in the stackblitz._

## How to reproduce

https://stackblitz.com/edit/angular-wryxc3

## Expected behavior

_The lighter background from before the update._

## Versions

* Angular: [8.2.4]
* Clarity: [2.1.2]

**Device:**

* Type: [Dell Laptop]
* OS: [Windows]
* Browser [chrome]
* Version [76]

## Additional notes

_The error comes in mergerequest #3677. $clr-datagrid-loading-background was not translated correctly it should be hsla(0, 0%, 100%, 0.6) and not hsla(0, 0%, 0%, 0.6)_

**Comment by mathisscott** [comment]
This has already been fixed and merged. #3736 

It should be released in the next version of 2.x
