### ISSUE TITLE
Auto focus causes page scroll for ClrAlert and ClrSignpost components

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#3762]
## Describe the bug

If we open https://clarity.design/documentation/signposts we are automatically scrolled down to the last signpost trigger on the page.
This is not expected

## How to reproduce

Visit 
https://clarity.design/documentation/signposts 
or
https://clarity.design/documentation/alerts

## Expected behavior

Signpost trigger shouldnt be focused automatically(at least not if its in closed state)

## Versions

**App**

* Clarity: [1.2.x] and [2.x]

## Additional notes

This behavior is breaking apps if they use libraries like ngx-infinite-scroll since clarity scrolls it down to the last signpost which triggers the infinite scroll fetch, and the app is stuck in a continuous fetch and focus loop.

**Comment by Shijir** [comment]
closed by #3787 and #3774
