### ISSUE TITLE
Angular Timeline Component

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#3765]
## Summary

Based on the specs here: https://github.com/vmware/clarity/issues/1633 create a Clarity timeline component. 

* What is the change?
Clarity has static timeline for `@clr/ui` this will add an angular version with bindings and behavior that uses the existing style.
* Why should it go in Clarity?
There is already a static version. 
* Does this change impact existing behaviors? If so how?
n/a
* If this change introduces a new behavior, is this behavior accessible?
n/a
## Use case

See, https://github.com/vmware/clarity/issues/1633 or existing docs: https://clarity.design/documentation/timeline

## Examples
yes, see #1633
## Workarounds

n/a

**Comment by mcosta74** [comment]
Hi, I have a proposal for this issue, shall I create a new Issue with the Contribution template or should I attach it here ?

**Comment by gnomeontherun** [comment]
You can post it here, happy to review it!

**Comment by mcosta74** [comment]
## Summary

Implement a Timeline component

## Use case

Dynamic timeline

## Examples

N/A

## API

Here a proposed snippet
```
<clr-timeline clrLayout="horizontal">
  <clr-timeline-step clrState="success">
    <clr-timeline-header>...</clr-timeline-header>
    <clr-timeline-title>...</clr-timeline-title>
    <clr-timeline-description>...</clr-timeline-description>
  </clr-timeline-step>

  <clr-timeline-step clrState="processing">
    <clr-timeline-header>...</clr-timeline-header>
    <clr-timeline-title>...</clr-timeline-title>
    <clr-timeline-description>...</clr-timeline-description>
  </clr-timeline-step>

  <clr-timeline-step clrState="not-started">
    <clr-timeline-header>...</clr-timeline-header>
    <clr-timeline-title>...</clr-timeline-title>
    <clr-timeline-description>
      ...
      <button class="btn btn-sm">Action</button>
    </clr-timeline-description>
  </clr-timeline-step>
</clr-timeline>
```

Components/Directives:

* `clr-timeline` component

| Input/Output | Values                   | Default      | Effect                            |
| ------------ | ------------------------ | ------------ | --------------------------------- |
| [clrLayout]  | 'horizontal', 'vertical' | 'horizontal' | define the layout of the timeline |


* `clr-step` component

| Input/Output | Values                                                     | Default        | Effect                |
| ------------ | ---------------------------------------------------------- | -------------- | --------------------- |
| [clrState]   | 'not-started', 'current', 'processing', 'success', 'error' | 'not-started'  | set the right icon    |

* `clr-timeline-header` component
* `clr-timeline-title` component
* `clr-timeline-description` component

## Implementation plan

* What parts of the code are affected?
  
  A new Angular module `ClrTimelineModule`

* Will you introduce new services, components or directives?

  New components: `ClrTimeline`, `ClrTimelineStep`, `ClrTimelineHeader`, `ClrTimelineTitle`, `ClrTimelineDescription`

* Can you describe the basic flow of information between classes?

  No data are passed between components

* Does this introduce asynchronous behaviors?

  No

* Will you need to refactor existing Clarity code?

  No

* Will reasonable performance require optimizations?

  No

* Will it need to access native elements (and be incompatible with server-side rendering)?

  No


## Conclusion

I cannot spent much time per day so it may require 1-2 weeks; the idea is very simple so maybe I'll need help with the testing and documentation part

**Comment by gnomeontherun** [comment]
Thanks @mcosta74, I've assigned this to you and think your proposal is generally in alignment with what we'd like to see. Thanks for taking this on, and I presume we don't need a topic branch since I believe this would be small enough code (especially since its all new).

**Comment by mcosta74** [comment]
hi @gnomeontherun.
Not sure it will be super small because we should address:
* code + unit tests
* documentation
* dev app

So, you expect to have a single PR with `master` as target branch ?

**Comment by gnomeontherun** [comment]
I don't expect it to be super small, and if we need a topic branch we can make one if you wish. You let me know what works best, or you can also work on your own branch and ping us for a review before you make an official PR. I'm flexible, mostly just want to see us move forward smoothly.

**Comment by mcosta74** [comment]
Actually I'm almost done with the [code](https://github.com/mcosta74/clarity/tree/feat/timeline-angular-component).

I have to write UTs and complete the documentation.

**Comment by mcosta74** [comment]
@gnomeontherun I'm writing UTs but form Coding Guidelines is not clear (at least to me) what is the difference between `Template API` and `View`.

I think `Typescript API` are tests to check the component logic without interacting with the template but .... what about the other two ?

**Comment by gnomeontherun** [comment]
Good question, let me try to clarify.

`Typescript API` is to test any public methods on the components themselves, like they are just generic objects. Your tests should only manipulate the components through the component methods and then validate the behaviors.
`View` tests are to validate the resulting behaviors from if a user interacted, like if there is a way to click an item or type into a field. The tests should use user input methods to manipulate the component and then validate the behaviors.
`Template API` is to test that the input and output bindings are working, so if an application programmatically changes the values you want to ensure they are correctly rendered. These tests should change the input bindings or listen to output events to validate the behaviors.

**Comment by mcosta74** [comment]
great, I think this answer could go (as is) in the` CODING_GUIDELINES.md` instead of the `(details coming soon)`

**Comment by mcosta74** [comment]
@gnomeontherun, what about if I create a PR with code and unit tests. once it will be merged (and API approved) I can create a second PR for the documentation.

In the current branch I have also updated the dev app to show both static and angular version of the timeline

**Comment by gnomeontherun** [comment]
Closed by #3873

**Comment by spitfjre** [comment]
The documentation was not updated for the angular component as fas i see it.

**Comment by mcosta74** [comment]
the PR has been merged but not yet released

**Comment by mcosta74** [comment]
@gnomeontherun any update on this? any plan to have it released at some point ?

**Comment by gnomeontherun** [comment]
It is available in v3 https://clarity.design/documentation/timeline.

**Comment by mcosta74** [comment]
nope, the documentation is still the old one, and also the code is not in the v3.0.0 tag https://github.com/vmware/clarity/tree/v3.0.0/src/clr-angular/timeline

**Comment by hippee-lee** [comment]
@mcosta74 
Component commited to master here: https://github.com/vmware/clarity/commit/cc5e7e5727018eb86f75f8ad5f6435d669b1c7d9
Documentation commited to master here: https://github.com/vmware/clarity/commit/874e82278ac3e5a8181607759e76e18e3f2207c0

stackblitz od timeline component and Clarity v3 here: https://stackblitz.com/edit/clarity-v3-dark-theme-timeline-demo

**Comment by mcosta74** [comment]
Hi @hippee-lee, we were talking about the Angular Component (the one implemented here https://github.com/vmware/clarity/pull/3873). It has been merged and an other PR updated the doc (in the same branch). but the target branch have been never merged in master

**Comment by hippee-lee** [comment]
I see, I forgot all about this. that branch was used as a staging area to clean up and get external contributions ready for master. I'll cherry-pick it and open up a pr for master with your contribution. Sorry about the confusion.

**Comment by mcosta74** [comment]
> I see, I forgot all about this. that branch was used as a staging area to clean up and get external contributions ready for master. I'll cherry-pick it and open up a pr for master with your contribution. Sorry about the confusion.

no problem 👍
