### ISSUE TITLE
Show/Hide password icon is not displayed on IE 11

### ISSUE THREAD

**Issue by florin-borceanu** [vmware/clarity#3769]
## Describe the bug

The show/hide password icon is not displayed on IE 11, Clarity version 1.x, although the focus outline appears.

## How to reproduce

Clarity v1.x:
![image](https://user-images.githubusercontent.com/53469024/64020784-1e196300-cb3b-11e9-9c90-688a3783fce3.png)
https://v1.clarity.design/password

Clarity v2.x:
![image](https://user-images.githubusercontent.com/53469024/64020812-2f626f80-cb3b-11e9-84b8-73804004146f.png)
https://clarity.design/documentation/password

1.  Go to https://v1.clarity.design/password using IE11
2.  Scroll down to live examples
2.  Click on the right side of the input
4.  See the focus outline, but no icon

## Expected behavior

The hide/show password icon should be displayed.

## Versions

**App**

* Clarity: 1.x

**Device:**

* Type: Desktop
* OS: Windows 10
* Browser: IE
* Version: 11

## Additional notes

_Add any other notes about the problem here._

**Comment by bdryanovski** [comment]
Its seems that the Icon for some reason is not loaded on IE11 or Edge. 

## V1
![Screenshot (2)](https://user-images.githubusercontent.com/204564/64024253-ce14af00-caee-11e9-96ad-b7e546909d72.png)

## V2
![Screenshot (3)](https://user-images.githubusercontent.com/204564/64024254-cf45dc00-caee-11e9-9898-63bc9cdde13d.png)

**Comment by florin-borceanu** [comment]
After your comment, I investigated and I found out that the icons are not loaded on the entire website when is accessed with IE11.

**Comment by mathisscott** [comment]
@bdryanovski 
If you could triage this and find a root cause, that will help us figure out next steps. Thanks!

**Comment by bdryanovski** [comment]
Sure, 

I think that we had a similar issue with not loading some icons but there was just missed icon import but this is only IE/Edge related so it could be some SVG issue?

I
