### ISSUE TITLE
[WEB] Direct navigation not working in vertical nav sub pages

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#3776]
## Describe the bug

In V1 website direct links to Vertical Nav page and sub-pages is no working. Including internal component routing URLs

## How to reproduce

1.  Go to https://v1.clarity.design/vertical-nav/
2.  Try to refresh if you navigate to it
3.  Try internal routing link https://v1.clarity.design/vertical-nav/nav-groups/credit

## Expected behavior

It should be possible to directly land on the page and its sub-pages

## Versions

**App**

* Clarity: 1.x

## Additional notes

Previously similar problems were observed with incomplete or wrong entries in sitemap.xml

**Comment by gnomeontherun** [comment]
This is because we aren't generating `index.html` files for each of the subroutes in our build for v1. This should be fine in v2 since we aren't doing HTML redirects anymore.

**Comment by gnomeontherun** [comment]
Closing as this is a v1 specific issue and it is out of support.
