### ISSUE TITLE
Support for input groups in Angular

### ISSUE THREAD

**Issue by williangd** [vmware/clarity#3778]
## Describe the bug

Misaligned input and select when on same line/row.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-f4sha7

## Expected behavior

Correctly aligned input and select.

## Versions

**App**

* Angular: 8.2.4
* Node: 10
* Clarity: 2.1.2

**Comment by Jinnie** [comment]
Note: one of the issues is that the 2 demonstrated demos have different alignment.
This should be avoided by adding a `.clr-input-wrapper` container on the input, as shown here:
https://stackblitz.com/edit/forms-alignment-issue?file=src/app/app.component.html
This is the result:
![Screenshot from 2019-09-03 10-15-50](https://user-images.githubusercontent.com/1798828/64151854-f1639500-ce33-11e9-9672-9fabfc5382f0.png)

Apart from this, I am not sure if we would want to have total alignment of the adjacent items without any padding between them, as this can be a bit confusing for the users.

Leaving this open for some time, so the team can give more comment if needed.

**Comment by gnomeontherun** [comment]
We don't currently have documented nor built into the Angular components. We do have the static version that you can use for now though if you look at our dev app here. https://github.com/vmware/clarity/blob/master/src/dev/src/app/forms/input-group/input-group.html#L25

I'll repurpose this as a feature request for the Angular component support and documentation.

**Comment by williangd** [comment]
If I change the order of select and input, the layout is broken.

https://stackblitz.com/edit/clarity-light-theme-v2-qaqlje

Changing `.clr-input-group` `max-width` to 100% the problem does not occur.

```
clr-input-group {
    max-width: calc(100% - 1rem);
}
```
```
clr-input-group {
    max-width: 100%;
}
```

**Comment by gnomeontherun** [comment]
Ok, we'll have to take that into account when working on this. Its not documented because we weren't ready to support it, so right now your milage may vary.

**Comment by erabl-identos** [comment]
@bdryanovski it looks to me as if #4403 should not close this issue, since the PR only provides static CSS styling and no Angular component to achive the input group layout.
Is the Angular component tracked elsewhere?

**Comment by bdryanovski** [comment]
@erabl-identos  We need first to resolve some small design miss alignment before a component wrapper could be created. There is still discussion internally so I'm gonna leave it like that for now.
Keeping in mind your comment.

**Comment by gnomeontherun** [comment]
This is possible with using CSS form controls in Clarity Angular, or upgrading to the Clarity Core forms which have better input groups built-in. Closing as resolved.
