### ISSUE TITLE
clrPassword's underline is missing when user chooses to autofill the field

### ISSUE THREAD

**Issue by h657070128** [vmware/clarity#3779]
## Describe the bug

clrPassword's underline is missing when user chooses to autofill the field

## How to reproduce

1.  Go to https://clarity.design/documentation/password using Chrome
2.  Enter some random text, "test" for example and then navigate to some other page, Chrome will prompt you asking if you want to save the username/password, choose "yes" and navigate back to the password page
3.  The password field should be prepopulated. If not, focus on the first password field and choose the previous username/password pair.
4.  Notice that when any pair is hovered on, the underline of the field is covered and thus invisible, which causes a style issue.

![Screen Shot 2019-09-03 at 3 31 06 PM](https://user-images.githubusercontent.com/6769465/64152869-1968ed80-ce60-11e9-85c1-1ac9594f315e.png)

## Versions

**App**

* Angular: 8
* Clarity: 2

**Device:**

* Type: MacBook 10.13.6
* Browser chrome 76

**Comment by Jinnie** [comment]
Auto-fill is a browser feature, which we have no control over. Setting focus on the password field is something that's not expected to happen while auto-filling. There are also numerous password management 3rd party solutions, which may have various approaches to focus handling and highlighting the fields they operate on.
All this happens on the browser level or above it, and is outside the scope of Clarity.

**Comment by h657070128** [comment]
@Jinnie Thanks for the quick response. I believe those widely used third-party plugins also follow some kind of standards when dealing with these inputs. In clrPassword case, it is the introduction of the wrapper `clr-input-group` that causes the plugin to behave incorrectly. I still believe it's better for Clarity to be compatible with it. For our project, we have to find a way to overwrite the styles or fallback to use `clrInput` for password field and implement our own password visibility toggle functionality.

**Comment by Jinnie** [comment]
@h657070128 I presented this for discussion in the team. If we decide we can invest in it, I'll update and reopen the issue.
Thanks for your report!

**Comment by gnomeontherun** [comment]
It looks like we can investigate further, just to confirm @h657070128 are you just using Chrome's built in password system or is this a third party tool? Some third party tools might cause more issues than we can accommodate depending on how they are implemented.

**Comment by h657070128** [comment]
@gnomeontherun Hi Jeremy, yes I am using Chrome's built-in password system. Attached is another screenshot on the login page of Clarity docs site(https://clarity.design/documentation/login). Thank you guys for the open attitudes towards it!

<img width="852" alt="Screen Shot 2019-09-04 at 9 24 50 AM" src="https://user-images.githubusercontent.com/6769465/64219136-c7bf7200-cef6-11e9-9630-97e0a4297d6c.png">

**Comment by florin-borceanu** [comment]
I investigated this issue and I found out that this "feature" is implemented only in Chrome and Opera. The position of the underline is different between clrPassword and basic password, as you can see here:
![Screenshot from 2019-09-09 09-53-13](https://user-images.githubusercontent.com/53469024/64509101-afc96300-d2e7-11e9-9340-2bf84497fb6e.png)

![Screenshot from 2019-09-09 09-52-41](https://user-images.githubusercontent.com/53469024/64509059-9c1dfc80-d2e7-11e9-8de5-7cdcfec36167.png)

The easiest way to solve this is to move the underline a few pixels down, because, as long as I investigated, there is no certain way to remove the auto-fill background (there are some "tricks" that change the color to white, but the underline is still covered and I tested it only on Chrome).

**Comment by gnomeontherun** [comment]
We aren't going to change the underline behavior right now, we only want to consider implementing a workaround to the autocomplete behaviors in Chrome/Opera (probably latest Edge). See https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/ for additional considerations.

**Comment by florin-borceanu** [comment]
Hi @gnomeontherun 
I took a look over this trick, and the only thing that can be done is to change the background color, it cannot be transparent. Also, it cannot be moved, so, the underline is still covered.
This is the best result I can get:
![Screenshot from 2019-09-10 11-21-54](https://user-images.githubusercontent.com/53469024/64596797-43209800-d3bd-11e9-94a5-76fb2a19fcd4.png)
![Screenshot from 2019-09-10 11-20-55](https://user-images.githubusercontent.com/53469024/64596798-4451c500-d3bd-11e9-9685-34cf76754c95.png)
If this is the right fix for this issue, you can assign me to this issue and I will fix it that way.

**Comment by gnomeontherun** [comment]
I don't think it makes sense to change this behavior then, because it makes it more confusing about what is happening. Let's just mark this for design to review in a forms audit and leave the behavior for now.

**Comment by nmarkapuram-vmw** [comment]
HI @gnomeontherun , Today I too faced the issue while changing the earlier clarity input to password and noticed that the ticket is already available for this. 

I found a small workaround for this. Need your input on this.

Workaround
Apply the theme background color (#fafafa) for autofill and increase the padding bottom of clr-input-group is resolving it.

input:-webkit-autofill, input:-webkit-autofill:hover, input:-webkit-autofill:focus, input:-webkit-autofill:active {
    -webkit-box-shadow: 0 0 0 30px #fafafa inset;
}

.login-wrapper .login .login-group .clr-control-container .clr-input-wrapper>.clr-input-group {
*****Existing*****
padding:bottom:1.3rem;
}

I tested in Chrome, Safari for now.

Attaching the screenshot
<img width="504" alt="Screenshot 2020-10-22 at 5 54 14 PM" src="https://user-images.githubusercontent.com/52527886/96871987-a326b080-1490-11eb-87ab-51c2060ec28d.png">

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
