### ISSUE TITLE
Need some icons to be added to clarity-icons for feature parity with fontawesome

### ISSUE THREAD

**Issue by clementcur** [vmware/clarity#378]
We’re currently using fontawesome for our iconography. We're doing the switch to clarity-icons, but we are missing a few icons:
 - http://fontawesome.io/icon/tags/
 - http://fontawesome.io/icon/plus-circle/
 - http://fontawesome.io/icon/circle/
 - http://fontawesome.io/icon/columns/

Could those be added to the set of icons in clarity-icons?

**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Environment details

* **Angular version:** 2.2.4

* **Clarity version:** 0.8.2

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by lil-kim** [comment]
Delivered the requested svg icons as part of a larger set to @Shijir via OneDrive:
Files > Clarity-UX-Design > Icons:
volume2_complete_svg.zip

**Comment by clementcur** [comment]
Thx Lilia for fixing it so quickly!
Just one question though, I can see the 'tag' icon in the new [iconography release](https://vmware.github.io/clarity/documentation/iconography), but not the 'tags' one, is it coming in a next release?
I found all the other ones, they're perfect, thx!

**Comment by Shijir** [comment]
@clementcur there are few icons including `tags` icons that I am still working on their markups. They will be released in next week.

**Comment by clementcur** [comment]
@Shijir perfect, thx a lot!

**Comment by clementcur** [comment]
@Shijir it looks like we would require another icon: 
 - http://fontawesome.io/icon/university/
We're using this icon in the context of a budget value. Let me know if you prefer me to open a new issue and if it can make it to the next release.
Thx!

**Comment by jaffoneh** [comment]
@clementcur could you open another ticket (since this one is closed, we want another ticket open so we're able to assign it and have it go through both design and implementation). Thanks!

**Comment by clementcur** [comment]
sure, done: https://github.com/vmware/clarity/issues/423
