### ISSUE TITLE
Specs + Visual discrepancy - Button text in Docs, Sketch Template and Build

### ISSUE THREAD

**Issue by EileenLB** [vmware/clarity#379]
**Select one ...**  (check one with "x")
```
[ x ] bug
[ ] feature request
[ ] enhancement
```
**The following tasks will be needed:**

1. Determine the desired visual style for the Button text
2. Update Clarity Typography Docs, Sketch/Invision files –or– code accordingly

### Expected behavior
The appearance & specifications for the Button text should be consistent between the Clarity Typography docs, Sketch Template, and the build.

### Actual behavior
These specifications in the Sketch Template are different 
from what is implemented in the Clarity build.
- line-height
- letter-spacing
- font-size
- font-weight

These specifications in the Clarity Typography docs are different 
from what is implemented in the Clarity build.
- letter-spacing
- font-size

### Reproduction of behavior
See these screen captures:

**Clarity Typography specifications**
![btn-text-docs-typography-specs](https://cloud.githubusercontent.com/assets/14795506/22118178/a02061dc-de2b-11e6-8af3-c791a6f7b8b0.png)

**Sketch Template specifications**
![btn-outline-sketch-specs](https://cloud.githubusercontent.com/assets/14795506/22080704/61a9bdf6-dd75-11e6-9eeb-b07d8fe5eaf0.png)

**Build CSS specifications**
<img width="1545" alt="btn-outline-build-specs" src="https://cloud.githubusercontent.com/assets/14795506/22080787/ab581128-dd75-11e6-9fda-2dfe3377592d.png">

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.8.2

* **OS and version:**  Version doesn't matter.  The issue is in the code, not the OS.

* **Browser:** [all |

**Comment by reddolan** [comment]
*Font Size & Font Weight*
@EileenLB according to the original [InVision spec](https://vmware.invisionapp.com/d/main#/console/9262860/198357235/preview) the UI Template is correct. There are two different sized buttons, Normal and Small. Normal is 12px semibold, Small is 11px semibold (which is what your screenshot shows). This also means that the [Button](https://vmware.github.io/clarity/documentation/buttons) CSS above is also correct (at 12px). 

What is incorrect is the [Typography documentation](https://vmware.github.io/clarity/documentation/typography) where is calls out Button at 13px. That is an old spec when We were using Proxima Nova. We will update the Typography page with the correct specs.

*Line Height*
UI Template: This is set like this as it was causing conflicts in symbol creation

*Letter Spacing* 
There isn't a way to replicate .12em in Sketch, this is the closest we came (value of 1)

**Comment by reddolan** [comment]
**To Dev**
[Typography](https://vmware.github.io/clarity/documentation/typography) documentation needs to be updated. Changes
- for row .p3 the instance of "Button text" should be on .p4 and read "Button text (Normal)"
- add "Button text (small)" to row .p6

![image](https://cloud.githubusercontent.com/assets/1858226/22261283/eda06060-e231-11e6-899f-0f2dcda74393.png)

**Comment by bonnielovesgreen** [comment]
Hey @reddolan, correct me if I'm wrong, but I think the Button CSS is still incorrect. Isn't 400 font weight regular not semibold? I noticed these discrepancies yesterday.

**Comment by reddolan** [comment]
@bonnielovesgreen ah yes, you are correct. I will ping Matt about this too

@hippee-lee the font weight on Buttons should be semi-bold which is 500, not 400 which it currently is. This change will need to happen too

**Comment by hippee-lee** [comment]
@reddolan - is this a change for all buttons? (just trying to scope the impact of making font weight changes for the docs)

**Comment by reddolan** [comment]
@hippee-lee is that the value in the CSS/Sass that goes out into the repo or is it just on the website? When I inspected the CSS on that page, it looked like it was just on the site. But I didn't look very hard.

**Comment by hippee-lee** [comment]
Which page  are you seeing buttons with the wrong weight? 
I'm looking at the typography page but there aren't any buttons on there. 
I'm pretty sure it's an easy change in the scs. Because it will also impact all buttons, I want to be sure before I change it.

**Comment by reddolan** [comment]
[Buttons](https://vmware.github.io/clarity/documentation/buttons) page is showing a font-weight:400

![image](https://cloud.githubusercontent.com/assets/1858226/22435055/22b0cb44-e6e4-11e6-861d-191fa8e3abf4.png)

**Comment by hippee-lee** [comment]
Got it. Thank.
I'll look into getting this live today.

**Comment by reddolan** [comment]
@hippee-lee font-weight:500 is correct. Thanks for getting this out
