### ISSUE TITLE
Dropdown is overriding `id` provided to `clrDropdownItem`

### ISSUE THREAD

**Issue by kalpeshhpatel** [vmware/clarity#3795]
## Describe the bug

In Clarity version 2, we can't provide custom `id` to dropdown item.
If we explicitly provide `id`, it overrides it with some autogenerated id. (for instance. `clr-id-12`)

## How to reproduce

1.  Go to 'https://stackblitz.com/edit/clarity-light-theme-v2-upskue'
2.  Note that `action1` id has been added to `Action 1` in HTML code (https://stackblitz.com/edit/clarity-light-theme-v2-upskue?file=src%2Fapp%2Fapp.component.html)
3.  Click on 'DROPDOWN' to open dropdown menu
4. Observe the `id` of `Action 1` dropdown item.
4. It has been overridden to another ID that starts with `clr-id-`

## Expected behavior

If `id` has been provided to any element, it should use that `id` instead of overriding.

## Versions

**App**

* Angular: ^8.0.0
* Clarity: ^2.0.0

## Additional notes

This behavior breaks our automation test suite and other business logic.

**Comment by gnomeontherun** [comment]
This does appear to be a problem, though I don't recommend putting an ID in there to begin with in this case because we have to link some aria-attributes with that ID. We will backlog this bug as something that we should fix, but I don't know in what cases you'd want to put an ID on the element?

**Comment by lx307697527** [comment]
I have the same issue. when i use the id to mark an element for test case, i found the id was overrided by clarity. is there any solution?

**Comment by gnomeontherun** [comment]
The workaround is to use another attribute like `data-id` until we fix this internally.
