### ISSUE TITLE
Datagrid - Multiline Text

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#38]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
```

### Expected behavior
Currently, multi-line text is supported(-ish) for text inside rows. We don't have a spec for multi-line text in column headers, though. So:
1) Confirm the current design for multi-line text in rows is the one we want. See screenshot attached.
2) Create spec for multi-line text in headers.

<img width="949" alt="screen shot 2016-08-19 at 16 56 32" src="https://cloud.githubusercontent.com/assets/690949/20275905/120b62c6-aa4f-11e6-80a6-634f19422770.png">

**Comment by vkpavan26** [comment]
Any update on this enhancement ? When is this planning to be released?

We have a use case of Multi-line text in rows.

**Comment by youdz** [comment]
Multi-lines work fine both in rows and in headers. This issue was here just to make sure that the UX side of the team was fine with the current design (aligned top, line-height, ...).

Multi-line in headers have been fixed a while back too, there is no issue with them.

**Comment by jaffoneh** [comment]
@yenmade since this seems to work based on the demo available here: https://vmware.github.io/clarity/documentation/datagrid I am closing this issue. Please reopen with specific issues if needed or if we have a difference in the design required. For now, this works as the screenshot shows.
