### ISSUE TITLE
Restarting Fade progress bar causes backward animation 

### ISSUE THREAD

**Issue by RainTomassi** [vmware/clarity#380]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Fade Progress bar reinitializes to 0 progress without animation. 

### Actual behavior
I'm using a flash then fade progress bar for file upload progress.  It is quite lovely seeing the progress bar animate up to 100, flash green, then fade out.  However, when I reset the progress value back to 0 in anticipation of another upload, the progress bar shows up and animates itself downwards down to 0. 

I tried hiding the bar, resetting the value to 0, then displaying it, but I may not be doing that correctly, as it still seems to have the same behavior. 

Is this expected behavior? If so, can you suggest a way to work around it?  It is a beautiful control, but that re-animation as it jump back down to zero catches my eye every time. 

I can understand a use case for having negative progress for the other controls once progress reaches 100, but it feels as though the spirit of the fade progress is that when it fades out, progress for that instance is complete. 

### Reproduction of behavior
Behavior can be seen in the docs for the Flash then Fade progress bar: 
https://vmware.github.io/clarity/documentation/progress

### Environment details

* **Angular version:** 2.0.X
"@angular/core": "^2.3.1"

* **Clarity version:** 
    "clarity-angular": "^0.8.1",
    "clarity-icons": "^0.8.1",
    "clarity-ui": "^0.8.1",

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
That's not the intended behavior. I'll tag this as a bug. Thanks for filing an issue on it.
