### ISSUE TITLE
icons: could not add new icons with capital letters for shapeName

### ISSUE THREAD

**Issue by bdryanovski** [vmware/clarity#3800]
## Describe the bug

When you add a new shape icon with capital letter - you could not fetch it with the `clrIcon` component

```js
ClarityIcons.add({"customIcon": "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 36 36'><title>MAC set</title></svg>"});
```

```html
<clr-icon shape="customIcon" size="36"></clr-icon>
```

The icon is not found.

## How to reproduce

https://stackblitz.com/edit/clarity-dropdown-search-k2gi83

## Expected behavior

The icon must be shown no matter the shape name.

## Versions

**App**

* Clarity: 2.2.0

**Device:**

* OS: All
* Browser All

## Additional notes

When adding icons we use this method. 

```js
// src/clr-icons/clr-icons-api.ts 66:77
  add(icons?: IconShapeSources): void {
    if (typeof icons !== 'object') {
      throw new Error(`The argument must be an object literal passed in the following pattern: 
                { "shape-name": "shape-template" }`);
    }

    for (const shapeName in icons) {
      if (icons.hasOwnProperty(shapeName)) {
        this.setIconTemplate(shapeName, icons[shapeName]);
      }
    }
  }
```
`setIconTemplate` won't change the name of the shape at any point so the icon will be registered with the capital letter. When we try to get the icon we will search for `customicon` instead of `customIcon` so we won't find anything. 

```js
// src/clr-icons/clr-icons-element.ts 88:96
  if (this.hasAttribute('shape')) {
    const shapeAttrValue = this._normalizeShape(this.getAttribute('shape'));

    this._shapeTemplateSubscription = ShapeTemplateObserver.instance.subscribeTo(
      shapeAttrValue,
      (updatedTemplate: string) => {
        this._injectTemplate(updatedTemplate);
      }
    );
```
The reason for that is that there is this method `this._normalizeShape` will trim the name of the icon but also will replace all capital letters. 

The reason for replacing all capital letters is to be able to not make a difference when requesting icons from the component.

```html
<clr-icon shape="customicon" size="36"></clr-icon>
<clr-icon shape="CUSTOMICON" size="36"></clr-icon>
```
That have to be the same icons. Icon names don't have to be case-sensitive.

There is a workaround of that issue: DONT use capital letters when adding icons, and everything will work as expected. Also non of the Clarity icons have capital letters in their names so for consistency newly added icons are not planned to have capital letters in there name.

**Comment by danail-vasilev** [comment]
Just a small correction in the description that the issue has been reproduced since v2.1.0

**Comment by gnomeontherun** [comment]
I believe this is related to the `toLowerCase` functionality that was added, but it didn't get pulled through all the way.

**Comment by bdryanovski** [comment]
There are two quick solutions for that issue:

* Update `validateName` function in `clr-icons.api.ts` to throw an error when the name includes upper case character.

```js
throw new Error('Shape name or alias must not contain any capital letter characters!');
```

* Update `add` function in `clr-cions.api.ts` to make everything to `lowerCase`
```js
icons.shapeName = icons.shapeName.toLowerCase()
```

Other option is to revert the change for `toLowerCase` into the component. But this will introduce the bug that this two things will be separate icons `[shape]='Settings'` and `[shape]='settings'`

**Comment by gnomeontherun** [comment]
We should not throw errors in cases we can handle. This lower case functionality was added without a real request to do so, so we own this as a regression for breaking behaviors. It used to be case sensitive (because JavaScript strings `'Settings' !== 'settings'` and this was fine in the past. 

However, I think it makes sense to be case insensitive and to always lower case the names during insertion. That would be the best fix and keep everybody going, with the potential exception if someone did have two by the same name, but different capitalizations. Therefore, this should only go into `master`.
