### ISSUE TITLE
On website forms page Input grouping heading overlaps example

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#3802]
## Describe the bug

The heading of the `Input groups` section overlaps previous `Do/Don't` section.
<img width="488" alt="Screen Shot 2019-09-10 at 1 51 33 PM" src="https://user-images.githubusercontent.com/1798828/64608096-951fe880-d3d2-11e9-89ab-6ac7d7c04b80.png">

## How to reproduce

1.  Go to https://clarity.design/documentation/forms
2.  Scroll down to "Input grouping" section
3.  See that it overlaps previous example

## Expected behavior

Heading starts after the example

## Versions

**App**
* Clarity: 2.2.1

**Device:**

* Type: Mac
* Browser: chrome, safari

## Additional notes

It seems to be fine the v1 site documentation

**Comment by florin-borceanu** [comment]
I investigated and I found out that the issue is caused by a `height: 100%` added in https://github.com/vmware/clarity/commit/874e82278ac3e5a8181607759e76e18e3f2207c0
I will investigate more, in case that something else is affected.

Can you assign me? Thanks!
