### ISSUE TITLE
ClrDatagridFilter openChange event not being fired

### ISSUE THREAD

**Issue by davidrourke** [vmware/clarity#3804]
## Describe the bug

The ClrDatagridFilter openChange event is not being fired.  The event name has been changed from openChanged (in v2.1.2) to openChange (in v2.2.0).

## How to reproduce

In version 2.1.2, I subscribed to the openChanged event and received events.  However, in version 2.2.0, I now am subscribed to the openChange event, but I am not receiving events.

I have provided a stackblitz.io example: https://angular-denw5k.stackblitz.io

## Expected behavior

I should receive openChange events.

## Versions

**App**

* Angular: 8.0.0
* Node: 10.14
* Clarity: 2.2.0

**Device:**

* Type: MacBook Pro
* OS: 10.14.6
* Browser Chrome
* Version Version 76.0.3809.132

**Comment by davidrourke** [comment]
Any update on this?  Since this broke current functionality, I would think it would be a higher priority.  In addition, this is keeping me from upgrading to your latest release (2.2.1) which I need to address other issue we are experiencing.

**Comment by tnuttin1** [comment]
Any update on this bug fix?
