### ISSUE TITLE
Dark / bright theme switch via prefers-color-theme CSS

### ISSUE THREAD

**Issue by pumano** [vmware/clarity#3807]
## Summary

Currently we can only use one theme and theme switching is annoying problem. Looks like will be good to have support for new CSS media query rule : `prefers-color-theme` for applying theme styles. 

* What is the change?
Possibility to switch theme at runtime
* Why should it go in Clarity?
Better UX for users
* Does this change impact existing behaviors? If so how?
Yes, looks like need to change styles to support it
* If this change introduces a new behavior, is this behavior accessible?

## Use case

Possibility to switch theme without problems via CSS

## Examples

Any popular application possible to switch theme

## Workarounds

Has workaround

**Comment by mathisscott** [comment]
':prefers-color-theme` has no support in IE or Edge 18, so we cannot introduce a feature into the library to use it to switch between dark and light theme.

If your product does not need to support current Microsoft browsers, you can use this on the product side by building the dark theme CSS (`ng serve dev -c dark`) in terminal and then grab the generated CSS and apply it in your own app.

We will be introducing an easier way to theme (and switch between themes) in 3.0 and ultimately drop the current SASS-based theming in 4.0.
