### ISSUE TITLE
Datalist component

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3813]
## Summary

Implement an HTML `datalist` element as an Angular control, and make sure it fits well within our forms layouts and styling.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist 

* What is the change? This is a new component but of an existing HTML element that is widely supported
* Why should it go in Clarity? It provides a limited combobox like behavior and might be ideal in many scenarios
* Does this change impact existing behaviors? If so how? No its new
* If this change introduces a new behavior, is this behavior accessible? It should be the same as other form controls

## Use case

We've seen people using dropdowns to create a combobox like functionality, but a datalist is often sufficient. 

## Examples

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by florin-borceanu** [comment]
I would like to be assigned. Thanks!

**Comment by AlexMarcuBytex** [comment]
Im currently working on this. I investigated the datalist more carefully and i found that css style wont work for these datalist options.
![Screenshot from 2019-10-04 17-17-20](https://user-images.githubusercontent.com/53469146/66214751-ff266780-e6ca-11e9-90be-a66f103224e2.png)

In this case, what should be done?

**Comment by gnomeontherun** [comment]
For this, the best styling that we can do out of the box is where we should start. We don't style everything in a select box fully because HTML form elements don't always have ways to do this. So get as far as possible and we'll review it.
