### ISSUE TITLE
Datagrid pagination reset current page when destory

### ISSUE THREAD

**Issue by sdg32** [vmware/clarity#3815]
## Describe the bug

When datagrid pagination destory, it will reset current page to 1. I am not sure it’s a bug or not.

In my application, when user close the detail page and back to list page, they may forget the last page number they visited. So I cache the page number, then users can see the last page they visited instead of first page. But the pagination reset the current page, the last page number is always 1.

## Expected behavior

Pagination should not reset current page to 1 when destory.

## Versions

**App**

* Angular: 8
* Clarity: 2.2.0

**Comment by gnomeontherun** [comment]
Are you wanting the pagination to not reset before destroy? What is the use case exactly? I can imagine a way for us to prevent the binding/output from updating, but want to understand what your expectations are better.

**Comment by sdg32** [comment]
I want to cache the pagination current page and page size, so I can show the data when user back to the list page.

For example, in order list page, user add sort and some filters. Then user nagivate to page 3, click one order item to see the detail. When user back to the order list page, I want to show the page 3 with sort and filters instead of page 1.

Actually, I found `clrDgRefresh` event is better than `clrDgPageChange`. I just don't quite understand the purpose of the pagination reset page before destroy.
