### ISSUE TITLE
Transform on body tag breaks new popover positioning

### ISSUE THREAD

**Issue by sgrtho** [vmware/clarity#3820]
## Describe the bug

Adding a transform to the body tag breaks popover positioning.

## How to reproduce

Go to [https://stackblitz.com/edit/angular-mfe4zt](https://stackblitz.com/edit/angular-mfe4zt):

1. Try out the popovers (column toggle, single action menu)
2. Hit the top button to toggle the transform
3. Scroll a little down, e.g. to the bottom
4. Try the popovers again (now misplaced)

## Expected behavior

No change when transform is there.

## Versions

**App**

* Angular: [8]
* Clarity: [2.2]

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
