### ISSUE TITLE
Datagrid Sort Icons remain active until column is resized

### ISSUE THREAD

**Issue by rootix** [vmware/clarity#3823]
## Describe the bug

When sorting different columns, all of them remain visually in sorted state until you resize the particular column. Then the state is correctly removed.

Same happens if you programatically set the sortOrder of a column. The icon is only shown after you resize the affected column. 

## How to reproduce

You can reproduce it on the documentation website of Version 2.2.0:

https://clarity.design/documentation/datagrid/binding-properties

1.  Sort by the "Name" column
2.  Sort by the "Creation Date" column
3.  Resize the "Name" column

## Expected behavior

When sorting a column, all other columns should not be shown as sorted anymore.

## Versions

**App**

* Angular: 8.2.6
* Node: 10.6
* Clarity: 2.2.0

**Device:**

* OS: Windows
* Browser: Brave
* Version 0.68.132 Chromium: 76.0.3809.132

**Comment by rootix** [comment]
Interesting thing: I can reproduce this in my local usage and on the website in every browser on my machine: Edge 18, Internet Explorer 11, Firefox, Chrome and Brave. But others in my company don't have this problem. I fear that this is not an easy reproducable issue. From my perspective it looks like a change detection issue but i have no idea how it can differ from machine to machine.

**Comment by plaisted** [comment]
I am experiencing this same behavior since upgrading to 2.2.0.

**Comment by gnomeontherun** [comment]
This definitely looks like a bug that we need to review.

**Comment by slcj** [comment]
I'm also experiencing this behaviour since upgrading to 2.2.0.
Angular 8.2.8
Chrome 77.0, Firefox 69.0 Safari 12.1.2 on Mac-OS
Chrome 75.0 and Firefox 60.7.1esr on Windows 10

I'm not experiencing this bug with version 2.1.0.

**Comment by ph55** [comment]
Exist on both server and client grids.
You can reproduce on official docs:

![image](https://user-images.githubusercontent.com/1386622/66589934-4bc0e580-eb98-11e9-9f42-cdeb9f27c70f.png)

![image](https://user-images.githubusercontent.com/1386622/66589987-727f1c00-eb98-11e9-9bb5-4aeabc977496.png)
