### ISSUE TITLE
First aid kit icon

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#3828]
## Summary

* What is the icon?

An icon depicting a first aid kit.

* What does the requested icon signify?

Quick help.

## Use case

Similar to the help icon, but with a focus on fixing existing problems. 

Help icon: How exactly do I use application X?
Fist aid kit icon: What can I do if application X is broken?

## Examples

![98137](https://user-images.githubusercontent.com/3655915/65031735-154dcd00-d942-11e9-9279-48882283c358.png)

## Alternatives

The help icon. In my opinion this icon however is best used for general FAQ style help.

**Comment by gnomeontherun** [comment]
@lil-kim

**Comment by lil-kim** [comment]
This icon was completed as a part of epic #3688
