### ISSUE TITLE
Clarity structure breaks Angular `scrollPositionRestoration`

### ISSUE THREAD

**Issue by jeremywiens** [vmware/clarity#3829]
## Describe the bug

_When the Clarity structure is used (main-container, content-container, etc.), Angular's routing option of `scrollPositionRestoration` does not work as expected._

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-afps9j

**Note**: Ensure that lines 1, 13, 14, 16, 17, and 18 are still **commented** out in `app.component.html`.

1.  Open in new Window (live) (Does not work on the stack blitz side browser)
2.  Scroll down home page and press button `New Page`
3.  Notice page navigates to top of the page as expected
4.  Press back arrow to navigate back to the home page, page navigates to where the user left off on home page
5.  Go to the code editor and un-comment lines in `app.component.html`
6.  Repeat steps 1-4 but notice the behavior is not as expected

## Expected behavior

Note: I am fairly new to clarity, I could be missing something. However, I expect that using Clarity's layout should not impact Angular's navigation.

## Versions

**App**

* Angular: [e.g. 8.0.0]
* Node: [e.g. 8.9.4]
* Clarity: [e.g. 2.0.0]

**Device:**

* Type: [e.g. Lenovo]
* OS: [e.g. Windows]
* Browser [e.g. chrome]
* Version [e.g. 76]

## Additional notes

_Verified same result on recent versions of Edge and Firefox._

**Comment by gnomeontherun** [comment]
I believe this is related to the viewport locking we do to create the two panes in main-container, it also causes us issues with our visual screen testing. This is likely a side effect of some of the CSS used, which we'll have to investigate.
