### ISSUE TITLE
Clarity font semibold weight does not render correctly

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#383]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Screenshot of the semibold font weight when the font is directly used without the BASE64 encoding:
<img width="204" alt="screen shot 2017-01-19 at 12 52 51 am" src="https://cloud.githubusercontent.com/assets/1426805/22121148/a4159dd2-de37-11e6-9be9-77ea049573c3.png">

### Actual behavior

Metropolis semibold font doesn't render correctly on Windows. We are not able to replicate this issue when we use the font directly so we suspect this has something to do with the font BASE64 encoding process.

Screenshot of what semibold looks like:
<img width="520" alt="screen shot 2017-01-19 at 12 53 30 am" src="https://cloud.githubusercontent.com/assets/1426805/22121131/8e8f799c-de37-11e6-820b-01fabc105d5d.png">

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** All

* **OS and version:** Windows

* **Browser:** [IE all]

**Comment by tigran-av** [comment]
Any updates on this?

**Comment by jaffoneh** [comment]
@tigran-av we're actually looking at it at the moment. @adityarb88 is trying to figure out what's going on here.

**Comment by likwifi** [comment]
@adityarb88 I've just converted woff font to base64 and this issue seems to fixed
[fixed style.txt](https://github.com/vmware/clarity/files/756762/fixed.style.txt)

**Comment by adityarb88** [comment]
Hi @likwifi: Thanks! I published a PR for this fix yesterday: https://github.com/vmware/clarity/pull/460. Although the change is very simple, we need to test multiple things before merging it since it affects all components. Also, I wasn't able to replicate this issue consistently. It appeared a few times but only on Windows 8 IE11. Edge and IE10 worked fine without the fix so it may be the browser too which is causing this issue.

On a different note, could you tell us how you generated the base64 version? Just command line or font squirrel?

**Comment by likwifi** [comment]
Ok, great.
I've used this one https://www.giftofspeed.com/base64-encoder/

**Comment by tigran-av** [comment]
An updated Metropolis looks like fixing 14px 600 bold, but introduces some problems with 11px 600 (datagrid header settings). We will doublecheck it to provide more info.

**Comment by adityarb88** [comment]
Hi @tigran-av: I tested it again on Windows 8 IE11 and it looks fine to me. Screenshots below:

Before:
<img width="860" alt="screen shot 2017-02-08 at 5 48 45 am" src="https://cloud.githubusercontent.com/assets/1426805/22739866/65fea2ba-edc2-11e6-8e36-2e6a3d5f4d5c.png">

After:
<img width="990" alt="screen shot 2017-02-08 at 5 49 05 am" src="https://cloud.githubusercontent.com/assets/1426805/22739870/69e96d9c-edc2-11e6-8064-f28c565c29eb.png">

Please provide more info on which browser you are testing on so that we can replicate the issue.
