### ISSUE TITLE
clr-alerts, *ngFor, and OnPush issue

### ISSUE THREAD

**Issue by real-artswan** [vmware/clarity#3834]
## Describe the bug

I have custom component that uses OnPush strategy, it wraps clr-alerts which contains clr-alert components bind to array with *ngFor. On the first load it shows all contained alerts at once. If I change change detection strategy to default all works as expected.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-j4pjrh

## Expected behavior

it should not show all alerts at once.

## Versions

**App**

* Angular: 8
* Clarity: 2.0-2.2

**Comment by gnomeontherun** [comment]
Curious, we'll have to investigate this further. Workaround is not to use OnPush, which doesn't save you much here anyways.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
