### ISSUE TITLE
[core] Add confirmation to the npm run publish:all task

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#384]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior

When publishing clarity to the npm repository the user should be prompted with a yes / no choice before the task proceeds with publishing on npm. `Yes` continues publishing the packages to npm. `No` stops the publishing task `npm run publish:all`

### Actual behavior
Currently when running `npm run publish:all` the task automatically publishes to npm. 

### Environment details
n/a

**Comment by mathisscott** [comment]
@hippee-lee : is this still something we want to keep in our backlog?

**Comment by hippee-lee** [comment]
@mathisscott it hasn't been an issue so far. If we decide to do it, this can be re-opened.
