### ISSUE TITLE
[Header] Put overflow items in a dropdown

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3843]
Clarity responsive header shows hamburger on a media breakpoint. But if screen is larger, all items, which doesn't fit into a screen, gets cut off or force page to scroll horizontally (which may be highly unwanted), depending on overflow behavior set on a particular page.
Most popular approach is to put those items in a drop-down menu (I would like to consider other options as well).

I would like to see this implemented for Clarity header component.
Header should track it's items (not just nav-links) width, and dynamically put them into a special drop-down menu.

Workarounds: to implement it manually.

![image](https://user-images.githubusercontent.com/32732457/65501969-9a009400-deca-11e9-9c02-94156d273fa6.png)

[Stackblitz](https://stackblitz.com/edit/clarity-dark-theme-v2-xk7gtl?file=src/app/app.component.html)

**Comment by gnomeontherun** [comment]
Thanks for the suggestion, I'll put it into our list of considerations.

**Comment by cristianfalcone** [comment]
A pattern, examples and implementations to take in consideration for this: https://css-tricks.com/the-priority-navigation-pattern/

**Comment by boeckMt** [comment]
If it is possible to customize the breakpoint of the Responsive Navigation then the items maybe could be placed there.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
