### ISSUE TITLE
[Header] Drop-downs support in header

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3844]
Many applications and web-sites doesn't fit in Clarity 3-level navigation model. And there are a lot of cases, when you need multi-level menu inside Header component (alone, or even when used together with subnav or side menu). For example, when you want to let users see which 2nd-level nav items can be found inside, without forcing him to navigate just to see what's inside.

Technically, I can put drop-down menu and add nav-link class to it, but it won't be properly styled.
![image](https://user-images.githubusercontent.com/32732457/65464936-c1704600-de63-11e9-908e-98411c5e1c34.png)
![image](https://user-images.githubusercontent.com/32732457/65464978-dcdb5100-de63-11e9-8b7c-0c2b735c406d.png)

Dropdowns work only in header actions section, which is not enough.

[Stackblitz](https://stackblitz.com/edit/clarity-dark-theme-v2-fddu6b?file=src/app/app.component.html)

Workaround: fix css manually. 

```
@mixin header-nav-dropdown {
  .header-nav {
    & > .dropdown {
      $clr-header-action-caret-icon-right-position: 0.5rem;

      & > .dropdown-toggle {
        height: $clr-header-height;
        line-height: $clr-header-height;
        @include header-nav-appearance();
      }

      $dropdown-nav-text-dist: 1.5rem;
      .dropdown-toggle.nav-text {
        padding: 0 $dropdown-nav-text-dist 0
          $clr-header-nav-text-horizontal-padding;

        clr-icon[shape^='caret'] {
          right: $clr-header-nav-text-horizontal-padding;
        }
      }

      .dropdown-toggle.nav-icon {
        padding-right: 0;
        width: $clr-header-height;
      }

      // Pull the dropdown menus of all dropdowns up to compensate for the height of the header.
      .dropdown-menu {
        left: auto;
        margin-top: -0.166667rem;
        right: 0;
      }
    }
  }
}

header,
.header {
  @include header-nav-dropdown();
}
```

**Comment by gnomeontherun** [comment]
I need to dig into the history of why we don't have dropdowns, but the vertical nav is where we intend to have nested links. Adding to considerations.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
