### ISSUE TITLE
[Header] Add support for fixed/sticky header. 

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3845]
I'd like to have an option for Header component, which would control it's appearance during page scrolling.

Please, consider following scenarios.

### Fixed header

Equal to position: fixed. Page content should be automatically shifted down on a size of header's height (plus, perhaps, app alert height, if it's present).

### Sticky header

Same as fixed, but header must disappear when user scrolls down, and appear, if user scrolls up.

### Transparent background

Initially, header background is transparent.
When users scrolls page content and reaches some breakpoint, background switches from transparent to selected color.
Additionally, if app-level alert is present, it should probably stay fixed.
Applies to both fixed and sticky headers.

Optionally, Clarity may also expose some service and/or directive, to let user add sticky behavior to his own custom components.

I saw something similar implemented in Icons page on a website internally, but it looks pretty heavy and isn't suitable for implementing such behavior quickly.

**Comment by gnomeontherun** [comment]
Another interesting suggestion, and again I need to dig into the history and see if there are reasons we haven't done this already.

**Comment by elielia** [comment]
Is there any way of achieving a sticky header at the moment?

**Comment by sdurnov** [comment]
@elielia with css overrides and a custom directive which will track page scroll direction - yes, but it may be tricky to set up scroll thresholds and show/hide animation for it to work perfectly. Also, I still need to find how to correctly work with mobile browsers overscroll. I'll paste a snippet here or via Stackblitz later if I'll have time.

**Comment by sdurnov** [comment]
> Is there any way of achieving a scrollable header at the moment?

Do you mean, horizontal scrolling of a content inside the header?

**Comment by elielia** [comment]
@sdurnov Thanks. No, I meant that the header won't be sticky and will scroll up/down when scrolling the page.

**Comment by sdurnov** [comment]
> @sdurnov Thanks. No, I meant that the header won't be sticky and will scroll up/down when scrolling the page.

If you mean fixed header, that will always stay on top of the page, all you need is to add position: fixed to header's container and add bigger top margin to content area.

**Comment by quanglddev** [comment]
> > @sdurnov Thanks. No, I meant that the header won't be sticky and will scroll up/down when scrolling the page.
> 
> If you mean fixed header, that will always stay on top of the page, all you need is to add position: fixed to header's container and add bigger top margin to content area.



> @sdurnov Thanks. No, I meant that the header won't be sticky and will scroll up/down when scrolling the page.

Any chance you know how to disable the sticky header? I don't want the header to always be there like @elielia said.
Also, I find that any element that is put inside <clr-main-container> is sticky. I'm trying to make footer for website but it's always appeared sticky on the phone view.

My code summary is this:
`<clr-main-container class="main-container">
  <app-top-nav></app-top-nav>
  <div class="content-container" style="flex: 1;">
    <ng-content></ng-content>
  </div>
  <app-footer class="footer"></app-footer>
</clr-main-container>
`

Any suggestion is great apprreciated. I've tried changing some css in source code such as position: fixed but it doesn't work. Maybe I was changing the wrong thing.

**Comment by vitale232** [comment]
@elielia and @quanglddev,

I have a requirement that on the home page of our app, the header needs to be part of the scollable page. I was able to work around this issue by placing the `<header>` inside of the `content-area` container, then applying the following css to the header:

```css
.landing-header {
    background-color: #EBEBEB;
    margin-left: -24px;
    margin-top: -24px;
    margin-right: -24px;
}
```

The idea here is to allow the header element to expand outside of it's container. YMMV.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
