### ISSUE TITLE
Clarity v2 Stackblitz broken (possible dependency issue)

### ISSUE THREAD

**Issue by georgedimmitrov** [vmware/clarity#3847]
## Describe the bug

Stackblitz project using clarity v2 is broken due to some dependency issue. 

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2

#### Steps to reproduce the behavior:
See error `Error in /turbo_modules/intl@1.2.5/locale-data/complete.js (718:4)`
`IntlPolyfill is not defined`
![Screenshot 2019-09-24 at 10 35 13](https://user-images.githubusercontent.com/16158865/65491506-d5459780-deb7-11e9-85b3-f6d8203a31eb.jpg)

## Expected behavior

Working Stackblitz

## Versions

**App**

* Angular: 8.2.0
* Clarity: 2.1.0

**Device:**

* Type: MacBook
* OS: MacOS
* Browser Google Chrome
* Version 76

**Comment by sdurnov** [comment]
Commenting intl line in polyfills recovers it

**Comment by gnomeontherun** [comment]
This seems like some transient dependency issue that is causing it. The workaround is to remove it for now, usually not needed for our demos.

**Comment by georgedimmitrov** [comment]
Thanks @sdurnov! Commenting out the intl line in polyfills worked and made our stackblitz behave normally for now 👍 

I think the issue (probably a transitive dependency as mentioned above) should still be tracked/fixed, but it's good that we have a workaround for now :)

**Comment by gnomeontherun** [comment]
I just set the default templates to comment out `intl` package. Closing as resolved.

**Comment by kathygit** [comment]
How to fix an existing one on stackblitz, e.g. ?
https://stackblitz.com/edit/clarity-light-theme-v2-cwbulg?file=src%2Fapp%2Fapp.component.html

**Comment by gnomeontherun** [comment]
Just comment out the line from polyfills.ts like so, and then reload the preview browser (it doesn't seem to automatically refresh sometimes with catastrophic errors).

```
// import 'intl';  // Run `npm install --save intl`.
```
