### ISSUE TITLE
Nested <clr-dg-action-overflow> in datagrid

### ISSUE THREAD

**Issue by jacobbutton** [vmware/clarity#3848]
Provide similar functionality as nested dropdown menus

https://v2.clarity.design/dropdowns

in the datagrid single action menu.

https://v2.clarity.design/datagrid/single-action

**Comment by hippee-lee** [comment]
@jacobbutton - the row action component projects whatever it is given so you can put a dropdown in there if the app needs it e.g - https://stackblitz.com/edit/gh-datagrid-row-action-dropdown

I'm going to close this as a question.
