### ISSUE TITLE
Fix typo in chart color graphic

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#3849]
## There's a typo in the graphic under Color Palette >Chart Color Schemes
https://v2.clarity.design/color#chart
![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/7eb406a2-8623-4cd7-8cae-229f5016d2dd)

Please replace image with this one:![img_charting_example.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/234ca394-2bc5-496c-a6d7-6327fc57b9ba)

**Comment by gnomeontherun** [comment]
I liked it before myself.

**Comment by mathisscott** [comment]
This was pushed/merged into `master` and will be fixed when 3.0 documentation is generated and released.
