### ISSUE TITLE
[Website] Header from Alerts example overlays its title over website header title

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#3853]
## Describe the bug

On an Alerts documentation page, Header from the example somehow interferes with the website header and overlays its title over website header branding area.

![image](https://user-images.githubusercontent.com/32732457/65671831-a7e02180-e050-11e9-89cd-3abd045b62ad.png)

## How to reproduce

1.  Go to [https://v2.clarity.design/alerts](alerts documentation)
2.  Click on a hamburger menu in a mobile view (I use Galaxy S5 preset)
3.  See bold "Header" title overlays Clarity icon in the branding section of a website header

## Expected behavior

Content shouldn't mess up the website elements

## Versions

**Website**

* Angular: [8.0.0]

**Device:**

* Type: [PC, Galaxy S5 browser preset]
* OS: [Win 10]
* Browser [Opera (Chromium engine]
* Version [63.0.3368.94, Chrome engine v76]

**Comment by gnomeontherun** [comment]
Strange but the zindex seems different on this page.

**Comment by rkomiyama** [comment]
<img width="589" alt="Screen Shot 2019-10-04 at 2 03 13 PM" src="https://user-images.githubusercontent.com/347483/66229429-cb8a1400-e6af-11e9-9ec1-3021f71d5db6.png">

I have a fix. Will be putting up my first PR shortly.
