### ISSUE TITLE
hamburger menu position

### ISSUE THREAD

**Issue by hc-codersatlas** [vmware/clarity#3857]
## Summary

Ability to select the hamburger menu button position (and the side which the menu slides out from).

* What is the change?

variable to choose e.g. left or right

* Why should it go in Clarity?

Improve mobile experience

* Does this change impact existing behaviors? If so how?

No

* If this change introduces a new behavior, is this behavior accessible?

Yes

## Use case

Most modern mobile menus have shifted to the right as most users are right handed. And or otherwise it would be good for it to be configurable.

## Workarounds

N/A

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
