### ISSUE TITLE
Add a link for downloading the SVG icons

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#386]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Link to download the all of the SVG icons (and variants) 
[icons_vol1-2_svg.zip](https://github.com/vmware/clarity/files/733121/icons_vol1-2_svg.zip)

Link to read: Download all SVG icons (and variants)

### Actual behavior
no way exists for users to download the existing SVG icons

### Reproduction of behavior
![image](https://cloud.githubusercontent.com/assets/1858226/22124263/b9277b06-de54-11e6-8ef6-76d393dbeb7e.png)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@reddolan can we include link to all icons including vol2 now that we have vol2? cc @lil-kim

**Comment by reddolan** [comment]
That would be even better. I wasn't aware that vol 2 had been finalized and ready for use yet. I will circle back with @lil-kim

**Comment by reddolan** [comment]
I updated the zip file to include both vol1 and vol2 and variants.
