### ISSUE TITLE
Stepper Prevent Navigation for Async Tasks

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#3861]
## Summary

Currently the stepper uses Angular Forms to determine state and when to navigate to the next step panel. If an async task needs validation it can use async validators to pause before continuing. Currently however if you need to run an async task that needs to return a result and is not input validation the stepper will continue to the next step regardless if the async task has completed. 

## Use case

The stepper needs a API to disable the automatic navigation to the next step so a developer can trigger and async task and then programmatically move to the next step when completed.

## Examples

As a developer I want to on submit of the final step save the form data to an API and leave the last panel open showing a loading indicator. When the API is completed then be able to programmatically close or move to the next step.

A possible minimal API to accomplish this would be an option on the step button to disable the next functionality and expose a public next method on the stepper component.

```html
<clr-stepper-panel formGroupName="password">
  <clr-step-title>Password</clr-step-title>
  <clr-step-description>...</clr-step-description>
  <clr-step-content *clrIfExpanded>
    <p>...</p>
    <button clrStepButton="submit" clrDisableNext (click)="submit()" [clrLoading]="submitBtnState">submit</button>
  </clr-step-content>
</clr-stepper-panel>
```

```typescript
  @ViewChild(ClrStepper, { static: false }) clrStepper: ClrStepper;

  submit() {
    this.submitBtnState = ClrLoadingState.LOADING;
    
    setTimeout(() => {
      this.submitBtnState = ClrLoadingState.SUCCESS;
      this.clrStepper.navigateToNextPanel();
    }, 2000);
  }
```

## Workarounds

Currently you can work around this by hiding the built in stepper button and using a regular clarity button. With the hidden button you can trigger it to navigate to the next step.
https://stackblitz.com/edit/clarity-light-theme-v2-blmt1j?file=src%2Fapp%2Fapp.component.html

**Comment by nghiado** [comment]
+1

**Comment by the-santosh** [comment]
Thanks @coryrylan, your workaround worked for me.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
