### ISSUE TITLE
Holidays or non-availability notification icon

### ISSUE THREAD

**Issue by KakovkinPA** [vmware/clarity#3863]
## Summary

* What is the icon?
Airplane in the chat bubble.
* What does the requested icon signify?
Message that person has a holiday, vacation, availability limitation, etc.
* In which product(s) will this icon be used?
Any services with persons.
## Use case

It's a type of information icon which specifically shows that person is unavailable for work or communication because of some reason. You may use it nearby person's name just to notify users that the person is unavailable or use it with signpost component to show time period and information message in it right on the page. 

## Examples
![holidays_gray](https://user-images.githubusercontent.com/8651325/65935384-1e12c880-e443-11e9-987f-715251dcd45e.jpg)
[holidays_icon.zip](https://github.com/vmware/clarity/files/3674476/holidays_icon.zip)

## Alternatives

For such kind of notification people may use existing icons such as info-standard, user, calendar, bubble-exclamation, no-access or any of travel shapes. I believe these icons are more general and can be applied in a wide range of use when the plane-bubble icon can be used for specific notification.

**Comment by gnomeontherun** [comment]
@lil-kim
