### ISSUE TITLE
Performance Issues On Datagrid with expandable rows

### ISSUE THREAD

**Issue by tran2** [vmware/clarity#3864]
## Describe the bug

Compared to v1, v2 datagrid with expandable rows performance is worse.

## How to reproduce

v1: https://stackblitz.com/edit/clarity-light-theme-v1-0-xux9hr
v2: https://stackblitz.com/edit/clarity-light-theme-v2-ycwsj6

1.  Go to stackblitz link for v1 and v2
2. Click on the load button
3. See that for v1 it takes a few seconds but v2 takes way longer (30+ seconds)

## Expected behavior

v2 and v1 datagrid with expandable rows should have similar load time

## Versions

**App**

* Angular: 8
* Node: 10
* Clarity: 2.2.0

**Device:**

* Type: macbook
* OS: Mojave
* Browser Chrome
* Version 77

## Additional notes

According to Ivan 

> I located the issue to be with an undesired initial animation. Though it is "empty" animation it is still requesting animation frames.

**Comment by Jinnie** [comment]
I confirm I have a fix for this. Needs to be prioritized, so it can get tested and merged.

**Comment by tran2** [comment]
@Jinnie do you know when the fix would be merged?

**Comment by Jinnie** [comment]
Done! Thanks for pinging, @tran2 
Expect to have it in the next v2 release.
