### ISSUE TITLE
Clean up the Clarity plunker

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#387]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

The plunker used to reproduce bugs should be much simpler than what it is right now. It should not worry about routing, and contain pretty much these files:
- index.html
- config.js
- app/main.ts
- app/app.module.ts
- app/app.component.ts
- app/app.component.html
- app/app.component.css

### Actual behavior

Currently, it contains at least 5 dead files that are not used anywhere, and bloats all examples with multiple pages and routing. If an example really needs routing, it should be added manually. 99% of the bugs we receive are completely independent of of the routing context.

### Reproduction of behavior

Current plunker: https://plnkr.co/edit/8TwwdL
Typical example we receive or share: https://plnkr.co/edit/OuZ3w6AecL4VvSXRd9sd

**Comment by jeeyun** [comment]
@hippee-lee updated the plunkr (thank you)! closing.
