### ISSUE TITLE
Datagrid initial value for selection

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#388]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

According from plnkr below, the first row in datagrid should be visually selected when loading the page. And user can click other rows to change selection.

### Actual behavior
The first row was selected programmatically but not visually. The background of the first row doesn't change to blue at the beginning. Only by clicking other row then click first row will it be visually selected.

### Reproduction of behavior
https://plnkr.co/edit/KHQaOgoiJbZb96emGrae?p=preview

### Environment details

* **Angular version:** 2.4.3

* **Clarity version:** 0.8.2

* **OS and version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
I just submitted a PR that solves this, but instead of binding to the class (which is a bit uncomfortable for us to maintain, in case we need to change our DOM), we offer a cleaner `[clrDgSelected]` input on the row, even when the datagrid itself is not selectable.

So in your plunker,
```html
<clr-dg-row *clrDgItems="let user of users" 
    (click)="selected = user" 
    [class.datagrid-selected]="selected == user">
```
would now become
```html
<clr-dg-row *clrDgItems="let user of users" 
    (click)="selected = user" 
    [clrDgSelected]="selected == user">
```
