### ISSUE TITLE
Replace "gemini" with "hemione" or something else

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#3881]
## Summary

* What is the change?
Replace the tool used to run visual regression testing (gemini)

* Why should it go in Clarity?
Gemini is declared as deprecated in the [github repository](https://github.com/gemini-testing/gemini); this mean that most likely will not be longer maintained.
The request is to introduce a different tool (maybe [hermione](https://github.com/gemini-testing/hermione))

* Does this change impact existing behaviors? If so how?
No behaviour change but change in the CI system

* If this change introduces a new behavior, is this behavior accessible?
N/A

## Use case

N/A

## Examples

N/A

## Workarounds

N/A

**Comment by gnomeontherun** [comment]
We already have a plan to move to Applitools. We already have some tests moved over, but were giving it a longer trial run before moving the rest. This will happen soon as we can.
