### ISSUE TITLE
Wizard is not responsive

### ISSUE THREAD

**Issue by ElesGergo** [vmware/clarity#3899]
## Summary
It would be great if the wizard component is reaponsive. I feel like it is not save to use it without the responsiveness, since nowdays most users are using phones.

* What is the change?
Make the wizard component responsive.
* Why should it go in Clarity?
Because now it makes the component not useable for mobile devices.
* Does this change impact existing behaviors? If so how?
Just the styling and placements. I would change the stepnav position.
* If this change introduces a new behavior, is this behavior accessible?

## Use case
Applications does not break on phone if the wizard is responsive.
## Examples
 One the official website the problem is visible.

I can take the issue and make it responsive if nobody have time for it.

**Comment by gnomeontherun** [comment]
This is known, and one reason why we've provided the Stepper as a strong alternative for the Wizard. If responsiveness is important, I recommend using the Stepper instead.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
