### ISSUE TITLE
Datagrid appending rows to table on pagination

### ISSUE THREAD

**Issue by asachan2707** [vmware/clarity#3900]
## Describe the bug

Rows are appending on pagination instead of navigation

## How to reproduce
Kindly follow these links to reproduce
https://stackblitz.com/edit/angular-kqi9nq
https://angular-kqi9nq.stackblitz.io/

Click on pagination buttons to see the behavior

## Expected behavior

Pagination must paginate according to row count

## Versions

**App**

* Angular 8.3
* Node 10.16.0
* Clarity: 2.2.2

@gnomeontherun @mathisscott

**Comment by Dannybrown2710** [comment]
Facing same issue in 8.2.9 and clarity 2.2.0 
Cannot replicate in 8.0.1 and clarity 2.0.1

**Comment by gnomeontherun** [comment]
It appears the demo is not setup fully. Clarity depends on the `BrowserAnimationsModule` and it appears adding that is solving the problem.

What is confusing to me is that there are no errors like I might expect, but that does appear to be a fix for it. I'll leave this open for now to dive a little deeper into why.

**Comment by asachan2707** [comment]
Thanks, @gnomeontherun it works. I had missed the required dependency. 

But if it's required then it has to throw some error to intimate the user as you are also expecting.

**Comment by gnomeontherun** [comment]
I'm not sure why there is no error or exactly why it happens without the animations module, but I'm going to close this as resolved since that is the issue.
