### ISSUE TITLE
`clrDgActionOverflowOpenChange ` event does not trigger with Clarity version 2.2.2

### ISSUE THREAD

**Issue by kalpeshhpatel** [vmware/clarity#3904]
## Describe the bug

With Clarity version 2.2.2, clrDgActionOverflowOpenChange event is not triggering for datagrid action menu.

## How to reproduce

Here is the stackblitz demo:
https://stackblitz.com/edit/clarity-light-theme-v2-dmofdk

1.  Go to 'https://stackblitz.com/edit/clarity-light-theme-v2-dmofdk'
2.  Click on grid action menu
3. Observe the console. It prints nothing since the `onActionMenuChange` method is not getting called.

## Expected behavior

`onActionMenuChange` method should get called.

Note: This used with work with version 2.1.2. Demo: https://stackblitz.com/edit/clarity-light-theme-v2-hvf95t

**Comment by Jinnie** [comment]
The event does not get emitted, because the following if-condition is always `false`:
```
@Input('clrDgActionOverflowOpen')
  public set open(open: boolean) {
    if (!!open !== this.smartToggleService.open) {
      // prevents chocolate mess
      this.smartToggleService.open = !!open;
      this.openChange.emit(!!open);
    }
  }
```

**Comment by kalpeshhpatel** [comment]
Guys, can we please have a fix for this. It's blocking us to upgrade to the latest version of Clarity which has some accessibility fixes.

- Thanks

**Comment by bdryanovski** [comment]
We have the same issue in another place. I will try to push a fix later today.

**Comment by kalpeshhpatel** [comment]
Hi @bdryanovski , were you able to fix this issue?

Thanks

**Comment by hippee-lee** [comment]
The pull request for this fix is currently in review.

**Comment by vkpavan26** [comment]
Thanks @hippee-lee .Could you please let us know ETA for this fix we are waiting for this fix to upgrade Clarity.

**Comment by hippee-lee** [comment]
If you subscribe to this issue it will notify when the PR closes it.
