### ISSUE TITLE
Vertical scroll bar gets hidden under datagrid header on Edge

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#3917]
## Describe the bug

The vertical scrollbar gets hidden behind the datagrid header? When it's short (i.e. many rows in the grid) it gets hidden completely behind the grid header and you cannot see it at all.

## How to reproduce

https://v2.clarity.design/datagrid/fixed-height 

## Expected behavior

See the scrollbar :)

## Versions

* Angular: 7
* Node: 8
* Clarity: latest 1.x (I believe also on 2.x)

**Device:**

* Type: Dell Laptop
* OS: Windows
* Browser Edge
* Version latest

**Comment by rbirkgit** [comment]
This css style is set: `-ms-overflow-style: -ms-autohiding-scrollbar;` Removing it the scrollbar no longer auto-hides and behaves properly.

**Comment by bdryanovski** [comment]
With `-ms-overflow-style: -ms-autohiding-scrollbar;`
![Capture](https://user-images.githubusercontent.com/204564/67577521-7614b600-f6f5-11e9-96e7-a3842f84c079.PNG)

And without
![Capture2](https://user-images.githubusercontent.com/204564/67577556-84fb6880-f6f5-11e9-9ff9-82678f9aacc7.PNG)

I think that the first screenshot the correct behavior. You are scrolling only the content between the header and the footer and the scrollbar is clearly informing you what is the scroll area.

**Comment by rbirkgit** [comment]
In the first screenshot, part of the scrollbar is hiding under the header. I rather see the whole scrollbar :)  All other browsers also have the scrollbar like in the lower picture.

**Comment by bdryanovski** [comment]
How small is this Datagrid? 

Can you provide Stackblitz demo?

**Comment by rbirkgit** [comment]
Size doesn't matter. You can go to Clarity doc site (link in original post) and you see that the scroll bar hides behind the header. When you get more items in your grid, the scrollbar gets shorter. At some point it will be shorter than the header and you won't be able to see the header at all. 

All other browsers have it like the lower pic, which makes sense as you can no see the whole scrollbar and not just part of it.

**Comment by bdryanovski** [comment]
Can you provide a working demo? 

I can't reproduce this. Thanks.

**Comment by rbirkgit** [comment]
https://v2.clarity.design/datagrid/fixed-height

Just tested with Edge and scrollbar hides behind header.

**Comment by gnomeontherun** [comment]
I'm quite certain this is related to old Edge/IE not handling sticky headers well. There are some versions of Edge that have a bug related to this.

**Comment by hippee-lee** [comment]
We can remove it but, that means that scrolling datagrids on edge will always have the vertical scrollbar. This will affect the horizontal width of the datagrid. When the datagrid fills its container horizontally and it has vertical scrolling there will always be horizontal scrolling because the scrollbar width gets added to the overall width of the columns. and the table content overflows horizontally.

**Comment by rbirkgit** [comment]
Not sure how it's different from chrome and firefox which always show the scrollbar.

**Comment by hippee-lee** [comment]
Actually, now that I'm checking the code on my Windows vm you are right. Edge is fine with it removed. However, this breaksdatagrid layout in IE11 pretty bad which is probably why I had it in there. I don't see an obvious way to address the reported issue without breaking scrolling datagrids in IE11. 
<img width="1031" alt="Screen Shot 2019-10-25 at 10 18 45 AM" src="https://user-images.githubusercontent.com/433692/67590869-e2e97980-f710-11e9-8a94-f57910570470.png">

**Comment by rbirkgit** [comment]
This is odd. I just tested removing the flag on my IE11 (Win10) and it looks and behaves good.

**Comment by hippee-lee** [comment]
How was it removed? Was the css rebuilt from sources and the page reloaded?

**Comment by gnomeontherun** [comment]
The issue appears to be resolved from the comments, so I'm going to mark this as resolved. If the issue returns, we can reopen and make sure its an issue with a recent version of Clarity.
