### ISSUE TITLE
Stepper - Need to access stepper state from template

### ISSUE THREAD

**Issue by nghiado** [vmware/clarity#3923]
## Summary

The step title section has three states: completed, active, to-do but we can't access them in template
* What is the change?
Expose stepper state so we can use it to display extra info based on stepper state.

* Does this change impact existing behaviors? If so how?
No

## Use case
Display some values configured inside each step on step completed

_Provide some specific details about how this change would improve your application and use case._

## Examples

<img width="1092" alt="Screen Shot 2019-10-17 at 2 10 28 PM" src="https://user-images.githubusercontent.com/1259031/67039895-f2047200-f0e7-11e9-9069-0ea51cfb3375.png">
<img width="1107" alt="Screen Shot 2019-10-17 at 2 10 40 PM" src="https://user-images.githubusercontent.com/1259031/67039896-f2047200-f0e7-11e9-9436-31b71ac33221.png">

**Comment by gnomeontherun** [comment]
@nghiado Could you elaborate a bit further on exactly what you need to do here? The states of a panel is linked to the form validation as well.

**Comment by nghiado** [comment]
As shown in the screenshots, we need to show domains (entered by user in Enter Domains step) only when that step is completed (user clicked on Next button in Enter Domains step and moved to the next step Choose Verification Method).
The state show as blue - completed in step 1 but from our component, we can’t access to step internal state.

**Comment by nghiado** [comment]
We can’t use form state since it could be valid but user hasn’t clicked on Next to complete the step yet

**Comment by plaisted** [comment]
We had a similar use case and just added a click handler to the next button like:
```html
<button clrStepButton="next" (click)="loadNextStep()">next</button>
```
It gets triggered regardless of if the stepper moves forward (eg. form validation prevents move to next step) so need to manually make sure state is valid but otherwise seems to work well.

**Comment by gnomeontherun** [comment]
There isn't an internal state to access with the Stepper, you have to manipulate the form's state to allow or disallow the step to be completed. For example, if a field is marked as required it will need to have a value before moving forward. I'm still not fully confident the use case or details are outlined here though. 

To help us clean up our backlog, we are going to close this knowing that the stepper state is simply a reflection of the pristine and validity form state.
