### ISSUE TITLE
Navigation targets (links) are centered in side panel with responsive design

### ISSUE THREAD

**Issue by thojo** [vmware/clarity#3927]
## Describe the bug

When using the responsive navigation the navigation links in the side panel are displayed with centered text instead of left aligned text,

## How to reproduce

Unfortunately, the StackBlitz Templates do not work for me in any browser. But you can reproduce it on the Clarity website.

1. Got to https://clarity.design/
2. Shrink the window to mobile width
3. Open side panel from hamburger menu
4. See navigation items with centered text

## Expected behavior

Text of navigation items in side panel of responsive navigation should be left aligned.

## Versions

**App**

* Clarity: >= 2.1.0

**Device:**

* mobile device or small desktop window
* all browsers

## Additional notes

For me it looks like a regression by #3458 ([see changed .nav-link styles](https://github.com/vmware/clarity/commit/389836086f818374639a1d4bea67c85f8da43e7a#diff-5798c40805bf1fc9d2e03b94980dea59R119)).

**Is this an intended change?**

**Comment by gnomeontherun** [comment]
We have moved away from the sidenav and rebuilt our website, so this is no longer visible. If you are impacted by this, some custom CSS could align the menu items. 

In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
