### ISSUE TITLE
Dropdown mistakenly reclaims focus when clrCloseMenuOnItemClick is set to false

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#3928]
### How to reproduce
1. See the last example on clarity documentation > dropdowns,
    where clrCloseMenuOnItemClick is set to false.
    Additionally an input field has been added next to the dropdown example
2. When the user opens the dropdown, eg selects one of the items, 
3. then clicks on the input element, 

**See error:** shortly the input elements gains focus but instantly it is reclaimed by the dropdown menu.
The dropdown mistakenly reclaims focus when clrCloseMenuOnItemClick is set to false.

![2019-10-21_061_cut_1_anim](https://user-images.githubusercontent.com/311619/67206742-8e918180-f412-11e9-9a11-44e729f99003.gif)

## Expected behavior
focus is hold by the element the user clicks on - in this case the input field.

## Versions

**App**
* Clarity: 2.2.3, v3

**Device:**
* Type: Notebook
* OS: Windows 10
* Browser Chrome 77

**Comment by d-m-s** [comment]
@gnomeontherun Hi Jeremy, are there any news on this issue? thx upfront!

**Comment by mathisscott** [comment]
This is the expected interaction/behavior. Clicking away from the dropdown closes the dropdown and returns focus to the element that opened the dropdown.

This behavior mirrors the behavior of native browser elements as well. See the video below. Opening the select options and clicking away does not focus the text input. It closes the select options menu. A second click is required to focus the text input.

https://user-images.githubusercontent.com/2728359/153304815-29fe4a6a-fe57-44d2-8143-23fc47961ebe.mov
