### ISSUE TITLE
Floating Action Button component

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#393]
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
- Similar to Material's floating action button 
> "Clarity has no button styling ideal for icon buttons in toolbars or floating action buttons" - requested from @gssjr on #137 

### References
- [Floating Action Button - Material Design](https://material.io/guidelines/components/buttons-floating-action-button.html)

**Comment by mathisscott** [comment]
This isn't something we will be adding to Clarity in the near or long term. If there is a strong use case for this component besides "Material has it", please comment below.

**Comment by reddolan** [comment]
thanks for the update @mathisscott. I had created this issue from an older one where it sounded like @gssjr wanted it.

**Comment by mhusari** [comment]
I would say that "FAB" is a commonly used piece of UI/UX that multitudes of users are already familiar with. Most of Googles products use this approach and those apps have a wide spread userbase.

**Comment by ChitMeng-VMware** [comment]
We have another use case where we want to have a floating action where customers can choose to click to get information about help sessions that are available to them during the work process. It is not a primary action like what Material Design has stated. It is more like Intercom where customers can choose to click to get help.

**Comment by gnomeontherun** [comment]
@ChitMeng-VMware Can you please open a new issue with a feature proposal with more details? Old issues get stale and are better to start fresh with current details and information. As we've said so far, this isn't likely to be added without a strong case, so help us out with details and use cases, and why it is better than other patterns or options.
