### ISSUE TITLE
Separators in button group overflow menu

### ISSUE THREAD

**Issue by jrharshath** [vmware/clarity#3930]
## Summary

Button group overflow menus should have the ability to have separators just like select dropdown components shown here: https://clarity.design/documentation/dropdowns

* It will enable some use cases where we want to logically section off the overflow menu with related actions grouped together
* It should be in Clarity because it makes the framework richer in terms of functionality
* It won't affect any existing UIs or code
* It can be made accessible in the same way that it's be done for the select component

## Use case

![image](https://user-images.githubusercontent.com/85807/67248959-d7e5cf00-f41a-11e9-8403-b19a48504dd9.png)

## Workarounds

The workaround is to not have a separator at all. It is not ideal, but TBH not a deal-breaker. This feature is the mayor of "just-nice-to-have" territory.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
