### ISSUE TITLE
Partial imports for clr/angular pull in the whole lib

### ISSUE THREAD

**Issue by amalitsky** [vmware/clarity#3931]
## Bug/feature request

`import { ClrIconModule } from '@clr/angular';` pulls the whole `@clr/angular` module into the app.

Basically it behaves the same way as whole library import via `import { ClarityModule } from '@clr/angular';`. No _tree shaking_ is being observed. 

Whole `@clr/angular` module weights about 1.2Mb (or 100Kb gzipped) hence it is very significant price to pay for a few (or even one) simple elements such as icon, button etc.

## How to reproduce

1. Use the regular seed app with `import { ClarityModule } from '@clr/angular';`, run webpack bundle analyzer. Write down the size of the bundled `@clr/angular` module.
2. replace import with `import { ClrIconModule } from '@clr/angular';` and re-run webpack bundle analyzer. Compare the size of bundled `@clr/angular` module with the one captured on the step 1.
3. Expected result: module size would shrink significantly. Actual result: no change in the module size.

Sandbox (not very helpful though): https://stackblitz.com/edit/clarity-light-theme-v2-ugaumx?file=src/app/app.module.ts

Screenshot of _@clr/angular_ module with only `ClrIconModule` module being imported:
![clarity-build-clr-icon-only](https://user-images.githubusercontent.com/1457274/67255272-15a42100-f436-11e9-9d09-23e0aaba3693.png)

## Versions

**App**

* Clarity: 2.2.0
* Angular: 8.1.1
* Node: 10.16.3

## Additional comments
Any help (aka workarounds) is very much appreciated. Also if this is relatively easy fix, ready to contribute (but would need some guidance).

**Comment by gnomeontherun** [comment]
Can you please provide details of exactly what tool you used to build and run the analysis? There are several tools and it isn't clear what you're using here.

**Comment by gnomeontherun** [comment]
I can't duplicate this on a simple test.

```
ng new bundle-test
cd bundle-test
ng add @clr/angular
ng build --prod --source-map=true
source-map-explorer dist/bundle-test/main.es5[HASH].js
```

This tree shakes as expected.

The question I have is that perhaps what is happening is you are seeing the icons here? Have you tried using a different module and `source-map-explorer` to look at your final bundles?

**Comment by amalitsky** [comment]
Lemme try same on the seed app itself, I'll get back to you. Screenshot attached was taken from the different app. Tool used to produce the report is https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by amalitsky** [comment]
Can confirm that tree shaking appears to be working for the seed app. For `ng build --prod` I am getting:
```
chunk {1} main.aa2b1bbaba554bff3e3c.js (main) 733 kB [initial] [rendered]
```
when `crl-icon` is the only component used _somewhere in html_ and
```
chunk {1} main.66fed0304ad7545f250b.js (main) 900 kB [initial] [rendered]
```
when `clr-data-grid` is also used.

Bundle size for the later is bigger and it makes sense. In **both** cases _@clr/angular_ lib is imported as `import { ClarityModule } from '@clr/angular'`.

Hence I assume that issue originally reported is being caused/affected by our build process which is _webpack_ only, we are not using _angular cli_ (and optimizations it provides).

Do you guys know if these optimizations are avail as webpack plugin? Will look for those.

Also will try to create similar app with ejected angular cli setup or wo it at all (from scratch). My assumption is that regular tree shaking which works for other TS/JS libraries based on things being imported is not working for _@clr/angular_. If that's the case is it smth you will be concerned about?

**Comment by gnomeontherun** [comment]
We have been fixing the bundling and tree shaking of icons in our Clarity Core effort, but unfortunately it isn't backport-able. The issue of how to get tree shaking with Webpack and Angular (without the CLI) is not something we can help with though as it is not specific to Clarity. Your options are to import the specific modules you need from Clarity (emulating tree shaking yourself by only importing ClrDatagridModule for example) or by implementing tree shaking (using rollup most likely) in your build tooling.

Closing this as it isn't related to Clarity.
