### ISSUE TITLE
clrDroppable does not work with fullTemplateTypeCheck

### ISSUE THREAD

**Issue by derkoe** [vmware/clarity#3932]
## Describe the bug

When using `clrDroppable` in an Angular application with `"fullTemplateTypeCheck"` activated in `"angularCompilerOptions"` then the application does not compile with:

    Directive ClrDroppable, Property 'isDraggableMatch' is private and only accessible within class 'ClrDroppable<T>'

## How to reproduce

- Create a new Angular app: `ng new my-app` (current Angular CLI sets `"fullTemplateTypeCheck": true` in `angularCompilerOptions` in `tsconfig.json`).
- Add Clarity `ng add @clr/angular`
- Add the following to `app.component.html`:
  ```
  <div clrDraggable>Drag this</div>
  <div clrDroppable>Drop area</div>
  ```
-  Run `ng build --prod`

## Expected behavior

The application should build with `"fullTemplateTypeCheck": true`.

## Versions

**App**

* Angular: 8.1.3
* Node: v10.16.3
* Clarity: 2.3.0

**Device:**

* Type: [e.g. MacBook]
* OS: Win10
* Browser: all
* Version: all

## Additional notes

Already created a fix in https://github.com/porscheinformatik/clarity/tree/fix/full-template-type-check

**Comment by gnomeontherun** [comment]
This was closed by #3933.
