### ISSUE TITLE
[ICON] file-share should be folder-share

### ISSUE THREAD

**Issue by artemisclyde** [vmware/clarity#3935]
I found the icons for _file_, _folder_ and _file-share_ to be slightly misleading.

_file-share_ depicts a _folder_ icon with a sharing symbol. I think it should either be renamed from _file-share_ to _folder-share_ (opening the opportunity for creating a real sharing icon for files) or the icon should be changed.

_(Image upload of the icons here on Github isn't working as I'm creating this)_

**Comment by lil-kim** [comment]
I created a new icon in https://github.com/vmware/clarity/issues/4107 to address this issue.
I named it "file_share2" because we already have one called "file_share" which is a **folder** with a share symbol. Ideally, it should be changed to "folder_share" but that would cause a breaking change.
