### ISSUE TITLE
clr-dropdown-menu not accepting spaces

### ISSUE THREAD

**Issue by rajukundu** [vmware/clarity#3940]
## Describe the bug
We have a text input dropdown menu, expecting user to enter free text with spaces(e.g. "free text") and on click of Save the dropdown should get closed. The dropdown gets closed on pressing spacebar and ignore spaces. hence user not able to enter text with spaces.

## How to reproduce
Sample code -
<clr-dropdown [clrCloseMenuOnItemClick]="false">
    <span clrDropdownTrigger>
      <clr-tooltip>
        <clr-tooltip-content clrPosition="bottom-right" clrSize="sm" *clrIfOpen>
          <span class="tooltip-wrap">Test</span>
        </clr-tooltip-content>
        <button type="button" clrTooltipTrigger #plainSelectorInput class="value-select wrap-value-text"
          [class.pointer-events-none]="isDisabled" name="value-dropdown-link">
          Test
        </button>
      </clr-tooltip>
    </span>

  <clr-dropdown-menu *clrIfOpen>
    <div>
    <div>
      <input class="clr-input" type="text" autocomplete="off" class="value-selector-input plaintext-value-input" [(ngModel)]="valueText" name="value-selector-texbox" />
    </div>
    <div>
      <button name="plain-text-value-label" class="plain-text-value-label" type="button" clrDropdownItem >Save</button>
    </div>
    </div>
  </clr-dropdown-menu>
</clr-dropdown>

1.  Run the code and click on the Test button.
2. Click inside text input field and try to enter text with spaces.

## Expected behavior

User should be able to enter text with spaces.

## Versions

**App**

* Angular: 8.1.2
* Clarity: 2.1.1

**Device:**

* Type: MacBook
* OS: macOS Mojave
* Browser: chrome
* Version: 77.0.3865.120

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Hello, while I see the intention of having an input here, it is not a pattern we will support in the dropdown menu. That is really the behavior of the #248 or #3813 both of which are coming soon. It is important that components are not conflated with behaviors that are semantically different, especially with regards to accessibility, consistency, and general usability.

Please look for one of the other patterns to utilize and I'm going to close this as something we won't support.
