### ISSUE TITLE
clr-dropdown-menu is cut when opened from the bottom of the window

### ISSUE THREAD

**Issue by GuyNitzan** [vmware/clarity#3945]
I'm using clr-dropdown-menu to display some optional operations on an object.
The dropdown is always opened to the bottom (unless I declare otherwise in the HTML), So if the object is too low in the window, the dropdown list is cut and the user can't see the bottom part of it.
Isn't there a support for this issue by Clarity? Or should I implement a function that returns the correct [clrPosition] attribute relative to the window position?

**Comment by bdryanovski** [comment]
We know for this issue and we gonna address it with the new Smart Popover.

**Comment by hippee-lee** [comment]
Thanks for reporting this. I'm going to close it in favor of https://github.com/vmware/clarity/issues/1262

When #1262 is resolved it will take care of this.
