### ISSUE TITLE
Alert text not selectable inside modal

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#3946]
![image](https://user-images.githubusercontent.com/1386622/67677604-23552b80-f98d-11e9-8717-e5d54d39b798.png)

Reproduction:
https://stackblitz.com/edit/angular-gtrjj9

Probably related to:
https://github.com/vmware/clarity/pull/3821

Workaround:
Adding `tabindex=1` to `clr-alert` will make it selectable.

**Comment by gnomeontherun** [comment]
I don't know if this is still an issue, but the provided Stackblitz is not functioning. If it is, please provide an updated demo and we can review otherwise I'm going to close this and it has a workaround as well.
