### ISSUE TITLE
Selection List

### ISSUE THREAD

**Issue by Karankang007** [vmware/clarity#3950]
```
[ ] bug
[x] feature request
[ ] enhancement
```

Ability to select a single an item or multiple items from a list of items. 
Clarity already has a list component, but it does not support selection capabilities natively.

Example:
https://material.angular.io/components/list/overview#selection-lists

**Comment by gnomeontherun** [comment]
How does this pattern differ from a list of checkboxes? What is the exact use case here that we're interested in addressing?

**Comment by gnomeontherun** [comment]
Closing as stale, and as a pattern that seems essentially the same as a list of checkboxes.
