### ISSUE TITLE
Core Component: Modal

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#3953]
# Core Modal
When implimenting the modal it may be a good time to check to see if the modal can internally use the native dialog element. It provides some needed functionality as well as a11y. There is a supported polyfill for the dialog API.

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
- https://github.com/GoogleChrome/dialog-polyfill
- https://gist.github.com/samthor/babe9fad4a65625b301ba482dad284d1

## API Proposal (Angular Example Usage)

```html
<cds-modal>
  Content...
</cds-modal>

<cds-modal (closedChange)="closed = $event.detail" size="lg">
  <cds-modal-header>I have a nice title</cds-modal-header>
  <cds-modal-content>
    <p>But not much to say...</p>
  </cds-modal-content>
  <cds-modal-actions>
    <div cds-layout="horizontal gap:sm align:right">
      <cds-button (click)="modal.close()">Cancel</cds-button>
      <cds-button (click)="modal.save()">Save</cds-button>
    </div>
  </cds-modal-actions>
</cds-modal>
```

### Properties
`size` - Adjust the modal size styles using tshirt style size options
`closable` - use false to disable the close button and background click, defaults to true

### Events
`closedChange` - event for when modal's close button is clicked or the ESC key is pressed

### Slots
`cds-modal-header` - header content
`cds-modal-header-actions` - header action content
`cds-modal-content` - body content
`cds-modal-actions` - actions content

**Comment by mathisscott** [comment]
Tech specs are in progress. Notes from early discussions...

The modal will need the following utilities...

1) focusTrap for a11y
2) focusReturn for a11y
3) scrollKiller for a11y
4) backdrop (which may or may not be the scrollKiller as well)
