### ISSUE TITLE
Warning icon color not accessible on light backgrounds

### ISSUE THREAD

**Issue by lpetkov** [vmware/clarity#3959]
Hi,

The Warning icon's yellow color is not accessible on light backgrounds (screenshot attached), and might be especially hard to see at 16x16

![image](https://user-images.githubusercontent.com/31132490/67933825-48d17780-fbcf-11e9-967a-702198185fe6.png)

Please advise and recommend a different shade of yellow to use. Also, should the exclamation point remain transparent, or should we color it in some dark color?

Cheers,
Lachezar | VMware vSAN

**Comment by mathisscott** [comment]
@lpetkov 
What version of Clarity are you using?  As of 2.2.1, the yellow is `hsl(38, 100%, 38%)`

**Comment by lpetkov** [comment]
Thank you, hsl(38, 100%, 38%) looks a lot better! We'll update our version of Clarity.
