### ISSUE TITLE
Form component for static text

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#3964]
## Summary

The old forms had a static input option to show plain text in the flow of a form. This is basically allowing for text in place of a text input but retaining formatting. The main question is what is the styling of the text in this case.

## Use case

This is used in cases where content may not be editable but still show up in a form and to match the layout.

## Examples

https://vmware.github.io/clarity/documentation/v0.11/forms

## Workarounds

You can put a span inside of the CSS structure manually to get the layout, but it is not supported with Angular components.

```
<div class="clr-form-control">
  <label class="clr-control-label">Label</label>
  <div class="clr-control-container">
    <span>My static text</span>
  </div>
</div>
```

**Comment by colinreedmiller** [comment]
Styling exists in this form elements file which matches the styling of the current forms:
https://www.figma.com/file/W2gCMtLUgR2BicLus4anti/forms?node-id=0%3A1

**Comment by gnomeontherun** [comment]
Need to clarify which example is the correct design for static text.

**Comment by colinreedmiller** [comment]
@gnomeontherun I will excerpt the specific design from the existing spec and add it to this issue as the static text design spec.

**Comment by bdryanovski** [comment]
@colinreedmiller

**Comment by rbirkgit** [comment]
The workaround above is not enough. You also need to add this style:

```
.clr-span {
  color: #000;
  font-size: .541667rem;
}
```

Then add the style to the span.

**Comment by rbirkgit** [comment]
Hopefully some day this could be added to clarity. We keep needing this everywhere.

**Comment by gnomeontherun** [comment]
You can also use a readonly input to display this. However, with Clarity Core this is possible and now documented through #5572. Closing as resolved.
