### ISSUE TITLE
Angular Modal Component close button callback

### ISSUE THREAD

**Issue by akcasoy** [vmware/clarity#3968]
I have been trying to use Clarity Components for my Angular app. The Angular modal component <clr-modal> has a **close button in its modal-header**, which we can also turn off with [clrModalClosable] (input). But I **could not see a way of defining a callback function for this button**, so I can run some logic when this button is pressed.

It seems strange because for the normal modal-footer buttons like ok or cancel, you can just use the angular click event, but since the close button in header is defined in the component itself, I could not find a way of getting informed when the modal is closed by this button.

I think the input "clrModalClosable" should be named "clrModalClose" and it should also be a 2 way binding like clrModalOpen which also informs user when this button is clicked.

**Comment by gnomeontherun** [comment]
There is a callback that you can hook into with the two way binding Angular provides. This is true of any two way binding in Angular, not just what you see in Clarity.

```
<clr-modal [clrModalOpen]="openModal" (clrModalOpenChange)="onChange($event)">
    <h3 class="modal-title">I have a nice title</h3>
    <div class="modal-body">
        <p>But not much to say...</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-outline" (click)="basic = false">Cancel</button>
        <button type="button" class="btn btn-primary" (click)="basic = false">Ok</button>
    </div>
</clr-modal>
```

Then implement an `onChange(event) {}` method in your controller, and you'll get the state changes to do any additional work.

Closing this as a question with a solution.
