### ISSUE TITLE
Make the header responsive

### ISSUE THREAD

**Issue by ElesGergo** [vmware/clarity#3969]
## Summary
It would be great if  the header component would be responsive.

* What is the change?
Header component to be be responzive, work with the usual hamburger menu on the right side.
* Why should it go in Clarity?
Would improve the overall developer experiece
* Does this change impact existing behaviors? If so how?
I dont think so.
* If this change introduces a new behavior, is this behavior accessible?
-
## Use case
Developers would not need to implement this fuctionality.
## Examples
I have implemented it but it seems that with the existing header component dropdown opens slowly on mobile device.
## Workarounds
Custom css/scss.

**Comment by gnomeontherun** [comment]
Please review our https://v2.clarity.design/navigation page for how to use the responsive navigation Angular components. That should address your use case and not require custom workarounds.

Closing as already existing.
