### ISSUE TITLE
Provide keyboard navigation for Clarity stack views and accordions

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#3973]
## Summary

User must be able to navigate and collapse / expand sections in the Clarity Stack View and accordion only with keyboard like it is pointed out 
here https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

* What is the change?
Provide a keyboard navigation matching WASG recommendations for accordion
* Why should it go in Clarity?
It is a basic requirement for accessibility compliance - https://www.w3.org/TR/WCAG20/#keyboard-operation
* Does this change impact existing behaviors? If so how?
No
* If this change introduces a new behavior, is this behavior accessible?
Yes

## Use case

As a user of the Starch View component I want to be able to navigate through it using only keyboard

## Examples
 https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html

## Workarounds
No

**Comment by gnomeontherun** [comment]
The accordion and stack view are both keyboard navigable. Can you provide an isolated demo of where this isn't working on latest v2?
