### ISSUE TITLE
Stack-view toolbar buttons vs Datagrid toolbar buttons

### ISSUE THREAD

**Issue by ttsvetko** [vmware/clarity#3977]
We are using Clarity as a main component library in our product.  Recently, some of our clients are asking us why the stack-view toolbar buttons are positioned on the right side and the datagrid buttons are on the left side. Both of them are toolbars from user point of view. 
Is there any reason for placing in different position both toolbar's buttons?

**Comment by gnomeontherun** [comment]
The StackView has one button (EDIT) and it does go on the right. We don't really have any other use cases defined for toolbars with the Stack View. To answer the question, the Stack View pattern was designed to replace some other existing component in some products and this was the design that looked best.

I don't disagree that these things should be considered and perhaps realigned to be consistent, but it would likely be tackled as part of a larger overhaul of several aspects of the Stack View.

Closing as the question was answered.
