### ISSUE TITLE
Add support for select box inside the header

### ISSUE THREAD

**Issue by aokremer** [vmware/clarity#398]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
The header should be able to contain a select box with reasonable style

### Actual behavior
One can add a select box to the header but since there is no style support, it doesn't look good

### Reproduction of behavior
https://plnkr.co/edit/uBlMHNzNQ4Kbz1cbxd39?p=preview

### Environment details

* **Angular version:** 2.2.3

* **Clarity version:** 0.8.3

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@yenmade @reddolan how would the select box look in the header, this requires some input from the ClarityUX team.

**Comment by reddolan** [comment]
@aokremer can you help us understand the use case(s) for having a basic select box in the header?

Currently, Clarity header navigation allows having icons and username on the right side of the the header with dropdowns. Will either of those experiences meet your need?

**Comment by reddolan** [comment]
@aokremer at this time, we won't be supporting any new elements to the Header navigation like the `<select>`
