### ISSUE TITLE
Move the close button to the beginning of the Clarity modal/wizard  DOM

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#3982]
## Summary

Move the close button to the beginning of the Clarity modal/wizard  DOM so it will be the first element focused and read by the screen readers when user enters in the content.
Otherwise keyboard-only users and screen reader users may be disoriented when elements receive order in an unpredictable order.

* What is the change?
Move the close button to the beginning of the Clarity modal/wizard  DOM
* Why should it go in Clarity?
To provide better accessibility
* Does this change impact existing behaviors? If so how?
No
* If this change introduces a new behavior, is this behavior accessible?
Yes

## Use case

As a keyboard/ screen reader user I want to be able to press the close button without going through all modal/wizard controls

## Examples
https://getbootstrap.com/docs/4.3/components/modal/

## Workarounds

NA

**Comment by gnomeontherun** [comment]
We intentionally put the focus on the modal title, so the user gets to hear immediately the title and not a message like 'Close'. 

This would go against that improvement and I'm going to close this as something we won't change.
