### ISSUE TITLE
Provide ARIA attributes for the expanded/collapsed sections of the Clarity Stack View

### ISSUE THREAD

**Issue by bashibozuk** [vmware/clarity#3986]
## Summary

Clarity Stack View does not provide information about collapsed/expanded state of its panels

* What is the change?
Add aria labels to indicate the state of the panels
* Why should it go in Clarity?
Accessibility improvement
* Does this change impact existing behaviors? If so how?
No
* If this change introduces a new behavior, is this behavior accessible?
Yes

## Use case

As a screen reader user I want to be notified when a panel in Clarity Stack View expands/collapses

## Examples

N/A
## Workarounds

N/A

**Comment by gnomeontherun** [comment]
The Angular component for Stack View does this as far back as 0.12 releases, see https://github.com/vmware/clarity/commit/e99c1d5730a43007ba8bfa6fa132edd1eb3f19ee. If you are using the HTML/CSS version, you would have to implement that yourself. Do you have a reproduction of this issue currently?

**Comment by bashibozuk** [comment]
You can close this one, sorry for the noise.
