### ISSUE TITLE
Upgrade to BS4 Alpha 6 Grids + Utility Classes

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#399]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

Upgrade BS4 from alpha 5 to 6

alpha 6 changes some grid + utility classes so it may be a breaking change.

https://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/

**Comment by manju-reddys** [comment]
Where is this on your priority list?

**Comment by adityarb88** [comment]
Hi @manju-reddys: This is on our priority list but we have to analyze how big a breaking change this is. Also, since this is a breaking change this change can only go in 0.9.0 or 0.10.0. We don't have any concrete dates for 0.9.0 yet. But this shouldn't affect anything major apart from the Grid class names and a few other utility classes. The only major component that we use is Grids and that is fully functional right now. Could you please let us know which feature are you looking for from Alpha 6? cc: @jaffoneh

**Comment by manju-reddys** [comment]
Hi @adityarb88, 

I'm particularly interested in [equal width column](http://v4-alpha.getbootstrap.com/layout/grid/#equal-width). I'm working portlet layout where user can drag and drop the widget (a portlet). When they drop the widget on the existing row it will adjust the width (just css) and if one of the widget width changed (javascript => resize) then the rest of the columns get adjusted automatically (again css). I can't use col-* because V4-RC6 ``col`` will take care of wrapping when the columns overflown into new row.

For now I don't have much dependency on Clarity but when I use this [portlet layout](https://github.com/manju-reddys/Portlet-Layout) module in the main application it may conflict.

I hope I have given enough info!

**Comment by adityarb88** [comment]
Hi @manju-reddys: Although the class names have changed in Alpha 6, I believe we do provide that functionality:

![image](https://cloud.githubusercontent.com/assets/1426805/22696645/a87eaf5a-ed03-11e6-93fb-a090acda4c01.png)

Is this what you are looking for?

**Comment by manju-reddys** [comment]
Hi @adityarb88, There is difference between `.col-<breakpoint>` and just `.col'. The `.col-<breakpoint>` stacks up when the size reaches the break point but the `.col` won't.

**Comment by adityarb88** [comment]
@manju-reddys: But you could the lowest breakpoint right? `.col-xs`?

**Comment by manju-reddys** [comment]
Hi @adityarb88, Better I will showcase when I finished my project. `.col-xs` will not work in my case.

**Comment by manju-reddys** [comment]
Hi @adityarb88, No. here is the reason:

When user drag and drop the widget first time, it will have default width and one can drop upto 6 widgets in one row (we enforce the restriction). In default mode all `column`'s will take up equal space. If user resize one or more of the widget the remaining widgets will adjust the size automatically (CSS controlled). If any of the widget or sum of the widgets size greater than the container size then it should stack up (like using `col-xs-12 col-sm-3`). If we use the `col-xs-<size>`, it always allow only one column per row which is undesirable in my case.

**Comment by manju-reddys** [comment]
which release it would go in? I have strong requirements to upgrade to BS 6.

**Comment by mathisscott** [comment]
@manju-reddys : What do you mean when you say "strong requirements"? It will help us to prioritize this issue if we have a better understanding of your use case.

**Comment by mathisscott** [comment]
Closing for now. Will open a new issue when we decide to upgrade to the latest BS4 version.

**Comment by manju-reddys** [comment]
I would recommend to remove bootstrap dependency that helps who is keeping up with bootstrap version will not consider to discontinue using clarity (like me).... For me writing components are lot easy over customizing css (which also need to document not easy job).... Keep up the good work, will consider the clarity in the future work :)
