### ISSUE TITLE
warning status for form inputs

### ISSUE THREAD

**Issue by royling** [vmware/clarity#3990]
## Summary

Currently there're only valid and invalid status (error), do you think it makes sense to add  the support for warning status?

* What is the change?
At least allowing to customize the icon in the containers?

* Why should it go in Clarity?
It can make those input containers customizable and more flexible.

* Does this change impact existing behaviors? If so how?
May not, but possibly I did not see it.

* If this change introduces a new behavior, is this behavior accessible?

## Use case

Allow to customize the status icon in input containers.

## Examples

did not search it...

## Workarounds

Tried to customize the color styles of border, error text, etc. But the icon cannot be changed.

**Comment by gnomeontherun** [comment]
There is really two requests here:

1) Support a warning state (though there is no Angular form equivalent)
2) Support custom icons in place of error icon

Both sound interesting but I'd like to know more about the use cases. I'm going to ping @colinreedmiller so he sees this and can take this into account with some form changes we're investigating.

**Comment by royling** [comment]
The custom icon request is like a mean/workaround so that we could get a warning state (with css change). Now it's not possible to insert an icon in the place of error icon. 🙄

**Comment by colinreedmiller** [comment]
Warning seems like an odd state for an input, but there may be cases where this makes sense.  We would need some use cases to evaluate this. I can't think of any reason to prevent the user substituting the icon, but use cases here would also be necessary to fully evaluate it.

**Comment by royling** [comment]
My use case is:
In a form, there're several different controls, which may be related. The values filled/selected may be not recommended or causing potential issues, we want to __highlight__ this in the form specifically __with warning text__. An error icon looks too critical, instead a warning icon is much better...

**Comment by colinreedmiller** [comment]
Sounds like a sensible reason to consider this. Will the user require additional information about the returned warning? Is changing the icon sufficient or will some messaging be required? How will the user understand he reasons for receiving the warning and the steps they may take to address this?

**Comment by royling** [comment]
> Sounds like a sensible reason to consider this. Will the user require additional information about the returned warning? Is changing the icon sufficient or will some messaging be required? How will the user understand he reasons for receiving the warning and the steps they may take to address this?

Yes, warning messages are required for notifying user the steps/actions if any.
I think it's very similar to `<clr-control-error />`, with some differences:
1. use a warning icon instead, e.g. exclamation-triangle
2. highlight the input and text with warning styles

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
