### ISSUE TITLE
Datagrid with open Master Detail prevents focus

### ISSUE THREAD

**Issue by TekSiDoT** [vmware/clarity#3999]
## Describe the bug

Opening the detail view on a Datagrid prevents form elements outside of this Datagrid to be focused.

## How to reproduce

Stackblitz: [https://stackblitz.com/edit/clr-datagrid-detail-focus-rebounder](https://stackblitz.com/edit/clr-datagrid-detail-focus-rebounder)

Repro:
1. Select 'My name' -> is focusable and editable
2. Open the detail view by clicking a '>>' button of any row
3. 'My name' is no longer focusable

## Expected behavior

Form elements should remain focusable even if a Datagrid Detail is shown.

## Versions

**App**

* Angular: 8.2.9
* Clarity: 3.0.0-next.1

**Device:**

* Type: MacBook Pro
* OS: MacOS Catalina
* Browser Chrome 78

## Additional notes

The error seems to be caused by two span elements before and after the root app element with the class `offscreen-focus-rebounder` which seem to be related to `clrFocusTrap`

**Comment by hippee-lee** [comment]
I believe that this behavior is needed to make the detail pane accessible to screen reader users. 
Is this correct @chlane ?

**Comment by gnomeontherun** [comment]
This is something I fixed in a version of the detail pane, the focus trap is too greedy in some cases (though in a modal it is sensible).

**Comment by chlane** [comment]
Yes we are doing this to serialize the focus order for keyboard-only and screen reader users using the tab key.

**Comment by TekSiDoT** [comment]
Does removal from the backlog indicate low priority?

**Comment by gnomeontherun** [comment]
No we're changing how we organize issues.
