### ISSUE TITLE
Graphs and Charts

### ISSUE THREAD

**Issue by prateek-shroff** [vmware/clarity#4001]
## Summary

_Summary the request and address the questions as appropriate._

* What is the change?
Features to develop Graphs and Charts in the application.
* Why should it go in Clarity?
Nowadays the major part of UI design includes Dashboards, which requires data to be presented in form charts and graphs
* Does this change impact existing behaviors? If so how?
This will be entirely a new module which shouldn't impact existing behavior.
* If this change introduces a new behavior, is this behavior accessible?
NA
## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_
NA
## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_
Use different frameworks along with clarity like Chart.js

**Comment by gnomeontherun** [comment]
Thanks for the request, but there is no real details about what use cases and why Clarity should be doing this (vs any of the existing charting libraries). Can you elaborate further on needs and use cases?

**Comment by prateek-shroff** [comment]
We are creating application using Clarity Design, and there is a use case to develop couple of graphs (Bar and Pie) to show the data along with other request. While we use Charting Libraries for the graphs, the look and feel becomes different from other components that is because different CSS style sheets. We need consistency in the looks for our dashboard.
Another reason, we find Clarity design much easier to integrate in comparison to other Charting libraries.
So i thought to check with your team if there is anything that you have created for charting or is there any plan to enhance the feature in clarity design.

**Comment by hippee-lee** [comment]
We don't have anything specific for charting in dashboards. Internally at VMware product teams make their own choices wrt the charting library best for their app(s). 

I have heard the requests for better guidelines wrt to charting/colors/a11y & theming for an out of the box experience for different libraries. However, thats a large effort and there isn't anything to report or point to in the library at this time. 

If you want to use the Clarity color palate we recently refactored the css to use custom properties and all of the color properties make use of these in the upcoming Clarity v3. You could build a charting theme based on the custom properties for the Clarity color palette and apply it to the charting library the app consumes. This might give a close look-n-feel inside and next to the Clarity components.
