### ISSUE TITLE
If clarity support filter with checkbox option for multi-selection for datagrid?

### ISSUE THREAD

**Issue by hurrine** [vmware/clarity#4002]
https://v2.clarity.design/datagrid/custom-filtering

Currently seems there is multi-selection without checkbox.

**Comment by gnomeontherun** [comment]
Please use our issue templates to fill out issues so we can understand what is being asked. Right now its unclear to me if you are looking for support, asking a question, or requesting a feature. To get a meaningful response please clarify your post with more detail.

The demo you linked shows a custom filter, which could have a checkbox list inside of it, but that is defined by the app itself. The filter can be found here https://github.com/vmware/clarity/blob/master/src/website/src/app/documentation/demos/datagrid/utils/color-filter.ts.

**Comment by bdryanovski** [comment]
Marking this issue as stale - so I'm closing it
