### ISSUE TITLE
Website Overhaul

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#4005]
This epic is to contain all of the website related tasks by v4.

* [ ] Homepage refresh
* [ ] Release notes refresh

**Comment by jmls** [comment]
are there any docs available for the v4 rc0 ?

**Comment by mathisscott** [comment]
@jmls 
I do not believe we have a preview available publicly. But if you fork a copy of our repository on github, running the v4 docs locally should be pretty straightforward.

**Comment by jmls** [comment]
ok, I'll give it a bash

**Comment by rcomblen** [comment]
Didn't manage to get the doc generated for v4 using the latest v4 tag ? Could you provide a procedure ?
