### ISSUE TITLE
How to identify Row and Column headers in VMWARE Clarity for Section508 compliance 

### ISSUE THREAD

**Issue by akumar2812** [vmware/clarity#4006]
I am using Clarity Datagrid and I need to be able to identify the Row and Column Headers. It is not clear how to do this using Clarity Datagrid. 

Thanks in advance.  

I have tried adding role="columnheader" but it gets ignored. 
Please see https://webaim.org/techniques/tables/data

The header for each data cell should display the **column** and **row** header for it to be Section508 compliant. 

<pre>

<table>
<caption>Shelly's Daughters</caption>

<tr>
<th scope="col">Name</th>
<th scope="col">Age</th>
<th scope="col">Birthday</th>
</tr>

<tr>
<th scope="row">Jackie</th>
<td>5</td>
<td>April 5</td>
</tr>

<tr>
<th scope="row">Beth</th>
<td>8</td>
<td>January 14</td>
</tr>

</table>

</pre>

![image](https://user-images.githubusercontent.com/16270634/68691353-39d8b680-0539-11ea-95ad-fdbeb989b8bd.png)

**Comment by gnomeontherun** [comment]
The Datagrid is not a table, and we apply the correct aria tags to make it defined as a grid type. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role You shouldn't have to handle this on your own, unless you are making a regular table yourself.

Do you have more detail about what is wrong exactly?

**Comment by gnomeontherun** [comment]
Closing as we don't have actionable details or a reproduction.
