### ISSUE TITLE
Hide Unhide capability for Columns in Clarity DataGrid

### ISSUE THREAD

**Issue by vkpavan26** [vmware/clarity#401]
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
As part of Clarity DataGrid currently we do not have a capability to hide few columns by default and if user wishes to unhide them user could do it as per their preference.

Hide/Unhide feature is extensively used in our existing UI projects.

![image](https://cloud.githubusercontent.com/assets/25317393/22238429/485390ae-e237-11e6-81cf-5c1ee2893b6f.png)
![image](https://cloud.githubusercontent.com/assets/25317393/22238434/4f9ba13a-e237-11e6-8d99-fb77ea61d9e2.png)

**Comment by clementcur** [comment]
In our project, we implemented a column picker feature on top of the Clarity ng datagrid. If that's any of your interest, I would be glad to contribute back to Clarity! You could have a quick look at what've implemented and let me know - the code is currently hosted in our internal git repo, I'll be happy to provide you the URLs via DM (slack/email/...)

**Comment by hippee-lee** [comment]
As discussed with @reddolan - these are the limits on user interaction with the hide / show toggle component:

### Limits / Rules
1. `Select All` link is active in every selection state until there is all cols are selected.
2. If all columns are selected it will become disabled
3. Users can hide columns until there is only one column showing. Then the checkbox/label will become inactive/disabled and they will not be able to click on it. 

### Mockup:
`Note:` the relevent entry is the state of the last item in the image. 
![pasted image at 2017_03_30 12_26 pm](https://cloud.githubusercontent.com/assets/433692/24517949/07a25492-1535-11e7-9690-60f446d34353.png)
