### ISSUE TITLE
Replace Metropolis with Clarity City font

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#4010]
## Summary

Replace the default font with Clarity City. https://github.com/vmware/clarity-city

It should follow the pattern of Core where it is included via a CSS file through @clr/city package.

Make sure the documentation is included for the change and how to update. Might have migration paths, getting started info, etc.

## Use case

Cleans up some of the font issues from Metropolis

## Examples

Nope.

## Workarounds

N/A

**Comment by erabl-identos** [comment]
Hi,

will the new font also address this issue [https://github.com/chrismsimpson/Metropolis/issues/9](https://github.com/chrismsimpson/Metropolis/issues/9)?

Having same-width numbers when viewing large amounts of data in a table really helps to compare each row's values.

The ability to control the styling with `font-variant-numeric: tabular-nums;` has the benefit to not affect the flow of continuous text paragraphs, but still allows the application developer to choose tabular styling for an analytical context.

**Comment by mathisscott** [comment]
I don't think Clarity City has tabular numbers. But I could be wrong on that. @colinreedmiller would know for sure.

That said, it's one of the deficiencies we've put forward so tabular numbers are coming in the future if they aren't already in the font now.

**Comment by colinreedmiller** [comment]
I have not been informed that the tabular numbers have been created / added yet to Clarity City. The workaround has been to use Consolas for situations where column alignment is required.

**Comment by gnomeontherun** [comment]
We have adopted Clarity City within Clarity Core, making this as completed.
