### ISSUE TITLE
Date Picker cannot be disabled

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#4016]
## Describe the bug

When I disable the Date Picker input the calendar button is still enabled and enables the user to change the date.

## How to reproduce

https://stackblitz.com/edit/clarity-date-picker-disable

1.  Go to https://stackblitz.com/edit/clarity-date-picker-disable
2.  See calendar icon of disabled Date Picker is still enabled
2.  Click on calendar icon of disabled Date Picker
3.  Select a date
4.  See the date in the input has changed

## Expected behavior

Calendar button should be disabled in case the date input is disabled.

## Versions

**App**

* Angular: 8.2.13
* Clarity: 2.3.1

**Device:**

* OS: Windows 10
* Browser: Chrome 78

## Additional notes

Regarding #2515 it seems to be a regression.

**Comment by TekSiDoT** [comment]
I've played around with this issue a little:

* This issue does only occur when using [(clrDate)] Date-Object bindings
* I _suspect_ that the issue is related to this.ngControl being null [during ngOnInit() of the wrapped-control.ts](https://github.com/vmware/clarity/blob/a0aeea9536/src/clr-angular/forms/common/wrapped-control.ts#L122)

**Comment by gnomeontherun** [comment]
@TekSiDoT That seems correct, we are setting the disabled state based on the disabled state of NgControl, but using `[(clrDate)]` changes the logic path and doesn't have NgControl access (its not an Angular form control). So I believe the fix would be to also capture the disabled attribute in the ClrDateInput directive and figure out how to pass that up to the container.

**Comment by TekSiDoT** [comment]
Do you have any reservations against setting a public 'disabled' boolean on the container from the ClrDateInput directive? Would then be checked along the isEnabled getter in the container.

If you're ok with that I'd prepare a PR.

**Comment by gnomeontherun** [comment]
I haven't had a chance to look into this deeply, but generally we try to use services to communicate between components. If you have a proposal that isn't too difficult to implement, I'd be happy to review a PR.

**Comment by TekSiDoT** [comment]
Nice, I've never gotten around to pursue this further. My approach was also a lot more complicated, thanks @bdryanovski
