### ISSUE TITLE
Date Picker button title not reflecting internationalization string override

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#4018]
## Describe the bug

Date Picker button title not reflecting internationalization string override.
Refer stackblitz link for reproduction
![image](https://user-images.githubusercontent.com/12848838/68859931-698ce780-070e-11ea-9221-48bb549481ee.png)

## How to reproduce
https://stackblitz.com/edit/clarity-light-theme-v2-gfvji8

## Expected behavior

It should work as documented in the guide

## Versions

**App**

* Angular: 8.2.x
* Clarity: 2.3.1

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser chrome

**Comment by hippee-lee** [comment]
Thanks for reporting this.
