### ISSUE TITLE
Component 'Badges' documentation is missing and throwing console error 'StaticInjectorError'

### ISSUE THREAD

**Issue by Oliverq755** [vmware/clarity#4022]
## Describe the bug

In the component list, the badges component is missing. I am not able to see the badges even the routes in the address bar is not changing. Checking for badge component (onclick), console error is throwing (screenshot attached) (error: Uncaught (in promise): NullInjectorError: StaticInjectorError(a)[$r -> qr]:....).
## How to reproduce

Reproducing this bug is easy, just you have to navigate(or check for badge component).

Steps to reproduce the bug:

1.  Go to 'https://clarity.design/documentation/get-started'
2.  Click on 'Badges option' in Component accordions 
3.  Open your browser developer tool and check for console error

## Expected behavior

The expected behaviour should show the all possible design of badges as like other components.

## Versions

**App**

* Angular: [8.3.18]
* Node: [v12.13.0]
* Clarity: [2.3.2]

**Device:**

* Type: [Lenovo X230]
* OS: [Ubuntu]
* Browser [chrome]
* Version [78.0.3904.97]

## Additional notes

Do check the screenshot for the error and overview of bug.
![clarity_issue](https://user-images.githubusercontent.com/34798266/68924192-385ff600-07a6-11ea-9fcb-152b27a81126.png)

**Comment by bdryanovski** [comment]
This issue is resolved into this PR https://github.com/vmware/clarity/pull/3948 - so I'm closing it.
