### ISSUE TITLE
[i18n] Hardocded title in hide/show icon button at clr-password-container

### ISSUE THREAD

**Issue by Jor0Stam** [vmware/clarity#4029]
## Describe the bug

Hardcoded message in hide/show icon button at clr-password-container.

1.  Create password input field with clr-password-container
2. Hover on 'eye' icon button 
3. 'Show' and 'Hide' messages are not translated according to locale

## Expected behavior

'Show' and 'Hide' titles of icon button must be translated

## Versions

* Angular: 8.0.3
* Node: 12.11.0
* Clarity: 2.2.0

**Device:**

**Comment by gnomeontherun** [comment]
The title looks to the strings service for the translation, do you have a reproduction?

**Comment by Jor0Stam** [comment]
https://stackblitz.com/edit/clarity-light-theme-v2-j1wcwf

Switch the locale of the browser and observe the strings "Show"\"Hide" not being translated

**Comment by gnomeontherun** [comment]
That is expected, the browser locale is not used but the locale defined by the application. If you have support for different locales, the application has to take charge of changing the defined locale based on its own rules (a language switcher, looking at browser locale, etc).

Closing this as working as expected. The value is not hard coded, but you can learn more at https://v2.clarity.design/internationalization.
