### ISSUE TITLE
Update documentation on how to include webcomponents polyfill

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#4032]
## Describe the bug

According to the [documentation](https://v2.clarity.design/get-started), the webcomponents polyfill should be included in `angular.json` like this:

```
"scripts": [
  ... any existing scripts
  "../node_modules/@webcomponents/custom-elements/custom-elements.min.js",
  "../node_modules/@clr/icons/clr-icons.min.js"
]
```

When building like that, I was getting an error in IE11: 

```
customElements is undefined
```

## How to fix

I fixed the problem by instead including the webcomponents polyfill in `polyfills.ts` at the very end of the file:

```
... other polyfills
import '@webcomponents/custom-elements';
```

This is also the way I found that the polyfills are loaded in the stackblitz examples. If this is indeed the way to go and this was not some other configuration issue in my project, the documentation should be updated accordingly.

## Versions

**App**

* Angular: 8
* Clarity: 2

**Device:**

* Browser IE11

**Comment by gnomeontherun** [comment]
@coryrylan Do you know why this happens?

**Comment by coryrylan** [comment]
I ran into this testing Core this past week and its on my todo list to update. The latest version of the Web Component polyfills has changed its polyfills path. The above works. What we will probably recommend due to the feature set of Core is adding the following to the scripts instead

```javascript
"scripts": [
  "node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js",
  "node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js"
]
```

**Comment by gnomeontherun** [comment]
Should be updated for v1 & v2 as well.
