### ISSUE TITLE
Expandable rows animation not working correctly when using clrIfExpandedChange

### ISSUE THREAD

**Issue by omerheller** [vmware/clarity#4034]
## Describe the bug

When using expandable rows with clrLoading(for lazy loading) and with clrIfExpandedChange, the row expand animation plays but the row remains closed. Finally the row open without animation.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-o6nez4

1.  Expand row

## Expected behavior

Expandable row animation should start only when loading is set to false

## Versions

**App**

* Angular: 8
* Clarity: 2.3.2

**Device:**

* Browser: chrome
* Version: 78

**Comment by hippee-lee** [comment]
This started as a question on [Stackoverflow](https://stackoverflow.com/questions/58900388/expandable-rows-with-lazy-loading-not-working-correctly-when-using-clrifexpanded).

**Comment by Jinnie** [comment]
Using `clrLoading` here does not play well with the animation. As a workaround I can suggest to use *ngIf="!isLoading" here.
You can also add a "Loading..." placeholder this way, while the async operation is running.
```
 <clr-dg-row-detail clrIfExpanded (clrIfExpandedChange)="func(user)">
    <div *ngIf="isLoading">Loading...</div>
    <div *ngIf="!isLoading">Lorem ipsum...</div>
  </clr-dg-row-detail>
  ```
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.

(Though, as the Expandable rows have various accessibility issues, I can't guarantee if they will make it into Core, as a feature. At least - as they are in Clarity Angular)
