### ISSUE TITLE
Clarity Datagrid: alignment issues with row item / Col item 

### ISSUE THREAD

**Issue by itimie** [vmware/clarity#4037]
## Describe the bug

 

When inserting to a grid, column width calculation does not happen.

 

## How to reproduce

https://stackblitz.com/edit/server-driven-datagrid-starter-c2s8em?file=src/index.html

Use input 1 press enter. Then, input 2 press enter.

 

## Expected behavior

I expect the column to recalculate based on data that has changed

_A clear and concise description of what you expected to happen._

Once inserting input 2, I expect that either I see an ellipsis or the width recalculates

 

## Versions

 

**App**

 

* Angular: 6.2.9

* Node: 8.11.4

* Clarity: 0.13.11

 

**Device:**

Chrome

75.0.3770.142 (Official Build) (64-bit)

 

 

 

## Additional notes

1. There was a refactoring change added to version 1 (#2760). Will this change fix this issue?

2. I modified my clarity version to match what I use on stackblitz, I'm not sure this will make any change.

3. the datagrid does not adhere to the ellipsis class provided.

4. I’m unable to attach pictures for more clarity.

5. I tried removing clrDgRowSelected and the col were aligned properly. Why would this be the case?

**Comment by hippee-lee** [comment]
### Issue Recap
#2760 was an issue related to modals. I'm not sure how it applies here can you provide more details?
Just to confirm, the stackblitz provided is on Clarity v2.3.2  but you are having the issue with Clarity v0.13.11. Correct? 

### Questions

1. Is this be a server driven datagrid? From the code provided it doesn't look like the datagrid is server driven. (I'm not seeing the refresh method implemented)
2. Does the app add a row to the dataset already in the browser? Shouldn't the app add the row to the server and then refresh the data for the datagrid? I believe this is how server driven should work.  
3. Can you simplify the example? There are alot of layers here, the original [server-driven-starter](https://stackblitz.com/edit/server-driven-datagrid-starter) implements the datagrid at the top app.component.html level and uses pagination to demonstrate how the refresh output works for pagination.
4. It seems like the use case is to have a button that adds a row of data. If thats the case, it needs to add it to the server and then fetch the updates form the server to refresh the data. 

Here are the docs for v13: https://vmware.github.io/clarity/documentation/v0.13/datagrid/server-driven.

**Comment by itimie** [comment]
My bad was referring to https://github.com/vmware/clarity/pull/2670

Yes I was referring to 0.13.11. How do you create stackblitz with specific version of cor, angular and node?

The app should add to server and then fetch updates from server. Will modify

**Comment by hippee-lee** [comment]
Here is a v0.13.11 starter: https://stackblitz.com/edit/clarity-light-theme-v013
The render refactor didn't break the auto-sizing for column widths. 

Fyi - server driven datagrids implement the `(refresh) @Output and iterate with `*ngFor` instead of `*clrDgItems`.

**Comment by gnomeontherun** [comment]
0.13 is out of support and won't get further patches. If you can provide a working reproduction on v1 or newer, we can review it. Otherwise I'm going to close this as it has been a month without an update, you can post if you can reproduce the issue.
