### ISSUE TITLE
Datagrid showing horizontal scroll if the last column is hidden

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#4039]
## Describe the bug
Datagrid showing horizontal scroll if the last column is hidden

## How to reproduce
![image](https://user-images.githubusercontent.com/12848838/69304729-bcebc200-0c47-11ea-9891-2da97bbacf56.png)
https://clarity-datagrid-horizontalscroll.stackblitz.io

https://stackblitz.com/edit/clarity-datagrid-horizontalscroll

## Expected behavior
It should not show horizontal scroll if the width is enough in the window.

## Versions

**App**

* Angular: 8.x
* Clarity: 2.3.1

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
This is a known issue.Please subscribe to #1248 for updates. fwiw - the PR for drag and drop columns should fix that issue. Can you confirm @Shijir ? 

I'm closing this in favor of the existing issue.
