### ISSUE TITLE
Enable Community Icon _Contributions_

### ISSUE THREAD

**Issue by tenthirtyam** [vmware/clarity#4041]
## Summary

Allow users to submit pull requests for community designed icons that are reviewed and meet the Clarity design standards.

## Use case

Allows the community members to submit icons that are within the Clarity style guide for broader consumption either as native icons or additional packs.

## Implementation plan

- Provide documentation contributing to icons. using the content in the [Medium blog post](https://medium.com/claritydesignsystem/how-to-design-clarity-icons-a443b19ad84b) in the Clarity documentation for contributing icons.
- Provide a location for all SVG icons in the repo for submissions.
- Provide a backlog of icons that the community members can help support and the maintainers can review.
- Provide a method to ensure submitted icons are reviewed, tagged, etc and then introduced to Clarity.

**Comment by gnomeontherun** [comment]
We have all of our icons in our repo and documented, but as far as submitting new ones we aren't necessarily opposed to having someone upload assets for them for us to review. However, we don't have the source files available and it would be a major amount of process to setup and manage a contribution workflow for icons.

In my opinion, if someone has an icon to share they should share it but I can't guarantee it would meet our guidelines and most likely would be modified before being released.

I'm going to close this, you can open an issue with a contribution but be sure to provide sources and details about it to consider.
