### ISSUE TITLE
Stepper - clrInitialStep not working

### ISSUE THREAD

**Issue by tschambalamba** [vmware/clarity#4048]
## Describe the bug

clrInitialStep not working --> always showing first Panel
## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-mabxxu

1.  Go to 'Page'
2.  Second Panel (contact) should be shown

## Expected behavior 

Panel which is defined in clrInitialStep should be displayed

## Versions
Angular: 8.2.12
Node: 10.16.0
Clarity: 2.3.0

**Comment by gnomeontherun** [comment]
I can verify it works with reactive forms, but something is not quite right with template forms. Template forms are not equal in how they group controls, so perhaps we've got some internal logic wrong, or worst case is we can't support it.

Workaround is to use reactive forms for now.

**Comment by bdryanovski** [comment]
Can we close this ? @gnomeontherun
