### ISSUE TITLE
core tag/badges: alias API removal

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4056]
Currently with badges and tags we have three APIs to style them

`status` which aligns with alerts/buttons (`warning`, `info`, `danger`, `success`)
`color` defines a predetermined color value (`blue`, `purple`, ect) 
`alias` which maps to defined colors via alias numbers (`1`, `2`)

Opening this issue to determine if alias should exist or not for the new API and if not then remove before 3.0. Alias seems unnecessary as it introduces two APIs to accomplish the same task but any feedback or maybe historical knowledge on the old alias API is welcome.

**Comment by mathisscott** [comment]
Our intent with the `alias` was so that the various stylings of badges, etc., wouldn't be tied to a specific color. I'm fine with getting rid of it. I don't think a lot of people use the aliases in the way we thought they would...

**Comment by coryrylan** [comment]
Ok, after internal discussion I think we are going to drop the alias API and improve the WC theme architecture as a separate issue.
