### ISSUE TITLE
Datepicker steals focus when hitting escape

### ISSUE THREAD

**Issue by rogerfar** [vmware/clarity#4060]
## Describe the bug

When using a date picker it always listens for the escape key, even when closed. 

When hitting the escape key when the date picker is closed it will focus on the little calendar icon. If the date-picker is out of view the page will scroll to the picker.

## How to reproduce

1. https://v2.clarity.design/datepicker
2. Hit escape
3. The focus will shift to the first available date picker

## Expected behavior

Nothing should happen when the picker is closed.

## Versions

Reproducible on Clarity 2.3.2 and Angular 8.2.14

**Comment by hippee-lee** [comment]
It looks like the datepicker container needs a guard that checks the ifOpenService state to make sure that it is open before it calls `this.toggleButton.nativeElement.focus()`.

This is the line where the datepicker escape listener is handled: https://github.com/vmware/clarity/blob/master/src/clr-angular/forms/datepicker/date-container.ts#L132

**Comment by bdryanovski** [comment]
I could address this as part of the clear functionality. Or in separate PR. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
