### ISSUE TITLE
Affinity Designer Assets pack

### ISSUE THREAD

**Issue by ratsey** [vmware/clarity#4064]
## Summary

* What is the change?
Provides an asset pack for Affinity Designer based upon the existing Sketch UI assets.

* Why should it go in Clarity?
Gives designers an additional design outlet

* Does this change impact existing behaviors? If so how?
No impact

* If this change introduces a new behavior, is this behavior accessible?
No new behavior

## Use case
Design end user web pages using Affinity Designer

## Examples
N/A

## API
N/A

## Implementation plan
Attached!
[ClarityDesign.zip](https://github.com/vmware/clarity/files/3913251/ClarityDesign.zip)

**Comment by gnomeontherun** [comment]
Thanks for the assets for Affinity! We don't have the bandwidth or capability to maintain another library format at this stage, but we hope that you'll share this to anyone who has need.

Closing as we won't be able to adopt this, but thanks for the assets pack!
