### ISSUE TITLE
Clarity Icons: Store each shape markup in an individual file 

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#407]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X ] enhancement
```

### Expected behavior

Currently, we are adding new SVG icon markups to our clarity-icons template files so their sizes are becoming very large. The volume 2 icons alone might put ~150KB into template files. The possible solution to that might be storing each shape markup in an individual file so users could use and load only particular shapes.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
This issue will be solved by enabling users to embed and load the source of individual icons once we refactor our iconography website. Also, currently, users can download all icons as `svg` files.

**Comment by mathisscott** [comment]
Reopening this as it is key to some issues our users are experiencing in terms of confusion as to which sets to load or which sets are loaded.

**Comment by Shijir** [comment]
We have already made several optimizations in Clarity Icons. We will be further improving the optimizations as outlined in this issue https://github.com/vmware/clarity/issues/2052. So closing this one now.

**Comment by alesf** [comment]
I really hope this could be implemented as right now it's practically impossible to import only the icons you need which drastically increases the file size.

**Comment by mathisscott** [comment]
@alesf 
The `@clr/icons` library isn't built to import only the icons you need – as you've noted.

Fortunately, we are deprecating that library in the not-too-distant future and its replacement in `@clr/core` already has parity with the previous library. Take a look at [the @clr/core library](https://github.com/vmware/clarity/tree/master/src/clr-core) and also [this example of how to use the Clarity Core icons](https://github.com/vmware/clarity/blob/master/src/dev-core/src/app/icon/icon.demo.module.ts) to do exactly what you want.

**Comment by alesf** [comment]
@mathisscott 
Thank you!
I've tried importing icons from @clr/core but I ran into one issue. I'll report the issue there if someone will be able to help.
