### ISSUE TITLE
Modal can't be opened a second time after closing with X in IE11

### ISSUE THREAD

**Issue by rootix** [vmware/clarity#4070]
## Describe the bug

If a modal is closed with the close() method of the modal, it cannot be opened anymore in IE11. Debugging showed that the fadeDone method is not called in IE11 and therefore the openChange output event is not triggered. It works in all other tested browsers.

## How to reproduce

The bug can be reproduced on the Documentation website:

https://v2.clarity.design/modals

Choose any of the Angular modals and close it with X. You can't open it again. 

## Expected behavior

The modal can be opened every time.

## Versions

**App**

* Angular: 8
* Node: 10.16.0
* Clarity: 2.3.2

**Device:**

* OS: Windows 10
* Browser: Internet Explorer
* Version: 11

## Additional notes

https://clarity.design/ doesn't work anymore in IE11 probably due some Webcomponents things with the new Core components?

**Comment by rootix** [comment]
Related to #1148

**Comment by gnomeontherun** [comment]
Hi @rootix, thanks for this and I do see the issue in Clarity 2, but interestingly Clarity 3 appears to be working. Do you see the same thing at https://clarity.design/documentation/modals? This seems like an issue with IE11 and Angular animations at the root, I'm not sure if we're able to address it at the moment. It is not related toe the web components, however.

The workaround is to update to v3, which I know might not be an option for everybody. The second workaround would be to use the static modals.

**Comment by gnomeontherun** [comment]
This issue appears to be resolved in v3+, and it has not been updated in a while so I'm marking it as closed.
