### ISSUE TITLE
Focus does not move appropriately when the wizard dialog appears

### ISSUE THREAD

**Issue by clane** [vmware/clarity#4081]
## Describe the bug

 [Test URL]
https://clarity-light-theme-v2-a6ykys.stackblitz.io

[WCAG 2.1 Guideline]
2.4.3 Focus Order
(Level A)

[Screen Reader/Browser]
Any

[Description]
Focus does not move appropriately when the wizard dialog appears

[User Impact]
Screen reader users do not hear anything after activating the "Toggle" button which may be confusing.

[Recommendation]
Move browser focus to the the first heading in the wizard dialog when it opens.

## How to reproduce

1.  Using a screen reader, go to the Test URL
2.  Activate the "Toggle" button
3.  Observe that you do not hear any content from the wizard dialog

## Expected behavior

Move browser focus to the the first heading in the wizard dialog when it opens.

## Versions

**App**

* Angular: Uknown
* Node: : Uknown
* Clarity: : Uknown

**Device:**

* Type: Any
* OS: Any
* Browser: Any
* Version: Any

**Comment by Shijir** [comment]
This is closed by https://github.com/vmware/clarity/pull/3818 and https://github.com/vmware/clarity/pull/3496
