### ISSUE TITLE
Screen readers can read content outside of the wizard dialog

### ISSUE THREAD

**Issue by clane** [vmware/clarity#4082]
## Describe the bug

 [Test URL]
https://clarity-light-theme-v2-a6ykys.stackblitz.io

[WCAG 2.1 Guideline]
2.4.3 Focus Order
(Level A)

[Screen Reader/Browser]
Any

[Description]
Screen readers can read content outside of the wizard dialog.

[User Impact]
Screen reader users may be confused by reading content that is not supposed to be read in the current application context.

[Recommendation]
Use aria-modal="true" and text implemented with .is-off-screen to create textual boundaries for the wizard dialog.

## How to reproduce

1. Using a screen reader, go to the Test URL
2.  Activate the "Toggle" button
3.  Using the screen reader's cursor, attempt to read content outside of the dialog and observe that you can.

## Expected behavior
Screen reader users should not be confused by reading content that is not supposed to be read in the current application context.

## Versions

^?**App**

* Angular: Uknown
* Node: : Uknown
* Clarity: : Uknown

**Device:**

* Type: Any
* OS: Any
* Browser: Any
* Version: Any

## Additional notes
NA

**Comment by gnomeontherun** [comment]
This is resolved in the latest Clarity version already, this demo is v2.1.0 and updating shows the correct implementation as expected.
