### ISSUE TITLE
Modal: Focus moves out of the modal while pressing CapsLock + Right Arrow Key

### ISSUE THREAD

**Issue by Tushar2098** [vmware/clarity#4091]
## Describe the bug

Focus moves out of the modal while pressing CapsLock + Right Arrow Key

![image](https://user-images.githubusercontent.com/8487521/70230048-7cc72c00-177d-11ea-9bba-91acce2cd94c.png)

## How to reproduce

1. Go to : [https://v2.clarity.design/modals](https://v2.clarity.design/modals)
2. Start the Voiceover
3. Launch the Modal
4. Keep on hitting CapsLock + Right Arrow Key until focus moves out of the modal
5. Observe the Voiceover

## User Impact
Vision-impaired users may get confused about the modal content.

## Expected behavior

Focus should not move out of the modal even while doing CapsLock + Right Arrow

## Versions

This issue is reproducible with the latest version of Clarity in Chrome

**Comment by hippee-lee** [comment]
This is related to the modifier key (The behavior can also be observed with CTRL+OPTION+ right arrow key).

@clane - is this something the focus trap should actively prevent?

**Comment by gnomeontherun** [comment]
This is not something we can fix since these applications can override our focus trap capabilities, but we have implemented offscreen messages that screen readers should hear when they hit the boundaries of the modal to address this concern. Closing as working as expected.

**Comment by chlane** [comment]
This a VoiceOver reading cursor issue rather than a browser focus (document.activeElement) related issue. VoiceOver's reading cursor can access anything that is not hidden with aria-hidden="true".  We addressed this in https://github.com/vmware/clarity/issues/3420.
