### ISSUE TITLE
Incorrect colors in v3 preview docs

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#4099]
## Describe the bug

Some colors in color docs don't match CSS vars.

**Secondary Action 50:**
CSS var at runtime: #f7e6ff (incorrect)
hex from provided HSL: #F7E5FF

**Secondary Action 1000:**
HSL in code:
`$clr-color-secondary-action-1000: hsl($clr-secondary-action-hue, 100%, 14%) !default;`
hex from that: #320047
hsl in docs: hsl(282, 48%, 14%) (incorrect)
css var: #320047(correct)

**Warning 50:**
CSS var at runtime: #fffae6 (incorrect)
hex from provided HSL: #FFFAE5 (correct)

**Danger colors are all under a question**, as in [code](https://github.com/vmware/clarity/blob/master/src/clr-core/styles/variables/_variables.color.scss) we see real hue is 9, but comment says that it should be 14. In docs we see it having a value of 14, but in vars and components - still 9:
```
// Stoplight Danger color: alerts, error messaging, danger buttons
// 14 is the correct temperature

$clr-danger-hue: 9;
$clr-color-danger-50: hsl($clr-danger-hue, 100%, 97%) !default;
$clr-color-danger-100: hsl($clr-danger-hue, 95%, 92%) !default;
$clr-color-danger-200: hsl($clr-danger-hue, 91%, 86%) !default;
$clr-color-danger-300: hsl($clr-danger-hue, 83%, 76%) !default;
$clr-color-danger-400: hsl($clr-danger-hue, 85%, 67%) !default;
$clr-color-danger-500: hsl($clr-danger-hue, 88%, 61%) !default;
$clr-color-danger-600: hsl($clr-danger-hue, 92%, 50%) !default;
$clr-color-danger-700: hsl($clr-danger-hue, 100%, 43%) !default;
$clr-color-danger-800: hsl($clr-danger-hue, 100%, 38%) !default;
$clr-color-danger-900: hsl($clr-danger-hue, 100%, 30%) !default;
$clr-color-danger-1000: hsl($clr-danger-hue, 100%, 20%) !default;
```
in runtime we see this:
--clr-color-danger-50: #fff2f0 (equal to hsl(9, 100, 97))
in docs color swatch we see hsl(14, 100, 97) in a swatch label:
real rendered color of Danger-50 swatch: #FFF3F0 (equal to hsl(14, 100, 97))

So, you have to decide which $clr-danger-hue value is correct - 9 or 14?

**added:**
functional Backgrounds and borders 200, 500, 600 and 700 are different from neutral 200, 500, 600 and 700. Actually, they look similar to what you had before or at the beginning of colors update.

**Looks like most of the functional colors are also outdated.**

## How to reproduce

Just compare values in [code](https://github.com/vmware/clarity/blob/master/src/clr-core/styles/variables/_variables.color.scss) to CSS vars at runtime and to [color docs](https://clarity.design/documentation/color)

## Expected behavior

Colors in code should match colors in docs

## Versions

**Website**

3.0.0-next.4 as of now

**Comment by sdurnov** [comment]
Also:
functional Backgrounds and borders 200, 500, 600 and 700 are different from neutral 200, 500, 600 and 700. Actually, they look similar to what you had before or in the beginning of colors update.

**Comment by gnomeontherun** [comment]
In v3, we now use only hsl to define colors. SASS generates HEX codes from these values, which depending on the specific calculator used may generate extremely small variances. When in doubt, use the hsl values. I'm closing this as resolved.

**Comment by sdurnov** [comment]
> In v3, we now use only hsl to define colors. SASS generates HEX codes from these values, which depending on the specific calculator used may generate extremely small variances. When in doubt, use the hsl values. I'm closing this as resolved.

My point was, apart from those small differences, that there was a mismatch between some SASS values and values provides on a website. Not small differences, but typos or something like that.

**Comment by mathisscott** [comment]
These aren't typos, though. This is how the browser (or in our case SASS) interprets the values. We shouldn't be comparing the v3 hsl values (or rendered values) to the v2 documentation.

You should be [comparing the hsl values in v3 against its own hsl values](https://clarity.design/documentation/color)...

**Comment by sdurnov** [comment]
> These aren't typos, though. This is how the browser (or in our case SASS) interprets the values. We shouldn't be comparing the v3 hsl values (or rendered values) to the v2 documentation.
> 
> You should be [comparing the hsl values in v3 against its own hsl values](https://clarity.design/documentation/color)...

Yep, I will compare it for the v3 release and will leave a comment here in case I'll see something. I'm performing the update of my Figma library and recreating color palette from scratch, so I'll definitely go over all base pallette values.

**Comment by mathisscott** [comment]
The Figma files will need to be updated to HSL. I'm sure @reddolan has that on his roadmap.

**Comment by sdurnov** [comment]
> The Figma files will need to be updated to HSL. I'm sure @reddolan has that on his roadmap.

I'm having my own lib, which is optimized for heavy tasks, so I handle that myself 🙂 Though, I wouldn't recommend using anything, but HEX values in Figma, because there is a known bug in Figma, when they mess up some non-HEX values, which is impossible to fix for a file where it happened and some other files, which use "infected" library, other than by rolling back entire library. And guys from Figma aren't giving any estimates on fixing that.

**Comment by gnomeontherun** [comment]
HSL is our guideline and if there is an issue with Figma then it will need to approximate the HEX value to the best degree. If there are minor calculation differences (#FFFAE5 vs FFFAE6) that is just a rounding issue with the calculation. Our color palette documentation on the website with HSL is the source of truth, everything else should adhere as closely as it can. I'm going to lock this as resolved and if there is a specific bug please advise in a new issue.
