### ISSUE TITLE
Timeline variables are not overridable

### ISSUE THREAD

**Issue by srikanthps** [vmware/clarity#4104]
## Describe the bug

Many of CSS variables in Timeline component are not overriddable.

Ref: https://github.com/vmware/clarity/blob/e9d804682fa6b9f410a1de04553fa69fbec450ad/src/clr-angular/timeline/_variables.timeline.scss

```
// overall
$clr-timeline-icon-size: $clr_baselineRem_1_5;
$clr-timeline-icon-inner-padding: $clr_baselineRem_2px;
...
```
Typical practice in clarity has been to append `!default` to variables, but in this file many of the styles don't have `!default` added.   Is this a miss or there is a conscious decision to not allow overrides?

We are clr baseline of 16px, needed to adjust the various sizes of clr-timeline for it to still appear as it appears in Clarity website https://v2.clarity.design/timeline#examples.  Without overriding variables, the timeline appears bit smaller - though it is working as expected.

Ours
![image](https://user-images.githubusercontent.com/102016/70540456-4fb6b700-1b8b-11ea-907b-0ad002e3b548.png)

Clarity:
![image](https://user-images.githubusercontent.com/102016/70540476-5c3b0f80-1b8b-11ea-816b-5823ab9f2ca4.png)

## How to reproduce

Following guide on themeing (https://v2.clarity.design/themes) to add custom theme

```
// Your Application Theme File
@import "./theme.scss";

// Clarity Component SCSS
@import "../node_modules/@clr/ui/src/utils/components.clarity";

```

In theme.scss, change icon size to 2rem
$clr-timeline-icon-size: 2rem

## Expected behavior

Icons become bigger in timeline

## Versions

**App**

* Angular: 8.2.13
* Node: v10.16.0
* Clarity: 2.2.2

**Device:**

* Type: Dell Laptop
* OS: Windows 10
* Browser Chrome
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
Generally speaking, Clarity avoids making sizing and layout variables "overrideable".

Given the nature of the timeline component and the precise positioning involved, changing the sizes within the component could cause unexpected side effects to the layout of the component. 

What is it you are trying to override and why?

**Comment by srikanthps** [comment]
With baseline as 16px in our theme,  the icon size is 24 px (1.5rem).  I would like to make the icon size to 36px by using 2rem.  Thats the first step -- I do see alignment issues if I use bigger icon.  I was thinking that by overriding multiple timeline SCSS variables, I should be able to make timeline look like the clarity with baseline 16px

**Comment by mathisscott** [comment]
That would require a pretty deep knowledge of the variables. IMO, the best path forward is applying custom CSS. It would allow you to optimize the layout for your specific use case without unintended side effects creeping in.
