### ISSUE TITLE
Chat-bubble 404

### ISSUE THREAD

**Issue by LucasHimelfarb** [vmware/clarity#4105]
## Describe the bug
chat-bubble icon is not found...
_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

https://clarity.design/icons

first step:  Search in Clarity design: "chat".
second step: Download chat-bubble icon.

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
This works for me. I click on the `SVG Icon` button and it downloads as expected.

Are there any other details you'd like to share? Or do you want to try again?

**Comment by bdryanovski** [comment]
Closing issue as invalid
