### ISSUE TITLE
Icons Volume 17 

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#4107]
## Summary
An Icon to distinguish between "users/customers" and "employees" is missing.
The "user" icon is already available in clarity: shape="user" and shape="users".
Whats missing is the equivalent for employee/s.

* What is the icon? 
an employee, a group of employees
* What does the requested icon signify? 
differentiation if an entity is assigned to customers or employees
* In which product(s) will this icon be used? 
business to customer application

## Use case
differentiation if an entity (appointment, task, search-result, ...) is assigned to customers or employees

## Examples
see screenshots, something like the exisiting user icon with a tie:

![2019-12-11_09h32_44](https://user-images.githubusercontent.com/311619/70606182-4154b380-1bfc-11ea-8ebb-bb8ea3fbccd8.png)

![2019-12-11_09h45_50](https://user-images.githubusercontent.com/311619/70606017-ea4ede80-1bfb-11ea-937d-0ab4b8609d76.png)

## Alternatives
alternative, that of course does not transport any meaning:
![2019-12-11_09h52_44](https://user-images.githubusercontent.com/311619/70606061-005c9f00-1bfc-11ea-899f-c0fd3fc9f51b.png)

us the solid and outline ones to distinguish between customers and employees
(shape="user" class="is-solid")

**Comment by mathisscott** [comment]
@lil-kim 
What do you think about a volume 17 set in early 2020?

**Comment by lil-kim** [comment]
@d-m-s 
How about the "id-badge" icon to represent employee?
![image](https://user-images.githubusercontent.com/23196444/70648500-03f22500-1c00-11ea-8096-e8b0f3dacf88.png)

**Comment by dorthrithil** [comment]
An animation icon would be great in the new icon set. I'm building a tool in which you can animate elements. Clicking the icon would lead to the animation configurator.

Example:

![46381](https://user-images.githubusercontent.com/3655915/70704899-3587f080-1cd3-11ea-8cc8-4725e617dab6.png)


There is the `play` icon already, but this goes more in the direction of actually starting the configured animation.

![Screen Shot 2019-12-12 at 11 28 58](https://user-images.githubusercontent.com/3655915/70704851-20ab5d00-1cd3-11ea-93a9-8e53c71bf512.png)

**Comment by d-m-s** [comment]
> @d-m-s
> How about the "id-badge" icon to represent employee?
> ![image](https://user-images.githubusercontent.com/23196444/70648500-03f22500-1c00-11ea-8096-e8b0f3dacf88.png)

**nice idea! thanks!**
- as a workaround that works pretty good, but we also need icons like driver-licence or identification cards, there we use the "id-badge"
- so on the long run, 
  - some user-icon with tie or 
  - an user icon with badges in the upper/lower right corner - where probably any other clr-icon could be placed, would be great!

**Comment by lil-kim** [comment]
Icons for Vol 17

1. Employee
2. Group of employees
3. Factory
4. Holiday / not available notification
5. File share
6. Color palette
7. Animation 
8. CI/CD

**Comment by lil-kim** [comment]
Here are all the .svg icons requested in this Epic.
[volume-17-icon-set.zip](https://github.com/vmware/clarity/files/4068486/volume-17-icon-set.zip)
Included in the zip attachment:

![image](https://user-images.githubusercontent.com/23196444/72482645-47b5ec80-37b3-11ea-98e7-52fd66e5dc0f.png)

**Comment by mathisscott** [comment]
Added to `clarity-assets`. 
https://github.com/vmware/clarity-assets/commit/f31104556a209e185df5418716fbf517e40bc012

Working on adding to clr-icons and clr-core next...
