### ISSUE TITLE
Sketch icon library is missing some icons

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#4108]
Our designer reported, that the sketch icon library 2.2 is missing the following icons:

- `campervan`
- `language`

**Comment by mathisscott** [comment]
@reddolan : Thoughts?

**Comment by reddolan** [comment]
I will look into it with this next cycle of lib updates

**Comment by gnomeontherun** [comment]
Sketch has been deprecated, closing this as no longer relevant.
