### ISSUE TITLE
Update Header documentation with new "VMW" bug (icon)

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#4115]
VMware Marketing team has created a new VMW icon to replace the current VM icon (a.k.a "VM bug") shown in Clarity headers. All references and images to the VM bug need to be updated.
@rebbecca  mcmillin will provide more content to this ticket regarding usage for the new icon.

**Comment by mathisscott** [comment]
Is this something that we need to backport? Or is it only 3.0 and up?

**Comment by lil-kim** [comment]
@mathisscott, No backport. 3.0 and up.

**Comment by mathisscott** [comment]
Note: When we get this icon, we'll need to put it in `@clr/icons` and `@clr/core` (replacing the `vm-bug` icon in both instances.

**Comment by lil-kim** [comment]
Here's the icon:
[VMW-bug.svg.zip](https://github.com/vmware/clarity/files/3963076/VMW-bug.svg.zip)

**Comment by mathisscott** [comment]
Note: this work should be considered blocked until #4112 is merged. Reason = no sense in completing it in two phases when the `@clr/core` Core icons set is already in PR...
