### ISSUE TITLE
ClrPopoverToggleService to use BehaviorSubject instead of Subject for openChange observable

### ISSUE THREAD

**Issue by bdryanovski** [vmware/clarity#4118]
## Summary

Currently `ClrPopoverToggleService` implement its `openChange` observable as follows:

```ts
// src/clr-angular/utils/popover/providers/popover-toggle.service.ts
private _openChange: Subject<boolean> = new Subject<boolean>();
```
We could replace it to use the `BehaviorSubject` like this:
```ts
private _openChange: BehaviorSubject<boolean> = new BehaviorSubject<boolean>(false);
```

This way we could not only subscribe to changes and take some actions but also get the last value. This will simplify the implementation of how we track the state (open/close) and will eliminate potential bugs when we try to compare values as we had here: #3804 #3904 

Additional to this change we could use `distinctUntilChanged` and remove the need of keeping local variable for the state (open/close)
```ts
import { BehaviorSubject } from 'rxjs'
import { distinctUntilChanged } from 'rxjs/operators';

const subject = new BehaviorSubject(false);

subject
.pipe(distinctUntilChanged())
.subscribe(console.log);

subject.next(false);
subject.next(true);
subject.next(true); // this change won't be fired
subject.next(false);

// => false
// => true
// => false
```

* What is the change?
In the most simplest form, the change requires just to change the type of `openChange` no additional charge is required.

**Comment by gnomeontherun** [comment]
Given this is an internal detail, I'm concerned about possible side effects. At this stage it makes sense to close this and only consider it if we have issues with the existing implementation.
