### ISSUE TITLE
ControlIdService & DatalistIdService could be optimized 

### ISSUE THREAD

**Issue by bdryanovski** [vmware/clarity#4124]
Both classes `DatalistIdService` and `ControlIdService` are almost identical. Both of them are using `this._id` to return and track the internal state of the class. This could be optimized by using the already provided `BehaviorSubject.getValue`.

```ts
private _idChange: BehaviorSubject<string> = new BehaviorSubject(`<css-class>-${++counter}`);

get id(): string { 
  return this._idChange.value; 
}
set id(value: string) { 
  this._idChange.next(value); 
}
get idChange(): Observable<string> { 
  return this._idChange.asObservable();
}
```

**Comment by gnomeontherun** [comment]
This is not committed into master yet, I'm going to close this since you can make this comment on the open PR #4121

**Comment by bdryanovski** [comment]
We had a talk with @hippee-lee and decide that this is out of the scope of #4121 - but it's true only one of the services right now is into master. 

So this a good "Help Wanted"  task.
