### ISSUE TITLE
3.0.0-next.5 - breaks --strictNullChecks builds

### ISSUE THREAD

**Issue by TekSiDoT** [vmware/clarity#4140]
## Describe the bug

Clarity 3.0.0-next.5 breaks builds that use --strictNullChecks as a TypeScript Configuration.

## How to reproduce

1.  Enable strictNullChecks in your project (either in tsconfig or via tsc parameter)
2.  Build / Serve
3.  The following error will occur (plenty of times): 

`../../node_modules/@clr/core/icon/collections/essential.d.ts:xxx - error TS2411: Property '[_someIconeName_]' of type 'string | undefined' is not assignable to string index type 'string'.`

## Expected behavior

Project should build properly

## Versions

**App**

* Angular: [8]
* Node: [12]
* Clarity: [3.0.0-next.5]

## Additional notes

Probably related to https://github.com/vmware/clarity/pull/4125 / https://github.com/vmware/clarity/pull/4112

**Comment by TekSiDoT** [comment]
Workaround: enable `skipLibCheck` in your projects tsconfig

**Comment by coryrylan** [comment]
Fixed https://github.com/vmware/clarity/pull/4178
