### ISSUE TITLE
Color palette for charts

### ISSUE THREAD

**Issue by nikhildhankani** [vmware/clarity#415]
```
[ ] bug
[ ] feature request
[x ] enhancement
```

It will be great if clarity and can recommend a color palette to be used in charts when using clarity. That will help interfaces using clarity look consistent. This can be an enhancement to [existing color documentation](https://vmware.github.io/clarity/documentation/color) or a new addition.

**Comment by yenmade** [comment]
We will be looking into expanding the Clarity color palette to include colors for charting.

**Comment by mathisscott** [comment]
@lil-kim : Plz post the Color Palette screens when you can and remove the needs-UX-input label. If you wouldn't mind, please also remove yourself as the assignee and move this issue into the Bullpen so we can assign it to someone to put up on the website.

**Comment by lil-kim** [comment]
We have merged your request into Enhanced Color Palette... #885. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you
