### ISSUE TITLE
[Datagrid] Datagrid content should scroll within its container when content is too wide

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#416]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If a datagrid is wider than its container, then the content within the datagrid should scroll horizontally instead of overflowing its container. The borders of the datagrid should shrink to the size of the container and the content should scroll inside of it similar to the way that bootstrap tables behave. This should work for both width and height when the containing div is smaller than the datagrid contents.

### Actual behavior
Similar to [this issue](https://github.com/vmware/clarity/issues/395) the datagrid behaves strangly when its content is wider than its container. The content of the datagrid horizontally overflows outside of its container.

### Reproduction of behavior
https://plnkr.co/edit/xtJWXKHcwxKTLx5APt8D

### Environment details

* **Angular version:** 
2.3

* **Clarity version:** 
0.7.4

* **OS and version:** 
macOS Sierra 10.12.2
 
* **Browser:** 
all

**Comment by jaffoneh** [comment]
@jbgarr I am closing based on issue #395 since this seems to be the same issue. We'll be sharing updates there (it is on our top priority list so you should see updates to that soon).

**Comment by jbgarr** [comment]
@jaffoneh Sounds good. I was about to add to that issue myself, but I didn't want to overload one issue in case you guys wanted to treat it separately.
