### ISSUE TITLE
Datagrid singleSelectedChanged is emitted when component is destroyed

### ISSUE THREAD

**Issue by MirakoMachine** [vmware/clarity#4162]
When we have a field with a filter, upon component destruction the filter is cleared which emits singleSelectedChanged with empty selection. 

Steps to reproduce: 
1. Have a grid with clrDgField set for a field in the grid.
2. Use the filter for that field to filter out some items. Then select one of the items. singleSelectedChanged is emitted with the selected item. 
3.  Destroy the component. Before destruction singleSelectedChanged is emitted again with "undefined" for selection. Expected is that singleSelectedChanged won't be triggered at all upon component destruction.

**Comment by gnomeontherun** [comment]
Can you provide an isolated example of this problem for us to review? What version are you using? We have a bug report template to help us understand what you are seeing, please use it to help us understand and prioritize reports.

Use https://stackblitz.com/@clr-team to find a starter template to work with.

**Comment by ivvatov** [comment]
Please take look at this repro: https://stackblitz.com/edit/clarity-light-theme-v2-2duxst?file=src%2Fapp%2Fapp.component.html .
Filter by name, e.g. with "doe", then select the row and click on the checkbox which will remove the grid. The selection change event is fired just then.

**Comment by hippee-lee** [comment]
I did a bit of high level investigation and it looks like the selection service is setting the currentSingle (selected item) to undefined here: https://github.com/vmware/clarity/blob/master/packages/angular/projects/clr-angular/src/data/datagrid/providers/selection.ts#L74 when Items gets destroyed.

More investigation is needed for a correct fix. I'm marking as a bug and putting into backlog.
