### ISSUE TITLE
feat(icons): CI/CD Icon

### ISSUE THREAD

**Issue by danielhelfand** [vmware/clarity#4166]
## Summary

Add a technology icon for CI/CD.

* What is the change?

Add a technology icon to represent CI/CD. Possibly a pipe as a CI/CD process is typically referred to as a pipeline. 

* Why should it go in Clarity?

There isn't an icon that captures CI/CD.

* Does this change impact existing behaviors? If so how?

N/A

* If this change introduces a new behavior, is this behavior accessible?

N/A

## Use case

I would like to have an icon to represent CI/CD as part of developing a plugin for Tekton to use with Octant.

**Comment by mathisscott** [comment]
@lil-kim
