### ISSUE TITLE
Datagrid: Select All functionality not only per page when pagination is active

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#4176]
## Summary

* What is the change?
We need a way to select all items from clr-datagrid not only per page but "ALL" when pagination is active.

* Why should it go in Clarity? 
We can't find a proper solution which isn't in a conflict with Clarity UX

* Does this change impact existing behaviors? If so how?
It impacts the current behavior of select all because the current selects all items only on the current page.

* If this change introduces a new behavior, is this behavior accessible?
yes

## Use case

Our use case is to select a big inventory of 4000 VMs without going through 100+ pages and select every single page one by one if we want to select the full list.

## Examples
I have prepared a stackblitz for it
https://stackblitz.com/edit/clarity-light-theme-v2-2v2blj-datagrid-selectall

Different ideas of presenting the "select all" trigger are commented in the .html file

## Workarounds

Not a reliable one which isn't in a conflict with Clarity UX.

**Comment by gnomeontherun** [comment]
@iivanovgit I think 'Select All' button in a `clr-dg-action-bar` element this is the preferred solution for applications to offer this type of select all functionality. The others obscure or conflate other UI elements at the same time (alerts, signposts) where we already have an action bar for the datagrid.

We're not likely to change the default select all button anytime soon, and this is generally the direction that makes sense. I'd only suggest that you label the Select All button differently to better differentiate its behavior vs the checkbox inside of the datagrid.

Closing as the suggested implementation is the best solution.
