### ISSUE TITLE
Aria-hidden on modal code sample

### ISSUE THREAD

**Issue by emily-kay** [vmware/clarity#4177]
The code sample has aria-hidden="true" when the modal is supposed to be visible which would cause the content to be skipped by screen readers. I'd highly recommend an indication that attribute needs toggled depending on state.

**Comment by gnomeontherun** [comment]
Hi @emily-kay which code sample are we talking about specifically? What you suggest is correct, but we have static examples that applications will need to dynamically change the attribute when it opens. We do control this correctly in our Angular component for you.

It sounds like you're really asking for an additional comment to mention that applications will need to control this value themselves if they don't use the Angular component for modals?

**Comment by emily-kay** [comment]
Yes, I was speaking to the modal code sample. Sorry for confusion. An additional comment in the documentation for modals is needed. Aria-hidden is used twice in that example, once for the modal and once for the icons. Since the latter example is meant to be permanently set to true, a comment saying the modal specific instance should toggle based on how it's visually represented would be a good idea.
