### ISSUE TITLE
Direct navigation to a Vertical nav group doesn't expand parent

### ISSUE THREAD

**Issue by dexfab** [vmware/clarity#4183]
## Describe the bug

Navigate directly to https://v2.clarity.design/vertical-nav/nav-groups/electric/pikachu
Parent node "Electric" should be expanded

## How to reproduce

Navigate directly to https://v2.clarity.design/vertical-nav/nav-groups/electric/pikachu

## Expected behavior

Parent node "Electric" should be expanded

## Versions

**App:**

* Angular: latest
* Node: latest
* Clarity: latest

**Device:**

* Browser: chrome
* Version: latest

**Comment by gnomeontherun** [comment]
This is actually to be handled by the application, but we don't have a good example of this it seems. We don't have a direct integration with the router to automatically handle this for you.

**Comment by mathisscott** [comment]
Adding in to the website work because it seems all we need is a working example.

**Comment by wokis** [comment]
For those like me looking for how to do it, this should do the trick. `<clr-vertical-nav-group routerLinkActive="active" [clrVerticalNavGroupExpanded]="this.router.url.includes('./electric')">`. You will of course also need to inject the router into your compoent, `constructor(public router: Router) { }`.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
