### ISSUE TITLE
Clarity 3.0.0-next.5 - Date Picker: min/max doesn't accept string variable

### ISSUE THREAD

**Issue by larsk27** [vmware/clarity#4184]
When trying to implement a min value for the Date Picker, it was not possible to use a string variable instead of a hard coded date. No date in the whole Date Picker then is selectable. Every date is deactivated.

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v2-yxfmhu

I tried to implement the issue on stackblitz. I have modified the package.json but it seems to me that it took no effect.

## Expected behavior

_A clear and concise description of what you expected to happen._

**App**

* Angular: [8.2.14]
* Node: [13.2.0]
* Clarity: [3.0.0-next.5]

**Device:**

* Type: [e.g. MacBook]
* OS: Windows 10
* Browser: Chrome, Firefox
* Version: latest

`<input type="date" clrDate name="mydate" [(ngModel)]="validFrom" required pattern="\d{2}(.)\d{2}(.)\d{4}" min="startDate">`

I tried it even with `this.startDate = "2020-01-09"` in ngOnInit.

**Comment by hippee-lee** [comment]
Hi @larsk27  - when submitting an issue please use the template provided and include a stackblitz that isolates and demonstrates the issue being reported. 

Thanks.

**Comment by larsk27** [comment]
@hippee-lee I tried my best to implement the issue on stackblitz. I think my changes in the package.json file are not used. Seems to use clarity 2.
Could you please check and support me?

**Comment by hippee-lee** [comment]
I modified the stackblitz to use latest Clarity packages (@clr/angular@next)
https://stackblitz.com/edit/clarity-dark-theme-v2-k6kuun

This demonstrates how to set min attribute values (similar to how its naturally set with html).

Please keep in mind that this stackblitz is still using Angular at version 8. Clarity v3 is still being prepared for Angular v9 as it goes through the beta and release candidate phase. 

I'm going to close this issue as answered. If you have more how to questions about Clarity please ask a question on StackOverflow and tag it with `vmware-clarity`.
