### ISSUE TITLE
[Accessibility]: Arrow keys tabs navigation using Clarity 1.

### ISSUE THREAD

**Issue by znpopov** [vmware/clarity#4187]
## Summary

Please back-port the following change to v1: https://github.com/vmware/clarity/pull/3609/commits

## Use case

Arrow keys tabs navigation using Clarity 1.

**Comment by mathisscott** [comment]
@Jinnie 
Is a backport of #3609 to v1 feasible?

**Comment by Jinnie** [comment]
It's a commit of medium complexity. I don't see what could prevent it, but there is a set of component changes there, also the KeyFocus directive was introduced. We'll probably have some manual work around replacing the ifOpenService, too. I think I can timebox it to a day and see if it goes smoothly.

**Comment by mathisscott** [comment]
Ok. Are the "component changes" additions to the API or breaking changes?

I'll discuss with @gnomeontherun at the planning meeting today and we'll get back to you on the priority. Thanks, @Jinnie !

**Comment by Jinnie** [comment]
No API changes, only the way the user interacts with the component (using arrow keys).
