### ISSUE TITLE
[CORE] Add CSS regression testing to Clarity's repo

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#42]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
```

### Expected behavior
We currently have tools that we use to make sure components work when we make changes but we should have public CSS regression testing as part of our build/submission process.

**Comment by jeeyun** [comment]
TODO:
- [ ] add css regression to Clarity core
- [ ] add css regression to Clarity website

The above tasks also include the task of hooking it up to TravisCI.
