### ISSUE TITLE
Theme: Instead of two theme file clarity.ui.min.css and clarity.ui-dark.css can we have three files one for clarity-core.css and two for respective light and dark theme.

### ISSUE THREAD

**Issue by rahultokase** [vmware/clarity#4200]
## Summary

_Summary the request and address the questions as appropriate._

* What is the change? Instead of two css file for light and dark theme we should also have one common css like clarity.core.css which will be common for light and dark theme.
* Why should it go in Clarity? If Application is having a theme switcher functionality between light and dark theme in this case replacing the light theme with dark theme will distort the UI. Ideally layout related css should be move to common.css and that should be always be present.
* Does this change impact existing behaviors? If so how?
* If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._
If Application is having a theme switcher functionality between light and dark theme in this case replacing the light theme with dark theme will distort the UI. Ideally layout related css should be move to common.css and that should be always be present. While Switching theme layout should not be distorted.
## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by mathisscott** [comment]
While a great suggestion, this will become unnecessary in 4.0 with CSS Custom Properties. The current SASS variables are being deprecated in 3.0. I'm closing this as a duplicate because it is work that is on our roadmap for 4.0.
