### ISSUE TITLE
Custom filter interface not mismatch with example. Need help to create a custom filter. 

### ISSUE THREAD

**Issue by MaxySpark** [vmware/clarity#4203]
* version 2.3.4
* File
`node_modules\@clr\angular\data\datagrid\interfaces\filter.interface.d.ts`

```
import { Observable } from 'rxjs';
export interface ClrDatagridFilterInterface<T, S = any> {
    isActive(): boolean;
    accepts(item: T): boolean;
    changes: Observable<any>;
    readonly state?: S;
    equals?(other: ClrDatagridFilterInterface<T, any>): boolean;
}
```

here `accepts` has only one parameter but in example two parameters being used.
https://github.com/vmware/clarity/blob/master/src/website/src/app/documentation/demos/datagrid/utils/pokemon-filter.ts

```
export class PokemonFilter implements ClrDatagridStringFilterInterface<User> {
  accepts(user: User, search: string): boolean {
    return '' + user.pokemon.number === search || user.pokemon.name.toLowerCase().indexOf(search) >= 0;
  }
}
```

I need to create a custom filter.

I have a column of name.

name structure
```
user: {
    name: {
       first: string;
       middle: string;
       last: string;
   }
}

```
I am displaying like this
```
<clr-dg-cell>{{ user.name.first }} {{ user.name.middle ? user.name.middle : '' }} {{ user.name.last }}</clr-dg-cell>
```

I need to create a filter for the name. I tried like this from the example but getting error 

`Property 'accepts' in type 'NameFilter' is not assignable to the same property in base type 'ClrDatagridFilterInterface<User, any>'.
  Type '(user: User, search: string) => boolean' is not assignable to type '(item: User) => boolean'.`

My filter 
```
export class NameFilter implements ClrDatagridFilterInterface<User> {

    accepts(user: User, search: string): boolean {
        return `${user.name.first} ${user.name.middle ? user.name.middle : ''} ${user.name.last}`.toLowerCase().indexOf(search) >= 0;
    }
}
```

**Comment by hippee-lee** [comment]
Hi @MaxySpark - here is a simple datagrid in a stackblitz app that works: https://stackblitz.com/edit/gh-4203-datagrid-filter

Please modify it to re-create the issue you are seeing. Its a challenge to triage issues that do not have a stackblitz reproduction. Thats why we ask for them in the issue template.

**Comment by MaxySpark** [comment]
I mixed `ClrDatagridStringFilterInterface` and `ClrDatagridFilterInterface`

working now... https://stackblitz.com/edit/gh-4203-datagrid-filter-vbdsvf?file=src/app/app.component.ts

thanx @hippee-lee
