### ISSUE TITLE
[RFC] Clarity Motion System

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#4206]
MVP motion system for clarity. Links can be provided by Clarity designers.

## Summary

This is an MVP to begin the process of adding motion to all appropriate Clarity components in a systematic way. By creating a set of unifying principles and a taxonomy of components we are able to create a hierarchical set of motion attributes which result in stylistic unity and economy of (design) scale

* Change: Addition of motion attributes to a select set of components
* Why: Addition of motion has aesthetic and usability benefits.
* Impact existing: Some motion that exists will need to be changed to achieve alignment.
* Accessible: All a11y concerns have been exposed and addressed.

## Examples

Sandbox here:
https://framer.cloud/KDGHg/index.html

Principles: Link can be provided by Clarity designers.

**Comment by colinreedmiller** [comment]
Motion system specification including:

Taxonomy allowing motion types to be applied in a modular manner
Curves and timings 
Principles 
https://confluence.eng.vmware.com/pages/viewpage.action?spaceKey=DESIGN&title=MVP

https://confluence.eng.vmware.com/pages/viewpage.action?spaceKey=DESIGN&title=Principles

**Comment by gnomeontherun** [comment]
We're going to start with tightening up the existing animations that exist to match the new spec. Then verify the implementation and requirements are in line with desired outcomes. This ought to be a stretch goal for v4 after we focus on requirements.

**Comment by gnomeontherun** [comment]
This is being closed as the implementation is nearing completion. Follow #5395 for the initial work!
