### ISSUE TITLE
DateFormControlService is null in DatePicker with 2.3.5

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#4208]
## Describe the bug

With the update from 2.3.4 to 2.3.5 I get the following error:

```
 TypeError: Cannot read property 'setDisabled' of null
      at ClrDateInput.set [as disabled] (../../../node_modules/@clr/angular/bundles/ng:/@clr/angular/forms/datepicker/date-input.ts:154:33)
```

It seems to be related to the following new line #4016 (#4174 - [Code Link](https://github.com/bdryanovski/clarity/blob/22f6eecf87e01b5946ce1b834e457ef3689d6594/src/clr-angular/forms/datepicker/date-input.ts#L164))

```ts
  // @Optional() private dateFormControlService: DateFormControlService,

  @Input('disabled')
  set disabled(value: boolean | string) {
    this.dateFormControlService.setDisabled(isBooleanAttributeSet(value));
  }
```

## Versions

**App**

* Angular: 8.2.14
* Clarity: 2.3.5

**Comment by martinbrom** [comment]
Removing the @Optional annotation for the DateFormControlService fixes the issue for me.

**Comment by gnomeontherun** [comment]
@bdryanovski can you add a check before using the service? We missed this in the reviews.

**Comment by BramMeerten** [comment]
Had the same issue after upgrading. It forces me to use a `clr-date-container` so `DateFormControlService` is provided.

```
<clr-date-container> <!-- Without clr-date-container you get the error -->
  <label>Label</label>
  <input type="date" clrDate [(clrDate)]="date" [disabled]="disabled"/>
</clr-date-container>
```
