### ISSUE TITLE
Chevron (caret) icon placement inconsitencies 

### ISSUE THREAD

**Issue by lpetkov** [vmware/clarity#4220]
Hi, 
Recently the VMware vSphere team replaced the old custom vertical tree sidebar in vSphere with a Clarity Vertical Nav component:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/31132490/72800993-3b1d1280-3c51-11ea-929d-603cd27533da.png">

It looks neat, however in VMware vSAN we use the Clarity Accordion Component right next to the newly introduced Vertical Nav component and there's an issue with how the caret icons are placed:

<img width="736" alt="image" src="https://user-images.githubusercontent.com/31132490/72800538-46237300-3c50-11ea-89c4-063a289fb6b0.png">

As you will notice in this image, the caret icons in Vertical Nav are placed to the right of the corresponding string, while in the Accordion component they are placed to the left of the corresponding string. This introduces a major inconsistency for us, and for anyone that will ever use both components in their projects (especially if they are placed next to each other like in our case)

Please consider a consistent look.

Thanks,
Lacho | Product Designer VMware vSAN

**Comment by colinreedmiller** [comment]
Needs review re: 
Consistent Navigation AA
https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-consistent-locations.html

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
