### ISSUE TITLE
Datagrid steals focus on programmatic page change

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#4229]
## Describe the bug

When changing the page number via the input `[clrDgPage]="pageNumber"` the Datagrid focuses itself ([GoToCode](https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid.ts#L254)). That is stealing the focus of other elements on the page, like in our case an important, autofocused input field.

## Expected behavior

A programmatically set page should not affect the focus state on the page.

## Versions

**App**

* Angular: 8.2.14
* Clarity: 2.3.4

**Device:**

* Browser: Chrome

**Comment by hippee-lee** [comment]
This behavior meets an accessability requirement for pagination in the datagrid. (https://github.com/vmware/clarity/issues/3370)

This is not something I think we can change. 

Before I close this can you create a simple stackblitz that demonstrates your use case so we can take it into consideration and get some feedback from our accessibility team?

**Comment by twittwer** [comment]
If I get it right your accessibility concern is, to focus the table after a page change is caused by an interaction with the pagination component.
My use case is a programmatic page change, so it would be nice for example, if the focus is only triggered by a button click in the pagination component.

**Comment by gnomeontherun** [comment]
It would be useful for us to have a more specific use case and demonstration to review. Right now, while focus is stolen you can also steal it back as a workaround. Its not ideal, but also the general use case for accessibility should be preserved. Its also likely that if you programmatically change the page that focus should move in other cases, so we really need to know what the use case is to understand better.
