### ISSUE TITLE
Need icon 'fa-university' in clr-icons

### ISSUE THREAD

**Issue by clementcur** [vmware/clarity#423]
http://fontawesome.io/icon/university/

We're using this icon in the context of a budget value. Let me know if it can make its way to the next release.

**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Environment details
* **Clarity version:** 
0.8.4

**Comment by lil-kim** [comment]
[bank_icons_svg.zip](https://github.com/vmware/clarity/files/743438/bank_icons_svg.zip)
@Shijir I've attached the icon and its variants. I named it "bank" rather than "university" because of CCureau's use case.

**Comment by Shijir** [comment]
@lil-kim Awesome. Thank you!
