### ISSUE TITLE
ng build --prod broken in v3.0.0-next.7

### ISSUE THREAD

**Issue by KANekT** [vmware/clarity#4230]
## Describe the bug

ERROR in node_modules/@clr/angular/clr-angular.d.ts.ClrDatagridFilter.html(5,15): Property 'datagridFilterAriaLabel' does not exist on type 'Readonly<ClrCommonStrings>'.

## How to reproduce

ng build --prod

## Versions

**App**

* Angular: [^8.2.5]
* Clarity: [v3.0.0-next.7]

**Comment by Shijir** [comment]
Please make sure your @clr/core is updated to v3.0.0-next.7 as well.

**Comment by KANekT** [comment]
![CD3D86B4-6653-4AF4-BEA9-10F1063F63B1](https://user-images.githubusercontent.com/580273/73083503-5baccd00-3edc-11ea-9112-56518e1df859.jpeg)

Thanks, I not see version 7

And npm not update to 7:(
