### ISSUE TITLE
Add API/Configuration for disabling direct page access in datagrid pagination

### ISSUE THREAD

**Issue by martovmarinov** [vmware/clarity#4233]
## Summary

* What is the change?
We have a case where the pagination between the pages is happening based on DB-like cursor indexes. Thus jumping to a random page is not possible. It is only possible to go First/Previous/Next/Last pages.
Because of this we need the ability to not have input for direct page number access in the datagrid pagination control.

* Why should it go in Clarity?
Current workaround for this is two step process which is not maintainable and not looking good one.

* Does this change impact existing behaviors? If so how?
No.

* If this change introduces a new behavior, is this behavior accessible?
Yes.

## Use case
Server side datagrid with DB cursor-based pagination

## Examples
N/A

## Workarounds
Current workaround for this is two step process:
- disable the input
- style with ::ng-deep to have the input lookes like a label

**Comment by Jinnie** [comment]
Should be an easy one. 
I verified the case with @martovmarinov - seems legit to me.
We _may_ want to discuss additional corner-cases together with this. An example is when the Total is unknown, which I've observed in scenarios where access rights are applied after data retrieval, and this makes the total calculation either inaccurate or too expensive.

**Comment by milesich** [comment]
I have a case where I don't know the Total so the total is calculated like there is always a one more page. So on page 1 it shows there are 2 pages and on page 2 there are 3 pages.

**Comment by Jinnie** [comment]
V2 also updated with commit a13af0c2b1bfbe2b7d850537954b4da4e2ca06e8
