### ISSUE TITLE
Wizard Navigation : Not able to load error related CSS class 

### ISSUE THREAD

**Issue by akate1** [vmware/clarity#4238]
**Issue:**
 The CSS class '**clr-wizard .clr-wizard-stepnav-item.error'**  is not getting loaded.

**Versions:**
clr/icons": "2.3.6" 
clr/ui": "2.3.6"

**Screenshot:**
![image](https://user-images.githubusercontent.com/51195071/73252924-8b601b80-41e1-11ea-9465-09ebdfaf59ab.png)

**CSS File :**

}
.clr-wizard .clr-wizard-stepnav-item {
 display:block;
 box-shadow:.166667rem 0 0 #ededed inset;
 margin:0 0 -1px;
 padding:.25rem 0;
 padding-left:.333333rem;
 color:#303030;
 font-weight:400
}
.clr-wizard .clr-wizard-stepnav-item.active {
 color:#000;
 font-weight:500
}
.clr-wizard .clr-wizard-stepnav-item.active .clr-wizard-stepnav-link {
 background-color:#d8e3e9;
 border-radius:.125rem 0 0 .125rem
}
.clr-wizard .clr-wizard-stepnav-item.complete {
 box-shadow:.166667rem 0 0 #61b715 inset;
 transition:box-shadow .2s ease-in
}
.clr-wizard .clr-wizard-stepnav-item.no-click button {
 pointer-events:none
}
.clr-wizard .clr-wizard-stepnav-link {
 width:100%;
 display:inline-block;
 color:inherit;
 line-height:.666667rem;
 padding:.416667rem .125rem .416667rem .416667rem;
 font-size:.583333rem;
 font-weight:inherit;
 letter-spacing:normal;
 text-align:left;
 text-transform:none;
 margin:0
}
.clr-wizard .clr-wizard-stepnav-link::before {
 content:counter(a);
 counter-increment:a;
 padding-right:.2916666667rem;
 min-width:.625rem
}
.clr-wizard .clr-wizard-title {
 color:#000;
 margin-top:0;
 padding:1rem .5rem 1rem 1rem;
 -webkit-flex:0 0 auto;
 flex:0 0 auto
}

**Comment by gnomeontherun** [comment]
Can you please help us with an isolated reproduction from Stackblitz? https://stackblitz.com/@clr-team has starters for you to work from.

**Comment by gnomeontherun** [comment]
Hi @akate1, due to inactivity on this issue we're going to close it. If you are able to provide a working reproduction of the problem, please update this issue and we can evaluate it again.
