### ISSUE TITLE
[Datagrid] [IE11] Expanded filter on datagrid column not properly rendered

### ISSUE THREAD

**Issue by Gesh4o** [vmware/clarity#4239]
## Describe the bug

Apply filter on a datagrid column when expanded is not properly visualized in IE11 when having multi-selection:
![Screen Shot 2020-01-28 at 1 01 33 PM](https://user-images.githubusercontent.com/13942085/73258458-64e4b500-41ce-11ea-9f6c-df9dc6686d11.png)

## How to reproduce
Stackblitz: https://clarity-light-theme-v1-0-hjxrrv.stackblitz.io

1.   Open the project locally (stackblitz won't open on IE11)
2.  Set screen width around 500px
3.  See error
It may look something like this:

![Screen Shot 2020-01-28 at 1 25 23 PM](https://user-images.githubusercontent.com/13942085/73260070-d1ad7e80-41d1-11ea-9cd2-4739e2328ea8.png)

## Expected behavior
![Screen Shot 2020-01-28 at 1 27 17 PM](https://user-images.githubusercontent.com/13942085/73260120-ebe75c80-41d1-11ea-8596-eceb2defea0f.png)

NOTE: The above pictures are from chrome but simulate the effect which is replicated on windows.

## Versions

**App**
* Clarity: v1

**Device:**

* Type: PC
* OS: Windows
* Browser: IE
* Version: 11

## Additional notes

Workaround: put _z-index: 500_ on ".datagrid-filter" div.

**Comment by hippee-lee** [comment]
This issue has been fixed in v2 but it was a breaking change and cannot be backported to v1. The suggested workaround is to upgrade to v2.

https://stackblitz.com/edit/clarity-light-theme-v1-0-dfuqts
