### ISSUE TITLE
I am using clarity v1 for wizard .The event added in next are not there when navigating through left menu items #1

### ISSUE THREAD

**Issue by meghachandel** [vmware/clarity#4242]

**Comment by hippee-lee** [comment]
Hi @meghachandel.

We provide an [issue template ](https://github.com/vmware/clarity/blob/master/.github/ISSUE_TEMPLATE/bug-report.md)designed to help isolate, triage and investigate issues. Please use it and provide a simple stackblitz reproduction that helps us understand a working re-production of the reported issue. 

Without the[ issue template ](https://github.com/vmware/clarity/blob/master/.github/ISSUE_TEMPLATE/bug-report.md)details and the stackblitz accurately reproducing the issue you have experienced makes it very difficult to focus on the correct area for the investigation. 

### Please update the issue with 
1. the details requested in the[ issue template ](https://github.com/vmware/clarity/blob/master/.github/ISSUE_TEMPLATE/bug-report.md)
2. a working stackblitz that demonstrates the issue as described

**Comment by gnomeontherun** [comment]
Closing due to no reproduction, please open a new issue with a reproduction and details if this issue still exists.
