### ISSUE TITLE
Fresh Angular 8 install, fresh Clarity install -- Cannot find module '@clr/core/common'

### ISSUE THREAD

**Issue by danrald** [vmware/clarity#4244]
Read the documentation for Clarity V3, 3.0.0-next.7. Did the angular, icons, ui install per docs, https://clarity.design/documentation/get-started 
I do npm start and get the following error:

ERROR in ./node_modules/@clr/angular/fesm2015/clr-angular.js
Module not found: Error: Can't resolve '@clr/core/common' in 'C:\development\Dashboard\ntcDashboard\node_modules\@clr\angular\fesm2015'
i ｢wdm｣: Failed to compile.
    
    ERROR in node_modules/@clr/angular/utils/i18n/common-strings.service.d.ts(1,46): error TS2307: Cannot find module '@clr/core/common'.
    node_modules/@clr/angular/utils/i18n/index.d.ts(1,34): error TS2307: Cannot find module '@clr/core'.

Don't understand what to do now.

**Comment by danrald** [comment]
Come on guys! The documention needs to state that you need to install @clr/core@next
Furthermore, the getting started guide should not mix Option1/2 with steps. If you need help let me know.

**Comment by hippee-lee** [comment]
Hi @danrald,

Thanks for the feedback. We are a small team and the docs are a work in progress, especially wrt core.Pull requests are always welcome. 
 
Also, there are some women engineers on the team so please be mindful of your language. 

I've marked this as something to address in the backlog.

**Comment by danrald** [comment]
Thanks @hippee-lee!
Understandable. Since I have gottne it up and running I've been about to do copious amount of work/design. Good stuff, works as easy as I was told. 

I'll watch my language in the future, thanks!

**Comment by luis-cortina** [comment]
I'm having the same issue with clr 3 and angular 9, how did you fix it?

**Comment by gnomeontherun** [comment]
@luis-cortina Did you make sure you have `@clr/core@3` installed? If you didn't update using `ng update @clr/angular` you might have missed the automatic migration to install this for you.

**Comment by luis-cortina** [comment]
@gnomeontherun that did it...
