### ISSUE TITLE
The left menu of the wizard does not have control over the next button event handler 

### ISSUE THREAD

**Issue by meghachandel** [vmware/clarity#4246]
The left menu of the wizard does not have control over the next button event handler because of which if user navigates the screen though left menu he can enter any data even when the data shows error message when he navigates though next button in the wizard.

Is there any API which can be used here?

**Comment by mathisscott** [comment]
I'm not clear on the use case. Do you want to prevent users from using the wizard stepnav?

**Comment by meghachandel** [comment]
My wizard's next button has a handler for validation, and on successful validation user is allowed to go to the next page. 

Assume, the wizard has 3 pages.
1. Pg.1 takes an input and validate that when 'Next' is clicked. On successful validation user is landed to Pg.2. 
2. Pg.2 doesn't have any validation, as inputs here are optional and needn't be validated. 
3. Pg.3 is 'Summary' or 'Ready to Complete' screen, which just dumps the input user has provided in previous pages. The page also has a 'Commit' button that makes a 'POST' call to the server.

== The Flow ==
1. User opens wizard, and provide valid input on Pg.1, and click 'Next'
2. On Pg.2, user clicks 'Next'. (With or without input, doesn't matter).
3. User lands on 'Summary' page (Pg.3) . Till now everything is fine, no breakages.
4. On Pg.3 user thought of changing the input provided in Pg.1, so she uses wizard-nav of Pg.1 and lands there, changes input of Pg.1 by providing a wrong value, clicks the 'Summary' page's wizard-nav
and comes to Pg.3. [This means the validation check written for Pg.1 is missed], and also the summary page is showing the old data as it is also not re-evaluated. User clicks on 'Commit' and things go wrong as back-end throws error.

Did you now get what is the problem, the 4th point states that. I'd need a mechanism: 

That will re-evaluate the next handler of a page if something is changed on that, and user didn't use 'Next' button.
or
That will freeze wizard-navs of subsequent pages if something is changed on a page, and page has a next handler.

Thanks!
