### ISSUE TITLE
Datagrid: Use of "last" with conditional footer causes ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by BigBadaboom** [vmware/clarity#4258]
## Describe the bug

I have a list of users where the last entry is styled a little differently from the others.

    <clr-dg-row *clrDgItems="let user of users; last as isLast" [clrDgItem]="user">
        <clr-dg-cell>{{user.id}}</clr-dg-cell>
        <clr-dg-cell><hello [name]="isLast ? 'Last':'Not last'"></hello></clr-dg-cell>
    </clr-dg-row>

    <clr-dg-footer>
      <clr-dg-pagination #pagination [clrDgPageSize]="3">
        <clr-dg-page-size [clrPageSizeOptions]="[3,10]">Users per page</clr-dg-page-size>
        {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
        of {{pagination.totalItems}} users
      </clr-dg-pagination>
  </clr-dg-footer>

This works fine.  However I don't like displaying the pagination bar when there are zero entries.  I think it is weird to display "1 -3 of 0 users".

However if I add an `*ngIf` to the footer to hide it, I get the dreaded ExpressionChangedAfterItHasBeenCheckedError.

    <clr-dg-footer *ngIf="users.length > 0">
    ...
    </clr-dg-footer>

See: https://stackblitz.com/edit/angular-sccyse

It doesn't matter whether length is 0, or not. Just adding it causes the error.

```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'name: Not last'. Current value: 'name: Last'.
    at viewDebugError (errors.ts:37)
    at expressionChangedAfterItHasBeenCheckedError (errors.ts:23)
    at checkBindingNoChanges (util.ts:103)
    at checkNoChangesNodeInline (view.ts:473)
    at checkNoChangesNode (view.ts:461)
    at debugCheckNoChangesNode (services.ts:466)
    at debugCheckDirectivesFn (services.ts:394)
    at Object.eval [as updateDirectives] (VM11555 AppComponent.ngfactory.js:45)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:386)
    at checkNoChangesView (view.ts:341)
```

- Avoiding the use of `last` gets rid of the error.  Other keywords, such as `odd` work fine.
- Removing the `*ngIf` from `<clr-dg-footer>` also prevents the error.

A workaround I found is to use `[hidden]="filteredCardholders.length === 0"` instead. But `*ngIf` should ought to work, shouldn't it?

## Expected behavior

No error :)

## Versions

**App**

* Angular: 8.2.14
* Clarity: 3.2.6

**Device:**

* Type: Desktop
* OS: Windows 10
* Browser Chrome
* Version [79.0.3945.130

**Comment by Shijir** [comment]
We don't support the exported values of `NgForOf` in `ClrDgItems`. What you can do is that you can index your items and easily determine the one that's at the last. Please take a look:
 
https://stackblitz.com/edit/angular-indexed-items

**Comment by BigBadaboom** [comment]
Those values are available to access. So they work in that way.  Do you mean that you don't guarantee that they will work?

**Comment by gnomeontherun** [comment]
This is really a rendering lifecycle issue, where the ngIf throws the rendering out of sync slightly and then we get these kinds of errors. 

It seems like what you really want to do is to put an NgIf on the internal content instead of the whole footer. This will display `1-3 of 5 users` when there are users, but just `0 users` when there are none.

```
<clr-dg-footer>
      <clr-dg-pagination #pagination [clrDgPageSize]="3">
        <clr-dg-page-size [clrPageSizeOptions]="[3,10]">Users per page</clr-dg-page-size>
<ng-container *ngIf="users.length > 0">
        {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
        of </ng-container>
{{pagination.totalItems}} users
      </clr-dg-pagination>
  </clr-dg-footer>
```

This would be my recommendation, it avoids the Expression Changed error and is slightly more performant because it doesn't rerender the footer, just the text.

I'm going to close this as resolved by this particular solution.

**Comment by BigBadaboom** [comment]
Thanks.  That's a reasonable solution also.  Our design choice was to not show any footer when the datagrid was empty. Which is why we were hiding the entire footer.
