### ISSUE TITLE
Icon 'tag' does not paint with the CSS font color

### ISSUE THREAD

**Issue by clementcur** [vmware/clarity#426]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
the code below should paint the 'tag' clarity-icon in white.

### Actual behavior
the code below paints the 'tag' clarity-icon in black.

### Reproduction of behavior
HTML:
`
<clr-icon shape='tag' class='my-icon'></clr-icon>
`

CSS:
`
.my-icon{
  color: #fff
}
`

See screenshot attached:
![screen shot 2017-01-27 at 3 17 53 pm](https://cloud.githubusercontent.com/assets/6166832/22391194/b0c1263c-e4a4-11e6-9345-3cc9fb29ff01.png)

### Environment details

* **Clarity version:** 
0.8.4

**Comment by Shijir** [comment]
@clementcur, thanks for informing us about this bug. Some icons have `fill` attribute that's preventing the color style from taking effect.

**Comment by mathisscott** [comment]
SVG uses fill, not color. 

That said, we can make the default 'fill: currentColor' and that should do what you want. 

As a workaround until then please use 'fill: #fff' instead of color. Or in addition to it if you want.

**Comment by mathisscott** [comment]
Since this is working as designed, I removed the bug designation. It's more of an enhancement.

**Comment by clementcur** [comment]
@mathisscott thx for the tip.
I tried out the fill attribute, but it still does not apply the fill color to that svg icon. Though it's working for some other icons, e.g. 'dashboard'.

So, it looks like the 'tag' icon fill value is ignored and always set to '#231f20'.

**Comment by lil-kim** [comment]
[tags_icons.zip](https://github.com/vmware/clarity/files/743473/tags_icons.zip)
hi @Shijir I found that my original .svg files were using #231f20 instead of #000000. So you can blame this one on me. 😞  I'm attaching the corrected files with the color set to #000000, in case that helps.

**Comment by lil-kim** [comment]
[tag_single_icon.zip](https://github.com/vmware/clarity/files/743489/tag_single_icon.zip)
This problem was found in the singular tag icon as well. Corrected svg files attached. Thanks Shijir!

**Comment by Shijir** [comment]
@lil-kim it's okay. I have now unit tests that catch these kinds of overlooked parts. 😎

**Comment by clementcur** [comment]
Thx for the prompt fix!
