### ISSUE TITLE
Form error and icon error use different red

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#4260]
The error icon in forms is slightly different red than the error icon in general. The form use $clr-forms-invalid-color (#C72100) while the general error icon use $clr-icon-color-danger (#E02200)

Same for warning, the icon (#C27B00) and badges (#FFDA0A) are different yellow.

Looking at the https://v2.clarity.design/color page the only red there mentioned is the old form error red in the deprecated forms (clarity 0.11). i.e. #C92100. Seems this doc page is out of date.

**Comment by gnomeontherun** [comment]
Clarity Core should resolves this issue, so the recommendation is to adopt the Clarity Core version for this capability or override it if you need in your use case.

In an effort to clean up our backlog and focus our attention, I’m going to close this as resolved by Clarity Core. Please follow our development and releases to keep up with improvements!
