### ISSUE TITLE
ng add @clr/angular fails

### ISSUE THREAD

**Issue by MasashiTeruya** [vmware/clarity#4264]
## Describe the bug

ng add @clr/angular fails with an error 
> No matching version found for @clr/ui@2.3.7.

## How to reproduce

1. Install Angular CLI 8.3.25
2. ng new my-project-name
3. ng add @clr/angular

## Versions

**App**

* Angular: 8.2.14
* Node: 12.13.0
* Clarity: 2.3.7

## Additional notes
Log shows 

> 46 error code ETARGET
> 47 error notarget No matching version found for @clr/ui@2.3.7.
> 48 error notarget In most cases you or one of your dependencies are requesting
> 48 error notarget a package version that doesn't exist.
> 48 error notarget
> 48 error notarget It was specified as a dependency of 'my-project-name'
> 49 verbose exit [ 1, true ]

I do not see the latest version of @clr/ui published on npm.
For @clr/angular, 2.3.7 is on the list https://www.npmjs.com/package/@clr/angular?activeTab=versions
For @clr/ui, 2.3.7 is missing at https://www.npmjs.com/package/@clr/ui?activeTab=versions

**Comment by jroliveira** [comment]
I rollback to the previous version and it worked.
```bash
$ ng add @clr/angular@2.3.6
Package has unmet peer dependencies. Adding the package may not succeed.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
UPDATE src/app/app.module.ts (587 bytes)
- Installing packages...
√ Packages installed successfully.
```

**Comment by bdryanovski** [comment]
It seems that the `@clr/ui@2.3.7` is not published in the registry. I gonna check to see what could be the reason for that.

**Comment by hippee-lee** [comment]
The script ran yesterday b/c I had to put my OTP in so I'm not sure what happened here.
I manually published `@clr/uiv2.3.7` again: https://www.npmjs.com/package/@clr/ui/v/2.3.7

Please update this issue if you still experience the issue.

**Comment by akqira** [comment]
Hi, 
Having the same issue as you can see on attached picture. It concerns now  **@clr/icons@next**
<img width="573" alt="Capture d’écran 2020-03-04 à 7 56 52 PM" src="https://user-images.githubusercontent.com/28217846/75913015-6bf88600-5e52-11ea-9d57-db78cef226b4.png">

Regards

**Comment by gnomeontherun** [comment]
@akqira what command did you run? Now that v3 is out you just run `ng add @clr/angular` without a version tag.

**Comment by akqira** [comment]
Hi @gnomeontherun,
I just followed the Get Started page instructions and as i already have an existing angular App i used the command **ng add @clr/angular**
I'm running under macOS 10.15.3
npm --version -----> 6.3.14
If you need any more information just ask me :)
Thank you

**Comment by gnomeontherun** [comment]
@akqira Please open a new issue with your details so we can track it. Since its an existing application, I need to understand what version of Angular you are using.
