### ISSUE TITLE
Drag and drop on touch screens

### ISSUE THREAD

**Issue by skipgeldens** [vmware/clarity#4269]
## Summary

_Summary the request and address the questions as appropriate._

* What is the change?

The `clrDraggable` functionality currently starts the drag action directly. This is not very intuitive on touch devices, especially as we use dnd in a tree view (which is scrollable). On touch the drag and drop action should first wait for a user to hold an item for an x amount of time. On normal mouse-based interaction the dnd action could still happen directly. 

For as far as I can see touch events can easily be captured like:
*touchstart*
*touchmove*
*touchend*

* Why should it go in Clarity?

To support touch-based devices in a better way.

* Does this change impact existing behaviors? If so how?

No, because normal dnd could / should still happen instantly, without holding.

* If this change introduces a new behavior, is this behavior accessible?
...

## Use case

We have an application where we rely heavily on drag and drop (with the built in directives of Clarity). We know that 50% of our users will use the app on a touch device, and the current implementation of dnd interferes with what they know and like from interacting with these touch devices. 

## Examples

https://patrickhlauke.github.io/touch/

## Workarounds

Implementing your own drag-and-drop system, which is not ideal.

**Comment by Shijir** [comment]
Hi @skipgeldens , thanks for filing this issue. This is a known issue for me. In fact, I have started working to solve this issue. As you suggested, my plan is to offer an input property that defines the sensitivity/hold period of drag start. So keep an eye out for PRs for this issue :)

**Comment by skipgeldens** [comment]
Hi @Shijir , has there been any progress to this issue? We really like the drag and drop implementation that is currently in Clarity, but fixing this issue would make it just perfect!

**Comment by Shijir** [comment]
@skipgeldens I got back to this issue recently and actively working on it now.
