### ISSUE TITLE
clrExpandTrigger error. Please include either "BrowserAnimationsModule" after udpating to Angular 9

### ISSUE THREAD

**Issue by MartinWelcker** [vmware/clarity#4270]
## Describe the bug

After updating my angular application from version 8 to 9 im getting the following error on modules where the _ClrStackView_ is used:
`
ERROR Error: "Found the synthetic property @clrExpandTrigger. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application."
`

This occurs though I included the _BrowserAnimationsModule_ inside _the app.module.ts_. I tried deleting _node_modules_ and npm cache, but both did not help.

## How to reproduce
1. Use nested StackView inside Component
2. Import  _BrowserAnimationsModule_ inside _the app.module.ts_

## Expected behavior

The StackView should work, like with the previous angular version.

## Versions

**App**

* Angular: 9.0.1
* Clarity: 2.3.5

**Comment by Shijir** [comment]
Hmm I remember fixing this issue here in our effort of upgrading to Angular 9: https://github.com/vmware/clarity/pull/4232/files#diff-62b84aa46d276897b3ccabadeb217628R44

But this fix is only applicable to Clarity v3. I think we could/should fix this specific issue in Clarity v2 as well. But even after that, I believe Clarity v2 doesn't work quite well with Angular 9. 
@gnomeontherun could elaborate more on that probably.

**Comment by MartinWelcker** [comment]
> 
> 
> Hmm I remember fixing this issue here in our effort of upgrading to Angular 9: https://github.com/vmware/clarity/pull/4232/files#diff-62b84aa46d276897b3ccabadeb217628R44
> 
> But this fix is only applicable to Clarity v3. I think we could/should fix this specific issue in Clarity v2 as well. But even after that, I believe Clarity v2 doesn't work quite well with Angular 9.
> @gnomeontherun could elaborate more on that probably.

As you recommended was able to solve the error, simply updating the clarity version.
```
    "@clr/angular": "3.0.0-next.8",
    "@clr/icons": "3.0.0-next.8",
    "@clr/ui": "3.0.0-next.8",
    "@clr/core": "3.0.0-next.8",
```

**Comment by gnomeontherun** [comment]
Thanks, Clarity v3 and Angular v9 are the only versions compatible together, so updating Clarity from v2 to v3 requires updating to Angular v9.

Closing as resolved.
