### ISSUE TITLE
datePicker on modal popup behind it

### ISSUE THREAD

**Issue by balandinve** [vmware/clarity#4272]
## Modal with datePicker

I'm place datepicker on a modal. It showed behind of modal.

## How to reproduce

Modal is already open. Tap datepicker and popup with dates showed behind of modal.
https://stackblitz.com/edit/clarity-light-theme-v3-next-rrieqj

## Versions

**App**

* Angular: 9.0
* Clarity: 3.0-next8

**Comment by gnomeontherun** [comment]
This is related to https://github.com/vmware/clarity/issues/4213, same fix should address both of these.

**Comment by plaisted** [comment]
Still present in RC1.

Workaround/hack (saas)
```
::ng-deep .clr-popover-content.datepicker
  z-index: 9000
```

**Comment by bdryanovski** [comment]
This issue is resolved by this PR #4693
