### ISSUE TITLE
core: set global namespace version track

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4278]
## Summary

Add a global namespace to append versions to so we can easily track Core versions being used for issue reports and easily detect if version conflicts when dependencies are not deduped.
Only append when in running in the browser. When a version is loaded add to the list.

```javascript
// something like this, could be a func to get more details, need investigation and review for options
window.CDS = {
  versions: ['3.0.0'] 
}
```

**Comment by mathisscott** [comment]
We will want to do some kind of workaround for SSR to make sure we don't break vuepress and ngUniversal, etc.

I think it's fine that we just don't set the version in those environments. It's a nice-to-have and we shouldn't write code that relies on versions, IMO.

**Comment by coryrylan** [comment]
closed in https://github.com/vmware/clarity/pull/4306
