### ISSUE TITLE
core: SSR bug Vuepress

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4279]
## Describe the bug

Currently SSR is breaking for Vuepress applications due to a window reference. This is likely an issue for any SSR site.

**Comment by mathisscott** [comment]
This would constitute a blocker for the website work that is currently in progress...

**Comment by gnomeontherun** [comment]
This is also blocked by SSR issues with lit-html and lit-element, some of which we can attempt to fix via PRs.

**Comment by coryrylan** [comment]
Closing for now with has workaround. Will track lit-html progress on SSR streaming in node
