### ISSUE TITLE
Treeview with clrRecursiveFor gives Error: Multiple components match node with tagname clr-tree-node in Angular 9

### ISSUE THREAD

**Issue by ygoron** [vmware/clarity#4282]
## Describe the bug

Treeview with clrRecursiveFor gives "Error: Multiple components match node with tagname clr-tree-node" in Angular 9  Also shows "ERROR TypeError: Cannot read property 'context' of undefined"

## How to reproduce
The "Recursive Tree" sample doc  from Clarity reproduces this error in Angular 9. Works in Angular 8

Steps to reproduce the behaviour:

<clr-tree>
  <clr-tree-node *clrRecursiveFor="let file of root; getChildren: getChildren"
                 [(clrSelected)]="file.selected">
      {{file.name}}
  </clr-tree-node>
</clr-tree>

root = [
    {
        name: "src",
        selected: ClrSelectedState.INDETERMINATE,
        files: [
            {
                name: "app",
                selected: ClrSelectedState.INDETERMINATE,
                files: [
                    {
                        name: "app.component.html",
                        selected: ClrSelectedState.UNSELECTED
                    },
                    {
                        name: "app.component.ts",
                        selected: ClrSelectedState.UNSELECTED
                    },
                    {
                        name: "app.module.ts",
                        selected: ClrSelectedState.SELECTED
                    },
                    {
                        name: "app.routing.ts",
                        selected: ClrSelectedState.UNSELECTED
                    }
                ]
            },
            {
                name: "environments",
                selected: ClrSelectedState.SELECTED,
                files: [
                    {
                        name: "environments.prod.ts",
                        selected: ClrSelectedState.SELECTED
                    },
                    {
                        name: "environment.ts",
                        selected: ClrSelectedState.SELECTED
                    }
                ]
            },
            {
                name: "index.html",
                selected: ClrSelectedState.UNSELECTED,
            },
            {
                name: "main.ts",
                selected: ClrSelectedState.UNSELECTED,
            }
        ]
    },
    {
        name: "package.json",
        selected: ClrSelectedState.UNSELECTED
    },
    {
        name: "tsconfig.json",
        selected: ClrSelectedState.UNSELECTED
    }
  ]; 
  getChildren = (folder: any) => folder.files;
## Expected behavior

_A clear and concise description of what you expected to happen._

Should show a tree instead of crash

## Versions

**App**

* Angular: 9.0.1
* Node: 12.16.0
* Clarity:v2

**Device:**
Chrome
* Type: MacPro
* OS: Catalina
* Browser chrome
* Version [e.g. 22]

## Additional notes

_Add any other no
![Screen Shot 2020-02-15 at 1 58 24 PM](https://user-images.githubusercontent.com/4013029/74593639-3f8fdd80-4ffb-11ea-8b01-b8e538aee314.png)
tes about the problem here._

**Comment by Shijir** [comment]
@ygoron have you tested it with Clarity v3? https://clarity.design/news/3.0.0-next.8

**Comment by ygoron** [comment]
No - I will give it a try.

Thanks,
Yuri

**Comment by gnomeontherun** [comment]
Clarity v2 and Angular 9 are not compatible because of changes in Angular and TypeScript. Please update as this issue was fixed in #4232 and is in the latest v3 release.

Closing as resolved, unless you have a specific demo of the issue persisting with Clarity 3 and Angular 9.
