### ISSUE TITLE
[doc, scss, datagrid, best practice, integratability with other css frameworks] css integratability with other global (css) frameworks

### ISSUE THREAD

**Issue by geyuqiu** [vmware/clarity#4297]
## Summary
Hi, I am basically a new comer. I checkouted the tests in github. And I really liked them comparing what I see in other material design libraries e.g. the default Angular material design library :) 

But what I am missing currently is:
Documentation about how clarity css work with other global (css) frameworks.
Question: what can I do differently, more effortlessly in combination with frameworks like jhipster (Angular) that utilize global css classes e.g. for input that messes up css-collectors provided by clarity-ui.

- I tried to import clarity-css files locally separately inside a component (e.g. with `encapsulation.ShadowDom` enabled, which is also a bad work around that requires resetting encapsulation in component tests). Basic css styles are working, however, `font-size `and `line-height ` etc. are not yet optimal comparing with e.g. [this](https://stackblitz.com/edit/clarity-datagrid?file=index.html)

## Use case

integrate clarity with jhipster version 6.6

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

what I've done so far are: 

1. all steps in [Getting started](https://v2.clarity.design/get-started)
2. except Step 3: Adding scripts and styles (globally)
because it messes up jhipster global css-classes etc. currently in vendor.scss
3. search for all classes that could be effecting `.datagrid` and `.clr-icon`, and copy them to `vendor.scss`, if some css looks wrong, reproduce a basic example similarly via [above link in stackblitz](https://stackblitz.com/edit/clarity-datagrid?file=index.html), which looked like a work around that I had in previous project with jHipster when loading material-icons in offline.
4. as complete explaination please look at following example

## Example

1. enable sorting and filtering in data grid colums

 `<clr-dg-row *clrDgItems="let launch of response?.launches" [clrDgItem]="launch">`

2. datagrid-string-filter.ts has some styles that I have not imported yet:
![image](https://user-images.githubusercontent.com/4540661/74836800-69f5d980-5320-11ea-91e1-36978faeb7c3.png)
3. add them manually
4. how can do this all in a more sufficient and overall more convenient way ?

answer in https://github.com/vmware/clarity/issues/756 did not solve my problem

**Comment by hippee-lee** [comment]
There seem to be two aspects to this issue:

### Creating and building the Angular app (for jHipster)
1. How does jHipster create angular applications? Does it use the Angualr CLI to generate the application shell and build and serve the application?Can it use the `ng add` command to add in Clarity?  The best practice way to include exteranl stylesheets is with the angular.json manifest that describes the building/serving/testing etc of the application. E.g - https://stackblitz.com/edit/clarity-light-theme-v2?file=angular.json

### Mixing Clarity CSS w/ other frameworks
In general we do not recomend that Clarity be used with other frameworks (e.g Bootstrap). WHile we have css namspacing ewith the `clr-` prefix mixing the css from two frameworks is bound to result in conflicts that neither framework could anticipate or handle. This means that any issues need to be handled by the application.

**Comment by geyuqiu** [comment]
@hippee-lee thanks for the answer, so I am closing this. JHipster diverted from angular cli, because there were too many bugs ? But there is a feature request to come back to it, because it improved in the last years.

**Comment by hippee-lee** [comment]
Thanks for the update. le me know if you come back to this and need help.
