### ISSUE TITLE
[filter] clear filter onXClick

### ISSUE THREAD

**Issue by geyuqiu** [vmware/clarity#4299]
## Summary

_Summary the request and address the questions as appropriate._

* What is the change?
clear filter onXClick
* Why should it go in Clarity?
* Does this change impact existing behaviors? If so how?
Currently clicking on X, the filter field will disappear and the filter text/criteria will remain
* If this change introduces a new behavior, is this behavior accessible?

## Use case

Currently, the user has to manually click into the input field and delete the characters that are supposed to be filtered

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_
![image](https://user-images.githubusercontent.com/4540661/74840447-4b471100-5327-11ea-9ac7-962096b9a4e5.png)

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_
partial workaround: clear all filters button

**Comment by mathisscott** [comment]
Any effort towards improving the UX for datagrid filtering should be put towards #1632.

This is very specific and, while applying to your specific case, would cause problems for other apps as it overloads the closing of the existing filter panels.

This overloading would make filtering unusable for users who rely on keyboard navigation.
