### ISSUE TITLE
master branch - `npm run angular:dev:start` fails with ERROR: Task not found: "'core:build:ts"

### ISSUE THREAD

**Issue by srikanthps** [vmware/clarity#4301]
## Describe the bug
Unable to run dev mode of Clarity after checking out master.

Following error is reported.
```
λ npm run angular:dev:start

> @clr/clarity@3.0.0-next.8 angular:dev:start C:\Users\shrees3\Documents\clarity
> npm run core:build:src && ng serve dev


> @clr/clarity@3.0.0-next.8 core:build:src C:\Users\shrees3\Documents\clarity
> npm-run-all core:build:sass:components 'core:build:ts -- --force'

ERROR: Task not found: "'core:build:ts"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @clr/clarity@3.0.0-next.8 core:build:src: `npm-run-all core:build:sass:components 'core:build:ts -- --force'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @clr/clarity@3.0.0-next.8 core:build:src script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shrees3\AppData\Roaming\npm-cache\_logs\2020-02-20T14_17_10_235Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @clr/clarity@3.0.0-next.8 angular:dev:start: `npm run core:build:src && ng serve dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @clr/clarity@3.0.0-next.8 angular:dev:start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shrees3\AppData\Roaming\npm-cache\_logs\2020-02-20T14_17_10_370Z-debug.log
```
## How to reproduce
1. Clone Clarity and checkout `master` branch.
2. Run `npm install`
3. Run `npm run angular:dev:start`

## Expected behavior

Clarity Dev application runs and http://localhost:4200 can be viewed in browsers.

## Versions

**App**

* Angular: 9.0.2
* Node: 10.16.0
* Clarity: "3.0.0-next.8",

**Device:**
Windows Laptop

## Additional notes
None

**Comment by srikanthps** [comment]
I will raise the question on StackOverflow.  I am not sure its a bug, but certainly it does not work on my PC.  I did not have any issues with "v2" branch.

**Comment by gnomeontherun** [comment]
This is a Windows specific issue with the handling of single quotes `'`. We don't actively develop on Windows so don't always catch these things. The quotes probably need to be escaped for Windows, unless you opt to use the Ubuntu shell.
