### ISSUE TITLE
Forms field set

### ISSUE THREAD

**Issue by colinreedmiller** [vmware/clarity#4303]
## Summary

Addition of component to encapsulate form elements into sections

* Sections for forms
* Needed by forms pattern which will specify use of sections
* No impact on existing - new form element
* No behavior is associated with this component - its a container that improves hierarchy

## Use case

Sections in forms reduce cognitive load for users by grouping like elements together. They also provide for improved editing experiences by controlling and limiting focus on a specific area.

## Examples

example: A users name and address are contained in **Profile** and their **Preferences** are located in another section.

## Workarounds

Styling an html fieldset for this purpose.

**Comment by gnomeontherun** [comment]
@colinreedmiller Do we have a design for how the fieldset should appear or is this a placeholder issue for the design? We're assuming its not ready until we have a design.

**Comment by colinreedmiller** [comment]
@gnomeontherun There are some designs in products but we have not finalized which we should use - more of a placeholder until we analyze the design(s) and complete the requirements.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).

**Comment by gnomeontherun** [comment]
Core actually has form groups as well, which might close this request as resolved.

**Comment by colinreedmiller** [comment]
The core form group is different - more than one selection under a single label. This request is for a visual element that divides a form into sections. The html fieldset is equivalent - simply a container for grouping inputs by type, in this case styled for Clarity consistency.

**Comment by colinreedmiller** [comment]
design reference: https://www.figma.com/file/oejFPZmH05Y0A5ycr3zI5q/Forms-fieldset?node-id=0%3A1
