### ISSUE TITLE
Datagrid Batch Action  - checkbox visual issue on Safari

### ISSUE THREAD

**Issue by georgedimmitrov** [vmware/clarity#4307]
## Describe the bug

Sligh visual issue with checkbox on Batch Action datagrid on Safari browser.

## How to reproduce

Problem is reproducible on Clarity's website.
https://v2.clarity.design/datagrid/batch-action 

Steps to reproduce the behaviour:

1.  Go to https://v2.clarity.design/datagrid/batch-action
2.  Scroll down to first example
3.  Click on any checkbox
4.  See problem - white checkbox has a black line going through it
![ClarityBatchDatagridCheckboxIssueSafari](https://user-images.githubusercontent.com/16158865/75154066-84abc200-5715-11ea-9973-4b4f169bc6c3.jpg)

## Expected behaviour

To look the same as in Chrome/Firefox, without a thin line

## Versions

**Device:**

* Type: MacBook
* OS: MacOS
* Browser: Safari
* Version 13.0.3

## Additional notes
On the same version of Safari, the same page has problems loading at all.
![Screenshot 2020-02-24 at 14 17 03](https://user-images.githubusercontent.com/16158865/75153917-339bce00-5715-11ea-941b-9754c83c90c6.jpg)

**Comment by gnomeontherun** [comment]
Yes, something is strange with the way it appears in a datagrid vs normal checkboxes.

**Comment by gnomeontherun** [comment]
This does not appear to be an issue with latest version of Clarity and Safari, closing as resolved and likely something quirky in Safari.
