### ISSUE TITLE
Datagrid selection: Allow footer text to be customizable or change default text

### ISSUE THREAD

**Issue by snnaik** [vmware/clarity#4309]
## Summary

_When using selection in Datagrid, selecting a row shows a disabled checkbox in the footer with the count of rows selected. This text should reflect what the number means. Either change default text to "# selected" or make it customizable_

## Use case

_After this change, making selections in datagrid will reflect more descriptive text in the footer._

## Workarounds

_No. The footer text template is hard-coded to show only the count of selections._

<img width="881" alt="Screen Shot 2020-02-24 at 13 42 39" src="https://user-images.githubusercontent.com/1762022/75193911-0696ed80-570c-11ea-8dfe-00c0d4a72633.png">

**Comment by gnomeontherun** [comment]
This is hard coded and sparse to give enough space for other content that might be in the footer. I'm not sure what it would look like to make this customizable at the moment, but this is a feature request to consider.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
