### ISSUE TITLE
Internationalization class error after upgrade to 3.0next

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#4316]
## Describe the bug
I updated my project to Angualr 9.0.2 and clarity-3.0.0-next.8 

I'm facing the following error.
![image](https://user-images.githubusercontent.com/12848838/75448546-68b45480-5991-11ea-9e9b-e36ea63584a1.png)

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: 9.0.2
* Node: 12.13.0
* Clarity: 3.0.0-next.8 
* typescript: 3.7.5

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Please be sure to also install `@clr/core` to address this problem. The update script for v3 will address this automatically for you in the future.

That should solve it for you, so will close this as resolved.

**Comment by shravansofts** [comment]
Yes, I added it manually.
Hope _ng update_ command will add automatically from next release onwards.
Thanks for the response.

**Comment by gnomeontherun** [comment]
`ng update @clr/angular` for v3 has a schematic which will do this now!
