### ISSUE TITLE
Core breaks in Stackblitz

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4319]
## Describe the bug
In stackblitz it forces all content to compile down to ES5 and there is no way to disable this. Unfortunately this puts the code in a invalid state as TS compiles a spread operation in a Set which breaks the code. https://stackblitz.com/edit/js-hnuwde

Related issue https://stackoverflow.com/questions/41783499/does-typescript-have-an-equivalent-of-es6-sets

```
Error in /turbo_modules/@clr/core@3.0.0/common/utils/global.js (40:74)
(intermediate value).slice is not a function
```

https://github.com/vmware/clarity/blob/master/src/clr-core/common/utils/global.ts#L63

```typescript
// source
function setRunningVersion() {
  window.CDS._version = [...new Set([...window.CDS._version, '@VERSION'])];
  (document.querySelector('body') as HTMLElement).setAttribute('cds-version', window.CDS._version[0]);

  if (window.CDS._version.length > 1) {
    console.warn(
      'Running more than one version of Clarity can cause unexpected issues. Please ensure only one version is loaded.'
    );
  }
}
```

This is what stackblitz force compiles to which causes the exception
```javascript
function setRunningVersion() {
   // broken ES5 slice on Set
    window.CDS._version = new Set(window.CDS._version.concat(['3.0.0'])).slice();
    document.querySelector('body').setAttribute('cds-version', window.CDS._version[0]);
    if (window.CDS._version.length > 1) {
        console.warn('Running more than one version of Clarity can cause unexpected issues. Please ensure only one version is loaded.');
    }
}
```

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
Just leaving a note here that this is a Stackblitz issue. We're going to address it to be supportive of our users. But _c'mon Stackblitz_!
