### ISSUE TITLE
Reset Modals and Wizards

### ISSUE THREAD

**Issue by johnhenriksson** [vmware/clarity#432]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
I think there should be some way of resetting the modals.

### Actual behavior
If I add a form to a Modal and reopen the closed(and finished form) the properties of the form is still there.

### Environment details

* **Angular version:** 2.4.0

* **Clarity version:**  0.8.2

* **OS and version:** macOS Sierra

* **Browser:** [all]

**Comment by mathisscott** [comment]
Hi @johnhenriksson 
@youdz and I had a discussion about this today. We have a couple of restrictions within the old code deep in the guts of Clarity that make this difficult to do atm. But we are looking into it and trying to figure out the best way to do it.

**Comment by mathisscott** [comment]
This was added in #156.

The demo files https://github.com/vmware/clarity/blob/master/src/app/wizard/wizard-reset.demo.ts and https://github.com/vmware/clarity/blob/master/src/app/wizard/wizard-reset.demo.html give an example of how to do it.

This will be documented in the near future. But until we have a chance to get the documentation for the new wizard up the demos are the best reference.
