### ISSUE TITLE
clr-tree-node component breaking after clarity upgrade

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#4320]
## Describe the bug

I'm had upgraded the clarity from 2.x to 3.0 GA.
I'm seeing the following error:
![image](https://user-images.githubusercontent.com/12848838/75570502-48fa5a80-5a7d-11ea-8c8b-e40cd610326a.png)

Is there some breaking changes on this component?

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

* Angular: [e.g. 6]
* Node: [e.g. 8.10.0]
* Clarity: [e.g. 0.12.5]

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Please provide a reproduction of your issue to help us triage and understand what is happening.

**Comment by Shijir** [comment]
@shravansofts you need to wrap your tree with `clr-tree` from now on. This was optional, but it's now mandatory in v3. We need to update our changelog for this breaking change. If you need details, you can take a look at the PR: https://github.com/vmware/clarity/pull/3851.

**Comment by gnomeontherun** [comment]
Closing as resolved.

**Comment by gnomeontherun** [comment]
Reopening, 

@jeeyun Can you add this in during release to the notes?

**Comment by Shijir** [comment]
@gnomeontherun the changelog has been already updated: https://clarity.design/news

**Comment by gnomeontherun** [comment]
Resolved.
