### ISSUE TITLE
overflow:hidden on closing elements

### ISSUE THREAD

**Issue by andrei-gheorghiu** [vmware/clarity#4328]
Today, part of my work involved reviewing Clarity for implementation in some of our products. 

My final vote was against it, but I do appreciate the effort that went into the development of most components. 

While some of the issues might be considered arguable in terms of design/UI quality, there was one in particular which stood out: you're not setting `overflow:hidden` on closing UI elements (i.e: treeview - tested on Chrome, latest, desktop) - which makes a small scrollbar get rendered while the element is closing 

You might think of it as a minor detail. Admittedly, it is. But it's the type of detail which tells: _"nobody in this team assigned with paying attention to details"_ (or if there is, they might have too much on their plate) (not OK for a UI library, IMHO). 
Losing you any users who can't have that label on their products.

I thought it was fair to let you know. Keep up the good work.

**Comment by mathisscott** [comment]
Thanks for the feedback and consideration.
