### ISSUE TITLE
styles of clr-dg-row not working for columns in overflow if width are set individually for each column separately

### ISSUE THREAD

**Issue by geyuqiu** [vmware/clarity#4331]
## How to reproduce

https://stackblitz.com/edit/angular-h5s4tj

it is a follow-up question of https://github.com/vmware/clarity/issues/3827#issuecomment-532727150 ( https://stackblitz.com/edit/angular-dbzvmg)

However it works for https://github.com/vmware/clarity/issues/3827#issuecomment-532250551

btw. the data are not displayed in one line any more, if there are any spaces within the column string. Is there a possibility to not allow the automatic line break

![image](https://user-images.githubusercontent.com/4540661/75725400-b2c66e80-5ce0-11ea-9830-64f2a0b4ba0c.png)

issues that are maybe related: https://github.com/vmware/clarity/issues/3696

## Expected behavior

styles like hover, border etc. should also be working

## Versions

**App**

occurs on different versions, latest being: 

* Angular: 8.2.14
* Node: 10.16 or 12.x
* Clarity: 2.3.7

**Device:**

* OS: Windows
* Browser: chrome, firefox
* Version: 80

## Additional notes

Don't know if this has something to do with overflow-auto.

**Comment by geyuqiu** [comment]
> [style.min-width.px]="85"

is partially working for me in the moment. 

However it will be much better, if  `[style.width.px]="85"` works

**Comment by gnomeontherun** [comment]
Can you clarify which Stackblitz to review here? The first one is running 0.11 and Angular 5.

**Comment by geyuqiu** [comment]
@gnomeontherun  https://stackblitz.com/edit/angular-h5s4tj
I messed up a little bit with the versions Angular and clarity, but it can be reproduced the same way with higher versions
