### ISSUE TITLE
Date picker inside a Wizard doesn't show the calendar popup

### ISSUE THREAD

**Issue by imasm** [vmware/clarity#4338]
## Describe the bug

Date picker inside a Wizard doesn't show the calendar popup.

## How to reproduce

https://clarity-v3-wizard-date-picker.stackblitz.io

Editor:  https://stackblitz.com/edit/clarity-v3-wizard-date-picker

1.  Open the wizard.
2.  Click on calendar icon.
3.  See that nothig happens.
4. Check that, outside the wizard, it works well.

## Expected behavior

Open calendar popup in order to select the date

## Versions

**App**

* Angular: "9.0.4"
* Node: "12.14.1"
* Clarity:  "3.0.0"

**Device:**

* Type: Windows 10
* OS: Win32 x64
* Browser:  chrome, firefox
* Version  Chrome 80.0.3987.132, Firefox 73.0.1

**Comment by hippee-lee** [comment]
This is related to https://github.com/vmware/clarity/issues/4213 and the fix for that should address this as well. 

A workaround for now would be to use: 

```
::ng-deep .clr-popover-content {
    z-index: 2000;
}
```

**Comment by Anuj21** [comment]
> ## Describe the bug
> Date picker inside a Wizard doesn't show the calendar popup.
> 
> ## How to reproduce
> https://clarity-v3-wizard-date-picker.stackblitz.io
> 
> Editor: https://stackblitz.com/edit/clarity-v3-wizard-date-picker
> 
> Steps to reproduce the behavior:
> 
> 1. Open the wizard.
> 2. Click on calendar icon.
> 3. See that nothig happens.
> 4. Check that, outside the wizard, it works well.
> 
> ## Expected behavior
> Open calendar popup in order to select the date
> 
> ## Versions
> **App**
> 
> * Angular: "9.0.4"
> * Node: "12.14.1"
> * Clarity:  "3.0.0"
> 
> **Device:**
> 
> * Type: Windows 10
> * OS: Win32 x64
> * Browser:  chrome, firefox
> * Version  Chrome 80.0.3987.132, Firefox 73.0.1

@hippee-lee : IMHO, The problem is this needs to be done at the root level which will solve the issue for lots of the problem regarding z-index. The variable should be created and refactor everywhere for the z-index as a best practice ex: 

$zindex: (
  modal     : 9000, 
  overlay   : 8000,
  dropdown  : 7000,
  header    : 6000,
  footer    : 5000
);
