### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by nickbewley** [vmware/clarity#4340]
## Summary

Notifications is a key feature area for many applications and services. This ticket represents three components of an overall notifications strategy: toasts, snackbars, and panels.

* What is the change? This ticket represents contributing notification components — specifically a snackbar, toast, and panel — to Clarity.
* Why should it go in Clarity? Notifications is a common feature area leveraged across applications. 
* Does this change impact existing behaviors? If so how? Yes, application owners will now have more ways to distribute notifications to their users.
* If this change introduces a new behavior, is this behavior accessible? Yes

## Use case

• System needs to inform user about upcoming maintenance.
• System needs to inform user about messages from another user.
• System needs to provide feedback about an action.
• User needs to manage their action items. 

## Examples

• Toasts:
![toast](https://user-images.githubusercontent.com/5789940/75917644-2a92b700-5e0f-11ea-8080-18bbb097197f.png)

• Snackbars:
![snackbar](https://user-images.githubusercontent.com/5789940/75917672-341c1f00-5e0f-11ea-97f3-fd74cc55a73c.png)

• Panel:
![panel](https://user-images.githubusercontent.com/5789940/75917839-81988c00-5e0f-11ea-9379-b53905e49d62.png)

## API

None

## Implementation plan

None

## Conclusion

Design and research is complete. See attached tickets for detailed designs.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
