### ISSUE TITLE
ng add @clr/angular not working

### ISSUE THREAD

**Issue by akqira** [vmware/clarity#4341]
## Describe the bug

When running **ng add @clr/angular** in an existing angular app folder the following error is raised
<img width="573" alt="Capture d’écran 2020-03-04 à 7 56 52 PM" src="https://user-images.githubusercontent.com/28217846/75917819-e7f6cc00-5e5a-11ea-9d46-87d48a21a60a.png">

## How to reproduce

On existing angular app built using the following version 

1.  Go to the angular app root folder
2.  run the command **ng add @clr/angular**
3.  See error below
<img width="617" alt="Capture d’écran 2020-03-04 à 9 02 18 PM" src="https://user-images.githubusercontent.com/28217846/75918145-75d2b700-5e5b-11ea-8ef5-9683ff65cf4d.png">

## Expected behavior

Correct installation of all packages needed and a confirmation message of correct installation should be shown

## Versions

**App**

* Angular CLI: 8.2.2
* Node: 10.16.3
* Clarity: v2.3.6 ( i guess because i used the command without specifying the version as described in doc)

**Device:**

* Type: Macbook Pro
* OS: MacOS Catalina 10.15.3
* Browser Chrome
* Version 80.0.3987.122 (x64 official build)

## Additional notes
The angular app used is already built by .net core 3.1 template (using the command line : dotnet new angular)

<img width="512" alt="Capture d’écran 2020-03-04 à 8 59 29 PM" src="https://user-images.githubusercontent.com/28217846/75918027-44f28200-5e5b-11ea-88fe-cb214ced7e08.png">

Content of the log file (last lines)
<img width="1220" alt="Capture d’écran 2020-03-04 à 9 08 37 PM" src="https://user-images.githubusercontent.com/28217846/75918693-7e77bd00-5e5c-11ea-9203-91010e0f652c.png">

Thank you in advance @gnomeontherun

**Comment by akqira** [comment]
Tried the following without success : 
- running the command as root 
- removing package-lock.json
- clearing npm cache with force

**Comment by gnomeontherun** [comment]
Workaround should be to run `ng add @clr/angular@2` since that is the compatible version that works with Angular 8. Running `ng add @clr/angular` will try to install v3, since it is now the latest.

Will investigate why it tries to use `next` in this case.

**Comment by akqira** [comment]
I tried right now the workaround by running **ng add @clr/angular@2**
Having the same error message for  @clr/ui@next

**Comment by gnomeontherun** [comment]
I see a possible issue with the logic trying to detect if it should use `next`. Until then follow the get started guide, its pretty easy to install manually.

**Comment by akqira** [comment]
Just to inform you that it is working for **ng add @clr/angular@2.3.8**
