### ISSUE TITLE
Provide error object in clrIfError context

### ISSUE THREAD

**Issue by gerinjacob** [vmware/clarity#4345]
## Summary

_Describe the change or feature in detail. Try to answer the following questions._

* What is the change?
Expose error object in the context of `clrIfError`

* Why should it go in Clarity?
This is a generic usecase, where error object can be easily accessed.

* Does this change impact existing behaviors? If so how?
No, existing behavior will not be affected.

* If this change introduces a new behavior, is this behavior accessible?
Not related to accessibility

## Use case

Currrently, `clrIfError` structural directive only looks if an error is present. In some cases to display a meaningful message it is useful to get access to the error object itself.
e.g. `Street name should be minimum 3 characters long. You have provided only 1`
Today, especially in reactive forms, we need to traverse through FormGroup/FormArray to access this error object.
e.g. `complexForm.get('billing.address.street').errors.minlength.requiredLength`
e.g. `complexForm.get('billing.address.street').errors.minlength.actualLength`
Also we need to revisit the error section for any change in the form structure.
It will be useful if error object is directly available.
e.g. `error.requiredLength`
e.g. `error.actualLength`

## API

Proposal is to set the error object in the context of `clrIfError` while creating the embedded view.
https://github.com/vmware/clarity/blob/master/src/clr-angular/forms/common/if-error/if-error.ts#L55
```javascript
this.container.createEmbeddedView(this.template, { 
  error: this.control.getError(this.error) 
});
```
Usage:
```html
<clr-control-error *clrIfError="'minlength';error as err">
  Street name should be minimum {{err.requiredLength}} characters long.
  You have provided only {{err.actualLength}}.
</clr-control-error>
```

**Comment by mathisscott** [comment]
Pushed to `v2` and merged to `master`.

Will be released in `3.1` and `2.4`.

Thanks for the contribution, @gerinjacob . It looks great!
