### ISSUE TITLE
Clarity Wizard does not provide any way to intercept click on CANCEL or close icon and prevent the default action.

### ISSUE THREAD

**Issue by Maharshi** [vmware/clarity#435]
**Select one ...**  (check one with "x")
```
[] bug
[x] feature request
[] enhancement
```

### Expected behavior
I need to override the wizard behavior when the user clicks "Cancel" button OR clicks on the "x" (close) icon? I would like to show a message, warning the user that the data filled in the wizard steps will be lost if the user chooses to "Cancel" or "Close" the wizard.
What I am expecting here is for Clarity to provide an option for CANCEL and close icon, similar to the one provided for click on NEXT/FINISH button i.e. clrWizardPagePreventDefault.
This is a fairly common scenario that one encounters when implementing applications for Enterprise and thus it would be essential and a good thing to support it.

### Actual behavior
On clicking the CANCEL button or close (x) icon the wizard closed immediately and then emits the clrWizardOpenChanged event. However, by that time it is too late since the wizard modal window is already closed.

### Reproduction of behavior
This is a feature request and hence the feature does not exist in the code for me to demonstrate it using Plunker.

### Environment details

* **Angular version:** 2.2.0

* **Clarity version:0.8.4

* **OS and version:Mac OS X (El capitan)

* **Browser:** [all]

**Comment by mathisscott** [comment]
Hi @Maharshi :

This may be possible once we are done with #156 

I'm going to leave this open for now until we know for sure if this will make it into the refactor or if it will need to be work done separately after the refactor is finished.

**Comment by Maharshi** [comment]
Any update? Do you any rough estimate as to by what date I can expect to get this behavior in Wizard component?

**Comment by mathisscott** [comment]
@Maharshi : Considering where the work is at this time and all the documentation and unit tests that will be needed, the wizard refactor is still a ways off. I may have a more concrete ETA in a few weeks but right now the wizard is still very much a work in progress.

**Comment by Maharshi** [comment]
Ok. I will check back with you in couple of weeks.

**Comment by mathisscott** [comment]
Closing this issue as a duplicate because it will be included with #156 when that is finished.
