### ISSUE TITLE
Stepper always expands first step and user cannot collapse it in Clarity 3

### ISSUE THREAD

**Issue by dexfab** [vmware/clarity#4353]
## Describe the bug

Stepper always expands step 1 after completion and it cannot be collapsed

## How to reproduce

1.  Go to https://clarity.design/documentation/stepper#examples
2.  Type input
3.  Click on 'Next
4.  Step 1 and 2 gets expanded. Step 1 cannot be collapsed

## Expected behavior

As in previous versions, step 1 should collapse when step 2 expands. User should be able to expand it on demand.

## Versions

**App**

* Angular: 9
* Clarity: 3

**Device:**

* Browser: chrome

**Comment by gnomeontherun** [comment]
Thanks, that is a bug we need to investigate.
