### ISSUE TITLE
Cannot customize color of progress bars

### ISSUE THREAD

**Issue by dexfab** [vmware/clarity#4354]
## Describe the bug

Progress bar color cannot be changed through CSS anymore

## How to reproduce

Got to https://clarity.design/documentation/progress#color
Try changing the color of the progress through CSS, nothing happens.

## Expected behavior

It should be possible to theme the progress bar by changing its color.

## Versions

**App**

* Angular: 9
* Clarity: .

**Device:**

* Browser: chrome

**Comment by gnomeontherun** [comment]
Need to investigate, it used to work but might be an issue with some host bindings.

**Comment by dexfab** [comment]
Hi, any updates on this issue? We have a theme and this is the only component we cannot customise with our branding.

**Comment by BFergerson** [comment]
I'm also experiencing this issue. I've tried 
```html
<div class="progress top" style="color: black !important;">
    <progress style="color: black !important;" value="40" max="100"></progress>
</div>
```

Yet, the progress bar remains blue.

**Comment by macharius40** [comment]
Any news about this issue? I have the same problem. It doesn't work when I modify the color in Chrome dev tools. It doesn't work also on Firefox but it work on IE 😅

**Comment by prakashjp123** [comment]
Below code worked for me in chrome and firefox.
```
<div class="progress-block" id="custom-progress-bar">
    <clr-progress-bar clrValue="10" clrMax="20"></clr-progress-bar>
</div>
```
```
#custom-progress-bar {
    --clr-progress-bg-color: lightgray;
    --clr-progress-default-color: orange;
}
```

**Comment by bdryanovski** [comment]
Here are the properties that are related to the progress-bar

```scss
      --clr-progress-default-color: var(--clr-color-action-600);
      --clr-progress-alt-color-1: var(--clr-color-success-400); // green
      --clr-progress-alt-color-2: var(--clr-color-danger-800); // red
      --clr-progress-alt-color-3: var(--clr-progress-alt-color-2); // red
      --clr-progress-bg-color: var(--clr-color-neutral-200);
```

If you need to change the color you need to change the property of:

```scss
 .progress>progress::-webkit-progress-value
```
