### ISSUE TITLE
Clarity 1.x  source map inlined inside distribution Javascript

### ISSUE THREAD

**Issue by mattmutt** [vmware/clarity#4359]
## Describe the bug

The shipped Javascript is unnecessarily bloated with inlined sourceMap code. 

## How to reproduce

Pull Clarity from a repository

`npm install "@clr/angular@1"`

visit the file
`node_modules/@clr/angular/fesm5/clr-angular.js`

The size is well over 2.4 MB

## Expected behavior

The size should be less than 1 MB. The reason is due to inlined source maps

## Versions

**App**

* Clarity: [1.x]

## Additional notes

While v2 and v3 are fine, this implies that the Clarity 1 build is made to inline a large, extraneous source map.

**Comment by gnomeontherun** [comment]
Hi @mattmutt, I would expect that the application would be able to drop out source maps though, is this not the case? I reviewed v1, and it doesn't have a configuration to inline the source map, so this might be an issue with one of our build dependencies. We just use Angular and ng-packagr to build the package.

**Comment by mattmutt** [comment]
it's not a problem for production builds as the minification occurs. Overall this is a harmless effect, other than the fact that an extra MB of sourcemap is added for non production ( meaning dev or watch mode ) builds. In our `postinstall` script we will compress Clarity distributions ( fesm5, fesm2015) as soon as they are installed into `node_modules` thereby providing remedy. The effect is a 84% size reduction.

**Comment by gnomeontherun** [comment]
Ok, given the nature of the build addressing this issue, it seems low priority and fixed in v2+. Since our support of v1 is in the final stages and I'm concerned about downstream impact, I don't expect we'll be able to address this, so I'm going to close this for now. Thanks for testing with other versions!
