### ISSUE TITLE
Karma Unit Test case coverage for lazy loading in Angular 8 

### ISSUE THREAD

**Issue by dharemsj** [vmware/clarity#4360]
How to write the unit test cases for lazy loading in angular 8. i tried a lot but my unit test cases are not covering "loadChildren" routing.

import { NgModule, ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from "@angular/router"; 
import { AppRoutingComponent } from "./app-routing.component";

const appRoutes: Routes = [

{ path: "index.html", component: AppRoutingComponent }, 
{ path: "product", loadChildren: () => import('app/dashboard/product.module').then(m => m.ProductModule) },
{ path: "", redirectTo: "/main", pathMatch: "full" } ];

export const routedComponents = [ AppRoutingComponent,

];

@NgModule({
imports: [routing],
exports: [RouterModule]
})

export class AppRoutingModule { }

Please provide some guidance.
Thanks in advance.

**Comment by gnomeontherun** [comment]
Hi @dharemsj I'm not sure what this question has to do with Clarity. I suggest that you take a look at https://stackoverflow.com/questions/tagged/angular and search for related questions there.

Closing as off topic to Clarity.
