### ISSUE TITLE
An error occurred when using a ngIf on a clr-tab

### ISSUE THREAD

**Issue by terryvdgriend** [vmware/clarity#4361]
## Describe the bug

I have noticed when upgrading from Clarity 2.0.1 to 2.2.0 that a bug was introduced when using an ngIf on clr-tab. 

In the versions before Clarity 2.1.2 it was possible to have a ngIf on a clr-tab. When the condition was false the clr-tab would disappear and one of the other tabs would be selected. 

However when using Clarity 2.1.2 or higher this error occurs: `ERROR
Error: Cannot set property 'tabIndex' of null`

## How to reproduce

I have reproduced the issue on https://clarity-v3-light-theme-qjvdzr.stackblitz.io.

1.  Go to Tab "Second"
2.  Click on the button "Delete"
3.  Open the console window
4.  See error

## Expected behavior

I would expect that the to be removed Tab "Second "would disappear and that the Tab "First" would now be selected.

## Versions

**App**

* Angular: [9.0.4]
* Clarity: [3.0.0]

**Device:**

* Type: [Laptop]
* OS: [Windows]
* Browser [Chrome]
* Version [80.0.3987.132]

## Additional notes

This used to work before this [PR](https://github.com/vmware/clarity/pull/3700)

**Comment by gnomeontherun** [comment]
This has been resolved by https://github.com/vmware/clarity/pull/4291 and part of 2.3.9. Please update to the latest v2 to get this fix, thanks!

Closing as a duplicate and resolved by this week's release.

**Comment by terryvdgriend** [comment]
@gnomeontherun awesome thx for the tip!
