### ISSUE TITLE
Angular get started: Next step

### ISSUE THREAD

**Issue by miohtama** [vmware/clarity#4369]
First let me thank you for this awesome open-source product. I really really like Clarity.

## Summary

After following [Get started instructions](https://clarity.design/documentation/get-started) to get Angular packages installed for your application, there is a lack of natural next step in the instructions.

This causes new developers to get lost and dropping the interest, as there is no easy way to start toying with Clarity.

The natural next step is to show how you can construct your application main view with Clarity: adding logo, navigation, footer and so on. It could be as simple as showing how to copy-paste some HTML code and importing Clarity components.

## Use case

Developer friendliness: This would increase speed and comfort how easily new developers can get started.

## Examples

[Here is a step-by-step tutorial how to use MD Bootstrap framework within your Angular app](https://mdbootstrap.com/education/angular/agenda-app-overview/). However, as the first baby step a much simpler code copy-paste instructions are enough.

**Comment by miohtama** [comment]
[Here is an outdated tutorial I came across](https://medium.com/@beeman/tutorial-project-clarity-and-angular-cli-50d845a24d5b)

**Comment by gnomeontherun** [comment]
No longer an issue or resolved in the upcoming website work. Closing as resolved.
