### ISSUE TITLE
Add a footer to datagrind detail

### ISSUE THREAD

**Issue by jvpoucke** [vmware/clarity#4370]
## Summary

_Have a static footer in the detail panel of the datagrid._

* Make the detail panel act more like a card, allowing for a header, body and footer. The footer is missing currently?

## Examples
Example: I want to add secondary actions and info that should be static.

**Comment by gnomeontherun** [comment]
Thanks for the suggestion and we'll put it under consideration. 

This is something that could be built on the app side as needed. If you want to do this, adding an element to the bottom of the body and styling it as appropriate is a good workaround.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
