### ISSUE TITLE
The "datagrid-detail-caret-button" buttons need unique aria-label.

### ISSUE THREAD

**Issue by chlane** [vmware/clarity#4374]
## Describe the bug

[Test URL]
https://clarity.design/documentation/datagrid/detail-pane

[WCAG 2.1 Guideline]
Success Criterion 2.4.6 Headings and Labels
(Level AA)

[OS]
any

[User Agents/Assistive Technologies]
any

[Component]
Datagrid Detail Pane

[Description]
The "datagrid-detail-caret-button" buttons need unique aria-label.

See the relevant HTML below.

button type="button" aria-haspopup="dialog" class="datagrid-detail-caret-button" aria-label="Open" aria-expanded="false" aria-controls="clr-id-12"

[User Impact]
Screen reader users will hear the same label "Open" for every button and may not know which specific record is being opened by these buttons. 

[Recommendation]
Provide aria-label values that tell the user which specific record is being opened by these buttons e.g., aria-label="open detail pane for user id 13345".

## How to reproduce

- Go the the Test URL
- Using a screen reader, read all the "datagrid-detail-caret-button" buttons
- Observe that they are all announced as "Open"

## Expected behavior
aria-label values that tell the user which specific record is being opened by these buttons e.g., aria-label="open detail pane for user id 1334

**Comment by gnomeontherun** [comment]
We can support an input to collect customized text, but applications will have to supply it.
