### ISSUE TITLE
Datalist options use more than string list

### ISSUE THREAD

**Issue by joshnickleby** [vmware/clarity#4377]
## Summary

I have tried to use the datalist for a list of objects (value as id but display the name) and it isn't clear whether this is possible. If it is then just some more documentation on how to do it. It would be nice to have a way to reference the whole object by dropdown name so that it can get added to the parent object.

## Use case

    // interface
    interface Effect {
        name: string;
        description: string;
    }
    
    // parent object
    newObject = {
        effect: null
    }
    
    // template code
    <input clrDatalistInput [(ngModel)]="newObject.effect">
    <datalist>
        <option *ngFor="let effect of effects" [ngValue]="effect">{{effect.name}}</option>
    </datalist>

## Examples

The standard select for angular works in this way.

## Workarounds

Using `(ngModelChange)` to find the object by the value in the component.

**Comment by gnomeontherun** [comment]
Hi @joshnickleby, this is a great suggestion and it would be wonderful to have. However, the datalist is a native HTML element and only stores string values. The best way to deal with this will be to use the Combobox (see #4286 for upcoming implementation).

Another way to deal with this is to store the index of the option as the value, and then use it to look up the value after a model change by binding to the change event.

Based on the Combobox work (which will enable this capability) and the inability to modify the datalist itself (based on HTML behaviors), I'm going to close this.
