### ISSUE TITLE
The popup for show/hide datagrid columns has unlocallized strings

### ISSUE THREAD

**Issue by kaleksandrov** [vmware/clarity#4384]
## Describe the bug

The popup for show/hide datagrid columns has unlocallized strings. The SELECT ALL button and SHOW COLUMNS title are always shown in English.

## How to reproduce

1.  Use Chinese locale
2. Create a Datagrid with hidden columns
3.  Go to the bottom left corner of the datagrid and click the action button for show/hide columns
3.  Observe that the SELECT ALL and SHOW COLUMNS strings are not translated

## Expected behavior

All strings should be properly localized 

## Versions

**App**

* Angular: 8.1.2
* Node: 10.15.3
* Clarity: 2.3.0

## Additional notes

![](http://engweb.eng.vmware.com/bugs/files/0/2/5/3/1/8/3/8/Configure_vSAN_FileShares_Hardcode_Build15838543_CN.png)

**Comment by hippee-lee** [comment]
Are you overriding the custom strings with the commonStrings servcie?  The Hide/Show datagrid toggle provides:

- selectAll
- close
- showColumns

They are customizable with the common strings service that was introduced in [2.1.1](https://clarity.design/news/2.1.1)

Docs for the i18n service are here: https://clarity.design/documentation/internationalization

**Comment by gnomeontherun** [comment]
Hi @kaleksandrov, due to inactivity in a reproduction, the issue will be closed per our [issue policy](https://github.com/vmware/clarity/issues/4372). If you are able to provide a reproduction it can be reopened to track or create a new issue in the future.

**Comment by kaleksandrov** [comment]
> Is the app overriding the custom strings with the commonStrings service? The Hide/Show datagrid toggle provides:
> 
>     * selectAll
> 
>     * close
> 
>     * showColumns
> 
> 
> They are customizable with the common strings service that was introduced in [2.1.1](https://clarity.design/news/2.1.1)
> 
> Docs for the i18n (custom strings) service are here: https://clarity.design/documentation/internationalization

Thanks for the reply! No, I was not aware of this localization service. Thanks for letting me know. I'll give it a try.
