### ISSUE TITLE
Datagrid styles get clobberd when there is a Compact Form with a Compact Datagrid inside it

### ISSUE THREAD

**Issue by BobRam** [vmware/clarity#4397]
Broken header with checkbox in DataGrid when multi-item selection enabled

everything works but looks bad, see screenshot below

clarity 3.0.1
angular 9.0.4

&#x3C;clr-datagrid class=&#x22;datagrid-compact&#x22; [(clrDgSelected)]=&#x22;selected&#x22;&#x3E;
  &#x3C;clr-dg-column&#x3E;id&#x3C;/clr-dg-column&#x3E;
  &#x3C;clr-dg-column&#x3E;name&#x3C;/clr-dg-column&#x3E;
  &#x3C;clr-dg-column&#x3E;value&#x3C;/clr-dg-column&#x3E;
  &#x3C;clr-dg-column&#x3E;type&#x3C;/clr-dg-column&#x3E;
  &#x3C;clr-dg-row *clrDgItems=&#x22;let ch of characteristic&#x22; [clrDgItem]=&#x22;ch&#x22;&#x3E;
    &#x3C;clr-dg-cell&#x3E;{{ch.id}}&#x3C;/clr-dg-cell&#x3E;
    &#x3C;clr-dg-cell&#x3E;{{ch.name}}&#x3C;/clr-dg-cell&#x3E;
    &#x3C;clr-dg-cell&#x3E;{{ch.value}}&#x3C;/clr-dg-cell&#x3E;
    &#x3C;clr-dg-cell&#x3E;{{ch.type}}&#x3C;/clr-dg-cell&#x3E;
  &#x3C;/clr-dg-row&#x3E;
&#x3C;/clr-datagrid&#x3E;

![image](https://user-images.githubusercontent.com/62503810/77248430-5bb21a80-6c4a-11ea-9d79-1f2e038ec309.png)

**Comment by hippee-lee** [comment]
Hi there,

I'm not able to see your issue. We ask that reported issues also submit a stackbltitz that isolates the component and demonstrates the issue. 

When I take the code provided and try to replicate the issue I'm not seeing it. Is it possible that somehting in the app style is overriding the datagrid style? 

I've gone ahead a forked one of our v3 starter apps in stackblitz. Please modify it so tit replicates your issue: https://stackblitz.com/edit/gh-issue-4397

**Comment by BobRam** [comment]
Hi,
unfortunatelly I am unable to reproduce issue on stackblitz.
App does not contain any custom css styles and only clarity components + "angular-split": "3.0.3" component which seems to be not related to the issue. Problem visible in different browsers on different pc.

**Comment by gnomeontherun** [comment]
Perhaps cloning your application and stripping out anything unnecessary could be useful to isolate the problem. I would also try to disable angular-split just in case there is a conflict. Without a reproduction, we're really unsure how else to proceed.

**Comment by BobRam** [comment]
ok, i found out how to reproduce, just place datagrid inside form tag:

<div class="main-container">
	<header class="header-2">
		<div class="branding">
			<a class="nav-link">
				<clr-icon shape="home" size="24"></clr-icon>
				<span class="title">Clarity</span>
			</a>
		</div>
		<div class="header-nav">
			<a class="active nav-link nav-text">Home</a>
		</div>
	</header>
	<div class="content-container">
		<div class="content-area">
			<h3></h3>
        <form clrForm clrLayout="compact">
			<clr-datagrid class="datagrid-compact" [(clrDgSelected)]="selected">
				<clr-dg-column>id</clr-dg-column>
				<clr-dg-column>name</clr-dg-column>
				<clr-dg-column>value</clr-dg-column>
				<clr-dg-column>type</clr-dg-column>
				<clr-dg-row *clrDgItems="let ch of [1,2,3,4,5]" [clrDgItem]="ch">
					<clr-dg-cell>{{ch}}</clr-dg-cell>
					<clr-dg-cell>{{ch}}</clr-dg-cell>
					<clr-dg-cell>{{ch}}</clr-dg-cell>
					<clr-dg-cell>{{ch}}</clr-dg-cell>
				</clr-dg-row>
			</clr-datagrid>

			<clr-datagrid [(clrDgSelected)]="selected">
				<clr-dg-column>id</clr-dg-column>
				<clr-dg-column>name</clr-dg-column>
				<clr-dg-column>value</clr-dg-column>
				<clr-dg-column>type</clr-dg-column>
				<clr-dg-row *clrDgItems="let ch of [1,2,3,4,5]" [clrDgItem]="ch">
					<clr-dg-cell>{{ch}}</clr-dg-cell>
					<clr-dg-cell>{{ch}}</clr-dg-cell>
					<clr-dg-cell>{{ch}}</clr-dg-cell>
					<clr-dg-cell>{{ch}}</clr-dg-cell>
				</clr-dg-row>
			</clr-datagrid>
        </form>
		</div>
	</div>
</div>

**Comment by BobRam** [comment]
https://gh-issue-4397-48msfa.stackblitz.io/

**Comment by hippee-lee** [comment]
Ths issue I see in the stackblitz that needs more investigation is as follows: the `datagrid-compact` styles on a compact datagrid inside of a compact form seem to be getting clobbered. e.g its not just the checkbox label, cell content in rows (but not headers)  is also misaligned and possibly other vusual defects.

Link to the stackblitz editor: https://stackblitz.com/edit/gh-issue-4397-48msfa

I marked it as a regression but I'm not sure how it previously behaved in older versions. It has been added to the backlog.

**Comment by BobRam** [comment]
Its getting clobbered even without "clrLayout="compact"" on form and without class="datagrid-compact" on datagrid

**Comment by hippee-lee** [comment]
I'm trying to keep this issue focused on compact form with comapct datagrid inside it. 
The fix will likely apply to non compact forms and non compact datagrids as well. 

Hard to say at this point but they are two distinct use cases.

**Comment by gnomeontherun** [comment]
This can be solved by using Clarity Core forms instead, as they are more isolated and won't absorb styles the same way as Clarity UI did. I'm going to mark this as resolved by using the Core version of the components. See https://clarity.design/core-components/form/
