### ISSUE TITLE
Datalist styling not working in production mode

### ISSUE THREAD

**Issue by JonathanTheZero** [vmware/clarity#4398]
In my Application I use this a datalist and it works perfectly fine when running `ng serve`, however when I run it with a production flag or try to build it, the datalist appears unstyled like this: ![image](https://user-images.githubusercontent.com/25566023/77360500-be400f00-6d4d-11ea-9ca1-91f7e16d4f8e.png)

The console doesn't give me any errors related to this

## Code

```html
<form clrForm (submit)="submit()">
  <clr-datalist-container>
    <label>Status</label>
    <input name="status" clrDatalistInput [(ngModel)]="status" />
    <datalist>
      <option [value]="'Online'">Online</option>
      <option [value]="'Offline'">Offline</option>
      <option [value]="'DnD'">DnD</option>
    </datalist>
  </clr-datalist-container>
</form>
```

## Expected behavior

The datalist input should keep its style and work like in development mode and look like this: 
![ezgif-7-db394fdd98a5](https://user-images.githubusercontent.com/25566023/77360783-47574600-6d4e-11ea-8210-a24d4d186f25.gif)

## Versions

**App**

* Angular: 9.0.2
* Node: v12.16.0
* Clarity: 3.0.0

**Device:**

* Type: Laptop (but also happens on my Desktop)
* OS: Windows 10 (both)
* Browser Opera, Firefox

**Comment by gnomeontherun** [comment]
Is this the only thing that looks wrong? Our website is built with --prod so seems like there is possibly a configuration issue here. It would be helpful to have a reproduction to review.

**Comment by JonathanTheZero** [comment]
As far as I can tell: yes, this is the only thing that looks different. All other forms, inputs whatever look like the should.

What do you need for a reproduction? Sadly the repository is private and I can't make it public. Is stackblitz capable of running with different flags?

**Comment by gnomeontherun** [comment]
The easiest thing is to rip _everything_ extra out of your project except a single component with the datalist. I don't have a path forward honestly at the moment to triage, it seems like there is either some third party scripts conflicting or a build configuration detail. 

Can you also post the rendered HTML of the datalist? That might provide some clues to what is happening or not.

**Comment by JonathanTheZero** [comment]
It solved itself apparently. 

I used a BehaviourSubject at one point and apparently it was undefined when entering the Dashboard, although I gave it a value in its constructor, fixing this also fixed the style of the component (but also happened with the Login Component later on again). Apparently other errors block the CSS from loading or something like that
