### ISSUE TITLE
Multi Select component support

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#4401]
## Describe the bug
Select with multiple selection feature documentation is missing. 
Is this intentional or a miss? 
If there is a better component please let us know.

https://vmware.github.io/clarity/documentation/v0.11/select-boxes
https://v2.clarity.design/select

## How to reproduce
https://v2.clarity.design/select

https://v2.clarity.design/select

## Expected behavior
Please provide documentation and update the sketch as well.

## Versions

**App**

* Angular: 8
* Node: [e.g. 8.10.0]
* Clarity: 2.x

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
Hello @shravansofts, the documentation doesn't show a demo of a multi-select select box, but it is supported. I'll submit a fix for the docs to address this confusion shortly.

See https://stackblitz.com/edit/clarity-light-theme-v2-8zdytl?file=src%2Fapp%2Fapp.component.html

**Comment by mathisscott** [comment]
@hippee-lee 
Can you check that this is in the new website? It's an ask for a multi-select example.

**Comment by gnomeontherun** [comment]
There is a demo on the new site. Closing.
