### ISSUE TITLE
Cannot read property 'control' of null while submitting a form in template driven approach

### ISSUE THREAD

**Issue by Dnalop** [vmware/clarity#4414]
## Describe the bug

This bug occurs, when submitting a form (template driven approach). While it does execute the whole code behind submitting a form, the following error shows up:

```
ERROR TypeError: Cannot read property 'control' of null
    at SafeSubscriber.eval [as _next] (wrapped-control.ts:73)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:265)
    at SafeSubscriber.next (Subscriber.ts:207)
    at Subscriber._next (Subscriber.ts:139)
    at Subscriber.next (Subscriber.ts:99)
    at Subject.next (Subject.ts:70)
    at MarkControlService.markAsTouched (mark-control.service.ts:19)
    at ClrForm.markAsTouched (form.ts:57)
    at ClrForm.onFormSubmit (form.ts:75)
    at Object.eval [as handleEvent] (AppComponent.html:5)
```

## How to reproduce

Here's a link to a reproduction scenario on StackBlitz: https://stackblitz.com/edit/clarity-v3-light-theme-vgxu5m

1. Just submit the form. No matter if you fill it in, or not, you should see `form.value` object (It is logged on `ngSubmit`), and the aforementioned error.

## Expected behavior

No error should occur on submitting the form.

## Versions

**App**

* Angular: 9.0.7
* Node: 12.1.0
* Clarity: 3.0.1

**Device:**

* Type: Notebook (Dell Inspiron 5570)
* OS: Windows 10 Home 64bit (version 10.0.18362) 
* Browser: Google Chrome (version 80.0.3987.149)

**Comment by gnomeontherun** [comment]
Hi @Dnalop this isn't a Clarity issue, but rather incorrect Angular forms usage in your demo. It doesn't properly assign any values to `ngModel` so the form isn't wired up to work with Angular and wouldn't work with or without Clarity.

See https://stackblitz.com/edit/clarity-v3-light-theme-dphkak?file=src/app/app.component.html for an updated version of your demo. Closing as an implementation question with a working demo.

**Comment by Dnalop** [comment]
Oh, I see now. Sorry for inconvenience.
