### ISSUE TITLE
Replace Clarity hero image with temporary doodle image

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#4417]
## Summary

Replace the standard hero image on the homepage with the attached .svg. To be used as a temporary image just to keep the page fun and fresh. No requirement on when or how long it should live on the page; 2-4 weeks should suffice.

-dimensions are the same as the standard hero image. 
-The opacity of the card layered on top of the image should be reduced to 70% to allow the image to show through.

Temporary doodle image:
[Clarity logo-collaboration-img.svg.zip](https://github.com/vmware/clarity/files/4390923/Clarity.logo-collaboration-img.svg.zip)

Should look like this:
![image](https://user-images.githubusercontent.com/23196444/77711745-0ac65d00-6f8f-11ea-9ab1-3577b7cefa24.png)

**Comment by gnomeontherun** [comment]
Scott will do this during the next release.

**Comment by mathisscott** [comment]
Will be live with the 3.1 release
