### ISSUE TITLE
[Clarity 2.x] Datagrid filter is accepting Empty string and showing as a filter applied

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#4418]
## Describe the bug

Datagrid filter component is accepting Empty string and showing as a filter applied even though no filter is applied on the rows rendering.

## How to reproduce
Can be seen from doocumentation example.
https://v2.clarity.design/datagrid/binding-properties

Refer gif below
![clarity_empty_string_filter](https://user-images.githubusercontent.com/12848838/77746894-afa27200-7043-11ea-819f-5f695d84c79a.gif)

## Expected behavior
Either don't allow empty string and filter applied icon or show the filtered data by considering empty string

## Versions

**App**

* Clarity: 2.x

**Device:**

* Type: [e.g. MacBook]
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This seems to be related to how we store a cleaned version of the search string and `trim()` on it, before we compare it to values on that column object. That makes it possible for whitespace to be stripped during comparison but not in the source input. This seems like a very limited edge case, and a custom filter could change this behavior if they wanted as a workaround.
