### ISSUE TITLE
White and Black aren't represented correctly in Neutral Palette

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#442]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Background of white item should be #FFF.  Background of black item should be #000 (with white text)

### Actual behavior
Both palette elements have a grey background with black text

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/color

### Environment details

* **OS and version:** 

* **Browser:** Noted in Chrome

**Comment by hippee-lee** [comment]
Hey @joshjohnson72,

I'm looking into this but don't see the issue on the site.
![screen shot 2017-02-09 at 12 53 03 pm](https://cloud.githubusercontent.com/assets/433692/22802733/d9ce5be0-eec6-11e6-864e-e127b19ea761.png)
Can you confirm that I am looking at the correct palette?

**Comment by joshjohnson72** [comment]
That is the right one.  I just looked at it again and it appears to be working now.  Not sure what changed from then to now, but can no longer reproduce.

**Comment by jaffoneh** [comment]
Thanks @joshjohnson72 for confirming. Closing based on the last comment.
