### ISSUE TITLE
Grid Within Expanded DataGrid Row Does Not Take Full Width

### ISSUE THREAD

**Issue by jeffjarzombeck** [vmware/clarity#4424]
# Describe the bug
When using a datagrid with expandable rows, a grid placed within the expanded row does not utilize the full width of the datagrid.

# How to reproduce
https://stackblitz.com/edit/clarity-v3-light-theme-nzr5hb
See the Default datagrid below.

Place a clarity grid within the expanded row of a clarity datagrid.

# Expected behavior
The grid should take up the full width automatically.

# Workaround
https://stackblitz.com/edit/clarity-v3-light-theme-nzr5hb
See the Width 100% datagrid below.

Accomplished by setting the width of a parent div to width 100%.

# Versions
Clarity 3.0.0
Chrome 80.0.3987.87

# HTML
```html
Default

<clr-datagrid>
  <clr-dg-column>User ID</clr-dg-column>
  <clr-dg-column>Name</clr-dg-column>
  <clr-dg-column>Creation date</clr-dg-column>
  <clr-dg-column>Favorite color</clr-dg-column>

  <clr-dg-row *ngFor="let user of users">
    <clr-dg-cell>{{ user.id }}</clr-dg-cell>
    <clr-dg-cell>{{ user.name }}</clr-dg-cell>
    <clr-dg-cell>{{ user.creation | date }}</clr-dg-cell>
    <clr-dg-cell>{{ user.color }}</clr-dg-cell>

    <clr-dg-row-detail *clrIfExpanded>
      <div class="clr-row">
        <div class="clr-col-4">
          <span>4</span>
        </div>
        <div class="clr-col-6">
          <span>6</span>
        </div>
        <div class="clr-col-2">
          <span>2</span>
        </div>
      </div>
    </clr-dg-row-detail>
  </clr-dg-row>

  <clr-dg-footer>{{ users.length }} users</clr-dg-footer>
</clr-datagrid>

Width 100%

<clr-datagrid>
  <clr-dg-column>User ID</clr-dg-column>
  <clr-dg-column>Name</clr-dg-column>
  <clr-dg-column>Creation date</clr-dg-column>
  <clr-dg-column>Favorite color</clr-dg-column>

  <clr-dg-row *ngFor="let user of users">
    <clr-dg-cell>{{ user.id }}</clr-dg-cell>
    <clr-dg-cell>{{ user.name }}</clr-dg-cell>
    <clr-dg-cell>{{ user.creation | date }}</clr-dg-cell>
    <clr-dg-cell>{{ user.color }}</clr-dg-cell>

    <clr-dg-row-detail *clrIfExpanded>
      <div style="width:100%;">
        <div class="clr-row">
          <div class="clr-col-4">
            <span>4</span>
          </div>
          <div class="clr-col-6">
            <span>6</span>
          </div>
          <div class="clr-col-2">
            <span>2</span>
          </div>
        </div>
      </div>
    </clr-dg-row-detail>
  </clr-dg-row>

  <clr-dg-footer>{{ users.length }} users</clr-dg-footer>
</clr-datagrid>

```
![DataGrid](https://user-images.githubusercontent.com/16842860/77788224-ddc98700-702e-11ea-9d87-0b73d1dff562.PNG)

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
