### ISSUE TITLE
NPM Error when installing HTML/CSS Framework or Clarity Angular

### ISSUE THREAD

**Issue by engineers-tools** [vmware/clarity#4426]
## Describe the bug

_While following the [get started](https://clarity.design/documentation/get-started) guidelines, an error is reported during installation._

## How to reproduce

Follow the _HTML/CSS Framework_ or _Angular Option 1: Installing using Angular CLI (Recommended)_ instructions

Both fail with the following log output:

`verbose stack @clr/ui: No matching version found for @clr/ui@next.`

## Expected behavior

Clarity to install as per get started guidelines

## Versions

**App**

```Angular CLI: 9.0.7
Node: 12.14.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.7
@angular-devkit/build-angular              0.900.7
@angular-devkit/build-optimizer            0.900.7
@angular-devkit/build-webpack              0.900.7
@angular-devkit/core                       9.0.7
@angular-devkit/schematics                 9.0.7
@ngtools/webpack                           9.0.7
@nguniversal/module-map-ngfactory-loader   8.0.0-rc.1
@schematics/angular                        9.0.7
@schematics/update                         0.900.7
rxjs                                       6.5.4
typescript                                 3.7.5
webpack                                    4.41.2
```

**Device:**

* Type: [Lenovo X1 Carbon]
* OS: [Windows 10]
* Browser [Chrome,Brave]
* Version [e.g. 80]

**Additional Information**
This install is being tried on a clean install of the [Clean Architecture's ClientApp](https://github.com/jasontaylordev/CleanArchitecture/tree/master/src/WebUI/ClientApp)  template.

[Issue #4264](https://github.com/vmware/clarity/issues/4264) seems to be related, but was closed.

**Comment by hippee-lee** [comment]
Hi @engineers-tools - there is not an `@ next` version for Clarity as ofMarch 30, 2020. We had one while we were certifying the v3.0 release and will add one once we start to get the v4 release ready. 

For now you should install with just `npmi @clr/ui`. I just tested a fresh install with the latest on a blank projct and did not have an issue.
