### ISSUE TITLE
One Word: SPLITTER

### ISSUE THREAD

**Issue by dustwhirl** [vmware/clarity#4439]
## Summary

Allow for the sectional display areas to be resized by dragging a slider up and down (vertical) or left and right (horizontal).

## Use case

We build a lot of mapping applications where we have data on one side and a map on the other. It would be great if we could resize either the map or the data by dragging a slider.

## Examples

angular-split, kendo splitter

## Workarounds

Not that I know of

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
