### ISSUE TITLE
A form inside of Modal prevents modal body rendering.

### ISSUE THREAD

**Issue by vzayko** [vmware/clarity#444]
[ ] bug
[ ] feature request
[x] enhancement

Hi!
I use a form inside of Modal control (Angular2).
But form tag prevents of Modal body rendering in case if the tag is outside of modal-body block.
Expected: to be able to put <form> tag around modal body.
Plunker: https://plnkr.co/edit/hmfQeOGRkGNrk5gWqgiN?p=preview
Angular version: 2.4.5
Clarity version: 0.8.4
OS: Windows 10
Browser: all
Thanks!

**Comment by youdz** [comment]
This is expected, we require the different pieces to be direct children of the modal so we can split them and project them in the right place.

In your case, there are two solutions: either put the `<form>` element inside the modal body itself, or put it completely around the modal like so: `<form><clr-modal>...</clr-modal></form>`.
The first one is simpler if you just need the form to wrap the body, the second is needed when the buttons in your footer are also part of the form.

**Comment by belyan** [comment]
Hi @vzayko!
Sorry, if it is not actual for you already, but I found this question on SO:
https://stackoverflow.com/questions/38054631/angular2-validate-and-submit-form-from-outside

According to it there are two ways to solve this problem.

1) Associate button with form via HTML attribute `form` e.g.:
```
<form id="myForm" [formGroup]="form" (ngSubmit)="onSubmit()">
...
</form>
<button type="submit" form="myForm">Submit</button>
```
This solution does not working in IE and Edge less than 16:
https://caniuse.com/#search=form%20attribute

2) Emit submit event when clicking of button:
```
<form #myForm="ngForm" [formGroup]="form" (ngSubmit)="onSubmit()">
...
</form>
<button type="submit" (click)="myForm.ngSubmit.emit()">Submit</button>
```
