### ISSUE TITLE
Performance of page decreases drastically when accordion used with list

### ISSUE THREAD

**Issue by kpl9** [vmware/clarity#4443]
## Describe the bug

When we use multiple accordion with list present in it, performance of application decrease drastically. This works well if we load all accordion in collapse mode and then expand all (this case takes overall less time then opening all accordion by default)

## How to reproduce
1. Create multiple accordion with list present in it.
2. Render the page with option : Accordion open by default

## Expected behavior
Page takes to long to load, browser crashed multiple times while loading this data

**Comment by gnomeontherun** [comment]
This does not have a reproduction, and part of our policy is to require a reproduction to triage issues. I'm going to close this and if the issue continues please update with a reproduction or create a new issue and follow our bug report format fully to help us provide support.
