### ISSUE TITLE
The Schematic workflow failed when try to add clarity to the project

### ISSUE THREAD

**Issue by DonTomato** [vmware/clarity#4444]
## The Schematic workflow failed when try to add clarity to the project

When I try to add clarity to my angular project with command `ng add @clr/angular`, it fails with the error below.
![image](https://user-images.githubusercontent.com/1098084/78529585-92f7fe00-77ea-11ea-8ee9-6fb752224084.png)

## How to reproduce
Reproduce the Angular Option 1 from the [Getting Started Page](https://clarity.design/documentation/get-started)
Steps to reproduce the behavior with Angular/cli 9.1.0:

1.  `ng new` ...
2.  `ng add @clr/angular`

## Versions

**App**

* Angular: 9.1.0
* Node: 12.16.1
* Clarity: -

**Device:**

* Type: PC
* OS: Windows 10

## Log is attached
[2020-04-06T06_45_14_408Z-debug.log](https://github.com/vmware/clarity/files/4436229/2020-04-06T06_45_14_408Z-debug.log)

**Comment by DonTomato** [comment]
It looks like the reason is that `npm install @clr/core` fails with `No matching version found for @clr/core@NaN.` error.
It can be installed only with version `npm install @clr/core@3.1.0`

**Comment by slippuu** [comment]
I get the same, except it's not just for core for me.

`ng new testapp`
`ng add @clr/angular`

Comes up with the error `No matching version found for @clr/ui@NaN` - running `ng add @clr/angular` seems to switch between `@clr/ui@NaN`, `@clr/core@NaN` and `@clr/icons@NaN`.

package.json shows:
```
"dependencies": {
    ...
    "@clr/angular": "^3.1.0",
    "@clr/ui": "NaN",
    "@clr/icons": "NaN",
    "@clr/core": "NaN",
    "@webcomponents/webcomponentsjs": "^2.0.0"
    ...
}
```

**Comment by sdurnov** [comment]
Having the same issue.

**Comment by antitoine** [comment]
I downgrade to v3.0.1 for now, until the 3.1.0 fix : 
```bash
ng add @clr/angular@3.0.1
```

**Comment by antitoine** [comment]
I downgrade to v3.0.1 for now, until the v3.1.0 fix:
```bash
ng add @clr/angular@3.0.1
```

**Comment by gnomeontherun** [comment]
You can also follow the manual steps from getting started, it only requires a few small edits to get everything setup the same way.

**Comment by DonTomato** [comment]
> You can also follow the manual steps from getting started, it only requires a few small edits to get everything setup the same way.

No, you can't. As soon as you try to follow manual installation, you will face with `No matching version found for @clr/core@NaN`, as it described in first comment to this issue.

**Comment by gnomeontherun** [comment]
If you review the documentation on our getting started here https://clarity.design/documentation/get-started, under Angular Option 2 you'll see the manual steps I'm referring to. It does not run the schematic when you follow these steps.

**Comment by gnomeontherun** [comment]
PR is up, this should be fixed in the next release!

**Comment by gnomeontherun** [comment]
Another workaround is to explicitly set the Angular version in your package.json file, so `9.0.0` instead of `^9.0.0` should allow the current script to run and setup a project for you.

**Comment by huskerona** [comment]
Workaround for this problem is to first run:

`npm i @clr/{core,icons,angular,ui}@3.1.0 @webcomponents/{webcomponentsjs,custom-elements}`

then

`ng add @clr/angular`

After this, both **angular.json** and **app.module.ts** are updated accordingly.
