### ISSUE TITLE
Mini Icon set

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#4445]
## Summary

A new set of icons that have a thicker stroke and can be scaled down as low as 10px (or possibly 8px) while retaining their visual integrity.

## Use case

We've had a lot of requests for icons that can scale down to tiny sizes for various use cases. Some of our current icons don't scale down below 14px before the icons become blurry.

## Requirements

1. These icons should be the same size as our existing icons (36px with a 2px whitespace around the glyph). But they will have thicker stroke weights.
2. These icons WILL NOT have badges or alert triangles. That is outside of their use case. At most, they will have outline and solid glyphs.
3. These icons should have their name appended with the word `-mini`. So the mini icon for `check-circle` would be named `check-circle-mini`...
4. We are starting with about a dozen icons that have been asked for in the past and that we could use in Clarity today. Additional "mini" icons will be reviewed on a request-by-request basis.
5. This new set _will only exist in Clarity Core_ icons. `@clr/icons` is not getting any new icons or sets.

## Icon List

We are asking for "mini" versions of the following icons in the styles specified below...

* arrow (outline only)
* calendar (outline and solid)
* check (outline only)
* check-circle (outline and solid)
* error-standard (outline and solid)
* event (outline and solid)
* filter-grid (outline and solid)
* filter-grid-circle (outline and solid)
* info-circle (outline and solid)
* times (outline only)
* warning-standard (outline and solid)

CC: @gnomeontherun @lil-kim

**Comment by lil-kim** [comment]
@mathisscott 
Here's the set of mini-icons. I addressed the issues we discussed in our email yesterday as much as I could within the tiny size.

[mini-icons-23-04-20.zip](https://github.com/vmware/clarity/files/4525377/mini-icons-23-04-20.zip)
