### ISSUE TITLE
DatePicker wrong localization

### ISSUE THREAD

**Issue by epoch79** [vmware/clarity#4446]
## Describe the bug
When I set turkish localization setting from Appmodule like this

import localeTr from '@angular/common/locales/tr';
import localeTrExtra from '@angular/common/locales/extra/tr';
import { registerLocaleData } from '@angular/common';
registerLocaleData(localeTr, 'tr', localeTrExtra);

providers: [
    {
      provide: LOCALE_ID, useValue: 'tr'
    },

I can't see true month names in datepicker.

![image](https://user-images.githubusercontent.com/11553260/78577593-f740af00-7836-11ea-91b6-f5d366845120.png)

But When I set locale to "tr-CY" i can see the tru month names

* Angular: [e.g. 9.1]
* Node: [e.g. 12.13.0]
* Clarity: [e.g. 3.1.0]

**Device:**

* Type: [e.g. Windows]
* OS: [e.g. Windows 10]
* Browser [e.g. chrome]

**Comment by gnomeontherun** [comment]
We don't have a reproduction here, so I'm going to close this as stale. If this issue still exists, please provide a working reproduction for us to review.
