### ISSUE TITLE
Broken "Sketch" file links

### ISSUE THREAD

**Issue by elycruz** [vmware/clarity#4448]
## Describe the bug

Sketch library links are broken on "Get Started" page at:
https://clarity.design/documentation/get-started

## How to reproduce
Click on broken links listed below:
- UI LIBRARY - DARK (): https://github.com/vmware/clarity-assets/raw/master/sketch/light/clarity-library-light-.sketch
- UI LIBRARY - LIGHT (): https://github.com/vmware/clarity-assets/raw/master/sketch/dark/clarity-library-dark-.sketch

1.  Scroll down to "Using Clarity Design Resources" section.
2.  Click on "UI LIBRARY - DARK ()" (see that it leads to "github" 404 page).
3.  Click on "UI LIBRARY - LIGHT ()" (see that it leads to "github" 404 page).

## Expected behavior

Download of sketch files should begin?

## Versions

**App**

Chrome browser (latest).

**Device:**

**Comment by mathisscott** [comment]
I've verified that the links in Github have changed for these files...

They now follow the address in this way...

https://github.com/vmware/clarity-assets/blob/master/sketch/light/clarity-library-light-2.2.0.sketch?raw=true

We need to update this on the website.

**Comment by mathisscott** [comment]
Thanks for reporting this, @elycruz . I tested these links last week so there must've been some update between now and then. The url is different now.

**Comment by elycruz** [comment]
Ah, ok gotcha :).  Updates tend to do this, from time to time lol.  Cool, no prob 👍 :).

**Comment by jeeyun** [comment]
Website updated with new links.
