### ISSUE TITLE
Consider removing Clarity Seed from documentation on V4

### ISSUE THREAD

**Issue by Skripd** [vmware/clarity#4452]
## Describe the issue

_Clarity seed_ has been deprecated for nearly two years. The link in documentation on V2 and V3 is invalid. It's become legacy in favor of schematics. Clarity seed is not a component or a feature on V2 or V3. Consider removing it from documentation on the release of V4.

## How to reproduce

View documentation on the website.

## Expected behavior

New users have a clear understanding on what features are available.

## Versions

**App**

* Clarity: V2, V3

## Additional notes

None.

**Comment by hippee-lee** [comment]
Thanks for filing this.
I looked on the v2/v3 getting started pages but do not see a reference to the Clarity seed. Is there another place that you are seeing it?

**Comment by Skripd** [comment]
![2020-04-08 18_34_07-Clarity Design System - Documentation](https://user-images.githubusercontent.com/8613325/78809725-a1e7d780-79c7-11ea-98c1-c90f7c635053.png)
![2020-04-08 18_33_17-Clarity Design System - Documentation](https://user-images.githubusercontent.com/8613325/78809726-a2806e00-79c7-11ea-8d24-f3d8fc0ca33e.png)

**Comment by hippee-lee** [comment]
@Skripd Thank you!

**Comment by gnomeontherun** [comment]
No longer an issue or resolved in the upcoming website work. Closing as resolved.
