### ISSUE TITLE
Datagrid: Expandable row condition change clears the whole row

### ISSUE THREAD

**Issue by znpopov** [vmware/clarity#4466]
## Describe the bug

When a data grid row is changed from expandable to non-expandable, or vice versa, the data gets cleared from the row.

## How to reproduce

https://stackblitz.com/edit/expandablerows-ngif-jgtpjc

1.  Go to https://stackblitz.com/edit/expandablerows-ngif-jgtpjc
2.  Click on 'Updated Data'.

## Expected behavior

No data should be cleared.

## Versions

**App**

* Angular: [8.2.14]
* Node: [10.19]
* Clarity: [2.3.9]

**Device:**

* Type: [MacBook]
* OS: [macOS High Sierra]
* Browser [Firefox]
* Version [74.0.1]

## Additional notes

The issue seems related to https://github.com/vmware/clarity/issues/3617

**Comment by Shijir** [comment]
closed by #4469

**Comment by znpopov** [comment]
We will need this fix in Clarity 2. Can you please back-port it? 
Thanks!

**Comment by gnomeontherun** [comment]
@Shijir this needs to go into v3 and v2 branches.

**Comment by Shijir** [comment]
Backported into v3 and v2 branches:
https://github.com/vmware/clarity/tree/v3
https://github.com/vmware/clarity/tree/v2
