### ISSUE TITLE
Updates to support different types of search in header

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#447]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior

Headers need to support three types of search elements:
1. Using a search form with pseudo-element search icon and input elements
2. Using a search div with clr-icon (search) and input 
3. Using simple clr-icon search button, right aligned

### Actual behavior

This change needs to be supported in the clarity-ui and implemented on the header documentation page.

**Comment by adityarb88** [comment]
will be fixed with #186
