### ISSUE TITLE
Add output events when Modal become shown or hidden

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#4476]
## Summary

There are tasks when should be done when modal window become shown or hidden. Due to fact that Modal window has animation, it needs time for change state from open to close state:
- OpenStart -> animation -> OpenEnd
- CloseStart -> animation -> CloseEnd

But in Clarity 3 no ability to do something on events OpenEnd or CloseEnd because ClrModal component does not have such output events.

Needs to support these events how it already done in Bootstrap or Angular Material.

## Use case

- Set focus in input field inside of modal window when it is opened.
- Open new modal window when another is closed.

## Examples

https://getbootstrap.com/docs/4.4/components/modal/#events
https://material.angular.io/components/dialog/api#MatDialogRef

## Workarounds

Needs to use setTimeout with delay equal to animation duration.
https://stackblitz.com/edit/clarity-focus-on-view-init

**Comment by gnomeontherun** [comment]
This is a feature coming soon to Clarity Core with the work in our animations. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
