### ISSUE TITLE
Form validation error inside Wizard using <clr-control-error> is not popping up

### ISSUE THREAD

**Issue by dechengc** [vmware/clarity#4480]
## Describe the bug

The issue is observed in Wizard with Form Validation: the input field has class="clr-input ng-pristine ng-invalid ng-touched" but the <clr-control-error> dirctive doesn’t show up.

## How to reproduce

This issue cannot be reproduced in (https://stackblitz.com/@clr-team), but it is observed in (https://clarity.design/documentation/wizards) Wizard with Form Validation section. If you click “WIZARD + FORM VALIDATION” button, in the wizard “Enter a number” step, click “Your number” field, then mouse away and click elsewhere on the same wizard page, the error messaage doesn’t show up as expected. The validation error message will show up when you repeat the click the input field and mouse away.

1. Go to (https://clarity.design/documentation/wizards) Wizard with Form Validation section.
2. Click on “WIZARD + FORM VALIDATION” button.
3. Fill out the name field, then clisk "NEXT" button.
4. In the “Enter a number” page, click “Your number” field, then mouse away and click elsewhere on the same wizard page.
5.  See error: the error messaage doesn’t show up as expected.
6. The validation error message will show up when repeat the click the “Your number” field and mouse away and click elsewhere on the same wizard page.

## Expected behavior

the error message should show up when input field is touched and invalid.

## Versions

**App**

* Angular: 9.1.1
* Node: 10.15.0
* Clarity: 3.1.0

**Device:**

* Type: Macbook Pro
* OS: MacOS
* Browser: Chrome and Firefox
* Version: Chrome 80, Firefox 74

**Comment by bbogdanov** [comment]
Leaving this comment here for future reference:

Even the solution we implement is a workaround, there is one more solution to this bug. By setting `@HostListener('blur')` to `@HostListener('focusout')`. For some reason, the `blur` event on `<input type="number" />` added by `WrappedControl` is called before the`blur` event of  `ngControl`  that sets the `ng-touched`. This is the reason, the component on its first `blur` does not display as `invalid`.
