### ISSUE TITLE
create a util function for checking keyCodes in core

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#4487]
## Describe the bug

We have a couple of places where we are doing checks to see if a key pressed is a certain key (ESC, ENTER, etc). Let's refactor this into a reusable function.

## Expected behavior
Instead of having checks like:
 ```
if (e.keyCode === ESC || e.key === 'Esc') {
   ...
}
```
where `e` is of type `KeyboardEvent` we could have a reusable function, e.g.:
```
if (keyEquals(e, Keys.Escape)) {
   ...
}
```
And the function would check against our dictionary of tuples to check the key in a cross-browser compatible way.

**Comment by mathisscott** [comment]
We need to get #4479 merged before we do this...
