### ISSUE TITLE
Provide validation for text areas

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#45]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
```

The following tasks will be needed.
- [ ] Design form validation/errors for textareas
- [ ] Implement error/validation messages for textareas
- [ ] Add Documentation on the website

### Expected behavior
How does a user provide validation to a text area. In an input field, there is an error icon to the right of the field which provides a tooltip with information about the error, how does that match to text areas?

### Actual behavior
No validation yet.

**Comment by reddolan** [comment]
Here is the recommended design for validation on a textarea

![text-area](https://cloud.githubusercontent.com/assets/1858226/25927181/fed35b24-35a8-11e7-8b02-f4852b6e2f1a.png)

**Comment by gnomeontherun** [comment]
This is no longer valid and similar work will resolve this with forms refactoring.

**Comment by gnomeontherun** [comment]
This is a feature only available in newer forms 0.13+. We recommend updating to newer forms to enable textarea validation, or work to implement your own validation if you are unable to update.
