### ISSUE TITLE
Buttons in header do not inherit the headers bg color

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#450]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Buttons used in the header should inherit the same bg color as the header. 
Multiple buttons used in the header actions container should have a separator.

Resolve the difference between the clarity-angular component:

```
<clr-dropdown class="dropdown bottom-left">
                    <button class="nav-text" clrDropdownToggle>
                        john.doe@vmware.com
                        <clr-icon shape="caret down"></clr-icon>
                    </button>
                    <div class="dropdown-menu">
                        <a href="javascript://" clrDropdownItem>Preferences</a>
                        <a href="javascript://" clrDropdownItem>Log out</a>
                    </div>
                </clr-dropdown>
```

and the clarity-ui element:
```
<div class="header-actions">
<div class="header-actions">
            <clr-dropdown [clrMenuPosition]="'bottom-right'">
                <button class="nav-icon" clrDropdownToggle>
                    <clr-icon shape="cog"></clr-icon>
                    <clr-icon shape="caret down"></clr-icon>
                </button>
                <div class="dropdown-menu">
                    <a href="javascript://" clrDropdownItem>About</a>
                    <a href="javascript://" clrDropdownItem>Preferences</a>
                    <a href="javascript://" clrDropdownItem>Log out</a>
                </div>
            </clr-dropdown>
        </div>
```

### REF: _header.clarity.scss 
* Line  number 321 (ish)
* Also, determine if its possible to reduce the nesting to only three levels 

### Actual behavior / Reproduction
See the general Issue example here: https://plnkr.co/edit/UgbEXl?p=info

* **Angular version:** 2.0.X

* **Clarity version:** 
0.8.x

* **OS and version:** 

* **Browser:** [all]

**Comment by adityarb88** [comment]
Hi @hippee-lee. You missed adding the `.dropdown-toggle` class on all the dropdown toggles. Also there were some cases where the toggle and the menu weren't wrapped by the `.dropdown` class. Refer this: https://plnkr.co/edit/yPMACQ0Z8SZDeRjIHH91?p=preview for more information. Closing based on this.
