### ISSUE TITLE
core: common strings

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#4502]
# Core: i18n & a11y internal strings

Prototype: https://stackblitz.com/edit/typescript-kbwbop 

Many but not all components need to have a specific label for a11y. Example, a modal close button should give more context to a screen reader user than just "close modal". Instead it should specify its intent. Example, "Close VM setup modal". Other components such as the date-picker will internally need strings that can be switched out for i18n but may not be specific to the context usage.

I18n also has similar needs in that these internal strings need to be set and dynamically changed. This API proposal unifies both into a single API that allow customization of internal strings at a global and component instance level.

## API

Each component expose a `i18n` property that can will contain an object of all i18n strings
for that component. This object would be initialized with default values from the global `CommonStringsService`. This would allow all i18n values to be overridden at a global level or component level and not require individual attrs/props to be added or removed from the component public API.

```typescript
export class CdsDatepicker extends LitHtml {
  @i18n() i18n = CommonStringsService.keys.datepicker; 
}
```

```html
<cds-datepicker cds-i18n="{ nextMonth: 'next available month', toggle: 'toggle schedule calendar' }">
  <label>Today</label>
  <input tyle="date" />
</cds-datepicker>
```

This API allows i18n strings to be customized at a component level and global level. They can be customized for i18n or a11y specific reasons with no change in the public API.

## i18n decorator

The `@i18n` decorator uses the `@property` decorator internally but provides additional behavior. 

1. Use component default values and merge any custom overridden value via the component or `ComonStringsService`.
2. Provide a way to mark certain strings as required per instance for a11y.  

The lit elements property decorator which i18n will use automatically supports simple flat objects in attributes or JS properties. https://lit-element.polymer-project.org/guide/properties#initialize-property-values-from-attributes-in-markup 

```javascript
const datepicker = document.querySelector('cds-datepicker');
datepicker.i18n = myCustomI18nValues;
```

The flat object styles make the API stable and easy to customize but also easy to support i18n with server side rendering systems to serialize to the component

```cshtml
// C# razor view
<cds-datepicker @Html.Attr("cds-i18n", model.i18n)></cds-datepicker>
```

## Validation

Some i18n strings could be required to be customized per the usage for a11y. The i18n decorator could take a list of required strings to warn the developer to set per component. This may need to be a future feature to add on depending on a11y requirements.

```typescript
export class CdsModal extends LitHtml {
  @i18n({ required: ['close'] }) i18n = CommonStringsService.keys.modal; 
}
```

```html
<cds-modal cds-i18n="{ close: 'close vm setup modal' }"></cds-modal>
```

**Comment by mathisscott** [comment]
This looks great. Make it so!
