### ISSUE TITLE
Datagrid header breaks with open detail pane if first column is hidden

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#4503]
## Describe the bug

The datagrid header breaks with open detail pane if the first column is hidden. 

With hidden first column:

![Screenshot 2020-04-23 at 11 07 57](https://user-images.githubusercontent.com/3655915/80081129-d1afe700-8552-11ea-88de-7686aea8eb71.png)

Without hidden first column:

![Screenshot 2020-04-23 at 11 08 08](https://user-images.githubusercontent.com/3655915/80081182-e3918a00-8552-11ea-8899-eb9f3c7977f7.png)

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-v3-light-theme-kwgxiw
2.  Click on one of the arrows to expand the detail pane
3.  See error

## Expected behavior

Show the first visible column next to the detail pane.

## Versions

**App**

* Angular: 9.0.4
* Clarity: 3.1.0

**Comment by gnomeontherun** [comment]
I can see this but the expectation is that you would not to allow first column to be hideable. There is some work coming soon to address this with reordering columns where should should be resolved. 

I'm going to close this in favor of the work in #4020
