### ISSUE TITLE
Datagrid, when should we use detailpane over expandable row ?

### ISSUE THREAD

**Issue by MonsieurMan** [vmware/clarity#4507]
I was reading through the doc to choose a solution for displaying additional details and I feel like the doc is maybe missing some guidelines on when we should use detailpane over expandable row.

I know you guys have great ux design and I'd like to hear the difference you make between the two.

My feeling is that expandable row is more for raw information, whereas the detail pane could be a little bit richer visually and maybe have some user interaction.

Thanks for the good job you do on the design system o/

**Comment by gnomeontherun** [comment]
We should add some content around this, but the short answer is always use Detail Pane as it provides proper accessibility unlike expandable rows. We may never remove expandable rows, but don't recommend using it for anything new.

**Comment by milesich** [comment]
You can have multiple expandable rows open and they don't hide any columns. I could be useful if you have a long horizontal content and you want to compare it between rows.
