### ISSUE TITLE
Add additional use cases for search elements in the header

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#451]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
There are three identified use cases for using search elements in the header:

1. The header needs a search form (container) with label (:before pseudo element to create the search icon) and an input.
2. The header needs a search container with a clr-icon shape="search" and an input. 
3. While 1 & 2 are structurally different they should respond the same.
4. The header needs to support a search container with a button and the container should be right aligned to the header-actions container. 

### Actual behavior
Uncovered these enhancements when updating the documentation for header page.

### Reproduction of behavior
https://plnkr.co/edit/UgbEXl?p=preview

## Note
The header docs page should be updated with the new markup to reflect these changes.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
0.8.x

* **OS and version:** 

* **Browser:** [all]

**Comment by hippee-lee** [comment]
@adityarb88 Did I forget anything?

**Comment by adityarb88** [comment]
will be fixed with #186
