### ISSUE TITLE
Stepper closes for dynamic fields

### ISSUE THREAD

**Issue by mathisloge** [vmware/clarity#4512]
## Describe the bug

I don't really know if this is a bug or if I'm missing something. But in the provided example you will see the stepper closing, when adding new fields to the form.

This doesn't happen when you put the dynamic field page on the first page.

## How to reproduce

* AppUrl: https://clarity-v3-light-theme-dkrgag.stackblitz.io
* Editor:  https://stackblitz.com/edit/clarity-v3-light-theme-dkrgag

1.  Go to the provided example
2.  Click on 'NEXT'
3.  Click on 'ADD USER'
4.  See error

## Expected behavior

I'm expecting that the stepper page won't close

## Versions

**App**

* Angular: 9
* Clarity: 3.0 and 3.1

**Device:**

* OS: Windows
* Browser edge chromium

**Comment by exequiel09** [comment]
I encounter this problem as well. In other situations, using `emitEvent` option set to `false` is enough. However, this is really an annoying bug especially when you're using a `FormArray` instance inside stepper panel. Could be easily solvable if Angular have `emitEvent` functionality for FormArray mutation functions as well (https://github.com/angular/angular/issues/23336)
