### ISSUE TITLE
Allow custom width of opened detail pane in a data-grid

### ISSUE THREAD

**Issue by prgmtx** [vmware/clarity#4514]
Currently in a DataGrid with DetailPane "When the pane is open, it takes 2/3 of the width of the Datagrid" the 2/3 width is hardcoded. 

It would be suitable to enable to override the width to a custom value.

**Comment by gnomeontherun** [comment]
Hi @prgmtx, thanks for the request. It helps us if you use our issue templates and fill out more details about the request.

The width is currently designed to be fixed based on the original design. However, it is possible to override with CSS in the app if needed.

Closing as can be customized, but design is explicit about 2/3 width.
