### ISSUE TITLE
Old Datagrid pagination API causes ExpressionChangedAfterItHasBeenCheckedError in Ivy

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#4515]
## Describe the bug

The following is Datagrid's old pagination API:
```html
 <clr-dg-footer>
          {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
          of {{pagination.totalItems}} users
          <clr-dg-pagination #pagination [clrDgPageSize]="2"></clr-dg-pagination>
</clr-dg-footer>
```

This API causes the ExpressionChangedAfterItHasBeenCheckedError if used with Ivy enabled. The underlying issue came with Angular 9's release. The bug has been reported here: https://github.com/angular/angular/issues/34821

However, users can avoid this issue if they use Datagrid pagination's new API:

```html
<clr-dg-footer>
    <clr-dg-pagination #pagination [clrDgPageSize]="10">
        <clr-dg-page-size [clrPageSizeOptions]="[10,20,50,100]">Users per page</clr-dg-page-size>
        {{pagination.firstItem + 1}} - {{pagination.lastItem + 1}}
        of {{pagination.totalItems}} users
    </clr-dg-pagination>
</clr-dg-footer>
```

So to resolve this issue, we could either wait for a bug fix from Angular or deprecate the old Datagrid pagination API and replace all examples of it with the new API examples on our documentation.

## How to reproduce

The issue is visible in our client app if Ivy mode is enabled.

## Expected behavior

There must be no ExpressionChangedAfterItHasBeenCheckedError errors.

## Versions

**App**

* Angular: ^9.x
* Clarity: ^3.x

**Comment by gnomeontherun** [comment]
Closing as we haven't had any issues or reports of this problem, and the workaround is straightforward.
