### ISSUE TITLE
Grid filter placeholder?

### ISSUE THREAD

**Issue by duzenko** [vmware/clarity#4518]
## Summary

Would it be possible to add placeholder text to filter input like on the screenshot attached? I don't see any way to achieve this with data grid out of the box.

![image](https://user-images.githubusercontent.com/1481807/80503585-bd1c8600-897a-11ea-8197-b7b20728058e.png)

**Comment by gnomeontherun** [comment]
The default string/number filters do not have an API for this at this time. Given our future movement towards a different filtering pattern (#1632), I don't know if we'll make this change before that feature is implemented.

Either way, a workaround is to make a custom filter so you can control the contents of the popup to whatever your needs are.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
