### ISSUE TITLE
Datagrid with expandable rows gets messed up column widths when cells are truncated

### ISSUE THREAD

**Issue by irinanik9** [vmware/clarity#4524]
I have a datagrid with expandable rows, where some columns will contain long text. I want to force the grid to show each item on a single line so  I use text overflow with ellipsis for the columns with long text. However, this causes the columns to be sized really bad: 
1) the ones which are truncated have minimal width 
2) the remaining columns have big width and the datagrid overflows

Everything looks well if I just remove the clr-dg-row-detail element!

Here is a stackblitz example: https://stackblitz.com/edit/angular-zudsut?file=src%2Fapp%2Fapp.component.html

1.  Have a clr-datagrid with multiple columns
2.  Apply custom CSS on one or more clr-dg-cell elements to truncate long text contents:
         white-space: nowrap;
        overflow: hidden !important;
        text-overflow: ellipsis;
3.  Populate the datagrid with data and observe the layout - all columns are properly distributed and take as much width as needed. 
4. Add a <clr-dg-row-detail *clrIfExpanded> with any content 
3. Populate the datagrid with data and observe the layout. Notice the messed up column widths:
   3.1. The columns which are truncated have small width just to accomodate the header text
   3.2. The remaining columns have too long width making the datagrid to overflow in width and to have horizontal scrollbar

<img width="1663" alt="ActualBehavior" src="https://user-images.githubusercontent.com/64581347/80692147-dd168b80-8ad9-11ea-8846-23c98c799a26.png">

## Expected behavior

The problem occurs only for datagrids with expandable rows. I expect the columns to be rendered properly and in the same way as if the grid has no expandable rows.

<img width="1665" alt="ExpectedBehaviour" src="https://user-images.githubusercontent.com/64581347/80692155-df78e580-8ad9-11ea-83c4-71feaa7d3b3b.png">

## Versions
**App**

* Angular: 8.2.14
* Node: 10.15.3
* Clarity: 2.3.6

**Device:**

* Type: MacBook
* OS: 10.14.6
* Browser: chrome
* Version: 81.0.4044.129

**Comment by hippee-lee** [comment]
Automatic sizing for content projected into tables relies on how browsers size content in tables. Specifically, any content projected into a datagrid will go through a phase that uses the browser to calculate column width. So when the overflow is hidden in the stackblitz example the rendering calculation for the column with long text will default to the minimum column width. 

The correct way for this situation is to set the column width from the app side. I modified the example in one way to solve this use case:  I used `break-word` for the white-sapce and set a column width of 200px. This give the flexibility of a width chosen by the app but obviously shows on more than one line so it may not work for you. If something more dynamic is needed, the app should do the width calucation on the content projected into the cells for that collumn to find the desired width on its side before passing or updating the data to the datagrid. 

``` html
    </clr-dg-column>
      <clr-dg-column [style.width.px]="400">
      <ng-container *clrDgHideableColumn="{hidden: false}">
        Title
      </ng-container>
    </clr-dg-column>
```
Here is the modified example: https://stackblitz.com/edit/angular-lju2kc

I'm closing as the column width calculation is working as expected in this scenario.
