### ISSUE TITLE
TreeView: RangeError: Maximum call stack size exceeded...

### ISSUE THREAD

**Issue by BobRam** [vmware/clarity#4530]
Hi,

RangeError: Maximum call stack size exceeded
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:267)
    at SafeSubscriber.next (Subscriber.ts:207)
    at Subscriber._next (Subscriber.ts:139)
    at Subscriber.next (Subscriber.ts:99)
    at Subject.next (Subject.ts:70)
    at RecursiveTreeNodeModel.fetchChildren (recursive-tree-node.model.ts:65)
    at RecursiveTreeNodeModel.get [as children] (recursive-tree-node.model.ts:75)
    at ClrTreeNode.isExpandable (tree-node.ts:106)
    at Object.eval [as updateDirectives] (ClrTreeNode.html:15)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:385)

(sometime several times and sometime with different call stack)

on recursive TreeView loaded with some data (not too big)

`<clr-tree-node *clrRecursiveFor="let node of root; getChildren: getChildren" >
    <a class="clr-treenode-link" >{{node.name}}</a>
  </clr-tree-node>
</clr-tree>`

[https://stackblitz.com/edit/gh-issue-4397-g7pfc2](https://stackblitz.com/edit/gh-issue-4397-g7pfc2)

tried on
clarity:   3.0.1, 3.1.1
angular 9.0.7, 9.1.4

**Comment by hippee-lee** [comment]
Hi @BobRam - is there a specific set of steps that need to happen to get the error? The stackblitz isn't showing any errors for me in the console.

**Comment by hippee-lee** [comment]
Actually, scratch that last comment, I tried it in Chrome and see the error. I'm not seeing it in Firefox. Thanks for the report, I'll mark this for investigation.

**Comment by BobRam** [comment]
It also occurs in FireFox in my app, but not in stackblitz


ERROR InternalError: "too much recursion"
    Angular 4
        handleError
        detectChangesInternal
        detectChanges
        childrenFetchSubscription
    RxJS 5
        __tryOrUnsub
        next
        _next
        next
        next
    Angular 98
        fetchChildren
        get children
        isExpandable
        ClrTreeNode_Template
        executeTemplate
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        detectChangesInternal
        detectChanges
        childrenFetchSubscription
    RxJS 5
        __tryOrUnsub
        next
        _next
        next
        next
    Angular 16
        fetchChildren
        get children
        isExpandable
        ClrTreeNode_Template
        executeTemplate
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshDynamicEmbeddedViews
        refreshView
        refreshComponent
core.js:6237:19
    Angular 4
        defaultErrorLogger
        handleError
        next
        schedulerFn
    RxJS 5
        __tryOrUnsub
        next
        _next
        next
        next
    Angular 11
        emit
        onHandleError
        invoke
        run
        runOutsideAngular
        onHandleError
        handleError
        runTask
        invokeTask
        invoke
        timer

​

**Comment by jtruffot** [comment]
Hi! I had the same problem with a large tree (~ 500 nodes). I used [lazy-loading recursive trees](https://clarity.design/documentation/tree-view#lazy-loading-recursive) without async or observables. That works for me.

You can control the node's expand with `clrExpanded` attribute. In your Stackblitz's example, this gives:

```
<clr-tree [clrLazy]="true">
  <clr-tree-node *clrRecursiveFor="let node of root; getChildren: getChildren"
  [clrExpanded]="true">
    <a class="clr-treenode-link" >{{node.name}}</a>
  </clr-tree-node>
</clr-tree>
```

**Comment by BobRam** [comment]
@jtruffot thank you, that works for me too.

**Comment by gnomeontherun** [comment]
I'm going to close this as it sounds like this is resolved, and it does make sense that there might be a problem with loading too many nodes without using lazy mode. Thanks for the help @jtruffot and recommendation is to use lazy mode to avoid hitting the call stack limit.
