### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by williamgomez71** [vmware/clarity#4536]
hi,

The next link related to _variables.clarity is broken, where I can find all _variables.clarity.scss

https://github.com/vmware/clarity/blob/master/src/clr-angular/utils/_variables.clarity.scss

Thanks !!

**Comment by KANekT** [comment]
@williamgomez71 

https://github.com/vmware/clarity/blob/master/packages/angular/projects/clr-angular/src/utils/_variables.clarity.scss
