### ISSUE TITLE
Stepper allows to interact with the status of their clr-stepper-panels

### ISSUE THREAD

**Issue by luis-cortina** [vmware/clarity#4539]
## Summary

I want to be able to modify the status of the Stepper Panels from the component code(i.e. set some panels as successful and therefore the user is allowed to click on them instead of having to visit each pane)
![image](https://user-images.githubusercontent.com/25346332/81223523-59f6a900-8fa3-11ea-8e91-ecd7fbc9ff7d.png)

- What is the change? Expose the status of the clr-stepper-panel so they can be changed from code.
- Why should it go in Clarity? I think is a greate feature addition to the stepper.
- Does this change impact existing behaviors? If so how? I don think it does.
- If this change introduces a new behavior, is this behavior accessible? Yes

## Use case

I have a stepper to guide the user in the creation of a complex object (i.e. a Quote or Estimation Process) I want the user to be able to save the status and when they return to the stepper, all the panels that have been visited(not part of this request, dev should track that) should be interactable by then.

## Examples

Pretty standard request, I don't think it applies to other elements.

## Workarounds

I couldn't find one.

**Comment by luis-cortina** [comment]
Thinking about it a bit more, it would be nice to have more programatic control over the stepper, close and open panels, disable panels based on rules, etc.

**Comment by gnomeontherun** [comment]
The Stepper uses Angular forms to control its state, so much of the Stepper simply reflects the state of the form. If you have three groups that are all considered valid, it would show as validated.

The accordion is more general purpose, and maybe that is another option for you to add the icons and behaviors you wish to see there.

**Comment by rob3c** [comment]
@gnomeontherun The stepper panels don't seem to reflect the angular FormGroup state.

For example, here's a screenshot of the reactive forms sample in the docs showing a conflict between the step 1 panel icon and the panel's control states:

![clarity stepper panel status possible bug](https://user-images.githubusercontent.com/1098077/90705462-f9912c00-e260-11ea-9b99-de6b6da9e47b.png)

The step 1 controls are invalid - and therefore the containing formgroup bound to the panel is invalid - but the panel icon contains a green checkmark.

This was done by first entering valid data in step 1, then clicking next to step 2, then returning to step 1 and deleting the valid data to make the step 1 formgroup invalid again. Unfortunately, the panel icon still indicates it's valid and complete.

Is this intended behavior or a bug?

**Comment by gnomeontherun** [comment]
@rob3c please provide us with a reproduction and open a new issue so we can investigate, thanks!
