### ISSUE TITLE
Enhance password field

### ISSUE THREAD

**Issue by nikhildhankani** [vmware/clarity#454]
```
[ ] bug
[x] feature request
[ ] enhancement
```
Password input field should have an attribute using which developers can show/hide a see password icon. This is a common design in modern password fields and also helps in improving the security of application.

**Comment by reddolan** [comment]
A eye-show/eye-hide toggle at the end of a password field would ideal. Clicking the control would swap the view of the input field from one to another and the icon toggle would swap as well. 

```'eye-show' icon showing: password state (dots)
'eye-hide' icon showing: text field state (alphanumeric)``` 

@mathisscott mentioned that we would need to be conscious of native browser controls that do this for the user (Edge?)

**Comment by mathisscott** [comment]
need to know what this will look like. where it sits in reference to the text field. also how it conflicts with existing functionality across OSes.

**Comment by gnomeontherun** [comment]
This has been completed in new forms.
