### ISSUE TITLE
Basic Core example doesn´t work

### ISSUE THREAD

**Issue by luisartola** [vmware/clarity#4542]
## Describe the bug

I have followed [these instructions](https://github.com/vmware/clarity/tree/master/packages/core)  and there is no modal component in the node_modules @clr/core, so the import fails.

**Comment by mathisscott** [comment]
The modal was just recently merged into master and is not yet available in the `@clr/core` package. It will be published with the 4.0 release.

Try the instructions in our online documentation: https://clarity.design/storybook/core/?path=/docs/documentation-getting-started--page
