### ISSUE TITLE
Add a simple demo app to core demos that we can use to test IE

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#4547]
## Summary

- What is the change?

Add a simple demo app to the core demos that we can use to test the web components in IE.

The app can be empty. We can add what we want to it locally for testing.

We should be able to launch it for local IE testing from terminal.

The app doesn't have to be on a framework. This is left to the implementer's discretion.

- Why should it go in Clarity?

Storybook is a pita to run locally in IE.

- Does this change impact existing behaviors? If so how?

Nope.

**Comment by mathisscott** [comment]
Given that our IE11 testing matrix for Core ends with version 4. Is this still a priority?

**Comment by mathisscott** [comment]
@coryrylan

**Comment by coryrylan** [comment]
No longer needed.
