### ISSUE TITLE
Long alerts on IE11 are cropped

### ISSUE THREAD

**Issue by aruseff** [vmware/clarity#4548]
## Describe the bug
Longer alerts (more than a line) in the IE11 are shown with a scroll. And the issue is when we put the alerts inside a div with .main-container class then the scroll is hidden and the text is just cropped.
Same behavior is observed on multiple alerts with the arrow.
All the described cases are working consistently well on other browsers.

## How to reproduce

```
<div class="main-container">
  <clr-alerts>
    <clr-alert [clrAlertType]="'info'" [clrAlertAppLevel]="true">
      <clr-alert-item>
        <span class="alert-text"><strong>Title of the alert bot in app level.</strong> - Lorem Ipsum is simply dummy
          text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever
          since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
          It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
          unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
          passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem
          Ipsum.</span>
        <div class="alert-actions">
          <button class="btn alert-action">Button title</button>
        </div>
      </clr-alert-item>
    </clr-alert>
  </clr-alerts>
</div>
```
![image](https://user-images.githubusercontent.com/9435825/81274655-41e16100-9059-11ea-87df-75521ddc9e61.png)

## Expected behavior
This image is taken from Microsoft Edge.Version 84.0.505.0 (Official build) canary (64-bit) (Chromium)

![image](https://user-images.githubusercontent.com/9435825/81274244-b10a8580-9058-11ea-992c-064943e28280.png)

## Versions

**App**

- Angular: 7.0.0
- Node: 10.16.0
- Clarity: 1.0.5

**Device:**

- OS: Windows 10
- Browser: IE
- Version: 11

**Comment by gnomeontherun** [comment]
Have you tried this on the latest Clarity v1 (or more recent versions of Clarity)? Otherwise can you setup a demo for us to triage?

**Comment by aruseff** [comment]
Hello @gnomeontherun, here is the demo I prepared - https://github.com/aruseff/clarity-demos. It is a GitHub project as I couldn't make stackblitz work for IE11.

**Comment by hippee-lee** [comment]
Hi @aruseff - I checked the demo provided on IE 11 and can see the issue. I also checked a simple Clarity app with latest Clarity/Angular and its still there. 

This issue is with how IE11 deals with `flex-basis: auto`. 
I'll submit a PR with a fix shortly.
