### ISSUE TITLE
DataPicker (more dynamic DatePicker)

### ISSUE THREAD

**Issue by quanglddev** [vmware/clarity#4549]
#4549 Summary
- What is the change?
This is a new component. The reason is we can reuse code that we already have in the date picker. The DataPicker will have the similar look and functions as DatePicker, but the creator can have the chance to replace date/month with their own data. One good example is the Emoji/Icon Picker. 
- Why should it go in Clarity?
I believe this is one essential component and enterprise website usually have toolbars, which needs an icon picker most of the time if it's a web-app.
- Does this change impact existing behaviors? If so how?
It doesn't chance anything.
- If this change introduces a new behavior, is this behavior accessible?
No new behavior from DatePicker.

## Use case

So developers can have their own data picker without using any external library.

## Examples

I don't know much about designing but I can try if you want. Otherwise, imagine no date, just emojis (small data) and months are categories.

## API

API is the same as DatePicker

## Implementation plan

I will be examining the DatePicker code and build from there.

## Conclusion

It would be helpful if I have some help from anyone in the Clarity Team. This is such an amazing library so thank you all and I want to contribute to it too. Please let me know if you have any suggestions!

**Comment by gnomeontherun** [comment]
Hi @quanglddev, thanks for making a suggestion. I am not very clear on the details here or the use case. Why is a generic 'picker' something that Clarity should provide? The date picker is built specifically for picking dates, so I don't think its likely to work by trying to build something similar to it. 

To move forward, I need a lot more detail about _why_ this is valuable and the use cases before we could consider this as something that Clarity should adopt. Then we'd have to review the design and use cases carefully before we develop anything.

**Comment by quanglddev** [comment]
Hi @gnomeontherun !
Thank you so much for the reply. I believe this is extremely helpful since there are many applications to it: emoji picker, color pickers etc.
You can find a similar version here: https://github.com/tech-advantage/ngx-icon-picker

Use cases:
1. The component gets a list of string and display it in a grid and have pages to navigate around.
2. Optional categories also so user can switch around categories.

I’m not experienced with use cases so please follow up if you want more information. Thank you.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
