### ISSUE TITLE
DataGrid Cell Misaligned

### ISSUE THREAD

**Issue by svbach** [vmware/clarity#4550]
## Describe the bug

This problem is with dynamic datagrid.  The datagrid renders just fine with the initial set of data.   When the data is refreshed with additional rows the first column of the newly added row is renders as the last row. The rest of the columns shifted to the right.  When all rows are removed, the content of clr-dg-placeholder gets rendered but the rows were not removed.  

## How to reproduce

See https://stackblitz.com/edit/angular-clr-datagrid?file=src%2Fapp%2Fmy-datagrid.component.html

1.  The datagrid is initially rendered with one row.  There is a table below the datagrid with the same data.
1.  Add a new row by completing all 3 fields (name, type, categories) and click the Add App button.
2.  The newly added row has the 3rd column rendered as the first column.  The table below has the correct behavior.
3.  Click the Clear Grid button.
4.  The datagrid rows were not removed as expected.  The table behaves as expected.

## Expected behavior

Cell content rendered in the right column.

**App**

- Angular: 8.2.14
- Node: 8.9.4
- Clarity: 2.4.1

**Device:**

- Type: Macbook
- Browse:r Chrome

**Comment by gnomeontherun** [comment]
This was resolved by https://github.com/vmware/clarity/pull/4540 and is available if you update to Clarity 2.4.2! I tested in your stackblitz by updating and it is working now. Thanks for the report!

I'm going to close as resolved.

**Comment by svbach** [comment]
That you @gnomeontherun.  Version 2.4.2 fixes the problem.
