### ISSUE TITLE
Full Screen Wizard css?

### ISSUE THREAD

**Issue by luis-cortina** [vmware/clarity#4558]
I had some help from @mathisscott to create a full screen modal here #1344. 
Any chance I can get some help to do the same for a full screen wizard?

Luis

**Comment by mathisscott** [comment]
@luis-cortina 
What version of Clarity are you using?

**Comment by luis-cortina** [comment]
This css was good enough for me.

.modal-dialog.modal-xl {
  width: 100%;
}

.clr-wizard.wizard-xl .modal-dialog {
  height: 100%;
}
