### ISSUE TITLE
Wizard triggers load on its first page twice when init

### ISSUE THREAD

**Issue by zivanov123** [vmware/clarity#456]
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
onLoad of the first page should be called once

### Actual behavior
The first page's onLoad is called twice when the wizard is opening.
The problem is that in the wizard - selectTab()  is called in addition to the Tab's implementation of setUpLinksAndContents:
1. wizard code - https://github.com/vmware/clarity/blob/6536b1156ea729c682e183ba3bd3807c2cc95461/src/clarity-angular/wizard/wizard.ts#L98

2. tab - https://github.com/vmware/clarity/blob/6536b1156ea729c682e183ba3bd3807c2cc95461/src/clarity-angular/tabs/tabs.ts#L81

This is causing first page to retrieve it's data twice.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  LATEST

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Fixed with wizard refactor #156 in 0.9.0.
