### ISSUE TITLE
Datepicker is opened behind modal

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#4566]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

https://stackblitz.com/edit/clarity-v3-datepicker-in-modal

1. Click the calendar icon
2. See the calendar popup opening behind the modal

Currently, `.modal` has a `z-index: 1050` and `.datepicker` has only `z-index: 1000`

## Expected behavior

The datepicker should work inside a modal as well.

## Versions

**App**

- Angular: 9.1.6
- Clarity: 3.1.2

**Comment by gnomeontherun** [comment]
This is resolved via #4703.
