### ISSUE TITLE
How to disable client side sorting for specific columns

### ISSUE THREAD

**Issue by namitabandal** [vmware/clarity#4571]
## Summary

_Summary the request and address the questions as appropriate._

- What is the change?
- Why should it go in Clarity?
- Does this change impact existing behaviors? If so how?
- If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by bdryanovski** [comment]
You could read more on how to use the `ClrDatagrid` [here](https://clarity.design/documentation/datagrid/structure)
