### ISSUE TITLE
The built in clrDgItem attribute on columns adds both sorting and filtering by design. There may be some use cases that only sorting or only filtering is needed.

### ISSUE THREAD

**Issue by namitabandal** [vmware/clarity#4574]
## Summary

_Summary the request and address the questions as appropriate._

- What is the change?
- Why should it go in Clarity?
- Does this change impact existing behaviors? If so how?
- If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by gnomeontherun** [comment]
Hi @namitabandal what is the reason to disable the functionality? What are the use cases and can you help us understand more about why we should consider this?

**Comment by sdurnov** [comment]
I pretty much see it making sense when you need sorting, but you implement custom filters with some complex logic outside of a Datagrid's UI, so built-in filtering may not only be redundant, but it may not work as expected.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
