### ISSUE TITLE
Clarity Stepper resets the form on submit when inside a modal

### ISSUE THREAD

**Issue by anilrautvc** [vmware/clarity#4592]
## Describe the bug
I am using clarity stepper component version 3.1.2, i have 4 pages or steps in the stepper. When i am done with all the steps in submit button click i am clearing the form, looks like i am doing something wrong in clearing out the form.

_A clear and concise description of what the bug is, and the conditions when it occurs._
When i open the stepper which is on top of a CLRMODAL popup, i am clicking the close button on top of the modal right hand corner, i am doing this twice after opening the modal. Then for the third time when i open the modal popup in my first step i added the required field and clicked next, at this point the first step is not collapsing by the accordian and moving to the second step. In the console i can notice following error :-
![image](https://user-images.githubusercontent.com/35384163/81751182-8bc0b180-9474-11ea-8ee6-a5e96dd7d73e.png)
![image](https://user-images.githubusercontent.com/35384163/81751383-ece88500-9474-11ea-8574-8c1952bff08f.png)
Even the UI looks pretty distorted 
![image](https://user-images.githubusercontent.com/35384163/81751312-ce828980-9474-11ea-9b3a-1cd43328f14a.png).

In the last page of my stepper i have a Summary page where i shows the last steps selected items but last 2 steps list items are not showing up on the summary page.

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._
https://stackblitz.com/edit/clarity-v3-light-theme-hra5bn

1.  Go to 'https://stackblitz.com/edit/clarity-v3-light-theme-hra5bn'
2.  Click on '....' The Create Button. Open the modal twice and close the modal dialog twice by clicking the right hand top corner close button. Third time after opening the modal by clicking the Create button, just enter required details in 1st step and click Next button you can see in console toggle error and the UI looks bad.
![image](https://user-images.githubusercontent.com/35384163/81752423-07236280-9477-11ea-8a8a-c82183bff36c.png)
3.  Scroll down to '....'
4.  See error
You can see toggle error in browser console and UI distorted.

In the last page of my stepper i have a Summary page where i shows the last steps selected items but previous 2 steps selected items are not showing up on the summary page.
![image](https://user-images.githubusercontent.com/35384163/81752467-1dc9b980-9477-11ea-99d6-06bcbf0d038f.png)

## Expected behavior

_A clear and concise description of what you expected to happen._

I should not see any error on the browser console as toggle error and the UI should not look distorted, the toggling of steps in my stepper should happened without any issues.

The Summary page should list down the previous page selected items.
## Versions

**App**

- Angular: [e.g. 6] = 9.1.6
- Node: [e.g. 8.10.0]
- Clarity: [e.g. 0.12.5] = 3.1.2

**Device:**

- Type: [e.g. MacBook] = Windows
- OS: [e.g. iOS] = Windows 10
- Browser [e.g. chrome, safari] = Chrome
- Version [e.g. 22] = Version 81.0.4044.138

## Additional notes

_Add any other notes about the problem here._

**Comment by anilrautvc** [comment]
Here is another stackblitz sample exactly the copy paste of existing stepper example of clarity design :- https://stackblitz.com/edit/clarity-v3-light-theme-hh77xr.
I need to have the stepper on top of a clrmodal so that i can pop it up with a button click, this is my requirement.

The steps to reproduce is pretty simple just open the popup by clicking create and close it by clicking close button.
Open the popup again and input name and description then click Next you will see toggle error in console and the UI does not refresh.

**Comment by gnomeontherun** [comment]
Something is strange about the stepper in a modal, I haven't fully investigated it yet but also wonder if you want a modal why not use the Wizard which is a modal based workflow? That might be a better solution in general here.

**Comment by anilrautvc** [comment]
Hi @gnomeontherun as i mentioned in my problem description the issue was due to form reset in clr stepper on a clr modal. Then while searching online i found one of your post about resetting forms which seems to be fixed my issue.
https://stackoverflow.com/questions/52459708/how-to-reset-error-state-of-clarity-forms.
But i think we need a proper fix for this as this is a workaround you have provided in this post.
Please keep me posted if you have a proper fix for this now or in future.
