### ISSUE TITLE
Feature Request: Spinner Button

### ISSUE THREAD

**Issue by chunghha** [vmware/clarity#463]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
I would like to have Spinner Button component.

### Actual behavior
Currently Clarity doesn't have the component.

### Use Case
Let's assume that users click on a submit button to get response from backend. And, we want to disable the button for users to prevent resubmission while running and show a proper indication message with Spinner to users like this picture,
![image](https://cloud.githubusercontent.com/assets/24458075/22711756/030ebcb4-ed48-11e6-871d-102d26b7db90.png)

We can do that with Clarity's Button/Spinner currently provided like this code:
```
<span class="input-group-btn">
     <button class="btn btn-outline" type="submit" [disabled]="groupNumber || isValidating">Validate</button>
</span>
<div *ngIf="isValidating">
     <span class="spinner spinner-inline">
     </span>
     <span>
            Validating...
     </span>
</div>
```

Then, by looking at the implementation of "Loading Data" in recently introduced Tree View, I am now thinking that Spinner inside Button might be more giving consistent Look&Feel to my users instead of disabled Button with spinner-inline message.

![image](https://cloud.githubusercontent.com/assets/24458075/22712966/41e0b1fa-ed4c-11e6-8325-e64f3ff8153f.png)

So would you take a look at this request to provide Spinner Button ng component?

https://hashnode.com/post/ux-where-to-display-a-spinner-on-a-button-ciw12i39115c3ob53cfqkzmwb

**Comment by youdz** [comment]
Is this what you're thinking of? https://plnkr.co/edit/lg56rS14hmSrnfUrIZ6g?p=preview

We can look into making some form of shortcut for it, but what I wrote in that plunker is simple enough that this probably won't be that much of a priority.

I think this should go through UX first, to see if there is a specific design that would look better and not "jump around" when the spinner appears.

**Comment by chunghha** [comment]
yes, similar to yours like this:
https://plnkr.co/edit/I1PfWuU9nBFbEp5UK0mr?p=preview

Understood and appreciate for going thru your UX process. I am a programmer so this kind of things are difficult to decide.

**Comment by jaffoneh** [comment]
@reddolan could you provide some UX input here on how a button should behave in this case noticing that the button would "jump" around. Should we even have text when the spinner is there or just have the spinner and disable the button until we bring back an actionable button?

**Comment by reddolan** [comment]
@chunghha When a loading/processing experience happens, the message and/or indicator should appear where the user activated the process. In this case, the best place for this would be within the button itself. The Plunker you shared is what I would recommend. The ellipses at the end isn't necessary though. The spinner give the user sufficient system feedback

**Comment by youdz** [comment]
I think this is a nice feature for an external contribution, if the desired API is well defined. So here goes.

The implementation of this spinner button should use our [reusable loading pattern](https://github.com/vmware/clarity/tree/master/src/clarity-angular/loading). What we want the consumer to write is simply:
```html
<button [clrLoading]="loading">Hello World</button>
```
where they change the `loading` property to true or false based on whatever user action they want, for instance a click on the button.
To obtain this API, all we have to do is write a component with selector `button[clrLoading]` that implements `LoadingListener`.

**Comment by victormejia** [comment]
Trying to look at the example provided by @chunghha but the Plunkr seems broken. Is it pretty much just showing the loading indicator to the left of the text?

**Comment by chunghha** [comment]
Yes, it's pretty much just showing the spinner.
https://plnkr.co/edit/7UvBtSxC05JAK7Wffqeg?p=preview

If Clarity team would agree with, I'd like to have a position input as well such as enum of 'none' (default), 'left' and 'right" for the component to know where to display button text with spinner.

**Comment by reddolan** [comment]
Like I mentioned previously, we recomme removing the ellipses at the end of "Validating". So it would just show "[icon] Validating"

**Comment by victormejia** [comment]
@reddolan awesome, thanks. I'll work on this one if it's alright

**Comment by victormejia** [comment]
@youdz started working on this, but the injected listener in the `Loading` directive keeps coming in as null, not entirely sure why. Here is what the `LoadingButton` component is looking so far:

```javascript
@Component({
    selector: "button[clrLoading]",
    template: `
        <span class="spinner spinner-inline" *ngIf="loading"></span>
        <ng-content></ng-content>
    `
})
export class LoadingButton implements LoadingListener {

    private loading: Boolean;

    startLoading(): void {
      this.loading = true;
    }

    doneLoading(): void {
      this.loading = false;
    }
}
```
