### ISSUE TITLE
Difficult to percieve the difference between toggle checked and unchecked states when it is disabled

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#465]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
It should be easy to determine whether a toggle is switched on or off when it is disabled.

### Actual behavior
Difficult to percieve the difference between toggle checked and unchecked states when it is disabled because both states use a version of gray

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.8.5

* **OS and version:** Windows 10

* **Browser:** all

**Comment by lil-kim** [comment]
Please implement color changes as shown under "New":
![image](https://user-images.githubusercontent.com/23196444/26842474-cd887500-4aa1-11e7-91d8-c117f32f413e.png)
Visual changes reviewed by Jehad and Yen
