### ISSUE TITLE
Pre populating clarity stepper data

### ISSUE THREAD

**Issue by anilrautvc** [vmware/clarity#4670]
## Describe the bug
I am using clarity stepper with 4 steps, 1st step is just 2 input fields but 2nd and 3rd steps are with multiple checkboxes. The validation for the 2nd/3rd step is at least 1 checkbox should be selected.
I am using FormArray for these multiple checkbox. Creation of new object using the stepper works fine for me, my problem is with edit. In edit view i would like to pre populate or check some of the checkboxes out of available checkboxes. I could able to pre populate the data but check/uncheck of checkboxes is collapsing the step all the time which should not be the case. I think i am doing something wrong with pre populating the FormArray. I have tried using the reactive form "patchValue" but its throwing this error :-
![image](https://user-images.githubusercontent.com/35384163/82603188-d4b0ee00-9b77-11ea-8b00-e2b8aa461c4a.png). 
Could someone please take a look and suggest how to do this.

## How to reproduce

STACKBLITZ LINK :- https://stackblitz.com/edit/clarity-v3-light-theme-7rkipd

1.  Go to 'The above stackblitz link'
2.  Click on 'The EDIT Button, which will pre populate data, then click NEXT in 1st step'
3.  In 2nd step Contact Information, try unchecking the already checked checkbox or check a unchecked checkbox.
4.  You will notice the 2nd step Contact Information, is collapsing all the time you select or unselect a checkbox.

## Expected behavior

Select/unselect of checkbox should not collapse the step

## Versions

**App**

- Angular: [9.1.9]
- Node: [e.g. 8.10.0]
- Clarity: [3.1.2]

**Device:**

- Type: [Windows 10]
- OS: [Windows 10]
- Browser [chrome]
- Version [Chrome Version-81.0.4044.138]

## Additional notes

_Add any other notes about the problem here._

**Comment by anilrautvc** [comment]
Hi Jeremy @gnomeontherun Could you please take a look at this issue, please provide your inputs on this.

**Comment by el-davo** [comment]
Does this example help? https://stackblitz.com/edit/clarity-v3-light-theme-dmmngb?file=src%2Fapp%2Fapp.component.ts

**Comment by anilrautvc** [comment]
> Does this example help? https://stackblitz.com/edit/clarity-v3-light-theme-vzkhuq?file=src%2Fapp%2Fapp.component.ts. Includes validation

Hey @el-davo, yes it does, thanks for your help, during my online research i found that if i will mark the form as dirty in the edit button clicked event handler, the stepper collapse/expand works properly for me.
I have updated my stackblitz please take a look in the edit event handler and let me know your thoughts on this.

**Comment by gnomeontherun** [comment]
This looks like an implementation question, as it looks like it is working as expected now. I'm going to close as resolved, thanks!

**Comment by anilrautvc** [comment]
> Does this example help? https://stackblitz.com/edit/clarity-v3-light-theme-vzkhuq?file=src%2Fapp%2Fapp.component.ts. Includes validation
Hi @el-davo i have following issues using this example, could you please help.
1. The validateAtLeastOneChecked you used is throwing error as not a ValidatorFn type.
2. In my actual implementation the stepper data is fetched from a backend service so how can i populate the stepper in the constructor function.

**Comment by el-davo** [comment]
> > Does this example help? https://stackblitz.com/edit/clarity-v3-light-theme-vzkhuq?file=src%2Fapp%2Fapp.component.ts. Includes validation
> > Hi @el-davo i have following issues using this example, could you please help.
> 
> 1. The validateAtLeastOneChecked you used is throwing error as not a ValidatorFn type.
> 2. In my actual implementation the stepper data is fetched from a backend service so how can i populate the stepper in the constructor function.

Updates example - https://stackblitz.com/edit/clarity-v3-light-theme-ypcdfs?file=src%2Fapp%2Fapp.component.ts

1. Sorry, I have fixed this
2. You can dynamically add form controls like in the updates example
