### ISSUE TITLE
pre-commit hook adds unstaged files to the staging zone and then to commit itself

### ISSUE THREAD

**Issue by amalitsky** [vmware/clarity#4679]
## Describe the bug

Files from _Untracked_ and _Changes not staged for commit_ zone are pulled into the _staging_  (and subsequently into commit) by `npm run license:fix` script run by pre-commit githook.

## How to reproduce
1. have three changed files in your tree: one in staged zone (_Changes to be committed_), one in _Changes not staged for commit_ and another one in _Untracked files_:
```
user@mac:clarity$ git status
On branch func-return-value
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   packages/core/src/modal/modal.element.ts

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   packages/core/src/alert/alert-actions.element.ts

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.gitmessage.txt
```
2. run `npm run license:fix` (which is run by husky pre-commit hook)
3. run `git status` once again:
```
user@mac:clarity$ git status
On branch func-return-value
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   .gitmessage.txt
	modified:   packages/core/src/alert/alert-actions.element.ts
	modified:   packages/core/src/modal/modal.element.ts
```
Both un-staged files got moved into the _staged_ (_Changes to be committed_) zone and would have been included into resulting commit had I run `git commit` instead of `npm run license:fix`.

## Expected behavior
Unstaged files are ignored by git hook scripts (linters, checkers, etc) and aren't pulled into the commit automatically.

## Versions
- Type: MacBook
- OS: iOS
- git: 2.21.1

## Additional notes
Not sure whether this is bug or a feature but wanted to check before looking into ways of fixing it.

Thanks

**Comment by coryrylan** [comment]
Yes, this is a bug in the build that has not been addressed yet.

**Comment by hippee-lee** [comment]
Looks like the issue is with this line of the script: https://github.com/vmware/clarity/blob/master/scripts/update-license.js#L34
