### ISSUE TITLE
Provision to prevent dropdown from redirecting

### ISSUE THREAD

**Issue by ajinkyac** [vmware/clarity#468]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[] enhancement
```

### Expected behavior
When a dropdown option is clicked redirection should not happen.
There could be a property to prevent dropdown item click to redirect.
The documentation clearly mentions the usage of dropdown vs. select box, but we have a requirement where we want a dropdown (menu), clicking the items open modal box.

It would be great to use the dropdown instead of a custom button + UL/LI menu.

### Actual behavior
The default behavior of dropdown item click is to navigate away from current view state.

### Reproduction of behavior
Can be reproduced by pulling in clarity-seed project and using a clr-dropdown.

### Environment details

* **Angular version:** 2.0.X
Angular 2.4.1

* **Clarity version:** 
Using latest version of clarity.

* **OS and version:** 
macOS Sierra 10.12.2 (16C67)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
Sorry but I am unable to understand the problem correctly. Can you post the markup of the dropdown that you are using? 

Are you saying that the page redirects after you click on the dropdown item? If yes, are you using anchor tags for dropdown items? If yes, you could also use buttons and that way the page won't redirect:
![image](https://cloud.githubusercontent.com/assets/1426805/22796537/8c9cb590-eeaf-11e6-9de8-4ab6894ffaff.png)

**Comment by ajinkyac** [comment]
@adityarb88 - Yes that works for me.
Thank you for the quick response, appreciate the help.

Closing the ticket based on your inputs.
