### ISSUE TITLE
On clr-dropdown clrCloseMenuOnItemClick breaks if clrDisabled is used

### ISSUE THREAD

**Issue by eemt** [vmware/clarity#4690]
## Describe the bug

When **clrDisabled** is dynamic on a **clr-dropdown-menu**, it appears to break **clrCloseMenuOnItemClick** behavior on **clr-dropdown**.

This code works fine. 
```
<clr-dropdown>
    <button class="btn" clrDropdownTrigger>
        {{currentValue}}
        <clr-icon shape="caret down"></clr-icon>
    </button>
    <clr-dropdown-menu>
        <label class="dropdown-header" aria-hidden="true">Select Item</label>
        <ng-container *ngFor="let s of selections; index as i">
          <div clrDropdownItem aria-label="s.name"
            (click)="setValue(s.name)"
          >{{s.name}}</div>
        </ng-container>
    </clr-dropdown-menu>
  </clr-dropdown>
```

But with this code, the menu no longer closes on item click: 
```
<clr-dropdown>
    <button class="btn" clrDropdownTrigger>
        {{currentValue}}
        <clr-icon shape="caret down"></clr-icon>
    </button>
    <clr-dropdown-menu>
        <label class="dropdown-header" aria-hidden="true">Select Item</label>
        <ng-container *ngFor="let s of selections; index as i">
          <div clrDropdownItem aria-label="s.name"
            [clrDisabled]="s.name === currentValue"
            (click)="setValue(s.name)"
          >{{s.name}}</div>
        </ng-container>
    </clr-dropdown-menu>
</clr-dropdown>
```
NOTES: If the clrDisabled is changed to 
`i === 1` or `s === 'husky'`
the close on click behavior is restored.  Thus, it only seems to be an issue on a dynamic value for clrDisabled.

## How to reproduce

1.  Trivial sample code:  https://stackblitz.com/edit/angular-eemt-clr-dropdown
2.  Below "Make a selection on the dropdown" is a basic dropdown.  Click on it and select any item.
3.  The value updates, but the drop down menu does not close.

## Expected behavior

Drop down menu should close on click (by default or if clrCloseMenuOnItemClick is true).

## Versions

**App**

- Angular: 9
- Clarity: 3

**Device:**

Behavior seems to be the same on any device, any current browser.  Primarily tested in Chrome 83.

## Additional notes

n/a

**Comment by gnomeontherun** [comment]
Hi @eemt thanks for the report. This does seem like a problem, though the use case here makes it look like a select box which we don't support using a dropdown for this purpose, a select box is more appropriate.

An investigation is required, but my first thought is a lifecycle issue that happens with ngFor. There is a workaround to manually close the dropdown.

```
<clr-dropdown>
    <button class="btn" clrDropdownTrigger>
        {{currentValue}}
        <clr-icon shape="caret down"></clr-icon>
    </button>
    <ng-template [(clrIfOpen)]="state">
      <clr-dropdown-menu>
            <button 
              *ngFor="let s of selections; index as i"
              clrDropdownItem 
              aria-label="s.name"
              [clrDisabled]="s.name === currentValue"
              (click)="setValue(s.name)"
            >{{s.name}}</button>
      </clr-dropdown-menu>
    </ng-template>
</clr-dropdown>
```

Then in the controller

```
  state = false;

  setValue(selection: string) {
    this.currentValue = selection;
    this.state = false;
  }
```

**Comment by eemt** [comment]
Thank you for the quick response.  

I have confirmed the work around works!

I'll look at switching to a select.  In retrospect, I'm not sure why dropdown was chosen over select.

**Comment by gnomeontherun** [comment]
This request has merit but we are not currently planning to address it due to it likely requiring a major refactoring and breaking change to implement. Our strategy with Clarity Angular is to support by addressing bugs and focus on stability, but enhancements that require changes are not going to be prioritized. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
