### ISSUE TITLE
Cannot read property 'control' of null when using [(clrDate)]

### ISSUE THREAD

**Issue by derkoe** [vmware/clarity#4695]
## Describe the bug

This happens when submitting a form with a [(clrDate)] binding in it. Everything works but the error is logged to the console.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-light-theme-mjggsf

1. Click on on Save

## Expected behavior

No error is shonw.

## Versions

**App**

- Angular: 9.0.4
- Clarity: 3.0.0

## Additional notes

See also #4414 (but this is different)

**Comment by gnomeontherun** [comment]
The problem from #4414 is the same, the container expects an instance of NgControl but using only clrDate doesn't provide it. We use that for validation and errors, so those features would be disabled if the date was invalid and not using an Angular form control.

The workaround is to assign it an ngModel (even if you ignore it) to get the error to go away.

**Comment by derkoe** [comment]
Ok - so the working solution is an empty ngModel:

```html
<input
    type="date"
    [(clrDate)]="model.birth"
    ngModel <!-- this is needed -->
    name="birth">
```

Would be great to add this to the example in the docs https://clarity.design/documentation/datepicker
