### ISSUE TITLE
How to unselect a Datagrid row in case of Single selection?

### ISSUE THREAD

**Issue by shravansofts** [vmware/clarity#4696]
## Describe the bug

In case of datagrid with single selection rows. If a user selects a row and if we want to unselect it programatically ( [(clrDgSingleSelected)]=selectedRecord ). Programatically if we set the two binded variable to null(i.e; selectedRecord = null) is not working.

How do we do this?

## How to reproduce

https://v2.clarity.design/datagrid/selection-single

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**App**

- Angular: 8
- Node: 12
- Clarity: 2.4.3

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
You should be able to de-sugar the syntax. e.g
```
<clr-datagrid [clrDgSingleSelected]="selectedUser" (clrDgSingleSelected)="mySelectedChangeFn(change)">
```

If that doesn't work for you please update the issue with a stackblitz that demonstrates the code tried and the issue described. 

I'm closing this for now as I believe this is an implementation question. Feel free to update and re-open if thats wrong.
