### ISSUE TITLE
Need to document the 6px grid used in Clarity

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#471]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
- Explain on the site how the 6px grid factor is used in spacing and sizing components in Clarity
- Tie this in with the 24px baseline documentation

### Actual behavior
- at this time we only have documentation around the 24px baseline
- nothing describes the horizontal space between elements

### Reproduction of behavior
- original request came from Josh Johnson on Slack
![image](https://cloud.githubusercontent.com/assets/1858226/22800973/b80c881a-eed0-11e6-88af-48c11109464b.png)
![image](https://cloud.githubusercontent.com/assets/1858226/22801013/d5391ade-eed0-11e6-9461-b2cd67849abc.png)
![image](https://cloud.githubusercontent.com/assets/1858226/22801050/efaa43c0-eed0-11e6-81ae-4313f37c076f.png)

**Comment by jaffoneh** [comment]
The docs are available in application layout here: https://vmware.github.io/clarity/documentation/app-layout.

Improvement to documentation, in general, is needed but this should cover this specific issue.

<img width="886" alt="screen shot 2017-06-26 at 2 11 36 pm" src="https://user-images.githubusercontent.com/690949/27560559-7df17c16-5a79-11e7-9f82-d4f34a484ddd.png">
