### ISSUE TITLE
Filter in DataGrid

### ISSUE THREAD

**Issue by husainsr** [vmware/clarity#4710]
## Describe the bug
1.) I check with 1000 Data Only in Grid and then Filter it it takes more time to Filter and Stucks also.
2.) When I  press F12 in browser for check log then F12 to back to screen the table stucks because of more data.

## Versions
**App**

- Angular: 9
- Node: 12.7.0
- Clarity: 3.1.3

**Comment by hippee-lee** [comment]
Hi @husainsr - we ask that new issues include a an isolated stackblitz that reproduces the issue so we can investigate and triage. We keep starter stackblitz apps here: https://stackblitz.com/@clr-team

**Comment by Jinnie** [comment]
I tried this and it worked fine with 10,000 items, both with latest Clarity and v3. Closing it, as no reproduction has been provided for several months now.
