### ISSUE TITLE
App level alerts no longer centered horizontally (regression)

### ISSUE THREAD

**Issue by erabl-identos** [vmware/clarity#4711]
## Describe the bug

This is a regression bug introduced by https://github.com/vmware/clarity/commit/1590daed127964ec1b5f4fa7df9422ec974057e8
The `flex-basis: 100%` causes the .alert-text to grow to its maximum width, moving the icon and text to the left, while the .alert-actions are pushed to the right.

## How to reproduce

Have a look at the _App-Level Alerts_ section in the clarity documentation (https://clarity.design/documentation/alerts).

This is the current style:
![grafik](https://user-images.githubusercontent.com/17832299/83997804-7e0d2780-a95f-11ea-8dff-c323f6905aab.png)

## Expected behavior

Setting `flex-basis: auto` for the .alert-text element in the browser debug tools causes the icon, text and actions to be centered.
![grafik](https://user-images.githubusercontent.com/17832299/83997981-e6f49f80-a95f-11ea-8ff7-228faa7520c3.png)

## Versions

**App**
- Clarity: 3.1.3

**Comment by gnomeontherun** [comment]
There is a workaround fix for this and the Clarity Core implementation of alerts can also be used to avoid this issue. See https://clarity.design/core-components/alert/.
