### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by sannamalai176** [vmware/clarity#4715]
Hi,

Where can i find the API Documentation? i can only see examples of different features in documentation site.

for example - what are the features , data grid offers.

Please advice

**Comment by hippee-lee** [comment]
The current docs have `Summary of Options` tables that list most of the Inputs/Outputs. Thats the best place for now. There are some gaps though so you might also look at the source if you feel comfortable there. Specifically for the datagrid - the demos describe the `API` for a particular feature and the Input/Output information there is targets to using the feature. 

We are working on an updated website for the v4 release with a dedicated API page for each component. Keep an eye out as we get closer to the v4 release.
