### ISSUE TITLE
Sharing the storybook location on the website

### ISSUE THREAD

**Issue by bbogdanov** [vmware/clarity#4716]
I've been looking at the source code lately and I found the storybook really helpful and easy to interact with component without the need to do a stackblitz snippets to test a scenario.

Do you guys plan to share the storybook location on the website?

I found the only way to know about the web-accessible clarity storybook is by searching on the web for it.

**Comment by mathisscott** [comment]
We have several efforts in progress right now to bring Storybook, Clarity Angular, and Clarity Core together. After that time, the documentation should be available similarly to how you are seeing it in the source code now.
