### ISSUE TITLE
how can i use only pagination with my table content (not using entire clr-data)grid

### ISSUE THREAD

**Issue by balajun01** [vmware/clarity#4717]
## Summary

_Summary the request and address the questions as appropriate._

- What is the change?
- Why should it go in Clarity?
- Does this change impact existing behaviors? If so how?
- If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by hippee-lee** [comment]
Clarity doesn't offer a stand alone pagination component. There is an open issue for it here: https://github.com/vmware/clarity/issues/2268 but at this time its not currently prioritized by the team. 

Please subscribe to that issue and leave any relevant feedback on there.

**Comment by balajun01** [comment]
Thank you for quick replay.
is there any way to implement in grid first three column and last column fixed with horizontal scroll to scroll intermediate five column in clarity data-grid.
