### ISSUE TITLE
[StackView][V3]When we have an 'Stack View With Editing' we can use tab to navigate to content that is in a collapsed stack block

### ISSUE THREAD

**Issue by civanova** [vmware/clarity#4718]
## Describe the bug

When we have an 'Stack View With Editing' we can use tab to navigate to content that is in a collapsed stack block.

## How to reproduce
When we have an 'Stack View With Editing' we can use tab to navigate to content that is in a collapsed stack block.
The issue is reproducible in v2 and v3

It can be seen in the https://clarity.design/documentation/stack-view
1. Go to section - "Stack View With Editing in a Modal"
2. Click "Edit"
3. Use Tab to focus the input of "Label 2"
4. Tab one more time
5. Actual: The focus is moved to "Sub-content 1" the content of "Sub-label 1" block that should not be visible, since its parent stack-block is collapsed. The parent stack block is no longer visible and is replaced with the child.

## Expected behavior

We should not be able to navigate with Tab to the collapsed content of a stack block.

## Versions

**App**

- Angular: 9.1
- Clarity: 2/3

**Device:**
- OS: Windows 10
- Browser: Chrome
- Version: 83.0.4103.97 (Official Build) (64-bit)

**Comment by bbogdanov** [comment]
@civanova This fix will be available in the next minor versions of v4 and v3 and also in the incoming v5.
