### ISSUE TITLE
Feature Request: User triggered collapsable Sidenav

### ISSUE THREAD

**Issue by pblasco** [vmware/clarity#472]
**Select one ...**  (check one with "x")
```
[ ] bug
[X ] feature request
[ ] enhancement
```

### Expected behavior
Right now, the sidenav will be collapsed on smaller screen sizes.  It would be nice to be able to trigger that action independent of screen size.  This would allow a user to perform some action such as clicking a button to collapse the sidenav to have more screen real estate when not using the sidenav.

Would it be as simple as exporting the clrResponsiveNavigationService so that it could be used by other modules to trigger navigation actions?

**Comment by jaffoneh** [comment]
@pblasco that's actually something we're researching and exploring on the UX side right now so a timely request. We don't have a spec to share just yet but it is something @yenmade has been exploring. Would love to hear your feedback once a design spec is posted (we'll share it here).

**Comment by joshjohnson72** [comment]
@pblasco Is your use case to collapse the sidenav temporarily so the user can see more data on a particular page with the assumption it'll be expanded again before the user continues elsewhere, or is it to collapse the sidenav indefinitely because the user always wants more space on every page?  I ask because the resulting design would vary drastically between the two.

**Comment by pblasco** [comment]
The preferred use case for our needs would be the first one.

We are building a fairly data dense application, with some full width data tables and corresponding controls.  When viewing an individual data view (corresponding to a nav item on the sidenav), it would be nice to be able to collapse that down while interacting with the view to get the most screen real estate, and then expand that out when you want to see the navigation hierarchy.  This would size the non side nav content down correspondingly when expanded.

I could see other users wanting more of a sidenav overlay, where it overlaps the content, much like the mobile menu does now.  But for our team we'd prefer a sidenav that sizes the rest of the content.

**Comment by joshjohnson72** [comment]
Thanks Peter that's really helpful.  What you describe makes a lot of sense for your usecase, and sounds similar to what Amazon AWS has implemented for services like EC2 (https://console.aws.amazon.com/ec2/) where an arrow toggles whether the sidenav is displayed and content resizes to fit.

**Comment by pblasco** [comment]
Would it make more sense to think of the component as a generic sidebar that could contain content other than navigation?  I could see it being useful for containing other actions if an application didn't need to navigate.  That might be expanding the scope of the component too far, though.

**Comment by BlakeDraper** [comment]
I would like to sound a hearty second for the use case @pblasco has detailed here. I am building an app that sounds remarkably similar to the one he describes and I opened the repo to submit this feature request myself. Then I figured I should see if anyone else already had, and sure enough, here it is.

It would be very useful to be able to treat the sidenav as a generic sidebar for me as well. My users may only wish to see the navigation when they need it, and it would be great to be able to toggle the sidenav open and closed at will on large screens.

**Comment by pblasco** [comment]
To further comment on this, I can give an example of what we have implemented and our product people seem to prefer as a sidebar navigation tool.  Each item in the navigation list has an icon, and when at sizes where the sidebar would normally be visible, you can collapse the sidebar down to an icon bar.  When the screen is small enough it uses the existing Clarity behavior of the sidebar being an overlay.

I understand that this maybe a little too specific for one particular use case for what Clarity intends to implement, but it would sure be nice to have this built into the toolkit =).

Here's a gif of how our stuff is looking to give you an idea.

![sidebar](https://cloud.githubusercontent.com/assets/1203826/25459427/14fa4a14-2a93-11e7-8491-9fe1dc4badbc.gif)

**Comment by jaffoneh** [comment]
@pblasco we're actually looking at this from a design point of view at this point so this is really helpful. CC @yenmade and @reddolan / @mathisscott

**Comment by pblasco** [comment]
For our company's specific use case, we'd also like to be able to have hierarchical navigation for some of the main items in the sidenav, like demonstrated in the Clarity sidenav documentation.  The question then becomes what happens to the navigation items when you collapse a sidenav?

It seems to me that flattening the hierarchy and displaying all navigation items in a collapsed navbar would be not a great way to handle that.

My current experiment was to collapse the sidebar down as shown, showing only the top level navigation icons.  A click on any navigation item that contained sub navigation items pops a menu up, showing the sub navigation options.  This allows a user to navigate the hierarchy while leaving the sidenav collapsed. 

I'm not UX person by any means, so I'm sure there is a better solution, but the people I demo'ed this to seemed to respond pretty positively to this solution.  

I'm sure there is an argument that in this case a user should have to expand the sidebar, or a click on a top level item would cause the sidebar to expand, but I don't really have the qualifications to determine which solution is the best for most users =).

I can fix up a demo .gif like the one attached above if this is not clear and someone feels it would be useful.

**Comment by mathisscott** [comment]
@reddolan : This is the left-nav ticket if you need to find it.

**Comment by reddolan** [comment]
@pblasco you mentioned "we'd also like to be able to have hierarchical navigation for some of the main items in the sidenav". How many levels of hierarchy are you needing?

**Comment by pblasco** [comment]
We currently have need for one and are using that, and one of our product people has expressed a need for two.  

I was just going to implement it as an additional level of nesting but there is probably a more elegant way of attempting that.

**Comment by reddolan** [comment]
@pblasco We have merged your request into Vertical Navigation #1001. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you
