### ISSUE TITLE
The number of items in the Datagrid footer is not properly calculated when a filter is active

### ISSUE THREAD

**Issue by Angelmmiguel** [vmware/clarity#4722]
## Describe the bug

The current implementation of the Datagrid ignores active filters when generating the "number of items" in the Datagrid footer. It causes weird situations when reading the table with an screen reader. 

For example, if we apply a filter and we don't get any row based on it, the table will announce 0 rows while the footer will still say `X users`. 

## How to reproduce
1.  Go to the [Datagrid Filter example in the Clarity Docs](https://clarity.design/documentation/datagrid/built-in-filters)
2.  Filter the Pokemon column with an `asd` value
3.  See the table is empty but the footer says `10 Users`

## Expected behavior

I believe it would be useful to add some information about the filtered values: `0 Users based on the current filter, 10 users in total`. You can simplify how it looks in the UI, but the previous string is definitively useful when reading the table.

## Versions

All 

## Additional notes

Anything

**Comment by Jinnie** [comment]
The footer is highly configurable. The footer from the built-in filters demo just shows the full size of the data. This demo page is focused on the filter itself, so we've not added a more advanced footer.
You can see filtering and advanced footer working together on our Full Demo datagrid page here:
https://clarity.design/documentation/datagrid/full

We could possibly add a more advanced footer to this demo too, but with respect to some ongoing website updates, I think that the Full Demo above should be sufficient for now.
