### ISSUE TITLE
clr-daypicker as a standalone calendar component

### ISSUE THREAD

**Issue by NiKlimenko** [vmware/clarity#4729]
## Summary

It would be nice to have daypicker as a standalone calendar component to use outside of the input components.

Currently, this component can't be used separately from the Date Picker due to service injections: ```No provider for ViewManagerService!```

### Motivation
To have ability show calendar in plain view, like it's in google calendar.

### Does this change impact existing behaviors? If so how?
No, it shouldn't.

### If this change introduces a new behavior, is this behavior accessible?
I think there is no new behavior, but the existing functionality is still sufficient.

## Use case
Use it as a simple calendar to navigates through dates.

## Examples

![image](https://user-images.githubusercontent.com/11063519/84587599-37b93c00-ae29-11ea-8d60-c00d115c4b61.png)

## Workarounds
It seems there is no workaround to use it outside of the Date Picker at the moment.

**Comment by sdurnov** [comment]
Totally support that! Since there’s no time range selection component in Clarity, more flexibility with calendar parts would help.

**Comment by gnomeontherun** [comment]
@mathisscott Would we be building a generic calendar for Core as part of Datepicker?

**Comment by mathisscott** [comment]
@gnomeontherun 
Yes. It would make sense for that to be a reusable component inside the datepicker drop down.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
