### ISSUE TITLE
Combobox documentation for website

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#4741]
## Summary

Make sure we have website documentation for the Combobox.
Either in the website that's under development, or in the old one, which ever meets the release of 4.0.

We have this PR with the main combobox code merged https://github.com/vmware/clarity/pull/4286 but it only has dev-app docs, not website!

**Comment by hippee-lee** [comment]
@Jinnie - closing this as done. Thanks to you it now lives in the new website docs.

**Comment by mattmutt** [comment]
"Mutli selection combobox" section in two areas needs checking
