### ISSUE TITLE
Issues maintaining selection on data change

### ISSUE THREAD

**Issue by ryan-bradford** [vmware/clarity#4742]
## Describe the bug

When using server driven datagrid, the feature that maintains selection has strange edge cases. Namely, when you select all items, change the data displayed such that a new items is in the grid, the select all button maintains checked. Additionally, pressing the select all button again does not select the new row in the grid. The workaround for this is to call `this.datagrid.rows.notifyOnChanges();`.

## How to reproduce

1. Go to https://stackblitz.com/edit/clarity-v3-light-theme-qa7fsd
2. Click on the select all rows button
3. Click on "New Items"
4. Observe that now select all is still checked, even though "Mary" is not selected.
5. Click the select all rows button twice
6. Observe that now select all is still checked, even though "Mary" is not selected.

## Expected behavior

We would expect the select all button to be an indicator of whether all rows currently displayed are checked. Additionally, we would expect pressing select all to select all rows currently displayed in the datagrid. 

## Versions

**App**

- Angular: 9.0.0
- Clarity: 3.1.3

**Device:**

- Type: Macbook Pro
- OS: MacOs 10.15.4
- Browser Chrome
- Version 83

**Comment by hippee-lee** [comment]
Hi Ryan,

Thanks for the stackblitz.
You are correct that select all button should reflect the currently displayed rows. 

In the example, it looks like the component that wraps datagrid has an input for trackBy.
I updated the stackblitz and passed in the trackBy fn supplied in the host: https://stackblitz.com/edit/gh-4742-datagrid-trackby

The stackblitz now behaves correctly. I'm going to close this as I believe its working as it should. Feel free to re-open if I missed something in your use case.
