### ISSUE TITLE
clrFocusOnViewInit prevents link navigation

### ISSUE THREAD

**Issue by GrahamFord** [vmware/clarity#4743]
## Describe the bug

I have a simple form with one input field that has the clrFocusOnViewInit attributes. There is also a navigable link on the page. When the page loads and the link is clicked, the input field takes focus and prevents the navigation. A second click on the link will succeed.

## How to reproduce
https://stackblitz.com/edit/angular-ivy-nohs9z

1. When the embedded browser loads the page, click on the `Route 2` link. 
2. The input field loses focus, the validation message is displayed but the link isn't activated.
3. Clicking on the link again will take you to Route 2

## Expected behavior

I would expect the navigation to work on the first click.

## Versions

**App**

- Angular: 9.1
- Node: 14.4.0
- Clarity: 3.1.4

**Device:**

- Type: MacBook
- OS: Catalina
- Browser: Firefox, Chrome
- Version: latest

## Additional notes

The documentation on `clrFocusOnViewInit` is brief so please let me know if I'm using it incorrectly.

**Comment by Jinnie** [comment]
There is a very "mechanical" explanation to what you are observing there.
When you try to click the Route2 link, there are 2 events that will be emitted:
- input field blur event
- link click
The first event leads to an immediate change detection cycle which results in the display of the error-text.
This error text displaces the Route2 link though. And as a result, the click event does not happen.

To verify the above, just move the Route2 link above the input.
Or, as a workaround, place the input-container in a div with fixed height, which will make sure that validation does not alter the page layout.
