### ISSUE TITLE
Datepicker with reactive form and strictTemplates throws Type 'string' is not assignable to type 'Date'

### ISSUE THREAD

**Issue by dpsarrou** [vmware/clarity#4744]
## Describe the bug

The datepicker component in its reactive form implementation as shown in the [official documentation](https://clarity.design/documentation/datepicker) at the *Reactive Form Demo* section, throws the following typescript compilation error, when `strictTemplates: true` in `tsconfig.json`:

```
error TS2322: Type 'string' is not assignable to type 'Date'.
```

The app is compiled successfully when `strictTemplates` is disabled. 

## How to reproduce

1. Ensure `strictTemplates` is enabled `tsconfig.json`
```tsconfig.json
{
...
  "angularCompilerOptions": {
    ...
    "strictTemplates": true
  }
}
```
2. Use the example code, exactly as found in the [official documentation](https://clarity.design/documentation/datepicker) at the *Reactive Form Demo* section.

3. See typescript compilation error
```
ERROR in ...component.html:5:26 - error TS2322: Type 'string' is not assignable to type 'Date'.
```

## Expected behavior

The app should compile successfully as it does when `strictTemplates` is not enabled.

## Versions

**App**

- Angular: [9.1.11]
- Node: [14.4.0]
- Clarity: [3.1.4]

**Device:**

- Type: [MacBook]
- OS: [iOS > docker > node:14-alpine]
- Browser [chrome]
- Version [latest]

**Comment by sdurnov** [comment]
@coryrylan any plans to fix that? Disabling strict templates in a whole project just because of that is awful :(

**Comment by twittwer** [comment]
We had a similar problem #4604 - it could be fixed by extending the input coercion
```diff
- public static ngAcceptInputType_date: Date | null;
+ public static ngAcceptInputType_date: Date | null | '';
```
