### ISSUE TITLE
smart popovers are not getting closed on body scroll.

### ISSUE THREAD

**Issue by pavandixit93** [vmware/clarity#4745]
## Describe the bug
Clarity smart popovers are not getting closed on scrolling of body scrollbar. It is closing on scroll of the datagrid wrapper container only.

## How to reproduce
FYI: https://stackblitz.com/edit/clarity-v3-datagrid-on-body-scroll-popover-issue 
I have added small datagrid example. Here as per common requirement, body has scrollbar, Also i have set datagrid height to `300px` so that datagrid also has scrollbar.

1.  Go to [Clarity Datagrid basic example](https://stackblitz.com/edit/clarity-v3-datagrid-on-body-scroll-popover-issue)
2.  Click on Show or hide columns button, present at leftmost side in datagrid-footer.
3.  It opens the smart popover column-switch dialog.
4.  Scroll the body scrollbar i.e. right most scrollbar.
5. Smart popover remains open and it does not move alongwith datagrid.
Again, 
Repeat 1-3 steps from above and now try to scroll the datagrid scrollbar i.e. scrollbar before the body scrollbar.
Now in this case smart popover gets closed.
## Expected behavior
Smart popover should be closed on scroll of body scrollbar like it closes on scroll of datagrid wrapper scrollber.
## Versions

**App**

- Angular: [e.g. 6]
- Node: [e.g. 8.10.0]
- Clarity: [e.g. 0.12.5]

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by pavandixit93** [comment]
Hi Team, Any update on this. This is critical issue when body has scrollbar.

**Comment by pavandixit93** [comment]
Hi Team, Please let me know if any input needed from my side.

**Comment by Jinnie** [comment]
Hello @pavandixit93 
This problem is observed only on the body tag in my research.
We definitely recommend using the Clarity layout, where this problem is not observed. It also won't be observed if the datagrid is nested in any body child in a way that will make the body not scroll itself. But we also don't want to limit the use of popover featuring components without a good reason. So I'll add this to our bug list.

**Comment by pavandixit93** [comment]
@Jinnie Thank you for update. Yes i know this work around, But as per UI requirement i also can not change my GUI to Clarity layout. In many cases we can have body scrollbar directly and not the body child scrollbar. 
Yes it works perfectly when datagrid is nested in any body child in a way that will make the body not scroll itself but when GUI has boy scrollbar it brokes and this is happening in my GUI,
Thank you for considering my requirement :).

**Comment by bdryanovski** [comment]
@Jinnie Can we close this now with the upcoming release of dropdown and popovers in core?

**Comment by Jinnie** [comment]
Yes, as we have a workaround and a fix in Core, we don't intend to work on this one for Clarity Angular.
