### ISSUE TITLE
Screen Reader dialog boundaries are not communicated for datagrid show/hide column

### ISSUE THREAD

**Issue by pratikgala** [vmware/clarity#4754]
@
## Describe the bug

Accessibility Issue.
Dialog boundaries are not communicated for datagrid show/hide column,
Example of this include:
- Show Columns dialog. The div for the dialog contains role of a dialog. However, it does not provide name.

[User Impact]
When this is not done, it is not clear to screen readers when they are leaving or entering a dialog when using the virtual cursor.

[Code Reference]
`<div class="column-switch clr-popover-content ng-star-inserted" clrfocustrap="" role="dialog" tabindex="0" id="clr-id-833" style="top: 334.5px; left: 313px;">...</div>`

## How to reproduce

https://clarity.design/documentation/datagrid/hide-show

1.  Use a screen reader like JAWS or NVDA.
2.  Go to clarity datagrid
3.  Click on show/hide
4.  Scroll down to the datagrid
5.  Click open the dialog to show/hide column
 Inspect the dialog code, the dialog code does not provide role name for the dialog.
 The dialog does not provided aria-labelledby and aria-label attributes.

## Expected behavior

[Recommendation]
Ensure that the dialog is properly labeled. Make use of role=dialog and ensure that the dialog is named by using aria-label (if no visual title is present) or aria-labelledby (if a visual title is rendered within the dialog).

[Compliant Code Example]
aria-label:
```
<div role="dialog" aria-label="My Dialog Title">
 <p>Lorem ipsum dolor set... /p>
</div>
```

aria-labelledby:
```
<div role="dialog" aria-labelledby="myDialogTitle">
 <h3 id="myDialogTitle">Dialog Title</h3>
 <p>Lorem ipsum dolor set... /p>
</div>
```

## Versions

**App**

- Angular: [8.1.0]
- Node: [10]
- Clarity: [2.4.2]

**Device:**
- Browser [chrome]
- Version [84]

## Additional notes

![Screenshot 2020-06-26 at 15 00 56](https://user-images.githubusercontent.com/3613248/85905644-c7af9c00-b7c0-11ea-8338-db213ba868aa.png)

**Comment by gnomeontherun** [comment]
Hello @pratikgala is this in relation to a VMware product?

**Comment by pratikgala** [comment]
@gnomeontherun yes this is VMware product, the issue I have reported in on the clarity website component, but is the same for products using those components as well.

**Comment by Jinnie** [comment]
I'll backport this to v4
