### ISSUE TITLE
Smart Positioning for Dropdowns

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#4755]
## Summary

Currently, dropdowns are always shown in a fixed position. It should be smart enough to automatically position the dropdown to an available space.

## Reproduction:
Check the samples in the dropdown docs.
As you can see in this screenshots, the trigger is currently positioned at the bottom of the page. The expectation is it should automatically adjust its position so it will not be cut-off or go off-screen. This same goes to a case where the trigger is positioned at the right or left.
![image](https://user-images.githubusercontent.com/1977391/85922988-e2197080-b8b9-11ea-8c3b-f1bca0b99464.png)

## Real-world scenario
I have a dynamic overflow bar (similar to Office Fabric UI's command bar/overflow set) that may contain multi-level dropdowns. Since this component is dynamic and the layout is fluid, the position of the trigger may change. The problem is that there's no way for me to configure the dropdown so that it automatically positioned itself to be always visible in the viewport.
![image](https://user-images.githubusercontent.com/1977391/85923139-396c1080-b8bb-11ea-84fb-0728a89a1616.png)

Since smart popovers are already in Clarity, maybe it's also possible to apply that utility in dropdown components.

**Comment by hippee-lee** [comment]
Thanks for reporting this. We already have an issue tracking the work that needs to be completed for this (and the other popover components)/

I'm closing this in favor of #1757
