### ISSUE TITLE
Datagrid selection not preselected

### ISSUE THREAD

**Issue by rotirk20** [vmware/clarity#4759]
Hello I'm using Angular and Clarity.I use datagrid with selection in which I want to open a edit page which they are some checked elements of each edit page.I got the icon with total selected items but they are not checked in the datagrid.
I use the refresh(state: ClrDatagridStateInterface) and (clrDgRefresh)="refresh($event)" [(clrDgSelected)]="selected"

## How to reproduce
https://stackblitz.com/edit/clarity-v3-dark-theme-djvtey?file=src/app/app.component.html

This is only a reproduction without server driven pagination.I use that too.

## Expected behavior

Expecting preselection

## Versions

**App**

- Angular: [9]
- Clarity: [3]

**Comment by dorthrithil** [comment]
I see several issues in your code:

- The main issue is, that you use different arrays of data for the row iterator (`*ngFor`) and the selected inout `[clrDgSelected]`. Clarity is checking if an item from `data` is contained in `membersData` to set the checkbox tick which is never the case as object identities are different in every case. 
- You are not using the smart iterator `*clrDgItems` but `*ngFor`. Most of the Datagrid features rely on the smart iterator.
- `clrDgSelected` on the row should be a two way binding to keep the model in sync with the selected state of the item.

See the updated stackblitz here:

https://stackblitz.com/edit/clarity-v3-dark-theme-ds6goj

**Comment by rotirk20** [comment]
Yes but with *clrDgItems the server driven pagination doesn't work well.And do I need to use refresh for that?

**Comment by gnomeontherun** [comment]
@rotirk20 you are correct that when you use server driven, then you need to use `*ngFor`. @dorthrithil is right about the object equality being a problem. If you want a server driven datagrid though, you can't expect to use object equality for comparison as you will be creating and destroying your data on refresh.

By default, iterators look for strict object equality, but you have two independent objects created even if some of them have the same signature. The solution is to add trackBy, which lets you define how two objects should be compared for equality (for example, by comparing just their unique ID). In this example some IDs are in the selected array but not in the data array, so there are extra items selected and it would be assumed they are in another page of the data somewhere. 

See https://stackblitz.com/edit/clarity-v3-dark-theme-cufcvt?file=src%2Fapp%2Fapp.component.ts

Closing as working as expected once you add TrackBy.
