### ISSUE TITLE
Add a skip link within the header

### ISSUE THREAD

**Issue by scroniser** [vmware/clarity#4760]
## Summary

- What is the change: Include a skip link within the [header code](https://clarity.design/documentation/header)
- Why should it go in Clarity? Skip links must be included as the first focusable element at the top every page in order to be accessible. E2E stories are requirement and this is a must-have for consistency. 
- Does this change impact existing behaviors? If so how? This element becomes the first focusable element in lieu of other elements
- If this change introduces a new behavior, is this behavior accessible? This behavior is improves accessibility for all products

## Use case

A person who only uses a keyboard (instead of a mouse) will find it easier/faster to navigate to the main content area.

## Examples

**Internal link removed**

## Workarounds

Each product team must implement this on their own in order to implement accessibility compliance.

**Comment by colinreedmiller** [comment]
Skiplink on Clarity docs site:
https://github.com/vmware/clarity/issues/3153#issuecomment-471000263

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
