### ISSUE TITLE
customized title for <clr-signpost>

### ISSUE THREAD

**Issue by talentjeff** [vmware/clarity#4763]
## Summary

_Summary the request and address the questions as appropriate._
The title of <clr-signpost> is hardcode(title="Info"). It isn't friendly when the page is switch to other language, such as JP, FR,DE and so on,

- What is the change?
<clr-signpost [title]="XXXXXXX">
input customized title

- Why should it go in Clarity?
The title of <clr-signpost> can't be changed from outside of the component. 

- Does this change impact existing behaviors? If so how?
No. If no customized title is provided, we can keep the default title 'Info'.

- If this change introduces a new behavior, is this behavior accessible?
No, there is no new behavior.

## Use case

_Provide some specific details about how this change would improve your application and use case._
When user switch language to Chinese, we would provide a different title. For example '信息'.

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_
No

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_
After the view the init, find all the <clr-signpost> tag in the page, then change the title. This workaround is quite strange.

**Comment by hippee-lee** [comment]
@talentjeff - If I understand the issue as described there is a need to place a title on the signpost and update it for i18n.

This can be accomplished today with a custom trigger: https://stackblitz.com/edit/gh-4763-signpost-title-input
In this example the custom trigger has the title attribute (imo that is the proper place for it, not on the signpost component) and it can easily be updated by an application as needed. 

The missing piece is that our default (no trigger) signpost has no way for an app to set a title. I'm going to mark this as consideration for an enhancement.

**Comment by mathisscott** [comment]
@hippee-lee 
Another consideration is removing the convenience of a "default signpost trigger" or, perhaps, displaying a warning when people don't provide a custom trigger. Essentially letting app developers know that our guidance is to provide your own triggers.

A custom trigger is no harder to provide than a string. And it gives applications more control over their applications.

**Comment by gnomeontherun** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. We would consider a contribution to address this issue if someone is able to work out a solution. As we build Clarity Core implementations, we expect that this issue won’t be an issue or will be configurable on the application side. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
