### ISSUE TITLE
Stackview: Partial highlight of selected and hover state.

### ISSUE THREAD

**Issue by ali5ter** [vmware/clarity#4765]
## Describe the bug

When selecting, or hovering, on an expandable stackview row, only the key area is highlighted. 

## How to reproduce

This can be seen in the stackview code example in the Clarity documentation at https://clarity.design/documentation/stack-view. The first code example show this unexpected partial highlighting and the following examples show the expected full row highlighting. 

## Expected behavior

The expected behavior is for the whole row to be highlighted.

## Versions

**App**

- Angular: [e.g. 6]
- Node: [e.g. 8.10.0]
- Clarity: [e.g. 0.12.5]

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
@bbogdanov 
This is listed in the review pipeline. Is it still in review? If not, please close it.
