### ISSUE TITLE
Side arrows(>) for dropdown items that trigger a nested dropdown are not showing up when using ng-template to repeat the nested dropdown template

### ISSUE THREAD

**Issue by ps37** [vmware/clarity#4766]
## Bug description
I am trying to render nested dropdown by using ng-template to repeat the nested dropdown template. However, I am not able to get the side arrows(`>`) for dropdown items that trigger a nested dropdown in this case. 
Following is the Stackblitz showing the issue…
https://stackblitz.com/edit/clr-dynamic-dropdown?file=app%2Fapp.component.html
Please notice the items like ‘Action 0’ that can trigger nested dropdown does not show the side arrows

I was able to work around the issue by creating a wrapping component for the recursing template and use that component to repeat the template. Following is the Stackblitz showing this...
https://stackblitz.com/edit/clr-dynamic-dropdown-2?file=app%2Fdropdown.component.html

Looks like the child dropdown does not recognize that it has a parent dropdown and gets the presentation of a root item. This is probably because of the corresponding CSS styles not being applied in this scenario.

## Expected behavior
Side arrows(>) have to be shown for the dropdown items even when ng-template to repeat the nested dropdown template.

## Versions
"@clr/angular": "3.1.3",
"@angular/core": "9.1.9",

**Device:**
- MacBook
- macOS Mojave
- Chrome

**Comment by Jinnie** [comment]
ngTemplateOutlet creates a view from a template dynamically. Then it attaches the view to the view container.
https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_template_outlet.ts
It does it on the View level, in isolation from the overall component hierarchy, which can be demonstrated with this test:
https://stackblitz.com/edit/parent-template-study-2?file=src%2Fapp%2Fapp.component.html
It resolves parent and children components in both cases - direct component nesting and using templates and template outlets.
It will work fine with independent components, but not with ones that need to know about the component hierarchy, as the tree or the nested dropdowns.
So, using components as wrappers, not template outlets, should be the correct way to go.

I am leaving this temporarily open, to encourage more discussion, but I don't think we'll make any change on our API design.

**Comment by Jinnie** [comment]
Closing this as we don't intend to change the API and the component wrapper approach is sufficiently viable solution for this dynamic use case scenario. Also, for a more data-intensive case, please consider using the tree component instead.
