### ISSUE TITLE
Components showcase offline

### ISSUE THREAD

**Issue by dsubiros** [vmware/clarity#4768]
## Summary

Hi guys. Excellent job which you are doing.
Maybe this isn't the right way or place to ask for this, but how can I get the components show case offline?

Thanks and sorry for opening a new Issue just to ask this, but I didn't know where else to go.

**Comment by bbogdanov** [comment]
Hi @dsubiros, I suppose you are asking for the components examples on the website.

One good way to run the examples locally is to download the repo, install the packages by `yarn` and run these two in separate terminals:

`yarn angular:dev:serve`
`yarn angular:dev:start`

These above two will run the components examples in a website that you can be able to locate on `https://localhost:4200`.

Hope that helps.
