### ISSUE TITLE
Suggestion needed for debugging Clarity app in browser runtime.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#477]
**Select one ...**  (check one with "x")
```
[ ] bug
[] feature request
[x] enhancement
```

### Expected behavior

I used seed project to initialize an Angular Clarity project, but I found it is difficulty to debug when I met errors by using the default configurations of seed provided, so I just want to need some suggestions about how to debug clearly and conveniently under browser console? By using plug-in or configuring settings about? Thanks a lot.
### Actual behavior

None
### Environment details

* **Angular version:** 2.3

* **Clarity version:** 0.7.5

* **OS and version:** OS X, Windows 10

* **Browser:** [all | Chrome 56 | Firefox 51 | IE 11 | Safari 8 ]

**Comment by jeeyun** [comment]
Hi @wknet123 which version of the seed are you using (angular-cli, systemjs, or webpack)? Might be helpful to checkout Augury, which is a chrome extension for debugging Angular 2 applications: https://augury.angular.io/

**Comment by jeeyun** [comment]
Closing since this is a general front end dev environment/tool issue, and not specific to Clarity framework. Please feel free to re-open if there's are specific bugs in the seed, etc.

**Comment by Jinnie** [comment]
@wknet123 Augury, as suggested by @jeeyun, is really powerful.
Also, if you have difficulties finding the correct piece of code in the browser, to which you need to set your breakpoints, you may use [debugger statements](https://www.w3schools.com/jsref/jsref_debugger.asp) in your code instead to force a break from the code.
