### ISSUE TITLE
Indeterminate Progress Bars not animated on Firefox

### ISSUE THREAD

**Issue by patriceo** [vmware/clarity#4770]
**Description:** 

The indeterminate progress bars are not animated on Firefox

After having the issue on my project, I came to the conclusion this is a Clarity issue because It can be reproduced from the clarity documentation page. Note the indeterminate progress bar works on Chrome & Safari.

**URL:**
https://clarity.design/documentation/progress

Firefox 78.0.1 (latest version) behaviour: Progress bar remains at 100% with no animation
![image](https://user-images.githubusercontent.com/2040346/86895967-8e065b80-c105-11ea-9c74-e7246db95c01.png)

**Comment by jmls** [comment]
odd. I just tried it with FF and works just fine
![image](https://user-images.githubusercontent.com/929523/86903264-002b7000-c107-11ea-9bca-5f85f887e46d.png)

78.01 on ubuntu

**Comment by patriceo** [comment]
Have you tried the one in **Indeterminate (Looping) Progress Bars** section ?  The one from your screenshot also works on my firefox (macOs) but if I scroll down to the looping example it does not.

**Comment by jmls** [comment]
and you are right. no animation ;)

**Comment by Jinnie** [comment]
I reproduced and researched it.
The animation is there, but the background color in FF is for some reason the same blue color as the animation block color. It is defined as #e8e8e8, and this setting is active, but something, maybe on the ::after block, overrides it and we have a blue block on blue background.

**Comment by mathisscott** [comment]
@Jinnie 
Firefox had bugs with its browser related to progress bars when we created them in 2016. I would wager that Firefox has fixed those issues and now we can probably remove those browser-related overrides.

**Comment by gnomeontherun** [comment]
I don't see this issue in Firefox now, and I'm going to close this as resolved. There is also the Clarity Core https://clarity.design/core-components/progress-circle/ and upcoming work on other progress formats that could be used.
