### ISSUE TITLE
The border of the Detail Pane is partially lost when content in the pane is long

### ISSUE THREAD

**Issue by iilieva** [vmware/clarity#4773]
## Describe the bug

The border of the Detail Pane is partially lost when content in the pane is long.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-light-theme-dzkhzm?file=src%2Fapp%2Fapp.component.html

1.  Add datagrid
2. Add detail pane with content longer than the table rows height.

## Expected behavior
The border should covert the whole height of the detail pane.

## Versions

**App**
Cloud Director

- Angular: 9.1
- Node: v12.16.1
- Clarity: 3.1.3

**Device:**

- Type: MacBook
- OS: Catalina
- Browser Chrome, FireFox

## Additional notes

-
<img width="1665" alt="Detail Pane border issue" src="https://user-images.githubusercontent.com/21175375/87039564-fdf50e80-c1f7-11ea-9454-3e85c3e07be5.png">

**Comment by Jinnie** [comment]
Seems that .datagrid-table-wrapper does not go to 100% height. Have to check if it's intentional and I think it can be easily fixed.
