### ISSUE TITLE
Spacing classes like Bootstrap

### ISSUE THREAD

**Issue by vmagesh** [vmware/clarity#4775]
Following are some classes provided in Bootstrap for responsive design and for spacing,
.row,
.col,col-md-*,col-sm-*,col-lg-*,
m-*,
p-*

Are there any CSS classes in clarity as well similar to bootstrap?

**Comment by mathisscott** [comment]
@vmagesh 
For the analogs to the `.col-*` and `.row-*` classes, see https://clarity.design/documentation/grid.

As for our future direction on this topic, take a look here https://clarity.design/storybook/core/?path=/story/experimental-layout-get-started--page

Thanks for checking in!

**Comment by vmagesh** [comment]
got it thanks @mathisscott
