### ISSUE TITLE
Clarity 'storage' icon does not support dark theme

### ISSUE THREAD

**Issue by kodemasta** [vmware/clarity#4777]
## Describe the bug

<clr-icon shape="storage"></clr-icon>

The clarity 'storage' still appears black when applying clarity dark theme. Expecting a lighter white as other Clarity icons appear to support dark theme.

Using clarity 3.1.4 and ng9. macOS

![Screen Shot 2020-07-10 at 7 38 46 AM](https://user-images.githubusercontent.com/2491690/87166557-98993000-c280-11ea-83dc-baa4d76fb827.png)
![Screen Shot 2020-07-10 at 7 38 36 AM](https://user-images.githubusercontent.com/2491690/87166565-9b942080-c280-11ea-916f-08143b99913a.png)

. Chrome.

See screenshots.

**Comment by mathisscott** [comment]
Hi @kodemasta 
I don't see anything in the 3.1.4 @clr/icons technology shapes that would cause the behavior that is being reported.

Could you help us out by [providing a stackblitz](https://stackblitz.com/edit/clarity-v3-dark-theme)?

I don't know if there's something on your end that is overriding the styles for that glyph. And it looks fine on my end.

Thanks!

**Comment by kodemasta** [comment]
That was it ! We had an override for 'storage' icon. I removed it and it is working. Thanks for the tip.
