### ISSUE TITLE
Prevent wizard closure on ESC key when clrWizardClosable is false

### ISSUE THREAD

**Issue by vishalmanohar** [vmware/clarity#478]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When clrWizardClosable is false, hitting the Escape key should NOT close the wizard.

### Actual behavior
Hitting ESC closes the wizard

In wizard.ts, it needs to check for `closable` enabled before calling the `close()` method.

```
@HostListener("body:keyup.escape")
    _close(event?: any): void {
        this.close();
    }
```

**Comment by mathisscott** [comment]
@vishalmanohar : Would you expect using the ESC key in this instance to go through the same routine as clicking the cancel button in the wizard? 

I will also ask @reddolan and @yenmade for their input here. 

I am linking this issue to #156.

**Comment by vishalmanohar** [comment]
Good question. 

My own use case for the wizard is to use it in a non-modal scenario -- and I thought that the `clrWizardClosable` was meant for such cases -- because the 'X' close button and the ESC key actions are suited for modal and the toggle should perhaps affect both actions.

**Comment by mathisscott** [comment]
I see. Our current use case is for wizards in modals. I don't know if inline wizards are something we are looking to support.

I would advise creating your own extension of the wizard that overrides the escape key binding. That shouldn't be too complicated.

**Comment by vishalmanohar** [comment]
Yes, that is what I ended up doing. Thanks for the input.

**Comment by ciptoj** [comment]
Hi, I'm having the same issue can share easiest way to implement that custom component?
No luck so far.

**Comment by mathisscott** [comment]
@ciptoj 
The code for the custom component is in @vishalmanohar's post above.

**Comment by ciptoj** [comment]
tried it got errors

**Comment by ciptoj** [comment]
what to put in template/templateurl?
how do you use it in another parent component?

**Comment by ciptoj** [comment]
the vishalmanohar's solution does not work on your latest. beside I see that only _open is provided.
My solution with out Stub the class is to use:
(clrWizardOpenChange)="onopen($event)"

and then on close just reopen it :)
 onopen(isopen:boolean){
    if(!isopen){
        this.wizard.open();
    }
  }

**Comment by mathisscott** [comment]
@ciptoj 
Learning how to use components, component selectors, and templates is best explored in the [Angular website's documentation](https://angular.io/tutorial/toh-pt3).

**Comment by pratikgala** [comment]
I found this solution to be much better that @HostListener
Angular supports key event filtering inside templates.

<clr-wizard .... 
    (keydown.escape) = 'keyDownEscape()'>
</clr-wizard>

component:

 keyDownEscape(){
    // do some thing is escape is pressed.
}

**Comment by rachwani** [comment]
I am facing the same issue 
scenario:-we are creating a  wizard and once we accidentally pressed escape key button it was all gone just the white screen..
need solution to restrict escape button as prevent default and stop propagation does not work

**Comment by mathisscott** [comment]
@rachwani 
[Please submit a stackblitz demonstrating your issue](https://stackblitz.com/@clr-team) and open another ticket if you feel it's a bug in Clarity. Most of the posts in this issue are referring to a hack that some people use that can make the wizard work inline instead of in a modal. Note, this is something that Clarity enables but does not expressly support [because our recommendation is to use a stepper component](https://github.com/vmware/clarity/issues/2503) instead.

I would expect the inline wizard hack to be deprecated and removed a couple of major versions after the stepper is released. (So deprecated in 3.0 and removed in 4.0)
