### ISSUE TITLE
Will you provide a v3 sketch library?

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#4783]
## Summary

Hi there, 
have you deprecated sketch library for v3? Under https://clarity.design/documentation/get-started only Figma is listed.
I'd really appreciate it :). 

![image](https://user-images.githubusercontent.com/16038088/87404620-aa4f4000-c5be-11ea-99e0-aadfde3ebe83.png)

**Comment by mathisscott** [comment]
@aavelyn 
Yes, the Sketch library for Clarity was deprecated and our support for it ended in 3.0. I went on a quick search through our documentation's history and it appears that this wasn't called out externally (outside of a few mentions here on github). Internally, our entire design team made a concerted shift from Sketch to Figma so it seems that we may have lost the external communication in that process. 

With 3.0, you can still use the Sketch libraries in 2.0. There are a few color changes and some features that aren't in the 2.0 Sketch libraries but they are still pretty complete. Once the Figma libraries are updated to 4.0, however, things are starting to get much different between the two files.

I apologize for the confusion.

CC: @gnomeontherun @reddolan

**Comment by aavelyn** [comment]
@mathisscott Thanks for the reply and sad to hear it! We've been using clarity and clarity designs in sketch since 2018 and switching over to figma would be quite a challenge.

Do you have an estimate on how long the Sketch libraries in 2.0 will stay "relevant" so that we can plan a potentiall migration?

**Comment by mathisscott** [comment]
@aavelyn 
The sketch library is only a _little_ out of date now. It will be more out of date with the release of v4 (later this month) and by v5 (near the end of this year) or v6 (Spring 2021) it will be fully out of sync.
