### ISSUE TITLE
Color palettes on website are not correct

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#4784]
### In codebase
`$clr-color-warning-900 = hsl(38, 100%, 38%)`

### On website (v3)
`$clr-color-warning-900 = hsl(38, 100%, 28%)`

### In codebase
`$clr-color-success-700 = hsl(99, 100%, 26%)`

### On website (v3)
`$clr-color-success-700 = hsl(93, 100%, 26%)`

We need to thoroughly review the color palettes in v2, v3, and v4 and make sure we update the documentation to the correct values.

**Comment by bdryanovski** [comment]
@mathisscott already done that in his sleep so. Closing with no work to be done flag.

... but taking the credit for it ..
