### ISSUE TITLE
Support using trackBy for datagrids using clrDgItems

### ISSUE THREAD

**Issue by moiraine** [vmware/clarity#4786]
## Summary

Support using trackBy for datagrids using clrDgItems

**What is the change?**
The request is to support trackBy on datagrids using clrDgItems so that the original data reference can be swapped out, but still maintain the clarity built-in goodness (filtering, sorting, paginating, clrDgPreserveSelection, and more?)

**Why should it go in Clarity?**
This is an enhancement that would save some non-ideal workaround code in the case where we want data to update but don't have server-side sort/filter/pagination

**Does this change impact existing behaviors? If so how?**
This change should not impact existing behaviors

**If this change introduces a new behavior, is this behavior accessible?**
There should be no new UX behavior as a result of this change

## Use case

Our use case is that we have data in grids that can have changing columns, such as a state column that goes from "Pending" to "Connected".  We want to be able to easily swap the old data out for the new, and the cleanest would be to simply reassign what is being fed into clrDgItems

## Workarounds

Here's my stackblitz workaround to sync the data without touching any references that clarity needs in order to keep existing functionality in place: https://stackblitz.com/edit/slack-dg-single-selection-memory-ttt9cw?file=src%2Fapp%2Fapp.component.html

**Comment by mathisscott** [comment]
Hi @moiraine 
Thanks for the stackblitz and suggestion! I'll take this back to @hippee-lee and @gnomeontherun for triage.

**Comment by gnomeontherun** [comment]
Clarity does support trackBy on clrDgItems, so I'm not exactly sure if there is anything that we need to do. I'm going to close this as already a feature.
