### ISSUE TITLE
[DataGrid]: Cannot add/remove columns when grid is empty

### ISSUE THREAD

**Issue by Tushar2098** [vmware/clarity#4790]
## Describe the bug

DataGrid doesn't update the columns when we try to add/remove the columns when the grid is empty. 
DataGrid shows correct columns only when the grid has data. But I should be able to update columns even when the grid is empty.

Also, I should be able to update columns without using `clrDgHideableColumn` attribute.

## How to reproduce

1.  Go to [Stackblitz](https://stackblitz.com/edit/clarity-scrollbar-hiddencol-pnbxpj)
2.  Click on Add Color Col button. 
3.  Notice Color column is not added when the grid is empty

## Expected behavior

I should be able to update columns even when grid is empty

## Versions

- Clarity: 2.4

**Comment by mathisscott** [comment]
@gnomeontherun & @hippee-lee 

Note that the current workaround is to add a call to resize the datagrid (see commented out code in the stackblitz).

The question is, whether we should handle that on our end.

**Comment by bdryanovski** [comment]
Can we close this?
