### ISSUE TITLE
Semantic tagging of icons to allow a flexible search

### ISSUE THREAD

**Issue by ayashjorden** [vmware/clarity#4792]
## Summary

_When I search for an icon on Clarity website, I want to search based on the need, for example searching for the `lightbulb` icon can be searched by using `light`, but also by using `idea` (currently, `idea` does not yield any results.)_

## Use case

Assist the user to get the right icon based on more than just the exact keyword for that specific icon.

## Examples

`lightbulb` icon should show up when searching `idea` - just my line og thought.

## Workarounds

None. need to search for partial or exact match.

**Comment by mathisscott** [comment]
We try to handle this through icon aliases. We have a few icons already that do this. "Home" and "House", for example, point to the same icon. And if you search for "warning", you'll see "exclamation-triangle" in the results.

I think the main issue here is that we are lacking in some aliases. I'd be happy to add them if a list were compiled. The problem with us adding aliases willy-nilly is it becomes a bit like throwing darts at a board blindfolded. Sure, a few might stand out. But the ROI would be low for us to try to predict the context for all the icons in the library.

Do you have any aliases you would like us to add?

**Comment by dorthrithil** [comment]
I think an issue with aliases in contrast to tagging is that they have to be unique. For example all the currency icons could be tagged with "currency" or "money", but you cannot give them the same alias. 
The suggested tagging is probably more a website enhancement than an actual change in the library.

**Comment by gnomeontherun** [comment]
This is certainly limited to an enhancement to the website, which was recently relaunched. I agree that adding more tagging is potentially helpful but also potentially arbitrary and hard to define. We will close this issue for now as something we don't intend to prioritize in the near future, but should someone consider a contribution we would be open to it.
