### ISSUE TITLE
Can you provide a wrapper for tabler icons similar to your clr-icon component

### ISSUE THREAD

**Issue by wpfeiffe** [vmware/clarity#4794]
## Summary

_Can you provide a wrapper for [tabler](https://github.com/tabler/tabler-icons) icons._

- Provide nice wrapper for [tabler](https://github.com/tabler/tabler-icons) icons. 
- Seems like a nice compliment to your existing icon set
- Should NOT impact existing behaviors

## Use case

_Larger set of icons to choose from_

## Examples

_See  [tabler](https://github.com/tabler/tabler-icons) icons._

## Workarounds

_Use another icon within your set or write my own wrapper or use tabler svg directly in my app_

If you choose not to implement this, I'll completely understand, but you don't get what you don't ask for!

**Comment by hippee-lee** [comment]
The [Clarity Icons API](https://clarity.design/icons/api) can accolade this.  

```typescript
ClarityIcons.add({"my-custom-icon": "<svg ... >[your SVG code goes here]</svg>"});
```
