### ISSUE TITLE
Enhancement - Select Component Disabled State Looks Similar to Active State with Placeholder

### ISSUE THREAD

**Issue by jkuo-vmware** [vmware/clarity#4795]
## Summary

_Summary the request and address the questions as appropriate._

This is an enhancement request due to the select box's active state with placeholder text looking too similar to the disabled select component.

## Use case

Having a clear visual distinction between active and disabled states for any component is crucial to helping to set expectations to users for what they can and cannot perform actions on.

## Workarounds

Continue using as is to remain Clarity compliance

**Comment by mathisscott** [comment]
I believe this was handled by #4461 

Closing as a duplicate unless that turns out to not be the case.
