### ISSUE TITLE
Setting clrForm [clrLayout] does not work

### ISSUE THREAD

**Issue by GaryHyland** [vmware/clarity#4796]
## Describe the bug

I find that the following code to change form layout depending on page width does not work.

`<form clrForm [clrLayout]="window.innerWidthPx>576?'horizontal':'compact'"  #frmForm="ngForm">`

Initial HTML generated for a window > 576 width is as expected below
`<form _ngcontent-igw-c6="" clrform="" novalidate="" ng-reflect-layout="horizontal" class="ng-untouched ng-pristine ng-valid clr-form clr-form-horizontal">`

However when I resize the window < 576 I get HTML

`<form _ngcontent-igw-c6="" clrform="" novalidate="" ng-reflect-layout="compact" class="ng-untouched ng-pristine ng-valid clr-form clr-form-horizontal">`

So the reflect layout has been updated but the clr-form-horizontal class remains.

For now I find that set the classes directly as below to get required behaviour

`<form clrForm [class.clr-form-horizontal]="window.innerWidthPx>576" [class.clr-form-compact]="window.innerWidthPx<=576" #frmForm="ngForm">`

## How to reproduce

Refer details above

## Expected behavior

Use of [clrLayout] should adjust the classes defined on the form element.

## Versions

**App**

- Angular: [e.g. 8.2.14]
- Node: [e.g. 12.16.2]
- Clarity: [e.g. 2.4.2]

**Device:**

- Type: PC
- OS: Win10
- Browser: Chrome
- Version: 83.0.4103.116

**Comment by gnomeontherun** [comment]
This is missing a demo to view, and I don't know what `window.innerWidthPx` is a reference to. However, this is bad practice to reference the window object directly in the template and won't trigger change detection. You'd want to store this property on the controller instead and have a listener updating that value in your controller instead. Closing as this is likely an implementation issue and the goal of the form classes is to be responsive by default so this shouldn't even be necessary.
