### ISSUE TITLE
[DataGrid]: Cannot drag ghost element outside of the grid area

### ISSUE THREAD

**Issue by mibryamov** [vmware/clarity#4797]
## Describe the bug

We have a grid column with drag-handle icons to support dragging a row/rows outside of the grid and dropping them to some other area (clarity tree in our case). When you grab a row and start dragging, the dragging "ghost" element appears and starts following the pointer. The issue is that the "ghost" element cannot be moved outside of the grid, hence i am not able to drop it over the target drop area. This is the main issue, but other than that there are some other minor issues as well and all of them are regressions compared to Clarity: 2.4.4, that is why in the repro steps i am providing a link to the same app built with Clarity 2.4.4:

- dragging "ghost" element goes below the grid header and below the checkboxes column (when there is a multiple selection). I noticed that the selection column and the header row have `position: sticky;` style applied.
- i am not able to make the drag-column first by applying `order: -1;` style, the checkboxes column is always displayed first.
- the "ghost" element's background is very transparent and when i drag it at some point it is hard to read the ghost's content text when there is some other text in the background. I couldn't fix it by setting opacity:1; on the ghost.

## How to reproduce

1.  Go to [Stackblitz](https://stackblitz.com/edit/draggable-grid-clr-313)
2.  Grab the drag handle icon on some of the rows and start dragging.
3.  Try to drag the element outside of the grid boundaries and over the selection column or grid header.
4.  See the ghost element does not go outside of the gird, and also it goes below the selection column and header row.

The same repro steps are working fine as expected with Clarity 2.4.4 - [grid dragging clr 2.4.4](https://stackblitz.com/edit/draggable-grid-clr-244)

## Expected behavior

Behaviour must be the same as in Clarity 2.4.4:
- when dragging you should be able to move ghost element outside of the grid so you can drop it over the target area
- i should be able to make the dragging column first even if there is a selection column with multi-selection
- the ghost element's background should be opaque so the content is clearly readable

## Versions

- Clarity: [3.1.3]

**Comment by Shijir** [comment]
Hi @mibryamov!

The issue you are experiencing in Clarity v3.x is due to the underlying bug from Angular: https://github.com/angular/angular/issues/34066.

Once dragging starts, we apply `in-drag` class to the body element. You can apply your custom style if necessary within that class. You might need to apply those custom styles in your global style file. Take a look at the following example where I have applied some style changes in `style.css` file:

https://stackblitz.com/edit/draggable-grid-clr-313-dcddtu

**Comment by mibryamov** [comment]
Hi @Shijir, thanks for workaround, it worked! If angular fixes their bug, would you need to change something in your code? If not, i will close this bug, otherwise i will leave it open. Thanks!

**Comment by bdryanovski** [comment]
@Shijir can we close this ?
