### ISSUE TITLE
Unable to interact with elements outside of inline wizard in chrome

### ISSUE THREAD

**Issue by jguillot-altran** [vmware/clarity#4801]
## Describe the bug

Users are unable to interact with elements outside of an inline wizard (header / alerts / ...) when the content of the wizard page is superior to 100vh (when they zoom for example). This issue prevent closing global errors for example. This only happen with chrome, and when the content of the page is less than 100vh, user can interact with the rest of the app.

## How to reproduce

https://clarity-light-theme-v2-u6mjla.stackblitz.io

1. Try to close the global error with the cross button
2. You'll scroll in the view instead of closing the error

## Expected behavior

Error get closed.

## Versions

**App**

- Angular: 8.2.14
- Node: 12.18.0
- Clarity: 2.3.3

**Device:**

- Type: Dell laptop
- OS: Windows 10
- Browser Chrome
- Version 83.0.4103.116

**Comment by mathisscott** [comment]
The static, inline wizard is not supported. It was introduced as a convenience for product teams with the caveat that it is a pattern we would not be putting active development towards, beyond providing basic CSS to place the wizard inline.

The behavior you are seeing is likely related to the focus trap on the wizard. I recommend either sub-classing the wizard to turn that off or finding a way to turn that off through your application.

**Comment by jguillot-altran** [comment]
Adding resolution for other that share this use case: removing the tabindex attribute of the modal (clr-wizard > clr-modal > .modal, the one with the directive clrfocustrap) solve the issue.

In my case I simply did `this.wizardContainer.nativeElement.querySelector('.modal').removeAttribute('tabindex');` where wizard container is a div wrapping my clr-wizard
