### ISSUE TITLE
Detail pane indicator doesn't follow track by

### ISSUE THREAD

**Issue by ryan-bradford** [vmware/clarity#4806]
## Describe the bug

When using a trackBy and a detail pane. If the user opens the detail pane, the arrow lights up blue. If the data in the grid is then refreshed, the detail pane stays open (as it should), but the arrow turns back to gray. The grid should be smart enough to use the trackBy to maintain the detail pane indicator status.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-light-theme-7sphh9?file=src%2Fapp%2Fapp.component.html

1. Open any detail pane
2. Observe that the detail pane is open and the arrow is blue
3. Click the "Edit" button to trigger a data refresh
4. Observe that the detail pane is still open but the arrow is gray
5. Press edit
6. Observe that the detail pane is still open and the arrow is blue again

## Expected behavior

The arrow should always stay blue because the entity was never removed according to the track by function.

## Versions

**App**

- Angular: 9
- Node: 12
- Clarity: 3.0.0

**Device:**

- Type: Macbook
- OS: Catalina
- Browser Chrome
- Version 83.0.4103.116

**Comment by gnomeontherun** [comment]
This is interesting, the issue is likely that we aren't testing equality somewhere with trackBy in mind, so it doesn't highlight the correct row. Should be a minor fix, but adding to the buglist.

**Comment by ryan-bradford** [comment]
Thanks for triaging this Jeremy, appreciated as always!

**Comment by iilieva** [comment]
Hey Team,
Any update on this problem? It starts to escalate on our side...
Thanks!
