### ISSUE TITLE
Popover pointer not inheriting color correctly

### ISSUE THREAD

**Issue by ryan-bradford** [vmware/clarity#4807]
## Describe the bug

The popover pointer on the signpost uses a `border-right: 0.6rem solid white;` to get its color. It should instead use some CSS property (when enabled) to set the color (in the case of the default theme white). This breaks theming of the signpost when a user is using CSS properties.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-light-theme-b8kbka?file=angular.json
1. Open the signpost
2. Inspect the `.popover-pointer:before` element
3. See that the border-right uses the fixed color of `white` whereas on the `.signpost-wrap` the background-color uses some CSS property.

## Expected behavior

The `.popover-pointer:before` element should be theme-able using CSS properties.

## Versions

**App**

- Angular: 9
- Node: 12
- Clarity: 3.0.0

**Device:**

- Type: Macbook
- OS: Catalina
- Browser Chrome
- Version 83.0.4103.116

**Comment by Jinnie** [comment]
Assigning to myself, as I am currently working on some signposts changes.

**Comment by ryan-bradford** [comment]
Hi, did this issue ever get fixed along with the signpost changes?

**Comment by Jinnie** [comment]
The Clarity Angular popovers rework was put on hold in favor of the work on the Clarity Core (web-components) popovers.

**Comment by bdryanovski** [comment]
@Jinnie Can we close this now, we have some progress on that is coming into the next few release as beta components?

**Comment by Jinnie** [comment]
It seems it has been fixed in Angular too.
It is using `clr-signpost-pointer-invisible-border` currently.
