### ISSUE TITLE
Update CLI installer to support Angular 10, tslib 2.0 and @clr/ui 4.0

### ISSUE THREAD

**Issue by Nikkala-AIS** [vmware/clarity#4809]
## Describe the bug

The Clarity packages have not been updated to support Angular 10 and tslib 2.0.

## How to reproduce

I have Angular 10 installed, and tslib 2.0.  When trying to install Clarity for the first time using the Angular CLI option 1 (ng add @clr/angular), it did not install @clr/core and gave me a warning about unmet peer dependencies.  It did install the other Clarity elements.

When I installed @clr/core separately, it gave more peer dependency messages, but did install:  
<img width="1093" alt="Screen Shot 2020-07-18 at 10 43 50 AM" src="https://user-images.githubusercontent.com/62292109/87855162-6329bd80-c8e4-11ea-9bb4-a1127486da4c.png">

Note that the Clarity ui @clr/ui is at version 4.0.0 and also triggers a peer dependency warning.

1.  Go to Angular app root directory in terminal window
2.  Enter "ng add @clr/core"
3.  See npm warnings

## Expected behavior

CLI installation of Clarity should proceed without npm warnings.

## Versions

**App**

- Angular: 10
- Node: 13.11.0
- Clarity: 3.1.4

**Device:**

- Type: MacBook
- OS: iOS
- Browser None
- Version n/a

## Additional notes

_Add any other notes about the problem here._

**Comment by bdryanovski** [comment]
@Nikkala-AIS Thanks for pointing this out.

I could confirm this.

```bash
ng new my-app
cd my-app
ng add @clr/angular
```

Will install Clarity like this:

```json
"@clr/angular": "^3.1.4",
"@clr/ui": "next",             // 4.0.0-rc.1
"@clr/icons": "next",          // 4.0.0-rc.1
```
This setup doesn't trigger any errors. But after updating  to `@clr/angular: next` I'm getting this error:

```
npm WARN @clr/icons@4.0.0-rc.1 requires a peer of @webcomponents/custom-elements@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @clr/angular@4.0.0-rc.1 requires a peer of @clr/core@4.0.0-rc.1 but none is installed. You must install peer dependencies yourself.
``` 

This will be handle in the next release. 
If you need to use the `@clr/core` you could install it by hand for now. 

```bash
❯ npm run start

> my-app@0.0.0 start /Users/bdryanovski/trash/my-app
> ng serve

Compiling @angular/core : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/compiler/testing : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/core/testing : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser/testing : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/common/testing : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/platform-browser/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/common/http/testing : es2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : es2015 as esm2015
Compiling @angular/router/testing : es2015 as esm2015

chunk {main} main.js, main.js.map (main) 58.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 781 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.29 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.55 MB [initial] [rendered]
Date: 2020-07-21T07:49:42.586Z - Hash: d91532f04a756eb5fe30 - Time: 11502ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```

**Comment by gnomeontherun** [comment]
Clarity v3 does not work with Angular 10. The best way to get it setup is to run `ng add @clr/angular@next`. The bug listed here is resolved in the v4 release so this shouldn't happen after v4 is launched.

To fix your current issue run `npm i -D @clr/angular@next @clr/icons@next @clr/ui@next` to get the latest preview release.

Closing as should already be resolved.

**Comment by Nikkala-AIS** [comment]
Thanks!  When will v4 come out, is there an estimate?

**Comment by bdryanovski** [comment]
Hopefully by the end of the week

**Comment by Nikkala-AIS** [comment]
Excellent!
