### ISSUE TITLE
clr Angular issues when connecting to AWS Amplify UI library

### ISSUE THREAD

**Issue by chris-daw** [vmware/clarity#4814]
Hello folks,

I'm encountering an issue with clarity on Angular when used in conjunction with AWS Amplify libraries for authentication. I'm still trying to figure out what/where the issue is, but hopefully by posting my early findings some of you who know clarity better than my beginner level will be able to share a pointer or two...

I'm basing this on Angular 10, Clarity 3.1.4, and AWS Amplify 3.0.20 with @aws-amplify/ui-angular UI components 0.2.12. I've not included a reproduction build as it requires a working AWS Amplify authentication back end.

I've noticed this issue on Dropdown menus, but it may not be limited to just those.

When the application is run with no <amplify-authenticator> wrapping it, dropdown menus display just fine. When you do include an <amplify-authenticator> around it however, the styling goes completely, and whilst they open they don't seem to close up again, and links within dropdown elements don't seem to work.  A screenshot from Chrome (it seems to happen across Chrome, Firefox, Edge) will show you what I mean with it opening - this is just a standard <clr-dropdown> in the header bar.
![clr-angular-withamplify](https://user-images.githubusercontent.com/601226/88170496-b3bb5680-cc15-11ea-8ddd-dc597f16e52a.png)

I haven't figured out what's going on yet, and will post updates as and when I make any steps forward. If any more info is useful to diagnose, please let me know.

**Comment by bdryanovski** [comment]
Hey @chris-daw, 

It's hard to even understand what is the issue by screenshot. What I'm seeing is just a lot of components/texts/icons on top of each other but it's hard to know why and is there any way to improve it. 

So if you could provide us with some code and examples, something that we could try to test and play with - it will be really hard to help you.

**Comment by gnomeontherun** [comment]
Closing this as stale since we don't have anything actionable to triage or review. If the issue persists, please provide an updated reproduction so we can triage.
