### ISSUE TITLE
Showing datagrid detail when first column is hidden breaks datagrid layout

### ISSUE THREAD

**Issue by brannislav** [vmware/clarity#4815]
## Describe the bug

When the first column of a datagrid is hidden and detail pane is shown the header and column layout is broken.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-light-theme-wxad1s

1.  Click show detail button on any row.

## Expected behavior

Layout should not break.

## Versions

**App**

- Angular: 9.1.9
- Node: 10.19.0
- Clarity: 3.1.1

**Device:**

- Type: PC
- OS: Windows 10
- Browser: Chrome
- Version: 84

## Additional notes

This seems to be related to the fact that when detail pane is shown all columns except the first one are hidden. However if the first column is hidden than this issue occurs.

**Comment by hippee-lee** [comment]
Can you explain the issue you observe? Here is what I see in the reproduction (thank you for that) and it seems correct to me. 

![Screen Shot 2020-07-22 at 7 58 11 AM](https://user-images.githubusercontent.com/433692/88192253-29f99200-cbf1-11ea-9e80-3bb62cfb6020.png)

**Comment by brannislav** [comment]
Few things seem odd to me when detail is shown:

- The header shrinks in height
- White-space is shown between header and first row
- Gap opens in the datagrid detail border (left of the detail header text)

I'm adding a gif that illustrates those issues.

![Datagrid detail issue when first column is hidden](https://user-images.githubusercontent.com/24313515/88270183-ea5ca400-ccdd-11ea-93df-cbfb966e3ba3.gif)

**Comment by gnomeontherun** [comment]
The first column is automatically used to display in detail mode, so if you allow it to be hidden the Datagrid will show an empty column like this. The intention is that you'd not allow the first column (presumably something clearly identifying) to be hidden. This is working as expected, but we should make sure to call this out in the documentation.

**Comment by bdryanovski** [comment]
I'm marking this as resolved
