### ISSUE TITLE
Cells from a datagrid row disappear when using a conditional to control visibility of expandable row

### ISSUE THREAD

**Issue by vigie** [vmware/clarity#4818]
## Describe the bug

Cells from a datagrid row disappear when using a conditional to control visibility of expandable row.

If you update the reference to the data in the row the cells come back. However, this workaround does not work if you are also using a trackBy function.

## How to reproduce

Open this, count to 3 and watch cells disappear. Other scenarios and workarounds explored in code comments here:

https://stackblitz.com/edit/clarity-v3-dark-theme-yhhu6z

## Expected behavior

Cells should not disappear regardless of using new data/existing data/trackBy

## Versions

**App**

- Angular: 8 and 9
- Clarity: 2 and 3

**Device:**

- Type: MacBook
- OS: iOS
- Browser chrome
- Version 84.0.4147.89

**Comment by bdryanovski** [comment]
This issue is not reproducible into the latest v3 version (v3.1.14)
