### ISSUE TITLE
CSS no word-break in "alert" component/element

### ISSUE THREAD

**Issue by aleksandrenko** [vmware/clarity#4819]
Case: Rendering server errors containing long non-breakable string in an alert component/element. The text is rendered in a single line not breaking into multiple like it should.

1.  Go to https://clarity.design/documentation/alerts
2.  Edit a error text and change it to:" Rendering_server_errors_with_no_place_for_auto_breaking_words_Rendering_server_errors_with_no_place_for_auto_breaking_words_Rendering_server_errors_with_no_place_for_auto_breaking_words_Rendering_server_errors_with_no_place_for_auto_breaking_words_Rendering_server_errors_with_no_place"

3.  The text will overflow and keep the error on single line. 

## Expected behavior

- It should break the string into multiple lines letting the parent dom element to respect the styling and sizing restrictions.

## Additional notes

fix: word-break: break-all.

**Comment by bdryanovski** [comment]
You are right for that, but not sure if there is a practical reason for having such a long word without any space in it. Also when it comes to accessibility this will be for sure something hard for SR to say. 

Still, there could be some cut-off on really small windows or high screen zoom.
