### ISSUE TITLE
Stepper `firstPanel` is undefined

### ISSUE THREAD

**Issue by portothree** [vmware/clarity#4822]
## Describe the bug

I know that there's a already issue for that problem https://github.com/vmware/clarity/issues/4353, in my case thestepper seems to work correctly, but it throws a `TypeError: can't access property "id", firstPanel is undefined` which refers to the function `openFirstPanel()` found in `clr-angular.js` webpack bundle.
```js
openFirstPanel() {
        const firstPanel = this.getFirstPanel();
        this._panels[firstPanel.id].open = true;
        this._panels[firstPanel.id].disabled = true;
        this.stepperModelInitialize = true;
    }
```

## How to reproduce

1.  Open any page with a `clr-stepper-panel`
2.  See error on console

## Expected behavior

The first panel gets opened without throwing a TypeError

## Versions

**App**

- Angular: 9.0.1
- Node:12
- Clarity: 3.1.5

**Device:**

- OS: Debian
- Browser: Firefox
- Version 78

**Comment by bdryanovski** [comment]
Hey @portothree thanks for reporting this but I can't reproduce it, did not saw any error anywhere, can you provide a StackBlitz example, you could find a startup template here: https://stackblitz.com/@clr-team 

It will be a lot easier for us to find and fix if there are any issues. 

Thanks.

**Comment by portothree** [comment]
> Hey @portothree thanks for reporting this but I can't reproduce it, did not saw any error anywhere, can you provide a StackBlitz example, you could find a startup template here: https://stackblitz.com/@clr-team
> 
> It will be a lot easier for us to find and fix if there are any issues.
> 
> Thanks.

Thanks for the fast response. I have uploaded a similar case https://stackblitz.com/edit/clarity-v3-light-theme-bfft4r, and by doing so I realize what my problem was; forgot to use `*clrIfExpanded` and the second panel interacts/depents on the first one, so it was running before the user fills the first panel.

**Comment by bdryanovski** [comment]
Thanks for the demo, will check it to see what is going on .. .

**Comment by portothree** [comment]
Nice!! Thank you for taking a look
