### ISSUE TITLE
Date picker doesn't work well with data grid custom filter

### ISSUE THREAD

**Issue by vraddy** [vmware/clarity#4827]
## Description
Date picker doesn't work well with data grid custom filter.
Trying to implement date range custom filter in data grid column.
- Date picker has less z-index than custom filter panel - so it gets hidden behind custom filter panel
- On select of date custom filter panel gets closed.
- There is some position issue in this sequence, open clr-dg-column-toggle panel -> close it -> open custom filter panel, now custom filter panel is displaying in top left corner of the page.
- on click of custom filter column filter icon, sort action is getting triggered. 
- and also custom filter show up in clr-dg-column-toggle panel, is this expected behavior ?

## How to reproduce
https://stackblitz.com/edit/clarity-v3-light-theme-4qytsw
example of custom date range filter in data grid.

## Expected behavior
- Date picker should have more z-index than custom filter panel - so it should show on top of custom filter panel
- Custom filter panel should not close on date select, it should stay on until user close.
- custom filter panel should not loose it position on open and close of clr-dg-column-toggle panel.
- on click of filter icon in custom filter column should not trigger sort action.
- Is there a way to hide custom filter in clr-dg-column-toggle ?

## Versions

**App**

- Angular: 9
- Clarity: 3

**Comment by vraddy** [comment]
@gnomeontherun thanks for looking into this, Do you have any workaround for "On select of date custom filter panel gets closed." ?

**Comment by alfidanov** [comment]
Are there any plans to fix this issue? It is a pretty common scenario to use a DatePick to filter a Date column.

**Comment by Kangcor** [comment]
There is some known workaround for this?
