### ISSUE TITLE
responsive alignment tokens for cds-layout

### ISSUE THREAD

**Issue by krotscheck** [vmware/clarity#4831]
## Summary

I am looking for responsive equivalents of `align:stretch` in the new cds-layout engine.
```
< ... cds-layout="vertical align@sm:stretch" >
```

The reason I feel it should be in clarity, is because I intuitively expected them to be there. Working through a component using `display:none display@sm:flex` and similar styles, I automatically assumed that responsive alignment markers would also be available. When I didn't find them in the documentation, I dug through the code to see that they weren't there.

## Use case

Alignment of controls towards the bottom on mobile devices, easily accessed by thumbs, while the content between the header and the controls can scroll. On non-mobile devices, allow the controls to flow as per the clarity button alignment guidelines.

## Examples

Attached are a desired layout for `lg` and `xs`
<img width="1307" alt="Screen Shot 2020-07-29 at 10 22 58 AM" src="https://user-images.githubusercontent.com/965182/88832423-a35f2a80-d185-11ea-930a-9ab8aea8ddba.png">
<img width="430" alt="Screen Shot 2020-07-29 at 10 23 39 AM" src="https://user-images.githubusercontent.com/965182/88832428-a528ee00-d185-11ea-9a3f-e3bb790c5b9f.png">

## Workarounds

I've tried to add my own extensions to `cds-layout` with no luck. Importing and using the clarity breakpoint variables also doesn't seem to be officially supported, but it's feasible.

**Comment by coryrylan** [comment]
Thank you for opening an issue. This feature was intentionally left out for the first release due to performance. To generate each alignment direction for all breakpoint combinations caused the global CSS to bloat quite a bit. We can revisit this and see if we can better optimize the output for higher compression levels or maybe a subset of all combinations.

**Comment by krotscheck** [comment]
Well, the bar you'll be measured against is flexbox, because it's the toolkit that already solves these problems. Anyone trying to use cds-layout (like me) won't have much patience for feature gaps.

**Comment by coryrylan** [comment]
Resolved and implemented in https://github.com/vmware/clarity/pull/4892
