### ISSUE TITLE
Icons Volume 18

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#4839]
## Icons Volume 18

Epic to consolidate icon requests for the next icon release

**Comment by d-m-s** [comment]
an icon for marking birthdays would be great.

Something similar exists in Material Design - See https://material.io/resources/icons/?icon=cake&style=outline

<img width="87" alt="2020-10-27_16h16_29" src="https://user-images.githubusercontent.com/311619/97322596-3d5f6d80-1870-11eb-8d87-40bb80f790cb.png">

**Comment by lil-kim** [comment]
@gnomeontherun,
I've attached all the icons for this epic:
[icons-vol-18.zip](https://github.com/vmware/clarity/files/5527224/icons-vol-18.zip)
This completes issues: #4730 and #4840
