### ISSUE TITLE
[Datagrid] update of data with streaming api in datagrid breaks the view and does not show any row.

### ISSUE THREAD

**Issue by pksatgithub** [vmware/clarity#4842]
issue1 : I tried to consume a reactive api (spring webflux) using EventSource, 

pushed each packet of data to the  clrDgItems holder.

rows of datagrid are not displaying until we click on window.

 issue2: 
when we trigger event using single row action (cancel) then after success of event. reloading the datagrid rows using the reactive api breaks datagrid.

getting this error:

errors.ts:30 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'null'.
    at throwErrorIfNoChangesMode (errors.ts:59)
    at bindingUpdated (bindings.ts:62)
    at Module.ɵɵproperty (property.ts:39)
    at ManagePickupDatagridComponent_Template (manage-pickup-datagrid.component.ts:26)
    at executeTemplate (shared.ts:553)
    at refreshView (shared.ts:411)
    at refreshComponent (shared.ts:1691)
    at refreshChildComponents (shared.ts:141)
    at refreshView (shared.ts:468)
    at refreshEmbeddedViews (shared.ts:1641)

So, is it possible to trigger an update or how can I handle this?

implementation:

`  <clr-dg-row *clrDgItems="let rowData of tableData" [clrDgItem]="rowData"`

```
setPickup() {
    this.loader = { status: true, msg: this.i10n.SHARED.loadingMsg };
    this.selectedPickup = undefined;
    this.displayAllAction();
    this.clearTable();
    this.managePickupService
      .getPickup()
      .pipe(
        finalize(() => {
          if (this.loader.status) {
            this.setNoDataFound();
          }
          this.filterByDateOfRequest(this.requestDateFilterForm.value);
          this.resetPaginationToFirstPage();
          this.pickupGuidTracklaneMap.clear();
          this.pickupAlertMap.clear();
        }),
        takeUntil(this.unsubscribeAll$)
      )
      .subscribe(
        (pickup: any) => {
          if (this.loader.status) {
            this.setNoDataFound();
          }
          pickup = <ManagePickupModel>JSON.parse(pickup);
          this.setDateOfSanitizationAndDateOfPickup(pickup);
          this.addPickup(pickup);
          this.datagrid.rows.notifyOnChanges();
        },
        error => {
          this.pickupList = this.clearedPickupList;
          this.tableData = this.clearedTableData;
          console.log('error in fetching pickup : ', error);
        }
      );
  }

  clearTable() {
    this.clearedPickupList = this.pickupList.splice(0, this.pickupList.length);
    this.clearedTableData = this.tableData.splice(0, this.tableData.length);
  }

  addPickup(pickup: ManagePickupModel): void {
    if (this.whitelistPickup(pickup)) {
      this.pickupList = [...this.pickupList, pickup];
      if (this.showArchived) {
        this.tableData = [...this.tableData, pickup];
      } else if (this._constants.PICKUP_STATUS.ARCHIVED.value.toUpperCase() !== pickup.status.toUpperCase()) {
        this.tableData = [...this.tableData, pickup];
      }
    }
  }
```

**Comment by hippee-lee** [comment]
This sounds like a [server driven datagrid](https://clarity.design/documentation/datagrid/server-driven). They use `*ngFor` and have a few other differences like the `(refresh)` output. 

Can you try with that and see if it solves the issue? If not, We keep [stackblitz starter apps ](http://stackblitz.com/@clr-team)for creating a minimal reproduction that we can use to diagnose and triage with.

**Comment by pksatgithub** [comment]
Sure i will try with [server driven datagrid.](https://clarity.design/documentation/datagrid/server-driven).

**Comment by gnomeontherun** [comment]
This issue does not have a reproduction and we are going to close it as stale. If the issue persists, please provide a working [Stackblitz demo](https://stackblitz.com/@clr-team) to get started.
