### ISSUE TITLE
Compilation error with clrLayout directive and strictTemplates = true

### ISSUE THREAD

**Issue by rootix** [vmware/clarity#4847]
## Describe the bug

When strictTemplates check in Angular 9/10 is enabled, i get the following error when i have a form with `clrForm` and `[clrLayout]="'vertical'"`:

`error TS2322: Type '"vertical"' is not assignable to type 'Layouts'.`

The Layouts enum is not exported in the library an therefore not usable.

## How to reproduce

1.  Create a sample form with clrForm and `[clrLayout]="'vertical'"`
2.  Enable strict template checks (https://angular.io/guide/template-typecheck#strict-mode)
3.  Compile and see build error

## Expected behavior

Use string literal type or export the Layouts enum to be usable in client code.

## Versions

**App**

- Angular: 10
- Node: 12.16
- Clarity: 3.1.4

**Comment by gnomeontherun** [comment]
This PR is open to try and fix this, https://github.com/vmware/clarity/pull/4601.
