### ISSUE TITLE
Compilation error with *clrIfExpanded directive and strictTemplates = true

### ISSUE THREAD

**Issue by rootix** [vmware/clarity#4848]
## Describe the bug

When using the `*clrIfExpanded` directive as documented with strictTemplates check enabled in Angular 9/10, i get the following compilation error: 

`error TS2322: Type 'string' is not assignable to type 'boolean'`

## How to reproduce

1.  Add the *clrIfExpanded directive to any supported component (i had it on grid `clr-dg-row-detail`)
2.  Enable strict template checks (https://angular.io/guide/template-typecheck#strict-mode)
4.  Compile and see build error

## Expected behavior

The compiler throws no error with the documented approach

## Versions

**App**

- Angular: 10
- Node: 12.16
- Clarity: 3.1.4

**Comment by bbogdanov** [comment]
Hi @rootix, thank you for sharing this issue with us. 

Could you please give us a stackblitz or repo example?

**Comment by rootix** [comment]
Hi @bbogdanov 

Sure, i made a simple reproduction case. 

https://stackblitz.com/edit/clarity-issue-4848?file=src/app/app.component.html

I was wrong with my initial expected behaviour. Allowing undefined is no solution, as it seems to get an empty string (hence the error message).

**Comment by envyN** [comment]
this happens even for *clrIfOpen usages and with strictTemplates:true in the tsconfig.

**Comment by Jinnie** [comment]
@bdryanovski can this issue be, by any chance, covered by our recent strict-mode related fixes?

**Comment by bdryanovski** [comment]
I think that for expand is cover but not for clrOpen .. or at least what I'm seeing from my phone. Will take a look, next week when get back to the office
