### ISSUE TITLE
Datagrid: Ability to pass custom loader template instead of default spinner loader

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#4852]
## Summary
Currently, we have support for traditional spinners to show while we wait for async data . To get closer to progressive loading concept (ghost elements/ skeleton) we need to have ability to provide custom template from outside for the consumers of data grid. Products like  facebook, slack are using ghost elements to have more engaging and progressive loading of elements.
_Summary the request and address the questions as appropriate._

- What is the change?
Support to pass custom template for data grid loader to replace the default spinner

- Why should it go in Clarity?
Clarity grid being heavily used across different VMware products and with the efforts to have more engaging User interfaces, it might be good from UX standpoint to be able to have progressive loader using ghost elements/skeletons. We need support 
 in the clarity's data grid component.

- Does this change impact existing behaviors? If so how?
This can be an optional behavior and can be used only when customisation is required.
 
- If this change introduces a new behavior, is this behavior accessible?
There shouldn't be an impact from a11y perspective due to loader.

## Use case

_Provide some specific details about how this change would improve your application and use case._

Using ghost elements matching with the data that would be rendered when actual data arrives would be more engaging for the users compared to spinner that we have today. It's like visualising the content that doesn't exist yet.
![image](https://user-images.githubusercontent.com/4294012/89056402-94d96480-d379-11ea-9faf-d9a7122a50a8.png)

Skeleton/Ghost elements if exposed as components can also be used at other places like navigation. 
e.g. Clarity's storybook
![image](https://user-images.githubusercontent.com/4294012/89057025-96eff300-d37a-11ea-91a3-ea971ce010dc.png)

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_
![image](https://user-images.githubusercontent.com/4294012/89056089-167cc280-d379-11ea-8227-b9a019d58270.png)
![image](https://user-images.githubusercontent.com/4294012/89056094-18468600-d379-11ea-8ebf-2486bc1cdbd7.png)

There are some frameworks that support skeleton/ghost elements as components. Not sure if that fits in roadmap for clarity but could be something for consideration.
e.g. https://ng.ant.design/components/skeleton/en

## Workarounds
_Is there a workaround for this feature at the moment, even if it is less than ideal?_
No. Couldn't find a workaround to render the custom ghost elements in place of clarity spinner.
Current spinner: https://github.com/vmware/clarity/blob/108707ac84f031174cde683eb24802e437c430c0/packages/angular/projects/clr-angular/src/data/datagrid/datagrid.html#L76

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our GitHub Discussions.
