### ISSUE TITLE
Combobox: Dropdown can still be opened when disabled

### ISSUE THREAD

**Issue by jisensee** [vmware/clarity#4868]
## Describe the bug

The dropdown of the new Combobox component can still be opened even when the control is disabled.

## How to reproduce

Set up a combobox with the reactive forms API and set the `disabled` field on the formControl to `true`.
The input field is correctly disabled but the caret button to open the dropdown is not and will trigger when clicked.

## Expected behavior

The caret button should also be disabled.

## Versions

**App**

- Angular: 10
- Node: 12
- Clarity: 4.0.o-rc.1

**Device:**

- Type: PC
- OS: Windows 12
- Browser: Chrome
- Version: 84

**Comment by bbogdanov** [comment]
@jisensee The fix will be available with `4.0.5` next week.
