### ISSUE TITLE
Fixed-height datagrid header obscures the first row if the header is bigger

### ISSUE THREAD

**Issue by hristozov** [vmware/clarity#4872]
## Describe the bug

When the datagrid header is bigger (e.g. a column caption is wrapped) on a fixed-height datagrid, it obscures the first row.

## How to reproduce

1.  Go to https://clarity.design/documentation/datagrid/fixed-height
2. Shrink the "Creation date" column enough to wrap "date" on the next line.
3. The first row is partially obscured.

<img width="897" alt="Screenshot 2020-08-05 at 17 58 24" src="https://user-images.githubusercontent.com/197483/89428643-4c3cf500-d745-11ea-83ca-812b628598e6.png">

## Expected behavior

The first row should be fully visible. Note this is the behavior in at least 3.1.3 and earlier.

## Versions

**App**

- Angular: 9.1.9
- Node: 10.x
- Clarity: 3.1.5

**Device:**

- Type: Macbook
- OS: Mojave
- Browser: Firefox 79 / Chrome 84

## Additional notes

This is a regression I found when upgrading from 3.1.3 to 3.1.5.

**Comment by whizkidwwe1217** [comment]
I'm also having the same issue. It happens when the column header text overflows.
![image](https://user-images.githubusercontent.com/1977391/89483095-e0529f00-d7cd-11ea-891e-3b330ebc664a.png)

**Comment by bbogdanov** [comment]
#4886 seems to fix particular cases. We will proceed with a different fix, cause the current one breaks the design in some cases when resizing the column.

@hristozov #4886 might be helpful until we do a better fix.

**Comment by Jinnie** [comment]
A commit in the v4 branch and release in v4 is needed before we can close this.

**Comment by hristozov** [comment]
Any plans for a minor 3.x update with this fix?

**Comment by mathisscott** [comment]
@hristozov 
Yep. We're working on that.
