### ISSUE TITLE
partial-property clrDgItem binding isn't applied to select all of datagrid

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#4885]
## Describe the bug

When clrDgItem is not the iterator object but its property, select all will still get the array of all objects.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v2-15mfeu

Scenario A:
1. refresh the page
2.  click on the select-all checkbox in the header
3. observe that the selected array is an array of all objects
4. observe that none of the checkboxes of data rows are checked

Scenario B:
1. refresh the page
2. check every checkbox of data rows
3. observe that the selected array is an array of all ids
4. observe that the select-all checkbox in the header is still unchecked

## Expected behavior

Scenario A:
1. the selected array should be an array of ids
2. all the checkboxes of data rows should be checked

Scenario B:
1. the select-all checkbox in the header should be checked

## Versions

**App**

- Angular: [8]
- Clarity: [1, 2, 3]

**Comment by bbogdanov** [comment]
Hi @KingMario, thank you for sharing this.

The team will need to do some investigation before we proceed with a fix. 

---

Meanwhile, there are two workarounds.

Instead of letting the `datagrid` select the `id`s of each object, you can do a mapping to get only the `id`s afterward.

```
selected.map(item => item.id)
```

Or listen for change in `datagrid` and extract the `id`s there.
```
<clr-datagrid [(clrDgSelected)]="selected" (clrDgSelectedChange)="selectionChanged($event)">
```

```
selectIdsHolder: number[];

// Some performance improvements will be needed depending on the data size
selectionChanged($event) {
   selectIdsHolder = $event.map(item => item.id);
}
```

**Comment by gnomeontherun** [comment]
`[clrDgItem]` needs to be the row object. Selected array should always reflect the list of selected items, so this is really an implementation problem. When you pass something that isn't the row object, we can't compare the objects correctly to understand what it is. So `[clrDgItem]` is always a reference to the row object you define in the `ngFor` or `clrDgItems` iterator. As Bogdan says, you can always look up the ids in the selected array if you need them.

I'm going to close this as working as expected when you use the documented API.

**Comment by KingMario** [comment]
Thanks @bbogdanov 
Thanks @gnomeontherun
