### ISSUE TITLE
Datagrid header row won't stick to the top with fixed height

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#4889]
## Describe the bug

When styling the datagrid with a fixed height and selecting page size of e.g. 100, the header row scrolls along after a while.
 
## How to reproduce

1. Go to clarity's [datagrid component with pagination](https://clarity.design/documentation/datagrid/pagination)
2. Select page size 100
3. Inspect the datagrid DOM element and give it a fixed height of 500px
4. Scroll down

## Expected behavior

Header row stays on top

## Versions

**App**

- Clarity: 3.1.5 

**Device:**

- Type: MacBook
- OS: macOs
- Browser: Chrome
- Version 84.0.4147.89

## Additional notes

I noticed on inspecting that div.datagrid-table-wrapper and div.datagrid-table don't have the full height als the row items, which is why the sticky header row stops sticking. Compare to older datagrid verions, you seem to have added new wrapper elements, maybe it's a styling bug?

![image](https://user-images.githubusercontent.com/16038088/89781441-9b9f6e80-db13-11ea-9db3-eb1c4b4e278a.png)

**Comment by bdryanovski** [comment]
Hello @aavelyn, thanks for opening the issue, we will investigate it and get back to you.

**Comment by edgas316** [comment]
@bdryanovski any update on this issue?

**Comment by bdryanovski** [comment]
No sorry, @edgas316 there is no fix for that for now. We gonna investigate it soon. 

I think I have an idea why this is happening but have to test it.
