### ISSUE TITLE
Tooltip Inside data-grid cuts off

### ISSUE THREAD

**Issue by kalpeshhpatel** [vmware/clarity#4891]
## Describe the bug

The tooltip gets cuts-off when used inside the datagrid.

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-datagrid-basic-bhegso
2.  Observe the tooltip for the first row. It gets truncated and user can't see the content. Also if we change the position of tooltip to the bottom, the scrollbar appears when tooltip for the last row is opened.

![image](https://user-images.githubusercontent.com/5223493/89790846-2bf3a880-db40-11ea-8204-8e0755abbd63.png)

Scrollbar for the tooltip position bottom:

![image](https://user-images.githubusercontent.com/5223493/89790936-475eb380-db40-11ea-98f9-bece76e150e2.png)

## Expected behavior

The tooltip should be completely visible to the user.

## Versions

**App**

- Clarity: 2.4.0

## Additional notes

The position relative on the `.datagrid-table` class seems to be the cause of this issue. Not sure why it is needed and what will be the side-effect to overriding it.

![image](https://user-images.githubusercontent.com/5223493/89791251-ad4b3b00-db40-11ea-83d9-adfa05380d42.png)

**Comment by bdryanovski** [comment]
It seems that by removing the `position: relative;` solve the issue - At first, I did not find any visible issues but have to test a bit more to be sure, it may be something left behind from previous implementations. 

It affects all versions from v2 to v4. 

Rewriting the tooltip with the SmartPopover must solve this type of issue in the feature.

**Comment by kalpeshhpatel** [comment]
Hi @bdryanovski , yea agree on SmartPopover based implementation for the tootip.

Is there any tentative timeline for the smart popover based tooltip and the signpost too ?

Adjusting tooltip and signpost position manually based on content is very annoying. And the smart popover is the only solution for such cases.

**Comment by bdryanovski** [comment]
Not yet, we are estimating currently the effort for migrating all components to use the Smart Popover, and there some improvements that have to be made before we could continue on that.

What I could say for sure that this is something that we have on our timeline and we are discussing it.

**Comment by kalpeshhpatel** [comment]
Thanks for the update @bdryanovski . Appreciated it.

**Comment by Jinnie** [comment]
This issue is tightly dependant on the smart popovers story https://github.com/vmware/clarity/issues/1757, which has been recently closed as something we want to fix in Clarity Core, and not duplicate effort for Angular too. As there is also a workaround, I am going to close this one.
