### ISSUE TITLE
 The grid row is not marked as selected after data refresh

### ISSUE THREAD

**Issue by dkanev** [vmware/clarity#4903]
## Describe the bug

I have clarity server side grid with selection. The grid uses *ngFor and trackBy function.
When I select a row in the grid and then refresh page data, the grid row becomes unselected, its check box becomes unchecked.
It is visible that the grid still keeps the selection, the footer shows that there is still selected row and if I move to the next grid page and return back to the previous grid page the grid row again is marked as selected and its check box is checked.

## How to reproduce
https://stackblitz.com/edit/clarity-v3-datagrid-selection

1.   Select a row
2.  Press "Refresh data" button
3.  The row becomes unselected, its check box is unchecked.

## Expected behavior
The row to stay marked as selected when refresh the data in the grid page.

## Versions

**App**

- Angular: 9.1.9
- Clarity: 3.1.3

**Device:**
- Browser Chrome

**Comment by bdryanovski** [comment]
Changing `*ngFor` to `*clrDgItems` will solve this issue:

```html
 <!-- Before --!>
  <clr-dg-row *ngFor="let user of users; trackBy: trackById" [clrDgItem]="user">

 <!-- After --!>
  <clr-dg-row *clrDgItems="let user of users; trackBy: trackById" [clrDgItem]="user">
```

**Comment by dkanev** [comment]
@bdryanovski :My use case is server side grid, so I can't use *clrDgItems. This is mention also in the description of the bug. Please consider reopen he bug as your suggestion doesn't work for my case.

**Comment by bdryanovski** [comment]
The issue here is that the `selection` array is holding an old reference to the `data` array. 

So to fix that you need to make sure that `selection` array is having the correct items inside when updating the data that is displayed.

```ts
this.selection = this.allUsers.filter((user) => this.selection.find((selection) => selection.id ===user.id))
```

**Comment by dkanev** [comment]
Why the grid doesn't update correctly the selected items, when I provide new data? I have provided a track by function, it is visible that the grid keeps selected items, why not mark the rows as selected when the new provided data have the same trackby property as the initial one . When I select a row move to the next page,  update the data and then return back, I don't update the selected items, but the correct rows are selected and selection is visible. It will be good the grid to update and mark the correct rows as selected when I only update the data too. In real example I don't have all data so to filter through them and find again selected rows so to provide them to the grid, I probably can  write a directive which to solve my problem, but  I think that it will be good the grid to be fix and to behave correctly as it behaves correctly when I select a row, move to the next page, update the data and return to previous page and the selected row is visible.
