### ISSUE TITLE
Tabs overflow menu do not become hidden when clicks outside

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#4906]
## Describe the bug

Tabs overflow menu do not become hidden when clicks outside.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-tabs-overflow?file=src/app/app.component.html

1.  Click on '...'
3.  Click outside of opened tabs overflow menu
4.  See error

## Expected behavior

Tabs overflow menu should become hidden when clicks outside.

## Versions

**App**

- Angular: 9.0.0
- Node: 10.13.0
- Clarity: 3.0.0

**Device:**

- Type: MacBook
- OS: MacOS
- Browser: Chrome
- Version: Latest

## Additional notes

This behaviour was broken when the positioning of this menu was changed from fixed to absolute.

**Comment by gnomeontherun** [comment]
Have you updated to the latest v3? I don't see this problem when I update the dependencies in Stackblitz.

**Comment by belyan** [comment]
Not yet, I am still using 3.0.1. I am going to check this defect in version 3.1, If it would be not reproduce I will close this issue.

**Comment by belyan** [comment]
@gnomeontherun, I checked this defect on version 3.1.x, it is not reproduce anymore.

One more question. Why overflow menu doesn't become hidden after selecting tab from it? Is it proper behaviour?

On old versions the menu become hidden in this case:
https://vmware.github.io/clarity/documentation/v0.13/tabs

**Comment by belyan** [comment]
I created new bug report based on my last comment:
https://github.com/vmware/clarity/issues/5006

P.S. It would be nice to get any feedback on my questions. Because I spend my time to improve your library.
