### ISSUE TITLE
Selectable Card Component

### ISSUE THREAD

**Issue by mandyxs** [vmware/clarity#4908]
## Summary

I'd like to propose a selectable card component. This component is largely based on the current card component. Currently the card component can be used as a container to group information with action buttons in it. It is also used as a clickable link sometimes in VMware products. 

This proposal aims to expand the capabilities of the card so that it can be used as a selectable target. 

The selectable card is used in a similar way as radio button. Each card is a selectable target that contains extra information related to the option. The selectable card has 4 states, normal, hovered, selected, and disabled. Each card has a radio button on it to help indicate that the card is a select target. The radio button also makes the component more accessible because users with low vision and/or are color blind can easily tell which card is selected by looking at the radio button. (In many of the selectable card behavior examples we found online, the only way to tell a card is selected or not is from the outline color or the background color of the card).

<img width="773" alt="Screen Shot 2020-08-14 at 11 06 45 AM" src="https://user-images.githubusercontent.com/29969351/90279555-4b2f5600-de1e-11ea-8d03-b1b2c35478d2.png">

Selectable cards can also contain additional options related to the selected option. This allows the additional option to stay in context and makes the selection process more intuitive.

<img width="612" alt="Screen Shot 2020-08-14 at 11 07 59 AM" src="https://user-images.githubusercontent.com/29969351/90279630-6e5a0580-de1e-11ea-910c-a9b3590d99d4.png">

Selectable cards provide the capability to display additional information related to an option, which helps users compare options easily and make informed decisions. They group information efficiently, allow better browsability of the options in the UI and they provide larger click targets. 

Selectable cards can be displayed horizontally or stacked vertically depending on the available screen space, making them a good pattern for responsive design. 

It's not the best idea to use selectable cards when there are more than 6 options, as these cards can take up a lot of space and user might need to scroll up and down to see all the options. 

The selectable cards would not change the current behavior of the cards. And because this component is largely based on existing clarity components (card and radio button) with similar behavior/look & feel, we believe it's an accessible component.

This component could benefit other products who want to adopt this component in their design. Selectable cards are widely used in consumer contexts (apple.com) as well as many enterprise cloud providers' product (AWS, IBM Cloud, Digital Ocean). Examples included in the **Other Examples** section below. 

## Use case

Today VMC on AWS and VMC on Dell are already using a custom version of the selectable card in the products.

> ![image](https://user-images.githubusercontent.com/29969351/90282302-f7733b80-de22-11ea-9d50-0e130cace102.png)
> In VMC on AWS, when the user goes to create a subscription, they get to choose the type of subscription from selectable cards. The cards emphasize the options with additional explaination to help the user make a choice.
> 

> ![image](https://user-images.githubusercontent.com/29969351/90282389-1bcf1800-de23-11ea-879a-5fb134f184d7.png)
> In VMC on Dell, selectable cards are used to present SDDC rack options when the user is ordering a SDDC. Since the user need to access additional information in order to make an informed decision, we pack the relative information in a card for easy browsability. Some rack options require additional power source location option and we are able to include this option on the card to keep it within its context.

> ![image](https://user-images.githubusercontent.com/29969351/90282435-330e0580-de23-11ea-9be9-b1d4f73b8c75.png)
> In VMC on Dell, selectable cards are also used to display host instance options. 

And because these cards are design & developed by different teams, they look and behave slightly different. Some of them might also have usability or accessibility issues. In order to provide a consistent experience and look & feel for our users, as well as to reduce engineering support effort for these custom cards, we believe it is worth it to make the selectable card a standardized component in Clarity. 

## Examples

Here are some examples we found from other consumer company and enterprise cloud products. 

> ![image](https://user-images.githubusercontent.com/29969351/90282572-6fd9fc80-de23-11ea-8b5a-ef58ec321f91.png)
> Apple.com uses selectable cards to help users easily select the configuration of their devices.

> ![image](https://user-images.githubusercontent.com/29969351/90282591-79636480-de23-11ea-9cb4-25897406c028.png)
> AWS Lightsail uses selectable cards to highlight the prices of each instance plan. 
> 

> ![image](https://user-images.githubusercontent.com/29969351/90282614-81bb9f80-de23-11ea-9e24-9403fdb76b1e.png)
> IBM Cloud uses selectable cards to present options when the user is creating a cloud instance. This is very similar our use cases.

> ![image](https://user-images.githubusercontent.com/29969351/90282633-8b450780-de23-11ea-96fd-e95bca786af0.png)
> DigitalOcean also uses selectable card when the user is creating a cloud instance. 

## Workarounds

As mentioned above, VMC on AWS and VMC on Dell are using custom versions of the selectable card in their product today. However, because they were design and implemented by different teams, they look slightly different from each other and behave differently. We hope the component can become part of Clarity so that these VMware Cloud products can provide a more consistent look & feel and experience for our customers and users. 

---
Thank you

**Comment by gnomeontherun** [comment]
Thanks for the detailed request and I want to make sure @colinreedmiller and @yuxin-ux see this. 

We already have 'clickable' cards, but this is a different pattern where cards act like a form control. The main concern I see around the request is about having nested clickable items (the card, and additional form controls inside of it). This is because of accessibility, so we would have to audit that carefully with the accessibility team.

**Comment by yuxin-ux** [comment]
@gnomeontherun I worked with Mandy a bit on this proposal. I had a similar concern about the clickable area. But at a certain time, there is only one thing that will be clickable. Either the whole card when not selected or the controls within the card when selected. So to me it's fine. We also had Amy Li looked at it briefly. She was ok with the design but more concerned about the implementation when we get to it.

**Comment by chlane** [comment]
I recommend against making cards clickable as a whole. If the cards contain interactive controls this will create an illogical focus order and confusing link text due to the large amount of content in the cards(https://webaim.org/techniques/hypertext/link_text#link_length). Additionally, some of the data in the card examples is tabular, blind screen reader users will not understand the tabular nature of the data when it is presented as a link.

**Comment by colinreedmiller** [comment]
@chlane since this is a useful enhancement for products, is there a way we might offer it with limitations that prevent the a11y errors from occurring?

**Comment by chlane** [comment]
If there is not much content in the card, and they don't contain tabular data or interactive controls, I think it's ok.

**Comment by colinreedmiller** [comment]
No tabular data or interactive controls makes for a clear guideline.
How can we apply specificity to 'not much content'?

**Comment by mathisscott** [comment]
The examples in the description show these cards as having `View Rack Diagram` Links or buttons.

How are those not interactive?

**Comment by chlane** [comment]
Yes I'm recommending against any designs that include anything interactive inside a link, button, radio button ect..

**Comment by mandyxs** [comment]
I had a chat with @chlane. I will update my examples to make sure no other interactive element is included in the card (and make sure to write that in the guideline). Chris also agree that in our domain, sometime we can't avoid the fact that an option comes with additional data to help user make an inform decision. So the kay-value pairs are acceptable. But we can put it in the guideline that we recommend less hierarchy in the card content.

**Comment by chlane** [comment]
It's not valid HTML to put interactive content inside an `<a> `element. Putting interactive content inside links as proposed here would violate [ Success Criterion 4.1.1 Parsing](https://www.w3.org/TR/WCAG21/#parsing). See the text "there must be no interactive content descendant, a element descendant, or descendant with the tabindex attribute specified." from https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element.

**Comment by chlane** [comment]
@colinreedmiller Regarding too much content being the length, the concern is that the link's purpose will not be understood. This would violate https://www.w3.org/TR/WCAG21/#link-purpose-in-context.  If a blind screen reader user hears link text like "M1s.medium sockets 1 cpu 24 cores 384 GB storage 24 TB no. of hosts 3 Power Configuration voltage 200 - 240 volts whips 4 whip length 10 ft power source connection i select power connector type nema L6 -30P" they may not understand what the link does.

**Comment by gnomeontherun** [comment]
I do like this general concept and think there is value in having support for the general concept. However, I think the title and semantics of this component are confusing. What we are talking about are radio or checkbox inputs that have more complex content inside of the labels (and perhaps hide the input itself). They are not cards, and we would not implement them as cards. 

It is important to make sure we are clear about the role and responsibility of the component. Being a radio/checkbox input also gives more guidance about what you can do with this component, since labels cannot contain interactive elements. 

I think we should get away from the notion of cards. Calling it a card seems to indicate that we want to follow the same card conventions, but that doesn't seem accurate or desirable. We are not planning to support clickable cards in the future because of what @chlane mentioned about Success Criterion 4.1.1.

From a design spec standpoint, we are missing specifics about how the designs are sized, spaced, and colored. Are we allowing free form content inside of the label container? Do we want to design any standard formats or leave it up to the implementation? We don't have a light and dark theme variation yet, and I don't think we should assume the basics of cards apply to this design spec. Overall its still pretty fuzzy to me what the implementation should be and what guidance we'd give to consumers about how to use this, so more detail and expanding the spec is needed to ensure a clear path forward.

**Comment by yuxin-ux** [comment]
That's a valid point on the radio vs. card. This is is actually a radio button with a rectangular container. So we should probably rename it. I will work with @mandyxs to get more design details in to the spec.

**Comment by chlane** [comment]
@yuxin-ux This limitation applies to radio buttons as well. Radio buttons are created with `input` elements and `input `elements cannot have anything inside of them.  See https://html.spec.whatwg.org/multipage/input.html#the-input-element. These have a content model of 'none' meaning they should not have anything inside of them.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
