### ISSUE TITLE
Add built-in case-insensitive sort to datagrid

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#491]
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior

The default string sort of a datagrid column is case-sensitive. In many cases, the desired sort is case-insensitive. It would be nice to have an option to use a case-insensitive search without having to write a custom comparator.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by reddolan** [comment]
@rongery we recommend case-insensitive as default, and we’ll work on fixing this for the existing default filter

cc: @youdz

**Comment by youdz** [comment]
Easy contribution for anyone who wants to pick this up, our `DatagridPropertyComparator` should become case-insensitive.

**Comment by victormejia** [comment]
I volunteer :)
