### ISSUE TITLE
One line toggle switch

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#4911]
## Summary

Could you please add a directive for the toggle switch component to make both the first level label and switch in the same line?

## Use case

Sometimes, we want to have a toggle switch with its prompt label in the same line.

![image](https://user-images.githubusercontent.com/3956876/90386902-cfe8d100-e0b7-11ea-8cee-51f3149c0012.png)

## Examples

https://stackblitz.com/edit/clarity-dark-theme-v2-7ksjz8

## Workarounds

We can set the flex-direction of the `clr-toggle-container` to `row` and set the line-height of the label to 1rem.

But it'd be better if we have clarity built-in directive to achieve it.

If you think this feature is acceptable, I'd like to contribute by implementing it.

Thanks.

**Comment by gnomeontherun** [comment]
@colinreedmiller Any thoughts about this? If we do this, it would be through Core.
