### ISSUE TITLE
Customize width of detail pane

### ISSUE THREAD

**Issue by Wallabeng** [vmware/clarity#4915]
## Summary

We have the requirement that the detail pane in datagrid should consume more than 2/3 of the grid.

- What is the change?
So we want to customize the width values for the datagrid part (.datagrid-inner-wrapper) and detail pane part (.datagrid-detail-pane).
Preferrably with  CSS3 variables (fixed or percentage should be possible).

- Why should it go in Clarity?
To have a future proof way of modifying the width of the detail pane.

- Does this change impact existing behaviors? If so how?
No it doesn't.

- If this change introduces a new behavior, is this behavior accessible?
No new behavior.

## Use case

Our first column is pretty short and the table has a lot of horizontal space. So the detail pane could use much more space for its content

## Examples

None

## Workarounds

Override the css class with desired percentages/fixed values. But we want to avoid that, as clarity internals could change.

**Comment by bdryanovski** [comment]
Hey @Wallabeng, can you provide more examples and use cases so we could get a better picture of what and how this could be useful for other users.

**Comment by gnomeontherun** [comment]
The width is determined by CSS, and its 1/3 first column and 2/3 detail pane. Right now, the solution is to override that with your own values.

**Comment by Wallabeng** [comment]
> Hey @Wallabeng, can you provide more examples and use cases so we could get a better picture of what and how this could be useful for other users.

We have this table below and the timestamp field could be a fixed width when opening the detail pane.
The data in the detail pane is some kind of changelog detail and could contain more data than shown in screenshot.

<img width="1627" alt="Bildschirmfoto 2020-08-19 um 07 17 00" src="https://user-images.githubusercontent.com/33118495/90595114-628a8c80-e1ec-11ea-8855-2339d6108199.png">
<img width="1627" alt="Bildschirmfoto 2020-08-19 um 07 18 37" src="https://user-images.githubusercontent.com/33118495/90595169-7cc46a80-e1ec-11ea-90e9-f89d82bc0da2.png">

**Comment by Jinnie** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
