### ISSUE TITLE
Global spinner css rule on wizard spinner is causing problems for spinners in wizard body

### ISSUE THREAD

**Issue by zombierobo** [vmware/clarity#4921]
https://github.com/vmware/clarity/blob/c77dee037dda21556dba30aa4eb742ea1832677b/packages/angular/projects/clr-angular/src/wizard/_wizard.clarity.scss#L432

This style rule is causing the problem. It is setting all the spinners inside the wizard body to be positioned at the center of the wizard body.

Reproduced at stackblitz https://clarity-light-theme-v2-wffvi9.stackblitz.io

**Comment by mathisscott** [comment]
You need to use the `spinner-inline` class on the spinner if you want it to be positioned in line with the content.
