### ISSUE TITLE
Wrong example in password docs (v1 - v4)

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#4927]
## Describe the bug

![Screenshot 2020-08-20 at 09 02 03](https://user-images.githubusercontent.com/3655915/90727726-05620a00-e2c4-11ea-9f83-771d995bfb00.png)

The live example doesn't show any error state (`.clr-error` is not used) and the helper text is rendered to the right of the input and not below it, as usually.

Also the text of the helper message doesn't align to the example code. The same applies for the above "Full password display" example.

## How to reproduce

Visit https://clarity.design/documentation/password and scroll to "CSS Password Component" -> "Error state" (The error is present in all versions of the docs)

## Expected behavior

Example code aligns with live examples and descriptions.

**Comment by bdryanovski** [comment]
@dorthrithil thank you for reporting this we will try to address this in the next few releases.
