### ISSUE TITLE
Combobox: Ability to disable browser autocomplete for input

### ISSUE THREAD

**Issue by Wallabeng** [vmware/clarity#4928]
## Describe the bug

In combobox I get the browser autocomplete/autofill in addition to the combobox autocomplete.

## How to reproduce

Go to https://clarity.design/documentation/combobox and have autofill/autocomplete active in your browser.
<img width="394" alt="Bildschirmfoto 2020-08-20 um 09 01 33" src="https://user-images.githubusercontent.com/33118495/90728037-83261580-e2c4-11ea-8f8a-1a4642b5b2d7.png">

After hitting ESC it shows the combobox autocomplete:
<img width="371" alt="Bildschirmfoto 2020-08-20 um 09 01 39" src="https://user-images.githubusercontent.com/33118495/90728082-90430480-e2c4-11ea-91f4-e9564b103434.png">

## Expected behavior

Browser autocomplete/autofill should be disabled for the combobox input or is there any usecase to leave it enabled?
see https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

Alternatively this attribute should be controllable via @Input parameter.

## Versions

**App**

- Angular: 10
- Clarity: 4

**Device:**

- Type: iMac
- OS: macOs
- Browser: chrome
- Version: 84.0.4147.125

**Comment by coryrylan** [comment]
I can't think of a valid reason the `autocomplete` should not be set to false. If there is a use case as stated above we could expose it as an input prop.

**Comment by Wallabeng** [comment]
Resolved by #5000
