### ISSUE TITLE
Label of progress bar become hidden when progress value is 100

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#4930]
## Describe the bug

Label of progress bar become hidden when progress value is 100.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-progress-bar-label?file=src/app/app.component.html

1.  Go to https://clarity-v3-progress-bar-label.stackblitz.io
2.  See error

## Expected behavior

Label of progress bar should stay visible independent of progress value.

## Versions

**App**

- Angular: 9.0.0
- Node: 10.13.0
- Clarity: 3.0.0

**Device:**

- Type: MacBook
- OS: MacOS
- Browser: Chrome
- Version: Latest

**Comment by bdryanovski** [comment]
Hey, @rimildeyjsr if you wish, we will be happy to get some help from you. 

Here you could find some documentation to get you started:

https://github.com/vmware/clarity/blob/v3/docs/CONTRIBUTING_DEVELOPMENT.md
https://github.com/vmware/clarity/blob/v3/docs/CODING_GUIDELINES_ANGULAR.md

**Comment by rimildeyjsr** [comment]
@bdryanovski Thank you! on it :)

**Comment by hippee-lee** [comment]
This issue is fixed as of the latest v5 package. The fix is to upgrade Clarity packages.
