### ISSUE TITLE
combobox: supply string matching directive for resultset entries

### ISSUE THREAD

**Issue by mattmutt** [vmware/clarity#4932]
## Summary
Feature request to combobox to have some formatting helper utilities in the form of a directive that can help highlight the parts of the string where the match was found.

Oftentimes the first few characters show a lot of data. While the sorting looks good, offering additional visual cues in the form of user-defined styling of the part of the text would help

- What is the change?
Offer some convenience utilities to help format the partial matches of a string based result set. 
- Why should it go in Clarity?
Better UX

- Does this change impact existing behaviors? If so how?
No it is additional

- If this change introduces a new behavior, is this behavior accessible?
if the colors alone are sufficient to convey the change, yes

## Use case

as user types in characters, the ordered result set could further have context regarding which part of each item was matched. Sometimes when doing substring matches alone with just a few characters, a large dataset will load up, possibly confusing the user.

Best to give contextual clues to reassure why those choices were positioned in the result set drop down

## Examples

![combobox-multi](https://user-images.githubusercontent.com/8688570/90831017-aa4a0a80-e2f7-11ea-9b11-9ceb09bc908b.png)

## Workarounds

users are capable of building their own, but this is going to result in lots of custom formatters when a generic one that adds a class ( possibly a Clarity controlled one ) around just the subset of characters matched.

**Comment by Jinnie** [comment]
Hello, @mattmutt 
We have this directive in the source code, but we didn't manage to achieve reliable sanitization, and left it out of the initial release for security considerations. Our goal is to release it post GA, after we reiterate over the options for sanitization.
You can check the directive here:
https://github.com/vmware/clarity/blob/master/packages/angular/projects/clr-angular/src/forms/combobox/filter-highlight.directive.ts

**Comment by Jinnie** [comment]
There is a workaround available for this issue, and we recommend using it for Clarity Angular. To help us clean up our backlog, we are going to close this with a functional workaround available and suggest you follow updates for Clarity Core for enhancements that can support your use case with Clarity Core components.
