### ISSUE TITLE
clrLoading directive is not working

### ISSUE THREAD

**Issue by smadurange** [vmware/clarity#4938]
## Describe the bug

I have a button in a modal footer with the `clrLoading` directive. I'm following the documentation at [loading button](https://clarity.design/documentation/buttons). However, I do not see a spinner in the button.

## How to reproduce

Tried to create a project at [stackblitz](https://stackblitz.com/edit/angular-ivy-hcprra?file=src%2Fapp%2Fapp.component.ts) with a simplified sample but I get the error `ngcc failed to run on @clr/angular@4.0.0.` So, providing my actual code here.

I have a modal:

```
<clr-modal [clrModalOpen]="isOpen | async" (clrModalOpenChange)="setDialogIsOpen($event)" (keydown.enter)="submit()">

  <h3 class="modal-title">My dialog</h3>
  <div class="modal-body">
    <form class="default-padding" clrForm clrLayout="vertical" [formGroup]="form">
      <clr-input-container>
        <label>Name</label>
        <input [(ngModel)]="name" clrInput formControlName="name" type="text"/>
        <clr-control-error *clrIfError="'required'">Name is required.</clr-control-error>
      </clr-input-container>
      <clr-date-container>
        <label>Date</label>
        <input [(ngModel)]="date" type="date" clrDate formControlName="date" [min]="minDate()">
    </clr-date-container>
      <span class="clr-error">
        <span class="clr-error clr-subtext" *ngIf="badRequest | async">{{badRequest | async}}</span>
      </span>
    </form>
  </div>

  <div class="modal-footer">
    <button (click)="cancel()" class="btn btn-outline" type="button">Cancel</button>
    <button [clrLoading]="loadingState" (click)="submit()" class="btn btn-success-outline">Submit</button>
  </div>

</clr-modal>
```

Code behind this modal is

```
import {Component, OnInit} from '@angular/core';
import {Observable} from 'rxjs';
import {FormControl, FormGroup, Validators} from '@angular/forms';
import {select, Store} from '@ngrx/store';
import {IAppState} from '../../../states/app-state';
import {map} from 'rxjs/operators';
import {selectBadRequest, selectMyDialogIsOpen} from '../../state/selectors/browser.selector';
import {setMyDialogIsOpen} from '../../state/actions/browser.action';
import {Model} from '../../models/model';
import { ClrLoadingState } from '@clr/angular';
import * as moment from 'moment';
import { setInProgress, myDialogWork} from '../../state/actions/my-dialog.action';

@Component({
  selector: 'app-my-dialog',
  templateUrl: './my-dialog.component.html',
  styleUrls: ['./my-dialog.component.scss']
})
export class MyDialogComponent implements OnInit {
  public loadingState: ClrLoadingState = ClrLoadingState.DEFAULT;
  public isOpen: Observable<boolean>;
  public name: string;
  public date: Date;
  public badRequest: Observable<string>;

  public form = new FormGroup({
    name: new FormControl('', Validators.required),
    date: new FormControl('', Validators.required),
  });

  constructor(private store: Store<IAppState>) {
  }

  ngOnInit(): void {
    this.isOpen = this.store.pipe(select(selectMyDialogIsOpen));
    this.badRequest = this.store.pipe(select(selectBadRequest), map(m => m?.error));
    this.isOpen.subscribe(x => {
      if (x) {
        this.form.reset();
      }
    });
  }

  public submit(){
    this.loadingState = ClrLoadingState.LOADING;
    this.form.markAllAsTouched();
    if (this.form.valid) {
      let m: Model = {
        name: this.name,
        date: new Date(new Date(this.date).toISOString())
      };

      this.store.dispatch(setInProgress({value: true}));
      this.store.dispatch(myDialogWork({model: m}));
    }
  }

  public cancel(){
    this.setDialogIsOpen(false);
    this.form.reset();
    this.badRequest = null;
  }

  public minDate(): string {
    let min = new Date();
    min.setDate(min.getDate() + 1);
    return moment(min).format('YYYY-MM-DD');
  }

  setDialogIsOpen($event: boolean) {
    this.store.dispatch(setMyDialogIsOpen({value: $event}));
  }
}
```

This modal is opened from another component using a directive like 

`<app-my-dialog></app-my-dialog>`

The modal opens correctly and the buttons work and they do what they are supposed to do. However, the submit button does not show a spinner at all.

## Expected behavior

Spinner must be shown in the submit button when the submit button is called.

## Versions

**App**

- Angular: 9.0.7
- Node: 12.18.3
- Clarity: clr/core 3.1.4, clr/angular 4.0.0

**Device:**

- Type: ThinkPad
- OS: Windows
- Browser: Vivaldi, Firefox, Chrome

**Comment by Jinnie** [comment]
The idea of a stackblitz is to show isolated occurrence of the problem.
Your attempted reproduction has a multitude of problems:
- Missing ReactiveFormsModule import in your module
- Adjacent use of Template driven and Reactive forms on the same component
- And overall lot of unrelated code that does not help with the problem isolation
- Reported use of Clarity 4 with Angular 9, while Clarity 4 is designed to work with Angular 10. (Though the failing stackblitz does not feature this)

I created a new stackblitz and removed all unrelated code. And the loading animation seems to display fine:
https://stackblitz.com/edit/issue-4938-2?file=src%2Fapp%2Fapp.component.html
Please try to make a reproduction that's based on my clean example.
My advise is also to keep a copy of the last working version you have, because I've also had some issues with Ivy on the stackblitz that lead to the same error you noticed. And reverting your last change does not always fix it.

**Comment by smadurange** [comment]
When I shed all the reactive code, it seems to be working. But once I try this in my actual component it's not working. I've decided to go with `ng-disabled` directive for now as I can't reproduce it outside my code. So, feel free to close this.

**Comment by Jinnie** [comment]
Thanks for the feedback.
