### ISSUE TITLE
Combobox - placeholder not visible

### ISSUE THREAD

**Issue by lohiaad** [vmware/clarity#4943]
## Describe the bug

placeholder in combobox component not visible

## How to reproduce

can be seen in clarity documentation 

## Expected behavior

placeholder should be visible

## Versions

**App**

- Angular: [9]
- Node: [10.16]
- Clarity: [4.0.0]

**Comment by coryrylan** [comment]
It looks like we are not passing `placeholder` attr down to the native element.
