### ISSUE TITLE
Datagrid. Access filtered data

### ISSUE THREAD

**Issue by real-artswan** [vmware/clarity#4944]
Is there a way to access filtered data if I don't use server driven filtering (clrDgRefresh)?
I want to show summary in the footer like number of items and summ of some columns.
I found `items.displayed` inside `ClrDatagrid` instance, is it the right way to get it?

**Comment by Jinnie** [comment]
@real-artswan 
Yes, getting a reference to the datagrid and then using `items.displayed` is the way to go. We're not exposing this information on the Template API level, so the Typescript API should be used.
