### ISSUE TITLE
Having a Pivot/Tabbed Browsing Component

### ISSUE THREAD

**Issue by leonletto** [vmware/clarity#4947]
## Summary

Would love to see a Tabbed Browsing / FlexBox / Pivot component which is easy to implement and consistent

- Add a component to allow easy implementation of tabbed interface
- It is in common use across all we design frameworks for menus
- No. 
- I am not sure but I suspect so

## Use case

I currently use this in my app and I find it a very convenient alternative to implementing Routing for simple apps.

## Examples

https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot
https://a11y.nicolas-hoffmann.net/tabs/#robust_accessible

## Workarounds

Building it manually using CSS or using another component.  This would make my tabbed layout view different from others at VMware.

<img width="351" alt="Screen Shot 2020-08-25 at 11 23 20 AM" src="https://user-images.githubusercontent.com/2295131/91212722-77bc5b00-e6c5-11ea-8597-e618ab55578b.png">

**Comment by hippee-lee** [comment]
For tabbed browsing, is there a reason not to use the existing tabs component? 
For a pivot component, is there a reason not to use the existing Vertical Nav? 

Are the use cases standard application routing or is there more to it for your app?

**Comment by leonletto** [comment]
Because I can't read meh!  Thanks for responding.

**Comment by hippee-lee** [comment]
Thanks for the follow-up. Sorry about the confusion, we are working on bringing the docs into alignment and hope to make it more clear where to find code for the various tech platforms.
