### ISSUE TITLE
Freeze Column header of datagrid with vertical scroll is not working after scrolling down

### ISSUE THREAD

**Issue by namitabandal** [vmware/clarity#4948]
Fixed column headers with scrolling records is not working properly.
I have given a fixed height to data grid so for initial few records it is working fine but after scrolling down few records, column headers are not fixed.
This is because **position: sticky** will not work if its parents are having **overflow:auto**. and in the code we have parent div with overflow :auto style. 
So this feature is breaking.

**Comment by bdryanovski** [comment]
Hey @namitabandal thanks for reporting this issue, we already have an open issue for that #4889 

So I'm closing this one in favor of #4889
