### ISSUE TITLE
Combobox - Need templates for "Loading" and "No Results" options

### ISSUE THREAD

**Issue by lohiaad** [vmware/clarity#4971]
## Summary

Currently templates for "loading" or "no results" are fixed. need a way to customise both templates

## Use case

wanted to show different message with icons if async search is in progress or no result found.

## Examples

https://ng-select.github.io/ng-select#/templates

**Comment by Jinnie** [comment]
The texts can be changed through the Internationalization API:
https://clarity.design/documentation/internationalization

@lohiaad Will this be enough, or your use case requires more customization than changing the texts?

**Comment by lohiaad** [comment]
@Jinnie i have 2 requirements or suggestions 
1. i want to change loading icons or add icon with no result text. 
2. Initially i want to show "enter minimum 3 characters for search" and then show loading template when actual api is getting called.

**Comment by dorthrithil** [comment]
When someone types a search query and then deletes it again the Combobox announces `Searching for matches for ""`. By adding templates we could work around this by showing the user a more useful hint.
Is there a workaround for this currently? Just closing the Dropdown when the input changes to an empty string would help until templates are available.

**Comment by Jinnie** [comment]
Thank you for your suggestions!
They are "under consideration", as labelled by Scott, and this means that they may appear in the Clarity Core version of the combobox (as framework neutral web-component). With the new lifecycle of the product we are not planning to make breaking changes on any of the Angular components.

**Comment by dave105010** [comment]
Hi, I appreciate the work that you guys do! 
We are not using Angular and we would love to completely rely on Clarity for Combobox and not use selectize.js or any other dependencies for that.

I was wondering if there are any updates about making combobox(multiple selectable items as a select box that looks like tags) available for the Clarity Core version.

**Comment by mathisscott** [comment]
> Hi, I appreciate the work that you guys do!
> We are not using Angular and we would love to completely rely on Clarity for Combobox and not use selectize.js or any other dependencies for that.
> 
> I was wondering if there are any updates about making combobox(multiple selectable items as a select box that looks like tags) available for the Clarity Core version.

Thanks @dave105010 

We do plan to have a Clarity Core combobox. Right now, we are working hard on building a basic dropdown (a.k.a. positioned overlay). Once that is merged in, components like the datepicker and combobox become a lot easier to build.

**Comment by juanmendes** [comment]
Until this is built, any HTML that is passed into the `clr-options` will be transcluded into the drop down. The VCD team is using it to display a loading, error, and too-many-results indicators. 

See https://github.com/vmware/vmware-cloud-director-ui-components/blob/master/projects/components/src/sharing-modal/tabs/sharing-modal-tab.component.html#L2-L62

![clr-combobox](https://user-images.githubusercontent.com/549331/137136651-1a100954-5bff-4a40-874e-a1a54c1f032e.gif)


https://user-images.githubusercontent.com/549331/137136651-1a100954-5bff-4a40-874e-a1a54c1f032e.gif
