### ISSUE TITLE
ClrTimeline 4 Angular not working with clrState value as string as depicted in example

### ISSUE THREAD

**Issue by kartiki-sahu** [vmware/clarity#4982]
After integrating the clarity timeline component with my **angular application** I got build issue 

 Error occurs in the template of component.
    src/application/app/shared/components/analysis-bread-crum/analysis-bread-crum.component.html:11:24 - error TS2322: Type '"not-started"' is not
assignable to type 'ClrTimelineStepState'.

Have used the clarity timeline similar as an example
`<clr-timeline>
  <clr-timeline-step clrState="current">
    <clr-timeline-step-title>A</clr-timeline-step-title>
  </clr-timeline-step>
<clr-timeline-step clrState="not-started">
    <clr-timeline-step-title>B</clr-timeline-step-title>
  </clr-timeline-step>
</clr-timeline>`

**I was able to resolve this issue by adding local ENUMS instead of string for clrState**
I added this in my local and used it directly to give clrState value
`export enum ClrTimelineStepState {
    NOT_STARTED = 'not-started',
    CURRENT = 'current',
    PROCESSING = 'processing',
    SUCCESS = 'success',
    ERROR = 'error'
  }`

`<clr-timeline class="clr-offset-md-2 clr-offset-sm-0 clr-col-md-10 clr-col-sm-12">
        <clr-timeline-step clrState="ClrTimelineStepState.CURRENT">
            <clr-timeline-step-title>B</clr-timeline-step-title>
        </clr-timeline-step>
        <clr-timeline-step clrState="ClrTimelineStepState.CURRENT">
            <clr-timeline-step-title>C</clr-timeline-step-title>
        </clr-timeline-step>
        <clr-timeline-step clrState="ClrTimelineStepState.NOT_STARTED">
            <clr-timeline-step-title>T</clr-timeline-step-title>
        </clr-timeline-step>
        <clr-timeline-step clrState="ClrTimelineStepState.NOT_STARTED">
            <clr-timeline-step-title>R</clr-timeline-step-title>
        </clr-timeline-step>
    </clr-timeline>`

Ideally, the ENUM ClrTimelineStepState inside ClrTimeline should be allowed to import in your custom web-components and use it directly,  or string should be allowed as clrState

**Comment by bdryanovski** [comment]
Hello there, thanks for reporting this issue, but without a reproduction, we are unable to triage issues. 

Please use https://stackblitz.com/@clr-team for a starter kit.

**Comment by alsahlawi** [comment]
Hello there,

This might be old, but did you sort this out? I have installed the package as described in the docs and copied the example. All icons all not showing, except the progress circle.

Thank you.

**Comment by gnomeontherun** [comment]
Please provide a working reproduction as described by @bdryanovski above so we can help, it sounds like the icons are not being loaded in the application, see https://clarity.design/icons/get-started. Closing as stale without a reproduction.
