### ISSUE TITLE
Combobox - submit event gets fired when selecting option using enter key

### ISSUE THREAD

**Issue by lohiaad** [vmware/clarity#4983]
## Describe the bug

Form submit event getting fired when pressing "ENTER" key for option selection

## How to reproduce

https://angular-10-clarity-4.stackblitz.io

1. type state name in combobox
2. press enter.

## Expected behavior

form submit event should not be called.

## Versions

**App**

- Angular: [e.g. 10]
- Node: [e.g. 10.16]
- Clarity: [e.g. 4.0.0]

**Comment by Jinnie** [comment]
I can confirm this will happen. With the latest implementation (w/ aria-activedescendant) the focus is always on the input field. We should intercept the enter button and check if we have have the dialog still open.
