### ISSUE TITLE
Adding one icon adds all shapes from a set

### ISSUE THREAD

**Issue by wendellestradairely** [vmware/clarity#4991]
## Describe the bug

I'm only adding one or few hand-picked icons from a set but it includes all the icons in the set. As per #2599, this was already fixed but it looks like it's not working in version 4.0+.

Source-map Explorer shows that it reaches almost 700kb.

![image](https://user-images.githubusercontent.com/50942719/91866029-9f528b00-eca4-11ea-9f2e-0244ec05d2da.png)

## How to reproduce

```
import "@clr/icons";
import { ClrShapeThumbsUp, ClrShapeThumbsDown } from "@clr/icons/shapes/social-shapes";
import {
	ClrShapeUndo,
	ClrShapeNote,
	ClrShapeHistory,
	ClrShapePinboard,
	ClrShapeFile,
	ClrShapeCircle,
	ClrShapePlus,
	ClrShapePencil,
	ClrShapeTrash,
	ClrShapeRefresh,
	ClrShapeResize
} from "@clr/icons/shapes/essential-shapes";
import {
	ClrShapeInstall,
	ClrShapeExport,
	ClrShapeImport,
	ClrShapeCode
} from "@clr/icons/shapes/technology-shapes";
import { ClrShapeCalculator } from "@clr/icons/shapes/commerce-shapes";
import { ClrShapeAirplane, ClrShapeOnHoliday } from "@clr/icons/shapes/travel-shapes";
import { ClrShapeNumberList } from "@clr/icons/shapes/text-edit-shapes";
import { ClrShapePlay } from "@clr/icons/shapes/media-shapes";
import { ClarityIcons } from "@clr/icons";

export class AppModule {
	constructor() {
		ClarityIcons.add({
			resize: ClrShapeResize,
			refresh: ClrShapeRefresh,
			trash: ClrShapeTrash,
			"thumbs-up": ClrShapeThumbsUp,
			"thumbs-down": ClrShapeThumbsDown,
			undo: ClrShapeUndo,
			file: ClrShapeFile,
			pinboard: ClrShapePinboard,
			history: ClrShapeHistory,
			note: ClrShapeNote,
			install: ClrShapeInstall,
			calculator: ClrShapeCalculator,
			circle: ClrShapeCircle,
			plus: ClrShapePlus,
			pencil: ClrShapePencil,
			code: ClrShapeCode,
			import: ClrShapeImport,
			export: ClrShapeExport,
			number: ClrShapeNumberList,
			airplane: ClrShapeAirplane,
			"on-holiday": ClrShapeOnHoliday,
			play: ClrShapePlay
		});
      }
}
```

`ng build --prod`

## Expected behavior

It should only include the specified icons.

## Versions

**App**

- Angular: 10
- Node: [e.g. 8.10.0]
- Clarity: 4.0
**Device:**

- Type: Dell XPS 13
- OS: Windows 10

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This is a known issue, but the resolution is to update to use the new Core icons. This allows for proper tree shaking of icons. We will be making this the default in v5, but you can use them now to avoid this problem.

https://clarity.design/storybook/core/?path=/story/components-icon-getting-started--page

If you are loading icons used inside of Clarity Angular components, you will need to still load the current @clr/icons package and the default set of icons, but any others can be used individually.

**Comment by wendellestradairely** [comment]
@gnomeontherun Do you have a sample code for Angular? I tried the sample code in https://clarity.design/storybook/core/?path=/story/components-icon-getting-started--page but it didn't worked.

npm i @clr/core

```bash
'cds-icon' is not a known element:
    1. If 'cds-icon' is an Angular component, then verify that it is part of this module.
    2. If 'cds-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

**Comment by gnomeontherun** [comment]
@wendellestradairely You'll have to add `CUSTOM_ELEMENTS_SCHEMA` to Angular, see this section for details https://clarity.design/storybook/core/?path=/story/documentation-angular--page
