### ISSUE TITLE
Too long underline in the Date Picker

### ISSUE THREAD

**Issue by d-atanasov** [vmware/clarity#5009]
## Describe the bug

When the [Date Picker](https://clarity.design/documentation/datepicker) component is focused its underline becomes too long.

## How to reproduce

1.  Click in the Date Picker input
2.  The input underline becomes too long

## Expected behavior

The underline should be as long as the input itself.

## Versions

**App**

- Angular: 10
- Clarity: 4

**Device:**

- OS: Windows
- Browser: chrome, safari, firefox

## Additional Notes

Currently there is a problem with reproducing the issue in Stackblitz, but I use just a simple Date Picker:
```
<form clrForm>
  <clr-date-container>
    <label for="demo">Test Date</label>
    <input type="date" clrDate name="demo" id="demo" [(ngModel)]="date">
  </clr-date-container>
</form>
```

And here is a video that shows the issue:
![long_undeline](https://user-images.githubusercontent.com/28918357/92116338-60cfe400-edfc-11ea-95ca-feb13b5cbad6.gif)

**Comment by Jinnie** [comment]
Similar issue is observed with the datalist. 
The animation is on a container, which takes 100% of the container, while the non-focused underline is on the input field only
