### ISSUE TITLE
Sidenav content shifts left in IE11 when anchor tag receives focus via tab

### ISSUE THREAD

**Issue by StephenAlbrecht** [vmware/clarity#5014]
## Describe the bug

In Internet Explorer 11, using the tab key to navigate through the nav-links in a sidenav causes the nav-links to shift left when they are focused, as if their left margin is cut off.

![ie-bug-01](https://user-images.githubusercontent.com/25337035/92299145-c962b200-ef1d-11ea-8972-d0f72c62b39f.png)
![ie-bug-02](https://user-images.githubusercontent.com/25337035/92299147-c962b200-ef1d-11ea-94b7-00f2b54422cf.png)
![ie-bug-03](https://user-images.githubusercontent.com/25337035/92299193-36764780-ef1e-11ea-8677-49442a9586e1.png)
![ie-bug-04](https://user-images.githubusercontent.com/25337035/92299194-370ede00-ef1e-11ea-9cc5-c09ea9a4a6fa.png)

## How to reproduce

Because this bug only occurs in IE and StackBlitz doesn't work in IE, I've created a small project [here](https://github.com/StephenAlbrecht/clarity-sidenav-ie).

1.  After cloning the project and running "npm install", start an IE compatible dev server with "ng s -c=es5"
2.  Navigate to "http://localhost:4200" in Internet Explorer 11
3.  Use the tab key to focus one of the nav-links in the sidenav

## Expected behavior

The content should not shift upon receiving focus.

## Versions

**App**

- Angular: 10.1.0
- Node: 12.17.0
- Clarity: 4.0.1

**Device:**

- Type: Desktop
- OS: Windows 10
- Browser: Internet Explorer 11.1016.18362.0

## Additional notes

I noticed that the presence of any margin on nav-groups, nav-lists, or nav-links will cause the shift. I was able to work around the issue by using wrappers and applying padding instead of margin, but I had to rewrite much of the sidenav css, which is obviously not ideal.

While this is probably not an issue with Clarity itself but rather IE11, the default sidenav CSS causes usability issues for IE11 users. Since Clarity is supposed to be IE11 compatible, this issue should be addressed.

**Comment by hippee-lee** [comment]
I moved this to backlog - a fix will be dependent on getting the dev app rendering in IE11 again.

**Comment by gnomeontherun** [comment]
We have recently dropped IE11 support as of the end of 2020 for any version of Clarity. In an effort to better manage our backlog, we are closing this issue. If someone has a need to address this bug we can welcome a pull request.
