### ISSUE TITLE
Clarity Spinner Appears with Scrollbar in Modal

### ISSUE THREAD

**Issue by AshleyVDW** [vmware/clarity#5016]
I currently have a website using clarity and angular 8,

when adding the clarity spinner to a clarity modal it gives a scroll bar on the side of the modal, which appears and disappears from time to time while loading.

(this sometimes happens when hovering with your mouse over the modal and other times it appears by itself)

I'm not entirely sure if this has something to do with the screen size or browser because it doesn't have any effect when changing the size of the modal.

see link to stackblitz : [https://clarity-light-theme-v2-oftfd8.stackblitz.io](https://clarity-light-theme-v2-oftfd8.stackblitz.io)
image:  ![scroll](https://user-images.githubusercontent.com/70890019/92377497-86166800-f104-11ea-88b8-e924c0378cac.PNG)

**Comment by gnomeontherun** [comment]
This is related to the rotating object for the spinner. You will need to give the spinner container some extra margin to allow it to rotate without changing the height (which is triggering the scrollbar).
