### ISSUE TITLE
clrRange input fires an event twice when subscribed from a FormControl.

### ISSUE THREAD

**Issue by nkolchakov** [vmware/clarity#5017]
## Describe the bug

When subscribed to clrRange fromControl's `valueChanges` it fires an event twice.

## How to reproduce

https://stackblitz.com/edit/clarity-v3-dark-theme-timeline-demo-fbmge8?file=src/app/app.component.ts

1.  Go to Console
2. Try to fill the clrRange and clrText inputs. (the range input prints the text twice)

## Expected behavior

On valueChanges the clrRange input event should fire once.

## Versions

**App**

- Angular: ^9.1.9
- Clarity: 3+

**Device:**
- Browser Chrome, Firefox, Opera

**Comment by bbogdanov** [comment]
Hi @nkolchakov! 

Forms are part of Angular and we are not adding anything on top of angular forms.

You can use pipes to handle this situation - `pipe(distinctUntilChanged())`

` this.formGroup.get("clrRange").valueChanges.pipe(distinctUntilChanged()).subscribe((newValue: any) => {
     console.log('trigger clrRange - ', newValue);
  });`

Hope that helps!

**Comment by gnomeontherun** [comment]
To be more clear, this happens to a range input regardless if you use Clarity or not. The change event fires on changing of the value, and when you release the mouse.
