### ISSUE TITLE
Some Icons are showing up not correctly in stackblitz

### ISSUE THREAD

**Issue by boeckMt** [vmware/clarity#5018]
## Describe the bug

Some Icons are displayed with the `exclamation-circle` shape and not with there 'normal' shape in stackblitz.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-dark-theme-icon-missing?file=src%2Fapp%2Fapp.component.html

## Expected behavior

The Icons should be displayed like on the Clarity Homepage.

## Versions

**App**

- Angular: [10]
- Clarity: [4.0.1]

**Device:**
- Browser [chrome, Firefox, Edge]

## Additional notes

I only recognized this on stackblitz, not in a local angular cli project.

**Comment by bbogdanov** [comment]
Hi @boeckMt! Thank you sharing this.

https://stackblitz.com/edit/clarity-v4-dark-theme-icon-missing-nnebqe?file=src%2Fmain.ts

Take a look at lines 2-3.

More info about the solution https://clarity.design/icons/get-started at `Load Clarity Icons API and icon sets in Typescript:` 

Happy coding!

**Comment by boeckMt** [comment]
@bbogdanov thanks for the hint!

I had this Issue in another stackblitz template which I copied from a project created by the angular-cli.
So if I understand the doku correctly one could either load all Icons by script (like configured by `ng add @clr/angular`) or like you described, to load the individually sets.

So it should also work without the typescript imports but with a angular config file like this?

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
...
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
           ...
            "styles": [
              "node_modules/@clr/icons/clr-icons.min.css",
              "node_modules/@clr/ui/clr-ui-dark.min.css",
              "src/styles.css"
            ],
            "scripts": [
             "node_modules/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js",
             "node_modules/@webcomponents/webcomponentsjs/webcomponents-bundle.js",
             "node_modules/@clr/icons/clr-icons.min.js"
            ]
          }
     ...
}
```
But then i don't get any icons: https://stackblitz.com/edit/clarity-v4-dark-theme-icon-load-by-script?file=angular.json

**Comment by boeckMt** [comment]
Found this Issue on stackblitz: https://github.com/stackblitz/core/issues/700

**Comment by gnomeontherun** [comment]
The Stackblitz demo is only loading the core set of icons, so if you use other icon sets you'll have to explicitly declare them in TypeScript. The configuration option you showed loads all icons by default.

You'll add the sets individually like `import '@clr/icons/shapes/travel-shapes';`
