### ISSUE TITLE
Customize color palette?

### ISSUE THREAD

**Issue by VinnyVicious** [vmware/clarity#502]
Is it possible to customize the color palettes in Clarity when installing it on top of an Angular app? If so, how?

**Comment by Shijir** [comment]
@VinnyVicious you can customize the color palettes by overriding our default variables in `~/node-modules/clarity-ui/src/utils/overwrites.clarity.scss`, compile the `main.scss` and use the `compiled-main.css` in your application.

**Comment by Shijir** [comment]
Related to #506
