### ISSUE TITLE
Name was not identical in icon shape 'ellipsis'

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#503]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The icon shape 'ellipsis' can not be found as its name.
### Actual behavior

 It used a name as 'ellipses', not identical as the document described online. Please confirm it.
### Environment details

* **Angular version:** 2.4.1

* **Clarity version:** 0.8.0

* **OS and version:** OS X

* **Browser:** [all]

**Comment by Shijir** [comment]
@wknet123 Yes, we have deprecated `ellipses-*` shapes and renamed them as `ellipsis-*`. However, those `ellipses-*` shapes still exist in the sets and we will remove them in 0.9.0.

**Comment by wknet123** [comment]
Thanks, I got it.
