### ISSUE TITLE
How to make component right or left alignment in datagrid cell?

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#504]
I mean like ellipses action button that right alignment at a datagrid cell.
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Environment details

* **Angular version:** 2.4.1

* **Clarity version:** 0.8.0

* **OS and version:** OS X

* **Browser:** [all ]

**Comment by Jinnie** [comment]
Check documentation for "custom cell renderer".
Something like this should work, if I got your question right:

<clr-dg-cell><span style="float: right;">Your right aligned content here...</span></clr-dg-cell>

Best regards

**Comment by wknet123** [comment]
BTW, how can I apply selection in datagrid cells, I can't do that following with the document.

**Comment by Jinnie** [comment]
What are you trying to achieve? Give an example, please.
You can select rows in the datagrid, as they represent objects. Anything selected goes to the array referenced by the [(clrDgSelected)] binding. If you want to pre-select some rows, just put their objects in the referenced array.
If you want to be doing something on a cell level, it's up to you to implement it, I think :)

**Comment by wknet123** [comment]
I want to achieve it like the sample "Selection" section in datagrid document, but it doesn't make change to me as I composed tags like this example.

**Comment by Jinnie** [comment]
Post a code example, please.

**Comment by wknet123** [comment]
`<clr-datagrid [(clrDgSelected)]="selected">`
    `<clr-dg-action-bar>`
       ` <div class="btn-group">`
           ` <button type="button" class="btn btn-sm btn-secondary" (click)="onAdd()"><clr-icon shape="plus"></clr-icon> Add to group</button>`
            `<button type="button" class="btn btn-sm btn-secondary" (click)="onDelete()" ><clr-icon shape="close"></clr-icon> Delete</button>`
            `<button type="button" class="btn btn-sm btn-secondary" (click)="onEdit()" *ngIf="selected.length == 1"><clr-icon shape="pencil"></clr-icon> Edit</button>`
       ` </div>`
   `</clr-dg-action-bar>`
   `<-- ... -->`
   `<clr-dg-row *clrDgItems="let user of users" [clrDgItem]="user">`
        <-- ... -->
    `</clr-dg-row>`
  ` <-- ... -->`
`</clr-datagrid>`

**Comment by wknet123** [comment]
May be simple as this.
`<clr-datagrid [(clrDgSelected)]="selected">`
    `<-- ... -->`
    `<clr-dg-row *clrDgItems="let user of users" [clrDgItem]="user">`
        `<-- ... -->`
    `</clr-dg-row>`
   `<-- ... -->`
`</clr-datagrid>`

Selected users: <span *ngFor="let user of selected">{{user.name}}</span>

**Comment by Jinnie** [comment]
You've put the <-- ... --> items only for the sample, right? They represent placeholders for the actual content, like headers, row data, etc. Sorry for this question, but we need to be clear on that :)

Otherwise, you'll need a selected field or property on your component .ts file.
I'd just initialize it as:
`selected = [];`
inside the class, above the controller.

Sorry if this all seems obvious, but I don't see any issues with html markup, so I am trying to get the initial details clear.

Best regards

**Comment by wknet123** [comment]
I think I missed setting `selected = []`, I'll try it.

**Comment by wknet123** [comment]
Another issue is how to add 'Single Row Action' feature to this datagrid. I saw it was mentioned in the document, but I couldn't achieve it following the steps.

**Comment by youdz** [comment]
The documentation on Single Row Actions is pretty clear, it tells you to simply add a `<clr-dg-action-overflow>` in your row containing the actions. I don't understand what you mean by "following the steps" and how it could not work. Just search for "Single row action" on https://vmware.github.io/clarity/documentation/datagrid.

Just to be safe, here is a copy-paste of the example from that documentation:
```html
<clr-dg-row *clrDgItems="let user of users" [clrDgItem]="user">
    <clr-dg-action-overflow>
        <button class="action-item" (click)="onEdit(user)">Edit</button>
        <button class="action-item" (click)="onDelete(user)">Delete</button>
    </clr-dg-action-overflow>
    <-- ... -->
</clr-dg-row>
```

**Comment by wknet123** [comment]
But here is what I see,
![image](https://cloud.githubusercontent.com/assets/5027302/23074441/b1b7483e-f573-11e6-81eb-cde65bca0315.png)

`<clr-datagrid [(clrDgSelected)]="selected">`
  `<clr-dg-column>...</clr-dg-column>`
  `<--...-->`
  `<clr-dg-row *clrDgItems="let p of projects" [clrDgItem]="p" [(clrDgSelected)]="p.selected">`
   `<clr-dg-action-overflow>`
      `<button class="action-item" (click)="onEdit(p)">Edit</button>`
      `<button class="action-item" (click)="onDelete(p)">Delete</button>`
    `</clr-dg-action-overflow>`
    `<clr-dg-cell><a [routerLink]="['/harbor', 'projects', p.id, 'repository']" >{{p.name}}</a></clr-dg-cell>`
    `<clr-dg-cell>{{p.public == 1 ? 'Public': 'Private'}}</clr-dg-cell>`
    `<-- ... -->`
  `</clr-dg-row>`
  `<clr-dg-footer>{{ (projects ? projects.length : 0) }} item(s)</clr-dg-footer>`
`</clr-datagrid>`

**Comment by youdz** [comment]
Which version of Clarity are you using? This really looks like the `clr-dg-action-overflow` doesn't exist and is used raw. The fact that you added `schemas: [ CUSTOM_ELEMENTS_SCHEMA ]` hides the error, so if you added it considering it was a fix, you should really really remove it. It's only going to lead to more silent errors.

Single row actions were added in Clarity 0.8.7.

**Comment by wknet123** [comment]
So quickly the version updated, I've just pulled the project seed 2 days ago. But I think the document doesn't mention the version against to component clearly.

**Comment by jeeyun** [comment]
@wknet123 that's a valuable feedback. We are working on improving our documentation so that it's clear from which version a certain feature is available. It seems that our version/documentation updated since the time you pulled the seed. As for the issue that you were having, please feel free to close this issue if it was resolved by trying out the latest version. If not, let us know and we'll investigate. Thank you!
