### ISSUE TITLE
date Picker under the signpost  ,when i open the datepicker inside the signpost and once selected date signpost also closing issue

### ISSUE THREAD

**Issue by muruganG** [vmware/clarity#5040]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._
In the signpost under add the datepicker  input box ,when i try to selected the date  ,once selected the date immediately closing the signpost also ,issue seen on latest version clarity 4.0 issue.

_If this is an accessibility related report, please use the correct template at https://github.com/vmware/clarity/issues/new?template=accessibility-report.md_

## How to reproduce
 Inside the signpost add the date picker , and open the signpost ,once open the signpost  in the input datepicker select select the date ,once you select the date immediately it close the signpost also .
_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior
inside the signpost once selected the date using datepicker ,it will not close the signpost  
_A clear and concise description of what you expected to happen._

## Versions

**App**

- Angular: [e.g. 10]
- Node: [e.g. 12.0.0]
- Clarity: [e.g. 4.0.1]

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
Please, follow our issue submission template and provide all requested information, especially a Stackblitz representation of the problem.
Also, based on the signpost description from our website
> The signpost is a convenient, lightweight way to show contextual help of information without taking the user out of the current context.
It is not intended to have heavy actionable elements inside it.

**Comment by muruganG** [comment]
in clarity 2.0 and 3.0 have the support for signpost under date picker able to use ,why 4.0 onwards the restriction?, we already release the signpost under  date picker feature  on customer. Is there any work  around. for the solution?.   

![image](https://user-images.githubusercontent.com/10629787/93319496-8d88f000-f82d-11ea-83d0-559cd17e43cb.png)

**Comment by Jinnie** [comment]
If you would like us to investigate more into this, file a new issue, following the template, with a stackblitz reproduction, please.
Not sure if we will decide to support it, but at least we can research exactly what happens and offer workaround if one exists.
