### ISSUE TITLE
Cannot open clarity documentation page

### ISSUE THREAD

**Issue by geekz-reno** [vmware/clarity#5042]
## Describe the bug

Hi, just notice i can't open clarity [documentation page](https://clarity.design/documentation) _(if can, page load are very long)_ and when open i cannot click all link on sidenav.

**Comment by bdryanovski** [comment]
There is some issue with the internal redirection. As a workaround, you could navigate from the [homepage](https://clarity.design/)

**Comment by bdryanovski** [comment]
Also, it could be an issue with Netlify we gonna investigate

**Comment by Jinnie** [comment]
The Netlify service itself is inaccessible right now.

**Comment by bdryanovski** [comment]
Everything is working now .. closing
