### ISSUE TITLE
date Picker under the signpost ,when i open the datepicker inside the signpost and once selected date signpost

### ISSUE THREAD

**Issue by muruganG** [vmware/clarity#5059]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._
   In the signpost under add the datepicker input box ,when i try to selected the date ,once selected the date immediately closing the signpost also ,issue seen on latest version clarity 4.0 issue.

_If this is an accessibility related report, please use the correct template at https://github.com/vmware/clarity/issues/new?template=accessibility-report.md_

## How to reproduce
   Inside the signpost add the date picker , and open the signpost ,once open the signpost in the input datepicker select select the date ,once you select the date immediately it close the signpost also .

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._
   https://clarity-v4-light-theme-z34mq1.stackblitz.io/

1.  Add the signpost inside date picker
2.  Click on  date picker and select the date 
3.  once you selected the date 
4.  its closes the date picker and signpost also closed

## Expected behavior
inside the signpost once selected the date using datepicker ,it will not close the signpost

_A clear and concise description of what you expected to happen._

## Versions

**App**

- Angular: [e.g. 10]
- Node: [e.g. 12.10.0]
- Clarity: [e.g. 4.0.1]

**Device:**
All browsers able to produce the issue 
- Type: [e.g. MacBook]

## Additional notes
 Its working fine on clarity 1,2,3 .If you not supporting from clarity 4.0 version onwards  ,required the workaround to solve the problem.

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
Hi there 👋🏼. 

We don't recommend putting form controls in a signpost.
> The signpost is a convenient, lightweight way to show contextual help of information without taking the user out of the current context.

Before I investigate if there is a workaround, can you elaborate on the use case driving this design?

**Comment by Jinnie** [comment]
Related: #5040 
Matt, I closed it for lack of repro and empty issue template, but you can still find some screenshots that were added there.

**Comment by muruganG** [comment]
I already shared snapshot information ,is there any workaround for signpost inside datepicker selection event  approach.

**Comment by Jinnie** [comment]
The stackblitz is broken. Even if I remove the extra `div`, it is still not in a state that's easy to investigate, as it has a lot of unrelated code. Please try to isolate the core issue better in future.
Still, I managed to make it work and reproduce it. It is a duplication of another issue:
https://github.com/vmware/clarity/issues/4610
Though it's about datagrid filters, the underlying issue is the same.
There is a workaround posted in the link above, please use this workaround and update the above issue if needed.
Closing this as duplicate.
