### ISSUE TITLE
Remove overwrite.scss from main.scss

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#506]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Users should be able to build our main.scss with their own overwrites. For example:

`main.user.scss`:
```
@import "overwrite.clarity";
@import "path/to/node_modules/clarity-ui/main";
```

### Actual behavior

Right now as we've included overwrites.scss in our main.scss, users' overwrites of our default variables are being nullified. So users' overwrites of default variable values wouldn't take effect.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by KashMoneyMillionaire** [comment]
Is there any documentation supporting this behavior (even if it's beta)? I didn't see it in Docs -> Color Palette, but maybe I'm blind.

Specifically, I'm looking for the variables to overwrite and how to incorporate this into the angular-cli build.

**Comment by mathisscott** [comment]
@KashMoneyMillionaire 
We have the code behind to support using/theming Clarity in this way but we are presently working through the process internally to validate it and then document it for our users.

**Comment by mfp22** [comment]
Any updates on this?

**Comment by mathisscott** [comment]
@mfp22 
Yes, we are very close to having a dark theme ready for review. This effort will include a more simplified approach to theming Clarity.

**Comment by mfp22** [comment]
Awesome!! Is there another issue for that I can watch?
