### ISSUE TITLE
[Clarity v4.0.2] [Regression] clr-control-errors don't show for custom validators

### ISSUE THREAD

**Issue by AtanasVYordanov** [vmware/clarity#5060]
## Describe the bug

[Stackblitz](https://stackblitz.com/edit/clarity-v4-dark-theme-auvyne)

There is a regression after https://github.com/vmware/clarity/pull/5025.
clr-control-errors are not shown for custom validators - only the exclamation mark icon is displayed.

## How to reproduce

1. Add custom validator for input field
2. Add clr-control-errors for the validator and provide error message
3. Trigger validation
4. Error message is not shown

## Expected behavior

The error message should be shown for custom validators.

## Versions

**App**

- Angular: [10]
- Clarity: [4.0.2]

**Device:**

- Type: [MacBook]
- OS: [ iOS]
- Browser [chrome]

## Additional notes

**Comment by bdryanovski** [comment]
Hello @AtanasVYordanov can you provide us with the StackBlitz demo?

You could find a template [here](https://stackblitz.com/@clr-team)

**Comment by AtanasVYordanov** [comment]
> Hello @AtanasVYordanov can you provide us with the StackBlitz demo?
> 
> You could find a template [here](https://stackblitz.com/@clr-team)

Added StackBlitz link to the description.

**Comment by bdryanovski** [comment]
Sorry, maybe I didn't saw it ;)

There two solutions here: 

Change inside the template: 
```html
<!-- Before -->
<clr-control-error *clrIfError="'testValidator'">Some error</clr-control-error>

<!-- After -->
<clr-control-error *clrIfError="'invalid'">Some error</clr-control-error>
```

Or change inside the validator:
```ts
// Before
   validate(control: AbstractControl): ValidationErrors | null {
      return {'invalid': true };
   }
// After 
   validate(control: AbstractControl): ValidationErrors | null {
      return {'testValidator': true };
   }
```

**Comment by AtanasVYordanov** [comment]
Thanks 👍 . Before this version, the example in StackBlitz worked. Not sure if the old or current behaviour is the correct one.
