### ISSUE TITLE
Signpost gets clipped when put inside a stack view

### ISSUE THREAD

**Issue by tishun** [vmware/clarity#5061]
## Describe the bug

Whenever a clr-signpost is nested in a clr-stack-view and the signpost contents take more space than is available in the stack view the signpost is clipped and does not overflow the stack view.

## How to reproduce

Scenario shown here : https://stackblitz.com/edit/clarity-v3-light-theme-dxqjat?file=src/app/app.component.html

1.  Click on the info button next to "Quick Boot"
2.  Observe that the signpost is clipped either on the top of right side, depending on the screen size

## Expected behavior

The signpost should not be clipped, but instead it should overflow the stack view.

Similar issues:
https://github.com/vmware/clarity/issues/4891

## Versions

**App**
(Used by StackBlitz, but other versions exhibit the same issues)
- Angular: 9.0
- Clarity: 3.0

**Device:**

- Type: MacBook
- OS: macOS Catalina v10.15.6
- Browser: Firefox, Chrome 
- Version: 80.0.1, Version 85.0.4183.102 (Official Build) (64-bit)

**Comment by hippee-lee** [comment]
This is one example of the limitation of the old popover implementation. We have an issue to track migrating a better solution to existing components here: https://github.com/vmware/clarity/issues/1757

I'm going to close this issue in favor of that one.
