### ISSUE TITLE
Please create React supportive npm plugin

### ISSUE THREAD

**Issue by naminder-trantor** [vmware/clarity#5064]
## Summary

_Summary the request and address the questions as appropriate._

- Create React supportive npm plugin
- Does this change impact existing behaviors? No
- If this change introduces a new behavior, is this behavior accessible? - This would be an extension to what is available right now.

## Use case

All existing react applications can switch from using ant.design and use clarity designs.

## Workarounds

Currently for icons one can use <clr-icons> but for other features like DataGrid, one has to rely on Custom coding

**Comment by mathisscott** [comment]
`@clr/react` was officially launched with v4.0. We are working on increasing the visibility of the new library, as well as adding more components. Thanks for the interest! 

NPM package: https://www.npmjs.com/package/@clr/react
Documentation: https://clarity.design/storybook/core/?path=/story/documentation-react--page

**Comment by naminder-trantor** [comment]
> `@clr/react` was officially launched with v4.0. We are working on increasing the visibility of the new library, as well as adding more components. Thanks for the interest!
> 
> NPM package: https://www.npmjs.com/package/@clr/react
> Documentation: https://clarity.design/storybook/core/?path=/story/documentation-react--page

Thanks for sharing this is great. For features could we have features like in ant.design, just a suggestion.

**Comment by naminder-trantor** [comment]
Also if you could share how to overwrite the default font family, that would be great.

Thanks in Advance.

**Comment by naminder-trantor** [comment]
Hi @mathisscott ,
I could not find key features like dataGrid, please advise.

Thanks in advance.

**Comment by mathisscott** [comment]
@naminder-trantor
