### ISSUE TITLE
Datagrid context menu pressing tab key focus goes out side instead of cycle in the menu list.

### ISSUE THREAD

**Issue by dilipshelake03** [vmware/clarity#5065]
I have clarity server side grid with selection inside clarity modal dialog. The grid uses *ngFor and trackBy function.
When I open context menu for any row. While pressing tab key continuously the focus is going out side of menu list instead of cycle in menu list. This issue is only occurs for datagrid with clarity modal dialog.

On lastest clarity version i.e 4.1 this seems working. 

**How to reproduce**
https://stackblitz.com/edit/clarity-app-modal-datagrind-context-menu

**Steps to reproduce the behavior:**
- Open modal dialog
- Open context menu for datagrid row. (Clicking in first cell menu items will show up)
- Press tab key continuously. 
- Focus will go outside of menu list. 

**Expected behavior**
The focus should go back to first item in menu list & cycle within it.

**Versions**
App

Angular: 8.2.2
Clarity: 2.4.0
Device:

Browser Chrome

**Comment by hippee-lee** [comment]
Hi There, thanks for reporting this with the stackblitz. I'm not able to reproduce this issue described. I forked the example and downgraded Angular to the reported Angular v8.2.2 and it also cycles for me. https://stackblitz.com/edit/clarity-app-modal-datagrind-context-menu-yij57h

Can you add some guidance so I can re-create the issue as it happens for you?

**Comment by mathisscott** [comment]
I'm marking this issue as stale since we asked for a reproduction 2 weeks ago and haven't heard back.
