### ISSUE TITLE
Style issue with StackView component 

### ISSUE THREAD

**Issue by rumanhassan** [vmware/clarity#5067]
## Describe the bug

When we have nested stack-block, expanded state styles are not applied to stack-block-content component as shown in attached image.
![image](https://user-images.githubusercontent.com/7890944/93809276-b684f880-fc12-11ea-892c-b6b5a13c85ca.png)

## How to reproduce

https://stackblitz.com/edit/clarity-v3-dark-theme-timeline-demo-fadjma

1.  Expand label 3
2. Expand Label 3-1

## Expected behavior

Styles should be consistent

## Versions

Clarity V3

**Comment by kbuffington** [comment]
I was able to fix this by adding the following styles:
```
clr-stack-block.stack-block.stack-block-expanded:not(.stack-block-expandable) > .stack-block-label > .stack-block-content,
clr-stack-block.level-1-with-children.stack-block-expanded > .stack-block-label > .stack-block-content,
clr-stack-block.level-1-with-children.stack-block-expandable:hover:not(.stack-block-expanded) > .stack-block-label > .stack-block-content,
clr-stack-block.level-1-with-children.stack-block-expandable:not(.stack-block-expanded) > .stack-block-label > .stack-block-content {
    background-color: inherit;
}
```
