### ISSUE TITLE
clr-accordion-content not inheriting theming correctly

### ISSUE THREAD

**Issue by ryan-bradford** [vmware/clarity#5076]
## Describe the bug

The background and border colors of the clr-accordion-content are hard bound to be 
```
background: #fff;
border: .05rem solid #ccc;
```

This is a problem when you try and load the dark theme with CSS variables and the colors are not carried over correctly.

## How to reproduce

Navigate to this Stackblitz: https://stackblitz.com/edit/clarity-v3-light-theme-n3v29h?file=src%2Fstyles.css

1.  Open the Item 1 dropdown
2.  Inspect the content of the accordian's HTML
3.  Click the div with a class of `clr-accordion-content`
4.  Observe that the background and border colors are not CSS variables.

## Expected behavior

The background color should be var(--clr-accordion-header-background-color, #fafafa) and the border color should be var(--clr-accordion-border-color, #cccccc). 

## Versions

**App**

- Angular: 9.1.9
- Node: 12
- Clarity: 3.1.3

**Device:**

- Type: Macbook
- OS: Cataline
- Browser Chrome
- Version 85.0.4183.102

**Comment by mathisscott** [comment]
@ryan-bradford 
Thanks for the detailed description and stackblitz. That made this so much easier to track down.
