### ISSUE TITLE
Badge warning style

### ISSUE THREAD

**Issue by spitfjre** [vmware/clarity#5079]
## Describe the bug

Badge warning style is incorrect.

## How to reproduce

It is also incorrect on the [website documentation](https://i.imgur.com/h7MhYU4.png).

## Expected behavior

The color should match the label warning style.

## Versions

**App**

- Clarity: [e.g. 4.0.2]

**Comment by mathisscott** [comment]
Per UX, the badge style on https://clarity.design/storybook/core/?path=/story/components-badge-stories--status is the correct one.

Labels in Clarity UI have not been updated to the new colors in core. But the changes were initiated due to WCAG AA 2.1 contrast requirements.
