### ISSUE TITLE
Icon bug fixes for 8.8 release

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#508]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
- Ellipsis icon (horizontal) should be vertically centered on canvas
- There should be a solid version of the Filter icon on the Iconography page

### Updated files attached:
[icon fixes.zip](https://github.com/vmware/clarity/files/784419/icon.fixes.zip)

**Comment by hippee-lee** [comment]
PR #514 is merged. Closing this.
