### ISSUE TITLE
Datagrid filter / sorting not working

### ISSUE THREAD

**Issue by kaliopane** [vmware/clarity#5085]
## Describe the bug

When we have a checkbox input that defines a filter and it is turned on, this breaks the datagrid sorting and filtering.

## How to reproduce

[Link to Stackblitz](https://stackblitz.com/edit/clarity-v3-datagrid-selection-asnknn?file=src/app/app.component.ts)

1. Click on the button
2. Start sorting and / or filtering columns
3. Observe that no elements are present in the datagrid

## Expected behavior

All datagrid entries should be visible. Regression introduced after upgrade from Clarity v1.

## Versions

**App**

-   Angular: [9.1.12]
-   Node: [10.19] - locally
-   Clarity: [3.1.7]

**Device:**

-   Type: [MacBook]
-    OS: [Mojave]
-    Browser [FF]
-    Version [80.0.1]

**Comment by sis0k0** [comment]
@kaliopane, it seems that the behavior is reproducible even without the filters. Sorting + pagination in the datagrid is enough. Here's a minimal reproduction - https://stackblitz.com/edit/clarity-v3-datagrid-selection-bcncz1?file=src/app/app.component.ts.

We're working on resolving the issue.

**Comment by kaliopane** [comment]
Thanks for the updates guys!
It seems we ought to switch to using Ivy as well, as Angular is not really being helpful in this particular situation.
