### ISSUE TITLE
Icon Request: Update Icon

### ISSUE THREAD

**Issue by alanrenouf** [vmware/clarity#5089]
Not sure if you are open to Icon requests for future versions but it would be nice to have an update icon please.

**Comment by hippee-lee** [comment]
Hi Alan,

Icon requests are always welcome. Please use the icon issue template [here](https://github.com/vmware/clarity/issues/new?template=icon-request.md).

**Comment by lil-kim** [comment]
Hi @alanrenouf 
We don't have a specific update icon, but this one is often used. Would it work in your use case?
![image](https://user-images.githubusercontent.com/23196444/106971053-f8ff2b80-6702-11eb-9fa4-57f21e7ead98.png)
