### ISSUE TITLE
Manually adding Clarity to an Angular project is not working

### ISSUE THREAD

**Issue by developer-bala** [vmware/clarity#5093]
Hello Team,

I am trying to add Clarity to my Angular project manually but it is not working for me. I am referring [this](https://clarity.design/documentation/get-started)

I am keep on getting "An accessor cannot be declared in an ambient context" error in many places of @clr/angular package.

`
../node_modules/@clr/angular/timeline/timeline-step.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14     get iconShape(): string;
           ~~~~~~~~~
../node_modules/@clr/angular/timeline/timeline-step.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15     get isProcessing(): boolean;
           ~~~~~~~~~~~~
../node_modules/@clr/angular/utils/focus/key-focus/roving-tabindex.d.ts:7:9 - error TS1086: An accessor cannot be declared in an ambient context.

7     set rovingIndexItems(elements: Array<FocusableItem>);
          ~~~~~~~~~~~~~~~~
../node_modules/@clr/angular/utils/focus/key-focus/roving-tabindex.d.ts:8:9 - error TS1086: An accessor cannot be declared in an ambient context.

8     get rovingIndexItems(): Array<FocusableItem>;
          ~~~~~~~~~~~~~~~~
../node_modules/@clr/angular/utils/focus/key-focus/roving-tabindex.d.ts:10:9 - error TS1086: An accessor cannot be declared in an ambient context.

10     set rovingTabindexDisabled(disabled: boolean);
           ~~~~~~~~~~~~~~~~~~~~~~
../node_modules/@clr/angular/clr-angular.d.ts:63:31 - error TS2300: Duplicate identifier 'ɵc'.

63 export { AbstractConatiner as ɵc } from './forms/common/abstract-container';
                                 ~~
../node_modules/@clr/angular/clr-angular.d.ts:86:41 - error TS2300: Duplicate identifier 'ɵc'.

86 export { FOCUS_ON_VIEW_INIT_PROVIDER as ɵc } from './utils/focus/focus-on-view-init/focus-on-view-init.provider';
                                           ~~
../node_modules/@clr/angular/clr-angular.d.ts:63:10 - error TS2305: Module '"./forms/common/abstract-container"' has no exported member 'AbstractConatiner'.

63 export { AbstractConatiner as ɵc } from './forms/common/abstract-container';
            ~~~~~~~~~~~~~~~~~

ERROR in Directive ClrAbstractContainer in /opt/perfdash/perfdash.git/ngfrontend/node_modules/@clr/angular/clr-angular.d.ts has no selector, please add it!
`




Any help would be greatly appreciated. Thanks in advance

**Comment by Jinnie** [comment]
What versions of Clarity, Angular and Typescript are you trying to setup. My guess is about mismatch of the Typescript version. Latest Clarity is not yet using Angular 10.1 and Typescript 4.0.2.
Setting 
```
"compilerOptions": {
    "skipLibCheck": true
}
```
in your tsconfig.json might fix the issue, but my recommendation is to stick to the corresponding Angular/TS versions if possible.

**Comment by developer-bala** [comment]
My versions are, 

Angular - 8
Typescript - 3.4
Clarity - 4.0

Yes. I saw that skipLibCheck option, but i'm nervous to use that.

**Comment by Jinnie** [comment]
Clarity major releases are aligned with Angular major releases. And each Clarity major release has corresponding Angular one.
Clarity 4 is designed for use with Angular 10.0.2 (don't yet use 10.1) and TS 3.9.5.
Angular 8 was supported in Clarity 2.0.
