### ISSUE TITLE
datalist styling (issue with length on focus/validation)

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#5094]
## Describe the bug

[Datalist ](https://clarity.design/documentation/datalist) alters length on focus/on validation

## How to reproduce
See Clarity Datalist Documentation https://clarity.design/documentation/datalist

1.  Go to 'https://clarity.design/documentation/datalist'
2.  Click on 'input valid data'
3.  Click on 'input invalid data'
4.  Width of control skips around upon setting focus into/out of the ui-control

![2020-09-30_10h38_50](https://user-images.githubusercontent.com/311619/94663520-0bf39080-030a-11eb-9deb-c5a30730adca.png)

## Expected behavior
Consistent width. 
Same behavior like other input controls in form (input, textarea, select, ...)

## Versions

**App**
- Angular: 10
- Clarity: 4.0.x

**Device:**
- Type: Notebook, Windows, Chrome

**Comment by derkoe** [comment]
Seems like this commit broke it c6995410ac0f5ed396f0f708057bdb8a935a12d0 with this style:
```css
 .clr-focus {
    width: 100%;
  }
```

**Comment by hippee-lee** [comment]
Thanks for reporting this. There was already an issue and PR that will address this: https://github.com/vmware/clarity/pull/5053
The original issue is https://github.com/vmware/clarity/issues/5009. I'm closing this as the fix will go out in the next release.
