### ISSUE TITLE
modal onOpen/onClose events?

### ISSUE THREAD

**Issue by roeeovadia** [vmware/clarity#510]
does the modal support that events?

**Comment by Jinnie** [comment]
No, but it seems there is a clrModalOpenChange(boolean) event.
It's not documented in the example page, but you can find it in the code.

Use it like this in the template:
`<clr-modal (clrModalOpenChange)="openCloseHandler($event)">...`

And then, in the component .ts file, add your handler function:

```
openCloseHandler(open) {
    if (open) {
        // your onOpen code...
    } else {
        // your onClose code...
    }
}
```

Hope this helps :)

**Comment by roeeovadia** [comment]
@Jinnie 
do you have an example?

**Comment by Jinnie** [comment]
This should work:
https://embed.plnkr.co/382rKZ5QiYBfq7c2jNic/
Or you can make changed a property and hook your code on the `set opened()` function.
Not sure which is better.
I experimented with attaching event listener on (clrModalOpenChange), as I initially suggested, but it gets tricky to make it work, and I don't think it's worth it.

**Comment by jeeyun** [comment]
@roeeovadia does example provided by @Jinnie solve your needs? If so, please feel free to close this issue. Otherwise, let us know how we can help further.

**Comment by jaffoneh** [comment]
Closing based on @jeeyun's comments.

**Comment by WuglyakBolgoink** [comment]
Hallo @Jinnie 

is it possible to use this component like a bootstrap-UI Modal from this library https://angular-ui.github.io/bootstrap/#!#modal ??
