### ISSUE TITLE
Stepper resets when having a combobox inside.

### ISSUE THREAD

**Issue by Wallabeng** [vmware/clarity#5101]
## Describe the bug

Stepper resets when having a combobox inside.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-zaowaw

1.  Go to https://stackblitz.com/edit/clarity-v4-light-theme-zaowaw
2.  Click on Next
3.  Select a value from combobox
4.  Stepper resets to first panel

If you change anything in first step to make the form non-pristine, it works as expected.

## Expected behavior

Stepper should not reset

## Versions

**App**

- Angular: 10.0.6
- Node: 8
- Clarity: 4.0.0-rc.1 (inside stackblitz, as I can't update there), but also on latest 4.0.2

**Device:**

- Type: MacBook
- OS: macOS
- Browser chrome, safari

## Additional notes

The listener in stepper for form status changes resets the panel, as the form is pristine.
https://github.com/vmware/clarity/blob/master/packages/angular/projects/clr-angular/src/accordion/stepper/stepper.ts#L76

Seems that the combobox control update which sets the form to non-pristine is after the check above.

**Comment by gnomeontherun** [comment]
This only seems to happen with a combobox in the last panel, adding a third panel does not cause this. There might be something related to the custom form control implementation that triggers a change, but needs more investigation.

**Comment by Wallabeng** [comment]
Just added a third panel and still doesn't work for me.
My observations are that as soon as any control gets altered (setting it non-pristine) before selecting something from the combobox it works.
IMO the combobox sets the form to non-pristine too late, so the stepper resets the form as it thinks it's pristine.

**Comment by Jinnie** [comment]
Dirty state management issue on the combobox was fixed recently with https://github.com/vmware/clarity/pull/5320
We have to check if it affects the current issue, once it gets released.

**Comment by Jinnie** [comment]
The fix mentioned in my last comment did not address this issue.
It turned out to be in Combobox. We were using 2 tactics in parallel to achieve the same status update. One was called once to many and too early, resulting in temporary clearance of the dirty state of the form. In the end, the correct dirty state was served, but the Stepper was subscribed to all changes and reacted to the extra "pristine" event by resetting itself.
Fix coming soon.
