### ISSUE TITLE
Combobox behavior is buggy in Safari on mobile

### ISSUE THREAD

**Issue by sdurnov** [vmware/clarity#5102]
## Describe the bug

- results popover position is often incorrect in Safari (and in other iOS browsers, for instance Firefox, it's even worse)
- browser automatically zooms page when you interact with combobox, which is fine, but if popover doesn't fit into the screen, you can't scroll it without having popover disappear
- border radius seems overridden by browser and input looks somewhat crippled
- In a multi select mode, if you type something and won't select any search result, but just tap outside, popover closes (which is correct), but text that you typed gets erased

## How to reproduce
Just open a docs website and play with Combobox examples.

[Screen recording](https://youtu.be/W0vaSGr2Nhg)

## Expected behavior

Component must look like in other platforms and popover position should be correct

## Versions

**App**

- Angular: [10]
- Clarity: [4.0.4]

**Device:**

- Type: [iPhone 11]
- OS: [iOS 13, 14]
- Browser [Safari, Firefox 28]

**Comment by sdurnov** [comment]
One more thing, that you can also see in a video. When you have something selected in a Combobox with a single selection mode - when you press dropdown caret, it shows you only an item that is selected. To see other items you need to delete text from a textbox. What is the point of that? You can do nothing with this only displayed item.

**Comment by Jinnie** [comment]
@gnomeontherun do we have a support matrix for mobile devices? We can expect "surprises" there with various smart-popover based solutions.
If we want to support the combobox on mobile, we'll need a new design spec for mobile.
Alternatively we may spend an iteration on trying to make it not-unusable.

**Comment by gnomeontherun** [comment]
Let's talk more about what surprises you are expecting, and why. As far as mobile, we support the same as desktop browsers.

**Comment by Jinnie** [comment]
> Let's talk more about what surprises you are expecting, and why. As far as mobile, we support the same as desktop browsers.

My point is that our smart popovers are designed to close on scroll. Also, the positioning algorithm makes 1 pass trying to find better position if there are boundary infringements.
In a mobile, we'll easily be hitting cases there we infringe more than 1 boundary. And a larger popover will most likely be overflowing. Any attempt to scroll the page to see the rest of the popover will result in it being immediately closed.

A useful responsive solution would be to show popovers on whole screen, with scrollable content, when going mobile. But smart popovers don't have this functionality so far.

@sdurnov most of the behaviors of the dropdown (filtering, as per your last comment) are based on the W3C ARIA specs and examples. See this:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html
About clearing the typed text, why would you want to have the typed text preserved if you closed without making a selection?

**Comment by sdurnov** [comment]
> A useful responsive solution would be to show popovers on whole screen, with scrollable content, when going mobile. But smart popovers don't have this functionality so far.

Yes, it was working great on Windows Phone. Not sure it's suitable for all cases, but would be nice to have such an option.

> About clearing the typed text, why would you want to have the typed text preserved if you closed without making a selection?

Exactly. It's annoying if you tapped outside accidentally and everything was deleted.

**Comment by Jinnie** [comment]
> > About clearing the typed text, why would you want to have the typed text preserved if you closed without making a selection?
> 
> Exactly. It's annoying if you tapped outside accidentally and everything was deleted.

My concern about this is that combobox behaves differently than datalist with random text in the input field. The datalist will submit whatever is inside the input, using the options only as a polite suggestion, while the combobox is more like a select control, where you can only have some of the predefined options. I would prefer to avoid this disambiguation and when the popover is closed - do not display anything in the input field, than will not be submitted.
