### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError when using dynamic variables inside an expanded by default accordion

### ISSUE THREAD

**Issue by dereklin** [vmware/clarity#5105]
When an accordion is expanded by default, using any dynamic variables inside of the accordion content produces ExpressionChangedAfterItHasBeenCheckedError.

Here is the stackblitz to demonstrate the issue:
https://stackblitz.com/edit/clarity-light-theme-v2-6hkjqq?file=src%2Fapp%2Fapp.component.html

**App**

- Angular: ^8.2.14
- Node: 12
- Clarity: 2.3.8

**Comment by mathisscott** [comment]
The issue here is related to the way the accordion is wired up. It looks like a bug. Moving to the backlog.

**Comment by theKristi** [comment]
Anyone have a good work around for this?
