### ISSUE TITLE
Remove ClrAriaLiveService

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#5109]
ClrAriaLiveService was never broadly announced and was not used internally in our own code base. It was deprecated in 5.0. This ticket is to mark its removal in 6.0.

**Comment by tovinayv** [comment]
I understand that this was deprecated and decided to remove based on bug https://github.com/vmware/clarity/issues/5083, Got a recommendation to use LiveAnnouncer from @angular/cdk, However, i found that the LiveAnnouncer from @angular/cdk behaves the same way as ClrAriaLiveService.

There is a workaround to make this work, Take a look at this https://stackblitz.com/edit/clarity-v4-dark-theme-wizard-ktrnvg?file=src%2Fapp%2Fapp.component.html

So just wondering, do we really need to remove this from?

**Comment by mathisscott** [comment]
@gnomeontherun

**Comment by gnomeontherun** [comment]
I'm not sure I understand the workaround, but either way this service doesn't work well with certain screen readers and doesn't offer much value in the end that applications benefit from. There are different ways that an app might want to make live announcements, and to that end I'm still planning to remove this.

**Comment by gnomeontherun** [comment]
We won't actually remove this to avoid breaking changes, but it is deprecated and useful only if it works for you. If it doesn't, then we suggest using a different service or building your own.
