### ISSUE TITLE
How do I add more breakpoint to _variables.layout. $clr-grid-breakpoints

### ISSUE THREAD

**Issue by digish777** [vmware/clarity#5125]
I need a break point in _variables.layout, the variable being: $clr-grid-breakpoints

I need to use that breakpoint in _responsive-nav.clarity.scss
@media screen and (max-width: map-get($clr-grid-breakpoints, xl2)) {
}

example:

$clr-grid-breakpoints: ( xs: 0, sm: 576px, md: 768px, lg: 992px, xl: 1200px, xl2:1280px) !default;

/* stylelint-enable */

$clr-grid-columns: 12 !default;
$clr-grid-gutter-width: $clr_baselineRem_1 !default;
$clr-sizes: () !default;
$clr-sizes: map-merge((25: 25%, 50: 50%, 75: 75%, 100: 100%, 150:150%, auto: auto), $clr-sizes);

but If I change node mode scss. In the next npm install it will disappear. 

What would be a permanent solution for adding a break point in for higher resolution:
in this case: 1280px

Thanks in advance

**Comment by mathisscott** [comment]
A SASS override is the clearest path forward for this. But it also depends on how your application is set up to use Clarity. If you are (re)building the Clarity CSS in your own project, the SASS override is straightforward. Just define `$clr-grid-breakpoints` before importing the Clarity SCSS files. That gives you a lot of latitude in customizing the breakpoints.

If you are not pulling in the Clarity SCSS files into a build step, it would be perhaps overly painful to redo your build tooling just to change one SASS variable. In this case, writing custom CSS is the better choice.

**Comment by digish777** [comment]
I refer:
"styles": [
                            "node_modules/@clr/icons/clr-icons.min.css",
                            "node_modules/@clr/ui/clr-ui.min.css",
]
I am not rebuilding. I am referring the scss in the Angular.json file.

Can the variable be overided at this stage?

**Comment by mathisscott** [comment]
@digish777 
No, this is the latter case I described. You will need to use a CSS override.

**Comment by digish777** [comment]
How to add breakpoint for hamburger to appear at 1280px/150% zoom. css over ride code. There is so much code in the base class. It becomes really tough to write similar code in css. any usable code?

**Comment by mathisscott** [comment]
@digish777 
You could literally inspect the styles in Chrome debugger, pull the code for an existing breakpoint, change the breakpoint to what you need it to be, edit it however you want, and ship it. You could even do all of this inside the chrome debugger on its own to verify that it is working as you want it to before copy-pasting it back into your own CSS.

I don't know why you would need to get the code from me...
