### ISSUE TITLE
Datagrid selection handler is sometimes run out of the Angular zone

### ISSUE THREAD

**Issue by hristozov** [vmware/clarity#5126]
## Describe the bug

`clrDgSelectedChange` started behaving differently in version 3.1.8. Seems it now doesn't run the code in the handler in the Angular zone.

This might break `clrDgSelectedChange` handlers which trigger AJAXes and rely on their results noticed by the change detector, or even just a plain `setTimeout`.

## How to reproduce

Stackblitz:
https://stackblitz.com/edit/clarity-v3-light-theme-5am8r6?file=src/app/app.component.ts

1. Click on any item in the list.
2. The text above the grid does not change. ("No updates yet").
3. Click again on other item in the list.
4. Note the text is now (correctly) changed.

## Expected behavior

We should see the correct number of items (1) on step 2.

## Versions

**App**

- Angular: 9
- Clarity: 3.1.8

**Device:**

- Type: MacBook
- OS: Mojave
- Browser: Chrome / Firefox
- Version: latest

## Additional notes

Wrapping the call in `zone.run` seems to resolve the issue, further confirming the handler is invoked outside the zone:
https://stackblitz.com/edit/clarity-v3-light-theme-nne8rc?file=src/app/app.component.ts

Downgrading to 3.1.7 fixes the issue:
https://stackblitz.com/edit/clarity-v3-light-theme-tg5hag?file=package.json

**Comment by bbogdanov** [comment]
@hristozov The fix will come with `v3.1.11` next week.

**Comment by hristozov** [comment]
> @hristozov The fix will come with `v3.1.11` next week.
> 
> Thank you for letting us know about it!

Thanks for the quick fix, Bogdan!
