### ISSUE TITLE
Unable to unselect from combobox for single select

### ISSUE THREAD

**Issue by cloutidj** [vmware/clarity#5128]
## Describe the bug

When using a combobox to select a single value, once the user has selected a value there is no method for them to clear the form control and remove the selection.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-hm2cry?file=src%2Fapp%2Fapp.component.ts

1.  Go to https://clarity-v4-light-theme-hm2cry.stackblitz.io
2.  Select a value from the list
3.  Clearing text from the control will just select the last selected value

## Expected behavior

The user should have a clear button or deleting the text should remove the selection

## Versions

**App**

- Angular: 10.1
- Node: 10.15.3
- Clarity: 4.0.3

**Device:**

- OS: Windows 10
- Browser chrome
- Version 85

## Additional notes

_Add any other notes about the problem here._

**Comment by gnomeontherun** [comment]
This is true of a normal HTML select too, so often people will add an 'empty' option as the default to allow you to unselect one of the options. I think that would be the same expected behavior here, since this is functionally very similar.

**Comment by cloutidj** [comment]
I tried going that approach but wasn't able to find a way to make it work. I've updated the stackblitz with an additional clr-option with a clrValue of null but I'm not able to select the value from the list.

**Comment by gnomeontherun** [comment]
I believe the problem is you are mixing a static list and dynamic list, and since your 'None' option doesn't exist in the dynamic options list it isn't behaving as expected. Adding a new 'None' option to your array should be the way to go here, then check it during form validation or backend processing.

**Comment by cloutidj** [comment]
I'm not sure how that would work.  Adding a null value to the list of values breaks the functionality with the field designation on a null object in the list and the search no longer works and throws errors in the console.  The only way I can see this working would require additional logic to map a null initial form value to a selection only to also map away from that upon form submission.  Even with that, a user would have to know to search for and select 'None'  in the list to clear the value instead of just deleting the text or clicking an 'x' button as happens with multi-select.  Also, with a blank value the option becomes collapsed and nearly invisible in the dropdown list opposed to a select where the option remains a much more clear value to select in the list.

Also, when trying this approach, I tried using a null value for the id property in my example and that throws errors that break the application, so it appears trying to use a null value for a list item key also fails.

**Comment by gnomeontherun** [comment]
@Jinnie any insights to share?

**Comment by Jinnie** [comment]
I compared with the W3C specs. They clear the value if the combobox filter is emptied. We keep the last valid value.
So, it is a bug and needs to be fixed.
