### ISSUE TITLE
Character counter for input/text-area

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#5132]
## Summary
Provide **character counter** for 
 - input (single-line text field)
 - textarea

## Use case
- **Limited amount** of possible chars that can be entered in the field 
(max. amount limited due to db-column settings, printed text, ...)
- **Defined amount** that should be entered 
(eg. zip-code, vehicle-identification-number, ...)

**Design rationale**
- Counter communicates that amount effectively and transparent to the user.
- If the maximum/defined amount is reached, a validation/success text could be displayed. Either instead of the counter or additionally.

## Examples
**Material Design**
https://material.io/components/text-fields (Option: Character counter)
![2020-10-09_16h11_34](https://user-images.githubusercontent.com/311619/95594694-94c9a500-0a4b-11eb-8185-5a5258a46817.png)

**Material Components**
https://material.angular.io/components/input/examples
![2020-10-09_16h18_36](https://user-images.githubusercontent.com/311619/95594635-8085a800-0a4b-11eb-8a01-430784f46d24.png)

**Carbon Design**
https://www.carbondesignsystem.com/components/text-input/usage
![2020-10-09_13h54_13](https://user-images.githubusercontent.com/311619/95594775-b165dd00-0a4b-11eb-9fbf-c39985730716.png)

## Workarounds
- `<input maxlength="x"/>`
- validation

**Comment by bdryanovski** [comment]
@d-m-s  Thanks for the suggestion, we gonna consider it. 

We need to think about how this could be done in the most accessible way. For example how ofter we want to inform the user of the change of the length or do we want to update it over the loss of focus and so on. 

Do we want to block a user from adding more than the limit or go to negative values? And how this will be communicated to the user?

Do we want to check for changes on keyup/keydown or blur. 

@chlane could give some input on the issue :)

**Comment by d-m-s** [comment]
- updating the counter must happen on keydown/up, - on blur would be quite useless.
- for the "loss of focus" i don't see any usecase - as the user is informed about the current focus it's obvious where the focus relies at all times.
- of course the user should be blocked to add more characters than the maximum. I haven't seen any implementation in any design system - including the major ones mentioned above going for negative values.
- a11y should not pose any problems as it basically is an helper-utility that itself can not be interacted with.

@chlane/ @hippee-lee  please add some input to speed things up a little here.

**Comment by chlane** [comment]
Two blind screen reader users I've worked with like hearing a beep when a character limit has been reached as seen at http://www.chrislane.info/examples/maxLengthNotify.html.

**Comment by gnomeontherun** [comment]
I believe this can be implemented by an application with minimal effort today, but it is a good suggestion to have a standard.

The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
