### ISSUE TITLE
clr-dg-action-overflow clicking on the ellipsis causes the cursor to move to top of the page

### ISSUE THREAD

**Issue by digish777** [vmware/clarity#5138]
clr-dg-action-overflow clicking on the ellipsis causes the cursor to move to top of the page

I could not find the reproduce the same in stackblitz

https://stackblitz.com/edit/clarity-ucg3hc?embed=1&file=app/app.component.html
but locally it is happening. 

thanks in advance.

**Comment by bbogdanov** [comment]
Hi, @digish777 without steps to reproduce we are not able to help you. The component is highly used in production and we didn't face such a case.

We will be happy to help you when we have steps to reproduce.
