### ISSUE TITLE
Login Form fields alignment broken in v4

### ISSUE THREAD

**Issue by nmarkapuram-vmw** [vmware/clarity#5146]
## Describe the bug

All the form fields in "v4" are having **max-width:fit-content**, which is causing login form to have different width for user name and password. 

This is impacting all the text input fields in other forms as well.

## How to reproduce

Please navigate to https://clarity.design/documentation/login. Check the alignment of Username and Password form fields.

<img width="503" alt="Screenshot 2020-10-13 at 5 10 35 PM" src="https://user-images.githubusercontent.com/52527886/96092550-ab0eaf80-0ee8-11eb-9341-c9c95f929a0d.png">

## Expected behavior

All the form fields should be aligned with 100% width.(Similar to Clarity v3)

<img width="853" alt="Screenshot 2020-10-15 at 1 18 37 PM" src="https://user-images.githubusercontent.com/52527886/96092786-f9bc4980-0ee8-11eb-9695-640a35d7c7ce.png">

## Versions

**App**

- Angular: 10
- Node: 12.6.1
- Clarity: 4

**Device:**

- Type: MacBook
- OS: Mac OS Catalina
- Browser chrome
- Version 86

**Comment by hippee-lee** [comment]
I'm adding the regression label. This is happening because of a fix I made for t[his PR](https://github.com/vmware/clarity/pull/5053) and [this issue](https://github.com/vmware/clarity/issues/5009)

**Comment by bbogdanov** [comment]
The fix will be available with version `4.0.5`

**Comment by bbogdanov** [comment]
The fix is not working as expected. Something along the way misguides me that the `login` example on the website works fine with the fix. Found what is wrong with the fix. The correct behavior will be available in the next release. `4.0.6`.

**Comment by bbogdanov** [comment]
The fix is not working as expected. Something along the way misguides me that the `login` example on the website works fine with the fix. Found what is wrong with the fix. The correct behavior will be available in the next release. `4.0.6`.
