### ISSUE TITLE
Inconsistent styles for disabled select option between browsers.

### ISSUE THREAD

**Issue by zhangxin511** [vmware/clarity#5153]
## Describe the bug

Selection option missing color for disabled attribute, browser used browser defined attribute directly causing different representations.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-nguv7h

1.  Use chrome
2.  Click the selection, should see "two" disabled with grey text
3.  Use firefox
4.  Click the section, should see "two" disabled, but with pure 000 color and have no difference with others.

## Expected behavior

Clarity should define a css for options with disabled options, so the browser will not use default behavior.

## Versions

**App**

- Clarity: 4

**Device:**

- Type: laptop
- OS: windows
- Browser chrome, firefox

## Additional notes

Chrome display greyed, but I honestly don't understand how chrome display the text as grey by looking the css inheritance:
![image](https://user-images.githubusercontent.com/3719246/96206215-745f8600-0f36-11eb-98bd-f1c1d1903401.png)

Firefox display pure black from clarity predefined css, the css inheritance looks right to me and explains why firefox shows pure black:
![image](https://user-images.githubusercontent.com/3719246/96206277-90fbbe00-0f36-11eb-8951-16c4c9d0f226.png)

**Comment by gnomeontherun** [comment]
Browsers do not allow you to customize the options dropdown in this way, so this is not a Clarity issue but a browser inconsistency we cannot modify. You could consider using the Combobox which is not an HTML select and can disable items. Closing as not an issue for Clarity.
