### ISSUE TITLE
"gulp build --prod" failed if node_modules installed by npm.

### ISSUE THREAD

**Issue by chunghha** [vmware/clarity#516]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No build failure as if node_modules installed by yarn.

### Actual behavior
The prod build failed by Jasmine Type error ( /@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected. ) if node_modules installed by npm. 

If installed by yarn, then I see the build completed perfectly.

Please take a look at this issue for your further research/fix. And, meanwhile, putting a statement about using yarn to the BUILD.md would be helpful for others at least.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14569

### Reproduction of behavior
- $ git clone clarity repo.
- $ cd clarity
- $ npm i
- $ gulp build --prod

### Environment details

* **Clarity version:** checkout from the clarity master branch (as of 2/21/17)

* **OS and version:** Windows 7

* ** Typescript version:** 2.1.6

**Comment by Shijir** [comment]
Just saw you commented on this https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14569. We use yarn.lock to avoid this kind of error. We will soon upgrade our typescript version to the latest possible version, which might solve the problem as other people suggested.
