### ISSUE TITLE
Removing Tabs from Overflow Drop-down Does Not Work Properly in Some Cases

### ISSUE THREAD

**Issue by BojidarTrenchev** [vmware/clarity#5161]
## Describe the bug

I have a horizontal group of clr-tabs, some of which are in an overflow drop-down menu. Every button in the drop-down, when clicked, should move from the drop-down to the list of non-overflowing tabs, when setting clrTabLinkInOverflow = false. This does not work when there two or more tabs in the overflow menu and instead, the tabs just disappear, except for the last one left in the overflow menu.

## Steps to reproduce

1. Create a new component and add a horizontal tab group of clr-tabs, where there are any number of clr-tab, each containing a single button that can contain any text;
2. Add @ViewChildren allTabs : ClrTabLink to the component class for access to the tabs' buttons;
3. Add a click event to every tab's button which calls a function which changes this tab's inOverflow property;
4. Create the function changeOverflow(event), which takes the tab's id from the event object, finds the ClrTabLink object with the same id from allTabs and switches its inOverflow property (tab.InOverflow = !tab.inOverflow). Add this function to the click events;
5. Compile;
6. Open the app in the browser and click a button. It is successfully added to the overflow drop-down menu. Click the same button in the drop-down and it is successfully removed from the overflow menu and added back to the other tabs;
7. Now click at least two button and add them to the overflow menu;
8. Click all buttons in the overflow menu until one remains there. You can see that they simply disappear and tiny white space is inserted where the clicked button's initial position was, instead of the button itself. This does not apply to the last remaining button in the menu which successfully goes back to its place among the non-overflow tabs.

Please note that there is probably a simpler way to reproduce the bug, e.g. manually manipulate the inOverflow property of only two tab buttons, but the above steps demonstrate the problem better.

## Expected Behavior

A tab button which is in overflow menu and its inOverflow property is set to false, is to properly display on its original position among the tabs list and to be removed from the overflow drop-down.

If I have an event which on click, sets all overflow buttons' inOverflow property to false at the same time, then it works fine and they are all returned to their original positions in tabs list.

Another strange behavior is when I have several buttons with inOverflow=true and there is another tab button which is not in overflow but has a click event which switches one of the other buttons' inOverflow, then it works fine - the in-overflow buttons are properly moved to the tabs list and then can be added to the overflow drop-down again.

## Versions 
Software used for this use case:

Clarity version: 4.0.4
Angular CLI: 8.3.25
Node: 10.19.0
OS: linux x64
Angular: 8.2.14
Browsers: tested on the latest Google Chrome and Firefox

## Additional Notes

I also tested another use case, where I dynamically add and remove tabs from the overflow drop-down depending on the browser window width. This scenario works fine. However, this and the previous use case do not work properly (the tabs disappear when inOverflow set from true to false and the UI breaks even more) when I use the following software versions:

Clarity version: 2.3.9
Angular CLI: 8.3.25
Node: 10.19.0
OS: linux x64
Angular: 8.2.14

## Code Extracts
Here is the click event I used in the tabs component class:
```  
@ViewChildren(ClrTabLink) tabs : QueryList<ClrTabLink>;
 changeOverflow(event){
    let currentTab = this.tabs.find((tab) => tab.tabLinkId === event.srcElement.id);
    currentTab.inOverflow = !currentTab.inOverflow;
  }
```
Code for dynamically adding and removing tabs to overflow drop-down depending on the browser window width:
```
@ViewChildren(ClrTabLink) tabs : QueryList<ClrTabLink>;
  @HostListener('window:resize', ['$event'])
  onWindowResize(event){

    let windowWidth = event.target.innerWidth;
    let latestRightPosition = 0;
    let tabWidth = 120;
    let dropdownButtonOffset = 50;

    this.tabs.forEach((tab) => {
      let rightPosition = tab.el.nativeElement.getBoundingClientRect().right;

      if(tab.inOverflow){

        if(latestRightPosition + tabWidth + dropdownButtonOffset < windowWidth){
          tab.inOverflow = false;
          latestRightPosition += tabWidth;
        }

      }
      else{
        if(rightPosition + dropdownButtonOffset > windowWidth){
          tab.inOverflow = true;
        }
        else{
          latestRightPosition = rightPosition;
        }
      }
    });
  }
```

**Comment by gnomeontherun** [comment]
Hello, to help us triage can you please make an isolated reproduction for us to view? https://stackblitz.com/@clr-team has some starters. Also do you have Ivy disabled?

**Comment by BojidarTrenchev** [comment]
I am sorry for the delay. Here is the [demo](https://stackblitz.com/edit/clarity-v4-light-theme-isiqnj?file=src/app/app.component.ts) that demonstrates the bug. Just click on the last two buttons in the overflow dropdown menu. They will disappear instead of being added to the other buttons not in the overflow menu.

I am using the latest version of Angular in the example so Ivy should be enabled.

**Comment by Jinnie** [comment]
Hello, Bojidar,
Thanks for the provided demo. But I can't reproduce the problem looking at it. The items move between the overflow and main menu as expected.

**Comment by BojidarTrenchev** [comment]
Hello, this is very weird as it still does not work for me when I click on the Settings or Images tab, they just disappear. Have you tried clicking those tabs?

**Comment by Jinnie** [comment]
I managed to fully reproduce in Firefox and partially (only key-focus handling) in Chrome. Will need to be investigated further.
