### ISSUE TITLE
Datagrid wrapped DIV height looks too lower to contain the component.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#517]
Datagrid wrapped DIV height looks too lower to contain the component.

![image](https://cloud.githubusercontent.com/assets/5027302/23210649/880ae5ee-f939-11e6-8d60-4d6af02baf8d.png)
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Don't want to show vertical scroll bar beside the grid.
Here is my HTML code structure.
`<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">`
    `<clr-datagrid [(clrDgSelected)]="selected">`
    `<!-- Omitted -->`
    `</clr-datagrid>`
`</div>`
### Actual behavior

Vertical scroll bar always display and the DIV height looks too lower.
### Environment details

* **Angular version:** 2.4.1

* **Clarity version:** 0.8.0

* **OS and version:** OS X 10.12.3 

* **Browser:** [all | Chrome 56 | Firefox 51 ]

**Comment by jaffoneh** [comment]
@wknet123 could you post a plnkr with the issue so we're able to reproduce it?

**Comment by mathisscott** [comment]
Hi @wknet123,

Thanks for submitting the issue. We haven't heard back from you so I'm assuming the issue was resolved on your end.
