### ISSUE TITLE
Documentation for @clr/react

### ISSUE THREAD

**Issue by paul-ebose** [vmware/clarity#5175]
## Summary

It will be nice to have examples for use of Clarity Design and React in the documentation. I know official React support is fairly new but I am opening this in hope that contributors can come in to assist in the process. I can help also

- What is the change?
A change in documentation. It can be integrated in the current documentation or in a separate one

- Why should it go in Clarity?
To help in a smoother transition for people coming from React 

- Does this change impact existing behaviors? If so how?
No, it does not
- If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by coryrylan** [comment]
We are actively working on revamping our documentation website to improve docs on the Web Components and Clarity React so this should improve in the near future. Our temporary docs for React and the Web Components can be found at our storybook doc site. We also have some example apps for reference as well. 

here https://clarity.design/storybook/core/?path=/story/documentation-react--page
https://github.com/vmware/clarity/tree/next/apps 
https://stackblitz.com/edit/react-ts-b1kzck

**Comment by paul-ebose** [comment]
okay thank you

**Comment by gnomeontherun** [comment]
I'm going to close this as already available, and we're working on enhancing this in the coming weeks.
