### ISSUE TITLE
ETA Figma Design update to V4

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#5176]
## Summary

With the addition of several awesome new components (e.g. combobox) we wanted to update our figma design.
So I wanted to ask you if there are any ETAs for a figma library update to clarity v4 :)

**Comment by coryrylan** [comment]
@colinreedmiller may be able to provide a status update on this

**Comment by colinreedmiller** [comment]
The library is continuously updated and published  - as often as 1x a week. Each update contains new components or bug fixes, whatever is prioritized by the team. We are in the process of catching up with 4.0 but do not have a specific timeline for parity with the release.

**Comment by gnomeontherun** [comment]
I'm going to close this as a question and please do follow the Figma file for updates.
