### ISSUE TITLE
Link to Metropolis Font on clarity getting started page is broken

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#5177]
## Describe the bug

On the [getting started](https://clarity.design/documentation/get-started) page, the link to the metropolis font reaches a github 404.

![image](https://user-images.githubusercontent.com/16038088/96685393-53a39000-137d-11eb-8603-5c39b8a37daa.png)
 
## How to reproduce

On the [getting started](https://clarity.design/documentation/get-started) page click "Metroplis R8" button

## Expected behavior

Dowload Metropolis font_

**Comment by gnomeontherun** [comment]
This is interesting, it appears the maintainer of Metropolis deleted his repository. Thanks for raising this up, we'll have to manually add the original files for people to download, which I've attached here. 

[Metropolis.zip](https://github.com/vmware/clarity/files/5425574/Metropolis.zip)

**Comment by gnomeontherun** [comment]
Fixed on website.
