### ISSUE TITLE
Clr-signpost inside of clr-modal doesn't fit in the screen

### ISSUE THREAD

**Issue by AleksandrovaP** [vmware/clarity#5182]
## Describe the bug

When a clr-signpost is being used in a clr-modal, the signpost overflows the screen and it’s bottom part cannot be seen.

## How to reproduce
https://stackblitz.com/edit/clarity-modal-with-signpost

<img width="939" alt="Screen Shot 2020-10-21 at 1 48 53 PM" src="https://user-images.githubusercontent.com/37516804/96710067-359d5600-13a4-11eb-88a2-f41463be69e3.png">

1.  Have a component that opens up a clr-modal
2.  Have a clr-signpost in that modal with long content
3.  Observe that the bottom of the signpost is outside the visible part of the screen

## Expected behavior

The whole signpost to be in the visible part of the screen. In the case when the content of the signpost is too big, it can be scrollable.

## Versions

- Angular: 8
- Node: 12
- Clarity: 2.4

**Device:**

- Type: MacBook Pro
- OS: macOS 10.15.7
- Browser chrome
- Version 86

**Comment by gnomeontherun** [comment]
An app could workaround this by adding CSS to make the content of the signpost scrollable, but from a UX perspective this is quite a large signpost which makes me wonder why it needs to be so large? Perhaps another pattern is better, like expanding content inline?

**Comment by Jinnie** [comment]
The smart popovers story, which would be a good solution candidate for this issue, was recently closed as something we prefer to implement in Clarity Core and avoid duplication of effort. https://github.com/vmware/clarity/issues/1757
Based on this and the proposed workaround, I'm going to close this one.
