### ISSUE TITLE
DatePicker width get increased, when it is in focused state. 

### ISSUE THREAD

**Issue by lalitbhagtani** [vmware/clarity#5184]
## Describe the bug

When user clicks on date picker input element (focus state), then width of date picker get increased.

## How to reproduce

1.  Go to Datepicker
2.  Click on input field
4.  See error, width of input is increased

## Expected behavior

When user click on date picker input element, then its width should not get increased.

## Versions

**App**

- Angular: 10.1.1
- Node: 12.18.3
- Clarity: 4.0.2

**Device:**

- Type: MacBook Pro
- OS: IOS
- Browser: Chrome
- Version: 86.0.4240.80

**Comment by gnomeontherun** [comment]
Hi there, we need a reproduction of this to understand what the issue is. I don't see this happening on the documentation. You can find starter kits at https://stackblitz.com/@clr-team.

**Comment by gnomeontherun** [comment]
This issue does not have a reproduction and we are going to close it as stale. If the issue persists, please provide a working [Stackblitz demo](https://stackblitz.com/@clr-team) to get started.
