### ISSUE TITLE
Cannot set id for combobox

### ISSUE THREAD

**Issue by magistvan** [vmware/clarity#5185]
**Describe the bug**
When trying to specify an id for a combobox, getting the error:
 "Cannot set property id of [object Object] which has only a getter"

**How to reproduce**
Stackblitz link: https://stackblitz.com/edit/clarity-v4-combobox-id?devtoolsheight=33&file=src/app/app.component.ts

**Expected behavior**
Combobox can have an id.

**Versions**

Angular: 10.0.14
Node: 10.16.0
Clarity: 4.0.1

**Comment by coryrylan** [comment]
@macfaden please provide a stackblitz reproduction to help us better understand the issue. You can find starter kits at https://stackblitz.com/@clr-team.

**Comment by Jinnie** [comment]
It's probably related to the A11Y driven need to move the id to the underlying input element, so it's properly referenced by the label's 'for' attribute.

**Comment by krotscheck** [comment]
Here's the repro https://stackblitz.com/edit/clarity-v4-light-theme-eqg4wi
See the test browser console as an example.
