### ISSUE TITLE
Datalist v3 does not display all options when deleting last character

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#5188]
## Describe the bug

Datalist v3 does not display all options when deleting last character

![image](https://user-images.githubusercontent.com/16038088/96845635-2e805180-1451-11eb-90b9-1ea86889b540.png)

![image](https://user-images.githubusercontent.com/16038088/96845658-350ec900-1451-11eb-8b63-c88388a46787.png)

## How to reproduce

1.  Go to [Datalist Demo](https://v3.clarity.design/datalist)
2.  Click on Datalist component in 'Basic Example' and input '1'
3.  Delete '1'
4.  Does not display all option when input field is empty 

## Expected behavior

Expect to see all available options

## Versions

**App**
- Clarity: v3

**Comment by coryrylan** [comment]
This unfortunately is out of our control as the datalist UI is completely controlled by the browser. Also a note that the behavior of datalist can vary between browsers. You can see the same behavior on the MDN examples. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
