### ISSUE TITLE
Multiselection Combobox dirties ReactiveForm during initialization

### ISSUE THREAD

**Issue by MalteJoe** [vmware/clarity#5199]
## Describe the bug

Using `<clr-combobox clrMulti="true">` with Angular Reactive Forms marks the form `dirty` during initial render.
Also an `ExpressionChangedAfterItHasBeenCheckedError` is thrown when using `dirty` in the template and Angular Ivy.

## How to reproduce

Stackblitz: https://stackblitz.com/edit/clarity-v4-dark-theme-wxzwox?devtoolsheight=33&file=src/app/app.component.ts

1.  Observe the log of the [Stackblitz](https://stackblitz.com/edit/clarity-v4-dark-theme-wxzwox?devtoolsheight=33&file=src/app/app.component.ts) during component render. After view initialization, the form should be `pristine`, but is `dirty`
2.  Also the "Save" button is bound to be disabled when the form is pristine, but it is not.
3.  Click "Save" (resets the form)
4.  The button is properly disabled (as expected)

## Expected behavior

* The form is not dirty when not touched by the user. 

## Versions

**App**
See also [Stackblitz `package.json`](https://stackblitz.com/edit/clarity-v4-dark-theme-wxzwox?file=package.json)

- Angular: `10.0.11`
- Clarity: `4.0.0`, `4.0.4`

**Device:**

- Type: Laptop
- OS: Ubuntu
- Browser: At least Chrome 86.0.4240.111 and Firefox 81.0.2

**Comment by coryrylan** [comment]
Thank you for filing the issue with a stackblitz demo. We will take a look into this. It looks like we are missing something in the lifecycle when we setup the component.

**Comment by MalteJoe** [comment]
I noticed the component works somewhat like expected when using `null` instead of an empty list. 
When initializing the `FormControl` with values from the `items` list, its value is `undefined`, but I expect it to be `[item[0], item[1]]`
