### ISSUE TITLE
Documentation is a bit lacking

### ISSUE THREAD

**Issue by alvirtuoso** [vmware/clarity#520]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Documentation about some angular components' example code don't match screenshots.  The Header component is more detailed and does a better job than Navigation. In particular, the example code for navigation didn't provide  what class should be used for the list of menu links. It turned out I had to put nav-link, which was a pain to find it.  THe documentation should be more pleasurable. I hope it's a work in progress. 

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@alvirtuoso thanks for the feedback! We're working on improving the docs but we'd like to hear more from you (if you have time) on the details of docs improvements that you'd like to see (beyond the above)!.

**Comment by bryanerayner** [comment]
I personally would like to see Angular specific documentation entering into the code. Right now, there's a lot of HTML / CSS code which is in the docs (awesome to have that), but you've done so much work to build `clarity-angular`. We can't properly benefit from that work.

If you only made one change, it would be a demo of the applicable Angular directives / components, alongside the HTML / CSS demos.

**Comment by victormejia** [comment]
Willing to write some docs, just wanted to first ask if there's a plan for this? Tackle specific components first?

**Comment by mathisscott** [comment]
It's more an issue of the UX team reworking the documentation. If you see specific areas on the website branch that could be worded better or features that may be missing explanation, feel free to open an issue or submit a PR!

**Comment by jaffoneh** [comment]
Documentation is something we're working on as @mathisscott mentioned but since this issue has no specific pages, I am closing. That said, please do open tickets on specific pages so we can prioritize first. In the meantime, we'll be working on improving pages one at a time. Take a look at Modals, Buttons, and Button Groups for example of new pages and would love to hear feedback!
