### ISSUE TITLE
clicking on the internal anchor tag inside drop down list which is placed inside clr-header does not trigger Heamburer menu close

### ISSUE THREAD

**Issue by digish777** [vmware/clarity#5203]
clicking on the internal anchor tag inside drop down list which is placed inside clr-header does not trigger Heamburer menu close

**Comment by coryrylan** [comment]
@digish777 please provide a reproducible example with Stackblitz. You can find starter kits here https://stackblitz.com/@clr-team

**Comment by Jinnie** [comment]
I guess you're referring to the same setup as in #5294 
As already discussed, this is not a supported configuration.
As can be seen on the updated example below, you should not have access to the actions dropdown once the hamburger is open:
https://stackblitz.com/edit/header-nav-vs-actions-demo?file=src/app/app.component.html
