### ISSUE TITLE
Combobox in datagrid filter not working properly

### ISSUE THREAD

**Issue by magistvan** [vmware/clarity#5208]
## Describe the bug

When a datagrid filter contains a multiselect combobox, there are some strange behaviors:

- When a new (non selected) option is clicked from the list, it is added to the selected ones, but the whole filter disappears (the filter probably does not recognize the combobox's list as its own child component)

- When an already selected option is clicked again, the filter disappears, BUT the list of options is still shown.

- When the last selected option is removed, the ngModel (which is a list) becomes null.

## How to reproduce

See on stackblitz: https://stackblitz.com/edit/clarity-v4-combobox-issue-datagrid?devtoolsheight=33&file=src/app/app.module.ts

## Expected behavior

When clicking on a non-selected option, the filter should still be shown, and selected option should be added to the list.
When clicking on an already selected option, the filter should still be shown, the list should disappear and the selected option should remain the same.
When removing the last item which is selected, the ngModel attached to the combobox should become an empty list.

## Versions

**App**

- Angular: 10
- Node: <whatever version stackblitz is using>
- Clarity: 4.0.0

**Device:**

- Type: Lenovo P50
- OS: Windows
- Browser Chrome
- Version 86

## Additional notes

ngModelChange is called for every change twice, but I think that's not related to combobox.

**Comment by Lasoloz** [comment]
An additional note from my side: we also think that both components (filter and combobox) using popovers might be related to the issue.

**Comment by Jinnie** [comment]
I agree with your findings about both components using popover... though it's a bit vague if the issue is in the combobox, or in the filter.
