### ISSUE TITLE
Broken aria-describedby for toggle switch

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#5216]
## Describe the accessibility issue

the aria-describedby of input is broken.

besides, if `clr-control-helper` isn't provided, the aria-describedby should not be set.

## How to reproduce

inspect the official example of helper text of https://clarity.design/documentation/toggle-switches:

![image](https://user-images.githubusercontent.com/3956876/97520839-1ff8e380-19d7-11eb-9692-93147763692f.png)

## Expected behavior

the id for helper should be `clr-form-control-4-helper`.

**Comment by gnomeontherun** [comment]
This is a duplicate issue we are tracking internally as 162. Closing as a duplicate of #4475
