### ISSUE TITLE
Release Link results in 404

### ISSUE THREAD

**Issue by ad9999** [vmware/clarity#5229]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

_If this is an accessibility related report, please use the correct template at https://github.com/vmware/clarity/issues/new?template=accessibility-report.md_

## How to reproduce

Visit: 

https://next.clarity.design/releases/v4

Try to click on `Release 2020-10-15`

## Expected behavior

User able to see corresponding page with change log

## Versions

**App**

N/A

**Device:**

Macbook

Chrome

## Additional notes

N/A

![Screen Shot 2020-10-30 at 10 12 09 AM](https://user-images.githubusercontent.com/24609252/97736498-04561180-1a99-11eb-8fc1-da9deb9df2af.png)

**Comment by bdryanovski** [comment]
I manage to reproduce it .. 

I'm getting this link when I click

```
https://next.clarity.design/releases/function%20()%20%7B%20[native%20code]%20%7D
```

**Comment by gnomeontherun** [comment]
This has been resolved in the website, closing as fixed.
