### ISSUE TITLE
Remove unsupported stackblitz versions and add new ones for v5.0

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#5231]
## Summary

- [x] We need to remove the stackblitz templates with unsupported Clarity versions from https://stackblitz.com/@clr-team
- [x] We need to add stackblitz templates for @clr/core and @clr/react

Presently we have stackblitz templates for v0.10 and v0.11. 😳 

Note: I don't know who can do this (I tried and couldn't) so I'm assigning to @hippee-lee.

I think it's okay if this happens shortly after 5.0.

**Comment by gssjr** [comment]
The latest template never loads and gets errors in the console

**Comment by Jinnie** [comment]
Done.
Also added v12 templates.
