### ISSUE TITLE
Incorrect package.json metadata for repository field

### ISSUE THREAD

**Issue by rarkins** [vmware/clarity#5235]
## Describe the bug

Packages within this repository have incorrect values for `repository` within their `package.json`. This means, for example, that automated tools cannot detect this source repository and it is not displayed on pages such as https://www.npmjs.com/package/@clr/core

## How to reproduce

Look at any `package.json`, e.g. https://github.com/rarkins/clarity/blob/667b83a135f03cc64498f82b06ad34f5c725d2e1/packages/core/package.json#L31

## Expected behavior

Replace `"url": "git@github.com:vmware/clarity.git"` with `"url": "https://github.com/vmware/clarity.git"`

## Versions

All

## Additional notes

It's also recommended that the `repository.directory` field be set too, to identify which subdirectory in the monorepo that the source is located.

**Comment by bdryanovski** [comment]
@coryrylan I think that we could easily update this ?

**Comment by gnomeontherun** [comment]
Technically, `git@github.com:vmware/clarity.git` is a valid repository URL for accessing using SSH. I can change this though in the upcoming release.

**Comment by hippee-lee** [comment]
fwiw - I use the ssh urls.

**Comment by rarkins** [comment]
Then at least pick a URL syntax for SSH that is supported by npm given that you are publishing them to npm

**Comment by gnomeontherun** [comment]
Will be fixed by #5345.
