### ISSUE TITLE
Unable to access to clarity sig post inside ng template

### ISSUE THREAD

**Issue by jeevanm18** [vmware/clarity#5239]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

_If this is an accessibility related report, please use the correct template at https://github.com/vmware/clarity/issues/new?template=accessibility-report.md_

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/edit/clarity-light-theme-v2-hlqvvd?file=src%2Fapp%2Fapp.component.html). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v2-hlqvvd?file=src%2Fapp%2Fapp.component.html
2.  Cannot see sign post icon in the web page
3.  remove ng template in the code and now we can see the ng signpost

## Expected behavior

_Sign post should icon should be seen and should be accessible 

## Versions

**App**

- Angular: [8]
- Node: [12]
- Clarity: [2]

**Device:**

- Type: [MacBook]
- OS: [iOS]
- Browser [chrome, safari]
- Version [84]

## Additional notes

_Add any other notes about the problem here._

**Comment by bbogdanov** [comment]
Hi @jeevanm18

Like I said in `slack`, what you are missing is `[ngIf]="true"` inside the `ng-template`

[Here](https://stackblitz.com/edit/clarity-light-theme-v2-ts35gk?file=src/app/app.component.html) you can see the example.

https://angular.io/guide/structural-directives#the-ng-template is where you can find more info about `ng-template`
