### ISSUE TITLE
Document required fields explicitly on the site

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#524]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
"In the above, it looks like that appeared there because the field is invalid. It would be worth calling out this style guideline more explicitly." - @vigie via Slack

### Actual behavior
- Required field design specifications don't exist in detail on the website
- there is one small, nested example of a required field but is easily overlooked
  - in the Compact Forms section of [Forms](https://vmware.github.io/clarity/documentation/forms)

### Reproduction of behavior
![image](https://cloud.githubusercontent.com/assets/1858226/23232225/11d39052-f910-11e6-92ac-b0b819948eb1.png)

**Comment by reddolan** [comment]
To be placed before the "Validation" section on the [Forms](https://vmware.github.io/clarity/documentation/forms) page

### <h4>Required Fields
Used to indicate required form fields to be filled out by a user. Required fields show a red asterisk at the end of the label. It is done by applying `class=“required”` to the form field's label.

![image](https://user-images.githubusercontent.com/1858226/27560926-9b913812-5a8b-11e7-93a5-7a1a33eecf67.png)

**Comment by adityarb88** [comment]
fixed
