### ISSUE TITLE
Clarity sign post content  inside data grid has a horizontal scroll bar

### ISSUE THREAD

**Issue by jeevanm18** [vmware/clarity#5244]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

_If this is an accessibility related report, please use the correct template at https://github.com/vmware/clarity/issues/new?template=accessibility-report.md_

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/edit/clarity-light-theme-v2-hlqvvd?file=src%2Fapp%2Fapp.component.html). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to https://stackblitz.com/edit/clarity-light-theme-v2-hlqvvd?file=src%2Fapp%2Fapp.component.html
2.  Click on any of the signpost button inside data grid
3.  Scroll horizontal  to view the whole data

## Expected behavior

Scroll bar should not appear and the whole data should be shown one below the other

## Versions

**App**

- Angular: [8]
- Node: [12]
- Clarity: [2]

**Device:**

- Type: [MacBook]
- OS: [iOS]
- Browser [chrome, safari]
- Version [82]

## Additional notes

_Add any other notes about the problem here._

**Comment by bbogdanov** [comment]
[Solution](https://stackblitz.com/edit/clarity-light-theme-v2-bgo65e?file=src%2Fapp%2Fapp.component.css)
