### ISSUE TITLE
Combobox search values longer than input get cleared.

### ISSUE THREAD

**Issue by mathi123** [vmware/clarity#5246]
## Describe the bug

When typing search text in the combobox, the typed value gets cleared if the input is longer than the input size.

## How to reproduce

1.  Go to the [combobox documentation page](https://clarity.design/documentation/combobox#examples)
2.  Enter a search value of 21 characters in the first example combobox
3.  Upon typing the 22th character, the search value disappears

Making the search input width longer, increases the number of characters typed before its cleared.

## Expected behavior

The search input box behaves like a normal text input: the last x typed characters are visible.

## Versions

**App**

- Clarity: 4.0.2
- Angular 10.0.0-rc.6

But problem occurs on latest build to (see docs example).

**Device:**

All devices.

## Additional notes

**Please indicate if this is expected behavior or not.**
I have been browsing the clarity code, but I can't find where this behavior is configured.

## Why?

Combobox search input is used to enrich combobox with a simple and clean 'Create' option.

![2020-11-02 16_20_48-TrendTracker](https://user-images.githubusercontent.com/3677437/97885285-72b00380-1d27-11eb-8912-c883739b715f.png)

The bug prevents me of adding items with a long name.

Please advice if this is against guidelines.

**Comment by Jinnie** [comment]
Fixed by https://github.com/vmware/clarity/pull/5320

**Comment by Jinnie** [comment]
The underlying issue was that longer text was generating horizontal scrolling event in the input field itself, which got intercepted by the close-on-scroll popover handler and the value was cleared as part of the on-close handler.
