### ISSUE TITLE
Accordion v4 nesting into reusable component throws error - Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by igpeev** [vmware/clarity#5268]
## Describe the bug

When I place (2) inside a `child` component with reuse in mind ((1) stays in `parent`), the error `cannot read property 'open' of undefined` is thrown on-load and on-expand-click (the expand/collapse also doesn't work under this scenario)

Components of Clarity Accordion referred:
1. `<clr-accordion>`
2. `<clr-accordion-panel>`,  `<clr-accordion-title>` and `<clr-accordion-content>`

## How to reproduce
[StackBlitz](https://stackblitz.com/edit/clarity-v4-light-theme-zaggi-accordion-issue?devtoolsheight=33&file=src/app/app.component.html)

1.  Load the provided StackBlitz and inspect the console (the error is thrown)
2. Try expand the Accordion and inspect the console (the error is thrown)

## Expected behavior

The Accordion should load normally and expand/collapse without errors

## Versions

**App**

- Angular: [10.1]
- Node: [12.13.1]
- Clarity: [4.0.2]

**Device:**
- Browser [Chrome]

## Additional notes

_Add any other notes about the problem here._

**Comment by bdryanovski** [comment]
The error is thrown from here `projects/clr-angular/src/accordion/accordion-panel.ts`

It seems that these lines are having a hard time returning the correct service

```
    this.panel = this.accordionService.getPanelChanges(this.id).pipe(tap(panel => this.emitPanelChange(panel)));
```

So we are getting `this.panel.open` to be `undefined`

**Comment by gnomeontherun** [comment]
This changes the component hierarchy, so the expectations have to be different. What is the full use case here as to why you wouldn't just put the accordion inside of the child component too?

**Comment by bdryanovski** [comment]
Here is part of the Slack discussion: 

> For example
> in parent:
```html
<clr-accordion>
    <child [header]="'Sofia'" [data]="'Temperature 10C'"></child>
    <child [header]="'NYC'" [data]="'Temperature 15C'"></child>
</clr-accordion>
```
> in child
```html
<clr-accordion-panel>
    <clr-accordion-title>{{ header }}</clr-accordion-title>
    <clr-accordion-content>{{ data }}</clr-accordion-content>
</clr-accordion-panel>
```
> And this is a real example what else what I’ll be putting in header (i.e. not just a string, but - bubbles, ?-links to contextual help, and other functionality that we want to abstract (to be hosted in child)

@igpeev mention that they have some workaround on the issue (a bit sketchy workaround). 

I did not test it ... but setting `descendants: false` could help - but probably it's not added by chance so it could break something else.

```ts
// projects/clr-angular/src/accordion/accordion.ts 
@ContentChildren(ClrAccordionPanel, { descendants: true }) /* current state */
```

**Comment by gnomeontherun** [comment]
I don't want to over complicate this either, a potential solution is to rethink how you nest the components. Angular (and therefore our components) can expect certain component trees, and abstractions can get in the way of the lifecycle processing. 

You aren't getting much value by wrapping the accordion title and content elements entirely, just wrap the internals of the content. While we might be able to support this in the Accordion, it is possible to follow this pattern instead and avoid the complexities of trying to handle this in Clarity for very little gain.

```
<clr-accordion>
  <clr-accordion-title>Sofia</clr-accordion-title>
  <clr-accordion-content>
    <app-child></app-child>
  </clr-accordion-content>
</clr-accordion>
```

**Comment by Jinnie** [comment]
I second Jeremy's recommendation. 

I also confirm Bozhidar's research. I can add to it that the data actually is there, but we're getting abnormal lifecycle events with no data after the regular ones.
