### ISSUE TITLE
Invalid password input changes width when focused

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5269]
## Describe the bug

An invalid password inout changes it's width when focused.

![Screen Shot 2020-11-05 at 14 07 59](https://user-images.githubusercontent.com/3655915/98244860-5e127c00-1f70-11eb-9f25-b681e606b550.png)
![Screen Shot 2020-11-05 at 14 08 04](https://user-images.githubusercontent.com/3655915/98244864-5eab1280-1f70-11eb-8793-640e60e5e928.png)

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-v4-light-theme-ilsewj?file=src/app/app.component.html
2.  Type e.g. "ABC" in the password input
3.  Click out of the input to trigger validation
4.  Focus it again
5. See the changing width of the red line that shifts the icon to the right

## Expected behavior

Width stays the same.

## Versions

**App**

- Angular: 10.2.2
- Clarity: 4.0.5

**Device:**

- Browser Chrome

**Comment by bdryanovski** [comment]
@dorthrithil thank you for reporting this - it seems that there is a bug in how we calculate the width of the input. Not sure why - but we gonna investigate it a bit more

**Comment by dorthrithil** [comment]
@bdryanovski Version 4.0.6 brings another probably related bug:

Focused password inputs now take 100% width

![Screen Shot 2020-11-13 at 10 29 49](https://user-images.githubusercontent.com/3655915/99056872-3d16e000-259b-11eb-86b3-088e09588102.png)

Here's a stackblitz:

https://stackblitz.com/edit/clarity-v4-light-theme-p9fvw2?file=package.json

Maybe related to the fix for https://github.com/vmware/clarity/issues/5146 where password inputs didn't take 100% width in the login form anymore? This was fixed in 4.0.6 and now we have a new 100% width bug.

**Comment by bdryanovski** [comment]
@dorthrithil you are right it seems like a regression - need to check to be sure.

We gonna try to fix it for the next release

**Comment by sneksinnej** [comment]
We are having the same issue while using clarity 4.0.6
It seems that when you focus a field it adds a `clr-focus` class to the `clr-input-group`.
This `clr-focus` has only 1 css field `width: 100%`.
This seems to only happen for `<clr-password-container>` that are within `<form>`  tags.
The same is happening on the documentation site of clarity.

**Comment by royling** [comment]
looks like the `.clr-focus` style declared [here](https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/forms/combobox/_combobox.clarity.scss#L39-L41) is polluting [the style used in password input](https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/forms/password/password-container.ts#L32).

a simple workaround is like:

```css
.clr-input-group.clr-focus {
  width: auto;
}
```

maybe this can be a fix in https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/forms/styles/_input-group.clarity.scss.

If you think that's ok, I can submit a PR for it.
