### ISSUE TITLE
Using datatable with Metronic admin theme (bs 3)

### ISSUE THREAD

**Issue by sebitsi** [vmware/clarity#527]
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] question
```

### Environment details

* **Angular version:** 2.4.0

* **Clarity version: 0.8.7 

* **OS and version: Win 10 

Hi. 

Is it possible to use Clarity components (especially datagrid) inside existing SPA application
based on bootstrap 3  and Metronic template ?. 

There is no problems with ts code and icons.
But using both Metronic.css and Clarity-UI.css is not working perfect.

Is it possible somehow override styles just for datatable component ?

Thanks

Edvin

**Comment by jaffoneh** [comment]
Hi, @sebitsi: we cannot handle specific conflicts with the Metronic template, however, you should be able to use the Clarity datagrid inside of it if you do the modifications needed yourself (by simply overriding CSS styles although be careful that this means supporting the datagrid moving forward with updates from Clarity is going to be difficult and time consuming on your part) or if you work with the Metronic team to add support for Clarity.

**Comment by youdz** [comment]
If you want to use an external theme with Clarity, you will have to handle CSS conflicts on your side, mostly by overriding the conflicting parts on both side in your own stylesheet with whichever value produces the result you want.

Sadly, Datagrid is an extremely complex component for which the internal template and classes are not documented, on purpose. We need to be able to update and modify the internal styles without it being a breaking change every time. 
Overriding one style on your side for a very specific reason would probably be fine, but overriding almost all the styles to get an entirely different look and feel would definitely not be maintainable.

**Comment by sebitsi** [comment]
Hi, 
thanks for both answeres.

I like Clarity UX very much. Concepts how components are created to.
If we start with empty project based on clarity clarity will bi great option.

But we have project based in Metronic and some jquery libraries.
If we want migrate to Clarity this is not possible because of conflicts with css.

I have 2 more questions:

1. In project roadmap i noticed baclog item "Move off Bootstrap".
    What this mean ? If you remove dependices to bootstrap will you change classes names and there 
    will be no conflicts with bootstrap in same project ?
    If so this could be solution for my problem.

2. Clarity-UI.min.cs has 737 KB size. Why is so big ? Clarity-Angular.js has only 164 KB.  
    BS 3 on other hand is "only" 191 KB. 

Regards.

Edvin
