### ISSUE TITLE
Add disabled state for button group

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5272]
## Summary

Add a disabled inout to the `clr-button-group` component that disables all buttons including the overflow button.

## Use case

When all actions in a button group should be disabled. This can be the case if you e.g. first have to provide some input in a form before using any of the buttons. 

## Workarounds

Disable all single buttons - this leaves the overflow still active, which doesn't look good (can be fixed by CSS of cause):

![Screen Shot 2020-11-06 at 11 34 46](https://user-images.githubusercontent.com/3655915/98356573-10efe200-2024-11eb-9bda-3361ba824ec5.png)

**Comment by gnomeontherun** [comment]
If all buttons are disabled, what is the value in showing them at all? I'm curious about the use case, but I would agree that if all overflow items are disabled that the overflow itself might also be "disablable".

**Comment by dorthrithil** [comment]
If a user doesn't see the buttons at all he may wonder why there are any input fields in the form at all if there is no action linked to them. When you show disabled buttons the user knows that he most probably has to fill out the form for the buttons to become enabled.

A good example for this is the github comment box where it's exactly the same. With the exception that single buttons are used. As I need to save some space in my concrete usecase I opted for the buttongroup with overflow for the rarely used actions.

**Comment by Jinnie** [comment]
If the overflow button is disabled, then the user will not be able to preview which actions are available, though disabled, inside the overflow. I don't think we should disable the overflow button.

**Comment by dorthrithil** [comment]
I think user doesn't need to see the actions inside the overflow to understand the situation, at least in my concrete usecase. 

Here's a little more context:

![Screen Shot 2020-11-16 at 10 12 12](https://user-images.githubusercontent.com/3655915/99234081-5f576a80-27f4-11eb-9d30-dca5c76c06b6.png)

As a user my thoughts would be:

- I want to assign a role
- Theres a select with no role selected and some disabled buttons next to it
- OK, I have to select a role and then I can assign the role in one or the other way using the buttons which will probably become enabled after selecting a role

@gnomeontherun's suggestion of not showing the overflow at all would lead to a jumpy UI, I think disabling is a better solution.



Maybe this request is a bit to specific but I think it would be a good addition to Clarity to allow the Clarity user to disable all kinds of buttons. Currently I use an OK workaround by just greying out the overflow button using CSS and disabling all buttons inside it but it's a bit counter intuitive because you can click the button which actually looks disabled.

**Comment by Jinnie** [comment]
Thanks for the detailed description.

Though the suggested approach "looks" OK as design and UX, it can lead to accessibility implications.
All disabled buttons still need to be reachable for the accessibility user. That's a requirement to us.

You can easily add a placeholder text or a single disabled "dummy" button (even a group of two with ellipsis in the 2nd) if the buttons in the overflow are irrelevant in your specific case.

I understand your point, but the value of prioritizing it is questionable for the common case and brings certain risks. Also there is a viable workaround, as described.
