### ISSUE TITLE
Date Picker with calendar weeks (optionally shown in first column)

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#5273]
## Summary

Enhance the current date picker to optionally (via parameter) show the calendar weeks in the first column.

- What is the change?
add parameter to show calendar weeks.

- Why should it go in Clarity?
In Europe, probably with focus to german speaking areas, calendar weeks are commonly used to refer to a data.
More particular in delivery and production businesses the calendar week is an important criteria.

- Does this change impact existing behaviors? If so how?
Should be introduced as optional parameter. May not break/occur on existing usages of the date picker.
Ideally could be globally activated/deactivated for all usages of datefields within an application if not overridden by parameter.

- If this change introduces a new behavior, is this behavior accessible?
Selection of calendar  week is not necessary, hence only information is displayed.

## Use case
The user knowns that a delivery is expected in calendar week 46 (CW46), eg. from some phone call or paper delivery bill, and wants to set eg. monday of this week into the date field.

## Examples

**Clarity example, currently without calendar week**
> <img width="376" alt="2020-11-06_11h52_00-Clarity currently without CW" src="https://user-images.githubusercontent.com/311619/98362582-c96e5380-202d-11eb-88ea-3443de321902.png">

**Microsoft Fluent Design**
[https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker](https://developer.microsoft.com/en-us/fluentui#/controls/web/datepicker)
> <img width="254" alt="2020-11-06_12h28_13-KW-FluentDesign" src="https://user-images.githubusercontent.com/311619/98362587-ca9f8080-202d-11eb-9aed-977066276950.png">

**Outlook**
> <img width="142" alt="2020-11-06_12h40_17-KW-Outlook" src="https://user-images.githubusercontent.com/311619/98362589-cb381700-202d-11eb-9d63-dc96813bf2d1.png">

**Bootstrap**
> <img width="236" alt="2020-11-06_11h56_27-KW-Bootstrap" src="https://user-images.githubusercontent.com/311619/98362584-ca06ea00-202d-11eb-8b69-0b1164ec4977.png">

## Workarounds
Cumbersome, looking into physical calender's or other software products (Outlook) switching back to application and entering the date.

**Comment by bdryanovski** [comment]
@d-m-s this is something that we could consider adding but probably as part of the new Core component as part of the DatePicker and TimePicker component that we plan to replace the current one. This is something that we have on our roadmap for the next year.

**Comment by d-m-s** [comment]
Hi @bdryanovski, do you refer to the mentioned #474, or is there another existing?

**Comment by bdryanovski** [comment]
It's one of them. We are planning to redesign and rework the component, and want to do it right so that's why we are taking more time to plan what we want to include and how to make it accessible for everyone. We have some plan on how to do it, not everything is public, it's just not in the roadmap until the end of the year (for now).

**Comment by d-m-s** [comment]
can you give us a little more info about *when* this will start to be implemented? 
or if *some form of contribution* could speed up the process?

**Comment by gnomeontherun** [comment]
Hey @d-m-s, we're starting to consider enhancements only for Clarity Core implementations of components, as we wish to stabilize Clarity Angular for long term support. We've had internal discussions about how and when to build the Clarity Core versions of Date Picker, but have currently settled for the default browser date picker as we have a few dependencies to build first (we need to finish working on popovers in Core for example). We haven't done any design work on this yet, and I don't have any timeline as its not a current top priority until we finish the necessary dependencies. I also don't know what the accessibility requirements might be to add this additional column, so there are a few fundamental things to understand before we could tackle it so we aren't ready to encourage a contribution at this stage.

**Comment by Jinnie** [comment]
Transferring my last comment form #5351 

This should definitely go through Accessibility team first, as I don't see this feature in the W3C examples:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/datepicker-dialog.html
@chlane

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
