### ISSUE TITLE
Combobox: Shown options are not reset after resetting the ngModel value

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5275]
## Describe the bug

When first clicking the arrow of a combobox, all options are shown. When you select an item, then reset the value of `ngModel` and then click the arrow again only the previously selected item is shown.

**All items are shown first:**

![Screen Shot 2020-11-09 at 10 09 44](https://user-images.githubusercontent.com/3655915/98521451-bf3d9680-2273-11eb-9840-4f6d354d33ba.png)

**The selected item is shown:**

![Screen Shot 2020-11-09 at 10 09 48](https://user-images.githubusercontent.com/3655915/98521454-bfd62d00-2273-11eb-8e58-524ceeca4a68.png)

**Model is reset but still only the previously selected items shows up:**

![Screen Shot 2020-11-09 at 10 09 53](https://user-images.githubusercontent.com/3655915/98521455-c06ec380-2273-11eb-83b4-b93ee039534f.png)

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-v4-light-theme-rwr3wp?file=src/app/app.component.ts
2.  Select an item
3.  Click submit (`ngModel` is reset to null)
4.  Click the arrow of the combobox: Only the previously selected item shows up in the list.

## Expected behavior

All items should be shown after reset.

## Versions

**App**

- Angular: 10.2.2
- Clarity: 4.0.5

**Comment by bdryanovski** [comment]
@dorthrithil thank you for reporting this - you are right it looks like a bug into the Combobox and forms - we need to investigate it a bit more.
