### ISSUE TITLE
Stackblitz template broken?

### ISSUE THREAD

**Issue by duzenko** [vmware/clarity#5277]
## Describe the bug

Trying to create a demo for an issue I encounter with Clarity but the Stackblitz template fails to initialize

## How to reproduce

Go to https://stackblitz.com/edit/clarity-v4-light-theme
Preview fails to load
Open browser console
Observe an error log
![image](https://user-images.githubusercontent.com/1481807/98527256-77267000-2283-11eb-9d98-93292e74a83b.png)

![image](https://user-images.githubusercontent.com/1481807/98527403-a6d57800-2283-11eb-94f7-ae08a09d082a.png)

```
{"dependencies":{"rxjs":"6.6.0","tslib":"2.0.0","@clr/ui":"4.0.0-rc.1","zone.js":"0.10.3","@clr/core":"4.0.0-rc.1","@clr/icons":"4.0.0-rc.1","@clr/angular":"4.0.0-rc.1","@angular/core":"10.0.6","@angular/forms":"10.0.6","@angular/common":"10.0.6","@angular/router":"10.0.6","@angular/compiler":"10.0.6","@angular/animations":"10.0.6","@angular/platform-browser":"10.0.6","@webcomponents/custom-elements":"1.4.2","@angular/platform-browser-dynamic":"10.0.6","@angular/compiler-cli":"10.0.6"}}
```

```
{"error":"MISSING_PEERS","data":{"typescript":{"@angular/compiler-cli@10.0.6":">=3.9 <4.0"}}}
```

## Expected behavior

No errors in console

**Comment by dorthrithil** [comment]
The posted link works for me (Chrome 86.0.4240.111 on Mac). But I experienced other issues using stackblitz lately. After updating the dependencies to the newest clarity version stackblitz didn't compile anymore. After disabling ivy it worked.

**Comment by Jinnie** [comment]
I am also unable to reproduce it:
<img width="1124" alt="Screen Shot 2020-11-12 at 6 44 08 PM" src="https://user-images.githubusercontent.com/1798828/98969052-1e6f0580-2517-11eb-97f1-1a77988520ff.png">

Please try the following:
- Different browser
- Incognito mode of the same browser
- Clear browser cache

**Comment by duzenko** [comment]
It does work in a different browser but
https://github.com/stackblitz/core/issues/1305
