### ISSUE TITLE
clr-combobox displayed value

### ISSUE THREAD

**Issue by real-artswan** [vmware/clarity#5278]
It is more kind of question.

I'd like to use combobox inside reactive form so that I'm assigning `formControlName="clientId"`, but it contains id while I want to display a name instead.
So is there a way (template?) to customize displaing a selected value? I tried to use `clrOptionSelected="let selected"` but it doesn't display anything in my case.

this code displays filtered list but not the selected value
`
<clr-combobox formControlName="clientId" [clrLoading]="loadingClients" (clrInputChange)="fetchClients($event)" >
		<ng-container *clrOptionSelected="let selected">
			<span> {{selected}} </span>
		</ng-container>
		<clr-options>
			<clr-option *clrOptionItems="let client of clients$ | async; field:'name'" [clrValue]="client.id">
				<span>{{client.name}}</span>
			</clr-option>
		</clr-options>
	</clr-combobox>
`
![зображення](https://user-images.githubusercontent.com/3417195/98530770-0a61a480-2288-11eb-99c9-f8be2a1937f5.png)
![зображення](https://user-images.githubusercontent.com/3417195/98530848-249b8280-2288-11eb-9d74-6e96edfc788b.png)

**Comment by bdryanovski** [comment]
@Jinnie can you share some secrets from the kitchen on that :)

**Comment by Jinnie** [comment]
Please, use the stackblitz templates here when reproducing a problem: https://stackblitz.com/@clr-team

Generally, in single selection combobox, the selected value is displayed inside the filter area. And it's editable. So, it will be the field you are using for as display value - in your case it's the `field='name'`. When you move your focus out of this field, even if you edited it, but did not make a selection, the last selected value will be populated.
Templates are only used in multi-selection scenario for defining the display of the generated pills, not in single-selection, where current value is in the input field itself.
See these W3C specs for reference:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html

**Comment by real-artswan** [comment]
I'm sorry, it seems I wasn't clear enough. Here is the sample
https://stackblitz.com/edit/clarity-v4-dark-theme-977ppm?file=src/app/app.component.html

Select any item in the combobox and see that selected value is not visible in the input field. So the question was: "how to fix it?"
Thanks in advance.

**Comment by Jinnie** [comment]
I see...
`[clrValue]="client.id"` <- the misconception is that the combobox does not really operate as the HTML `<select>` element. The `clrValue` is of object type and that's the type of the objects in your data set. So, it should be changed to `[clrValue]="client"` and then you can get the field you need from the selected object.
I understand that this may be imposing some difficulties, but currently the combobox does not support trackBy, or external comparator function, which would be needed to resolve objects by their id's, or other key identifiers. Without this functionality, we won't be able to do the initial value resolution and track the selected items by their ids only. So far, this is out of scope for the current implementation of the Combobox.

**Comment by real-artswan** [comment]
Thanks for the clarification, it seems I still can not live without ng-select
