### ISSUE TITLE
Selecting an already selected option in combobox leaves the menu open

### ISSUE THREAD

**Issue by magistvan** [vmware/clarity#5282]
## Describe the bug

When an option is combobox is selected and the user opens the dropdown for combobox again and selects the same one again, the dropdown remains open.

## How to reproduce

1. Select an option in combobox
2. Open dropdown of combobox / delete the last character from the selected value in input
3. Select the same value
4. Dropdown remains open

Stackblitz link: https://stackblitz.com/edit/clarity-v4-combobox-same-selected?devtoolsheight=33&file=src/app/app.component.html

## Expected behavior

After the already selected item is clicked, the dropdown should simply disappear.

## Versions

**App**

- Angular: 10
- Node: whatever version stackblitz is using
- Clarity: 4

**Device:**

- Type: Notebook
- OS: Windows 10
- Browser Chrome
- Version 86

**Comment by Jinnie** [comment]
Selecting the same value actually does not count as selection event.
I am currently working on some related issues around the open/closed state, so I'm assigning this to myself, to keep in mind and see if we the new updates will affect it.

**Comment by Jinnie** [comment]
With the latest implementation, after assuming a11y team feedback, selecting any option in multi-select mode will leave the menu open, to allow for more selections, while selecting an already selected option will toggle it.
