### ISSUE TITLE
Custom filter shows In left corner after opening show/hide column menu

### ISSUE THREAD

**Issue by MichaelWGibson** [vmware/clarity#5290]
## Describe the bug

After creating a custom filter component for the data grid component everything initially worked as expected. Then after I add the ability to hide and show columns, and changed the visible columns in the UI, the filter started rendering in the top corner of the screen instead of below the filter icon.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-custon-filter

1.  Open stack blitz link
2.  Click on the filter Icon for the name column (filter renders correctly)
3.  Click on the the icon in the bottom left corner of the Datagrid
4.  Close the 'Show Columns' Pop up
4.  Click on the filter Icon for the name column (filter renders in the top corner of screen)

## Expected behavior
This is what it looks like the first time you click the filter Icon (this is what I would expect to happen every time)

![working-filter](https://user-images.githubusercontent.com/32117195/98863943-5cd8c780-2426-11eb-97dc-7bb17e8315fe.PNG)

This is what it looks like after opening the show/hide columns menu

![broken-filter](https://user-images.githubusercontent.com/32117195/98863942-5ba79a80-2426-11eb-87c9-82a82ec20f0f.PNG)

## Versions

**App**

- Angular: 10
- Clarity: 4.0.5

**Device:**

- Type: Pc
- OS: Windows 10
- Browser Chrome, Edge

**Comment by Jinnie** [comment]
You need to get the filter definition out of the structure directive `*clrDgHideableColumn` template.
Otherwise you get an out-of-place filter button inside the "show/hide" popover menu too.

https://stackblitz.com/edit/clarity-hideable-filter?file=src/app/app.component.html
