### ISSUE TITLE
How do I close Hamburger menu which is open, from an button click in the page?

### ISSUE THREAD

**Issue by digish777** [vmware/clarity#5292]
How do I close Hamburger menu which is open, from an button click in the page?

**Comment by Jinnie** [comment]
Use the close button on the right:
<img width="369" alt="Screen Shot 2020-11-12 at 6 32 32 PM" src="https://user-images.githubusercontent.com/1798828/98967766-89b7d800-2515-11eb-8ff4-838751d0beba.png">

Also, please use the Github Discussions for questions about the use of Clarity and its components.
