### ISSUE TITLE
Scrolling on parent page is disabled when we close the modal windows.

### ISSUE THREAD

**Issue by AamirSaeedCL** [vmware/clarity#5301]
Description 

The no-scrolling css style auto added after closing the modal windows which disabled the scrolling on parent page.

How to reproduce: 

Have a simple listing page with scrolling enabled on body section. Then open a modal windows by clicking on any menu option or button. When we closed the modal windows, the scrolling on parent page will be disabled. It seems clarity added the `no-scrolling` style on the body which should remove once we close the modal windows.

## Expected behavior

Scrolling should be enabled after closing the modal windows.

**App**

- Angular:  v10
- Clarity:  v4.0.2
 Browser : Chrome

**Comment by gnomeontherun** [comment]
Hello there, do you have a reproduction of this? The modal should remove the scrolling block on close.

**Comment by Jinnie** [comment]
We don't have a reproduction and we've not observed this behavior ourselves. I'm closing this as stale. 
In case you create a stackblitz reproduction, we'll reopen it. If the thread gets later locked by our inactivity bot, you'll have to file a new issue.
