### ISSUE TITLE
clr-combobox - ability to configure the dropdown not to close on select

### ISSUE THREAD

**Issue by IvayloP** [vmware/clarity#5307]
## Summary

Provide a way to configure the clr-combobox whether the dropdown to be closeable on option select.

## Use case

This change will provide an easier interaction with the combobox multi select

## Examples
With `ng-select` `[closeOnSelect]` https://stackblitz.com/edit/ng-select-closeonselect-example?file=src/app/app.component.html

## Workarounds
No workaround at the moment.

**Comment by Jinnie** [comment]
I don't think it needs to be configurable, but a default behavior. Thanks for posting this issue.

**Comment by IvayloP** [comment]
I agree, it makes more sense to be a default behavior, thanks :)
