### ISSUE TITLE
[Icon Request] Icons for VCSA UI installer for vSAN bootstrap

### ISSUE THREAD

**Issue by jazhang** [vmware/clarity#531]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
New icons in VCSA UI installer for vSAN bootstrap

The icons are for claiming ESXi host's disks to create a vSAN datastore. 
1. We'll list all valid disks of the ESXi host and give an icon for each disk: if the disk if flash type, it will be flash disk icon; otherwise it will be normal/other disk type;
2. User can select the disk and do following operations:
- Claim this disk as cache tier in vSAN;
- Claim this disk as capacity tier in vSAN;
- Do not claim this disk (which means this disk won't be used to create vSAN datastore);
- Mark as Flash Disk: The selected disk is not flash type but we can mark it as flash
- Mark as HDD: The selected disk is not HDD type but we can mark it as HDD

We need following icons:
1. vSAN cache tier (vsan-cache-tier)
2. vSAN capacity tier (vsan-capacity-tier)
3. Do not claim disk (do-not-claim)
4. Flash disk (flash-disk)
5. HDD disk (hdd-disk)
6. Normal/Other disk (normal-disk or other-disk) - see row 6 in the attachment

### Actual behavior
Currently there're no usable icons for vSAN bootstrap in VCSA UI installer

### Reproduction of behavior
1. Get a build of VCSA UI installer 2.0 and run the installer;
2. Connect the installer to a host that meet following requirements:
- Get a ESXi host from vSAN patch branch;
- Make sure this host is not managed by a vCenter Server
- Connect the installer 2.0 to this host
- Choose create a new vSAN datastore at select datastore step
- Go to claim disks for vSAN step
- Check icons on this step

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.4

* **OS and version:** Mac | Windows | Linux

* **Browser:** all

**Comment by lil-kim** [comment]
@jazhang  I don't see the attachment (although I think I saw it here or somewhere before). Would you mind reposting the image? That would be helpful. Thank you.

**Comment by lil-kim** [comment]
Closing this issue as these icons were duplicates of a Bugzilla request from another dev: https://bugzilla.eng.vmware.com/show_bug.cgi?id=1828558  
I've discussed w/ @jazhang and added him to the bug.

**Comment by jaffoneh** [comment]
Closing based on Lilia's last comment.
