### ISSUE TITLE
Height and content (message, action buttons) alignment issue with Web component version of Alerts

### ISSUE THREAD

**Issue by git-ram-pal** [vmware/clarity#5311]
## Describe the bug

Web component alerts are not consistent with their heights and also content inside the alerts are also not aligned properly.

![Screenshot 2020-11-18 at 10 43 42 AM](https://user-images.githubusercontent.com/46098781/99487393-41247280-298c-11eb-83b8-80fde7803c78.png)

## Expected behaviour

The expected behaviour is that web component alerts should have consistent height as we see in Angular version of alerts.
Also alerts contents ( message, action buttons, close icon ) should be aligned properly (vertically centered).

## Versions

**App**

- Angular: [10]
- Node: [15.0.0]
- Clarity: [4.0.0]
- WebComponent: [2.5.0]

**Device:**

- Type: [MacBook]
- Browser [chrome, safari]
cc: @amalitsky, @alextsg

**Comment by mathisscott** [comment]
This is fixed for the core web component alerts in 4.0.6.

<img width="1083" alt="Screen Shot 2020-11-18 at 8 39 37 AM" src="https://user-images.githubusercontent.com/2728359/99544248-b3d82280-2979-11eb-9690-e14e64c72427.png">
