### ISSUE TITLE
[clarity/core] Disabled flat button missing style

### ISSUE THREAD

**Issue by andresmgot** [vmware/clarity#5315]
## Describe the bug

I am using the `@clr/core` package in a React app, when adding the properties `action="flat" disabled={true}`, the button loses the "flat" style:

![Screenshot from 2020-11-18 13-53-43](https://user-images.githubusercontent.com/4025665/99533041-86a16980-29a5-11eb-8303-298b1670914f.png)

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to https://stackblitz.com/edit/clarity-core-disabled-flat-button?file=index.tsx

## Expected behavior

When using clarity classes, it uses the proper style:

![Screenshot from 2020-11-18 13-58-06](https://user-images.githubusercontent.com/4025665/99533399-1e9f5300-29a6-11eb-9559-868ac2b66565.png)

## Versions

**App**

- React: ^16.8.0
- Clarity: 4.0.6

**Comment by mathisscott** [comment]
@andresmgot

**Comment by mathisscott** [comment]
@andresmgot 
I think this is "as intended". All the buttons have the same look when disabled. IIRC, this was from the accessibility team and design. If you need one of the button types to look differently, it can be accomplished with a CSS edit

https://stackblitz.com/edit/clarity-core-disabled-flat-button-xxermr?file=style.css

**Comment by andresmgot** [comment]
Thanks for the workaround @mathisscott
