### ISSUE TITLE
Custom properties for disabled buttons are not cascading properly

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#5316]
## Describe the bug

See #5315 

and the workaround stackblitz here: https://stackblitz.com/edit/clarity-core-disabled-flat-button-xxermr?file=style.css

It looks like the way [the custom properties are being set for disabled buttons](https://github.com/vmware/clarity/blob/41de28e5ffe06dbda59b275968ec09a5cba72cb2/packages/core/src/button/base-button.element.scss#L195) breaks the ability for us to update their backgrounds and such with custom property overrides.

In the workaround above, I could access the `--background` css var inside the CSS so I had to override the color instead.

This seems harder than it should be.

This may all be fixed already with @coryrylan 's work on theming: #5284 

Assigning to him to verify if it is still an issue.

**App**

- Angular: [e.g. 6]
- Node: [e.g. 8.10.0]
- Clarity: [4.0.6]

**Comment by coryrylan** [comment]
This is fixed now from https://github.com/vmware/clarity/pull/5567 
demo https://stackblitz.com/edit/clarity-core-disabled-flat-button-c8yzeg?file=style.css
