### ISSUE TITLE
Expanding a node with 1000 children in Tree View is slow

### ISSUE THREAD

**Issue by skpetkov** [vmware/clarity#5317]
## Describe the bug

I have a recursive Tree with large number of nodes. It takes about 3-4 seconds to expand a node with 1000 child elements. While a node is being expanded the whole app freezes and browser is unresponsive to any other user interaction. Performance drops further as more and more nodes are expanded. I also noticed that tree operations are highly dependable on the browser machine (slower machines are heavily affected).

## How to reproduce
Here is a sample app to demonstrate the issue https://clr-recursive-tree-slow-rendering-ks1gtw.stackblitz.io/

Expand any node in the provided sample app. As more nodes are expanded, performance drops further.

## Expected behavior

Better performance with smooth animations. Web app should not freeze while the tree is being expanded.

## Versions

**App**

- Angular: 9.1.9
- Clarity: 3.1.3

**Device:**

- Type: Intel Core i5
- OS: Windows
- Browser Chrome, Firefox, Edge

**Comment by hippee-lee** [comment]
Performance issues are tricky and subjective with out good profiling information. This has been brought up before. See https://github.com/vmware/clarity/issues/3665.

 In general we cannot expect thousands of items to render smoothly without delay or lag, especially on older machines. 

I'm going to close this in favor of the existing issue.
