### ISSUE TITLE
Invisible Input boxes when unfocused

### ISSUE THREAD

**Issue by dan-p-dev** [vmware/clarity#5323]
## Describe the bug

In my web pages, some of my clrInput fields will be invisible unless they have focus. When they have focus, they will have the
blue underline as usual, however the line will be thinner than normal. 

![invisible field](https://user-images.githubusercontent.com/74742379/99730634-672c3e80-2a82-11eb-9f8f-9ecca6c81324.PNG)
![visible when focused](https://user-images.githubusercontent.com/74742379/99730732-8dea7500-2a82-11eb-8cac-72f881a51133.PNG)

There is no consistency as to which clrInput fields are invisible across different pages, however on a given page it will consistently be input fields in a specific location (i.e. if I swap the visible job # field with the invisible lot # field, job # will become invisible and lot # will become visible).

Additionally, if I override the bottom border width, the invisible fields will become visible. However, they are thinner than all the other input fields that were visible before the width change.

I viewed the web page in Chrome and in Firefox. The issue is present in both, but the invisible fields are in different locations in each browser.

## How to reproduce

I don't know. I updated to version 4.0.4 recently from 3.1.5, however I attempted to revert to 3.1.5 and the issue was still present.

## Expected behavior

I would like all my input fields to be consistently visible and the same size.

## Versions

**App**

- Angular: [11.0.2]
- Node: [10.6.3]
- Clarity: [4.0.4]

**Device:**

- Type: [Dell Desktop]
- OS: [Windows 10]
- Browser [Chrome, Edge, Firefox]

**Comment by hippee-lee** [comment]
Without an isolated reproduction it's hard to figure out what is going on here. 
If you can re-create the issue in one of our [starter stackblitzes](https://stackblitz.com/@clr-team) it will help us, help you.

**Comment by dan-p-dev** [comment]
> Without an isolated reproduction it's hard to figure out what is going on here.
> If you can re-create the issue in one of our [starter stackblitzes](https://stackblitz.com/@clr-team) it will help us, help you.

Turns out, that's actually exactly what I needed. I couldn't reproduce it, so I figured it had to be one of my custom styles. I tried each one and discovered where my problem was.

https://clarity-v4-light-theme-yzsy1h.stackblitz.io

`.clr-col-1, .clr-col-2, .clr-col-3, .clr-col-4, .clr-col-5, .clr-col-6,
.clr-col-7, .clr-col-8, .clr-col-9, .clr-col-10, .clr-col-11, .clr-col-12 {
    overflow: hidden !important;
    text-overflow: ellipsis !important;
}`

I made this style because I didn't like how, when the screen gets too narrow, anything I had in a grid would collapse and change the height. If you take a look at the stack blitz, you should notice that the input field bottom border is very slightly thinner than is normal. After you focus on it and leave, it will be thicker again.

It is a very subtle difference, and perhaps it won't be noticeable on your screen. However, in my application, it is going even further and causing some of the input fields to be invisible.

Would this be considered a bug or just a case of bad styling on my side? I'll get rid of my style for now since that's what's causing the issue.

**Comment by bbogdanov** [comment]
Hi @dan-p-dev,

It is definitely not a bug. 

Sometimes when playing around with the code that sets visual changes to a component library there are side-effects that can appear and also a responsibility comes to handle these side-effects inside the application.

Try to follow our [guidelines](https://clarity.design/documentation/forms) I believe you will find the right solution for your case there.
