### ISSUE TITLE
Rich text edit control

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#533]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

It would be awesome to have an integrated rich edit control with options to support bold, italic, bullet lists, number lists, links, etc.

Short of that, perhaps a 3rd party rich text editor could be recommended.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@rongery I am not sure this is a component that should be part of Clarity. Making a recommendation is also difficult because it will depend on the requirements you're looking for.

**Comment by jaffoneh** [comment]
With many rich text edit controls out there and the depth of building something like this as a component while continuing to support editing tools, I am leaning towards not making this a component in Clarity at the moment. Based on that, I am closing this issue. That said, please feel free to add more details if needed and we can discuss further.

**Comment by anil1712** [comment]
@jaffoneh I am trying to show this RTE in our modal but its not rendering that directive.
Is there anything I need to configure in our modal?

FYI: here is the modal repo link.
https://github.com/Ledzz/angular2-tinymce

**Comment by mathisscott** [comment]
@anil1712 
Could you create a [plunkr replicating your issue](https://plnkr.co/uNwwZe) ?

Without a way to see what you are having problems with, we can't help.
