### ISSUE TITLE
Inherit color and cursor for Clarity icons

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#5332]
## Describe the bug

When using the `CdsIcon` component of Clarity Core, we noticed cursor and color inheritance always get lost.

Cursor inheritance is always appreciated in interactive contexts. Having a default color is nice for icon consistency across the board, but in the cases of links, for example, it means we need to manually apply `--color: var(--cds-token-color-action-600)` to the underlying icon, which is something I would expect the icon to take care on its own.

We are switching from Font Awesome to Clarity Icons, and as it was the default behavior of Font Awesome icons, we have to add manual overrides for all icons, and were wondering if it would not be better for Clarity to handle it itself.
If this is not something that needs to be fixed in Clarity Core, do you have any recommendations on how to address this correct?

![cds-icon](https://user-images.githubusercontent.com/113730/100158928-f1a5e100-2e7a-11eb-94c2-b0ad6f1ba0e9.gif)

![cds-icon2](https://user-images.githubusercontent.com/113730/100159105-26b23380-2e7b-11eb-8f2c-40c7e0673224.gif)

## How to reproduce

The link above was produced with the following code, and standard set up of the Clarity CSS files:

```jsx
<p cds-text="body">
  <a href="#" cds-text="link">
    This is a link with <CdsIcon shape="map-marker" solid /> an icon
  </a>
</p>
```

## Versions

- `"react": "16.14.0",`
- `"@clr/core": "4.0.7",`
- `"@clr/react": "4.0.7",`

**Device:**

- Type: MacBook
- OS: Catalina 10.15.7
- Browser: Chrome 
- Version 86.0.4240.183

**Comment by bbogdanov** [comment]
Hi @astorije,

Can you please provide us a stackblitz examples for the cases you shared above?

**Comment by astorije** [comment]
Hi @bbogdanov!
This is my best attempt, let me know if that helps! https://stackblitz.com/edit/react-ts-nizyzw

**Comment by mathisscott** [comment]
Hi @astorije 
We have a bit of an issue on our end with how the icon was set up to "inherit" the color of its parent. It's a quick fix but, for your use case, here is a workaround for now: https://stackblitz.com/edit/react-ts-kpt22u?file=style.css

**Comment by astorije** [comment]
That's interesting, thanks for this, @mathisscott! Would it be worth adding this in the Clarity Core CSS file for links?

Also, any idea how to inherit the cursor?
![cds-icon](https://user-images.githubusercontent.com/113730/100754167-bba3b800-33b8-11eb-8375-8d6ae7c7fe06.gif)

**Comment by mathisscott** [comment]
You could put `cursor: pointer` inside that style block if you want

**Comment by astorije** [comment]
Right, that would address links, but that means we need to manually set it for every icon out there, right? As in there is no way to inherit the cursor of the surrounding block. Is that correct?
You can see that on the second example of https://stackblitz.com/edit/react-ts-nizyzw

**Comment by mathisscott** [comment]
@astorije 
I updated the stackblitz to demo it better. https://stackblitz.com/edit/react-ts-kpt22u?file=index.tsx

You can inherit the cursor of the surrounding block.

**Comment by mathisscott** [comment]
@Shijir 
I'm sending this your way because you're already working on Vol 18 icons. Please take a look at the stackblitz (https://stackblitz.com/edit/react-ts-kpt22u?file=index.tsx). It shows the use case of this issue and dips into the fixes required. You may want to set `--color` to `currentColor` instead of hard-coding it like I did though.

CC: @coryrylan

**Comment by astorije** [comment]
This is really great, thank you so much @mathisscott et al.

I confirm that setting the following in a global CSS stylesheet fixes all our issues, and indeed it would be really great if the base component included this:

```css
cds-icon {
  --color: currentColor;
  cursor: inherit;
}
```

**Comment by astorije** [comment]
Actually, I realize that I am using `--color: currentColor` locally and not `fill: currentColor` which avoids the need for the `!important` in the example.

**Comment by mathisscott** [comment]
@astorije : yep, that's how we'd do it to fix it in the code too. if you're up for another contribution.... 😊

**Comment by astorije** [comment]
Absolutely! I will open a PR today :)
