### ISSUE TITLE
Not properly applied styles for dark-theme

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#5339]
## Describe the bug

clr-icon.is-green, clr-icon.is-success has less priority in dark-theme over the regular style so its brighter color is not applied in dark-theme

## How to reproduce

1.  Go to 'https://stackblitz.com/edit/clarity-v4-dark-theme-6rwcmx?file=src%2Fapp%2Fapp.component.html'
2.  open dev tools and inspect the style of `<clr-icon shape="success-standard" class="is-success"></clr-icon>`
3.  see that the dark-theme color(fill: #61b715;) is overridden by the regular color (fill: #2e8500;)

## Expected behavior

the dark-theme color should be fill: #61b715;

## Versions

**App**

- Angular: [10.0.11]
- Clarity: [4.0.0]

**Device:**

- Type: [PC]
- OS: [windows10]
- Browser [chrome]
- Version [87]

## Additional notes

I am reporting this bug specifically for clr-icon .is-success where the dark-theme style has less priority over the regular style.
If this is a matter of a general method applying styles it might affect other components as well.

**Comment by bdryanovski** [comment]
@iivanovgit thanks for reporting it. We gonna take a look at it.
