### ISSUE TITLE
"Finish" button doesn't change to "Next" when unskipping pages in wizard 

### ISSUE THREAD

**Issue by kars7e** [vmware/clarity#534]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When current page is wizard last page, and action on this page unskips some hidden pages following the current one, "Finish" button should change text to "Next".

### Actual behavior
When current page is wizard last page, and action on this page unskips some hidden pages following the current one, "Finish" button does NOT change text to "Next". Clicking it however works as expected (it moves to following page). Going back also makes it stay at "Next". It seems that the recalculation of text happens only when page is changed, but not when pages are skipped/unskipped.

### Reproduction of behavior
https://plnkr.co/edit/QvxzEJw77tHmuqo0pRBg?p=preview

### Environment details

* **Angular version:** 2.4.1

* **Clarity version:** 0.8.8

* **OS and version:** macOS 10.12.3

* **Browser:** [all ]

**Comment by mathisscott** [comment]
We are presently working on a rewrite/refactor of the Wizard component #156 .

The plan is to release the new wizard in 0.9.0 and we are working to release an alpha for 0.9.0 soon.

Closing this ticket because we are recommending that people use the new wizard.
