### ISSUE TITLE
Make Signposts dynamically reposition if they are obstructed or go out of the window bounds

### ISSUE THREAD

**Issue by BojidarTrenchev** [vmware/clarity#5340]
## Summary

The clr-signpost-content component of the Signpost can be made to dynamically change its position depending on whether this component goes beyond the browser window size, e.g. when it contains too much text or when the window is resized by the user. The automatic repositioning can be turned on or off by the developer.

## Use cases
For instance, let's say that we have a signpost content component with some text and right-middle positioning. The user, then resizes the browser window and thus makes its width smaller. Now some part of the signpost content box is beyond this width and the text is not readable. The signpost could detect this situation and automatically set the signpost content's position to be left-middle. If the browser window is enlarged the signpost content can return to its original position.

Another use case is when the user opens the signpost in a smaller window, the signpost content should automatically find the most suitable position to increase its visibility.

## Potential improvements
This change would improve the usability and the responsiveness of the signpost component and make it easier for the users to read it.

## Workarounds
Currently, implementing this feature requires workarounds and is not very scalable. The current signpost component has to wrapped in a custom component which does the position checking and manipulation and if there are many signpost components in a project already, all of them have to be updated. For example, a custom code can be written to check on click of the signpost icon, take the signpost content component and check if it fits in the window, if not find a better position and rerender the component.

**Comment by bbogdanov** [comment]
Hi @BojidarTrenchev and thank you for sharing your idea! 

We are aware that the signpost component positioning can be improved and we aiming to solve it with smart popovers #1757.

Because we are moving our focus to `@clr/core` this might not be solved in `@clr/angular`. @gnomeontherun can share more info where this fits in our roadmap.

**Comment by Jinnie** [comment]
As Bogdan mentioned, this issue will be resolved as part of the #1757 effort. The latter was recently closed for Clarity Angular, as something we prefer to do in Clarity Core and avoid effort duplication.
