### ISSUE TITLE
Icon for timeline-view

### ISSUE THREAD

**Issue by gerneck** [vmware/clarity#5348]
## Summary

The purpose of the icon is to indicate the switch to a timeline-view. The same is currently possible with the icons view-list, view-cards and tree-view.

## Use case

Switching between different representation of same data.

## Examples

A similar icon is the tree-view icon. But the timeline-view icon should be without indention.

**Comment by bbogdanov** [comment]
@lil-kim Can you please take a look at this one?

**Comment by lil-kim** [comment]
Hi @gerneck 
Would you please attach an image of what the timeline looks like? A google image will suffice. Thank you.

**Comment by gerneck** [comment]
It should give a hint what I can expect when switching to a view which uses the Clarity Timeline Component

Clarity Timeline Component
![Clarity Timeline](https://user-images.githubusercontent.com/75367966/100925820-d1150100-34e2-11eb-9c6b-8a6b4f41be37.png)

Suggestions
![Timeline icon proposal 1](https://user-images.githubusercontent.com/75367966/100925945-fbff5500-34e2-11eb-89e7-932c2e44fdbc.png)
![Timeline icon proposal 2](https://user-images.githubusercontent.com/75367966/100925958-ff92dc00-34e2-11eb-9ba7-fc2e30b8d4fa.png)
