### ISSUE TITLE
Datagrid count should differentiate between plural and singular based on count

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#535]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
If the datagrid is showing objects of type "foobar", the count at the bottom should show:
0 foobars
1 foobar
2 foobars
N foobars

### Actual behavior
If the datagrid is showing objects of type "foobar", the count at the bottom currently shows:
0 foobars
1 foobars  <--- this is wrong
2 foobars
N foobars

### Reproduction of behavior
https://embed.plnkr.co/O9Kz1h/

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.X

* **OS and version:** MacOS 10.12

* **Browser:** Tested in Chrome (but likely all)

**Comment by Jinnie** [comment]
Hi @joshjohnson72,

In my opinion pluralization should not be of concern to the framework itself. You could use some pluralization directive in the footer to achieve this. Here's an example with the Angular2 built-in experimental ngPlural directive.

```
<clr-dg-footer [ngPlural]="users.length">
      <template ngPluralCase="0">No items</template>
      <template ngPluralCase="1">1 item</template>
      <template ngPluralCase="other">{{users.length}} items</template>
</clr-dg-footer>
```

Check this plunker to see it in action: https://plnkr.co/iEyWlc7DJQ2by8RVdmkx

**Comment by jaffoneh** [comment]
@joshjohnson72 based on the discussion, what @Jinnie mentioned is accurate. Since this is a localization-related issue, it is on the app itself to do it. Closing based on that.
