### ISSUE TITLE
Date-picker control: Support for work week numbers

### ISSUE THREAD

**Issue by karan-kang** [vmware/clarity#5351]
## Summary

It would be great if the date picker control can support showing the work week number in the left most column for ease selection.

- What is the change?
Adding an extra column (leftmost) in each row.
- Why should it go in Clarity?
Most line of business applications use work weeks for scheduling, so this would make the date picker more complete.
- Does this change impact existing behaviors? If so how?
No, this is display only change. We can make the visibility of work week optional to keep this backward compatible.
- If this change introduces a new behavior, is this behavior accessible?
Yes

## Examples

Sample UX with clarity date picker:
![image](https://user-images.githubusercontent.com/1234394/100927663-2f29f000-34b3-11eb-9fe6-1622506ad66a.png)

Other projects:

- https://www.telerik.com/kendo-react-ui/components/dateinputs/datepicker/week-num-column/
- https://bbbootstrap.com/snippets/blue-themed-date-picker-date-range-and-week-number-61366925
- https://www.jqueryscript.net/time-clock/Week-Picker-Bootstrap-4.html

## Workarounds

None at the moment

**Comment by Jinnie** [comment]
This should definitely go through Accessibility team first, as I don't see this feature in the W3C examples:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/datepicker-dialog.html
@chlane

**Comment by Jinnie** [comment]
Just found this to be duplication of #5273
Please follow the above for updates

**Comment by chlane** [comment]
Added to the accessibility team's internal database for Clarity Accessibility Issues
