### ISSUE TITLE
Detail pane toggle icon grayed out after row update

### ISSUE THREAD

**Issue by tran2** [vmware/clarity#5352]
## Describe the bug

After row update, the toggle icon is no longer blue.

## How to reproduce

https://stackblitz.com/edit/clarity-v406-detail-pane-refresh?file=src%2Fapp%2Fapp.component.ts

1.  Go to the stackblitz https://stackblitz.com/edit/clarity-v406-detail-pane-refresh?file=src%2Fapp%2Fapp.component.ts
2. Click on >> open detail pane
3. Click on Load New Data
4.  See that >> is no longer blue and icon has changed to <<
![image](https://user-images.githubusercontent.com/7945885/100930832-dce2d200-34a6-11eb-9f46-e943f1ab0a9b.png)

## Expected behavior

I would expect that after using trackBy id and refresh data the toggle still stays on. 

## Versions

**App**

- Angular: [10.0.1]
- Node: [10]
- Clarity: [4.0.6]

**Device:**

- Type: [MacBook]
- OS: [Catalina]
- Browser [chrome]
- Version [86.0.4240.198]

**Comment by mathisscott** [comment]
The datagrid isn't set up to preserve state across actions like reloading data. The expected behavior would be for the detail pane to close when new data is loaded into the datagrid.

[Here is a stackblitz](https://stackblitz.com/edit/clarity-v406-detail-pane-refresh-y8t9ye?file=src%2Fapp%2Fapp.component.ts) that demonstrates how that can be accomplished.

**Comment by tran2** [comment]
@mathisscott thank you for the stackblitz, I ran into this issue while trying out the detail pane closing:

1. Open detail pane for id 3
2. Filter for 4 from the string filter
3. See that detail pane is closed and only 4 is being shown
4. Click on the toggle to see detail pane for 4
5. Clear filter
6. Now filter again for 3
7. See that there's an error in the console 
![image](https://user-images.githubusercontent.com/7945885/101224760-d1311000-364c-11eb-9e09-6e20b76c5041.png)

Added youtube vid just in case you need more info:
[![clarity detail pane](http://img.youtube.com/vi/WU2QRey1nUQ/0.jpg)](http://www.youtube.com/watch?v=WU2QRey1nUQ "clarity detail pane")
