### ISSUE TITLE
Flipping an icon seems to not be working

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#5355]
## Describe the bug

It seems the `flip` attribute of the Clarity Core `cds-icon` element has no effect on the `next` branch.

<img width="221" alt="Screen Shot 2020-12-02 at 3 50 01 PM" src="https://user-images.githubusercontent.com/113730/100940665-60f88200-34c6-11eb-8d1e-903e8ebd3047.png">

## How to reproduce

I did not do any research or anything, just came across this when running the latest Core Storybook, and figured I would report it back.

## Expected behavior

This was taken from https://clarity.design/storybook/core/?path=/story/components-icon-stories--flip:

<img width="180" alt="Screen Shot 2020-12-02 at 4 10 18 PM" src="https://user-images.githubusercontent.com/113730/100940645-4e7e4880-34c6-11eb-8af9-ab8acb514db4.png">

**Comment by mathisscott** [comment]
Thanks for the report, @astorije. We will take a look at it.
