### ISSUE TITLE
Datalist changes width when focused

### ISSUE THREAD

**Issue by akate1** [vmware/clarity#5357]
## Describe the bug

Datalist is changing its width when focused.

## How to reproduce

1.  Go to https://clarity.design/documentation/datalist#examples 
2.  Go to basic example or any other example
3.  Click inside datalist or type anything in datalist
4.  See the changing width of datalist

## Expected behavior

Datalist width should not change on focus

## Versions

**Device:**

- OS: Windows
- Browser : chrome Version 86.0.4240.198 (Official Build) (64-bit)
- Version : clr-ui: 4.0.7

## Additional notes
This issue was not present in clr-ui : version 3

**Comment by bdryanovski** [comment]
@akate1 thanks for reporting this, we have opened an issue related to this #5269

So I'm closing this one in its favor
