### ISSUE TITLE
Signpost content cut off when signpost present in a stack view label

### ISSUE THREAD

**Issue by WhiteLord** [vmware/clarity#5358]
## Bug description

Long signpost content is being cut off, when the signpost is present in a stack view label, or content, in that matter.

## How to reproduce

1. Use the example stack view on [Clarity website](https://clarity.design/documentation/stack-view)
2. Add a basic [singpost](https://clarity.design/documentation/signposts) in the `<clr-stack-label>`
3. Add a new paragraph to the signpost content that contains a ["lorem ipsum" text](https://www.lipsum.com/) or a random long sequence of characters.
4. Observe that the content of the signpost is cut off

![clarity-stack-block-signpost](https://user-images.githubusercontent.com/20514574/101013156-88a22580-356c-11eb-9593-debf00ab4586.gif)

## Expected behavior

The user should be able to see the contents of the signpost and not see the signpost being cut off.

I see a few possible solutions to this problem. 
- One that may be hard to implement includes expanding the signpost content screen **outside** the containing `clr-stack-view`. 
- Another may include creating a dynamic calculation based on including component (in this case the `clr-stack-view`). If the `signpost` content section height is bigger than the one of the `stack view`, create a `max-height` property that is correspondent to the height of the containing (`stack view` in our example) section.

## Versions

**App**

- Angular: [9.1.12]
- Node: [10.19.0]
- Clarity: [3.1.13]

**Device:**

- Type: [MacBook]
- OS: [Catalina]
- Browser [FF]
- Version [82.0.3]

## Additional notes

Example Stackblitz: https://clarity-v3-stack-view-signpost.stackblitz.io

**Comment by bbogdanov** [comment]
Hi @WhiteLord,

It is not a good practice to nest clickable items. One of the reasons is a11y support. 

A possible workaround will be to use `stopPropagation` when you click the sign post trigger, but I do not recommend you go in this direction.

Have you tried solving your issue with [tooltips](https://clarity.design/documentation/tooltips)? 

Also, the stackblitz example is broken.

**Comment by WhiteLord** [comment]
Tooltips unfortunatelly, could not be used as a solution here, as we're following UX design. 
Yes, I now see that Stackblitz is broken for some unobvious reason, but the example is really mainstream and could be reproduced easily. 
Thanks for taking a look at this!

**Comment by gnomeontherun** [comment]
This is the relative positioning issue that clips the signpost. See #5061 and #1757, but the best solution is when we have a Clarity Core signpost that won't have this issue since this would require a major overhaul of our popovers (signposts, tooltips, etc) in Clarity Angular.

Bogdan is right about the nested click targets, which is an accessibility and UX usability problem. Nothing we change can solve that problem, and best suggestion is to consider an alternative to this UX.

**Comment by WhiteLord** [comment]
I see. Well then, we're sticking with what we have. It's too-late to ask for a UX rework now, and since you guys have this on the roadmap, eventually we'll get it once it's released.

**Comment by bbogdanov** [comment]
Related to #5340
