### ISSUE TITLE
Datagrid Detail Pane used in Modal -> Close button missing.

### ISSUE THREAD

**Issue by Dreamerset** [vmware/clarity#5360]
## Describe the bug
Detail pane close button on top right corner is missing.

## How to reproduce

Implement Datagrid with Details Pane enabled component in modal screen.

1.  Go to modal with Datagrid and Detail Pane.
2.  Click on '>>' to open details for random row from the grid.
3.  See if "x" closing detail pane button is present.

## Expected behavior

Detail pane close button on top right corner is present .

## Versions

**App**

Angular CLI: 9.1.12
Node: 10.15.1
OS: win32 x64
Clarity: 
    "@clr/angular": "^3.1.3",
    "@clr/core": "^3.0.0",
    "@clr/icons": "^3.1.3",
    "@clr/ui": "^3.1.3",

**Device:**

- Type: PC
- OS: win32 x64
- Browser Chrome Version 87.0.4280.66 (Official Build) (64-bit)

**Comment by bdryanovski** [comment]
Hey @Dreamerset can you provide a reproducible Stackblitz demo - I can't reproduce your issue locally

**Comment by Dreamerset** [comment]
Excuse the delay.
Couldn't reproduce it either in Stackblitz - https://clarity-datagrid-in-modal.stackblitz.io/
Must be local setup issue to find.
