### ISSUE TITLE
Combobox auto-complete list doesn't reset itself when losing focus

### ISSUE THREAD

**Issue by RockLikeAmadeus** [vmware/clarity#5361]
I'm using a combobox control in a pretty typical way. As expected, when I start typing in the text entry field of the dropdown, the dropdown list narrows itself to items which match my search criteria.

But if I click the focus away from the combobox, or close the modal dialog which contains the combobox, even though the text entry is emptied, the dropdown list still seems to be filtered by my most recently entered text. The only way to reset the list seems to be to enter some text and then delete it. No matter what tricks I use to try and force the list of options to reset, it still seems to be filtered by the (now removed) text I last entered.

![Screen Shot 2020-12-03 at 5 17 43 PM](https://user-images.githubusercontent.com/5766618/101105733-94511480-358b-11eb-9e35-23b2f313b1ca.png)
![Screen Shot 2020-12-03 at 5 18 05 PM](https://user-images.githubusercontent.com/5766618/101105769-a9c63e80-358b-11eb-91e5-5d6171a0449d.png)
![Screen Shot 2020-12-03 at 5 18 11 PM](https://user-images.githubusercontent.com/5766618/101105775-ad59c580-358b-11eb-9b5a-d64fb5378ba3.png)
![Screen Shot 2020-12-03 at 5 18 18 PM](https://user-images.githubusercontent.com/5766618/101105782-b0ed4c80-358b-11eb-8b9d-a1bac664aa75.png)

**Comment by mathisscott** [comment]
@alhampton9 
I've [tried reproducing this and cannot](https://stackblitz.com/edit/clarity-v4-light-theme-3j2x11?file=src%2Fapp%2Fapp.component.html). Can you make a reproduction?

**Comment by RockLikeAmadeus** [comment]
Thanks Scott, sure thing, when I get a moment in the next couple of days
I'll put one together.

-Alec

**Comment by Jinnie** [comment]
Probably related to this: https://github.com/vmware/clarity/issues/5275
Which was fixed 2 releases ago, I think. 
Make sure you're using the latest release for the Clarity version you use.

**Comment by Jinnie** [comment]
I reproduced it on the website, with the "My State" single-selection demo. I guess we're clearing the input on blur but not clearing the selection model.

**Comment by RockLikeAmadeus** [comment]
Thanks Ivan. In my case, it does seem to have been the package version. I
was exactly 2 releases behind -_-
