### ISSUE TITLE
Combobox popover is not repositioned after selection

### ISSUE THREAD

**Issue by VladimirAnaniev** [vmware/clarity#5364]
## Describe the bug

Now that the Multi Combobox popover is not closed after each selection, if we select or deselect many items and new rows are added to the input field, the combobox is not being moved and starts covering the content or is left detached from the field.

## How to reproduce

https://stackblitz.com/edit/combobox-popover-not-repositioned

1.  Resize the window to 450px
2. Select all three items in the combobox
3. See popover is covering content
4. Close popover and open it again (the input should first be focused - #5344)
5. Deselect all three items
6. See Popover is now detached from the combobox input.

https://streamable.com/nx58cu

## Expected behavior

Combobox popover does not cover the selected items and is displayed right below the search field

## Versions

**App**

- Angular: 11
- Clarity: 4.0.7

**Device:**

- Type: MacBook
- OS: MacOs
- Browser Chrome
- Version 87

**Comment by Jinnie** [comment]
Not sure if this can be addressed with the current smart popovers design. But it's worth investigating if it's possible to retrigger the layouting process with the container-provided offset, which now only happens on init.
