### ISSUE TITLE
Clarity site takes 8 seconds to load

### ISSUE THREAD

**Issue by ezekeal** [vmware/clarity#537]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
[Site](https://vmware.github.io/clarity/) should load in around 1 second

### Actual behavior
[Site](https://vmware.github.io/clarity/) loads in around 8 seconds
Time to interactive is around 6 to 7 seconds

### Reproduction of behavior
* reload page and move mouse over button to see hover state
* With metrics: 
    1. open dev tools and go to `timeline` tab
    2. right click on refresh button and select `Empty cache and hard reload`
    3. view timeline

### Environment details

* **OS and version:**  OSX 10.11.6

* **Browser:** Chrome 56

**Comment by mathisscott** [comment]
The issue here is the gitbug widget on the top right of the page. The script in the iframe freezes onload of the webpage altogether. There are workarounds for this that we should investigate.
