### ISSUE TITLE
Customized trigger point for datagrid hide/show column action

### ISSUE THREAD

**Issue by neospio** [vmware/clarity#5376]
## Summary

We keep receiving user's requests on how to open the datagrid hide/show column pannel. As in the previous version(before swtich to clarity), we had an obvious toggle button at the top of the grid. To fulfill the user's request, we want to have a customized appoach to be able to trigger the hide/show column panel from an external element event. 

The requirement should be a common need for applications which need to aglin with the exiting UX design. The optional customized trigger could add some flexibility to the datagrid component.

## Use case

The customized trigger could be attached to a new defined element outside the datagrid. And use #id to bind to each other.

When the customized trigger element has been clicked, the hide/show column pannel can be displayed round the customized trigger element.

E.g.
![image](https://user-images.githubusercontent.com/7780988/101891655-4d8f9a00-3bdd-11eb-9fbd-cc5b180b8eaf.png)

## Examples

No related examples found.

## Workarounds

No workaround found.

**Comment by bbogdanov** [comment]
Hi @neospio! 

Here is a [quick stackblitz](https://stackblitz.com/edit/datagrid-toggle-columns-button?file=src/app/app.component.html) example I created to show this can be done for all columns in a single click. The same way you can create a button for each column in the datagrid.

Let me know if that helps!

**Comment by neospio** [comment]
> Hi @neospio!
> 
> Here is a [quick stackblitz](https://stackblitz.com/edit/datagrid-toggle-columns-button?file=src/app/app.component.html) example I created to show this can be done for all columns in a single click. The same way you can create a button for each column in the datagrid.
> 
> Let me know if that helps!

Thanks for your response! The example is straightforward and easy to understand. However, if we want to have the similar functionality with Clarity's built-in hide/show column pannel(toogle all columns in the grid dynamically), we need to re-implement the same widget again.

If the built-in hide/show columns pannel can but reused by providing a trigger API/endpoint, that would be really helpful.

Thanks!

**Comment by bbogdanov** [comment]
Hi @neospio, 

At this stage, this is the only way to create a custom column toggle panel. The team expects this to be more flexible with the `core` implementation of the datagrid that will come in the next couple of months. 

Closing the issue as solved.
