### ISSUE TITLE
Pagination component

### ISSUE THREAD

**Issue by hammerlink** [vmware/clarity#538]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

There is a pagination integration in the datagrid. But this is only available to the datagrid itself. Could it be possible to get this component standalone?

The reason I want this is that I want a custom styled table, because the datagrid is not very customizable.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.0

* **OS and version:** Windows 10 / Ubuntu

* **Browser:** Chrome

**Comment by reddolan** [comment]
@hammerlink have you considered using Clarity buttons to accomplish what you are trying to do? I imagine you would be able to have buttons get the next set of records in a dataset or return a previous set.

**Comment by reddolan** [comment]
@hammerlink pinging you again for my question above ^

**Comment by reddolan** [comment]
@hammerlink we are closing this issue for now. If you still need this feature, please respond back answering the above questions
