### ISSUE TITLE
Responsive design for dropdowns in header > header-actions

### ISSUE THREAD

**Issue by sswaroop-cont** [vmware/clarity#5380]
## Summary

_Summary the request and address the questions as appropriate._

- What is the change?
Add responsive behaviour for dropdowns inside header-actions present in header
- Why should it go in Clarity?
currently clarity supports header navigation with only links but not dropdowns. Header can consist of both links and dropdowns. 
- Does this change impact existing behaviors? If so how?
there is no current responsive behavior for dropdowns inside headers. 
- If this change introduces a new behavior, is this behavior accessible?
Yes

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_
No

**Comment by sswaroop-cont** [comment]
https://stackblitz.com/edit/angular-tu6gyw?file=angular.json

**Comment by sswaroop-cont** [comment]
Do we have any update on this?

**Comment by gnomeontherun** [comment]
Header actions are not considered navigation, so we don't have responsive navigation built-in. At the moment, the application will have to decide what to do with the actions based on their own needs. We don't have any demos showing multiple dropdowns in the header like this, which might require different treatment based on what the actions are for.

@yuxin-ux @colinreedmiller We don't have any guidance on this specific use case, but I wanted to get this on your radar as an ask. I think there are other possible patterns, depending on exactly what the use cases are.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
