### ISSUE TITLE
Extra space getting displayed in grid

### ISSUE THREAD

**Issue by VedikaGujarBiomni** [vmware/clarity#5383]
Hi All,

I am currently using latest **Clarity version 0.13.11**, with **Angular 6**.
I am facing a minor issue, while using data grid.
When I try using both Pagination and Selection batch action both with data grid, there is an empty space getting created after the end of the rows.
This happens when I use both pagination and action bar, if I skip any of them it works perfectly fine.
Below is the code

**SCREENSHOT**
![image](https://user-images.githubusercontent.com/76034646/102186046-f2de9280-3ea9-11eb-8a73-a654f38d0481.png)

**CODE**
![image](https://user-images.githubusercontent.com/76034646/102187062-69c85b00-3eab-11eb-85f9-3719749e41b1.png)

Can you please help me with this issue.

Thanks and Regards,
Vedika.Gujar

**Comment by bbogdanov** [comment]
Hi @VedikaGujarBiomni! 

We dropped the support for versions below v2, but If you provide us a stackblitz example we will be happy to take a look and advice you on how to proceed.

**Comment by VedikaGujarBiomni** [comment]
Hi @bbogdanov 

Thank you for your reply. :) 

Please find the [stackblitz example](https://stackblitz.com/edit/extra-space-in-grid-vedika?file=src/app/app.component.html).

Thanks 
Vedika Gujar

**Comment by bbogdanov** [comment]
For some reason, something sets `style="height: ...` on the `clr-datagrid` tag and that's why there is an empty space.

```css
/* CSS */

clr-datagrid {
  height: auto !important; /* important is necessary to overwrite the inline added style */
}
```

Unfortunately, I can't find any code on our side that does this in the published packages, but this should unblock you to continue further. 

I would encourage you if possible to update to our latest versions. This issue doesn't exist there.

**Comment by VedikaGujarBiomni** [comment]
Hi @bbogdanov ,

Thank you for your reply.
We are not using the latest version of Clarity, because we are using VCloud Director version 9.7, which supports Angular 6 and Clarity 0.13.11

Adding above CSS solves the issue, but it creates small problem in pagination.
Data Grid height gets resized on every page, and its not constant.
So if we have just 2 records on the last page, height will reset accordingly.

**First Page**
![image](https://user-images.githubusercontent.com/76034646/102607177-d6fb1b00-414d-11eb-9969-807bf1439d59.png)


**Last Page**
![image](https://user-images.githubusercontent.com/76034646/102607118-c21e8780-414d-11eb-9bd2-c572ae88b68b.png)


I have added Example 1,Example 2 and Example 3 in [this](https://stackblitz.com/edit/extra-space-in-grid-vedika?file=src/app/app.component.html).
If you check the last page, you'll get to know the difference.
