### ISSUE TITLE
Checkbox 'glow' is cut off in overflow-hidden containers

### ISSUE THREAD

**Issue by ezekeal** [vmware/clarity#539]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Checkbox should show glow on all sides when focused in a container with overflow hidden

### Actual behavior
Checkbox glow does not show on all sides in a container with overflow hidden (clarity modals for example)
![checkbox issue](http://i.imgur.com/1TUtn4f.png)

### Reproduction of behavior
* place a checkbox inside a containing div with overflow hidden
  * (I changed the surrounding div on your checkbox example page)
* click and unclick the checkbox
* observe checkbox glow

### Environment details

* **OS and version:** OSX 10.11.6

* **Browser:** Chrome 56

**Comment by adityarb88** [comment]
Hi @ezekeal: I don't this is an issue because thats the way `overflow: hidden` works. You need to add a padding to the container div to make sure that the outline style is not clipped.

**Comment by ezekeal** [comment]
It is because the element needs to make room for its own visuals. The case of placing the checkbox in a clarity modal is a good one. You expect that the visual of the checkbox will not be mangled.

**Comment by adityarb88** [comment]
@ezekeal: Sorry about that. There is one case when the checkbox outline does get cut off in the modal (when you use forms in a grid in a modal). Let me talk to our UX team and check if we can add a padding to the modal body. For now you might have to wrap the `form` in a wrapper and add a padding to that. WIll reopen the issue.

**Comment by ezekeal** [comment]
I made a plunker to illustrate the differences between the clarity UI and the base UI. The modal is fine. It's the checkbox that needs to make room for it's outline.
[example](https://embed.plnkr.co/bx87lVyy5jUifcXWX99A/)

**Comment by Radu-Dunarentu** [comment]
any update on this? or a workaround? tried with input:focus {outline:0;} and it didn't work.
