### ISSUE TITLE
CdsCheckbox indeterminate not working in React

### ISSUE THREAD

**Issue by ashleyryan** [vmware/clarity#5397]
## Describe the bug

using the `indeterminate` property in the React wrapper `CdsCheckbox` doesn't work

## How to reproduce

Stackblitz:

https://stackblitz.com/edit/react-ts-hraphp?file=index.tsx

1. Create a checkbox with refs on both the `CdsCheckbox` and `input` components
2. apply `indeterminite` to the input ref in `useEffect` (after the nativeElement promise has resolved)
3. Nothing happens

## Expected behavior

You can't apply the `indeterminate` attribute on the input directly in the JSX, you must do it via a ref.  You'll see how this works in the stackblitz with an unwrapped input, but nothing happens to the Clarity Checkboxes. 

## Versions

**App**

- React: 16.14
- Clarity: 4.0.7 (I also tried with v5)

## Additional notes

I dug into the code and confirmed that the input `ref` and `this.inputControl` from [checkbox.element.ts](https://github.com/vmware/clarity/blob/next/packages/core/src/checkbox/checkbox.element.ts#L56) are the same component. The mutation observer is being added to the element, but the callback is never being hit.

I tried adding a MutationObserver manually in my stackblitz and struggled to get that to fire on a vanilla input either though, so this may be an issue with react.

**Comment by ashleyryan** [comment]
I also discovered that I'm not able to set the input as checked directly on the element (or via a ref) either.

**Comment by mathisscott** [comment]
@ashleyryan 
Thanks for reporting this issue. Good news is I'm replicating this issue with no problem. The stackblitz helped. The bad news is this issue is not easily solved. It's going to take some investigation. I've tried a few passes at low-hanging fruit fixes but need to dive into the architecture.

CC: @coryrylan

**Comment by ashleyryan** [comment]
Cory did reply to me on slack and said he thinks he knows what the problem is and will look into it after the holiday

**Comment by coryrylan** [comment]
Fixed, this will go out in our next release https://github.com/vmware/clarity/pull/5431
