### ISSUE TITLE
core: disabled state colors for cds-button

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#5403]
## Describe the bug

The `flat` variant of `cds-button`, when disabled, has incorrect text color, and gets some background interaction on hover:

![flat-disabled](https://user-images.githubusercontent.com/113730/102681765-311dcf80-4192-11eb-96ef-202c9ba506bd.gif)

## How to reproduce

You can see the code for the above screencast at https://stackblitz.com/edit/react-ts-js9w2u?file=index.tsx

## Expected behavior

I would expect a flat button to not react on hover at all when disabled, and have white text color.

## Version

Clarity (both `@cds/core` and `@cds/react`): 5.0.0-next.0

**Comment by mathisscott** [comment]
@Shijir : What is our status on this?

**Comment by coryrylan** [comment]
Looks like this was fixed with the theme fixes in the 5.0 release 
![Screen Shot 2021-01-26 at 10 27 15 AM](https://user-images.githubusercontent.com/2021067/105873438-19234200-5fc1-11eb-9f8d-0664cd76cf5f.png)

**Comment by astorije** [comment]
I noticed that, thank you!
Quick question though, was it on purpose that:
- text on disabled state is dark gray on gray, as opposed to white on gray (as it was on disabled solid before)?
- outline disabled has changed? I think the previous way worked better

/Cc @jaybellew1 @sbaldwa-cht

**Comment by coryrylan** [comment]
@astorije ah yes I see the diff comparing to clr-ui. I'll check on if they are supposed to be synced as one disabled style now or each different. Comparison this is clr-ui


![Screen Shot 2021-01-26 at 12 55 39 PM](https://user-images.githubusercontent.com/2021067/105891092-d5870300-5fd5-11eb-9df6-2c80482856b9.png)

**Comment by astorije** [comment]
Hey @coryrylan, it looks like #5518 fixed this issue so I think it can be closed.

Given the following buttons:

<img width="470" alt="Screen Shot 2021-02-05 at 7 30 23 PM" src="https://user-images.githubusercontent.com/113730/107061261-f3a6ed00-67a5-11eb-8ae0-f93d0223cd22.png">

We correctly get the following now:

<img width="466" alt="Screen Shot 2021-02-05 at 7 29 24 PM" src="https://user-images.githubusercontent.com/113730/107061341-0e796180-67a6-11eb-8eac-9d34025f595a.png">

So that's much better!

However, would you be open to adjusting the solid-disabled text color like the following? Disabled text is rather hard to read at the moment:

<img width="473" alt="Screen Shot 2021-02-05 at 7 30 07 PM" src="https://user-images.githubusercontent.com/113730/107061594-61531900-67a6-11eb-9932-d3d9cf76f341.png">

**Comment by coryrylan** [comment]
@astorije hey yeah lets leave this issue open and I'll update the title

**Comment by coryrylan** [comment]
Closing, working with design on updating our base action color tokens so this will be addressed with that effort.
