### ISSUE TITLE
Placeholder of combobox is not visible

### ISSUE THREAD

**Issue by belyan** [vmware/clarity#5410]
## Describe the bug

Placeholder of combobox is not visible.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-combobox?file=src%2Fapp%2Fapp.component.html

## Expected behavior

Placeholder of combobox should be visible.

## Versions

**App**

- Angular: 10.0.14
- Node: 10.17.0
- Clarity: 4.0.8

**Device:**

- Type: MacBook Pro
- OS: Mac OS High SIerra
- Browser Chrome
- Version 87

## Additional notes

The issue is duplicated by:
https://github.com/vmware/clarity/issues/4943

**Comment by bdryanovski** [comment]
@belyan thanks for reporting this - it seems that we (I in this case) forgot to backport it to v4. 

It will be resolved in the next release.

**Comment by bdryanovski** [comment]
The fix is merged and will be released soon.
