### ISSUE TITLE
Tooltip is cut off inside data grid with details open

### ISSUE THREAD

**Issue by kirilmicev** [vmware/clarity#5425]
## Describe the bug
I have datagrid with tooltip which gets cut off when Detail Pane is open 

https://i.imgur.com/on9AL8l.png
## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

Tooltip should be visible 

## Versions

**App**

- Angular: 10.0.7
- Node: 6.14.4
- Clarity: 3.1.5

**Device:**

- Type: [MacBook]
- OS: [iOS]
- Browser [chrome, safari]

## Additional notes

_Add any other notes about the problem here._

**Comment by bdryanovski** [comment]
This is duplicate - so I'm closing it in favor of https://github.com/vmware/clarity/issues/4891
