### ISSUE TITLE
Link visited colour is preventing hover colour from displaying

### ISSUE THREAD

**Issue by grahamford** [vmware/clarity#5432]
## Describe the bug

The order of the CSS styling for links is currently `link`, `hover`, `active`, `visited`.
https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/utils/_reboot.clarity.scss

The hover colour doesn't show for visited links because the `visited` state is defined last.
The order should be `link`, `visited`, `hover`, `active`.

## How to reproduce
Stackblitz complains that it encountered errors with ngcc each time I try to create a demo

## Expected behavior

The hover colour should display for links even if they are visited

## Versions

**App**

- Angular: 11.0.5
- Node: 14
- Clarity: 4.0.7

**Device:**

- Type: MacBook
- OS: Big Sure
- Browser Firefox
- Version 84.0.1

## Additional notes

_Add any other notes about the problem here._

**Comment by bdryanovski** [comment]
@GrahamFord thanks for reporting this - I gonna make some test to see are they any side-effects from changing the order and may push a fix by the end of the week
