### ISSUE TITLE
Export focus / focus-trap related directives

### ISSUE THREAD

**Issue by sheguloves** [vmware/clarity#5436]
## Summary

Export focus / focus-trap related directives

Since more and more website need to support VPAT and Clarity includes many directives which are implementations for VPAT support. Others can use them instead of repeat them.

## Examples

If I want to implement a customized dropdown list component and it need to be VPAT support, then I can use focus-trap to catch focus and use key-focus / key-focus-item to make dropdown items focusable and support keyboard event.

## Conclusion

Export focus / focus-trap related directives will reduce many duplicated work on VPAT.

**Comment by gnomeontherun** [comment]
Hello, the focus trap and related things are not something we are currently considering to make public. They weren't designed for general purpose consumption and aren't documented well, so its likely they might not work as expected in some use cases.

There are at least two options: 

1. You could clone the focus trap directives from Clarity and use them in your project. That way you can also update or change behaviors as needed.
2. Angular has several accessibility features in the CDK, including a focus trap. https://material.angular.io/cdk/a11y/overview

Closing as something we aren't considering at the moment.
