### ISSUE TITLE
Deep tree with components in nodes

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#544]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Hi team,
When tree nodes are nested inside ng components the tree logic for expand/collapse fails, as it expects direct `<clr-tree-node>` descendants, while the components add intermediate dom elements, which are not accounted for.

The use case:
(see plunker below for simplified demo)
A tree that can have 3 types of nodes. One type is simple data, the other is a group of simple data elements, the third can either have simple, and/or group children. The root of the tree can host any/all of the three types. As we don't want to repeat the group and simple data html code on all three levels, we want to have them extracted in components.

### Actual behavior
<img width="275" alt="screen shot 2017-03-02 at 10 43 23 am" src="https://cloud.githubusercontent.com/assets/1798828/23499549/371725c4-ff35-11e6-8aa0-ffc34e331c6f.png">

The tree structure is rendered correctly, but for all nodes of second level or more, sub-tree folding (expand/collapse) does not work

### Reproduction of behavior
https://plnkr.co/uQjBHY

### Environment details

* **Angular version:** 2.4.8

* **Clarity version:** 0.8.8

* **OS and version:** OS X

* **Browser:** Tested with Chrome

**Comment by bertofer** [comment]
You can do it by specifying your child-item to projectAs the clr-tree-node (`ngProjectAs='clr-tree-node'` as attribute when using the child-item). 

I had the same problem when trying to do a recursive tree. Have a look at [this issue](https://github.com/vmware/clarity/issues/487)

**Comment by Jinnie** [comment]
Thanks a lot, @bertofer 😃 
This seems a pretty good solution.
Closing this issue as duplicate of #487.
