### ISSUE TITLE
btn-group class affects inner buttons' on-focus style due to its { overflow: visible } style property

### ISSUE THREAD

**Issue by imonikaimonika** [vmware/clarity#5446]
## Describe the bug

btn-group class affects inner buttons' on-focus style due to its { overflow: visible } style property

Not particularly an accessibility issue, the focus of the buttons inside a btn-group does work, 
but it is not styled properly.

<img width="1444" alt="Screenshot 2021-01-14 at 13 00 25" src="https://user-images.githubusercontent.com/77442222/104588995-e8aee000-5671-11eb-9790-a8773c9d2df2.png">

## How to reproduce

Refer to the clarity documentation for Button Group and reproduce there by  focusing on the examples with a "tab".
Observe the curly style of a button when focused, which should be a rectangle instead: 
https://clarity.design/documentation/button-group 

## Expected behavior

The style of a focused button should be a rectangle.

## Local fix

Locally, until this bug is resolved,
I have fixed it by overwriting clr's style for the inner buttons under a btn-group with
`{ overflow: hidden }
`
## Versions

**App**

- Angular: [e.g. 6]
- Node: 14
- Clarity: [e.g. 0.12.5]

**Device:**

- Type:  MacBook
- Browser  chrome

**Comment by bdryanovski** [comment]
I could confirm that this is reproducible.

**Comment by royling** [comment]
I'll submit a PR to fix this soon.
