### ISSUE TITLE
[website] Core Component alert website page shows a modal

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#5447]
## Describe the bug

When you navigate to the Core Component -> Alert Page you see a modal that cannot be dismissed

## How to reproduce

1. Build website (branch `next`)
2.  Open the Core Component -> Alert Page
3.  There's a modal (not closable) that blocks the website

## Expected behavior

Work as https://next.clarity.design/web-components/alert/#placement

## Versions

**App**

- Clarity: [sha1 0bc553b6b]

**Comment by mathisscott** [comment]
@hippee-lee
