### ISSUE TITLE
Unable to set icon alias

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#545]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
After adding alias:
`ClarityIcons.alias({"user": ["person"]});`
Use it in shape attribute:
`<clr-icon shape="person"></clr-icon>`

### Actual behavior
info icon instead and error messages in console:
> 'person' is not found in the Clarity Icons set.

### Reproduction of behavior

https://plnkr.co/4ClCqL

### Environment details

* **Angular version:** 2.4.8

* **Clarity version:** 0.8.8

* **OS and version:** OS X

* **Browser:** Chrome

**Comment by Shijir** [comment]
@Jinnie I am looking into this issue. I don't think the problem lies in setting the alias, but in loading `ClarityIcons` as a module. If you see what is inside the chrome web inspector tool, you might see `Systemjs` error.

**Comment by Jinnie** [comment]
Thanks @Shijir,
I've first hit this issue in my project (clarity seed 0.7.x manually updated to 0.8.x), although together with another issue. But I wanted to clear the problems one by one, and I also can't reproduce the second in plunker. 
I'll mention it as a possible clue, not as something to be resolved in this case. So, the problem was that trying to add alias for some icons looked OK (like "user") and for others triggered error, which was something like "the icon you are trying to set alias to does not exist in Clarity". I hit this with "application", "window-max". 
I have workarounds (like not using aliases 😃), but this is documented and should be working out of the box. 
I am also not exactly sure where do I need to set the alias, so it will be active, and I set it in the component constructor, although I've tried to pull it forward to the app module, and the result is still the same.

Best regards!

**Comment by Jinnie** [comment]
Btw, this error is not produced if you open the plunker in edit mode and run in there.
I first wondered how I may have missed it, but it only appears in the preview mode (or whatever it's name is)
Strange...

**Comment by Shijir** [comment]
@Jinnie thanks for providing additional information. I produced an error in the clarity-seed's `systemjs` version when I tried to import `ClarityIcons`. It works fine when loaded in `script` tag. So I am investigating why it's throwing runtime errors when I import `ClarityIcons` in the root module as you did in your plunkr. The error logged in the web inspection tool doesn't give me a decent clue atm.

**Comment by Shijir** [comment]
if you are receiving this error, `the icon you are trying to set alias to does not exist in Clarity`, try loading the `technology` shapes first like this:
 
```
import "./shapes/technoloyg-shapes";
```

**Comment by Jinnie** [comment]
Thanks for that, I'll give it a try.

Digging a little more in my project configuration - I see that clarity-icons are loaded in the scripts section of the angular-cli.json
I guess this was pre-configured in the seed project.

Then I directly try to import and use them in the Component where I need them.

**Comment by Shijir** [comment]
@Jinnie btw, everything is working just fine in clarity-seed's angular-cli version. The error is occurring when you try to import `ClarityIcons` in the component file and you are using `systemjs`.

**Comment by Shijir** [comment]
@Jinnie, I forgot to check something obvious. So I looked into the systemjs mapping config and set that up. And the error is gone. This is what my current systemjs mapping looks like

```

<script>
    (function (global) {

        // packages tells the System loader how to load when no filename and/or no extension
        var packages = {
            'app': {main: 'index.js', defaultExtension: 'js'},
            'clarity-angular': {main: 'clarity-angular.umd.js', defaultExtension: 'js'},
            'clarity-icons': {main: 'clarity-icons.min.js', defaultExtension: 'js'},
            'rxjs': {main: 'Rx.js', defaultExtension: 'js'},
            '@angular/core': {main: 'bundles/core.umd.js', defaultExtension: 'js'},
            '@angular/compiler': {main: 'bundles/compiler.umd.js', defaultExtension: 'js'},
            '@angular/common': {main: 'bundles/common.umd.js', defaultExtension: 'js'},
            '@angular/forms': {main: 'bundles/forms.umd.js', defaultExtension: 'js'},
            '@angular/http': {main: 'bundles/http.umd.js', defaultExtension: 'js'},
            '@angular/platform-browser': {main: 'bundles/platform-browser.umd.js', defaultExtension: 'js'},
            '@angular/platform-browser-dynamic': {
                main: 'bundles/platform-browser-dynamic.umd.js',
                defaultExtension: 'js'
            },
            '@angular/router': {main: 'bundles/router.umd.js', defaultExtension: 'js'}
        };

        var config = {
            <!-- @if NODE_ENV='dev' -->
            map: {
                'clarity-angular': 'node_modules/clarity-angular',
                'clarity-icons': 'node_modules/clarity-icons',
                'rxjs': 'node_modules/rxjs',
                '@angular/core': 'node_modules/@angular/core',
                '@angular/common': 'node_modules/@angular/common',
                '@angular/compiler': 'node_modules/@angular/compiler',
                '@angular/platform-browser': 'node_modules/@angular/platform-browser',
                '@angular/platform-browser-dynamic': 'node_modules/@angular/platform-browser-dynamic',
                '@angular/http': 'node_modules/@angular/http',
                '@angular/router': 'node_modules/@angular/router',
                '@angular/forms': 'node_modules/@angular/forms'
            },
            <!-- @endif -->
            packages: packages
        };
        System.config(config);

    })(this);

</script>

```

**Comment by Jinnie** [comment]
@Shijir thanks a lot.
I really appreciate how much time you put in this.
It may be due to misconfiguration on my project then. I've always had some doubts about upgrading manually the 0.7.x seed to 0.8.x libraries. Maybe I will have to set-up a new seed and port my code to it.
Thanks again!
