### ISSUE TITLE
Icon request: Digital Signature

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#5451]
## Summary

Icon to represent digital signature.
- What is the icon?
   Pen, Fountain-Pen
- What does the requested icon signify?
   Open Signature Pad where the user can provide his/her digital signature.

## Use case
   Digital sign some document / some object.

## Examples
Material Icons, Font Awesome
<img width="88" alt="2021-01-15_12h27_18" src="https://user-images.githubusercontent.com/311619/104719630-0e4cef80-572d-11eb-8407-8285b98ca209.png">

<img width="58" alt="2021-01-15_11h32_23" src="https://user-images.githubusercontent.com/311619/104717884-528ac080-572a-11eb-8867-5f10cd60a9df.png">

<img width="51" alt="2021-01-15_11h33_39" src="https://user-images.githubusercontent.com/311619/104717886-53235700-572a-11eb-8a22-c71fe4971f5e.png">

<img width="56" alt="2021-01-15_11h37_31" src="https://user-images.githubusercontent.com/311619/104717888-53bbed80-572a-11eb-9b94-4d373263c91a.png">

<img width="82" alt="2021-01-15_11h37_59" src="https://user-images.githubusercontent.com/311619/104717889-53bbed80-572a-11eb-8550-5fe00648763a.png">

<img width="70" alt="2021-01-15_11h38_12" src="https://user-images.githubusercontent.com/311619/104717891-54548400-572a-11eb-8fca-04a9220c90d7.png">

## Alternatives
 
<img width="75" alt="2021-01-15_12h09_07" src="https://user-images.githubusercontent.com/311619/104718036-8c5bc700-572a-11eb-97f7-3c616a13af7e.png">

<img width="61" alt="2021-01-15_12h09_20" src="https://user-images.githubusercontent.com/311619/104718039-8c5bc700-572a-11eb-8a20-71e8f59a4fb4.png">

**Comment by gnomeontherun** [comment]
@lil-kim Here is an icon request to consider
