### ISSUE TITLE
CdsTag is clickable by default [React]

### ISSUE THREAD

**Issue by ashleyryan** [vmware/clarity#5455]
## Describe the bug

By default, with no additional properties `CdsTag` behaves like a button, even without the `clickable` property.

In addition, adding a `closable` property, does not render an X like expected.

## How to reproduce

Stackblitz: https://stackblitz.com/edit/react-ts-9sxe8z?file=index.tsx

## Expected behavior

Tags should render without clickable behavior by default.

"Closable" tabs should render with an X

## Versions

**App**

- Clarity: cds/core and cds/react 5.0.0-rc.1

**Comment by mathisscott** [comment]
@jeeyun : since you are in this area of the code already, could you take a look?

**Comment by ashleyryan** [comment]
I just realized that I believe this is the expected behavior and you have to add `readonly` if you *don't* want it clickable.
