### ISSUE TITLE
Datagrid fixed height gets broken once the user changes page size

### ISSUE THREAD

**Issue by tonyganchev** [vmware/clarity#5456]
## Describe the bug

When you have a clarity data grid with fixed height (in pixels or percent) and the datagrid is paged, whenever the user changes the page size the grid resizes to a different height (same as needed to exactly fit the new page size).

From this point on the grid can never get back to it intended fixed height.

## How to reproduce

You can see the following stack blitz example: https://stackblitz.com/edit/clarity-datagrid-broken-height

0. I've set 100 items per page as the default and everything is fine.
1. Change the page size to 50 - and the layout breaks - the grid expands vertically to fit all 50 rows.
2. Change the size to 10 - now the grid is smaller than it's original fixed size.

If you change the default page size to 10 you see that there is leftover space beyond the tenth element. If you try switching to 5 elements the grid shrinks in height to fit exactly 5 rows.

## Expected behavior

Datagrid height remains fixed no matter what page size the user picks.

## Versions

**App**

- Angular: tested with 10.0.11 and 11.0.5
- Node: N/A
- Clarity: 4.0.8

**Device:**

- Type: PC
- OS: Win 10
- Browser: 
  - Opera 73.0.3856.329
  - Chrome 87.0.4280.141
  - New Edge 87.0.664.75
  - Firefox 84.0.1

**Comment by tonyganchev** [comment]
On further digging, the issue seems to be related to the height reset happening on page change. The handler for size change (https://github.com/vmware/clarity/blob/e28c89b74aad11aeb861ca5cd4a569d9953e8b96/packages/angular/projects/clr-angular/src/data/datagrid/render/main-renderer.ts#L71) triggers `resetDatagridHeight()`
https://github.com/vmware/clarity/blob/e28c89b74aad11aeb861ca5cd4a569d9953e8b96/packages/angular/projects/clr-angular/src/data/datagrid/render/main-renderer.ts#L167-L170
This is when the size set on the grid is lost. If I replace the empty string with the fixed size as originally intended all is good.

**Comment by tonyganchev** [comment]
Seems that if I strictly follow the example from the clarity docs and define the fixed height in a class based on the grid's parent container all works as expected: https://stackblitz.com/edit/clarity-datagrid-broken-height-workaround. Basically instead of specifying `height="600px"` on the `<clr-datagrid />` itself I had to have a CSS class defined based on the clr-datagrid being part of a wrapping container with specific class:
```
.fixed clr-datagrid {
  height: 600px;
}
```
... and then ...
```
<div class="fixed">
   <clr-datagrid>
   ...
   </clr-datagrid>
</div>
```
The specific issue can be considered resolved, but this design is not intuitive and ant the very least has to be called out explicitly in the docs.

**Comment by bdryanovski** [comment]
@tonyganchev thanks for open this issue, we gonna take a look at it ...
