### ISSUE TITLE
docs: broken links on Get Started/Introduction

### ISSUE THREAD

**Issue by ghost** [vmware/clarity#5457]
Hi everyone!
I've found a bug on [Introduction Page](https://next.clarity.design/get-started/). 

When clicking on: 
1. [Getting started with Clarity Core using our Web Components](https://next.clarity.design/angular/components/web-components/get-started.html) 
2. [Getting started with Clarity Angular using our Angular Components](https://next.clarity.design/angular/components/angular-components/get-started.html)

you get 404 pages because:
1. redirects to https://next.clarity.design/angular/components/web-components/get-started.html instead of https://next.clarity.design/web-components/get-started/
2. redirects to https://next.clarity.design/angular/components/angular-components/get-started.html instead of https://next.clarity.design/angular-components/get-started/

To reproduce open https://next.clarity.design/get-started/ and then click on those links otherwise, when trying to open those broken links in a new tab or new window you don't get 404 pages, but [starting page](https://next.clarity.design/) and the menu isn't collapsing - which you will experience when opening links above directly. This I'm not sure how to fix. 

I would be happy to fix the documentation. Any tips would be useful.

**Comment by bdryanovski** [comment]
@macieyn thanks for point this out ;)

**Comment by gnomeontherun** [comment]
This is fixed on https://clarity.design/get-started/. Closing as resolved.
