### ISSUE TITLE
Datagrid: Exception thrown when keeping the detail pane open after re-emitting datagrid data

### ISSUE THREAD

**Issue by ConnerEnders** [vmware/clarity#5459]
## Describe the bug

If the datagrid's data comes from an observable, and the data is updated while the detail pane is open (through a form in the detail pane), the `[(clrIfDetail)]` value needs to be re-set to keep the detail pane open to the same item.

In doing so, an exception is thrown: `Error: ExpressionChangedAfterItHasBeenCheckedError`

## How to reproduce

[Stackblitz Example](https://stackblitz.com/edit/clarity-detail-pane-bug?file=src/app/app.component.ts)

1.  Open a detail pane for any item in the datagrid
2.  Edit input (optional) and submit form
3.  See the exception in the console
4.  Try all 3 behaviors and repeat

I have included 3 behaviors:

1. Do not touch the `clrIfDetail` value after submitting the form (this throws an exception, which is probably expected)
2. Set the `clrIfDetail` value to null after submitting the form (this does not throw an exception, but closes the detail pane)
3. Set the `clrIfDetail` value to the updated version of the datagrid row object (also throws an exception)

## Expected behavior

It is very possible that this is just a misuse of `rxjs` on my part, but I would hope there is a solution to keep the datagrid detail pane open even after the observable data source of the datagrid emits updated data, without errors.

## Versions

**App**

- Angular: 11.0.9
- Node: 7?
- Clarity: 4.0.9

**Device:**

- Type: Macbook
- OS: Mac OS
- Browser: Chrome
- Version: 87

**Comment by Jinnie** [comment]
Hello, @ConnerEnders 

In order to be able to preserve state (selection, panel, etc) between calls, we need to be able to identify unique records in your data. For this, the datagrid needs a trackby function, similar to this:
in template
```
	<clr-dg-row *clrDgItems="let entity of entities | async; trackBy: trackBy" .....
```
and in controller:
```
  trackBy(index, item) {
    return item.id;
  }
```
Check this updated example. It should be working fine:
https://stackblitz.com/edit/clarity-detail-pane-bug-5459?file=src%2Fapp%2Fapp.component.ts
