### ISSUE TITLE
Clarity change viewbox of svg's when using clarity-icons

### ISSUE THREAD

**Issue by rubiktubik** [vmware/clarity#546]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I have a dashboard application which is using clarity as the ui-framework.
In this application a use a custom angular2-module which includes svg charts.
I wanted to add the clarity icons which needed the two entries in the angular-cli.json

- "../node_modules/@webcomponents/custom-elements/custom-elements.min.js",
-  "../node_modules/clarity-icons/clarity-icons.min.js"

My charts should work fine and i should see the clarity icons.

### Actual behavior
When i add the "custom-elements.min.js" clarity seems to change the viewBoxes of my svg's in my custom charts module.

### Reproduction of behavior
https://plnkr.co/edit/MNh01jN1hgos3aTliGto

if you remove:
`<script src="https://unpkg.com/@webcomponents/custom-elements/custom-elements.min.js"></script>`

from index.html the svg is displayed correctly!

### Environment details

* **Angular version:** 2.0.X
2.4.3
* **Clarity version:** 
0.8.8
* **OS and version:** 
Windows 10
* **Browser:** [Firefox 51.0.1 | Edge 38.14393.0.0 ]

Works fine in Chrome 56.0.2924.87

**Comment by mathisscott** [comment]
@rubiktubik : One issue I see is that you have an unnecessary space in the `shape` attribute of your icon. So if you change `<clr-icon shape=" dashboard">` to `<clr-icon shape="dashboard">`, the info icon goes away. 

You should also specify a color in your CSS (#fff?) so that the icon doesn't appear blue. It's picking up the blue color because it's wrapped inside a link.

**Comment by mathisscott** [comment]
@rubiktubik : This looks to me like a browser issue with SVGs in general. In MS Edge, the rectangle is being cut off. But the rectangle is positioned oddly inside the viewbox and the svg is left to its own devices to determine its width. So the svg element is doing double the effort of trying to figure out its width and height as well as applying viewbox. From my experience, it's easier to put the svg inside a containing div so it only has to worry about sizing to its container.

I'm not sure what custom-elements is doing that is interfering here. But if using a container doesn't suffice, it may be worth it to file a bug on their project.

**Comment by rubiktubik** [comment]
I found this issue on the custom-elements project:
https://github.com/webcomponents/custom-elements/issues/14
Using alpha4 and rc1 version solves the problem!

This versions are not on npm yet. So i needed to download it from github manually.

**Comment by mathisscott** [comment]
Awesome. Thanks for following up on that, @rubiktubik.

We will need to make sure we update when these packages are available through NPM.

**Comment by jaffoneh** [comment]
Looks like 1.0.0-rc.3 has been published: https://www.npmjs.com/package/@webcomponents/custom-elements

**Comment by mathisscott** [comment]
We should make sure this gets into planning this week or next. Thanks for the heads up.

On Apr 4, 2017, at 5:54 PM, Jehad Affoneh <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like 1.0.0-rc.3 has been published: https://www.npmjs.com/package/@webcomponents/custom-elements<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.npmjs.com_package_-40webcomponents_custom-2Delements&d=DwMCaQ&c=uilaK90D4TOVoH58JNXRgQ&r=fTP1U0GY81PhDMWNG5UbxoWqeCcP89bIAA4eQJ2VcGk&m=-Zq5HncaxY18FHei46utb7x-eLevYvdR87m4wAsQs60&s=jXDowItpw9H1YGFuRqe_O37iUQLJ-HMbUbeGFgjIuUk&e=>
