### ISSUE TITLE
[website] Checkbox page issue

### ISSUE THREAD

**Issue by mcosta74** [vmware/clarity#5462]
## Describe the bug

Core Checkbox page is empty

## How to reproduce

1.  Build the website from `next` branch
2.  Go to 'Core Components --> Checkbox page`
3.  The page is Empty

## Expected behavior

The page should not be empty https://next.clarity.design/web-components/checkbox/

## Versions

**App**

- Clarity: sha1 `94e1f4b35`

**Comment by gnomeontherun** [comment]
The page is live on the main website without a 404, see https://clarity.design/core-components/checkbox/. If you have more details with the latest site please let us know, otherwise closing as resolved.
