### ISSUE TITLE
clrAlertClosed input is not respecting value change

### ISSUE THREAD

**Issue by nightwolfdev** [vmware/clarity#5468]
## Describe the bug

The alert component's **clrAlertClosed** input is not respecting a value change. 

## How to reproduce

[https://stackblitz.com/edit/clarity-v4-light-theme-nspfiu](https://stackblitz.com/edit/clarity-v4-light-theme-nspfiu)
[https://clarity-v4-light-theme-nspfiu.stackblitz.io](https://clarity-v4-light-theme-nspfiu.stackblitz.io)

1.  When the app first loads, the alert is closed.
2.  Click the Test button.
3.  In the console, you'll see that **this.closed** went from true to false.

This was working fine in v2 but when I moved up to v4, I noticed that was no longer the case.

## Expected behavior

The alert did not open. It should have opened because its input value changed from true to false.

## Versions

**App**

- Angular: 10
- Node: 12
- Clarity: 4

**Device:**

- Type: Any
- OS: Any
- Browser: Any
- Version: Any

**Comment by nightwolfdev** [comment]
Hello, just checking in to see if this could be looked at? This is impacting applications that utilize the alert component, which is not appearing when it should be. Thank you!

**Comment by hippee-lee** [comment]
Hi @nightwolfdev - I'm sorry, this hasn't been investigated yet. It may just be a lifecycle issue but I'm not sure without debugging the alert code. As a workaround, you could add an `*ngIf` to the alerts tied to the open state for each one. [Here](https://stackblitz.com/edit/clarity-v4-light-theme-lgdeqq?file=src/app/app.component.html) is a fork of your stackblitz.
