### ISSUE TITLE
Grid Row Detail component (new)

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#547]
### Description
When a Datagrid row has additional data or details that can be shown when interacting with the row. This is also known as Master Detail or Master Child in some situations. 

### Use Cases Under Consideration
- expansion
- custom views loaded into details area
- override row data with custom view
- details per cell
- dynamic loading
- open multiple rows at a time
- loading design
- empty state design

#### Basic
- use when a row has additional data that you want the user to see or interact with
- a grey caret on the left side of a grid row indicates it has details and can be expanded
- hovering over a caret will change the background to hover-grey
- rows without a caret do not have details and are not expandable
- a user can expand multiple rows

![basic](https://cloud.githubusercontent.com/assets/1858226/23519856/15ac1f9e-ff3e-11e6-80e2-8a3d40cc535a.png)

#### Details Expanded
- after clicking the caret, the row will expand showing any details within
- details are indented on the left, aligning with the first column of content
- details area background color is white
- default details content is text
- the details space can be loaded with any custom view
- expanding a row will push following rows down, making the grid vertically longer

![details expanded](https://cloud.githubusercontent.com/assets/1858226/23519864/1f5005ce-ff3e-11e6-8bc3-2b4c178d3f1e.png)

#### Mixed Row Selectors
- row expander (caret) can be paired with the Single Row Selector or Single Row Action
- recommended that row expander be between other controllers and first data cell
- it is not recommended to include all three row controllers, it takes up a lot of space

![mixed row selectors](https://cloud.githubusercontent.com/assets/1858226/23519874/24d5b7d2-ff3e-11e6-8496-ab1049c1bf69.png)

#### Fixed Height Grid
- with a fixed-height grid, expanding a row will push following rows down
- users can scroll down to see the additional rows

![fixed height grid](https://cloud.githubusercontent.com/assets/1858226/23519889/2c482176-ff3e-11e6-9833-bc146d68c234.png)

#### Dynamic Loading
- with large amounts of details for a row or rows, content can be loaded dynamically
- details are retrieved when the user interacts with the row expander
- Loading state (above) will be displayed until details come back from the server

#### Loading State
- when a user clicks the row expander, a loading spinner will show until details are displayed

![loading state](https://cloud.githubusercontent.com/assets/1858226/23519898/365dd7fa-ff3e-11e6-9f06-88c0ce3937f1.png)

#### Empty or Error State
- displays when details fail to load
- default message provided but can be overridden with a custom message

![empty state](https://cloud.githubusercontent.com/assets/1858226/23519906/3e1d9a3e-ff3e-11e6-8a5f-004b92fa3ca3.png)

*Documentation is subject to change*

**Comment by chunghha** [comment]
Please consider to take into account arrays in JSON object (which is typical from server's service response) to be displayed in grouping mode like ui-grid's grouping feature.
http://ui-grid.info/docs/#/tutorial/209_grouping

Without the above UX input (I mean with current version of datagrid), if I want to display arrays in JSON such as this to a datagrid:
{
"name":"John",
"age":30,
"cars":[ "Ford", "BMW", "Fiat" ]
}
I need to write double for-loop to assign arrays to plain rows so datagrid displayed as

name       age      car
John        30        Ford
John        30        BMW
John        30        Fiat

But, desired datagrid would be

(expand)   name    age    car
      +  ............. John     30      
    .......................................     Ford
    .......................................    BMW
    .......................................     Fiat

I hope I explained well what I request with this master/child change. From the above UX input, I don't see how use-case of "car" column in my example can be displayed. If better to request as new, I will open one for "Datagrid Grouping" instead.

**Comment by reddolan** [comment]
@youdz heads up ^

**Comment by halachliyskid** [comment]
Hi Red,

This looks like a mix of a hierarchical datagrid and a master/detail pattern. 
Actually there are multiple places where we need both at the same time.

Example: In VSAN there is a datagrid with hosts which expand to see their disks groups. Upon selecting one of the groups, details about the disk group are shown below the grid (the details consist of a datagrid with the disks in the disk group). You will find some more examples below.

Hierarchical datagrids
In general we have two use cases for them in products such as vSphere, VSAN, SRM, VR, VUM, etc.:
* Grids with two types of objects. In these hierarchical datagrids we need to preserve the columns. Take for example a grid that of Clusters and Hosts - they have absolutely the same columns. These columns might be Compliance status, Date of last Compliance Check, etc. Similarly take datastore clusters which expand to reveal the datastores inside - again the columns should be the same. The VSAN example I gave in the beginning also falls under this category.
Preserving the columns allows me to filter/sort across all rows. In your proposal the columns are lost
* Sections. Rows in the datagrid may have to be split into several sections. Take for example a host's storage adaptor view where the rows are split by model (actually this is a very good example where we need both a hierarchical datagrid and a master/detail). Or in other cases rows are split by type - in VUM there are several types of baselines which are split in this way.

Master/Detail
The proposed design only works for "light-weight" detail content such as a few key-value pairs, or something similar.
In products such as vSphere, VSAN, SRM, VR, VUM, etc. we need to have more complex details. There are multiple cases where the details view has tabs - check out the Storage adapters of a host, or the Storage devices of a host, or the Virtual switches of host, or the Vmkernel adapters of a host, etc. The examples are really too many to enumerate.
In the majority of the other cases (where tabs are not needed in the detail view) the detail view consists of a full datagrid.
I don't see how these complex controls are going to fit within the proposed design.

I can provide more examples and details if needed.

Thanks,
Deyan

**Comment by youdz** [comment]
Closed by #700.

**Comment by s-rusev** [comment]
Not sure if this is the right place to ask but if we have an extended row and then we change the datagrid's data provider is there a way to keep our row extended?

**Comment by youdz** [comment]
To identify a row as being the same even with a full data refresh, you want to use `*ngFor`'s `trackBy` option. See https://angular.io/api/common/NgForOf for more info. This means the iterator will know it still is the same object, and will not destroy and rereate the row but rather keep it in its current state.

Note that we support the exact same option and syntax for `*clrDgItems`.

**Comment by AlexeyKub** [comment]
How to use "details per cell" in the datagrid row?

**Comment by sbabich-nix** [comment]
@reddolan ,
Where can I find template example for **Rows with and without detail** from this image?
![](https://cloud.githubusercontent.com/assets/1858226/23519856/15ac1f9e-ff3e-11e6-80e2-8a3d40cc535a.png)
In documentation page there is only example when **all** items can be expanded.

**Comment by youdz** [comment]
@sbabich-nix: There is an example of how to do this on StackOverflow: https://stackoverflow.com/questions/49074726/conditional-clarity-datagrid-expandable-rows

I hope this answers your question.

**Comment by ags504** [comment]
Hi @reddolan 
#### 

> Dynamic Loading
> * with large amounts of details for a row or rows, content can be loaded dynamically
> * details are retrieved when the user interacts with the row expander
> * Loading state (above) will be displayed until details come back from the server

Where can I found an example or can you give me the sample code for this?

**Comment by hippee-lee** [comment]
@ags504 - our docs have implemtation details about the loading use case you describe here: https://clarity.design/documentation/datagrid/expandable-rows

In the future, please ask implementation questions on stackoverflow. Thanks.
