### ISSUE TITLE
Update Accordion content

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#5475]
## Describe the bug

Accordion content needs to be updated to reflect the most current [design spec](https://www.figma.com/file/rWE0j6DRp0LR8euGGJ97Dz/Core-Accordion?node-id=22%3A425).

At the time of filing this issue, the Anatomy section should **not** be implemented. `

## Expected behavior

Accordion content will match with the spec.

**Comment by bdryanovski** [comment]
I don't think that this is valid anymore?

@hippee-lee @gnomeontherun

**Comment by hippee-lee** [comment]
@bdryanovski - correct.
