### ISSUE TITLE
Combine button documentation into a single page. 

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#5476]
## Describe the bug

There are three documentation pages for Button, Icon Button and Inline Button. They need to be combined into a single page and under Button and the content should be updated with the [current design spec.](https://www.figma.com/file/JPEKbovrfAz5IYX3ZJfcMU/Core-Button?node-id=138%3A0) 

At the time of filing this issue, the Anatomy section should **not** be implemented. `

## Expected behavior

1. Button content will  be updated
2. Icon button page will be removed
3. Inline button page will be removed

**Comment by bdryanovski** [comment]
I could do that but I'm not sure that this is still part of the design-spec 

@hippee-lee @gnomeontherun
