### ISSUE TITLE
Update Alert content structure

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#5477]
## Describe the bug

Alert content needs to combine the status and placement content under the correct type h3 element. 

there should be two h2's (##) in the markdown: Usage & Types
Under types there should be three h3's (###) Standard, App-Level & Lightweight Alerts with the relevent content grouped under each alert type.

**Comment by yuxin-ux** [comment]
Actually, the current implementation is correct. The 3 types Standard, App-Level & Lightweight Alerts are introduced in the Type section first. Then type is expanded to their own H2 section because of their distinct usage guidelines.

**Comment by yuxin-ux** [comment]
The "Size" section within "Standard alerts" was originally part of the Anatomy section. This is the only type that is offered in two sizes (Default, compact). I will recommend it as a H3, following "Status" and "Placement" until we bring in the Anatomy section.

**Comment by bdryanovski** [comment]
Can we close this now? 

@hippee-lee
