### ISSUE TITLE
Update Tags docuemntation content

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#5479]
Tags content needs to be updated to align with the [latest design spec](https://www.figma.com/file/5Bc8WraulEfarU14IaDyvj/Core-Tags?node-id=253%3A206).

Note: The anatomy section is not part of this update so it can be left out.

**Comment by bdryanovski** [comment]
I can't find the spec design document - it seems it's moved or expired - so is this valid still?

@hippee-lee
