### ISSUE TITLE
https://v4.clarity.design is down (DNS issue?)

### ISSUE THREAD

**Issue by mayesgr** [vmware/clarity#5481]
https://v4.clarity.design isn't displaying in my browser on my desktop or phone (using a separate network).

![Screen Shot 2021-01-21 at 3 30 39 PM](https://user-images.githubusercontent.com/1157057/105425246-d4348f80-5bfd-11eb-9bd3-1502dd625f0a.png)

**Comment by gnomeontherun** [comment]
We are working on the cutover, and having issues to get it deployed. For now, you can view https://v3.clarity.design which has almost everything that v4 has.

**Comment by gnomeontherun** [comment]
Is up now! https://v4.clarity.design/
