### ISSUE TITLE
Support for CSS Component in Clarity 5 ?

### ISSUE THREAD

**Issue by kumar-tadepalli** [vmware/clarity#5484]
## Summary

_Summary the request and address the questions as appropriate._

- What is the change?
I could not find the CSS component in Clarity 5 documentation. Our current application is on clarity 4 and using CSS component approach. Is the CSS component support removed? 
- Why should it go in Clarity?
The CSS way is much useful to customize the form like showing radio inline.
- Does this change impact existing behaviors? If so how?
How can we migrate to Clarity 5 if the code is using CSS component styling?
- If this change introduces a new behavior, is this behavior accessible?

## Use case

_Provide some specific details about how this change would improve your application and use case._

## Examples

_Are there any examples in other projects that demonstrate this feature or enhancement?_

## Workarounds

_Is there a workaround for this feature at the moment, even if it is less than ideal?_

**Comment by gnomeontherun** [comment]
We have not removed the CSS options, but they are documented within the Angular Components section. If you are using v4, you may wish to continue to use the https://v4.clarity.design documentation site as needed. Nothing has or will change for Clarity UI, but Clarity Core is the long term path for allowing applications to use Clarity in a framework agnostic way.
