### ISSUE TITLE
Combobox "No results" translation

### ISSUE THREAD

**Issue by alexpichler99** [vmware/clarity#5486]
## Summary

It seems like the text's provided by Clarity for the combobox can't be translated. I'm having the issue, that I want to change the text for "No results" in the combobox to another language/text. It would be nice to have some input property where you can set the text.

![image](https://user-images.githubusercontent.com/17060999/105477420-1d3e1f80-5ca2-11eb-95fa-2e737a956d30.png)

**Comment by Jinnie** [comment]
Check the internationalization documentation:
https://clarity.design/foundation/internationalization/

Use the `comboboxNoResults` property.
