### ISSUE TITLE
Datagrid Detail Pane with Filter Errors

### ISSUE THREAD

**Issue by tran2** [vmware/clarity#5494]
## Describe the bug
After the reproduce steps, I get error and filter stopped working while working with detail pane. 
![image](https://user-images.githubusercontent.com/7945885/105535629-4fed1580-5cac-11eb-8637-07a6cfa3d689.png)
Video if it helps: https://www.youtube.com/watch?v=WU2QRey1nUQ

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1. Go to https://stackblitz.com/edit/clarity-v410-detail-pane-filter-issue?file=src/app/app.component.html
1. Open detail pane for id 3
1. Filter for 4 from the string filter
1. See that detail pane is closed and only 4 is being shown
1. Click on the toggle to see detail pane for 4
1. Clear filter
1. Now filter again for 3
1. See that there's an error in the console
2. Datagrid stopped working

## Expected behavior

Expect that datagrid still works after above steps.

## Versions

**App**

- Angular: 10
- Node: N/A
- Clarity: 4.0.10

**Device:**

- Type: Mac
- OS: Catalina
- Browser Chrome
- Version: 87.0.4280.141

**Comment by Jinnie** [comment]
Confirmed. It properly closes the detail pane when it's out of scope, but we're missing a detection cycle somewhere.
