### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by siddharth1903** [vmware/clarity#5499]
Could understand from the release notes that IE11 is no longer supported. Would like to know the reason behind this, since microsoft hasn't declared IE11 dead yet... Is this a strategic decision? Our clients are still looking to use IE11 as long as it is supported and we have been using clarity right from 0.11  till 4 now.

**Comment by Jinnie** [comment]
VMware is ending support for IE11:
https://blogs.vmware.com/vsphere/2020/09/end-of-support-for-ie-11.html
based on Microsoft ending support for IE11 in their applications themselves:
https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666

Also, although support for custom elements in IE11 is possible with the use of polyfills, it does not support shadow DOM natively and this might lead to degraded performance. The colleagues working more directly on Clarity Core might want to add or comment more on this perspective.

**Comment by Jinnie** [comment]
Please, reopen in Discussions if you need more information. 
Because of an open Github bug, I am currently not able to convert this issue.
