### ISSUE TITLE
clr-password-container formatting of eye icon broken inside a timeline

### ISSUE THREAD

**Issue by AlicePain** [vmware/clarity#5501]
The password clear text eye icon wraps to a new line and is 36x36px

Use the following code in app.component.html

`<clr-timeline clrLayout="horizontal">
  <clr-timeline-step clrState="success">
    <clr-timeline-step-title><a routerLinkActive="disabled" routerLink="personal-info">Create your account</a></clr-timeline-step-title>
    <clr-timeline-step-description>
      <div class="clr-row">
        <div class="clr-col-sm-12 clr-col-md-6 clr-col-lg-6">
          <h3>Primary administrator</h3>
          Please enter information
            <clr-password-container>
              <label>Password *</label>
              <input clrPassword name="password" required />
            </clr-password-container>
            <clr-password-container>
              <label>Confirm password *</label>
              <input clrPassword name="confirmpassword" required />
            </clr-password-container>
        </div>
      </div>
     </clr-timeline-step-description>
  </clr-timeline-step>
</clr-timeline>
`

**Comment by Jinnie** [comment]
You code throws errors when I am trying to reproduce it.

Please, use the template provided by the "New Issue" page.
We need to know what versions you are using and we need a working stackblitz example (links to starter projects for different Clarity versions are provided in the new issue template)

I will close this one, so you can go through the New Issue template again.
