### ISSUE TITLE
Helper text (clr-control-helper) text color has contrast that is too low

### ISSUE THREAD

**Issue by eemt** [vmware/clarity#5505]
## WCAG Guideline

"Helper Text" (clr-control-helper) for the various input controls has contrast that is too low for Web Content Accessibility Guidelines (WCAG) standards. 

Color contrast should minimally be 4.5:1 
(AA, https://www.w3.org/WAI/WCAG21/quickref/#contrast-minimum)
preferrably 7:1
(AAA, https://www.w3.org/WAI/WCAG21/quickref/#contrast-enhanced)

## How to reproduce

1.  Create a Clarity input control with helper text.
2.  In Chrome, Right click the helper text and "inspect".  In the Dev Tools, Elements tab, CSS side bar, left click the "color".  It will show the contrast as 3.36.  It shows AA 4.5 and AAA 7.0 options.

You can also view this error with an Accessibility checker such as AXE.

Here is a StackBlitz with sample helper text for checkboxes:

https://stackblitz.com/edit/eemt-ng-clarity-helper-text-a11y

## Expected behavior

Colors used should satisfy at least WCAG AA guidelines.

## Versions

**App**

- Angular: 9, 10, 11
- Clarity: 3, 4, 5

**Device:**

not device specific

## Additional notes

This same principle, different instance of: https://github.com/vmware/clarity/issues/5098

**Comment by Jinnie** [comment]
This is already tracked by our A11Y team and is in nature the same as the one you linked. The same blocker is in effect. 
I will close this, to avoid duplication.
