### ISSUE TITLE
The radio for HEX/HSL is not working on the website color page 

### ISSUE THREAD

**Issue by yuxin-ux** [vmware/clarity#5507]
The HEX/HSL switch on the color page is not working. 
https://clarity.design/foundation/color/#dark-theme-functional-colors

**Comment by Jinnie** [comment]
Note: it rejects mouse clicks, but works fine with k/b only.

**Comment by hippee-lee** [comment]
This only breaks with a bookmarked link. When navigating from the site root all of the radio buttons work. Given that the color foundation content needs a complete re-write to reflect core I'm going to remove the high priority label.
