### ISSUE TITLE
The link "Get started with web component" on homepage uses a different font style and it links to storybook

### ISSUE THREAD

**Issue by yuxin-ux** [vmware/clarity#5520]
The font style looks different and i assume it should link to the get started page on the website (https://clarity.design/get-started/developing/)

![image](https://user-images.githubusercontent.com/33043434/105916615-0e2ed880-5fe6-11eb-9f2c-5eb10821d94f.png)

**Comment by hippee-lee** [comment]
This was fixed with #5521.
