### ISSUE TITLE
Documentation: button vs link

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#5529]
## Describe the bug
Button vs. Link - find the difference ... ;-)

## How to reproduce
1.  Go to 'https://clarity.design/core-components/button/'
2.  See error in screenshot
<img width="689" alt="2021-01-28_16h06_11" src="https://user-images.githubusercontent.com/311619/106157569-25ef9380-6183-11eb-8db0-f0d994c21971.png">

## Expected behavior
Proper documentation.

## Versions
Current docu version.

**Comment by Jinnie** [comment]
The paragraph before the demo explains "While buttons and links can both be given similar visual treatments..."
It's about the semantic meaning of `<button>` vs `<a>`.
But it can be hard to understand the way it currently is. We could probably add a bit of code sample to the demo to make it clear.
@hippee-lee leaving it open for you to decide if we may want to improve.
And we do need to fix the `..` at the end of description.
