### ISSUE TITLE
Icon updates and fixes

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#553]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Icon updates, Missing icons
- Some icons seem to be missing from the Iconography page. 
- Updated (redesigned) the "Router" icon, please replace
- "network_globe" (in attached zip file) is missing from Iconography page. Possibly overwritten by another image called "network" with is badged with a gear/cog?

All files to be published:
[updated and missing icons.zip](https://github.com/vmware/clarity/files/815627/updated.and.missing.icons.zip)

**Comment by Shijir** [comment]
resolved by https://github.com/vmware/clarity/pull/578
