### ISSUE TITLE
Documentation: Inline-button

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#5531]
## Describe the bug
Styling of hover-state on inline-button seems like an accident.

## How to reproduce
1.  Go to 'https://clarity.design/core-components/inline-button/'
2.  See error in screenshot
<img width="346" alt="2021-01-28_16h00_43" src="https://user-images.githubusercontent.com/311619/106158536-22104100-6184-11eb-9b1d-f8398f060f42.png">

## Expected behavior
Proper Styling.

Rethink necessity of inline-button ... is there really one?
links, buttons (outline, solid, flat) ... everything is there!

<img width="678" alt="2021-01-28_16h17_10" src="https://user-images.githubusercontent.com/311619/106158732-58e65700-6184-11eb-86a3-cd7451e4325b.png">

Does the world really need an inline-button in clarity??? ;-)

## Versions
Current docu version.

**Comment by hippee-lee** [comment]
I linked the PR that fixes this issue and will close it. The fix will be available in the next release and it will also fix the website.
