### ISSUE TITLE
Timeline component is broken

### ISSUE THREAD

**Issue by stefanmichalk** [vmware/clarity#5534]
## The timeline component is not rendering well.
The Icon of a timeline step is not rendering like in v4.

## How to reproduce

Just visit your own site [Timeline Documentation](https://clarity.design/angular-components/timeline/)

## Versions

**App**

- Angular: 11.1.1
- "@cds/core": "^5.0.0",
- "@clr/angular": "5.0.0",
- "@clr/icons": "5.0.0",
- "@clr/ui": "5.0.0",

**Device:**

- Type: MacBook Pro 16 2019
- OS: macOS BigSur 11.0.1
- Browser: Chrome Version 88.0.4324.96, Safari Version 14.0.1 (16610.2.11.51.8)

**Comment by gnomeontherun** [comment]
@bbogdanov Can you take a look, the icons are not styled properly in v5.
