### ISSUE TITLE
Title attribute is not necessary to be set for clr-dg-action-overflow

### ISSUE THREAD

**Issue by wghglory** [vmware/clarity#5542]
## Describe the bug

Let's say we have a datagrid with some options for each row. The triple dot generated by clr-dg-action-overflow also has a hardcoded text "Available actions". L10n team fired a bug for this hardcoded text.

## How to reproduce

```html
<clr-dg-action-overflow>
  <button>...</button>
</clr-dg-action-overflow>
```

## Expected behavior

`<clr-icon shape="ellipsis-vertical" title="Available actions" role="none"></clr-icon>`

title attribute should not be generated with hardcoded text.

## Versions

**App**

- Angular: 10.0.0
- Node: 14.0.0
- Clarity: 4.0.8

**Device:**

- Type: MacBook
- OS: MacOS
- Browser chrome, safari
- Version 22

**Comment by hippee-lee** [comment]
The `rowAction` can be internationalized with the common strings service. See [here](https://v4.clarity.design/documentation/internationalization) for how to localize as well as a full list of properties that can be localized. 

I'm closing this as not an issue but if there is an issue with the common strings please follow up here.

**Comment by wghglory** [comment]
Thanks @hippee-lee ! Very helpful
