### ISSUE TITLE
Clarity Stackblitz template does not compile

### ISSUE THREAD

**Issue by jzabinski** [vmware/clarity#5559]
## Describe the bug

When the Clarity Stackblitz template is opened on Stackblitz, the following message appears:
"Error in ~/src/main.ts
ngcc failed to run on @clr/angular@5.0.0-next.0."

## How to reproduce

[template provided by Clarity](https://stackblitz.com/edit/clarity-v4-light-theme-oeq1uy)

Navigate to Clarity's supplied template

## Expected behavior

The Stackblitz template provided by Clarity should compile successfully.

## Versions

**App**

- Angular: 11.0.3
- Node: whatever Node version is used by Stackblitz
- Clarity: 5.0.0-next.0 and 4.0.7

**Device:**

- Type: HP Elitebook
- OS: Windows 10
- Browser Chrome
- Version 89

**Comment by sis0k0** [comment]
@jzabinski, thank you for reporting the issue! We're actively working on resolving it.

**Comment by Jinnie** [comment]
There are known issues with Stackblitz and Ivy, that prevent our project from compiling with Ivy on at Stackblitz. So, please, just turn Ivy off in the Settings page of the Stackblitz (or in tsconfig.json file) before/after forking the project, as a workaround.
We'll take care to update the templates so they don't fail by default.

**Comment by Jinnie** [comment]
Templates updated
