### ISSUE TITLE
Clarity datagrid | Cannot add row after removing all rows

### ISSUE THREAD

**Issue by himanshunegi1987** [vmware/clarity#5561]
## Describe the bug
After removing all items from datagrid source, if I add more items, datagrid does not display the new items.
**Screen Capture**
![Screen_Capture](https://user-images.githubusercontent.com/6043434/106840310-bda62380-6654-11eb-8426-d7aa52ddf874.gif)

## Steps to reproduce the behavior
1. Bind datagrid source to an array
2. Add first item to array
3. datagrid shows one row
4. Add second item to array
5. datagrid shows two rows
6. remove all items from array
7. datagrid shows no rows
8. Add an item to array
9. Data grid should show one row, but UI is broken

## Expected behavior
Datagrid should add new rows on the UI

## Stackblitz link
https://clarity-thmjrf.stackblitz.io/
Seems to work in Stackblitz. Not sure why same code it not working in our application. It has the same package.json file as well.

## Code
**HTML**
```
<div class="row">
  <button type="button" class="btn btn-secondary" (click)="addOneRow()">Add one Row</button>
  <button type="button" class="btn btn-secondary" (click)="removeAllRows()">Remove all rows</button>

  <clr-datagrid>
    <clr-dg-column>Col 1</clr-dg-column>
    <clr-dg-column>Col 2</clr-dg-column>
    <clr-dg-column>Col 3</clr-dg-column>

    <clr-dg-row *ngFor="let item of myarr">
      <clr-dg-cell>{{item}}</clr-dg-cell>
      <clr-dg-cell>{{item}}</clr-dg-cell>>
      <clr-dg-cell>{{item}}</clr-dg-cell>
    </clr-dg-row>
  </clr-datagrid>
</div>
```

**Typescript**
 ```
myarr: number[] = [];

  addOneRow = () => {
    this.myarr.push(this.myarr.length + 1);
  }

  removeAllRows = () => {
    this.myarr = [];
  }
```

## Versions
- Angular: [9.1.7]
- Clarity: [3.1.2]

## Device
- Browser [Chrome]
- Version [88]

**Comment by bbogdanov** [comment]
Hi @himanshunegi1987,

Seems like the installed version of Clarity in the stackblitz is `3.1.15`. I remember doing a fix not along ago with @Jinnie about the rows manipulation and it was definitely after `3.1.2`.

Give it a try with `3.1.15` and let me know how it went.

**Comment by himanshunegi1987** [comment]
@bbogdanov 
Does that mean '3.1.15' > '3.1.2' ?
I will give '3.1.15' a try and update back

..........Update..........
Works with version '3.1.15'
Thanks
