### ISSUE TITLE
Combobox: error can be thrown while combobox is focused

### ISSUE THREAD

**Issue by jzabinski** [vmware/clarity#5565]
## Describe the bug

When Angular removes the combobox while the combobox is focused, the error 'ApplicationRef.tick is called recursively' can be thrown.

## How to reproduce

[This repository](https://github.com/jzabinski/clarity-combobox-ondestroy-error) has code which emulates the issue.

1. Download the repository.
2. `npm install`
3. `ng serve`
4. In the combobox, click the right portion of the combobox to activate the dropdown. (The dropdown icon sometimes does not appear.)
5. Wait a second, and you should see the combobox disappear, replaced by a spinner.

The error 'ApplicationRef.tick is called recursively' can be seen in the console.

## Expected behavior

The combobox should be able to be removed by Angular without triggering an error.

## Versions

**App**

- Angular: 11.1.2
- Node: 12.13.1
- Clarity: 5.0.0-next.0

**Device:**

- Type: PC
- OS: Windows 10
- Browser Chrome
- Version 89

## Additional notes
This behavior would apply when some part of the app decides that one of the combobox's parent containers needs to be removed from the screen. The demo emulates this behavior by setting a variable that Angular can react to when the dropdown is opened.

The root cause of the issue seems to be this code in ComboboxFocusHandler:
```
addFocusOnBlurListener(el) {
        if (isPlatformBrowser(this.platformId)) {
            this.renderer.listen(el, 'blur', event => {
                if (this.focusOutOfComponent(event)) {
                    this.toggleService.open = false;
                    // Workaround for popover close-on-outside-click timing issues in Edge browser
                    this.appRef.tick();
                }
            });
        }
    }
```
This code runs successfully when the combobox is otherwise blurred. But when Angular needs to remove the focused combobox, it is already doing so in the context of a call to ApplicationRef.tick.

**Comment by gnomeontherun** [comment]
I imported this as Stackblitz for easier triage https://stackblitz.com/github/jzabinski/clarity-combobox-ondestroy-error
