### ISSUE TITLE
Icons Volume 19

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#5575]
## Icons Volume 19

Epic to consolidate icon requests for the next icon release

**Comment by lil-kim** [comment]
Icons for this Epic:
#5089
#5451
#5348 
#5517

**Comment by JChernashki** [comment]
Icons for #5089 #5451 #5348 #5517 

[digital_signature_line.svg.zip](https://github.com/vmware/clarity/files/6005350/digital_signature_line.svg.zip)
[timeline_line.svg.zip](https://github.com/vmware/clarity/files/6005352/timeline_line.svg.zip)
[update_line.svg.zip](https://github.com/vmware/clarity/files/6005353/update_line.svg.zip)

**Comment by lil-kim** [comment]
Also...Icons for issue #5517 
[5517-icons.zip](https://github.com/vmware/clarity/files/6005770/5517-icons.zip)

**Comment by d-m-s** [comment]
not sure if discussion is correct, but please also consider a new icon for auction/hammer: https://github.com/vmware/clarity/discussions/5831
@lil-kim
