### ISSUE TITLE
Typo on the website - progress bar

### ISSUE THREAD

**Issue by yuxin-ux** [vmware/clarity#5578]
There is a typo on the [angular component/progress bar page](https://v4.clarity.design/documentation/progress)
Should be "estimated"

![image](https://user-images.githubusercontent.com/33043434/106991300-ca954680-672a-11eb-86d6-bb3f0f4f2001.png)

**Comment by hippee-lee** [comment]
It looks like this is fixed in the latest release. 
![Screen Shot 2021-02-05 at 1 08 02 PM](https://user-images.githubusercontent.com/433692/107089281-3a4f1400-67b3-11eb-813a-9dce147ba51e.png)
