### ISSUE TITLE
Broken styles in Header while trying to migrate to Clarity Core

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5581]
## Describe the bug

Today I started to tackle the migration towards Core and immediately ran into some issues. Here's the first:

The header button font is not centered anymore:

![Screenshot 2021-02-06 at 17 02 36](https://user-images.githubusercontent.com/3655915/107123347-57f8a800-689d-11eb-85ee-3069d966e6d2.png)

I found some more issues but I'm struggling to get the stackblitz for reproduction working. See additional notes below.

## How to reproduce

https://stackblitz.com/edit/clr-5-core-migration-issues-header-font-alignment?file=src/app/app.module.ts

## Expected behavior

Font is centered.

## Versions

**Clarity project:**

- [X] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [x] v5.0.1

**Framework:**

- [x] Angular

**Framework version:**
Angular 11.1.2

## Additional notes

I tried to create a Stackblitz for another issue I found but ran into this Stackblitz error:

```
Error in /turbo_modules/@clr/angular@5.0.1/bundles/clr-angular.umd.js (2:111)
Unexpected token 'export'
```

Any idea how to fix it? Is it stackblitz's fault? https://stackblitz.com/edit/clr-5-core-migration-issues-clr-angular-stackblitz-error?file=src/app/app.component.html

**Comment by mathisscott** [comment]
@dorthrithil 

If the `cds-text` attribute is used on a container that will have lots of child nodes like `body` or `html`, the `disable-lhe` value should be added to it to remove the line-height erasers.

[Here is an example](https://stackblitz.com/edit/clr-5-core-migration-issues-header-font-alignment-zrqe2n?file=src%2Findex.html)

**Comment by dorthrithil** [comment]
It's still a little off as the default line-height is set to `1rem` after the fix. However the header nav-link is designed for a line-height of `1.2rem`. I guess I have to add some custom CSS and wait for the header to be implemented in core?

![Screenshot 2021-02-12 at 17 23 15](https://user-images.githubusercontent.com/3655915/107794349-9ee01500-6d57-11eb-9d23-da4d5a7054d4.png)

**Comment by gnomeontherun** [comment]
@mathisscott can you review this question?

**Comment by mathisscott** [comment]
@dorthrithil 
This is due to the `cds-text` line-height conflicting with the Clarity UI CSS' line-height. It's a straightforward workaround to [add the line-height back in on the product side](https://stackblitz.com/edit/clr-5-core-migration-issues-header-font-alignment-zrqe2n?file=src/styles.css). 

You may want to consider putting the `cds-text` declaration on the `.content-container` element instead of globally on `body`.
