### ISSUE TITLE
Combobox behavior is confusing for single selection

### ISSUE THREAD

**Issue by dexfab** [vmware/clarity#5589]
When using the single select combobox as per example: https://clarity.design/angular-components/combobox/#single-selection-combobox-2

Once an item is selected and the combo is opened by the user again, only the selected option is being shown. Our users have been complaining about this behavior as they still expect to see all items shown and not have to clear the selection in order to see the full list.

Example of the expected behavior: https://ng-select.github.io/ng-select#/search

**Comment by Jinnie** [comment]
Our combobox is following the W3C ARIA recommendations. You can verify that the W3C combobox has the same behavior:
https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html

I will close this issue, as working as designed, but I will take care to report it to our A11Y team for reference and comment.
