### ISSUE TITLE
Tabs is not working properly

### ISSUE THREAD

**Issue by manuelarte** [vmware/clarity#560]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

I can use tabs
### Actual behavior

I get the following error:

More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: TabLink,WizardStep ("exChanged($event)"
          (clrTabsCurrentTabContentChanged)="onTabContentActivated($event)">
    [ERROR ->]<clr-tab-link [clrTabLinkId]="'link1'" [clrTabLinkActive]="true">Dashboard</clr-tab-link>
    <clr-ta"): HomeHowToComponent@28:4
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: TabLink,WizardStep (">
    <clr-tab-link [clrTabLinkId]="'link1'" [clrTabLinkActive]="true">Dashboard</clr-tab-link>
    [ERROR ->]<clr-tab-link>Management</clr-tab-link>
    <clr-tab-link>Cloud</clr-tab-link>

### Reproduction of behavior
I downloaded the seed template for SystemJS (around a few months ago), and I get the error described above when trying to use tabs.

### Environment details

* **Angular version:** 2.0.X
~2.2.1
* **Clarity version:** 
^0.7.0
* **OS and version:** 
Windows 10

* **Browser:** [Chrome 56.0.2924.87]

**Comment by jaffoneh** [comment]
@manuelarte can you provide a plnkr so we know a bit more about what's going on there? We're not really sure what's happening there from just the error posted above. Also, you probably need to check a newer seed version and confirm you still have this issue.

**Comment by mathisscott** [comment]
It's been a while since this was opened and still no plunkr. I'm assuming that @manuelarte found a workaround?

**Comment by manuelarte** [comment]
Hi mathisscott, 

I updated clarity to its latest version and now it is working.

**Comment by mathisscott** [comment]
@manuelarte : Cool. Thanks for getting back to me on that.
