### ISSUE TITLE
Datagrid does not remember scroll position after removing a row

### ISSUE THREAD

**Issue by politicsruinseverything** [vmware/clarity#5603]
## Describe the bug
With clrDgSingleSelected on, removing the selected row (item from array) results in the scroll position being reset to the top.

## How to reproduce
With clrDgSingleSelected on, remove the selected row (item from array) by using a button or some method to trigger a function to do so.

## Expected behavior
The grid either needs to a) provide a "sticky" scroll option, or, b) try to maintain scroll position after an item removal as closely as possible, or c) provide a way for the developer to manually set the scroll position. I imagine I could do this in a roundabout way by obtaining a template reference to the component and drilling into the DOM prior to removing an item but if I can do it, so can you, and make it a part of the codebase for all to enjoy :)

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ X] Clarity Angular/UI

**Clarity version:**

- [ X] v3.x
- [ ] v4.x
- [ ] v5.x

**Framework:**

- [ X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_Angular 11

**Device:**

- Type: Dell laptop
- OS: Windoze 10
- Browser: Edgium / Chrome
- Version: 88.0.705.63

## Additional notes
I searched for an open or closed issue regarding "datagrid position" and "datagrid remove" but did not find anything.

**Comment by Jinnie** [comment]
We need a stackblitz reproduction in order to be able to research the issue.
Please use one of these: https://stackblitz.com/@clr-team
Behavior can vary depending on whether you use client-side or server-side datagrid, if you use trackby, etc.

**Comment by gnomeontherun** [comment]
This issue does not have a reproduction and we are going to close it as stale. If the issue persists, please provide a working [Stackblitz demo](https://stackblitz.com/@clr-team) to get started.

**Comment by politicsruinseverything** [comment]
I tried reproducing for Clarity v4 and it seems resolved now. Thanks. I was only seeing the issue in v3.

By the way, if Ivy is turned on in Stackblitz, it seems to blow up any demo you're working on and I couldn't find a way to undo it. Probably a good idea to make note on the "fork this project" instructions going forward.

**Comment by Jinnie** [comment]
Thanks @politicsruinseverything, this is a known issue, we've already logged to Stackblitz, but have no response yet
https://github.com/stackblitz/core/issues/1364
Should be able to undo it by either disabling Ivy in the Stackblitz project Settings or in the "tsconfig.json" file.
