### ISSUE TITLE
Combobox input not cleared on selection

### ISSUE THREAD

**Issue by moqmar** [vmware/clarity#5604]
## Describe the bug

In the "Multi selection combobox" example (https://clarity.design/angular-components/combobox/), entering something and then selecting the option from the list doesn't clear the input, which means that I have to press Ctrl+A again if I want to add something else.

## How to reproduce

1.  Go to https://clarity-v4-light-theme-b1nr24.stackblitz.io/
2.  Click on the 'Favorite States' input
3.  Enter "Tes" & press Enter to select "Test" (or click on the option in the dropdown)
4.  The string "Tes" remains in the input field, even though the element has been selected

Source: https://stackblitz.com/edit/clarity-v4-light-theme-b1nr24?file=src/app/app.component.html

## Expected behavior

The input is cleared when selecting an option from the list.

## Versions

**Clarity project:**

- [ ] Clarity Core (?!)
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 10/11

**Device:**

- Type: PC
- OS: Ubuntu Linux
- Browser: Firefox
- Version: 85

**Comment by Jinnie** [comment]
It is working as designed. The input acts as a filter text. It is not supposed to get auto-cleared on its own.
If we do clear it, it will become accessibility issue, as we won't be able to inform the user that we just deleted the text that was entered.
The combobox is a complex component that tries to address multiple goals with one solution. It is not easy to find the balance between all different possible requests and preferences. Accessibility is very high on our priorities list.
