### ISSUE TITLE
clr-vertical-nav-group-children component duplicated when Vertical Nav collapsed and opened again quickly

### ISSUE THREAD

**Issue by BojidarTrenchev** [vmware/clarity#5608]
## Describe the bug

`clr-vertical-nav-group-children` component in a `clr-vertical-nav-group` is duplicated if the button for collapsing the Vertical Nav is clicked and then quickly clicked again before the nav has fully collapsed.

`*clrIfExpanded="true"` must be set for the `clr-vertical-nav-group-children `component otherwise the scenario works as expected.

The following error is thrown in the browser console when the issue appears:
`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'is-expanded: true'. Current value: 'is-expanded: false'.`

## How to reproduce

Go to [the sample Stackblitz](https://stackblitz.com/edit/clarity-nav?file=package.json)

1. Tap on the << button then quickly tap it again before the nav has fully collapsed
2. Open up the library `clr-vertical-nav-group` menu
3. There are now two or more `clr-vertical-nav-group-children` components (instead of just one)

## Expected behavior

clr-vertical-nav-group-children component should not be duplicated in this case.

## Versions

Clarity: 5.0.1, but same problem appears on 3.1.14
Angular: 9.1.13
Ivy: disabled in the Stackblitz, but enabled in the project I work on - both cases the issue appears

- OS: Ubuntu
- Browser Firefox, Edge, Chrome (latest versions)

**Comment by wendellestradairely** [comment]
I have the same issue. I've been experiencing this even before the Ivy was introduced.

**Comment by Jinnie** [comment]
I reproduce it with the Stackblitz, but not yet reproducing it with our demos. Needs a bit more investigation before we can say why it happens.

**Comment by Jinnie** [comment]
With the current component architecture, there are some inner states and events that depend on the collapsing/expanding animations. In the same time we have two animations in this scenario - one for the nav and one for the group. Triggering the nav animation sometimes triggers the group animation.
This scenario - quick subsequent expand/collapse events, in conjunction with the *ifExpanded directive, leads to very complex and unstable lifecycle with many variables that need synchronization.
I can't find a quick and reliable solution, without more major rework, but I have two suggested workarounds:

1. Don't use *clrIfExpanded to pre-expand the group children. Use this property instead '[clrVerticalNavGroupExpanded]' on the `clr-vertical-nav-group` (not on the children). This will save the node duplications but not the exceptions.

2. Disable the animations on the group only, like this:
```
	<clr-vertical-nav-group @.disabled>
        .........
```
It resolves both issues, for the price of missing animation on the group.

**Comment by Jinnie** [comment]
My expectation is to have a permanent fix in Clarity Core, where we have a separate motion layer for the animations which would allow much better handling and separation of the component lifecycle from the animations lifecycles.

We also welcome any community research or contribution for the current Angular version, if you feel the workarounds are not enough.
