### ISSUE TITLE
Wizard-it should always be reset to the first step page each time when open it.

### ISSUE THREAD

**Issue by ghvm2014** [vmware/clarity#561]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

it should always be reset to the first step page each time when i open it.

### Actual behavior

1. the first time after i opened it, i click next to the third page.
2. then i close the wizard, and open it again
3. the wizard is showing the third page, not the first page.

### Reproduction of behavior

you can try the demo in the https://vmware.github.io/clarity/documentation/wizards.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
0.8.8
* **OS and version:** 
win10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Hi @ghvm2014. Thanks for the feedback. The current wizard works as designed.

What is being requested here is comparable to reset functionality that we are including in the wizard refactor #156 that we are working to complete for 0.9.

Closing this issue as a duplicate. Thanks again for the suggestion.
