### ISSUE TITLE
Keyboard navigation in nested Stack view breaks the visual layout

### ISSUE THREAD

**Issue by TeodoraNozharova** [vmware/clarity#5615]
## Describe the bug

If keyboard navigation is used in Stack view with nested stack blocks, when the last item of a given nested stack block is reached using the down arrow key, the next keystroke brakes the visual layout of the next stack block.

## How to reproduce

Can be reproduced on Clarity documentation page, I've added a gif which visualizes the issue as well as a Stackblitz with the example in Clarity 4.0 for simple Stack view.
![StackLabel](https://user-images.githubusercontent.com/16055815/108174627-57b3a480-7108-11eb-8fac-25b98e102933.gif)

https://stackblitz.com/edit/clarity-v4-light-theme-crbbr8?file=src/app/app.component.html

1. Have Stack view with 2 (or more) nested stack blocks, having the first one expanded and the second one collapsed.
2. Navigate through the stack view using the down arrow key
3. Go to the last element of an expanded nested stack block and use the down arrow key to navigate to the next stack block that is collapsed.
4. Observe that the visual representation of the next stack block is broken. The first stack content is rendered on top of the stack label

## Expected behavior

Keyboard navigation should not disrupt the visual representation of the content of the Stack view.

## Versions

**Clarity project:**

- [X ] Clarity Angular/UI

**Clarity version:**

- [X ] v4.x

**Framework:**

- [X ] Angular

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
Note: we talked today with Teodora and it's possible to be NVDA specific issue, as she's testing it in A11Y context. 
We'll have more information tomorrow.

**Comment by Jinnie** [comment]
We confirmed this is fixed in v5. 
It was just backported to v4 too. Expect it in the next release.
