### ISSUE TITLE
Fix colors for disabled checkbox and radio buttons (Clarity4)

### ISSUE THREAD

**Issue by danail-vasilev** [vmware/clarity#5633]
## Describe the bug

In Clarity 4 colors for disabled checkbox and radio button look like that - https://www.screencast.com/t/0bY5gudIuZ 

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-ukokpe

## Expected behavior

I have checked core components documentation
- Disabled checkboxes look like that - https://www.screencast.com/t/TIY2861DkK  Different than in Clarity 4.
- Disabled radio buttons - Actually they are not disabled in the doc, but after manually setting
disabled property they look like that - https://www.screencast.com/t/BObLvFcB

Colors for disabled in checkbox/radio button are different between both - v4 don't look disabled, while in core they do.

## Versions

**Clarity version:**

- [ ] v3.x
- [x ] v4.x
- [ ] v5.x

**Framework:**

- [ x] Angular 10
- [ ] React
- [ ] Vue
- [ ] Other:

**Comment by bbogdanov** [comment]
Hi @danail-vasilev, 

Thank you for letting us know about this issue.

I am going to investigate it cause it seems like a Clarity issue. I'll write back as soon as I find the root cause.

**Comment by bbogdanov** [comment]
@danail-vasilev Found the root cause, there is a PR raised and hopefully the fix will be available in the next minor release.

**Comment by bbogdanov** [comment]
#5652 is in. @danail-vasilev expect the fix in next minor release and let me know if the issue still appears

**Comment by danail-vasilev** [comment]
Thanks @bbogdanov  for looking into that !
Actually there are 3 issues reported here:
- Disabled radio button - that seemed to be fixed with #5652 
- Disabled checkbox - it's icon color is different than the one from core components.
- Core components doc:
    - checkboxes tick icon is misaligned
    - disabled radio buttons can be clicked. Also for disabled example it's better to have one of the buttons checked, like it's with radio buttons disabled example.

If you think the above issues must be handled separately please open separate issue for them.
Regards,
Danail

**Comment by gnomeontherun** [comment]
We had some color improvements that are in Clarity Core but not Clarity Angular due to it being a breaking change that might cause products to have some different color combinations. We are not intending to update the Angular colors at this time for this reason.

**Comment by danail-vasilev** [comment]
@gnomeontherun  I have reported 3 bugs above. Which of them is your comment related to ? The first issue seem to be merged, what about it ?

**Comment by bbogdanov** [comment]
I believe Jeremy comment is about the second point you made `Disabled checkbox - it's icon color is different than the one from core components.` The color improvements are made in order to bring a11y support.

We are about to do a PR on the `tick` icon alignment.

The last time I used the `core` disabled radio button I haven't seen any issues but I'll check it and will do a PR if I see issues there.

**Comment by bbogdanov** [comment]
@danail-vasilev The radio buttons cannot be clicked when you have a `disabled` attribute on the `input`.

There is an issue with the input groups when the group container is disabled but it doesn't pass the disabled attribute to the inputs inside it. I am about to create a separate task about it.

Thank you once again for bringing our focus to these issues!
