### ISSUE TITLE
Documentation for Angular Components (Alert) - incorrect example images

### ISSUE THREAD

**Issue by milesich** [vmware/clarity#5636]
## Describe the bug

In documentation for Angular Components - Alert the example images of standard alerts are swapped as you can see on the screenshot below.  

## How to reproduce

![Screenshot 2021-02-20 at 21 22 51](https://user-images.githubusercontent.com/1993963/108607642-dc7d1780-73c1-11eb-9843-1040251bc55e.png)

**Comment by bbogdanov** [comment]
@hippee-lee Seems like the file names are not correct in S3. I could of do a fix but I don't have access to the S3, yet.

![image](https://user-images.githubusercontent.com/15037947/108681364-bd80a180-74f7-11eb-88f6-31a65755a7e6.png)
