### ISSUE TITLE
Icons are broken in clr-vertical-nav and clr-accordion

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#5644]
## Describe the bug

The icon for expand/collapse buttons in `clr-vertical-nav` and `clr-accordion` are broken.

## How to reproduce

![Screenshot 2021-02-23 at 20 55 23](https://user-images.githubusercontent.com/3958008/108905482-9d72e000-75d4-11eb-9e8f-b49df3448f2e.png)
![Screenshot 2021-02-23 at 21 04 30](https://user-images.githubusercontent.com/3958008/108905487-9e0b7680-75d4-11eb-9619-de8dcb026e52.png)

https://stackblitz.com/edit/clarity-v5-light-theme-accordion?file=src/app/app.component.html
https://stackblitz.com/edit/clarity-v5-light-theme-vertical-nav?file=src/app/app.component.html

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
Reason analysis: `clr-icons.scss` has this setting for the `svg` element  inside the `clr-icon`. the `cds-icon` lacks it, which leads to non-centered icon if height of the `cds-icon` is manipulated.

```
 & > * {
    height: 100%;
    width: 100%;
```

**Comment by dorthrithil** [comment]
For everyone who is looking for a workaround:

```css
.nav-group-trigger .nav-group-trigger-icon {
  display: flex;
}
```

also fixes the issue without the need of any hacks to pierce the shadow DOM which are needed to apply Jinnies fix.

**Comment by Jinnie** [comment]
@dorthrithil thanks for providing the workaround!
My "fix" was not a workaround suggestion, but just a direction to what we need to fix inside the component. I have a commit for it, but it currently depends on another related change, which I want to push together with this.

**Comment by sis0k0** [comment]
The icons in the vertical nav should be fixed with https://github.com/vmware/clarity/pull/5862.
The accordion ones were already fixed with https://github.com/vmware/clarity/pull/5810.

**Comment by sis0k0** [comment]
The fixes will be shipped with the next release.
