### ISSUE TITLE
Searhbox unreadable in 5.0.2 dark theme

### ISSUE THREAD

**Issue by kdvolder** [vmware/clarity#5645]
## Describe the bug

The searchbox in dark theme is unreadable because of dark font on dark background.

## How to reproduce

Someone else in clarity slack was able to reproduce it. So I'm sharing his link here:

https://stackblitz.com/edit/clarity-v5-dark-theme-m5nx4u

1.  Create a searchbox in 5.0.1
2.  Look at searchbox in browser, it looks good and readable.
3.  Upgrade to version 5.0.2
4.  Look at searchbox in UI again. Searchbox 

Screenshots:

5.0.2:
![version-5 0 2](https://user-images.githubusercontent.com/1002156/108911109-ac10c580-75db-11eb-9e0f-d8d60365f688.png)

5.0.1:
![version-5 0 1](https://user-images.githubusercontent.com/1002156/108911112-ac10c580-75db-11eb-98b2-36e4f7cf81d7.png)

## Expected behavior

I expect the text in the searchbox to be readable and have good contrast to the background.

## Versions

**Clarity project:**

I have no idea which part of clr framework is to blame. But we are using it with angular and have the dark theme selected.

**Clarity version:**

- v5.0.2 (probably regression from 5.0.1)

**Framework:**

- [X ] Angular

**Framework version:**

Angular 11.0.1_

**Device:**

- Type: [Dell]
- OS: [Ubuntu Linux]
- Browser: chrome
- Version: Version 88.0.4324.182 (Official Build) (64-bit)

## Additional notes

I tried overriding the bad color in our own css but couldn't find a way to do it because the 'black' font color is applied by rule marked with `!important` which always takes priority over whatever I try to put instead.

In the end I just reverted us back to 5.0.1 and the problem went away. So I assume this is some sort of regression in how 5.0.2 assigns colors to the searchbox input text.

**Comment by Shijir** [comment]
Reproduction: https://stackblitz.com/edit/clarity-v5-dark-theme-m5nx4u

**Comment by kdvolder** [comment]
Not a bug in Clarity. So closing this.

Seems like the problem was something to do with our app having some missing css imports.

The full list of imports that are needed and make it work are:

```
@import '~@clr/ui/clr-ui-dark.min.css';
@import '~@clr/icons/clr-icons.min.css';

@import '~@cds/core/global.min.css';
@import '~@cds/core/styles/module.shims.min.css';
@import '~@cds/city/css/bundles/default.min.css';
@import '~@cds/core/styles/theme.dark.min.css';
```

Previously we had only:

```
@import '~@clr/ui/clr-ui-dark.min.css';
@import '~@clr/icons/clr-icons.min.css';
@import '~@cds/core/styles/theme.dark.min.css';
```

Thanks a lot to @Shijir for helping me with this problem.
