### ISSUE TITLE
Nested Menu Component

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#565]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Description
Nested menus save space and organize items/actions into categories. The user can hover to reveal deeper levels as needed.
- Hierarchy: darker border and slight overlap (4px) of nested menus help to show stack order.
- 168 px /336 px  Min/max width 
- Default ine height is 30 px. 36 px for x-small breakpoint (<544px)
 -- Current dropdown menu line height (24px) to be updated to 30px
- Group name stays in selected state to serve as a breadcrumb
- By default nested menus should pop up on the right side of the previous menu. If space isn’t available, the menu should appear on the left side. A third menu would appear on the right side of the second menu in a zig-zag pattern.

### Interaction
- With mouse: Hover-over group name to reveal nested menus. Add a delay to mitigate user errors and disappearing menus. On touch screens: nested menus are revealed on touch.
- Clicking outside of menu dismisses all menus
![nm_example](https://cloud.githubusercontent.com/assets/23196444/23683465/f039a79a-034d-11e7-8b18-e519690605be.png)

### Menu stack order and positioning
By default nested menus pop up to the right side of the previous menu 
![default positioning](https://cloud.githubusercontent.com/assets/23196444/23681707/e9cc96b4-0344-11e7-95ea-e018f204703d.png)

If there isn’t enough space, the second menu should pop up on the left side of the first menu. The third menu would appear on the right side of the second menu in a zig-zag pattern.

![responsive](https://cloud.githubusercontent.com/assets/23196444/23681711/ee195072-0344-11e7-96b5-53086de52104.png)

![nm_redline](https://cloud.githubusercontent.com/assets/23196444/23683483/0f928206-034e-11e7-9e0d-362368c7e602.png)

**Comment by mathisscott** [comment]
@seedhuro 
You tab through the elements in the menu and it will focus on all actionable items in your menu. You use the Enter or spacebar keys to execute any actions.

I don't know what you mean by "focus on first letter from the list" and I don't understand why you would want users to have to move focus through every single letter of a word.

**Comment by seedhuro** [comment]
ok sorry for bed word usage :) I want to use clarity dropdown like a <select> in usually HTML. In the <select> solution when you open the drop-down, you have the possibility to access every <option> item with the arrow key or simply enter the first letter from the item you want to access.

**Comment by mathisscott** [comment]
@seedhuro 
So you want to be able to use the dropdown menu like an HTML select menu?

**Comment by seedhuro** [comment]
yes indeed. my problem is: I have dynamically generated a dropdown menu using Angular 6. If I have multiple lines generated by a function, my users ask me to have the possibility to use arrow keys to navigate to the right drop-down item or like a search field, jump to the right item using the first letter of the word. This is my code:

                <clr-dropdown clrMenuPosition="bottom-left" class="btn-secondary btn-sm medium-right-padding">
                    <button class="btn dropdown-toggle button-min-height" clrDropdownToggle>
                        {{ lang.text('equipments') }}: {{ getEquipmentsDropdownName() }}
                        <clr-icon shape="caret down"></clr-icon>
                    </button>
                    <clr-dropdown-menu>
                        <span *ngFor="let eq of this.equipmentsTypes.getAll()">
                            <a clrDropdownItem  (click)="setFilterSelectedEquipment(eq.id)">{{ eq | GetNameOfObject }}</a>
                        </span>
                    </clr-dropdown-menu>
                </clr-dropdown>

**Comment by mathisscott** [comment]
Is [this more like what you are looking for](https://github.com/vmware/clarity/issues/248)?

Or are you asking for advanced keyboard navigation specifically and only for dropdown menus?

**Comment by seedhuro** [comment]
no, I want to use clarity drop-down menu just I mention above. if I have 100 item in a drop-down, I need to use quick search by typing a letter, or instead of using the mouse scroll, I want to use up/down key from the keyboard.

**Comment by mathisscott** [comment]
Okay, @seedhuro . I think I understand. You want advanced keyboard navigation for large dropdown menus. Does that sound right?

Quick question, though, what is the use case for having 100 items in a dropdown menu?

**Comment by seedhuro** [comment]
thank you for answering. for example, I work on the software which is implemented in a Hotel. Tha data is generated dynamically depending on how many rooms are in the hotel. In my case, I have approx 120 rooms. :) If my client wants to select one of them, the issue becomes real challenge :) In an ordinary case, I handle it with select and options tag but in this case, the design pattern is Clarity Design. Thank you for your time.

**Comment by mathisscott** [comment]
So... you _do_ want the select behavior like in [our planned Select++ component](https://github.com/vmware/clarity/issues/248) which should have search/filtering and selections as well as (eventually) arrow key navigation?

If you want to be able to _select_ an option, then isn't ☝️ what you want?
