### ISSUE TITLE
Focus should return to previously active element after closing modal

### ISSUE THREAD

**Issue by zoroaster00** [vmware/clarity#5668]
## Describe the bug

After closing clarity modal, the previously active element is not focused.

## How to reproduce

https://clarity-v3-light-theme-focus-element.stackblitz.io

1.  Use keyboard to navigate to button "foo".
2.  Hit "Enter" to open modal.
3.  Hit "Escape" to close the modal.

## Expected behavior

The button "foo" should be focused.

## Versions

**Clarity project:**

- [x] Clarity Angular/UI

**Clarity version:**

- [x] v3.x
- [x] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 9

## Additional notes

It should be fixable in focus-trap.directive.ts since it is already doing so, but it sets previousActiveElement wrong. In AfterViewInit it is set to the element inside focusTrap, it will be fixed if it is set to document.activeElement before AfterViewInit (in onInit maybe?).

**Comment by igpeev** [comment]
Also reproducible with Clarity Angular Dropdowns - [StackBlitz](https://stackblitz.com/edit/clarity-light-theme-v5-xsa2sk?file=src/app/app.component.html)
