### ISSUE TITLE
Unexpected token when testing Clarity app with Jest 

### ISSUE THREAD

**Issue by twittwer** [vmware/clarity#5672]
## Describe the bug

When running tests that contain Clarity components with Jest it fails with an `Jest encountered an unexpected token` error in the icon component of `@cds/core`.

It occurs after the upgrade of Clarity from `v4.0.10` to `v5.0.2`.

## How to reproduce

See Repo (incl. Readme): https://github.com/twittwer/clarity-jest

1. `git clone git@github.com:twittwer/clarity-jest.git`
2. `npm install`
3. `npm test`

```
 FAIL   clarity-jest  apps/clarity-jest/src/app/app.component.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Users\tw\git\clarity-jest\node_modules\@cds\core\icon\index.js:6
    export * from './icon.element.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1350:14)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        5.909 s
Ran all test suites.
```

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular (v11)
- [ ] React
- [ ] Vue
- [ ] Other:

**Comment by coryrylan** [comment]
Clarity Core only ships native ESM code to npm. Jest by default always compiles down to ES5 but ignores node_module dependencies like Clarity. The fix is to configure Jest to enable native ESM. I would look into the docs here https://jestjs.io/docs/en/ecmascript-modules or consider compiling your upstream dependencies with `transformIgnorePatterns` option.
