### ISSUE TITLE
Website documentation- Update the usage guidelines for accordion

### ISSUE THREAD

**Issue by yuxin-ux** [vmware/clarity#5674]
See the latest content and illustrations in the figma file
https://www.figma.com/file/rWE0j6DRp0LR8euGGJ97Dz/Core-Accordion?node-id=22%3A425

Use the latest core component (the color should be light blue)
![image](https://user-images.githubusercontent.com/33043434/109579325-8b4de180-7aad-11eb-85ce-ee4a92ca83df.png)

**Comment by bdryanovski** [comment]
Is this still valid?

@coryrylan @hippee-lee

**Comment by coryrylan** [comment]
I believe so, the only thing I think that would be different would be us renaming the accordion panel to section in 6.0 https://github.com/vmware/clarity/pull/6195

**Comment by hippee-lee** [comment]
We have an item in the (internal) MSProject item tracking the graduation of core components from beta -> prod that I believe will cover this. I think we can close it since this is a docs issue that is being internally tracked.
