### ISSUE TITLE
Combobox `OnPush` Initial/Programmatic Selection

### ISSUE THREAD

**Issue by sgrtho** [vmware/clarity#5676]
## Describe the bug

If `ChangeDetectionStrategy.OnPush` is used neither an initial nor a dynamically chosen item is reflected in the Angular Combobox component. It is reflected once the input gains focus though.

## How to reproduce

1. Go to 'https://stackblitz.com/edit/clarity-v4-light-theme-9j8rm6'
2. Click input field
3. Click the "Add/Select" button
4. Click the input field

## Expected behavior

The Combobox should reflect both cases the same way it does once an item is clicked in the list.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [?] v3.x
- [X] v4.x
- [X] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: MacBook
- OS: MacOS
- Browser: Chrome
- Version 88

**Comment by bdryanovski** [comment]
@Jinnie is there a reason for that or ... ?

**Comment by Jinnie** [comment]
With a little change of the demo, we can see that the change is not completely omitted, but goes one change cycle behind.
https://stackblitz.com/edit/issue-combobox-on-push-research?file=src/app/app.component.ts

There is an open Angular bug about the problem of adding a component that implements the `ControlValueAccessor` interface in a parent that utilizes the OnPush strategy: https://github.com/angular/angular/issues/10816 

It's more than four years old now, so we probably can't rely on a fix coming soon.
Though it's kept open for so long, and in "confirmed" state, there are some interesting thoughts there about the architectural impossibility to add complex components, with internal bi-directional bindings, to an OnPush parent, which wants to use uni-directional data flow pattern.
There is a workaround suggested for the initial value (adding `this.cdr.markForCheck()` to the `ngAfterViewInit()` handler (commented in my updated stackblitz), but this does not cover the hot value update problem observed later.

Additionally, using OnPush is breaking the keyboard focus handling of the component.

Once this gets prioritized, I would spend an iteration, trying to see if we can try to rework our internal communications to rely on immutable objects. Though I suppose we have many direct bi-directional bindings which are not trivial to replace completely, but at least we can try to improve the arrow-key focus handling.
