### ISSUE TITLE
Datagrid Expandable rows angle icon direction not working with clr-datagrid class="datagrid-compact" 

### ISSUE THREAD

**Issue by guetin** [vmware/clarity#5677]
## Describe the bug

Datagrid Expandable rows angle icon direction not working with clr-datagrid class="datagrid-compact".

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v5-qnuoea

Create a clr-datagrid with class="datagrid-compact"
Create a clr-dg-row-detail element inside it

## Expected behavior

The direction icon must be right when row is unexpanded and down when expanded.

## Versions

**Clarity project:**

- [ 5.0.2] Clarity Core
- [ 5.0.2] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x ] v5.x

**Framework:**

- [x ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [Lenovo]
- OS: [Windows 10]
- Browser [Chrome & Firefox]
- Version [Chrome 88.0.4324.190 (Build officiel) (64 bits) & Firefox 87.0b4 (64 bits)]

**Comment by bdryanovski** [comment]
Hey @guetin, thanks for reporting this, I manage to reproduce the case so it seems like a bug, we gonna need some time to investigate a little more to see what is the root of the issue.

**Comment by bbogdanov** [comment]
Found the root of it - 
![image](https://user-images.githubusercontent.com/15037947/109941104-7787c280-7cdb-11eb-8ccc-769097e54c0c.png)


We will need to remove the transform styles cause they are no longer needed. I'll be able to do a PR tomorrow. On the other hand @guetin - it is a good "first issue".

**Comment by guetin** [comment]
I also found this styling but was not able to override it with something like :

.datagrid-compact .datagrid-cell cds-icon, .datagrid-compact .datagrid-cell clr-icon {
  transform: none;
}

Thank you for your response.
