### ISSUE TITLE
Setting css visibility on Alert behaves differently in V5

### ISSUE THREAD

**Issue by grahamford** [vmware/clarity#5685]
## Describe the bug

Setting the visibility on an Alert to "hidden" in Clarity V4 hid the element but retained the positioning. In V5, the icons are still shown.

## How to reproduce

In this example with version 4, there are two alerts but only one is visible.

https://stackblitz.com/edit/clarity-4-alert-examples?file=src%2Fapp%2Fapp.component.html

<img width="500" alt="Screenshot 2021-03-05 at 09 45 22" src="https://user-images.githubusercontent.com/321023/110097934-8338bf00-7d97-11eb-8cba-0d6c8a5721b8.png">

With Clarity V5, although the second alert box isn't visible, the icons are still shown. I tried with the core components and just one of the icons was displayed

https://stackblitz.com/edit/clarity-5-alert-examples?file=src%2Fapp%2Fapp.component.html

<img width="566" alt="Screenshot 2021-03-05 at 09 48 02" src="https://user-images.githubusercontent.com/321023/110098267-e4609280-7d97-11eb-8241-41308093b985.png">

## Expected behavior

The alert in V5 should behave as in V4.

## Versions

**Clarity project:**

- [X] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Comment by bbogdanov** [comment]
Hi @GrahamFord

The second example seems to be broken. Could you please take a look and provide a fixed one?

**Comment by coryrylan** [comment]
The example worked for me, had to reload a couple of times (stackblitz is being flakey). I see the issue. The icon component does not inherit the visibility of the parent style so when the alert or group is hidden it remains visible. This is partially due to how shadow DOM behaves. I think the fix is on our end by putting the following in `icon.element.scss`

```scss
:host {
  visibility: inherit;
}
```

**Comment by grahamford** [comment]
Thanks for taking a look guys. (I'd agree that StackBlitz does seem to be unreliable when building Angular pages).

 I'm trying to upgrade from 4 to 5 and this is the only issue I've come across with the components. Version 5 is looking good 👍

**Comment by coryrylan** [comment]
Fixed in #5711
