### ISSUE TITLE
[react] TextArea component not working properly in Chrome

### ISSUE THREAD

**Issue by andresmgot** [vmware/clarity#5687]
## Describe the bug

When using Chrome + React + Clarity UI + Text Area core component. The Text area cannot be edited:

```ts
import { CdsTextarea } from "@cds/react/textarea";
import React, { useState } from "react";
...
import "@clr/ui/clr-ui.min.css";

function App() {
...
        <CdsTextarea>
          <label>Text area</label>
          <textarea
            id="textarea-1"
            rows={4}
            placeholder={"foo, bar"}
            value={value}
            onChange={onChange}
          />
        </CdsTextarea>
..
}

render(<App />, document.getElementById("root"));
```

The textarea in that case cannot be edited. It's curious but if the textarea is not empty (has some default value) it can be edited but becomes impossible when the value is cleared out.

Apparently the problem is when importing clr css, if I remove the line `import "@clr/ui/clr-ui.min.css";` the textarea works properly (but without style).

It only happens on Chrome, I tried with Firefox and it works properly.

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to https://stackblitz.com/edit/react-cds-textarea-onchange?file=index.tsx
2.  Try to edit the textarea

## Versions

**Clarity project:**

- [X] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [ ] Angular
- [X] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by bbogdanov** [comment]
Seems like the `clr-ui` had some issues and stopped the execution of the rest of the javascript because of 
![image](https://user-images.githubusercontent.com/15037947/110121306-e4c45200-7dc6-11eb-802f-853c5a5d55c4.png)
. 

https://stackblitz.com/edit/react-cds-textarea-onchange-bbkzqk?file=index.tsx Here is a working example using the `core` css

**Comment by gnomeontherun** [comment]
The Clarity Core React package does not depend on @clr/ui styling, so that should not be a dependency unless you are actually using some of those features.

**Comment by andresmgot** [comment]
@bbogdanov @gnomeontherun thanks for the reply!

> Seems like the `clr-ui` had some issues and stopped the execution of the rest of the javascript because of
> ![image](https://user-images.githubusercontent.com/15037947/110121306-e4c45200-7dc6-11eb-802f-853c5a5d55c4.png)
> .
> 
> https://stackblitz.com/edit/react-cds-textarea-onchange-bbkzqk?file=index.tsx Here is a working example using the `core` css

I didn't see that warning, indeed if the javascript is properly loaded the issue disappears :+1: 

> The Clarity Core React package does not depend on @clr/ui styling, so that should not be a dependency unless you are actually using some of those features.

We are working in a fairly big application, not every component is using the Core package yet (we are migrating it little by little).

**Comment by andresmgot** [comment]
> I didn't see that warning, indeed if the javascript is properly loaded the issue disappears 
> 
> >

Actually I was wrong, even without that error the textarea doesn't work :/

Cant `clr-ui` used along with the core package?

**Comment by andresmgot** [comment]
For the record, I managed to workaround it setting the `font` property which is the troubling one:

```
.cds-textarea-fix {
  font: caption;
}
```
