### ISSUE TITLE
[react] Dynamic checkboxes

### ISSUE THREAD

**Issue by andresmgot** [vmware/clarity#5689]
## Describe the bug

Sorry for the brief description, not sure if this is a bug. I was trying to create a dynamic list of checkboxes. See the example:

https://stackblitz.com/edit/react-cds-checkboxes?file=index.tsx

It gave me quite a headache because the new elements were not being added, noticed that the `slots` property was missing (not sure what that does) and I had to add it manually.

**Comment by coryrylan** [comment]
Thank you for the reproduction. Should be able to get this fixed up soon.
