### ISSUE TITLE
Combobox clrOpenChange event fired twice on Tab key when combobox is in closed state

### ISSUE THREAD

**Issue by erabl-identos** [vmware/clarity#5693]
## Describe the bug

Combobox fires obsolete events on the (clrOpenChange) output, when navigating away from a focused but closed combobox using the tab key.

## How to reproduce

1. Go to https://stackblitz.com/edit/clarity-v4-dark-theme-jfuyl2?file=src/app/app.component.ts
2. Open the console
3. Focus the input without opening the menu
4. Hit Tab button
5. Observe 2 subsequent events (open and close).

## Expected behavior

No unneeded events should be observed.

## Versions

**Clarity:**
"@clr/angular": "4.0.12",
"@clr/core": "4.0.12",
"@clr/icons": "4.0.12",
"@clr/ui": "4.0.12"

**Framework:**
Angular 10.2.4

## Additional notes

This seems to be related to https://github.com/vmware/clarity/issues/5553, which was resolved with https://github.com/vmware/clarity/pull/5618 and shipped in v4.0.12

**Comment by coryrylan** [comment]
Thanks for filing this. I was able to replicate the issue from the stackblitz. It is isolated to the tab key focusing away rather than any blur event.
