### ISSUE TITLE
Cannot install @cds/angular for Angular 11 project due to wrong peer dependency on Angular 9

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5696]
## Describe the bug

`npm i` yields the following error when trying to install `@cds/angular` in an Angular 11 project:

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^9.0.0" from @cds/angular@5.0.3
npm ERR! node_modules/@cds/angular
npm ERR!   @cds/angular@"^5.0.3" from the root project
```

## How to reproduce

Try the teps described above.

## Expected behavior

CDS Angular v5 (like CLR Angular) has a dependency on Angular 11, not 9 (https://github.com/vmware/clarity/blob/next/packages/angular/projects/cds-angular/package.json). 

## Versions

**Clarity project:**

- [X] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

## Additional notes

Can be fixed by adding `--force` flag to `npm i` command.

**Comment by bbogdanov** [comment]
Hi @dorthrithil, 

Thank you sharing this with us. 

Seems like you are right and we need to update the deps on our `clr` and `cds` packages. 

We will take some time to investigate if there is anything else that we missed to update and do a PR asap.

**Comment by coryrylan** [comment]
https://github.com/vmware/clarity/blob/next/packages/angular/projects/cds-angular/package.json#L11

**Comment by gnomeontherun** [comment]
The @cds/angular package should allow Angular 9+, so update the dependency requirements to something like `>9`.
