### ISSUE TITLE
List options are not announcing as selected.

### ISSUE THREAD

**Issue by KushalPandya-JS** [vmware/clarity#5697]
**Description:**
Windows + Mozilla:
List items are not reading as selected when user is selecting them.

Mac + Safari:
when navigating through 'Control + option + right/left arrow keys', it is reading as list box Collapse .
When moving one to another list item. It has extra blank navigation.

Here is the live example at Clarity site https://v4.clarity.design/documentation/tree-view#examples.

**Tester Notes:**
the web page should provide sufficient notification and description about any changes to the content on the web page that occur as a result of interaction with a link or button.

WCAG 2.1 Success Criterion 
--
4.1.2

WCAG Conformance Level
--
A

**Comment by gnomeontherun** [comment]
@scroniser Are we tracking this?

**Comment by scroniser** [comment]
@gnomeontherun, yes, we're tracking this. Please let me know if you want the specific issue numbers.

**Comment by KushalPandya-JS** [comment]
Yes, Please provide me.  @scroniser
