### ISSUE TITLE
Core Typography - cds-text="truncate" is cutting letter descenders.

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#5708]
## Describe the bug

The "truncate" transform cut too much. It should only cut horizontal overflow and add ellipsis.

## How to reproduce

1.  Go to https://clarity.design/storybook/core/iframe.html?id=foundation-typography--page&viewMode=story#transforms
2. Observe "Text Truncation (truncate): The quick brown fox jumps over the lazy dog."
3. Verify that letters that have descenders (like these: qjpyg) get cut, as in this screenshot:
![Screenshot 2021-03-10 at 18 39 47](https://user-images.githubusercontent.com/1798828/110667751-3d368d80-81d3-11eb-94f2-66e43095ced5.jpg)

## Expected behavior

Letter descenders are intact

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Comment by Jinnie** [comment]
Research notes:
1. Trying to set overflow only to X axis won't work, because due to browser implementations of the W3C specs, when one of the axes has overflow different from "visible", the other evaluates to overflow: auto, no matter what is actually written in the CSS. So we can't have hidden on one axis and visible on the other.
2. The line gets line-height: 20px from the `[cds-text*='body']` definition, from this property:
```
  --cds-global-typography-body-line-height: 1.2rem;
```
CC @mathisscott, I'd appreciate some comment in which direction we should look for a solution. The body line-height looks a bit suspicious to me, but I have no knowledge about the reasoning behind it.

**Comment by mathisscott** [comment]
@Jinnie 
You should look into disabling the line height erasers when `cds-text` is set to `truncate`
