### ISSUE TITLE
Getting the error: Cannot read property 'production' of undefined

### ISSUE THREAD

**Issue by SameerRathod** [vmware/clarity#5728]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._
![image](https://user-images.githubusercontent.com/3888454/111113651-1d62e900-8588-11eb-9950-6fe89f65b7fe.png)

![image](https://user-images.githubusercontent.com/3888454/111113749-3ec3d500-8588-11eb-8e3b-ac53f294f7ef.png)

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

_A clear and concise description of what you expected to happen._

## Versions

**Clarity project:**

- [*] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [*] v5.x

**Framework:**

- [ ] Angular
- [*] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by SameerRathod** [comment]
If the tag is already initialized, it is not taking environment value see the screenshot attached

**Comment by SameerRathod** [comment]
Temp Fix 
![image](https://user-images.githubusercontent.com/3888454/111114086-c4e01b80-8588-11eb-9889-61ee09c117d6.png)

**Comment by bdryanovski** [comment]
Hey @SameerRathod can you provide some reproducible demo in StackBlitz so we could investigate a little bit more.

**Comment by SameerRathod** [comment]
@bdryanovski We are trying to use it inside our project. There are no particular steps. It was working a few days back and suddenly it stooped. I can share the package.json dependency. and index.js where we are importing the moduels. Apart from that, we have done nothing it's a  simple project. 

Package.json
"dependencies": {
    "@cds/core": "^5.0.3",
    "@cds/react": "^5.0.3",
    "@clr/core": "^4.0.8",
    "@clr/icons": "^4.0.6",
    "@clr/react": "^4.0.8",
    "@clr/ui": "^5.0.0",
    "@emotion/core": "^11.0.0",
    "@emotion/react": "^11.1.1",
    "@emotion/styled": "^11.0.0",
    "@material-ui/core": "^5.0.0-alpha.16",
    "@material-ui/icons": "^4.9.1",
    "@testing-library/jest-dom": "^5.11.5",
    "@testing-library/react": "^11.1.1",
    "@testing-library/user-event": "^12.2.0",
    "@vmware-react/clarity": "^0.5.22",
    "@webcomponents/custom-elements": "^1.4.3",
    "array-move": "^3.0.1",
    "axios": "^0.21.1",
    "babel-jest": "^26.6.0",
    "bootstrap": "^4.5.3",
    "jquery": "^3.5.1",
    "jwt-decode": "^3.1.2",
    "react": "^17.0.1",
    "react-avatar": "^3.9.7",
    "react-bootstrap": "^1.4.0",
    "react-dom": "^17.0.1",
    "react-drag-listview": "^0.1.8",
    "react-iframe": "^1.8.0",
    "react-native-segmented-progress-bar": "^1.0.10",
    "react-paginate": "^7.1.0",
    "react-pdf": "^5.1.0",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.0",
    "react-sortable-hoc": "^1.11.0",
    "react-spring": "^8.0.27",
    "react-tooltip": "^4.2.11",
    "reactjs-mappletooltip": "^1.4.63",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "rxjs": "^6.6.3",
    "styled-components": "^5.2.1",
    "web-vitals": "^0.2.4"
  },


Index.js

import React from 'react';
import ReactDOM from 'react-dom';
import { Route, Link, BrowserRouter as Router } from 'react-router-dom';
// import '../node_modules/@clr/icons/clr-icons.min.css';
// import '../node_modules/@cds/core/global.min.css';
import '../node_modules/@vmware-react/clarity/dist/react-clarity.css';

import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import configureStore from './Store';
import { Provider } from 'react-redux';
import './fonts/Metropolis/Metropolis-Regular.otf';
// import '@cds/core/modal/register.js';
import '@cds/core/internal/utils/register.js';
import '@cds/core/icon/register.js';
import '@cds/core/divider/register.js';
import '@cds/core/button/register.js';
import '@cds/core/modal/register.js';
import '@cds/core/search/register.js';
import '@cds/core/radio/register.js';
import '@cds/core/select';
import '../node_modules/@clr/ui/clr-ui.min.css';
import '../node_modules/@clr/icons/clr-icons-lite.min.js';
import '../node_modules/@clr/icons/shapes/all-shapes.min.js';

import { ClarityIcons, userIcon } from '@cds/core/icon';

ClarityIcons.addIcons(userIcon);

const store = configureStore();

const routs = (
  < Router >
     <div>
        <Route path="/" component={App} />
     </div>
  </  Router >
);

ReactDOM.render(
  <Provider store={store}>
    {routs}
  </Provider>,
  document.getElementById('root')
);


reportWebVitals();

**Comment by bdryanovski** [comment]
Sorry, @SameerRathod I could not reproduce your issue. We gonna need something that is running and we could debug, this snippet above is not giving us the how picture, you may have some issue inside the webpack or some optimization, or some code could overwrite it !?

**Comment by gnomeontherun** [comment]
We do need a reproduction of the issue more simply to triage. However, it also seems like the main issue is the context that you are trying to call for the CDS properties is running before the web components have been bootstrapped, so it is likely some issue with the ordering of calls. You might also just guard against undefined errors by checking the object property presence before using it.

**Comment by SameerRathod** [comment]
@gnomeontherun Thanks.. that helped I pasted all the CDS statements just after importing react and it worked. Seems like it is not getting registered or since we have multiple versions of clarity it was conflicting with the object structure. 
We had placed a temp patch as an if condition in utils/register.js to check if the environment key on the window.CDS exists or not.
