### ISSUE TITLE
Compatibility issue with Firefox 43

### ISSUE THREAD

**Issue by zsamvm** [vmware/clarity#573]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The wizard should pop up on browser.

### Actual behavior

The wizard does not pop up on browser in Firefox 43

### Reproduction of behavior

Simply go to clarity official website using Firefox 43, go to the wizard page, and the issues will be presented there.

### Environment details

Firefox 43.0.4

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
FireFox 43 is not a supported browser for Clarity. We support two versions back. Firefox is currently at 52 so 43 is not supported. Closing based on that.
