### ISSUE TITLE
Disabled control group doesn't disable the controls

### ISSUE THREAD

**Issue by bbogdanov** [vmware/clarity#5734]
## Describe the bug

`CdsInternalControlGroup` disabled property doesn't disable the controls inside the group container.

`disabled` attribute is not passed to the controls inside the group container.

## How to reproduce

https://codesandbox.io/s/control-group-disabled-e973f

Click on any of the checkboxes.

## Expected behavior

Any of the controls inside a child of `CdsInternalControlGroup` should be disabled when the group has a `disabled` property.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [x] v5.x

**Comment by bbogdanov** [comment]
#5633

**Comment by gnomeontherun** [comment]
@coryrylan is this expected to be done automatically or do apps need to set disabled themselves?

**Comment by coryrylan** [comment]
This is a bug, setting it should set disabled on the child controls of the group. I think the fix is in the `updated` method of `control.element.ts` add a `syncProps` call to sync the disabled property.

```typescript
  updated(props: Map<string, any>) {
    super.updated(props);
    this.messages.forEach(message => syncProps(message, this, { disabled: props.has('disabled') }));

    // when the internal disabled is set by the group this will sync the native input
    syncProps(this.inputControl, this, { disabled: props.has('disabled') }); 
  }
```
