### ISSUE TITLE
Need to disable steps in prepopultaed wizard

### ISSUE THREAD

**Issue by anilrautvc** [vmware/clarity#5747]
## Describe the bug

I have a wizard with 5 steps, i am prepopulating data in the wizard and showing the last or 4th step of wizard when its open.
I want the second and third step to be grayed out or not clickable in the side nav.

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

_Please provide a link to a reproduction scenario using one of the [Clarity Stackblitz templates](https://stackblitz.com/@clr-team). Reports without a clear reproduction may not be prioritized until one is provided._

1.  Go to '...'
Here is the sample i am trying https://stackblitz.com/edit/clarity-v4-dark-theme-2wrkqy
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior
I have a wizard with 5 steps, i am prepopulating data in the wizard and showing the last or 4th step of wizard when its open.
I want the second and third step to be grayed out or not clickable in the side nav.
_A clear and concise description of what you expected to happen._

In this sample = https://stackblitz.com/edit/clarity-v4-dark-theme-2wrkqy
I want to disable Step 2 and Step 3 so it should not be clickable in the left navigation and while hitting the back button from Step 5 it should move from Step 5 to Step 4 and then jump to Step 1 instead of Step 2 and 3.
I should not see the page content for Step 2 and Step 3.

Similarly while clicking next from Step 1 it should jump to Step 4 and by pass Step 2 and Step 3.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by bdryanovski** [comment]
You could read more on how to do that [here](https://v4.clarity.design/documentation/wizards) into the "Preventing Navigation and Disabling the Stepnav" section.

**Comment by anilrautvc** [comment]
> Disabling the Stepnav
@bdryanovski Thanks for your suggestion, i read through the section "Preventing Navigation and Disabling the Stepnav" in the link provided. As per the document if i set this property clrWizardDisableStepnav = true for the wizard its disable click on the entire left nav.
My requirement is i want to gray or disable ONLY the Step 2 and Step3 in the left nav of the wizard, please refer to the following snapshot

![image](https://user-images.githubusercontent.com/35384163/111536415-37dbc480-8738-11eb-8eb6-46e1a6c26cb3.png)

I have also tried the following code but its disabling navigation for the entire left nav on the wizard.
this.page2.navService.wizardDisableStepnav = true;
this.page3.navService.wizardDisableStepnav = true;

Not sure if there is a way to only disable Step 2 and Step 3 in the wizard, i would appreciate if you can modify my stackblitz https://stackblitz.com/edit/clarity-v4-dark-theme-2wrkqy sample with your suggestion.

While hitting the back button from Step 5 it should move from Step 5 to Step 4 and then jump to Step 1 instead of Step 2 and 3.
I should not see the page content for Step 2 and Step 3.
