### ISSUE TITLE
Button width re-sizing on click event when it has `[clrLoading]`

### ISSUE THREAD

**Issue by AamirSaeedCL** [vmware/clarity#5749]
The button with `[clrLoading]` to showing loading get resize in width on click event. It gets small in width and then get back to normal immediately when spinner start moving inside it. 

## How to reproduce
Have  a simple button on form with `[clrLoading]` and call an api with some delay.

Run the page
Click the button (should have `clrLoading`
see an issue

## Expected behavior

It shouldn't resize.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [x ] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: [Dell]
- OS: [Windows 10]
- Browser [chrome]

## Additional notes

None.

![image](https://user-images.githubusercontent.com/16438909/111444335-2b3c7980-8702-11eb-91d7-96bcdd4f1012.png)

**Comment by bdryanovski** [comment]
@AamirSaeedCL can you provide some working demo on the issue. 

I try to reproduce the issue [here](https://stackblitz.com/edit/angular-qnfyvt?file=src/app/app.component.ts) and I'm not seeing any change in size.

If you start the button with a loading state and then change the content inside the button it's normal to get some different size of the button - cause at that stage the button size is loading icon size.

**Comment by gnomeontherun** [comment]
This issue does not have a reproduction and we are going to close it as stale. If the issue persists, please provide a working [Stackblitz demo](https://stackblitz.com/@clr-team) and we can reopen to review.
