### ISSUE TITLE
Pagination total item count cannot be applied where it is at a callback function.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#575]
I found it has no effect when I set the total items count in a http service callback method. 
This value can be effective when I directly set to the tag or set it outside the callback method as a property.

` this.auditLogService`
` .listAuditLogs(this.queryParam)`
`.subscribe(`
` response=>{`
` this.total = response.headers.get('x-total-count');  //has no effect to the pagination component.`
`},`
`error=>{`
`...`
`}`
`);`

`this.total = 8; ` 
or 
`<clr-dg-pagination [clrDgTotalItems]="total"></clr-dg-pagination>`
or
`<clr-dg-pagination [clrDgTotalItems]="8"></clr-dg-pagination>`
Both of them are OK.

**Select one ...**  (check one with "x")
```
[] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
Want to set the value at callback.

### Actual behavior
Cannot apply to the pagination, but the value actually set.

### Environment details

* **Angular version:** 2.4.1

* **Clarity version:** 0.8.6

* **OS and version:** OS X

* **Browser:** [all | Chrome 56 ]

**Comment by youdz** [comment]
Please post a plunker reproducing this. As far as we've tried, dynamic values for total number of items do work in pagination. Thank you.

**Comment by wknet123** [comment]
Sorry for my misunderstanding, I've retried and solved this issue. Thanks again.
