### ISSUE TITLE
Add Clarity-styled select[multiple="true"] element to Clarity

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#576]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Users can add a `<select multiple="true">` element to a Clarity that has Clarity styles to it.

### Actual behavior
Nada. Zilch. Nothing-a-rooni.

### Environment details

* **Clarity version:** 0.8.10

NOTES
===
We hit problems with styling the selected color of multi-selects. We can further research if there's a viable way to do it but there doesn't appear to be a good cross-browser solution.

At a bare minimum, multi-selects should look like our text areas.

If we cannot set the selected color to a Clarity color, we should note this in the documentation.

We will also need to document this twist on the HTML select element in Clarity.

Example:
<img width="1317" alt="screen shot 2017-03-09 at 8 36 20 am" src="https://cloud.githubusercontent.com/assets/2728359/23754998/977d1076-04a4-11e7-9134-a7e1bdab5322.png">

Relevant JSFiddle
http://jsfiddle.net/dcgs3zqh/

**Comment by mathisscott** [comment]
Adding UX input so they can take a swing at this before implementation...

**Comment by reddolan** [comment]
The visual example you provided will work for now. It makes it usable. We can circle back on this later if we get feedback that folks want it Clarity-styled
