### ISSUE TITLE
@cds/react install version 5 and above throwing undefined error when start up react dev server

### ISSUE THREAD

**Issue by MRHarrison** [vmware/clarity#5767]
## Describe the bug

After `yarn install @cds/react @cds/core` and then startup of the react dev server `yarn start` I get this error from the react dev server:

```
TypeError: Cannot read property 'production' of undefined
notProductionEnvironment
src/internal/services/log.service.ts:34
  31 | }
  32 | 
  33 | function notProductionEnvironment() {
> 34 |   return !window.CDS.environment.production;
  35 | }
  36 | 
```
`
## How to reproduce

You don't have a react template

1.  `yarn install @cds/react 5.1 or >`
2.  `yarn start` react dev server
3.  Yarn dev server output in the browser shows `TypeError: Cannot read property 'production' of undefined`

## Expected behavior

No error in the dev server

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: React 17.0.1

**Device:**

- Type: MacBook
- Browser [e.g. brave]

**Comment by coryrylan** [comment]
Do you have a reproducible example that you can post? I could not get this using https://create-react-app.dev/ My concern is how the code reaches that far without initializing our CDS object. There might be an issue with the modules loading properly dependent on the toolchain.

**Comment by gnomeontherun** [comment]
This issue does not have a reproduction and we are going to close it as stale. If the issue persists, please provide a working reproduction and we can reopen the issue.
