### ISSUE TITLE
Combobox validation and value selections issues

### ISSUE THREAD

**Issue by alexpichler99** [vmware/clarity#5782]
## Describe the bug
There are two issues with the combobox:

1. If a set value in the combobox is opened and a result is clicked, the dropdown stays open
2. If a value is selected in the combobox, a required validation error appears 

## How to reproduce the first issue

https://stackblitz.com/edit/issue-4938-2-vzaypl?file=package.json

1.  Select a value in the combobox
2.  Open the combobox again and click on the set value
3.  The combobox doesn't close

![bug1](https://user-images.githubusercontent.com/17060999/112804302-8ceed300-9074-11eb-933b-37e285fa99a7.gif)

## Expected behavior

The combobox should close when clicking on the set value.

## How to reproduce the second issue

I didn't manage to create a stackblitz for it because when I tried to create a form for the required validation, I got this error:
`Error in /turbo_modules/@clr/angular@5.0.0/bundles/clr-angular.umd.js (2:111)
Unexpected token 'export'`

1.  Select a value in the combobox
2.  A validation error is shown that a brand is not selected

![image](https://user-images.githubusercontent.com/17060999/112806850-84e46280-9077-11eb-81fe-c651eeb38a23.png)

## Expected behavior

A validation error should not be shown

## Versions

**Clarity project:**

- [x ] Clarity Core
- [x ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x ] v5.x

**Framework:**

- [x ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: Thinkpad
- OS: Windows 10
- Browser Chrome
- Version 89.0.4389.90 

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
@Jinnie - looking into `clr-option` code and the `option-selection.service.ts` The behavior for the first issue here seems correct. Can you confirm that we do not want to close the option-items list if the user clicks a currently selected option?

@alexpichler99 - I created a simple combobox with validation that works as follows:

1. no error on initialization.
2. select an option and close options list -> no error
3. remove the selection option value -> error is shown

I believe this is how it should work. Please fork and update [this reproduction ](https://stackblitz.com/edit/gh-5782-click-selected-to-close-and-combobox-validaion?file=src/app/app.component.html)so I can see what is different between the simple worked demo and a demo that breaks.

**Comment by alexpichler99** [comment]
@hippee-lee Thanks for providing the stackblitz. With that I found out that the validation issue was an error on my side.

But I still think that the issue with the combobox staying open should be fixed because it doesn't seem intuitive.

**Comment by Jinnie** [comment]
The combobox is a complex component that tries to cover many scenarios at once. This will inevitably lead to not being able to cover each and every one scenario in the most optimal way.
The choice to keep it open comes from the need to be able to select many items subsequently. Especially for an accessibility user, who only uses the keyboard, the inconvenience to have to open the menu again and navigate to the correct element is quite big. We already do have some ideas on simplifying it and improving the accessibility for the Clarity Core version of the combobox.
Thanks for the report and research.
