### ISSUE TITLE
[Documentation improvement] Signpost vs. helper message 

### ISSUE THREAD

**Issue by yuxin-ux** [vmware/clarity#5786]
This is based on a conversation that happened during a Clarity office hour. The suggestion was to add a comparison between when to signpost vs. helper message. 
Colin and I both agree that it can be helpful to the broader audience. Let's add the information to the end of the Usage section in the signpost documentation to provide guidance. See the attached image for details. The figma file can be found [here](https://www.figma.com/file/8UgpkpTtxgxTfmESNl8sSc/Signpost-vs-helper-message?node-id=0%3A1)

If we don't want to spend time on the angular documentation anymore, we can add this section when signpost becomes available in core. 

![image](https://user-images.githubusercontent.com/33043434/112917965-a580dc80-90b8-11eb-97b3-1c2305426a1e.png)

**Comment by hippee-lee** [comment]
I'm adding a label to this [blocked by core]. In order to implement this as a demo that readers can interact with the website needs the core component which will work natively in the browser.
