### ISSUE TITLE
Styling issue with clr-control-container within form

### ISSUE THREAD

**Issue by drourke2** [vmware/clarity#5787]
There is a styling issue with controls within a form.  When the control is focused the focus (underline) extends beyond the control to fill the entire width of the form.

Not in focus:

<img width="452" alt="Screen Shot 2021-03-30 at 9 06 21 AM" src="https://user-images.githubusercontent.com/48953195/112993895-af95f000-9137-11eb-83d6-2906aa6834ea.png">

In focus:

<img width="446" alt="Screen Shot 2021-03-30 at 9 10 32 AM" src="https://user-images.githubusercontent.com/48953195/112994021-cf2d1880-9137-11eb-8d8c-2bcd6e451093.png">

Reproduce via stackblitz.io:

https://clarity-v4-light-theme-iv2dee.stackblitz.io

Angular: 10.2
Project Clarity: 4.0.12 

Regards,
David

**Comment by Jinnie** [comment]
It's common issue for several different form elements. I think it was already fixed for datalist at least.

**Comment by Jinnie** [comment]
I found it:
https://github.com/vmware/clarity/issues/5269
There is an open PR for the above.
Closing this one as duplicate. Thanks for reporting.
