### ISSUE TITLE
Unable to run "ng add @clr/angular" with npm 7pm 

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#5788]
npm 7 has a breaking change - automatically installs peer dependencies.
We need to add the correct peerDependencies in package.json
The currently released version of @clr/angular has no @clr/icons peerDependency at all. That's why it resolves to undefined thus to 0.0.0

1.  Use npm v7 (comes with node v15)
2.  ng new test
3. cd test
4. ng add @clr/angular
5.  See error
```
Installing packages for tooling via npm.
An unhandled exception occurred: npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ui@0.0.0
npm ERR! Found: @clr/icons@5.1.0
npm ERR! node_modules/@clr/icons
npm ERR!  @clr/icons@"^5.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @clr/icons@"0.0.0" from @clr/ui@5.1.0
....................
```

## Expected behavior

No errors

**Comment by ph55** [comment]
Should be fixed by https://github.com/vmware/clarity/issues/5762

**Comment by Jinnie** [comment]
Yes, thank you, @ph55 
That's the fix that was needed.
