### ISSUE TITLE
New Icons to publish Vol. 4 (2 of 2)

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#579]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Here are this week's icons to be implemented

![image](https://cloud.githubusercontent.com/assets/23196444/23774100/f32ce2d4-04d6-11e7-992f-444720366b0c.png)

@Shijir 
**SVG Icons:**  [vol4_svg_2of2.zip](https://github.com/vmware/clarity/files/832469/vol4_svg_2of2.zip)
**Addendum - SVG Icons:**[thumb_down.zip](https://github.com/vmware/clarity/files/832568/thumb_down.zip)

*NOTE: This zip contains an update of mobile_phone_line.svg and mobile_phone_solid.svg. Please replace the previous version. Thanks!

**Comment by Shijir** [comment]
@lil-kim They look great! Thank you!
