### ISSUE TITLE
Headers are broken

### ISSUE THREAD

**Issue by wendellestradairely** [vmware/clarity#5791]
In the version 5.0, the header actions are broken. It's just showing a loading indicator and an inverted caret.

![image](https://user-images.githubusercontent.com/50942719/113383399-6bfce980-93b6-11eb-8e82-0f24137bc5cf.png)

Even in the Angular samples in the documentation website are inverted.
![image](https://user-images.githubusercontent.com/50942719/113383481-9c448800-93b6-11eb-8676-e0ca7f9eba2a.png)

Code:

```<div class="header-actions">
			<div class="dropdown bottom-left">
				<button class="nav-icon dropdown-toggle" aria-label="toggle settings menu">
					<clr-icon shape="cog"></clr-icon>
					<clr-icon shape="angle" direction="down"></clr-icon>
				</button>
				<div class="dropdown-menu">
					<a href="javascript://" class="dropdown-item">About</a>
					<a href="javascript://" class="dropdown-item">Preferences</a>
					<a href="javascript://" class="dropdown-item">Log out</a>
				</div>
			</div>
		</div>```

**Comment by hippee-lee** [comment]
@wendellestradairely - I tracked down the underlying issue for the caret rotation. Basically the @clr/ui css was preventing the direction functionality built into cds-icon. 

As far as the loading indicator - I'm unable to recreate or see that locally or on the docs. That three dot _loading_ indicator means that the Icon was not loaded into the browser. Any more details or a stackblitz recreating it would be appreciated.

**Comment by wendellestradairely** [comment]
Thanks @hippee-lee. Regarding the icon, I don't have an issue with it anymore. It's because I used cds-icon instead of clr-icon. I haven't migrated to the core icons yet.
