### ISSUE TITLE
Flip the toggle so angular dark mode styles use css vars

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#5793]
Dark mode angular styles are not using css vars. Now with IE no longer supported, we should be able to flip the $clr-use-custom-properties toggle so css vars are created and used.

This will make life using dark mode easier to use, especially for us having custom controls and pages using the variables and trying to conform and align withe clarity colors.

Step 2 would be if dark mode using the same css styles as light and only updates the css vars needed. But this may be a breaking change.

**Comment by sis0k0** [comment]
@rbirkgit, can you please share more about your use case?

**Comment by sis0k0** [comment]
Blocked by https://github.com/vmware/clarity/pull/5765.

**Comment by rbirkgit** [comment]
The main goal is to be able to use only the main light theme and be able to switch to dark mode with only css vars overrides. Same as in Clarity Core. We are very close.
