### ISSUE TITLE
loadingState error when using CdsButton in React with Typescript

### ISSUE THREAD

**Issue by wghglory** [vmware/clarity#5795]
## Describe the bug

I'm using react and typescript. When writing CdsButton, loadingState always raised an error: Type '"loading"' is not assignable to type 'ClrLoadingState | undefined'.

## How to reproduce

```jsx
import { CdsButton } from '@cds/react/button';

export default function Test() {
  return (
    <CdsButton loadingState={'loading'} size='sm'>
      Test
    </CdsButton>
  );
}
```

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Framework version:**
React 17 + typescript 4.1.2

**Comment by sis0k0** [comment]
@wghglory, thank you for reporting this issue! We'll take a look into it and provide a fix as soon as we can.

**Comment by wghglory** [comment]
> @wghglory, thank you for reporting this issue! We'll take a look into it and provide a fix as soon as we can.

Thanks so much!

**Comment by sis0k0** [comment]
@wghglory, we just shipped the fix for this issue 🎉  To get it, update `@cds/core` and `@cds/react` to `5.1.1`.

**Comment by wghglory** [comment]
@sis0k0 Many thanks, I will update to 5.1.1!
