### ISSUE TITLE
New icon request for project VMware Marketplace

### ISSUE THREAD

**Issue by kavitab1980** [vmware/clarity#5811]
_Please review our [Contribution guide](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md) for more details about how to contribute effectively._

## Summary

_Describe the change or feature in detail. Try to answer the following questions._

Need a new icon for VMware Marketplace site 
1. Identity 
2. Internet of things
3. Artificial Intelligence

- Why should it go in Clarity?
These are widely used in our domain and I am sure other product teams might need it sometime.

- Does this change impact existing behaviors? If so how?
No
- If this change introduces a new behavior, is this behavior accessible?
No

## Use case
Need icons to add in a category section. These are the main touch points on Marketplace site. Users can click on it to see relevant Apps/Services/Solutions belong to that category.

_Provide some specific details about how this change would improve your application and use case._
These are visual cues to help users quickly find the category they are looking for. 

## Examples

_If possible, show examples of the change. You may create one yourself, or link to external sites that have the idea. It can also be very useful to prototype the idea in isolation outside of Clarity with a [Stackblitz example](https://stackblitz.com/@clr-team)._ !
[Screen Shot 2021-04-07 at 4 42 23 PM](https://user-images.githubusercontent.com/82118076/113924478-3db94880-97c0-11eb-88e2-a79363ac73fb.png)
![Screen Shot 2021-04-07 at 4 43 18 PM](https://user-images.githubusercontent.com/82118076/113924591-5d507100-97c0-11eb-8d0e-cc34016b797b.png)
![Screen Shot 2021-04-07 at 4 43 50 PM](https://user-images.githubusercontent.com/82118076/113924646-70634100-97c0-11eb-8676-dc3adb81e6bf.png)

## API

_Describe the intended API for the feature you want to add. This would include:_

- CSS classes and DOM structure for pure static UI contribution, and inputs/outputs, components, directives, services, or anything that is exported publicly for Angular contributions.
- Examples of code snippets using this new feature.
- Note very clearly if anything **might** be a breaking change.

_In the case of bug fixes or internal changes, there will most likely be no API changes._

## Implementation plan

_Describe how you plan to implement the feature, answering questions among the following or anything else you deem relevant._

- What parts of the code are affected?
- Will you introduce new services, components or directives?
- Can you describe the basic flow of information between classes?
- Does this introduce asynchronous behaviors?
- Will you need to refactor existing Clarity code?
- Will reasonable performance require optimizations?
- Will it need to access native elements (and be incompatible with server-side rendering)?
- ...

## Conclusion

_Describe how long you expect it to take to implement, what help you might need, and any other details that might be helpful. Don't worry, this is obviously non-contractual. 😛_
We have 2 Weeks time to deliver it to development team.

**Comment by hippee-lee** [comment]
Thanks for the contribution offer, I'll discuss with the team and get back to you.

**Comment by gnomeontherun** [comment]
@kavitab1980 could you post in the Clarity slack about this? This is not the correct place for requesting internal icons. I'm going to close this as the wrong place to ask.
