### ISSUE TITLE
Copy the icons that are used inside Datagrid group buttons to core-shapes package

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#582]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Icons that are used in Clarity components should be in `core-shapes` package. 

### Actual behavior

Some icons used in Datagrid aren't copied into `core-shapes` package. As a result, users loading the lite version of `clarity-icons` will see `error` icons as well as console errors.

<img width="618" alt="screenshot 2017-03-10 02 14 07" src="https://cloud.githubusercontent.com/assets/3958008/23791538/279b312c-0538-11e7-9639-36eefaf61ed8.png">

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
This issue can be resolved in the same PR with https://github.com/vmware/clarity/issues/579

**Comment by youdz** [comment]
Wait, these icons are _not_ used in Datagrid! We don't want to bloat the core shapes with them.
They are used in the Datagrid *demos*, which is completely different. We can just have the website  and demo apps load the corresponding shapes too.

But really, don't add them to core shapes, it makes no sense.

**Comment by Shijir** [comment]
I see. I was playing the on the demo app and wrongly assumed those were built-in features in Datagrid. My bad, so closing this now.
