### ISSUE TITLE
Modal [clrModalSkipAnimation] type missmatch in docs 

### ISSUE THREAD

**Issue by ph55** [vmware/clarity#5825]
https://clarity.design/angular-components/modal/api/

In docs `[clrModalSkipAnimation]` is `boolean` when in fact it's required to be sent as `string`:
https://github.com/vmware/clarity/blob/e28c89b74aad11aeb861ca5cd4a569d9953e8b96/packages/angular/projects/clr-angular/src/modal/modal.ts#L62

**Comment by sis0k0** [comment]
Thank you for reporting that! We'll fix it with the next release of the Clarity website.
