### ISSUE TITLE
Datagrid style looks broken during filtering 

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#583]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

Initial state:

<img width="1147" alt="screenshot 2017-03-10 02 26 07" src="https://cloud.githubusercontent.com/assets/3958008/23791899/a9fe047c-0539-11e7-8c26-8f8c9c128326.png">

it looks like some parts of datagrid get cut off once a user starts typing in something inside the filtering input:

<img width="1153" alt="screenshot 2017-03-10 02 26 23" src="https://cloud.githubusercontent.com/assets/3958008/23791895/a5516d1a-0539-11e7-95d8-ac8c4ec16dd8.png">

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@adityarb88 : Could you verify whether this is still an issue or not after your PR goes in?

**Comment by adityarb88** [comment]
@mathisscott: It is. I linked it. But I am doubtful if my PR will go in tomorrow :-(

**Comment by mathisscott** [comment]
No worries. If you feel it can make it into 0.9.2, would you mind moving it to that milestone?
