### ISSUE TITLE
Icons in small buttons are too big and misaligned with Clarity v5

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#5832]
## Describe the bug

I noticed with latest Clarity Angular (compared to v4) the small buttons with images has changed. The images are larger and misaligned. In v4 there was a style for the images in small buttons fixing this, but this style seems gone in v5.

## How to reproduce

A simple small button with an icon. It seems the style for the small icon changed to only support cds-icon:

v4:
.btn-sm:not(.btn-link) clr-icon, .alert-app-level .alert-item .btn:not(.btn-link) clr-icon  {
}

v5:
.btn-sm:not(.btn-link) cds-icon, .alert-app-level .alert-item .btn:not(.btn-link) cds-icon {
}

## Expected behavior

Support both cds-icon and clr-icon

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Comment by sis0k0** [comment]
Fixed with #5835. Will be shipped with the next release.
