### ISSUE TITLE
Signpost scss for angular light theme is not using css vars in some places

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#5836]
## Describe the bug

When the signpost scss got updated to use css vars, there were a few places missed, e.g.:

```
&.bottom-right {
  .popover-pointer {
    border-bottom: $clr-signpost-pointer-border;
    top: -1 * $clr-signpost-border-size + $clr_baselineRem_1px;
    &:before {
      border-bottom: $clr-signpost-pointer-psuedo-border;
      top: $clr_baselineRem_2px;
    }
  }
}
```

## How to reproduce

Using the light theme and overriding the css vars (with dark theme colors for example) the tip of the signposts remain white. This because of some places are still hard coded colors.

## Expected behavior

The tip of signpost to also use css vars

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [x] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 10/11

**Comment by rbirkgit** [comment]
I'm too lazy to open a new bug, but similar issue in the .nav style where it's not using css var:

```
.nav {
  display: flex; //For the elements inside the nav
  height: $clr-subnav-height;
  list-style-type: none;
  align-items: center;
  box-shadow: 0 (-1 * $clr_baselineRem_1px) 0 $clr-nav-box-shadow-color inset;
```

**Comment by sis0k0** [comment]
Thanks for reporting this again! The fix will be shipped with the next release of Clarity.
