### ISSUE TITLE
Dark theme angular uses old rem sizes

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#5837]
## Describe the bug

The dark theme file for angular uses the old style rems, i.e. the numbers directly instead of the rem variables. This causing border sizes that should be 0.6rem be rendered as 0.5rem

## How to reproduce

`$clr-signpost-border-size: 0.5rem;
`

Using above variable gives wrong size.

## Expected behavior

Update theme file to use remvariables to get correct sizes

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11/10

**Comment by sis0k0** [comment]
Fixed with #5855. It will be shipped with the next release.
