### ISSUE TITLE
Align clarity-ui focus styles

### ISSUE THREAD

**Issue by leonardb** [vmware/clarity#5839]
## Describe the bug

It seems that for certain form elements in Core there is no removal of the browser default for :focus and the elements are having a 1px border applied.

Primary affected components:
checkbox
radio
textarea
range
toggle

Additionally, this behaviour seems to occur not only for form elements but for any element which does not have an override for :focus.

It appears that 'input' type elements are not affected as they have overriding styles applied.

For example, inspecting a focused textarea control show the following as a 'user agent stylesheet' applied properties
```
textarea:focus {
    outline-offset: 0px;
}
:focus {
    outline: -webkit-focus-ring-color auto 1px;
}
```

## How to reproduce

Using Chrome browser the behavior can be seen at:
https://clarity.design/storybook/core/?path=/story/forms-textarea--page
and
https://clarity.design/core-components/textarea/

## Expected behavior

I would expect that no border be added to the elements.

## Versions

**Clarity project:**

- [X] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
unknown

**Device:**

- Type: MacBook, Desktop, Android Mobile
- OS: Mac, Ubuntu Xenial, Android
- Browser: Chrome
- Version multiple

**Comment by sis0k0** [comment]
@jeeyun, it seems that Core form components have that behavior built-in. Do you think that's expected or is it something we should fix?

**Comment by leonardb** [comment]
I'd expect that the behavior/styling of the core components would match the Angular components, no?

If the plan is to deprecate the Angular components in favor of the Core components should the styling/behavior not remain consistent between the two?

**Comment by coryrylan** [comment]
This styling is due to Clarity UI applying a custom CSS box shadow when elements are focused. The Core components default to the native browser focus style as it can [provide better a11y](https://coryrylan.com/blog/dont-override-css-outline-focus-styles). The native focus auto adjusts the color based on the background contrast levels. I am adjusting this issue to determine how we would like to align the Clarity UI focus style to match Core.

**Comment by Jinnie** [comment]
Fixed in v12 and v5
