### ISSUE TITLE
nav style is not using css var

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#5841]
## Describe the bug

The nav style missed a place to use css vars (for box shadow):

```
.nav {
  display: flex; //For the elements inside the nav
  height: $clr-subnav-height;
  list-style-type: none;
  align-items: center;
  box-shadow: 0 (-1 * $clr_baselineRem_1px) 0 $clr-nav-box-shadow-color inset;
```
  

## How to reproduce

Using the light theme and overriding the css vars (with dark theme colors for example) the undeline of the navbar remains white. This because of hard coded colors.

## Expected behavior

The navbar to use css vars

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [x] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 10/11

**Comment by mathisscott** [comment]
I believe a fiix for this was merged with PR #5856
