### ISSUE TITLE
Form alignment broken in cds-modal popup

### ISSUE THREAD

**Issue by hofalk** [vmware/clarity#5844]
## Describe the bug

Using cds form elements inside a cds-modal that is dynamically shown seems to break the column alignment for a horizontal form layout. 

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v5-lzkql3?file=src/app/app.component.ts

1.  Click on 'show modal'
2.  See vertical misalignment of the form labels and input fields

## Expected behavior

The form is aligned in columns of equal width.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: Thinkpad
- OS: Arch Linux
- Browser: Chrome
- Version: 89

## Additional notes

The form is aligned okay, if the modal is already visible on page load (e.g. change AppComponent show property to start as 'true' in the stackblitz above).

On a sidenote: the implicit htlm5 sync validation for the form also does not seem to work properly... (no style changes, and cds-control-messages are just always visible) but this is probably unrelated and a different bug !?

**Comment by coryrylan** [comment]
For forms to auto align they must be able to measure the parent container size when the form is created. Rather using `hidden` on the modal try using `*ngIf`

https://stackblitz.com/edit/clarity-light-theme-v5-an4se6?file=src%2Fapp%2Fapp.component.html

```html
<cds-modal *ngIf="show">

</cds-modal>
```

**Comment by hofalk** [comment]
Ah, ok I see, that does fix the alignment issue. Thanks!

Unfortunately it only seems to cover part of the problem in cds-modals.

As soon as I add separate sections like cds-modal-content the form alignment does not work as expected anymore.
E.g. vertical Forms do not stretch to the width of the modal (even though the cds-modal-content element does)
Modified example: https://stackblitz.com/edit/clarity-light-theme-v5-phpfjg?file=src/app/app.component.html

Or is this expected?

**Comment by coryrylan** [comment]
This is due to the form element not spanning the container and constraining the form group. Try adding this to the form
`<form style="width: 100%;">`

**Comment by hofalk** [comment]
Alright, that did it. Thanks a lot for your help @coryrylan.

Still wondering: from what I could gather from the documentation (e.g. https://clarity.design/storybook/core/?path=/story/components-modal--page#scrolling-modal-content) it seems like the "hidden" attribute should be used for most cases when showing the modal.

It also has the show/hide animation associated with it, which is quite nice and configurable through the component API to some extent. This is lost if you make use of *ngIf instead of hidden.

If "form" modals need to use *ngIf tor visibility, how would I make sure it stays "compliant" to the official API and can make use of e.g. those animation features?

**Comment by coryrylan** [comment]
I think I can find a way to get the form auto label alignments to work with hidden/modal better. Likely we could use something like the Intersection Observer API to do this. I opened a new issue to investigate improving this so you will be able to use hidden. https://github.com/vmware/clarity/issues/5930

**Comment by coryrylan** [comment]
Closing as has workaround and needed fix described in https://github.com/vmware/clarity/issues/5930
