### ISSUE TITLE
clr-control-error doesn't show error message unless you click some where else on screen for the first time

### ISSUE THREAD

**Issue by vinayvivekananda** [vmware/clarity#5847]
## Describe the bug
clr-control-error doesn't show error message unless you click some where else on screen for the first time. From the second time onwards the error displays as soon as value changes.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-light-theme-clr-control-error-bug?file=src%2Fapp%2Fform-demo%2Fform-demo.component.html

1.  Go to [https://clarity-v4-light-theme-clr-control-error-bug.stackblitz.io/](https://clarity-v4-light-theme-clr-control-error-bug.stackblitz.io/)
2.  From Select 1 control, Select 3 or 4, which is invalid (only 1 and 2 are valid)
3.  Notice, error message doesn't show.
4.  Click some where else on the screen.
5.  Notice Error message appears.
6.  Select value 1 or 2 (valid value), notice error message hides.
7.  Again From Select 1 control, Select 3 or 4, which is invalid (only 1 and 2 are valid)
8. Notice Error message appears without clicking anywhere.

So only for the first time after selecting the invalid value, the error message doesn't show unless user clicks somewhere else on screen.

## Expected behavior

Even with the first time after selecting the invalid value, the error message should show without user having to click somewhere else on screen.

## Versions

**Clarity project:**

- [ x ] Clarity Angular/UI

**Clarity version:**

- [ x ] v4.x

**Framework:**

- [ x ] Angular

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: MacBook
- OS: 11.2.2
- Browser: Chrome, Firefox
- Version [Chrome: 89.0.4389.114 , Firefox: 87]

## Additional notes

_Add any other notes about the problem here._

**Comment by sis0k0** [comment]
@tovinayv, sorry for the delayed response. In your Stackblitz example, you're using `select`. Is there a reason why you want to allow users to pick an invalid option in a select box?

**Comment by vinayvivekananda** [comment]
@sis0k0,
We have a UX that should display 'Not Available', if there are no possible options. We simple add 'Not Available' as an option and we have custom validator to mark it as invalid.

**Comment by vasil-ivanov-vmw** [comment]
This is a pretty nasty bug for the use case where for some reason you load invalid configuration and present it in a form. As soon as the form is rendered there is no indication that there is a problem with existing data. The error will not appear till the user actually visits the problematic field. If they just want to edit the other fields validation will not let them submit the form because of the problematic one and no error message would appear.
