### ISSUE TITLE
CSS of Custom Filter is disarranged when optional column is selected in the Datagrid

### ISSUE THREAD

**Issue by miryalanaga** [vmware/clarity#5860]
Hi Clarity team
Custom Filter CSS is behaving weird when we chose optional columns to display in the datagrid. It works fine if none of the optional columns are chosen to display in the datagrid. When there is an optional column selected and when we click on a filter, respective custom filer is being displayed at the top left corner (Screenshot attached)
can someone point us on the fix if available. 
<img width="1415" alt="Screenshot 2021-04-16 at 1 37 17 PM" src="https://user-images.githubusercontent.com/64389530/114992922-e6e6f980-9eb8-11eb-850d-e573eaf1011e.png">

**Comment by sis0k0** [comment]
Hi @nagakalyanm, can you please share a reproduction in Stackblitz using one of Clarity’s templates - https://stackblitz.com/@clr-team?

**Comment by miryalanaga** [comment]
Hi @sis0k0 we are good to close the issue. its working fine now
