### ISSUE TITLE
Keyboard navigation not working on Clarity dropdown menu

### ISSUE THREAD

**Issue by SaiSatwik** [vmware/clarity#5867]
## Describe the bug
Keyboard navigation with down arrow button is not working on clarity dropdown options when there is a wrapper div around dropdown items.

## How to reproduce

For some reason, I was not able to reproduce this issue on stackblitz. But here is the github repo https://github.com/SaiSatwik/clarity-dropdown for my project. Please clone the repo and do npm install and ng serve to start application on localhost. I am using node version v10.22.0. 

1.  Click on Clarity Dropdown Items button. This will show dropdown options.
2. Now pressing down arrow on keyboard, we are not able to navigate thorugh the available options.

## Expected behavior

We should be able to navigate through the available options by pressing Keyboard down and up arrows.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [x] v4.x
- [ ] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
10.1.x

**Device:**

- Type: [MacBook]
- OS: [iOS]
- Browser [chrome, safari, firefox]

## Additional notes

I tried to debug the issue. I could see `@ContentChildren(FocusableItem) items: QueryList<FocusableItem>;` line in [dropdown-menu.ts](https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/popover/dropdown/dropdown-menu.ts) file in clarity project is not returning focusable items.

**Comment by mathisscott** [comment]
@SaiSatwik 
This issue is that there is a wrapper div around the dropdown items. If you remove the wrapper div and have the dropdown items as the direct children of the dropdown, this works as expected.

**Comment by SaiSatwik** [comment]
hi @mathisscott , even if there is wrapper div around dropdown items it used to work before. If you see this [stackblitz](https://stackblitz.com/edit/clarity-light-theme-playground-ffnof2?file=src%2Fapp%2Fapp.component.html), it is somehow working here.
In my case I want to style the dropdown menu component. Without having wrapper div, I cannot do that right?
