### ISSUE TITLE
Cannot use cds-icon with direction inside an angular button with .btn style

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#5869]
## Describe the bug

I tried updating our dropdown components to use cds-icon but the direction is not working when inside a button. Whatever I use the icon direction is not changed. It seems you cannot use directions when inside a button. If I move the icon outside the button, then the direction works. Using 5.1.1

## How to reproduce

```
<button class="btn">
    <cds-icon shape="angle" direction="down"></cds-icon>
</button>

```
## Expected behavior

The direction to work

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

## Additional notes

You cannot have cds-icon inside a button as this css has priority:
```
.btn-group>.btn cds-icon, .btn-group>.btn clr-icon, .btn cds-icon, .btn clr-icon {
    transform: translate3d(0,-.1rem,0);
}
```
over:
```
:host([direction="down"]) {
    transform: rotate(180deg);
}
```
In v4 the css was different and had priority (higher specificity):
```
clr-icon[dir=down] svg, clr-icon[shape$=" down"] svg {
    transform: rotate(180deg);
}
```

**Comment by rbirkgit** [comment]
Maybe we also need to change the top property to 35% (currently v5 sets it to 45%):
```
.dropdown .dropdown-toggle cds-icon[shape^=angle] {
    position: absolute;
    top: 35%;
```

**Comment by rbirkgit** [comment]
The 'flip' property has the same issue and also doesn't work when cds-icon is inside a button.

**Comment by mathisscott** [comment]
@rbirkgit 
Thanks for reporting this issue! There is a [PR out for it now](https://github.com/vmware/clarity/pull/5898).

**Comment by rbirkgit** [comment]
Great!
