### ISSUE TITLE
cds core form alignment broken in clr-modal popup

### ISSUE THREAD

**Issue by wokis** [vmware/clarity#5870]
## Describe the bug

Using cds form elements inside a  clr-modal seems to break the alignment for a vertical form layout. Letters are cropped.

![image](https://user-images.githubusercontent.com/4148643/115242084-d2f20080-a121-11eb-92e2-10eef88b5618.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v5-nzwlxs?file=src/app/app.component.html

1. Click on 'show modal'

## Expected behavior

Letters and error label (including upper case ÅÄÖ) should not be cropped.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: [PC]
- OS: [Windows 10]
- Browser [Chrome]
- Version [90]

**Comment by mathisscott** [comment]
@wokis 
I can't get your stackblitz to run. Any chance you could get it fixed so I can see the issue?

**Comment by wokis** [comment]
> @wokis
> I can't get your stackblitz to run. Any chance you could get it fixed so I can see the issue?

Think I fixed it now. Can you retry?

**Comment by mathisscott** [comment]
It's running now. Thanks! I'll check it out and try to figure out what's happening.
