### ISSUE TITLE
Datagrid Documentation: Wrong single action example video

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5877]
## Describe the bug

The example video for single action shows the single selection.

![Screenshot 2021-04-20 at 10 35 14](https://user-images.githubusercontent.com/3655915/115364904-29178000-a1c4-11eb-96e8-77334feef435.png)

## How to reproduce

https://clarity.design/angular-components/datagrid/#single-action

## Versions

**Clarity project:**

- [x] Clarity Angular/UI

**Clarity version:**

- [x] v5.x

**Comment by mathisscott** [comment]
@hippee-lee 
I suspected that maybe we were pointing to the wrong video in this instance but we are not. The website is pointing to the correct video but the video is wrong. I don't know how these videos were created. I'm happy to pair up with you on it if you want.

**Comment by hippee-lee** [comment]
A new video has been pushed to the edge of the cdn.
