### ISSUE TITLE
cds-file input doesn't trigger onChange event when using the X button to clear the input

### ISSUE THREAD

**Issue by wokis** [vmware/clarity#5889]
## Describe the bug

cds-file input doesn't trigger onChange event when using the X button to clear the input. Additionally configured validators on the input field are also not run.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v5-kpekkw?file=src/app/app.component.ts

1.  Click "Browse" and select some files
2.  The upload button should no longer be disabled
3.  Click the "X" button to the right of the "Browser" button

## Expected behavior

Once cds-file input is cleared the upload button should be disabled. "event fired" should be printed to the console log.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: PC
- OS: Windows 10
- Browser: Chrome
- Version: 90

**Comment by mathisscott** [comment]
Thanks for filing this issue @wokis . This looks like a bug.
