### ISSUE TITLE
Provide a .forRoot() method on ClarityModule to prevent reimport of ClrResponsiveNavigationService in lazy-loaded feature modules

### ISSUE THREAD

**Issue by JohannesRudolph** [vmware/clarity#59]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
`ClarityModule` needs a `.forRoot()` method so that it cooperates nicely with lazy-loaded feature modules. 

### Actual behavior
The current implementation results in separate instances of `ClrResponsiveNavigationService` per injector scope of lazy loaded feature modules

### Reproduction of behavior
For reference, see https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-for-root

### Environment details

* **Angular version:** 2.2

* **Clarity version:** 0.7

* **OS and version:** OS X El Capitan

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
Thanks for filing this issue @JohannesRudolph. @youdz will try to get this fixed ASAP. Assigning this to him.

**Comment by jaffoneh** [comment]
Actually, @hippee-lee will take care of this one!
