### ISSUE TITLE
Stack block selection using tab in stack view messes up the UI

### ISSUE THREAD

**Issue by vidhibansal** [vmware/clarity#5904]
When a clr-stack-block is selected using Tab instead of Enter, the UI gets messed up. 
Attaching the screenshot for the same:
![Screenshot 2021-04-26 at 3 38 29 PM](https://user-images.githubusercontent.com/28995296/116229233-e03b6a80-a773-11eb-9b01-2d703b3f7fbc.png)

**Comment by gnomeontherun** [comment]
Hello, for us to be able to review this issue we need an isolated reproduction of this issue to triage. Please provide a working [Stackblitz demo](https://stackblitz.com/@clr-team) that has the minimal elements needed to reproduce this issue.

**Comment by Jinnie** [comment]
Also, please tell us which version of Clarity are you using. 
I'm almost sure we had a fix for this some time ago.

**Comment by Jinnie** [comment]
Yes, this must have been fixed with this commit:
https://github.com/vmware/clarity/commit/ee73df36e5ed356d7f9236042d61ecbd4d44af31
Please open a new issue with more details if you're using an up to date version of Clarity and still observing the problem.
