### ISSUE TITLE
core: accordion typography override 

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#5915]
## Describe the bug

The Core Accordion is setting its own default font values causing content that is projected to inherit those values. This is causing style issues when projecting certain content that relies on inheriting its typography from the global scope. This can make migrations more difficult from clr-ui to core.

https://github.com/vmware/clarity/blame/next/packages/core/src/accordion/accordion-content.element.scss#L10-L11 

## How to reproduce

Project any text content within an accordion that relies on the global typography scope.
https://stackblitz.com/edit/typescript-prepp5?file=index.html 

## Expected behavior
Generic container components not override the projected content typography. The two css props can be updated to use `inherit`.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [x] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by coryrylan** [comment]
ping @astorije

**Comment by astorije** [comment]
Thanks @coryrylan, I'll open a PR shortly!
