### ISSUE TITLE
@cds/angular not playing nice with element bindings

### ISSUE THREAD

**Issue by gnomeontherun** [vmware/clarity#5916]
## Describe the bug

The element bindings and attributes are not getting reflected correctly by the @cds/angular wrappers to the core elements.

## How to reproduce

https://stackblitz.com/edit/angular-ivy-d3mqge?file=src%2Fapp%2Fapp.component.html

1. Start focus on the first link
2. Hit tab
3. Expect focus to move to second link, because tag is supposed to be `readonly`.
4. Change from using pure Core in the AppModule to using CdsModule.
5. Start focus again on first link
6. Hit tab
7. Observe focus hits tag. 
8. Review the element and see that it does not reflect the readonly state properly into the web component.

## Expected behavior

That bindings will work 1:1.

## Versions

**Clarity project:**

- [X] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by Shijir** [comment]
Resolved by https://github.com/vmware/clarity/pull/5932
