### ISSUE TITLE
Make the content-container and content-area to stretch to the remaining height or provide utility class

### ISSUE THREAD

**Issue by manju-reddys** [vmware/clarity#592]
**Select one ...**  (check one with "x")
```
[ ] bug
[ x] feature request
[ ] enhancement
```

### Expected behavior
Make the `content-container` and `content-area` to grow the remaining space. Or either provide utility class to make the container grow to the remaining space. 

[See the plnkr for example (click on + icon and then stretch it) ](https://plnkr.co/SkD58EryxskBtZX2pTk4)

### Actual behavior
The `content-container` and `content-area` grow based on the content size. 

### Reproduction of behavior
[The document site itself is aexample](https://vmware.github.io/clarity/documentation/app-layout)

### Environment details

* **Angular version:** 2.0.X
Nothing to do with Angular

* **Clarity version:** 
Latest

* **OS and version:** 
All
* **Browser:** [all]

**Comment by adityarb88** [comment]
@manju-reddys: I am not sure I understand the feature request correctly. The `.main-container` has a height of `100vh`. The `.content-container` occupies the space remaining from the `.header` and the `.subnav`. And the `.content-area` occupies 100% of the height of its parent (`.content-container`). 

If you are looking at the website, the `.main-container` height has been overridden to `height: auto` instead of `height: 100vh` just for the documentation purposes.

Could you please provide more details on what exactly you want and also the use case for it?

**Comment by manju-reddys** [comment]
@adityarb88, I have attached the image which shows the content-container grows to 100% only if there is enough of the content in the container.
![sample](https://cloud.githubusercontent.com/assets/1906881/23876624/99880614-07fb-11e7-9981-5b70b4bc81cf.png)

**Comment by adityarb88** [comment]
Oh now I understand the issue. We have a class `.u-main-container` that you can use to wrap the `.content-container` in case it is not a direct child of `.main-container`. You can use that to wraper with that class to wrap the `.subnav` and the `.content-container` (or you can directly attach to the host). Let me know if that works.

**Comment by manju-reddys** [comment]
didn't work either, see the attachment
![sample](https://cloud.githubusercontent.com/assets/1906881/23877624/6979c084-0800-11e7-9ffd-5a84ade0d62d.png)

**Comment by adityarb88** [comment]
@manju-reddys: The `.content-container` and the `.subnav` have to be a direct child of `.u-main-container`. We use `display: flex` so you need them to be direct children for the flex properties to work.

**Comment by manju-reddys** [comment]
@adityarb88 I have initially added them as direct children of `.u-main-container` that didn't work too.

**Comment by adityarb88** [comment]
works for me: https://plnkr.co/edit/OJ50040dFvgSt7z1UPci?p=preview. Check `app.component.html`

**Comment by adityarb88** [comment]
Closing this based on the above comment. Feel free to reopen the issue if its still not resolved.
