### ISSUE TITLE
Recursive lazy-loaded TreeView clrExpandable causes an EHCAIWC error

### ISSUE THREAD

**Issue by wokis** [vmware/clarity#5927]
## Describe the bug

When opening an expandable node in a recursive lazy-loaded TreeView an error is thrown and logged in the console:
`Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ngIf: true'. Current value: 'ngIf: false'.`

## How to reproduce

1. Go to https://stackblitz.com/edit/clarity-light-theme-v5-py3ndx?file=src%2Fapp%2Fapp.component.html
2. Expand the src node
3. Observe the ExpressionChangedAfterItHasBeenCheckedError in the console

## Expected behavior

No ExpressionChangedAfterItHasBeenCheckedError should be raised.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: PC
- OS: Windows 10
- Browser: Chrome
- Version: 90

## Additional notes

If `[clrExpandable]` is not used no EHCAIWC error is raised. This issue might be related to #3300 but it looks like it was resolved.

**Comment by bbogdanov** [comment]
Hi @wokis,

The stackblitz gives a great example how to reproduce the issue. We need some time to investigate what is still causing the issue and we will get back to you as soon as we have something to share.
