### ISSUE TITLE
core: cds-form-group shouldn't set label width in vertical layouts

### ISSUE THREAD

**Issue by ashleyryan** [vmware/clarity#5931]
## Describe the bug

Input labels in cds-form-group have a min width set, even when using a vertical layout with labels on top of inputs.

## How to reproduce

cds-form-group calculates the largest label and sets all labels in the group to be the same width. This is expected behavior in a horizontal layout, but shouldn't happen when the layout is set to vertical and the labels are above the input. This is particularly noticeable when creating a horizontal layout of inputs as in the stackblitz example below:

https://stackblitz.com/edit/typescript-gtygdk?file=index.html

## Expected behavior

When the `layout` attribute  of `cds-form-group` is set to `vertical` or `vertical-inline`, `cds-internal-control-label` should not have `--internal-label-min-width` set.

## Versions

**Clarity project:**

- [X ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ X] v5.x

I discussed this with @coryrylan  on slack

**Comment by coryrylan** [comment]
Adding a note to extend a closely related issue. The label width is no longer controllable via a CSS prop to enforce specific label text wrapping. Fixing both with the same solution.
