### ISSUE TITLE
clr-angular dropdown cds-icon styles

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#5941]
## Describe the bug
The clr-dropdown example on the website shows an example with a button containing a cds-icon and a icon shape of angle. However the prior versions also supported the alias `caret`. If users use the alias rather than angle the styles of the icon are not correct. The icon is larger and not aligned to the right like it should when using shape angle.

Current v5:
<img width="743" alt="Screen Shot 2021-05-12 at 5 37 04 PM" src="https://user-images.githubusercontent.com/2021067/118052640-b3c54800-b348-11eb-9c74-64ebc476b6d2.png">

Prior v4:
<img width="624" alt="Screen Shot 2021-05-12 at 5 42 21 PM" src="https://user-images.githubusercontent.com/2021067/118053082-7b723980-b349-11eb-8ec7-6ec605c2fd05.png">

To fix we can add the alias selector `caret` to ensure the styles for angular apps continues to work

```css
cds-icon[shape^='caret']
```

https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/popover/dropdown/_dropdown.clarity.scss#L67 

We can also improve the angular docs and update the code examples to use angle rather than the alias caret.
https://clarity.design/angular-components/dropdown/#clarity-ui-component

## How to reproduce

Use a cds-icon with the caret shape in a clr-angular dropdown button.

## Expected behavior

Caret icon should align to right and be the correct size.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by elesueur** [comment]
@coryrylan should it also include `clr-icon[shape^='caret']` for backward compatibility?

**Comment by sis0k0** [comment]
Fixed with #5946. Will be released in the next patch version of Clarity.
