### ISSUE TITLE
Clarity 4 - Angular 12 Production Build failure when clarity css files are included

### ISSUE THREAD

**Issue by ccjasonlin** [vmware/clarity#5947]
## Describe the bug
Angular 12 production build doesn't work with Clarity v4.0 when css files are included

## How to reproduce

- Tested with Angular v12.0.0. Make sure you Angular cli is 12.0
- ng new application
- add following to package.json
    "@clr/icons": "^4.0.15",
    "@clr/ui": "^4.0.15",
- add following to angular.json
            "styles": [
              "node_modules/@clr/icons/clr-icons.min.css",
              "node_modules/@clr/ui/clr-ui.min.css",
              "src/styles.scss"
            ],

run `ng build --configuration production`

Build will fail with a cryptic error, but this is related to adding css files to the app.
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✖ Index html generation failed.
undefined:10:269535: property missing ':'
## Expected behavior

Production build should succeed

## Versions

**Clarity project:**

- [ ] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [X] v4.x
- [ ] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12.0.0

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
Clarity 4 is built to be used with Angular 10. 
Using Clarity 4 with newer Angular versions is out of our support matrix.
We yet have to release a version that will be tested and supported with Angular 12.

**Comment by BoykoAlex** [comment]
It is the same with Clarity 5.2.0 - same issue for me with Angular 12. There is something in clarity UI CSS files that angular build doesn't like

**Comment by BoykoAlex** [comment]
I have commented out all styles attributes with value `url(...)` in **clr-ui-dark.css** (dark theme only in our app) under node_modules/@clr/ui, switched to this CSS file rather than minified ran the app with `npm start` (not to nuke stuff under node_modules) and it went through so i suspect something angular 12 doesn't like in clarity CSS... maybe too pedantic checking the format of inlined SVG... not sure...

**Comment by thmueller1** [comment]
Using Base64 will solve this

**Comment by BoykoAlex** [comment]
I'm seeing the same with Clarity 5.2.1 as well. Any chance you could look into this again?

**Comment by Jinnie** [comment]
Just follow the release documentation for the moment we release Clarity version that will work with Angular 12.
