### ISSUE TITLE
Multi level form/wizard support???

### ISSUE THREAD

**Issue by blackdust21** [vmware/clarity#595]
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
How do I create a multi step form/wizard?

### Actual behavior
When a form is not just a single step but like a wizard for installation, how do i do it in Clarity?

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all ]

**Comment by jaffoneh** [comment]
@blackdust21 are you looking for wizards: https://vmware.github.io/clarity/documentation/wizards?
