### ISSUE TITLE
Icon shape 'map' doesn't have badge version

### ISSUE THREAD

**Issue by tarangkhandelwal** [vmware/clarity#5956]
## Describe the bug
The icon of the shape 'map' does not have a variant with a badge. We are looking to use this icon for product/feature guided tours and the version with badge will be useful to mark any new changes to the tour or unseen steps in the tour.

## How to reproduce
Not required as this is a request for support of badge behavior in the existing Clarity icon.

## Expected behavior
Icon map should support badge behavior

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
@lil-kim 
Would this be something we could add to the map icon?

**Comment by lil-kim** [comment]
Hi @mathisscott 
Here are the variants for the Map icon:
[Map icon variants.zip](https://github.com/vmware/clarity/files/6504783/Map.icon.variants.zip)

**Comment by mathisscott** [comment]
@lil-kim 
Map apparently has a solid variant. Can we get badges/alerts for the solid version as well?

**Comment by lil-kim** [comment]
@mathisscott 
Oops! Thanks for catching that. Here it is: 
[map-solid variants.zip](https://github.com/vmware/clarity/files/6510342/map-solid.variants.zip)
