### ISSUE TITLE
Regression: clrAccordionPanelOpenChange emits only when the panel is expanded

### ISSUE THREAD

**Issue by pniv** [vmware/clarity#5957]
## Describe the bug

There is a regression in Accordion/Stepper component. `clrAccordionPanelOpenChange` event emits only when a panel is expanded.

## How to reproduce

The bug is 100% reproducible on ClrStepper and ClrAccordion. `ClrAccordionPanel.panelOpenChange` does not emit when the panel is collapsed.

## Expected behavior

`clrAccordionPanelOpenChange` should emit `true` when a panel is expanded and `false` when a panel is closed.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: MacBook
- OS: iOS
- Browser:  Chrome
- Version: 90

## Additional notes

The regression is introduced by this commit:
https://github.com/vmware/clarity/commit/4e338f3bde2ea10c8b0b7a704c8624058cf2e2f7

**Comment by bdryanovski** [comment]
@pniv thanks for reporting this. I gonna need some time to check this out.
