### ISSUE TITLE
"icon" is not found in the Clarity Icons set.

### ISSUE THREAD

**Issue by Natdanai-Wongtib** [vmware/clarity#596]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I do not understand why I can use Icon just only core shapes. I'm trying to use the icons in Essential Shapes and Social Shapes. It shows the error message on console = **'half-star' error message found in the Clarity Icons set.**

### Actual behavior
I include the icon font with static html file. not angular project. 

```
<link rel="stylesheet" href="path/to/node_modules/clarity-icons/clarity-icons.min.css">
<script src="path/to/node_modules/clarity-icons/clarity-icons.min.js"></script>
```
### Environment details

* **Static HTML file.

**Comment by Shijir** [comment]
Hi @Natdanai-Wongtib, I just tested clarity-icons to check whether I experience the issue or not. I can access all the shapes in `clarity-icons.min.js`. You can see it's accessing the shapes here in this plunkr: https://plnkr.co/edit/sAtxZaQoVuDk4FokRKdQ?p=preview. The cause of your issue could be somewhere else, for example, in the way you setup your application so please recreate your issue using this boilerplate plunkr https://plnkr.co/8TwwdL.

**Comment by mamos98** [comment]
I get the exact same error in my console and I followed the instructions very carefully! The problem is I can use core icons but not others. I added clarity to existing ngCli project. @Shijir

**Comment by Shijir** [comment]
Without looking at how you are setting up `clarity-icons` in your app, we couldn't help you sufficiently. So please recreate your issue in the [Plunkr](https://plnkr.co/8TwwdL) we provide.

**Comment by BeryJu** [comment]
I am having the same issue. This can be seen in this [Plunkr](https://plnkr.co/edit/fduA7RTKxxvvAUtzZxik?p=preview)

**Comment by BeryJu** [comment]
After some further research, this is because in `src/clarity-icons/index.ts` only `CoreShapes` are loaded. This can be fixed by adding
```
import { EssentialShapes } from "./../node_modules/clarity-icons/src/shapes/essential-shapes";
import { SocialShapes } from "./../node_modules/clarity-icons/src/shapes/social-shapes";
import { TechnologyShapes } from "./../node_modules/clarity-icons/src/shapes/technology-shapes";
[..]
clarityIcons.add(EssentialShapes);
clarityIcons.add(SocialShapes);
clarityIcons.add(TechnologyShapes);
```
to the index file, or loading `node_modules/clarity-icons/shapes/social-shapes.js` in the browser after loading the .min.js file.

**Comment by noce2** [comment]
@BeryJu when you add the above lines to the index file, how do you recompile the ts into a minified js file?

**Comment by BeryJu** [comment]
I build one monolithic JS file with Grunt, which I load in the header. It is enough to include `node_modules/clarity-icons/clarity-icons.min.js` in this file and all icons work. @noce2

**Comment by mathisscott** [comment]
@BeryJu 
Depending on what version of Clarity you are running, you can now import `all-shapes` if you want...

https://github.com/vmware/clarity/issues/1214

This should work in Clarity ≥ 0.9.15

**Comment by Shijir** [comment]
@noce2 @BeryJu If you guys use the JS version of Clarity Icons, which is `clarity-icons.min.js`, it will load all sets and icon shapes automatically. And you can load it just like a regular JS library in your app's HTML file:

```
<script src="path-to/node_modules/clarity-icons/clarity-icons.min.js"></script>
```

If you use the TS version of Clarity Icons, you have a control over which sets to import in your app. That means having `import "clarity-icons"` doesn't load all the shapes automatically like `clarity-icons.min.js` does. So you need to import those sets if you are using any icons from them. For example, If my app uses icons from `Social Shapes` and `Technology Shapes`, I would import them like this:

```
import 'clarity-icons'; // loads only core-shapes alone and Clarity Icons API
import 'clarity-icons/shapes/social-shapes';
import 'clarity-icons/shapes/technology-shapes';
```

But if your app is using shapes from all sets, 
```
import 'clarity-icons'; // loads only core-shapes alone and Clarity Icons API
import 'clarity-icons/shapes/all-shapes'; // loads all shapes from all sets
```

**Comment by kjavia** [comment]
Also the scripts need to be loaded before your client app code is loaded.

    <script src="./node_modules/@webcomponents/custom-elements/custom-elements.min.js"></script>
    <script src="./node_modules/@clr/icons/clr-icons.min.js"></script>
