### ISSUE TITLE
Angle icon alias "caret" doesn't work

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#5969]
## Describe the bug

Displaying the angle icon via the `caret` alias doesn't work. I assume I imported everything correctly because the `angle` shape is working.

![Screenshot 2021-05-20 at 12 13 31](https://user-images.githubusercontent.com/3655915/118961645-d1a43580-b964-11eb-8d21-08591e0b6a79.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v5-vlhlht?file=src/app/app.module.ts

## Expected behavior

Icons for angle and caret are both working.

## Versions

**Clarity project:**

- [X] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

v5.2.0

**Framework:**

- [X] Angular

**Comment by gnomeontherun** [comment]
We don't automatically add the aliases with Clarity Core, so you would have to define it as an alias. You can see more about this here: https://medium.com/claritydesignsystem/goodbye-clarity-icons-hello-clarity-core-adb07de9739e. Too many aliases can limit adding new icons and we've decided there isn't real value to multiple names for the same thing.

**Comment by dorthrithil** [comment]
Makes sense for most cases, but in this specific case I would expect the alias to be automatically available as `caret` is the cds icon shape that is used in various examples throughput the docs (e.g. dropdown). Also you're targeting specific CSS rules to this shape name (see https://github.com/vmware/clarity/issues/5941). Having to add a custom alias to make the examples work is quite unexpected.

**Comment by dorthrithil** [comment]
Ah, I just read in the exact same issue that I referenced, that you're planning to switch to `angle` everywhere. 

> We can also improve the angular docs and update the code examples to use angle rather than the alias caret.

So then this issue wouldn't be an issue anymore. I guess this can be closed then.
