### ISSUE TITLE
Grid with pagination disappears on click of header sorting or using filter.

### ISSUE THREAD

**Issue by cloud9amit** [vmware/clarity#5980]
Steps :

have a grip with at-least 2 pages.
Click on header column sorting 2-3 times and then click next page and grid data dissappears.

this issue is already discussed here: https://github.com/vmware/clarity/issues/4752#issuecomment-673525158

We are specifically using version 2.4.6 and angular version 8.1.0 and it's not possible at this moment to upgrade to a new version. Please suggest if there is a workaround other than upgrade to a new version.
Below is the stackblitz link: (specifically used 2.4.6 version). I tried with version 2.4.2 and issue is not seen there so it's a regression. 
https://clarity-light-theme-v2-4-6.stackblitz.io

**Comment by Jinnie** [comment]
You can call ClrDatagrid.resize() on sort. It seems to be enough to rerender the items properly.
See the "First Name" column of this altered version of your stackblitz:
https://stackblitz.com/edit/clarity-2-sort-workaround?file=src/app/app.component.ts

I'm closing the issue, as 2.x is out of support, in 3.x it's fixed, and we have a workaround.

**Comment by cloud9amit** [comment]
> You can call ClrDatagrid.resize() on sort. It seems to be enough to rerender the items properly.
> See the "First Name" column of this altered version of your stackblitz:
> https://stackblitz.com/edit/clarity-2-sort-workaround?file=src/app/app.component.ts
> 
> I'm closing the issue, as 2.x is out of support, in 3.x it's fixed, and we have a workaround.

Hi Jennie,

This workaround works for the sorting but same issue is there on filter as well. If you open filter box and type some random text which does not match with the column content and later clear that content then rows don't show up. 
This workaround doesn't address that issue.

**Comment by Jinnie** [comment]
The same example has been updated with a new implementation using the (clrDgRefresh) handler, which fixes all columns in the datagrid at once and covers the filter issue, too.
