### ISSUE TITLE
How to add a custom icon in the version 5?

### ISSUE THREAD

**Issue by wendellestradairely** [vmware/clarity#5989]
The documentation shows how to add a custom icon but the function doesn't exists. Is there a sample code or a documentation on how to add a custom icon in the latest version? Thanks!

![image](https://user-images.githubusercontent.com/50942719/119365598-a8780200-bce2-11eb-9720-64c7e0f61dd5.png)

![image](https://user-images.githubusercontent.com/50942719/119365518-939b6e80-bce2-11eb-9cfe-841d7353464a.png)

**Comment by mathisscott** [comment]
With the `@cds/core` icons the method call signature is slightly different. 

https://gist.github.com/mathisscott/a0b8bad7473bb3639839cb87d5b337cd#file-adding-icons-js

What you want to do would look like this...

`ClarityIcons.addIcons([ 'indent': '<svg...></svg>']);`
