### ISSUE TITLE
Datagrid issue

### ISSUE THREAD

**Issue by lynxone67** [vmware/clarity#600]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Return "parameter" on datagrid refresh

### Actual behavior
I have a datagrid with auto filters. When I activate the filter, it returns only the value, not the parameter. Filter parameter doesn't return when I use *ngFor.

### Reproduction of behavior

https://plnkr.co/edit/y2maSN8GDkryje3PsSUj?p=preview
### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Jinnie** [comment]
Hi @lynxone67,

I don't understand your request very well, but your plunker does not seem to work.
You should use *clrDgItems instead of *ngFor to allow Clarity's filters and sorting to work.

`    <clr-dg-row *clrDgItems="let person of zamestnanci">
`

Hope this helps.

**Comment by lynxone67** [comment]
OK, thank you for your answer, but until yesterday everything worked even with *ngFor, so I don't understand what happend. As I understand if I use *clrDgItems, then i need to get all  records from api. In some cases it's about 600 records and that's too much.

**Comment by Jinnie** [comment]
You can think of it as a smart wrapper of *ngFor, which handles all data processing. Otherwise, you have to implement the filtering, sorting, etc logic yourself, as *ngFor knows nothing about filters etc.
If you want to load the records dynamically, check the example in the Server-driven datagrid section of the datagrid documentation.

**Comment by lynxone67** [comment]
@Jinnie 
Server-driven datagrid section of the datagrid documentation says:

> One important thing to note is that since you don't have all the data available at once, you cannot use the smart iterator *clrDgItems: it would sort, filter and paginate a subset of the data that has already gone through all that. So all you need to do is to go back to a simple *ngFor, which we support.

The next thing is that, as I already wrote, the filtering with *ngFor worked until yesterday. What happened? Why doesn't it work now?

**Comment by Jinnie** [comment]
You are right - it can't sort or filter something that has not yet been loaded. You have to handle that server side.
The latest release has been 6 days ago, nothing from yesterday. But honestly - I've never seen it work with *ngFor. And I've hit it quite a few times myself, even filed an issue for this. It's easy to miss.

**Comment by lynxone67** [comment]
Until yesterday it was so, that I loaded first 15 records with query parameters. Then, if I wanted to filter, the refresh($event) got me something like `[last_name: 'pl']` according to what was writen in filter and where it was used. Then I queried the api with `http://apiserver/api/?limit=15&offset=0&last_name=pl`.

But that doesn't work now. I can't get the property `last_name` in this case. The filter returns only value `'pl'`

Is there an option to downgrade and try an older version of datagrid?

**Comment by Jinnie** [comment]
You are now receiving an instance of Filter object instead of {property, value}.
This is a regression from this issue https://github.com/vmware/clarity/issues/355
Type check at datagrid.ts:99 fails now.
You have ways to workaround it, but I'd suggest downgrading to a previous version of Clarity and waiting for a fix in next version.
It's been submitted for 0.8.9, so you need something before it.
For a workaround (but you may need to revert later), the value is in filter.value (as before), but the property name will be in filter.filterFn.prop

**Comment by youdz** [comment]
Yes, this is definitely a regression on our side. We "unwrapped" the automatic ones for you before, but their type has changed and we didn't update the unwrapping test.

Should be an easy fix, I'll see in we can squeeze it in today to publish it in 0.8.11 this week.

**Comment by Jinnie** [comment]
Btw, the demo page for the server-driven, also fails to filter properly. I guess it's coming from the same problem, but didn't have time to debug it there, only in the plunker.
;)

**Comment by lynxone67** [comment]
Thank you all, temporarily i downgraded to 0.8.8 and that helped. Later this month I will try the new version.
