### ISSUE TITLE
z-index is not working

### ISSUE THREAD

**Issue by theromie** [vmware/clarity#601]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
```

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
 When i opening dropdown menu or select option are showing below div even z-index is set to 1000
check out this link for [reference](https://a33i.imgup.net/download1d1e.png)

**Comment by mathisscott** [comment]
@theromie : we need more information than that small image provides. 

Could try reproducing in a [Plunkr](https://plnkr.co/8TwwdL)?

**Comment by mathisscott** [comment]
Hi @theromie 
We haven't heard back about this issue. Did you find a workaround? Or did a recent release fix it for you?
