### ISSUE TITLE
content-container/area not displayed properly when using routing!

### ISSUE THREAD

**Issue by zntr1** [vmware/clarity#6012]
## Describe the bug

When using the "Vertical-Navbar" inside a component, loaded through a `<router-outlet></router-outlet>`, the navbar is not taking its full content-height on the left side of the application and only uses a small portion. It seems like there is a problem with using the router-outlet together with "content-container", "content-area" and so on.

## How to reproduce

Just see the example I build:
https://stackblitz.com/edit/angular-10-claritybug-verticalnav?file=src/app/app.component.html

If you comment out the "router-outlet" and instead uncomment the other part, it works as intended. When using the same structure inside the dummy.component.html, it stops working again.

## Expected behavior

Expecting to act just as if it was loaded without <router-outlet>, properly displaying the vertical navbar and content-area.

## Versions

**Clarity project:**
- [ ] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**
- [ ] v3.x
- [X] v4.x
- [X] v5.x

**Framework:**
- [x] Angular

**Framework version:**
_ie: Angular 10.2.5

## Additional notes

Maybe I did something wrong but tried a lot of stuff and it boils down to the same problem again and again.

**Comment by Jinnie** [comment]
I see what you are trying to do, but it comes to the way Angular components are built, and there is not much we can enforce as solution from the Clarity side, without some heavy-lifting code, which may have many unexpected side effects. The good news is that you have a very easy solution for your code.
Why this happens?
Our nav and content-area sections get their placement from the content-container. The content container dictates that it will be a flex-box and it's children, placed by default, one next to the other.
When you add the nav and content area through a component, though, they are not the immediate children of the content-container anymore. There is an intermediate host-container for the component. It is the single child of the content-container now and it has no display definitions on its own. So, its children (the nav and content-area) are placed naturally, as divs, one below the other.
What we can do is to add flex-box to the host-container. I.e. add this to your `dummy.component.css` file:
```
:host {
  display: flex;
}
```
