### ISSUE TITLE
Support Angular 12

### ISSUE THREAD

**Issue by bgpedersen** [vmware/clarity#6018]
## Describe the bug

Installing latest CLR in Angular 12 projects will give warning 

`npm WARN @clr/angular@5.3.0 requires a peer of @angular/core@^11.0.0 but none is installed. You must install peer dependencies yourself.`

## How to reproduce

Run this command in Angular 12 project
`$ npm i @cds/core@latest @clr/angular@latest @clr/icons@latest @clr/ui@latest
`

## Expected behavior

No warnings for requirements for Angular 11.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Comment by Jinnie** [comment]
We're working on this. Closing as duplicate to several other issues and a discussion.

**Comment by bgpedersen** [comment]
@Jinnie I did not find any other issues, when i searched for angular 12 on the open issues. thats why i created this. Do you have a link to the current open issue regarding this?

**Comment by Jinnie** [comment]
They have been probably closed in favor of this discussion: https://github.com/vmware/clarity/discussions/6004
This is an often appearing request and we're working actively on resolving it soon.
It's currently depending on another task, related to separating our Core and Angular sources and websites, which is also near completion and will be immediately followed by continuing the upgrade to Angular 12.
