### ISSUE TITLE
Support more tabs than can fit on the page

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#602]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

If I have more tabs to display than can fit on the page or in their container, they should either scroll, or wrap, or offer some way to access the last ones.

### Actual behavior

At the moment, they simply overflow the `<clr-tabs>` element. If it scrolls, the whole content of the tabs scroll, the delimiter doesn't go across all the links, ... If it doesn't scroll, the last tabs are simply not accessible.

### Reproduction of behavior

https://plnkr.co/edit/IMzGJy?p=preview

### Environment details

* **Angular version:** 2.4.X

* **Clarity version:** 0.8.X

* **Browser:** all

**Comment by mathisscott** [comment]
The recommendation here is to use vertical tabs instead of horizontal tabs when you have a long list of tabs.

**Comment by jaffoneh** [comment]
@mathisscott this does not solve all use cases considering the responsive case (where you have more than few tabs on that page). We need a way to see additional tabs in the case of horizontal tabs.

**Comment by mathisscott** [comment]
@jaffoneh : I understand that. I was documenting our thought process because this was a known issue when tabs were released.

This is not a new discovery.

**Comment by reddolan** [comment]
@yenmade and I talked about using the similar pattern to what is being developed in Button Groups (#247), the Overflow feature. When the fully responsive interaction is in place, it would also allow for responsive tabs

**Comment by mathisscott** [comment]
@reddolan : Could we get a few more details on this so we can prioritize the work and move it to the backlog?

**Comment by reddolan** [comment]
Similar to the way additional button actions are placed in an overflow icon (ellipses) we could put additional tab items into an overflow (ellipses) that when it is clicked on, it can show a dropdown with remaining tabs inside

**Comment by reddolan** [comment]
Here are design specs for both Tabs and Subnav

![group](https://user-images.githubusercontent.com/1858226/27041902-ff447662-4f5a-11e7-8bd9-c127f51d33c4.png)

**Comment by kevinmcbride** [comment]
I was also looking for how to handle tabs in a responsive design where the tabs don't fit at some resolutions.  The only problem I have with the above design is that when an overflow tab is selected, it does not surface the tab name to be visible.  Highlighting the ellipsis is not very helpful.  Seems like the whole point of a tab bar is to show which tab you are on.  Adding a Page Title for the content is not a good answer for us because we are already using a page title above the tabs.  Have you considered other alternatives: 1) using arrows to scroll the tabs right and left?  2) always show the selected tab and swap other tabs into the menu if necessary?

**Comment by kevinmcbride** [comment]
Here's an example of scrolling tabs - need to make your browser smaller to squeeze some of the tabs out of view. https://material.angularjs.org/latest/demo/tabs

**Comment by jaffoneh** [comment]
CC @reddolan to provide feedback on the above

**Comment by reddolan** [comment]
@kevinmcbride It's a valid point. I will circle back with the devs and get back to you about whether this is possible

**Comment by reddolan** [comment]
@kevinmcbride I talked with Dev about option 2. There are some issues with it though:
1. when pulling the selected value out of the overflow menu and making it a visible tab, there is a risk of there not being enough room to display the new tab. This would cause collision issues. The effort to figure out how to detect if there is enough room is challenging on top of that. 
2. There is a usability issue of the tabs moving. There is quite a bit of context switching going on when moving tabs. Where did the tab go that vanished? Will the user know to look for it in the overflow menu? 
3. There is an accessibility issue of moving the tabs, the DOM changes confusing users with screen readers. 

Option 1 also has challenges:
1. Scrolling arrows are introducing a new overflow experience in Clarity, one that users have to understand and get used to
2. Scrolling gives the user no sense of the total number of tabs available (similar to infinite scroll)
3. A user has no idea what other tabs are available and have to scroll through the entire site at least once to understand which options are available to them.
4. The issue of clicking or holding down an arrow to get to the tab you need

I understand the need to display current location in navigation and agree it's important. Out of the three options presented, I still stand by my recommendation as it has the least amount of issues. I understand it isn't perfect though.

If the tab in question has a high amount of importance, it doesn't belong in the overflow to begin with. We recommend that tabs be in order of importance and use. That way overflow options are ones that are used infrequently are the ones that end up in overflow scenarios. This lessens the burden of a user not knowing where they are.

**Comment by reddolan** [comment]
cc: @youdz ^

**Comment by jeeyun** [comment]
@reddolan: for active tab state in the overflow, are we adopting the active style of the regular dropdown? For example, when current tab is Tab 6 and the user again clicks on the ellipsis, should Tab 6 be highlighted?

**Comment by reddolan** [comment]
@jeeyun yes, regular dropdown design and experience
