### ISSUE TITLE
[UI] Upgrade font to Metropolis Release 9

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#603]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

Expected Behavior
Upgrade Metropolis font to Release 9: https://github.com/chrismsimpson/Metropolis/releases/tag/r9

Actual Behavior
We are currently on Release 8

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Closing this as we have other Metropolis font things on the horizon.

**Comment by sdurnov** [comment]
@mathisscott any updates on this?

**Comment by gnomeontherun** [comment]
See https://github.com/chrismsimpson/Metropolis/pull/28 for updates. This also causes some breaking changes, so the timeline for it is not yet defined.

**Comment by sdurnov** [comment]
@gnomeontherun looks like Chris don't have enough time to even push changes fast enough. Have you thought about forking his repo or adding it to existing Clarity repo?
