### ISSUE TITLE
Dropdown menu with built-in filtering

### ISSUE THREAD

**Issue by rongery** [vmware/clarity#604]
<img width="371" alt="screen shot 2017-03-15 at 4 45 04 pm" src="https://cloud.githubusercontent.com/assets/11431579/23975614/0c2d9284-099f-11e7-9525-80e1382988de.png">
<img width="367" alt="screen shot 2017-03-15 at 4 45 29 pm" src="https://cloud.githubusercontent.com/assets/11431579/23975616/11c752c0-099f-11e7-8d88-d114fb5de569.png">

**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
We need what amounts to a 'select' control, but we'd like to have a search box attached to help filter down the potentially very long list. See attached for the control I've built manually using clr-dropdown and some css hacking. It's missing details like auto-focusing of the search box, being able to hit Enter to auto-choosing the top-most filtered item, etc.

This seems like a control that would be useful in any application where the user needs to choose from a long list.

Original implementation of this was a 'select' control, but our users asked for filtering.

**Comment by youdz** [comment]
We've got an issue open to track this: #248.
Feel free to subscribe to it and post additional comments or requirements if you want. 👍 

Closing this a duplicate.
