### ISSUE TITLE
Tabs in overflow are not activated when clicked on mobile

### ISSUE THREAD

**Issue by kjetilhp** [vmware/clarity#6046]
Similar to #5684 but only present for mobile in my case

## Describe the bug

When on mobile I am unable to click/touch the items in the overflow list, no event occurs. The overflow is working as it should when in browser phone simulator and on regular browser. However, on the phone or in the iOS xcode simulator nothing happens when clicking the items. Items are just highlighted and then it disappears without selecting the tab

## How to reproduce

https://clarity-overflow-problem.stackblitz.io

1.  Open on mobile device or iOS simulator
2.  Click on '...'
3. Select an item..
4. .. nothing happens, no event

## Expected behavior

Tab should be showing its content

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ x ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x ] v5.x

**Framework:**

- [x ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_Angular 10, 11, 12_

**Device:**

- Type: [Phone, simulator]
- OS: [iOS]
- Browser [chrome, safari]

## Additional notes

My behaviour is similar to #5684 but happens when the overflow is used on mobile. When on mobile I am unable to click/touch the items in the overflow list, no event occurs. The overflow is working as it should when in browser phone simulator and on regular browser. However, on the phone or in the iOS xcode simulator nothing happens when clicking the items. Items are just highlighted and then it disappears without selecting the tab. Tried adding click action to see if anything happens when clicking on the item, but no luck.

**Comment by hippee-lee** [comment]
Thank you for reporting this. Triage does indicate that there is an issue with [toggleOverflowOnClick](https://github.com/vmware/clarity/blob/next/packages/angular/projects/clr-angular/src/layout/tabs/tabs.ts#L192)

Triaging this on desktop Safari (not in mobile dev mode) I noticed that 
```(focus)="openOverflowOnFocus()"  works in Desktop Safari```
but
```(click)="toggleOverflowOnClick()" does not. ```
