### ISSUE TITLE
cds: long message in cds-control-message switches form layout to vertical

### ISSUE THREAD

**Issue by wokis** [vmware/clarity#6053]
## Describe the bug

A long message in a `cds-control-message` switches form layout from horizonal to vertical. If the `cds-control-message` message is longer after a failed input validation the input will switch between horizontal and vertical layout.

![image](https://user-images.githubusercontent.com/4148643/121739666-3f72f580-cafc-11eb-81f0-a7dfef509baf.png)

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v5-upxtde?file=src%2Fapp%2Fapp.component.html

See the stackbliz demo

## Expected behavior

A horizontal form layout shouldn't become vertical if `responsive = false` and the `cds-control-message` contains a long message.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.3.0

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: PC
- OS: Windows 10
- Browser: Chrome
- Version: 91

## Additional notes

Changing `flex-flow: row wrap` to `flex-flow: row` seems like a good workaround but I haven't been able to apply it outside Chrome's dev console. (Can't figure out the correct `::ng-deep` selectors)

![image](https://user-images.githubusercontent.com/4148643/121739349-c5db0780-cafb-11eb-9e1f-4d8a2a0fa171.png)

**Comment by hippee-lee** [comment]
Adding `wrap:none` [here](https://github.com/vmware/clarity/blob/next/packages/core/src/forms/control/control.element.ts#L179) prevents the input and control message from wrapping under the label. However before proceeding with a PR I'm not sure if the current behavior is intended. @coryrylan  or @mathisscott - do you have any insight into why it currently wraps like this? I'm looking for clarification if is  a UX thing or something else. If not, I can submit a PR.

**Comment by coryrylan** [comment]
I am looking at a similar issue that was mentioned in the support slack. I'll double check

**Comment by coryrylan** [comment]
Ok, I think I have a possible fix for this. Its a bit more involved due to another related issue with the label control width with the auto layouts and long text wrapping. I'll try to get a PR up sometime this week.
