### ISSUE TITLE
Updating clarity v5 stackblitz templates makes them utterly broken

### ISSUE THREAD

**Issue by wokis** [vmware/clarity#6054]
## Describe the bug

Updating `@cds/core` or `@clr/angular` in the clarity-x-theme-v5 makes the template utterly broken.

    Error in /turbo_modules/@clr/angular@5.0.2/bundles/clr-angular.umd.js (2:111)
    Unexpected token 'export'`

## How to reproduce

1.  Select on of the Clarity Stackblitz v5 templates from https://stackblitz.com/@clr-team
2.  Update `@cds/core` or `@clr/angular`
4.  See error

## Expected behavior

The update should succeed.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: PC
- OS: Windows 10
- Browser: Chrome
- Version: 91

**Comment by hippee-lee** [comment]
We have known about  this for a while. We reached out to the @StackBlitz team for help investigating it because the error messages make it hard to see what is causing it and why it is failing. 

This is under investigation so stay subscribed for any updates when they are available.

**Comment by hippee-lee** [comment]
@bdryanovski or @bbogdanov - any updates on the investigation?

**Comment by bdryanovski** [comment]
We still have issues with the normal Stackblitz Angular template ...

As a workaround I could offer this for the moment https://stackblitz.com/edit/clarit-angular-node - this is based on the new Strackblitz Node templates - and things here work for the moment.

**Comment by bbogdanov** [comment]
Unfortunately, we didn't get a response back in a while so we assumed we have to move in another direction. 

What @bdryanovski provided is what we will be working with from now on. I believe what we could do is just pin the template to our main clarity template source.

**Comment by Jinnie** [comment]
For the time being, we've adopted the Node version of the template.
Please, use it instead.
As we have a viable workaround and fixing the Angular-version templates is not something we can do on our side, I will close this bug.
