### ISSUE TITLE
Getting a warning when running ng serve(angular12)

### ISSUE THREAD

**Issue by AllForNothing** [vmware/clarity#6068]
## Describe the bug

Warning: Entry point '@clr/angular' contains deep imports into './node_modules/@cds/core/icon', './node_modules/@cds/core/icon/register'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

1.  npm install   
2. ng serve
3. then you can see the warning  

## Expected behavior

Everything works fine, but why getting this warning? 

## Versions

dependencies": {
    "@angular/animations": "^12.0.3",
    "@angular/common": "^12.0.3",
    "@angular/compiler": "^12.0.3",
    "@angular/core": "^12.0.3",
    "@angular/forms": "^12.0.3",
    "@angular/localize": "^12.0.3",
    "@angular/platform-browser": "^12.0.3",
    "@angular/platform-browser-dynamic": "^12.0.3",
    "@angular/router": "^12.0.3",
    "@cds/core": "^5.3.0",
    "@clr/angular": "^5.3.0",
    "@clr/icons": "^5.3.0",
    "@clr/ui": "^5.3.0"
}

**Comment by gnomeontherun** [comment]
This is just a warning because we use deep imports, because that is how we properly setup tree shaking with our Core package. This might be a problem if our Core package was Angular, but it is not so the warning is not applicable to this scenario. Closing as not an issue.

**Comment by AllForNothing** [comment]
@gnomeontherun Thanks a lot for the explanation.

**Comment by gnomeontherun** [comment]
Also found a way to disable those messages if you like.

https://github.com/angular/angular/issues/35615#issuecomment-592253747
