### ISSUE TITLE
No documentation for clr-hidden-[size]

### ISSUE THREAD

**Issue by hadrienbecle** [vmware/clarity#6071]
There is no documentation for the css classes .clr-hidden-[size]. There already was an issue a few years back (#3586), but it was marked as resolved last year, even though it's nowhere to be found on the website.

I think it should be either on the _Grid_ page, or in a _Display utilities_ page (like Bootstrap).

Also, I don't understand why the _Grid_ page is in the _Angular Components_ submenu, shouldn't it be in _Core Components_?

**Comment by mathisscott** [comment]
As we focus more on `@cds/core` providing layouts and utilities, I don't think we will grow support or documentation for legacy CSS utilities in `@clr/ui`. That said, this is an interesting legacy feature that I don't think we have in `@cds/core`.

Maybe worth considering, @coryrylan ?
