### ISSUE TITLE
Browser warnings from core icons when running 5.4.0 Angular

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#6076]
## Describe the bug

When upgrading to 5.4.0 I started seeing a myriad of these warnings in the browser when starting up. Several pages long. They did not happen with 5.2.1.

```
client:126 [WDS] Warnings while compiling.
client:135 D:/Git/tango-ui-sdk/node_modules/@cds/core/icon/collections/chart.js
Module Warning (from D:/Git/tango-ui-sdk/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'D:\Git\tango-ui-sdk\node_modules\src\icon\collections\chart.ts' file: Error: ENOENT: no such file or directory, open 'D:\Git\tango-ui-sdk\node_modules\src\icon\collections\chart.ts'

```
## How to reproduce

Have this in my angular,json so we can debug libraries:

```
"sourceMap": {
  "scripts": true,
  "styles": true,
  "vendor": true
}
```

## Expected behavior

Less warnings :) 

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.4.0

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

**Comment by coryrylan** [comment]
The issue is from our source maps pointing to the relative path of the original source You can see an example here https://cdn.skypack.dev/-/@cds/core@v5.4.0-Jtim6zAWRrhsEAt0O3e8/dist=es2020,mode=raw/icon/collections/chart.js.map
