### ISSUE TITLE
New Icons to publish Vol. 5

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#609]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### svg icons - ready for implementation Vol. 5 (1 of 2)
![image](https://cloud.githubusercontent.com/assets/23196444/24262621/dc31a81c-0fb7-11e7-9777-0e285638a6f0.png)

### svg icons - ready for implementation Vol. 5 (2of 2)
![image](https://cloud.githubusercontent.com/assets/23196444/24312605/8f2b3b0c-1096-11e7-8707-41547c82ae47.png)

### svg icons - ready for implementation Vol. 5 - 9.0 Fixes
![image](https://cloud.githubusercontent.com/assets/23196444/24637561/0687f12e-1897-11e7-92f0-2ff5a6782b50.png)

### SVG Icons attached:
[vol5_1of2.zip](https://github.com/vmware/clarity/files/865684/vol5_1of2.zip)
[vol5_2of2.zip](https://github.com/vmware/clarity/files/869118/vol5_2of2.zip)
[Vol5_9-0 fixes.zip](https://github.com/vmware/clarity/files/891825/Vol5_9-0.fixes.zip)

**Comment by adityarb88** [comment]
For Icon Updates, @Shijir has create a new issue https://github.com/vmware/clarity/issues/791 because its a breaking change.
