### ISSUE TITLE
cds-file poor long file names handling

### ISSUE THREAD

**Issue by vitali-bulky** [vmware/clarity#6098]
## Describe the bug

When selecting a file with a long filename browse button shows the whole string breaking layouts.

## How to reproduce

1.  Go to https://clarity.design/core-components/file/
2.  Click on any browse button
3.  Select a file with about 100 or more chars long filename
4.  See how browse button overflows other content

![screenshot](https://user-images.githubusercontent.com/77749812/123196625-3ed14c00-d478-11eb-8dd2-11b6b1a862db.png)

## Expected behavior

Mimic native html file input behaviour.

![screenshot2](https://user-images.githubusercontent.com/77749812/123196791-8e177c80-d478-11eb-8ecf-97357a4f681e.png)

**Comment by coryrylan** [comment]
Related issue will be fixed with same PR https://github.com/vmware/clarity/issues/6053
