### ISSUE TITLE
Clicking next step in wizard should move to the next page

### ISSUE THREAD

**Issue by ScottLangham** [vmware/clarity#610]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x ] enhancement
```

### Expected behavior
After completing a page, clicking on the next step (at the left) should move the user to the page for that step (assuming the current page is valid). It should do the same as the NEXT button.

After watching users trial our product, it's been noted they try to hit on the step (on the left of the wizard) to go to the next page, as well as to go backwards.

### Actual behavior
Clicking on the next step does not take the user to the page for that step. They have to use the NEXT button. (However, users can click on steps to go backwards, so it seems sensible that they should be able to click steps to go forward too).

### Reproduction of behavior
The examples on this page show the behavior: https://vmware.github.io/clarity/documentation/wizards

### Environment details

* **Angular version:** 2.4.9

* **Clarity version:** 0.8.9

* **OS and version:** Windows 8

* **Browser:** all

**Comment by reddolan** [comment]
I agree, if we are able to make this interaction available

**Comment by mathisscott** [comment]
I'll check to see if it is possible in the new wizard. If not, I'll assign this as an enhancement after the new wizard is out.

**Comment by mathisscott** [comment]
I've verified that the new wizard does not allow this. It follows the interaction/behavior of the pre-0.9 wizard.

I will add this to the backlog. I can see where it is confusing. But it will have to be an enhancement we add after the 0.9 wizard is final.
