### ISSUE TITLE
npm/yarn not working on windows machine.[Windows specific]

### ISSUE THREAD

**Issue by pavandixit93** [vmware/clarity#6105]
## Describe the bug

I am not able to install dependencies on windows machine by using `npm` or `yarn`, and due to which i am not able to build clarity on windows, Please attached screenshots.

FYI, I have node version 12.20.2 still it throws error.

![npmNotWorking](https://user-images.githubusercontent.com/21095558/123741699-1efeb580-d8c8-11eb-9200-479b51c987a3.PNG)
![yarnNotWorking](https://user-images.githubusercontent.com/21095558/123741705-202fe280-d8c8-11eb-92f8-761c5a5b797a.PNG)

## How to reproduce

On windows machine clone the clarity repository and try to run `npm i` ir `yarn`.

Please 

1.  Get the 'windows machine'
2.  Git clone on windows machine 'git clone https://github.com/vmware/clarity.git'
3.  Switch to newly created folder using `cd` command 'cd clarity'
4.  Run `npm i` or `yarn` to install dependencies in node_modules.

## Expected behavior

Ideally i should be able to install dependencies and run clarity build successfully.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by Jinnie** [comment]
You need the correct node version for the Clarity version you want to install, as specified in the error message.
For best node-version management experience, I'd suggest installing NVM (node version manager). There is a windows version. Please check this article from Microsoft:
https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-windows

Closing, as Clarity is successfully used on Windows from many developers across VMware and Node version management is not something that resides in our domain of development or documentation.

**Comment by pavandixit93** [comment]
@Jinnie Thanks for the link, I am going through it.
