### ISSUE TITLE
sidenav vertical scroll is blinking

### ISSUE THREAD

**Issue by likwifi** [vmware/clarity#611]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

Sidenav component vertical scroll is blinking during hover and drag  

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 
Windows 7
* **Browser:** [Chrome latest]

**Comment by adityarb88** [comment]
Hi @likwifi: We need more information to replicate this. Please reopen the issue with a Plnkr. Our website uses the sidenav too and we are unable to replicate this there. Thanks!

**Comment by likwifi** [comment]
@adityarb88 I was able to duplicate that issue on your website, did you hovered on scrollbar on windows chrome browser?

**Comment by Jinnie** [comment]
Hi @adityarb88 
I also observed it on the Clarity documentation site. 
When the content of the sidenav overflows, we have overflow:hidden by default.
The scrollbar gets enabled on hover here:
/clarity/src/clarity-angular/nav/_sidenav.clarity.scss:75-76
(unless the file has changed as I am looking at a few weeks old forked source on my machine)
```
        .sidenav-content {
            .....

            &:hover {
                overflow-y: auto;
            }
```

The scrollbar itself is not considered part of the containing sidenav, it seems. So once your mouse gets on the scroller, we get a mouseout event. Once the mouse is moved, we're again upon the container area, so mouseover comes and the scrollbar appears again.

That's what brings the flickering effect, described by @likwifi 

I won't be trying submit a fix for this, as the initially hidden overload is obviously a desired feature, and you need to talk with the UX team if it can be dropped.
I can't quickly figure out a technical workaround, although it may be not impossible 😄.

Best regards

**Comment by likwifi** [comment]
@adityarb88 @Jinnie It looks like this issue was fixed after upgrade to chrome version 57.0.2987.110 but it is still reproducible on 56.0.2924.87

**Comment by Jinnie** [comment]
Yes @likwifi,
This seems to be a specific Chrome 56.x bug. There are several issues on this. Good that they fixed it with 57. I also only reproduced it in Chrome 56.x

**Comment by adityarb88** [comment]
oh okay. thats why i might not have been able to replicate this. Then I guess we don't have to take a look at this? Let me know if thats not the case. Thanks for your help @likwifi & @Jinnie
