### ISSUE TITLE
[Core] Datalist has extra caret when focused

### ISSUE THREAD

**Issue by Jinnie** [vmware/clarity#6110]
## Describe the bug

The Core Datalist component displays extra caret symbol after being focused. It is not visible, when out of focus

## How to reproduce

1.  Go to storybook / datalist page
2.  Focus the input
3.  Observe that a second, displaced, caret appears

![Screen Shot 2021-07-01 at 13 44 59](https://user-images.githubusercontent.com/1798828/124112912-78efae80-da73-11eb-9bce-f7ee613c1e59.jpg)

## Expected behavior

No extra caret.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [x] Other: web-components

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: Macbook
- OS: OSX
- Browser Chrome

**Comment by Jinnie** [comment]
Some research done:

The usual approach, which we also have in Clarity, is to do this:
```
cds-datalist input::-webkit-calendar-picker-indicator {
  display: none;
}
```
It works fine with the calendar picker, but for some reason, the datalist, which obeys this rule, disregards the "display" property. Using opacity instead seems to work better:
```
cds-datalist input::-webkit-calendar-picker-indicator {
  opacity: 0;
  cursor: text;
}
```

**Comment by bbogdanov** [comment]
Brave browser
![image](https://user-images.githubusercontent.com/15037947/126951936-f0454b3f-9db8-4bbc-b819-7c64a307dcc9.png)

Safari browser
![image](https://user-images.githubusercontent.com/15037947/126952222-298f5a0f-ae1d-437a-8c1a-0aaaa41a2433.png)

Firefox browser
![image](https://user-images.githubusercontent.com/15037947/126952302-2d3dfa7c-f8fc-4c24-b6af-7f6dbce12586.png)

Chrome browser
![image](https://user-images.githubusercontent.com/15037947/126952360-82627e0f-ce64-476d-8691-69ba04e073ba.png)

I guess we have to revisit this issue cause the behaviour of the caret is different on every browser.
