### ISSUE TITLE
Signpost not clickable, won't open when starting with display:none state

### ISSUE THREAD

**Issue by JeTmAn1981** [vmware/clarity#6113]
I have an Angular component (date-field) which should show a signpost icon when you hover over it.  The signpost icon should appear to the right of the component.  I'm using this CSS to show the signpost:

```
clr-signpost
{
    display:none;
}

date-field:hover~clr-signpost
{
    display: inline-block;
}
```

Unfortunately, when the signpost does show up on hover, it's no longer clickable.  It will not open.  Am I doing this wrong?

**Comment by JeTmAn1981** [comment]
I should note I am running Clarity 3.1.3 :(

**Comment by Jinnie** [comment]
Please, use a stackblitz to reproduce the issue:
https://stackblitz.com/@clr-team

I have to note, though, that relying only on hover to display an actionable element does not sound to have good accessibility. How will this signpost be activated with keyboard only, for example?

**Comment by JeTmAn1981** [comment]
My apologies, it looks like this was actually a CSS problem on my end of things, no issue with Clarity that I am aware of.  Thank you for your response.
