### ISSUE TITLE
[0.8.11] bootstrap navbar-fixed-bottom broken 

### ISSUE THREAD

**Issue by chunghha** [vmware/clarity#612]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

navbar-fixed-bottom should be displayed at the bottom.

### Actual behavior
navbar-fixed-bottom is no longer displayed at the bottom with 0.8.11 updated from 0.8.10.

### Reproduction of behavior
https://plnkr.co/edit/2Yct1RfWtb9bldgFOpgN?p=preview

To see difference beetween 0.8.10 an 0.8.11, please switch clarity versions in index.html and config.js.

### Environment details

* **Angular version:** 2.4.10

* **Clarity version:** 0.8.11

* **OS and version:** Windows

* **Browser:** Chrome 57

**Comment by adityarb88** [comment]
Hi @chunghha: This was removed as part of the cleanup of the CSS. Clarity provides 3 options for [navigation](https://vmware.github.io/clarity/documentation/navigation) and we don't plan to support the BS4 navbar. If you still need the BS4 navbar you would have to import the bootstrap css separately. Thanks!

**Comment by chunghha** [comment]
@adityarb88 thanks for taking a look.

That's what I was wondering while reading your commit regarding CSS cleanup. So I guess Clarity is getting off from Bootstrap style as planned.
