### ISSUE TITLE
cds-button loading doesn't reverse side effects

### ISSUE THREAD

**Issue by loucyx** [vmware/clarity#6129]
## Describe the bug

Hi folks! I don't know if this was reported already, but the behavior of `cds-button` with the `loading-state` attribute is kinda bugged. If you set that property to the value `"loading"` and then you either set it to `"default"` or you just remove it, the button keeps being disabled.

## How to reproduce

You can reproduce the bug and play with it here: https://stackblitz.com/edit/clarity-button-bug?file=index.html 

1. Set the `loading-state` attribute of a `cds-button` to `"loading"`  (you can use `document.querySelector("cds-button").setAttribute("loading-state", "loading")`).
2. Change that attribute to `"default"` or remove it (you can use `document.querySelector("cds-button").setAttribute("loading-state", "default")` to set it or `document.querySelector("cds-button").removeAttribute("loading-state")`).

This is what happens:

| loading-state | Output                                   | Expected?          |
|---------------|---------------------------------------------------|--------------------|
| "loading"     | Button disabled with spinner instead of content   | :heavy_check_mark: |
| "success"     | Button disabled with checkmark instead of content | :heavy_check_mark: |
| "error"       | Button disabled with "x" instead of content       | :heavy_check_mark: |
| "default"     | Button keeps being disabled, showing content      | :x:                |
| unset/removed | Button keeps being disabled, content is hidden    | :x:                |

## Expected behavior

Loading has the side effect of adding the `disabled` property, so it should go back to the original state when stops loading (when `loading-state` has the values `"loading"`, `"success"` or `"error"` it should show the button as disabled, otherwise it should take the `disabled` state from whatever the developer set):

| loading-state | Output                                            |
|---------------|------------------------------------------------------------|
| "loading"     | Button disabled with spinner instead of content            |
| "success"     | Button disabled with checkmark instead of content          |
| "error"       | Button disabled with "x" instead of content                |
| "default"     | Button with disabled state set by dev, and showing content |
| unset/removed | Button with disabled state set by dev, and showing content |

## Versions

**Clarity project:**

- [x] Clarity Core

**Clarity version:**

- [x] v5.x

**Framework:**

- [x] Angular
- [x] React
- [x] Vue
- [x] Other: Vanilla

**Comment by coryrylan** [comment]
Thanks for filing this. I just saw this issue as well on https://cds.wtf/

**Comment by coryrylan** [comment]
closed by fix https://github.com/vmware/clarity/pull/6183
