### ISSUE TITLE
How to rebuild the clarity-ui.min.css from clarity-ui project?

### ISSUE THREAD

**Issue by tigran-av** [vmware/clarity#613]
This is not a problem report. We need to be able to build clarity-ui.min.css from clarity-ui project sources (scss files). How to build it? No any scripts are being provided out of the box to do that. Please instruct. Question is for vmware internal needs. Thanks.

**Comment by hippee-lee** [comment]
Hi @tigran-av - from the information provided it sounds like your need is outside what we support with the published version of clarity. 

We recommend using the published version directly from npm in your build / bundle process.
