### ISSUE TITLE
Radio Group Label cut off with vertical layout and overflow

### ISSUE THREAD

**Issue by ashleyryan** [vmware/clarity#6135]
## Describe the bug

When using a Radio Group inside of a container with overflow: auto, the label is cut off 1px at the top.

## How to reproduce

https://stackblitz.com/edit/clarity-react-node-zet6nv?file=src/App.js

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.4.2

## Additional notes

Scott pointed out the issue is here, so I'll open a PR to fix: https://github.com/vmware/clarity/blob/4caabde3c06ea172d2e61e7a54a48fbaf262eafb/packages/core/src/styles/typography/_typography.scss#L311

**Comment by Jinnie** [comment]
I see the PR is merged. Can we close this issue now?

**Comment by mathisscott** [comment]
yep. my bad. i thought it was linked/closed to the PR already.
