### ISSUE TITLE
Overflow no longer scrolls in 0.8.11

### ISSUE THREAD

**Issue by jvendryes** [vmware/clarity#614]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Scrolling works when content extends past the viewable area.

### Actual behavior
Scrolling no longer works when content extends past the viewable area.

### Reproduction of behavior
This behavior changed with the upgrade from 0.8.10 to 0.8.11. Specifically, the `overflow: hidden;` change added in this commit is what changed the behavior: https://github.com/vmware/clarity/commit/d63e7800fb3a1e06701b6b93c39e3b2dd2ac9ea5

### Environment details

* **Angular version:** 2.4.10

* **Clarity version:** 0.8.11

* **OS and version:** Mac OS X 10.12.3

* **Browser:** Chrome 56 | FireFox 52

**Comment by jvendryes** [comment]
After further testing on my side, I think the addition of `overflow:hidden` may not have actually caused scrolling to stop working. I'm using `<router-outlet></router-outlet>` and it appears that the flex layout breaks and it was only obvious with the `overflow:hidden` addition.

**Comment by adityarb88** [comment]
@jvendryes: Could you please create a plunkr replicating your issue? The flex layout assumes that the `.header`, `.sidenav`, `.content-container` is a direct child of the `.main-container` and the `.content-area` and the `-sidenav` are direct children of the `.content-container`. Is that the case with your layout?

**Comment by jvendryes** [comment]
Hi @adityarb88,
I believe my structure is following what you mention above, I could be wrong. Here is the Plunkr: https://plnkr.co/edit/65ro42?p=preview

On the "Incidents" page, you'll see the side nav border doesn't expand to the bottom of the page. Click on the "Summary" side nav item and you'll see some mock content that extends past the viewable area of the page.

Thanks!
J

**Comment by adityarb88** [comment]
One issue that I see in the plunk that you posted is that the `.content-container` is not a direct child of the `.main-container`. I fixed that here: https://plnkr.co/edit/uiaVVNFruwPiRyvPCuaP?p=preview
All I did was that I moved the `.content-container` class to the host (Incident Component). Let me know if that solves your issue.

**Comment by jvendryes** [comment]
Yeah that appears to have fixed it. I updated your example to use the `@HostBinding` decorator instead:

```
import { Component, HostBinding OnInit } from '@angular/core';

@Component({
  selector: 'app-incidents',
  templateUrl: 'app/incidents/incidents.component.html'
})
export class IncidentsComponent implements OnInit {
  
  @HostBinding('class.content-container') contentContainerClass: boolean = true;

  constructor() {
  }

  ngOnInit() {
  }

}
```

Thanks, sorry for the false alarm!
J

**Comment by adityarb88** [comment]
Thats alright. Closing the issue based on your last comment.

**Comment by jvendryes** [comment]
Just incase anyone is curious why I went with HostBinding here, just following the Angular Styleguide recommendation here: https://angular.io/docs/ts/latest/guide/style-guide.html#!#06-03

Thanks to the Clarity team on their work!
