### ISSUE TITLE
Seeing Entry point '@clr/angular' contains deep imports

### ISSUE THREAD

**Issue by kumar-tadepalli** [vmware/clarity#6149]
### Discussed in https://github.com/vmware/clarity/discussions/6007

<div type='discussions-op-text'>

<sup>Originally posted by **shravansofts** May 27, 2021</sup>
Hi Team,

I'm seeing this error while building and my project uses clarity angular only and i'm not using cds/core not even imported in app module it is just present in package.json.

But Im seeing the below warnings. Can you provide any info, whether i'm missing anything?

Warning: Entry point '@clr/angular' contains deep imports into 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/icon', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/icon/register'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point '@cds/angular' contains deep imports into 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/accordion/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/alert/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/badge/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/button/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/checkbox/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/datalist/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/date/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/divider/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/file/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/forms/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/icon/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/input/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/modal/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/password/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/progress-circle/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/radio/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/range/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/search/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/select/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/tag/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/test-dropdown/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/textarea/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/time/register.js', 'C:/Users/administrator/Desktop/ng11/app3/node_modules/@cds/core/toggle/register.js'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

</div>

**Comment by Jinnie** [comment]
Answered in the linked discussion. Thanks for bringing it up again.
