### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by halachliyskid** [vmware/clarity#616]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
A breadcrumb is a component used for building a bath to the root. It is commonly used in the web. The breadcrumb consists of a line Links separated by Dividers, where the last item is not clickable and usually represents the current view.

**Comment by joshjohnson72** [comment]
If it's useful, I did a redline spec for our team to build our own breadcrumb component as part of a page heading.  Feel free to use for reference or ignore. :-)

![breadcrumbs](https://cloud.githubusercontent.com/assets/8105536/24889314/25ad70e2-1e1e-11e7-950b-23524ecbbc5d.png)

**Comment by reddolan** [comment]
I don't believe that we will be creating the breadcrumb component. Generally, I see breadcrumbs as a band-aid, a way of overcoming poor information architecture. If design is done well, users can navigate to the things they need without complicating the UI with additional, space consuming, components. 
Jared Spool talks about this in more detail [https://articles.uie.com/breadcrumbs/](https://articles.uie.com/breadcrumbs/)

**Comment by yaroslavya** [comment]
Basically any file path and url can be treated as a breadcrumb. Does that mean people should stop using file paths? Is there an example of a design done right that eliminates the file paths and user is still able to navigate his/her file system? Hope theres a chance you, guys, reconsider.

**Comment by reddolan** [comment]
@yaroslavya My comment was more about having a well developed information architecture and UI controls to support it. When both are well thought out, users can still navigate easily, At that point, having a breadcrumb is taking up UI space unnecessarily. Also, by having a well-developed URL, you only end up duplicating the experience in the UI with by adding a breadcrumb as they are essentially the same thing.

URL
[domain]/Project3/Folder1/SubFolder3/File

Breadcrumb
Home > Project 3 > Folder 1 > Sub Folder 3 > File

**Comment by yaroslavya** [comment]
Thanks for the clarification, @reddolan , I guess I know what you mean now. But regarding the navigation of the user in a complex tree structure I see no other way, but to show the breadcrumb. Sometimes it can be done with the url. But even if you can do that, its not convenient in terms of navigating, say 3 levels up as for that you`ll have to manually go to the url and erase them. Doesnt look like a clean solution. 

So I cant see how one can go without breadcrumbs. Of course they should not be used mindlessly and one should first try all the other alternatives. But there are use cases( like navigating the complex tree structures ) where breadcrumb is the best solution. If theres any other way that is better for the user in any way - let me know. 

For now I only see a tree control can compete, but it still is inferior in many cases.

**Comment by reddolan** [comment]
It sounds like you saw [Tree View](https://vmware.github.io/clarity/documentation/tree-view) which was another component that I was going to recommend for navigating tree structures. Which allows a user to easily navigate up 3 levels like you mentioned. I don't understand what you mean about Tree View being inferior though.

**Comment by dgrahn** [comment]
I'll add my support for this view type. There are sometimes when breadcrumbs are the most appropriate visual component. For instance, imaging navigating through a file system without breadcrumbs.

**Comment by d-m-s** [comment]
some further reading on breadcrumbs can be found here https://www.nngroup.com/articles/breadcrumb-navigation-useful/
