### ISSUE TITLE
datagrid with pagination disappears  within tab-content

### ISSUE THREAD

**Issue by ghost** [vmware/clarity#6162]
## Describe the bug

I'm using clr-tabs, clr-tab, clr-datagrid, clr-dg-pagination to create a datagird inside a clr-tab. When the clr-datagrid is not the active tab on load, on activation doesn't not render.

However if it's on first tab it works fine

## How to reproduce

Not working Tab2 datagrid [Not working datagrid](https://stackblitz.com/edit/clarity-light-theme-v5-prnzbk?file=src/app/app.component.html). Just press Tab2->Tab1->Tab2 again

Working Tab2 datagrid as active tab [Working Datagrid](https://stackblitz.com/edit/clarity-light-theme-v5-ijuyyf?file=src/app/app.component.html). Just press Tab1->Tab2 again (You might need to refresh the page)

## Expected behavior

On Tab change datagrid and pagination should work as expected

## Versions

**Clarity project:**

- [ 5.4.0] Clarity Core
- [ 5.4.0] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ X] v5.x

**Framework:**

- [X ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 12_

**Device:**

- Type: [HP i7]
- OS: [Windows]
- Browser [chrome]
- Version [ 91.0.4472.164 ]

**Comment by hippee-lee** [comment]
This can be accomplished by using the de-sugared syntax of the `*clrIfActive` structural directive.

```html
  <clr-tab>
    <button type="button" clrTabLink>Tab2</button>
    <ng-template [(clrIfActive)]="showDatagrid">
      <clr-tab-content>
        Content Tab2
        <clr-datagrid>
          <clr-dg-column>User ID</clr-dg-column>
          <clr-dg-column>First Name</clr-dg-column>
          <clr-dg-column>Last Name</clr-dg-column>
          <clr-dg-column>Email</clr-dg-column>
          <clr-dg-row *clrDgItems="let user of users">
            <clr-dg-cell>{{user.id}}</clr-dg-cell>
            <clr-dg-cell>{{user.first_name}}</clr-dg-cell>
            <clr-dg-cell>{{user.last_name}}</clr-dg-cell>
            <clr-dg-cell>{{user.email}}</clr-dg-cell>
          </clr-dg-row>
          <clr-dg-footer>
            {{users.length}} users
            <clr-dg-pagination></clr-dg-pagination>
          </clr-dg-footer>
        </clr-datagrid>
      </clr-tab-content>
    </ng-template>
  </clr-tab>
```

[Here](https://stackblitz.com/edit/clrifactive-datagrid-tab2?file=src/app/app.component.ts) is an example.

I am going to convert this into a discussion, it isn't an issue with Clarity and it may be helpful to others with the same question.
