### ISSUE TITLE
Button group does not render well when it contains at least two btn-group-overflow

### ISSUE THREAD

**Issue by Blackleones** [vmware/clarity#6165]
## Describe the bug

The button group does not render well when it contains at least two `btn-group-overflow`.

![img_from_demo](https://user-images.githubusercontent.com/10961232/126472438-c8302853-79b1-4289-a0d8-1ff12b6bd896.png)

## How to reproduce

This code comes from your [demo](https://clarity.design/angular-components/button-group/). I have just duplicated the `<div class="btn-group-overflow">...</div>` to replicate the problem.

```html
<div class="btn-group btn-primary">
  <button class="btn">
    <cds-icon shape="home"></cds-icon>
    Home
  </button>
  <button class="btn">
    <cds-icon shape="cog"></cds-icon>
    Settings
  </button>
  <div class="btn-group-overflow">
    <button class="btn dropdown-toggle">
      <cds-icon shape="ellipsis-horizontal"></cds-icon>
    </button>
    <div class="dropdown-menu">
      <button class="btn">
        <cds-icon shape="user"></cds-icon>
        User
      </button>
      <button class="btn">
        <cds-icon shape="cloud"></cds-icon>
        Cloud
      </button>
    </div>
  </div>
  <div class="btn-group-overflow">
    <button class="btn dropdown-toggle">
      <cds-icon shape="ellipsis-horizontal"></cds-icon>
    </button>
    <div class="dropdown-menu">
      <button class="btn">
        <cds-icon shape="user"></cds-icon>
        User
      </button>
      <button class="btn">
        <cds-icon shape="cloud"></cds-icon>
        Cloud
      </button>
    </div>
  </div>
</div>
```

## Expected behavior

The button group renders all its items as expected: only the first and last items should have rounded borders at their edges, as you can see from the demo when it contains `btn-group-overflow` once.

![img_expected_from_demo](https://user-images.githubusercontent.com/10961232/126472743-acc43ede-8251-4771-828e-62b990d9d9ea.png)

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [x] v5.0.1

**Framework:**

- [x] Angular

**Framework version:**
Angular 11

**Comment by coryrylan** [comment]
I think the overflow group was only built for being the last element in the group. If you want a second dropdown/group I think its possible to omit the group and have the inner buttons refer to a dropdown. https://stackblitz.com/edit/clarity-light-theme-v5-mdghgm?file=src%2Fapp%2Fapp.component.html
