### ISSUE TITLE
Button group does not render well when it contains <clr-dropdown>

### ISSUE THREAD

**Issue by Blackleones** [vmware/clarity#6166]
## Describe the bug

The button group does not render well when it contains `<clr-dropdown>...</clr-dropdown>`

![img-from-angular](https://user-images.githubusercontent.com/10961232/126473806-dfaeb6b7-9473-4e41-9506-be2af364684b.png)

## How to reproduce

```html
<div class="btn-group btn-primary">
  <button class="btn">
    <cds-icon shape="home"></cds-icon>
    Home
  </button>
  <button class="btn">
    <cds-icon shape="cog"></cds-icon>
    Settings
  </button>
  <clr-dropdown [clrCloseMenuOnItemClick]="true">
    <button type="button" class="btn" clrDropdownTrigger>
      <clr-icon shape="trash"></clr-icon>
      <span class="clr-hidden-xs-down">Delete</span>
    </button>
  </clr-dropdown>
</div>
```

## Expected behavior

The button group renders all its items as expected: only the first and last items should have rounded borders at their edges, as you can see from the demo.

![img_expected_from_demo](https://user-images.githubusercontent.com/10961232/126474102-8b537dd1-da85-41d2-9f4b-238abba8b5e4.png)

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [x] v5.0.1

**Framework:**

- [x] Angular

**Framework version:**
Angular 11

## Additional notes

I think this problem is related to [issue 6165](https://github.com/vmware/clarity/issues/6165)

**Comment by coryrylan** [comment]
Reproducible demo https://stackblitz.com/edit/clarity-light-theme-v5-mdghgm?file=src%2Fapp%2Fapp.component.html
