### ISSUE TITLE
Size of icons in combobox component are wrongly defined

### ISSUE THREAD

**Issue by eclipse-jorgelmo** [vmware/clarity#6167]
https://github.com/vmware/clarity/blob/3281f777e84b7efce3e7697e82f6c85df802b3b5/packages/angular/projects/clr-angular/src/forms/combobox/combobox.html#L45

![image](https://user-images.githubusercontent.com/647982/126538769-46a35643-f80f-40b1-8455-1e299aec1784.png)

**Comment by coryrylan** [comment]
Can you clarify what you mean by wrongly defined or provide a stackblitz demo replicating the issue? https://stackblitz.com/@clr-team The icon does support px sizing like the size="12" option in the source but it looks like the API docs don't show that option.

**Comment by bdryanovski** [comment]
The code above uses the `string` type. `cds-icon` size could be a string that represents the width and height and we also provide t-shirt size for more consistent sizes. 

In the code above `'12'` is ok as a value. (12 width x 12 height)


I'm closing this as resolved.
