### ISSUE TITLE
Datagrid width calculations are broken by detail rows

### ISSUE THREAD

**Issue by grahamford** [vmware/clarity#6177]
## Describe the bug

Including detail rows in a datagrid messes up the calculations for the column widths.

## How to reproduce

https://stackblitz.com/edit/clarit-angular-node-disabled-buttons-zh1vma?file=src%2Fapp%2Fapp.component.html

(Sorry, I couldn't get StackBlitz to give me a more meaningful url)

The first datagrid shows one row per record. The second datagrid uses the same data but has a detail row for each. The calculations for the column widths seem to be thrown out by the details row.

## Expected behavior

The detail row shouldn't affect the column widths.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x
- [x] v12.0 

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Comment by hippee-lee** [comment]
Thanks for reporting this. This does seem to be an issue with the datagrid rendering lifecycle and the `*clrIfExpanded structural directive. It will need more investigation. 

In the mean time, is using [detail pane](https://v4.clarity.design/documentation/datagrid/detail-pane) an option for you? That is the recommended solution for this pattern. 

One thing about the expandable row is that it is not accessible as we do not recommend using it for new applications. It is still there to support apps that adopted it before we overhauled the angular components for accessibility.

**Comment by grahamford** [comment]
Thanks for the feedback @hippee-lee. I've considered using the detail pane but it can only show info about a single row at a time and it partially obscures the data grid. I'll have to see what other options I can use to display extended data.
