### ISSUE TITLE
Combobox multi - Label not adapting to the width of wrapper

### ISSUE THREAD

**Issue by boeckMt** [vmware/clarity#6179]
## Describe the bug

If a Combobox with the option `clrMulti` is used and text of the labels (`clr-combobox-pill-content`) is longer than the width for the container (`clr-combobox-wrapper`), the Label overflows the container.

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v5-v2vpwk?file=src%2Fstyles.css

1.  Open the combobox and select one or multiple Items
2. `label-combobox-pill` should overlap `clr-combobox-wrapper` so the close icon is not working.

## Expected behavior

The label shouldn't overlap the container, so the close button and trigger will work both. <br>
Maybe there could be an option to adapt the template rendering to reduce the length of the text, or show it as `overflow ellipsis`.

## Versions

**Clarity project:**
- [x] Clarity Angular/UI

**Clarity version:**
- [x] v5.x

**Framework:**

- [x] Angular

**Framework version:**
_ie: Angular 10.2.4

**Device:**
- Browser [chrome]

## Additional notes

**If the Combobox will be available in [Clarity core](https://clarity.design/core-components/) soon and there is not such an Issue, this can be closed.**

**Comment by Jinnie** [comment]
As the pills templates are fully customizable in multi-select mode, it's in your power to create a container which will size itself as you expect.
Something in this line limits the pill size in my tests:
CSS:
```
.small-pill {
  display: inline-block;
  max-width: 120px;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
HTML:
```
....
 <ng-container *clrOptionSelected="let selected">
   <span class="small-pill" title="{{selected.title}}">{{selected.title}}</span>
  </ng-container>
....
```
I agree it would be more convenient to have it pre-baked, but not imposing any restriction on projectable content is common for many places in Clarity Angular, as these restrictions are easy to be set in the user application and hard to unset if they break some other user's scenario.

I'm going to close this as something that has a workaround, which we don't intend to change in Clarity Angular.
Though the Core Combobox is not yet under development, I expect that it will be also leaving the fine details to the user application side.

**Comment by boeckMt** [comment]
I understand your concerns regarding styling and projectable content. 
Thanks for the Information about the status of the Core Component.
