### ISSUE TITLE
If Accordion is nested, nested accordion doesn't have proper colors

### ISSUE THREAD

**Issue by vinayvivekananda** [vmware/clarity#6188]
## Describe the bug

If Accordion is nested, nested accordion doesn't have proper colors for accordion-header and wrong caret icon shows which indicates whether the panel is open or not.

To summarise, nested accordion's header always appears as if it is open.

## How to reproduce

1.  Go to 'https://stackblitz.com/edit/clarity-v4-light-theme-tqby8n'
2.  Click on 'Nested Test'
3.  It opens the content with nested accordion.
4.  Observe the appearance of the accordion inside the Test accordion contents
5.  Header Nested Item 1 and Nested Item 2 appears as if it is expanded irrespective of whether is is expanded or not.

## Expected behavior

Whether the accordion is nested or not, it is should appear as per it's state.

## Versions

**Clarity project:**

- [ x] Clarity Core
- [ x] Clarity Angular/UI

**Clarity version:**

- [ x] v3.x
- [ x] v4.x
- [ x] v5.x

**Framework:**

- [ x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by hippee-lee** [comment]
Thank you for reporting this. I know this issue has come up before and I thought it was fixed. 
It needs investigation to determine the fix.
