### ISSUE TITLE
Ability to freeze first column of data grid

### ISSUE THREAD

**Issue by bdunkz** [vmware/clarity#619]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
When a data grid has many columns, it is often convenient to "freeze" the first column so that it is always visible.  For example, the first column may contain a name or id and as I scroll horizontally to view additional columns I would like to keep the context of which item I am looking at.

### Actual behavior
Not available today.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** Latest

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by chunghha** [comment]
Here is an example of column pinning to visualize this request. In my angularjs app, not only first few columns, I often pin last column too.

http://ui-grid.info/docs/#/tutorial/203_pinning

**Comment by reddolan** [comment]
@bdunkz we are in the final stages of releasing a datagrid feature to show/hide columns (#401) which I believe would satisfy the use case you mentioned of wanting to retain context when many columns are present. I am going to close this issue for now. If you still need this exact functionality, comment here and we can reopen it.

**Comment by bdunkz** [comment]
@reddolan I did check out issue #401 but it seems a bit different to me.  Can you confirm that #401 allows the first column to always be visible, even when scrolling horizontally to view other columns?

**Comment by chunghha** [comment]
@reddolan show/hide columns and freeze/unfreeze(pinning) serve two different purpose. With latter, I have ui-grid datagrid (AngularJS app) pinning first and last columns (imagine, first column is ID and last column is last update timestamp), columns between those two are scrollable horizontally but the first/last columns are always visible while scrolling. So I would like to request that kind of pinning feature with Clarity datagrid.

**Comment by reddolan** [comment]
@bdunkz @chunghha I had understood the need was to retain context when too many columns are present, which #401 would be able to facilitate by hiding unnecessary columns. 

Understanding the use case in better detail now, I will reopen the issue. Thank you both for the additional clarification on the use cases.

**Comment by vijay-venkatraman-vmware** [comment]
We have merged your request into #1586 and will be closing this one. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you.
