### ISSUE TITLE
Combobox options not displaying when dot used in search input

### ISSUE THREAD

**Issue by murray-stephen** [vmware/clarity#6194]
### Describe the bug

In v5, when using the  Combobox with a list containing users, searching using the users name works as expected. When attempting to search with an email address, the dot character does not seem to be accepted by the Combobox showing no results. 

### How to reproduce
Create a list with a property that contains a dot. Set the Combobox field to that property. Search for the value in the combobox and no results will be shown in the results dropdown. 

Search user name
![image](https://user-images.githubusercontent.com/5611925/127301359-54c39663-166b-4287-a5ef-31003be27b95.png)

Search users email
![image](https://user-images.githubusercontent.com/5611925/127301712-9859b6e3-334e-48dd-8b18-6cf76c3b173c.png)

### Expected behaviour
Options display all list items it is linked to.

### Versions
Clarity project:

- [x] Clarity Core
- [x] Clarity Angular/UI

### Clarity version:

- [x] v5.0.1

### Framework

- [x] Angular

### Framework Version
Angular 11

**Comment by Jinnie** [comment]
I don't see a reproduction and I'm unable to reproduce it locally.
Though, I can make some assumptions:
You probably have different data and display value. The filter works on the data, not the display value.
You probably also have `field` specifier on the `*clrOptionItems` iterator. If you have this specifier (which is optional), it will only be searching in the specified field. If you skip it, the combobox will search/filter in all item property values.

**Comment by murray-stephen** [comment]
HI Jinnie, thanks for the response, I've tried removing the field specifier as you've said but still get the same issue, am I missing something? It looks good to me. I've checked the Clarity source code and don't think I'm missing anything. 

```
<clr-combobox-container>
    <clr-combobox
      clrMulti="true"
      [(ngModel)]="searchedUsers"
      (clrInputChange)="lookupUser($event)"
      [clrLoading]="isLookingUpUsers$ | async"
    >
      <ng-container *clrOptionSelected="let selected">
        {{ selected?.name }}
      </ng-container>
      <clr-options 
        <clr-option *clrOptionItems="let searchedUser of searchedUsers$ | async;" [clrValue]="searchedUser">
          {{ searchedUser.name }} ({{ searchedUser.email}})
        </clr-option>
      </clr-options>
    </clr-combobox>
  </clr-combobox-container>
```

SearchedUser:

```
export interface SearchedUser {
  id: string;
  active: boolean;
  email: string;
}
```

**Comment by Jinnie** [comment]
I created a stackblitz, based on your code and it seems to work ok.
https://stackblitz.com/edit/clarity-light-theme-v5-uhzzjs?file=src%2Fapp%2Fapp.component.ts
Please try to reproduce the problem using the above link.

**Comment by murray-stephen** [comment]
Thanks, issue is resolved now. The Stackblitz is much appreciated.

**Comment by Jinnie** [comment]
Great to hear that, thanks for the quick feedback
