### ISSUE TITLE
how to implement Table colspan for datagrid 

### ISSUE THREAD

**Issue by ietabhi** [vmware/clarity#6197]
Hi Team,
I am using library from last 4-5 year.
I have one new use case in current application, need to add column grouping.

Need column with child column grouping in display. 

Please let me know how this is possible with filter and sorting.

Angular >=9x
Clarity >= 3x

If this is not possible in current application, any plan to implement in future releases?

![image](https://user-images.githubusercontent.com/7829397/127435471-1fe8fb66-17e5-45be-abaa-1466732b8dca.png)

**Comment by Jinnie** [comment]
No, it's something that we don't support in the datagrid. There has been some discussion around it (https://github.com/vmware/clarity/issues/2463), but it brings some design and accessibility challenges, as the datagrid is a complex and interactive component and this would interfere with data filtering/sorting and disabled users navigation.
For a simpler case you can try using tables instead:
https://clarity.design/angular-components/table/
