### ISSUE TITLE
[NG] Support AoT compilation

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#62]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Applications using Clarity components should be able to use AoT compilation.

### Actual behavior

Some of the Clarity components cannot be compiled ahead of time, mostly because they modify HTML elements directly instead of going through the renderer.

### Reproduction of behavior

Pretty hard to reproduce in a plunker...

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.7.0

* **OS and version:** all

* **Browser:** all

**Comment by pratheekhegde** [comment]
I wish this gets resolved ASAP. AOT is a lifesaver sometimes.

**Comment by photostu** [comment]
+1 for needing this... angular-cli v beta.22-1 now has AOT turned on by default

**Comment by wodCZ** [comment]
Hello,
we are currently starting new project with Clarity and [angular-seed](https://github.com/mgechev/angular-seed) and we are having troubles with i18n because of this. 

Please, do you have an estimate on when AoT would be supported in ClarityNG?

Thanks!

**Comment by kucharzyk** [comment]
It will be great to have aot  in Clarity - It looks like angular-cli will need aot compatibillity even without aot enabled (sic!)

**Comment by dragosrusu** [comment]
+1

**Comment by jaffoneh** [comment]
Thanks everyone. This currently our top priority. We have a couple of things to resolve before we're able to make the move and we'll be able to provide better estimates beginning of next week. Stay tuned!

**Comment by photostu** [comment]
This will help bundles sizes for sure, is there an open ticket anywhere to split up the CSS into modules? The CSS bundle for Clarity is really big

**Comment by dragosrusu** [comment]
Don't know if it helps. We created a sass helper for BEM that, unlike
csstyle, perfectly binds to BEM doc; helped us a lot with current devops
project. It also makes a distinction between a modifier and a state. We
opensourced it so I could share the name and components some files for you
to see how it would look.
Of course, it's modularized and customizable on build (you can build the
components based on selected app theme).
Let me know if this is something of interest.

--
Kind regards,
Dragos

**Comment by bytexro** [comment]
Here's the SASS helper: https://github.com/bytexro/xbem

`
@charset "UTF-8";
@include block(selectbox) {
  position: relative;
  font-size: map-get($webc-selectbox, fontsize-text);

  @include element(button) {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    justify-content: space-around;
    @include flex($align: center);
    height: map-get($webc-selectbox, height-button);
    margin: 0;

    @include element(icon) {
      @include flex($justify: center, $align: center);
      background: {
        color:    transparent;
        image:    url('images/arrows.svg');
      }
    }
  }

  @include element(menu) {
    position: fixed;
    overflow: hidden;
    color: map-get($webc-selectbox, menu-color);
    background: {
      color: map-get($webc-selectbox, background-menu);
    }
    @include state(hidden) {
      display: none;
    }
  }
  @include element(list) {
    @include element(item) {
      @include flex($align: center);
      cursor: default;
      @include state(selected) {
        &::before {
          content: '✔';
        }
      }
    }
    @include element(label) {
      overflow: hidden;
      max-width: 80%;
      white-space: nowrap;
      text-overflow: ellipsis;
    }

    @include state(haslimit) {
      max-height: 240px;
      overflow-y: auto;
      &::-webkit-scrollbar-track-piece {
        background: transparent;
      }
    }
  }

  @include element(searchcontainer) {}
  @include element(search) {}
  @include state(alternative) {
    @include element(button) {
      background-color: map-get($webc-selectbox, background-menu);
      @include element(icon) {
        background-image: none;

        &::after {
          content: '▼';
          transform: scaleY(0.45);
          height: auto;
        }
      }
    }
  }

  @include state(ng-invalid, $is-angular-state: true) {
    @include element(button) {
      border-color: map-get($webc-selectbox, color-alert);
    }
  }
}
`

**Comment by photostu** [comment]
"We have a couple of things to resolve before we're able to make the move and we'll be able to provide better estimates beginning of next week. Stay tuned!"

Any updates? Thanks :)

**Comment by jaffoneh** [comment]
@photostu @jeeyun is actually working on getting a PR out there sometime this week!

**Comment by kucharzyk** [comment]
It looks like PR is ready.

Is there any estimated date for next release with this changes?

**Comment by mathisscott** [comment]
If the PR is approved and there isn't too much effort involved with the remaining SASS issue and code review changes, then it should be going into 0.8.0.

The plan is for 0.8.0 to drop next week. If all goes well, it will. If not, it will probably drop the week after.

**Comment by photostu** [comment]
Oh Fuck Yeah! ;-)
