### ISSUE TITLE
Datagrid: Resizable columns

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#621]
**Select one ...**  (check one with "x")
```
[ ] bug
[ x] feature request
[ ] enhancement
```

### Expected behavior

We need to make Datagrid columns resizable so users can adjust the width of the Datagrid columns by dragging the end of the column header. To implement this feature, we need to investigate various potential solutions. For example, right now off top of my head, we could make use of generic `mouse` and `touch` events or native HTML5 Drag and Drop API (Not fully supported in all browsers, so might require polyfills).

This feature is first requested in https://github.com/vmware/clarity/issues/145.
This could be also related to https://github.com/vmware/clarity/issues/620.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by dabkowitz** [comment]
This is what Olga and I came up with...  
Resizing Columns:
- The cursor changes when the user hovers on or near the separator line dividing column headers.
- Only adjacent columns resize at one time.
- The user resize actions should be persistent between log in sessions.

Reordering Columns:
- Optimally this would be a drag and drop action.   User click and drag the column name as opposed to click for sort.
- Optionally reordering could be accomplished in the dialog where the user can select which columns are visible.   This is sub optimal because it is removed and vertical movement does not map well to the horizontal movement of the columns.

**Comment by Shijir** [comment]
Hi @dabkowitz, thanks a lot for your suggestions. I am currently working on column resizing and close to wrapping up. 

>1. The cursor changes when the user hovers on or near the separator line dividing column headers.
>2. Only adjacent columns resize at one time.
>3. The user resize actions should be persistent between log in sessions.

As your first suggestion, the cursor changes when a user tries to resize the column in the current implementation. Also in the current implantation, when a user resizes a column, only that column will be affected. Finally, users can listen to column resizing event through `(clrDgColumnResize)` so they can save the resized width of the columns, apply the width on the next session. 

You can look at the current implementation of column resizing (work in progress) demo by downloading this [video](https://www.dropbox.com/s/71uk115jd54ei8g/datagrid-column-resizing.mov?dl=0).

**Comment by Jinnie** [comment]
Hi @Shijir,
The demo looks great. I have one question though - how it works with the content scrolling feature?
If the datagrid has fixed width and height, then content gets scrollable between the header and footer, both vertically and horizontally.
How will column resizing work when horizontal scroll is on?

**Comment by Shijir** [comment]
Hi @Jinnie, resizing columns doesn't affect the vertical scrolling features much. I would say scrolling feature still works as one expects with the column resizing feature. 

Let's say someone resizes the column width to its very minimum and its content gets squeezed and start to push downward leading to vertically enlarged rows. This will make vertical scrolling just longer as one or more columns' content have become vertically longer. Here is a [demo](https://www.dropbox.com/s/7josow430j7y6yb/datagrid-column-resizing-vscrolling.mov?dl=0) for that case.

The same thing for the horizontal scrolling, when one enlarges a column by dragging, it will just make the horizontal scrolling longer as one of the columns has become larger. Here is a [demo](https://www.dropbox.com/s/56xijilvw22dsli/datagrid-column-resizing-hscrolling.mov?dl=0) for that case.

Fyi, I will get the PR for this issue out tomorrow 😃
