### ISSUE TITLE
@cds/core: `cds-control` with a "label" `cds-control-action` should not apply styling to the custom control

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#6212]
## Describe the bug

When using a `cds-control-action` with `action="label"` (such as the following), the custom control is given custom styling, specifically left/right paddings.

Consider the following code:

```tsx
        <CdsControl>
          <label>with label control action</label>
          <CdsControlAction action="label" aria-label="get more details" onClick={() => alert("!")}>
            <CdsIcon shape={infoCircleIconName}></CdsIcon>
          </CdsControlAction>
          <input placeholder="example" />
        </CdsControl>
```

The `input` element will be automatically given a `style` attribute with:

```css
padding-left: calc((6 / var(--cds-global-base)) * 1rem) !important;
padding-right: calc((6 / var(--cds-global-base)) * 1rem) !important;
```

This causes issues, particularly when the custom control takes care of its own styling. The issue doesn't appear when `cds-control-action` is not used.

## How to reproduce

https://codesandbox.io/s/cds-control-label-bug-udetm

On this sandbox, you can clearly see that the second input is given extra padding when it should not:

<img width="741" alt="Screen Shot 2021-08-04 at 1 07 18 PM" src="https://user-images.githubusercontent.com/113730/128224221-c515be95-ca61-4c9b-9ad2-aff13350de84.png">

## Expected behavior

Both controls on the sandbox above should be identical, i.e. they should look like the top one.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.5.0

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Comment by mathisscott** [comment]
Thanks for submitting this, @astorije 

I will look into why these inline styles are being applied only in the one case to see if I can prevent that from happening. 

Question though... would it be a problem if they were to both look like the bottom one?

**Comment by astorije** [comment]
It would be a problem because this is just a contrived, minimalist example.
When using real-world components that are more complex than a simple input, you're taking a chance by styling the top-level element that might not be the actual control (in our case it's a container, the control is below in the tree).
So if it looked like the bottom one, we'd have to remove the styling on our end, which we cannot because it is applied as a `style` attribute with `!important`, so any solution would require a hack to remove the style on a timeout or something.

I think it would be more beneficial to assume whatever custom control takes care of its own styling.

**Comment by mathisscott** [comment]
Fair enough, @astorije . Thanks for the extra details there.
