### ISSUE TITLE
@cds/core: Incorrect status colors when a control is disabled

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#6214]
## Describe the bug

When a control is disabled and has a `status` of either `success` or `error`, some colors seem a little off:

- The input border goes from red/green back to default disabled gray
- The control message goes from red/green back to default disabled gray
- The status icon retains a non-disabled color

This can be seen below, where a regular input is given as reference:

<img width="742" alt="Screen Shot 2021-08-04 at 1 58 57 PM" src="https://user-images.githubusercontent.com/113730/128233491-b5e664d5-b81d-49b8-af34-11f5919c56a5.png">

## How to reproduce

Here is a sandbox where the above screenshot was taken: https://codesandbox.io/s/cds-control-colors-bug-w2e5e

## Expected behavior

I would expect a lighter red/green exist to represent the disabled states, and have it applied onto the border, message, and icon alike.
Using `var(--cds-global-color-red-200)` and `var(--cds-global-color-green-500)` purely as a frame of reference (because `danger-tint` and `success-tint` are way too light to even make out the text at all), this is how I would envision it:

<img width="745" alt="Screen Shot 2021-08-04 at 2 13 09 PM" src="https://user-images.githubusercontent.com/113730/128233834-52c6ef2c-3cbc-4489-8979-9714b6c337df.png">

(This green definitely does not work here, it needs to be more transparent, not more bright)

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.5.0

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [x] Other: All

**Comment by mathisscott** [comment]
Thanks for creating this issue, @astorije 

I think we need @colinreedmiller 's input on this. Also, I'm not sure if the correct path is to make these inputs and messages light green/red or to make the success/error icons gray. That would be in @colinreedmiller 's wheelhouse. The light red/green text does have some impact on accessibility so that's a consideration as well.

**Comment by colinreedmiller** [comment]
I am not reading this as a bug per se. I see a preference for making a visual change, but not support for it improving usability while not confounding a11y or something else. Can we examine a use case where the component is in an error or success state then becomes disabled, or where it is surfaced to the user in a success/error + disabled state already? The color is largely decorative / an additional cue for sighted users, while the (crucial) communication of state is conveyed by the icon - this appears to be less effective and possibly an a11y concern in the latter example.

**Comment by astorije** [comment]
Fair enough. Let me know if there is any change to the component styling you would like me to open a PR for, otherwise feel free to close this PR!
