### ISSUE TITLE
Incorrect package version

### ISSUE THREAD

**Issue by wendellestradairely** [vmware/clarity#6225]
When you `npm i @clr/<package>@latest`, the version number becomes 12.0
![image](https://user-images.githubusercontent.com/50942719/128456211-9cd64935-4365-4072-96cd-4f959d360f23.png)

**Comment by bbogdanov** [comment]
Hi @wendellestradairely, 

That's correct! 12.0.1 is the latest version of `@clr/*` packages.

https://www.npmjs.com/package/@clr/angular
