### ISSUE TITLE
clr-datagrid action-overflow not visible and formatting issues with dynamic data

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#623]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The datagrid should work flawlessly even for dynamic data.

### Actual behavior
If i have data coming in from server, the datagrid does not show the action-overflow column for the grid and the columns are also highly misaligned.
Only when some user-action triggers something in angular does the datagrid re-render properly as expected.
1. In the plunker, wait for two seconds for the first grid to load data.
2. See the problems. 
3. Then just hover over the green button which has a bound (mousehover) to trigger angular.
4. Watch how the first grid re-renders correctly

### Reproduction of behavior

https://plnkr.co/edit/J5oMyeVWgGWJFTrg9B73

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.11

* **OS and version:** 

* **Browser:** all

**Comment by youdz** [comment]
Very strange, it indeed looks like Angular doesn't redraw the grid until something, anything, happens. Even clicking anywhere in the slow-loaded Datagrid works.

We'll investigate this asap, but we'll just wait to see if a new feature coming in Datagrid soon that might fix this naturally (some redraw triggers were modified).

**Comment by sivaah** [comment]
I would suggest to test all [datagrid examples](https://vmware.github.io/clarity/documentation/datagrid) with results returned from server (by delaying the data by few milliseconds using setTimeout()). Since datagrid mostly used with dynamic data returned from server.

**Comment by Jinnie** [comment]
You can force a change detection cycle using ChangeDetectorRef::detectChanges(), like in this fork of your plunker:
https://plnkr.co/edit/tTIMvuXXEgOaqH5mkpPG?p=preview
In my opinion it should not be the user's concern to do this, but it will solve both your problems for the time being 😃

**Comment by raijinsetsu** [comment]
My team also bumped into this issue.
I wanted to look at the suggested work-around, but Jinnie's plunkr is not longer accessible.
