### ISSUE TITLE
Alert Component with custom Icon showing dotted loading animation

### ISSUE THREAD

**Issue by neffsvg** [vmware/clarity#6230]
## Describe the bug

Instead of showing the custom Icon shape alert component only shows dotted (loading) icon.

## How to reproduce

See docs: [https://clarity.design/core-components/alert/code/](https://clarity.design/core-components/alert/code/) 

## Expected behavior

Show correct shape. 

## Versions

**Clarity project:**

- [ 5.5.1] Clarity Core
- [ 12.0.1] Clarity Angular/UI

**Framework:**
I found that in our own project using latest 12.0.1 clr/angular and 5.5.1 cds/core. Went through the docs and found the same bug here.

**Device:**
- Type: laptop
- OS: macos | ubuntu
- Browser: chrome
- Version: latest

![clairty-custom-alert-icon-issue](https://user-images.githubusercontent.com/88536846/128492712-49a334eb-84ff-4974-b923-257c2493918e.png)

**Comment by mathisscott** [comment]
That is because the site isn't loading the custom icon into the `ClarityIcons` registry. Thanks for pointing that out. It's a pretty easy fix.
