### ISSUE TITLE
website(core/storybook): Tables are not displayed correctly when wrapping

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#6236]
## Describe the bug

This is how a table on Storybook renders:

<img width="971" alt="Screen Shot 2021-08-06 at 4 11 04 PM" src="https://user-images.githubusercontent.com/113730/128566266-c80c07e4-b92c-48c8-a439-c924ef00bbd0.png">

This is how it renders on a smaller monitor:

<img width="909" alt="Screen Shot 2021-08-06 at 4 11 46 PM" src="https://user-images.githubusercontent.com/113730/128566349-19aa81c4-2c9a-4a1c-8af5-022647b73f1f.png">

## How to reproduce

Go to https://clarity.design/storybook/core/?path=/story/foundation-object-styles--page and resize the page down.

**Comment by coryrylan** [comment]
I saw this issue, we need to adjust the breakpoints on the CSS grid that is laying out the table for the tokens https://github.com/vmware/clarity/blob/next/packages/core/src/styles/tokens/tokens.stories.ts#L33

We could probably set the breakpoint to ` cols@sm:4` instead of ` cols@md:4`
