### ISSUE TITLE
datagrid column  level sorting inconstitent  when we have list of  same value under the column 

### ISSUE THREAD

**Issue by muruganG** [vmware/clarity#6239]
## Describe the bug

When i have cloumn as same value in the datagrid sorting  inconsistent  ,some time sorting happeing  , what is the expected approach for same value on the column sorting .
sharing the snapshot  for the datagrid document datagrid filer with sorting.

1.  go to clarity 4 documentation and datagrid 
2.  datagrid filer same value and do the sorting/ 

## Expected behavior

Same value also datagrid  column level sorting need to happen. 

## Versions
clarity 4.1
**Clarity project:**

- [ yes] Clarity Core
- [ yes] Clarity Angular/UI

**Clarity version:**

- [ yes] v4.x

**Framework:**

- [ yes] Angular
-
**Framework version:**
_ie: Angular 10

**Device:**

## Additional notes

_Add any other notes about the problem here._

![image](https://user-images.githubusercontent.com/10629787/128660349-e4555272-4996-48af-9551-340461930070.png)

**Comment by Jinnie** [comment]
The built-in sorting utility depends on the native JS Array.sort() implementation. It does not use secondary parameter for sorting. If you need fully predictable sorting even in this case, you can implement a custom comparator, that takes any additional information needed while sorting.
Please find more information here: https://angular.clarity.design/documentation/datagrid/custom-sorting
