### ISSUE TITLE
No 'resize' icon in clarity iconography

### ISSUE THREAD

**Issue by Kushmaro** [vmware/clarity#624]
[ ] bug
[ ] feature request
[x] enhancement

### Expected behavior
Clarity icons should contain a 'resize' icon since it's a common icon to use.

### Actual behavior
No resize icon available

* **Clarity version:** 
latest

* **OS and version:** 
N/A 

* **Browser:** 
All

**Comment by lil-kim** [comment]
Hi @Kushmaro, 
I'm happy to create the new icon, I just need some context. Do you mean 'resize' in context of resizing a picture up/down; expanding a window - like at the bottom right corner of a comment window? Or other?
Thanks.

**Comment by Kushmaro** [comment]
Hi Lila,
I was thinking about something like this:
[image: Inline image 1]

make sense for windows / other expandable items.


Thanks for the prompt reply!
Omer

**Comment by Kushmaro** [comment]
Ah, just saw that gmail ruined my comment.
see reference 'resize' here:
http://fontawesome.io/icon/expand/

**Comment by lil-kim** [comment]
This icon is being addressed in Github issue #609
https://github.com/vmware/clarity/issues/609

**Comment by lil-kim** [comment]
Requested icon added to Github issue #609 for 0.8.13 release, closing this ticket.
