### ISSUE TITLE
core: `cds-control` can expand outside of its container width

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#6249]
## Describe the bug

When the content of a custom `cds-control` is long, it can force the component to go outside of its container.

<img width="748" alt="Screen Shot 2021-08-11 at 1 02 43 PM" src="https://user-images.githubusercontent.com/113730/129072178-2f1b0d7b-7732-45b0-b065-31aea82be9f9.png">

## How to reproduce

https://codesandbox.io/s/cds-control-overflow-sjdkz

The first block is a regular paragraph that stays within the boundaries of its container, even when force not to wrap.
The second block is a `cds-control`. As you can see, the content goes out of the screen.

## Expected behavior

Both elements should look like the top one.

<img width="747" alt="Screen Shot 2021-08-11 at 1 02 03 PM" src="https://user-images.githubusercontent.com/113730/129072222-a78634b5-751d-4ed4-ab3d-1d1ab2806626.png">

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [x] Other: All

## Additional notes

@mathisscott and @dturcotte had a chat about this, and it sure is tricky. We identified 2 options for this:

- @mathisscott suggested adding a `max-width` of `var(--internal-label-max-width)` (or `calc(var(--internal-label-max-width) - 1rem)` if using a `status`) as a hack to avoid changing the library itself. This works, but... only when used in a `cds-form-group` **and** its layout is `horizontal`. This solution means Clarity needs to expose `--internal-label-max-width` regardless of the layout.
- Another option is to try and add a boundary to the `div.input-container` element within the shadow root of `cds-control`, for example some variation of `max-width: 100%` + some math.

In both cases, `status` makes it tricky because it's not a simple `100%` anymore. Worse, since the control action can take any size, it's not a matter of `100% - 1rem` (as the default success/error action takes about that width).

@mathisscott, let me know if I missed or misrepresented something. Either way, thanks a ton for the help! 🙏

**Comment by coryrylan** [comment]
The second option could work as a fix. We can calc off the max width if the status is error or success on the .input-container.

Here is a possible workaround if you are blocked
https://stackblitz.com/edit/http-server-apny3t?file=src%2Findex.ts

**Comment by mathisscott** [comment]
I have a fix for this issue in the pipeline. I should have a PR up for it tomorrow. ￼

**Comment by astorije** [comment]
Resolved by https://github.com/vmware/clarity/pull/6254, thanks again!
