### ISSUE TITLE
core: month input type

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#6255]
## Summary

- What is the change?

Add support for  [`<input type="month" />`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month).

- Why should it go in Clarity?

Clarity Core already has support for [date](https://clarity.design/storybook/core/?path=/story/forms-date--page) and [time](https://clarity.design/storybook/core/?path=/story/forms-date--page), so `month` seems like a logical next step.

Additionally, it seems like Clarity is almost all the way there. Here is how it looks like when I use `type="month"` inside a `cds-date`:

<img width="566" alt="Screen Shot 2021-08-12 at 11 40 39 AM" src="https://user-images.githubusercontent.com/113730/129226505-cae98e92-48ff-4e7f-801a-af5811ec350a.png">

Close!

- Does this change impact existing behaviors? If so how?

Nope

- If this change introduces a new behavior, is this behavior accessible?

Yep

## Use case

We use month/year selectors _everywhere_ at CloudHealth. A lot of our features apply on a monthly basis, so this would help us a ton. At the moment, we are using a bunch of input groups with select boxes for month + year, but this would make the code a lot simpler and more accessible, as well as improve consistency across our applications.

## Examples

<img width="444" alt="Screen Shot 2021-08-12 at 11 44 55 AM" src="https://user-images.githubusercontent.com/113730/129226949-07284a86-8ce2-438c-92aa-1403348d70b7.png">

<img width="556" alt="Screen Shot 2021-08-12 at 11 45 57 AM" src="https://user-images.githubusercontent.com/113730/129227136-0fe650d5-dcc8-436c-b74c-45e46ef953d1.png">

<img width="606" alt="Screen Shot 2021-08-12 at 11 52 21 AM" src="https://user-images.githubusercontent.com/113730/129228180-6d694164-e044-47a6-8220-8c883e1e8195.png">

**Comment by mathisscott** [comment]
@astorije 
Right now, [the month input lacks browser support](https://caniuse.com/mdn-html_elements_input_input-month). We would need at least safari to adopt it in order to officially support it. That said, you can use any type of HTML input with `@cds/core` forms. So if you don't mind the browser support concerns coming up on the application side, you should be able to use the month input type with no issues.

**Comment by astorije** [comment]
> Right now, [the month input lacks browser support](https://caniuse.com/mdn-html_elements_input_input-month). We would need at least safari to adopt it in order to officially support it.

Oh my bad, I didn't realize support was so low there, that's too bad it would have been perfect. Thanks for pointing that out!
At CloudHealth we decided to adopt the exact same browser support than Clarity did, so it works for us to avoid this component for now and solely relying on yours.
