### ISSUE TITLE
Compact clarity forms do not work well with labels that wrap to two lines

### ISSUE THREAD

**Issue by tihomir-varbanov** [vmware/clarity#626]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Vertical spacing between labels in compact clarity forms should be fixed. Here are a few suggestions:
- when a label wraps to two lines, the second line should appear closer to the first line rather than closer to the next form-group element
- show ellipses instead of wrapping the label
- increase the space between the wrapped line and the next form-group element in the form

### Actual behavior

Long labels in forms wrap to two lines. For compact forms, the second line appears too close to the next form-group element.

### Reproduction of behavior

https://plnkr.co/slax56TnTXN3ljuulFz2

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8,11

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@tihomir-varbanov: If you have a case where you need to use a really long label then we recommend that you use forms in a grid. Refer to this plunk: https://plnkr.co/edit/hkKtU7yyDSgOF3eB2ko1?p=preview

Forms without grids assume that the label is short.

**Comment by Jinnie** [comment]
It's a bit cheesy, nevertheless...
Especially in applications featuring i18n and l10n, where the translations in languages like French of German can drastically increase in size compared to your best intentions in English to have a short and concise label.
Also some German texts can feature LongCompositeWordsWithoutBreak that can destroy your layout in ways you haven't imagined. 😄 
Although the grid helps, I think that the form elements need to be more self sufficient, and not make assumptions. I personally try to avoid using grids if possible, the code gets bloated and hard to maintain, IMO.

**Comment by adityarb88** [comment]
@Jinnie: Thats a good point. I guess we could consider adding a text-overflow: ellipsis option and make sure that the labels dont wrap but that doesnt solve the issue. The forms (without grids) were one of the first components implemented and the label was given a width of around 220px area to grow. We need to revisit this and make some styling changes. I will add this to our backlog and take a look.

**Comment by reddolan** [comment]
Overflow (ellipsis) is a nice additional feature. However in the case that teams want or need to wrap, decrease the line-height on labels is necessary. 

@adityarb88 even in the plnkr example using a grid, it still looks like the line-height needs to be decreased.

**Comment by gnomeontherun** [comment]
This should be resolved with the new forms, closing in favor of using new form layouts.
