### ISSUE TITLE
Dark theme styles exist but not being applied

### ISSUE THREAD

**Issue by afulkersonApollo** [vmware/clarity#6267]
EDIT: looks like you have to add "node_modules/@clr/ui/clr-ui-dark.min.css" to the styles section of angular.json to enable dark mode in an Angular app. It would be nice to include this information in the docs.

## Describe the bug

After bootstrapping a new Angular app and installing Angular and web components, dark mode styles are not applied even though they are visible in browser devtools as `[cds-theme=dark] { ... }`.

## How to reproduce

Bootstrap an Angular app and install the Angular and web components according to installation instructions. Attempt to enable dark mode by setting `cds-theme="dark"` on the body element.

## Expected behavior

Components will use the dark mode theme.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Device:**
MacBook Pro
Chromium/Chrome/Edge

**Comment by Shijir** [comment]
Have you installed `theme.dark.min.css` style file?
```css
// import into sass or css
@import '~@cds/core/styles/theme.dark.min.css';

```
```html
// or import in html
<link href="/node_modules/@cds/core/styles/theme.dark.min.css" rel="stylesheet">
```

You can learn more here: https://clarity.design/storybook/core/?path=/story/themes-getting-started--page

**Comment by afulkersonApollo** [comment]
> Have you installed `theme.dark.min.css` style file?
> 
> ```css
> // import into sass or css
> @import '~@cds/core/styles/theme.dark.min.css';
> ```
> 
> ```
> // or import in html
> <link href="/node_modules/@cds/core/styles/theme.dark.min.css" rel="stylesheet">
> ```
> 
> You can learn more here: https://clarity.design/storybook/core/?path=/story/themes-getting-started--page

I did all of that. I fixed it by adding "node_modules/@clr/ui/clr-ui-dark.min.css" to angular.json. Seems like the Angular installation script is missing a step or there should be documentation about it.

**Comment by Shijir** [comment]
If you are using components from @clr packages, `clr-ui-dark.min.css` is what you need to apply dark theme. For components from @cds packages, you need `theme.dark.min.css` along with `[cds-theme=dark] { ... }`

**Comment by afulkersonApollo** [comment]
> If you are using components from @clr packages, `clr-ui-dark.min.css` is what you need to apply dark theme. For components from @cds packages, you need `theme.dark.min.css` along with `[cds-theme=dark] { ... }`

Right, that's the proper way to use the dark theme but the documentation lacks that information.

**Comment by Shijir** [comment]
Currently, our documentation shows examples for both cds and clr components which leads to confusion. But, we are working on improving our documentation so there will be a clear separation between clr and cds components.

**Comment by afulkersonApollo** [comment]
> Currently, our documentation shows examples for both cds and clr components which leads to confusion. But, we are working on improving our documentation so there will be a clear separation between clr and cds components.

The documentation does show examples for the usage of components but does not contain information pertinent to the usage of the dark theme with CLR components. I'm not confused, the documentation doesn't contain the information required to properly install the dark theme for CLR components.
