### ISSUE TITLE
Table headers (Angular) don't have a setting in dark mode

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#6276]
## Describe the bug

The table headers in Angular use a hard coded color #666

![image](https://user-images.githubusercontent.com/6342391/130126191-3a37c714-3f1c-416e-8df3-e13e1bd31445.png)

The file  _theme.dark.clarity.scss doesn't have an override for it and the table headers remain darkish gray on dark mode.

## How to reproduce

Create a table with table header in dark mode. You can see the css var used in light mode here: https://angular.clarity.design/documentation/tables

There you noticed the hard coded color (as seen above)

## Expected behavior

A lighter color in dark mode

## Versions

**Clarity project:**

- [] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.4.1

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11.2.14

**Comment by rbirkgit** [comment]
First step is to find out what the color should be, then it's easy to add.

**Comment by Shijir** [comment]
Closed by https://github.com/vmware/clarity/pull/6285
