### ISSUE TITLE
Dark theme for cds-select does not apply the correct border color

### ISSUE THREAD

**Issue by afulkersonApollo** [vmware/clarity#6277]
## Describe the bug

When using `<cds-select>`, `<select multiple>` and `<body cds-theme="dark">`, the border-color of the select is black.

## How to reproduce

Install the dark theme and use the previously mentioned tags/attributes.

1. Screenshot attached

## Expected behavior

The multi-select will exhibit the proper border color.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Device:**

- Type: MacBook
- OS: macOS
- Browser Edge
- Version Latest

## Additional notes
![Screen Shot 2021-08-19 at 1 01 51 PM](https://user-images.githubusercontent.com/78375272/130128780-f40eac71-603c-4652-ae4e-fa3f5af69f1e.png)

**Comment by Shijir** [comment]
Looks like it's working as expected when I try to reproduce in Stackblitz: 
https://stackblitz.com/edit/clarity-light-theme-v5-yval7z?file=src/app/app.component.html

**Comment by afulkersonApollo** [comment]
So, I'd try if I could figure out how to get the terminal working (it hangs forever when I try to open a new one) but in my case I'm using both cds and clr for Angular and have included the CSS for those packages. In your example I don't see the clr CSS packages but if I remove them from my project, everything looks awful. The stackblitz is also using old packages.

**Comment by afulkersonApollo** [comment]
<img width="371" alt="Screen Shot 2021-08-20 at 9 44 32 AM" src="https://user-images.githubusercontent.com/78375272/130258991-cfc44a17-0fef-4ea2-aa7f-2be9b631c629.png">
<img width="429" alt="Screen Shot 2021-08-20 at 9 44 46 AM" src="https://user-images.githubusercontent.com/78375272/130259031-602fa307-65a9-4c51-a024-b44d0de9208f.png">
<img width="436" alt="Screen Shot 2021-08-20 at 9 45 51 AM" src="https://user-images.githubusercontent.com/78375272/130259179-d47ecfbc-83e2-4952-aaae-427657a4d071.png">
