### ISSUE TITLE
Index html generation failed. undefined:9:283862: property missing ':'

### ISSUE THREAD

**Issue by glivolsi** [vmware/clarity#6306]
The issue is in the the class
.clr-icon.clr-vmw-logo{
   background-image: url(.....)
}

PLEASE FIX

Just follow the release documentation for the moment we release Clarity version that will work with Angular 12.

_Originally posted by @Jinnie in https://github.com/vmware/clarity/issues/5947#issuecomment-851399532_

**Comment by coryrylan** [comment]
This is an upstream dependency issue in the Angular CLI. You can follow this issue for a workaround
https://github.com/angular/angular-cli/issues/20760

The typical workaround is adding `"inlineCritical": false` to the `angular.json` file
https://github.com/vmware/clarity/blob/next/apps/core-angular-cli/angular.json#L64
