### ISSUE TITLE
Card Width Independent from ColSpan Property

### ISSUE THREAD

**Issue by rpvmw** [vmware/clarity#6308]
## Describe the bug

The [grid documentation](https://clarity.design/storybook/core/?path=/docs/layout-grid--page) describes that the colspan of an individual block can be changed by setting the attribute `cds-layout="col:x"` where `x` is the colspan for that item.

However, when a grid block is a Card, the card will not fill up the entire colspan. It allocates space for it, but the card does not stretch to fill it.

## How to reproduce

I did not see a React template on StackBlitz to fork, but here is the code I am using for the page:
```js
import React from 'react';
import { CdsCard } from '@cds/react/card';

const TestPage = (props) => {
  return (
    <main cds-layout="p:lg vertical gap:lg" cds-text="body">
      <div cds-layout="grid gap:md">
        <CdsCard cds-layout="col:4">
          Can you imagine what we will be downloading in another twenty years?
        </CdsCard>
        <CdsCard cds-layout="col:5">
          Who would have ever thought that you could record sound with digital quality fifty years ago?
        </CdsCard>
      </div>
    </main>
  );
};
export default TestPage;
```

![image](https://user-images.githubusercontent.com/89876212/131581724-5ea88255-58b1-4670-a463-a0bb591603e9.png)

## Expected behavior
By adding a style component `style={{ backgroundColor: 'orange', width: '100%' }}` to the first card, we can see that the first Card is indeed taking up 4 columns but it's just not expanding over it.
![image](https://user-images.githubusercontent.com/89876212/131581605-b7f904a7-6037-4240-a4de-c9d0b0c3ca33.png)

We can also see that the card _will_ expand if we add more text to it.
![image](https://user-images.githubusercontent.com/89876212/131581519-2a31b632-feba-457c-bd9f-c26ed72de601.png)

I believe the desired behavior is that the Card border expands to fill the entire allotted space.

## Versions

**Clarity Project: Core**
**Clarity Version:**
```
├─ @cds/city@1.1.0
├─ @cds/core@5.5.2
│  ├─ @cds/city@^1.1.0
├─ @cds/react@5.5.2
│  ├─ @cds/city@^1.1.0
```

**Framework: React**
```
├─ react@17.0.2
├─ react-dom@17.0.2
```

**Device:**
- Type: MacBook Pro
- OS: Catalina 10.15.7
- Browser: Chrome 92.0.4515.159

## Additional notes
- Packaged using Webpack

**Comment by bbogdanov** [comment]
Hi @rpvmw, 

The reason for the behaviour is https://github.com/vmware/clarity/blob/884148ead594ef6a19db0c0fcf3581ab45d9f85d/packages/core/src/card/card.element.scss#L4 

We made sure to make the `width` property of the container available for change so you can change it as you see fit. 

[Demo](https://stackblitz.com/edit/http-server-ujxmez?file=src%2FApp.tsx)

**Comment by bbogdanov** [comment]
https://cds.wtf is a place that you can use to get stackblitz templates for React, Angular, Vue, etc.
