### ISSUE TITLE
Paging to last page of large dataset --> grid disappears !

### ISSUE THREAD

**Issue by kodemasta** [vmware/clarity#631]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
paging should work for large number of rows independent of total row count and pageSize.

### Actual behavior
For some paging settings --> selecting the last page causes the grid to disappear including header and footer ! Expected last page of data is not accessible !

### Reproduction of behavior
Create a grid with 1200 Users (rows)
Set pageSize to 473. Then select 3rd page and grid disappears.
We were able to repro with various page and data sizes as well.

(some sort of floating point paging calculation error ?)

plunkr: https://plnkr.co/edit/zZZOW0utKuNZS572CaGI?p=preview

### Environment details

* **Angular version:** 2.4.1

* **Clarity version:** 0.8.11 

* **OS and version:** MacOs 10.11.2

* **Browser:** Chrome, Firefox,...

**Comment by youdz** [comment]
Could you please post a plunker reproducing the error? Thank you.

**Comment by bobsheehan1** [comment]
OK Added plunker to bug description: https://plnkr.co/edit/zZZOW0utKuNZS572CaGI?p=preview

**Comment by Jinnie** [comment]
@bobsheehan1 
The datagrid on the last page gets "squeezed" up to the top by unpredicted sub-component behavior, which probably conflicts with the recent datagrid content scroll feature.

Here's a plunker that simplifies and illustrates the case:
https://plnkr.co/edit/CdJH5W7PUE4jKPkdKLYp?p=preview
The bottom half is growing in size (min-height) if you play with the page size.

@youdz, it seems someone had a premonition, writing this comment :rofl: 
> I hate doing this, with these 36px...

**Comment by youdz** [comment]
Thank you for the plunker. 👍 

As Jinnie mentioned, this is a general issue with the placeholder since the switch to flexbox. We have 2 or 3 issues related to this, hopefully we can fix them all at once.
