### ISSUE TITLE
Mixed User Feedback Display for `CdsControlMessage`

### ISSUE THREAD

**Issue by rpvmw** [vmware/clarity#6319]
## Describe the bug

`CdsControlMessage` is showing a mix of success/error user feedback when controlled by a state hook.

When a valid month is selected, the success message shows as expected.
![image](https://user-images.githubusercontent.com/89876212/132071896-2e051d82-1e3c-4004-aabb-f6c6ef8e4cd1.png)

But when an invalid month is selected, there is a combination of success/error feedback.
![image](https://user-images.githubusercontent.com/89876212/132071806-55888a5d-703c-4169-8386-64aca26b5de2.png)

## How to reproduce
Use state to control the `CdsControlMessage` in a `CdsSelect`. StackBlitz [here](https://stackblitz.com/edit/http-server-sjax8e?file=src/App.tsx)

## Expected behavior
All user feedback displays as either error or success.

## Versions

**Clarity Project: Core**
**Clarity Version:**
```
├─ @cds/city@1.1.0
├─ @cds/core@5.5.2
│  ├─ @cds/city@^1.1.0
├─ @cds/react@5.5.2
│  ├─ @cds/city@^1.1.0
```

**Framework: React**
```
├─ react@17.0.2
├─ react-dom@17.0.2
```

**Device:**
- Type: MacBook Pro
- OS: Catalina 10.15.7
- Browser: Chrome 92.0.4515.159

## Additional notes
- Packaged using Webpack
- Reproduced on StackBlitz

**Comment by rpvmw** [comment]
Possibly related to bug #6313? If so, maybe PR #6317 will fix?

**Comment by coryrylan** [comment]
@rpvmw yes pr #6317 will fix this issue
