### ISSUE TITLE
Icon: "Pin" icon needs its counterpart icon: "unpin"

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#6327]
The Clarity library currently has a "pin" (thumbtack) icon, but there is no icon denoting "unpin".
![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/075dce44-2580-4829-9223-078c9699b406)

**Comment by lil-kim** [comment]
Please add this "unpin" icon to the Clarity icon library:
[unpin icon.zip](https://github.com/vmware/clarity/files/7124322/unpin.icon.zip)
cc: skalarikkal@vmware.com

**Comment by bdryanovski** [comment]
This must be added into Icon vol 21

**Comment by coryrylan** [comment]
This is on the datagrid branch now
