### ISSUE TITLE
Clarity Vertical Nav documentation lacks code example for nav-header

### ISSUE THREAD

**Issue by TechScar** [vmware/clarity#6330]
## Describe the bug

The Clarity Vertical Nav documentation features an image example for a vertical nav including dividers and headers, however neither in the Overview (pre-v5 called "Design Guidelines") nor the API (pre-v5 called "Code & Examples") tab you can find any code example or further elaboration on the header feature.

I was only able to find the _.nav-header_ class by sheer coincidence after experimenting based on the divider API.

## How to reproduce

1.  Go to the [Layout section in the Clarity Vertical Nav documentation](https://clarity.design/angular-components/vertical-nav/#layout)
2.  See the rightmost of the three images with a description for **Dividers & Headers**
![image](https://user-images.githubusercontent.com/89379344/132458746-932804e5-d957-424a-9e98-f3051f09a65a.png)
3.  Expand all code sources (and check the API tab for v5)
4.  See that there is no mention of the **nav-header** feature anywhere

## Expected behavior

A mention of the nav header feature in the code examples and the API tab with the correct usage:
`<div class="nav-header">Header Text</div>`

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [x] v3.x
- [x] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12 (but really shouldn't matter as it's a documentation issue)

**Comment by bdryanovski** [comment]
@TechScar - thanks for noticing it, we need to update the documentation and provide an example of how to use the divider. We gonna try to add it into the upcoming releases of the documentation.
