### ISSUE TITLE
Using sass 1.33+ gives pages of deprecated warnings

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#6331]
## Describe the bug

sass 1.33.0 changed their syntax with regards to divisions. With this you get pages of deprecated warnings when building Clarity Angular projects. With Angular 12 @angular-devkit/build-angular is now hard coded to use 1.36.0 and ng-packagr is using ^1.32.8 which result that our projects will be using 1.33+
 
## How to reproduce

Create an Ang12 project and build a Clarity project. You will see all the warnings, e.g.:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($clr-baseline-denominator, $browser-default-size)
More info and automated migrator: https://sass-lang.com/d/slash-div
   ╷
18 │ $clr-basefont-size: ($clr-baseline-denominator/$browser-default-size) * 100% !default;
```

## Expected behavior

Update scss files syntax to new standard.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x
- [x] v12.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12.2

## Additional notes

I think this should be fine to do with Clarity 12 as Angular 12 projects will all be using 1.33+

**Comment by rbirkgit** [comment]
Looks like if you are using Angular 12.0 you may still have sass 1.32. With Angular 12.2 you will have 1.33+. I think it should be fine to require users to update to 1.33+ in their projects for those few remaining on 12.0.

**Comment by bdryanovski** [comment]
@rbirkgit thanks for reporting it. We gonna need to make some checks before updating it
