### ISSUE TITLE
core(progress-circle): default aria-label value

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#6334]
## Summary

- What is the change?

Add a default `aria-label="Loading…"` on the `cds-progress-circle` component. When `value` is used, this could instead be `Loading: ${value}%…`.

- Why should it go in Clarity?

Some Core components currently contain a default `aria-label`, such as the modal close button. This would be in line to provide a similar experience.

- Does this change impact existing behaviors? If so how?

It would impact existing use cases but not if the `aria-label` is already used: explicitly providing one would override the default value.

- If this change introduces a new behavior, is this behavior accessible?

I believe this would increase the accessibility of the existing component. There are internationalization considerations to keep in mind, but this would be no different than the modal close button label or similar other elements.

## Use case

At CloudHealth, we are replacing our existing circular progress component with Clarity's. Our component currently contains a default `aria-label` and we would like to avoid requiring all our developers to remember to add `aria-label` as it would be forgotten most of the time.

## API

There is no change to the existing API. However, if it is desirable to maintain the possibility to have no `aria-label`, one could explicitly give `aria-label=""`. It is probably not a good idea to not include an `aria-label` in general, so it seems like a good idea to make exceptions visually identifiable.

**Comment by mathisscott** [comment]
this sounds reasonable to me. it may take us a few weeks to get to it though...

**Comment by astorije** [comment]
Thanks @mathisscott! Let me know if I can help, I'd be happy to :)
