### ISSUE TITLE
core(progress-circle): support an explicit label next to the circular icon

### ISSUE THREAD

**Issue by astorije** [vmware/clarity#6335]
_This is not a duplicate or an alternative proposal to https://github.com/vmware/clarity/issues/6334, both those things would be independently valuable. There is however some overlap, which I'll describe below._

## Summary

- What is the change?

Having the ability to include a text label on the right side (in LTR languages) of the circular icon.

- Why should it go in Clarity?

While this can totally be done outside of this element (which is what we are currently doing, in fact), having this a part of the Clarity element ensures consistency and improved accessibility (I'll get to that) across projects using Clarity.

- Does this change impact existing behaviors? If so how?

It does not as the label would be optional.

- If this change introduces a new behavior, is this behavior accessible?

This should be accessible by design (it is just text, in the end). However, this might conflict with the `aria-label` on the surrounding `cds-progress-circle` element, especially if a default one is generated from https://github.com/vmware/clarity/issues/6334. In this case, the default could then take the value of the new `label` attribute, or be empty since the text is a more accessible solution than `aria-label`.

## Use case

It can be helpful in some cases to display a specific loading message / label, for example when:

- There are more than 1 distinct elements loading at a given time, to inform the user about what is being loaded.
- What is being loaded is not the direct response of a user action, so the user might not know what is being loaded and a custom message gives more appropriate feedback.

## Examples

This can be seen when loading https://console.cloud.vmware.com/csp/gateway/portal/#/consumer :

<img width="412" alt="Screen Shot 2021-09-10 at 4 59 02 PM" src="https://user-images.githubusercontent.com/113730/132917045-c4d2866f-7b0e-4f92-ac14-377172806aec.png">

At CloudHealth, we currently have this component:

<img width="120" alt="Screen Shot 2021-09-10 at 5 00 25 PM" src="https://user-images.githubusercontent.com/113730/132917087-9aedf6e2-dc43-40e7-9f77-8b4dd86acfba.png">

which we are replacing with a simple progress circle (hence the need for https://github.com/vmware/clarity/issues/6334) in most cases. However, we support giving the component a custom loading message:

<img width="239" alt="Screen Shot 2021-09-10 at 5 01 33 PM" src="https://user-images.githubusercontent.com/113730/132917212-2551ca64-bd05-4c36-9adf-2a8f093b8be1.png">

## API

- There is at least one new attribute to support here, e.g. `label` or `message`, etc.
- It might be good to provide an option where to locate the label, e.g. a `position` attribute. `left`/`right` might not be good for RTL languages (therefore `before`/`after` might be better), but I think for consistency purposes it would be a good idea to always keep the icon on the left of the label. Then said `position` attribute would only support `top` and `bottom` values.
- Also for consistency purposes, the label could be sized after the same `size` attribute than for the icon. They would "scale" together.

## Conclusion

I would be happy to help with this if you think this is a valuable addition to Clarity.

**Comment by bdryanovski** [comment]
@astorije - I think that this could be just a pattern on how to structure the progress circle component and adding additional content to it. Our goal is to have small and atomic components that could be used to create bigger complex components that could serve whatever is required.

We had some internal discussions on starting to provide design patterns on few common components without adding additional configuration to existing components - this way we gonna prevent having a lot of functionality that may or may not be useful for everyone.

I think here @mathisscott and @coryrylan - could say more on the topic.

**Comment by mathisscott** [comment]
Hi @astorije 

I think this is something that is best accomplished using the layouts and typography provided with Core already.

**Comment by astorije** [comment]
Makes sense. @mathisscott, does Core have recommendation on which typography to use for the use cases above? It would be great if there was a way to do this consistently across all VMW projects using Clarity Core. This would definitely be tremendous for us at CloudHealth.

**Comment by mathisscott** [comment]
Hi @astorije :

I think it depends on context. If we have a label like this next to a progress circle inside of a form control, I think the font-weight would depend on whether the form control mimicked an input or a radio/checkbox control.

If it's used as a loading notification, it likewise depends on how prominent the loading message needs to be. A heavier font weight adds visual noise so it's probably not appropriate if the loading message is not meant to draw the attention of the user. 

From the perspective of Clarity Core, this is something we would allow a custom property for. So apps could customize it as they need to.

I'm not sure if that is a helpful response. But I will ping @colinreedmiller for guidance on this topic as well.

**Comment by colinreedmiller** [comment]
@astorije 
Clarity Core takes the approach of limited sizes suggested for specific uses, with weight (and line height) flexible to provide latitude to adjust hierarchy. What this means in this case is that you are free to select the size that is appropriate. This should be straight forward because related components (such as form elements as Scott mentions) will provide the context. This 'consistent size' approach is best practice for typography for visual balance and consistency - by increasing or reducing weight you can get the right degree of importance.

In your case I'd suggest mirroring the size of what is nearby / related and reducing the weight since the prominence is that of an annotation or extra clarification of the circle. To get directly to it: I'd be surprised if it was anything other than: Secondary (13px) REGULAR 
```
--cds-global-typography-secondary-font-size
--cds-global-typography-font-weight-regular
--cds-global-typography-color-300
```
