### ISSUE TITLE
[Bug] Datagrid filter/order don't work with hyphen object.

### ISSUE THREAD

**Issue by MRMokwa** [vmware/clarity#634]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Filter and Sort should work when `<clr-dg-cell>` is used with an hyphenated property.

```
   <clr-dg-row *clrDgItems="let cidade of data">
      <clr-dg-cell>{{cidade['cod-pais']}}</clr-dg-cell> //Doesn't Work
      <clr-dg-cell>{{cidade.cidade}}</clr-dg-cell> //It Works
   </clr-dg-row>
```

### Actual behavior
Filter and Sort don't work.

Working with **{{cidade.cidade}}**
![Working](https://image.ibb.co/nQDTov/cidade.png)

Not Working with **{{cidade['cod-pais']}}**
![Not working](https://image.ibb.co/efmg8v/pais.png)

* **Clarity version:** 
0.8.11

**Comment by youdz** [comment]
You are not even showing how you set up the `[clrDgField]` input, which is the one thing that matters here. 

Please post a plunker reproducing the issue, so we can investigate.

**Comment by MRMokwa** [comment]
While setting up the plunker, noticed that it's **my mistake, not a bug**. 
Didn't know `[clrDgField]` had to be the same name as the displayed field. 
It works as it should, I'm closing it.
