### ISSUE TITLE
Accordion header should allow consumers to use --font-size custom property

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#6347]
## Describe the bug
cds-accordion-header exposes two custom properties for font: --font-size and --font-weight. IN the component scss these are applied to a non-existent span in the template. 

## How to reproduce
https://stackblitz.com/edit/http-server-vwjxto?file=src/index.css

1.  review the `.portal-header` header in css and see it applied in the demo html. 

## Expected behavior
Consumers should be able to set cds-accordion-header font size and font-weight through the exposed custom properties. 

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
n/a

**Device:**
n/a

## Additional notes

_Add any other notes about the problem here._

**Comment by coryrylan** [comment]
Similar/related issue https://github.com/vmware/clarity/issues/5915
