### ISSUE TITLE
DataGrid.dataChanged() doesn't recalculate height

### ISSUE THREAD

**Issue by cesar-moya** [vmware/clarity#6348]
## Describe the bug
I have a Server-Driven Clarity DataGrid  with items being rendered using *ngFor and paging enabled. 
Whenever the items change I would like to manually trigger a grid height resize on certain cases (I like that it doesn't resize when paging within unchanging items, but if the items changed dramatically - say from showing 100 records on pageSize=100 down to showing 4 records, then the paging footer stays way down).
I tried adding a @ViewChild reference to the datagrid and both resize() and dataChanged() do not adjust the height (resize does adjust the columns though)

## How to reproduce

1. Have a server-driven data grid with paging enabled, set pageSize = 100.
3. Feed it 100 items.
3. Change the items through an observable and return now only 5 items.
4. The paging footer will stay way down as if the grid was still showing 100 items
5. Notice we did not change pages, we simply fed fewer items to the binding
6. I have a button that calls dataGrid.dataChanged() and dataGrid.resize(), the grid height does not change.

## Expected behavior
Upon calling dataGrid.dataChanged() the height should be recalculated.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [x] v3.1.4
- [ ] v4.x
- [ ] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 9.1.11

**Device:**

- Macbook
- MacOS Big Sur v 11.6
- Browser Chrome
- Version [93.0.4577.82]

**Comment by guetin** [comment]
You can put a min-height css in your style.css (or style.scss) to overcome your issue, eg :

_.datagrid {
  min-height: 100px;
}_

**Comment by bbogdanov** [comment]
@cesar-moya Could you please provide a stackblitz example? https://stackblitz.com/@clr-team

**Comment by milesich** [comment]
> You can put a min-height css in your style.css (or style.scss) to overcome your issue, eg :
> 
> _.datagrid { min-height: 100px; }_

That would not work since datagrid height is based on the first page. If the first page has 100 rows and second only 10 it would still has the height as on the first page. It is mentioned here https://github.com/vmware/clarity/discussions/6352#discussioncomment-1370764

**Comment by hippee-lee** [comment]
I'd like to look into this.  As @bbogdanov mentioned please provide a simple isolated reproduction.
