### ISSUE TITLE
@cds/core Tag with Badge not displaying correctly (Angular)

### ISSUE THREAD

**Issue by ConnerEnders** [vmware/clarity#6360]
## Describe the bug

A Tag component containing a Badge component puts the Tag text off-center. The Badge also appears to be shifted out of place.

Screenshot:

![Screen Shot 2021-09-27 at 10 21 47 AM](https://user-images.githubusercontent.com/35942726/134927383-d5ed2833-14fe-41ad-b1e0-d987e3a00c82.png)

## How to reproduce

1. Made a new Angular project with the CLI
2. Added Clarity Core with `ng add @cds/angular`
3. Added this html in the app component:

```html
<cds-tag readonly>This is a test<cds-badge>1</cds-badge></cds-tag>
```

## Expected behavior

Expected the Tag with a Badge to look like it does in the examples.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

v5.5.4

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**

Angular 12.2.0

**Device:**

- OS: MacOS
- Browser: Chrome
- Version: 93

## Additional notes

Had some trouble getting @cds/angular working on Stackblitz, kept getting "Unexpected token 'export'" from the @cds/core package. Sorry for the inconvenience of no Stackblitz example.

**Comment by hippee-lee** [comment]
Hi Connor, sorry about the stackblitz trouble. We are aware of it but don't have a great workaround atm. 
FYI - you can also find stackblitz starters specifically for core here: https://cds.wtf

I made a quick example with just the html posted in the issue report but I don't see the same issue. It it possible there is something else affecting the element in the image? 

https://stackblitz.com/edit/http-server-gtxmbu?file=src/index.html

**Comment by ConnerEnders** [comment]
@hippee-lee Thank you for the stackblitz starters, was able to use it to reproduce the issue here:

https://stackblitz.com/edit/node-5qeujw?file=src/app/app.component.html

It seems to me that the tag + badge behave differently in Angular.
I tried to traverse the DOM and see if any of the CSS was different than a non-Angular tag + badge, but I couldn't find any discrepancies.
I am not sure what else it could be, but it's frustrating lol.

**Comment by ConnerEnders** [comment]
@hippee-lee Thought I should try looking into this again, and I think I see what's going on here.

When a `cds-badge` element is nested in a `cds-tag`, the `cds-badge` _should_ be getting the `slot="tag-badge"` attribute so that it goes in the appropriate slot.

However, it seems that in Angular, that `slot="tag-badge"` attribute is **not** being added to the `tag-badge` element, therefore, the `tag-badge` element lands in the `tag-content` slot, and not the `tag-badge` slot.

**Comment by ConnerEnders** [comment]
One more note: It also appears that this is a problem with nesting a `cds-icon` inside a `cds-tag`. The icon should get the attribute `slot="tag-icon"` but it does not.

I wonder, could there be more uses of slots across cds/core that might be broken in Angular?
