### ISSUE TITLE
core(radio): Radio Group label is wrapping in vertical layout

### ISSUE THREAD

**Issue by ashleyryan** [vmware/clarity#6361]
## Describe the bug

In a vertical form group, the label for a radio group is 192px instead of stretching and is causing long label text to wrap.

Also, putting a `vertical-inline` RadioGroup inside of a `vertical` FormGroup seems to be making the radio inputs stack instead of display inline

## How to reproduce

https://codesandbox.io/s/headless-moon-4801o?file=/src/App.tsx

## Expected behavior

The RadioGroup label stretches like the input label.

Vertical inline radio group should render as vertical inline inside of a FormGroup

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

## Additional notes

Jeremy on slack said: "Looks like a bug in the private-host not having align:stretch."

Looking into the CSS in devtools, the following CSS applies to the input label, but not the radio group label:

```
:host([layout*="vertical"]) cds-internal-control-label {
  --label-width: 100%;
}
```

Setting `--label-width: 100%` on the RadioGroup is a workaround for the label issue in the interim.

**Comment by mathisscott** [comment]
Thanks for the reproduction, @ashleyryan! It helped me track down the cause of the issue.

That max width [is getting set here](https://github.com/vmware/clarity/blob/0b5b5605e99359a73bc84c3503a7611b235b3764/packages/core/src/forms/control-label/control-label.element.scss#L17).

It doesn't seem like it would be a big change to set it to 100% in vertical layout. But I'm not sure what else that might break. Do you have any insight, @coryrylan ?

For now, I say stick with the workaround. Once we understand the implications of making this change, we will get it sorted.

Thanks again.

**Comment by coryrylan** [comment]
Looked into this and got a fix. The control groups were missing a similar line that standard controls have when in vertical layouts https://github.com/vmware/clarity/blob/0b5b5605e99359a73bc84c3503a7611b235b3764/packages/core/src/forms/control/control.element.scss#L28-L30
