### ISSUE TITLE
Icons are not loading in clr and cds Angular project

### ISSUE THREAD

**Issue by ben-str-evoila** [vmware/clarity#6363]
## Describe the bug

If installed the Clarity project works fine. Only the icons do not work.
The issue is that a coworker and I tried including icons, but they always turn into three dots that seem to be loading.
For some reason one or two work, f.e. info-circle.

## How to reproduce

Install clr project:
1. ng new test
2. cd test/
3. ng add @clr/angular

When the project is setup the icons won't load.
If the setup is done manually it also will not load.

## Expected behavior

if a icon f.e. <clr-icon shape="cog"></clr-icon> or
<cds-icon shape="cog"></cds-icon>
is used the cog icon should be displayed.

## Versions

**Clarity project:**

- [ x] Clarity Core
- [ x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ x] v5.x

**Framework:**

- [ x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: MacBook Pro and Lenovo
- OS: Windows 10 and macOS Big Sur version 11.5.2
- Browser Chrome

## Additional notes

-

**Comment by mathisscott** [comment]
Are you loading the cog icon into the registry [as demonstrated here](https://clarity.design/foundation/icons/#import)?

**Comment by ben-str-evoila** [comment]
Do I have to import every icon one by one? Can't I just import them all at once?

**Comment by mathisscott** [comment]
We don't recommend importing all the icons. The reason there is that it's likely a product doesn't use all of the icons. So the product's code base will be bloated with icons the product doesn't need.

If you absolutely must load many, many icons at once, [we have icon sets like in the old library](https://github.com/vmware/clarity/tree/next/packages/core/src/icon/collections). But we discourage teams from using them. 

It's a bad practice and we recommend loading the icons you need as they are needed instead.
