### ISSUE TITLE
Datagrid has wrong type for clrDgSelected not supporting undefined

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#6364]
## Describe the bug

The clrDgSelected property in the datagrid does not support the undefined type, though it supports it (in order to hide the checkboxes).

## How to reproduce

`myDataGrid.selected = undefined
`

Above gives compile error that selected does not support undefined.

See source code. T[] should be changed to T[] | undefined

```
  @Input('clrDgSelected')
  set selected(value: T[]) {
    if (value) {
      this.selection.selectionType = SelectionType.Multi;
    } else {
      this.selection.selectionType = SelectionType.None;
    }
    this.selection.updateCurrent(value, false);
  }

```  

## Expected behavior

Should be able to compile with strict mode

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v12.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 12

**Comment by bbogdanov** [comment]
@rbirkgit Curious why would you use `undefined` instead of empty array `[]`?

**Comment by rbirkgit** [comment]
This to turn off the checkboxes. The code does check for undefined, but the type does not allow it. So we have to add @tsignore statements in our code.

**Comment by bbogdanov** [comment]
@rbirkgit https://angular.clarity.design/news/12.0.6
