### ISSUE TITLE
Table Component throws error on bundling

### ISSUE THREAD

**Issue by blabbath** [vmware/clarity#6370]
When using the Table Component in a Vue 3 project and running npm run build the following error occurs:

> Error: CSS minification error: Parse error on line 1: 
> ...ar(--cds-global-space-5, calc((8 / var(--cds-global-base, 20)) * 1rem)) / 2
> ------------------------------------------------------------------------^
> Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN". File: css/chunk-vendors.ff777c58.css

When I delete the styling for the compact table from @cds/core/table/table.css 
```
table[cds-table~=compact] {
  --cell-padding: calc(var(--cds-global-space-5, calc((8 / var(--cds-global-base, 20)) * 1rem)) / 2) calc(var(--cds-global-space-6, calc((12 / var(--cds-global-base, 20)) * 1rem)) / 2);
}
```
and import the table.css the build process runs as expected.

## Versions

**Clarity project:**

- [ x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ x] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ x] Vue
- [ ] Other:

**Framework version:**
vue3

**Device:**

- Type: [e.g. Notebook]
- OS: [e.g. Windows 10]
- Browser [e.g. chrome]

**Comment by mathisscott** [comment]
@blabbath 
We've seen some inquiries along these lines a little while back. It seems like `cssnano` and `postcss-calc` both have issues with `calc()` in CSS...

https://github.com/cssnano/cssnano/issues/988

https://github.com/postcss/postcss-calc/issues/91

The workaround is to configure `cssnano` to ignore `calc()` declarations...

```
  "cssnano": {
    "preset": [
      "default",
      {
        "calc": false
      }
    ]
  }
```

**Comment by mathisscott** [comment]
I'm not sure there's much we can do to fix this on our end... @hippee-lee , what are your thoughts on that?

**Comment by hippee-lee** [comment]
You are correct. The workaround to disable calc for postcss-calc is the most reliable way to deal with it. I've seen it crop up in multiple frameworks now. There are several issues open on the postcss-calc repo. [Here](https://github.com/postcss/postcss-calc/issues/77) is another from March 2019.

My recommendation, @blabbath is to disable postcss-calc for the build.

@mathisscott, One our end, we could revisit the usage of nested calc's (I believe thats what causes the error). However the last time I looked into it I didn't see an easy way to do the things we need to do in the style code without them.

**Comment by blabbath** [comment]
Thank you for your fast replies!
Where exactly would I change the cssnano configuration? I am using the vue-cli with a vue.config.js file.

**Comment by hippee-lee** [comment]
It's hard to say for sure but we build the website with vuepress. There is a config.js file where we can configure things at build time. If I had this issue that is where I would start by adding:

```json
module.exports = {
    postcss: {
            plugins: {
                'cssnano': {
                    preset: [
                        "default",
                        {
                            "calc": false
                        }
                    ]
                }
            }
    }
}
```

In the one of the other issues I linked to, there is a [comment](https://github.com/postcss/postcss-calc/issues/77#issuecomment-491354918) about adding the override to the package.json file, so that might be an option also.

**Comment by mathisscott** [comment]
[Here is that config file iirc](https://github.com/vmware/clarity/blob/next/apps/website/.vuepress/config.js)
