### ISSUE TITLE
Detail Pane datagrid inside stepper is missing the close button

### ISSUE THREAD

**Issue by vundev** [vmware/clarity#6380]
Try to put a grid inside stepper. The result is that when you inspect the details for each grid row the close(x) button is not visible, it is there but its dimensions are reported as 0. If you drag the mouse to the top right corner you can see that the area is active and you can still do a close tap if you managed to hit the invisible icon.

The issue is reproducible only on a local angular build. I copied the local project into https://stackblitz.com/edit/clarity-light-theme-v5-za5b5w and the Close button starts to appear.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [x] v3.x
- [] v4.x
- [ ] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
 Angular 11

**Device:**

- Type: [MacBook pro]
- OS: [Catalina]
- Browser [chrome]
- Version [87.0.4280.88 (Official Build) (x86_64)]

**Comment by vundev** [comment]
![Screenshot 2021-10-06 at 12 07 51](https://user-images.githubusercontent.com/219103/136173953-96957787-27a5-468b-899c-73ed940725a4.png)
Here is a screenshot from the local setup

**Comment by bbogdanov** [comment]
Hi @vundev,

Could you please take a look at the example you provided? Some errors are raised by the compiler and it is not possible to load the project.

**Comment by hippee-lee** [comment]
I took the code provided and ported it to a working [stackblitz](https://stackblitz.com/edit/gh-issue-6380?) but was unable to recreate the reported issue. I am closing this for now. If there is something that I missed when porting the code please fork the stackblitz with code that reproduces the issue as reported
![Screen Shot 2021-10-28 at 4 13 17 PM](https://user-images.githubusercontent.com/433692/139348807-e3d07c9a-7a91-46a7-99d6-3b9cbfc3826a.png)
.
