### ISSUE TITLE
Vertical-nav trigger icon visibility in collapsed state

### ISSUE THREAD

**Issue by bbogdanov** [vmware/clarity#6383]
## Describe the bug

In collapsed state nav-group trigger icon goes out border and looks like its missing.

![image](https://user-images.githubusercontent.com/15037947/136395439-65c8af8e-c160-4735-abdd-9ab379cd7c37.png)

## How to reproduce

- Go to https://angular.clarity.design/documentation/vertical-nav/nav-groups/normal/pidgey#code-examples 

- Select `Vertical Nav Groups` option

- Collapse the navigation

## Expected behavior

![image](https://user-images.githubusercontent.com/15037947/136395765-5f63ac83-adab-4c59-8dd0-e53b31845d68.png)

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Comment by bdryanovski** [comment]
From what I see that there is already a fix so I'm closing this ...
