### ISSUE TITLE
Adding launchpad icon

### ISSUE THREAD

**Issue by tenguyen34** [vmware/clarity#6386]
_Please review our [Contribution guide](https://github.com/vmware/clarity/blob/master/CONTRIBUTING.md) for more details about how to contribute effectively._

## Summary

Request to add a new icon to Clarity

## Use case

Use for icons on various VMware apps

## Examples

Launchpad icon is currently included in [https://vmc.vmware.com/home](https://vmc.vmware.com/home) but is not included in the Clarity library

SVGs for new launchpad icon: [launchpad-icon.zip](https://github.com/vmware/clarity/files/7312768/launchpad-icon.zip)

**Comment by mathisscott** [comment]
@lil-kim 
This seems generic enough to me for the icons library. What are your thoughts?

**Comment by lil-kim** [comment]
@mathisscott Yep, agreed. This icon wasn't created by Visual design team, so I'd like to check the line weight, etc for accuracy before publishing it. I'll attach an updated .svg.

**Comment by lil-kim** [comment]
I adjusted the line weight for consistency and added a solid version. It's ready to publish:
[lauchpad_icon_updated.zip](https://github.com/vmware/clarity/files/7444384/lauchpad_icon_updated.zip)
