### ISSUE TITLE
CdsButton loadingState is not working

### ISSUE THREAD

**Issue by wghglory** [vmware/clarity#6389]
## Describe the bug

loading, error, success of CdsButton loadingState behaves just like default.

## How to reproduce

https://codesandbox.io/s/clarity-react-frze6?file=/src/App.tsx

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.5.7

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue

**Comment by bdryanovski** [comment]
@wghglory Thanks for reporting this I gonna but I gonna close it as duplicate in favor of #6390
