### ISSUE TITLE
will we upgrade to angular v4 once it's released?

### ISSUE THREAD

**Issue by royling** [vmware/clarity#639]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```
This is actually a question about the roadmap.
Now the project is based on angular v2.x, but this is [a bug about lazy loading modules](https://github.com/angular/angular/pull/14201) in that version, and it might not be planned to fix according to angular team (they already fixed the bug in v4 which introduces breaking changes and may cause difficulties on porting the solution back to v2.x).
Though I understand this is actually a problem in angular v2.x itself, it should be fixed, this may block our use of this clarity-angular project then, if it's not upgrading to v4.x.

### Expected behavior

upgrade to the angular v4.x

### Actual behavior

depending on angular v2.x, lazy loading modules get instantiated on each route.

### Environment details

* **Angular version:** 2.4.10

* **Clarity version:** latest

* **OS and version:** macOS

* **Browser:** all

**Comment by malkoto1** [comment]
Аре бе пичове, цял живот ли ще ви чакам?

**Comment by mattmutt** [comment]
Roy - using Clarity in Angular 4 works for us. There are just some warnings over the new template syntax changes to `<ng-template>`, which you can silence if you really need to. You'll have to remember to manually import the animation module and maybe some other minor chores.

**Comment by jaffoneh** [comment]
@royling we’re currently evaluating the move to Angular 4 and the Clarity/Angular2 compatibility we would want to offer. Given that the Angular team is moving directly to Angular 4 without much support/backward compatibility for Angular 2 in the future, we want to make sure we give enough time for our Angular 2 users to make the move. Our plan is to make that evaluation this/next week and then make a public plan of our move.

As @mattmutt mentioned, we do know of a few products within VMware pre-production that use Angular 4 + Clarity with no problems (except for a few warnings in the developer console) so you might be able to make the move and continue to use Clarity today.

We should have an official update on this with a plan next week.

In the meantime, we would love to hear your feedback.

**Comment by royling** [comment]
@jaffoneh thanks for the clarification of the plan.
and @mattmutt thanks for the info as well, will try to upgrade my project to ng v4.

**Comment by bertofer** [comment]
In our case, we could not migrate to Angular 4+ Clarity directly because we use the Clarity Tree, and it uses animations that are in a different package in Angular 4 but inside @angular/core in Angular 2.
