### ISSUE TITLE
Typescript will complain when passing style object into CdsButton and other core components

### ISSUE THREAD

**Issue by wghglory** [vmware/clarity#6390]
## Describe the bug

According to https://clarity.design/core-components/input/code/, CdsInput allows passing max-width style, but typescript complains when passing style object into Clarity React components.

I also see this issue for other components, not only for Input.

## How to reproduce

https://codesandbox.io/s/clarity-react-frze6?file=/src/App.tsx

## Expected behavior

Style object with supported fields should be valid.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

**Comment by coryrylan** [comment]
The `loadingState` issue seems to be a potential regression in one of our upstream dependencies and I'm looking into this now.

The `style` property issue is specific to a mismatch with the typings in React. This is a known issue with using [CSS Custom properties](https://chaseadams.io/posts/typescript-var-cssproperties/) but I am unsure why a regular CSS property is failing here. A workaround is to cast the correct type when assigning.

https://stackblitz.com/edit/http-server-fjbwky?file=src%2FApp.tsx
```tsx
<CdsInput layout="vertical" style={{maxWidth: '300px'} as CSSStyleDeclaration & CSSProperties}>
  <label>vertical custom width</label>
  <input placeholder="name" />
</CdsInput>
```

**Comment by wghglory** [comment]
@coryrylan thanks for the update. I will use the workaround for now. But eventually this CSSStyleDeclaration cast would not be needed after a fix, right?
