### ISSUE TITLE
clr-combobox [disabled] binding does not change state of the combobox

### ISSUE THREAD

**Issue by daukstsoskars** [vmware/clarity#6410]
## Describe the bug

setting [disabled] binding to true in HTML or through property in TS file does not disable the combobox

## How to reproduce

https://stackblitz.com/edit/clarity-dark-theme-v5-nqd74y?file=src%2Fapp%2Fapp.component.html

1.  Go to the provided link
2.  Observe setting [disabled] to true in HTML does not disabled combobox
3. Observe sett [disabled] through a property in TS file does not disable the combobox

## Expected behavior

clr-combobox should be disabled when [disable] binding is set to true from HTML or TS file

## Versions

**Clarity project:**

- [X] Clarity Angular/UI

**Clarity version:**

- [X] v5.x

**Framework:**

- [ ] Angular

**Framework version:**
_ie: Angular 11.2.9

**Device:**

- Type: [MacBook Pro]
- OS: [Big Sur]
- Browser [chrome, firefox]

**Comment by Jinnie** [comment]
Combobox is using the Angular Forms API to handle disabled and other states across both template driven and reactive forms.
So you need to import the angular FormsModule in your project
import { FormsModule } from '@angular/forms';
and add it to the imports  section of your app module.
