### ISSUE TITLE
Angular combobox takes string but treat all values as true

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#6432]
## Describe the bug

The combobox clrMulti property takes a string, but treats any value (except empty string) as true. 

```
@Input('clrMulti')
set multiSelect(value: boolean | string) {
  if (value) {
    this.optionSelectionService.selectionModel = new MultiSelectComboboxModel<T>();
  } else {
    this.optionSelectionService.selectionModel = new SingleSelectComboboxModel<T>();
  }
```

## How to reproduce

We had a typo in our code:
`[clrMulti]="'false'"`

I expected the strictTemplate setting to catch it, but the source of combobox as seen above takes a string input but doesn't check the content of the string, just if a string has value.

## Expected behavior

Either not supporting string or parse the string to actual tue/false.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [x] v12.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 12

**Comment by bdryanovski** [comment]
The reason for having `string` as a type is that the strict Angular (`fullTemplateTypeCheck` & `strictTemplates`) check requires every field that is `boolean` to have an additional type of `string`.

The reason is that internally Angular and DOM don't have an idea of what is a `boolean` everything is a string. Angular works with strings that look like boolean and try to handle this - sort of. The solution you had is right. And you could also notice that non-empty strings will be `true`. 

Here maybe will be a good place to have additional code to check strings (like `'true'` & `'false'`) and convert them to `boolean`.

I don't think that this is a bug - but we are open to accepting PR with changes to handle the above case.

**Comment by rbirkgit** [comment]
To me this is a clear bug and caused issues in our code. Either it should only accept an empty string as type or you have to convert string to proper vavlue. That how it is done in other components.

**Comment by rbirkgit** [comment]
It's seems inconsistent throughout the Clarity code base with many bugs. Some places do it this way:

```
  set clrInline(value: boolean | string) {
    if (typeof value === 'string') {
      this.inline = value === 'false' ? false : true;
    } else {
      this.inline = !!value;
    }
  }
```

Other places like this:
```
  @Input('disabled')
  set disabled(value: boolean | string) {
    if (this.dateFormControlService) {
      this.dateFormControlService.setDisabled(isBooleanAttributeSet(value));
    }
  }
```

Except this function is also buggy, not supporting strings properly (If I read the code correctly):

```
export function isBooleanAttributeSet(value: string | boolean): boolean {
  // for null just return false no need to check anything
  if (value === null) {
    return false;
  }
  if (typeof value === 'string') {
    // Empty string is valid, 'true' as string is also valid
    return value.length >= 0;
  }
  // Boolean value will be read as it is, everything else is false
  return typeof value === 'boolean' ? value : false;
}

```

**Comment by bdryanovski** [comment]
The method above that you mention `isBooleanAttributeSet` (I guess the name is a bit misleading - I'm guilty on that part) is designed to mimic the same way as the Browser will handle attributes for example this case:

```html
<input disabled=disabled />
<input disabled="false" />
<input disabled="random-word" />
<input disabled />
```
All of them have the same effect - there are `disabled`. 

The snippet of the code above if I'm correct is from the `clrSpinner` or `clrProgressBar` and they are designed so you could just mention the attributes and get the effect they provide. 

The same applies to `clrMulti`. 

Still don't find this as bug - just we don't guard for every possible data to be converted to "`boolean`". Cause if we want to cover all values that could be cast to value it will require a lot of more complex code. For example values as `1`, `0`, `'yes'`, `'no'`, `'true'`, `'false'`, `'on'`, `'off'`, etc.

The use of the `string` type can't be avoided when template `strict` is enabled - so you could not have any safety net for this type of typos. Even checking for string versions of `true` and `false` there could also be typoes there like `ture` or something else - and still, you will get the wrong result. 

We will be happy to accept external contributions to resolve this issue for this case or any other that could be found.

**Comment by rbirkgit** [comment]
That why I suggested to update the type to `boolean | ''`  Would that not work?

**Comment by Jinnie** [comment]
As long as our docs state that
> The multi selection mode is triggered with a clrMulti="true" 

I agree that this should be considered a bug.
