### ISSUE TITLE
[clrDgField] with dynamic field name

### ISSUE THREAD

**Issue by siteslave** [vmware/clarity#644]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

Can I set dynamic field name to [clrDgField]

```
<clr-dg-column  [clrDgField]="'column'" *ngFor="let column of columns">{{ column }}</clr-dg-column>
```

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
`[clrDgField]` is a standard Angular input. You can use dynamic values in it, as you do everywhere else: `[clrDgField]="myDynamicColumn.property"`.

**Comment by siteslave** [comment]
Now it work with v0.8.12 👍 

Thanks. :)
