### ISSUE TITLE
ng add @clr/angular not working

### ISSUE THREAD

**Issue by bhamidic** [vmware/clarity#6458]
## Describe the bug

I am not able to add @clr/angular to my project.

## How to reproduce
 
Node Version: v16.13.0
npm version: 8.1.3

Package                                         Version
---------------------------------------------------------
@angular-devkit/architect           0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/core                  13.0.1
@angular-devkit/schematics       13.0.1
@angular/cli                                13.0.1
@schematics/angular                  13.0.1
rxjs                                               7.4.0
typescript                                    4.4.4

1.  npm new my-app
2.  cd my- app
3.  ng add @clr/angular
4.  See error:
i Using package manager: npm
‼ Unable to find compatible package.  Using 'latest' tag.
‼ Package has unmet peer dependencies. Adding the package may not succeed.

The package @clr/angular@12.0.7 will be installed and executed.
Would you like to proceed? (Y/n)
4. press y
5. Final Error
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: e-clinical-genie@0.0.0
npm ERR! Found: @angular/common@13.0.0
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from @clr/angular@12.0.7
npm ERR! node_modules/@clr/angular
npm ERR!   @clr/angular@"12.0.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\chbha\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\chbha\AppData\Local\npm-cache\_logs\2021-11-09T11_41_00_321Z-debug.log
× Package install failed, see above.
## Expected behavior
Successfully add clr to project

**Comment by mathisscott** [comment]
Currently, we do not support Clarity Angular in Angular v13. It was released just last week. 

We have been actively working on angular v13 support for a couple of weeks already and plan to update v13 support as soon as that effort is complete.
