### ISSUE TITLE
Bug angular 13

### ISSUE THREAD

**Issue by wagnerdavanco** [vmware/clarity#6459]
## Describe the bug

when trying to add the angular clarity package i run into the following error when doing npm start

## How to reproduce

https://stackblitz.com/edit/angular-4swtwd

1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

## Expected behavior

when trying to add the angular clarity package i run into the following error when doing npm start

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ X] Clarity Angular/UI

**Clarity version:**

- 12.0.7

**Framework:**

- [X ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 13

**Device:**

- Type: [Windows]
- Browser [Google Chrome]

## Additional notes

Error: node_modules/@cds/core/internal/base/button.base.d.ts:8:5 - error TS2416: Property 'ariaDisabled' in type 'CdsBaseButton' is not assignable to the same property in base type 'LitElement'.
  Type 'string | null' is not assignable to type 'string'.
    Type 'null' is not assignable to type 'string'.

8     ariaDisabled: 'true' | 'false' | null;
      ~~~~~~~~~~~~

**Comment by mathisscott** [comment]
We are still working on angular 13 support. I recommend staying on angular 12 until we've had a chance to work through those issues.
