### ISSUE TITLE
Datagrid details view does not expand first column

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#6460]
## Describe the bug

When opening the details / master view of a row in the datagrid, the first column is not expanded to take available space. It remains same width originally. 

## How to reproduce

Go to https://angular.clarity.design/documentation/datagrid/detail-pane  
There narrow the width of the first column and open details view. 

![image](https://user-images.githubusercontent.com/6342391/140994796-78d9ce26-23ff-46ab-bc04-4f484dc2fa5a.png)

## Expected behavior

The column expands to take available space.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v12.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Browser [chrome]

## Additional notes

Our name column have long names and use "..." when not fit. It looks bad with our name column in details view where the names only show up having text in half the space.

![image](https://user-images.githubusercontent.com/6342391/140995062-37b4a1e9-be79-463f-846b-79ef71a2e4b2.png)

**Comment by gnomeontherun** [comment]
In the website demo, the content is only as wide as the text. If you add more text, it does fill the space. Does the first column have an explicit width assigned to it in your application, or was it resized before using the detail pane?
