### ISSUE TITLE
Controlling `*clrIfOpen` state of dropdowns programmatically doesn't work as expected

### ISSUE THREAD

**Issue by dorthrithil** [vmware/clarity#6462]
## Describe the bug

Using the desugarized syntax one should be able to control the dropdown open state via a boolean variable:

```html
<clr-dropdown>

    <!-- Trigger element -->

    <ng-template [(clrIfOpen)]="open">
      <clr-dropdown-menu>
        <div clrDropdownItem>Link 1</div>
        <div clrDropdownItem>Link 2</div>
      </clr-dropdown-menu>
    </ng-template>

</clr-dropdown>
```

However, changing the boolean in the code doesn't work. Only after the state gets changed the first time via `clrDropdownTrigger` the boolean is changeable as expected. It's a really weird bug, but I was able to reproduce it in a stackblitz.

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-atrn7g?file=src/app/app.component.html
2.  Click on the "open" button.
3.  See that nothing happens and the `open` variable stays false.
4.  Trigger the Dropdown by clicking into the input (the `clrDropdownTrigger` element)
5. See that the dropdown opens and the variable becomes true.
6. Click outside to close the dropdown. The variable becomes false.
7. Now click the button again. 
8. See that it now works!

By checking the logs from the `openDropdown` function you can see that the variable actually is true for a short time. But there seems to be some change detection hook that resets it back to false?

## Expected behavior

Glitch free dropdown open state control via `clrIfOpen`.

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.5.0 in the Stackblitz, but it's the same for 5.6.0

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Device:**

- Browser: Chrome

**Comment by steve-haar** [comment]
This is because the click event of the button bubbles up to the document click handler and it's seen as an outside click that causes the dropdown to immediately close. We are looking into this now, but a possible workaround might be to call `event.stopPropagation()` in the click handler: https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-m9ebow
