### ISSUE TITLE
Using sass 1.33+ gives pages of deprecated warnings

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#6468]
## Describe the bug

sass 1.33.0 changed their syntax with regards to divisions. With this you get pages of deprecated warnings when building Clarity Angular projects. With Angular 12 @angular-devkit/build-angular is now hard coded to use 1.36.0 and ng-packagr is using ^1.32.8 which result that our projects will be using 1.33+

## How to reproduce

Create an Ang12 project and build a Clarity project. You will see all the warnings, e.g.:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($clr-baseline-denominator, $browser-default-size)
More info and automated migrator: https://sass-lang.com/d/slash-div
   ╷
18 │ $clr-basefont-size: ($clr-baseline-denominator/$browser-default-size) * 100% !default;

```
## Expected behavior

Update scss files syntax to new standard.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v12.x

**Comment by rbirkgit** [comment]
This bug was previously opened as #6331 but accidentally closed. I cannot re-opened it, so have to create a new one. Hopefully this can get fixed as the pages of warnings is very distracting every time you build. Making it hard to find actual errors.

**Comment by bdryanovski** [comment]
@rbirkgit you are right I could confirm that this is still a valid bug. 

It's even known issue for Angular v13 release candidate #6455
