### ISSUE TITLE
Combobox: unintuitive behaviour on re-selection

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#6469]
## How to reproduce
See screencast for the steps to reproduce the behavior:
https://user-images.githubusercontent.com/311619/141486153-2c73a13e-02a7-44a9-9493-cd4f854f75ed.mp4

## Describe the bug
Imagine the following quite common scenario:
1. User types in/selects a value from the suggestion-list of the autocomplete-combobox.
2. This value is valid and eg. saved until a change of the value is required.
3. User now clicks on the caret-down to open the suggestion-list, as he/she wants to select another value.

In the [screencast example](https://user-images.githubusercontent.com/311619/141486153-2c73a13e-02a7-44a9-9493-cd4f854f75ed.mp4) the user had previously selected "Alaska" and wants to change it to "Arizona", which is not easy possible.

## Current behaviour
- when the user clicks on the caret-down to open the suggestion-list, as he/she wants to select another value, the suggestion-list only offers the current value.

- Some of our users where confused if there aren't no other valid options to select from, and
- other understood that they need to delete the current value and search for a new one but felt that this behavior is cumbersome and unintuitive. 

## Expected behavior
Therefore the behaviour should change as soon as a value has been selected = the combobox field is populated:
- then a click to open the suggestion-list should show all options, making the selection of another valid option via mouse easy.
- when the text of the input field is altered, the suggestion list reflects the search behaviour and adapts the search results in the suggestion-list as currently implemented.
- additionally a "x" at the end of the input field could help to easily clear the contents of the combobox. See common behaviour on search fields: 
     <img width="290" alt="2021-11-12_16h00_51" src="https://user-images.githubusercontent.com/311619/141487814-c261d15e-faeb-4584-8397-6181fff74c67.png">
see also #5641

## Versions

**Clarity project:**
- [x] Clarity Angular/UI

**Clarity version:**
- [x] v4.x
- [x] v5.x

**Framework:**
- [x] Angular

**Device:**
- Type: any, tested with Notebook
- OS: any, tested with Windows
- Browser: likely any, tested with Chrome

**Comment by mattmutt** [comment]
Our implementation had the same user feedback. We weren't satisfied with waiting until switching over to Clarity Core without guarantees.

So easier just to extend the Combobox with the behavior to mark its `input` tag with a "search" type. Now if that doesn't solve accessibility needs, then the blame shifts to old W3C standards. The "X" icon simply is from a bygone era when nobody cared about non-mouse users.

Example snippet directive where the combobox is decorated with the "X" icon to clear and also automatically open up the list when focus is received. There are two parameters defined, for simplicity sake I made them on by default.

```
import { AfterViewInit, Directive, Host, HostListener, Input } from '@angular/core';
import { ClrCombobox, ClrPopoverToggleService } from '@clr/angular';

@Directive({
    selector: 'clr-combobox',
})
export class CustomComboboxDirective<T> implements AfterViewInit {
    @Input('customFocusExpandable') public expandOnFocus: boolean = true; // UX requirement: show dropdown list when input receives focus
    @Input('customInputClearable') public inputClearable: boolean = true; // UX requirement: show clear button

    constructor(@Host() private cmp: ClrCombobox<T>, @Host() private clrToggleService: ClrPopoverToggleService) {}

    public ngAfterViewInit() {
        if (this.inputClearable) {
            const inputEl = this.cmp.textbox.nativeElement as HTMLInputElement;
            inputEl.type = 'search';
        }
    }

    @HostListener('click', ['$event'])
    public onFocus(evt: FocusEvent) {
        const isMouseFocusedEvent = evt.target === this.cmp.textbox.nativeElement;

        if ((evt.target as HTMLElement).parentElement === this.cmp.trigger.nativeElement) {
            return;
        }

        if (isMouseFocusedEvent && this.expandOnFocus && !this.cmp.openState && this.cmp.focused) {
            this.clrToggleService.toggleWithEvent(evt);
        }
    }
}

```


https://user-images.githubusercontent.com/8688570/141603492-a83c4b0d-7781-4597-bd83-35d2644061e4.mov

**Comment by bbogdanov** [comment]
Hi @d-m-s,

The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our GitHub Discussions.
