### ISSUE TITLE
Feature Request: Date Picker with calendar weeks (optionally shown in first column)

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#6470]
### Discussed in https://github.com/vmware/clarity/discussions/6369

<div type='discussions-op-text'>

<sup>Originally posted by **d-m-s** September 30, 2021</sup>
see Feature Request: https://github.com/vmware/clarity/issues/5273 Date Picker with calendar weeks (optionally shown in first column) 

Unfortunately I haven't found any public available feature request list, ... **is this still somehow in focus for development?**

We would require this feature for one of our applications and are looking for the best way to provide it!

 - I guess implementation in the angular components, would not be recommended 
 as they're pretty much feature-freezed, am I right?
 - Is the Datepicker available as CORE component any time soon? 
 Could we somehow contribute? 

Please point us in the most efficient direction on how we could realize the feature.

Thanks!

</div>

**Comment by bbogdanov** [comment]
Let's keep the communication in the discussion topic.
