### ISSUE TITLE
Feature Request: Icon with count-badges

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#6471]
### Discussed in https://github.com/vmware/clarity/discussions/5968

<div type='discussions-op-text'>

<sup>Originally posted by **d-m-s** May 20, 2021</sup>
# Idea
It would be great if icons itself support count-badges!

So something like the following usecase: "showing amount of notifications in a menu-bar" can be done easily.
<img width="133" alt="2021-05-20_11h21_49" src="https://user-images.githubusercontent.com/311619/118955738-44121700-b95f-11eb-8e0a-58d4fdde72fd.png">

# Current Situation
Currently Clarity poses the possibility to show badges to some of the icons.
<img width="614" alt="2021-05-20_11h24_41" src="https://user-images.githubusercontent.com/311619/118955314-df56bc80-b95e-11eb-9a32-c3bfee05393f.png">

# Description
For lots of usecases a counter should be additionally displayed. Think of amount of Emails, Notifications, Logmessages, Files, etc. 
At the time being this must be manually styled to fiddle a regular badge with count (see below) to the upper right of an icon.
<img width="556" alt="2021-05-20_11h28_44" src="https://user-images.githubusercontent.com/311619/118955343-e41b7080-b95e-11eb-9401-79b398a1b316.png">

A clean way that either all or choosen likely ones support count-badges would be a quick win!
<img width="123" alt="2021-05-20_11h39_37" src="https://user-images.githubusercontent.com/311619/118957673-00b8a800-b961-11eb-9aa4-df970d43e7c8.png">

</div>

**Comment by bbogdanov** [comment]
@colinreedmiller
