### ISSUE TITLE
Datagrid column width not set correctly inside hidden tab content

### ISSUE THREAD

**Issue by estrode** [vmware/clarity#648]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Two datagrids displaying the same data set inside different tabs should have the same column widths and appearance. 

### Actual behavior
The datagrid displayed on the first active tab has column widths that are properly sized for the content. But the datagrid in the second tab does not have the same column widths and does not appear the same as the first.

### Reproduction of behavior
https://plnkr.co/edit/rawWLfu1n7ejxPTgrUhq?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version: 0.8.12** 

* **Browser:** all

**Comment by Shijir** [comment]
@estrode Thanks for bringing this issue to our attention. We know what is causing this issue, but we will need to further investigate various ways to solve this problem and go with the most appropriate one.

In the meantime, I am showing you a way to circumvent this issue in the following Plunkr: 
https://plnkr.co/edit/oevUos8tbK40srgj8IEy?p=preview

**Comment by youdz** [comment]
Fixed in 0.10.0-rc.1 as part of the tabs refactor.
