### ISSUE TITLE
Placeholder in clr-combobox is truncated

### ISSUE THREAD

**Issue by AleksandrovaP** [vmware/clarity#6480]
## Describe the bug

The placeholder in clr-combobox gets trucated when the string is longer. This is a problem also from a11y perspective.

## How to reproduce

https://stackblitz.com/edit/clarity-light-theme-v5-5xe9qp

## Expected behavior

The whole placeholder should be visible.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [X] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11

**Device:**

- Type: MacBook Pro
- OS: MacOS Big Sur
- Browser Chrome
- Version 95

**Comment by bdryanovski** [comment]
I could confirm this it seems that the `input` require to have `width: 100%` to be able to fill the how container. But even with that, a very long text won't be visible.

<img width="483" alt="Screenshot 2021-11-24 at 13 44 12" src="https://user-images.githubusercontent.com/204564/143232456-b2eadca8-b27b-492e-8720-edd01915180c.png">

Not saying that this is not a bug that we need to fix, but will advise, not to go to the extreme with long placeholder text and use the `clr-control-helper` to give additional information about the field. 

I suspect that there is a reason to not go with `full-width` here. Maybe when trying to use the auto-complete could get some strange UI?

@Jinnie

**Comment by Jinnie** [comment]
The main problem here is that the input field has to fit together with the multiselection fix. It is intentionally done with limited max-height, so it can be wrapped to a new line at some moment.
I believe we may find a solution where it properly fills the rest of the line and is only wrapped after certain min-width, but any solution in this direction should be tested in both single selection and multi-selection (with many lines of selected items).
