### ISSUE TITLE
StackBlitz examples for Clarity V5 pointing to wrong angular version

### ISSUE THREAD

**Issue by juanmendes** [vmware/clarity#6481]
## Describe the bug

The [Clarity Angular and Angular Compatibility page](https://clarity.design/get-started/support/#clarity-angular-and-angular-compatibility) says that Clarity angular v5 should use angular v11 but the stackblitz templates for [Clarity Light Theme V5](https://stackblitz.com/edit/clarity-light-theme-v5?file=package.json) and [Clarity Dark Theme V5](https://stackblitz.com/edit/clarity-dark-theme-v5?file=package.json) are pointing to angular 12.

## How to reproduce

Go to https://stackblitz.com/edit/clarity-dark-theme-v5?file=package.json or https://stackblitz.com/edit/clarity-dark-theme-v5?file=package.json and notice the mismatched versions

## Expected behavior

Angular version for Clarity v5 should be 11

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11/12_

**Comment by Jinnie** [comment]
Fixed, thanks!
