### ISSUE TITLE
Installing clarity using Angular CLI doesnt install normalize css dependency

### ISSUE THREAD

**Issue by iamebuka** [vmware/clarity#6482]
## Describe the bug

When adding clarity to an Angular project using `ng add @cds/angular`, it includes node_module path to `normalize.css`  in `angular.json` file but doesn't install the normalize CSS dependency or includes it in the dependency list of package.json. 

## How to reproduce

1.  Open a new or existing Angular project.
2.  Add clarity using `ng add @cds/angular`
3.  Serve your Angular application.
4.  You should get the error message in the screenshot attached below.

![clarity-error](https://user-images.githubusercontent.com/11005120/142761539-d2548efa-5a5a-458a-89c6-cbc4c24ab770.PNG)
## Expected behavior

It is expected that the Angular application starts without error.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 12

**Device:**

- OS: [Windows]

## Additional notes

_Add any other notes about the problem here._

**Comment by bbogdanov** [comment]
Hi @iamebuka, 

Thank you for bringing our attention to it!

 I raised a PR to fix this issue. We are going to do a release soon so it will be fixed in near future.
