### ISSUE TITLE
The Stack View Cheveron is not middle aligned on Stack View with children

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#65]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Stack View's with children should display a chevron vertically aligned in the middle. 

### Actual behavior

The Stack View with children has a chevron aligned to the top of its container. 

### Reproduction of behavior

<img width="259" alt="screen shot 2016-11-15 at 3 53 30 pm" src="https://cloud.githubusercontent.com/assets/433692/20329206/b781ccb6-ab4b-11e6-8e89-923829b6fae7.png">

### Environment details

* **Angular version:** 2.2.0

* **Clarity version:**  0.7.0

* **OS and version:** OSX (El Capitan) & Windows 10

* **Browser:** [ Firefox 49.0, IE 10,  IE 11, MS Edge  ]

**Comment by jaffoneh** [comment]
@hippee-lee seems this has been fixed in 0.7.1 (I believe it was fixed by @Shijir). If you can still replicate it please reopen this issue. https://vmware.github.io/clarity/news/releases/0.7.1/
