### ISSUE TITLE
Columns in data rows for some data grids are too wide

### ISSUE THREAD

**Issue by ahmedmenaem** [vmware/clarity#6500]
## Columns in data rows for some data grids are too wide

_When we use data-grid to create a new table if we added a long text inside `<clr-dg-cell>` it's not working as expected some columns are too wide you can check this [Link to the reproduced issue](https://stackblitz.com/edit/clarity-dark-theme-v5-wvyxkc)_

## How to reproduce

_[Link to the reproduced issue](https://stackblitz.com/edit/clarity-dark-theme-v5-wvyxkc). You can find the issue that happened with this code on stackblitz._

## Expected behavior

_All columns are supposed to have the same `max-width` when we use`<clr-dg-cell>`_

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_Angular 11_

**Device:**

- Type: [MacBook]
- OS: [macos]
- Browser [chrome]
- Version [96]

## Additional notes

_No Additional notes._

**Comment by bdryanovski** [comment]
We don't truncate the content inside the columns so long string single strings will always take more space, if you have some specific use case and require to have this type of "hash" strings you could truncate them yourself by creating an Angular Pipe for that or truncate them with CSS by adding a custom class. 

Marking this as support question.
