### ISSUE TITLE
Structured Lists

### ISSUE THREAD

**Issue by lambdakris** [vmware/clarity#651]
**Select one ...**  (check one with "x")
```
[ ] bug
[x ] feature request
[ ] enhancement
```

### Expected behavior
I was wondering whether there is any support or planned support for the kinds of lists sometimes used for outlook style inbox side bars or mobile style menu lists. To be honest, I'm not sure what the right terminology is but I have included some links to frameworks/libraries/kits that contain something of the sort:
http://harmony.intuit.com/lists/
https://grommet.github.io/docs/list
https://semantic-ui.com/elements/list.html
http://react-toolbox.com/#/components/list
https://www.material-ui.com/#/components/list

### Actual behavior
I spent some time looking through the docs but was unable to find something resembling a "structured list". In particular, the all of the following components seem to be quite explicitly for simple textual content:
https://vmware.github.io/clarity/documentation/lists
https://vmware.github.io/clarity/documentation/sidenav
https://vmware.github.io/clarity/documentation/tree-view

The stack view kinda has the look but clearly has a different function:
https://vmware.github.io/clarity/documentation/stack-view

I suppose the closest thing might be to use single column table with no header:
https://vmware.github.io/clarity/documentation/tables

Of course, I'm sure one could just style a ul or a series of divs oneself, but that would kinda defeat the purpose of using a pattern/component library like Clarity...

### Environment details

Clarity 0.8.12

**Comment by reddolan** [comment]
@lambdakris thanks for sharing this with us. This would be a unique component and I could see it being useful as Clarity continues to open up mobile/touch experiences. That said, do you happen to have use cases or mockups outlining your use cases?

**Comment by lambdakris** [comment]
Well, this is tough to describe because I don't know what the patterns are called, but I'm beginning to think that what I'm thinking of might easily be two different patterns or components. The first is a list that would appear in something like a sidebar with structured content within each item and separators within the items. The Intuit Harmony site seems to refer to it as a "Complex List" (see http://harmony.intuit.com/lists/ towards the bottom where it is used to list companies on the left side of the "Splitview"). The second would be a list used as the main or part of the main content, so the items would be wider and typically contain more content. An example might be the activity feed in this Grommet sample app, http://ferret.grommet.io/activity.

I also cooked up some really barebones codepens made with grommet.

https://codepen.io/lambdakris/pen/LWXRQz?editors=0010#0
https://codepen.io/lambdakris/pen/JWeRVM?editors=0010

Hope this helps

**Comment by reddolan** [comment]
These help. I was hoping to understand more of the content details that would show in a row
Do you know if you need:
- one line of text, two, multiple
- left-aligned text only, or right-aligned text as well
- free form design possibilities similar to this
![screen](https://cloud.githubusercontent.com/assets/1858226/24616728/96edc896-1857-11e7-969f-a6cbcb79168b.png)

**Comment by mathisscott** [comment]
@lambdakris 
Do you have any more information for @reddolan's questions above?

**Comment by lambdakris** [comment]
Yikes, completely tuned out of this one... my bad

Ideally, a list item should:
Support multiple lines
Support left aligned content and right aligned content
Support content with padding and without padding

In truth, you can accomplish the look with a list of divs with dividers between. You could place the list of divided divs inside of a container bordered or non-bordered according to how you want it to look against the other elements on the page.

**Comment by mathisscott** [comment]
Thanks, @lambdakris

**Comment by gnomeontherun** [comment]
This is a larger issue due to the number of potential permutations. I believe its a potentially valuable component, but we do need to settle on the constraints. It is largely just styling types of lists, I believe.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
