### ISSUE TITLE
Timeline current step icon has both aria-current="true" and aria-label="Curent" set

### ISSUE THREAD

**Issue by KingMario** [vmware/clarity#6524]
## Describe the bug

Timeline current step icon has both aria-current="true" and aria-label="Curent" set

## How to reproduce

1.  Create a timeline
2.  Inspect the current step's dot circle icon
3.  Observe that the icon has both aria-current="true" and aria-label="Curent" set

## Expected behavior

For screen reader user, the current step icon will be announced as "Current current".

Redundant words might confuse screen reader users.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Comment by bbogdanov** [comment]
@scroniser Can you please take a look at this? We can drop the `aria-current` cause this Firefox is the only browser that doesn't support it. On the other hand `aria-label` is been read by every browser and we have both in our code. https://github.com/vmware/clarity/blob/5aa9006d88c6de955f494a866266a6e04b56894c/projects/angular/src/timeline/timeline-step.ts#L24
