### ISSUE TITLE
Your own seed project can't compile. It says "webpack: Failed to compile."

### ISSUE THREAD

**Issue by tomjaeschke** [vmware/clarity#653]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
following these steps at the get started...
1. Clone the seed app: git clone https://github.com/vmware/clarity-seed.git
2. Install the dependencies: npm install
3. Run the seed app: npm start
...should run the app.

### Actual behavior
I get a webpack error saying "webpack: Failed to compile."

### Reproduction of behavior
1. Clone the seed app: git clone https://github.com/vmware/clarity-seed.git
2. Install the dependencies: npm install
3. Run the seed app: npm start

### Environment details

It's your stuff.

**Comment by Shijir** [comment]
Hi @tomjaeschke, we have `yarn` and recommend users to use it instead of `npm install`. Some of the dependency modules might have been upgraded, which could cause such an error.
