### ISSUE TITLE
Read-only Input Field Component

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#656]
### Description
Read-only is a state of an input field in which the value is not editable. In another context, or if a condition has been met, the same input value may be editable.

### Example
![image](https://cloud.githubusercontent.com/assets/23196444/24431163/38d4ca48-13cf-11e7-94dd-5f3e55503cec.png)

![image](https://cloud.githubusercontent.com/assets/23196444/24431173/46838c06-13cf-11e7-952a-78ff390e9de6.png)

In this context, the action “Allow” is the only option available. Removing the input line and the caret makes it clear that “Allow” is a fixed value. This focuses the user’s attention on editable input fields, making it easier and faster to fill out the form.

Read-only text is at 100% opacity rather than greyed (disabled) in order to make it distinguishable from disabled text and help text, and to maintain the importance of the text.

### Read-only spec

![image](https://cloud.githubusercontent.com/assets/23196444/24431129/08019a2c-13cf-11e7-8445-421eeb21a1fd.png)

**Comment by adityarb88** [comment]
I have added the styles for readonly input fields with this PR: #987 but I am still keeping it open to discuss possibilities for other form fields
