### ISSUE TITLE
wrong documentation for .subnav

### ISSUE THREAD

**Issue by laco0416** [vmware/clarity#658]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

`.subnav` is the correct selector for Subnav component.

### Actual behavior
https://vmware.github.io/clarity/documentation/header#subnav

the documentation says it is `.sub-nav`. 

![image](https://cloud.githubusercontent.com/assets/1529180/24437081/fe42ffac-1479-11e7-8e05-fb9fcaf40bb4.png)

example code is correct.

![image](https://cloud.githubusercontent.com/assets/1529180/24437105/2db5bf90-147a-11e7-97ee-95c0d033b82f.png)

I wanted to contribute directly with PR, but I cannot find where is that documentation placed in...

**Comment by adityarb88** [comment]
Thanks for reporting this issue. Fixed.
