### ISSUE TITLE
[@core/react] NotSupportedError Failed to construct 'CustomElement': The result must not have attributes

### ISSUE THREAD

**Issue by astorije-vmware** [vmware/clarity#6589]
## Describe the bug

I was investigating why breadcrumbs were not working properly in our of our apps where we upgraded Clarity Core from v5.5.4 to v5.6.2. Upon creating a reproducible sandbox, this appeared:

<img width="372" alt="Screen Shot 2022-01-24 at 2 20 40 PM" src="https://user-images.githubusercontent.com/90871916/150849765-c8ebc12a-17dc-432c-9b67-6e35f1a25a79.png">

I don't know if the broken breadcrumbs are a consequence of this (you can see the breadcrumbs underneath looking like "FooBarBaz" instead of "Foo / Bar / Baz") but I did experience this same `Failed to construct 'CustomElement'` error when I started using `CdsCard` so it doesn't seem to be an isolated event.

## How to reproduce

The error should appear upon loading of: https://codesandbox.io/s/fragrant-pond-zf71n?file=/src/App.tsx

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.6.1 / v5.6.2

**Framework:**

- [ ] Angular
- [x] React 17
- [ ] Vue
- [ ] Other:

**Comment by astorije-vmware** [comment]
I just noticed this on v5.6.1 as well, so we will downgrade to v5.6.0 for now :(

**Comment by coryrylan** [comment]
I see the issue, we should have this corrected in the next release.

**Comment by astorije-vmware** [comment]
Thanks @coryrylan! I know that's a long shot, but do you have any time estimate? That would help us plan our next steps, but no worries if not :)

**Comment by mathisscott** [comment]
We just finished a release so our next one is likely to be week after next (two week cadence). Some stuff is going on. So maybe it happens sooner or later. But only by a week either way regardless.

**Comment by astorije-vmware** [comment]
Are you talking about v6.0.0-next.3?
Any chance this fix could make it into a v5.6.3 release so we're not stuck on v5.6.0 until v6 is a stable release?

Thank you!

**Comment by mathisscott** [comment]
If this change is not a breaking change, you can expect it to land in 5.6.3. That said, 5.6.3 isn't going to be out for at least two weeks from now due to our two week release cycle...
