### ISSUE TITLE
clarity-seed-master not working

### ISSUE THREAD

**Issue by makgul1** [vmware/clarity#659]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
 I expect the code to run.

### Actual behavior
The code cannot be compiled.

### Reproduction of behavior

-download seed master clarity-seed-master from https://github.com/vmware/clarity-seed
-npm install clarity-icons --save
-npm install @webcomponents/custom-elements@1.0.0-alpha.3 --save
-npm install mutationobserver-shim@0.3.2 --save
-npm install clarity-ui --save
-npm install clarity-angular --save
-npm serve

The error is:

ERROR in multi script-loader!./~/core-js/client/shim.min.js script-loader!./~/mu
tationobserver-shim/dist/mutationobserver.min.js script-loader!./~/@webcomponent
s/custom-elements/custom-elements.min.js script-loader!./~/clarity-icons/clarity
-icons.min.js script-loader!./~/web-animations-js/web-animations.min.js
Module not found: Error: Can't resolve 'D:\JetBrains\Prjs\clarity-seed-master\no
de_modules\web-animations-js\web-animations.min.js' in 'D:\JetBrains\Prjs\clarit
y-seed-master'
 @ multi script-loader!./~/core-js/client/shim.min.js script-loader!./~/mutation
observer-shim/dist/mutationobserver.min.js script-loader!./~/@webcomponents/cust
om-elements/custom-elements.min.js script-loader!./~/clarity-icons/clarity-icons
.min.js script-loader!./~/web-animations-js/web-animations.min.js
webpack: Failed to compile.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** clarity-seed-master

* **OS and version:** windows 7, 64 bit

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Jinnie** [comment]
This issue was soon discussed here:
https://github.com/vmware/clarity/issues/653
@Shijir suggests it's better to use yarn instead of npm install.

**Comment by Shijir** [comment]
Hi @makgul1, if you are using `clarity-seed`, you don't need to do the setup yourself.

>-download seed master clarity-seed-master from https://github.com/vmware/clarity-seed
-npm install clarity-icons --save
-npm install @webcomponents/custom-elements@1.0.0-alpha.3 --save
-npm install mutationobserver-shim@0.3.2 --save
-npm install clarity-ui --save
-npm install clarity-angular --save
-npm serve

All these dependencies will be installed after you run `yarn` or `npm install`. And then, you would want to run `ng serve` to serve your app.
