### ISSUE TITLE
Host icon - size and style inconsistencies

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#6598]
##  Replace host icon with updated .svgs
Issues: 1) Size of base icon is smaller than the badge and alert versions. 2)Downloaded base icon is different from preview

![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/21b632f9-bb9e-4679-89eb-d7ad94ba470e)

_See above: the base icons (in pink boxes) are smaller than the badge/alert versions. The download is also slightly smaller_

**Please replace the whole set as I made a small change to each:**
[https://app.zenhub.com/files/69590701/cb8abdab-adc8-462d-9950-c4c4f70e10fd/download](https://app.zenhub.com/files/69590701/cb8abdab-adc8-462d-9950-c4c4f70e10fd/download)

The icons should look like this:
![image.png](https://images.zenhubusercontent.com/5840974cb9dc3c622022d1df/01842d90-cc45-46de-8d21-dabac5b6c701)

**Clarity project:**

- [ ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ x ] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by Shijir** [comment]
Hi @lil-kim, I just checked the icon assets provided. The solid and alert variation icon assets have styles in their svg. Can we have them in a single path svg?

**Comment by lil-kim** [comment]
Hi @Shijir 
I've updated the icons as requested:
[host_icon_1-31-22.zip](https://github.com/vmware/clarity/files/7974491/host_icon_1-31-22.zip)
