### ISSUE TITLE
Datepicker  older year selection inputbox making empty. no option to disable older years

### ISSUE THREAD

**Issue by muruganG** [vmware/clarity#6606]
## Describe the bug
There is two observation found on related to latest clarity 5 datepicker
  1.older year disable option not there.
  2. when i select older years with date combination ,input box going empty. not changed the value of previous value.

## How to reproduce
i have shared the step screens  you able to reproduce the you documentation datepicker sample also.

1. Go to the clarity 5 documentation  datepicker sample try to change the year 950 and try to change the date , when you select the date  input box its not showing the date.

## Expected behavior
Is there any option we can disable the older years? 
older year selection should show the selected [value.](url)
## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._
![step4](https://user-images.githubusercontent.com/10629787/151488675-8ce6d10c-7130-4e9a-985f-c34dc46632bb.PNG)

**Comment by muruganG** [comment]
Step1
![Step1](https://user-images.githubusercontent.com/10629787/151488859-f0dbbc96-d5eb-4628-a94e-02e2635121c6.PNG)

Step2
![Step2](https://user-images.githubusercontent.com/10629787/151488798-484b8cc1-139b-44a4-b121-50d73c67b81b.PNG)


Step3 
![Spet3](https://user-images.githubusercontent.com/10629787/151488823-52f78ffa-3987-49f1-8ca1-271b7ce5a037.PNG)

Step4 
![step4](https://user-images.githubusercontent.com/10629787/151488841-4a88aee9-9d0f-45d5-b4a8-633fe90b0481.PNG)

**Comment by bbogdanov** [comment]
Hi @muruganG,

Seems like we have a logic that doesn't allow years under 999 to be selected. https://github.com/vmware/clarity/blob/648fb89ed867f508c9057a9cc6a835b376a78609/projects/angular/src/forms/datepicker/utils/date-utils.ts#L29

Would you like to give us some clarity about your case?

I also would encourage you to check our Clarity Core datepicker that doesn't give you such restrictions and give you all the freedom to select whatever date you need. https://clarity.design/storybook/core/?path=/story/forms-date--page

**Comment by muruganG** [comment]
There are two thing need  to understand. I went throw the documentation 
1. its allowing to select older years  and date if not valid date should not clear previous selected date and year. that is the problem currently facing. (Spet 4 snapshot its cleared  existing selected value,  because of  invalid date and year)
2. Is there any  way we can block older year selection any custom approach?

**Comment by bbogdanov** [comment]
What I believe it will be the best approach here is to set a `min` on the `input` and hook on `(ngModelChange)` or `(change)` and maintain the state manually to keep the previous selected inside the input if the new value is not a valid one. The `min` property will prevent the datepicker to disable older than the `min` dates to be selected but at the same time it won't prevent manual entrance.
