### ISSUE TITLE
clr-dg-action-overflow throws an error after an item is removed from the datasource

### ISSUE THREAD

**Issue by vasil-ivanov** [vmware/clarity#661]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No runtime error should be thrown

### Actual behavior
A runtime exception is thrown: TypeError: Cannot read property 'destroy' of undefined

### Reproduction of behavior

This is the grid that I define:

`<clr-datagrid>
    <clr-dg-column [clrDgField]="'name'">
        Name
    </clr-dg-column>
    <clr-dg-column [clrDgField]="'location'">
        Location
    </clr-dg-column>
    <clr-dg-row *clrDgItems="let dataRow of data">
        <clr-dg-action-overflow>
            <button class="action-item" (click)="onEdit(dataRow)">Edit</button>
            <button class="action-item" (click)="onDelete(dataRow)">Delete</button>
        </clr-dg-action-overflow>
        <clr-dg-cell>
            {{dataRow.name}}
        </clr-dg-cell>
        <clr-dg-cell>
            {{dataRow.location}}
        </clr-dg-cell>
    </clr-dg-row>
</clr-datagrid>`

The onDelete() function is defined as follows:
`
public onDelete(item: any): void {
   this.data.splice(this.data.indexOf(item), 1);
}
`
When I click delete for an item the items gets properly removed. However, if go and invoke the menu for the second time and click Edit or click outside the menu an error is generated:
TypeError: Cannot read property 'destroy' of undefined
    at eval (clarity-angular.umd.js:1676)
    at SafeSubscriber.schedulerFn [as _next] (core.umd.js:4135)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:250)
    at SafeSubscriber.next (Subscriber.ts:202)
    at Subscriber._next (Subscriber.ts:135)
    at Subscriber.next (Subscriber.ts:95)
    at EventEmitter.Subject.next (Subject.ts:61)
    at EventEmitter.emit (core.umd.js:4109)
    at QueryList.notifyOnChanges (core.umd.js:9149)
    at CompiledTemplate.proxyViewClass.View_DatagridActionOverflow0.detectChangesInternal (/ClarityModule/DatagridActionOverflow/component.ngfactory.js:67)

Clarity Plunker: https://plnkr.co/JHBWtz

NOTE: On Firefox The vertical ellipsis at the beginning of each row do not render for some reason in plunker but they are clickable and the menu gets shown. So just click the white space at the beginning of the row.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version: 0.8.11** 

* **OS and version: Windows 8.1** 

* **Browser:** [Chrome XX | Firefox XX | IE XX ]

**Comment by Shijir** [comment]
Closing this issue as the reported bug has been no longer reproducible in Clarity v0.9.1 and v0.8.16.
The following demo is running 0.8.16: https://plnkr.co/edit/TOakzh60uU6ZRnRxbN4c?p=preview.
