### ISSUE TITLE
clr-dg-action-bar feature should be enabled for datagrids which do not offer selection

### ISSUE THREAD

**Issue by vasil-ivanov** [vmware/clarity#662]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
If I have a simple grid where I don't need any selection (no checkboxes/radios). I want to be able to use the `clr-dg-action-bar` component so that I can show some action buttons related to the list which do not depend on selection. Such would be the case where I show an Add button for adding new items to the list.

See: [Sample datagrid](http://imgur.com/zRTX7rM)

### Actual behavior

clr-dg-action-bar is only available if selection is present.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version: 0.8.11** 

* **OS and version: Windows 8** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jeeyun** [comment]
Hi @yenmade and @reddolan, can you provide some UX input on this?

Previously we have implemented the action bar to only display the action bar buttons if the user selects one or more items in the datagrid.

With this change request (use case above), we will now be delegating to the app-side to make it context sensitive. So the same logic (of only showing the buttons when a user selects one or more items) will be achievable, but no longer automatically provided by Clarity. I think this is ok, but just wanted to check.

**Comment by mathisscott** [comment]
@reddolan : Could you take a look at Jeeyun's comment?

**Comment by reddolan** [comment]
@vasil-ivanov I am concerned that a user would only ever be able to add rows and not edit or remove them. What happens if a user accidentally adds one too many rows and needs to remove it? I am having a tough time thinking of a use case where a user would only ever do "irreversible" actions. Aside from "add", what other actions or use cases would be able to be done at the datagrid-level versus row-level?

**Comment by dabkowitz** [comment]
@reddolan The vast majority of tables we have in VRA/Prelude have the table level action "Add New".  I could imagine others like "Print" or "Add Property".    For many of these we also have line level actions that could be single or multi select, such as Delete, Edit, Start, Stop, etc.

I suggest that the datagrid level actions appear until line item(s) are selected.  When items are selected presumably you want to take action on them and the bulk actions appear above the datagrid in place of the table level actions, e.g. Delete.   After the selected items have been acted on then they are deselected, if they still exist, and the datagrid actions reappear e.g. Add New.

**Comment by jeeyun** [comment]
It makes sense that the action bar can be used for when there's no selection for table-level action, and for the content of the action bar to change upon selection to be context sensitive. I'll move forward with this PR and put it up for code review.
