### ISSUE TITLE
Creat React App / Webpack 5

### ISSUE THREAD

**Issue by coryrylan** [vmware/clarity#6622]
## Describe the bug

_A clear and concise description of what the bug is, and the conditions when it occurs._

## How to reproduce

```
yarn create react-app test
cd test
yarn add @cds/core @cds/city @cds/react
yarn install --check-files
```

## Expected behavior

With Webpack 5 import paths must require a `.js` extention on the end of file imports. 
https://github.com/vmware/clarity/pull/5714 but then a regression re-introduced later

All imports in the `@cds/react` library that are a path to a direct file need to have the `.js` extention. Most are the following path

```javascript
import { logReactVersion } from '../utils/index';
```

https://github.com/vmware/clarity/blob/next/packages/react/src/badge/index.tsx#L5 

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
This should be fixed in #6627

**Comment by coryrylan** [comment]
This is a different issue, https://github.com/vmware/clarity/pull/6627 did fix its intended issue

**Comment by coryrylan** [comment]
Opened separate issue here https://github.com/vmware/clarity/issues/6695, thought this was a duplicate
