### ISSUE TITLE
Regular and compact outline buttons with dropdown do not resize according to the button text (Figma).

### ISSUE THREAD

**Issue by pnedkovavmware** [vmware/clarity#6628]
## Describe the bug

Both regular and compact outline buttons with dropdown do not have auto layout, so they do not resize according to the button text.

## How to reproduce

It's a Figma component error.

Just create an instance of the outline button component with a dropdown (compact or regular) and try to write a text whose width is longer than the component's width. 

## Expected behavior

The button should resize according to the text in it. 

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [ ] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**

- Type: [e.g. MacBook]

## Additional notes

_Add any other notes about the problem here._

**Comment by mathisscott** [comment]
@colinreedmiller
