### ISSUE TITLE
Cannot enlarge clr-stack-label …

### ISSUE THREAD

**Issue by KlausEichinger** [vmware/clarity#663]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
[x] help
```

### Expected behavior
Enlarge the clr-stack-label

### Actual behavior
Given is a clr-modal with clr-stack-view. 

Inside there are four blocks w/ several children. The block.titles within cld-stack-label are names like:
William Monroe Dafoe
John 'Sugarhill Gang' Johnson
Thomas Irving Rutherford

I would like to have these names in one line, not multi-lined. But I can’t override the css class dt.stack-block-label

`<clr-stack-view>

	<clr-stack-block>
		<clr-stack-label>Thomas Irving Rutherford VII</clr-stack-label>
                
	</clr-stack-block>

</clr-stack-view>`

### Environment details

* **Angular version:** 2.4.7

* **Clarity version:** 0.8.6

* **OS and version:** os: darwin x64

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
Hi @KlausEichinger! Are you trying to display your stack blocks in columns? If then, our current `clr-stack-view` doesn't support that.

**Comment by KlausEichinger** [comment]
Hi Shijir Tsogoo! I call a modal from a button via (click)=„editModal=true“

**Comment by Shijir** [comment]
@KlausEichinger could you provide a [Plunkr](https://plnkr.co/8TwwdL) for what you are trying to achieve? So then, we could give you a better support.

**Comment by KlausEichinger** [comment]
`<a (click)="editModal= !editModal"></a>
<clr-modal [(clrModalOpen)]="editModal">
    <h3 class="modal-title">Edit mode</h3>
    <div class="modal-body">
        <clr-stack-view>
            <clr-stack-block>
                
                <clr-stack-label>William Monroe Dafoe</clr-stack-label>
                
                

                
                <clr-stack-block>
                    <clr-stack-label>Game</clr-stack-label>
                    <clr-stack-content>
                        <input type="text" value="World of Warcraft"/>
                    </clr-stack-content>
                </clr-stack-block>
                <clr-stack-block>
                    <clr-stack-label>Game</clr-stack-label>
                    <clr-stack-content>
                        <input type="text" value="FIFA 17"/>
                    </clr-stack-content>
                </clr-stack-block>
        </clr-stack-view>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" (click)="editModal = false">Done</button>
    </div>
</clr-modal>`

**Comment by KlausEichinger** [comment]
[plunkr](https://plnkr.co/edit/gtU7GpvWjV5SPuZotIO1?p=preview)

I'm not very familiar w/ plnkr. Hope you can see what's the problem.
