### ISSUE TITLE
Regression: Empty boolean attributes are broken in @cds/angular@5.6.1 (and up)

### ISSUE THREAD

**Issue by thojo** [vmware/clarity#6642]
## Describe the bug

After updating Clarity from 5.5.1 to 5.6.2 empty boolean attributes are evaluated as falsy. This was once already fixed for 5.2.1 in #5932.

```html
<cds-tag readonly>readonly tag</cds-tag>
```

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-dark-theme-v5-ljlano?file=package.json
2.  Click on "Readonly Tag" an see interaction behaviour like "Clickable Tag", which shouldn't be there.
3.  Downgrade `@cds/angular` to 5.6.0
4.  Click on "Readonly Tag". There is no interaction behaviour.

## Expected behavior

Empty boolean attributes are interpreted as truthy/present like in version 5.6.0.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11 and 12

## Additional notes

A workaround is to use property binding syntax:

```html
<cds-tag [readonly]="true">readonly tag</cds-tag>
```

**Comment by coryrylan** [comment]
Thank you for the reproduction! We should be able to get a fix out for our next release.
