### ISSUE TITLE
When tree-nodes come from other components, they render horizonatally

### ISSUE THREAD

**Issue by dstovall** [vmware/clarity#6662]
## Describe the bug

When a Tree View includes other components that render their content as tree-nodes, these nodes render horizontally instead of vertically.

## How to reproduce

https://stackblitz.com/edit/clarity-v4-tree-node-components

The tree in this StackBlitz is just the Basic Tree example from the documentation, except the _Jim Halpert_ and _Angela Martin_ nodes have been moved into the separate _inner-node_ component.

1.  Go to https://stackblitz.com/edit/clarity-v4-tree-node-components
2.  See the error on the right

## Expected behavior

_Jim Halpert_ and _Angela Martin_ tree nodes should appear below the _Michael Scott_ node and they should hide when the _Michael Scott_ node is collapsed.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [X] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [X] v4.x
- [ ] v5.x

**Framework:**

- [X] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_Angular 10_

**Device:**

- Type: MacBook
- OS: OSX
- Browser Chrome
- Version 98.0.4758.80

## Additional notes

I know that this technique worked in the past, but I do not know what changed since I observed this working.

**Comment by Jinnie** [comment]
Angular fails to identify `app-inner-node` as something that should be projected inside the tree component.
We can help this by adding `ngProjectAs` attribute like this:
```
      <app-inner-node ngProjectAs="clr-tree-node"
      ></app-inner-node>
```
It works where we have direct content projection using `<ng-content>`, like here, in the tree, but will not work in other areas where projection is handled manually with `@ContentChildren`.
So it is not universal fix. But in this case it seems to be working.
