### ISSUE TITLE
Documenation: SVG-Icon download link broken

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#6666]
## Describe the bug

SVG-Icon download link seems to be broken for all icons.

## How to reproduce

1.  Go to https://clarity.design/foundation/icons/shapes/
2.  Click on 'any icon'
3.  Select button download "SVG ICON"
4.  See error
    404 ERROR, Page not found. 
    The link is broken or the page has moved.

## Expected behavior
Download SVG icon

## Versions

**Clarity project:**

- [x] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**
current version
- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Device:**
any

**Comment by mathisscott** [comment]
Hi @d-m-s 
Thanks for the heads up. I redeployed the website. These links should work now.

**Comment by d-m-s** [comment]
perfekt, works fine thx @mathisscott
