### ISSUE TITLE
Datagrid filters broken when multiple filters are open

### ISSUE THREAD

**Issue by jarinwhite** [vmware/clarity#668]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When opening multiple filters on a datagrid, each filter should display as "open" and operate independently.

### Actual behavior

After opening one filter and leaving it open, opening another filter takes two clicks. Upon the second click, a box appears with only an "x" and no filter contents. This small box cannot be closed. Continuing to click the filter icon causes erratic behavior, such as opening new filter windows on top of the existing ones.

![image](https://cloud.githubusercontent.com/assets/2184186/24591233/82eca992-17c2-11e7-9b05-09d112b99040.png)

![image](https://cloud.githubusercontent.com/assets/2184186/24591244/c8242346-17c2-11e7-802e-8f7cbb6966cd.png)

### Reproduction of behavior
Clarity's own documentation page exhibits this behavior. 
https://vmware.github.io/clarity/documentation/datagrid

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** Verified in latest Chrome and Firefox

**Comment by adityarb88** [comment]
Hi @jarinwhite: Could you please provide a plunker so that we can replicate this issue? https://plnkr.co/8TwwdL

**Comment by adityarb88** [comment]
actually nevermind. I am able to replicate it on the website. Thanks for reporting this.

**Comment by jarinwhite** [comment]
Happy to help! Thank you @adityarb88 for the quick response.

**Comment by jarinwhite** [comment]
Sorry to be a pain, but is there an ETA on this by any chance? I saw that it was removed from the 0.9.1 milestone so I was just curious what the status is. Thank you!

**Comment by jeeyun** [comment]
Hi @jarinwhite we discovered a couple of issues with the fix, so currently working on addressing them. I expect the fix to go out pretty soon. Best case scenario is 0.9.2 but might slip to 0.9.3.

**Comment by jarinwhite** [comment]
Sounds great. Thanks @jeeyun!
