### ISSUE TITLE
The detailButton of Clarity Datagrid Row is with wrong type in the datagrid-row.d.ts

### ISSUE THREAD

**Issue by TodorBonchev** [vmware/clarity#6694]
ClrDatagridRow has a public field detailButton which is of type ElementRef: https://github.com/vmware/clarity/blob/angular/projects/angular/src/data/datagrid/datagrid-row.ts#L173

But in the typings file: datagrid-row.d.ts the type of the field is HTMLButtonElement

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11_

**Device:**

- Type: [e.g. MacBook]

**Comment by bbogdanov** [comment]
Hi @TodorBonchev,

<img width="1642" alt="image" src="https://user-images.githubusercontent.com/15037947/155182050-2a183576-b6ef-4828-8ab3-edfd36e959b1.png">

This is what I see in our `dist` folder. 

I remember doing a PR about changing this from `HTMLButtonElement` to `ElementRef` around 3-4 months ago. Maybe the version you are using is older than the latest.

**Comment by TodorBonchev** [comment]
Thanks Bogdan,
In this case you can close the issue if it is already fixed.
