### ISSUE TITLE
Feature Request: TreeView

### ISSUE THREAD

**Issue by aldialimucaj** [vmware/clarity#67]
We would love to have TreeView in the awesome framework.

```
[ ] bug
[X ] feature request
[ ] enhancement
```

**Comment by jaffoneh** [comment]
@aldialimucaj thanks for the feedback, a tree view is definitely on our roadmap.

**Comment by kucharzyk** [comment]
@jaffoneh Maybe it's good idea to publish clarity roadmap to avoid issues like this one?

**Comment by jaffoneh** [comment]
@kucharzyk we're actually working on it. We're considering a few ways to do it (Trello, GitHub Projects and Issues, etc) but our goal to provide short term goals (that you can depend on) as well as longer term roadmap as well.

**Comment by aldialimucaj** [comment]
@jaffoneh thanks for the quick response. im closing this issue then and wait for the roadmap.
