### ISSUE TITLE
cannot work updateFilterValue with custom filters 

### ISSUE THREAD

**Issue by kitodev** [vmware/clarity#6702]
## Describe the bug

I want to use updateFilterValue when click to clear all filter button, but it does not work with the built in filters:

https://stackblitz.com/edit/clear-allfilter?file=src/app/app.component.ts

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
 Angular 13

**Comment by Jinnie** [comment]
It does work with built-in filters. Here's your StackBlitz from the previous bug, updated:
https://stackblitz.com/edit/clear-allfilter-ur3tzc?file=src%2Fapp%2Fapp.component.ts

The difference with the new StackBlitz is that it features some custom filters, which are themselves not working in the linked demo above, see your HTML template.  Probably left-over from some attempts to make it work with custom filters?

**Comment by kitodev** [comment]
@Jinnie thank you for the response. in fact, i want to use the Clear Filter option on the custom filter. There is any solutions maybe, how can i do that?

**Comment by Jinnie** [comment]
@kitodev I'd ask to start with a working reproduction. The above StackBlitz does not really work, so I can't say or debug now at what level the functionality gets broken.
I'll reopen the issue and mark it as needing reproduction.
