### ISSUE TITLE
Icon 'script-execute' and 'script-schedule' not in icon/index.js

### ISSUE THREAD

**Issue by ccjasonlin** [vmware/clarity#6708]
I tried to import "scriptExecuteIcon" "scriptScheduleIcon" from '@cds/core/icon' but I couldn't find them.

**Comment by Jinnie** [comment]
@ccjasonlin Please try to reproduce your problem in one of our stackblitz templates:
https://stackblitz.com/@clr-team

**Comment by ccjasonlin** [comment]
https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-xgpkdz?file=src%2Fapp%2Fapp.component.ts

You can reproduce it as simple as adding the import
import { ClarityIcons, homeIcon, scriptScheduleIcon } from '@cds/core/icon';

The following error will show

Error: src/app/app.component.ts:2:34 - error TS2305: Module '"@cds/core/icon"' has no exported member 'scriptScheduleIcon'.

2 import { ClarityIcons, homeIcon, scriptScheduleIcon } from '@cds/core/icon';

=====
`import { Component } from '@angular/core';
// import { ClarityIcons, homeIcon } from '@cds/core/icon';
import { ClarityIcons, homeIcon, scriptScheduleIcon } from '@cds/core/icon';

import '@cds/core/icon/register.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular-cli';

  constructor() {
    ClarityIcons.addIcons(homeIcon);
    ClarityIcons.addIcons(scriptScheduleIcon);
  }
}`

**Comment by bbogdanov** [comment]
Hi @ccjasonlin,

Seems like we didn't export it as a single icon. You can use the `technologyCollectionIcons` to use that icon until we export it as one. 

https://stackblitz.com/edit/clarity-light-theme-clr12-cds5-rlc6yk?file=src%2Fapp%2Fapp.component.ts Example
