### ISSUE TITLE
Styling for: input type="file"

### ISSUE THREAD

**Issue by civanova** [vmware/clarity#672]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
To be able to apply clarity styling on `<input type="file">` 

### Actual behavior
No styling is available so we are displaying the standard `<input type="file">`  that has a different look on different browsers

### Environment details

* **Angular version:** 2.0.X

* **Clarity version: 0.8.13

* **OS and version:OS X El Capitan 10.11.6

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
This is actually a pretty hard problem if you try to remain accessible, from what I remember. 
Just tagged it, we'll see how much of a priority it is during our planning sessions.

**Comment by civanova** [comment]
Hello,
We have an additional request for the input field.
We need it to be able to receive a custom label so that it can be identical to all browsers and localized depending on the user's locale

**Comment by bmireles** [comment]
We also have a need for this feature. Our need also ask's for the addition of multiple files. I created a concept below for use to develop and test. Would like to see what the clarity team thinks of this design.

![screen shot 2017-05-10 at 11 04 16 am](https://cloud.githubusercontent.com/assets/18449355/25908699/73d04240-3570-11e7-9bc2-6443983297e5.png)

In this design, the browse button allows the user to search for local files and add them. Once added, the file name is displayed in a label with and "x" icon to delete. I also enclosed the labels in a container that scrolls to limit the vertical space but still allows for multiple files to be added and easily accessed.

**Comment by jaffoneh** [comment]
@bmireles thanks for taking a look at this and coming up with a proposal, this helps. So here is the angels I see to this (so we have a clear understanding of this when we start working on it) and please let me know if I missed anything:

1. We need a quick styling of `input type="file"` itself when we're uploading a single file.
2. We need a case where we might want to upload *multiple* files before we actually go ahead and upload them together or post them together.

The above addresses 2 and somewhat addresses 1 styling wise. Keeping the needs-ux-input label to work on this and we'll prioritize it soon. / cc @mathisscott

**Comment by mathisscott** [comment]
Thanks, @bmireles . This looks like it would need to be an angular component. I will ask @reddolan to review it in the near future before discussing implementation with the team.

Any information on your circumstances of need will be helpful because we have a lot of competing priorities right now.

**Comment by reddolan** [comment]
@bmireles This looks good. Do you happen to also have a design for the single file experience?

**Comment by bmireles** [comment]
@reddolan Here is what I was thinking for a single file. Would like to get feedback on it though.

![browse-button-interaction-single-file-v1](https://user-images.githubusercontent.com/18449355/26839764-a46744a0-4aa9-11e7-9d76-54c75edb47c7.png)

**Comment by reddolan** [comment]
By default, the file upload handles one file at a time. HTML5 has an additional attribute that allows for multiple uploads. Though the files have to come from the same folder and be selected at the same time. If you select one file and then browse and select another file, the first one is replaced with the new selection. 

I recommend we go with the Option 2 design but keep the Browse button active at all times. After uploading more than one, than the design would expand like you have spec'd on your previous comment. This gives the user two ways of being able to change the file being uploaded: 
1. clicking the Browse button and selecting another file
2. clicking the X icon on the file name listed to remove it, then clicking Browse to select another file

**Comment by bmireles** [comment]
TY for the clarification @reddolan.

**Comment by omrico** [comment]
Nice workaround I came up with, use the input inside a label. You can style the label with Clarity .btn and .btn-link classes:

```
<label class="btn btn-link">
    <input type="file"
           (change)="onChange($event)"
           placeholder="Upload file"
           accept="*">
    Attach Files
</label>
```

**Comment by rdvojmoc** [comment]
In which version we can expect this to be implemented in Clarity?

**Comment by gnomeontherun** [comment]
The new forms has this styling designed, though we haven't built the Angular component for it yet.

**Comment by furti** [comment]
Maybe you can add "Drag & Drop" support to the file input component when you build a Angular component for it.

I created a custom file comonent for our project. When a file is dragged over the document, the component indicates that a file can be dropped with a border and a message:
![image](https://user-images.githubusercontent.com/2047555/58685405-e81de480-837b-11e9-8966-f975cfc95382.png)
When the file is dragged inside the border, the border color indicates this:
![image](https://user-images.githubusercontent.com/2047555/58685427-ff5cd200-837b-11e9-96db-00fd7588b9f2.png)

When the drag is cancelled, the border is removed.

Now when I look at it, maybe the button should also be hidden when a drag is in progress.

**Comment by d-m-s** [comment]
it seems a little silent around this component ...

could you guys @mathisscott, @gnomeontherun give us a bit of a heads up here:
 - is this design specification ready for implementation?
 - are there any planning details predictable? 
   currently no milestone, no project ...

**Comment by gnomeontherun** [comment]
It hasn't been prioritized yet, but there is the CSS version you can use available today (undocumented). https://github.com/vmware/clarity/blob/master/src/dev/src/app/forms/controls/file.html

**Comment by nmcbride** [comment]
Any updates on this?

**Comment by hippee-lee** [comment]
Its not currently prioritized for the core teams workload. Is it a feature you are interested in contributing?

**Comment by d-m-s** [comment]
file-upload seems like a very common component for an ui framework!

**any chances this get a little more attention?**

**Comment by d-m-s** [comment]
> It hasn't been prioritized yet, but there is the CSS version you can use available today (undocumented). https://github.com/vmware/clarity/blob/master/src/dev/src/app/forms/controls/file.html

![2020-06-16_13h58_21](https://user-images.githubusercontent.com/311619/84771326-860d3d00-afd9-11ea-86b9-2373e2797802.png)

**Comment by gnomeontherun** [comment]
Files have moved https://github.com/vmware/clarity/tree/master/packages/angular/projects/dev/src/app/forms/controls

**Comment by gnomeontherun** [comment]
This is available through @clr/core now, so I'm going to close this as resolved.
