### ISSUE TITLE
Documentation for read-only missing

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#6728]
## Describe the bug

- Documentation of `read-only` feature is missing for `input` controls.

**Related**: #6729 `readonly` attribute not supported/working for `select` (dropdown) input controls. 

## How to reproduce

See https://vmware.github.io/clarity/documentation/v0.12/input-fields
<img width="910" alt="readonly-v-0-12" src="https://user-images.githubusercontent.com/311619/155727080-1e186b20-ad0c-4fa4-a432-1da0e93d6351.png">

- :heavy_check_mark: Version **0.12** Documentation available  
- :x: Version **5.x** Documentation missing 

## Expected behavior

Add documentation to **Input**
https://clarity.design/core-components/input/
<img width="506" alt="input-v-5-x" src="https://user-images.githubusercontent.com/311619/155728273-7024e515-62be-4906-85c6-9694805a1025.png">

and probably to **Forms**
https://clarity.design/core-components/form/

:left_speech_bubble: **Note:** See further documentation available at https://github.com/vmware/clarity/issues/656

## Versions

**Clarity project:**
:heavy_check_mark: Clarity Core
:heavy_check_mark: Clarity Angular/UI

**Clarity version:**
:heavy_check_mark: v5.x

**Framework:**
:heavy_check_mark: Angular

**Device:**
Any

**Comment by ashleyryan** [comment]
Hello, this repository has been archived. If your issue still exists, please recreate the issue in one of the new repositories:

- [Clarity Core](https://github.com/vmware-clarity/core)
- [Clarity Angular](https://github.com/vmware-clarity/ng-clarity)
