### ISSUE TITLE
Read-only attribute not working for select-input component

### ISSUE THREAD

**Issue by d-m-s** [vmware/clarity#6729]
## Describe the bug
Similar to the input control, where the readonly attribute renders the component not-editable, the select control currently is not rendering the control not-editable.

**See design-spec**
 https://github.com/vmware/clarity/issues/656

<img width="633" alt="designspec-656-readonly" src="https://user-images.githubusercontent.com/311619/155731021-92937780-7a40-42ff-bfea-66b147154a3f.png">

## How to reproduce
1. Add `readonly` attribute to any select component
**Result** Component ignores the attribute and still renders editable.

## Expected behavior
:left_speech_bubble: As visible in the screenshot above or see further documentation at https://github.com/vmware/clarity/issues/656
- Current value of the select component should render not-editable.
- Drop-down caret should be hidden.

## Versions

**Clarity project:**
:heavy_check_mark: Clarity Core
:heavy_check_mark: Clarity Angular/UI

**Clarity version:**
:heavy_check_mark: v5.x

**Framework:**
:heavy_check_mark: Angular

**Device:**
Any

**Comment by ashleyryan** [comment]
Hello, this repository has been archived. If your issue still exists, please recreate the issue in one of the new repositories:

- [Clarity Core](https://github.com/vmware-clarity/core)
- [Clarity Angular](https://github.com/vmware-clarity/ng-clarity)
