### ISSUE TITLE
Lack of badge for namespaces icon

### ISSUE THREAD

**Issue by narnaudov-1** [vmware/clarity#6730]
## Describe the bug

I'd like to show problems with namespaces in a tree. Unfortunately, it seems that the namespaces icon doesn't support badging. Other options like changing color are not accessible.

## How to reproduce

Try to add badge to a namespace icon. 

## Expected behavior

I expect to be 

## Versions

**Clarity project:**

- [ ] Clarity Core
- [ *] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [* ] v5.x

**Framework:**

- [ *] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
_ie: Angular 11_

**Device:**
All

## Additional notes

If you have a jira project, I can open it there, too?

**Comment by mathisscott** [comment]
@narnaudov-1 
Not all the icons have badges. I will ping @lil-kim to see if badges could be added to this one.

**Comment by lil-kim** [comment]
I added the badges:
[namespace icon w badges.zip](https://github.com/vmware/clarity/files/8165138/namespace.icon.w.badges.zip)

**Comment by ashleyryan** [comment]
Hello, this repository has been archived. If your issue still exists, please recreate the issue in one of the new repositories:

- [Clarity Core](https://github.com/vmware-clarity/core)
- [Clarity Angular](https://github.com/vmware-clarity/ng-clarity)
