### ISSUE TITLE
Datagrid pageSize is not saved to localestore after page refresh

### ISSUE THREAD

**Issue by kitodev** [vmware/clarity#6736]
## Describe the bug

I'm trying to get server driven pagesize to work, but everytime I change pagesize, after page refresh jumps back to the default value.
Here is the example:

https://stackblitz.com/edit/clarity-datagrid-pagination-resize-1ekwae?file=src/app/app.component.ts

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 13

Is this a bug or am I using the pageSize incorrectly?

**Comment by bdryanovski** [comment]
You need to pass the stored value to the `[clrDgPageSize]="pageSize"`
