### ISSUE TITLE
[clr-data-grid] column grouping support

### ISSUE THREAD

**Issue by envyN** [vmware/clarity#674]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
Developers should be able to group together columns programatically

### Actual behavior
Currently not supported

### Reproduction of behavior
Check the following reference implementations:
https://www.primefaces.org/primeng/#/datatable/colgroup
http://demos.telerik.com/kendo-ui/grid/multicolumnheaders

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by reddolan** [comment]
@envyN your description mentions "users grouping columns". 
- PrimeNG demo: doesn't seem to allow a "user" to group column headers, it looks like the grouping would be done by the product team developing the datagrid. 
- Kendo demo: allow a user to drag and reorder the column headers, but not merge them into new groups. 

Can you elaborate on the specific use case you are wishing to achieve? Are you wanting column grouping but done at the product development level (like the demos)? Or something different?

**Comment by reddolan** [comment]
@envyN I wanted to circle back with you on this. Have you had a chance to review my questions from the previous comment?

**Comment by envyN** [comment]
Hi @reddolan sorry i missed the comments earlier.
I actually meant developers being able to do that.
updating the issue.

**Comment by vivekreddy** [comment]
Hi,

Any update on when this feature can be available?

**Comment by mathisscott** [comment]
Hi @vivekreddy 

This feature request for the data grid still needs to go through design before we can begin implementation.

So it's still a ways off.

Please subscribe to the issue so that you can receive updates on it in the future.

Thanks!

**Comment by sdurnov** [comment]
Am I understanding this correctly? Is this issue about "stacked columns", when 2 or more columns are grouped under the common header?
If yes, than I must say this is top 1 feature that prevented us using Clarity in our enterprise app.
I was able to almost get it working - "stacking" itself is working - just put columns and cells in a nested way + minor CSS fixes. But cells width isn't being adjusted automatically. You can get it with CSS by setting % values to column width, but this is hardcoding and isn't acceptable in real life, and won't work with dynamic set of columns and show/hide functionality.

**Comment by envyN** [comment]
@reddolan @mathisscott any updates ? been quite some time now and this feature (not being there) could be the deal breaker for many.

**Comment by mathisscott** [comment]
Hi @envyN 
Thanks for contacting us! I think @youdz has more info on this feature request. But I'm also interested in getting a better understanding of what problem this feature is trying to solve?

**Comment by youdz** [comment]
We still haven't started design work on that, and it is not one of our highest priority tasks at the moment.

In addition to this, we are still waiting to hear about why this feature is considered a blocker by some of you, and what the problem you are trying to address with this feature is. We do not want to research and offer a solution that doesn't actually solve your use case.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
