### ISSUE TITLE
CdsDropdown throws an exception in jsdom

### ISSUE THREAD

**Issue by ashleyryan** [vmware/clarity#6764]
## Describe the bug

When rendering `CdsDropdown` in a react-testing-library test, it throws an exception: `[TypeError: Cannot read property 'disconnect' of undefined]`

## How to reproduce

https://github.com/vmware-clarity/starters/compare/main...ashleyryan:rtl-cdsdropdown

- `cd create-react-app`
- `yarn install`
- `yarn test`

You'll see the failure

## Expected behavior

The test should pass

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [ ] v5.x
- [x] v6.x

**Framework:**

- [ ] Angular
- [x] React
- [ ] Vue
- [ ] Other:

## Additional notes

The stack trace indicates this line is the issue: https://github.com/vmware/clarity/blob/4006bea6dfe7b31a4708cc656dc628aad47562fa/packages/core/src/internal/controllers/first-focus.controller.ts#L33

MutationObserver is implemented in jsdom,  but they might do something weird, which may have something to do with it.

**Comment by mathisscott** [comment]
good catch. that should be easy to fix by changing the line to...

`this.observer?.disconnect();`

Apparently, `listenForAttributeChange()` can return `undefined` in some environments. 🤔

**Comment by ashleyryan** [comment]
> Apparently, listenForAttributeChange() can return undefined in some environments. 🤔

I saw that as well, which doesn't make sense, unless `listenForAttributeChange` is somehow never called in jsdom. I'm hoping I can repro it in my jsdom environment that I used for cds-select.

That should be an easy fix, but the type isn't nullable, so it's going to be weird to add the `?`
