### ISSUE TITLE
Possible missing @clr/core 4.0.16? 

### ISSUE THREAD

**Issue by ebauman** [vmware/clarity#6767]
[Not a code bug, but maybe a workflow one?]

I noticed on npm there is no v4.0.16 of @clr/core. There IS v4.0.16 of @clr/angular, @clr/ui, etc. The latest available version for core is v4.0.15. 

Is this intentional? My assumption was that (until v5 when CDS came into the picture) that all @clr/ tagged things received a simultaneous version bump. 

Anywho, just looking for some guidance on how to properly update to latest in v4 train. Thanks all!

**Comment by ashleyryan** [comment]
Hello, this repository has been archived. If your issue still exists, please recreate the issue in one of the new repositories:

- [Clarity Core](https://github.com/vmware-clarity/core)
- [Clarity Angular](https://github.com/vmware-clarity/ng-clarity)
