### ISSUE TITLE
Datagrid action overflow is clipped with 4 more action items.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#679]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```
Related issue vmware/harbor#1899

### Environment details

* **Angular version:** 2.4.10

* **Clarity version:** 0.8.7

* **OS and version:** 10.12

* **Browser:** [all]

**Comment by youdz** [comment]
This should have been fixed in `0.8.13`, so upgrading to the latest version should fix this issue. 👍

**Comment by wknet123** [comment]
Thanks, I'll have a try on it.
