### ISSUE TITLE
Homepage should have a link to the sketch template when mentioning it

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#68]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Actual behavior
Currently, we mention the sketch template on the homepage but do not provide a link to it, this might be confusing to some users based on discussion here: https://news.ycombinator.com/item?id=12965381. We should provide a link to the sketch template when appropriate, even on the homepage.

**Comment by jaffoneh** [comment]
@yenmade could you provide some more input here? Do we want the "big card" on the homepage to link each of its four aspects to the documentation to make it easier to find those assets/docs?

**Comment by yenmade** [comment]
Proposed enhancements to the website:
1. Home page
   * Main card - change text from "Sketch UI Kit" to "Sketch template" (this should be applied anywhere we mention "UI kit")
   * Link "Sketch template" in body to download the template (https://vmware.github.io/clarity/images/sketchTemplates/Clarity-Template-0.6.0.sketch)
<img width="1377" src="https://cloud.githubusercontent.com/assets/22527471/20539607/791bf4d8-b0aa-11e6-8f17-a072f808e784.png">

2. Get Started (https://vmware.github.io/clarity/get-started/index.html#sketchTemplate) - replace blurb with: <p>Jumpstart your project with the Clarity Sketch template, a library of components versioned alongside other products in Clarity’s ecosystem. To use with the template, install the open-source Metropolis font by Chris M. Simpson.  Clarity uses these font weights:  light, regular, semibold, and medium.</p>
3. Documentation (https://vmware.github.io/clarity/documentation/)
   * Remove "Sketch Templates" link in sidenav
