### ISSUE TITLE
The tooltip is fixed after clicking the tooltip bound element

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#681]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The popup tooltip should disappear when another tooltip appear or pointer has left the tooltip bound element.

### Actual behavior

The tooltip will be fixed after clicking the tooltip bound element.

### Reproduction of behavior

Click the tooltip bound element.

### Environment details

* **Angular version:** 
2.4.2

* **Clarity version:** 
0.8.7
* **OS and version:** 
Mac/Ubuntu
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by Jinnie** [comment]
As a user I would rather consider this as a feature. But it could be valuable if I could copy the tooltip text, which is not possible with the current implementation.
Any UX comment, Clarity Team?

**Comment by steven-zou** [comment]
Sometimes the issue may cause confusions.
<img width="331" alt="2017-04-06 6 30 27" src="https://cloud.githubusercontent.com/assets/5753287/24749845/2f9838aa-1af7-11e7-94a1-823614cf14f7.png">

**Comment by Jinnie** [comment]
I totally agree that there should be only one fixed.

**Comment by jeeyun** [comment]
hi @steven-zou we just released a tooltip angular component in 0.8.13. Try it and let us know if you still experience the same issue.

**Comment by steven-zou** [comment]
Upgrade to 0.8.15, issue is fixed. Close this issue now.
