### ISSUE TITLE
Combine Icon & Text in header-nav 

### ISSUE THREAD

**Issue by dbratsun** [vmware/clarity#682]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[X] enhancement
```
How to correct make the nav-link section with icon and text together?

**Comment by jaffoneh** [comment]
@dbratsun one of our design recommendations is to not combine icons and links in nav-link in the header. More information is available there: https://vmware.github.io/clarity/documentation/header#top. Let me us know if you have specific use cases where this might need to change and provide some more detailed design info as well as a plnkr of what you tried if possible. Thanks.
