### ISSUE TITLE
Enabling clr-dg-row for parameter disable 

### ISSUE THREAD

**Issue by anilsil** [vmware/clarity#685]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
'clr-dg-row' should be disabled if [disabled]="basedUponSomeCondition" used.

### Actual behavior
It throws error - "Can't bind to 'disabled' since it isn't a known property of 'clr-dg-row'"

### Reproduction of behavior
 <clr-dg-row *clrDgItems="let cluster of clustersArray" [clrDgItem]="cluster" (click)="setCluster(cluster)" [disabled]="someCondition"> 

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 
8.13
* **OS and version:** 
Mac 10.12.3 (

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome

**Comment by youdz** [comment]
What does "disabling" a row do? They are not actionable elements, they do not have a "disabled" state.

I see that you attached a click listener to it, so I'm guessing disabling would be as simple as just removing the click listener? This is all happening on the application side, though, there is nothing we can do in the library to help you with this.

**Comment by jaffoneh** [comment]
Closing based on @youdz's last comment. If there is more to this please offer additional information first and then we can discuss before we reopen if needed.
