### ISSUE TITLE
DatagridRowRenderer cell width

### ISSUE THREAD

**Issue by BugsyFTW** [vmware/clarity#686]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The cell would render normally without any issues

### Actual behavior
I have a sidenav with multiples links. that when clicked changes the Datagrid columns and cells. I do this my setting the content array to empty and filling it again with the new data.

![error](https://cloud.githubusercontent.com/assets/3944235/24764992/157fcca2-1aee-11e7-818e-93b06444c7b1.PNG)

![stricterror](https://cloud.githubusercontent.com/assets/3944235/24765060/51670f1e-1aee-11e7-87d8-97ecdfb40eb6.PNG)

### Reproduction of behavior
It's hard to reproduce the behavior, but if it's really necessary i'll waste some time on it.

### Environment details
clarity: 0.8.11

@angular/cli: 1.0.0-rc.1
node: 7.7.4
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.1
@angular/compiler-cli: 2.4.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Howdy @BugsyFTW,

In order to understand and help we need to see a minimum example that demonstrates your issue. 
Please fork the [clarity plunker](https://plnkr.co/edit/8TwwdL) to recreate your issue and add the link  here so we can take a look.

Thanks.

**Comment by jarinwhite** [comment]
Make sure the number of <clr-dg-cell> per row matches the number of columns you have defined. In my case when I've seen this error, I had an extra cell and it was presumably trying to grab the width of a column that didn't exist.

**Comment by hippee-lee** [comment]
I ran into a similar issue while working on #401.
Will hopefully fix it as part of that feature.
