### ISSUE TITLE
Not able to add custom icons using ClarityIcons.add 

### ISSUE THREAD

**Issue by tarundhillon** [vmware/clarity#689]
`ClarityIcons.add({"myLogo": '<svg version="1.1" viewBox="0 0 36 36" preserveAspectRatio="xMidYMid meet" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">		< title > zoom - out < /title>< path d="M16,4A12,12,0,1,0,28,16,12,12,0,0,0,16,4Zm0,21.91A10,10,0,1,1,26,16,10,10,0,0,1,16,25.91Z" class="clr-i-outline clr-i-outline-path-1" /><path d="M31.71,29.69l-5.17-5.17A13.68,13.68,0,0,1,25.15,26l5.15,5.15a1,1,0,0,0,1.41-1.41Z" class="clr-i-outline clr-i-outline-path-2" /><path d="M20,15H12a1,1,0,0,0,0,2h8a1,1,0,0,0,0-2Z" class="clr-i-outline clr-i-outline-path-3" /></svg>'});`

Ideally it will be good to link an external file here.

**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

<clr-icon shape="myLogo" class='is-inverse'></clr-icon>
this should display the Logo svg 
### Actual behavior

Error in the browser console 'myLogo' is not found in the Clarity Icons set.

### Reproduction of behavior

https://plnkr.co/edit/2NzkpsExVOOHBg6QYYXy?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
@tarundhillon I looked at the Plunkr and it looks like you placed your application logic in the `AppModule`, which is solely responsible for bootstrapping your application. So you would want to place it in the root component class. Also, It needs to be in a constructor or method to run.

**Comment by b-ritter** [comment]
Unfortunately, I was not able to get this solution to work with Angular 4. Here is [a fork of the Clarity seed repo](https://github.com/b-ritter/clarity-seed/commit/504b4725d035c655f8c899a5822215fa9f80bd31) with the svg used in the [documentation](https://embed.plnkr.co/MiRlaQDHIIJd3e3Hgxyj/). I am able to console.log the data from the svg immediately after adding it with the api, but in trying to access it in the template using the clr-icon directive it throws the error `'my-first-custom-icon' is not found in the Clarity Icons set`. Any help would be much appreciated!

**Comment by mathisscott** [comment]
[I made a plunkr out of the code in the fork](https://plnkr.co/edit/XKCbAD?p=preview) and it works.

**Comment by b-ritter** [comment]
Thank you @mathisscott for your quick response! The issue I am experiencing is when I run the app with the angular cli using `ng serve`. I can perhaps try to modify it to run locally with [AOT](https://angular.io/guide/aot-compiler#ahead-of-time-compilation).

**Comment by mathisscott** [comment]
@Shijir may be able to help you figure out the issue. We have clarity-icons running with both `ng serve` and AOT, iirc.

**Comment by b-ritter** [comment]
Okay, thank you. clarity-icons works wonderfully, it's just adding custom icons that is the problem.

**Comment by Shijir** [comment]
The problem you are facing could happen when you are running two instances of ClarityIcons. If you are importing and loading ClarityIcons in your typescript, make sure you are not loading it through `script` tag too.

**Comment by tarundhillon** [comment]
It works for me with on Angular4, I have approached it as follows 

1. Define a service 
`
import { Injectable } from '@angular/core';
@Injectable()
export class IconService {
    constructor){}
    
    icons : any = {
        "appLogo": '<svg viewBox="0 0 100 100"><use xlink:href="/src/icons/logo.svg#appLogo"></use></svg>',
        "appLogoWithText": '<svg viewBox="0 0 100 100"><use xlink:href="/src/icons/logo.1.svg#appLogo"></use></svg>'
    };

    public load(){        
          window['ClarityIcons'].add(this.icons);
    }

}

`

2. Call the load at an appropriate point, for it was when a component is being loaded 

`  constructor(private iconService: IconService) {
        iconService.load();`

3. in the html 
 <clr-icon [attr.shape]="appLogo" size='48'></clr-icon>

**Comment by b-ritter** [comment]
@Shijir, thank you, [I removed the line from the angular-cli.json](https://github.com/b-ritter/clarity-seed/commit/abba919082b96e19f0a47717e1aa60770cb7e735) scripts section that includes clarity-icons.js. It works! Very cool.
