### ISSUE TITLE
Feature Request: Multiple select for dropdown/select boxes

### ISSUE THREAD

**Issue by Radu-Dunarentu** [vmware/clarity#69]
### Multiple select
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
With a select box/drop-down, the users can select one or multiple items from a list of values. On the option list, every option can have a checkbox in front of it. Should be able to select/check all options and uncheck/unselect all options. This feature would be very useful on a dashboard application. 

### Example: 
http://i.stack.imgur.com/1SYwV.gif

**Comment by uNki23** [comment]
checkboxes should be optional - the selected options could be highlighted in another way (another background, bold text, ...).
to get this working, #123 would be needed, so one would be completely free to style the items (selected) template.
it's also important to distinguish between two modes:
- display selected items ("User 1, User 4, User 6") 
- display customizable selected items count ("3 users selected")

**Comment by youdz** [comment]
I believe a multi-select component was on our roadmap at some point. This is a totally valid request that we will add on our backlog.

This component seems to have dropped out of our priorities though, so I will let @jaffoneh answer with more details when he comes back next week.

Also, before we can start implementing, this new component will need to go through our UX team for evaluation and a first draft, so I'm labelling this as such.

**Comment by jaffoneh** [comment]
Work on this has started as part of the enhanced autocomplete/select work. cc @reddolan

**Comment by jaffoneh** [comment]
I am closing this as a duplicate considering the work will be completed as part of the larger "autocomplete" ticket (Issue #90). Thanks for posting this issue.

**Comment by reddolan** [comment]
We have merged your request into #248. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you
