### ISSUE TITLE
datagrid issue: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by laurentsd** [vmware/clarity#690]
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No error

### Actual behavior
Console error:
TypeError: Cannot read property 'destroy' of undefined at http://localhost:4201/vendor.bundle.js:51064:31 at SafeSubscriber.schedulerFn [as _next] (http://localhost:4201/vendor.bundle.js:44897:36) at SafeSubscriber.__tryOrUnsub (http://localhost:4201/vendor.bundle.js:569:16) at SafeSubscriber.next (http://localhost:4201/vendor.bundle.js:518:22) at Subscriber._next (http://localhost:4201/vendor.bundle.js:471:26) at Subscriber.next (http://localhost:4201/vendor.bundle.js:435:18) at EventEmitter.Subject.next (http://localhost:4201/vendor.bundle.js:3467:25) at EventEmitter.emit (http://localhost:4201/vendor.bundle.js:44871:76) at QueryList.notifyOnChanges (http://localhost:4201/vendor.bundle.js:90682:71) at CompiledTemplate.proxyViewClass.View_DatagridActionOverflow0.detectChangesInternal (/ClarityModule/DatagridActionOverflow/component.ngfactory.js:101:28) at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4201/vendor.bundle.js:91287:14) at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4201/vendor.bundle.js:91482:44) at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4201/vendor.bundle.js:91272:18) at View_MainComponent3.detectChangesInternal (/AppModule/MainComponent/component.ngfactory.js:305:19) at View_MainComponent3.AppView.detectChanges (http://localhost:4201/vendor.bundle.js:91287:14)
message
:
"Cannot read property 'destroy' of undefined"
stack
:
"TypeError: Cannot read property 'destroy' of undefined↵    at http://localhost:4201/vendor.bundle.js:51064:31↵    at SafeSubscriber.schedulerFn [as _next] (http://localhost:4201/vendor.bundle.js:44897:36)↵    at SafeSubscriber.__tryOrUnsub (http://localhost:4201/vendor.bundle.js:569:16)↵    at SafeSubscriber.next (http://localhost:4201/vendor.bundle.js:518:22)↵    at Subscriber._next (http://localhost:4201/vendor.bundle.js:471:26)↵    at Subscriber.next (http://localhost:4201/vendor.bundle.js:435:18)↵    at EventEmitter.Subject.next (http://localhost:4201/vendor.bundle.js:3467:25)↵    at EventEmitter.emit (http://localhost:4201/vendor.bundle.js:44871:76)↵    at QueryList.notifyOnChanges (http://localhost:4201/vendor.bundle.js:90682:71)↵    at CompiledTemplate.proxyViewClass.View_DatagridActionOverflow0.detectChangesInternal (/ClarityModule/DatagridActionOverflow/component.ngfactory.js:101:28)↵    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4201/vendor.bundle.js:91287:14)↵    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4201/vendor.bundle.js:91482:44)↵    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4201/vendor.bundle.js:91272:18)↵    at View_MainComponent3.detectChangesInternal (/AppModule/MainComponent/component.ngfactory.js:305:19)↵    at View_MainComponent3.AppView.detectChanges (http://localhost:4201/vendor.bundle.js:91287:14)"

### Reproduction of behavior
I already showed that bug to Eudes :-)   
1) Open a datagrid with pagination and action menu on the row
2) Open the action menu
3) Click to another grid page (without closing the action menu)
4) Click again the action menu and see the console error

### Environment details

* **Angular version:** 2.4.6

* **Clarity version:**  0.8.11

* **OS and version:** Mac OS 10.10.3

* **Browser:** [all]

**Comment by Shijir** [comment]
Closing this issue as the reported bug has been no longer reproducible in Clarity v0.9.1 and v0.8.16.
The following demo is running 0.8.16: https://plnkr.co/edit/TOakzh60uU6ZRnRxbN4c?p=preview.
