### ISSUE TITLE
[Angular] Button group click event doesn't tell what child button is clicked. Child buttons also not responding to their own click event

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#691]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Can't determine what button is clicked.

### Actual behavior
Should be able to determine what button is clicked in a button group.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by hippee-lee** [comment]
Hi @whizkidwwe1217 

Can you submit a [https://plnkr.co/edit/8TwwdL?p=info](plunker) with an example of your usage so we can investigate?

**Comment by whizkidwwe1217** [comment]
Hi,
There's nothing special about the code. Just wire a simple click event to a
button group or to a child button in a button group. Here's my sample code:

app.component.html

**
<clr-button-group class="btn-primary" *(click)="groupClicked($event)"*>
  <clr-button id="btnCreate">Create</clr-button>
  <clr-button id="btnFavorite">Favorite</clr-button>
</clr-button-group>
**
<clr-button-group class="btn-primary">
  <clr-button id="btnCreate2"
*(click)="childClicked($event)"*>Create</clr-button>
  <clr-button id="btnFavorite2">Favorite</clr-button>
</clr-button-group>

app.component.ts

groupClicked(e) {
  // How can I get the button that was clicked?
  console.log(e);
}

childClicked(e) {
  console.log(e);
}

**Comment by whizkidwwe1217** [comment]
Hi,
There's nothing special about the code. Just wire a simple click event to a button group or to a child button in a button group. Here's my sample code:

**app.component.html**
```
<!-- Sample button group with click event. THIS WORKS BUT CANT TELL WHAT BUTTON WAS CLICKED -->
<clr-button-group class="btn-primary" (click)="groupClicked($event)">
  <clr-button id="btnCreate">Create</clr-button>
  <clr-button id="btnFavorite">Favorite</clr-button>
</clr-button-group>

<!-- Sample button group with child button click event. THIS DOES NOT WORK -->
<clr-button-group class="btn-primary">
  <clr-button id="btnCreate2" (click)="childClicked($event)">Create</clr-button>
  <clr-button id="btnFavorite2">Favorite</clr-button>
</clr-button-group>
```
**app.component.ts**
```
groupClicked(e) {
  // How can I get the button that was clicked?
  console.log(e);
}

childClicked(e) {
  console.log(e);
}
```

**Comment by adityarb88** [comment]
Thanks for raising this issue @whizkidwwe1217. We are working on a fix for this.

**Comment by adityarb88** [comment]
Hi @whizkidwwe1217. Thanks for raising this issue. We are planning to fix the child button click events but we are not planning to add a click event which notifies which button was clicked on the button group component itself.
