### ISSUE TITLE
Built as AOT failed.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#693]
**Error at**  `/aot/node_modules/clarity-angular/datagrid/datagrid-pagination.ngfactory.ts:657:45: Property 'page' is private and only accessible within class 'DatagridPagination'.`
```
[x] bug
[ ] feature request
[ ] enhancement
```
### Actual behavior

Built as AOT failed since the component does not meet AOT compilation specification.
### Environment details

* **Angular version:** 2.4.10

* **Clarity version:** 0.8.7

* **OS and version:** macOS, Ubuntu 16.04.2

* **Browser:** [all | Chrome XX | Firefox XX ]

**Comment by Shijir** [comment]
Hi @wknet123, the fix to this issue has been introduced in v0.8.9. So please upgrade to v0.8.9 or later versions to get the fix.
