### ISSUE TITLE
Broken bottom-right class in drop down

### ISSUE THREAD

**Issue by konsultaner** [vmware/clarity#694]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
the class bottom-right should cause the drop down to align bottom right.

### Actual behavior / reproduce
the class bottom-right does not cause the drop down to align bottom right. This is a bug can be viewed on the [clarity website](https://vmware.github.io/clarity/documentation/header#types)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.8.14

* **OS and version:** Win10

* **Browser:** Chrome 57.0.2987.133 (64-bit)

**Comment by shadowkrusha** [comment]
Was just trying to track this down on my app.

bottom-left not working either.

**Comment by TechRazor** [comment]
This weekend I ran into the same thing but found the answer in the dropdowns docs (https://vmware.github.io/clarity/documentation/dropdowns)

Change your dropdown to use the Clarity angular dropdown component instead of the HTML ones and it will work properly.

**Comment by jeeyun** [comment]
@konsultaner @shadowkrusha thank you for bringing this to our attention.

Just investigated this and parts of our website doc is not up to date. We have had an input called `clrMenuPosition` in the angular dropdown component for a while, but it used to work just fine even if you put css classes directly on the the `<clr-dropdown>` element to position it (thought this wasn't the intended design). 

This breaks for the angular dropdown component starting 0.8.13. Now our component relies on the `clrMenuPosition` input value to smartly position it, so the angular dropdown must provide this input value for positioning (it defaults to `bottom-left` if unspecified).

I've created a PR to update our documentation (https://github.com/vmware/clarity/pull/695) to show correct examples of using the dropdown component.

Let me know if using the `clrMenuPosition` input doesn't resolve your issue, and I'd be happy to take another look.

**Comment by konsultaner** [comment]
@jeeyun I used it like this and it worked as expected, thank you!

    <clr-dropdown clrMenuPosition="bottom-right">
    ...
    </clr-dropdown>
