### ISSUE TITLE
datagrid-column overlapping if the grid width is not enough

### ISSUE THREAD

**Issue by ghvm2014** [vmware/clarity#703]
**Select one ...**  (check one with "x")
```
[* ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The column width and grid width should be automatically computed and should not overlapped.
(0.8.13)
if the width of gird is  not enough for all the columns, it should add a horizon scroll bar.
it is not a problem on the version 0.8.8.

### Actual behavior

In my env(0.8.13), the page width is about 500px. 
However, i have 8 columns, the second column was displayed by overlapping the first column.

### Environment details

* **Angular version:** 2.0.X
2.0.x
* **Clarity version:** 
0.8.13
* **OS and version:** 
win10
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
Please post a plunker reproducing this in 0.8.13, because our internal demo components properly show a horizontal scrollbar.

**Comment by ghvm2014** [comment]
![overlapping](https://cloud.githubusercontent.com/assets/7811184/24996655/39be6948-2066-11e7-94c1-3a1a84c1d8b3.png)

**Comment by ghvm2014** [comment]
the above grid is included in one page of wizard.
By the way, could we set the height of grid to 90%--100% of the step page's height.

**Comment by youdz** [comment]
Regarding the column wrapping, please post a plunker. A screenshot is not enough for us to investigate. I tried quickly with our setup, and the columns never overlap, when there really isn't enough room the datagrid just starts scrolling horizontally. If we can't reproduce it, we can't debug it.

Regarding the grid height, it's as simple as setting the `height` style on your datagrid element. You can even do it in your CSS. We will not do it ourselves, because datagrids in wizards are not necessarily the only element on the step's page. There can be text paragraphs, forms, or pretty much anything around it.

**Comment by ghvm2014** [comment]
Hi youdz
I have found a work round to  solve this issue. But i still think it is a bug.
Reason:
we have a wizard that includes 13 steps.
In step 2, we defined a datagrid and defined a datalist variable in ts file:
step2 do not have problems.
<clr-dg-row *clrDgItems="let cluster of oplist" [clrDgItem]="cluster">
ts file
let oplist: Cluster[] = [];
 
But in step 5, we have  reused the same grid and datalist variable.
<clr-dg-row *clrDgItems="let cluster of oplist" [clrDgItem]="cluster">
Now the column of datagrid in the step5 page are overlapping.......

my solution:
we defined a new variable in ts file
let oplist_step5: Cluster[] = CloneList.toList(this.oplist);
<clr-dg-row *clrDgItems="let cluster of oplist_step5" [clrDgItem]="cluster">
Now the overlapping problem are gone....

Why can we reuse the same array variable in different step pages for datagrid component?
In my solution, i have to defined a new array variable which have the same values with the first one.
(From the sources raw html in the browser, i noticed that the overlapping datagrid-cell's style was set
as the following: style="{width:0px}"
But the normal datagrid -cell always have a fixed number not zero.
you  know that the component auto generated and inserted this style, i do not set any style here.)

**Comment by youdz** [comment]
Hi @ghvm2014,  please post a plunker reproducing this behavior if you want us to investigate.

**Comment by samdidos** [comment]
It's an issue for me too.

Here's a [Plunker](https://plnkr.co/edit/2FBKsjVnIje5V3NI9NVq).
If you stretch the window enough to let the form group elements in the same line, you'll see that the title overlap itself in one line.

I've seen a TODO in the code at this effect (in the compiled node module at clarity-ui/src/forms/_forms.clarity.scss)t, but I'm not enough skilled in Sass to propose a solution and I don't find it in your source code.

**Comment by youdz** [comment]
@samdidos: Your plunker is not related to the original issue, this one is about Datagrid columns.

I do see the bug for forms in you plunker, but could you open a separate issue for it? Thank you.

**Comment by samdidos** [comment]
Ah yeah, sorry about that @youdz . It's pretty similar though, hope this related issue will help finding the bug.

I've created the issue #828, thank you.
