### ISSUE TITLE
datagrid checkbox-column is not shown if the [(clrDgSelected)] model  is undefined before the component initiation

### ISSUE THREAD

**Issue by ghvm2014** [vmware/clarity#704]
**Select one ...**  (check one with "x")
```
*[ ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

1. when i defined a datagrid with [(clrDgSelected)]="userSelectedLists".
2. if we define a variable " userSelectedLists" in typescript file but not init it with value.
   class component{
   .....
  userSelectedLists: any[];
   ''''
   }
3. then i will reinit this variable in the page load function (clrWizardPageOnLoad).
4. The checkbox column should be displayed.

workround:
class component{
   .....
  userSelectedLists: any[] = [];
   ''''
   }
Give it  a value when  creating the component.

### Actual behavior

1. when i defined a datagrid with [(clrDgSelected)]="userSelectedLists".
2. if we define a variable " userSelectedLists" in typescript file but not init it with value.
   class component{
   .....
  userSelectedLists: any[]
   ''''
   }
3. then i will init this variable in the page load function (clrWizardPageOnLoad).
4. The checkbox column is not displayed.
### Environment details

* **Angular version:** 2.0.X
2.0.x
* **Clarity version:** 
0.8.13
* **OS and version:** 
win10
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
This is actually anted behavior. We need an empty list anyway, so if we accept `undefined`, we'd have to emit the new `[]` value on initialization, which would result in the famous "Expression has changed after it was checked" error.

So the workaround you show is actually what we recommend doing. In your case, start with `userSelectedLists: any[] = []` in your component declaration, and either replace the list with the new one on `clrWizardPageOnLoad`, or populate the existing list in place. Either will work.

Is there any specific reason for you not wanting to declare the empty selection at the beginning?

**Comment by youdz** [comment]
We can't investigate unless you post a reproduction of your issue on StackBlitz, but it looks like you are initializing `[(clrDgSelected)]` on the datagrid with an empty array and `[(clrDgSelected)]="userGroup.selected"` to various values on the rows themselves. The selection can't both be empty *and* some rows, so the two input values you're giving are incompatible. As such, we emit an output which synchronizes them, and this triggers the ExpressionChangedAfterItHasBeenCheckedError in Angular.

If you want to discuss all this, please ask the question on [StackOverflow](https://stackoverflow.com/questions/tagged/vmware-clarity) with the `vmware-clarity` tag, and we'll answer it in more detail. We try not to encourage questions on GitHub, just bug reports and feature requests.

**Comment by tarquinrex** [comment]
Thanks for the tip - when I keep the array of selected items in sync then the error goes away. :)
