### ISSUE TITLE
Does Clarity have a concrete version list of browsers supporting?

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#705]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
There should be a version list of supporting browsers for Clarity UI.

### Actual behavior
Just show the supporting browsers list in the home page.
Met several issues related with browser versions.

**Comment by mathisscott** [comment]
List of browser support is here: https://vmware.github.io/clarity/get-started#browserSupport

We typically support the last two versions of the browsers listed.

**Comment by jaffoneh** [comment]
@steven-zou if you've seen issues with browsers that meet our supported list (last two versions of every browser - chrome, firefox, safari, and Edge - as well as IE 10 and 11, please report them as issues here in GitHub so we can take a look!
