### ISSUE TITLE
Datagrid filter "jumps" down when it changed in Server-driven mode

### ISSUE THREAD

**Issue by savelievser** [vmware/clarity#706]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Filter stays on it's place.

### Actual behavior
Filter jumps to the bottom of the grid while data is loading and returns back when loading is over.

### Reproduction of behavior
Clarity's own documentation page exhibits this behavior.
https://vmware.github.io/clarity/documentation/datagrid
1. Scroll to Server-driven grid
2. Open any filter and start typing

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** latest Chrome

**Comment by jeeyun** [comment]
This should be fixed by #710.
