### ISSUE TITLE
[DOCS] Add contributor to the website

### ISSUE THREAD

**Issue by adityarb88** [vmware/clarity#707]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ ] enhancement
```

Add Victor Mejia to the website as a contributor.

Corresponding PR: https://github.com/vmware/clarity/pull/688

**Comment by mathisscott** [comment]
@victormejia added with 0.9.0 push.

**Comment by victormejia** [comment]
thanks @mathisscott ! 😃
