### ISSUE TITLE
Clarity website Iconography: Two hex numbers are incorrect

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#709]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Clarity website > Iconography > Design Guidelines
The Predefined color classes table shows a couple incorrect hex #s:

![image](https://cloud.githubusercontent.com/assets/23196444/24973777/ef1eebd4-1f74-11e7-974f-37f637ca1c1a.png)

Hex numbers should be updated to match the icons in the right column.

**Comment by mathisscott** [comment]
I'll fix this for tomorrow's release...

**Comment by mathisscott** [comment]
Done. Completed with 0.9.0 push.
