### ISSUE TITLE
Support Momentum Scrolling on .main-container

### ISSUE THREAD

**Issue by JohannesRudolph** [vmware/clarity#71]
**Select one ...**  (check one with "x")
```
[x] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
The main container should support momentum scrolling on iOS devices. 

### Actual behavior
The main container does not scroll nicely on iOS devices (tested with iPad on iOS 9). 

### Reproduction of behavior
E.g. the clarity docs site: 

Adding this css fixes the issue: 
```
.main-container {
  /* has to be scroll, not auto */
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch;
}
```

### Environment details

* **Angular version:** 2.2.X

* **Clarity version:** 0.7

* **OS and version:** 

* **Browser:** [iOS 9/10 Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
Quick question.

This works fine on iPhone 6 and iPhone 5. We are applying `-webkit-overflow-scrolling: touch;` responsively.

So I am wondering if you're using iPad in portrait or landscape mode? Maybe there is an issue with the breakpoint?

Thanks.

**Comment by JohannesRudolph** [comment]
Thanks for the quick response @mathisscott, using iPad in Landscape mode os it's above the breakpoint. Momentum scrolling should work regardless of breakpoint. You can also reproduce this in Safari Mobile using Xcode's iOS Device Simulator.

**Comment by mathisscott** [comment]
Yup. I've reproduced some bad issues with an iPad in landscape mode. Thanks for bringing them to our attention. In portrait mode, the site appears to do fine. But we need to fix a bunch of issues with landscape mode, mostly around responsive breakpoints.

Thanks for pointing this out, @JohannesRudolph.
