### ISSUE TITLE
Validation on inputs with type="number"

### ISSUE THREAD

**Issue by tihomir-varbanov** [vmware/clarity#713]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Up/Down buttons in input[type="number"] should appear at the end of the input field.

### Actual behavior
When I enable validation for the numeric text input and when I use the **.valid** class to style the input, the Up/Down buttons do not look properly aligned - they do not appear at the end of the text input.

The same issues can be observed with normal validated inputs in IE. There is a "x" button in normal text inputs in IE that appears misaligned when Clarity validation styling is added to it.

### Reproduction of behavior
https://plnkr.co/1ND8cK

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.14

* **OS and version:** Windows 8.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@reddolan : This should probably be added to the broader research into form validation ala #45 and #46.

**Comment by reddolan** [comment]
@tihomir-varbanov  Looking at the CSS for the element, I see a padding-right:28px applied which would push the stepper over from the far right side. This is to create space for the error icon in case of an error and to not cause collision/overlap issues. 

@mathisscott noted, will add to the collection. Is it possible to have the padding only be applied when there is an error? Maybe by adding a class when an error is present?

**Comment by mathisscott** [comment]
@reddolan : Yeah, I think we could tie the right padding to the CSS that shows the error icon...

**Comment by reddolan** [comment]
Here is the recommended design for validation on a input type="number"

![input-type-number](https://cloud.githubusercontent.com/assets/1858226/25927310/fc133c5a-35a9-11e7-9c0f-21b9e26fefdd.png)

**Comment by gnomeontherun** [comment]
This is different now that validation design has changed for new forms and this will no longer be an issue.
