### ISSUE TITLE
Modal Dialog box not displayed

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#716]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Modal dialog box should open when button is clicked

### Actual behavior
Modal does not open and the following error is shown in the web console: 

ERROR Error: Found the synthetic listener @fadeDown.done. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

### Reproduction of behavior
https://plnkr.co/edit/7vrkfrG683q4mXGNfIhW?p=preview

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**   0.8.14

* **OS and version:**  Windows 7

* **Browser:** [all | Chrome 57| Firefox 52| IE 11| Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by beaker1977** [comment]
Correction: My Angular version is 4.0.0

**Comment by mathisscott** [comment]
Hi @beaker1977 
Clarity 0.8 and earlier is on Angular 2.x. To use Angular 4, you will need Clarity 0.9 and above -- which we are in the process of releasing.
