### ISSUE TITLE
Expandable rows are throwing errors in Microsoft Edge and IE browsers.

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#718]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Actual behavior

Datagrid's expandable rows are throwing errors in Microsoft Edge, IE11 and IE 10.

Rendered view:

<img width="1271" alt="screenshot 2017-04-13 14 03 11" src="https://cloud.githubusercontent.com/assets/3958008/25024568/4616a736-2053-11e7-8cac-a0839b2b15a2.png">

Errors thrown:

<img width="472" alt="screenshot 2017-04-13 14 06 42" src="https://cloud.githubusercontent.com/assets/3958008/25024569/461c8912-2053-11e7-98d9-0e290f2b21f5.png">

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8.15

* **OS and version:** Windows

* **Browser:** [ IE XX ]

**Comment by mathisscott** [comment]
@youdz ^

**Comment by mathisscott** [comment]
Also needs to be backported to 0.8.16
