### ISSUE TITLE
Alternating table/datagrid row colors

### ISSUE THREAD

**Issue by beaker1977** [vmware/clarity#719]
**Select one ...**  (check one with "x")
```
[ ] bug
[ X] feature request
[ ] enhancement
```

### Expected behavior
Rows in either Tables or Datagrids alternate in colors. Helps to differentiate the rows visually. I'd also like to see a slightly darker shade in table header to offset it from the rows. See screen mockup for alternating row colors look.

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

![image](https://cloud.githubusercontent.com/assets/27329476/25025810/966d7034-2058-11e7-90be-8094c797fa50.png)

**Comment by mathisscott** [comment]
Thanks for the suggestion, @beaker1977. I will forward this to our UX team for consideration.

**Comment by reddolan** [comment]
We won't be creating this feature. The row lines act as visual separators and are sufficient for the visibility of differentiating data.
