### ISSUE TITLE
[WEB] weird indentation happening with top line of code examples

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#720]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```
With the NG4 update we are seeing some odd indentation with the first line of code examples on the website. It is probably unwanted whitespace.

**Comment by Jinnie** [comment]
Can this be related to the recent issue of Modal backdrop not covering the beginning of the page?
https://github.com/vmware/clarity/issues/739

I wasn't able to reproduce it myself, though...

**Comment by mathisscott** [comment]
I don't think this is related to #739, @Jinnie . The reason I say this is that #739 only appears to be happening in Firefox. This indentation is happening in all browsers.

We are thinking it is related to the code minification in the website.

**Comment by mathisscott** [comment]
The fix for this was pushed with https://github.com/vmware/clarity/commit/3407cdd92fde708875435b99c5cb35edad7ecc53

It should be fixed when the website is next deployed.
