### ISSUE TITLE
Animations do not work in Safari

### ISSUE THREAD

**Issue by estrode** [vmware/clarity#724]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Animations such as the modal fade should work in Safari.

### Actual behavior
The modal displays without any animation.

### Reproduction of behavior
https://plnkr.co/edit/uNwwZe?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.0

* **OS and version:** macOS 10.12

* **Browser:** [Safari 10.1 ]

**Comment by youdz** [comment]
I think you might just be missing the polyfill. I recommend looking at the [Animations docs](https://angular.io/docs/ts/latest/guide/animations.html) for Angular, they have a note at the very top explaining that you need the `web-animations` polyfill for them to work on all browsers.

**Comment by estrode** [comment]
Yes, that was the issue!
