### ISSUE TITLE
Datagrid page-backwards button jumps around

### ISSUE THREAD

**Issue by ramonaisonline** [vmware/clarity#726]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When looking through a datagrid, it is easy to focus on the data and repeatedly click the "next page" (the right chevron > button) without looking / paying attention to it. I would expect paging backwards to work the same, where the "previous page" (the left chevron < button) stays in the same place so I can just focus on reading the information in the grid.

### Actual behavior

The "previous page" button does not stay in a consistent place due to the changing number of elements between the previous / next buttons. 
![screen shot 2017-04-14 at 2 29 48 pm](https://cloud.githubusercontent.com/assets/27519395/25056610/dfc8fab6-211e-11e7-983a-1cd0cd2cfd14.png)

### Reproduction of behavior

This is visible in any of the paginated datagrid examples (e.g. the last example) on the datagrid page
https://vmware.github.io/clarity/documentation/datagrid

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
This is actually one of the issues that was raised when we first implemented the Datagrid design. We completely forgot about it, thanks for filing this issue.

**Comment by reddolan** [comment]
Acknowledged. Ramona and I talked about this offline and I asked her to submit the issue. I will take a look at this and give recommendations on what would be a better interaction.

**Comment by mathisscott** [comment]
@reddolan : Any recommendation here?

**Comment by reddolan** [comment]
One of two things needs to happen here
1. address the navigation jiggle with the current design or
2. redesign the pagination control

I recommend we consider the second one to address some other spacing and interaction issues that have come up.

**Comment by mathisscott** [comment]
I agree on that @reddolan

**Comment by reddolan** [comment]
Going to close this one as it will get fixed when we work on #1384
