### ISSUE TITLE
Header drop down is cropped.

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#729]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Header should display the whole drop down box.

### Actual behavior
The header drop down is cropped.

### Reproduction of behavior
Code just copied from the documentation. Please see screenshot.

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.0

* **OS and version:** Windows 10 Pro

* **Browser:** [all | Chrome XX
![screenshot 2 _li](https://cloud.githubusercontent.com/assets/1977391/25062988/0ad8b09c-220b-11e7-8d8a-6f0162c50fcb.jpg)
 ]

**Comment by adityarb88** [comment]
@whizkidwwe1217: It looks like the screen is clipping the dropdown. We recommend that you use the `bottom-right` direction. We have listed the same example on our documentation:

![image](https://cloud.githubusercontent.com/assets/1426805/25064487/da2c751a-21af-11e7-8d79-b9ed6626ce5c.png)

Which example on the documentation did you use? If there is any demo on the website which is not following this example, we will have to fix it. Please let me know.

**Comment by whizkidwwe1217** [comment]
Hi,

It's now fixed. I was using an outdated code so the dropdown was clipped.

Thanks!
