### ISSUE TITLE
[New Wizard] Need clrWizardStepIsSkipped option

### ISSUE THREAD

**Issue by yaooluu** [vmware/clarity#731]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

According to 0.9.0 changelog, **clrWizardStepIsSkipped** has been removed in favor of *ngIf. 

My team have been using an array to declare/show/hide wizard pages dynamically during runtime. We have the below code in old wizard:

`<clr-wizard-step *ngFor="let page of pages" [clrWizardStepIsSkipped]="page.skipped">{{page.title}}</clr-wizard-step>`

The new wizard makes it impossible to do so since *ngIf cannot be used with *ngFor on the same element. Can we add this option back?

### Environment details
* **Clarity version:** 0.9.0

**Comment by mathisscott** [comment]
No. The new wizard does this automagically for you. You no longer need to use car-wizard-step. 

And the nav item on the left will go away when the page does.

**Comment by yaooluu** [comment]
Hi Scott,

Can you tell me in the code below (using new Wizard). How can I set a page to be skipped (or not) according from the value of "page.skipped"?

`
  <clr-wizard-page *ngFor="let page of pages; let i = index;">
    <template pageTitle>{{page.title}}</template>
    <template pageNavTitle>{{page.title}}</template>
    <h3>This is the page content.</h3>
  </clr-wizard-page>
`

**Comment by mathisscott** [comment]
'''
<ng-container *ngFor="let page of pages; let I=index;">
<clr-wizard-page *ngIf="page.skipped"> <ng-template pageTitle>{{page.title}}</ng-template> <ng-template pageNavTitle>{{page.title}}</ng-template> <h3>This is the page content.</h3> </clr-wizard-page>
</ng-container>
'''
