### ISSUE TITLE
Should not show the hint of the Clarity icon

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#734]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No DOM native hint shown for the Clarity icon.

### Actual behavior
Hint is displayed when hover on the icon.
<img width="152" alt="2017-04-17 10 56 14" src="https://cloud.githubusercontent.com/assets/5753287/25077450/875c354c-235c-11e7-8b62-dd57a552c913.png">

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
[Legacy - 0.8.15]

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  
<=0.8.15

* **OS and version:**  OS 10.11.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Firefox 52 | Safari 9.0

**Comment by Jinnie** [comment]
Second time this gets reported:
https://github.com/vmware/clarity/issues/678

**Comment by mathisscott** [comment]
Thanks for the reminder, @Jinnie. #678 was a broad "this happens in places" issue. This one is specific to tooltips and gives us something to move forward with.

**Comment by steven-zou** [comment]
Guys,

  Any progress?

**Comment by mathisscott** [comment]
@steven-zou 
This has been added to our backlog and is currently behind other priorities. If you give us your use case, we may be able to move it in priority. 

Since the fix is most likely to use CSS to turn pointer events off for clr-icon elements in some cases, this is also something you could probably fix as well if you need it urgently.

**Comment by victormejia** [comment]
@mathisscott let me know if you'd like me to tackle this one.

**Comment by mathisscott** [comment]
Absolutely, @victormejia . It would be greatly appreciated.

I suspect it could be as simple as using `pointer-events: none` in the CSS when a `clr-icon > svg` is inside a tooltip triggering element.

**Comment by Jinnie** [comment]
I had a plunker with this some time ago, but it seems I've lost it in a recent plunker space cleanup. 😞 
It was exactly as @mathisscott proposes, with pointer-events:none, but this also prevents any mouse interaction with the svg. So you need to have some html element as container, to be able to intercept clicks, hovers, change the pointer.

**Comment by mathisscott** [comment]
Since the `svg` element is always inside a `clr-icon` element, I don't think an html element container is a concern.

This change should also be isolated to specific instances in the code base (as with tooltips) and many of those require this change because they are already interactive in some way.
