### ISSUE TITLE
Edit documentation to add supported browser versions

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#737]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
Add text in the browser support section of getting started, we should add "Last two versions of each browser except IE".

### Actual behavior
We currently just have the browser names.

### Reproduction of behavior
https://vmware.github.io/clarity/get-started#browserSupport

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
The change for this has been pushed to the website branch. It will be resolved the next time we push the website.

https://github.com/vmware/clarity/commit/a7c343cdfbc0a336ba346944cb2e45989d999178
