### ISSUE TITLE
Checkbox alignment breaks when used in table TD

### ISSUE THREAD

**Issue by brankoleone** [vmware/clarity#743]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

The checkboxes and their labels should appear aligned vertically on the middle as on the examples when used in the table TDs.

### Actual behavior

When integrating the checkbox component into a table cell the alignment is broken.
The checkbox input and the label text are not aligned vertically.

### Reproduction of behavior

http://plnkr.co/E7b8JQ

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

http://plnkr.co/E7b8JQ

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.0

* **OS and version:** Ubuntu 16.4

* **Browser:** all

**Comment by reddolan** [comment]
Alignment would be preferable. I would also want to make sure that if a cell wraps to multiple lines that we still have alignment with the first line. Text wraps under checkboxes which will be fine
