### ISSUE TITLE
New Icons to publish Vol. 6

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#749]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### svg icons - ready for implementation Vol. 6 (1 of 2)
![image](https://cloud.githubusercontent.com/assets/23196444/25158702/5b37de18-245f-11e7-8d7a-14e71586153d.png)

### SVG icons attached:
[vol 6_1of2.zip](https://github.com/vmware/clarity/files/931450/vol.6_1of2.zip)

**Comment by Shijir** [comment]
@lil-kim they look awesome! Nice work!
