### ISSUE TITLE
Documentation site is running in Angular dev mode

### ISSUE THREAD

**Issue by benelliott** [vmware/clarity#75]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior
The documentation site at https://vmware.github.io/ is currently running in Angular 2 Development mode. This means that debug metadata is still attached to elements and slows the site down. You could improve the speed of the site significantly by adding a production setup which disables dev mode and includes AOT compilation.

### Reproduction of behavior
Open console on site to see dev mode warning message.

**Comment by mathisscott** [comment]
I no longer believe this is the case. I think this has been resolved with our AoT work and the website migration that happened along with that.
