### ISSUE TITLE
Document how to use dropdown in header-nav

### ISSUE THREAD

**Issue by JohannesRudolph** [vmware/clarity#76]
**Select one ...**  (check one with "x")
```
[x] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Documentation should include an example for how to correctly use a dropdown with a text label in the navbar.

### Actual behavior
Consider the following code: 
```
<clr-main-container>
  <clr-header>
    <div class="branding">
      <a routerLink="/home" class="nav-link">
        <span class="clr-icon clr-clarity-logo"></span>
        <span class="title">Logo</span>
      </a>
    </div>

    <div class="header-nav">
      <clr-dropdown clrMenuPosition="bottom-right">
        <a clrDropdownToggle class="nav-link" id="changeProject">
          <span class="nav-text">{{currentProject.name}}</span>
          <clr-icon shape="caret" class="icon-orient-down"></clr-icon>
        </a>
        <div class="dropdown-menu">
          <a clrDropdownItem *ngFor="let p of projects" [routerLink]="['p', p.tag]">{{p.name}}</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item disabled" href="#">All</a>
        </div>
      </clr-dropdown>
...
```

This positions the caret in the center of the nav-link like so: 
![image](https://cloud.githubusercontent.com/assets/130103/20353818/4d0aa93a-ac1c-11e6-9e29-976fcb2bbe2e.png)

I can fix this using the following hack/workaround: 
```
.dropdown .dropdown-toggle:not(.btn) clr-icon[shape="caret"] {
  right: 0;
  left: initial;
}
```
Which then looks like this
![image](https://cloud.githubusercontent.com/assets/130103/20353724/11e71708-ac1c-11e6-876a-d5e3885a5f99.png)

I'm either doing something wrong OR this is a bug in clarity. 

### Reproduction of behavior
See above

### Environment details

* **Angular version:** 2.2.X

* **Clarity version:** 0.7

* **OS and version:** OS X el Capitan

* **Browser:** [Chrome 54, others likely affected as well]

**Comment by adityarb88** [comment]
Hi @JohannesRudolph. Really appreciate your feedback. We will get this fixed this asap.

**Comment by adityarb88** [comment]
@JohannesRudolph: Our UX team does not recommend using dropdowns in the `.header-nav` section of the header. Clarity supports 3 levels of navigation. If you want to add another level of navigation to the header, we recommend you consider using the Sub Navigation or the Sidenav. We have a section on our docs which explains this in more detail: https://vmware.github.io/clarity/documentation/app-layout

You can however add a dropdown to the `.header-actions` area of the header. I will document how to add a dropdown on that section ASAP.

cc: @yenmade

**Comment by sivaah** [comment]
@adityarb88 , Using text as dropdown toggle in .header-action is not documented
https://vmware.github.io/clarity/documentation/header

```
<clr-dropdown [clrMenuPosition]="'bottom-right'" [clrCloseMenuOnItemClick]="true">
    <button class="btn btn-link" clrDropdownToggle>
        Dropdown
        <clr-icon shape="caret" class="icon-orient-down"></clr-icon>
    </button>
    <div class="dropdown-menu">
    ...
    </div>
</clr-dropdown>
```

Example shows icon as dropdown toggle in the .header-action.

Adding text as dropdown toggle looks like this
###Actual behaviour
![screen shot 2016-11-23 at 1 54 44 pm](https://cloud.githubusercontent.com/assets/6573919/20555015/ad9c67ac-b185-11e6-8fb2-055a593a2ee2.png)

###Expected behaviour
![screen shot 2016-11-23 at 1 56 17 pm](https://cloud.githubusercontent.com/assets/6573919/20555066/dee7ac7c-b185-11e6-849d-e00e49d7d1cf.png)

**Comment by adityarb88** [comment]
Hi @sivaah. Thanks for reporting this. Adding this to my TODO. Will get this resolved ASAP.
