### ISSUE TITLE
.editorconfig file

### ISSUE THREAD

**Issue by victormejia** [vmware/clarity#761]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

Would be great to have a `.editorconfig` file to maintain consistent coding styles, as there are various plugins for the popular editors to automatically format accordingly. Main rules would be indent 4 spaces.

**Comment by mathisscott** [comment]
@victormejia : I agree this would be helpful but need to take it back to the team to figure out prioritization. Thanks for the suggestion.
