### ISSUE TITLE
Datagrid: Default to DatagridPropertyComparator when [clrDgSortBy] is undefined

### ISSUE THREAD

**Issue by jarinwhite** [vmware/clarity#771]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Unable to use [clrDgSortOrder] to specify default sort on columns unless [clrDgSortBy] is also defined. In many cases it's useful to just fall back to the default comparator. Currently I have to import DatagridPropertyComparator and pass it to [clrDgSortBy] manually. If not a fallback, could we have an easier way to specify that the default comparator should be used?

### Actual behavior
Does not sort unless [clrDgSortBy] is specified

### Reproduction of behavior
https://plnkr.co/edit/wUpQqjhf1Jcpgaa5DZI5?p=preview (No clrDgSortBy, does not apply sort)

https://plnkr.co/edit/V7dytjr0PN1weaRs4SLc?p=preview (Passed DatagridPropertyComparator instance, applies sort correctly)

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.1

* **OS and version:** 

* **Browser:** Chrome 58

**Comment by youdz** [comment]
`[clrDgField]` already sets the default comparator, that's the whole point of it. You should not have to specify `[clrDgSortBy]` in addition to it.
 So I think this is actually a bug where the sort order input is processed before the field input. Thanks for raising this.
