### ISSUE TITLE
attribute interpolation does not work on shape attribute of clr-icon

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#774]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

Binding or interpolating the **shape** attribute of the **clr-icon** does not work.
Sample code:
`<clr-icon [attr.shape]="{{page.icon}}"></clr-icon>`

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@whizkidwwe1217: Works fine. Check this link: https://plnkr.co/edit/eexlZg?p=preview

Try changing your code to:
`<clr-icon [attr.shape]="page.icon"></clr-icon>`
