### ISSUE TITLE
Initial Datagrid Column width

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#775]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
hi there! Is there a way to force the column widths to a certain ratio?
Some data like name or title needs more space while some sortable attributes like number or status can do with less.

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.1

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Shijir** [comment]
@aavelyn You can set the width of the columns in percentage. For example, the width of column Name is set to 40% of the total width of the Datagrid here:

```
<clr-datagrid>
    <clr-dg-column>User ID</clr-dg-column>
    <clr-dg-column [style.width.%]="40">Name</clr-dg-column>
    <clr-dg-column>Creation date</clr-dg-column>
    ...
</clr-datagrid>
```
