### ISSUE TITLE
Font size of button seems not consistent in different languages

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#776]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Should keep consistent size

### Actual behavior
Look a little smaller when switch languages, E.g: from 'en-US' to 'zh-CN'.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

Switch different languages.

### Environment details

* **Angular version:** 2.4.4

* **Clarity version:**  0.8.10

* **OS and version:** Mac 10.11.4

* **Browser:**  All. 
[all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
![bug1](https://cloud.githubusercontent.com/assets/5753287/25320357/e6c13fd8-28d8-11e7-9b32-00d8938fcb6c.png)
![bug2](https://cloud.githubusercontent.com/assets/5753287/25320366/024b5cf2-28d9-11e7-9209-d415d2f1df71.png)

**Comment by mathisscott** [comment]
@steven-zou 

The Metropolis font supports extended Latin and Cyrillic. It doesn't support languages beyond that. So what you are seeing is the browser's fallback.

I will ask the Clarity UX team for how they feel we should address this issue.

**Comment by reddolan** [comment]
@steven-zou when switching language to 'zh-CN' does the text become unreadable?

@mathisscott we may want to do a smoke test on changing the language to a non-Metro supported and see how it affects other components. This may be a larger challenge that needs to be addressed.

**Comment by steven-zou** [comment]
@reddolan 

  Text is still readable when switching to 'zh-CN', but seems a little smaller.

**Comment by reddolan** [comment]
@steven-zou thank you for letting us know it is still readable. We will look into different solutions to this issue and post updates as we have them.

**Comment by reddolan** [comment]
@mathisscott if we are able to provide a way for teams to increase/decrease the font-size based on language, that would be helpful.

I found a [potential solution](https://stackoverflow.com/a/15267560), but am unable to test it.
```
html:lang(en) h1{
    font-size: 20px;
}

html:lang(ko) h1{
    font-size: 10px;
}
```

**Comment by reddolan** [comment]
If that doesn't work and we don't have a recommendation of how to increase/decrease based on language, I don't know what else to suggest. If the language is still readable, which is seems it is based on @steven-zou's comment, this may have to be the way it is.

**Comment by mathisscott** [comment]
That's a good suggestion, @reddolan . We will take a look at that possible workaround when we can fit it in.

**Comment by gnomeontherun** [comment]
Looks like something we need to consider when we talk about improving fonts with Clarity, though a workaround does exist for changing the size per language.

**Comment by gnomeontherun** [comment]
Given the nature of fonts and changes, it sounds like the issues will have to be addressed on the app size by ensuring that other fonts have the same baseline sizes or adjust accordingly. 

Closing due to being stale and the solution being likely application driven.
