### ISSUE TITLE
Datagrid: Undefined [clrDgSortOrder] overrides value on previous columns

### ISSUE THREAD

**Issue by jarinwhite** [vmware/clarity#781]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Datagrid should presumably ignore `[clrDgSortOrder]` when undefined so that sorting can be conditionally applied.

### Actual behavior
If `[clrDgSortOrder]` is defined on a column and the value of `[clrDgSortOrder]` on a sequential column is falsy, the value of `[clrDgSortOrder]` on prior columns is ignored.

### Reproduction of behavior
https://plnkr.co/edit/A77ndTiWhJAfk8JWpzX0?p=preview (Sort on 'ID' is overridden by later columns even though `[clrDgSortOrder]` is undefined)

https://plnkr.co/edit/GLAXWc8kOHGQzgsogiSv?p=preview (Sorts properly on 'Age' column because it is last in line)

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.1

* **OS and version:** Windows 10

* **Browser:** Chrome 58 | Firefox 56

**Comment by mathisscott** [comment]
@Shijir : are you working on this? if so, could you assign it to yourself?
