### ISSUE TITLE
bug in datagrid selection

### ISSUE THREAD

**Issue by water42** [vmware/clarity#787]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
no errors in datagrid selection. when a datagrid is reset (not sure if that's the right term) the updatedItems is null and should not have things run on it.

### Actual behavior
in https://github.com/vmware/clarity/blob/ba2ff47795cd26933c696d2ed9da029032f6bf52/src/clarity-angular/datagrid/providers/selection.ts#L41, an error is thrown when updatedItems is null (cannot run map on null). 

### Reproduction of behavior
I'll try adding a plunker to this later. In my use case, I have two datagrids where the 2nd datagrid changes based on what data is displayed in the 1st datagrid. UpdatedItems gets set to null after the dependent datagrid changes, causing the map error. I fixed this locally by changing the line to also check if updatedItems is null. 

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.0

* **OS and version:** Windows 7, Ubuntu 16.04

* **Browser:** all

**Comment by water42** [comment]
I figured that my fix was a hack; just needed something to keep the previous functionality working after updating to 0.9.0. 

Thanks

**Comment by youdz** [comment]
Note that until we publish the fix, the cleanest solution for you is simply to make sure you use an empty array rather than `null` or `undefined` in `*clrDgItems` before you have the data. That way you don't have to modify internal code.
