### ISSUE TITLE
Add installation instruction for Clarity using angular-cli

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#79]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

In the documentation, add instruction on how to include Clarity for projects using angular-cli.

**Comment by amellnik** [comment]
I missed it the first time around, but I think [this section](https://github.com/vmware/clarity#installing-clarity-angular) of README.md covers it.

**Comment by jeeyun** [comment]
@amellnik we thought it wouldn't hurt to add more specific instructions on how to include our static assets to your application if it's built with angular-cli. Now both the README and our website documentation are updated.
