### ISSUE TITLE
Publish the Clarity Craft Library on the site

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#790]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
- have a download link to the library on the 

### Actual behavior
- no link is present for the library download

### Update content page
Original
#### Using the Clarity Sketch UI Template
Jumpstart your project with the [Clarity Sketch UI template](https://vmware.github.io/clarity/assets/images/sketchTemplates/Clarity-Template-0.9.0.sketch), a library of components versioned alongside other products in Clarity’s ecosystem. To use with the template, install the [open-source Metropolis font](https://github.com/chrismsimpson/Metropolis) by Chris M. Simpson. Clarity uses these font weights: light, regular, semibold, and medium.

Change to
#### Using Clarity Design Resources
Jumpstart your Clarity Project with one of our [Sketch](https://www.sketchapp.com/)-based design resources. Start by downloading the [Metropolis font](https://github.com/chrismsimpson/Metropolis). Then download your resource of choice.

![image](https://cloud.githubusercontent.com/assets/1858226/25458808/103aa448-2aa1-11e7-97a2-21aa31efc574.png)

link for [Craft Manager plugin](https://www.invisionapp.com/craft)

link for [Clarity.Craft.library.zip](https://github.com/vmware/clarity/files/962175/Clarity.library.zip)

**Comment by reddolan** [comment]
Added Clarity Craft Library zip. All assets for this are done

**Comment by adityarb88** [comment]
done: https://vmware.github.io/clarity/get-started#sketchTemplate :-)
