### ISSUE TITLE
Replace image icons with Clarity Icons

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#795]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

We should be using actual `clr-icon` instead of image icons in the alert components.

![screenshot 2017-04-25 17 29 57](https://cloud.githubusercontent.com/assets/3958008/25413203/6ee0cc3a-29dd-11e7-8a68-ec57010a2951.png)

### Actual behavior

Currently, we are using SVG base64 images in the places of alert icons.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by youdz** [comment]
I believe the problem here is that this will be a breaking change. By using clarity icons, we can't have them as pseudo-elements anymore, the consumer will have to manually include them. So yes, let's do it, but it's going to be a bit more involved than a simple quick fix.

**Comment by adityarb88** [comment]
Yes. actually @Shijir might have forgotten to add the milestone 0.10.0 but we discussed that we need to add a issue on github for 0.10.0 to track it. This is a breaking change.
