### ISSUE TITLE
Tree View clear selection

### ISSUE THREAD

**Issue by jabirfth** [vmware/clarity#797]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

When using a button to clear the tree view selection, the selected nodes should be unchecked on the view.

### Actual behavior

I tried to clear the tree view selection by clicking on a button (set selection = [ ]) , also i tried to loop over the selection array and set all the selected field to false; but it seems like the two way binding ( [(clrTreeSelected)]="selection" ) doesn't work as expected; Would someone take a look on my Plunker example code below.

### Reproduction of behavior

https://plnkr.co/edit/9y7IQl5BHHdyjrOWaY1T

### Environment details

* **Angular version:** 2.0.X / 4.0.1

* **Clarity version:** 0.9.0

* **OS and version:** Windows 10

* **Browser:** Chrome

**Comment by youdz** [comment]
Oh, wow, looking at the bug this is an obvious bug. I have no idea how we missed that, it's definitely something we need to fix.

Thanks for reporting it. Once the fix is in, you can expect your first solution (set `selection = []`)  to work.

**Comment by adityarb88** [comment]
@youdz: I thought we discussed that the `TreeSelection` array was only going to be used to initialize the tree. If the user wants to completely reset the selection, then they go through the root nodes and uncheck the selection using the `clrTreeNodeSelected` input.

**Comment by hippee-lee** [comment]
I have a one line change that addresses this issue. But, @adityarb88 pointed out that it reuses something that was originally intended to be used once`TreeView.populateTree(...)`. My change is pretty simple, it adds logic to it and calls it in the setter for the `@Input selected` setter. @adityarb88 had the above question wrt expecting the user to uncheck root nodes so we brought the discussion here. 

As I see it to resolve this issue I can proceed in one of three ways:

1. Add logic to the `TreeView.populateTree` function and call populateTree in the `selected` setter with the @Input value given
2. Ask the user to handle it by unchecking all the parent nodes
3. Add functionality to the service that can handle updates to the selection [] in a general way

I think 1/3 are easier for users of the TreeView and #1 is probably a bit faster to implement (its already done) than #3.

**Comment by adityarb88** [comment]
@jabirfth: We recently release 0.10.0-alpha with refactored Tree View to tackle issues raised here: https://github.com/vmware/clarity/issues/917. We won't be supporting global selection anymore because the new Tree lazy loads all child nodes. To clear selection you can now simply set the selection of root node to false. Selection has been moved to the node level in the new tree view. Please refer to the release notes for more details: https://vmware.github.io/clarity/news/0.10.0-alpha. I am closing this issue but feel free to reopen the issue if you have any more questions/feedback. Thanks!
