### ISSUE TITLE
[datagrid] In a datagrid that relies on *ngFor for iteration, filtering breaks datagrid when there are 0 results

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#804]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
If a filter results in 0 results the datagrid should display the empty results message.

### Actual behavior
Right now when filtering on a grid that uses *ngFor for iteration (since it's server based) and the result of the filter produces 0 results, the datagrid breaks with the following error: `ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.` and is not responsive afterwards.

### Reproduction of behavior
In the following plunker, try to sort or filter any column to see the bug.
https://plnkr.co/edit/OdJU4Phs7FUbckzMyQWY?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.X

* **OS and version:** macOS Sierra

* **Browser:** Chrome 57.0.2987.133 (64-bit)

**Comment by jbgarr** [comment]
Any updates here? This bug is pretty bad as it totally breaks the datagrid and the app that it's running in with the error it throws. A refresh is necessary after running into it.

**Comment by jeeyun** [comment]
@jbgarr I believe this will be fixed by: https://github.com/vmware/clarity/pull/710. The PR is being reviewed as we speak. Hoping to make it to next release.

**Comment by jbgarr** [comment]
@jeeyun unfortunately the issue is still there even after updating to the latest release (0.9.3).

**Comment by youdz** [comment]
@jbgarr: I just took a look at your plunker, you actually are using an `*ngIf` on the placeholder. That's our job, we handle when to display it or not. The fact that we're both trying to do the same thing means we hit lifecycle issues.

So the solution is simply to remove your `*ngIf` and everything works fine: https://plnkr.co/edit/OxpnSsSNNiWiiffgRpRZ?p=preview
