### ISSUE TITLE
Does datagrid support changing specific cells' data without refreshing whole dataset? 

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#807]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```
Does datagrid support changing specific cells' data without refreshing whole dataset? 

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.x

* **OS and version:** 10.12.4

* **Browser:** [all | Chrome XX | Firefox XX ]

**Comment by youdz** [comment]
I'm not sure what you mean, but since the cells are just interpolated, changing the properties of an item will correctly update the corresponding cells.
Or if you mean displaying a completely different property in a cell, you can just use `*ngIf` inside the cell.

I hope this answers your question.
