### ISSUE TITLE
Sketch Clarity Library - Radio Button and Flat buttons

### ISSUE THREAD

**Issue by bmireles** [vmware/clarity#811]
**Select one ...**  (check one with "x")
```
[ x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When I override the label for the button, the bounding box should expand to expose all the text and keep the radio button and text in place in place.

### Actual behavior
Radio button: When I resize the bounding box, the radio button shifts to the right as I am resizing.
<img width="570" alt="screen shot 2017-04-27 at 3 58 34 pm" src="https://cloud.githubusercontent.com/assets/18449355/25504149/6c00ea14-2b62-11e7-983f-8258c5675c83.png">

Flat Button: When overriding the button text and resizing the text is clipped.
<img width="310" alt="screen shot 2017-04-27 at 4 00 51 pm" src="https://cloud.githubusercontent.com/assets/18449355/25504250/cb0dd5da-2b62-11e7-955d-d9bc30b140bc.png">

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details
* **Sketch:**  43.1

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by reddolan** [comment]
Changes made and merged into #1077
