### ISSUE TITLE
[NG] Page change when filtering too much in server-driven datagrid

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#812]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

If the user is on page 4, then changes a filter in the datagrid that reduces the available items down to 2 pages, the datagrid should end up moving from the page 4 to page 2 without issues.

### Actual behavior

This currently happens by emitting 2 state changes, one when the filter is modified, then another one when the data comes back from the server and we learn that there is no 4th page.
This second event is synchronous, and typically changes the `[clrLoading]` binding of the parent app, which results in the beloved `Expression has changed after it was checked` error.

Note that this is not such a big priority, because an easy workaround for the app is simply to wrap its `this.loading = true` (or whatever handles this logic) in a timeout: `setTimeout(() => this.loading = true)`.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

_I will add a plunker soon, I just do not want to forget this._

### Environment details

* **Angular version:** 4.x

* **Clarity version:** 0.9.x

* **Browser:** all

**Comment by jbgarr** [comment]
I was actually just running into similar issues that seem related to this. Please let me know if you would rather I create a new issue.

In the situation where a user is in the middle of a large dataset, and then they filter, the data in the datagrid would basically be on the first page. I was wondering if the pager should actually be reset to reflect that in this case? Right now it seems like the page does not change at all (unless it's the case where the user was on a page that no longer exists as you've explained above).

**Comment by youdz** [comment]
I'm actually surprised, why do you assume that filtering should bring you back to the first page? I could see reasons for both cases, preserving the current page or jumping to the first. We can ask @reddolan what he thinks about this, I'm fine implementing either behavior.

Regarding the double fetch, I believe there is no way around it if we try to preserve the current page. First we need a call requesting page 42 with the new filter, because we don't know if there is still a page 42. The server responds that there is no page 42 anymore, so we need to make a new call to fetch the "new" last page. Always moving to page 1 on a filter change would solve this issue, but it has its own drawbacks.

**Comment by jbgarr** [comment]
When filtering, the user is essentially getting a new set of data. It's obviously a subset of all the data, but it has a different number of pages in most cases. If the original dataset is very large, then the filtered set could be much smaller in size (as is the case in my situation). In that case, the current page the user was on before they filtered completely loses context, so to me it makes the most sense to set the user to the beginning of the filtered data. I could see potentially if they are on the very last page before filtering to leave them on the new last page, but other than that the page number doesn't really mean anything in terms of where they "are" in the new set of filtered data.

Even if my argument doesn't make sense in all cases, if I want to manually reset the user to the first page there is a double fetch going on. I've been able to work around this, but I'm not sure why it's happening in the first place. On my side, whenever the user filters data, I'm sending the filter info as well as setting the page to 1 in my request so my server responds with the first page of the filtered data. When the filtered data is received I am passing it to my datagrid, as well as setting page number to one. What seems to happen though is that first the data is set, then the page number is set and after that a refresh event is fired so my app tries to refetch the data. Is there a way to get my updates for data AND page number to the datagrid at the same time to avoid the refetch?

**Comment by reddolan** [comment]
@youdz I agree with @jbgarr on this. If a user filters in the middle of a large dataset, whether the filter results paginate or not, directing the user to the first page of the filter results makes the most sense. If the user was in the "M's" area during pagination, trying to recreate that place seems like it would be difficult to recreate and direct the user to. The same sort of experience would be expected with sorting.
