### ISSUE TITLE
Header clipping issue in smaller screens

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#816]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```
The header, with top-level navigation is clipped when the page is resized to mobile/small screens even though there's still enough space to fit all the elements.

Small screen:
![image](https://cloud.githubusercontent.com/assets/1977391/25565862/6a51e496-2e02-11e7-80bb-a32948fa417c.png)

Desktop/full size:
![image](https://cloud.githubusercontent.com/assets/1977391/25565871/89ca8e4a-2e02-11e7-8237-2b17f880370e.png)

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@whizkidwwe1217: Please provide a plunkr or post your header markup here so that we can replicate. Thanks!

**Comment by whizkidwwe1217** [comment]
@adityarb88 I got it fixed by removing the fixed width of the **branding** in mobile. I set a fixed width for it to align its width to the sidenav. I'm closing this issue. Thanks.
