### ISSUE TITLE
Clarity 0.9 wizard doesn't emit clrWizardPageOnLoad on wizard step navigation

### ISSUE THREAD

**Issue by vediga** [vmware/clarity#822]
We recently upgraded our project to use Angular 4 and Clarity 0.9, but the animations were broken and on investigating further the new wizard doesn't emit clrWizardPageOnLoad on wizard step navigation and hence wizard step animations were not getting triggered.

NOTE: I have imported BrowserAnimationsModule and animations at other places are working fine except for the wizard.

**Comment by mathisscott** [comment]
Hi @vediga 

Thanks for bringing this to our attention.

Could you tell us which wizard you are using (the old one or new one) and provide a plunkr replicating the issue?

https://plnkr.co/uNwwZe

Thanks!

**Comment by mathisscott** [comment]
I don't know if it was before. But this is working as of 0.9.2 in the new wizard.

https://plnkr.co/edit/naLCt9XNAvu2UqFvZjLq?p=preview

**Comment by vediga** [comment]
Yes it was broken in Clarity 0.9.0 but works in 0.9.2
