### ISSUE TITLE
WizardPage into sub-component

### ISSUE THREAD

**Issue by Rebolon** [vmware/clarity#825]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ x] enhancement
```

### Expected behavior
I have a wizard that is rather big and i want to refactor it : 
 * the wizard is the main component that include sub-components
 * each sub-components is a wizardPage that have all the domain code with the onSubmit behaviors
 * those component have an output that is catched by the main component

### Actual behavior
A Wizard and its pages mus be in an all-in-one component

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:**  0.9

* **OS and version:** 

* **Browser:** all

**Comment by mathisscott** [comment]
Thanks for contacting us @Rebolon 

Do either of these plunkr instances address your use case?

https://plnkr.co/edit/OuDRI990zcnGfhrQa4GJ?p=preview

https://plnkr.co/edit/RjLGlkFkUmhpohNUCSvy?p=preview

If so, please close this issue. If not, please create a plunkr demonstrating how you are suggesting the wizard should be used, even if it doesn't run.

Thanks.

**Comment by Rebolon** [comment]
seems ok, thx !
