### ISSUE TITLE
Forms - Overlapping text in form group titles

### ISSUE THREAD

**Issue by samdidos** [vmware/clarity#828]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
The titles of the form elements should expand if the title is too long for one line.

### Actual behavior
Actually, the titles are overlapping on each others when titles and elements are horizontally aligned.

### Reproduction of behavior
Here's a [Plunker](https://plnkr.co/edit/2FBKsjVnIje5V3NI9NVq).
If you stretch the window enough to let the form group elements in the same line, you'll see that the title overlaps the others below.
I've seen a [TODO in the code](https://github.com/vmware/clarity/blob/master/src/clarity-angular/forms/_forms.clarity.scss#L76) at this effect, but I'm not enough skilled in Sass to propose a solution.

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.2 

* **OS and version:** Linux Ubuntu 16.04

* **Browser:** all

**Comment by adityarb88** [comment]
@samdidos: We already have a bug filed for this https://github.com/vmware/clarity/issues/626 but haven't started working on it yet. An alternative right now is to use forms in grids. Closing this as duplicate.
