### ISSUE TITLE
Not able to create wizard when I use *ngFor with clarity 0.9.0 and Angular 4.0.3

### ISSUE THREAD

**Issue by indukr** [vmware/clarity#832]
**Select one ...**  (check one with "x")
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Should be able to create wizard using *ngFor dynamically using inheritance concept.

### Actual behavior
Creating a wizard framework which can be extended to implement features wherever wizard needs to be used. Creating this on plugin-seed-0.9.5 using Angular 4.0 and Clarity 0.9.0.

Able  to generate the wizard with static data but when I am trying to create the steps using same data  dynamically using *ngFor, I am getting the following error:
appErrorHandler.ts:29 TypeError: Cannot read property 'title' of undefined
    at WizardNavigationService.get [as currentPageTitle] (clarity-angular.umd.js:6422)
    at Object.eval [as updateDirectives] (Wizard.html:26)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:12606)
    at checkAndUpdateView (core.es5.js:12018)
    at callViewAction (core.es5.js:12333)
    at execComponentViewsAction (core.es5.js:12279)
    at checkAndUpdateView (core.es5.js:12024)
    at callViewAction (core.es5.js:12333)
    at execComponentViewsAction (core.es5.js:12279)
    at checkAndUpdateView (core.es5.js:12024)
    at callViewAction (core.es5.js:12333)
    at execEmbeddedViewsAction (core.es5.js:12305)
    at checkAndUpdateView (core.es5.js:12019)
    at callViewAction (core.es5.js:12333)
    at execComponentViewsAction (core.es5.js:12279)

I am trying this in the monitor view of plugin-seed where other wizards like 'action2-wizard' are available.  Trying to bring up a new button to demo my wizard framework.

Works fine with following html:
-----------------------------------
[<clr-wizard] #wizard [(clrWizardOpen)]="open">
    <clr-wizard-title>{{title}}</clr-wizard-title>

    <clr-wizard-button type="cancel">Cancel</clr-wizard-button>
    <clr-wizard-button type="previous">Back</clr-wizard-button>
    <clr-wizard-button type="next">Next</clr-wizard-button>
    <clr-wizard-button type="finish">Finish</clr-wizard-button>

   
        <clr-wizard-page>
            <ng-template clrPageTitle>Page {{stepActions[0]}}</ng-template>
            <ng-template clrPageNavTitle>{{stepActions[0]}}</ng-template>
            Content for page {{stepActions[0]}}
        </clr-wizard-page>

        <clr-wizard-page>
            <ng-template clrPageTitle>Page {{stepActions[1]}}</ng-template>
            <ng-template clrPageNavTitle>{{stepActions[1]}}</ng-template>
            Content for page {{stepActions[1]}}
        </clr-wizard-page>

        <clr-wizard-page>
            <ng-template clrPageTitle>Page {{stepActions[2]}}</ng-template>
            <ng-template clrPageNavTitle>{{stepActions[2]}}</ng-template>
            Content for page {{stepActions[2]}}
        </clr-wizard-page>
  
</clr-wizard>
``

Does not work with the following html: (Getting the above error):
---------------------------------------------------------------------------
<clr-wizard #wizard [(clrWizardOpen)]="open">
    <clr-wizard-title>Wizard Title</clr-wizard-title>

    <clr-wizard-button type="cancel">Cancel</clr-wizard-button>
    <clr-wizard-button type="previous">Back</clr-wizard-button>
    <clr-wizard-button type="next">Next</clr-wizard-button>
    <clr-wizard-button type="finish">Finish</clr-wizard-button>

    <ng-container *ngFor="let stepAction of stepActions">
        <clr-wizard-page>
            <ng-template clrPageTitle> Step {{stepAction}} </ng-template>
            <ng-template clrPageNavTitle> Step {{stepAction}} </ng-template>
            Content for page {{stepAction}}
        </clr-wizard-page>
    </ng-container>
</clr-wizard>

.ts file Parent:(wizard.component.ts)
--------------
import { Component, Input, OnInit, ViewChild } from "@angular/core";
import {Wizard} from "clarity-angular/wizard/wizard";
import { Params, ActivatedRoute } from "@angular/router";

import { GlobalsService }   from "../../shared/index";
import { AppAlertService } from "../../shared/app-alert.service";
import { WebPlatform }  from "../../shared/vSphereClientSdkTypes";
import { APP_CONFIG } from "../../shared/app-config";
import { Host } from "../../services/host.model";
import { HostService } from "../../services/host.service";

/**
 * Generic wizard used to wrap sub-components in dev mode.
 * Each sub-component class must be declared here and define a handleSubmit method.
 */
@Component({
   selector: "wizard",  
   templateUrl: "./wizard.component.html"
})
export class WizardComponent implements OnInit {
   actionUid: string;
   host: Host;  
   basic: boolean = false;   
   private webPlatform: WebPlatform;   
   private webContextPath: string; 

  @Input()
  public stepActions:string[] =[];
  
  @Input()
  public title:string = "";  

   @ViewChild("wizard") wizard: Wizard;

   public formData = {
      param1: "",
      param2: "some default value",
      param3: "typeA"
   };

   constructor( public gs: GlobalsService,
   public appAlertService: AppAlertService,
   public hostService: HostService,
   public route: ActivatedRoute)
     {
      alert("In Wizard constructor");        
      this.webPlatform = this.gs.getWebPlatform();
      this.webContextPath = this.gs.getWebContextPath();
   }

   ngOnInit(): void {
       alert("in ngInit funtion of wizard");
      if (this.gs.isPluginMode()) {
         // this.opened = true;
         // Get host objectId and actionUid from query parameters:
         // - actionUid could also be hard-coded if this modal is only used for 1 action
         // - retrieve host name in order to change the dialog title
         this.route.params.forEach((params: Params) => {
            this.actionUid = params["actionUid"];
            let hostId = params["id"];
            this.hostService.getHostName(hostId, hostResult => {
               this.host = hostResult;
               this.webPlatform.setDialogTitle("Action4 wizard for " + this.host.name);
            });
         });
         alert("in Plugin mode");
         this.wizard.open();

      } else {
         // dev mode: modal dialog is opened from the Host monitor view,
         // host is already known and we set actionUid to the value in plugin.xml
         this.actionUid = APP_CONFIG.packageName + ".sampleAction4";          
         alert("actionUid: "+this.actionUid);
        // this.basic = true;
         //this.wizard.open();
      }
   }

   openWizard(host: Host, title: string) {

     this.host =  host;
     this.title =  title;     

     alert("In open function of Parent"); 
        alert("test title :"+title);
        alert("test host :"+host.name);     
      this.wizard.open();
   }

   onCommit(): void {
      this.webPlatform.closeDialog();

      let actionUrl = this.webContextPath + "/rest/actions.html?actionUid=" + this.actionUid;
      let jsonData = JSON.stringify(this.formData);
      this.webPlatform.callActionsController(actionUrl, jsonData, this.host.id);

      if (!this.gs.isPluginMode()) {
         this.appAlertService.showInfo(this.actionUid + " called with " + jsonData);
      }
   }

   onCancel(): void {
     alert("in cancel function");
      this.webPlatform.closeDialog();
   } 

}

.ts file Inherited (wizardtest.component.ts)
-------------------------------------------------
import {Component,Input} from '@angular/core';
import { ActivatedRoute } from "@angular/router";

import {WizardComponent} from './index';
import { GlobalsService }   from "../../shared/index";
import { AppAlertService } from "../../shared/app-alert.service";
import { WebPlatform }  from "../../shared/vSphereClientSdkTypes";
import { APP_CONFIG } from "../../shared/app-config";
import { Host } from "../../services/host.model";
import { HostService } from "../../services/host.service";

@Component({
    selector: "wizard-test",
    templateUrl: "./wizard.component.html",   
})

export class WizardTestComponent extends WizardComponent
{ 

  @Input()
   stepActions = ["First Step","Second Step","Third Step"];

  @Input()
   title = "Wizard Test";  

    constructor( public gs: GlobalsService,
   public appAlertService: AppAlertService,
   public hostService: HostService,
   public route: ActivatedRoute){

       super(gs,appAlertService,hostService,route);
   }

    openWizard(host: Host, title: string) {
        this.host = host;
        this.title =  title;
        alert("In open function of child");
        alert("test title :"+title);
        alert("test host :"+host.name);
      super.openWizard(this.host,this.title);
   }

}

### Reproduction of behavior
Working fine with static data. So did not make any plunker for this. Please help with resolving this issue.

### Environment details

* **Angular version:** ^4.0.3

* **Clarity version:**  ^0.9.0

* **OS and version:** Windows 7 Enterprise SP 1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@indukr

Please post a plunkr replicating your issue as opposed to raw code in the issue description. 

At a glance, your code appears to be missing a clr-wizard-title element, just like the error says.  But I can't really tell because github is munging up your raw code.

**Comment by indukr** [comment]
This issue got resolved. The error was due to both parent selector and child selector included in the same html. When we invoke wizard from child class, Angular is not able to decide between parent/child selector to run.

Thanks..

**Comment by mathisscott** [comment]
Happy to hear that, @indukr. Thanks for following up.
