### ISSUE TITLE
Remove examples of alerts above the modal title from the website

### ISSUE THREAD

**Issue by bdunkz** [vmware/clarity#834]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Adding a clr-alert as content to a clr-modal, I am expecting to see the alert appear above the title bar, as documented under the "Placement" section of Alerts (https://vmware.github.io/clarity/documentation/alerts).

### Actual behavior
The alert is not displayed.

### Reproduction of behavior
https://plnkr.co/edit/kt9L2eBGut33LJKrKdHA

### Environment details
* **Angular version:** 4.0.X
* **Clarity version:** Latest
* **OS and version:** Mac

* **Browser:** All

**Comment by mathisscott** [comment]
@reddolan : Could you take a look at this and make sure this pattern still holds for us? That way we can get it in the queue for implementation.

**Comment by reddolan** [comment]
Verified. The plnk provided has two demos: Clarity-UI Modal and Clarity-Angular Modal. The alert shows in Clarity-UI but does not show in Clarity-Angular. The alert should show in both. (cc: @mathisscott )

**Comment by jaffoneh** [comment]
@reddolan why would we allow the alert on top of title + "x"? Doesn't it seem more consistent to keep the "X" and title in a consistent location regardless of the existence of an alert or not?

Think of scenarios where the alert all of a sudden appears, now the location of an action (crucial action which is X) has all of a sudden changed, that doesn't seem like a good pattern, right?

**Comment by reddolan** [comment]
@jaffoneh this issue is about the alert not showing up, not about the alignment.

**Comment by jaffoneh** [comment]
@reddolan I don't believe so. What @mathisscott is asking is if we should keep the pattern or not.

**Comment by reddolan** [comment]
@jaffoneh I misunderstood @mathisscott's question. The pattern in the documentation should be updated to reflect better placement of the alert

**Comment by mathisscott** [comment]
Mkay. So to clarify... do we want to remove the documentation showing an alert at the top of the modal? Just trying to figure out what the recommended course of action here is....

**Comment by bdunkz** [comment]
One thing to also consider is how visible the alert is to the application user.  Considering a "modal level" alert, the user should always be able to see it.

Since the title bar is always visible, including it above the title means it should always be visible.  If placed within the modal content, the alert may not be visible if the user has scrolled down.

The use case I encountered is that I have a modal that has a scroll bar at the resolution on my laptop.  When I fill out the form in the modal and all field level validation is OK, then I submit and it results in a server error.  This is when I want to show a "modal level" alert to the user.

**Comment by reddolan** [comment]
@bdunkz if you want to add an alert, we recommend that it be below the title for now. We are considering our options for this use case
