### ISSUE TITLE
[ng] Input component

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#835]
We currently only have css for the input validation piece, so the validation error message is still clipped off (#37). What we need is an angular component for input fields.

**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior

Input component should have all the common functionalities of input built into the angular component. It should also use javascript (TypeScript) to position the tooltip so it's not clipped off.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by asenradev** [comment]
What are the plans on resolving this? To my perception this is more a bug than a feature request, since the only thing to be added to default input behavior is a fix of the clipping issue.
If you are not going to fix it soon, could you please provide a workaround? Also if you have any idea how the API for the input and tooltip will look, let me know, so minimum rework is needed later when the component is implemented.

**Comment by mathisscott** [comment]
@asenradev 
This is on our list of near-term priorities. It was jumped in queue by a couple of other items though. I don't know if this will be delivered to your standards of "soon", so I will ping @jeeyun , @youdz , and @adityarb88 for information on the API and any possible workarounds that may help you.

**Comment by asenradev** [comment]
Glad that this is priority for you. Soon for me would in few weeks if we don't have recommended workaround. Almost everyday somebody in our team struggles to work it around. As a result  we have few different behaviors, none of them as per the clarity guidelines.

**Comment by gnomeontherun** [comment]
This is actually done, as part of recent forms work.
