### ISSUE TITLE
[WEB] Dox for expanding row grid

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#838]
Creating an issue to track the work involved with adding expanding row documentation to the datagrid section of the website.

**Comment by youdz** [comment]
Please note that we already have the tech docs, so it's only the design and UX pattern documentation that's needed.

**Comment by reddolan** [comment]
Update initial paragraph with the following

```Use expandable rows when you have additional information for a row, or row cells that do not need to be shown at all times. This helps minimize visual clutter. It also frees up the need of a second datagrid that gets updated with details. This is sometimes called a master-detail or master-child pattern. Another use is replacing original row data with a custom view or layout which includes most or all of the original row data. The expanded area can be loaded with other components as well to fit your needs.```
