### ISSUE TITLE
JS Name change required.

### ISSUE THREAD

**Issue by xrobau** [vmware/clarity#850]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
HTML5 console works.

### Actual behavior
HTML5 console breaks because 'clarity-*.js' is blocked by EasyList.

### Reproduction of behavior
EasyList (which is used by a large number of adblockers) blocks any javascript called 'clarity-*.js'. [See here for more information](https://forums.lanik.us/viewtopic.php?p=117680#p117680). Opening vCenter console with any browser with EasyList enabled makes the HTML5 console crash.

At the very least, vCenter should detect that Clarity is missing an tell people to disable their ad blocker, rather than whitepage.

### Environment details
* **Browser:** Anything with uBlock Origin, or most other web browsers.

**Comment by jaffoneh** [comment]
We've been actually discussing this internally. Clarity itself does not ship a clarity-*.js file, it is the naming used within the HTML5 web client and that is about to change to support the case mentioned above. Closing based on the above considering this is not a Clarity issue and cannot be solved within Clarity.

**Comment by bdunkz** [comment]
Just to add some additional details: the latest Fling releases no longer request a clarity-*.js file and the next vCenter update/patch is also covered.

**Comment by mathisscott** [comment]
I've left a response on the EasyList forum for this issue. I'm hoping to hear back at some point.

If not, I will try emailing them directly to get direction on next steps. If the answer is for us to change the name of our deliverables, we need to come to an understanding that will prevent this issue from resurfacing in the future.

It's also a little silly that they have refused to whitelist our packages. We have three of them... 🙄

**Comment by mathisscott** [comment]
I'm going to need some help from @jeeyun to work through a webpack issue I'm hitting with this.

**Comment by mathisscott** [comment]
@jeeyun : Nevermind on previous comment. @hippee-lee helped me out. I just have one more hurdle to figure out. I'm hoping to have something to discuss on this on next Tuesday's standup. I know you're still out so no worries on that. ❤️
