### ISSUE TITLE
Circular Progressbar / Determine Spinner

### ISSUE THREAD

**Issue by sivix** [vmware/clarity#853]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[x] enhancement
```

### Expected behavior

I'm looking to have a Circle Progressbar like in the photon OS Dashboard:
https://i0.wp.com/www.virtuallyghetto.com/wp-content/uploads/2016/04/Screen-Shot-2016-04-17-at-11.43.10-AM.png?resize=770%2C335

Looking to Material for Angular.io they have a very good set of modules similar but looks more complete, for example the Spinner provide the ability to be "determine" or "indetermine" working as a percentage or manual progress, check the example here:
https://material.angular.io/components/component/progress-spinner

having a "determine" Spinner with Number in the center will replicate the need.

### Actual behavior

the Spinner available in Clarity is only "indetermine" so doesn't allow to set a specific percentage, or be used as a "circular" Progressbar.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all ]

**Comment by mathisscott** [comment]
Thanks for the suggestion @sivix 

This is not something we would be adding in the near term but we have added it to our backlog and will investigate when our more immediate priorities are met.

**Comment by reddolan** [comment]
@sivix have you seen the [progress bar](https://vmware.github.io/clarity/documentation/progress) we have with % indicator? Will this meet your needs?

**Comment by sivix** [comment]
Hi @reddolan thanks, but yes I've seen all the current progress bars, but they are linear.
What I was looking for was a Circle progressbar to show informations about counters.

What I found is this one https://github.com/crisbeto/angular-svg-round-progressbar is ready for angular.io and I've been able to import it and use it in Clarity.

<img width="1046" alt="screen shot 2017-05-09 at 11 27 39" src="https://cloud.githubusercontent.com/assets/3509604/25887397/4c1e6d2a-3562-11e7-8e70-6c6846327684.png">

**Comment by reddolan** [comment]
@sivix aside from aesthetics, what reason(s) do you want radial/semi-radial over linear? What problem is a radial solution solving for you?

**Comment by reddolan** [comment]
@sivix wanted to follow up with you again on this. Do you have more info on the questions I asked previously?

**Comment by sivix** [comment]
Hi Reddolan,
the radial can provide more rich data visualization, is not just aesthetic. actually what I've done is to use ngxcharts: https://github.com/swimlane/ngx-charts achieving something like that:
![image](https://user-images.githubusercontent.com/3509604/27095426-db48d168-506d-11e7-8279-09002f3e083d.png)

**Comment by reddolan** [comment]
@sivix I want to be sure I understand what you are asking for. The visual examples you have shared seem to show *charts* versus an active *progress spinner*. 

Can you describe how this is to be used by the user? Does the user see this when they visit a page and it will show how many resources have been consumed? Or will this be something a user sees after interacting with something, similar if they were downloading something?

**Comment by reddolan** [comment]
@sivix have you had a chance to review my previous questions?

**Comment by sivix** [comment]
Hi @reddolan ; the picture is just an example how  Circular progress may be more useful than a linear. but to be honest the circular progress initial request was more a request to be used to represent statistics for people voting in real-time. it was used as a Chart. no interaction required.

**Comment by reddolan** [comment]
@sivix Charts are on our roadmap for the future. We’ll consider this example when we work on them. For now, D3, charts.js or highcharts are recommendations you might consider for meeting this need. Thank you

**Comment by sivix** [comment]
@reddolan I used https://github.com/swimlane/ngx-charts because they are Angular ready. why not planning for them ?

**Comment by reddolan** [comment]
We are planning to build charts. We just have higher priority items to complete before getting to them

**Comment by mathisscott** [comment]
Hi @sivix 

@reddolan is correct in that a chart library is on our long-term roadmap. It is a large effort, however, and one which product teams have already found workarounds for their use cases. That said, as we do explorations on the chart library for Clarity, we are always interested in what people are using and why. So please feel free to share as many details as you can on your use case, the library you use, and what charts work best for your use case.

**Comment by arjunrao2709** [comment]
@reddolan To answer your questions, we have a case where we wish to show the progress of an action (Example : on clicking download in a card, I want the button to convert to a spinner and show progress of download) The problem with the progress bar is that it occupies too much space (it says this in the Clarity docs as well) and having progress bars on multiple cards will cause a visual overload. It'll be great if this can be picked up.

**Comment by reddolan** [comment]
@arjunrao2709 we have a spinner button spec out right now #1488. Is this what you are looking for?

**Comment by arjunrao2709** [comment]
@reddolan That is not it. I am looking for a determinate spinner. Here is an example. https://plnkr.co/edit/?p=preview
