### ISSUE TITLE
Document validation/error tooltips on Tooltip page

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#857]
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
See documentation around the error tooltip on the [Tooltip](https://vmware.github.io/clarity/documentation/tooltips) page

### Actual behavior
We only document the black (default) tooltip on the [Tooltip](https://vmware.github.io/clarity/documentation/tooltips) page

### Recommendations for documentation
- usage (link to [Input Validation](https://vmware.github.io/clarity/documentation/input-fields#form-validation))
- visual design
- behavior

**Comment by adityarb88** [comment]
New validation is not going to use Tooltips. Please see #932 for more info. Closing the issue.
