### ISSUE TITLE
clr-dropdown component close on click has delay

### ISSUE THREAD

**Issue by JohannesRudolph** [vmware/clarity#86]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Dropdown should close immediately after click

### Actual behavior
Dropdown closes approx 300ms or later after click. It's enough to be noticably delayed.

### Reproduction of behavior
Check out drop down under heading: "1. clrMenuPosition is set to top-left. Default is bottom-left" 
at https://vmware.github.io/clarity/documentation/dropdowns

### Environment details
* **Browser:** [Chrome 54]

**Comment by jaffoneh** [comment]
@reddolan do you mind taking a look to confirm the delay needed for this. I agree, it takes a bit too long for a dropdown to close once I click outside to close.

**Comment by adityarb88** [comment]
@jaffoneh, @reddolan: This is because there is a transition that we have set: `transition: visibility 0.2s ease-in`. If we remove this, the menu will hide without any delay but we had initially decided to add this transition. Let me know if we want to remove this and I can get this done.

**Comment by reddolan** [comment]
@adityarb88 do we have the transition set for both show/open and hide/close, or are there separate transitions for each? I would prefer to have an show/open transition if possible

We could do one of two things:
1. We could change the transition time to 0.1s (I've tested and it's much faster)
2. We could remove the transition altogether

**Comment by reddolan** [comment]
After testing it a bit more, it seems that the transition is only on hide/close. If I set the transition time to something ridiculous like 0.9s, it opens quickly and closes slowly. As it seems the transition is only affecting hide/close, I would recommend removing the transition altogether.

**Comment by hlzpy** [comment]
what, I don't konw
