### ISSUE TITLE
Error loading clarity angular. ES5

### ISSUE THREAD

**Issue by saularcones** [vmware/clarity#867]
[ x ] bug
[ ] feature request
[ ] enhancement

## Expected behavior
It should load correctly and let me import the ClarityModule

## Actual behavior
I get this error when I try to load clarity-angular.umd.js
```
Uncaught TypeError: Cannot read property 'Subject' of undefined
    at Alert.close._closed ( clarity-angular.umd.js:4)
    at  clarity-angular.umd.js:5
```

## Reproduction of behavior
https://plnkr.co/edit/BvDxqA6UPOPbgMfFMYZ0?p=preview

## Environment details

- Angular version: 4.1.1

- Clarity version:  0.9.3

- OS and version:  Windows 10

- Browser: Chrome

**Comment by mathisscott** [comment]
@jeeyun , @Shijir : Is this an issue or a problem with how @saularcones is setting up clarity in SystemJS?

**Comment by youdz** [comment]
Our rollup config for globals sets RxJS as `rxjs`, but they actually declare their global as `Rx` (yes, I don't know why they're doing this, their global is different from their package name, it's just painful for everyone else).

So we need to change our rollup config to `'rxjs' : 'Rx'`, or something like this. I don't know the exact details, I'm just pointing in the direction to look at.

**Comment by Shijir** [comment]
@jeeyun I am assigning this task. I have tried the Eudes' suggestion and that seems to fix the problem posted in this issue, but I was running into another `Rxjs` related issue, which might take a bit more involvement. Let me know if you want to further discuss this issue with me.
