### ISSUE TITLE
Alert-styled modals

### ISSUE THREAD

**Issue by reddolan** [vmware/clarity#876]
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
A modal that is designed to look like an alert

### Actual behavior
standard alert is displayed above modal title

### Reproduction of behavior
![image](https://cloud.githubusercontent.com/assets/1858226/25873094/ed335c1c-34c1-11e7-9ab9-6be6ca2c8bee.png)

### Design Recommendation
- original request and designs from Brian Mireles @bmireles 

![image](https://cloud.githubusercontent.com/assets/1858226/25874111/f71294ec-34c5-11e7-8a42-395a933d23ef.png)
![image](https://cloud.githubusercontent.com/assets/1858226/25874126/117d7e14-34c6-11e7-8e5e-ff851486e741.png)

**Comment by jaffoneh** [comment]
@reddolan what are the use cases? Why wouldn't you simply display an alert on top of the modal. I am not sure I understand the use case here.
