### ISSUE TITLE
Clarity Grid Misalignment Issues

### ISSUE THREAD

**Issue by tnravik** [vmware/clarity#878]
Please find attached below,  chat transcript between keshav and Eudes Petonnet-Vincent

Whenever we use *clrDgItems to create rows for datagrid records, we see a misalignment. If we use *ngFor, clarity does not seem to get full control w.r.t pagination.

Please advise a solution (or) ETA for fixing this issue.

![image](https://cloud.githubusercontent.com/assets/28587379/25884985/90908d92-3573-11e7-830b-68f18c1ba00e.png)

**Comment by jaffoneh** [comment]
@tnravik could you edit this issue or close and re-file using the template provided by default including the version used, reproduction behavior, etc? It's tough for others on the team to pick this up by simply looking at the conversation or the description provided.

**Comment by tnravik** [comment]
@keshav, please do the needful as per the above comment.

Thanks,
Ravi

**Comment by youdz** [comment]
@tnravik: Grid alignment issues have already been fixed in Clarity 0.9.1 (3 weeks ago): https://github.com/vmware/clarity/commit/505a3ad4438c3e5fb2d7a5ded917ee49bcab8071
