### ISSUE TITLE
Alert styled modals

### ISSUE THREAD

**Issue by bmireles** [vmware/clarity#881]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[ x ] enhancement
```

### Expected behavior
An alert modal increases the users awareness and provides them with a stronger visual cue for raising awareness of important information. The designs below tested well with our customers.

![info modal](https://cloud.githubusercontent.com/assets/18449355/25906169/7f49549c-3569-11e7-9c29-81b606b5bf22.png)

![success modal](https://cloud.githubusercontent.com/assets/18449355/25906172/828eaddc-3569-11e7-9c0b-0fcae6d3a479.png)

![warning modal](https://cloud.githubusercontent.com/assets/18449355/25906189/884e4f3e-3569-11e7-842a-4cff457145cb.png)

![error modal](https://cloud.githubusercontent.com/assets/18449355/25906194/8bdff2f6-3569-11e7-88da-5ea905d3366d.png)

### Actual behavior
When an alert is displayed in a modal it is often overlooked. In user testing, the alerts didn't provide them with a strong visual cue and they often missed important information.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
@bmireles I would be concerned with the risk of having to a design a specific modal that is visually different from others modals specifically for alerts (for example, what's the use case for a success modal that's this different). In general, we would want to use alerts in the case of something happening in the modal that requires validation/alerting or an alert modal (Where we can display an alert icon to the left with modal content in the middle) but without displaying a specific modal experience for alerting. This increases the challenge of maintaining this (from a design point of view) and of explaining the different warning possibilities in different cases. It adds an addition lego piece to the design system without a strong need or use case in addition to what's already provided.

It might be a good idea for a specific application for a specific use case but I am not sure it works well for the design system itself to recommend it across the board.

Based on the above, I am closing for now but do let me know if you have other thoughts, I am happy to discuss further. Thanks!

**Comment by bmireles** [comment]
@jaffoneh I see your point and understand your concern of adding another component that also adds maintenance cost. In regards to the designs above, the info and error styles were only designed to complete the concept. They were not tested in our user sessions. We only tested the warning and success styles.

As far as the use cases are concerned, I wouldn't say they differ from what the current alert style intends to solve for. We used the warning modal to ensure the user was explicitly aware of the consequences should they go forward with the action. The intent was for the design served as a yield sign before making a decision. My design attempts to capture the users attention with bolder visual design, to ensure prerequisites are met or consequences are clearly understood.

We tested the existing alert style in the modals and they were repeatedly overlooked. Users would proceed with the action and get stuck and ask why their decision led to that state. We would take them back to the modal with the alert and point out the information highlighted in the alert. They would have an "ah-ha" moment and continue.

Again, I feel your concerns are valid and so I am not suggesting we have to incorporate my designs into the clarity. But I would like us to continue to explore options to improve the responsiveness of our alerts when used in the manner which I have explained above. The existing pattern wasn't effective in our scenario. If possible, I would like to explore more options and continue this discussion.

-B

**Comment by jaffoneh** [comment]
@bmireles thanks for the reply, this is really helpful. If you have some of the research data I'd love to see it (internally) but in general, your point around improving the "alertness" of an alert to users and how we can grab their attention within the context of a modal is valid and something to look at.
