### ISSUE TITLE
The built in SORT and FILTER do NOT support *ngFor

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#887]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
built in SORT and FILTER work well if use *ngFor to loop data in datagrid.

### Actual behavior
built in SORT and FILTER DO NOT work if use *ngFor to loop data in datagrid.

We want to use *ngFor to support server backend pagination. Meanwhile, enabling the built in SORT and Filter is also required. But seems these two functions are conflict.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/jMCyX9

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.X

* **OS and version:** MAC 10.11.4

* **Browser:**ALL

**Comment by steven-zou** [comment]
Can implement one custom sorter or filter to be compatible with *ngFor?

**Comment by youdz** [comment]
The best I can do is redirect you to [our documentation on server-driven datagrids](https://vmware.github.io/clarity/documentation/datagrid/server-driven):
>An important thing to note is that when the server does handle pagination, it needs to also deal with sorting and filtering, because all three are tightly coupled.

and
>Since you don't have all the data available at once, you cannot use the smart iterator `*clrDgItems`: it would sort, filter and paginate a subset of the data that has already gone through all that. So all you need to do is to go back to a simple `*ngFor`, which we support.

`*clrDgItems`for server pagination makes absolutely no sense. You'd sort and filter the contents of a page, not the whole dataset.

Also, just like your other issues, your plunker isn't even working, it crashes when loading.

**Comment by steven-zou** [comment]
@youdz 

I understand clearly about the differences between *clrDgItems and *ngFor as I have read the doc many times to find a proper solution.

What I mean is if we use *ngFor to support our server end pagination, is it possible to enable the column sort and filter with custom comparators and filters like 'clrDgField' does?
![2017-05-12 10 55 33](https://cloud.githubusercontent.com/assets/5753287/25980504/8d942d76-3701-11e7-9d49-44e4dbf443c2.png)

The meaning of page object in the State object is very confusion.
`Object
from:0
size:15
to:14`

Or implement the filter function by ourselves as we currently do.
![2017-05-12 10 59 39](https://cloud.githubusercontent.com/assets/5753287/25980585/1fc1f480-3702-11e7-859c-c62516ea3633.png)


Additionally, if use *ngFor, an error may appear:
`<clr-dg-row *ngFor="let user of users">`
`
VM1274 DatagridRow.ngfactory.js:695 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.
    at viewDebugError (VM591 core.umd.js:8618)
    at expressionChangedAfterItHasBeenCheckedError (VM591 core.umd.js:8596)
    at checkBindingNoChanges (VM591 core.umd.js:8760)
    at checkNoChangesNodeInline (VM591 core.umd.js:12314)
    at checkNoChangesNode (VM591 core.umd.js:12288)
    at debugCheckNoChangesNode (VM591 core.umd.js:12907)
    at debugCheckDirectivesFn (VM591 core.umd.js:12809)
    at Object.View_DatagridRow_0.currVal_0 [as updateDirectives] (VM1274 DatagridRow.ngfactory.js:766)
    at Object.debugUpdateDirectives [as updateDirectives] (VM591 core.umd.js:12791)
    at checkNoChangesView (VM591 core.umd.js:12108)`

**Comment by steven-zou** [comment]
I suggest to reopen this issue for discussing.
