### ISSUE TITLE
Datagrid always has a fixed hight when enable pagination.

### ISSUE THREAD

**Issue by wknet123** [vmware/clarity#888]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Datagrid height can automatic adjust to fit rows.
### Actual behavior

![image](https://cloud.githubusercontent.com/assets/5027302/25937201/4ec8f120-365d-11e7-8868-ab828460cfbb.png)
There contains a big blank area when it only has three rows.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.1

* **OS and version:** OS X 10.12

* **Browser:** [all]

**Comment by adityarb88** [comment]
Hi @wknet123. Please provide a plunkr so that we can replicate the issue. https://plnkr.co/uNwwZe

**Comment by zivanov123** [comment]
Have you tried not to set the height of the grid?

**Comment by dragon503** [comment]
Also，I met the same issue.
Have this issue fixed now?

**Comment by adityarb88** [comment]
@wknet123, @dragon503: We need a plunkr & a clear description of the issue to reproduceit. Without that we won't be able to  proceed with the fix.

**Comment by mathisscott** [comment]
@wknet123 @dragon503 
We haven't heard back on the plunkr request. I assume this is working now?
