### ISSUE TITLE
Add an Autocomplete component

### ISSUE THREAD

**Issue by cstranex** [vmware/clarity#90]
[ ] bug
[X] feature request
[ ] enhancement

### Expected behavior
Implement an auto complete component that will automatically display a dropdown with possible choices. Should support:

- custom filter function
- drop-down template (eg: multiline lines)

### Reproduction of behavior
Example of an autocomplete component from another library: https://material.angularjs.org/latest/demo/autocomplete

**Comment by jaffoneh** [comment]
Work on this has started as part of the enhanced autocomplete/select work. cc @reddolan

**Comment by reddolan** [comment]
We have merged your request into #248 and will be closing this one. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you

**Comment by typhoon1978** [comment]
Any news about this?
