### ISSUE TITLE
All shapes in ClarityIcons should be loaded by importing a single module in TypeScript.

### ISSUE THREAD

**Issue by Shijir** [vmware/clarity#906]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[x] enhancement
```

### Expected behavior

It should be possible to import all shape sets through a single `import` module.

### Actual behavior

Right now, if users want to load all shapes they have to import multiple different shapes like this:

```
import 'clarity-icons';
import 'clarity-icons/shapes/essential-shapes';
import 'clarity-icons/shapes/social-shapes';
import 'clarity-icons/shapes/technology-shapes';
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
What we wind up doing here may depend on our solution to #407 and how we decide to handle loading on the icon library
