### ISSUE TITLE
Controls inside modal dialogs not working in Firefox

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#907]
```
[X ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
To work

### Actual behavior
Links, buttons, etc do not work when using Firefox. Chrome works fine. You get no feedback on Firefox (i.e. cursor change, hovering feedback on buttons etc). In some cases you cannot even click on the controls.

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/modals#examples

Go to the bottom and select the "Show Modal" buttons for example 2 and 3 for Angular components.

### Environment details

* **Clarity version: 0.9.3** 

* **OS and version: Win10** 

* **Browser: Firefox 53.0.2**

**Comment by hippee-lee** [comment]
Hi, @rbirkgit , 
Using the latest firefox `53.0.2 (64-bit)` When I go to the documentation for modals, all of the examples: `show, small, large, extra-large, no x in top right, and static backdrop` open for me. 

What version of firefox are you using? Is there any more info you can provide about your setup to help us recreate what you are experiencing?

**Comment by rbirkgit** [comment]
See this pic. The last examples don’t work with Firefox (i.e. #2 and #3). I am using:

**Comment by jaffoneh** [comment]
@rbirkgit there doesn't seem to be an attachment here. Could you include the images again?

**Comment by rbirkgit** [comment]
I tried with both Firefox 53.0.2 32bit and 64bit on Win10, same result. The last two samples (2. clrModalClosable and 3. clrModalStaticBackdrop) the buttons etc don't work. Have to press F5 (refreshing the whole page) to exit the dialogs.

**Comment by mathisscott** [comment]
Hi Ron,

Thanks for bringing this up. It appears to be related to https://github.com/vmware/clarity/issues/617


We have someone looking at it.


Scott

________________________________
