### ISSUE TITLE
Any more complete samples using Clarity and Angular?

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#908]
```
[ ] bug
[x ] feature request
[ ] enhancement
```

Are there any more complete example using Clarity and Angular, especially the angular components? I see the docs but they only show bits and pieces but not much how it all ties together. An example would be really nice.

Some controls don't have any docs at all about Angular components like headers. Maybe they don't have any? The component status claim there are.

**Comment by jaffoneh** [comment]
@rbirkgit what do you mean by complete samples? The components that are available with Angular pieces to them have extensive documentation (https://vmware.github.io/clarity/documentation). Few examples are datagrids, wizards, etc and some of them like Datagrids have full end to end demos of all features together.

I am closing this considering this already exists, if you have specific questions on specific components please feel free to file issues on those components with a direct ask and using the template provided in the issue on GitHub.
