### ISSUE TITLE
Does headers have angular component?

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#909]
The component status says headers have angular components, but I see nothing about it in the docs.

**Comment by mathisscott** [comment]
Hi Ron,

I believe this is referencing the responsive nav ( https://vmware.github.io/clarity/documentation/navigation#responsive_navigation ) which is referenced and linked from the header docs.


Thanks again,


Scott

________________________________

**Comment by youdz** [comment]
You can find an example in the [Responsive navigation docs](https://vmware.github.io/clarity/documentation/navigation#responsive_navigation).
I admit it was harder to find than I expected. I raised this to the team, we'll add it as part of the numerous tickets we have on the website's information architecture.

I hope this helps. 😄
