### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by Shengjian** [vmware/clarity#91]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```
After I updated the package.json file, then run rpm install
### Expected behavior

The latest clarity UI has been installed

### Actual behavior

It threw errors:
npm ERR! peerinvalid The package @webcomponents/custom-elements@1.0.0-alpha.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer clarity-icons@0.6.2 wants @webcomponents/custom-elements@github:webcomponents/custom-elements.git#v1.0.0-alpha.3

### Environment details
The dependencies in my package.json are:
    "@angular/common": "^2.1.0",
    "@angular/compiler": "^2.1.0",
    "@angular/core": "^2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "^2.1.0",
    "@angular/platform-browser": "^2.1.0",
    "@angular/platform-browser-dynamic": "^2.1.0",
    "@angular/router": "^3.1.0",
    "@angular/upgrade": "^2.1.0",
    "@webcomponents/custom-elements": "github:webcomponents/custom-elements#v1.0.0-alpha.3",
    "clarity-angular": "^0.6.0",
    "clarity-icons": "^0.6.0",
    "clarity-ui": "^0.6.0",
    "core-js": "^2.4.0",
    "font-awesome": "^4.5.0",
    "mutationobserver-shim": "^0.3.2",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "^0.19.27",
    "web-animations-js": "^2.2.1",
    "zone.js": "0.6.21"

* **Angular version:** 2.0.X

* **Clarity version:** 
0.7.0

* **OS and version:** 
MAC OS

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by rhodesy** [comment]
What version of Node.js are you running? Find out by using 'node -v' in your console. Updating this, if you're running an outdated version, might help out. It's recommend to run the latest Long Term Support version: v6.91 LTS.

**Comment by Shijir** [comment]
Hi @Shengjian,

Please make sure this package "@webcomponents/custom-elements": "github:webcomponents/custom-elements#v1.0.0-alpha.3" have no conflict with the same package that's installed globally.
