### ISSUE TITLE
[ng] fixed height is not working in datagrid

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#911]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

Specifying a fixed height should make a datagrid stretch to fill the height.

### Actual behavior

The footer is appended right after the last data row, even though in the dom the container is set to the specified height.

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/WMnaRUVmXGLAptIlAlzS?p=preview

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.4-patch

* **OS and version:** Mac OS Sierra

* **Browser:** all

**Comment by youdz** [comment]
@hippee-lee: Is this still bugged or did #905 fix it?

**Comment by hippee-lee** [comment]
Still a bug relatedf to the fix for #847 fix.
