### ISSUE TITLE
Wizard.currentPageChanged and WizardPage.onLoad should be called only on real page change

### ISSUE THREAD

**Issue by itaneva** [vmware/clarity#914]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

My expectation is that WizardPage.onLoad and Wizard.currentPageChanged are emitted only when the wizard page is really changed through navigation. If any data on the page changes, but the page remains the same, no event should be emitted. Thus the events will be usable for loading initial page data. 

### Actual behavior

Now the events are triggered on Wizard,ngDoCheck->navService.updateNavigation->setCurrentPage  even if the page has not changed.

### Environment details

* **Angular version:** 4.1.0

* **Clarity version:** 0.9.3

* **OS and version:** Windows 8.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@itaneva 
Try replicating on the 0.9.4-patch release that was just released last night. 

I believe this has already been fixed.

**Comment by itaneva** [comment]
I'll check it, when I'm able to upgrade to 0.9.4-patch (hopefully today).

**Comment by itaneva** [comment]
Checked with 0.9.4-patch and it's really fixed. Thanks.
