### ISSUE TITLE
Add a link to responsive navigation at the top of the header docs

### ISSUE THREAD

**Issue by jaffoneh** [vmware/clarity#915]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
There is confusion around the responsive header since it is not part of the header documentation. 

### Actual behavior
While we add it, we should have a link that's very clear and possibly at the top (or its own section) within the header documentation to link to responsive header docs. In the future, we should have that within header docs.

### Reproduction of behavior
https://vmware.github.io/clarity/documentation/header
https://vmware.github.io/clarity/documentation/navigation

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:**  0.9.4

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@jaffoneh and I discussed about this. We already have a link pointing to Responsive Navigation on the header page:

![image](https://cloud.githubusercontent.com/assets/1426805/26014436/6027dcce-3711-11e7-81e7-f78890d4feba.png)

But we still need to find a better way to document this. No action required on this for now until we come up with a plan to address this.
