### ISSUE TITLE
@webcomponents/custom-elements@1.0.0

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#916]
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Working

### Actual behavior
I get the following error:
npm ERR! peer dep missing: @webcomponents/custom-elements@1.0.0-rc.3, required by clarity-icons@0.9.4

### Reproduction of behavior
I am using:
@webcomponents/custom-elements@1.0.0

Does Clarity require the rc3 build or should the released 1.0 also work?

**Comment by adityarb88** [comment]
hey @rbirkgit: i dont think this is a bug but an enhancement. we released with a peer dep on 1.0.0-rc3 yesterday and it just so happened that version 1.0 was also published by them yesterday. you can check at your end if 1.0 works with clarity-icons but we haven't tested it yet. thanks for opening the issue though. we will track this for the upgrade to 1.0.

**Comment by rbirkgit** [comment]
I agree it may not be a bug but wasn't sure what to put. Feel free to change to what's appropriate. rc5 has been out for a while and I used it earlier. I just started playing with Angular and Clarity and my two line samples are not an indication that everything is well :)
