### ISSUE TITLE
[EPIC/NG] Fix Treeview

### ISSUE THREAD

**Issue by youdz** [vmware/clarity#917]
Epic grouping the 2 bugs and one critical performance improvement we need.

1. Recursive trees cannot be selectable.
2. Fully dynamic selection from the top of the tree doesn't work.
3. Every single node is eagerly created, which leads to terrible performance on large trees. (In addition to making it hard to do proper lazy-loading.)

**Comment by youdz** [comment]
Ok, so we have a plan.

### Top-level selection (#797)

It turns out that with proper lazy loading, we have absolutely no way to support the top-level `[(clrTreeSelected)]` two-way binding anymore. Depending on the state of the view, on how many nodes the user has expanded, we'd emit a different number of models every time. We cannot have a binding with this level of inconsistency.

So we're going to drop it, and that's a breaking change. This means that we would also drop `<clr-tree>` itself (unless we missed something), so we would only have a `<clr-tree-node>` component. The selection binding will now just be a simple `[(clrSelected)]` boolean binding on the tree nodes.

To obtain a "Select all" or "Select none" functionality, all the consumer will need to do is set `selected` to true or false on the root node. This will recursively select or unselect every other node.

### Proper lazy-loading (#900)

We will extract the `*clrIfExpanded` from Datagrid: https://github.com/vmware/clarity/blob/master/src/clarity-angular/data/datagrid/datagrid-if-expanded.ts
This way, nodes that are not displayed simply do not exist, and their selection state doesn't matter. It will also come with all the advantages described in #903, including good performance for trees with tens of thousands of nodes.
There are two ways to use such a directive:
```html
<clr-tree-node>
    A
    <clr-tree-node *ngIfExpanded>B</clr-tree-node>
    <clr-tree-node *ngIfExpanded>C</clr-tree-node>
</clr-tree-node>
```
```html
<clr-tree-node>
    A
    <ng-container *ngIfExpanded>
        <clr-tree-node>B</clr-tree-node>
        <clr-tree-node>C</clr-tree-node>
    </ng-container>
</clr-tree-node>
```
In both cases, B and C will be instantiated and displayed when the node A becomes expanded.

When loading new nodes asynchronously, the spinner will be displayed using [the new loading pattern](https://github.com/vmware/clarity/tree/master/src/clarity-angular/utils/loading), which is both less code for us and much easier to setup for the consumer.

### Allow recursion (#487)

When the consumers don't know the depth of the tree, their only recourse is to create a recursive component: `<my-recursive-node [node]="node"></my-recursive-node>`.
The template of this component would typically look like this:
```html
<clr-tree-node [clrLoading]="loading">
    {{node.label}}
    <ng-container *clrIfExpanded>
        <my-recursive-node *ngFor="let child of node.children" [node]="child"></my-recursive-node>
    </ng-container>
</clr-tree-node>
```
But doing so means the child nodes are hidden from `@ContentChildren`, which we use to propagate selection up and down. So we need to drop `@ContentChildren` for child detection and switch to a simple register/unregister pattern:
```typescript
ngOnInit() {
    this.parent.register(this);
}
ngOnDestroy() {
    this.parent.unregister(this);
}
```
Dependency injection follows the DOM tree and crosses components, so this will allow us to support this recursive pattern.
**The main issue with this** is that we lose the ability to keep track of the order of children. But by dropping the top-level selection binding, we now don't have a single part of the treeview that relies on this order.

### Why group them in a single task?

Each of these depends directly or indirectly on the others, and they require a big enough refactor of the tree (to make it **simpler**) that splitting them would just mean double the work for each step.
In addition, having a single, breaking change refactor of the tree will mean a single transition for the consumers. Sure we're ripping the band-aid, but having breaking changes on the tree every few weeks would be far worse.

**Comment by bashibozuk** [comment]
Guys, could you please give some estimation when do you expect this to be finished.
Thanks in advance!

**Comment by mathisscott** [comment]
@bashibozuk 
As a team, we avoid giving time-based estimations because our priorities change in real-time. 

What I can tell you about this particular issue is:

1) It is a top priority and is currently in progress.
2) It will introduce a breaking change that will kick off the work we are planning to do for 0.10.0.
3) When this item is completed, we will most likely release a 0.10.0-alpha so that people will have access to the fix and not have to wait for the other work for 0.10.0 to be completed.

Right now, this issue is at the top of our list and is currently being worked on. When the fix is submitted, we will do our best to make available to you.

Thanks for checking back in on this.

**Comment by bashibozuk** [comment]
Thanks for the fast response, good luck with the implementation!
