### ISSUE TITLE
stack view should have an option to remove the elements from DOM on collapsing.

### ISSUE THREAD

**Issue by VairavanV** [vmware/clarity#919]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
The stack-view removes the children elements from the DOM on stack-view collapse

This could be an optional param
### Actual behavior

This option is not available
### Reproduction of behavior
n/a

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:0.9.4

* **OS and version:** 

* **Browser:** chrome, firefox, IE11, edge

**Comment by mathisscott** [comment]
@youdz : Please add to backlog if this is something we want to do. Close with explanation if not.

**Comment by youdz** [comment]
Actually, this is a duplicate of #897 (which hasn't been written yet) and part of #903, so I'll close it as duplicate. But yes, we'll be working on this soon.
