### ISSUE TITLE
Alert text is not vertically centred to icon

### ISSUE THREAD

**Issue by cstranex** [vmware/clarity#92]
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Alert icons are aligned with text.

### Actual behavior
Text is slightly higher than the alert text.
![results](https://cloud.githubusercontent.com/assets/453573/20388292/dc4ae6e0-accc-11e6-9dd3-20fabd202f52.png)

### Reproduction of behavior
```
<div class="alert alert-warning alert-sm">
    <button type="button" class="close" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <div class="alert-item">
        <span class="alert-text">
            This text will not line up with icon
        </span>
    </div>
</div>
```

### Environment details

* **Clarity version: 0.7.0** 

* **Browser:** [ Chrome 54 | Firefox 49.0.2 ]

### Workaround
Specifying ```line-height: initial;``` on the alert-text will cause the text to line up correctly.

**Comment by adityarb88** [comment]
Hi @cstranex. Thanks for reporting this. I will get this fixed ASAP.
