### ISSUE TITLE
Stack view should provide an option to block the user from collapsing the stack

### ISSUE THREAD

**Issue by VairavanV** [vmware/clarity#920]
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
Stack view should take a param as a callback function when that function returns true, the user should not be able to collapse the stack block.

### Actual behavior
The option is not available currently

### Reproduction of behavior
N/A

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.94

* **OS and version:** 

* **Browser:**  Chrome XX | Firefox XX | IE 11 | Edge

**Comment by mathisscott** [comment]
@youdz, @reddolan : Opinions on this feature request?

**Comment by youdz** [comment]
I just want to point out that if we want to do this, we need a specific design for it, because preserving the exact style of a stack block for a "disabled" state would just lead to confusion.

Note that this issue is about preventing blocks from collapsing, but we could easily have the opposite case, where you prevent a block from expanding until a specific condition is met. Just making it "not expandable" would not work, because you'd have no way to distinguish a potentially expandable block that requires an action from a never-expandable one.

**Comment by mathisscott** [comment]
So let's get @reddolan 's thoughts on it and start the discussion after.

**Comment by reddolan** [comment]
@VairavanV 
- help us understand why disabling the ability to collapse is needed? 
- Can you share more information on the use case you are trying to solve for? 
- is it that you want the stack to always be open or only after a user has opened it?

**Comment by reddolan** [comment]
@VairavanV wanted to circle back with you to see if you had a chance to look over my previous questions?

**Comment by VairavanV** [comment]
usecase : We use it for edit settings. The user clicks on a  stack block to open and edit it. 
On edit, if there is a user error, we want to stop the user from collapsing it until they correct the error. 
So we dont want the block to be always open. Only if there is an error we want it to be open until the error is resolved.

**Comment by reddolan** [comment]
@VairavanV If an error exists in the stackview area, not being able to close the stack makes sense. The recommendation I can make for the design is to disable (disable cursor) the collapse chevron until the error has been corrected and then enable it again.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
