### ISSUE TITLE
[Datagrid] incorrect clr-icon vertical-align in <clr-dg-action-overflow>

### ISSUE THREAD

**Issue by siteslave** [vmware/clarity#924]
**Select one ...** 
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior

![screen shot 2560-05-14 at 11 14 31](https://cloud.githubusercontent.com/assets/526890/26031263/13d70c82-3897-11e7-914a-a034619b1241.png)

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

https://plnkr.co/edit/5adWGf1ZXyFtUXFqOswG?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:**  0.9.4

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
Hi @siteslave. Thanks for reporting this. This does look like a bug. Its happening because of the `vertical-align: bottom` style being applied to the `clr-icon`. For now you can use this style

```
.action-item clr-icon {
   vertical-align: middle;
}
```

at your end to fix this. We will track this issue and work on a fix for this soon.

**Comment by siteslave** [comment]
Thanks @adityarb88 👍
