### ISSUE TITLE
Tooltip not functional when we truncate string with ellipsis 

### ISSUE THREAD

**Issue by iivanovgit** [vmware/clarity#925]
```
[ x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
It should show us the tooltip on hover above the overflow:hidden.

### Actual behavior
The tooltip is not visible.

### Reproduction of behavior
When we hover the text we can't see the tooltip. 
By disabling the overflow:hidden from the .text-ellipses the tooltip is visible but it breaks the ellipsis effect.
https://embed.plnkr.co/SsJqTw/

### Environment details

* **Angular version:** 4.X

* **Clarity version:** 0.9.4

* **OS and version:** Windows 10

* **Browser:** all

**Comment by adityarb88** [comment]
@iivanovgit: Your `.text-ellipsis` style has `overflow: hidden` on it which is clipping off the tooltip which is the expected behavior. If you want to achieve the ellipsis effect without the tooltip getting clipped off, you could try something like this: https://plnkr.co/edit/7drLdK?p=preview

**Comment by adityarb88** [comment]
I am closing the issue based on the above comment. Please feel free to reopen if you feel that the above plunkr doesn't solve it.
