### ISSUE TITLE
Abnormal layout of drop-down menus with clr-icon in the header actions

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#926]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Good layout for the drop-down action in the header actions.

### Actual behavior
Abnormal layout: 
<img width="199" alt="2017-05-15 2 11 55" src="https://cloud.githubusercontent.com/assets/5753287/26080005/978f1c62-3979-11e7-8137-01215d5c6d32.png">

### Reproduction of behavior

> <div class="header-actions">
        <clr-dropdown clrMenuPosition="bottom-right">
            <button class="nav-icon" clrDropdownToggle>
                <clr-icon shape="cog"></clr-icon>
                <span>Preferences</span>
                <clr-icon shape="caret down"></clr-icon>
            </button>
            <clr-dropdown-menu>
                <a href="..." clrDropdownItem>About</a>
                <a href="..." clrDropdownItem>Preferences</a>
                <a href="..." clrDropdownItem>Log out</a>
            </clr-dropdown-menu>
        </clr-dropdown>

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:
https://plnkr.co/edit/1238YX

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:**  0.9.X

* **OS and version:** Mac 10.11.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@yenmade: Hey Yen. Do we want to support this (both icon + text) in dropdowns in the header? If I remember correctly we don't because of the limited space in the header. We either recommend just icon or just text, no?

**Comment by tarundhillon** [comment]
What about icon and text in clrDropdownItem, is that supported?

**Comment by adityarb88** [comment]
@tarundhillon: Yes. I believe that is supported. You should be able to use use:
```
<button href="..." clrDropdownItem>
  <clr-icon shape="home"></clr-icon>
  Home
</button>
```

**Comment by samdidos** [comment]
I've tried your example @adityarb88 and there's still a layout problem

code:
```html
...
    <clr-dropdown-menu>
        <button type="button" clrDropdownItem>
            <clr-icon style="color:black" class="is-solid" shape="wrench"></clr-icon>
            Admin
        </button>
        <a href="..." clrDropdownItem>Preferences</a>
        <a href="..." clrDropdownItem>Log out</a>
   </clr-dropdown-menu>
...
```
Screenshot : 
![dropdownlayoutissue](https://user-images.githubusercontent.com/7490081/27144918-a596e7c8-5101-11e7-8151-b1274b2f5860.png)

The wrench should be on the left side of "Admin" text. Instead it appears on the other line on the right side.

The only way I manage to have something pretty is to put only one dropdown item with an icon. This way, the wrench is in the same line as the "Admin" text but is still on the right.

It could be great to fix that :)

**Comment by tarundhillon** [comment]
This needs a little css tweak, example below should help. 


`
.menu.item.icon{
	position: inherit; 
	transform: none;
	margin-right: 1rem;
}

    <clr-dropdown [clrMenuPosition]="'bottom-right'" [clrCloseMenuOnItemClick]="false">
            <button clrDropdownToggle>
                    <clr-icon shape="ellipsis-horizontal"></clr-icon>
            </button>
            <clr-dropdown-menu>
                <label class='dropdown-header' >
                    Administration
                </label>
                <div class="dropdown-divider"></div>
                <button routerLink="metric" clrDropdownItem>
                   <clr-icon class='menu item icon' shape="block" size="30" ></clr-icon>  Metric
                </button>


                <button routerLink="data" clrDropdownItem>
                   <clr-icon class='menu item icon' shape="document" size="30" ></clr-icon>  Data File(s)
                </button>

            </clr-dropdown-menu>    
        </clr-dropdown>
`

**Comment by mathisscott** [comment]
Our recommendation is to use either text or an icon, instead of both.
