### ISSUE TITLE
The ellipsis indicator and position of action-overflow should be customized

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#927]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[X] enhancement
```

### Expected behavior
The ellipsis indicator of action-overflow can be customized. Like using some other icons or text.
The position be either first column of left side or the last column of right side.

### Actual behavior
Not be customized and position is fixed.

Users always have confusion about the action overflow. They don't know it's clickable and the related drop-down actions are bound with it. SHOULD use more obvious indicator.

### Reproduction of behavior
<NONE>

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.X

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by jaffoneh** [comment]
The recommendation is that we keep it in the same location for consistency. It is the same place we have checkboxes and radio buttons in cases of multi-select and we want to make sure consistency remains. Based on that, customizing the location is not an option recommended by our UX team. based on that, I am closing.

**Comment by pumano** [comment]
@jaffoneh I don't agree about not use datagrid ellipsis overflow as latest column. From UX point of view in any operation system or app style guides ellipsis used as latest button or as plain button with meaning "more". For example check native design guidelines: Android, BlackBerry OS 10 and etc.

Also you can check real world examples on dribbble.com using search keyword "edit table". 

I also want to use that overflow as latest column, not as first.

**Comment by jmcmichael** [comment]
I'd like to chime in to add a vote for allowing developers to place the action overflow menu, as well as choose an icon for the button.

I am working on a table with expandable rows and action overflow - this places both the action overflow and expansion controls right next to each other, causing a wide margin in the expanded content (see screenshot below). It also makes the left side of the table look a bit cluttered, IMO. I would prefer the overflow menu to be placed on the right, thus making the left side of the table less busy, and eliminate the wide left margin in the expanded content.

Additionally, the use of three vertical dots, while fitting in with the Clarity design system, might not work so well with users more familiar with design systems that use similar icons as an affordance for clicking/dragging.

![screen shot 2018-05-16 at 3 50 25 pm](https://user-images.githubusercontent.com/132909/40143397-f7e3bf06-5920-11e8-965c-4b8ffdbc1648.png)

**Comment by quanglddev** [comment]
In the mean time, is there any possible workaround to change the icon in the source code?
Thank you
