### ISSUE TITLE
[Datagrid]:ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

### ISSUE THREAD

**Issue by steven-zou** [vmware/clarity#928]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No error should appear when loading items to datagrid view with 'clr-dg-action-overflow' and '*ngFor' iterator.

### Actual behavior
Error is thrown in console:
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'.

### Reproduction of behavior
https://plnkr.co/edit/ADIq2O

Notes: If you comments the 'clr-dg-action-overflow', the error will be gone!

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.X

* **OS and version:** Mac 10.11.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
@steven-zou : I believe this issue is related to #623 which @youdz has been working on. I'm leaving open for now so we can circle back to verify if it is fixed or not when #623 is completed.
