### ISSUE TITLE
contained datagrid has mysterious sizing on the last header column and does not occupy the requested dimensions ( width )

### ISSUE THREAD

**Issue by mattmutt** [vmware/clarity#937]
**Select one ...**  (check one with "x")
```
[x ] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
when a datagrid is held in a sized DIV with a FIXED width and height, the grid should generally fit, and if there is scrolling, it should be calculated correctly

### Actual behavior
There is plenty of space in a 500px wide container, yet a scroll bar appears. Why is the last column sized to 96 pixels? Never expressed that intent in the markup.

### Reproduction of behavior
https://plnkr.co/edit/zI404dhrPDQt2rlEHndJ
### Environment details

* **Angular version:** 4

* **Clarity version:** 0.9.x

* **OS and version:** 

* **Browser:** [all  ]

**Comment by Shijir** [comment]
@mattmutt I think the problem is coming from that unwanted min-width which actually comes in the `clr-dg-column` by default. But you as a user can always change that `min-width` in `clr-dg-column`. 

```
clr-dg-column {
  min-width: 0px; //or any value you want.
}
```

**Comment by mattmutt** [comment]
@Shijir  - it works for initial viewing. however resizing a column a few pixels causes the proportions to get messed up. Is that acceptable. 

And the horizontal scrollbar appears over time if you resize enough. Maybe that is due to some columns starting to have a "fixed" pixel width now and the percentage no longer applies?  

Do you think percentage based header layouts are problematic? Because once you resize their percentage is "lost"?

I updated the above plunker

**Comment by Shijir** [comment]
@mattmutt yes, I am also speculating that using percentages in the column width is causing this issue. Will look into this problem. Thanks for getting this to our attention.

**Comment by gnomeontherun** [comment]
Seems to be an issue, not sure how we want to resolve this yet. Moving to new milestone.

**Comment by gnomeontherun** [comment]
This issue is about a version of Clarity that is out of support. In an effort to better manage our backlog, we are closing this issue. We recognize that some of these issues may remain problematic for you, but to help us to be able to prioritize it we ask for a new GitHub issue with an updated demo with a recent supported version of Clarity.
