### ISSUE TITLE
Fix issue in Clarity Icons where minifying is failing on kebab-case

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#940]
We can't rely on kebab-case surviving minification processes. @Shijir found a way where we can fix the issue without any deprecations or breaking changes. We're going to go with that.

**Comment by mattmutt** [comment]
the syntax although alien looking with the dashes in the method names is valid. The minifiers have some buggy logic OR don't have the right mangler options turned ON to preserve the quotes the Clarity supplied in the first place around the methods like `"note-edit"()`

**Comment by mathisscott** [comment]
@mattmutt 
You’re right that the syntax is valid and that the real problem is minifiers that are either improperly configured or just buggy.

The challenge for us, however, is that we have no control over users’ minifiers.

Frankly, the difference between kebab-case and snake_case is trivial for me. And switching from one to the other is more of a chore than a technical accomplishment.

But the value, I think, is that we are supporting users of Clarity Icons by naming icons in away that would result in valid un-quoted property names even if their minifiers are messed up.

The drawback is kebab-case feels more CSS. You see other icon libraries (font-based, mind you) using kebab-case so we seem like an outlier. But I think this is worth it to go the extra mile and solve this problem for users that they might not even know they have.
