### ISSUE TITLE
Datagrid Expandable rows manually trigger

### ISSUE THREAD

**Issue by aavelyn** [vmware/clarity#948]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
have a binding exposed so that I can expand specific row/rows with javascript.

### Actual behavior
can only open rows by click on the carret.

**Comment by mathisscott** [comment]
@youdz 
Please triage. I was under the impression users could already do this...

**Comment by youdz** [comment]
It already exists, we have a `[(clrDgExpanded)]` two-way binding on the rows themselves.
