### ISSUE TITLE
Stack View header style does not match state on repeated clicks

### ISSUE THREAD

**Issue by karmasakshi** [vmware/clarity#949]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Class `stack-block-expanded` should be added only when the Stack View is expanded.

### Actual behavior
Attached screenshot demonstrates how on clicking quickly (odd no. of times), one can achieve a disconnect between the state and the style of the Stack View header.

### Reproduction of behavior
Issue can be reproduced on the [Stack View documentation](https://vmware.github.io/clarity/documentation/stack-view) page under the **Angular stack view** section.

### Environment details

* **Angular version:** 4.1.1

* **Clarity version:** 0.9.5

* **OS and version:** macOS 10.12.4

* **Browser:** Tried on Chrome 58 and Safari 10.1.

### Screenshot

![Screenshot](https://cloud.githubusercontent.com/assets/4698762/26276213/3c3da318-3d90-11e7-9a99-80ac378dfcfb.png)

**Comment by mathisscott** [comment]
@youdz 
We need this triaged and prepped for contribution...

**Comment by youdz** [comment]
It's an actual bug, yes. It was thoroughly tested at the time stack view was written, but that was back when Angular 2 was still in beta. 😂 

So it could really be anything that broke the behavior: angular updates, animation updates, ... I would need to actually investigate to provide a proper estimate.

**Comment by gnomeontherun** [comment]
I reviewed this, and cannot reproduce it on the current documentation site.

I click quickly 9 times, and it resolves to being open as I would expect. The styling and classes appear to be resolved as expected as well. Can someone else confirm this is no longer reproducible?

**Comment by karmasakshi** [comment]
Fixed. Confirmed.
