### ISSUE TITLE
when migrating to datagrid with flex, columns are not properly resized

### ISSUE THREAD

**Issue by dedalusmax** [vmware/clarity#951]
[x] bug
[ ] feature request
[ ] enhancement

Expected behavior:
Our grid has data in cells that are too wide. In that case, column headers and row cells should widen to display full data (as in version 0.8.x before flex display was introduced).

Actual behavior:
The texts in cells are overlapping.

with 0.8.4 version:
![capture1](https://cloud.githubusercontent.com/assets/8254665/26309274/a8b4ece6-3efc-11e7-8f2d-2def9489e019.PNG)

with newest clarity version:
![capture2](https://cloud.githubusercontent.com/assets/8254665/26309286/b6598f46-3efc-11e7-9bfc-e4abd6aa3b36.PNG)

##Environment details

Angular version: 4.1.0

Clarity version: 0.9.5-patch

OS and version: 

Browser: all

**Comment by youdz** [comment]
Please post a plunker reproducing the issue, it doesn't seem to happen when I try. The columns are sized correctly to accommodate the long strings.

**Comment by dedalusmax** [comment]
here it is:
https://plnkr.co/edit/7MDDnR

**Comment by mathisscott** [comment]
@dedalusmax : Is that the right plunkr link? It doesn't appear to demonstrate the issue described above.

**Comment by dedalusmax** [comment]
how not? here is the screenshot from the plunkr:

![capture](https://cloud.githubusercontent.com/assets/8254665/26437583/4de5444a-411e-11e7-93a5-4d7a895f3058.PNG)

**Comment by adityarb88** [comment]
@dedalusmax: doesn't look like the right one to me. I see this:

![image](https://cloud.githubusercontent.com/assets/1426805/26458037/057b3670-4127-11e7-9ee6-8a245618f973.png)

**Comment by youdz** [comment]
I don't think you saved the plunker, or you shared the wrong link. When I look at your link, the datagrid's HTML only contains 2 columns, and it indeed looks like this:
![screen shot 2017-05-25 at 12 30 45](https://cloud.githubusercontent.com/assets/4647197/26459981/426fea5c-4146-11e7-8eb9-e846e084a069.png)
Could you either update this plunker or send us the correct link? Thank you.

**Comment by dedalusmax** [comment]
it must be the following:
https://plnkr.co/edit/7MDDnR?p=preview
