### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by taivu** [vmware/clarity#952]
`npm WARN clarity-icons@0.9.5 requires a peer of @webcomponents/custom-elements@1.0.0-rc.3 but none was installed.`

`@webcomponents/custom-elements@1.0.0` is out of release candidate. could we update this dependency?

**Comment by adityarb88** [comment]
@taivu: Thanks for raising this issue. We already have an issue tracking this: https://github.com/vmware/clarity/issues/916 Please subscribe to #916 for more updates. Closing this as duplicate.
