### ISSUE TITLE
tooltip cannot be displayed in flex datagrid

### ISSUE THREAD

**Issue by dedalusmax** [vmware/clarity#953]
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Tooltip is displayed for datagrid cell

### Actual behavior
after upgrading to datagrid 0.9.x, tooltip cannot be displayed any more on cell hover.

BEFORE (0.8.4):
![capture](https://cloud.githubusercontent.com/assets/8254665/26344279/552ac994-3f9f-11e7-9e83-29a4f479ef1b.PNG)

AFTER (0.9.x):
![capture2](https://cloud.githubusercontent.com/assets/8254665/26344283/5799e17e-3f9f-11e7-95f5-e806aa8abc7f.PNG)

Code I use:

``
<clr-datagrid id="printSection">

        <clr-dg-column class="no-print action-buttons-column">&nbsp;</clr-dg-column>
        
        <clr-dg-row *clrDgItems="let user of users | search: searchText" (click)="editUser(user.userId, $event)" >

            <clr-dg-cell class="no-print">
                <div class="action-buttons">
                    <span role="tooltip" aria-haspopup="true" class="tooltip tooltip-sm tooltip-top-left">
                        <clr-icon shape="key" size="16" (click)="changeUserPassword(user.userId, $event)"></clr-icon>
                        <span class="tooltip-content">{{ 'USERS.CHANGE_USER_PASSWORD' | translate }}</span>
                    </span>

                </div>
            </clr-dg-cell>
        </clr-dg-row>

        <clr-dg-footer>

        </clr-dg-footer>
    </clr-datagrid>

``
### Environment details

* **Angular version:** 4.1.x

* **Clarity version: 0.9.x

**Comment by mathisscott** [comment]
@dedalusmax 
Another plunkr here too?

https://plnkr.co/uNwwZe

**Comment by dedalusmax** [comment]
here it is:
https://plnkr.co/AhbCgI

**Comment by adityarb88** [comment]
@dedalusmax: Please try using the tooltip angular component. Created a plunkr that you can refer too: https://plnkr.co/edit/EjwoTC?p=preview

**Comment by dedalusmax** [comment]
now the tooltip is correctly displayed, except for color, which is blue. and when i click the icon, it has a rectangle around it. is there any way to circumvent this?

**Comment by dedalusmax** [comment]
ok, got it solved via style. thank you for your support.
