### ISSUE TITLE
when using dynamic columns, column width is not recalculated

### ISSUE THREAD

**Issue by dedalusmax** [vmware/clarity#954]
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Column width should be recalculated (widen to show properly text box instead of span).

### Actual behavior
Column width is fixed in width.

BEFORE (0.8.4):
(before in-place editing row)
![capture](https://cloud.githubusercontent.com/assets/8254665/26345257/a70e7e60-3fa2-11e7-8b58-1190c5ae3e09.PNG)

(when triggering editing)
![capture2](https://cloud.githubusercontent.com/assets/8254665/26345261/ac4948b0-3fa2-11e7-9fc9-6db99d2e3ef2.PNG)

AFTER (0.9.x):
(when triggering editing)
![capture3](https://cloud.githubusercontent.com/assets/8254665/26345269/b18bc514-3fa2-11e7-9a11-7816c11a3258.PNG)

part of the code that displays grid:

``    <clr-datagrid>
        <clr-dg-column>&nbsp;</clr-dg-column>
        <clr-dg-column *ngFor="let zone of depotZones">{{zone.name}}</clr-dg-column>

        <ng-container>
            <clr-dg-row *ngFor="let destination of walkingDistance.destinationHeader; let i=index">
                <clr-dg-cell>{{destination.name}}</clr-dg-cell>
                <clr-dg-cell *ngFor="let d of walkingDistance.depotZoneHeader; let j=index">
                    <div [hidden]="isEditMode">
                        {{walkingDistance.walkingDistanceMatrix[i][j]}}
                    </div>
                    <div [hidden]="!isEditMode">
                        <input #input type="number" min="0" [value]="walkingDistance.walkingDistanceMatrix[i][j]" (change)="setWalkingDistance(i, j, input.value)" />
                    </div>
                </clr-dg-cell>
            </clr-dg-row>
        </ng-container>

        <clr-dg-footer></clr-dg-footer>

    </clr-datagrid>
``

### Environment details

* **Angular version:** 4.1.x

* **Clarity version: 0.9.x

**Comment by mathisscott** [comment]
@dedalusmax 
Could you create a plunkr with your example? https://plnkr.co/uNwwZe

It will help us triage the issue. Thanks.

**Comment by youdz** [comment]
This is an edge case that has been raised before, and we cannot take the risk of constantly recomputing the columns widths. Because of this, we decided to offer a `resize()` method on the Datagrid itself to have it re-compute column sizes whenever you need to (as opposed to every change detection cycle).

So in your case, when switching from read-only to inline edit and vice-versa, you'd just call `datagrid.resize()` after the change and the columns should resize accordingly. I hope this helps.

**Comment by dedalusmax** [comment]
this works, BUT only with triggering the resize inside window.setTimeout. and it's pretty slow on big data (I have a matrix of 32 cols and 50 rows). I wonder why it is constructed this way in the recent versions, since with 0.8.4 everything worked smoothly. :(
