### ISSUE TITLE
[Datagrid] Using *clrDgHideableColumn with a datagrid containing a dropdown menu throws error

### ISSUE THREAD

**Issue by jbgarr** [vmware/clarity#956]
```
[ X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I should be able to use both the *clrDgHideableColumn directive and a dropdown in a table row cell without any issues.

### Actual behavior
Currently using both together results in the following error:
`
ERROR TypeError: Cannot read property 'id' of undefined
`

I also want to note that the only reason that I'm currently using the dropdown instead of the `clr-dg-action-overflow` element is that I'm waiting on a bug fix [#744](https://github.com/vmware/clarity/issues/744).

### Reproduction of behavior
https://plnkr.co/edit/V2EJ0aKrUEqPSUChb8i9?p=preview

### Environment details

* **Angular version:** 4.0.X

* **Clarity version:** 0.9.X

* **OS and version:** macOS Sierra

* **Browser:** Chrome

**Comment by hippee-lee** [comment]
Thanks for reporting this, its related to this issue #837.

**Comment by mathisscott** [comment]
This appears to be fixed now. The plunkr works on latest Clarity.
