### ISSUE TITLE
Dropdown/nested menu documentation: Need corrections and update of images

### ISSUE THREAD

**Issue by lil-kim** [vmware/clarity#957]
**Select one ...**  (check one with "x")
```
[ X] bug
[ ] feature request
[ ] enhancement
```
### Numbered Items in corrections png correspond to list here:
1. Replace image w/ 2x version (for sharpness on Retina)
2. Need padding 24px between h3 and list
3. Reduce padding to 72 px
4. Make columns equal. Center align “vs” circle horizontally.
5. Insert updated text:
- (h6) **Dropdown menus** (p1) present a list of options that take an immediate action or navigate the user outside of the current context.
- (h6) **Select Boxes** (p1) present a list of options from which the user can choose and apply to an input field.

**Comment by jeeyun** [comment]
Addressed most of the issues in PR #972. Remaining item is moved to a new issue (#973).
