### ISSUE TITLE
datagrid gets cut off when paging

### ISSUE THREAD

**Issue by dedalusmax** [vmware/clarity#958]
[x] bug
[ ] feature request
[ ] enhancement

### Expected behavior
The grid should display correctly.

### Actual behavior
When paging the grid, when going into second page, datagrid gets cut off for the last column: see the screenshots.

on the first page:
![capture](https://cloud.githubusercontent.com/assets/8254665/26394164/52044146-406c-11e7-973e-4e2dcd332073.PNG)

on the second page:
![capture2](https://cloud.githubusercontent.com/assets/8254665/26394168/54d987dc-406c-11e7-8a0c-bb57d9c20939.PNG)

### Environment details

* **Angular version:** 4.1.x

* **Clarity version:** 0.9.x

UPDATE:
I've tried to correct the behavior with earlier proposed datagrid.resize() method (inside window.setInterval, since without it doesn't work), but then the rest of the grid is empty, that is, the complete datagrid height doesn't shrink:

![capture3](https://cloud.githubusercontent.com/assets/8254665/26399576/b1523f48-407d-11e7-8eaa-b183e6c06996.PNG)

**Comment by mathisscott** [comment]
@dedalusmax 
I'm not able to reproduce this issue. Could you please supply a [plunkr](https://plnkr.co/uNwwZe) for it?

**Comment by mathisscott** [comment]
@dedalusmax 
I haven't heard back on this one and cannot reproduce. Closing for now.
