### ISSUE TITLE
Wizard enhancement to support, routes based wizard pages

### ISSUE THREAD

**Issue by rangagv** [vmware/clarity#961]
Hi,
<img width="1353" alt="wizard" src="https://cloud.githubusercontent.com/assets/6545268/26409233/9b794f0a-40bd-11e7-8400-500b8defd775.png">
<img width="715" alt="wizard_requirement" src="https://cloud.githubusercontent.com/assets/6545268/26409238/9e395eba-40bd-11e7-88e2-76a5a35320b9.png">

We were going through some of the samples for clarity wizard component.

Our observation was that it expects the wizard to always open inside a clarity modal.
Is there a way there to remove the dependency on the clarity modal.

Reason we want to do the this is that we want to use the wizard component in html plugin and leverage vsphere web platform’s open modal dialog api for rendering it.
If I do that with existing component, this is how it looks (outer modal is vsphere web platform modal and inner one is the clarity modal): Please check screenshot 1 (wizard)

Also, the wizard pages and wizard-title components are ng-content based.
Is there a way to make it routes based?

e.g:
Existing sample:

Wizard Title

Do I have a way to use it like this:

Wizard Title

Step 1

Reason for this approach is that our wizard workflows are busy and have lot of components.
So I do not intend to load all the wizard pages upfront in the DOM.
Here is screen shot of one of the pages from out wizard: Please check screen shot2(wizard_requirement)

**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.8

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by mathisscott** [comment]
To clarify, this is specifically about a route-based wizard component which may or may not require a new component to be built.

**Comment by mathisscott** [comment]
This would be something that would be much easier to work with in the minimally stateful wizard we are planning to work on for `@clr/core`. As a result, I'm marking this as a documentation requirement (providing an example) of how the core wizard would be used in this way and associating it with the core wizard epic.

**Comment by kumar-tadepalli** [comment]
I have the same requirement for vSphere HTML plugin.
Can we use .clr-wizard--inline in Clarity v4?
Are there any plans to deprecate in future versions?

**Comment by gnomeontherun** [comment]
@shravansofts we have not removed the inline wizard from Clarity Angular. We have not yet built a Clarity Core wizard, but the inline wizard is not currently a documented or official feature, so I can't guarantee we'll support it with Clarity Core.

**Comment by gnomeontherun** [comment]
This is a worthwhile enhancement request, but is challenging to implement due to the existing behaviors and nature of Clarity Angular. As we build out Clarity Core, this should be possible to realize with the applications managing the state and functionality more directly instead of Clarity Angular. 

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
