### ISSUE TITLE
Feature Request:  Text Input should support an optional Clear function

### ISSUE THREAD

**Issue by joshjohnsonux** [vmware/clarity#963]
**Select one ...**  (check one with "x")
```
[ ] bug
[x] feature request
[ ] enhancement
```

### Expected behavior
In some cases text inputs are used to insert long strings, and the removal of the long strings may be tedious.  In such case, it's useful to present a "clear" button at the end of the input to immediately remove everything in the input value.  Search and Filter inputs tend to be the most common cases requiring this feature, but others may exist.

### Actual behavior
Feature doesn't exist

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 0.9.X

**Comment by reddolan** [comment]
This was something that was spec'd out in the Search Design on #186

**Comment by colinreedmiller** [comment]
Changing #2718 to UX Ready - please make sure to enable the clear function in the date picker when addressing this.

**Comment by gnomeontherun** [comment]
Ok I didn't have time to setup a sync.

1) The optional clear function can be added but require that it is placed inside of an `clr-input-container` to work properly. I'm ok with that, its a new feature and won't work without it.
2) Look at the DOM structure of input groups in the dev app and the password. That is something we'd have to support (conditionally) when using this functionality. It makes for a more complicated template, which is the main challenge I see in this feature. There should be no need to set explicit widths.
3) Good question about should the clear button be there always or not. With the input group layout, it could be hidden until the control is dirty, which makes sense to me, and still hold the space. The validation icon is the right padding you highlighted above, which needs to be retained.
4) Color-wise, let's use the default colors and we'll get UX to confirm.
5) This can be done without breaking changes, but if you are concerned about that then I would shelve it for something different.

**Comment by mathisscott** [comment]
@gnomeontherun 
Have we considered what we would do for browsers (like IE, Edge, and some types of form fields in Chrome) that add this functionality all on their own?

**Comment by gnomeontherun** [comment]
My thinking was we'd disable/remove the behavior if we are implementing it ourselves. There are pseudo selectors to target this IIRC.

**Comment by andreiconstantinbytex** [comment]
I would like to be assigned to this issue.

**Comment by KANekT** [comment]
in progress or hold this issue ?

**Comment by gnomeontherun** [comment]
Its currently in backlog.

**Comment by gnomeontherun** [comment]
The feature request here has been captured into our list and we’re going to take it into consideration as we develop Clarity Core capabilities. In an effort to clean up our backlog and focus our attention, I’m going to close this as captured in our feature requests. Please follow our development and releases to see when we release relevant components to make this possible. Future feature requests can be made in our [GitHub Discussions](https://github.com/vmware/clarity/discussions).
