### ISSUE TITLE
Sketch Template:  Radio buttons don't resize correctly

### ISSUE THREAD

**Issue by joshjohnson72** [vmware/clarity#964]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
When resizing a radio button component, the radio button should remain pinned to the left edge, like checkboxes do.

### Actual behavior
Resizing a radio button component makes the radio button itself move and resize.  

### Environment details

* **Sketch version:** 43.2

* **Clarity Template version:** 0.9.0

**Comment by reddolan** [comment]
So, with the recent changes to resizing in Sketch 44, this is a much bigger issue than just Radio buttons. The entire Template and Library needs to be looked at and likely updated.

**Comment by reddolan** [comment]
Completed with #1077
