### ISSUE TITLE
Update sketch template for dark theme for 10.19

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#967]
Do we update the existing sketch template or create a new one?

Do we update the Craft library as well?

**Comment by reddolan** [comment]
Good questions

**Comment by mathisscott** [comment]
Passing over to @reddolan to create Dark Theme Sketch Library after dark theme implementation is approaching completion per discussion at this week's UX meeting.

**Comment by lil-kim** [comment]
Dark Theme Sketch template is ready to post on site:
[Clarity-UI-Library-dark-0.10.11.zip](https://github.com/vmware/clarity/files/1577350/Clarity-UI-Library-dark-0.10.11.zip)

**Comment by hippee-lee** [comment]
Adding to get-started on website.
