### ISSUE TITLE
Implement dark theme

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#968]
Of particular interest:

How do we package and deliver the dark theme?
Does it need to be bundled with our CSS by default? Does it have to be?

**Comment by lil-kim** [comment]
@hippee-lee 
Hi Matt, attached are button states and some other misc components for the dark theme.
[dark theme 5-1.zip](https://github.com/vmware/clarity/files/1126400/dark.theme.5-1.zip)
Let me know if you have any questions. I'll continue to work on the remaining elements and deliver them in increments.
Thank you!

**Comment by mpicard** [comment]
@el-davo
