### ISSUE TITLE
Minor: Debug code left in datagrid.ts

### ISSUE THREAD

**Issue by amellnik** [vmware/clarity#97]
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
No messages printed to the console from normal datagrid behavior.  

### Actual behavior
Prints the number of empty rows.

### Reproduction of behavior
Can be seen in demo app [here](https://amellnik.github.io/clarity-demo/tables).

### Environment details

* **Angular version:** 2.1.0

* **Clarity version:**  0.7.0

* **OS and version:** Win8.1 x64

* **Browser:** All

Line of code in question is [here](https://github.com/vmware/clarity/blob/1889971fe3a91f30ce4dffaf101fd524b2e678e2/src/clarity/datagrid/datagrid.ts#L145).

**Comment by youdz** [comment]
Thanks for noticing, we removed it as part of a "misc fixes" for Datagrid, which should go in tonight. 0.7.1 will not have the log anymore.
