### ISSUE TITLE
Documentation for signpost component

### ISSUE THREAD

**Issue by mathisscott** [vmware/clarity#971]
Create documentation for signpost component in new layout style.

**Comment by lil-kim** [comment]
**Here's the layout and accompanying images (@2x size for retina):**
[Doc Layout and Images.zip](https://github.com/vmware/clarity/files/1053317/Doc.Layout.and.Images.zip)

----------------------Doc begins here-------------------------
(h5) The signpost is a convenient, lightweight way to show contextual help or information without taking the user out of the current context.

(h3)Examples
![image](https://cloud.githubusercontent.com/assets/23196444/26805047/1cf9bf16-49ff-11e7-972c-1b4a10775613.png)

(h3) Description

(p1) A signpost displays contextual help or information in a popover dialog. Like a tooltip, it has an arrow/pointer that extends out to the trigger element, but the dialog is larger to fit more content. Signposts are designed to show a relatively small amount of content which may include: a title, images, text links or image links. A vertical scrollbar (browser default) may be used if the content exceeds the maximum height of the dialog.

(h5) Size
- Min-width  216 px;  Min-height  84 px
- Max-width  360 px;  Max-height  504 px

(h3) Usage

(p1) Signposts should be used when you want to show a small amount of contextual help or information without taking the user out of the current context. Use sparingly as a supplemental element and not as a primary method of adding detail.
- May be used when the amount of content won’t fit in a tooltip
- When you want to include a header, image or text/image links in the content 
- When the information presented needs to stay in view at length. Unlike tooltips, signposts stay in view until the user dismisses it. Users may interact with other elements on the page while the dialog is visible.

(h3) Interaction
(p1) Clicking the icon triggers the signpost. It remains visible until the user clicks the close icon or clicks anywhere outside of the dialog to dismiss it. To keep the interface uncluttered, only one signpost is displayed at a time. When a dialog is visible, clicking an icon to open another one automatically dismisses the previous dialog. 
![image](https://cloud.githubusercontent.com/assets/23196444/26805165/91ea4304-49ff-11e7-8cab-d1e30a188a74.png)

(h3) Trigger icon and dialog positioning
![image](https://cloud.githubusercontent.com/assets/23196444/26805189/abc4d0d2-49ff-11e7-9986-d6e96b7dbef9.png)
(p1) The default position for the dialog is 6 px to the right of the trigger icon. If space doesn’t permit, the position should adapt according to space available.

![image](https://cloud.githubusercontent.com/assets/23196444/26805233/e057ccd2-49ff-11e7-9aaf-e7948768d1d6.png)
(p1-Left image caption) Default position for the icon is 6 px from the end of the text
(p1-Rt image caption) In tables, the icons may be aligned in a column

(h3) Recommendations
(p1)The popover should not be so large that it dominates the screen
- Make sure that the popover doesn’t obstruct other important information on the screen
- With the exception of text/image links, don’t insert any actionable components, such as buttons, in the dialog
- Don’t rely on signposts as a primary method of displaying additional information, ie: as a way to save space on the page. Use sparingly as a device to add immediate, relevant information.
----------------------End of Doc-------------------------
Followed by "Code and Examples"
