### ISSUE TITLE
[web] improve styling for vs box

### ISSUE THREAD

**Issue by jeeyun** [vmware/clarity#973]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

The vs box should display with equal width so the vs is centered. Punted from #972 as I haven't found a cross-browser solution yet (but wanted to publish an update for the other changes that are ready).

### Actual behavior

Right now, the vs box may display two items of different widths if the texts accompanying the two items are of different lenghts as shown in the dropdown doc:
![screen shot 2017-05-24 at 6 25 24 pm](https://cloud.githubusercontent.com/assets/1827742/26432164/959c5c58-40ae-11e7-89b9-5816a496fc7d.png)

### Reproduction of behavior
Seen in dropdown doc:
https://vmware.github.io/clarity/documentation/dropdowns

**Comment by bangelakos** [comment]
Adding max-width: 47% to .clrweb-DoxVersusBox-itemWrapper solves the issue.

**Comment by coryrylan** [comment]
Closing for Website revamp 2020
