### ISSUE TITLE
Create a mechanism for disabling the sidenav buttons of the Wizard Component

### ISSUE THREAD

**Issue by malkoto1** [vmware/clarity#979]
**Select one ...**  (check one with "x")
```
[ ] bug
[X] feature request
[ ] enhancement
```

### Expected behavior
There must be an easy mechanism for disabling the the buttons in the sidenav of the Wizard component.

### Actual behavior
In order to disable the sidenav buttons, which is fairly common, by my opinion, one must perform a not that beautiful workaround. The current easiest workaround is to use some kind of overlay.
* Workaround link: https://plnkr.co/edit/vlWGED?p=preview

### Environment details

* **Angular version:** 4.0.1

* **Clarity version:** 0.9.x

* **OS and version:** macOS Sierra 10.12

* **Browser:** [all]

**Comment by mathisscott** [comment]
This is a feature that wasn't included as part of our core set of functionality for the wizard and probably should have been. The workaround included above is okay but this should be able to be toggled at the wizard level with an input that toggles off all navigational elements in the wizard.
