### ISSUE TITLE
Chips/Tags Component

### ISSUE THREAD

**Issue by gerinjacob** [vmware/clarity#980]
**Select one ...** 
- [ ] bug
- [x] feature request
- [ ] enhancement

### Expected behavior

Need an angular component `clr-chips` that can be used to enter multiple values on an input field using chips. [PrimeNG has a similar implementation](https://www.primefaces.org/primeng/#/chips). However, it has some limitations. Expected additional features on top of [PrimeNG](https://www.primefaces.org/primeng/#/chips) are,
1. PrimeNG chips gets added only on pressing return key. Need flexibility to accept other keys (customizable) like space, semi-colon. May be it can accept a regex attribute `clrSeperator` to accept other keys.
2. Should have a `clrPattern` attribute to specify a regex, the value is checked against. Helps in putting validations like email.
3. Should have support for more events like onChange, onBeforeAdd. That will give hooks to provide additional validations like duplicate check.

![image](https://cloud.githubusercontent.com/assets/7568688/26489471/241fc0ce-4225-11e7-9b80-020419d1267a.png)

### Usage
```
<clr-chips [(ngModel)]="array"
    [clrSeperator]="regex" 
    [clrPattern]="regex"
    [clrPlaceholder]="string"
    [clrReadonly]="boolean"
    [clrMax]="number"
    (clrAdd)="function"
    (clrRemove)="function"
    (clrChange)="function"
    (clrBeforeAdd)="function">
</clr-chips>
```

### Actual behavior

Clarity does not have an angular component like this.

### Environment details

* **Angular version:** 4.X.X

* **Clarity version:** 0.9.X

**Comment by mathisscott** [comment]
Thanks for the suggestion @gerinjacob and the detailed example in usage.

Our UX team needs to take a look at this and make their recommendation on it.

**Comment by gerinjacob** [comment]
After ux input, I can work on the implementation if that's all right.

**Comment by gerinjacob** [comment]
Any update from UX?

**Comment by mathisscott** [comment]
@gerinjacob
UX is currently working on other prioritized items. If you can give us more information on your use case and what is driving the urgency of this feature for your team, I can take this information back to them to re-assess.

**Comment by Jinnie** [comment]
It is not much different than the multiselect option of this issue, methinks:
https://github.com/vmware/clarity/issues/248

**Comment by gerinjacob** [comment]
@Jinnie yes it is similar to #248, but with some difference. The use case is for email field where we can add multiple email ids. Features required are,
- It should be a free text and not a drop down with values
- Support for multiple separators. A space, semi-colon should treat as next email id (`[clrSeperator]="regex"` for this purpose)
- Requires validation (`[clrPattern]="regex"`)
- Readonly (`[clrReadonly]="boolean"`)
I have already created this component. If required I can contribute this to clarity.

**Comment by youdz** [comment]
I'll wait for UX to come up with a review and maybe designs, but what I can already say is that we really try to stay away from PrimeNG-like APIs where you have, just like you posted, 10 different inputs/outputs on the same element. It goes against everything we go for with a declarative API.

So depending on the use cases our UX team decides to address and the different options we want to support, we'll have to decide what we want the API for this component to look like. Just expect it to be very different from what you posted, and as such to have a very different implementation from what you already have. We'd still be happy for contributions. 😄

**Comment by manndave** [comment]
FWIW, my $.02...I'd like to see the option of a fixed selection list, like the multi-select in  #248 but not be forced into just those choices.  Also, the ability to make some chips/tags static, ie. not removable would be great for my use case...
Thx.

**Comment by reddolan** [comment]
I have read this over a couple times. This is quite similar to #248 as mentioned, with some additional features. We should approach it that way as well, versus creating a separate component that behaves almost identically. 

Additional features I see:
- ability to add new options that aren't part of the option list, done while typing
- read-only
- validation design

Features not being implemented:
- No dropdown with values. Dropdown with values will stay as it provides feedback to the user of values that are available matching the string typed
- Support for multiple separators. Won't need to have this, as the "new option" experience would keep the user from needing to type additional characters

Let me know if I missed anything

**Comment by gerinjacob** [comment]
@reddolan additional features you have covered looks good. Hence closing this request.
