### ISSUE TITLE
Radio Buttons need zIndex in their style

### ISSUE THREAD

**Issue by bbronson** [vmware/clarity#988]
**Select one ...**  (check one with "x")
```
[X] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
I expect to be able to add a Clarity radio button inside a modal and add event handlers like (click) and get them to fire.

### Actual behavior
The event handlers do not fire.

### Reproduction of behavior
I found this bug today while trying to add Radio Buttons inside a modal with event handlers on them. The event handlers do not fire. The reason is the :before element is showing up on top of the input element. The easy CSS solution is to give the radio button inputs a z-index. I am now adding that override locally but you should fix it in the base product.

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details
2.4.1
* **Angular version:** 2.0.X
0.9.2
* **Clarity version:** 
Mac OSX 
* **OS and version:** 
Chrome 58.0.3029.110 (64-bit)
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by adityarb88** [comment]
@bbronson: Could you please post a plunkr replicating the issue? https://plnkr.co/edit/uNwwZe?p=info

**Comment by youdz** [comment]
Even without the plunker, I can already tell you that binding to the click event on radio buttons is a bad idea, because it's not accessible (and as a side effect, it will not work when a label is clicked). You want to listen to the change event, or even better, just use `[ngModel)]` two-way binding.

**Comment by bbronson** [comment]
Hi Aditya, 

I'm not going to upload the code because it is proprietary, and you can easily reproduce this with a clarity modal and a clarity radio button and any even handler, doesn't have to be onclick.

Thank you Youdz, I will keep that in mind, its just that this affects every event binding (mouseover, toggle, whatever) and it should be an easy fix for the Clarity team.

**Comment by adityarb88** [comment]
@bbronson: You don't have to upload your code. You just have to provide a simple reproduction of the error that you are facing in a plunkr. Without the plunkr we won't be sure if we are actually looking at the issue that you are facing. Thanks!

**Comment by bbronson** [comment]
Nevermind, I've upgraded to the latest Clarity version and latest clr-model and this issue seems to be resolved. Marking as closed.
