### ISSUE TITLE
Forms Layout and Input controls look uglier than most web form controls design

### ISSUE THREAD

**Issue by whizkidwwe1217** [vmware/clarity#989]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Expected behavior

I wish the input controls could have a very nice and clean design like the sample image below:
![image](https://cloud.githubusercontent.com/assets/1977391/26530518/a02d36c6-4408-11e7-8de7-bcef216b59f9.png)
### Actual behavior

The labels in the forms layout are eating a lot of space and it would look pretty good when text fields have full borders.
![image](https://cloud.githubusercontent.com/assets/1977391/26530522/d5626e42-4408-11e7-9c66-2c221754b146.png)
In the screenshot below (taken from the samples), the form kinda look pretty messed up and not a very clean design, maybe it's because of the bottom-only border of the input controls:
![image](https://cloud.githubusercontent.com/assets/1977391/26530681/4dd62ee2-440c-11e7-8725-f8da5e87af40.png)

So far, the rest of the components are pretty good but only the form controls I find very disappointing.
### Reproduction of behavior

* Include a link to the reproduction scenario you created by forking one of the Clarity Plunker Templates:

### Environment details

* **Angular version:** 2.0.X

* **Clarity version:** 

* **OS and version:** 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by whizkidwwe1217** [comment]
You could take a look at this [https://ant.design/components](https://ant.design/components). Although I don't like the typography but it's a very decent UI library.

**Comment by mathisscott** [comment]
@whizkidwwe1217
Thanks for the feedback on our form design. We appreciate your input. If you need to restyle the form fields for your application, you can do pretty much anything you with them using CSS. 

The Clarity UX team put a lot of research and effort towards the current design. We are committed to supporting the clean, minimal look of our forms through 1.0. We will take your feedback under consideration when the time comes for us to revisit the visual design for 2.0. 

Thanks again.
