### ISSUE TITLE
Add possibility for Sidenav to collapse all other elements

### ISSUE THREAD

**Issue by dedalusmax** [vmware/clarity#990]
[ ] bug
[x] feature request
[ ] enhancement

I can see from the roadmap that you're currently implementing Sidenav support in NG4. Since we're currently using it, but had to adapt it for Angular, it would be nice to include the feature that when an element is clicked (expanded), all other elements are collapsed. That is what we are using right now, but had to manually do it.

Thanks in advance,
Ratko.

**Comment by mathisscott** [comment]
@dedalusmax 
This is what we call "accordion" functionality. I don't know if it is included with the scope of work for the left nav or not but I will link the issues so we can track it. Thanks for the suggestion.

**Comment by mathisscott** [comment]
Linking to #472

**Comment by reddolan** [comment]
@dedalusmax We have merged your request into Vertical Navigation #1001. Please read the documentation and subscribe for updates. Comments and questions can be posted there.

Thank you
