### ISSUE TITLE
Incorrect alignment of radio buttons w/o text inside table

### ISSUE THREAD

**Issue by brinton-chand** [vmware/clarity#994]
**Select one ...**  (check one with "x")
```
[x] bug
[ ] feature request
[ ] enhancement
```

### Expected behavior
Radio buttons without text line up correctly in a table with centre alignment.

### Actual behavior
Radio buttons without text appear slightly offset of centre alignment.

### Reproduction of behavior
https://plnkr.co/edit/PkAqKe?p=preview

### Environment details

* **Angular version:** 4.1.2

* **Clarity version:** 0.9.6

* **OS and version:** Windows 10 Pro

* **Browser:** Chrome 58.0.3029.110 (64-bit) | Firefox 53.0.3 (32-bit)

**Comment by Shijir** [comment]
Hi @brinton-chand, I don't see this as a bug because cell content has `text-align: center` by default.  If cell content needs to be aligned, you could take advantage of left-aligned table cells. Example: https://plnkr.co/edit/TZjE6nr7SXE6jpriJKuv?p=preview

**Comment by mathisscott** [comment]
@brinton-chand : We haven't heard back in a while. I'm going to close this issue under the assumption that @Shijir 's workaround was satisfactory. Thanks!
