### ISSUE TITLE
Add possibility to display column headers vertically in DataGrid

### ISSUE THREAD

**Issue by dedalusmax** [vmware/clarity#995]
[ ] bug
[x] feature request
[ ] enhancement

We have a request from one of our customer to provide the data grid which has column headers displayed vertically, like this one: 

![capture](https://cloud.githubusercontent.com/assets/8254665/26618360/752f8090-45da-11e7-8b7b-849fc84e1121.PNG)

Note that some of the headers are still horizontally placed. Is it possible to add it into the data grid?

**Comment by mathisscott** [comment]
Hi @dedalusmax 
Thanks for submitting this! We took a look at the use cases and it seems like the most important use case here is limiting the horizontal space used in titles. There are multiple ways to do this currently (shortening title, wrapping, ellipses, etc). We don’t believe that showing it vertically is the way to go considering how much it impacts readability and the consumption of information. Based on that, we’ve decided not to implement this in Clarity.

Thanks again for submitting the request, we’re always happy to help and look at feedback!
