### ISSUE TITLE
Add a test for change detection in datagrids that can be conditionally shown with hideable columns

### ISSUE THREAD

**Issue by hippee-lee** [vmware/clarity#999]
We need a test to make sure the change detection in DatagridFooter does not throw an `Expression has changed after it was checked` error when hiding and showing a datagrid with hideable columns.

The footer should have a hideable column toggle component and it should not throw any errors when going from `*ngIf=true` to `*ngIf=false` and back again. 

Related to #993, #950

**Comment by mathisscott** [comment]
@youdz is this part of the EHC datagrid errors we've been seeing?

**Comment by youdz** [comment]
I think it's valid, we should add a general unit test for chocolate errors on datagrids that have an `*ngIf` on it. The test should be on a datagrid that uses most features all at once.

**Comment by coryrylan** [comment]
Closing as stale. Internals have been refactored and have not seen issues recently. If you feel this is still an issue in latest please reopen.
